### ISSUE TITLE
java.io.IOException: Underlying input stream returned zero bytes

### ISSUE THREAD

**Issue by MaximilianClemens** [keycloak/keycloak#10247]
### Describe the bug

Hello,

Yesterday I updated our Keycloak Instance from Version 15.0.2 to the 17.0.0.
Today we sporadically receiving an error when logging in.

Interestingly, it works on the second or third try and then fails again.

Regards
Maximilian

### Version

17.0.0

### Expected behavior

* SP redirect to IDP
* Kerberos auth
* IDP redirect to SP

### Actual behavior

```
Feb 16 08:30:22 <servername> kc.sh[165563]: Debug is  true storeKey true useTicketCache false useKeyTab true doNotPrompt true ticketCache is null isInitiator false KeyTab is <path to keytab> refreshKrb5Config is false principal is HTTPS/<cname>@<domain> tryFirstPass is false useFirstPass is false storePass is false clearPass is false
Feb 16 08:30:22 <servername> kc.sh[165563]: principal is HTTPS/<cname>@<domain>
Feb 16 08:30:22 <servername> kc.sh[165563]: Will use keytab
Feb 16 08:30:22 <servername> kc.sh[165563]: Commit Succeeded
Feb 16 08:30:22 <servername> kc.sh[165563]:                 [Krb5LoginModule]: Entering logout
Feb 16 08:30:22 <servername> kc.sh[165563]:                 [Krb5LoginModule]: logged out Subject
Feb 16 08:30:45 <servername> kc.sh[165563]: 2022-02-16 08:30:45,291 WARN  [org.keycloak.services] (executor-thread-26) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: java.io.IOException: Underlying input stream returned zero bytes
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:61)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at com.sun.proxy.$Proxy41.getDecodedFormParameters(Unknown Source)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:104)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1002)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:321)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:292)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:276)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:349)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:362)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:340)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:66)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/java.lang.Thread.run(Thread.java:829)
Feb 16 08:30:45 <servername> kc.sh[165563]: Caused by: java.io.IOException: Underlying input stream returned zero bytes
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/java.io.BufferedReader.read1(BufferedReader.java:212)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider.parseForm(FormUrlEncodedProvider.java:88)
Feb 16 08:30:45 <servername> kc.sh[165563]:         at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:57)
Feb 16 08:30:45 <servername> kc.sh[165563]:         ... 62 more
Feb 16 08:30:45 <servername> kc.sh[165563]: 2022-02-16 08:30:45,298 WARN  [org.keycloak.events] (executor-thread-26) type=LOGIN_ERROR, realmId=master, clientId=https://<client host>/saml-metadata/f01135ab-b043-4bd9-a0cc-de097b87078d, userId=null, ipAddress=<internal ip>, error=invalid_user_credentials, auth_method=saml, redirect_uri=https://<client host>/tas/public/login/verify, code_id=55251f1c-8e44-4a51-ad0c-cc7c78a53f27, authSessionParentId=55251f1c-8e44-4a51-ad0c-cc7c78a53f27, authSessionTabId=iww6o0-VQhI
```

### Anything else?

keycloak.conf

```
https-certificate-file=${kc.home.dir}conf/server.crt.pem
https-certificate-key-file=${kc.home.dir}conf/server.key.pem
hostname=<cname>
https-port=443
http-relative-path=/auth
```

**Comment by MaximilianClemens** [comment]
Issue was related to the kerberos authentication, solved in Firefox with the following settings in about:config:
```
network.negotiate-auth.allow-non-fqdn = true    
network.negotiate-auth.trusted-uris = <internal dns suffix>
network.negotiate-auth.allow-proxies = true

```
