### ISSUE TITLE
Keycloak unable to start using legacy JPA storage with CockroachDB

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10430]
### Describe the bug

When using CockroachDB with the legacy JPA storage, Keycloak fails to start with the following error:

```
2022-02-16 14:00:54,681 ERROR [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] (ServerService Thread Pool -- 58) Error has occurred while updating the database: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/jpa-changelog-1.3.0.xml::1.3.0::bburke@redhat.com:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "user_required_action" (127): unimplemented: primary key dropped without subsequent addition of new primary key in same transaction
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/48026/v21.2 [Failed SQL: (0) ALTER TABLE public.USER_REQUIRED_ACTION DROP CONSTRAINT CONSTRAINT_2]
```

This happens because CockroachDB doesn't allow a primary key to be dropped without adding a new primary key in the same transaction. Liquibase commits changes to the schema one by one, so all changesets that use the `dropPrimaryKey` change are incompatible with CockroachDB.

### Version

17.0.0

### Expected behavior

Keycloak should be able to start using CockroachDB

### Actual behavior

When using CockroachDB the server fails to start

### How to Reproduce?

Run `KeycloakServer` with the legacy JPA providers using a configuration that connects to a CockroachDB. It uses the Postgres driver so the config is very similar to that of Postgres. Simply adjust the connection URL with the correct host/port and it should work.

If done right, Keycloak will attempt to process the legacy changelogs and it will fail once it finds a changeset that attempts to drop a primary key.

**Comment by ahus1** [comment]
@sguilhen, @hmlnarik - adding this to our backlog. Please update labels and description if you have additional information about how important this is, how this relates to other tickets and when there would be a good time to tackle this. Thanks.

**Comment by xgp** [comment]
Hi @sguilhen . Following the thread at Cockroach about this. I might have some resources to help out with this. I'm not sure this is an idea that would make it past review, but I wanted to run it by you to see if you think it would be worth trying. Basically, the insight is that the "legacy" store won't last too much longer, so having a "fork" of the master changelog to accommodate would be acceptable to support crdb in the meantime.

1. Create a full changelog using liquibase generateChangeLog from an updated postgres instance.
2. Run that changelog using liquibase update on a crdb instance. Make any changes to the changelog that are required.
3. Put that changelog in `model/jpa/src/main/resources/META-INF/jpa-changelog-17.0.0-crdb.xml`
4. Create a new master as `model/jpa/src/main/resources/META-INF/jpa-changelog-master-crdb.xml` that includes just the above changelog.
5. Update `QuarkusLiquibaseConnectionProvider` to return `Liquibase` using the new changelog if the `Database` is an instance of `CockroachDatabase` (https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/liquibase/QuarkusLiquibaseConnectionProvider.java#L126)
6. From here until the end of the "legacy" store, make sure that new changelogs are compatible with crdb, and get referenced in the normal master and the crdb master changelogs.

I was originally hoping there would be some facility to do this in liquibase alone, but preconditions in master changelogs don't allow skipping imports. Do you see any problem with this idea? It's a bit hack-y, but I think it might side-step all of the problems that you have found.

**Comment by xgp** [comment]
@sguilhen Here is the suggested solution https://github.com/keycloak/keycloak/compare/main...xgp:xgp/crdb-legacy?expand=1 that passes the migration step without issues.

Note: I wasn't sure how liquibase determines database types, so I forced it in order to test it.

**Comment by sguilhen** [comment]
> @sguilhen Here is the suggested solution https://github.com/keycloak/keycloak/compare/main...xgp:xgp/crdb-legacy?expand=1 that passes the migration step without issues.
> 
> Note: I wasn't sure how liquibase determines database types, so I forced it in order to test it.

I think the scope of the required changes is a big broader than this. The quarkus distribution performs a series of optimizations, such as removing Liquibase database implementations that aren't used, so that only the DB that has been configured for Keycloak is included in the jar. This explains why you weren't able to get the right DB and had to "force" the processing of the new changelog. See the [LiquibaseProcessor](https://github.com/keycloak/keycloak/blob/main/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/LiquibaseProcessor.java#L81) and the [Database](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/Database.java) classes for a bit more info.

@pedroigor can probably help us here, but I believe the addition of CockroachDB will require a new entry in the `Vendor` enum in `Database`. Then we can test the implementation by configuring CockroachDB as the Keycloak database in the quarkus distro.

**Comment by xgp** [comment]
@sguilhen Thank you for looking at this!

I was able to get rid of the forcing problem by adding a `Database.Vendor` to the enum: https://github.com/keycloak/keycloak/compare/main...xgp:xgp/crdb-legacy?expand=1#diff-51d436821cd6094bbb2be82412756f807f81640d1882b7b9d2ffe2073bc7f87bR155

**Comment by sguilhen** [comment]
@xgp that great! So you were able to start keycloak with crdb? I will take a better look at the proposed changes later this week, but I think this looks promising. It might be interesting to also change the [LiquibaseJpaUpdaterProvider](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/LiquibaseJpaUpdaterProvider.java) so we can run the testsuite using Cockroach (it currently starts Keycloak on Undertow and it uses this provider to initialize the DB).

**Comment by xgp** [comment]
> So you were able to start keycloak with crdb?

Yes and no. I can start keycloak, and it makes it through the migration with the changes in my fork. 

After that, I run into a transaction serialization problem during the initial creation of the master realm. I spoke with @timveil-cockroach, and he suggested a way to do transaction retries that I'm trying right now. I'll add to this thread once I work through that. 

I'll also look at the LiquibaseJpaUpdaterProvider so we can run the testsuite using Cockroach.

**Comment by sguilhen** [comment]
Hey @xgp - been a while since we've last touched this discussion. Were you able to make any progress on the legacy CRDB integration? If you are still stuck could you share some details on what is currently blocking you?

**Comment by xgp** [comment]
@sguilhen Thanks for following up! We had some releases and customer issues to solve, so we haven't spent a ton of time around it. Here's a summary of where we are:
1. "Fixed" the migration issue as described above.
2. We were able to work through the initial realm creation where we were getting the attached CRDB error by retrying the *full* transaction. [example-startup.log](https://github.com/keycloak/keycloak/files/8763321/example-startup.log)
3. We have been running the rest of the Keycloak tests, and working through the exceptions there. 
4. Despite the problems above, we've got a version that mostly works for many simple use cases.

For a while, we pursued the approach from cloudtrust discussed [here](https://github.com/keycloak/keycloak/discussions/8885#discussioncomment-1689180), but we were not ultimately able to make their approach work (use of a savepoint, and retrying the whole transaction from the request filter). 

Basically, our problem is that retrying the whole transaction **DOES NOT WORK** in many cases, as we have found that some of the Keycloak transaction rollbacks in the code do not work properly. This means that retrying the whole transaction as a vehicle to retry the CRDB database transaction (i.e. their recommendation) isn't viable. 

Our next approach, which we are looking into now, is to isolate the hibernate/database "transaction" (the portion of the global Keycloak transaction that runs the CRDB database trasaction) to see if we can run just that as a retry loop. Externally (to the transaction manager) it would have the same superficial functionality as a single "transaction", but would do a loop under the covers. However, we are having a quite difficult time understanding where these get added to the transaction manager and how it would be possible to wrap them. Part of this is our lack of familiarity with this part of the Keycloak code, and the other part is the difficulty using a debugger to find it because of the indirection around dependency injection. Any help you can provide as to how this works would be helpful!.

Hope that helps, and happy to discuss more if you have some ideas/feedback for us.

**Comment by sguilhen** [comment]
Hi @xgp , thanks for the info and for the work you've put into this. If I'm not mistaken, the actual JPA transaction is already wrapped as a `KeycloakTransaction` and is enlisted here:

https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java#L104

Perhaps you can work with this `JpaKeycloakTransaction` that wraps the actual JPA transaction to add the retry logic?

**Comment by pedroigor** [comment]
@xgp @sguilhen Does it make sense to disable JTA? We have some databases that only work when JTA is disabled but this is usually because they are lacking JTA support.

Not sure if it applies here but I think is worth trying it out. To disable JTA, you should set the `transaction-xa-enabled` option to `false` as well as make sure the driver is also not XA.

**Comment by xgp** [comment]
@sguilhen That was our instinct as well. We tried `JpaKeycloakTransaction` (started by just putting some logging in there), but it never got called. Is that specific to the Wildfly version? 

@pedroigor We have been setting `transaction-xa-enabled` to false, but noticed it didn't seem to change anything. Your suggestion of "make sure the driver is also not XA" makes sense but I don't know how to do it? Is it a property you can set in the JDBC URL? Or do I have to use a different Postgres JDBC driver? We also tried setting [quarkus.datasource.jdbc.transactions](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.transactions), but that also seemed to have no effect.

**Comment by pedroigor** [comment]
The `transaction-xa-enabled` is a build option, did you run `build` command prior to start the server?

Or you can start the server using the `auto-build` option as follows:

```
kc.sh start --auto-build --transaction-xa-enabled=false <more options>
```

**Comment by xgp** [comment]
Or perhaps I'm misunderstanding the stack trace. Given the `javax.transaction.xa.XAException` error and the `io.agroal.narayana.LocalXAResource` references, my assumption is the XA is still turned on:

```
2022-05-26 14:33:25,037 WARN  [com.arjuna.ats.jta] (main) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffffc0a8010a:feb5:628f737b:0, node_name=quarkus, branch_uid=0:ffffc0a8010a:feb5:628f737b:3, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@7263b0c4) failed with exception XAException.XA_RBROLLBACK: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=0dad72d5 key=/Tenant/658/Table/392/1/"mcpw9"/0 pri=0.00067754 epo=0 ts=1653568401.925213382,2 min=1653568380.082823650,0 seq=2} lock=true stat=PENDING rts=1653568380.082823650,0 wto=false gul=1653568380.582823650,0
  Hint: See: https://www.cockroachlabs.com/docs/v21.2/transaction-retry-error-reference.html#retry_serializable
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
	at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:72)
	at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:702)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2400)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1502)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:105)
	at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:102)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:145)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:254)
	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:157)
	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.initializeKeycloakSessionFactory(QuarkusKeycloakApplication.java:68)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:49)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:86)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:34)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:88)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=0dad72d5 key=/Tenant/658/Table/392/1/"mcpw9"/0 pri=0.00067754 epo=0 ts=1653568401.925213382,2 min=1653568380.082823650,0 seq=2} lock=true stat=PENDING rts=1653568380.082823650,0 wto=false gul=1653568380.582823650,0
  Hint: See: https://www.cockroachlabs.com/docs/v21.2/transaction-retry-error-reference.html#retry_serializable
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:315)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:855)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:877)
	at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:355)
	at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:69)
	... 46 more
```

**Comment by pedroigor** [comment]
Sorry for asking this, but do you have some pointers on how I can run CockroachDB here to reproduce this problem?

**Comment by xgp** [comment]
Also, correcting my statement from earlier, the `JpaKeycloakTransaction` is getting used, but *AFTER* the exception above, and throws an `IllegalStateException`:

```
2022-05-26 14:33:25,045 INFO  [org.keycloak.connections.jpa.JpaKeycloakTransaction] (main) Committing transaction
2022-05-26 14:33:25,047 WARN  [org.keycloak.connections.jpa.JpaKeycloakTransaction] (main) Throwable committing transaction: java.lang.IllegalStateException: Transaction not successfully started
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:95)
	at org.keycloak.connections.jpa.JpaKeycloakTransaction.commit(JpaKeycloakTransaction.java:55)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:145)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:254)
	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:157)
	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.initializeKeycloakSessionFactory(QuarkusKeycloakApplication.java:68)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:49)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
...
```
This is what is leading me to believe that the `JpaKeycloakTransaction` isn't actually the thing running/wrapping hibernate and the SQL transaction.

**Comment by xgp** [comment]
> Sorry for asking this, but do you have some pointers on how I can run CockroachDB here to reproduce this problem?

I do have a doc we've been using internally, but I will need to clean it up (remove creds and such) to send it. I'll have more time to do it tonight.

**Comment by pedroigor** [comment]
@xgp Quarkus always enable a JTA transaction manager so when you set that option you are just telling it to use a regular JDBC datasource (non-XA) and transactions. We don't actually disable XA fully but allow using a regular JDBC datasource. Perhaps the option name is a bit misleading.

Perhaps, you can try to completely disable the JTA transaction manager by changing this line https://github.com/keycloak/keycloak/blob/19a17e79bad03c7d46c28fbcade7863a35713a0e/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java#L32. Instead of `enabled` you return `disabled`.

If you do that, it is expected that when you set `transaction-xa-enabled=false` you won't have an instance of `io.agroal.narayana.NarayanaTransactionIntegration` with XA fully disabled.

**Comment by xgp** [comment]
@pedroigor This seems to be working. I'll do some more tests tomorrow.

**Comment by xgp** [comment]
@pedroigor Is there an equivalent way to fully disable XA for the Wildfly/legacy version?

**Comment by pedroigor** [comment]
W.r.t. Wildfly, you can do this:

```
<spi name="jta-lookup">
    <provider name="jboss" enabled="false"/>
</spi>
```

W.r.t. to the changes to disabled XA, we can see if we can add/change that option to completely disable XA.

**Comment by xgp** [comment]
Here's a cleaned up branch with just the migrations fix and the disable XA approach: https://github.com/xgp/keycloak/tree/xgp/crdb-noxa

Diff: https://github.com/keycloak/keycloak/compare/main...xgp:xgp/crdb-noxa

Haven't run it through unit/integration test yet, but makes it through migrations, realm creation, and I ran through a couple of common use cases. Maddeningly simple, if this is actually the fix. We've also got a better setup with a local crdb with more debugging turned on that I'll try tomorrow. I'm curious to see how it's getting over the retry need now that it controls the transaction.

One thing I still don't understand is that when [this line](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultKeycloakTransactionManager.java#L102) gets called, the transaction manager is an instance of `io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager`. Somewhere in there, it's running the hibernate and jdbc code, but I can't find (or don't understand) how that actually gets added or where that code is. Despite our above breakthrough, I'm still worried that we'll encounter a need to retry. Where and how I could wrap that code in a retry loop is still a mystery to me. I probably need to learn more about quarkus and the dependency injection system that it uses, but I don't right now..

**Comment by pedroigor** [comment]
That bean is dynamically created when augmenting the application. See CDIDelegatingTransactionManager.

I also do not know more of the details but you can try to reach out Quarkus team.

**Comment by pedroigor** [comment]
@xgp Nice, thanks for looking at that.

To support disabling JTA completely, as we did here, is trivial but it should involve some discussions to review the `transaction-xa-enabled` option. For instance, the description says:

```
Manually override the transaction type. Transaction type XA and the appropriate driver is used by default.
```

This is also a bit confusing from Quarkus documentation, I think. When you set `false` to `transaction-xa-enabled` we are actually setting `[quarkus.datasource.jdbc.transactions](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.transactions)` to `enabled`. And that means enabling JDBC transactions by using a non-XA datasource. It does really disables JTA and the Nayrana transaction manager is still being used.

My take on this is that we rename the `transaction-xa-enabled` to `db-xa-enabled=true|false` because we are actually enabling the usage of non-XA data sources (but still using JTA).

And have a `transaction-jta-enabled=false|true` to actually remove JTA from the runtime.

**Comment by sguilhen** [comment]
Also, +1 to @pedroigor 's take on the configuration flags.

**Comment by xgp** [comment]
@sguilhen Yes. The integration testsuite.
@pedroigor I'll take a stab at making the conf flag changes you suggested.

**Comment by xgp** [comment]
For those still looking for a solution here, our patched Keycloak makes the above changes. We maintain a docker image that is up to date with Keycloak releases that contains our patch. 

https://quay.io/repository/phasetwo/keycloak-crdb

It must be run with a few configuration options set:
```
KC_TRANSACTION_XA_ENABLED=false                                                                                                                                                                                 
KC_TRANSACTION_JTA_ENABLED=false                                                                                                                                                                                
KC_DB=cockroach
```

**Comment by xgp** [comment]
Hi @pedroigor It looks like the `KC_TRANSACTION_JTA_ENABLED` flag and the associated logic got removed in this commit: https://github.com/keycloak/keycloak/commit/c17fcd49c84e835d0c7aea45704327a3e8fb4239

Do you know why? Is it possible to restore it?

**Comment by xgp** [comment]
Hi All! 

Given https://www.keycloak.org/2023/10/map-store-removal.html, would the team be willing to reconsider CRDB support in the "legacy" store? We have been maintaining a fork of Keycloak for our own and customers' use since `v19` which supports CRDB. The changes we made are described above in https://github.com/keycloak/keycloak/issues/10430#issuecomment-1076849162 

Here is a diff for `v22.0.4`:
https://github.com/keycloak/keycloak/compare/22.0.4...p2-inc:keycloak:22.0.4_crdb

And if you want to try it, our images are here:
https://quay.io/repository/phasetwo/keycloak-crdb

@sguilhen @ahus1 @pedroigor

**Comment by shawkins** [comment]
Closing as out-of-date. An issue on the general support of cockroachdb can be opened if desired.
