### ISSUE TITLE
REST API List Client Permission Issue

### ISSUE THREAD

**Issue by d-vo** [keycloak/keycloak#10583]
### Describe the bug

When using an existing Realm and listing all the clients using REST API connected to a custom client (`backend-client`), I encounter a permission error when using the Service Account Role: 

```
2022-03-03 21:18:26,412 DEBUG [org.keycloak.events] (executor-thread-42) type=CLIENT_LOGIN, realmId=Test, clientId=backend-client, userId=35ace610-8d85-4ffd-8bc6-f374aac9bd0e, ipAddress=192.168.178.20, token_id=472b413d-3ca0-43d6-89d1-81ac7f3ea0d1, grant_type=client_credentials, scope='profile email', client_auth_method=client-secret, username=service-account-backend-client, authSessionParentId=12833a94-336f-4782-89c0-aa535b517c5d, authSessionTabId=XT6dT54t-5E
2022-03-03 21:18:26,418 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-42) new JtaTransactionWrapper
2022-03-03 21:18:26,418 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-42) was existing? false
2022-03-03 21:18:26,419 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (executor-thread-42) Recalculated absoluteURI to http://192.168.178.20/admin/realms/Test/clients
2022-03-03 21:18:26,420 DEBUG [org.keycloak.services.resources.admin.AdminRoot] (executor-thread-42) authenticated admin access for: service-account-backend-client
2022-03-03 21:18:26,420 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-42) Error response 403: org.keycloak.services.ForbiddenException
	at org.keycloak.services.resources.admin.permissions.ClientPermissions.requireList(ClientPermissions.java:238)
	at org.keycloak.services.resources.admin.ClientsResource.getClients(ClientsResource.java:110)
	at jdk.internal.reflect.GeneratedMethodAccessor687.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:362)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:340)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I checked the corresponding code in: 
`org.keycloak.services.resources.admin.permissions.ClientPermissions.requireList(ClientPermissions.java:238)`
I checked that all roles from `realm-management` are actually attached to the Service Account User. 

When setting up a vanilla realm, it just works if I repeat exactly the same steps to set up the client and the corresponding Service Account User. Any clever idea how to debug this further or what could be missing or screwed up in my existing realm? 

Best regards, 
Dominik

### Version

17.0.0

**Comment by d-vo** [comment]
I found the issue: I accidentally deleted the `client roles` mapper in `Client Scopes` -> `roles` -> `Mappers`. 

Closed the issue.
