### ISSUE TITLE
The TCP/IP connection to the host mssql/keycloak, port 1433 has failed

### ISSUE THREAD

**Issue by ivangfr** [keycloak/keycloak#10614]
### Describe the bug

Hi, I am trying to make **JDBC_PING** working in a **Keycloak 17** cluster.

For **MySQL** and **MariaDB**, it's working perfectly. For **Postgres**, I am facing the following error also described in this issue #10235 .

Finally, for **Microsoft SQL Server** (the reason why I opened this issue), it looks like **Keycloak** cannot communicate with **MSSQL** on port `1433`.

### Version

17.0.0

### Expected behavior

A cluster of **Keycloak 17** should start using **JDBC_PING** with **Microsoft SQL Server** as both services are in the same network and **MSSQL** port `1433` is opened. 

### Actual behavior

Even having both **Keycloak** and **MSSQL** running in the same network and **MSSQL** port `1433` opened, **Keycloak** cannot communicate with **MSSQL**, as we can see in the exception below
```
ERROR [org.jgroups.protocols.JDBC_PING] (keycloak-cache-init) JGRP000115: Could not open connection to database: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host mssql/keycloak, port 1433 has failed. Error: "mssql/keycloak. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2431)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:656)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2440)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2103)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1950)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1162)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:735)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.jgroups.protocols.JDBC_PING.getConnection(JDBC_PING.java:290)
	at org.jgroups.protocols.JDBC_PING.attemptSchemaInitialization(JDBC_PING.java:250)
	at org.jgroups.protocols.JDBC_PING.init(JDBC_PING.java:111)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:854)
	at org.jgroups.stack.ProtocolStack.init(ProtocolStack.java:842)
	at org.jgroups.JChannel.<init>(JChannel.java:164)
	at org.infinispan.remoting.transport.jgroups.EmbeddedJGroupsChannelConfigurator.createChannel(EmbeddedJGroupsChannelConfigurator.java:128)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:694)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:666)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:478)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:463)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:41)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:70)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:354)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:752)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:720)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:401)
	at org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

- Create Docker network
  ```
  docker network create keycloak-net
  ```

- Run MSSQL
  ```
  docker run --rm --name mssql -p 1433:1433 \
    -e ACCEPT_EULA=Y \
    -e SA_PASSWORD=my_Password \
    --network keycloak-net \
    mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
  ```

- Create `keycloak` database
  ```
  docker exec -i mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P my_Password -Q 'CREATE DATABASE keycloak'
  ```

- Run `keycloak-clustered-1` Docker container
  ```
  docker run --rm --name keycloak-clustered-1 -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    -e KC_DB=mssql \
    -e KC_DB_URL_HOST=mssql \
    -e KC_DB_URL_DATABASE=keycloak \
    -e KC_DB_SCHEMA=myschema \
    -e KC_DB_USERNAME=SA \
    -e KC_DB_PASSWORD=my_Password \
    -e KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG \
    --network keycloak-net \
    ivanfranchin/keycloak-clustered:17.0.0 start-dev
  ```

**Comment by LukasVojacek** [comment]
Hello
Can you try change in the file "cache-ispn-jdbc-ping.xml" jgroup:

  <jgroups>
    <stack name="jdbc-ping-tcp" extends="tcp">
      <TCP external_addr="X.X.X.X"/>
      <JDBC_PING connection_driver="com.microsoft.sqlserver.jdbc.SQLServerDriver"
                 connection_username="${env.KC_DB_USERNAME}" connection_password="${env.KC_DB_PASSWORD}"
                 connection_url="jdbc:sqlserver://${env.KC_DB_URL_HOST}:1433;databaseName=${env.KC_DB_URL_DATABASE}"
                 info_writer_sleep_time="500"
                 remove_all_data_on_view_change="true"
                 stack.combine="REPLACE"
                 stack.position="MPING" />
    </stack>
  </jgroups>


P.S. TCP external_addr can help with connection between instances on different VMs

**Comment by ivangfr** [comment]
Hi @LukasVojacek Thanks for the suggestion!

Unfortunately, it didn't work. I've tried to inform as `external_addr` the IP of the `keycloak-clustered` Docker container inside the network `keycloak-net` and also the IP of the HOST machine. Same problem.

**Comment by vmuzikar** [comment]
Thanks for the report! Can you please confirm if the issue still persists with the latest Keycloak version for you? If so, feel free to reopen.

**Comment by DGuhr** [comment]
If the problem still persists, you might want to look into https://github.com/keycloak/keycloak/discussions/10177
