### ISSUE TITLE
Keycloak 17 in Docker: No suitable driver found when passing db info as environment variables

### ISSUE THREAD

**Issue by teuber789** [keycloak/keycloak#10636]
### Describe the bug

I have a very basic Docker file, which I'm using to stand up Keycloak with:

```Dockerfile
FROM quay.io/keycloak/keycloak:17.0.0
```

I then build it like so:

```console
$ cd iam/
$ docker network create ori-iam-network
$ docker run -d \
    --name ori-iam-db \
    --net ori-iam-network \
    -p 3306:3306 \
    -e MYSQL_DATABASE=keycloak \
    -e MYSQL_USER=keycloak \
    -e MYSQL_PASSWORD=password \
    -e MYSQL_ROOT_PASSWORD=root_password \
    mysql:8
$ docker build -t ori-iam:latest .
$ docker run \
    --name ori-iam \
    --net ori-iam-network \
    -p 8080:8080 \
    -e KEYCLOAK_ADMIN="admin" \
    -e KEYCLOAK_ADMIN_PASSWORD="asdfasdf" \
    -e KC_DB_URL="jdbc:mysql://ori-iam-db:3306/keycloak" \
    -e KC_DB_USERNAME="keycloak" \
    -e KC_DB_PASSWORD="password" \
    ori-iam:latest start-dev
```

However, when I run this, I get the following error message:

```console
Updating the configuration and installing your custom providers, if any. Please wait.
2022-03-07 19:42:17,700 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 5199ms
2022-03-07 19:42:20,293 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
2022-03-07 19:42:20,556 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:mysql://ori-iam-db:3306/keycloak
2022-03-07 19:42:20,557 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:mysql://ori-iam-db:3306/keycloak
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-03-07 19:42:20,838 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-03-07 19:42:20,846 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-03-07 19:42:20,867 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-03-07 19:42:21,078 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
2022-03-07 19:42:21,088 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:mysql://ori-iam-db:3306/keycloak
2022-03-07 19:42:21,563 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2022-03-07 19:42:21,563 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-03-07 19:42:21,564 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No suitable driver found for jdbc:mysql://ori-iam-db:3306/keycloak
2022-03-07 19:42:21,564 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

However, it works just fine if I pass the db information to start-dev:

```console
docker run \
    --name ori-iam \
    --net ori-iam-network \
    -p 8080:8080 \
    -e KEYCLOAK_ADMIN="admin" \
    -e KEYCLOAK_ADMIN_PASSWORD="asdfasdf" \
    ori-iam:latest \
    start-dev \
    --db="mysql" \
    --db-url="jdbc:mysql://ori-iam-db:3306/keycloak" \
    --db-username="keycloak" \
    --db-password="password"
Updating the configuration and installing your custom providers, if any. Please wait.
2022-03-07 19:58:34,210 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 5302ms
2022-03-07 19:58:36,976 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
2022-03-07 19:58:37,503 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-03-07 19:58:37,517 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-03-07 19:58:37,525 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-03-07 19:58:37,751 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
2022-03-07 19:58:38,447 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_454940, Site name: null
2022-03-07 19:58:38,967 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
2022-03-07 19:58:39,083 INFO  [io.quarkus] (main) Keycloak 17.0.0 on JVM (powered by Quarkus 2.7.0.Final) started in 4.673s. Listening on: http://0.0.0.0:8080
2022-03-07 19:58:39,083 INFO  [io.quarkus] (main) Profile dev activated. 
2022-03-07 19:58:39,084 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, infinispan-client, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-03-07 19:58:39,085 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

The only apparent difference is that the database parameters are passed via Docker environment variables at runtime in the first method, and they are passed as CLI options to `kc.sh start-dev` in the second.

### Version

17.0.0

### Expected behavior

I would expect that the container would connect to the database without any issues, regardless of whether the db information is passed as Docker environment variables or as parameters to start-dev.

### Actual behavior

See description

### How to Reproduce?

See description

**Comment by Wolfsrudel** [comment]
You'll have to define `KC_DB` with your relevant database driver/ type. See the docs section "Relevant Options": https://www.keycloak.org/server/containers

**Comment by teuber789** [comment]
It seems like a better approach is to inject the environment variables at image build time, and then just run the image. I'll try that instead.
