### ISSUE TITLE
Add kotlinModule to Jackson Resteasy provider

### ISSUE THREAD

**Issue by Szer** [keycloak/keycloak#10698]
### Description

When I'm reusing existing libraries written in Kotlin and there are `data classes` used as a model, I can't use it because built-in Jackson doesn't have `kotlinModule` enabled therefore REST inputs or responses can't serialized to JSON easily.

Here is end of a stacktrace:
```
2022-03-10 15:56:55	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:193)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
2022-03-10 15:56:55	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
2022-03-10 15:56:55	at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 2]
2022-03-10 15:56:55,790 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.thriveglobal.identity.keycloak.entity.CompanyRepresentation` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

I could add annotations to the code (`JsonProperty`) or make `data class` just an ordinary `class` with all fields being mutable.
Both options are not pleasant.

The problem is direr when you are not in control of 3rd party code and can't add annotations or make `data class` usual `class`.

Adding [Kotlin Module](https://github.com/FasterXML/jackson-module-kotlin) should be safe to non-Kotlin users and will add the ability to use Kotlin code/models in REST providers.

### Motivation

I want to use libraries written in Kotlin as models for REST providers (or use Kotlin in general)

**Comment by santosmken** [comment]
Hi @Szer do you have any work-around to make this work? I have the same issue as I'm using Kotlin to develop SPI extension and I want to validate `data classes` like with Konform/KValidator or similar kotlin validation library.

**Comment by Szer** [comment]
> Hi @Szer do you have any work-around to make this work? I have the same issue as I'm using Kotlin to develop SPI extension and I want to validate `data classes` like with Konform/KValidator or similar kotlin validation library.

No, just suffering with DTO models being extremely ugly :/

**Comment by santosmken** [comment]
> > Hi @Szer do you have any work-around to make this work? I have the same issue as I'm using Kotlin to develop SPI extension and I want to validate `data classes` like with Konform/KValidator or similar kotlin validation library.
> 
> No, just suffering with DTO models being extremely ugly :/

How do you handle validations with your DTO models? On my end, I'm validating it with if statements etc in my resource controller. I also make the data class properties `nullable` so I can handle it in the resource controller.

**Comment by Szer** [comment]
> How do you handle validations with your DTO models? On my end, I'm validating it with if statements etc in my resource controller. I also make the data class properties `nullable` so I can handle it in the resource controller.

Constructing a normal domain model which does a lot of ifs.

**Comment by shawkins** [comment]
Marking as priority low given the workaround. It seems feasible that someone could submit a pr to do this automatically by finding kotlin in the classpath.
