### ISSUE TITLE
Update the server to use RESTEasy Reactive

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#10713]
### Description

Accordingly, to @geoand, applications using `quarkus-resteasy-reactive` should still benefit from a better startup time, runtime performance, and memory footprint, even though not using reactive style/semantics. Most importantly, applications using RESTEasy Classic should be able to move to `quarkus-resteasy-reactive` without any changes to code if they are relying on JAX-RS API.

We should evaluate how much it would take to change the server to use `quarkus-resteasy-reactive`.

### Motivation

Benefit from the improvements brought by `quarkus-resteasy-reactive` and keep the server aligned with Quarkus goals.

**Comment by geoand** [comment]
When the team does decide to start looking at this, let me and I can help

**Comment by geoand** [comment]
@pedroigor there are various ways we can make your extension ignore the Application class.
I'll come back tomorrow as I'm on my phone now

**Comment by geoand** [comment]
The easiest way to exclude an `Application` class is to generate a `io.quarkus.arc.deployment.BuildTimeConditionBuildItem` in your extension.

**Comment by pedroigor** [comment]
Looks like using a `BuildTimeConditionBuildItem` helped to move forward but now I'm getting the following error:

```
Caused by: java.lang.RuntimeException: Could not create converter for [Ljava.lang.String; for method javax.ws.rs.core.Response grantPermission(java.lang.String resourceId, java.lang.String action, java.lang.String[] permissionId, java.lang.String requester) on class org.keycloak.services.resources.account.AccountFormService of type FORM
[ERROR]         at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:320)
[ERROR]         at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:85)
[ERROR]         at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.extractParameterInfo(EndpointIndexer.java:1168)
[ERROR]         at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:496)
[ERROR]         ... 14 more
[ERROR] Caused by: java.lang.RuntimeException: Failed to find converter for [Ljava.lang.String;
[ERROR]         at org.jboss.resteasy.reactive.server.processor.generation.converters.GeneratedConverterIndexerExtension.extractConverterImpl(GeneratedConverterIndexerExtension.java:104)
[ERROR]         at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.extractConverter(ServerEndpointIndexer.java:476)
[ERROR]         at org.jboss.resteasy.reactive.server.processor.ServerEndpointIndexer.handleOtherParam(ServerEndpointIndexer.java:316)
[ERROR]         ... 17 more
```

The issue above points to https://github.com/keycloak/keycloak/blob/99c06d11023689875b48ef56442c90bdb744c869/services/src/main/java/org/keycloak/services/resources/account/AccountFormService.java#L752.

I also noticed that because of indexing, some dependencies (injection points) can not be resolved at build time as before. These dependencies are some instances used during the request lifecycle for which we were using a `ContextInjector`. We also have some classes injecting Resteasy `HttpRequest` and `HttpResponse` instances. I fixed those.

**Comment by geoand** [comment]
That looks like a bug on our side where arrays are not supported. I'll have a look soon.

**Comment by danielFesenmeyer** [comment]
I have a question regarding the `@Context` annotation. We currently use it in custom resource implementation, for injecting JAX-RS `Request` or `HttpHeaders` via method parameters.

For example:

```
@Path("customResource")
public CustomDto customGet(@Context Request request, @Context HttpHeaders httpHeaders) {
    // do stuff with request and httpHeaders
    // ...
}
```

Will this still be supported in the future?

**Comment by geoand** [comment]
That works in RESTEasy Reactive

**Comment by vmuzikar** [comment]
@danielFesenmeyer As part of the improvements related to switch to RestEasy Reactive, we're also cleaning up our implementation at Keycloak side and removing support for injecting `Request` and `HttpHeaders` objects via CDI. This simplifies the code and enhances the performance thanks to avoiding the creation of proxies. The objects can be retrieved directly from `KeycloakSession`.

CC @pedroigor

**Comment by pedroigor** [comment]
@vmuzikar @danielFesenmeyer It should be lot simpler now as you already have access to the `KeycloakSession`. See https://github.com/keycloak/keycloak-documentation/pull/1721/files#diff-274488d8bdebf79497daf95b0b287e9e720c816f2d52e2cda9a0255b03639936.

The changes above are still a WIP and are subject to change. For instance, you should get those instances like this https://github.com/keycloak/keycloak/pull/15659.

**Comment by danielFesenmeyer** [comment]
@pedroigor Thanks for the explanation :)
