### ISSUE TITLE
AuthenticationFlowCallbackProviderTest.errorWithCustomProvider failing with various DBs

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10720]
### Describe the bug

This was spotted during the latest keycloak server pipeline runs. When running the `db_tests` the `AuthenticationFlowCallbackProviderTest.errorWithCustomProvider` fails in non-deterministic way for some DBs. Each run sees the test failing with different DBs.

Here's the error message/stacktrace:

```
org.openqa.selenium.NoSuchElementException: 
Unable to locate element with ID: kc-page-title
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'paas.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.25.1.el7.x86_64', java.version: '1.8.0_311'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementById(HtmlUnitDriver.java:1204)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver$4.call(HtmlUnitDriver.java:1970)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver$4.call(HtmlUnitDriver.java:1)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1606)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:1966)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:754)
	at org.jboss.arquillian.graphene.enricher.WebElementUtils.dropProxyAndFindElement(WebElementUtils.java:168)
	at org.jboss.arquillian.graphene.enricher.WebElementUtils.findElement(WebElementUtils.java:70)
	at org.jboss.arquillian.graphene.enricher.SearchContextInterceptor.intercept(SearchContextInterceptor.java:46)
	at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
	at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:47)
	at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:43)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
	at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.until(WebDriverWaitImpl.java:96)
	at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor.intercept(StaleElementInterceptor.java:43)
	at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.intercept(GrapheneContextualHandler.java:263)
	at org.jboss.arquillian.drone.webdriver.htmlunit.DroneHtmlUnitDriver$$EnhancerByGraphene$$924a1d86.findElement(<generated>)
	at org.keycloak.testsuite.pages.PageUtils.getPageTitle(PageUtils.java:9)
	at org.keycloak.testsuite.pages.ErrorPage.isCurrent(ErrorPage.java:55)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:49)
	at sun.reflect.GeneratedMethodAccessor838.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.intercept(GrapheneContextualHandler.java:263)
	at org.keycloak.testsuite.pages.ErrorPage$$EnhancerByGraphene$$3c6d7fcb.assertCurrent(<generated>)
	at org.keycloak.testsuite.forms.AuthenticationFlowCallbackProviderTest.errorWithCustomProvider(AuthenticationFlowCallbackProviderTest.java:81)
```

In build # 1310 it failed for MSSQL 2019 and Mariab DB. In build # 1311 it failed for OracleRAC, Maria DB and MySQL.

### Version

17.0.0

### Expected behavior

Test should pass on all DBs.

### Actual behavior

Test fails in non-deterministic way.

**Comment by hmlnarik** [comment]
@sguilhen Is this issue still valid?

**Comment by sguilhen** [comment]
No longer valid - latests `db_tests` runs in pipeline show no more failures for this test.
