### ISSUE TITLE
Error while generating offline session 

### ISSUE THREAD

**Issue by ronycha** [keycloak/keycloak#10859]
### Describe the bug

Error while generating offline session. 
Database: MySQL

1. Generated offline session
2. Deleted offline session using delete consent API.
3. Generated offline session

During step 3, we are getting the below exception. please verify and suggest your inputs.

javax.persistence.PessimisticLockException: could not execute statement
at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:84)
at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
at javax.persistence.api@2.2.3//com.sun.proxy.$Proxy90.flush(Unknown Source)
at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.createUserSession(JpaUserSessionPersisterProvider.java:85)
at org.keycloak.keycloak-model-infinispan@15.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.createOfflineUserSession(InfinispanUserSessionProvider.java:736)
.....
.....

Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting 

### Version

15.0.2

### How to Reproduce?

Database: MySQL
1. Generated offline session
2. Deleted offline session using delete consent API.
3. Generated offline session

During step 3, we are getting the below exception. please check and suggest.

javax.persistence.PessimisticLockException: could not execute statement
at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:84)
at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
at javax.persistence.api@2.2.3//com.sun.proxy.$Proxy90.flush(Unknown Source)
at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.createUserSession(JpaUserSessionPersisterProvider.java:85)
at org.keycloak.keycloak-model-infinispan@15.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.createOfflineUserSession(InfinispanUserSessionProvider.java:736)
at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.managers.UserSessionManager.createOfflineUserSession(UserSessionManager.java:141)
at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.managers.UserSessionManager.createOrUpdateOfflineSession(UserSessionManager.java:62)
at org.keycloak.keycloak-services@15.0.2//org.keycloak.protocol.oidc.TokenManager$AccessTokenResponseBuilder.generateRefreshToken(TokenManager.java:938)
.....
....
....
....
....
Caused by: javax.persistence.PessimisticLockException: could not execute statement
        at org.hibernate@5.3.20.Final//org.hibernate.internal.ExceptionConverterImpl.wrapLockException(ExceptionConverterImpl.java:273)
        at org.hibernate@5.3.20.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:108)
        at org.hibernate@5.3.20.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate@5.3.20.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate@5.3.20.Final//org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1478)
        at org.hibernate@5.3.20.Final//org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1458)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:60)
        ... 87 more
Caused by: org.hibernate.PessimisticLockException: could not execute statement
        at org.hibernate@5.3.20.Final//org.hibernate.dialect.MySQLDialect$3.convert(MySQLDialect.java:532)
        at org.hibernate@5.3.20.Final//org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
        at org.hibernate@5.3.20.Final//org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3192)
        at org.hibernate@5.3.20.Final//org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3706)
        at org.hibernate@5.3.20.Final//org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:90)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478)
        at org.hibernate@5.3.20.Final//org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356)
        at org.hibernate@5.3.20.Final//org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
        at org.hibernate@5.3.20.Final//org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1472)
        ... 93 more
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
        at com.mysql@8.0.11//com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql@8.0.11//com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
        at com.mysql@8.0.11//com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql@8.0.11//com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
        at com.mysql@8.0.11//com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1116)
        at com.mysql@8.0.11//com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1066)
        at com.mysql@8.0.11//com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1396)
        at com.mysql@8.0.11//com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1051)
        at org.jboss.ironjacamar.jdbcadapters@1.4.27.Final//org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:537)
        at org.hibernate@5.3.20.Final//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
        ... 101 more

**Comment by kamuridesu** [comment]
up

**Comment by sschu** [comment]
Can you please update to the latest Keycloak version and check whether the issue persists?

**Comment by pedroigor** [comment]
Please, try it out using latest as we had several changes in the store during this time.
