### ISSUE TITLE
All Threads is blocked

### ISSUE THREAD

**Issue by dingxiancheng** [keycloak/keycloak#11055]
### Describe the bug

jstack contents:

"http-nio-8081-exec-9" #61 daemon prio=5 os_prio=0 tid=0x00007efc702c1000 nid=0x4c waiting for monitor entry [0x00007efc778f6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.keycloak.adapters.rotation.JWKPublicKeyLocator.getPublicKey(JWKPublicKeyLocator.java:60)
        - waiting to lock <0x00000003f1888968> (a org.keycloak.adapters.rotation.JWKPublicKeyLocator)
        at org.keycloak.adapters.rotation.AdapterTokenVerifier.getPublicKey(AdapterTokenVerifier.java:121)
        at org.keycloak.adapters.rotation.AdapterTokenVerifier.createVerifier(AdapterTokenVerifier.java:111)
        at org.keycloak.adapters.rotation.AdapterTokenVerifier.verifyToken(AdapterTokenVerifier.java:47)
        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:103)
        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:88)
        at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:67)
        at org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticationProcessingFilter.attemptAuthentication(KeycloakAuthenticationProcessingFilter.java:154)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.keycloak.adapters.springsecurity.filter.KeycloakPreAuthActionsFilter.doFilter(KeycloakPreAuthActionsFilter.java:96)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
....

app call keycloak blocked，default timeout is not setted，I add an custom filter，following：

@Component
public class ChangeTimeOutFilter implements Filter {

    @Resource
    private AdapterDeploymentContext deploymentContext;

    private volatile boolean deploymentChanged = false;

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {

        HttpFacade facade = new SimpleHttpFacade((HttpServletRequest)request, (HttpServletResponse)response);
        KeycloakDeployment deployment = deploymentContext.resolveDeployment(facade);

        if (deployment == null) {
            chain.doFilter(request, response);
            return;
        }

        //deployment是全局唯一，只需要修改一次
        if (deploymentChanged) {
            chain.doFilter(request, response);
            return;
        }

        /**
         * 设置超时时间
         */
        HttpParams params = deployment.getClient().getParams();
        params.setIntParameter(CoreConnectionPNames.SO_TIMEOUT, 10000);
        params.setIntParameter(CoreConnectionPNames.CONNECTION_TIMEOUT, 10000);
        params.setLongParameter(ClientPNames.CONN_MANAGER_TIMEOUT, 10000L);
        deploymentChanged=true;

        chain.doFilter(request, response);
    }

please check my reponse can set the timeout or not？Thank you ！！！  
Or Have other methods to resolve this questions???

### Version

12.0.4

**Comment by ahus1** [comment]
I see you're using a very old version of Keycloak. To get support for issues, please show that the problem appear in the latest version (17.0.1) or the version before (16.1.1). 

If you experience the same problem with the latest version, please paste the complete jstack thread dump, as the thread dump you provided is incomplete: it shows `waiting to lock <0x00000003f1888968>`, and without the complete thread this can't be analyzed.

**Comment by ahus1** [comment]
As this issue is missing information to further analyze it, I close this issue. Please open a new issue once that information is available, and reference this issue in the new issue's body.

**Comment by samir-kamble** [comment]
Hi I am having same issue. Can we open this Thread or open a new thread?

**Comment by ahus1** [comment]
@samir-kamble - Please open a new issue and provide the details which were missing here.

**Comment by samir-kamble** [comment]
I am trying to put a new issue but it gives below error when i pasted entire dump

![image](https://github.com/keycloak/keycloak/assets/12523579/3a4e0d19-11b1-4a75-84fc-ede8c6817d30)

**Comment by samir-kamble** [comment]
![image](https://github.com/keycloak/keycloak/assets/12523579/eda54141-bde2-4261-af3f-cf606737f511)

Error when dragged file in editor.

**Comment by ahus1** [comment]
@samir-kamble - sorry, this is not a forum on how to use GitHub's web UI. Please get help from a friend or at a different forum about that issue.
