### ISSUE TITLE
Manually test operator on OpenShift

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#11059]
We can't test on OpenShift in GHA yet, so let's at least doublecheck manually.

**Comment by andreaTP** [comment]
There is a last issue:
https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-

We should set the correct rbac for the `finalizer` stanza of the CRDs explicitly.

cc. @metacosm

**Comment by andreaTP** [comment]
Original Stacktrace:

```
2022-04-06 14:45:24,062 ERROR [org.key.ope.OperatorManagedResource] (EventHandler-keycloakcontroller) Failed to create or update resource
2022-04-06 14:45:24,080 ERROR [org.key.ope.OperatorManagedResource] (EventHandler-keycloakcontroller) ---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: "keycloak"
    app.kubernetes.io/managed-by: "keycloak-operator"
  name: "example-kc-initial-admin"
  namespace: "test-keycloak-operator"
  ownerReferences:
  - apiVersion: "app.keycloak.org/v2alpha1"
    kind: "Keycloak"
    blockOwnerDeletion: true
    controller: true
    name: "example-kc"
    uid: "074472fc-d425-4ec9-9707-2c987d859335"
stringData:
  username: "admin"
  password: "c1ca9b956a2a44b99eede26d3df2768b"
type: "kubernetes.io/basic-auth"

2022-04-06 14:45:24,080 ERROR [org.key.ope.v2a.KeycloakController] (EventHandler-keycloakcontroller) --- Error reconciling: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/test-keycloak-operator/secrets. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. secrets "example-kc-initial-admin" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:610)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:305)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:644)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:83)
	at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:61)
	at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:48)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:318)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:105)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:63)
	at org.keycloak.operator.OperatorManagedResource.lambda$createOrUpdateReconciled$0(OperatorManagedResource.java:56)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.keycloak.operator.OperatorManagedResource.createOrUpdateReconciled(OperatorManagedResource.java:50)
	at org.keycloak.operator.v2alpha1.KeycloakController.reconcile(KeycloakController.java:100)
	at org.keycloak.operator.v2alpha1.KeycloakController.reconcile(KeycloakController.java:51)
	at org.keycloak.operator.v2alpha1.KeycloakController_ClientProxy.reconcile(Unknown Source)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:101)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:76)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:75)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:143)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:109)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:74)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:50)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by vmuzikar** [comment]
@andreaTP Closing this as agreed. Operator was manually tested on OpenShift and all issues were identified.
