### ISSUE TITLE
CodeQL analysis always fails

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#11123]
### Describe the bug

As you could see in the current CI runs, the codeQL analysis for Java always fails. See e.g. https://github.com/keycloak/keycloak/runs/5834668485?check_suite_focus=true 

### Version

current

### Expected behavior

CodeQL analysis works

### Actual behavior

it fails while initializing with the error message 

```
Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql' failed with exit code 2
      at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v1/lib/toolrunner-error-catcher.js:86:19)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Object.finalizeDatabase (/home/runner/work/_actions/github/codeql-action/v1/lib/codeql.js:[56](https://github.com/keycloak/keycloak/runs/5834668485?check_suite_focus=true#step:7:56)4:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:104:13)
      at async runFinalize (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:2[60](https://github.com/keycloak/keycloak/runs/5834668485?check_suite_focus=true#step:7:60):5)
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:78:9)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:212:9)
```

### How to Reproduce?

Create a PR that triggers the analysis

### Anything else?

as @abstractj pointed out to me it fails since yesterday (2022/04/04)

**Comment by DGuhr** [comment]
see also https://github.com/github/codeql/issues/5599 - seems to be a problem with disk space?!?

**Comment by abstractj** [comment]
Thank you Dominik!

**Comment by abstractj** [comment]
I will continue the investigation, but it seems that disk space may not be the issue. Actually, the Java database has 108M. It is possible to check that by running:

```
codeql database create java-database --no-run-unnecessary-builds --language=java --command='mvn install -Dmaven.test.skip -DskipQuarkus -DskipTestsuite -DskipExamples -DskipTests'
```
