### ISSUE TITLE
Create a development server on Docker with older version (16) of Keycloak

### ISSUE THREAD

**Issue by Or05230** [keycloak/keycloak#11133]
### Describe the bug

I'm using keycloak-js and currently i can't use version 17 (becauase it's intergrated with keycloak-angular which is not updated yet). 
 In the getting started guide it's recommended to get the newer server version.
I have tried to get an older version via the following command:
`docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:16.1.1`

But i'm getting the following error:

```
08:53:23,664 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 56) failed setting interface to /172.17.0.2: java.net.SocketException: Protocol not available (Error setting socket option)
08:53:23,672 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 56) failed setting interface to /172.17.0.2: java.net.SocketException: Protocol not available (Error setting socket option)
08:53:23,680 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 56) MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
        at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:66)
        at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
        at org.jboss.as.clustering.jgroups@26.0.1.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:116)
        at org.jboss.as.clustering.jgroups@26.0.1.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:58)
        at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:63)
        ... 7 more
Caused by: java.net.SocketException: Protocol not available
        at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:235)
        at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:328)
        at org.jgroups@4.2.15.Final//org.jgroups.protocols.UDP.createSockets(UDP.java:417)
        at org.jgroups@4.2.15.Final//org.jgroups.protocols.UDP.start(UDP.java:292)
        at org.jgroups@4.2.15.Final//org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:881)
        at org.jgroups@4.2.15.Final//org.jgroups.JChannel.startStack(JChannel.java:989)
        at org.jgroups@4.2.15.Final//org.jgroups.JChannel._preConnect(JChannel.java:853)
        at org.jgroups@4.2.15.Final//org.jgroups.JChannel.connect(JChannel.java:358)
        at org.jgroups@4.2.15.Final//org.jgroups.JChannel.connect(JChannel.java:352)
        at org.jboss.as.clustering.jgroups@26.0.1.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:112)
        ... 9 more

08:53:24,152 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "jgroups"),
    ("channel" => "ee")
]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.clustering.jgroups.channel.ee" => "java.lang.IllegalStateException: java.net.SocketException: Protocol not available
    Caused by: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
    Caused by: java.net.SocketException: Protocol not available"}}
08:53:24,211 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
08:53:24,221 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
WFLYCTL0448: 42 additional services are down due to their dependencies being missing or failed
08:53:25,208 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
08:53:25,278 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: Keycloak 16.1.1 (WildFly Core 18.0.4.Final) started (with errors) in 26288ms - Started 479 of 929 services (48 services failed or missing dependencies, 694 services are lazy, passive or on-demand)
```

### Version

16.1.1

### Expected behavior

Should run a dev server with an older version of keycloak.

### Actual behavior

Error on creating a server

### How to Reproduce?

`docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:16.1.1`

**Comment by DerH4NNES** [comment]
same here

**Comment by stianst** [comment]
I'm not able to reproduce this, and we don't support older versions of Keycloak. If there is an issue with the latest release feel free to re-open with more details on how to reproduce.

**Comment by marchalb** [comment]
Got the same problem on an M1 Mac .. but it did seem to work on Mac with Intel if I remember correctly .. Do you have an M1 Mac?
