### ISSUE TITLE
Nullpointer exceptions on resource page

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#11137]
### Describe the bug

After creating a resource showing the details creates a NPE:

```
2022-04-06 11:27:56,993 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.NullPointerException
	at org.keycloak.authorization.jpa.store.JPAPolicyStore.findByResourceType(JPAPolicyStore.java:232)
	at org.keycloak.authorization.store.PolicyStore.findByResourceType(PolicyStore.java:129)
	at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.lambda$findByResourceType$6(StoreFactoryCacheSession.java:1014)
	at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1110)
	at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1095)
	at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.findByResourceType(StoreFactoryCacheSession.java:1014)
	at org.keycloak.authorization.AuthorizationProvider$3.findByResourceType(AuthorizationProvider.java:415)
	at org.keycloak.authorization.admin.ResourceSetService.getPermissions(ResourceSetService.java:258)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

### Version

main branch quarkus build

### How to Reproduce?

Create a resource:
![image](https://user-images.githubusercontent.com/51133/161948953-666e8ecf-1672-45f1-ba13-22687505d625.png)
with a resource type filled in, go back to the list of resource and expand the details row:
![image](https://user-images.githubusercontent.com/51133/161949395-2454d023-bb08-4147-86d0-7a2c997805ff.png)

**Comment by stianst** [comment]
@pedroigor this one looks quite bad, should we try to get this included in 18?

**Comment by pedroigor** [comment]
Sending a fix, it was introduced by https://github.com/keycloak/keycloak/issues/10447.
