### ISSUE TITLE
kc.sh, kcadm.sh, kcreg.sh do not respect environment variables JAVA, JAVA_HOME to select JVM

### ISSUE THREAD

**Issue by quatauta** [keycloak/keycloak#11336]
### Description

When executing Keycloak Quarkus [`bin/kc.sh`](https://github.com/keycloak/keycloak/blob/main/quarkus/dist/src/main/content/bin/kc.sh), [`bin/kcadm.sh`](https://github.com/keycloak/keycloak/blob/main/integration/client-cli/admin-cli/src/main/bin/kcadm.sh), [`bin/kcreg.sh`](https://github.com/keycloak/keycloak/blob/main/integration/client-cli/client-registration-cli/src/main/bin/kcreg.sh), the first `java` command found in `$PATH` is executed. The environment variables `JAVA` and `JAVA_HOME` are not available to specify the `java` command / JVM to execute.

Our default server image needs to have a Java 8 JVM configured as "default" JVM in `$PATH`. Running Keycloak Quarkus `kc.sh` results in a UnsupportedClassVersionError because the default Java 8 JVM is used.

```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

$ ./bin/kc.sh
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/quarkus/bootstrap/runner/QuarkusEntryPoint has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

With `JAVA_HOME` is set to the installation directory of a Java 16 JVM (as example), `bin/kc.sh` still executes our default Java 8 JVM.

```
$ /usr/lib/jvm/java-16-openjdk-amd64/bin/java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
dev in dschoemer in ~/development/keycloak-17.0.1
$ JAVA_HOME=/usr/lib/jvm/java-16-openjdk-amd64 ./bin/kc.sh
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/quarkus/bootstrap/runner/QuarkusEntryPoint has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

### Expected behavior

`bin/kc.sh` (`bin/kcadm.sh` and `bin/kcreg.sh`, too) respect environment variables `JAVA` and/or `JAVA_HOME` to start a selected JVM.

### Actual behavior

`bin/kc.sh` (`bin/kcadm.sh` and `bin/kcreg.sh`, too) start the JVM whose `java` command is the first one found in environment variable `PATH`.

### Steps to reproduce

1. Set default JVM to a JVM older than Java 11
2. Verify that `java` starts the old JVM
3. Set environment variable `JAVA` or `JAVA_HOME` to a Java 11 JVM (or newer)
   1. Set `JAVA` to the fully qualified path of a JVM 11 (or newer) `java` command
   2. or set `JAVA_HOME` to the fully qualified installation directory of a JVM 11 (or newer)
4. Execute `bin/kc.sh`

### Motivation

Keycloak Legacy supports environment variables `JAVA` and `JAVA_HOME`.
Keycloak `bin/kc.bat` supports environment variables `JAVA` and `JAVA_HOME`.

### Details

I will prepare a PR to update [`bin/kcadm.sh`](https://github.com/keycloak/keycloak/blob/main/integration/client-cli/admin-cli/src/main/bin/kcadm.sh), [`bin/kcreg.sh`](https://github.com/keycloak/keycloak/blob/main/integration/client-cli/client-registration-cli/src/main/bin/kcreg.sh) and [`bin/kc.sh`](https://github.com/keycloak/keycloak/blob/main/quarkus/dist/src/main/content/bin/kc.sh) to support environment variables `JAVA` and `JAVA_HOME`.

**Comment by huynguyen-anduin** [comment]
Hi, I run into the same issue. Is there any solution for this issue now?

**Comment by danghuybk** [comment]
Hi, I have the same issue. Is there any solution now?
