### ISSUE TITLE
Webauthn registration configured for loginless flow returns "WebAuthn API .create() response validation failure"

### ISSUE THREAD

**Issue by shobull** [keycloak/keycloak#11488]
### Describe the bug

- _Security key_: Yubico Yubikey 5 NFC
- _WebAuthn Passwordless Policy_:
  - Require Resident Key: Yes
  - User Verification Requirement: required
  - other default values 
- Set required action for my user "WebAuthn Register Passwordless"

=> When user logs in using his credentials he is asked for security key. After inserting key user is redirected to error page and key wasn't registered.

### Version

nightly (2022-04-12)

### Expected behavior

User is redirected and successfully authenticated. His security key credentials are stored in his account.

### Actual behavior

Security key is not registered for user.

### How to Reproduce?

1) User logs in using his credentials
2) Button for registration of security key shows -> click
3) User is requested to insert security key -> done
4) Redirection back to app with error: **Security key registration result is invalid.
AbortError: The operation was aborted.**. 
5) Server log contains this WARN: **WebAuthn API .create() response validation failure. AbortError: The operation was aborted. **

**Comment by shobull** [comment]
Update: 
Problem seems to be browser related. My report was tested on **Firefox 99.0.1 (64-bit)**.
It works correctly on **Chrome Version 100.0.4896.127 (Official Build) (x86_64)** .

**Comment by nicolas-nunca** [comment]
Environment:
- Keycloak 18.0.0 Stable
- OS: Windows 11 21H2
- Browsers: Firefox 99.0.1 (64-Bit) and Edge 100.0.1185.50 (Official Build) (64-Bit)
- Security Key: YubiKey 5C NFC (Yubico passwordless login demo successful)

I have the same issue. I also want to avoid typing the username. I have meticulously followed the [Server Administration Guide: Loginless WebAuthn](https://www.keycloak.org/docs/latest/server_admin/#_webauthn_loginless). When adding the required action, loggin on as the user to register the security key, the windows security dialog **specifically** mentions that a resident key will be generated to allow login without entering a username.  So far, so good. But login won't work for me unless I add the username form before the webauthn passwordless execution, which is what I also want to avoid.

Apparently the WebAuthn implementation is in parts based on webauthn4j. Although old and already archived, I have researched to try and shed some light on the issue and found [this old thread](https://github.com/webauthn4j/keycloak-webauthn-authenticator/issues/22). @cdanger [mentions ](https://github.com/webauthn4j/keycloak-webauthn-authenticator/issues/22#issuecomment-504692087) that a PUBLIC_KEY_CREDENTIAL_ID attribute in the user model should be set. I don't know if modern-day keycloak still stores it there, but I can see that even though registering my security key works, this attribute is never set and I suspect that it might have to to to with the aforementioned missing attribute. If my theory is right, keycloak will not be able to retrieve the attribute because it was never stored in the first place and then throw invalid_user_credentials error.

However, I'm out of my depth here. Any advice on this is highly appreciated. Thank you.

@shobull: did you take any additional steps I might have missed?

Keycloak output:
```
2022-04-26 17:12:40,388 WARN  [org.keycloak.services] (executor-thread-588) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: authenticator: webauthn-authenticator-passwordless
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:257)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1042)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:904)
	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:151)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:326)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:189)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
	at jdk.internal.reflect.GeneratedMethodAccessor400.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:340)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:362)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jafkn** [comment]
> 

Instead of an Security Key, I tried to use Windows Hello, bit in principle, I think I have the same issue as @nicolas-nunca:
I described it in [Discussions](https://github.com/keycloak/keycloak/discussions/12987), resp. [Stackexchange](https://stackoverflow.com/questions/72853713/loginless-webauthn-dont-have-to-type-in-username-nor-password-when-using-webau) in detail.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by robertsantiago** [comment]
Environment:
	•	Keycloak 21.0.2
	•	OS: macOS Ventura 13.3
	•	Browser:  Chrome 106.0.5249.119 (Official Build) (arm64)
	•	Security Key: Touch ID

I am also experiencing the same issue with the latest  version of Keycloak (21.0.2) after following the same steps as described in the documentation. As administrator, I impersonate the user to register the security key (using Touch ID). At this point I am expecting a login form followed by a key registration form but all I get is a “Security Key login” form. If I try to login I get a “Security Key Error” dialog with the message “Failed to authenticate by the security key.”. 

In case it is helpful, I have attached a json export of the realm. I have tried other Webauthn use cases (e.g., username/password + Webauthn) and they all work. It seems that only the Loginless setup is broken.

[loginless-demo-realm-export.txt](https://github.com/keycloak/keycloak/files/11225615/loginless-demo-realm-export.txt)

**Comment by e3b0c442** [comment]
I can verify that this is still applicable in the latest released version of Keycloak (23.0.1) with the latest version of both Safari (17.1.2), Firefox (120.0.1), and Arc (a Chromium browser, 1.19.1) on macOS Sonoma 14.1.2.

**Comment by pkunal17** [comment]
This issue is still persisting with latest versions of Chrome, Edge and brave.

**Comment by mposolda** [comment]
Switching to priority "important" for now as it affects lots of users.

However I am not sure if this is strictly Keycloak bug or rather environment issue. Can someone please clarify if it is possible to login to some other sites with your security key like for instance https://webauthn.passwordless.id/demos/playground.html ?

**Comment by e3b0c442** [comment]
From my chair here this a Keycloak-specific issue. WebAuthn passwordless flow works as expected with YubiKeys for GitHub, Google and Microsoft across all modern browsers/OSes. Keycloak is the only place I have tried to set up a passwordless flow with a YubiKey where it fails.

**Comment by e3b0c442** [comment]
Unfortunately other responsibilities have prevented me from digging into the code and trying to diagnose this, but my _suspicion_ — given that platform authenticators work but YubiKeys do not — is that the relying party ceremony is requiring `platform` for `authenticatorAttachment` and failing the ceremony if `cross-platform` is reported as it would be from a YubiKey. 

Again, this is a swing at the problem without having really been able to dig into it myself, but worth looking at.

**Comment by rmartinc** [comment]
I cannot test with yubikeys but I can say that there was an issue https://github.com/keycloak/keycloak/issues/28113 with yubikeys involved and there at least it was working (there the issue was that in 24.0 the CA for yubikeys should be added to the truststore to make the attestation conveyance work).

**Comment by jonkoops** [comment]
I am no longer able to reproduce this issue with my YubiKey, and from what @rmartinc is saying above I suspect that this issue has since been resolved. I'll close the issue as unreproducible, but if anyone has steps to reproduce with the latest Keycloak let me know.
