### ISSUE TITLE
POST /{realm}/users/{id}/role-mappings/realm is returning 500

### ISSUE THREAD

**Issue by matheushent** [keycloak/keycloak#11517]
### Describe the bug

The bug is quite simple to understand: a POST request to `/{realm}/users/{id}/role-mappings/realm` is returning 500. The payload I am sending in the body is:

```json
{
    "roles": [
        {
            "name": "some-name"
        }
    ]
}
```

I also tried to pass the id of the role and the result is the same. From the logs I can see:

```shell
2022-04-19 20:48:18,135 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-417) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.keycloak.representations.idm.RoleRepresentation>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:193)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:101)
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:63)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:80)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:213)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:95)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:128)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Version

17.0.1

### Expected behavior

I expected no error 500

### Actual behavior

I'm receiving status code 500 from the API

### How to Reproduce?

1. Initiate a keycloak server;
2. Issue a token to call the admin API;
3. create a dummy user and create a dummy role
4. call the endpoint `/{realm}/users/{id}/role-mappings/realm` passing the id of the user created previously and the payload body as mentioned in the [describe the bug section](#describe-the-bug)

**Comment by matheushent** [comment]
I just noticed this behaviour is happening for all routes that have `role-mappings` in their paths. Excuse me here but this doesn't have medium impact, this is huge. I cannot simply add role-mappings to neither clients nor groups, not even users....

**Comment by matheushent** [comment]
Ok, after some debugging and help from a folk, I could realize there's an error in the documentation.
![image](https://user-images.githubusercontent.com/45343359/164520716-23a6e59f-9399-4e28-995a-5b3f8a2e56a0.png)
As the image above shows, the docs says the route expects a key-value pair in the body but I could make the request successfull passing no key, only the array. @mabartos how can we put in the roadmap a fix for the documentation?

**Comment by mabartos** [comment]
@matheushent Thanks for creating this issue and for your additional findings. This issue is still in a triage state and the impact needs to be investigated further. Everything related to the documentation you can find in this[1] repository. Feel free to create a PR, which can speed up the whole process.

[1] https://github.com/keycloak/keycloak-documentation

**Comment by simonjcarr** [comment]
I am also getting this 500 error. Here is my curl command

```bash
roles=$(curl -v -X POST "${KEYCLOAK_URL}/auth/admin/realms/task-repository-testing/users/${userId}/role-mappings/realm" \
 -H "Content-Type: application/json" \
 -H "Accept: application/json" \
 -H "Authorization: Bearer ${access_token}" \
 -D "[{\"id\":\"${roleId}\",\"name\":\"${roleName}\"}]")
```

Here are the values I am passing in
```bash
echo $userId
559ceed6-e527-4ae4-bc29-8cfa6b7094a2
echo $roleId
7e1718b9-62f1-42f7-aca9-0cd68286676e
echo $roleName
createProject
```

and the error I get is

```
* Connected to localhost (127.0.0.1) port 8085 (#0)
> POST /auth/admin/realms/task-repository-testing/users/559ceed6-e527-4ae4-bc29-8cfa6b7094a2/role-mappings/realm HTTP/1.1
> Host: localhost:8085
> User-Agent: curl/7.74.0
> Content-Type: application/json
> Accept: application/json
> Authorization: Bearer ***redacted***
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Referrer-Policy: no-referrer
< Date: Tue, 07 Mar 2023 22:36:45 GMT
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< Content-Type: application/json
< Content-Length: 25
< 
```

You can see that I am passing an array

I have also tried passing the following combinations

```bash
"[{\"id\":\"${roleId}\"]"
"[{\"name\":\"${roleName}\"}]"
```

Am I doing something wrong?

**Comment by avarf** [comment]
Hi @matheushent , how did you solve this issue?
I am using keycloak 19.0.3 and I tried below curl command but I am getting the exact same error as you:
```bash
echo "=== add roles to the client-scope"
SCOPE_ENDPOINT="$KEYCLOAK_URL/auth/admin/realms/test/client-scopes"
curl -X POST \
  -H "Authorization: bearer $bearer_token" \
  -H "Content-Type: application/json" \
  -d '{
    "roles": [
      {
        "id": "New-Role-1",
        "name": "New-Role-1",
        "description": "New-Role-1"
      },
      {
        "id": "New-Role-2",
        "name": "New-Role-2",
        "description": "New-Role-2"
      }
    ]
  }' \
  "$SCOPE_ENDPOINT/bd5a521b-0c51-47ba-ade7-b6e3fd759c65/scope-mappings/realm"
```

**Comment by avarf** [comment]
I just tested this against version 21.1.1 and although I can do a GET request but the POST request fails with a response `{"error":"unknown_error"}` and unlike version 19.0.3 there is no log.

GET request:
```bash
 SCOPE_ENDPOINT="$KEYCLOAK_URL/admin/realms/test/client-scopes"
curl -X GET \
  -H "Authorization: bearer $bearer_token" \
  -H "Content-Type: application/json" \
  "$SCOPE_ENDPOINT/ae7f1dab-342a-4242-8060-9434426be37e/scope-mappings/realm" | jq

[
  {
    "id": "7c48110b-75f6-47b3-899f-a785ed010f52",
    "name": "New-Role-3",
    "composite": false,
    "clientRole": false,
    "containerId": "87ba7ba2-4618-4033-8fff-424899a85975"
  }
]
```

**Comment by rmartinc** [comment]
@avarf You have to send an array of roles, for example, to add a realm role to a user:

```
curl "${KEYCLOAK_URL}/admin/realms/master/users/2588e59b-3538-4389-8071-1f5d49fe0608/role-mappings/realm" \
  -H 'authorization: Bearer xxxx' \
  -H 'content-type: application/json' \
  --data-raw '[{"id":"7fdc7768-d31f-4f94-8284-4fbed6e385c2","name":"admin","description":"${role_admin}","composite":true,"clientRole":false,"containerId":"34aeaffc-2277-4539-ba20-f5c0ea45daf0"}]'
```

I commented this several times, you can use the admin console and the web developer tools to see what the admin app is sending to the endpoint. The admin console uses the same endpoints to configure things.

**Comment by avarf** [comment]
Thank you that solves it. Previously I tried that but I forgot to remove the outer brackets.
Still, the problem remains that the documentation is not matching the code and documentation even at version 21 is calling for a key-value body: search for "POST /{realm}/client-scopes/{id}/scope-mappings/realm" at https://www.keycloak.org/docs-api/21.0.1/rest-api/index.html
