### ISSUE TITLE
Update the CLI installation scripts for the SAML Elytron adapter so they work with WildFly 25 and later

### ISSUE THREAD

**Issue by fjuma** [keycloak/keycloak#11551]
### Description

WildFly 25 removed support for legacy security and updated the out of the box configuration so that Elytron resources were configured by default instead.

The Keycloak SAML Elytron adapter installation scripts need to be updated so they work properly with the new out of the box configuration.

**Comment by grldchz** [comment]
Using the updated CLI script I still get the following error on startup of Wildfly26:
`Caused by: java.lang.RuntimeException: Legacy WildFly security layer is no longer supported by the Keycloak WildFly adapter
      at org.keycloak.keycloak-saml-wildfly-subsystem@21.0.0//org.keycloak.subsystem.adapter.saml.extension.KeycloakDependencyProcessorWildFly.addPlatformSpecificModules(KeycloakDependencyProcessorWildFly.java:42)
       at org.keycloak.keycloak-saml-wildfly-subsystem@21.0.0//org.keycloak.subsystem.adapter.saml.extension.KeycloakDependencyProcessor.deploy(KeycloakDependencyProcessor.java:68)
       at org.jboss.as.server@18.1.0.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
       ... 8 more
`
