### ISSUE TITLE
JPA/Hibernate: java.lang.ClassNotFoundException: org.jboss.jandex.DotName

### ISSUE THREAD

**Issue by gitdode** [keycloak/keycloak#11593]
### Describe the bug

We have a custom user federation provider accessing a database using JPA/Hibernate with some JPA entities. It is working fine since Keycloak 4 up to including 17.0.1 (Quarkus).

Since 17.0.0 (Quarkus) we are using auto-build with docker-compose:

`start --auto-build --http-relative-path /auth`

With 18.0.0 the provider now first fails with:

```
2022-04-22 10:54:57,628 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: java.lang.NoClassDefFoundError: org/jboss/jandex/DotName
 at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.<clinit>(ClassFileArchiveEntryHandler.java:35)
 at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl$ArchiveContextImpl.<init>(AbstractScannerImpl.java:119)
 at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl.scan(AbstractScannerImpl.java:38)
 at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:76)
 at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:107)
 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:269)
 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:182)
 at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:32)
 at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:88)
 at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilder(HibernatePersistenceProvider.java:166)
 at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:141)
[...]
Caused by: java.lang.ClassNotFoundException: org.jboss.jandex.DotName
 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
 at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:107)
 at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:57)
```
subsequent attempts to use the provider then give:

```
2022-04-22 10:35:44,019 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler
 at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl$ArchiveContextImpl.<init>(AbstractScannerImpl.java:119)
 at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl.scan(AbstractScannerImpl.java:38)
 at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:76)
 at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:107)
 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:269)
 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:182)
 at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:32)
 at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:88)
 at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilder(HibernatePersistenceProvider.java:166)
 at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:141)
```
Note that we create an EntityManagerFactory programmatically using an injected DataSource configured in `quarkus.properties`.

### Version

18.0.0

### Expected behavior

There should be no NoClassDefFoundError when Hibernate scans JPA entities.

### Actual behavior

Hibernate initially fails scanning JPA entities with `ClassNotFoundException: org.jboss.jandex.DotName`, then subsequently fails with `NoClassDefFoundError: Could not initialize class org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler`.

### How to Reproduce?

Probably not easy to reproduce without a custom user federation provider using JPA entities.
If necessary, I could try to create a minimal implementation reproducing the issue.

**Comment by gitdode** [comment]
Compared to 17.0.x, `org.jboss.jandex-2.4.2.Final.jar` is not present any more in `/opt/keycloak/lib/lib/main`, but is now present in `/opt/keycloak/lib/lib/deployment`. Naive as I am I just added it to `/opt/keycloak/lib/lib/main`, but that did not help.

Adding the classes of `org.jboss.jandex-2.4.2.Final.jar` to the provider uber jar however solves the issue.

**Comment by gitdode** [comment]
Having the same issue with `jakarta.servlet:jakarta.servlet-api`:

```
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
     at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:107)
     at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:57)
```
when doing this in the user federation provider:

```
value = keycloakSession.getContext().getAuthenticationSession()
        .getClientNote(LOGIN_SESSION_NOTE_ADDITIONAL_REQ_PARAMS_PREFIX + parameter);
```
This also worked up to including 17.0.1.
So it appears that all libraries that were moved from `main` to `deployment` are not available to custom providers any more. Is this on purpose?

**Comment by immieszko** [comment]
hi @gitdode, did you make some progress in this case, or maybe you have some temporary solution? I am in the same situation as you.

**Comment by gitdode** [comment]
Hi @immieszko 
my current workaround is to add these dependencies in the project building the provider uber jar:

        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <version>2.4.2.Final</version>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>4.0.3</version>
        </dependency>

and then include the classes in the configuration of `maven-shade-plugin` used to build the provider jar:

    <include>org.jboss:jandex</include>
    <include>jakarta.servlet:jakarta.servlet-api</include>

this solves the issue but it feels redundant since Keycloak includes these libraries, they just don't seem to be visible to the provider deployment.

**Comment by gitdode** [comment]
@pedroigor Thank you, it works fine following your quickstart. And I think it is more than enough to get up and running with this :-)

However a `persistence.xml` is not an option for us since we need to be able to configure arbitrary persistence units on-site, and I did not manage to get it to work without a `persistence.xml` following [Multiple persistence units](https://quarkus.io/guides/hibernate-orm#multiple-persistence-units) with a `quarkus.properties` like this:

    # works with persistence.xml
    quarkus.datasource.test.db-kind=postgresql
    quarkus.datasource.test.jdbc.url=jdbc:postgresql://db:5432/test
    quarkus.datasource.test.username=test
    quarkus.datasource.test.password=test
    quarkus.datasource.test.jdbc.max-size=10
    # added in attempt to make persistence.xml unnecessary
    quarkus.hibernate-orm.test.datasource=test
    quarkus.hibernate-orm.test.packages=package.containing.the.jpa.entities

Like that, `session.getProvider(JpaConnectionProvider.class, "test")` just returns `null`.
In a "plain" Quarkus app it works that way - am I missing something for Keycloak?

Creating the EMF programmatically works fine for us besides that we have to include `org.jboss:jandex` in our provider uber jar since Keycloak 18.0.0.

**Comment by pedroigor** [comment]
I see. It should not work indeed and for that, we would need additional code to make it possible.

I'm closing this one for now. If it shows up to be a common use case, we can evaluate enabling this by allowing you to write some hook during re-augmentation to configure additional PUs programmatically. I would say including that dependency is OK for now, if it works.

Thanks.
