### ISSUE TITLE
LDAP user federation no longer works with Keycloak 18

### ISSUE THREAD

**Issue by kaenganxt** [keycloak/keycloak#11675]
### Describe the bug

I'm logging in to keycloak with a user that exists in LDAP. On 17.0.0 it worked fine, while 18.0.0 leads to the following error in the log:
```
2022-04-26 16:50:02,650 WARN  [org.keycloak.services] (executor-thread-1) KC-SERVICES0013: Failed authentication: org.keycloak.models.ModelException: LDAP Query failed
keycloak_1       |      at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:176)
keycloak_1       |      at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getFirstResult(LDAPQuery.java:183)
keycloak_1       |      at org.keycloak.storage.ldap.LDAPStorageProvider.loadLDAPUserByUuid(LDAPStorageProvider.java:832)
keycloak_1       |      at org.keycloak.storage.ldap.LDAPStorageProvider.loadAndValidateUser(LDAPStorageProvider.java:491)
keycloak_1       |      at org.keycloak.storage.ldap.LDAPStorageProvider.validate(LDAPStorageProvider.java:166)
keycloak_1       |      at org.keycloak.storage.UserStorageManager.importValidation(UserStorageManager.java:116)
keycloak_1       |      at org.keycloak.storage.UserStorageManager.getUserByEmail(UserStorageManager.java:305)
keycloak_1       |      at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByEmail(UserCacheSession.java:386)
keycloak_1       |      at org.keycloak.models.utils.KeycloakModelUtils.findUserByNameOrEmail(KeycloakModelUtils.java:222)
keycloak_1       |      at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUserFromForm(AbstractUsernameFormAuthenticator.java:188)
keycloak_1       |      at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUser(AbstractUsernameFormAuthenticator.java:167)
keycloak_1       |      at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validateUserAndPassword(AbstractUsernameFormAuthenticator.java:148)
keycloak_1       |      at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.validateForm(UsernamePasswordForm.java:55)
keycloak_1       |      at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.action(UsernamePasswordForm.java:48)
keycloak_1       |      at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:169)
keycloak_1       |      at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:990)
keycloak_1       |      at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:321)
keycloak_1       |      at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:292)
keycloak_1       |      at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:276)
keycloak_1       |      at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:349)
keycloak_1       |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak_1       |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
keycloak_1       |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1       |      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak_1       |      at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
keycloak_1       |      at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
keycloak_1       |      at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
keycloak_1       |      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
keycloak_1       |      at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
keycloak_1       |      at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak_1       |      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
keycloak_1       |      at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
keycloak_1       |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
keycloak_1       |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
keycloak_1       |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
keycloak_1       |      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
keycloak_1       |      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
keycloak_1       |      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
keycloak_1       |      at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak_1       |      at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
keycloak_1       |      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
keycloak_1       |      at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
keycloak_1       |      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
keycloak_1       |      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
keycloak_1       |      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
keycloak_1       |      at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak_1       |      at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak_1       |      at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak_1       |      at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
keycloak_1       |      at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
keycloak_1       |      at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak_1       |      at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak_1       |      at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak_1       |      at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
keycloak_1       |      at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
keycloak_1       |      at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
keycloak_1       |      at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
keycloak_1       |      at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
keycloak_1       |      at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
keycloak_1       |      at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
keycloak_1       |      at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
keycloak_1       |      at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
keycloak_1       |      at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
keycloak_1       |      at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
keycloak_1       |      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
keycloak_1       |      at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak_1       |      at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak_1       |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak_1       |      at java.base/java.lang.Thread.run(Thread.java:829)
keycloak_1       | Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@172fec39
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
keycloak_1       |      at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:172)
keycloak_1       |      ... 68 more
keycloak_1       | Caused by: org.keycloak.models.ModelException: Could not query server using DN [ou=People,dc=*sth*,dc=de] and filter [(&(objectClass=*)(entryUUID=*someUUID*))]
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.lookupById(LDAPOperationManager.java:442)
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:261)
keycloak_1       |      ... 69 more
keycloak_1       | Caused by: javax.naming.NamingException: Cannot parse url: ldap://keycloak_keycloak-ldap_1 [Root exception is java.net.MalformedURLException: unsupported authority: keycloak_keycloak-ldap_1]
keycloak_1       |      at java.naming/com.sun.jndi.ldap.LdapURL.<init>(LdapURL.java:115)
keycloak_1       |      at java.naming/com.sun.jndi.ldap.DefaultLdapDnsProvider.lookupEndpoints(DefaultLdapDnsProvider.java:47)
keycloak_1       |      at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:200)
keycloak_1       |      at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:284)
keycloak_1       |      at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:185)
keycloak_1       |      at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:115)
keycloak_1       |      at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
keycloak_1       |      at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
keycloak_1       |      at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
keycloak_1       |      at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:711)
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:706)
keycloak_1       |      at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.lookupById(LDAPOperationManager.java:410)
keycloak_1       |      ... 70 more
keycloak_1       | Caused by: java.net.MalformedURLException: unsupported authority: keycloak_keycloak-ldap_1
keycloak_1       |      at java.naming/com.sun.jndi.toolkit.url.Uri.parseCompat(Uri.java:373)
keycloak_1       |      at java.naming/com.sun.jndi.toolkit.url.Uri.parse(Uri.java:233)
keycloak_1       |      at java.naming/com.sun.jndi.toolkit.url.Uri.init(Uri.java:174)
keycloak_1       |      at java.naming/com.sun.jndi.ldap.LdapURL.<init>(LdapURL.java:105)
keycloak_1       |      ... 84 more

```
The domain name `keycloak_keycloak-ldap_1` is fine as it is a docker container name.

I already investigated this issue further:
- The contained OpenJDK seems to have an issue in `java.naming/com.sun.jndi.toolkit.url.Uri.parseCompat`
- The relevant code part is `String hostport = ((this.host == null) ? "" : this.host) + ((this.host == null) ? "" : this.host));` which seems to be a copy-paste error from a backported fix
- The original OpenJDK code looks like this: `String hostport = (host == null ? "" : host) + (port == -1?"":(":" + port));` which makes much more sense.
- The correct code is only available since OpenJDK 18 (https://github.com/openjdk/jdk/blob/master/src/java.naming/share/classes/com/sun/jndi/toolkit/url/Uri.java#L363-L364), while the first example is included in the JDK 11 (so this seems to be a patch on the rpm package)

I am not sure where to report this properly, but I think it might be fixable by installing a different java package in the Keycloak Dockerfile.
If you could point me to the right place I could also report this issue somewhere upstream.

### Version

Quarkus 18.0.0 Docker Image

### Expected behavior

LDAP user federation should work just as in Keycloak 17

### Actual behavior

See above

### How to Reproduce?

This was not tested exactly with these steps as a configured Keycloak installation already existed.
- Run quay.io/keycloak/keycloak:18.0.0 docker image
- Setup LDAP user federation to an LDAP server with a simple URL like `ldap://ldap-server`
- Log in with a federated account

**Comment by pedroigor** [comment]
This seems to be related to https://www.oracle.com/java/technologies/javase/11-0-15-relnotes.html#JDK-8278972.

I'm unsure if this is an issue in JDK as I initially thought.

Looks like you can relax validations by setting `-Dcom.sun.jndi.ldapURLParsing="legacy"` and workaround the issue. But I'm sure this is not the best to do.

Need to look closer and see if instead, we need to change how we are crafting LDAP urls.

**Comment by pedroigor** [comment]
@andreaTP @kaenganxt I suspect the best approach is to remove the invalid `_` character from the hostname of the URI. If you change the URL to `ldap://keycloak-keycloak-ldap-1` it should work.

**Comment by andreaTP** [comment]
Following up on @pedroigor suggestion, this snippet correctly runs on 11.0.15:
```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 11
//JAVA_OPTIONS -Dcom.sun.jndi.ldapURLParsing=legacy
//JAVAC_OPTIONS --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED

import com.sun.jndi.ldap.LdapURL;
import static java.lang.System.*;

public class test {
    public static void main(String... args) throws Exception {
        out.println(getProperty("java.version"));
        new LdapURL("ldap://keycloak_keycloak-ldap_1");
    }
}
```

So, for this issue, a valid workaround is to set `-Dcom.sun.jndi.ldapURLParsing=legacy` in the `JAVA_OPTS_APPEND` environment variable.

e.g.
local: `export JAVA_OPTS_APPEND="-Dcom.sun.jndi.ldapURLParsing=legacy"`
docker run: `-e JAVA_OPTS_APPEND="-Dcom.sun.jndi.ldapURLParsing=legacy"`

**Comment by pedroigor** [comment]
@andreaTP Not sure if it is a valid recommendation. As I mentioned, the best is to format the hostname properly.

**Comment by kaenganxt** [comment]
Thanks for the recommendations, using a different hostname works.
This is kind of interesting as the Code in `Uri::parseCompat` in the used JDK is definitely wrong. It seems that with a correct hostname, the function is not called at all.

Interesting fact:
When looking at the JDK package of the ubi8 image repository (https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/Packages/j/java-11-openjdk-headless-11.0.15.0.9-2.el8_5.x86_64.rpm) it contains the incorrect code, but this source is nowhere to be found on the internet. The official OpenJDK repository for 11.0.15 contains the correct code (https://github.com/openjdk/jdk11u/blob/jdk-11.0.15%2B10/src/java.naming/share/classes/com/sun/jndi/toolkit/url/Uri.java).

I'm not sure where this problem might come from, but since it's not a problem on the Keycloak side, I'm closing this, thanks for your help.
