### ISSUE TITLE
Sometimes, a user logout leads to a keycloak server internal error

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#11697]
### Describe the bug

Hi,

Sometimes, a user logout leads to a keycloak server internal error.

Here is the associated stacktrace:

```
2020-12-10 16:46:12,539 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-1273) Uncaught server error: java.lang.IllegalStateException: Can't add se
ssion: task in progress for session
        at org.keycloak.models.sessions.infinispan.InfinispanKeycloakTransaction.put(InfinispanKeycloakTransaction.java:84)
        at org.keycloak.models.sessions.infinispan.InfinispanAuthenticationSessionProvider.createRootAuthenticationSession(InfinispanAuthenticationSessionProvider.java:8
2)
        at org.keycloak.services.managers.AuthenticationManager.createOrJoinLogoutSession(AuthenticationManager.java:289)
        at org.keycloak.services.managers.AuthenticationManager.browserLogout(AuthenticationManager.java:524)
        at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.initiateBrowserLogout(LogoutEndpoint.java:255)
        at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logout(LogoutEndpoint.java:144)
        at sun.reflect.GeneratedMethodAccessor1351.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498) 
```

### Version

11.0.3

### Anything else?

https://issues.redhat.com/browse/KEYCLOAK-16632

**Comment by mposolda** [comment]
Thanks for the report. I am adding label "Help wanted" as Keycloak team won't have time to look at this in the near future. It would need to be community contribution to improve this. See "Contributors" section under https://www.keycloak.org/community for more details.

There was some recent refactoring for logout, so it is possible that bug is not applicable anymore in latest Keycloak version (will be nice to confirm).

Another thing is, that this is probably applicable just to the old store and this bug may automatically disappear once we migrate to the new store by default (probably somewhen in 2023).

**Comment by jaapspiering** [comment]
We are observing the same issue, on Keycloak 12.0.4. For compatibility with our CAS integration extension we have not yet upgraded to a newer version.

**Comment by prsanjay** [comment]
I got this issue in Keycloak 20.0.1 but the issue is at Nginx side. upstream sent too big header while reading response header from upstream. And I found this SO related to this: https://stackoverflow.com/questions/57503590/upstream-sent-too-big-header-while-reading-response-header-from-upstream-in-keyc

**Comment by jaapspiering** [comment]
I will definitely look into that. Our Keycloak is hosted on Kubernetes and indeed fronted by an nginx proxy. Seems to be the cause of many issues!

More references:
https://keycloak.discourse.group/t/nginx-reverse-proxy-shows-502-for-keycloak-registration-form-submission/10550
https://gist.github.com/dasniko/059dc2a895f585f6f74edaa042a2da48

**Comment by reda-alaoui** [comment]
FYI, we don't use nginx. Our keycloak is behind HAProxy .

**Comment by azhurb** [comment]
We solved this by removing `id_token_hint` from params as it is optional https://github.com/keycloak/keycloak-documentation/blob/main/securing_apps/topics/oidc/java/logout.adoc
