### ISSUE TITLE
Keycloak sensitive data encryption

### ISSUE THREAD

**Issue by mazenaissa** [keycloak/keycloak#11716]
### Description

Hello, community,

In order to be compliant GDPR, I was asked to find a way to make Keycloak crypt sensitive data in a database (user's info like email, username../realm keys/...). The only solution I've found is to use an AttributeConverter on the sensitive columns, the implementation of the extension can be found [here ](https://github.com/mazenaissa/keycloak-data-encryption).

How does the extension work?

-Keycloak has some classes that load the file persistence.xml from the jar keycloak-model-jpa, the main idea was to have an ORM file containing the list of columns that will be encrypted with the converter. So to accomplish this I had to copy these 2 classes: DefaultJpaConnectionProvider & DefaultJpaConnectionProviderFactory and the [persistence.xml](https://github.com/mazenaissa/keycloak-data-encryption/blob/master/src/main/resources/META-INF/persistence.xml) from keycloak-model-jpa jar to my extension jar and link the [orm file](https://github.com/mazenaissa/keycloak-data-encryption/blob/master/src/main/resources/META-INF/orm.xml) in it and injecting the copied class as the default service of JPA.
-Now on every read/write action on sensitive columns described in the orm file, the class [StringColumnConverter ](https://github.com/mazenaissa/keycloak-data-encryption/blob/master/src/main/java/com/mazzo/keycloak/encryption/StringColumnConverter.java)will decrypt/decrypt it respectively.
-The algorithm used is AES-128 Bit-CBC with PKCS5PADDING.

Issues with the extension :

-The search of users in admin console UI is adding lower function and using the like operator on email, username,... Now this feature is broken and I had to remove the % in order to make the like works like .equals and make my encryption implementation stores data in lower case to match the search. The implementation of this case can be found [here ](https://github.com/mazenaissa/keycloak-data-encryption/blob/master/src/main/java/com/mazzo/keycloak/encryption/ColumnEncryptionUtility.java#L58).

-This extension must be reviewed and updated once we upgrade Keycloak as we are using its persistence.xml and 2 of its JPA model classes.
-This extension works perfectly with PostgreSQL, but when using other database systems like MySQL Keycloak fails to start with this exception :
`12:41:00,280 FATAL [org.keycloak.services] (ServerService Thread Pool – 57) Error during startup: org.hibernate.AnnotationException: AttributeConverter and explicit Type cannot be applied to same attribute [org.keycloak.models.jpa.entities.ComponentConfigEntity.value];remove @Type or specify @Convert(disableConversion = true) at org.hibernate@5.3.20.Final//org.hibernate.cfg.annotations.SimpleValueBinder.fillSimpleValue(SimpleValueBinder.java:461) at org.hibernate@5.3.20.Final//org.hibernate.cfg.SetSimpleValueTypeSecondPass.doSecondPass(SetSimpleValueTypeSecondPass.java:25) at org.hibernate@5.3.20.Final//org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1696) at org.hibernate@5.3.20.Final//org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1654) at org.hibernate@5.3.20.Final//org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:287) at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1215) at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1246) at org.keycloak.keycloak-model-jpa@12.0.1//org.keycloak.connections.jpa.util.JpaUtils.createEntityManagerFactory(JpaUtils.java:61) at deployment.keycloak-data-encryption-1.0.jar//com.mazzo.keycloak.jpa.DefaultJpaConnectionProviderFactory.lambda$lazyInit$0(DefaultJpaConnectionProviderFactory.java:198) at org.keycloak.keycloak-server-spi-private@12.0.1//org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:654) at deployment.keycloak-data-encryption-1.0.jar//com.mazzo.keycloak.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:121) at deployment.keycloak-data-encryption-1.0.jar//com.mazzo.keycloak.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:69) at deployment.keycloak-data-encryption-1.0.jar//com.mazzo.keycloak.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:47) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:274) at org.keycloak.keycloak-model-jpa@12.0.1//org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:51) at org.keycloak.keycloak-model-jpa@12.0.1//org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:33) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:274) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.DefaultKeycloakSession.realmLocalStorage(DefaultKeycloakSession.java:199) at org.keycloak.keycloak-model-infinispan@12.0.1//org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:152) at org.keycloak.keycloak-model-infinispan@12.0.1//org.keycloak.models.cache.infinispan.RealmCacheSession.getMigrationModel(RealmCacheSession.java:145) at org.keycloak.keycloak-server-spi-private@12.0.1//org.keycloak.migration.MigrationModelManager.migrate(MigrationModelManager.java:99) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.resources.KeycloakApplication.migrateModel(KeycloakApplication.java:234) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.resources.KeycloakApplication.migrateAndBootstrap(KeycloakApplication.java:175) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:138) at org.keycloak.keycloak-server-spi-private@12.0.1//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:228) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:129) at org.keycloak.keycloak-wildfly-extensions@12.0.1//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:29) at org.keycloak.keycloak-services@12.0.1//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:115) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152) at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2815) at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:371) at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:283) at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:93) at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140) at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97) at org.wildfly.extension.undertow@21.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990) at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) at java.base/java.lang.Thread.run(Thread.java:834) at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
`
This exception is thrown because we can't use AttributeConverter on the columns having @Nationalized annotation.

**We need you to help us reach our goal of implementing a solution in your jars to give us the possibility to crypt/decrypt sensitive data in Keycloak.**

Thanks,

**Comment by NoCoker** [comment]
Dear keycloak team - as china law requires since 1. november 2021 all "private/sensitive" data to be encrypted i would like to see a feature like descripted here in the roadmap soon. Myself i can only support with testing but i have no developing skills to support here !

We need to encrypt from china law view: username, email, password and mobile !

**Comment by sschu** [comment]
I don't know about the exact legal requirements, but if it is sufficient to encrypt data when it is stored persistently you should be able to do this on the database level.

**Comment by vidurgupta-fareye** [comment]
Anyone found any solution for this ?

**Comment by xalfonso** [comment]
Hi, is there any progress on this?

**Comment by jadamroth** [comment]
@xalfonso I saw you mentioned in the keycloak discourse you had implemented a solution

Is there any way you can upload your solution to your github or share via email? I'm struggling to come up with best practices for encrypting and searching encrypted user data

**Comment by MLukman** [comment]
Hi all,

Here is a good news that I've implemented a provider that performs encryption of user attributes before storing to database and later decrypt them upon loading from database.

https://github.com/MLukman/Keycloak-PII-Data-Encryption-Provider/

For now the provider only encrypt custom attributes with names that start with "pii-" since I have yet to figure out how to access the declarative user profile configurations from inside the entity listener. Future versions might be able to specify which user attributes to encrypt based on custom validation or annotation.

Ideas and contributions will be welcomed.

Cheers!

**Comment by MLukman** [comment]
> Unfortunatelly @MLukman solution is limited on custom attributes, but the crucial attributes to encrypt are the default ones (username, first name, last name and email)
> 
> Anyone found any solution for these attributes?

Good news! I've updated my solution to also include 4 default columns. Please check it out!

**Comment by MLukman** [comment]
Here is a good news that I've updated my Keycloak provider @ https://github.com/MLukman/Keycloak-PII-Data-Encryption-Provider/ to version 2, which now encrypts the four common attributes username, email, first name and last name. It also now restores the ability to search by those encrypted attributes, albeit only limited to exact searches.

Please feel free to try it out!

**Comment by mihirvadalia** [comment]
Do we have plan to add this as a Keycloak feature? We can help accelerate the work if needed - how can we assist?

**Comment by huyenvu2101** [comment]
Greeting from Vietnam. We are facing the same requirement due to the recently published Personal Data Protection Decree (Decree 13/2023/NĐ-CP). According, PII such as email, first name, and last name must be protected, including encryption at rest. Wish this's gonna be Keycloak official feature
