### ISSUE TITLE
Problem with connection to LDAPS

### ISSUE THREAD

**Issue by breedjaram32** [keycloak/keycloak#11772]
### Describe the bug

After switch to Keycloak 18.0.0 quarkus edition does not work ldap connection.
-After click to **Test connection** - Success! LDAP connection successful.
-After click to  **Test authentication** - Error! LDAP authentication failed. See server.log for details

Solution which works in nonquarkus edition
**import ldap cert to java cacert**
`keytool -importcert -alias ldapcert -cacerts -storepass changeit -noprompt -trustcacerts -file ldap.cer`

I tried the procedure on https://www.keycloak.org/server/outgoinghttp
1) for first in devel 
`kc.sh start --spi-connections-http-client-default-disable-trust-manager=true` **it does not work**
2)
`kc.sh start --spi-truststore-file-file=myTrustStore.jks --spi-truststore-file-password=password --spi-truststore-file-hostname-verification-policy=ANY`
and import certificate to myTrustStore.jks 
**it does not work too**

**Test authentication Log**
`2022-04-29 12:55:01,688 ERROR [org.keycloak.services] (executor-thread-32) KC-SERVICES0055: Error when authenticating to LDAP: simple bind failed: 192.168.1.150:30636: javax.naming.CommunicationException: simple bind failed: 192.168.1.150:30636 [Root exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]
	at java.naming/com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:219)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2895)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:266)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:226)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:284)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:185)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:115)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
	at org.keycloak.services.managers.LDAPServerCapabilitiesManager.testLDAP(LDAPServerCapabilitiesManager.java:99)
	at org.keycloak.services.resources.admin.RealmAdminResource.testLDAPConnection(RealmAdminResource.java:958)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:921)
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1291)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.naming/com.sun.jndi.ldap.Connection.writeRequest(Connection.java:414)
	at java.naming/com.sun.jndi.ldap.Connection.writeRequest(Connection.java:387)
	at java.naming/com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:359)
	at java.naming/com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214)
	... 66 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

### Version

18.0.0 quarkus

### Expected behavior

After successfully importing the certificate into the cacert the ldap connection should work.
kc.sh start --spi-connections-http-client-default-disable-trust-manager=true should work

### Actual behavior

kc.sh start --spi-connections-http-client-default-disable-trust-manager=true does not work
After successfully importing the certificate into the cacert the ldap connection does not work

### How to Reproduce?

More information is in Describe the bug

**Comment by jcz1** [comment]
I have workaround with stunnel. It is possible to terminate SSL for LDAP on stunnel and configure keycloak federation to non-encrypted ldap://<docker-host>:389.

/etc/stunnel/stunnel.conf example:

# TLS
sslVersionMin = TLSv1.2
renegotiation = no
ciphers = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

chroot = /var/lib/stunnel4/
setuid = stunnel4
setgid = stunnel4
pid = /stunnel4.pid

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
;compression = zlib

verify = 2
CAfile = /usr/local/share/ca-certificates/SOME-CA.crt

client = yes

[ldaps]
accept  = 389
connect = ldap-server.some.local:636
client  = yes

**Comment by darviche** [comment]
Hi,
I have the same issue. The workaround that worked for me is to add the certificates to the server/docker image and launch keycloak without the spi-truststore-file-* options.
I'm launching keycloak as a docker stack.

**Dockerfile :**
```yaml
FROM quay.io/keycloak/keycloak:18.0.0

USER root
ADD certificate.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust
```

**docker-compose (swarm mode):**
```yaml
version: '3.7'
services:
  keycloak:
    image: my_keycloak_image:latest
    command:
      - start
      - --hostname=keycloak_hostname
      - --https-certificate-file=/etc/x509/https/tls.crt
      - --https-certificate-key-file=/etc/x509/https/tls.key
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'my_password'
    configs:
      - source: cert
        target: /etc/x509/https/tls.crt
      - source: key
        target: /etc/x509/https/tls.key
    networks:
      - keycloak_net
networks:
  keycloak_net:
configs:
  cert:
    file: ./keycloak/tls.crt
  key:
    file: ./keycloak/tls.key
```

**Comment by breedjaram32** [comment]
@darviche This problem with connecting to LDAPS with non public certificate is a problem. My and your way is no longer working. I hope that will be resolved as soon as possible because otherwise Keycloak quarku is useless for me.

@jcz1 thanks for your way but I'd rather have a some default way by Keycloak :-)
Although it may be the only functional solution to this problem so far.

**Comment by pedroigor** [comment]
The instructions provided here https://www.keycloak.org/server/outgoinghttp should be enough to configure the Keycloak Truststore.

There is also this changeset to improve the guides a bit https://github.com/keycloak/keycloak/pull/12261.

W.r.t. enabling `ldaps` the following steps should be enough and some of them you did already:

* Create a truststore with your LDAP server certificate and chain (ca and intermediates).
* Configure the Keycloak Truststore as per https://www.keycloak.org/server/outgoinghttp.
* Make sure your LDAP URL is using the same hostname from the LDAP server certificate

W.r.t. #3 above, looks like the `hostname-verification-policy` is not working properly so you can't have `ldaps://foo:636` and the LDAP server using a subject certificate using, let's say, `cn=bar`. That seems to be an issue but I need to confirm.

@mposolda Is there a way to ignore hostname verification ? I don't see anything that configures trustmanagers but https://github.com/keycloak/keycloak/blob/8967ca40661ceb0bce4c3d83cd60f437422a34de/services/src/main/java/org/keycloak/truststore/JSSETruststoreConfigurator.java#L75.

**Comment by pedroigor** [comment]
Btw, the error:

```
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Is most likely related to the certificate chain not being available from the trust store.

I did some tests here using OpenLDAP and building a Java Truststore from the certs generated by the container during startup.

The steps I did were:

* `docker run --name myldap --hostname myldap -p 389:389 -p 636:636 --env LDAP_ORGANISATION="keycloak" --env LDAP_DOMAIN="keycloak.org" --env LDAP_ADMIN_PASSWORD="password" --env LDAP_TLS_VERIFY_CLIENT=never osixia/openldap:1.5.0`
* `docker cp myldap:/container/service/:ssl-tools/assets/default-ca/default-ca.pem .`
* `docker cp myldap:/container/service/slapd/assets/certs/ldap.crt .`
* `keytool -import -file default-ca.pem -alias myldapca -keystore server.truststore`
* `keytool -import -file ldap.crt -alias myldap -keystore server.truststore`
* `kc.sh --debug start-dev --spi-truststore-file-file=/tmp/keycloak-999-SNAPSHOT/conf/server.truststore --spi-truststore-file-password=password`
* Configure a LDAP using `ldaps://myldap:636`, binding to `cn=admin,dc=keycloak,dc=org`and credentials `password`

**Comment by pedroigor** [comment]
Oops, sorry :) I was supposed to ping @breedjaram32. I think your github username was in my cliboard and I just paste it without notice the mistake.

**Comment by grossws** [comment]
No problem ,)
Github issues is a good knowledge base and more cross-links could help somebody as info in #10553 helped me with `ldaps://`

**Comment by mposolda** [comment]
> The instructions provided here https://www.keycloak.org/server/outgoinghttp should be enough to configure the Keycloak Truststore.
> 
> There is also this changeset to improve the guides a bit #12261.
> 
> W.r.t. enabling `ldaps` the following steps should be enough and some of them you did already:
> 
>     * Create a truststore with your LDAP server certificate and chain (ca and intermediates).
> 
>     * Configure the Keycloak Truststore as per https://www.keycloak.org/server/outgoinghttp.
> 
>     * Make sure your LDAP URL is using the same hostname from the LDAP server certificate
> 
> 
> W.r.t. #3 above, looks like the `hostname-verification-policy` is not working properly so you can't have `ldaps://foo:636` and the LDAP server using a subject certificate using, let's say, `cn=bar`. That seems to be an issue but I need to confirm.
> 
> @mposolda Is there a way to ignore hostname verification ? I don't see anything that configures trustmanagers but
> 
> https://github.com/keycloak/keycloak/blob/8967ca40661ceb0bce4c3d83cd60f437422a34de/services/src/main/java/org/keycloak/truststore/JSSETruststoreConfigurator.java#L75
> .

I am not sure if there is a way to ignore hostname verification in the certificates when connecting to LDAP with `ldaps` . Our method `TruststoreProvider.getPolicy()` is not used at all in our codebase, which does connection to ldap server via `ldaps` .

We can possibly create issue for that if needed. However I guess this should be separate issue as it seems it is not quarkus specific problem though (and this issue is about quarkus integration if I understand correctly). I think that ability to disable hostname verification for `ldaps` connections is not yet available in the Wildfly distribution as well.

**Comment by mposolda** [comment]
@pedroigor @breedjaram32 BTV. There is surely a possibility to connect to LDAP with `ldaps` as our testsuite is doing this. When I run this from `testsuite/integration-arquillian`:
```
mvn clean install -Pauth-server-quarkus -Dtest=LDAPUserLoginTest,UserFederationLdapConnectionTest
```
it works as expected and connection to LDAP with `ldaps` is successful.

So it is just about proper setup and possibly improving documentation about this?

**Comment by pedroigor** [comment]
@mposolda Still, do we want `spi-truststore-file-hostname-verification-policy` taking effect when doing TLS? As I mentioned, it seems we are not using this option and forcing the hostname to match the certificate.

Otherwise, I'll be updating the documentation accordingly. Wdyt?

**Comment by ptman** [comment]
KC_SPI_TRUSTSTORE_FILE_FILE and KC_SPI_TRUSTSTORE_FILE_PASSWORD don't seem to be documented on https://www.keycloak.org/server/all-config

**Comment by mposolda** [comment]
@ptman It's documented here: https://www.keycloak.org/server/keycloak-truststore . Note that the page you pointed does not contain all configuration options of all Keycloak SPIs. Otherwise that would be ton of additional config options.

Some time ago, we discussed within the team that "./kc.sh help" may display the available SPIs + available implementations of those SPIs + available configuration options. But this is not yet done and might be something to consider for the future...

**Comment by rubendevgo** [comment]
Hi @breedjaram32, can you provide me the dockerfile and dockercompose file that you used on your solution?

**Comment by rubendevgo** [comment]
@breedjaram32 In the first solution: import to cacerts, did you config any env var related to the keystore?
