### ISSUE TITLE
SQL Error: 17410, SQLState: 08000 and  No more data to read from socket

### ISSUE THREAD

**Issue by yushaojian** [keycloak/keycloak#11785]
### Describe the bug

oracle version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
keycloak version: 16.1.0
oracle datasource configuration:
`
<datasource jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-java-context="true">

    <connection-url>url</connection-url>

    <driver>oracle</driver>

      <pool>

          <max-pool-size>200</max-pool-size>

      </pool>

      <security>

          <user-name>username</user-name>

          <password>password</password>

      </security>

  </datasource>
`

error log:
2022-05-01 09:02:21,115 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-2) SQL Error: 17410, SQLState: 08000
2022-05-01 09:02:21,116 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-2) No more data to read from socket
2022-05-01 09:02:21,141 ERROR [org.keycloak.services] (Timer-2) KC-SERVICES0089: Failed to run scheduled task ClearExpiredEvents: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: could not extract ResultSet
	at org.hibernate@5.3.24.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate@5.3.24.Final//org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1575)
	at org.hibernate@5.3.24.Final//org.hibernate.query.Query.getResultList(Query.java:132)
	at org.keycloak.keycloak-model-jpa@16.1.0//org.keycloak.events.jpa.JpaEventStoreProvider.clearExpiredEvents(JpaEventStoreProvider.java:91)
	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.scheduled.ClearExpiredEvents.run(ClearExpiredEvents.java:39)
	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
	at org.keycloak.keycloak-model-infinispan@16.1.0//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:55)
	at org.keycloak.keycloak-services@16.1.0//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: org.hibernate.exception.JDBCConnectionException: could not extract ResultSet
	at org.hibernate@5.3.24.Final//org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:115)
	at org.hibernate@5.3.24.Final//org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate@5.3.24.Final//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate@5.3.24.Final//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate@5.3.24.Final//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.getResultSet(Loader.java:2265)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2028)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1990)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.doQuery(Loader.java:949)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.doList(Loader.java:2787)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.doList(Loader.java:2770)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2604)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.Loader.list(Loader.java:2599)
	at org.hibernate@5.3.24.Final//org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:505)
	at org.hibernate@5.3.24.Final//org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
	at org.hibernate@5.3.24.Final//org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate@5.3.24.Final//org.hibernate.internal.SessionImpl.list(SessionImpl.java:1526)
	at org.hibernate@5.3.24.Final//org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1598)
	at org.hibernate@5.3.24.Final//org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1566)
	... 11 more
Caused by: java.sql.SQLRecoverableException: No more data to read from socket
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.T4CMAREngineStream.unmarshalUB1(T4CMAREngineStream.java:456)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:397)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
	at org.oracle@12.1.0.2.0//oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
	at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:504)
	at org.hibernate@5.3.24.Final//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	... 26 more

The system suddenly reported an error, and the problem was fixed after restarting keycloak.

### Version

16.1.0

**Comment by hmlnarik** [comment]
Thanks for reporting this issue. However, we are not able to reproduce this issue. It may be the issue has already been resolved, there are inaccurate steps to reproduce or it may be due to an issue outside of Keycloak.

**Comment by lemonit-eric-mao** [comment]
@hmlnarik 
Hello, I don't think this problem has been solved yet. You need to wait for more time. For example, after your test program interacts with Oracle, wait for 30 minutes, and the problem may recur

Oracle 12c, use this version of the database for testing

**Comment by hmlnarik** [comment]
Please retry with the most recent Keycloak version, and if this occurs then feel free to open the bug report including all the necessary information needed for reproducing the issue.
