### ISSUE TITLE
DB environment variables are not honored by the "export" command in quay.io/keycloak/keycloak:18.0

### ISSUE THREAD

**Issue by kiriakos** [keycloak/keycloak#11793]
### Describe the bug

In the following docker-compose.yml the `start-dev` command works as expected but the `export` command doesn't, failing with a "no suitable driver could be found error"

```docker-compose.yml
version: '3.1'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0
    command: --verbose start-dev
    #command: --verbose export --realm=MYREALM --users=same_file --dir=/tmp/exports
    ports:
      - "13481:8080"
    restart: always
    env_file:
      - "./keycloak-dev.env"
    environment:
      HOSTNAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  keycloak-db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "13483:5432"
    environment:
      - POSTGRES_USER=kcadmin
      - POSTGRES_PASSWORD=kcpassword
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

volumes:
  keycloak_db_data:
```

```shell
#keycloak-dev.env
KC_DB=postgres
KC_DB_URL_HOST=keycloak-db
KC_DB_URL_PORT=5432
KC_DB_URL_DATABASE=keycloak
KC_DB_USERNAME=kcadmin
KC_DB_PASSWORD=kcpassword
```

### Version

18.0

### Expected behavior

Expected behavior would be that the export happens, a full realm export of MYREALM in /tmp/exports/...

### Actual behavior

After starting the server and configuring the REALM, running with

```
command: --verbose export --realm=MYREALM --users=same_file --dir=/tmp/exports
```

yields the following log:

```
docker compose up --force-recreate keycloak
[+] Running 1/0
 ⠿ Container someapi-keycloak-1  Recreated                                                                                                              0.1s
Attaching to someapi-keycloak-1
someapi-keycloak-1  | 2022-05-02 09:16:31,234 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
someapi-keycloak-1  |  - quarkus.datasource.jdbc.driver is set to 'org.h2.jdbcx.JdbcDataSource' but it is build time fixed to 'org.postgresql.xa.PGXADataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
someapi-keycloak-1  | 2022-05-02 09:16:31,419 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
someapi-keycloak-1  | 2022-05-02 09:16:31,473 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
someapi-keycloak-1  | 2022-05-02 09:16:31,474 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
someapi-keycloak-1  | 	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
someapi-keycloak-1  | 	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
someapi-keycloak-1  | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
someapi-keycloak-1  | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
someapi-keycloak-1  | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
someapi-keycloak-1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
someapi-keycloak-1  | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
someapi-keycloak-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
someapi-keycloak-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
someapi-keycloak-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
someapi-keycloak-1  | 
someapi-keycloak-1  | 2022-05-02 09:16:31,907 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
someapi-keycloak-1  | 2022-05-02 09:16:31,919 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
someapi-keycloak-1  | 2022-05-02 09:16:31,929 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
someapi-keycloak-1  | 2022-05-02 09:16:32,035 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
someapi-keycloak-1  | 2022-05-02 09:16:32,108 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
someapi-keycloak-1  | 2022-05-02 09:16:32,108 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
someapi-keycloak-1  | 2022-05-02 09:16:32,157 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
someapi-keycloak-1  | 2022-05-02 09:16:32,158 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
someapi-keycloak-1  | 2022-05-02 09:16:32,158 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
someapi-keycloak-1  | 2022-05-02 09:16:32,158 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
someapi-keycloak-1  | 2022-05-02 09:16:34,165 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 79cb7b707a10-25245: no members discovered after 2002 ms: creating cluster as coordinator
someapi-keycloak-1  | 2022-05-02 09:16:34,170 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [79cb7b707a10-25245|0] (1) [79cb7b707a10-25245]
someapi-keycloak-1  | 2022-05-02 09:16:34,173 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `79cb7b707a10-25245`, physical addresses are `[172.29.0.4:48193]`
someapi-keycloak-1  | 2022-05-02 09:16:34,499 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 79cb7b707a10-25245, Site name: null
someapi-keycloak-1  | 2022-05-02 09:16:34,505 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
someapi-keycloak-1  | 2022-05-02 09:16:34,523 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
someapi-keycloak-1  | 2022-05-02 09:16:34,660 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
someapi-keycloak-1  | 2022-05-02 09:16:34,660 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Failed to obtain JDBC connection
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.storage.database.jpa.AbstractJpaConnectionProviderFactory.getConnection(AbstractJpaConnectionProviderFactory.java:55)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:134)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.initializeKeycloakSessionFactory(QuarkusKeycloakApplication.java:68)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:49)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
someapi-keycloak-1  | 	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
someapi-keycloak-1  | 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
someapi-keycloak-1  | 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
someapi-keycloak-1  | 	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
someapi-keycloak-1  | 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
someapi-keycloak-1  | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
someapi-keycloak-1  | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
someapi-keycloak-1  | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
someapi-keycloak-1  | 	at io.quarkus.runtime.Application.start(Application.java:101)
someapi-keycloak-1  | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
someapi-keycloak-1  | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:86)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:34)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.cli.command.AbstractExportImportCommand.run(AbstractExportImportCommand.java:61)
someapi-keycloak-1  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
someapi-keycloak-1  | 	at picocli.CommandLine.access$1300(CommandLine.java:145)
someapi-keycloak-1  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
someapi-keycloak-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
someapi-keycloak-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
someapi-keycloak-1  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
someapi-keycloak-1  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
someapi-keycloak-1  | 	at picocli.CommandLine.execute(CommandLine.java:2078)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:88)
someapi-keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:77)
someapi-keycloak-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
someapi-keycloak-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
someapi-keycloak-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
someapi-keycloak-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
someapi-keycloak-1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
someapi-keycloak-1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
someapi-keycloak-1  | Caused by: java.sql.SQLException: No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
someapi-keycloak-1  | 	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
someapi-keycloak-1  | 	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
someapi-keycloak-1  | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
someapi-keycloak-1  | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
someapi-keycloak-1  | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
someapi-keycloak-1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
someapi-keycloak-1  | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
someapi-keycloak-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
someapi-keycloak-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
someapi-keycloak-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
someapi-keycloak-1  | 
someapi-keycloak-1 exited with code 1

```

### How to Reproduce?

1. Create `keycloak-dev.env` and `docker-compose.yml` as in bug description
2. Run the system:
    ```shell
    docker compose up -d\
    ```
3. Log into keycloak and configure an additional realm
4. Switch the command in `docker-compose.yml` to the `export` one 
5. `docker compose up --force-recreate keycloak`

**Comment by DGuhr** [comment]
maybe related to https://github.com/keycloak/keycloak/issues/11767

**Comment by tschaffter** [comment]
I have the same issue (quay.io/keycloak/keycloak:18.0.0)

From #11767:

> meaning that the option KC_DB_URL_HOST has been ignored.

In my case, the environment variable `KC_DB_URL_HOST` is correctly read by the `export` command. The log below shows that KC tries to connect to `jdbc:postgresql://keycloak-db:5432/keycloak` where `keycloak-db` is the value that I gave to `KC_DB_URL_HOST`.

```console
challenge-registry-keycloak     | 2022-05-19 20:59:59,080 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
challenge-registry-keycloak     |       at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
challenge-registry-keycloak     |       at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
challenge-registry-keycloak     |       at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
challenge-registry-keycloak     |       at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
challenge-registry-keycloak     |       at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
challenge-registry-keycloak     |       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
challenge-registry-keycloak     |       at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
challenge-registry-keycloak     |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
challenge-registry-keycloak     |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
challenge-registry-keycloak     |       at java.base/java.lang.Thread.run(Thread.java:829)
challenge-registry-keycloak     | 
challenge-registry-keycloak     | 2022-05-19 20:59:59,558 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
challenge-registry-keycloak     | 2022-05-19 20:59:59,652 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
challenge-registry-keycloak     | 2022-05-19 20:59:59,667 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
challenge-registry-keycloak     | 2022-05-19 20:59:59,674 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
challenge-registry-keycloak     | 2022-05-19 20:59:59,812 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
challenge-registry-keycloak     | 2022-05-19 20:59:59,899 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
challenge-registry-keycloak     | 2022-05-19 20:59:59,900 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
challenge-registry-keycloak     | 2022-05-19 20:59:59,965 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
challenge-registry-keycloak     | 2022-05-19 20:59:59,965 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
challenge-registry-keycloak     | 2022-05-19 20:59:59,965 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
challenge-registry-keycloak     | 2022-05-19 20:59:59,965 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
challenge-registry-keycloak     | 2022-05-19 21:00:01,975 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 74b373dcd5d6-52480: no members discovered after 2002 ms: creating cluster as coordinator
challenge-registry-keycloak     | 2022-05-19 21:00:01,982 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [74b373dcd5d6-52480|0] (1) [74b373dcd5d6-52480]
challenge-registry-keycloak     | 2022-05-19 21:00:01,988 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `74b373dcd5d6-52480`, physical addresses are `[172.24.0.3:59096]`
challenge-registry-keycloak     | 2022-05-19 21:00:02,380 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
challenge-registry-keycloak     | 2022-05-19 21:00:02,547 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
challenge-registry-keycloak     | 2022-05-19 21:00:02,547 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
challenge-registry-keycloak     | 2022-05-19 21:00:02,548 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
challenge-registry-keycloak     | 2022-05-19 21:00:02,548 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
challenge-registry-keycloak exited with code 1
```

The KC command `start-dev` successfully connects to the same URL, `jdbc:postgresql://keycloak-db:5432/keycloak`.

@kiriakos Did you find a workaround to export KC data to files?

**Comment by tschaffter** [comment]
## Solution to export realm and users data to files

A temporary solution is to not us the pg database, instead persist the data that KC saves to `/opt/keycloak/data/h2`.

- Start KC (comment out all the `KC_DB_*` env vars).

```console
services:
  keycloak:
    image: sagebionetworks/challenge-registry-keycloak:latest
    container_name: challenge-registry-keycloak
    # restart: always
    env_file:
      - .env
    volumes:
      - ./imports:/tmp/keycloak/imports
      - ./h2:/opt/keycloak/data/h2
    ports:
      - 8081:8080
    command: >
      start-dev
```

- Login to KC Admin Console, create the realm `test`.
- Stop the stack.
- Update the command in docker-compose.yml:
  ```console
      command: >
        export
        --dir /tmp/keycloak/imports/
  ```

Files generated:

```console
$ ls -al imports/
total 212
drwxr-xr-x 2 vscode docker  4096 May 19 21:37 .
drwxr-xr-x 5 vscode vscode  4096 May 19 21:35 ..
-rw-r--r-- 1 vscode root   72272 May 19 21:37 master-realm.json
-rw-r--r-- 1 vscode root    1221 May 19 21:37 master-users-0.json
-rw-r--r-- 1 vscode root   65008 May 19 21:37 test-realm.json
```
