### ISSUE TITLE
Keycloak quarkus container remote debug fails with "java.net.SocketException: Connection reset"

### ISSUE THREAD

**Issue by gunterze** [keycloak/keycloak#11833]
### Describe the bug

```
$ docker run -p8787:8787 --name=keycloak --rm [quay.io/keycloak/keycloak:18.0.0](http://quay.io/keycloak/keycloak:18.0.0) start-dev --debug
Listening for transport dt_socket at address: 8787
...
```
but
```
$ jdb -attach localhost:8787
java.net.SocketException: Connection reset
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
    at jdk.jdi/com.sun.tools.jdi.SocketTransportService.handshake(SocketTransportService.java:136)
    at jdk.jdi/com.sun.tools.jdi.SocketTransportService.attach(SocketTransportService.java:255)
    at jdk.jdi/com.sun.tools.jdi.GenericAttachingConnector.attach(GenericAttachingConnector.java:119)
    at jdk.jdi/com.sun.tools.jdi.SocketAttachingConnector.attach(SocketAttachingConnector.java:83)
    at jdk.jdi/com.sun.tools.example.debug.tty.VMConnection.attachTarget(VMConnection.java:519)
    at jdk.jdi/com.sun.tools.example.debug.tty.VMConnection.open(VMConnection.java:328)
    at jdk.jdi/com.sun.tools.example.debug.tty.Env.init(Env.java:63)
    at jdk.jdi/com.sun.tools.example.debug.tty.TTY.main(TTY.java:1095)

Fatal error:
Unable to attach to target VM.
```

### Version

18.0.0

### Expected behavior

```
$ jdb -attach localhost:8787
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
Initializing jdb ...
> 
```

### Actual behavior

see describtion

### How to Reproduce?

see describtion

### Anything else?

Starting Keycloak 18.0.0 outside a docker container by `bib/kc.sh start-dev --debug`, jdb can attach to the VM.

**Comment by gunterze** [comment]
Caused by binding on 127.0.0.1. Workaround: `-e DEBUG_PORT='*:8787'`

**Comment by andreaTP** [comment]
Hi @gunterze , thanks a lot for reaching out!
Since we have a viable workaround I would close this issue; we do consider opening the debug port in the Docker container as a niche use case but we would be happy to re-consider this point if we receive more requests in this direction.
