### ISSUE TITLE
Getting "Unknown option: 'start'" when trying to run custom keycloak image in k8s via keycloak operator

### ISSUE THREAD

**Issue by gohanbg** [keycloak/keycloak#11840]
### Describe the bug

I'm creating a keycloak image like this:
```
FROM openjdk:18.0.1-jdk-slim AS BUILD_IMAGE
ENV APP_HOME=/root/dev/myapp/
RUN mkdir -p $APP_HOME/src/main/java
WORKDIR $APP_HOME
COPY build.gradle gradlew gradlew.bat $APP_HOME
COPY gradle $APP_HOME/gradle
COPY . .
RUN ./gradlew build

FROM quay.io/keycloak/keycloak:18.0.0 as BUILD_KEYCLOAK
# Copy my spi jar
COPY --from=BUILD_IMAGE /root/dev/myapp/build/libs/my-spi-jar* /opt/keycloak/providers/
# copy metrics spi
COPY keycloak-metrics-spi-* /opt/keycloak/providers/
# Install custom theme
COPY my-custom-theme /opt/keycloak/themes/my-custom-theme
RUN /opt/keycloak/bin/kc.sh build


FROM quay.io/keycloak/keycloak:18.0.0
COPY --from=BUILD_KEYCLOAK /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

USER 1000

EXPOSE 8080
EXPOSE 8443
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

Then I try to create Keycloak CR like this:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  image: "my-docker-repo:v1.2.3.4"
  hostname: my-hostname
  unsupported:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: docker-registry-secret
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url-host
      value: postgres-service-url
    - name: db-username
      value: keycloak
    - name: db-password
      secret:
        name: auth-postgresql
        key: postgresql-password
  tlsSecret: auth-tls
```

In k8s there is a tls secret named **auth-tls** and I have a running postgres instance with the password stored in **auth-postgresql**

The keycloak pod is constantly restarting and when i try to see the logs I see:
```
Unknown option: 'start'
Try 'kc.sh start --help' for more information on the available options.
```

If I try to run the same image via docker, it is fine. The following command results in:
```
docker run -e KC_DB=postgres -e KC_DB_URL_HOST=localhost -e KC_DB_USERNAME=user -e KC_DB_PASSWORD=pass -e KC_DB_PASSWORD=aaaa -e KC_HOSTNAME=localhost my-docker-repo:v1.2.3.4
```
The following log. There are some errors, but that's fine, I dont have db on localhost.
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/keycloak/lib/lib/main/org.jboss.slf4j.slf4j-jboss-logmanager-1.1.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/keycloak/lib/../providers/my-spi-jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Slf4jLoggerFactory]
2022-05-04 21:39:17,866 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.jdbc.driver is set to 'org.h2.jdbcx.JdbcDataSource' but it is build time fixed to 'org.postgresql.xa.PGXADataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
2022-05-04 21:39:18,193 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: localhost, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-05-04 21:39:18,273 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://localhost:5432/keycloak
2022-05-04 21:39:18,274 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/keycloak
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-05-04 21:39:18,936 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-04 21:39:18,956 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-04 21:39:18,969 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-04 21:39:19,132 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-04 21:39:19,222 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-05-04 21:39:19,222 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-05-04 21:39:19,297 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-05-04 21:39:19,297 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-05-04 21:39:19,297 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-05-04 21:39:19,298 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-05-04 21:39:21,309 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 9e2cd320fd5f-25981: no members discovered after 2002 ms: creating cluster as coordinator
2022-05-04 21:39:21,337 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [9e2cd320fd5f-25981|0] (1) [9e2cd320fd5f-25981]
2022-05-04 21:39:21,346 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `9e2cd320fd5f-25981`, physical addresses are `[172.17.0.2:57471]`
2022-05-04 21:39:21,757 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-05-04 21:39:21,907 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-05-04 21:39:21,908 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
2022-05-04 21:39:21,908 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

It looks like I'm misconfiguring something, but can't figure out what, especially with the error unknown option start.

Logs in the keycloak operator look like this(no errors or anything strange):
```
2022-05-04 21:36:27,670 INFO  [org.key.ope.v2a.KeycloakController] (EventHandler-keycloakcontroller) --- Reconciling Keycloak: example-kc in namespace: auth
2022-05-04 21:36:27,679 INFO  [org.key.ope.v2a.KeycloakDeployment] (EventHandler-keycloakcontroller) Trying to fetch existing Deployment from the API
2022-05-04 21:36:27,693 INFO  [org.key.ope.v2a.KeycloakDeployment] (EventHandler-keycloakcontroller) Found config secrets names: [auth-postgresql]
2022-05-04 21:36:27,712 INFO  [org.key.ope.v2a.KeycloakDeployment] (EventHandler-keycloakcontroller) Existing Deployment found, updating specs
2022-05-04 21:36:28,017 INFO  [org.key.ope.v2a.KeycloakController] (EventHandler-keycloakcontroller) --- Reconciliation finished successfully
```

### Version

18.0.0

### Expected behavior

Keycloak pod should be starting

### Actual behavior

The keycloak pod is constantly restarting and when i try to see the logs I see:
```
Unknown option: 'start'
Try 'kc.sh start --help' for more information on the available options.
```

**Comment by andreaTP** [comment]
Hi @gohanbg , thanks a lot for reaching out and testing the new operator in preview!

I can notice a couple of misconfigurations in your setup:
 - the custom image entrypoint should not contain the `start` sub-command to work out of the box with the operator (I already submitted a PR to reflect this in the docs)
 - in the multistage Docker file at the line `RUN /opt/keycloak/bin/kc.sh build` you either need to pass all of the desired ["build-time configurations"](https://www.keycloak.org/server/all-config?f=build) as command-line options or make them available as environment variables, [here](https://github.com/keycloak/keycloak/blob/eab2dff979d1b84a3de2e27837105b75d77701ef/operator/scripts/Dockerfile-custom-image#L5) you have a bare minimal example
 
 Please try out those suggestions and let us know if you have any additional issues!

**Comment by andreaTP** [comment]
The issue got automatically closed by the merged PR, @gohanbg feel free to re-open or get back here!

**Comment by gohanbg** [comment]
Thank you for the help @andreaTP. After applying the suggested changes it started working as expected :)

**Comment by andreaTP** [comment]
@gohanbg thanks for getting back! Glad you got it sorted out! 🙂
