### ISSUE TITLE
Realm import not working keycloak 18.0.0 - ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Script upload is disabled

### ISSUE THREAD

**Issue by mcsage** [keycloak/keycloak#11942]
### Describe the bug

I created a realm with client, role, role-mappings, users ... on  a new quay.io/keycloak/keycloak:18.0.0 keycloak instance

```
bash-4.4$ /opt/keycloak/bin/kc.sh --verbose show-config
Current Mode: development
Runtime Configuration:
        kc.cache =  local (PersistedConfigSource)
        kc.config.args =  --verbose;;show-config (SysPropConfigSource)
        kc.db =  dev-file (PersistedConfigSource)
        kc.features =  admin2,account2,scripts (PersistedConfigSource)
        kc.health-enabled =  false (PersistedConfigSource)
        kc.home.dir =  /opt/keycloak/bin/../ (SysPropConfigSource)
        kc.http-enabled =  false (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-18.0.0.jar!/META-INF/keycloak.conf])
        kc.http-relative-path =  auth (PersistedConfigSource)
        kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-18.0.0.jar!/META-INF/keycloak.conf])
        kc.log-file =  /opt/keycloak/bin/../data/log/keycloak.log (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-18.0.0.jar!/META-INF/keycloak.conf])
        kc.metrics-enabled =  false (PersistedConfigSource)
        kc.profile =  dev (PersistedConfigSource)
        kc.quarkus-properties-enabled =  false (PersistedConfigSource)
        kc.show.config =  none (SysPropConfigSource)
        kc.version =  18.0.0 (SysPropConfigSource)
```
Then I export the realm on the same instance
```

bash-4.4$ /opt/keycloak/bin/kc.sh export --dir /tmp/export/ --realm default --users realm_file
2022-05-11 12:28:27,351 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: admin2
2022-05-11 12:28:27,352 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: scripts
2022-05-11 12:28:27,405 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: 8,080, Proxied: false
2022-05-11 12:28:27,801 INFO  [org.infinispan.server.core.transport.EPollAvailable] (keycloak-cache-init) ISPN005028: Native Epoll transport not available, using NIO instead: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
2022-05-11 12:28:27,829 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-11 12:28:27,902 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-11 12:28:27,921 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-11 12:28:28,050 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Exporting into directory /tmp/export
2022-05-11 12:28:28,066 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-11 12:28:28,317 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_606485, Site name: null
2022-05-11 12:28:28,550 INFO  [org.keycloak.services] (main) KC-SERVICES0034: Export of realm 'default' requested.
2022-05-11 12:28:29,939 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Realm 'default' - data exported
2022-05-11 12:28:29,944 INFO  [org.keycloak.services] (main) KC-SERVICES0035: Export finished successfully
2022-05-11 12:28:29,978 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
2022-05-11 12:28:30,208 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-05-11 12:28:30,208 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2022-05-11 12:28:30,208 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: io.quarkus.runtime.QuarkusBindException
2022-05-11 12:28:30,209 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

And re-importing fails afterwards:

```
bash-4.4$ /opt/keycloak/bin/kc.sh --verbose import --file /tmp/export/default-realm.json      
2022-05-11 12:29:02,666 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: admin2
2022-05-11 12:29:02,667 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: scripts
2022-05-11 12:29:02,711 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: 8,080, Proxied: false
2022-05-11 12:29:03,030 INFO  [org.infinispan.server.core.transport.EPollAvailable] (keycloak-cache-init) ISPN005028: Native Epoll transport not available, using NIO instead: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
2022-05-11 12:29:03,116 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-05-11 12:29:03,124 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-05-11 12:29:03,133 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-05-11 12:29:03,208 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-05-11 12:29:03,390 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_989780, Site name: null
2022-05-11 12:29:03,838 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: OVERWRITE_EXISTING
2022-05-11 12:29:03,838 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /tmp/export/default-realm.json
2022-05-11 12:29:03,925 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'default' already exists. Removing it before import
2022-05-11 12:29:10,919 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-05-11 12:29:10,919 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Script upload is disabled
        at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.throwCanNotUpdatePolicy(JSPolicyProviderFactory.java:130)
        at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.onImport(JSPolicyProviderFactory.java:72)
        at org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2483)
        at org.keycloak.models.utils.RepresentationToModel.importPolicies(RepresentationToModel.java:2407)
        at org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:2353)
        at org.keycloak.models.utils.RepresentationToModel.importAuthorizationSettings(RepresentationToModel.java:2300)
        at org.keycloak.models.utils.RepresentationToModel.lambda$importRealmAuthorizationSettings$9(RepresentationToModel.java:2278)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.keycloak.models.utils.RepresentationToModel.importRealmAuthorizationSettings(RepresentationToModel.java:2276)
        at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:431)
        at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:557)
        at org.keycloak.exportimport.util.ImportUtils.importRealm(ImportUtils.java:110)
        at org.keycloak.exportimport.util.ImportUtils.importRealms(ImportUtils.java:65)
        at org.keycloak.exportimport.singlefile.SingleFileImportProvider$1.runExportImportTask(SingleFileImportProvider.java:62)
        at org.keycloak.exportimport.util.ExportImportSessionTask.run(ExportImportSessionTask.java:35)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:242)
        at org.keycloak.exportimport.singlefile.SingleFileImportProvider.importModel(SingleFileImportProvider.java:58)
        at org.keycloak.exportimport.ExportImportManager.runImport(ExportImportManager.java:87)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.createMasterRealm(QuarkusJpaConnectionProviderFactory.java:298)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.initSchema(QuarkusJpaConnectionProviderFactory.java:244)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:242)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:157)
        at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.initializeKeycloakSessionFactory(QuarkusKeycloakApplication.java:68)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:49)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:86)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:34)
        at org.keycloak.quarkus.runtime.cli.command.AbstractExportImportCommand.run(AbstractExportImportCommand.java:61)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:88)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:77)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

SideNote: I can import this exported realm on a keycloak 16.0.0 legacy instance with `-Dkeycloak.profile.feature.upload_scripts=enabled` set

### Version

18.0.0

### Expected behavior

Import works

**Comment by mcsage** [comment]
I found this section twice in my exported realm. After I removed them I was able to import the realm with keycloak 18.0.0
```
      "policies" : [ {
        "id" : "8fca7e38-0fa5-401a-8a53-caceab4e8827",
        "name" : "Default Policy",
        "description" : "A policy that grants access only for users within this realm",
        "type" : "js",
        "logic" : "POSITIVE",
        "decisionStrategy" : "AFFIRMATIVE",
        "config" : {
          "code" : "// by default, grants any permission associated with this policy\n$evaluation.grant();\n"
        }
      }, {
        "id" : "f20c019f-626d-49ab-8cfb-b798b8696545",
        "name" : "Default Permission",
        "description" : "A permission that applies to the default resource type",
        "type" : "resource",
        "logic" : "POSITIVE",
        "decisionStrategy" : "UNANIMOUS",
        "config" : {
          "defaultResourceType" : "urn:cxc-batches:resources:default",
          "applyPolicies" : "[\"Default Policy\"]"
        }
      } ],
```
Might be related to 

https://github.com/keycloak/keycloak/blob/aa6a131b73d55eec64cd9e4ade7f52e0c42d8e6f/services/src/main/java/org/keycloak/authorization/admin/ResourceServerService.java#L209

https://github.com/keycloak/keycloak/blob/45b203d74c267de60706d8dbfee0ef06a6e37336/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js/JSPolicyProviderFactory.java#L130

**Comment by mcsage** [comment]
Found the fix here https://github.com/keycloak/keycloak/issues/11664 

Cleaned up my clients, now the import works

**Comment by kennymac** [comment]
Is this an export bug?  v19.0.1 is exporting config that can't be round-tripped without manual intervention :)
