### ISSUE TITLE
Tests using auth-server-remote are failing with Quarkus dist

### ISSUE THREAD

**Issue by nehachopra27** [keycloak/keycloak#11956]
### Describe the bug

On running the testsuite with auth-server-remote profile, base_tests_remote are failing. 

### Version

18.0.0

### Expected behavior

Tests should pass successfully.

### Actual behavior

Tests are failing.
Stack trace:
`2022-05-11 13:00:19  08:00:14,105 INFO  [org.keycloak.testsuite.arquillian.AuthServerTestEnricher] ************************auth-server-remote*****************************************************************************
2022-05-11 13:00:19  May 11, 2022 8:00:16 AM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
2022-05-11 13:00:19  WARNING: Failed downloading org/jboss/jboss-parent/36/jboss-parent-36.pom from https://origin-repository.jboss.org/nexus/content/groups/ea/. Reason: 
2022-05-11 13:00:19  org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jboss:jboss-parent:pom:36 in fuse-dev (https://origin-repository.jboss.org/nexus/content/groups/ea/)
2022-05-11 13:00:19  08:00:17,401 INFO  [org.jboss.remoting] JBoss Remoting version 5.0.24.Final
2022-05-11 13:00:19  08:00:17,452 INFO  [org.wildfly.security] ELY00001: WildFly Elytron version 1.18.3.Final
2022-05-11 13:00:19  08:00:17,965 ERROR [org.keycloak.testsuite.account.AccountBrokerTest] [AccountBrokerTest] null() FAILED
2022-05-11 13:00:19  [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.927 s <<< FAILURE! - in org.keycloak.testsuite.account.AccountBrokerTest
2022-05-11 13:00:19  [ERROR] org.keycloak.testsuite.account.AccountBrokerTest  Time elapsed: 5.872 s  <<< ERROR!
2022-05-11 13:00:19  org.jboss.arquillian.container.spi.client.container.DeploymentException: Cannot deploy: testsuiteProviders.jar
2022-05-11 13:00:19  	at org.jboss.as.arquillian.container.ArchiveDeployer.createException(ArchiveDeployer.java:214)
2022-05-11 13:00:19  	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:179)
2022-05-11 13:00:19  	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:162)
2022-05-11 13:00:19  	at org.jboss.as.arquillian.container.ArchiveDeployer.deploy(ArchiveDeployer.java:91)
2022-05-11 13:00:19  	at org.jboss.as.arquillian.container.CommonDeployableContainer.deploy(CommonDeployableContainer.java:255)
2022-05-11 13:00:19  	at org.keycloak.testsuite.arquillian.AuthServerTestEnricher.deployProviders(AuthServerTestEnricher.java:427)
2022-05-11 13:00:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-05-11 13:00:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-05-11 13:00:19  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-05-11 13:00:19  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-05-11 13:00:19  	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
2022-05-11 13:00:19  	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
2022-05-11 13:00:19  	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
2022-05-11 13:00:19  	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
2022-05-11 13:00:19  	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
2022-05-11 13:00:19  	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
2022-05-11 13:00:19  	at org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:186)

### How to Reproduce?

Execute the base_remote_tests for a Quarkus dist

### Anything else?

During migration to Quarkus, custom providers need to be loaded differently and support for  jboss-deployment-structure.xml has ended
auth-server-remote is using the deprectaed approach for deploying custom providers (AuthServerTestEnricher.deployProviders())

 .addAsManifestResource("jboss-deployment-structure.xml");

**Comment by nehachopra27** [comment]
Will no longer be an issue if https://github.com/keycloak/keycloak/pull/14321 is merged

**Comment by shawkins** [comment]
Out of date.
