### ISSUE TITLE
Token endpoint: HTTP POST without form data and missing Content-Type leads to NPE and HTTP 500 response

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak#11971]
### Describe the bug

Doing a faulty POST Request on Token endpoint `/realms/{realm-name}/protocol/openid-connect/token`
here without form data and missing Content-Type leads to NullPointerException and HTTP 500 API response `{"error":"unknown_error"}`

For sure this is an usage error, but in other error case keycloak gives back clear error indication:
* Form data given, but Content-Type is missing: `{"error":"RESTEASY003065: Cannot consume content type"}`
* Form data missing, but Content-Type is given: `{"error":"invalid_request","error_description":"Missing form parameter: grant_type"}`

NullPointerException stacktrace for Form data and Content-Type missing:
```
2022-05-13 09:45:39,096 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser:177] [executor-thread-94] Recalculated absoluteURI to https://my-kc-server/auth/realms/master/protocol/openid-connect
/token
2022-05-13 09:45:39,097 ERROR [org.keycloak.services.error.KeycloakErrorHandler:67] [executor-thread-94] Uncaught server error: java.lang.NullPointerException
        at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:53)
        at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
        at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
        at com.sun.proxy.$Proxy45.getDecodedFormParameters(Unknown Source)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:169)
        at jdk.internal.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Version

18.0.0 (Quarkus)

### Expected behavior

No HTTP 500 and no NPE, but a HTTP 400 response with better error indication.

**Comment by mposolda** [comment]
@psytester Thanks for reporting this. I am adding label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to contribute the PR with fixing this (after it is investigated and confirmed that this is valid issue).

This is probably not hard to fix and it can be interesting for someone, who wants to learn OIDC basics. So I am adding also label "good first issue" .

**Comment by kisaga** [comment]
Hello keycloak people,

I've tried to reproduce this issue and I was able to.
I've done some analysis on the root cause but I am not sure how you want this to be fixed.

The exception (only in quarkus) is happening when [this line](https://github.com/keycloak/keycloak/blob/86883fd68a75a7b4590b47c0ad6bba7a7625877a/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L169) is executed. As we can see from the stack trace:
### Quarkus
```
2022-06-07 19:48:29,728 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: java.lang.NullPointerException
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:53)
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
	at com.sun.proxy.$Proxy45.getDecodedFormParameters(Unknown Source)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:169)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` 
The implementation of `getDecodedFormParameters()` that is chosen is from the one from the abstract class  [BaseHttpRequest](https://github.com/resteasy/resteasy/blob/cb3ee69a2a9da2e129845f3f37c497ba5ecf73da/resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/BaseHttpRequest.java#L71) which is calling the `getFormParameters()` and due to the missing headers the `mt` variable is null.

### Non-Quarkus
I've added some logs to check which implementation of `getDecodedFormParameters()` is chosen for non-quarkus and after an analysis I found that it is calling [this method](https://github.com/resteasy/resteasy/blob/cb3ee69a2a9da2e129845f3f37c497ba5ecf73da/resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletInputMessage.java#L147) from HttpServletInputMessage class. I've added some logging in the method to verify that my assumption is correct. 
```
22:58:54,709 INFO  [stdout] (default task-1) java.lang.Thread# getStackTrace: 1602
22:58:54,709 INFO  [stdout] (default task-1) org.jboss.resteasy.plugins.server.servlet.HttpServletInputMessage# getDecodedFormParameters: 152
22:58:54,709 INFO  [stdout] (default task-1) jdk.internal.reflect.NativeMethodAccessorImpl# invoke0: -2
22:58:54,709 INFO  [stdout] (default task-1) jdk.internal.reflect.NativeMethodAccessorImpl# invoke: 62
22:58:54,709 INFO  [stdout] (default task-1) jdk.internal.reflect.DelegatingMethodAccessorImpl# invoke: 43
22:58:54,709 INFO  [stdout] (default task-1) java.lang.reflect.Method# invoke: 566
22:58:54,709 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy# invoke: 169
22:58:54,709 INFO  [stdout] (default task-1) com.sun.proxy.$Proxy109# getDecodedFormParameters: -1
22:58:54,710 INFO  [stdout] (default task-1) org.keycloak.protocol.oidc.endpoints.TokenEndpoint# processGrantRequest: 169
22:58:54,710 INFO  [stdout] (default task-1) jdk.internal.reflect.NativeMethodAccessorImpl# invoke0: -2
22:58:54,710 INFO  [stdout] (default task-1) jdk.internal.reflect.NativeMethodAccessorImpl# invoke: 62
22:58:54,710 INFO  [stdout] (default task-1) jdk.internal.reflect.DelegatingMethodAccessorImpl# invoke: 43
22:58:54,710 INFO  [stdout] (default task-1) java.lang.reflect.Method# invoke: 566
22:58:54,710 INFO  [stdout] (default task-1) org.jboss.resteasy.core.MethodInjectorImpl# invoke: 170
22:58:54,710 INFO  [stdout] (default task-1) org.jboss.resteasy.core.MethodInjectorImpl# invoke: 130
22:58:54,710 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceMethodInvoker# internalInvokeOnTarget: 660
22:58:54,711 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceMethodInvoker# invokeOnTargetAfterFilter: 524
22:58:54,711 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceMethodInvoker# lambda$invokeOnTarget$2: 474
22:58:54,711 INFO  [stdout] (default task-1) org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext# filter: 364
22:58:54,711 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceMethodInvoker# invokeOnTarget: 476
22:58:54,711 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceMethodInvoker# invoke: 434
22:58:54,711 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceLocatorInvoker# invokeOnTargetObject: 192
22:58:54,711 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceLocatorInvoker# invoke: 152
22:58:54,712 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceLocatorInvoker# invokeOnTargetObject: 183
22:58:54,712 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceLocatorInvoker# invoke: 141
22:58:54,712 INFO  [stdout] (default task-1) org.jboss.resteasy.core.ResourceLocatorInvoker# invoke: 32
22:58:54,712 INFO  [stdout] (default task-1) org.jboss.resteasy.core.SynchronousDispatcher# invoke: 492
22:58:54,712 INFO  [stdout] (default task-1) org.jboss.resteasy.core.SynchronousDispatcher# lambda$invoke$4: 261
22:58:54,712 INFO  [stdout] (default task-1) org.jboss.resteasy.core.SynchronousDispatcher# lambda$preprocess$0: 161
22:58:54,712 INFO  [stdout] (default task-1) org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext# filter: 364
22:58:54,713 INFO  [stdout] (default task-1) org.jboss.resteasy.core.SynchronousDispatcher# preprocess: 164
22:58:54,713 INFO  [stdout] (default task-1) org.jboss.resteasy.core.SynchronousDispatcher# invoke: 247
22:58:54,713 INFO  [stdout] (default task-1) org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher# service: 249
22:58:54,713 INFO  [stdout] (default task-1) org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher# service: 60
22:58:54,713 INFO  [stdout] (default task-1) org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher# service: 55
22:58:54,713 INFO  [stdout] (default task-1) javax.servlet.http.HttpServlet# service: 590
22:58:54,713 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletHandler# handleRequest: 74
22:58:54,713 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.FilterHandler$FilterChainImpl# doFilter: 129
22:58:54,714 INFO  [stdout] (default task-1) org.keycloak.provider.wildfly.WildFlyRequestFilter# lambda$doFilter$0: 41
22:58:54,714 INFO  [stdout] (default task-1) org.keycloak.services.filters.AbstractRequestFilter# filter: 43
22:58:54,714 INFO  [stdout] (default task-1) org.keycloak.provider.wildfly.WildFlyRequestFilter# doFilter: 39
22:58:54,714 INFO  [stdout] (default task-1) io.undertow.servlet.core.ManagedFilter# doFilter: 61
22:58:54,714 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.FilterHandler$FilterChainImpl# doFilter: 131
22:58:54,714 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.FilterHandler# handleRequest: 84
22:58:54,714 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.security.ServletSecurityRoleHandler# handleRequest: 62
22:58:54,714 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletChain$1# handleRequest: 68
22:58:54,714 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletDispatchingHandler# handleRequest: 36
22:58:54,715 INFO  [stdout] (default task-1) org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler# lambda$handleRequest$1: 68
22:58:54,715 INFO  [stdout] (default task-1) org.wildfly.security.auth.server.FlexibleIdentityAssociation# runAsFunctionEx: 103
22:58:54,715 INFO  [stdout] (default task-1) org.wildfly.security.auth.server.Scoped# runAsFunctionEx: 161
22:58:54,715 INFO  [stdout] (default task-1) org.wildfly.security.auth.server.Scoped# runAs: 73
22:58:54,715 INFO  [stdout] (default task-1) org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler# handleRequest: 67
22:58:54,715 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.RedirectDirHandler# handleRequest: 68
22:58:54,715 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.security.SSLInformationAssociationHandler# handleRequest: 117
22:58:54,715 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler# handleRequest: 57
22:58:54,716 INFO  [stdout] (default task-1) io.undertow.server.handlers.PredicateHandler# handleRequest: 43
22:58:54,716 INFO  [stdout] (default task-1) io.undertow.security.handlers.AbstractConfidentialityHandler# handleRequest: 46
22:58:54,716 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler# handleRequest: 64
22:58:54,716 INFO  [stdout] (default task-1) io.undertow.security.handlers.AbstractSecurityContextAssociationHandler# handleRequest: 43
22:58:54,716 INFO  [stdout] (default task-1) org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler# handleRequest: 38
22:58:54,716 INFO  [stdout] (default task-1) io.undertow.server.handlers.PredicateHandler# handleRequest: 43
22:58:54,716 INFO  [stdout] (default task-1) org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler# handleRequest: 61
22:58:54,716 INFO  [stdout] (default task-1) io.undertow.server.handlers.PredicateHandler# handleRequest: 43
22:58:54,717 INFO  [stdout] (default task-1) org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler# handleRequest: 68
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.SendErrorPageHandler# handleRequest: 52
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.server.handlers.PredicateHandler# handleRequest: 43
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletInitialHandler# handleFirstRequest: 275
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletInitialHandler# access$100: 79
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletInitialHandler$2# call: 134
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletInitialHandler$2# call: 131
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1# call: 48
22:58:54,717 INFO  [stdout] (default task-1) io.undertow.servlet.core.ContextClassLoaderSetupAction$1# call: 43
22:58:54,718 INFO  [stdout] (default task-1) org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction# lambda$create$0: 1544
22:58:54,718 INFO  [stdout] (default task-1) org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction# lambda$create$0: 1544
22:58:54,718 INFO  [stdout] (default task-1) org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction# lambda$create$0: 1544
22:58:54,718 INFO  [stdout] (default task-1) org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction# lambda$create$0: 1544
22:58:54,718 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletInitialHandler# dispatchRequest: 255
22:58:54,718 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletInitialHandler# access$000: 79
22:58:54,718 INFO  [stdout] (default task-1) io.undertow.servlet.handlers.ServletInitialHandler$1# handleRequest: 100
22:58:54,718 INFO  [stdout] (default task-1) io.undertow.server.Connectors# executeRootHandler: 387
22:58:54,718 INFO  [stdout] (default task-1) io.undertow.server.HttpServerExchange$1# run: 852
22:58:54,719 INFO  [stdout] (default task-1) org.jboss.threads.ContextClassLoaderSavingRunnable# run: 35
22:58:54,719 INFO  [stdout] (default task-1) org.jboss.threads.EnhancedQueueExecutor# safeRun: 1990
22:58:54,719 INFO  [stdout] (default task-1) org.jboss.threads.EnhancedQueueExecutor$ThreadBody# doRunTask: 1486
22:58:54,719 INFO  [stdout] (default task-1) org.jboss.threads.EnhancedQueueExecutor$ThreadBody# run: 1348
22:58:54,719 INFO  [stdout] (default task-1) org.xnio.XnioWorker$WorkerThreadFactory$1$1# run: 1282
```

### Conclusion
The solution for this problem could be:

- Change [getFormParameters()](https://github.com/resteasy/resteasy/blob/cb3ee69a2a9da2e129845f3f37c497ba5ecf73da/resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/BaseHttpRequest.java#L44) to return the `formParameters` if the `mt` is null. An issue should be opened in RestEasy project and a bump the resteasy version in keycloak-quarkus.
- Further investigate the injection of [request in the TokenEndpoint](https://github.com/keycloak/keycloak/blob/86883fd68a75a7b4590b47c0ad6bba7a7625877a/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L137) and its type and why the getFormParameters method is invoked from the abstract BaseHttpRequest class and not from the concrete one HttpServletInputMessage. I think that this i the best solution but I just started getting familiar with quarkus, its dependency injection and how the methods are invoked for Context annotated fields.


Can you please let me know how you want this to be resolved ? 
If you prefer the second solution can you please provide some guidance on what may be causing the incorrect invocation of the method ?

**Comment by pedroigor** [comment]
@kisaga  @agaman We can fix this by changing this method https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/HttpRequestImpl.java#L58.

Similar to how we do [here](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/HttpRequestImpl.java#L70) we can check if media type is set, if not return an empty map.

**Comment by mghalbi** [comment]
**[Check Content-Type header in the request HttpRequestImpl]((https://github.com/keycloak/keycloak/pull/17274))**
