### ISSUE TITLE
Problem while using Unsupported without spec->containers section

### ISSUE THREAD

**Issue by tramiaczek** [keycloak/keycloak#12120]
### Describe the bug

I have a problem that the Keycloak Operator does not create service and ingress in case when I use the following section in my deployment file:

```
unsupported:
   podTemplate:
      spec:
         imagePullSecrets:
            - name: "{{ .Values.image.imagePullSecretName }}"
```

I must have unsupported section as I need to use custom image from Docker registry with authorized access and it is so far the only way to get the image.

Almost all object were created apart from Service and Ingress and the logs indicate the following:
```
2022-05-19 12:52:10,016 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (EventHandler-keycloakcontroller) Error during event processing ExecutionScope{ resource id: CustomResourceID{name='cop-keycloak-external', namespace='cop-dev'}, version: 10222458} failed.: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:459)
at org.keycloak.operator.v2alpha1.KeycloakDeployment.validatePodTemplate(KeycloakDeployment.java:137)
```

The line suggest that the code expect to have at least one container object on the list when using unsupported section.
When I comment out 'unsupported' part the deployment (with service and ingress) succeeded

### Version

18.0

### Expected behavior

The service and ingress should be created even if I do not specify containters section under unsupported section.

### Actual behavior

Service and Ingress are not created by Keycloak Operator when unsupported section is used.

### How to Reproduce?

Just try to get the Keycloak custom image from registry with authorized access (where secret is required) or try to set something in podTemplate -> spec section without adding containers section.

**Comment by vmuzikar** [comment]
@tramiaczek Thank you for reporting this! This is actually already fixed: https://github.com/keycloak/keycloak/pull/11864.
