### ISSUE TITLE
com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.1 Authentication required 

### ISSUE THREAD

**Issue by jaysnm** [keycloak/keycloak#12175]
### Describe the bug

Hello there

I have configured keycloak 18.0.0 with email settings appropriately feed into realm settings. "Test Connection" works and I get test email on my box. However, when I perform an action that triggers email sending (say creating account with `verify email` enabled), the email is note sent. Instead I get

```
2022-05-24 21:39:45,334 ERROR [org.keycloak.authentication.requiredactions.VerifyEmail] (executor-thread-3) Failed to send verification email: org.keycloak.email.EmailException: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.1 Authentication required

	at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:153)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:264)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:259)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:250)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:207)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendVerifyEmail(FreeMarkerEmailTemplateProvider.java:181)
	at org.keycloak.authentication.requiredactions.VerifyEmail.sendVerifyEmail(VerifyEmail.java:160)
	at org.keycloak.authentication.requiredactions.VerifyEmail.requiredActionChallenge(VerifyEmail.java:81)
	at org.keycloak.services.managers.AuthenticationManager.executeAction(AuthenticationManager.java:1327)

```

After inspecting the logs further, I found out that `useAuth` is flagged `false` when sending verification email. Please note that when configuring email settings I have `Authentication` enabled with username and password correctly defined.

Traceback on `Test Connection` (email is sent as expected)

```
[javax.mail] (executor-thread-3) getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
2022-05-24 21:29:59,338 FINE  [com.sun.mail.smtp] (executor-thread-3) useEhlo true, useAuth true
2022-05-24 21:29:59,339 FINE  [com.sun.mail.smtp] (executor-thread-3) trying to connect to host "smtp.example.com", port 587, isSSL false
2022-05-24 21:29:59,341 FINE  [com.sun.mail.smtp] (executor-thread-3) connected to host "smtp.example.com", port: 587
......
2022-05-24 21:29:59,351 FINE  [com.sun.mail.smtp] (executor-thread-3) Found extension "DSN", arg ""
2022-05-24 21:29:59,351 FINE  [com.sun.mail.smtp] (executor-thread-3) Found extension "AUTH", arg "PLAIN LOGIN"
2022-05-24 21:29:59,351 FINE  [com.sun.mail.smtp] (executor-thread-3) protocolConnect login, host=smtp.example.com, user=sender@example.com, password=<non-null>
2022-05-24 21:29:59,352 FINE  [com.sun.mail.smtp] (executor-thread-3) Attempt to authenticate using mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM XOAUTH2 
2022-05-24 21:29:59,352 FINE  [com.sun.mail.smtp] (executor-thread-3) Using mechanism LOGIN
2022-05-24 21:29:59,376 FINE  [com.sun.mail.smtp] (executor-thread-3) use8bit false
2022-05-24 21:29:59,518 FINE  [com.sun.mail.smtp] (executor-thread-3) Verified Addresses
2022-05-24 21:29:59,518 FINE  [com.sun.mail.smtp] (executor-thread-3)  receiver@example.com
2022-05-24 21:29:59,544 FINE  [javax.activation] (executor-thread-3) MailcapCommandMap: createDataContentHandler for multipart/alternative
2022-05-24 21:29:59,544 FINE  [javax.activation] (executor-thread-3)   search DB #1
2022-05-24 21:29:59,544 FINE  [javax.activation] (executor-thread-3)   search DB #2
2022-05-24 21:29:59,544 FINE  [javax.activation] (executor-thread-3)   search fallback DB #1
2022-05-24 21:29:59,544 FINE  [javax.activation] (executor-thread-3)     got content-handler
2022-05-24 21:29:59,544 FINE  [javax.activation] (executor-thread-3)       class com.sun.mail.handlers.multipart_mixed
2022-05-24 21:29:59,565 FINE  [com.sun.mail.smtp] (executor-thread-3) message successfully delivered to mail server
```

Traceback on `Verify Email`

```
2022-05-24 21:39:45,311 FINE  [javax.mail] (executor-thread-3) getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
2022-05-24 21:39:45,314 FINE  [com.sun.mail.smtp] (executor-thread-3) useEhlo true, useAuth false
2022-05-24 21:39:45,314 FINE  [com.sun.mail.smtp] (executor-thread-3) trying to connect to host "smtp.example.com", port 587, isSSL false
2022-05-24 21:39:45,316 FINE  [com.sun.mail.smtp] (executor-thread-3) connected to host "smtp.example.com", port: 587
....
2022-05-24 21:39:45,330 FINE  [com.sun.mail.smtp] (executor-thread-3) Found extension "AUTH", arg "PLAIN LOGIN"
2022-05-24 21:39:45,331 FINE  [com.sun.mail.smtp] (executor-thread-3) use8bit false
2022-05-24 21:39:45,331 FINE  [com.sun.mail.smtp] (executor-thread-3) got response code 530, with response: 530 5.7.1 Authentication required

2022-05-24 21:39:45,332 FINE  [com.sun.mail.smtp] (executor-thread-3) MessagingException while sending: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.1 Authentication required
```

### Version

18.0.0

### How to Reproduce?

- Run keycloak
- Create a realm
- Configure email server using realm settings
- Send test message using `Test Connection` button. Should work!
- Under Realm Settings > Login > Email settings, turn `verify email` radio on.
- Under Realm > Clients, follow `account-console` client home link to create a new account under the newly created realm
- Wait for the email, inspect logs

**Comment by rmartinc** [comment]
Hi!

I have followed your reproducer steps and I have received the email in keycloak 18 quarkus distribution (using a smtp in my same box):

```
2022-05-25 10:44:27,636 FINE  [com.sun.mail.smtp] (executor-thread-25) useEhlo true, useAuth true
2022-05-25 10:44:27,636 FINE  [com.sun.mail.smtp] (executor-thread-25) trying to connect to host "localhost", port 25, isSSL false
2022-05-25 10:44:27,636 FINER [com.sun.mail.util.socket] (executor-thread-25) getSocket, host localhost, port 25, prefix mail.smtp, useSSL false
2022-05-25 10:44:27,636 FINEST [com.sun.mail.util.socket] (executor-thread-25) create socket: prefix mail.smtp, localaddr null, localport 0, host localhost, port 25, connection timeout 10000, timeout 10000, socket factory null, useSSL false
2022-05-25 10:44:27,637 FINEST [com.sun.mail.util.socket] (executor-thread-25) set socket read timeout 10000
2022-05-25 10:44:27,637 FINEST [com.sun.mail.util.socket] (executor-thread-25) connecting...
2022-05-25 10:44:27,637 FINEST [com.sun.mail.util.socket] (executor-thread-25) success!
2022-05-25 10:44:27,639 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 220 hulk JAMES SMTP Server Server (JAMES SMTP Server ) ready
2022-05-25 10:44:27,639 FINE  [com.sun.mail.smtp] (executor-thread-25) connected to host "localhost", port: 25
2022-05-25 10:44:27,639 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) EHLO localhost
2022-05-25 10:44:27,640 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 250-hulk Hello localhost [127.0.0.1])
2022-05-25 10:44:27,640 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 250-PIPELINING
2022-05-25 10:44:27,640 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 250-ENHANCEDSTATUSCODES
2022-05-25 10:44:27,640 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 250 8BITMIME
2022-05-25 10:44:27,640 FINE  [com.sun.mail.smtp] (executor-thread-25) Found extension "PIPELINING", arg ""
2022-05-25 10:44:27,640 FINE  [com.sun.mail.smtp] (executor-thread-25) Found extension "ENHANCEDSTATUSCODES", arg ""
2022-05-25 10:44:27,640 FINE  [com.sun.mail.smtp] (executor-thread-25) Found extension "8BITMIME", arg ""
2022-05-25 10:44:27,641 FINE  [com.sun.mail.smtp] (executor-thread-25) use8bit false
2022-05-25 10:44:27,641 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) MAIL FROM:<keycloak@localhost>
2022-05-25 10:44:27,642 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 250 2.1.0 Sender <keycloak@localhost> OK
2022-05-25 10:44:27,642 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) RCPT TO:<ricky@localhost>
2022-05-25 10:44:27,647 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 250 2.1.5 Recipient <ricky@localhost> OK
2022-05-25 10:44:27,648 FINE  [com.sun.mail.smtp] (executor-thread-25) Verified Addresses
2022-05-25 10:44:27,648 FINE  [com.sun.mail.smtp] (executor-thread-25)   ricky@localhost
2022-05-25 10:44:27,648 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) DATA
2022-05-25 10:44:27,649 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 354 Ok Send data ending with <CRLF>.<CRLF>
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) Date: Wed, 25 May 2022 10:44:27 +0200 (CEST)
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) From: keycloak <keycloak@localhost>
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) Reply-To: keycloak <keycloak@localhost>
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) To: ricky@localhost
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) Message-ID: <534374692.5.1653468267636@localhost>
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) Subject: Verify email
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) MIME-Version: 1.0
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) Content-Type: multipart/alternative; 
2022-05-25 10:44:27,650 FINEST [com.sun.mail.smtp.protocol] (executor-thread-25) 	boundary="----=_Part_4_1201863332.1653468267635"
...
```

The code sends the login if `auth` is set to `true` in the destination user realm, this [code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java#L78). Take care if you are using admin from master to configure, the email tab should be configured in the user realm, in my case `test`. Please check you have it to true in your setup:

```
./kcadm.sh get realms/test
...
  "smtpServer" : {
    "password" : "**********",
    "starttls" : "",
    "auth" : "true",
    "port" : "25",
    "host" : "localhost",
    "from" : "keycloak@localhost",
    "fromDisplayName" : "keycloak",
    "ssl" : "",
    "user" : "keycloak@localhost"
  },
...
```

**Comment by jaysnm** [comment]
Hello @rmartinc  and thank you for finding time to review this

Following your guidance, I have been able to establish that the issue is on quay.io/keycloak/keycloak:18.0.0 docker image and not on [release archive](https://github.com/keycloak/keycloak/releases/download/18.0.0/keycloak-18.0.0.tar.gz). Below is output of `kcadm` command.

```
./kcadm.sh get realms/sandbox
......
"smtpServer" : {
    "replyToDisplayName" : "Reply To",
    "starttls" : "true",
    "envelopeFrom" : "",
    "ssl" : "false",
    "password" : "**********",
    "port" : "587",
    "replyTo" : "reply@example.com",
    "host" : "smtp.example.com",
    "from" : "no-reply@example.com",
    "fromDisplayName" : "From Name",
    "user" : "sender@example.com",
    "authentication" : "true"
  },
....
```

Apparently the [code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java#L78) is looking for `auth` from config parameters, but the parameter seems to have been renamed to `authentication` thus defaults to `false`.

I'm curious to know on what you mean with 
> Take care if you are using admin from master to configure

(because I am using master realm to manage other realms)

**Comment by rmartinc** [comment]
Hi @jaysnm !

Then it's clear that the error is in the UI and not in the keycloack server. As your output shows the UI is setting `authentication` while the correct parameter is `auth`. That's why it was not checked when you changed to the old UI (it was really not set). I filed https://github.com/keycloak/keycloak-admin-ui/issues/2701 for the UI issue.

@vmuzikar This is not a keycloak server issue, it's in the new keycloak.v2 admin UI. The config parameter was different. Please close it here and @jaysnm you can continue monitoring the new UI issue.

**Comment by jaysnm** [comment]
Thanks!
