### ISSUE TITLE
Saml Audience Restriction problem: Audience expects URL, fails when its not an url (eg. has illegal chars like whitespace)

### ISSUE THREAD

**Issue by npongracic** [keycloak/keycloak#12234]
### Describe the bug

I'm trying to implement identity federation with the Croatian National Identification and Authentication System (NIAS).
NIAS is using SAML 2.0 and is issuing client application certificates and using the Subject part of the certificate as the Service Provider Entity ID. This ultimately becomes the Audience and is in the following format: CN=someAppName, L=ZAGREB, OID.2.5.4.97=HR06149366560, O=FINA, C=HR.

As you can see, this string has whitespaces and perhaps some other URI illegal characters.
Everything goes well but when the iDP returns SAMLResponse, Keycloak fails to parse the response:
WARN  [org.keycloak.events] (executor-thread-211) type=IDENTITY_PROVIDER_RESPONSE_ERROR, realmId=myRealm, clientId=null, userId=null, ipAddress=172.17.0.1, error=invalid_saml_response, reason=invalid_saml_document
2022-05-27 23:18:02,624 ERROR [org.keycloak.saml.common] (executor-thread-210) Error in base64 decoding saml message.: java.lang.IllegalArgumentException: Illegal character in path at index 18: CN=someAppName, L=ZAGREB, OID.2.5.4.97=HR06149366560, O=FINA, C=HR
        at java.base/java.net.URI.create(URI.java:883)
        at org.keycloak.saml.processing.core.parsers.saml.assertion.SAMLAudienceRestrictionParser.processSubElement(SAMLAudienceRestrictionParser.java:54) 

I've traced the issue to SAMLAudienceRestrictionParser URI create call, i think this fix was introduced in this issue:
https://lists.jboss.org/pipermail/keycloak-dev/2018-August/011084.html

### Version

18.0.0

### Expected behavior

Dont force URI.create on the Audience tag, it's usually an url but it doesnt have to be.
I suggest to remove this URI.create call in SAMLAudienceRestrictionParser.processSubElement

### Actual behavior

Fails when the SAMLResponse Audience tag is not a valid URL.

**Comment by npongracic** [comment]
I’ll try to reason with them but this is a goverment institution and this
system is already in production for quite some time so i dont see that
happening. Is there an option to skip audience validation at least?

Also, every article i’ve read on this topic says that there is no strict
restriction of this Audience param to have to be URI, its only recommended
but it can technically be any string thats up to 1024 characters long so i
hope you’ll reconsider.

Also, how can i enter the Entity ID as non URI? If its gonna end up as the
audience, shouldnt it be restricted then to the URI format?

**Comment by hmlnarik** [comment]
> [...] Is there an option to skip audience validation at least?

Not at this moment, and since this would divert from strict SAML 2.0 spec, such an option would need to be backed by another SAML spec update / extension. If there is any, then it would open door for submitting a RFE, and then to updating the code.

----

I appreciate the point about governmental institution. For the sake of argument, perhaps also reusable elsewhere, let me quote the relevant part from the SAML spec:

> `<Audience>`
> A URI reference that identifies an intended audience. The URI reference MAY identify a document
that describes the terms and conditions of audience membership. It MAY also contain the unique
identifier URI from a SAML name identifier that describes a system entity (see Section 8.3.6).

Reading the first sentence, is there a room for interpreting this as non-URI?

I also have checked the updated https://docs.oasis-open.org/security/saml/v2.0/errata05/os/saml-v2.0-errata05-os.pdf, yet it does not seem to soften the `Audience` contents restriction.

----

> Also, how can i enter the Entity ID as non URI? If its gonna end up as the audience, shouldnt it be restricted then to the URI format?

There is a mapper in Keycloak for setting the audience which does not set the entity ID to audience if it is not an URI. Issuer name may be though an arbitrary string (saml-core spec, Section 2.2.2). Should the entity ID be used in the audience, it has to be an URI though.

**Comment by npongracic** [comment]
Sorry for troubling you, I know this issue is closed but i kinda missed your answer here: 

> There is a mapper in Keycloak for setting the audience which does not set the entity ID to audience if it is not an URI. Issuer name may be though an arbitrary string (saml-core spec, Section 2.2.2). Should the entity ID be used in the audience, it has to be an URI though.

Can you point me how to enable this? If I'm understanding correctly, because my Entity ID is not an URI, it shouldn't get mapped to the Audience field but it does, that's why Keycloak reports the response as invalid_saml_response. How can I configure this mapper in Keycloak so that my non-URI Entity ID doesn't get mapped to Audience?

Thank you!

**Comment by bmauser** [comment]
Hi @npongracic I have the same issue with Keycloak and NIAS, have you found any solution? I would be grateful if you could share it.

**Comment by npongracic** [comment]
Hello,
Unfortunately not, we ended up moving away from Keycloak and using a custom
solution.
You could make your own fork of Keycloak and fix this but i wouldnt
recommend it.

Kind regards,
Nebojša
