### ISSUE TITLE
Partial import does not import all the configuration

### ISSUE THREAD

**Issue by tarek-fourati** [keycloak/keycloak#12256]
### Describe the bug

Partial import does not import all the configuration as expected.

### Version

16.1.1

### Expected behavior

Partial import should work the  same way as   creating a realm from a file. It should apply all the configuration.

### Actual behavior

*  creating a realm from a file imports all the configuration.
*  creating an enabled realm and then importing the configuration from a file does update  clients and roles but  not the  provider keys as an exemple 

### How to Reproduce?

From a fresh keycloak installation, I've created a test realm and disabled  the "rsa-enc-generated" key . then i  exported it with groups, roles and clients. Export is in [test-export.txt](https://github.com/keycloak/keycloak/files/8798709/test-export.txt)

From a fresh keycloak installation, if we click add realm  and import the file we will have  the desired setup. But if we create an enabled realm and then open the partial import menu and import our file we won't have the key disabled.
here are the export file for both configurations
partial import : [test-creation-import-export.txt](https://github.com/keycloak/keycloak/files/8798750/test-creation-import-export.txt)
created with a file : [test-partial-import-export.txt](https://github.com/keycloak/keycloak/files/8798751/test-partial-import-export.txt)
 as you can see the "rsa-enc-generated" is enabled in the partial import configuration and disabled  as wanted in the created with a file configuration

**Comment by reppners** [comment]
Noticed that import also is not able to ingest ClientScopes and ClientScopeMappings that are exported. One would expected that everything that is exported with the partial export can also be imported with the partial import but that seems not to be the case.

**Comment by bpasson** [comment]
Any update on this?

**Comment by vramik** [comment]
Hello @tarek-fourati, thank you for reporting the issue. There are following resource types supported by partial import feature. https://github.com/keycloak/keycloak/blob/adeef6c2a0f7aa9e3f744bb9f3db98065d1bffab/services/src/main/java/org/keycloak/partialimport/ResourceType.java#L26

It seems to me more like feature request than bug, therefore I'm removing `kind/bug` label.

**Comment by ab-zackdemarco** [comment]
Could I make the case that if your import model accepts the "optional" property for things like "authenticationFlows" or any other property that is not in the ones you listed above, then its either a combination of bad documentation and/or misleading implementation as properties outside of the ones you specified should either warn the user that they are not going to be processed or throw a validation error? The other option would be to alter the partial import to essentially be a realm update to match the expected payload you specify in your api documentation?

**Comment by Akhilesh170194** [comment]
I am encountering an issue when attempting to partially import groups into Keycloak using the CLI. The roles import works as expected, however, I face a problem specifically with groups. Below is the command I used to import the file:

```shell
./kcadm.sh create partialImport -r ream_name -s ifResourceExists=OVERWRITE -o -f ../data/v1_1__keycloak-realm.json
``` 

Here is the JSON configuration I'm using for the import:

```
{
  "roles": {
    "realm": [
      {
        "name": "new_role_1",
        "description": "Description of new role 1",
        "composite": false,
        "clientRole": false
      },
      {
        "name": "new_role_2",
        "description": "Description of new role 2",
        "composite": false,
        "clientRole": false
      }
    ],
    "client": {
      "account": [
        {
          "name": "new_account_role_1",
          "description": "Description of new account role 1",
          "composite": false,
          "clientRole": true
        }
      ]
    }
  },
  "groups": [
    {
      "name": "HardblockGT Editor - Duplicate",
      "path": "/hardblock-gt-editor-duplicate",
      "subGroups": [],
      "attributes": {},
      "realmRoles": [
        "nforce-hbgt-edit"
      ],
      "clientRoles": {}
    }
  ],
  "policy": "OVERWRITE"
}
``` 

there is no problem with importing roles but when I try to import groups in, I get the following exception in the Keycloak Server log. 

```java
2024-05-14 10:55:11,709 ERROR [org.keycloak.services] (executor-thread-21) KC-SERVICES0037: Error creating new_group_1: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.GroupModel.getId()" because the return value of "org.keycloak.partialimport.GroupsPartialImport.findGroupModel(org.keycloak.models.KeycloakSession, org.keycloak.models.RealmModel, org.keycloak.representations.idm.GroupRepresentation)" is null
        at org.keycloak.partialimport.GroupsPartialImport.getModelId(GroupsPartialImport.java:53)
        at org.keycloak.partialimport.GroupsPartialImport.getModelId(GroupsPartialImport.java:35)
        at org.keycloak.partialimport.AbstractPartialImport.doImport(AbstractPartialImport.java:120)
        at org.keycloak.partialimport.PartialImportManager.saveResources(PartialImportManager.java:63)
        at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:59)
        at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
        at org.keycloak.storage.PartialImportRealmFromRepresentationEvent.fire(PartialImportRealmFromRepresentationEvent.java:53)
        at org.keycloak.storage.datastore.DefaultExportImportManager.partialImportRealm(DefaultExportImportManager.java:472)
        at org.keycloak.services.resources.admin.RealmAdminResource.getPartialImportResults(RealmAdminResource.java:1122)
        at org.keycloak.services.resources.admin.RealmAdminResource.lambda$partialImport$5(RealmAdminResource.java:1108)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:379)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:362)
        at org.keycloak.services.resources.admin.RealmAdminResource.partialImport(RealmAdminResource.java:1104)
        at org.keycloak.services.resources.admin.RealmAdminResource$quarkusrestinvoker$partialImport_ce9ad25ac2f46e088795dffac3bb2c388f1871d9.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
``` 
This error suggests there may be an issue with finding or creating the group model. I am wondering if there might be any required properties for groups that I am missing in my JSON configuration, or if this is an issue within Keycloak itself.

Could someone please offer any insights or guidance on how to resolve this error? Any help would be greatly appreciated as I am keen to ensure a smooth import process.

Keycloak Version: 24.0.1
Java Version: 17

**Comment by Akhilesh170194** [comment]
I found the issue. It was a configuration mistake on my part. One of the groups was missing the path property, which caused this issue. Thank you for the support!
