### ISSUE TITLE
JPA Map Storage: Keycloak fails to start on CockroachDB

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#12340]
### Describe the bug

When any storage is configured to use the Map JPA provider, Keycloak with CockroachDB fails to start due to lack of support for computed columns in foreign keys, which are present in the authorization changesets:

```
Exception in thread "main" java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication()
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:164)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2835)
...

Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/authz/permission/jpa-authz-permission-changelog-1.xml::authz-permission-1::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: unimplemented: computed column "resourceserverid" cannot reference a foreign key
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/46672/v21.2 [Failed SQL: (0) ALTER TABLE public.kc_authz_permission ADD CONSTRAINT authz_permission_fk_root_fkey FOREIGN KEY (resourceserverid) REFERENCES public.kc_authz_resource_server (id) ON DELETE CASCADE]

```

We might have to move all the foreign key constraints in the authz changelogs that reference a computed column to a changeset that runs only for PostgreSQL.

### Version

main

### Expected behavior

Keycloak should be able to process all new storage changelogs when CockroachDB is used.

### Actual behavior

Keycloak fails to start if any area is configured to use the new Map JPA store (which in Cockroach's case leads to all changelogs being processed)

**Comment by vramik** [comment]
> We might have to move all the foreign key constraints in the authz changelogs that reference a computed column to a changeset that runs only for PostgreSQL.

It might be slightly trickier as the constraint us used for cascade deletion: `ON DELETE CASCADE`. How the deletion would be done without the constraint?

**Comment by vramik** [comment]
There is omitted constraint within [model/map-jpa/src/main/resources/META-INF/authz/policy/jpa-authz-policy-changelog-1.xml](https://github.com/keycloak/keycloak/blob/be28e866b9bdfac39cae13d06a010994a1e058a7/model/map-jpa/src/main/resources/META-INF/authz/policy/jpa-authz-policy-changelog-1.xml#L122) with deferrable and initiallyDeferred

**Comment by ahus1** [comment]
I'll give this issue a go and see what's necessary to change for CockroachDB.
