### ISSUE TITLE
RPInitiatedLogoutTest failing with 401 Unauthorised error

### ISSUE THREAD

**Issue by nehachopra27** [keycloak/keycloak#12341]
### Describe the bug

RPInitiatedLogoutTest.logoutWithValidIdTokenWhenLoggedOutByAdmin() Fails when run with Quarkus dist

### Version

18.0.0

### Expected behavior

```
Error Message
HTTP 401 Unauthorized
Stacktrace
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:243)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:217)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy98.logoutAll(Unknown Source)
	at org.keycloak.testsuite.oauth.RPInitiatedLogoutTest.logoutWithValidIdTokenWhenLoggedOutByAdmin(RPInitiatedLogoutTest.java:348)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.jboss.arquillian.junit.Arquillian$8$1.invokeMethod(Arquillian.java:325)
	at org.jboss.arquillian.junit.MethodInvoker$1.invoke(MethodInvoker.java:18)
	at 
```

### Actual behavior

Test should pass succesfully

### How to Reproduce?

Run jvm_tests with QuarkusBuild branch in the pipeline  (rhel7 with mw_oraclejdk11)

**Comment by mabartos** [comment]
The test doesn't fail anymore.
