### ISSUE TITLE
cannot run nightly image on new operator: cannot connect to database

### ISSUE THREAD

**Issue by ibotty** [keycloak/keycloak#12374]
### Describe the bug

Due to some bugs in the released `18.0.0` regarding the port settings I want to run a newer image.

Unfortunately it does not work.  Note, that the 18.0.0-Image does connect to the database and works fine (apart from the wrong port).

The basic `keycloak` CRD:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: auth
spec:
  hostname: keycloak-auth.apps.cluster.schaeffer-ag.de
  instances: 2
  serverConfiguration:
  - name: db
    value: postgres
  - name: db-url-host
    value: keycloak-db
  - name: db-username
    secret:
      key: username
      name: keycloak-owner-user.keycloak-db.credentials.postgresql.acid.zalan.do
  - name: db-password
    secret:
      key: password
      name: keycloak-owner-user.keycloak-db.credentials.postgresql.acid.zalan.do
  tlsSecret: keycloak-auth-tls
```

### Version

nightly

### Actual behavior

```
2022-06-07 11:39:38,816 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.jdbc.driver is set to 'org.h2.jdbcx.JdbcDataSource' but it is build time fixed to 'org.postgresql.xa.PGXADataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
 - quarkus.datasource.health.enabled is set to 'false' but it is build time fixed to 'true'. Did you change the property quarkus.datasource.health.enabled after building the application?
2022-06-07 11:39:39,058 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <redacted>, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-06-07 11:39:39,160 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
2022-06-07 11:39:39,161 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
        at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
        at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-06-07 11:39:39,646 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://keycloak-db:5432/keycloak
```

### How to Reproduce?

Set `spec.image=quay.io/keycloak/keycloak:nightly` in the `keycloak` crd.

**Comment by andreaTP** [comment]
Hi @ibotty and thanks for submitting this issue!

We are actually testing in CI for every PR that the current container image of keycloak doesn't break the operator (and it's functionalities).

Although looking at your logs, I do see a couple of warnings that might be relevant:
```
 - quarkus.datasource.jdbc.driver is set to 'org.h2.jdbcx.JdbcDataSource' but it is build time fixed to 'org.postgresql.xa.PGXADataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
 - quarkus.datasource.health.enabled is set to 'false' but it is build time fixed to 'true'. Did you change the property quarkus.datasource.health.enabled after building the application?
```

I have a few questions:
- are you building a custom image out of the nightly?
- can you provide the full logs of a pod failing (e.g. from the very start and not just the Exception)?
- can you provide the entire `serverConfiguration` you are passing (just the keys is completely fine)?
- are you providing any additional settings to `spec.unsupported.podTemplate`?
- can you please provide the `db` in `serverConfiguration`:
https://github.com/keycloak/keycloak/blob/6ca658839142479c15cea778a524b569fe6006a3/operator/app/src/main/resources/example-keycloak.yaml#L8-L9
and let us know what's the result?

as a side note, I doubt, but this "might" be related to #12401 cc. @pedroigor

**Comment by ibotty** [comment]
Just quickly.  I have set `[name: db, value: postgres]`.  See above.  I also did not set anything else than above.  Only some annotations and the `status` are missing from the config above.

**Comment by ibotty** [comment]
Oh, now the complete log
[keycloak-nightly.log](https://github.com/keycloak/keycloak/files/8863925/keycloak-nightly.log)

**Comment by andreaTP** [comment]
oh, right! 🙂 
Now I see the confusion, the `spec.image` field expects a pre-augmented Keycloak container image, but you are providing the default which is not augmented.

Depending on what you are trying to achieve:
 - build a pre-augmented container image starting from nightly as described here: https://www.keycloak.org/server/containers
 - use the `nightly` operator as well (which uses the keycloak nightly by default [e.g.](https://github.com/keycloak/keycloak-k8s-resources/blob/4392792bb74206b5d1bc4924c9d2f3ba53f08b71/kubernetes/kubernetes.yml#L210-L211)
 - configure a different `default` base image with this env var: https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L206-L207
 
 Let me know if this works for you.

**Comment by ibotty** [comment]
I deployed the operator via OLM, so I cannot run the nightly operator as easily as I want to.

Unfortunately I don't quiet understand option three.  The env var will get overwritten by (I assume) OLM automatically.

That leaves option 1.  I'll see tomorrow whether that's going to work.

But is 18.0.1 going to be released soon, because I'd rather use the defaults.
