### ISSUE TITLE
Admin console inaccessible with keycloak.v2 theme on 18.0.1

### ISSUE THREAD

**Issue by kherock** [keycloak/keycloak#12619]
### Describe the bug

When enabling the `preview` or `admin2` feature on Keycloak, the resource loaders fails to locate the `index.ftl` for the new admin console theme.

### Version

18.0.1

### Expected behavior

The admin console should load!

### Actual behavior

```
2022-06-21 02:31:46,432 INFO  [io.quarkus] (main) Keycloak 18.0.1 on JVM (powered by Quarkus 2.7.5.Final) started in 28.895s. Listening on: http://0.0.0.0:8080
2022-06-21 02:31:46,433 INFO  [io.quarkus] (main) Profile dev activated.
2022-06-21 02:31:46,433 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-06-21 02:31:46,458 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
2022-06-21 02:32:15,005 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
at org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:71)
at org.keycloak.services.resources.admin.AdminConsole.getMainPage(AdminConsole.java:349)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.FreeMarkerUtil$ThemeTemplateLoader@1c52ee35.
at freemarker.template.Configuration.getTemplate(Configuration.java:2883)
at freemarker.template.Configuration.getTemplate(Configuration.java:2703)
at org.keycloak.theme.FreeMarkerUtil.getTemplate(FreeMarkerUtil.java:85)
at org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:64)
... 50 more
```

### How to Reproduce?

Enable the `keycloak.v2` admin theme on the `quay.io/keycloak/keycloak:18.0.1` image.

### Anything else?

This appears to be a regression in 18.0.1. This error is not present on 18.0.0.

**Comment by blairmorris** [comment]
Noticed the same behavior between 18.0.0 and 18.0.1, 
When admin2 feature is enabled on 18.0.1, keycloak will load as before, but when the admin UI is loaded, "Unexpected error" is shown, and the process throws this error:
`ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.`

Reverting to the previous 18.0.0 image, or disabling admin2 resolves this, but 18.0.1 won't load the Admin v2 UI

**Comment by csbrogi** [comment]
also experienced this same behavior with keycloak 22.0.1

**Comment by lizardpie** [comment]
I'm experiencing the very same behavior with Keycloak 21.1.2.

**Comment by demetrius-powers** [comment]
I'm experiencing the very same behavior with Keycloak 22.0.4

**Comment by jonkoops** [comment]
Comments on old issues will likely not be answered, if you are still experiencing issues please report this as a new bug so it can be triaged.

**Comment by bradtm2000** [comment]
I'm running the latest Keycloak docker image with Keycloak v26.3.1 and got this error when I was trying out the different themes and switched the admin theme to "base".  Yes, "base" is in the list.    This caused the `Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl` error above, which locked me out of the admin login screen.

If you run into this, you can fix it by using `curl` and `jq` to reset the theme to an empty string.  I was on the master realm, so you may need to change the URLs if your realm is different.

```
ACCESS_TOKEN=$(curl -s -X POST \
-d "grant_type=password" \
-d "client_id=admin-cli" \
-d "username=admin" \
-d "password=admin" \
-d "scope=openid" \
http://localhost:8080/realms/master/protocol/openid-connect/token \
| jq -r ".access_token")

echo $ACCESS_TOKEN

curl -s -X PUT \
-H "Authorization: Bearer $ACCESS_TOKEN" \
-H "Content-Type: application/json" \
-d '{"adminTheme":"", "loginTheme":"", "accountTheme":"", "emailTheme":""}' \
http://localhost:8080/admin/realms/master
```

**Comment by HagerError404** [comment]
Can confirm the problem in keycloak version 26.1.5.

**Comment by v-kamerdinerov** [comment]
Issue still persist in KK 26.3.4 :( 

I set Admin console theme to base and...

<img width="621" height="377" alt="Image" src="https://github.com/user-attachments/assets/f9daafcd-764c-4d70-bee0-13be84c82e53" />

```
2025-10-14 13:50:54,392 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-117) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
```

**Comment by jonkoops** [comment]
Please file a new issue if you can reproduce this, and provide steps to reproduce it from the latest version of Keycloak, and a fresh install.

**Comment by v-kamerdinerov** [comment]
> Please file a new issue if you can reproduce this, and provide steps to reproduce it from the latest version of Keycloak, and a fresh install.

There is already an open issue - https://github.com/keycloak/keycloak/issues/41924

Can you raise her priority?

**Comment by jonkoops** [comment]
I am no longer a maintainer, so I cannot. But I am sure the team will prioritize the issue.

**Comment by gaffarmalik** [comment]
> I'm running the latest Keycloak docker image with Keycloak v26.3.1 and got this error when I was trying out the different themes and switched the admin theme to "base". Yes, "base" is in the list. This caused the `Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl` error above, which locked me out of the admin login screen.
> 
> If you run into this, you can fix it by using `curl` and `jq` to reset the theme to an empty string. I was on the master realm, so you may need to change the URLs if your realm is different.
> 
> ```
> ACCESS_TOKEN=$(curl -s -X POST \
> -d "grant_type=password" \
> -d "client_id=admin-cli" \
> -d "username=admin" \
> -d "password=admin" \
> -d "scope=openid" \
> http://localhost:8080/realms/master/protocol/openid-connect/token \
> | jq -r ".access_token")
> 
> echo $ACCESS_TOKEN
> 
> curl -s -X PUT \
> -H "Authorization: Bearer $ACCESS_TOKEN" \
> -H "Content-Type: application/json" \
> -d '{"adminTheme":"", "loginTheme":"", "accountTheme":"", "emailTheme":""}' \
> http://localhost:8080/admin/realms/master
> ```

Just some slight addition to the above sample. If you've disabled public client, you would need to include the `client_secret` inorder to gain access to the admin-cli.

``` bash
 ACCESS_TOKEN=$(curl -s -X POST \
-d "grant_type=password" \
-d "client_id=admin-cli" \
-d "username=admin" \
-d "password=admin" \
-d "client_secret=abcdefghijklmnopqrstuvwxyz" \
-d "scope=openid" \
http://127.0.0.1:8080/realms/master/protocol/openid-connect/token \
| jq -r ".access_token")

```
