### ISSUE TITLE
Possible NullPointerException during OpenID Connect logout with disabled client

### ISSUE THREAD

**Issue by quatauta** [keycloak/keycloak#12624]
### Describe the bug

During migration from Keycloak 9.0.3 to 18.0.0 (Quarkus), we noticed a `NullPointerException` during OpenID Connect logout.

Some of our internal applications still use the legacy logout parameter `redirect_uri`. Based on https://www.keycloak.org/2022/04/keycloak-1800-released#_openid_connect_logout, we start Keycloak 18.0.0 with parameter `spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true`: `bin/kc.[sh|bat] --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start`

### Version

18.0.0

### Actual behavior

* `NullPointerException` after confirmation of Keycloak OpenID Connect logout

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-97) Uncaught server error: java.lang.NullPointerException
        at org.keycloak.services.resources.SessionCodeChecks.initialVerify(SessionCodeChecks.java:228)
        at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logoutConfirmAction(LogoutEndpoint.java:262)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

* Open OpenID Connect logout URL with parameter `redirect_url`
* Keycloak shows logout confirm dialog
* Confirm logout

### Anything else?

* https://www.keycloak.org/2022/04/keycloak-1800-released#_openid_connect_logout

**Comment by mposolda** [comment]
@quatauta Thanks for the report. I am adding this to Keycloak 19 for now, but we can further postpone if there is no time to fix this in time.

From the stacktrace, it appears that some of your clients is disabled.

**Possible Alternative steps to reproduce (without migration):**
- Login with some client "foo"
- Disable client "foo"
- Send the logout request without `id_token_hint` but with `client_id=foo`.
 
IMO The logout should be permitted even if client is disabled. Hence the expected behaviour would be IMO to logout the user instead of sending NPE.

**Implementation note: ** It seems that we may possibly refactor `SessionCodeChecks` and `LogoutSessionCodeChecks` and add some more into that, so that during logout there is not verification of disabled client.

**Comment by quatauta** [comment]
@mposolda Thank you so much for your feedback! 😃 

For your information only, #12622 should fix the NullPointerException (without refactoring, but only checks for `null`).

**Comment by dsteegen** [comment]
We are facing the same issue after upgrading our redhat-sso to version 7.6 which uses Keycloak 18 underneath.
The only workaround there is for now is to enable the client for which the issue occurs. However, in our case it was disabled for a good reason.
Adding the id_token_hint will also fix that but since there are 3rd party vendors interfacing with us that currently do not provide that parameter in the logout URL so they will face the NPE error on the confirmation screen.

**Comment by mposolda** [comment]
NOTE: It is also needed to test this with disabled `account` client and doublecheck that NPE is not there and logout is fine.
