### ISSUE TITLE
Creating user with non-existent groups using API returns internal server error

### ISSUE THREAD

**Issue by sirkrypt0** [keycloak/keycloak#12640]
### Describe the bug

Creating a user via the REST API with a non-existent group in the `groups` parameter results in an internal server error with `{"error":"unknown_error"}` as the HTTP response.

As the admin console generally only allows selecting existing groups, this issue does not impact normal use of the admin console. However, it may appear when using the admin REST API.

### Version

18.0.1

### Expected behavior

A proper error such as `Bad Request` or `Not Found` with a descriptive error message is returned and no error visible in the Keycloak logs.

### Actual behavior

`{"error":"unknown_error"}` with return code `500 Internal Server Error` is returned, and the following stack trace printed in the Keycloak log:

```java
2022-06-21 23:18:29,984 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-106) Uncaught server error: java.lang.RuntimeException: Unable to find group specified by path: /non-existent-group
        at org.keycloak.models.utils.RepresentationToModel.createGroups(RepresentationToModel.java:1900)
        at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:161)
        at jdk.internal.reflect.GeneratedMethodAccessor495.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

1. Configure a client to be able to create new users, e.g. using the `admin-cli` client in the `master` realm and assigning it the `admin` role.
1. Get an access token for that client.
1. Request the Admin REST API to create a new user. In the JSON, specify a non-existent group in the `groups` field.
1. Find the unexpected response and see the stack trace in the Keycloak logs.

The following Bash script also simulates this behavior (it requires `jq` to run):

```bash
#!/bin/bash

# base address
KC_BASE="http://localhost:8080/auth"
# client realm
KC_CLIENT_REALM="master"
# client id of resource client
KC_CLIENT="admin-cli"
# client secret of resource client
KC_SECRET="secret"
# realm to create user in
KC_REALM="master"

resp=$(curl -s -X POST "$KC_BASE/realms/$KC_CLIENT_REALM/protocol/openid-connect/token" \
 -H "Content-Type: application/x-www-form-urlencoded" \
 -d "grant_type=client_credentials" \
 -d "client_id=$KC_CLIENT" -d "client_secret=$KC_SECRET")
clientToken=$(echo $resp | jq -r .access_token)

# Create user
resp=$(curl -s -X POST "$KC_BASE/admin/realms/$KC_REALM/users" \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer $clientToken" \
 --data "{\"username\": \"demo.user\",\"groups\": [\"/non-existent-group\"]}"
)
echo "Response: $resp"
```

Which returns: `Response: {"error":"unknown_error"}` for me and prints the stack trace.

**Comment by pedroigor** [comment]
We should handle it properly on the `UsersResource#createUser` so that we return a more appropriate status code.

**Comment by diegoot-dev** [comment]
Any news? the issue still present in version 21.1.1
