### ISSUE TITLE
LDAP not accessible results in failed logins, even in unsynced edit mode

### ISSUE THREAD

**Issue by dfs-** [keycloak/keycloak#12831]
### Describe the bug

When using an active directory as User federation provider it requires to be accessible all the time. This is even with its edit mode set to READ_ONLY or UNSYNCED.

> READ_ONLY is a read-only LDAP store. WRITABLE means data will be synced back to LDAP on demand. UNSYNCED means user data will be imported, but not synced back to LDAP.

In my particular case the name of the AD server was changed which was automatically propagated to the hosts, but obviously not to the Keycloak configuration.

### Version

18.0.2

### Expected behavior

Active Directory user federation should allow for logons in Keycloak even when the active directory server presented in connectionUrl is not available, at least in UNSYNCED and maybe in READ_ONLY edit mode.

### Actual behavior

Logon currently fails with an error message ("Identity Provider failed")-

### How to Reproduce?

1. configure LDAP/AD user federation using editMode = UNSYNCED
2. import users
3. confirm login with AD user is possible
4. make AD server configured unavailable (either by turning of the service or any other way)
5. try to login with AD user -> currently not possible

### Anything else?

Log messages written:
```
2022-06-29 16:27:48,207 INFO  [org.keycloak.storage.ldap.LDAPIdentityStoreRegistry] (executor-thread-0) Creating new LDAP Store for the LDAP storage provider: 'MSAD', LDAP Configuration: {fullSyncPeriod=[604800], pagination=[true], connectionPooling=[true], usersDn=[OU=USER,OU=<redacted>,DC=<redacted>,DC=<redacted>], cachePolicy=[DEFAULT], useKerberosForPasswordAuthentication=[false], importEnabled=[true], enabled=[true], changedSyncPeriod=[86400], usernameLDAPAttribute=[sAMAccountName], bindDn=[CN=KEYCLOAK,OU=SPECIALUSER,OU=<redacted>,DC=<redacted>,DC=<redacted>], lastSync=[1656422803], vendor=[ad], uuidLDAPAttribute=[objectGUID], allowKerberosAuthentication=[false], connectionUrl=[ldap://<redacted>:389], syncRegistrations=[false], authType=[simple], debug=[false], searchScope=[2], useTruststoreSpi=[ldapsOnly], priority=[0], trustEmail=[false], userObjectClasses=[user], rdnLDAPAttribute=[cn], editMode=[UNSYNCED], validatePasswordPolicy=[false], batchSizeForSync=[1000]}, binaryAttributes: []
2022-06-29 16:28:09,324 WARN  [org.keycloak.services] (executor-thread-0) KC-SERVICES0013: Failed authentication: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:176)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getFirstResult(LDAPQuery.java:183)
	at org.keycloak.storage.ldap.LDAPStorageProvider.loadLDAPUserByUuid(LDAPStorageProvider.java:832)
	at org.keycloak.storage.ldap.LDAPStorageProvider.loadAndValidateUser(LDAPStorageProvider.java:491)
	at org.keycloak.storage.ldap.LDAPStorageProvider.validate(LDAPStorageProvider.java:166)
	at org.keycloak.storage.UserStorageManager.importValidation(UserStorageManager.java:116)
	at org.keycloak.storage.UserStorageManager.getUserByUsername(UserStorageManager.java:294)
	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByUsername(UserCacheSession.java:259)
	at org.keycloak.models.utils.KeycloakModelUtils.findUserByNameOrEmail(KeycloakModelUtils.java:228)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUserFromForm(AbstractUsernameFormAuthenticator.java:188)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUser(AbstractUsernameFormAuthenticator.java:167)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validateUserAndPassword(AbstractUsernameFormAuthenticator.java:148)
	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.validateForm(UsernamePasswordForm.java:55)
	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.action(UsernamePasswordForm.java:48)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:169)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:990)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:321)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:292)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:276)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:349)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@48a62e63
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:172)
	... 68 more
Caused by: org.keycloak.models.ModelException: Could not query server using DN [OU=USER,OU=NX_BERLIN_SWISSLAB,DC=nexus,DC=int] and filter [(&(objectClass=*)(objectGUID=\d6\39\39\b1\1c\31\34\40\b4\21\67\ab\68\a7\79\f6))]
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.lookupById(LDAPOperationManager.java:442)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:261)
	... 69 more
Caused by: javax.naming.CommunicationException: BE-DC01.nexus.int:389 [Root exception is java.net.ConnectException: Connection timed out: connect]
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapClient.<init>(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapClientFactory.createPooledConnection(Unknown Source)
	at java.naming/com.sun.jndi.ldap.pool.Connections.<init>(Unknown Source)
	at java.naming/com.sun.jndi.ldap.pool.Pool.getPooledConnection(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapPoolManager.getLdapClient(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(Unknown Source)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(Unknown Source)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(Unknown Source)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(Unknown Source)
	at java.naming/javax.naming.InitialContext.init(Unknown Source)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(Unknown Source)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:711)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:706)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.lookupById(LDAPOperationManager.java:410)
	... 70 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Unknown Source)
	... 93 more

2022-06-29 16:28:09,480 WARN  [org.keycloak.events] (executor-thread-0) type=LOGIN_ERROR, realmId=07f0714c-1144-44db-a505-c6cc6a12fb1f, clientId=<redacted>, userId=null, ipAddress=<redacted>, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://<redacted>/<redacted>, code_id=ae8f2500-4395-4e72-a7f4-3e3335d05693, username=<redacted>, authSessionParentId=ae8f2500-4395-4e72-a7f4-3e3335d05693, authSessionTabId=FKqeKC46P00
2022-06-29 16:28:47,375 WARN  [org.keycloak.events] (executor-thread-0) type=LOGIN_ERROR, realmId=07f0714c-1144-44db-a505-c6cc6a12fb1f, clientId=null, userId=null, ipAddress=<redacted>, error=cookie_not_found
```

**Comment by darius-m** [comment]
This may be caused by some information mapper for LDAP / AD entries that are set to always fetch data from the federation provider when a user's data is required.

Please make sure that you did not change the configuration to `Unsynchronized` after configuring the federation provider in a different mode, since mapper configurations are created using the expected access type, and are not changed when the synchronization mechanism changes, as mentioned in the [Administration Guide](https://www.keycloak.org/docs/latest/server_admin/index.html#edit-mode). For example, in `read-only` mode, Keycloak is expected to be able to fetch information from the backend every time, but should not able to write to the backend (e.g. change passwords).

**Comment by darius-m** [comment]
More importantly (I forgot this when I wrote the first answer), I do not believe that it is possible to work with an offline LDAP backend, since passwords are explicitly not saved in the Keycloak database, as mentioned in the [storage mode section](https://www.keycloak.org/docs/latest/server_admin/index.html#storage-mode).

**Comment by dfs-** [comment]
@darius-m thanks for pointing out my misunderstanding.
