### ISSUE TITLE
Cannot login to admin console, missing template error

### ISSUE THREAD

**Issue by nono-lqdn** [keycloak/keycloak#12859]
### Describe the bug

I cannot login to the admin console on a 18.0.2 install of Keycloak. 

The login URL is : https://sso.test.lqdn.fr/auth/admin/master/console/

### Version

18.0.1

### Expected behavior

Logging in to the Admin console working.

### Actual behavior

No login possible, internal server error.

### How to Reproduce?

- Make a clean install of Keycloak 18.0.1 with the following config file ; 
 
 ```
cat conf/keycloak.conf                                                         
# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
db=mariadb

# The username of the database user.
db-username=keycloak

# The password of the database user.
db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
db-url=jdbc:mariadb://localhost/keycloak

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
#hostname=myhostname
hostname-strict=false

# Server on port 8080 at localhost
http-enabled=true
http-host=127.0.0.1
http-port=8080

proxy=edge

features=authorization,account2,account-api,admin-fine-grained-authz,admin2,impersonation,scripts,token-exchange,web-authn,client-policies,ciba,map-storage,par,declarative-user-profile,dynamic-scopes,preview,recovery_codes
features-disabled=docker,openshift-integration

# Keep the same path as before for the proxy settings
http-relative-path=/auth
```

I've imported an existing Master realm from a 15.0.0 installation ; 

```
cat ../keycloak-backup/keycloak-user/master-users-0.json 
{
  "realm" : "master",
  "users" : [ {
    "id" : "59f1fc21-c78d-4c7b-9b38-36e1bff2ffdf",
    "createdTimestamp" : 1621590835020,
    "username" : "admin",
    "enabled" : true,
    "totp" : false,
    "emailVerified" : false,
    "firstName" : "System",
    "lastName" : "Admin",
    "email" : "sysadmin@email.net",
    "attributes" : {
      "locale" : [ "en" ]
    },
    "credentials" : [ {
      "id" : "20c05a5d-8e9b-4cdc-84f3-597cfdd70717",
      "type" : "password",
      "createdDate" : 1621590835157,
      "secretData" : "{\"value\":\"password==\",\"salt\":\"salt==\",\"additionalParameters\":{}}",
      "credentialData" : "{\"hashIterations\":27500,\"algorithm\":\"pbkdf2-sha256\",\"additionalParameters\":{}}"
    } ],
    "disableableCredentialTypes" : [ ],
    "requiredActions" : [ ],
    "realmRoles" : [ "default-roles-master", "admin" ],
    "notBefore" : 0,
    "groups" : [ ]
  } ]
}%                                                                                   
```

I get the following errors ;

```
2022-06-30 18:45:32,653 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
	at org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:71)
	at org.keycloak.services.resources.admin.AdminConsole.getMainPage(AdminConsole.java:349)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.FreeMarkerUtil$ThemeTemplateLoader@64226dec.
	at freemarker.template.Configuration.getTemplate(Configuration.java:2883)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2703)
	at org.keycloak.theme.FreeMarkerUtil.getTemplate(FreeMarkerUtil.java:85)
	at org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:58)
	... 50 more
```

**Comment by mister2d** [comment]
Same here!

**Comment by rmartinc** [comment]
I think this is the issue #12619 that triggered [18.0.2](https://www.keycloak.org/2022/06/keycloak-1802-released). Check with that version.

**Comment by nono-lqdn** [comment]
@rmartinc Seems like switching to 18.0.2 fixed the issue with the server side error. But I still have an issue with an error when trying to login.

I've imported two realms from a previous install, as stated earlier. The import goes well, but when I try to access it's path, be it Master or let's call it Realm2, I get an error page saying " We are sorry... Realm not enabled ". 

![Screenshot 2022-07-01 at 14-43-29 Sign in to master](https://user-images.githubusercontent.com/94455669/176896839-dd02a83f-d93f-487f-b36e-87e3fb5340fc.png)

**Comment by rmartinc** [comment]
@nono-lqdn That's a different issue. But the message is quite direct... Is your realm enabled in Realm Settings -> Enabled?

**Comment by nono-lqdn** [comment]
I cannot login to my Keycloak instance at all, not even the admin realm. Should I maybe try to not important the "Master" Realm, and only the second one ?

**Comment by nono-lqdn** [comment]
I can also open another issue for this altogether and continue the discussion there, so we can close this issue.

**Comment by rmartinc** [comment]
I don't know @nono-lqdn, I just answered the first quation because it is a known issue and the reason to have a 18.0.2 version. In your second question I would not touch the master realm. Just import the other realm. At least you will maintain access to the master realm. Note that importing via console doesn't import everything (passwords for example), if you want a realm export/import is better to use the DB way (https://www.keycloak.org/server/importExport).

**Comment by TrippyHank** [comment]
The first issue mentioned here is still valid in 21.01. 

When starting a build (i.e. using `kc.sh start --optimized`), try to change the admin UI theme to base. It will produce this exact error.

One can gain access back by exporting realms to a file, update the faulty theme (i.e from "base" to "keycloak.v2") to fix the issue and then import the file again.

Attempting to export to or import from a directory (even with the theme fixed) doesn't appear to resolve the issue.
