### ISSUE TITLE
SamlReverseProxyTest shouldn't depend on an external resource

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#12922]
### Describe the bug

The SamlReverseProxyTest will fail when the external service is not available. I also have problems running the test locally, as my local machine doesn't allow external DNS queries to resolve to 127.0.0.1. This is a known problem described in "troubleshooting" here https://nip.io/:

> Some DNS resolvers, forwarders and routers have [DNS rebinding protection](https://en.wikipedia.org/wiki/DNS_rebinding) which may result in failure to resolve local and private IP addresses. This service won't work in those situations.

This attempts to simplify this without the use of an external service.

```
2022-07-05T09:33:52.5802875Z --------- org.keycloak.testsuite.saml.SamlReverseProxyTest output end  ---------
2022-07-05T09:33:52.5804038Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.047 s <<< FAILURE! - in org.keycloak.testsuite.saml.SamlReverseProxyTest
2022-07-05T09:33:52.5809371Z -- [ERROR] org.keycloak.testsuite.saml.SamlReverseProxyTest  Time elapsed: 10.043 s  <<< ERROR!
2022-07-05T09:33:52.5810678Z -- java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: Temporary failure in name resolution
2022-07-05T09:33:52.5811524Z -- 	at org.keycloak.testsuite.util.ReverseProxy$1.evaluate(ReverseProxy.java:42)
2022-07-05T09:33:52.5812520Z -- 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2022-07-05T09:33:52.5813101Z -- 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2022-07-05T09:33:52.5815615Z -- 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2022-07-05T09:33:52.5818807Z -- 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-07-05T09:33:52.5821865Z -- 	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
2022-07-05T09:33:52.5825119Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
2022-07-05T09:33:52.5828442Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
2022-07-05T09:33:52.5831765Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
2022-07-05T09:33:52.5835028Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
2022-07-05T09:33:52.5838311Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
2022-07-05T09:33:52.5841834Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
2022-07-05T09:33:52.5845028Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
2022-07-05T09:33:52.5848207Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
2022-07-05T09:33:52.5851617Z -- Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: Temporary failure in name resolution
2022-07-05T09:33:52.5856708Z -- 	at org.keycloak.testsuite.arquillian.undertow.lb.SimpleUndertowLoadBalancer.start(SimpleUndertowLoadBalancer.java:123)
2022-07-05T09:33:52.5860646Z -- 	at org.keycloak.testsuite.util.ReverseProxy$1.evaluate(ReverseProxy.java:38)
2022-07-05T09:33:52.5863934Z -- 	... 13 more
2022-07-05T09:33:52.5881864Z -- Caused by: java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: Temporary failure in name resolution
2022-07-05T09:33:52.5885480Z -- 	at io.undertow.Undertow.start(Undertow.java:254)
2022-07-05T09:33:52.5889197Z -- 	at org.keycloak.testsuite.arquillian.undertow.lb.SimpleUndertowLoadBalancer.start(SimpleUndertowLoadBalancer.java:114)
2022-07-05T09:33:52.5892694Z -- 	... 14 more
2022-07-05T09:33:52.5896167Z -- Caused by: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: Temporary failure in name resolution
2022-07-05T09:33:52.5900054Z -- 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2022-07-05T09:33:52.5903893Z -- 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
2022-07-05T09:33:52.5907421Z -- 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
2022-07-05T09:33:52.5910900Z -- 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
2022-07-05T09:33:52.5914299Z -- 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
2022-07-05T09:33:52.5917667Z -- 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
2022-07-05T09:33:52.5921362Z -- 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
2022-07-05T09:33:52.5924981Z -- 	at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
2022-07-05T09:33:52.5931642Z -- 	at io.undertow.Undertow.start(Undertow.java:196)
2022-07-05T09:33:52.5934890Z -- 	... 15 more
```

### Version

999-SNAPSHOT

### Expected behavior

Should work without a dependency to an external service and the known troubles when resolving 127.0.0.1

### Actual behavior

Will fail when external service is not available, as happend before (see log).

**Comment by ahus1** [comment]
apparently there are a lot of placed within the testsuite using this. Replacing "proxy.kc.127.0.0.1.nip.io" with "localhost" worked for this test case, but there will be a lot of other places where this would still be used. Closing this, as the solution is not obvious / how this can be resolved.
