### ISSUE TITLE
importing bin/kc.[sh|bat] import --file <file> doesn't work when using external database

### ISSUE THREAD

**Issue by devinfopercept** [keycloak/keycloak#12939]
### Describe the bug

I am using external database MariaDB, and when I use importing using 'bin/kc.[sh|bat] import --file <file>' it doesnt work.

### Version

18.0.0

**Comment by approached** [comment]
I tested it in `18.0.2` version with mysql 8 and it works.

But **userimport** not work:
```
keycloak        | 2022-07-06 14:00:02,238 INFO  [org.keycloak.services] (main) KC-SERVICES0004: Imported realm local from file /opt/keycloak/bin/../data/import/local-realm.json.
keycloak        | 2022-07-06 14:00:02,330 INFO  [org.keycloak.services] (main) KC-SERVICES0003: Not importing realm local from file /opt/keycloak/bin/../data/import/local-users-0.json.  It already exists.
```

Test files:
https://github.com/approached/docker-services/tree/master/keycloak/import

Has anybody a idea how **user import** will be work? The files are generated with the export command.

**Comment by JonasCir** [comment]
Can confirm.

I run `bin/kc.sh import --file data/import/SOME_FILE.json --override=true` in a Dockerfile right before  before starting Keycloak in the entrypoint and I get the following exception:
```
 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.                                             
#0 1.956 2022-07-18 10:54:57,539 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
#0 1.956        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
#0 1.956        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
#0 1.956        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
#0 1.956        at org.postgresql.Driver.makeConnection(Driver.java:400)
#0 1.956        at org.postgresql.Driver.connect(Driver.java:259)
#0 1.956        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
#0 1.956        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
#0 1.956        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
#0 1.956        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
#0 1.956        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
#0 1.956        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
#0 1.956        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
#0 1.956        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
#0 1.956        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#0 1.956        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
#0 1.956        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
#0 1.956        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
#0 1.956        at java.base/java.lang.Thread.run(Thread.java:829)
#0 1.956 Caused by: java.net.ConnectException: Connection refused (Connection refused)
#0 1.956        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
#0 1.956        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
#0 1.956        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
#0 1.956        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
#0 1.956        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
#0 1.956        at java.base/java.net.Socket.connect(Socket.java:609)
#0 1.956        at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
#0 1.956        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
#0 1.956        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
#0 1.956        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
#0 1.956        ... 17 more

```
Postgres was configured through `bin/kc.sh build --db postgres`. It appears that the import command ignored the environment variables and connects to the default  `localhost:5432`. However, `KC_DB_URL_HOST` is set.

Another interesting insight is that `bin/kc.[sh|bat] start --import-realm` works without problems and uses `KC_DB_URL_HOST` without problems.

**Comment by JonasCir** [comment]
Any news here? It's blocking us from using the new Keycloak version in production...

**Comment by JonasCir** [comment]
Hey @approached, did you manage to work around this somehow? :)

**Comment by approached** [comment]
hi @JonasCir i use kcadm (Admin CLI) via `shell script` for init keycloak. I create automaticly my  realm and clients. It works very well.

**Comment by vmuzikar** [comment]
Possibly fixed by https://github.com/keycloak/keycloak/pull/19645
