### ISSUE TITLE
Keycloak tries to start server after realm export

### ISSUE THREAD

**Issue by Antonboom** [keycloak/keycloak#12957]
### Describe the bug

```bash
$ docker ps -f name=keycloak
CONTAINER ID   IMAGE                              COMMAND                  CREATED       STATUS       PORTS                                NAMES
c1429ffff47e   quay.io/keycloak/keycloak:18.0.0   "/opt/keycloak/bin/k…"   2 hours ago   Up 2 hours   8443/tcp, 127.0.0.1:3001->8080/tcp   keycloak
```

```bash
$ docker exec -it keycloak /opt/keycloak/bin/kc.sh export --realm MyRealm --users realm_file --file /tmp/realm.json
...
(main) Exporting realm 'MyRealm' into file /tmp/realm.json
(main) Export finished successfully

(main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
(main) ERROR: Failed to start server in (import_export) mode
(main) ERROR: Unable to start HTTP server
(main) ERROR: io.quarkus.runtime.QuarkusBindException
```

<details>
<summary>Log</summary>

```
2022-07-07 12:31:40,512 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-07-07 12:31:40,972 INFO  [org.infinispan.server.core.transport.EPollAvailable] (keycloak-cache-init) ISPN005028: Native Epoll transport not available, using NIO instead: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
2022-07-07 12:31:41,048 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-07-07 12:31:41,083 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-07-07 12:31:41,120 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-07-07 12:31:41,236 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-07-07 12:31:41,311 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-07-07 12:31:41,311 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-07-07 12:31:41,377 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-07-07 12:31:41,377 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-07-07 12:31:41,378 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-07-07 12:31:41,378 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-07-07 12:31:41,419 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [c1429ffff47e-19524|21] (2) [c1429ffff47e-19524, c1429ffff47e-23742]
2022-07-07 12:31:41,422 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `c1429ffff47e-23742`, physical addresses are `[172.22.0.5:33828]`
2022-07-07 12:31:41,823 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: c1429ffff47e-23742, Site name: null
2022-07-07 12:31:42,026 INFO  [org.keycloak.services] (main) KC-SERVICES0034: Export of realm 'MyRealm' requested.
2022-07-07 12:31:42,026 INFO  [org.keycloak.exportimport.singlefile.SingleFileExportProvider] (main) Exporting realm 'MyRealm' into file /tmp/realm.json
2022-07-07 12:31:42,527 INFO  [org.keycloak.services] (main) KC-SERVICES0035: Export finished successfully
2022-07-07 12:31:42,584 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
2022-07-07 12:31:42,692 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-07-07 12:31:42,730 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-07-07 12:31:42,730 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2022-07-07 12:31:42,730 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: io.quarkus.runtime.QuarkusBindException
2022-07-07 12:31:42,731 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

</details>

### Version

18.0.0

### Expected behavior

No errors after realm exporting.

**Comment by yeroc** [comment]
This also happens during import.  From 19.0.3:

```
JAVA_HOME=/usr/lib/jvm/java-11 ./bin/kc.sh import --file /tmp/data-keycloakx-dev.json                                                                                                                
2022-10-12 15:54:02,895 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: api.mykdm.dev.local, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: https://cal-app-dev-local.dev.local:8543/auth/, Admin: cal-app-dev-local.dev.local, Port: -1, Proxied: true
2022-10-12 15:54:04,628 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-10-12 15:54:06,884 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-10-12 15:54:06,943 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-10-12 15:54:07,046 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-10-12 15:54:07,689 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final2022-10-12 15:54:07,944 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-10-12 15:54:07,945 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-10-12 15:54:08,080 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB2022-10-12 15:54:08,081 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-10-12 15:54:08,081 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-10-12 15:54:08,081 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-10-12 15:54:08,163 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [cal-app-dev-local-4319|7] (2) [cal-app-dev-local-4319, cal-app-dev-local-40969]
2022-10-12 15:54:08,177 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `cal-app-dev-local-40969`, physical addresses are `[192.168.56.4:57049]`
2022-10-12 15:54:09,275 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: cal-app-dev-local-40969, Site name: null
2022-10-12 15:54:10,475 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: OVERWRITE_EXISTING
2022-10-12 15:54:10,475 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /tmp/data-keycloakx-dev.json
2022-10-12 15:54:10,476 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'master' already exists. Removing it before import
2022-10-12 15:54:12,352 WARN  [org.keycloak.storage.datastore.LegacyExportImportManager] (main) Using deprecated 'clientTemplates' configuration in JSON representation for realm 'master'. It will be removed in future versions
2022-10-12 15:54:13,669 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'master' imported
2022-10-12 15:54:14,046 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully
2022-10-12 15:54:14,451 ERROR [io.quarkus.vertx.core.runtime.VertxCoreRecorder] (vert.x-eventloop-thread-1) Uncaught exception received by Vert.x: java.lang.IllegalStateException: Result is already complete
        at io.vertx.core.Promise.fail(Promise.java:90)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$setupTcpHttpServer$1(VertxHttpRecorder.java:1071)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-10-12 15:54:14,458 ERROR [io.quarkus.vertx.core.runtime.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x: java.lang.IllegalStateException: Result is already complete
        at io.vertx.core.Promise.fail(Promise.java:90)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.lambda$setupTcpHttpServer$1(VertxHttpRecorder.java:1071)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-10-12 15:54:14,541 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-10-12 15:54:14,661 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-10-12 15:54:14,661 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2022-10-12 15:54:14,661 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: io.quarkus.runtime.QuarkusBindException
2022-10-12 15:54:14,666 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

Here we see a failure because we already have another process on the machine listening on port 8080.  For some reason our Keycloak config which has http disabled is completely ignored here.  We also can't seem to override the port using either on the command line(`--http-port=8180`) or via environment variable (`KC_HTTP_PORT=810`).  Ideally though a web server wouldn't be started up at all.

**Comment by HJK181** [comment]
I'm facing the same issue as @yeroc. We try to **import** a test realm before each Junit test execution. Unfortunately, we face the above error and an updated user from a previous test run, makes subsequent tests fail, as they rely on the initial user state from the realm export. However, if I login to the running java [test container](https://github.com/dasniko/testcontainers-keycloak) and do a "partial realm import" with the test realm and choose "override" + import everything, the realm gets correctly imported without any error.

Any updates on this?

**Comment by LCerebo** [comment]
same problem here with version 21.0.1, any update on this issue?

**Comment by Antonboom** [comment]
Not reproducable since **21.0.2**.
The issue can be closed.

**Comment by softening8** [comment]
> I'm facing the same issue as [@yeroc](https://github.com/yeroc) with version 20.0.1. We try to **import** a test realm before each Junit test execution. Unfortunately, we face the above error and an updated user from a previous test run, makes subsequent tests fail, as they rely on the initial user state from the realm export. However, if I login to the running java [test container](https://github.com/dasniko/testcontainers-keycloak) and do a "partial realm import" with the test realm and choose "override" + import everything, the realm gets correctly imported without any error.
> 
> Any updates on this?
> 
> ```
> 2022-12-12 14:05:33,089 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
> 2022-12-12 14:05:33,089 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Unable to start HTTP server
>         at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:758)
>         at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:318)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1866188241.deploy_0(Unknown Source)
>         at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1866188241.deploy(Unknown Source)
>         at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
>         at io.quarkus.runtime.Application.start(Application.java:101)
>         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
>         at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
>         at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
>         at org.keycloak.quarkus.runtime.cli.command.AbstractExportImportCommand.run(AbstractExportImportCommand.java:61)
>         at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
>         at picocli.CommandLine.access$1300(CommandLine.java:145)
>         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
>         at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
>         at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
>         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
>         at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
>         at picocli.CommandLine.execute(CommandLine.java:2078)
>         at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
>         at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
>         at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
> Caused by: java.util.concurrent.ExecutionException: io.quarkus.runtime.QuarkusBindException: Port(s) already bound: 9080: Address already in use
> ```





https://stackdev.space/questions/using-multicastsocket-in-conjunction-with-implementing-the-runnable-interface

**Comment by pschichtel** [comment]
I'm seeing this exact behavior when trying to export realms within a keycloak pod deployed by the keycloak operator.

**Comment by shawkins** [comment]
@pschichtel are you running the export command on the same pod as a running keycloak instance? That is documented as not being supported.

**Comment by pschichtel** [comment]
hmm okay, are there recommendations for alternative approaches? It seemed like a convenient way for running the export with all the necessary DB configuration already in place. The exported JSON files exist, the command just fails due to the port conflict.

**Comment by shawkins** [comment]
The recommended way is to start another pod. The operator does this for imports via a Kubernetes Job. You want a more isolated configuration for import / export - in particular with caching set to local so that it doesn't join the cluster - and because you're running instance will likely have its resources tuned just for running keycloak, not for running keycloak + potentially heavy-weight import / export tasks.

**Comment by pschichtel** [comment]
yeah I was already figuring out how to properly do that. In a perfect world the operator itself would provide this functionality, I'll quickly script up some bash script that extracts the necessary information from the keycloak object (image, wether it's optimized, ...).
