### ISSUE TITLE
NullPointerException in OctetStringEncoder during user search (KEYCLOAK-15604 follow-up)

### ISSUE THREAD

**Issue by titix29** [keycloak/keycloak#12953]
### Describe the bug

We encounter the same bug as described in [KEYCLOAK-15604](https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-15604) when searching for a given user in a realm with LDAP User Federation (MS AD). For the other users, search is working properly.
Error message in the web interface : "Error! No response from server."
Stacktrace extract :
```
Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@1e65d50e
        at org.keycloak.keycloak-ldap-federation@12.0.4//org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
        at org.keycloak.keycloak-ldap-federation@12.0.4//org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:172)
        ... 100 more
Caused by: java.lang.NullPointerException
        at org.keycloak.keycloak-ldap-federation@12.0.4//org.keycloak.storage.ldap.idm.query.internal.OctetStringEncoder.escapeAsString(OctetStringEncoder.java:30)
        at org.keycloak.keycloak-ldap-federation@12.0.4//org.keycloak.storage.ldap.idm.query.internal.OctetStringEncoder.encode(OctetStringEncoder.java:23)
        at org.keycloak.keycloak-ldap-federation@12.0.4//org.keycloak.storage.ldap.idm.query.internal.EqualCondition.applyCondition(EqualCondition.java:59)
        at org.keycloak.keycloak-ldap-federation@12.0.4//org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.createIdentityTypeSearchFilter(LDAPIdentityStore.java:413)
        at org.keycloak.keycloak-ldap-federation@12.0.4//org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:273)
```

[keycloak-stracktrace.txt](https://github.com/keycloak/keycloak/files/9061544/keycloak-stracktrace.txt)

### Version

12.0.4

### Expected behavior

The user account should appear in the Manage > Users view.
If Active Directory user attributes are incompatible with Keycloak or malformed, a specific error message should appear in the logs instead of a NullPointerException.

### Actual behavior

The user account does not appear in the Manage > Users view
The following error message is displayed instead : "Error! No response from server."

### How to Reproduce?

- Create a Keycloak realm
- Create an ldap Provider as User Federation with "Active Directory" vendor
- Use default settings (no specific mapper)
- In the Active Directory, create a user with specific attributes
- In the Manage > Users view, search for the specific user account

### Anything else?

Existing bug reference : [KEYCLOAK-15604](https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-15604)
We are using generic user accounts in our ActiveDirectory for perfomance tests. The error occurs on a single account, the others are working fine. When comparing ldif extracts for these accounts, we notice that the account in error has an additional attribute : lockoutTime (value : 0)

**Comment by hmlnarik** [comment]
@titix29 Could you please attempt to reproduce this with the latest Keycloak?

**Comment by titix29** [comment]
@hmlnarik 
I tested this morning (19.0.3-legacy) on the same AD account which previously gave the error : cannot reproduce, the account properly shows up on the  admin console. Either the NPE is fixed or this specific account has changed in the AD (attribute update) and doesn't trigger the NPE anymore.

**Comment by hmlnarik** [comment]
Thank you for your response, closing.
