### ISSUE TITLE
Jboss to Quarkus upgrade issue

### ISSUE THREAD

**Issue by nidhin077** [keycloak/keycloak#13112]
### Describe the bug

I have upgraded my Keycloak 16..1.1 to Quarkus 18.0.2. I'm experiencing some issues right now, and the container isn't up. The error is listed below.
-------------------------------------------------------
Jul 14, 2022 12:46:27 PM org.jboss.resteasy.resteasy_jaxrs.i18n
INFO: RESTEASY002220: Adding singleton resource org.keycloak.services.resources.admin.AdminRoot from Application class org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication
Jul 14, 2022 12:46:27 PM org.jboss.resteasy.resteasy_jaxrs.i18n
INFO: RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RealmsResource from Application class org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication
Jul 14, 2022 12:46:27 PM org.jboss.resteasy.resteasy_jaxrs.i18n
INFO: RESTEASY002220: Adding singleton resource org.keycloak.quarkus.runtime.services.resources.QuarkusWelcomeResource from Application class org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication
Jul 14, 2022 12:46:28 PM org.hibernate.resource.beans.container.spi.AbstractCdiBeanContainer stop
INFO: HHH10005004: Stopping BeanContainer : %s
ERROR: Failed to start server in (production) mode
ERROR: One or more configuration errors have prevented the application from starting. The errors are:
  - No value present
  - No value present
  - ---------------------------------------------------------

Got these errors when starting in development mode

--------------------------------------------------------------
ERROR: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to load the datasource driver POSTGRES for the default datasource
	at io.quarkus.agroal.deployment.AgroalProcessor.validateBuildTimeConfig(AgroalProcessor.java:133)
	at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.ClassNotFoundException: POSTGRES
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:464)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.quarkus.agroal.deployment.AgroalProcessor.validateBuildTimeConfig(AgroalProcessor.java:131)
	... 12 more

ERROR: Unable to load the datasource driver POSTGRES for the default datasource
ERROR: POSTGRES
--------------------------------------------------------------

Please look into the issue and advise me as to what changes I should do to fix it.

### Version

keycloak=18.0.2 postgres=13

### Expected behavior

Start the container in production mode

### Actual behavior

Getting errors

**Comment by mazenaissa** [comment]
Hello,
Could you please share with me your build & start commands?

**Comment by nidhin077** [comment]
I have listed my compose file used for keycloak. In the upgrade process, I have changed the jboss environment to Quarkus during the update process.

version: '3.4'
services:
  postgres:
    image: postgres:13
    container_name: remedy-analytics-keycloak-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: keycloak
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: citrus
    restart: always
    ports:
       - 5429:5432
    networks:
       - network
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: remedy-analytics-keycloak
    restart: always
    command: start-dev
    environment:
       - KC_DB=POSTGRES
       - KC_DB_URL_HOST=remedy-analytics-keycloak-postgres
       - KEYCLOAK_ADMIN=admin
       - KEYCLOAK_ADMIN_PASSWORD=citrus
       - KC_DB_SCHEMA=public
       - KC_DB_URL_DATABASE=keycloak
       - KC_DB_USERNAME=postgres
       - KC_DB_PASSWORD=citrus
       - KC_HOSTNAME=10.10.12.44
       - KC_HOSTNAME_PORT=8443
       - KC_METRICS_ENABLED=true
       - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
       - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
    volumes:
       - ./config/cert/example.crt:/etc/x509/https/tls.crt
       - ./config/cert/example.key:/etc/x509/https/tls.key
  
    ports:
       - 8443:8443
    networks:
       - network
    depends_on:
       - postgres

volumes:
  postgres_data: {}
networks:
  network:
    external:
      name: network

**Comment by mazenaissa** [comment]
> KC_DB=POSTGRES

Hello, you must change this to KC_DB=postgres. The type of DB vendor must be in lowercase like below
![image](https://user-images.githubusercontent.com/25006500/179791874-b1d01977-f824-4d92-85fe-73e938615e18.png)

**Comment by abstractj** [comment]
@nidhin077 have you tried the steps mentioned by @mazenaissa ?

**Comment by nidhin077** [comment]
Yes, it was fixed, thanks.@mazenaissa
