### ISSUE TITLE
Deleting Users in Keycloak Cluster with 3 or more Nodes is not possible

### ISSUE THREAD

**Issue by dirkoberhaus** [keycloak/keycloak#13122]
### Describe the bug

We use Keycloak X version 18.0.2 in an Kubernetes Cluster with 3 Nodes. If we try to delete users via admin web frontend we get an error with following log entries:

```
Node-2 2022-07-15 06:58:26,017 ERROR [org.infinispan.CLUSTER] (jgroups-69,fermata-keycloak-2-21964) ISPN000474: Error processing request 156@fermata-keycloak-1-64497: java.lang.ExceptionInInitializerError
Node-2     at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1268)
Node-2     at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1067)
Node-2     at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1381)
Node-2     at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298)
Node-2     at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231)
Node-2     at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
Node-2     at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectFromObjectStream(AbstractJBossMarshaller.java:137)
Node-2     at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectFromByteBuffer(AbstractJBossMarshaller.java:115)
Node-2     at org.infinispan.commons.marshall.AbstractMarshaller.objectFromByteBuffer(AbstractMarshaller.java:82)
Node-2     at org.infinispan.marshall.core.impl.DelegatingUserMarshaller.objectFromByteBuffer(DelegatingUserMarshaller.java:63)
Node-2     at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.read(MarshallableUserObject.java:139)
Node-2     at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.read(MarshallableUserObject.java:100)
Node-2     at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.unmarshall(ProtobufTagMarshallerDelegate.java:32)
Node-2     at org.infinispan.protostream.WrappedMessage.readMessage(WrappedMessage.java:539)
Node-2     at org.infinispan.protostream.WrappedMessage.read(WrappedMessage.java:351)
Node-2     at org.infinispan.protostream.ProtobufUtil.fromWrappedByteArray(ProtobufUtil.java:129)
Node-2     at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectFromByteBuffer(AbstractInternalProtoStreamMarshaller.java:97)
Node-2     at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectFromByteBuffer(AbstractInternalProtoStreamMarshaller.java:92)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readUnknown(GlobalMarshaller.java:905)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readUnknown(GlobalMarshaller.java:890)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:714)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-2     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-2     at org.infinispan.stream.impl.intops.IntermediateOperationExternalizer.readObject(IntermediateOperationExternalizer.java:378)
Node-2     at org.infinispan.stream.impl.intops.IntermediateOperationExternalizer.readObject(IntermediateOperationExternalizer.java:93)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-2     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-2     at org.infinispan.commons.marshall.MarshallUtil.lambda$unmarshallCollection$0(MarshallUtil.java:295)
Node-2     at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:278)
Node-2     at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
Node-2     at org.infinispan.marshall.exts.CollectionExternalizer.readObject(CollectionExternalizer.java:121)
Node-2     at org.infinispan.marshall.exts.CollectionExternalizer.readObject(CollectionExternalizer.java:28)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-2     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-2     at org.infinispan.stream.impl.CacheIntermediatePublisher$ReducerExternalizer.readObject(CacheIntermediatePublisher.java:72)
Node-2     at org.infinispan.stream.impl.CacheIntermediatePublisher$ReducerExternalizer.readObject(CacheIntermediatePublisher.java:64)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-2     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-2     at org.infinispan.reactive.publisher.impl.commands.batch.InitialPublisherCommand.readFrom(InitialPublisherCommand.java:157)
Node-2     at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
Node-2     at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:170)
Node-2     at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:88)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
Node-2     at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
Node-2     at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1454)
Node-2     at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1394)
Node-2     at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
Node-2     at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-0     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-0     at org.infinispan.commons.marshall.MarshallUtil.lambda$unmarshallCollection$0(MarshallUtil.java:295)
Node-0     at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:278)
Node-0     at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
Node-1     at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:42)
Node-1     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-1     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-1     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-1     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-0     at org.infinispan.marshall.exts.CollectionExternalizer.readObject(CollectionExternalizer.java:121)
Node-0     at org.infinispan.marshall.exts.CollectionExternalizer.readObject(CollectionExternalizer.java:28)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-1     at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:180)
Node-1     ... 38 more
Node-1 Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.util.AbstractMap() accessible: module java.base does not "opens java.util" to unnamed module @7219ec67
Node-1     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-0     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-0     at org.infinispan.stream.impl.CacheIntermediatePublisher$ReducerExternalizer.readObject(CacheIntermediatePublisher.java:72)
Node-0     at org.infinispan.stream.impl.CacheIntermediatePublisher$ReducerExternalizer.readObject(CacheIntermediatePublisher.java:64)
Node-1     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
Node-1     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Node-1     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
Node-1     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-0     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-1     at org.infinispan.marshall.exts.ThrowableExternalizer.readGenericThrowable(ThrowableExternalizer.java:282)
Node-1     at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:259)
Node-1     at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:42)
Node-1     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-1     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-1     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-1     at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
Node-0     at org.infinispan.reactive.publisher.impl.commands.batch.InitialPublisherCommand.readFrom(InitialPublisherCommand.java:157)
Node-0     at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
Node-0     at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:170)
Node-0     at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:88)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
Node-0     at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
Node-0     at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1454)
Node-1     at org.infinispan.marshall.exts.ThrowableExternalizer.readGenericThrowable(ThrowableExternalizer.java:276)
Node-1     ... 45 more
Node-1 
Node-0     at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1394)
Node-0     at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
Node-0     at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
Node-0     at org.jgroups.JChannel.up(JChannel.java:780)
Node-0     at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
Node-0     at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
Node-0     at org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
Node-0     at org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
Node-0     at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
Node-0     at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
Node-0     at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
Node-0     at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
Node-0     at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
Node-0     at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
Node-0     at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
Node-0     at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
Node-0     at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
Node-0     at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
Node-0     at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
Node-0     at org.jgroups.protocols.Discovery.up(Discovery.java:300)
Node-0     at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
Node-0     at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
Node-0     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Node-0     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Node-0     at java.base/java.lang.Thread.run(Thread.java:833)
Node-0 Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.util.AbstractMap() accessible: module java.base does not "opens java.util" to unnamed module @7219ec67
Node-0     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
Node-0     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
Node-0     at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
Node-0     at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
Node-0     at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.<init>(JDKSpecific.java:147)
Node-0     at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:84)
Node-0     at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
Node-0     at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
Node-0     at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
Node-0     at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
Node-0     at java.base/java.lang.ClassValue.get(ClassValue.java:116)
Node-0     at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
Node-0     at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:76)
Node-0     at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
Node-0     at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
Node-0     at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
Node-0     at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
Node-0     at java.base/java.lang.ClassValue.get(ClassValue.java:116)
Node-0     at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
Node-0     at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:152)
Node-0     at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:146)
Node-0     at org.jboss.marshalling.river.ClassDescriptors.<clinit>(ClassDescriptors.java:101)
Node-0     ... 79 more
Node-0 

```

### Version

18.0.2

### Expected behavior

User is deleted

### Actual behavior

User is not deleted and an error is shown on the admin frontend.

### How to Reproduce?

- Install Keycloak X with Java 17 (Coretto or Temurin) as cluster with 3 or more nodes.
- Create an user.
- Try to delete this user.

**Comment by Morl99** [comment]
Hello everyone, I wanted to chime in as I am in the same team as Dirk. I want to add some additional details that we were able to narrow down:

We are not seeing these problems if we use java 11 as a runtime. We also do not see the problem, if we have 2 or 1 node in the cluster, the issue starts appearing once we have 3 Nodes.

In our docker image, we set the following variables (not sure, if it is relevant)
```
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=admin2
ENV KC_FEATURES_DISABLED=account2
ENV KC_DB=postgres
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_CACHE_STACK=kubernetes
ENV KC_HTTP_ENABLED=true
```

**Comment by Morl99** [comment]
We had internal discussions about the question, if Java 17 is even a supported version, and now we are unclear. Can a maintainer of keycloak clarify on this? The docs are kind of vague :-)

**Comment by pedroigor** [comment]
We do not yet support 17. Please follow this [issue](https://github.com/keycloak/keycloak/issues/15014) to plans around that.

**Comment by Morl99** [comment]
Could we leave this issue open until the documentation is clarified on this? It would be very helpful to clearly state the JRE version requirements for Keycloak on all doc pages that talk about prerequisites for running Keycloak.

**Comment by Morl99** [comment]
I can try to collect all pages that are unclear:

https://www.keycloak.org/getting-started/getting-started-zip
(talks about 11+ which implies support for 17 and so on)

**Comment by pedroigor** [comment]
@Morl99 You're right. I'll add a comment to the previously linked issue to mention that we also need changes to docs.

**Comment by slominskir** [comment]
Duplicate (or very similar): https://github.com/keycloak/keycloak/issues/15607

**Note**: This problem still exists in Keycloak version 20.0.1, which is apparently supposed to support JDK 17.  Upgrading jboss-marshalling dependency appears to fix this.
