### ISSUE TITLE
Support for IAM authentication JDBC wrapper driver

### ISSUE THREAD

**Issue by jameshcovington** [keycloak/keycloak#13205]
### Description

Trying to include the io.magj.iamjdbcdriver.PostgreSqlIamAuthJdbcDriverWrapper driver to my keycloak image, looks like I'd need to include quarkus-specific properties to accomplish this.

### Motivation

The goal is to be able to connect to an AWS RDS Aurora postgresql instance with IAM authentication. 

### Details

See https://github.com/magJ/iam-jdbc-driver for details on this driver.

**Comment by trixpan** [comment]
@pedroigor 
I tried playing with KC_DB_DRIVER but doesn't seem to work. :-\ 

The loss of the ability to derive IAM based RDS authentication is a big regression for folk using RDS.

it would be great if:

* We provided the ability to set the driver
* Respected a non standard JDBC identifier as part of the URL(most RDS wrappers register their own JDBC "name", in the case of iam-jdbc-driver they use 'iampostgresql' or 'iammysql')
  * I believe we already to that but we may need to add test units to cover that

**Comment by pedroigor** [comment]
@jameshcovington Are you able to see if removing this condition helps to load the driver. See https://github.com/keycloak/keycloak/blob/f3c3bb50016e818d9f035e72a83d1cc26e0db9a2/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakClassLoader.java#L36.

I guess you are setting `db=postgres db-url=<custom>`, right?

**Comment by jameshcovington** [comment]
sorry, not in a position to clone the repo and build my own. I'll wait until a new Docker container is available for pull and test.

**Comment by jameshcovington** [comment]
This same issue would apply to AWS Secrets Manager, where a jdbc wrapper driver is also needed to take advantage of this service. In either case, it's a big step forward in security to not have to manage and store database passwords.

**Comment by pedroigor** [comment]
@trixpan @jameshcovington I'm trying to figure out why it is not working if you copy the JAR to the `providers` directory and set the `db-url` option.

**Comment by brettlounsbury** [comment]
@pedroigor  - I suspect the addition of the KeyCloakClassLoader may be problematic in some cases.  I am trying to make use of aws' `aws-advanced-jdbc-wrapper`.  This wrapper adds a few RDS specific functions (like IAM auth), but then delegates to the real db driver.

In my case, I have the following settings:

```
kc.db =  postgres (KcEnvVarConfigSource)
kc.db-driver =  software.amazon.jdbc.Driver (KcEnvVarConfigSource)
```

which leads to it properly using the `software.amazon.jdbc.Driver` but then it fails because the postgres driver isn't available due to the classloader explicitly ignoring java.sql.Driver loads.

2023-03-08 21:44:03,025 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver
2023-03-08 21:44:03,026 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver
        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:299)
        at software.amazon.jdbc.Driver.connect(Driver.java:95)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by brettlounsbury** [comment]
I can confirm that the issue comes from the custom ClassLoader.  I changed it so that it doesn't ignore load requests for `java.sql.Driver` (I was able to just delete the code below and javac it, and then replace that class in the keycloak jar).  With this change in place the wrapper driver and postgres driver both loaded and I was able to use IAM auth with my RDS instance.  This just happened to be the quickest/fastest way to test it because the ClassLoader has no dependencies outside of the JDK, making it easy to change and compile.

```
@Override
     public Enumeration<URL> getResources(String name) throws IOException {
-        // drivers are going to be loaded lazily, and we avoid loading all available drivers
-        // see https://github.com/quarkusio/quarkus/pull/7089
-        if (name.contains(Driver.class.getName())) {
-            return Collections.emptyEnumeration();
-        }
-
         return super.getResources(name);
     }
```

**Comment by pedroigor** [comment]
@brettlounsbury @jameshcovington Could you please check the nightly image (or build from sources) and see if it is now enabling the usage of JDBC wrappers?

**Comment by brettlounsbury** [comment]
@pedroigor - I confirmed this works in the latest nightly build.

sh-4.2$ ./bin/kc.sh build
Updating the configuration and installing your custom providers, if any. Please wait.
2023-04-06 16:56:13,725 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 15592ms
Server configuration updated and persisted. Run the following command to review the configuration:

        kc.sh show-config

sh-4.2$ ./bin/kc.sh show-config
Current Mode: production
Current Configuration:
        kc.cache =  ispn (PersistedConfigSource)
        kc.config.built =  true (SysPropConfigSource)
        kc.db =  postgres (KcEnvVarConfigSource)
        kc.db-driver =  software.amazon.jdbc.Driver (KcEnvVarConfigSource)
        kc.db-url =  jdbc:aws-wrapper:postgresql://<redacted>/keycloak?wrapperPlugins=iam (KcEnvVarConfigSource)
        kc.db-username =  keycloak (KcEnvVarConfigSource)
        kc.db.driver =  software.amazon.jdbc.Driver (KcEnvVarConfigSource)
        kc.db.url =  jdbc:aws-wrapper:postgresql://<redacted>/keycloak?wrapperPlugins=iam (KcEnvVarConfigSource)
        kc.db.username =  keycloak (KcEnvVarConfigSource)
        kc.health-enabled =  false (PersistedConfigSource)
        kc.hostname-strict =  false (KcEnvVarConfigSource)
        kc.hostname.strict =  false (KcEnvVarConfigSource)
        kc.http-enabled =  false (PropertiesConfigSource[source=jar:file:///home/ssm-user/keycloak-999.0.0-SNAPSHOT/lib/lib/main/org.keycloak.keycloak-quarkus-server-999.0.0-SNAPSHOT.jar!/META-INF/keycloak.conf])
        kc.http-relative-path =  / (PersistedConfigSource)
        kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///home/ssm-user/keycloak-999.0.0-SNAPSHOT/lib/lib/main/org.keycloak.keycloak-quarkus-server-999.0.0-SNAPSHOT.jar!/META-INF/keycloak.conf])
        kc.log-file =  ${kc.home.dir:default}${file.separator}data${file.separator}log${file.separator}keycloak.log (PropertiesConfigSource[source=jar:file:///home/ssm-user/keycloak-999.0.0-SNAPSHOT/lib/lib/main/org.keycloak.keycloak-quarkus-server-999.0.0-SNAPSHOT.jar!/META-INF/keycloak.conf])
        kc.metrics-enabled =  false (PersistedConfigSource)
        kc.provider.file.annotations-2.18.1.jar.last-modified =  1680800100337 (PersistedConfigSource)
        kc.provider.file.auth-2.18.1.jar.last-modified =  1680800100337 (PersistedConfigSource)
        kc.provider.file.aws-advanced-jdbc-wrapper-1.0.1.jar.last-modified =  1680800100337 (PersistedConfigSource)
        kc.provider.file.aws-core-2.18.1.jar.last-modified =  1680800100337 (PersistedConfigSource)
        kc.provider.file.aws-query-protocol-2.18.1.jar.last-modified =  1680800100337 (PersistedConfigSource)
        kc.provider.file.checker-qual-3.26.0.jar.last-modified =  1680800100337 (PersistedConfigSource)
        kc.provider.file.commons-dbcp2-2.9.0.jar.last-modified =  1680800100337 (PersistedConfigSource)
        kc.provider.file.ec2-2.18.1.jar.last-modified =  1680800100357 (PersistedConfigSource)
        kc.provider.file.endpoints-spi-2.18.1.jar.last-modified =  1680800100357 (PersistedConfigSource)
        kc.provider.file.http-client-spi-2.18.1.jar.last-modified =  1680800100357 (PersistedConfigSource)
        kc.provider.file.jackson-annotations-2.13.4.jar.last-modified =  1680800100357 (PersistedConfigSource)
        kc.provider.file.jackson-databind-2.13.4.jar.last-modified =  1680800100365 (PersistedConfigSource)
        kc.provider.file.json-utils-2.18.1.jar.last-modified =  1680800100365 (PersistedConfigSource)
        kc.provider.file.metrics-spi-2.18.1.jar.last-modified =  1680800100365 (PersistedConfigSource)
        kc.provider.file.profiles-2.18.1.jar.last-modified =  1680800100365 (PersistedConfigSource)
        kc.provider.file.protocol-core-2.18.1.jar.last-modified =  1680800100365 (PersistedConfigSource)
        kc.provider.file.rds-2.17.289.jar.last-modified =  1680800100373 (PersistedConfigSource)
        kc.provider.file.regions-2.18.1.jar.last-modified =  1680800100373 (PersistedConfigSource)
        kc.provider.file.sdk-core-2.18.1.jar.last-modified =  1680800100373 (PersistedConfigSource)
        kc.provider.file.third-party-jackson-core-2.18.1.jar.last-modified =  1680800100373 (PersistedConfigSource)
        kc.provider.file.utils-2.18.1.jar.last-modified =  1680800100377 (PersistedConfigSource)
        kc.spi-map-storage-concurrenthashmap-dir =  ${kc.home.dir:default}${file.separator}data${file.separator}chm (PropertiesConfigSource[source=jar:file:///home/ssm-user/keycloak-999.0.0-SNAPSHOT/lib/lib/main/org.keycloak.keycloak-quarkus-server-999.0.0-SNAPSHOT.jar!/META-INF/keycloak.conf])
        kc.spi-map-storage-concurrenthashmap-key-type-authz-resource-servers =  string (PropertiesConfigSource[source=jar:file:///home/ssm-user/keycloak-999.0.0-SNAPSHOT/lib/lib/main/org.keycloak.keycloak-quarkus-server-999.0.0-SNAPSHOT.jar!/META-INF/keycloak.conf])
        kc.spi-map-storage-concurrenthashmap-key-type-realms =  string (PropertiesConfigSource[source=jar:file:///home/ssm-user/keycloak-999.0.0-SNAPSHOT/lib/lib/main/org.keycloak.keycloak-quarkus-server-999.0.0-SNAPSHOT.jar!/META-INF/keycloak.conf])
        kc.spi-map-storage-concurrenthashmap-key-type-single-use-objects =  string (PropertiesConfigSource[source=jar:file:///home/ssm-user/keycloak-999.0.0-SNAPSHOT/lib/lib/main/org.keycloak.keycloak-quarkus-server-999.0.0-SNAPSHOT.jar!/META-INF/keycloak.conf])
        kc.transaction-xa-enabled =  false (KcEnvVarConfigSource)
        kc.transaction.xa.enabled =  false (KcEnvVarConfigSource)
        kc.version =  999.0.0-SNAPSHOT (SysPropConfigSource)
sh-4.2$ ./bin/kc.sh start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
2023-04-06 16:56:56,303 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 15100ms
2023-04-06 16:56:58,719 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2023-04-06 16:57:01,527 INFO  [org.infinispan.SERVER] (keycloak-cache-init) ISPN005054: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
2023-04-06 16:57:01,712 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-04-06 16:57:01,722 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-04-06 16:57:01,757 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-04-06 16:57:06,557 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-04-06 16:57:09,178 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
2023-04-06 16:57:10,268 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_676055, Site name: null
2023-04-06 16:57:11,152 INFO  [io.quarkus] (main) Keycloak 999.0.0-SNAPSHOT on JVM (powered by Quarkus 2.13.7.Final) started in 14.351s. Listening on: http://0.0.0.0:8080
2023-04-06 16:57:11,152 INFO  [io.quarkus] (main) Profile dev activated.
2023-04-06 16:57:11,152 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, vertx]
2023-04-06 16:57:11,162 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
