### ISSUE TITLE
JPA Map Storage with CRDB: ComponentsTest failures

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#13209]
### Describe the bug

**org.keycloak.testsuite.admin.ComponentsTest** presents failures/errors with `CockroachDB`:

```
[ERROR]   ComponentsTest.testConcurrencyWithChildren:97->testConcurrency:77 Did not create all components in time
[ERROR]   ComponentsTest.testConcurrencyWithoutChildren:87->testConcurrency:77 Did not create all components in time
```

- Required JPA stores to reproduce the failures: **realms**

For both tests, logs show the following error:

```
22:49:15,809 ERROR [io.undertow.request] UT005023: Exception handling request to /auth/admin/realms/admin-client-test/components/08e2f053-6f3c-41b7-b0b5-d6c726ef362a
org.keycloak.models.ModelException: javax.persistence.PersistenceException: org.hibernate.TransactionException: Unable to commit against JDBC Connection
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:84)
	at org.keycloak.models.map.storage.jpa.JpaTransactionWrapper.commit(JpaTransactionWrapper.java:53)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
	at org.keycloak.services.filters.AbstractRequestFilter.close(AbstractRequestFilter.java:64)
	at org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:49)
	at org.keycloak.testsuite.UndertowRequestFilter.doFilter(UndertowRequestFilter.java:47)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        ...
Caused by: javax.persistence.PersistenceException: org.hibernate.TransactionException: Unable to commit against JDBC Connection
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:60)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:107)
	at org.keycloak.models.map.storage.jpa.JpaTransactionWrapper.commit(JpaTransactionWrapper.java:51)
	... 39 more
Caused by: org.hibernate.TransactionException: Unable to commit against JDBC Connection
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:87)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:272)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
	... 40 more
Caused by: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=eb957377 key=/Table/401/2/"\r\xa2\xa3d\x97.B\x13\x85\xadҧ\x16]\xfa\xef"/"cn\x93\x8c\xcc\x06FI\xac\x1a\xfc?=i\x17,"/0 pri=0.01011300 epo=0 ts=1650678555.780086146,1 min=1650678555.776754247,0 seq=12} lock=true stat=PENDING rts=1650678555.776754247,0 wto=false gul=1650678556.276754247,0
  Hint: See: https://www.cockroachlabs.com/docs/v21.2/transaction-retry-error-reference.html#retry_serializable
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:315)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:855)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:877)
	... 42 more
```

	

### Version

main

### Expected behavior

Tests should run without failures or errors

### How to Reproduce?

1- Setup CockroachDB according to the instructions in https://github.com/keycloak/keycloak/discussions/9596
2- Run the test with the correct parameters, enabling JPA storage for **realms** only:

```
cd testsuite/integration-arquillian

mvn clean install -Pmap-storage -Dpageload.timeout=90000 -Dkeycloak.realm.map.storage.provider=jpa \
-Dkeycloak.map.storage.connectionsJpa.url=jdbc:postgresql://localhost:26257/keycloak \
-Dkeycloak.map.storage.connectionsJpa.user=keycloak -Dkeycloak.map.storage.connectionsJpa.password=pass \
-Dtest=ComponentsTest
```

**Comment by sguilhen** [comment]
Query to show table names/table ids:

```
SELECT  ti.descriptor_name as table_name, us.table_id, ti.index_name, total_reads
FROM  crdb_internal.index_usage_statistics AS us
JOIN crdb_internal.table_indexes ti
ON us.index_id = ti.index_id AND us.table_id = ti.descriptor_id
ORDER BY total_reads desc;
```
