### ISSUE TITLE
Upgraded keycloak app version to 18.0.2 and Hight availability stopped working.

### ISSUE THREAD

**Issue by sathishkumar3009** [keycloak/keycloak#13308]
### Describe the bug

Able to login into keycloak after version upgrade.

On click on the master console realms in UI it displayed "An unexpected Server Error has Occurred"

On selecting any realms only General tab is available, unable to do any realm configurations.

Pod Logs:
```
←[0m←[0m08:03:03,398 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
←[0m←[0m08:03:03,398 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990/
←[0m←[31m08:18:07,770 ERROR [org.keycloak.services] (Timer-2) KC-SERVICES0089: Failed to run scheduled task ClearExpiredUserSessions: java.lang.NullPointerException
        at org.keycloak.keycloak-model-infinispan@16.1.1//org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:266)
        at org.keycloak.keycloak-model-infinispan@16.1.1//org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:414)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.keycloak.keycloak-server-spi-private@16.1.1//org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
        at org.keycloak.keycloak-model-infinispan@16.1.1//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.removeAllExpired(InfinispanUserSessionProvider.java:584)
        at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.scheduled.ClearExpiredUserSessions.run(ClearExpiredUserSessions.java:39)
        at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.scheduled.ScheduledTaskRunner.runTask(ScheduledTaskRunner.java:74)
        at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:55)
        at org.keycloak.keycloak-services@16.1.1//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

### Version

16.1.1

### Expected behavior

Should be able to view the realms page without an issue and should be able to configure realm settings.

### Actual behavior

Displays error and unable to do realm configurations.

**Comment by sathishkumar3009** [comment]
Can someone assist us on this issue.

**Comment by trixpan** [comment]
@sathishkumar3009 usually keycloak doesn't support old versions. 16.1.1 is ancient. You will be more likely to get assistance by using 19.0.0 or 18.0.2 on your tests

**Comment by sathishkumar3009** [comment]
@trixpan - We planned to update first without quarks. Will update to latest 18.0.2 once this is success.
Currently facing below issue. Can you help me.

09:53:29,766 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (ServerService Thread Pool -- 64) ERROR: column realmentit0_.default_role does not exist
  Hint: Perhaps you meant to reference the column "realmentit0_.default_locale".
  Position: 720
09:53:29,770 INFO  [org.hibernate.event.internal.DefaultLoadEventListener] (ServerService Thread Pool -- 64) HHH000327: Error performing load command : org.hibernate.exception.SQLGrammarException: could not extract ResultSet
09:53:29,785 FATAL [org.keycloak.services] (ServerService Thread Pool -- 64) Error during startup: org.keycloak.models.ModelException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.keycloak.keycloak-model-jpa@16.1.1//org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:84)
        at org.keycloak.keycloak-model-jpa@16.1.1//org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
        at javax.persistence.api@2.2.3//com.sun.proxy.$Proxy97.find(Unknown Source)

**Comment by sathishkumar3009** [comment]
@trixpan - In the version 12.0.4 in postgresDB there are 94 tables, whereas in 16.1.1 in pogtgresDB there are 92 tables only.
So during this upgradation from lower to higher version, how does schema is copied?

**Comment by sathishkumar3009** [comment]
@txixpan- When trying to access the keycloak from other portal application, getting below error. Please help me how to overcome from this issue.

2022-08-16 10:55:02,751 WARN  [org.keycloak.events] (executor-thread-6) type=LOGIN_ERROR, realmId=integration, clientId=saas-portal-fabric, userId=63169bdd-1303-4b77-1abaa-a44d6256bcbf, ipAddress=10.23..., error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://dev.portal.saas.temenos.cloud/authService/100000002/oauth2/callback, code_id=bb4952a0-4aa2-432d-b665-114019e351f8, username=balaji.manickam@temenos.com, authSessionParentId=bb4952a0-4aa2-432d-b665-114019e351f8, authSessionTabId=o24Go5Ofnj4
2022-08-16 12:13:19,838 WARN  [org.keycloak.events] (executor-thread-10) type=CODE_TO_TOKEN_ERROR, realmId=integration, clientId=saas-portal-fabric, userId=null, ipAddress=....., error=invalid_code, grant_type=authorization_code, code_id=80322e8c-cc8b-484b-8f83-583e0e2845dde, client_auth_method=client-secret

Network F12 Logs:
{"details":{"message":"Request failed to url: https://keycloak.eun1.shs.saas.temenos.cloud/, path: /realms/integration/protocol/openid-connect/token, response code: 400, response body: {\"error\":\"invalid_grant\",\"error_description\":\"Code not valid\"}","errcode":400,"errmsg":"com.kony.api.client.RestClientException: Request failed to url: https://keycloak.eun1.shs.saas.temenos.cloud/, path: /realms/integration/protocol/openid-connect/token, response code: 400, response body: {\"error\":\"invalid_grant\",\"error_description\":\"Code not valid\"}"},"httpstatus":"Unauthorized","requestid":"5edd7ca0-d7a5-433c-8032-39fcdb6eee52","domain":"AUTH","code":-68,"mfcode":"Auth-68","message":"Failed while invoking token endpoint. Recheck token endpoint, Client Authentication scheme and client secret"}

**Comment by sathishkumar3009** [comment]
@trixpan Could you please help me and I found the issue. When the replica count is more than 1 for High Availability and that causing the issue.
Can I have the solution to use HA with this latest version?

**Comment by sathishkumar3009** [comment]
Can someone help me on this issue.

**Comment by sathishkumar3009** [comment]
@abbra Could you please help me on this.

**Comment by sathishkumar3009** [comment]
@trixpan - HA is not supported in the latest version?

**Comment by stianst** [comment]
Seems like you have multiple Keycloak nodes, but don't have clustering working properly.
