### ISSUE TITLE
Can't import realm when the configuration is referencing JS components and providers

### ISSUE THREAD

**Issue by mkucharsky** [keycloak/keycloak#13342]
### Describe the bug

I would like to import my realms configuration.
I exported configuration with command:
```
kc.sh export --file all-realms.json --users skip
```
When I run keycloak in docker, application start and terminate after a while without any errrors:
```
    docker run \
  --name keycloak \
  -e KC_HOSTNAME=my-hostname.com \
  -e KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/keystore.jks \
  -e KC_HTTPS_KEY_STORE_PASSWORD=pass \
  -v /certs/keystore.jks:/opt/keycloak/conf/keystore.jks \
  -v /realm:/opt/keycloak/data/import \
  -p 8443:8443 \
  quay.io/keycloak/keycloak \
  -v \
  start-dev \
  -Dkeycloak.migration.action=import \
  -Dkeycloak.migration.provider=singleFile \
  -Dkeycloak.migration.strategy=OVERWRITE_EXISTING \
  -Dkeycloak.migration.file=/opt/keycloak/data/import/all-realms.json
```
Logs:
```
Updating the configuration and installing your custom providers, if any. Please wait.

2022-07-26 17:29:18,176 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 10901ms

2022-07-26 17:29:21,746 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: dev-crm-hub-keycloak-quarkus.dev.pl.insim.biz, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false

2022-07-26 17:29:22,676 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal

2022-07-26 17:29:22,853 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled

2022-07-26 17:29:22,989 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'

2022-07-26 17:29:23,451 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final

2022-07-26 17:29:25,577 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml

2022-07-26 17:29:28,898 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_323266, Site name: null

2022-07-26 17:29:29,313 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: OVERWRITE_EXISTING

2022-07-26 17:29:29,313 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /opt/keycloak/data/import/aaa.json

2022-07-26 17:29:31,611 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'master' imported

2022-07-26 17:29:32,896 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'crmhub' imported

2022-07-26 17:29:33,163 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully

2022-07-26 17:29:33,662 INFO  [io.quarkus] (main) Keycloak 18.0.2 on JVM (powered by Quarkus 2.7.5.Final) started in 15.318s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8443

2022-07-26 17:29:33,663 INFO  [io.quarkus] (main) Profile dev activated. 

2022-07-26 17:29:33,663 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]

2022-07-26 17:29:33,670 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.

2022-07-26 17:29:33,931 INFO  [io.quarkus] (main) Keycloak stopped in 0.261s
```

I also tried to export each realm separately, put it in the ```data/import``` directory and use the ``` --import-realm ``` switch however importing realm master is skipped because it already exists

### Version

18.0.2

### Expected behavior

Applicarion run without terminate

### Actual behavior

Application terminate without any errors

**Comment by axi92** [comment]
I have the same issue, I cant understand how nobody else got this issue? Is nobody using the master realm for production?

**Comment by gerardborst** [comment]
Same error. If I import the master + 2 realms it went fine but if I add a service account with to sarealm I get this error.

```
keycloak_1  | Updating the configuration and installing your custom providers, if any. Please wait.
keycloak_1  | 2022-10-28 19:10:19,412 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 7320ms
keycloak_1  | 2022-10-28 19:10:20,954 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
keycloak_1  | 2022-10-28 19:10:22,063 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
keycloak_1  | 2022-10-28 19:10:23,284 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
keycloak_1  | 2022-10-28 19:10:23,398 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
keycloak_1  | 2022-10-28 19:10:23,436 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
keycloak_1  | 2022-10-28 19:10:23,730 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
keycloak_1  | 2022-10-28 19:10:25,101 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
keycloak_1  | 2022-10-28 19:10:27,533 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_3660, Site name: null
keycloak_1  | 2022-10-28 19:10:27,633 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory /opt/keycloak/data/import
keycloak_1  | 2022-10-28 19:10:27,635 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: OVERWRITE_EXISTING
keycloak_1  | 2022-10-28 19:10:30,113 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'master' imported
keycloak_1  | 2022-10-28 19:10:31,330 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'oauth-stub' imported
keycloak_1  | 2022-10-28 19:10:32,184 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'sarealm' imported
keycloak_1  | 2022-10-28 19:10:32,514 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
keycloak_1  | 2022-10-28 19:10:32,514 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Script upload is disabled
keycloak_1  | 2022-10-28 19:10:32,514 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

docker-compose:
```
keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      TZ: Europe/Amsterdam
    ports:
      - 9080:8080
    command:
    - start-dev
    - -Dkeycloak.migration.action=import
    - -Dkeycloak.migration.provider=dir
    - -Dkeycloak.migration.dir=/opt/keycloak/data/import
    volumes:
    - $PWD/dev/keycloak/import:/opt/keycloak/data/import
```
[import.zip](https://github.com/keycloak/keycloak/files/9890597/import.zip)

**Comment by gerardborst** [comment]
If I don't enable Authorization on creating service accounts as in the image the import goes without errors.

![image](https://user-images.githubusercontent.com/56296132/199457514-73cfc573-76ed-4a58-87e2-e74fa982a7da.png)

**Comment by vramik** [comment]
The issue seems to be related to https://github.com/keycloak/keycloak/issues/9865

In Keycloak 18 was removed "upload scripts" feature.  While debugging I found following stacktrace:
```
"main"
	at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.throwCanNotUpdatePolicy(JSPolicyProviderFactory.java:130)
	at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.onImport(JSPolicyProviderFactory.java:72)
	at org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:1243)
	at org.keycloak.authorization.AuthorizationProvider$3.create(AuthorizationProvider.java:350)
	at org.keycloak.models.utils.RepresentationToModel.importPolicies(RepresentationToModel.java:1165)
	at org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:1111)
	at org.keycloak.models.utils.RepresentationToModel.importAuthorizationSettings(RepresentationToModel.java:1058)
	at org.keycloak.services.managers.RealmManager.setupClientServiceAccountsAndAuthorizationOnImport(RealmManager.java:776)
	at org.keycloak.exportimport.dir.DirImportProvider$4.runExportImportTask(DirImportProvider.java:186)
	at org.keycloak.exportimport.util.ExportImportSessionTask.run(ExportImportSessionTask.java:35)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
	at org.keycloak.models.utils.KeycloakModelUtils$$Lambda$1157.0x0000000801a1e340.run
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
	at org.keycloak.exportimport.dir.DirImportProvider.importRealm(DirImportProvider.java:181)
	at org.keycloak.exportimport.dir.DirImportProvider.importModel(DirImportProvider.java:100)
	at org.keycloak.exportimport.ExportImportManager.runImport(ExportImportManager.java:102)
	at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:212)
	at org.keycloak.services.resources.KeycloakApplication$2.lambda$run$0(KeycloakApplication.java:146)
	at org.keycloak.services.resources.KeycloakApplication$2$$Lambda$1186.0x0000000801a43478.run
	at org.keycloak.models.dblock.DBLockGlobalLockProvider.withLock(DBLockGlobalLockProvider.java:77)
	at org.keycloak.models.locking.GlobalLockProvider.withLock(GlobalLockProvider.java:45)
	at org.keycloak.services.resources.KeycloakApplication$2.run(KeycloakApplication.java:146)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
	at org.keycloak.models.utils.KeycloakModelUtils$$Lambda$1157.0x0000000801a1e340.run
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:142)
	at org.keycloak.services.resources.KeycloakApplication$$Lambda$317.0x000000080141e8d0.run
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy
	at io.quarkus.runner.ApplicationImpl.doStart
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:98)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
	at org.keycloak.quarkus.runtime.cli.command.AbstractExportImportCommand.run(AbstractExportImportCommand.java:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:94)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	at java.lang.invoke.LambdaForm$DMH.0x0000000801005000.invokeStatic(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH.0x0000000801006400.invoke(LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

It seems that during import it's not correctly handled. Workaround would be to manually edit the exported file(s).

**Comment by pedroigor** [comment]
I don't know if we will improve this now but rely on the workaround to remove any JS policy/mapper/authenticator from the JSON file.

For that reason, we are setting it as a low priority.
