### ISSUE TITLE
o.k.adapters.OAuthRequestAuthenticator : failed to turn code into token when user trying to login

### ISSUE THREAD

**Issue by ajitlawhate** [keycloak/keycloak#13357]
### Describe the bug

We have created the application which exposes the 2 API's and we have secured those with keycloak.
Keycloak client is created for this application and uses **Client ID and secret** for client Authenticator.

Sometimes getting the 403 error as below when we enter the user login credentials in login screen,
If we refresh the same tab then user logs in to expected pages without reentering the credentials. May be there is some issue with the keycloak cookies not sure.

**Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 27 12:41:21 IST 2022
There was an unexpected error (type=Forbidden, status=403).
No message available**

In application pod logs below errors observed:

2022-07-27 12:40:11.228 ERROR 25 --- [io-8080-exec-10] o.k.adapters.OAuthRequestAuthenticator   : failed to turn code into token

java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(Unknown Source) ~[na:na]
        at java.base/java.net.SocketInputStream.read(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source) ~[na:na]
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161) ~[httpcore-4.4.9.jar!/:4.4.9]
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82) ~[httpcore-4.4.9.jar!/:4.4.9]
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:278) ~[httpcore-4.4.9.jar!/:4.4.9]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.9.jar!/:4.4.9]
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:286) ~[httpcore-4.4.9.jar!/:4.4.9]
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:230) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.9.jar!/:4.4.9]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.9.jar!/:4.4.9]
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:684) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.keycloak.adapters.ServerRequest.invokeAccessCodeToToken(ServerRequest.java:111) ~[keycloak-adapter-core-14.0.0.jar!/:14.0.0]
        at org.keycloak.adapters.OAuthRequestAuthenticator.resolveCode(OAuthRequestAuthenticator.java:335) ~[keycloak-adapter-core-14.0.0.jar!/:14.0.0]
        at org.keycloak.adapters.OAuthRequestAuthenticator.authenticate(OAuthRequestAuthenticator.java:280) ~[keycloak-adapter-core-14.0.0.jar!/:14.0.0]
        at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:138) ~[keycloak-adapter-core-14.0.0.jar!/:14.0.0]
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.authenticateInternal(AbstractKeycloakAuthenticatorValve.java:203) ~[spring-boot-container-bundle-14.0.0.jar!/:14.0.0]
        at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.authenticate(KeycloakAuthenticatorValve.java:50) ~[spring-boot-container-bundle-14.0.0.jar!/:14.0.0]
        at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.doAuthenticate(KeycloakAuthenticatorValve.java:57) ~[spring-boot-container-bundle-14.0.0.jar!/:14.0.0]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:578) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181) ~[spring-boot-container-bundle-14.0.0.jar!/:14.0.0]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2022-07-27 12:41:21.715 ERROR 25 --- [nio-8080-exec-2] o.k.adapters.OAuthRequestAuthenticator   : failed to turn code into token
2022-07-27 12:41:21.716 ERROR 25 --- [nio-8080-exec-2] o.k.adapters.OAuthRequestAuthenticator   : status from server: 400
2022-07-27 12:41:21.716 ERROR 25 --- [nio-8080-exec-2] o.k.adapters.OAuthRequestAuthenticator   :    {"error":"invalid_grant","error_description":"Code not valid"}

Errors in keycloak pod logs as below:
2022-07-27 12:41:21,712 INFO  [] (default task-208) Audit login event :
{  "level" : "audit",  "timestamp" : "Wed Jul 27 12:41:21 IST 2022",  "user_id" : null,  "tenant_id" : "system",  "audit_action" : "C
ODE_TO_TOKEN_ERROR",  "source_ip" : "X.X.X.X",  "audit_action_result" : "FAILED",  "audit_action_message" : "invalid_code",  "a
udit_object_type" : "CODE_TO_TOKEN_ERROR",  "audit_object_tenant_id" : "system",  "audit_action_data" : {    "original" : { },    "ne
w" : { },    "changed" : { },    "input_fields" : { },    "read_data" : {      "eventdata" : "type=CODE_TO_TOKEN_ERROR, realmId=11adf
a22-eb4c-43e3-8816-ec3cbc3cc9bb, clientId=userauth-tester, userId=null, ipAddress=X.X.X.X, error=invalid_code"    }  }}

2022-07-27 12:41:21,712 WARN  [org.keycloak.events] (default task-208) type=CODE_TO_TOKEN_ERROR, realmId=11adfa22-eb4c-43e3-8816-ec3c
bc3cc9bb, clientId=userauth-tester, userId=null, ipAddress=X.X.X.X, error=invalid_code, grant_type=authorization_code, code_id=
b5c15eef-b837-4d4f-8eb9-e73b180d83b2, client_auth_method=client-secret

### Version

14

### Expected behavior

User should be able to login without any issues.

### Actual behavior

Sometimes getting the 403 error even if user credentials are valid.

### How to Reproduce?

Launch the userauth application in server
Create the respective user in realm
access the userauth url- https://<<host>>/userauth-tester/
enter the user credentials.

### Anything else?

It gets reproduced after multiple login attempts and sometimes when session is idle for sometime.
Maybe there is some issue with the keycloak cookies stored in browser.

**Comment by stianst** [comment]
Looks more like an issue in o.k.adapters.OAuthRequestAuthenticator or in how you are using it than an issue in Keycloak. The error message from Keycloak is saying that the app/library is sending an invalid code during the oauth flow.
