### ISSUE TITLE
No BouncyCastleProvider found with Keyclaok 19

### ISSUE THREAD

**Issue by fabian-froehlich** [keycloak/keycloak#13395]
### Describe the bug

An exception is thrown when I want to create an Credential with the following snipped. This code works with keycloak 18.0.2.
Did I miss something in the migration guide? I already tried to include the legacy modules with no success.

```
import org.junit.jupiter.api.Test;
import org.keycloak.credential.CredentialModel;
import org.keycloak.credential.hash.PasswordHashProvider;
import org.keycloak.credential.hash.Pbkdf2PasswordHashProvider;
import org.keycloak.credential.hash.Pbkdf2Sha256PasswordHashProviderFactory;

public class PasswordCredentialTest {

  @Test
  void myTest() {
    PasswordHashProvider hash = new Pbkdf2PasswordHashProvider(
      Pbkdf2Sha256PasswordHashProviderFactory.ID,
      Pbkdf2Sha256PasswordHashProviderFactory.PBKDF2_ALGORITHM,
      Pbkdf2Sha256PasswordHashProviderFactory.DEFAULT_ITERATIONS
    );
    CredentialModel credential = hash.encodedCredential(
      "abc",
      Pbkdf2Sha256PasswordHashProviderFactory.DEFAULT_ITERATIONS
    );
  }
}
```
```
java.lang.ExceptionInInitializerError
	at org.keycloak.credential.hash.Pbkdf2PasswordHashProvider.getSecretKeyFactory(Pbkdf2PasswordHashProvider.java:129)
	at org.keycloak.credential.hash.Pbkdf2PasswordHashProvider.encodedCredential(Pbkdf2PasswordHashProvider.java:111)
	at org.keycloak.credential.hash.Pbkdf2PasswordHashProvider.encodedCredential(Pbkdf2PasswordHashProvider.java:75)
	...
Caused by: java.lang.IllegalStateException: Illegal state. Please init first before obtaining provider
	at org.keycloak.common.crypto.CryptoIntegration.getProvider(CryptoIntegration.java:40)
	at org.keycloak.common.util.BouncyIntegration.loadProvider(BouncyIntegration.java:38)
	at org.keycloak.common.util.BouncyIntegration.<clinit>(BouncyIntegration.java:35)
	... 74 more
```

The issue happens inside static method `CryptoProvider.getProvider()` because the init Method of the `CryptoProvider` was never called.  Doing it by myself (`CryptoIntegration.init(this.getClass().getClassLoader());`) does not work `java.lang.IllegalStateException: Not able to load any cryptoProvider with the classLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa`

```
dependency:tree
[INFO] +- org.keycloak:keycloak-admin-client:jar:19.0.0:compile
[INFO] |  +- org.keycloak:keycloak-core:jar:19.0.0:compile
[INFO] |  +- org.keycloak:keycloak-common:jar:19.0.0:compile
[INFO] |  +- org.jboss.resteasy:resteasy-client:jar:3.15.3.Final:compile
[INFO] |  |  +- org.jboss.resteasy:resteasy-jaxrs:jar:3.15.3.Final:compile
[INFO] |  |  |  +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  |  +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  |  |  +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:2.0.1.Final:compile
[INFO] |  |  |  \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  \- commons-io:commons-io:jar:2.11.0:compile
[INFO] |  +- org.jboss.resteasy:resteasy-multipart-provider:jar:3.13.2.Final:compile
[INFO] |  |  \- org.apache.james:apache-mime4j:jar:0.6:compile
[INFO] |  +- org.jboss.resteasy:resteasy-jackson2-provider:jar:3.13.2.Final:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.10.5:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.10.5:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.5:compile
[INFO] |  |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- com.github.fge:json-patch:jar:1.9:compile
[INFO] |  |  |  \- com.github.fge:jackson-coreutils:jar:1.6:compile
[INFO] |  |  |     \- com.github.fge:msg-simple:jar:1.1:compile
[INFO] |  |  |        \- com.github.fge:btf:jar:1.2:compile
[INFO] |  |  \- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |     \- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  \- org.jboss.resteasy:resteasy-jaxb-provider:jar:3.13.2.Final:compile
[INFO] |     +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
[INFO] |     \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile
[INFO] |     \- org.checkerframework:checker-qual:jar:3.22.0:compile
[INFO] +- org.keycloak:keycloak-server-spi:jar:19.0.0:provided
[INFO] +- org.keycloak:keycloak-server-spi-private:jar:19.0.0:provided
[INFO] |  \- com.github.ua-parser:uap-java:jar:1.5.2:provided
[INFO] |     +- org.yaml:snakeyaml:jar:1.30:provided
[INFO] |     \- org.apache.commons:commons-collections4:jar:4.1:provided
[INFO] +- org.projectlombok:lombok:jar:1.18.24:provided
[INFO] +- org.jboss.logging:jboss-logging:jar:3.5.0.Final:provided
[INFO] \- org.junit.jupiter:junit-jupiter:jar:5.9.0:test
[INFO]    +- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test
[INFO]    |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO]    |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test
[INFO]    |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO]    +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test
[INFO]    \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test
[INFO]       \- org.junit.platform:junit-platform-engine:jar:1.9.0:test
```

### Version

19

### Anything else?

We use this snipped inside our keycloak privisioner projekt where we add users from json representation.

**Comment by lexcao** [comment]
Hi, @fabian-froehlich 
I found this PR https://github.com/keycloak/keycloak/pull/12692 adding related changes.

You need to init the `CryptoIntegration` first, as well as add the default implementation.
```
CryptoIntegration.init(this.getClass().getClassLoader());
```

Could you please try adding this dependency as the default implementation of crypto?
```
<dependency>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-crypto-default</artifactId>
    <version>19.0.0</version>
</dependency>
```

**Comment by fabian-froehlich** [comment]
Hello @lexcao ,
thank you for your immediate support. It works with the steps you mentioned. Thank you very much!

Maybe this change should be explicitly pointed out in the changelog?
