### ISSUE TITLE
Unable to load templates from custom Authenticator

### ISSUE THREAD

**Issue by trixpan** [keycloak/keycloak#13414]
### Describe the bug

Upon upgrading to Keycloak 19 custom templates packaged under `src/main/resources/theme-resources/templates` no longer load.

### Version

19.0.0

### Expected behavior

template loaded

### Actual behavior

```
2022-07-29 07:46:22,422 ERROR [org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider] (executor-thread-1) Failed to process template: org.keycloak.theme.FreeMarkerException: Failed to process template login-choose-user.ftl
	at org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:71)
	at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.processTemplate(FreeMarkerLoginFormsProvider.java:524)
	at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createForm(FreeMarkerLoginFormsProvider.java:326)

...

Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "login-choose-user.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.FreeMarkerUtil$ThemeTemplateLoader@471b4818.
	at freemarker.template.Configuration.getTemplate(Configuration.java:2883)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2703)
	at org.keycloak.theme.FreeMarkerUtil.getTemplate(FreeMarkerUtil.java:85)
	at org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:58)
	... 66 more

```

**Comment by trixpan** [comment]
Seems linked to https://github.com/keycloak/keycloak/issues/13278

**Comment by tarasstasyuk** [comment]
seems the same as [#13401](https://github.com/keycloak/keycloak/issues/13401)

**Comment by trixpan** [comment]
Duplicate of #13401
