### ISSUE TITLE
uncaught exception: SSLEngine closed already

### ISSUE THREAD

**Issue by onlookor** [keycloak/keycloak#13454]
## Describe the bug

Http connection is disabled. No reverse proxy exists. Firefox 103. 0.1 64-bit used without proxy setting.
Firefox https://localhost:8083 connects to the welcome page with a link to Administration Console (https://localhost:8083/admin) and other links to Document, Mailing List, Keycloak Projects ... etc.
Click the Administration Console link, it jumps to https://localhost:8083/admin/master/console/, and show "Loading the admin console" with a spinner. Since then, browser gets no further response.
After a while - seconds to minutes - the keycloak server log reports "SSLEngine closed already". this is not reproduced everytime:
> 2022-08-01 11:24:20,892 ERROR [org.jboss.threads.errors] (executor-thread-2) Thread Thread[executor-thread-2,5,main] threw an uncaught exception: java.lang.RuntimeException: java.io.IOException: java.io.IOException: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext$VertxHttpAsyncResponse.vertxFlush(VertxHttpRequest.java:396) at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext$VertxHttpAsyncResponse$1.run(VertxHttpRequest.java:326)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: java.io.IOException: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
        at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.close(VertxOutputStream.java:128)
        at io.quarkus.resteasy.runtime.standalone.VertxHttpResponse.finish(VertxHttpResponse.java:145)
        at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext$VertxHttpAsyncResponse.vertxFlush(VertxHttpRequest.java:394)
        ... 8 more
Caused by: java.io.IOException: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
        at io.quarkus.resteasy.runtime.standalone.VertxBlockingOutput.write(VertxBlockingOutput.java:74)
        at io.quarkus.resteasy.runtime.standalone.VertxHttpResponse.writeBlocking(VertxHttpResponse.java:172)
        at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.close(VertxOutputStream.java:126)
        ... 10 more
Caused by: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
        at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:859)
        at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:798)
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:779)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:189)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
        at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.writeHeaders(VertxHttp2ConnectionHandler.java:205)
        at io.vertx.core.http.impl.VertxHttp2Stream.doWriteHeaders(VertxHttp2Stream.java:189)
        at io.vertx.core.http.impl.Http2ServerStream.doWriteHeaders(Http2ServerStream.java:118)
        at io.vertx.core.http.impl.VertxHttp2Stream.lambda$writeHeaders$5(VertxHttp2Stream.java:183)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 2 more
2022-08-01 11:24:20,910 ERROR [org.jboss.threads.errors] (executor-thread-1) Thread Thread[executor-thread-1,5,main] threw an uncaught exception: java.lang.RuntimeException: java.io.IOException: java.io.IOException: java.nio.channels.ClosedChannelException at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext$VertxHttpAsyncResponse.vertxFlush(VertxHttpRequest.java:396) at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext$VertxHttpAsyncResponse$1.run(VertxHttpRequest.java:326)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: java.io.IOException: java.nio.channels.ClosedChannelException
        at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.close(VertxOutputStream.java:128)
        at io.quarkus.resteasy.runtime.standalone.VertxHttpResponse.finish(VertxHttpResponse.java:145)
        at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext$VertxHttpAsyncResponse.vertxFlush(VertxHttpRequest.java:394)
        ... 8 more
Caused by: java.io.IOException: java.nio.channels.ClosedChannelException
        at io.quarkus.resteasy.runtime.standalone.VertxBlockingOutput.write(VertxBlockingOutput.java:74)
        at io.quarkus.resteasy.runtime.standalone.VertxHttpResponse.writeBlocking(VertxHttpResponse.java:172)
        at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.close(VertxOutputStream.java:126)
        ... 10 more
Caused by: java.nio.channels.ClosedChannelException
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1064)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 2 more
>

## Version

19.0.1

## Expected behavior

show the admin console login ui.

## Actual behavior

No response

## How to Reproduce?

See the bug description and configurations below.

### dockerfile
> FROM quay.io/keycloak/keycloak:latest as builder
ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
RUN /opt/keycloak/bin/kc.sh build
FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak
server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN keytool -genkeypair -storepass mSls@75c -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=login.ways.dev" -alias sso -ext "SAN:c=DNS:login.ways.dev,IP:10.210.48.199" -keystore conf/server.keystore
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
>

### compose file
> name: mfasso
services:
  keycloak-db:
    build:
      dockerfile: database.dockerfile
    image: onlookor/postgres
    container_name: keycloak_postgresql
    hostname: ssodb
    restart: always
    env_file: keycloak.env
  keycloak:
    build:
      dockerfile: keycloak.dockerfile
    image: onlookor/keycloak
    hostname: login
    container_name: keycloak
    command: 
      - "start"
      - "--optimized"
      - "--db-url=jdbc:postgresql://keycloak-db:5432/keycloak"
      - "--db-username=keycloak"
      - "--db-password=test"
      - "--https-certificate-file=/certs/tls.crt"
      - "--https-certificate-key-file=/certs/tls.key"
    restart: always
    depends_on: [keycloak-db]
    env_file: keycloak.env
    ports: ["8083:8443"]
    volumes: [../certs:/certs]
>

### environments
> POSTGRES_DB=keycloak
POSTGRES_PASSWORD=test		
POSTGRES_USER=keycloak
KC_HOSTNAME=10.210.48.199
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=sfm34NHQC.
>

#### Any suggestion would be appreciated.

**Comment by darius-m** [comment]
I doubt that anyone can help you just from the Java backtrace. Please provide more information on the reverse proxy's configuration and the client that you use.
From the backtrace message it appears that the connection is coming from a client or reverse proxy that expects a plain HTTP connection, but connects to the server's HTTPS port.

**Comment by pedroigor** [comment]
@onlookor I'm not sure if it is related to https://github.com/keycloak/keycloak/issues/13315.

If you can provide more details, I can try them out and see what might be happening. The information mentioned by @darius-m should help. I would just add to also provide the server configuration options.

**Comment by onlookor** [comment]
> 

No reverse proxy exists.
Client is Firefox 103.0.1 64-bit without proxy setting. There is not a "client" so-called in OIDC or something like. I just run a keycloak container with simplest configuration and try my first login as admin with a browser. That's why I followed an issue about quick start.
I supplemented the issue description.
Thank you.

**Comment by onlookor** [comment]
> 

Thanks for your concern.
I supplemented the issue description.
Let me know if additional information is needed.
Thanks again.

**Comment by onlookor** [comment]
> I doubt that anyone can help you just from the Java backtrace. Please provide more information on the reverse proxy's configuration and the client that you use. From the backtrace message it appears that the connection is coming from a client or reverse proxy that expects a plain HTTP connection, but connects to the server's HTTPS port.

No reverse proxy exists.
Client is Firefox 103.0.1 64-bit without proxy setting. There is not a "client" so-called in OIDC or something like. I just run a keycloak container with simplest configuration and try my first login as admin with a browser. That's why I followed an issue about quick start.
I supplemented the issue description.
Thank you.

**Comment by onlookor** [comment]
> @onlookor I'm not sure if it is related to #13315.
> 
> If you can provide more details, I can try them out and see what might be happening. The information mentioned by @darius-m should help. I would just add to also provide the server configuration options.

Thanks for your concern.
I supplemented the issue description.
Let me know if additional information is needed.
Thanks again.

**Comment by darius-m** [comment]
Not sure how Quarkus expects the configuration to be done (have currently only used WildFly), but there may be an issue with the port forwarding you perform - `8083:8443`, since it appears to be done transparently from the server (you are basically creating a reverse proxy with Docker). Keycloak may try to create links that use the regular `8443` port, instead of the one you expect - `8083`. Try to have both the port forward and server use the same port - either expose port `8443` directly or [change the HTTPS port](https://www.keycloak.org/server/enabletls#_switching_the_https_port).

To confirm what pages are accessed, go to the browser's Developer tools (press `F12`) and then go to the `Network` tab and see what pages are being loaded.

**Comment by pedroigor** [comment]
+1 to @darius-m.

You should be able to run the server as follows, similar to what you are trying to achieve:

```
docker run --name keycloak -p 3000:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=password -e KC_HOSTNAME=localhost -e KC_HTTP_ENABLED=true -e KC_HOSTNAME_PORT=3000 -e KC_HOSTNAME_STRICT_HTTPS=false quay.io/keycloak/keycloak start
```

Note the `hostname-port` option being set to the port bound to your host.

**Comment by pedroigor** [comment]
More information about running the container using a different port here https://github.com/keycloak/keycloak/pull/13570.
