### ISSUE TITLE
Deny Access Authenticator triggers exception when used in Direct Grant flow

### ISSUE THREAD

**Issue by MetroMarv** [keycloak/keycloak#13483]
### Describe the bug

When the "Deny Access" authenticator is used within a direct grant flow, an exception is triggered and the response code is 500.

### Version

- 18.0.2
- 19.0.1

### Expected behavior

- Response code HTTP 401
- error description as configured in the "Deny Access" authenticator config

### Actual behavior

- Response code HTTP 500
- Response body
```
{
  "error": "unknown_error"
}
```
- Stacktrace in the keycloak log
```
2022-08-02 09:14:42,076 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: java.lang.IllegalArgumentException: RESTEASY003715: path was null
	at org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.path(ResteasyUriBuilderImpl.java:382)
	at org.keycloak.authentication.AuthenticationProcessor$Result.getActionUrl(AuthenticationProcessor.java:562)
	at org.keycloak.authentication.AuthenticationProcessor$Result.form(AuthenticationProcessor.java:536)
	at org.keycloak.authentication.authenticators.access.DenyAccessAuthenticator.authenticate(DenyAccessAuthenticator.java:49)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:460)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:264)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1030)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.resourceOwnerPasswordCredentialsGrant(TokenEndpoint.java:603)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[...]

2022-08-02 09:14:42,086 WARN  [io.agroal.pool] (executor-thread-13) Datasource '<default>': JDBC resources leaked: 2 ResultSet(s) and 2 Statement(s)

```

### How to Reproduce?

- create a new flow for direct grant flow (by copying the exiting direct grant flow):
![image](https://user-images.githubusercontent.com/9006725/182340446-f2eda466-5a8f-40f3-9346-4c688cdd387e.png)
- make the new flow the new default flow for the direct grant flow in the "Bindings" tab
- fetch a token using the `/realms/master/protocol/openid-connect/token` endpoint and following form-urlencoded payload:
```
username:admin
password:admin
grant_type:password
client_id:<some public client>
```

**Comment by lexcao** [comment]
Hi @MetroMarv 
It seems like a duplicated issue.
Could you please check this out?
https://github.com/keycloak/keycloak/issues/13368

**Comment by MetroMarv** [comment]
@lexcao you're totally right. It's a duplicate.
