### ISSUE TITLE
IPv6 database `HHH000342: Could not obtain connection to query metadata`

### ISSUE THREAD

**Issue by tacerus** [keycloak/keycloak#13599]
### Describe the bug

Hello,

the server will not initiate a database connection if configured to connect to PostgreSQL over IPv6.

### Version

19.0.1

### Expected behavior

IPv6 should work the same way IPv4 does, with no extra burden.

If I configure the server to use IPv4, it starts up fine:

`keycloak.conf`:

```
db=postgres
db-username=keycloak
db-password=keycloak
db-url=jdbc:postgresql://localhost/keycloak   #works fine, both with the hostname and with 127.0.0.1
```

```
$ JAVA_HOME=/opt/jre sudo -Eu keycloak bin/kc.sh start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
2022-08-07 14:49:12,179 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 6907ms
2022-08-07 14:49:13,526 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: ::1, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-08-07 14:49:14,740 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-08-07 14:49:15,946 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-08-07 14:49:16,090 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-08-07 14:49:16,134 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-08-07 14:49:16,647 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-08-07 14:49:19,064 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2022-08-07 14:49:31,609 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_867761, Site name: null
2022-08-07 14:49:31,744 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2022-08-07 14:49:33,739 INFO  [io.quarkus] (main) Keycloak 19.0.1 on JVM (powered by Quarkus 2.7.6.Final) started in 21.442s. Listening on: http://0.0.0.0:8080
2022-08-07 14:49:33,740 INFO  [io.quarkus] (main) Profile dev activated. 
2022-08-07 14:49:33,740 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-08-07 14:49:33,744 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
^C2022-08-07 14:49:54,954 INFO  [io.quarkus] (main) Keycloak stopped in 0.169s
```

### Actual behavior

This `keycloak.conf`, utilizing IPv6:

```
db=postgres
db-username=keycloak
db-password=keycloak
db-url=jdbc:postgresql://ipv6-localhost/keycloak   #here I tried all three formats: ::1, [::1], and an /etc/hosts configured hostname resolving to ::1
```

results in:

```
$ JAVA_HOME=/opt/jre sudo -Eu keycloak bin/kc.sh start-dev
2022-08-07 14:41:14,702 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: ::1, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-08-07 14:41:15,902 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-08-07 14:41:16,629 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The connection attempt failed.
2022-08-07 14:41:16,630 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:400)
        at org.postgresql.Driver.connect(Driver.java:259)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
        at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: ipv6-localhost
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
        ... 17 more

2022-08-07 14:41:17,268 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-08-07 14:41:17,276 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-08-07 14:41:17,286 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-08-07 14:41:17,392 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The connection attempt failed.
2022-08-07 14:41:17,526 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-08-07 14:41:18,084 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2022-08-07 14:41:18,084 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-08-07 14:41:18,084 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: The connection attempt failed.
2022-08-07 14:41:18,084 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ipv6-localhost
2022-08-07 14:41:18,084 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### How to Reproduce?

1. Install Temurin OpenJDK 18 (binary/tar release)
2. Install Keycloak 19.0.1 (binary/tar release)
3. Configure a PostgreSQL user and database for Keycloak
4. Set a `pg_hba` entry permitting IPv6 connectivity by the Keycloak user to the Keycloak database with md5 authentication
5. Configure Keycloak with `db-url=jdbc:postgresql://[::1]/keycloak` (alternatively a hostname resolving only to an IPv6 address)
6. Attempt to start it with `kc.sh start-dev`

### Anything else?

- ~~The Keycloak system seems to prefer resolving hostnames to IPv4. For example, if my system is configured to prefer IPv6, and resolves `localhost` to `::1` by default (tested with for example `ping`,`curl`, or similar standard tools), Keycloak will still prefer to resolve it to `127.0.0.1` - the only cure is to configure a DNS name with no A records or to set an /etc/hosts entry. Is this a second bug?~~ This seems to be clear after finding #13577 and should not be related to this issue.

- I attempted `JAVA_OPTS_APPEND='-Djava.net.preferIPv6Stack=true'` as well as `'-Djava.net.preferIPv6Addresses=true'` but neither of the outcomes changed.

**Comment by pedroigor** [comment]
The PR you linked here is changing docs to mention how to properly prefer ipv6 addresses over ipv4:

```
export JAVA_OPTS_APPEND="-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true"
```

Can you please try it out?

**Comment by tacerus** [comment]
Hi!

Thanks for your response.

As mentioned, I tried these:

> I attempted JAVA_OPTS_APPEND='-Djava.net.preferIPv6Stack=true' as well as '-Djava.net.preferIPv6Addresses=true' but neither of the outcomes changed.

I do not want to set `-Djava.net.preferIPv4Stack=false`, because I still need IPv4 connectivity for other parts of Keycloak.

**Comment by pedroigor** [comment]
@tacerus AFAIK, setting `java.net.preferIPv4Stack=false` won't actually disable ivp4 but just force the JVM to prefer ipv6.

**Comment by tacerus** [comment]
Thank you very much, @pedroigor.
