### ISSUE TITLE
weird behaviour url resolution for OIDC well-known provider in docker - Uncaught server error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by coeit** [keycloak/keycloak#13699]
### Describe the bug

Hi there,

In a keycloak setup using docker (see docker-compose file below) i came across some weird behavior trying to request the OIDC well-known endpoint.

The minimal reproducible example docker-compose file looks like this:

```
version: "3.7"

services:

  keycloak:
    container_name: keycloak_test
    image: quay.io/keycloak/keycloak:19.0.1
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    networks:
      test:

networks:
  test:
```

When trying to request the OIDC well-known endpoint from inside the docker network (name: `test`) using the url 

`http://keycloak_test:8080/realms/master/.well-known/openid-configuration`

keycloak will return 
`{"error":"unknown_error"}`

with the following logs

```
2022-08-10 13:00:47,412 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: java.lang.NullPointerException
        at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.isHostFromFrontEndUrl(DefaultHostnameProvider.java:158)
        at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.forNonStrictBackChannel(DefaultHostnameProvider.java:132)
        at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.getScheme(DefaultHostnameProvider.java:60)
        at org.keycloak.models.KeycloakUriInfo.<init>(KeycloakUriInfo.java:46)
        at org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:78)
        at org.keycloak.protocol.oidc.OIDCWellKnownProvider.getConfig(OIDCWellKnownProvider.java:116)
        at org.keycloak.services.resources.RealmsResource.getWellKnown(RealmsResource.java:267)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

With the same setup requesting the realm endpoint `http://keycloak_test:8080/realms/master` will return just fine with 
```
{"realm":"master","public_key":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvvthe7U6OzYTfReKtTTsWldnx2qiC2i7HhurYjcQ7DODY5pya0Kj5xGK84ID4KydXFGhczyQya/bK6NoSq4rapDtwV2iOSqsrCNadorvwstNDm4T5oYXqaQgexbPHbrJNLnskHJ3jfKfGtp9P2gYwGKGX2tBySGLl3nZME64yKYwHmp2Dsp6OtBlIyqwpberW57GfssV9v+uMmMVpqX6y6qDYVIhOngvkHvHPYgOJ+eWbrD3kQ1c8sAKbsie9xN8FcO18QP3sb0tgwP/l6t3sLZi9E8Ipfw5exZLM27T6sclci7C2ZrfnFLQM/EXlZwPxAAH8lawJNRENDhOwBCrvwIDAQAB","token-service":"http://keycloak_test:8080/realms/master/protocol/openid-connect","account-service":"http://keycloak_test:8080/realms/master/account","tokens-not-before":0}
```
## Possible hint

Furthermore this behaviour seems to be related to the keycloak container name since when removing the "_" character from `keycloak_test`, using for example 
```
container_name: keycloak
```
requesting the OIDC well-known endpoint will work perfectly fine, no errors are thrown.

For the sake of completeness i queried the endpoint using docker curl image with this command:
```
docker run --network=<folder-name>_test --rm curlimages/curl:7.84.0 -L -v http://keycloak_test:8080/realms/master/.well-known/openid-configuration
```

### Version

19.0.1

### Expected behavior

OIDC well-known endpoint should return the requested information

### Actual behavior

OIDC well-known endpoint returns 
`{"error":"unknown_error"}`

and keycloak throws a `Uncaught server error: java.lang.NullPointerException`

### How to Reproduce?

See above bug-description for the minimal reproduciable docker-compose example

**Comment by pedroigor** [comment]
Indeed, it is weird behavior. The stack trace is unexpected because the line where you get that error should never use a null reference.

Do you have the steps to reproduce without using docker-compose?

**Comment by coeit** [comment]
> Indeed, it is weird behavior. The stack trace is unexpected because the line where you get that error should never use a null reference.
> 
> Do you have the steps to reproduce without using docker-compose?

Yes this is easily reproducable, steps i did:
1.  brand new keycloak download from https://github.com/keycloak/keycloak/releases/download/19.0.1/keycloak-19.0.1.zip.sha1
2. unzip
3. `bin/kc.sh start-dev`
4. add `0.0.0.0 keycloak_test` to `/etc/hosts` (or equivalent depending on the OS i guess)
5.  request OIDC well-known endpoint: `curl http://keycloak_test:8080/realms/master/.well-known/openid-configuration`

**Comment by pedroigor** [comment]
@coeit I see now. Some time ago we had this https://github.com/keycloak/keycloak/issues/11134.

Basically, an invalid hostname as per IETF in rfc2396 and Java resolves it to null when creating a URI:

```
        URI uri = URI.create("http://keycloak_test:8080");
        uri.getHost(); // is null
```

We can improve the error message by handling this situation. But it is expected.

We also have this update in our docs but that is for hostname configuration. See https://www.keycloak.org/server/hostname.

For now, I would close or create a new one to improve error message.

**Comment by coeit** [comment]
Ah, i see. That's very good to know. Thanks alot!
