### ISSUE TITLE
NullPointerException after upgrading to 19.0.1

### ISSUE THREAD

**Issue by BLeQuerrec** [keycloak/keycloak#13709]
### Describe the bug

After upgrading from 18.0.0 to 19.0.1, I have a NPE and Keycloak refuses to start. Looks like a Infinispan-related issue.

Config:
```
db=mariadb

db-username=REDACTED
db-password=REDACTED

hostname-strict=false

http-enabled=true
http-host=127.0.0.1
http-port=8080

proxy=edge

features=authorization,account2,account-api,admin-fine-grained-authz,impersonation,scripts,token-exchange,web-authn,client-policies,ciba,map-storage,par,declarative-user-profile,dynamic-scopes,preview,recovery_codes
features-disabled=docker,openshift-integration

http-relative-path=/auth
```

Logs:
```
$ sudo -u keycloak /opt/keycloak/current/bin/kc.sh --verbose -cf /etc/keycloak/keycloak.conf start --optimized
2022-08-10 20:13:35,615 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: admin_fine_grained_authz
2022-08-10 20:13:35,615 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: scripts
2022-08-10 20:13:35,615 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: token_exchange
2022-08-10 20:13:35,615 WARN  [org.keycloak.common.Profile] (main) Experimental feature enabled: map_storage
2022-08-10 20:13:35,615 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: declarative_user_profile
2022-08-10 20:13:35,615 WARN  [org.keycloak.common.Profile] (main) Experimental feature enabled: dynamic_scopes
2022-08-10 20:13:35,616 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: recovery_codes
2022-08-10 20:13:35,636 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true
2022-08-10 20:13:36,789 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-08-10 20:13:38,146 WARN  [org.keycloak.services.DefaultComponentFactoryProviderFactory] (main) No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.
2022-08-10 20:13:38,202 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-08-10 20:13:38,244 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-08-10 20:13:38,264 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-08-10 20:13:38,464 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-08-10 20:13:38,579 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-08-10 20:13:40,665 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) REDACTED-48613: no members discovered after 2002 ms: creating cluster as coordinator
2022-08-10 20:13:40,679 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [REDACTED-48613|0] (1) [REDACTED-48613]
2022-08-10 20:13:40,686 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `REDACTED-48613`, physical addresses are `[REDACTED:7800]`
2022-08-10 20:13:41,269 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-08-10 20:13:41,461 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-08-10 20:13:41,461 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.NullPointerException
        at org.keycloak.models.sessions.infinispan.InfinispanActionTokenStoreProviderFactory.initActionTokenCache(InfinispanActionTokenStoreProviderFactory.java:53)
        at org.keycloak.models.sessions.infinispan.InfinispanActionTokenStoreProviderFactory.postInit(InfinispanActionTokenStoreProviderFactory.java:67)
        at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:42)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:91)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

### Version

19.0.1

### Expected behavior

Keycloak starts.

### Actual behavior

Keycloak fails to start.

### Anything else?

Building works fine using `/opt/keycloak/current/bin/kc.sh -cf /etc/keycloak/keycloak.conf build`.

**Comment by pedroigor** [comment]
@BLeQuerrec The problem should be related to enabling the `map-storage` feature:

```
Experimental feature enabled: map_storage
```
Please, try removing that feature from your list of `features`.

**Comment by BLeQuerrec** [comment]
Thank you, it works. I can confirm you that removing `map_storage` from `features` configuration solves the issue.
