### ISSUE TITLE
How should the SecretQuestion example configure the authentication flow

### ISSUE THREAD

**Issue by brucelpt** [keycloak/keycloak#13744]
### Description

# KeyCloak Version
19.0.1

# compile environment
- openjdk 11.0.2
- windows10
- idea 
- KeyCloak V19.0.1

# runtime environment
- centos7
- openjdk 11.0.16
- Client spring-boot 2.3.5

# problem description
I’m learning KeyCloak, and I’m currently integrating official secret question examples.

I have placed the compiled JAR package in the /provider directory and executed the ${kc.home.dir}/bin/kc.sh build command.I then reopened KeyCloak and was able to select secret question from the authentication stream.

But when I connect my client link and automatically jump to the Keycloak authentication page, I get the following error:
Invalid username or password.
![erorr](https://canada1.discourse-cdn.com/free1/uploads/keycloak/original/2X/5/54a0a5ef3c4cc7551c890fcf6faba7ee75efa826.png)

server error logs:

```
2022-08-11 23:34:54,669 WARN  [org.keycloak.authentication.DefaultAuthenticationFlow] (executor-thread-44) REQUIRED and ALTERNATIVE elements at same level! Those alternative executions will be ignored: [auth-cookie, identity-provider-redirector]
2022-08-11 23:34:54,670 WARN  [org.keycloak.services] (executor-thread-44) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: authenticator: secret-question-authenticator
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:423)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:250)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1017)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:879)
	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:151)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:338)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:194)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
	at jdk.internal.reflect.GeneratedMethodAccessor479.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-08-11 23:34:54,679 WARN  [org.keycloak.events] (executor-thread-44) type=LOGIN_ERROR, realmId=ca7ca487-f63a-4ba1-ab7f-c95b9f4f04a3, clientId=app-authz-vanilla, userId=null, ipAddress=172.20.25.22, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=http://172.20.25.22:8081/getUserInfo, code_id=827be7e0-b798-4008-8eb0-561ff1e6288f, response_mode=query, authSessionParentId=827be7e0-b798-4008-8eb0-561ff1e6288f, authSessionTabId=kS_EC6JoUdY

```

My authentication flow is configured as follows:
![auth flow](https://canada1.discourse-cdn.com/free1/uploads/keycloak/original/2X/d/d7cabea0c95684f3b59dc09452c12acb602d921d.png)

My client configuration is as follows:
```
server:
  port: 8081
  servlet:
    context-path:
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
  error:
    include-message: always
spring:
  messages:
    basename: i18n/starterMessages,testMessages,i18n/messages
    cache-duration: 3600
    encoding: UTF-8
  # mysql 
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    username: XXX
    password: XXX
    url: jdbc:mysql://XXX:3306/ecm-dev?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  resource:
    static-locations: classpath:/static/,classpath:/public/
  #redis 配置
  redis:
    database: XXX
    host: XXX
    port: 6379
    password: XXX
    timeout: 3000
    pool:
      max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
keycloak:
#  public-client: true
  realm: hello-world-auth-test
  auth-server-url: http://10.30.51.30:8080/
  ssl-required: none
  resource: app-authz-vanilla
  verify-token-audience: true
#  use-resource-role-mappings: true
  credentials:
    secret: YTeBZRQyYuXYN5wEI1vkl6XNrconYo1b
  confidential-port: 0
  security-constraints:
    -  #logout
      securityCollections:
        - name: logout
          patterns:
            - /logout
    - # roles
      authRoles:
        - admin
      securityCollections:
        -
          name: admin
          patterns:
            - /admin/*
            - /system/*
    - # test
      authRoles:
        - admin
        - user
      securityCollections:
        - name: user
          patterns:
            - /test/*
            - /getUserInfo
            - /custom-resource/*
#  policy-enforcer-config:
#    on-deny-redirect-to: /unauthorized
```

**Comment by brucelpt** [comment]
I have no problem using the default authentication flow, but I get an error when I change it to the secret question  example

**Comment by brucelpt** [comment]
I notice that the message in the error message is to get the user information is empty so the error is reported.
My idea is to request the client's link address and then automatically jump to the authentication page of the secret problem. Is there something wrong with my configuration
![image](https://user-images.githubusercontent.com/37991444/184300827-5c06e9f7-4b82-44b9-859b-bedb6d6ffcb7.png)

My Client Config
![image](https://user-images.githubusercontent.com/37991444/184301026-b1395dd8-78fc-4806-9e94-c31c3f2183bc.png)
![image](https://user-images.githubusercontent.com/37991444/184301054-38d3e440-7b6e-4b3e-abe9-2943c1e5417e.png)
![image](https://user-images.githubusercontent.com/37991444/184301080-041b5b73-16d9-4142-8502-06362ea1db11.png)
![image](https://user-images.githubusercontent.com/37991444/184301097-321039b3-b93e-4f63-9eb6-ea720b229e3b.png)

**Comment by lexcao** [comment]
Hi, @brucelpt 
Could you please help me debug your situation?

> But when I connect my client link and automatically jump to the Keycloak authentication page
1. What does `connect my client link` mean?

2. Could you please provide your authentication flow ?
    * in `Authentication > Flow` 
4. and authentication binding?
    * in `Authentication > Bindings`

**Comment by brucelpt** [comment]
> Hi, @brucelpt Could you please help me debug your situation?
> 
> > But when I connect my client link and automatically jump to the Keycloak authentication page
> 
> 1. What does `connect my client link` mean?
> 2. Could you please provide your authentication flow ?
>    
>    * in `Authentication > Flow`
> 3. and authentication binding?
>    
>    * in `Authentication > Bindings`
I misconfigured the authentication flow, my current configuration is as follows, how should I configure the secret question and anser? 
For example a question for aclice users: your name? Answer: alice
![image](https://user-images.githubusercontent.com/37991444/184582211-37b2bec8-d06b-40dc-87cf-7361e314244b.png)

**Comment by lexcao** [comment]
From the screenshot you provided, I think it is fine.

> how should I configure the secret question and answer

You need to set a required action for the user to set up the secret answer.
Please refer to this [doc](https://github.com/keycloak/keycloak/blob/main/examples/providers/authenticator/README.md)

> Next you have to register the required action that you created. Click on the Required Actions tab in the Authentication menu. Click on the Register button and choose your new Required Action. You can also choose the Default Action for the Required Action and each new user has to set the secret answer. Your new required action should now be displayed and enabled in the required actions list.
