### ISSUE TITLE
Failed to run scheduled task ClearExpiredClientInitialAccessTokens

### ISSUE THREAD

**Issue by rmoqpd5t** [keycloak/keycloak#13818]
### Describe the bug

Regular "failed to run scheduled task ClearExpiredClientInitialAccessTokens" errors which seem to arise in relation to 19.0.0's new server-spi-private code:

2022-08-16 10:21:24,626 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Failed to run scheduled task ClearExpiredClientInitialAccessTokens: java.lang.IllegalAccessError: class org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 tried to access protected field org.keycloak.services.scheduled.ScheduledTaskRunner.task (org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 is in unnamed module of loader 'org.keycloak.keycloak-model-legacy-private@19.0.1' @43ecc098; org.keycloak.services.scheduled.ScheduledTaskRunner is in unnamed module of loader 'org.keycloak.keycloak-server-spi-private@19.0.1' @39ae030d)
        at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
        at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.keycloak-model-infinispan@19.0.1//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
        at org.keycloak.keycloak-server-spi-private@19.0.1//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
        at org.keycloak.keycloak-services@19.0.1//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

### Version

legacy 19.0.1

### Expected behavior

Pre 19.0.0 the ClearExpiredClientInitialAccessTokens task ran without errors

### Actual behavior

Post 19.0.0 the ClearExpiredClientInitialAccessTokens task should run without errors

### How to Reproduce?

Install legacy 19.0.0 (or later) and check the server.log.  Tested with OpenJDK version "11.0.16" and PostgreSQL 14.

**Comment by darius-m** [comment]
This was also reported in #13396.

**Comment by ahus1** [comment]
Closing as duplicate to #13396
