### ISSUE TITLE
Failed to run scheduled task ClearExpiredEvents and ClearExpiredClientInitialAccessTokens

### ISSUE THREAD

**Issue by korkutkose** [keycloak/keycloak#13824]
### Describe the bug

Hi everyone,
We've recently upgraded our Keycloak installation from 10.0.1 to 19.0.1-legacy straight (yeah that was way overdue). Although everything seems working nicely, there are errors in keycloak logs which is constantly repeating about schedulers. I am not sure this will affect us or not in the future, but the error is error.
Anyone has any idea how to mitigate this?
Cheers.

### Version

19.0.1-legacy

### Expected behavior

No errors showing in log file.

### Actual behavior

`12:47:46,416 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Failed to run scheduled task ClearExpiredEvents: java.lang.IllegalAccessError: class org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 tried to access protected field org.keycloak.services.scheduled.ScheduledTaskRunner.task (org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 is in unnamed module of loader 'org.keycloak.keycloak-model-legacy-private@19.0.1' @3288157b; org.keycloak.services.scheduled.ScheduledTaskRunner is in unnamed module of loader 'org.keycloak.keycloak-server-spi-private@19.0.1' @3a8da3d1)
188
	at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
189
	at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
190
	at org.keycloak.keycloak-model-infinispan@19.0.1//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
191
	at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
192
	at org.keycloak.keycloak-server-spi-private@19.0.1//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
193
	at org.keycloak.keycloak-services@19.0.1//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
194
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
195
	at java.base/java.util.TimerThread.run(Timer.java:506)
196
197`
*********************************************************************************************************************
`12:47:46,801 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Failed to run scheduled task ClearExpiredClientInitialAccessTokens: java.lang.IllegalAccessError: class org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 tried to access protected field org.keycloak.services.scheduled.ScheduledTaskRunner.task (org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1 is in unnamed module of loader 'org.keycloak.keycloak-model-legacy-private@19.0.1' @3288157b; org.keycloak.services.scheduled.ScheduledTaskRunner is in unnamed module of loader 'org.keycloak.keycloak-server-spi-private@19.0.1' @3a8da3d1)
198
	at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)
199
	at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)
200
	at org.keycloak.keycloak-model-infinispan@19.0.1//org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
201
	at org.keycloak.keycloak-model-legacy-private@19.0.1//org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
202
	at org.keycloak.keycloak-server-spi-private@19.0.1//org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
203
	at org.keycloak.keycloak-services@19.0.1//org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
204
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
205
	at java.base/java.util.TimerThread.run(Timer.java:506)`

### How to Reproduce?

I am not sure how to reproduce this one. We are using Keycloak with MsSQL and as I've mentioned earlier we've migrated from 10.0.1 to 19.0.1-legacy.

**Comment by darius-m** [comment]
This issue was also reported in #13396, and more recently in #13818.

**Comment by korkutkose** [comment]
Shut, my bad. Closing this one. Thanks @darius-m
