### ISSUE TITLE
Continuously Restarting

### ISSUE THREAD

**Issue by nidhin077** [keycloak/keycloak#13881]
### Describe the bug

I changed an entry in my keycloak compose file and rebuilt it. After the rebuild, it kept restarting, and when I checked the log file, I noticed the following error.

10:27:21,102 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 38) WFLYCTL0190: Step handler org.jboss.as.controller.AbstractAddStepHandler$1@4312ff6d for operation add at address [
    ("subsystem" => "infinispan"),
    ("cache-container" => "keycloak"),
    ("replicated-cache" => "work"),
    ("component" => "transaction")
] failed -- java.util.concurrent.RejectedExecutionException: java.util.concurrent.RejectedExecutionException
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:37)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2029)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:757)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.notification.NotificationSupports$NonBlockingNotificationSupport.emit(NotificationSupports.java:95)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.OperationContextImpl.notifyModificationBegun(OperationContextImpl.java:891)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.OperationContextImpl.ensureWriteLockForRuntime(OperationContextI

Could you please have a check and let me know, how to resolve the same. 

### Version

16.1.1

**Comment by stianst** [comment]
The WildFly based distribution of Keycloak has been deprecated since Keycloak 17 (February 2022), and will no longer be available in Keycloak 20, which is due to be released soon.

For this reason we're closing this issue as it is related to the WildFly based distribution. Please migrate to the new Quarkus distribution as soon as possible.
