### ISSUE TITLE
Not able to connect to the external Infinispan Server

### ISSUE THREAD

**Issue by ic2hrmk** [keycloak/keycloak#13926]
### Describe the bug

Hello,

I'm setting up the Keycloak 19.0.1 to be used in the cross-DC mode, and in order to do that, I deployed the Infinispan Server 13.0.9.

I changed the Quarkus configuration via the `keycloak.conf` to point it to the remote Infinispan as per the Quarkus configuration: https://quarkus.io/guides/infinispan-client#connecting-to-infinispan-clusters

To configure the Infinispan, I combined the default Infinispan configuration file with the `cache-container` definition taken from the Keycloak image.

Once the Docker Compose had started, Keycloak & Infinispan discovered each other (as per logs), but then Keycloak exits with the error after trying to put data to the work cache.

### Version

19.0.1

### Expected behavior

Keycloak connects to the Infinispan and writes and reads cache records from it. Infinispan server takes care of cross-site communication.

### Actual behavior

Keycloak starts and connects to the Infinispan server, and then shuts off with the error:

~~~
keycloak    | 2022-08-22 17:38:19,399 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (jgroups-8,keycloak-57082) ISPN000136: Error executing command PutKeyValueCommand on Cache 'work', writing keys [d0f4e0f2-ff97-48a8-ab31-1da5c2426ada]: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from infinispan-37599, see cause for remote stack trace
...
keycloak    | Caused by: java.lang.ClassNotFoundException: org.keycloak.cluster.infinispan.WrapperClusterEvent$ExternalizerImpl
~~~

### How to Reproduce?

To reproduce the issue, use the next Docker Compose setup:

`docker-compose.yaml`
~~~yaml
version: '3'

services:
  infinispan:
    image: quay.io/infinispan/server:13.0.9.Final
    container_name: infinispan
    hostname: infinispan
    volumes:
      - ./infinispan.xml:/opt/infinispan/server/conf/infinispan.xml:ro
    command:
      - --cluster-name=ISPN
    ports:
      - "9122:11222"

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    hostname: keycloak
    depends_on:
      - infinispan
    environment:
      KC_LOG_LEVEL: info
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      INFINISPAN_HOST: infinispan:11222
    ports:
      - "9121:8080"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "--verbose", "start"]
    volumes:
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro
~~~

`infinispan.xml`
~~~xml
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:13.0 https://infinispan.org/schemas/infinispan-config-13.0.xsd
                            urn:infinispan:server:13.0 https://infinispan.org/schemas/infinispan-server-13.0.xsd"
        xmlns="urn:infinispan:config:13.0"
        xmlns:server="urn:infinispan:server:13.0">

    <cache-container name="keycloak"> <!-- KEYCLOAK CACHE CONFIGURATION COPIED FROM THE quay.io/keycloak/keycloak:19.0.1 -->
        <transport cluster="${infinispan.cluster.name:cluster}" lock-timeout="60000"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>

    <server xmlns="urn:infinispan:server:13.0">
        <interfaces>
            <interface name="public">
                <inet-address value="${infinispan.bind.address:127.0.0.1}"/>
            </interface>
        </interfaces>

        <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
            <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
            <socket-binding name="memcached" port="11221"/>
        </socket-bindings>

        <security>
            <credential-stores>
                <credential-store name="credentials" path="credentials.pfx">
                    <clear-text-credential clear-text="secret"/>
                </credential-store>
            </credential-stores>
            <security-realms>
                <security-realm name="default">
                    <!-- Uncomment to enable TLS on the realm -->
                    <!-- server-identities>
                       <ssl>
                          <keystore path="application.keystore"
                                    password="password" alias="server"
                                    generate-self-signed-certificate-host="localhost"/>
                       </ssl>
                    </server-identities-->
                    <properties-realm groups-attribute="Roles">
                        <user-properties path="users.properties"/>
                        <group-properties path="groups.properties"/>
                    </properties-realm>
                </security-realm>
            </security-realms>
        </security>

        <endpoints socket-binding="default" security-realm="default" />
    </server>
</infinispan>
~~~

`keycloak.conf`
~~~
quarkus.infinispan-client.server-list=${INFINISPAN_HOST}

# quarkus.infinispan-client.auth-username=${INFINISPAN_USER}
# quarkus.infinispan-client.auth-password=${INFINISPAN_PASSWORD}
~~~

### Anything else?

PS: Can you please update the guide on configuring the cross-DC mode for the Keycloak 19+ as you had earlier for the legacy WildFly distribution?

* https://www.keycloak.org/2017/09/cross-datacenter-support-in-keycloak
* https://www.keycloak.org/docs/latest/server_installation/index.html#crossdc-mode

**Comment by templed** [comment]
I have been having a problem along similar lines to the OP too.

For context: I have an infinispan cluster with keycloak 12 connecting to them as clients. They use it solely as a cache for things like sessions, etc. I have tried to get keycloak 18 and 19 working with this ISPN-cluster <-> KC-client design (I tried with 18, didn't succeed, gave up, then saw 19 had ISPN tweaks so I tried again).

I have tried a number of different approaches and configurations, all of which either end in encoding/marshalling errors (such as the one OP has encountered) or timeouts. Moreover I have not been able to get KC to connect to an ISPN cluster _solely as a client_. No matter how I configure KC it always seems to want to act as an embedded ISPN server which then joins the cluster. In the Quarkus distribution is it even possible to have KC _only_ act as an ISPN client or is having an embedded ISPN server the only functionality currently implemented?

To give some more information on OP's problem: Using their docker-compose as a basis I have been able to work around the ClassNotFound exceptions by including the following JARs in the ISPN server's classpath:

```
org.keycloak.keycloak-model-infinispan-19.0.3.jar
org.keycloak.keycloak-server-spi-private-19.0.3.jar
org.keycloak.keycloak-server-spi-19.0.3.jar
org.keycloak.keycloak-core-19.0.3.jar
```

(at least for KC 19.0.3). After you include these JARs in the classpath KC will start serving the landing page. However if you try to log in (which means KC is trying to interact with the ISPN cache) there is an indefinite wait for the page to load. KC is emitting the following logs:

```
keycloak      | 2022-10-17 14:14:44,521 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p4-t1) ISPN000136: Error executing command PutKeyValueCommand on Cache 'authenticationSessions', writing keys [124b5abe-80d5-489b-a1fa-9c5039ce93c7]: org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks. Id=156
keycloak      |         at org.infinispan.util.concurrent.CommandAckCollector.createTimeoutException(CommandAckCollector.java:227)
keycloak      |         at org.infinispan.util.concurrent.CommandAckCollector.access$600(CommandAckCollector.java:59)
keycloak      |         at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:280)
keycloak      |         at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:260)
keycloak      |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
keycloak      |         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
keycloak      |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
keycloak      |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak      |         at java.base/java.lang.Thread.run(Thread.java:829)
```

This _may_ be a problem with the JGroups configuration baked into KC that is not cooperating with the JGroups configuration baked into ISPN. However I have tried using the KC JGroups stack config with ISPN, and I still get the same timeout problems.

My workaround for avoiding the marshalling exceptions is not, I believe, the correct way of doing this. In previous attempts I have tried forcing the encoding to be protostream, java-serialized-object, and the JBoss marshal format. They were met with various degrees of success but ultimately ended up encountering the timeout error, or a different error due to me attempting to use the JGroups cluster flags which also appear to be non-functional. I will create a separate issue with this as I believe it is related, but distinct, to the error OP is having (and also touches on the question about cross-DC functionality that the OP asked about at the end).

**Comment by martin-kanis** [comment]
Hi, thank you for the report and sorry for the late reply. I tried current `main` with remote Infinispan 14.0.0.Final server. Not cross-dc mode, just one Keycloak node with remote Infinispan store. This is my configuration:

`infinispan.xml`
```xml
<infinispan
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:infinispan:config:14.0 https://infinispan.org/schemas/infinispan-config-14.0.xsd
                            urn:infinispan:server:14.0 https://infinispan.org/schemas/infinispan-server-14.0.xsd"
      xmlns="urn:infinispan:config:14.0"
      xmlns:server="urn:infinispan:server:14.0">

   <cache-container name="remoteKeycloak" statistics="true">
      <transport cluster="${infinispan.cluster.name:globalCluster}" stack="${infinispan.cluster.stack:udp}" node-name="${infinispan.node.name:mainNode}" site="globalSite"/>
      <security>
         <authorization/>
      </security>
      
      <serialization marshaller="org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller">
            <allow-list>
                <class>org.keycloak.cluster.infinispan.WrapperClusterEvent</class>
                <regex>.*</regex>
            </allow-list>
        </serialization>

    <replicated-cache name="work">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </replicated-cache>
    
    
    <distributed-cache name="sessions">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="authenticationSessions">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="clientSessions">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="offlineSessions">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="offlineClientSessions">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="actionTokens">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="loginFailures">
    	<encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
   </cache-container>

   <server xmlns="urn:infinispan:server:14.0">
      <interfaces>
         <interface name="public">
            <inet-address value="${infinispan.bind.address:127.0.0.1}"/>
         </interface>
      </interfaces>

     <!-- to start remote ISPN server on 11333 port -->
      <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:111}">
         <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
         <socket-binding name="memcached" port="11221"/>
      </socket-bindings>

      <security>
         <credential-stores>
            <credential-store name="credentials" path="credentials.pfx">
               <clear-text-credential clear-text="secret"/>
            </credential-store>
         </credential-stores>
         <security-realms>
            <security-realm name="default">
               <!-- Uncomment to enable TLS on the realm -->
               <!-- server-identities>
                  <ssl>
                     <keystore path="application.keystore"
                               password="password" alias="server"
                               generate-self-signed-certificate-host="localhost"/>
                  </ssl>
               </server-identities-->
               <properties-realm groups-attribute="Roles">
                  <user-properties path="users.properties"/>
                  <group-properties path="groups.properties"/>
               </properties-realm>
            </security-realm>
         </security-realms>
      </security>

      <endpoints socket-binding="default" security-realm="default">
    <endpoint>
      <hotrod-connector name="hotrod">
        <authentication>
          <sasl mechanisms="DIGEST-MD5"
                server-name="infinispan" />
        </authentication>
      </hotrod-connector>
      <rest-connector name="rest"/>
    </endpoint>
  </endpoints>
   </server>
</infinispan>
```
Download Infinispan 14.0.0.Final, unpack it and create an admin user `./bin/cli.sh user create admin -p admin -g admin`. Then start the server `./bin/server.sh`. Infinispan 13 has problem to start with `<serialization marshaller="org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller>` (maybe bug in Infinispan?) therefore I used Infinispan 14.

`cache-ispn.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:13.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:13.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000" site="site1"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>

        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="sessions"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="authenticationSessions"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="offlineSessions"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="clientSessions"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="offlineClientSessions"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="loginFailures"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="actionTokens" owners="2">
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="actionTokens"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <replicated-cache name="work">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:13.0"
                          cache="work"
                          fetch-state="false"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="127.0.0.1" port="11333" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </replicated-cache>
    </cache-container>
</infinispan>
```
Start Keycloak server `./bin/kc.sh start-dev --debug --cache=ispn` (I'm using dev mode with debugging). Go to `http://localhost:8080/` and create an admin user. Log in to the admin console. To prove the remote store is working, stop Keycloak server, then start it again and go back to admin console to verify the admin session survived (You don't have to re-login).

Feel free to try with my configuration. Maybe the configuration can be simplified or/and improved from performance perspective, but that was out of scope for my investigations. Closing for now as explained but feel free to reopen if you think there is a bug.

**Comment by juluanb** [comment]
Hi @lvian 
Have you find a solution to resolve this behaviour. I have the same one here.

**Comment by thetoolsmith** [comment]
@juluanb @lvian, I also see this message with Keycloak 20.0.5 and external infinispan 14.0.19. Cache does seems to persist on Keycloak restarts (we are in dev mode right now). However, the same configuration I used which is what @martin-kanis posted does not work with Keycloak 22.0.1. I'm running local server installs of both infinispan and keycloak (no docker) and get this for the keycloak 22.0.1 testing ```2023-11-01 13:26:49,735 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.client.hotrod.exceptions.TransportException:: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:11333
2023-11-01 13:26:49,735 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:11333
2023-11-01 13:26:49,735 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection refused: /127.0.0.1:11333```
