### ISSUE TITLE
Docker Build Failure: KeycloakProcessor#configurePersistenceUnits NullPointerException

### ISSUE THREAD

**Issue by JulianWebb** [keycloak/keycloak#13979]
### Describe the bug

When attempting to build a custom container using the [`Dockerfile` shown here](https://github.com/JulianWebb/keycloak-discord-docker-compose/blob/development/Dockerfile), the build fails with `[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configurePersistenceUnits threw an exception: java.lang.NullPointerException` and exits.

### Version

19.0.0

### Expected behavior

A successful build

### Actual behavior

Build process produces error and exits.

### How to Reproduce?

1. `git clone https://github.com/JulianWebb/keycloak-discord-docker-compose.git`
2. `cd keycloak-discord-docker-compose`
3. `sudo docker compose build keycloak`

### Anything else?

Full Log:
```
[julian@computer Keycloak-Discord]$ sudo docker compose build keycloak
[+] Building 274.1s (6/9)                                                                                                                                                                      
 => [internal] load build definition from Dockerfile                                                                                                                                      0.1s
 => => transferring dockerfile: 1.19kB                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                         0.1s
 => => transferring context: 2B                                                                                                                                                           0.0s
 => [internal] load metadata for quay.io/keycloak/keycloak:19.0.1                                                                                                                       274.0s
 => [stage-1 1/3] FROM quay.io/keycloak/keycloak:19.0.1@sha256:b8dd5185ed3856488d127fe419a2593c675f1dc6c7e1e0977234f3b0cc13598f                                                         263.2s
 => => resolve quay.io/keycloak/keycloak:19.0.1@sha256:b8dd5185ed3856488d127fe419a2593c675f1dc6c7e1e0977234f3b0cc13598f                                                                   0.0s
 => => sha256:7941680be453af0abcb9197b4e40ff0bd3a487d7c960f4d32be147b950aaa2d0 4.33kB / 4.33kB                                                                                            0.0s
 => => sha256:1e09a5ee0038fbe06a18e7f355188bbabc387467144abcd435f7544fef395aa1 36.43MB / 36.43MB                                                                                         91.4s
 => => sha256:0d725b91398ed3db11249808d89e688e62e511bbd4a2e875ed8493ce1febdb2c 1.74kB / 1.74kB                                                                                            0.5s
 => => sha256:2e1406464243016fdf313ab5c926578672dcdc9690c0337ac8fdc5172d03aa16 171.61MB / 171.61MB                                                                                      259.6s
 => => sha256:b8dd5185ed3856488d127fe419a2593c675f1dc6c7e1e0977234f3b0cc13598f 743B / 743B                                                                                                0.0s
 => => sha256:dbce324a150e2c251a7345342364ab34efcc50049e3e86bbd286c1d256725806 1.16kB / 1.16kB                                                                                            0.0s
 => => sha256:02c6e6661f78244a937e5c51edda2984bf38c37f3023ffcfb6633dc9b4da2289 86.40MB / 86.40MB                                                                                        168.8s
 => => extracting sha256:1e09a5ee0038fbe06a18e7f355188bbabc387467144abcd435f7544fef395aa1                                                                                                 0.6s
 => => extracting sha256:0d725b91398ed3db11249808d89e688e62e511bbd4a2e875ed8493ce1febdb2c                                                                                                 0.0s
 => => extracting sha256:2e1406464243016fdf313ab5c926578672dcdc9690c0337ac8fdc5172d03aa16                                                                                                 1.0s
 => => extracting sha256:02c6e6661f78244a937e5c51edda2984bf38c37f3023ffcfb6633dc9b4da2289                                                                                                 1.9s
 => [builder 2/4] RUN curl -sL https://github.com/wadahiro/keycloak-discord/releases/download/v0.4.0/keycloak-discord-0.4.0.jar -o /opt/keycloak/providers/keycloak-discord-0.4.0.jar     2.2s
 => [builder 3/4] RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2  1.4s
 => ERROR [builder 4/4] RUN /opt/keycloak/bin/kc.sh build                                                                                                                                 6.1s
------
 > [builder 4/4] RUN /opt/keycloak/bin/kc.sh build:
#0 0.934 Updating the configuration and installing your custom providers, if any. Please wait.
#0 4.402 2022-08-24 20:15:04,085 INFO  [org.keycloak.common.Profile] (build-23) Preview feature enabled: token_exchange
#0 4.863 2022-08-24 20:15:04,563 WARN  [org.keycloak.services] (build-23) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
#0 5.450 2022-08-24 20:15:05,149 WARN  [org.keycloak.services] (build-23) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
#0 5.961 ERROR: Failed to run 'build' command.
#0 5.961 ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#0 5.961        [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configurePersistenceUnits threw an exception: java.lang.NullPointerException
#0 5.961        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
#0 5.961        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
#0 5.961        at java.base/java.util.Properties.put(Properties.java:1340)
#0 5.961        at java.base/java.util.Properties.setProperty(Properties.java:228)
#0 5.961        at org.keycloak.quarkus.deployment.KeycloakProcessor.configureJpaProperties(KeycloakProcessor.java:250)
#0 5.961        at org.keycloak.quarkus.deployment.KeycloakProcessor.configurePersistenceUnits(KeycloakProcessor.java:216)
#0 5.961        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 5.961        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#0 5.961        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 5.961        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#0 5.961        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
#0 5.961        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
#0 5.961        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#0 5.961        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
#0 5.961        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
#0 5.961        at java.base/java.lang.Thread.run(Thread.java:829)
#0 5.961        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#0 5.961 
#0 5.961 ERROR: Build failure: Build failed due to errors
#0 5.961        [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configurePersistenceUnits threw an exception: java.lang.NullPointerException
#0 5.961        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
#0 5.961        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
#0 5.961        at java.base/java.util.Properties.put(Properties.java:1340)
#0 5.961        at java.base/java.util.Properties.setProperty(Properties.java:228)
#0 5.961        at org.keycloak.quarkus.deployment.KeycloakProcessor.configureJpaProperties(KeycloakProcessor.java:250)
#0 5.961        at org.keycloak.quarkus.deployment.KeycloakProcessor.configurePersistenceUnits(KeycloakProcessor.java:216)
#0 5.961        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 5.961        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#0 5.961        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 5.961        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#0 5.961        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
#0 5.961        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
#0 5.961        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#0 5.961        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
#0 5.961        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
#0 5.961        at java.base/java.lang.Thread.run(Thread.java:829)
#0 5.961        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#0 5.961 
#0 5.961 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
------
failed to solve: executor failed running [/bin/sh -c /opt/keycloak/bin/kc.sh build]: exit code: 1
```
(note this log 

Host System Specifications:
Fedora 36 x86_64
Docker version 20.10.17, build 100c701

**Comment by vmuzikar** [comment]
@JulianWebb Thanks for the report! I would like to ask you to send your question to the [proper community channels](https://www.keycloak.org/community) meant for asking questions and getting help. The GH Issues here are meant for reporting bugs in Keycloak.

**Comment by JulianWebb** [comment]
You mean the same "proper community channels" that also have no area for talking about the official docker build?

Yeah, I gave up on this two months ago when I realized how much support it lacked.
