### ISSUE TITLE
Uncaught exception during startup

### ISSUE THREAD

**Issue by Herdo** [keycloak/keycloak#14046]
### Describe the bug

When starting the latest version of Keycloak at https://quay.io/keycloak/keycloak with `start`, the container doesn't start.
As this happens during the build part, I think the image might be broken somehow.

### Version

19.0.1

### Expected behavior

The container starts correctly.

### Actual behavior

Starting the version 19.0.1 with `--verbose` parameter outputs, these two different error messages in the logs:

```
2022-08-31 05:19:05,530 ERROR [org.jboss.threads.errors] (build-8) Thread Thread[build-8,5,build group] threw an uncaught exception: java.util.concurrent.RejectedExecutionException
        at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
        at org.jboss.threads.EnhancedQueueExecutor.rejectException(EnhancedQueueExecutor.java:2049)
        at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1713)
        at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:787)
        at io.quarkus.builder.BuildContext.depFinished(BuildContext.java:261)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:294)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
                at java.base/java.lang.Thread.start0(Native Method)
                at java.base/java.lang.Thread.start(Thread.java:798)
                at org.jboss.threads.JBossThread.start(JBossThread.java:558)
                at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1709)
                ... 8 more
```

and

```
2022-08-26 15:26:22,917 ERROR [org.jboss.threads.errors] (build-61) Thread Thread[build-61,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.ClassNotFoundException: io.quarkus.builder.diag.Diagnostic
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 6 more


2022-08-26 15:26:22,918 TRACE [io.quarkus.builder] (build-23) Finished step "io.quarkus.vertx.deployment.VertxProcessor#autoAddScope" in 176 ms

2022-08-26 15:26:22,918 ERROR [org.jboss.threads.errors] (build-23) Thread Thread[build-23,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2022-08-26 15:26:22,919 TRACE [io.quarkus.builder] (build-59) Finished step "io.quarkus.deployment.steps.ApplicationIndexBuildStep#build" in 111 ms

2022-08-26 15:26:22,919 ERROR [org.jboss.threads.errors] (build-59) Thread Thread[build-59,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2022-08-26 15:26:22,919 TRACE [io.quarkus.builder] (build-73) Finished step "io.quarkus.vertx.core.deployment.VertxCoreProcessor#ioThreadDetector" in 132 ms

2022-08-26 15:26:22,919 ERROR [org.jboss.threads.errors] (build-73) Thread Thread[build-73,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2022-08-26 15:26:22,919 TRACE [io.quarkus.builder] (build-49) Finished step "io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#parsePersistenceXmlDescriptors" in 179 ms

2022-08-26 15:26:22,919 ERROR [org.jboss.threads.errors] (build-49) Thread Thread[build-49,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2022-08-26 15:26:22,922 TRACE [io.quarkus.builder] (build-18) Finished step "io.quarkus.deployment.recording.substitutions.AdditionalSubstitutionsBuildStep#additionalSubstitutions" in 179 ms

2022-08-26 15:26:22,922 ERROR [org.jboss.threads.errors] (build-18) Thread Thread[build-18,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2022-08-26 15:26:22,922 TRACE [io.quarkus.builder] (build-63) Finished step "io.quarkus.vault.deployment.VaultProcessor#registerAdditionalBeans" in 114 ms

2022-08-26 15:26:22,922 ERROR [org.jboss.threads.errors] (build-63) Thread Thread[build-63,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2022-08-26 15:26:22,923 TRACE [io.quarkus.builder] (build-9) Finished step "io.quarkus.jdbc.oracle.deployment.OracleProcessor#feature" in 120 ms

2022-08-26 15:26:22,923 ERROR [org.jboss.threads.errors] (build-9) Thread Thread[build-9,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


2022-08-26 15:26:22,923 TRACE [io.quarkus.builder] (build-42) Finished step "io.quarkus.arc.deployment.ConfigBuildStep#vetoMPConfigProperties" in 111 ms

2022-08-26 15:26:22,923 ERROR [org.jboss.threads.errors] (build-42) Thread Thread[build-42,5,build group] threw an uncaught exception: java.lang.NoClassDefFoundError: io/quarkus/builder/diag/Diagnostic
        at io.quarkus.builder.BuildContext.run(BuildContext.java:280)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


ERROR: Failed to run 'build' command.
ERROR: java.util.concurrent.RejectedExecutionException

```

### How to Reproduce?

Start a new container instance with the version `19.0.1` / currently `latest`.
The variables are read from a file.

```
docker run \
  -it \
  --rm \
  --name keycloak \
  --cpus="1.0" \
  --cpu-shares=256 \
  --memory=1024m \
  --security-opt="no-new-privileges:true" \
  --pids-limit=100 \
  --network docker-network \
  --ip $DOCKER_CONTAINER_IP \
  -e "KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN_USERNAME" \
  -e "KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD" \
  -e "KC_DB=postgres" \
  -e "KC_DB_URL_HOST=$KEYCLOAK_DATABASE_HOST" \
  -e "KC_DB_URL_PORT=$KEYCLOAK_DATABASE_PORT" \
  -e "KC_DB_URL_DATABASE=$KEYCLOAK_DATABASE_DATABASE" \
  -e "KC_DB_SCHEMA=$KEYCLOAK_DATABASE_SCHEMA" \
  -e "KC_DB_USERNAME=$KEYCLOAK_DATABASE_USERNAME" \
  -e "KC_DB_PASSWORD=$KEYCLOAK_DATABASE_PASSWORD" \
  quay.io/keycloak/keycloak:latest start --hostname=sso.mydomain.eu --proxy=passthrough --log-level=ALL
```

### Anything else?

The `docker run` options `-it`, `--rm` and `--log-level=ALL` are for debugging only.
Normally I start the container with `-d` and `--restart unless-stopped`.

**Comment by pedroigor** [comment]
@Herdo Just tried here running:

```
docker run --name keycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me         quay.io/keycloak/keycloak:latest
```

It works fine. Not sure if how you run the container makes any difference but if you can provide more details on how you are actually running it, I appreciate it.

**Comment by Herdo** [comment]
@pedroigor I added the bash script that starts the container in `How to Reproduce?`
Also found another error message further up in the logs. Maybe this might be the root of the issue. I've added the message above.

**Comment by Herdo** [comment]
@pedroigor Running the container without any limitations works (throws a missing key material error later on, but that's understandable). However, running the container in production without limitations is not an option. Just to clarify, the limitations are:
- Limit to 1 CPU
- Relative CPU share of 256
- Memory limit of 1024 MB
- No new privileges can be obtained
- A maximum of 100 PIDs

**Comment by lexcao** [comment]
From the logs you provided,
```
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
```
and the limits you provided,
```
Memory limit of 1024 MB
Limit to 1 CPU
```
I think it may be related to the acutal value of these limits.

Could you please try these attempts?

### Attempt 1
* change `Memory limit` to 2048 MB to see if there is an error

### Attempt 2
* change `CPU` to 2 to see if there is an error

**Comment by pedroigor** [comment]
By running:

```
docker run -it --rm --name keycloak --cpus="0.5" --cpu-shares=256 --memory=1024m --security-opt="no-new-privileges:true" --pids-limit=100 -e "KEYCLOAK_ADMIN=admin" -e "KEYCLOAK_ADMIN_PASSWORD=admin" quay.io/keycloak/keycloak:latest start --hostname=mykeycloak --proxy=edge
```

It takes quite a while to start. The time taken to start can be explained because a `build` is happening automatically and when it happens, multiple threads are started to re-configure the server. This is basically how re-augmentation works in Quarkus, it runs using multiple threads.

I was also able to start the container by setting `cpus=0.3`. Again, it takes even more time to start but starts without any error.

Ideally, you should favor building your own image (setting the build options) so that you just start the server when running the container (using the `--optimized` option).

But still, I was not able to force the error you are reporting.

**Comment by Herdo** [comment]
@pedroigor Hm, that's strange. Maybe it's a side-effect issue, if the production machine is already running other containers under load, so there are not enough resources left. 😕 

I'll try to separate the `build` and `start` steps as documented. If that helps, I'll close this issue. 👍 
I'm sadly well aware that this is a hard to reproduce issue. 😢

**Comment by Herdo** [comment]
@pedroigor Splitting the `build` and `start` into two independent steps did help! Thank you very much 😊
