### ISSUE TITLE
Does not fail to authenticate user when an error occurs in the processing of nonexistent role-ldap-mapper

### ISSUE THREAD

**Issue by pedro-hos** [keycloak/keycloak#14099]
### Describe the bug

If you create some wrong role mapper, save and try to log in to RH-SSO using the user (who was able to log in well before) RH-SSO crashes and keeps reloading the login screen. Getting the following error:

~~~
Caused by: javax.naming.NameNotFoundException: [LDAP: error code 32 - NO_SUCH_OBJECT: failed for MessageType : SEARCH_REQUEST
Message ID : 34
    SearchRequest
        baseDn : 'ou=WrongRole,dc=redhat,dc=com'
        filter : '(&(member=uid=user1,dc=people,dc=example,dc=com)(objectclass=groupOfNames))'
        scope : single level
        typesOnly : false
        Size Limit : no limit
        Time Limit : no limit
        Deref Aliases : deref Always
        attributes : 'uid', 'cn', 'objectclass'
org.apache.directory.api.ldap.model.message.SearchRequestImpl@46ed56ba    ManageDsaITImpl Control
        Type OID    : '2.16.840.1.113730.3.4.2'
        Criticality : 'false'
'
: ERR_268 Cannot find a partition for ou=WrongRole,dc=redhat,dc=com]; remaining name 'ou=WrongRole,dc=redhat,dc=com'
	at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3284)
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3205)
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2996)
	at java.naming/com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1875)
	at java.naming/com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1798)
	at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
	at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
	at java.naming/javax.naming.directory.InitialDirContext.search(InitialDirContext.java:276)
	at java.naming/javax.naming.directory.InitialDirContext.search(InitialDirContext.java:276)
	at org.keycloak.keycloak-ldap-federation@18.0.0.redhat-00001//org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager$3.execute(LDAPOperationManager.java:256)
	at org.keycloak.keycloak-ldap-federation@18.0.0.redhat-00001//org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager$3.execute(LDAPOperationManager.java:253)
	at org.keycloak.keycloak-ldap-federation@18.0.0.redhat-00001//org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:731)
	at org.keycloak.keycloak-ldap-federation@18.0.0.redhat-00001//org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:711)
	at org.keycloak.keycloak-ldap-federation@18.0.0.redhat-00001//org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:706)
	at org.keycloak.keycloak-ldap-federation@18.0.0.redhat-00001//org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:253)
	at org.keycloak.keycloak-ldap-federation@18.0.0.redhat-00001//org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:279)
	... 109 more
~~~

### Version

18.0.0 (tested w/ RH-SSO 7.6.0)

### Expected behavior

Return some error page, and do not crash the login page.

### Actual behavior

The login page keeps reloading the page, and user can't login.

### How to Reproduce?

1. Create an LDAP User Federation
2. Create an `role-ldap-mapper` pointing to an nonexistent dn (e.g. `ou=WrongRole,dc=redhat,dc=com`)
3. Try to authenticate with an already existing user.

It also happens if you delete the role from LDAP as well.

**Comment by pedro-hos** [comment]
I am investigating this issue, and the error comes from

https://github.com/keycloak/keycloak/blob/ef47eee2dda29a0f08187ae67970323c28947f11/federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/query/internal/LDAPQuery.java#L176

And after the failed, the following method is called over and over again

https://github.com/keycloak/keycloak/blob/ef47eee2dda29a0f08187ae67970323c28947f11/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/UserRolesRetrieveStrategy.java#L56

I don't know, but the ModelException here https://github.com/keycloak/keycloak/blob/ef47eee2dda29a0f08187ae67970323c28947f11/federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/query/internal/LDAPQuery.java#L176 

doesn't trigger the frontend error page? Is there some special exception that we can replace the ModelExeption to trigger the frontend page, and stop the `public List<LDAPObject> getLDAPRoleMappings(...) {` being called many times.

**Comment by mposolda** [comment]
@pedro-hos I agree that this will be good to fix. I am not see it as big priority as creating invalid role mapper is the corner case and from the exceptions in server.log, it should be clear to administrator what is going on. So adding "help wanted" to see if we can have contribution for improving this.

As you pointed, it will be good to make sure there is no some kind of "infinite loop" (either introducing new subclass of ModelException and/or adjust some catch blocks etc)
