### ISSUE TITLE
Unable to send email to verify admin account email, but email is valid : org.keycloak.email.EmailException: Please provide a valid address

### ISSUE THREAD

**Issue by nono-lqdn** [keycloak/keycloak#14295]
### Describe the bug

Hello,

I've been trying to verify the admin account's email. Sadly, it does not work while saying that the email is invalid. I've double checked, triple checked, and the account's mail is indeed valid, as I've sent emails to it and received them. 

How could I either, change the email address of the admin account ( I can't connect to it for the moment ), or manually verify it's email address ? 

Please see attached logs below : 

```
sept. 09 11:13:12 server kc.sh[3863624]: 2022-09-09 09:13:12,261 WARN  [org.keycloak.events] (executor-thread-260) type=CUSTOM_REQUIRED_ACTION_ERROR, realmId=xxxx, clientId=security-admin-console, userId=null, ipAddress=87.xxxx, error=expired_code, code_id=xxxx, authSessionParentId=xxxxx, authSessionTabId=xxxx
sept. 09 11:13:39 server kc.sh[3863624]: 2022-09-09 09:13:39,592 ERROR [org.keycloak.services] (executor-thread-260) KC-SERVICES0029: Failed to send email: org.keycloak.email.EmailException: Please provide a valid address
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.DefaultEmailSenderProvider.toInternetAddress(DefaultEmailSenderProvider.java:167)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:126)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:264)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:259)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:250)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:207)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendVerifyEmail(FreeMarkerEmailTemplateProvider.java:181)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.authentication.requiredactions.VerifyEmail.sendVerifyEmail(VerifyEmail.java:160)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.authentication.requiredactions.VerifyEmail.requiredActionChallenge(VerifyEmail.java:81)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.executeAction(AuthenticationManager.java:1327)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.lambda$executionActions$15(AuthenticationManager.java:1275)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.executionActions(AuthenticationManager.java:1276)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.actionRequired(AuthenticationManager.java:1149)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.nextActionAfterAuthentication(AuthenticationManager.java:996)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:1003)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.resources.LoginActionsService.requiredActionGET(LoginActionsService.java:985)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.lang.Thread.run(Thread.java:829)
sept. 09 11:13:39 server kc.sh[3863624]: 2022-09-09 09:13:39,593 ERROR [org.keycloak.authentication.requiredactions.VerifyEmail] (executor-thread-260) Failed to send verification email: org.keycloak.email.EmailException: org.keycloak.email.EmailException: Please provide a valid address
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:153)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:264)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:259)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:250)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:207)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendVerifyEmail(FreeMarkerEmailTemplateProvider.java:181)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.authentication.requiredactions.VerifyEmail.sendVerifyEmail(VerifyEmail.java:160)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.authentication.requiredactions.VerifyEmail.requiredActionChallenge(VerifyEmail.java:81)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.executeAction(AuthenticationManager.java:1327)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.lambda$executionActions$15(AuthenticationManager.java:1275)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.executionActions(AuthenticationManager.java:1276)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.actionRequired(AuthenticationManager.java:1149)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.managers.AuthenticationManager.nextActionAfterAuthentication(AuthenticationManager.java:996)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:1003)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.services.resources.LoginActionsService.requiredActionGET(LoginActionsService.java:985)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
sept. 09 11:13:39 server kc.sh[3863624]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
sept. 09 11:13:39 server kc.sh[3863624]:         at java.base/java.lang.Thread.run(Thread.java:829)
sept. 09 11:13:39 server kc.sh[3863624]: Caused by: org.keycloak.email.EmailException: Please provide a valid address
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.DefaultEmailSenderProvider.toInternetAddress(DefaultEmailSenderProvider.java:167)
sept. 09 11:13:39 server kc.sh[3863624]:         at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:126)
sept. 09 11:13:39 server kc.sh[3863624]:         ... 74 more
sept. 09 11:13:39 server kc.sh[3863624]: 2022-09-09 09:13:39,595 WARN  [org.keycloak.events] (executor-thread-260) type=SEND_VERIFY_EMAIL_ERROR, realmId=xxxx-0a16ef244788, clientId=security-admin-console, userId=59f1fc21-xxxx, ipAddress=87.xxxx, error=email_send_failed, auth_method=openid-connect, response_type=code, redirect_uri=https://sso.org.fr/auth/admin/master/console/, remember_me=false, code_id=2e1c684xxx, email=sysadmin@domain.net, response_mode=fragment, username=admin, authSessionParentId=2e1c6844-xxx, authSessionTabId=xxxx
```

### Version

18.0.2

### Expected behavior

Receive email to validate account

### Actual behavior

No email sent by Keycloak

### How to Reproduce?

?

### Anything else?

N/A

**Comment by nono-lqdn** [comment]
To anyone facing this issue, here's how I fixed it : 

- BACKUP YOUR DATABASE.
- Login to MySQL.
- Execute the following commands on the database ;
  - `use keycloak;`
  - `describe USER_REQUIRED_ACTION;` - Check the table's existence, optional. 
  - `SELECT * FROM USER_REQUIRED_ACTION;` - Check that a user indeed needs to verify it's email.
  - `SELECT * FROM USER_ENTITY WHERE name = admin;` - Verify the admin account.
  - `UPDATE USER_ENTITY SET EMAIL_VERIFIED = b'1' WHERE USERNAME = "admin";` - Update the bit of the account, setting it to a verified email address. 
  - `SELECT * FROM USER_REQUIRED_ACTION;` - Compare the UUID of the account you need to verify with the row of this table. 
  - `DELETE FROM USER_REQUIRED_ACTION WHERE USER_ID = "59f1fc21-c78d-4c7b-9b38-5uygdjydh";` - Delete the verification step needed. 
- `systemctl restart keycloak` - Restart the service to match the database state.
- Login to your account.
