### ISSUE TITLE
Creating short password with BCFIPS approved mode

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#14314]
- Start Keycloak with BCFIPS in the approved mode with command:
```
./kc.sh start-dev -Dorg.bouncycastle.fips.approved_only=true
```

- Then go to http://localhost:8080 and try to create user `admin` with password `admin`

- An "Internal server error" page displayed with the exception in server.log:
```
2022-09-09 18:11:19,127 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: org.bouncycastle.crypto.fips.FipsUnapprovedOperationError: password must be at least 112 bits
	at org.bouncycastle.crypto.fips.FipsPBKD$Parameters.<init>(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsPBKD$Parameters.<init>(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsPBKD$ParametersBuilder.using(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvPBEPBKDF2$BasePBKDF2.engineGenerateSecret(Unknown Source)
	at java.base/javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:338)
	at org.keycloak.credential.hash.Pbkdf2PasswordHashProvider.encodedCredential(Pbkdf2PasswordHashProvider.java:111)
	at org.keycloak.credential.hash.Pbkdf2PasswordHashProvider.encodedCredential(Pbkdf2PasswordHashProvider.java:75)
	at org.keycloak.credential.PasswordCredentialProvider.createCredential(PasswordCredentialProvider.java:67)
	at org.keycloak.credential.PasswordCredentialProvider.updateCredential(PasswordCredentialProvider.java:138)
	at org.keycloak.credential.LegacyUserCredentialManager.lambda$updateCredential$2(LegacyUserCredentialManager.java:98)

```

NOTE: Password creation works when password is at least 14 characters long (112 bits)

**Comment by trixpan** [comment]
@mposolda be mindful this will be indirectly connected to this and "fixing it" may cause a regression of a security bug

https://github.com/keycloak/keycloak/pull/8706/files

**Comment by mposolda** [comment]
@trixpan I don't think that the fix for this bug will break https://github.com/keycloak/keycloak/pull/8706/files .

BTV. Can I have few questions about your deployment?
- I assume you are using FIPS 140-2 environment. Is it correct?
- Are you using BCFIPS as a dependency of Keycloak? Are you using approved mode?
- Are you aware of any password policies mandatory for FIPS 140-2? It seems to me there are some recommendations, but not any strict password requirements. Or am I missing something?
- Are you using Keycloak password policy to make sure that your users have password at least 14 characters long? If yes, can you share some details about your password policy config?

Just trying to figure what could be best way to deal with this and I hope your feedback may help.
