### ISSUE TITLE
Failed to make identity provider oauth callback: java.lang.IllegalArgumentException: Host name may not be null

### ISSUE THREAD

**Issue by Antoine-Leveque** [keycloak/keycloak#14365]
### Describe the bug

Hi,

I'm getting this error message when i try de use AzureAD as Oauth provider : 
`ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-3) Failed to make identity provider oauth callback: java.lang.IllegalArgumentException: Host name may not be null
`
The keycloak instance is behind an nginx reverse proxy and configure with a web proxy. 

I think the problem is with the nginx or web-proxy configuration because I can't reproduce when running a local keycloak instance (without reverse proxy, without web proxy, same version, default parameters) 

### Version

15.0.2

### Expected behavior

Fonctionnal Oauth authentication with Azure AD

### Actual behavior

Can't log in with AzureAD informations

**Comment by husira** [comment]
Hey @Antoine-Leveque 

Could you ever solve this issue?
We ran into the same issue...

**Comment by sschu** [comment]
Did you configure the outgoing proxy settings? See https://www.keycloak.org/server/outgoinghttp.

**Comment by husira** [comment]
Hey @sschu 
Thank you for your reply.

Yes, in the end we configured the variables HTTP_PROXY, HTTPS_PROXY, and NO_PROXY for outgoing client-connections. The corresponding URL was not part of the NO_PROXY env, so the outgoing connection should go through the forward proxy in my opinion.

In our setup we upgraded from Keycloak version 15.0.2 to 16.1.1 (I now the version is a bit outdated, but it doesn't matter in this context from my point of view).
In the Version 15.0.2 we still used the http-proxy.cli to add the proxy-mappings:

`PROXY_URL=http://sample-proxy-url:8080`
`ENABLE_PROXY_CONFIG=true`

```
# cat /opt/jboss/tools/cli/http-proxy.cli

embed-server --server-config=standalone.xml --std-out=echo
# In case there is no connectionsHttpClient definition yet

# Configure the proxy-mappings
/subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-mappings,value=[".*\\.sample-url\\.com;${env.PROXY_URL:http://sample-proxy-url:8080}"])
```

Regarding the documentation (https://www.keycloak.org/docs/16.1/server_installation/#_proxy_env_vars) we could also use the standard proxy environment. So we removed the ENV vars PROXY_URL & ENABLE_PROXY_CONFIG and added the standard proxy environment variables like HTTP_PROXY, HTTPS_PROXY, and NO_PROXY. We did this in addition to the upgrade to Keycloak 16.1.1.

In our Keycloak we have configured multiple Realms. Every Realm uses it's own Identity-Provider. Some Identity Providers use the SAML protocol, others use OpenID-Connect.

After upgrading to Keycloak 16.1.1 including the new standard proxy environment variables, all end user logins with SAML Identity-Providers worked as expected. But all user logins, where the Identity-Provider used OpenID-Connect, did not work. We always received the following error in the Log for all oidc logins:

```
[0m[33m08:00:25,209 WARN  [org.keycloak.events] (default task-147) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=xyz, clientId=xyz-test, userId=null, ipAddress=84.X.Y.Z, error=identity_provider_login_failure, code_id=66e8087d-5db0-4423-b8d5-621xf82cf187, authSessionParentId=66e8087d-5db0-4423-b8d5-621f983cf187, authSessionTabId=Hmakdm8mClI
[0m[31m08:00:40,308 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-147) Failed to make identity provider oauth callback: java.lang.IllegalArgumentException: Host name may not be null
            at org.apache.httpcomponents.core//org.apache.http.util.Args.containsNoBlanks(Args.java:81)
            at org.apache.httpcomponents.core//org.apache.http.HttpHost.<init>(HttpHost.java:80)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.connections.httpclient.ProxyMappings$ProxyMapping.valueOf(ProxyMappings.java:244)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.connections.httpclient.ProxyMappings.withFixedProxyMapping(ProxyMappings.java:123)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.connections.httpclient.DefaultHttpClientFactory.lazyInit(DefaultHttpClientFactory.java:172)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.connections.httpclient.DefaultHttpClientFactory.create(DefaultHttpClientFactory.java:77)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.connections.httpclient.DefaultHttpClientFactory.create(DefaultHttpClientFactory.java:63)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:316)
            at jdk.internal.reflect.GeneratedMethodAccessor367.invoke(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
            at org.keycloak.keycloak-services@16.1.1//com.sun.proxy.$Proxy128.getProvider(Unknown Source)
            at org.keycloak.keycloak-server-spi-private@16.1.1//org.keycloak.broker.provider.util.SimpleHttp.doPost(SimpleHttp.java:113)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.generateTokenRequest(AbstractOAuth2IdentityProvider.java:532)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.broker.oidc.OIDCIdentityProvider$OIDCEndpoint.generateTokenRequest(OIDCIdentityProvider.java:324)
            at org.keycloak.keycloak-services@16.1.1//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:500)
            at jdk.internal.reflect.GeneratedMethodAccessor1120.invoke(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
            at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
            at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
```

Maybe I misunderstand the documentation and the proxy mapping is still mandatory or is that not the case?

In addition to the upgrade, we also changed the `PROXY_ADDRESS_FORWARDING` ENV var from `false` to `true`, so that the client-ip will be logged in the Keycloak log under "ipAddress". In my opinion this should not have an impact on this.

Additional Info: our Keycloak runs in a K8s Cluster with istio services-mesh. So there is an istio sidecar proxy in the keycloak pod.

**Comment by sschu** [comment]
I also don't think that `PROXY_ADDRESS_FORWARDING` is related. If I get the stack trace right, Keycloak is trying to establish a connection to the proxy but the for some reason the host name of the proxy is null. I would probably attach a debugger to find out why that is...

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by husira** [comment]
From my perspective you can close this issue. We were able to connect successfully with Keycloak v21 through the HTTP_PROXY settings. According to docs, the HTTP_PROXY & HTTPS_PROXY env variable must always start with the Protocol.

https://www.keycloak.org/server/outgoinghttp#_proxy_mappings_for_outgoing_http_requests

Example: HTTP_PROXY=http:/my-proxy.example.com:8080

At that time were we had the issue, we made the mistake of defining the proxy as follows.
HTTP_PROXY=my-proxy.example.com:8080

I assume that the proxy settings did not work properly then and it tried to connect via proxy mappings instead of HTTP_PROXY Env. This would also match with the StackTrace I sent (commented [on Oct 27, 2022](https://github.com/keycloak/keycloak/issues/14365#issuecomment-1293280575).

**Comment by viniciusczar** [comment]
I had that problem with docker keycloak. Look the network if you are using docker. Test the dns resolution to 8.8.8.8 are being achieved
