### ISSUE TITLE
Unexpected error when handling authentication request to identity provider.

### ISSUE THREAD

**Issue by artemkrim** [keycloak/keycloak#14438]
### Describe the bug

A clean server, I can't login to the web under a local admin,but I can token api */realms/master/protocol/openid-connect/token
```
2022-09-15 22:04:54,065 WARN  [org.keycloak.services] (executor-thread-0) KC-SERVICES0013: Failed authentication: java.lang.ClassCastException: class org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity cannot be cast to class org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper (org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity and org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @77468bd9)
	at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.get(InfinispanChangelogBasedTransaction.java:128)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionEntity(InfinispanUserSessionProvider.java:332)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:265)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:260)
	at org.keycloak.authentication.AuthenticationProcessor.lambda$attachSession$0(AuthenticationProcessor.java:1056)
	at org.keycloak.utils.LockObjectsForModification.lockObjectsForModification(LockObjectsForModification.java:75)
	at org.keycloak.utils.LockObjectsForModification.lockUserSessionsForModification(LockObjectsForModification.java:65)
	at org.keycloak.authentication.AuthenticationProcessor.attachSession(AuthenticationProcessor.java:1056)
	at org.keycloak.services.managers.AuthenticationManager.finishedRequiredActions(AuthenticationManager.java:1061)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationComplete(AuthenticationProcessor.java:1118)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:985)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:314)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:285)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:277)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:342)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-09-15 22:04:54,113 WARN  [org.keycloak.events] (executor-thread-0) type=LOGIN_ERROR, realmId=80e52ba2-a638-40b0-b251-1718e96ae13a, clientId=security-admin-console, userId=null, ipAddress=192.168.144.36, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://keycloak-test.domain.ru/admin/master/console/, consent=no_consent_required, code_id=0bf7364f-ad93-472c-96fb-ad5160bd4b62, username=admin, authSessionParentId=0bf7364f-ad93-472c-96fb-ad5160bd4b62, authSessionTabId=sWW5XRm3uoM
```

### Version

quarkus 19.0.1

**Comment by avanlangup** [comment]
I have same error on KC 21.1.1 and ISPN remote server 14.0.9.Final-1

` ERROR  [o.k.s.e.KeycloakErrorHandler:61] (executor-thread-0) Uncaught server error: 
java.lang.ClassCastException: class org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity cannot be cast to class org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper 
(org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity and org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @19e0dffe)
	at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.get(InfinispanChangelogBasedTransaction.java:128)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionEntity(InfinispanUserSessionProvider.java:325)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:258)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:253)`

**Comment by JiChunRong** [comment]
How to solve this problem doesn't seem to be very clear to me? Could you please provide me with the detailed solution?
