### ISSUE TITLE
Race condition bug with EntityManagerFactory on custom providers

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#14570]
### Describe the bug

There is a problem with custom providers that try to do database changes in the `postInit` method.
The [scim-for-keycloak#59](https://github.com/Captain-P-Goldfish/scim-for-keycloak/issues/59) project is currently suffering from this  problem

It happens more often if the cache is set to `local` but it is not bound to that. It even happened with cache config `ispn`.

I added a `RealmResourceProvider` implementation that tries to create roles in existing realms and adds these roles to the admin user of the master realm. This code is now broken and prevents startup if the race condition fails.

Here is the code of the `RealmResourceProvider`

```java
public class ScimEndpointProviderFactory implements RealmResourceProviderFactory
{

  /**
   * this ID identifies the rest provider and is used as base context path for this module
   */
  public static final String ID = ContextPaths.SCIM_BASE_PATH;

  /**
   * @return the ID of this module that is used as base context path
   */
  @Override
  public String getId()
  {
    return ID;
  }

  /**
   * keycloak calls this method to create an instance of {@link ScimEndpointProvider} with each incoming request
   *
   * @param session the {@link KeycloakSession} object holds the authentication details about the current user
   *          and the realm the user is currently using
   * @return the {@link ScimEndpointProvider}
   */
  @Override
  public RealmResourceProvider create(KeycloakSession session)
  {
    return new ScimEndpointProvider(session);
  }

  @Override
  public void init(Config.Scope config)
  {
    // do nothing
  }

  /**
   * initialize the keycloak-scim environment
   */
  @Override
  public void postInit(KeycloakSessionFactory factory)
  {
    RealmRoleInitializer.initializeRoles(factory);
  }

  @Override
  public void close()
  {
    // do nothing
  }

}
```

within the postInit method the `RealmRoleInitializer` is called that executes this code:

```java
/**
   * initializes the {@link #SCIM_ADMIN_ROLE} on all existing realms if not present and makes sure that the role
   * will also be added to all new created realms
   */
  @SneakyThrows
  public static void initializeRoles(KeycloakSessionFactory keycloakSessionFactory)
  {
    if (isHotDeploying())
    {
      log.info("initializing scim-sdk-server");
      KeycloakModelUtils.runJobInTransaction(keycloakSessionFactory, RealmRoleInitializer::setupRealmAccess);
    }
    else
    {
      log.debug("Server startup, waiting for PostMigrationEvent");
    }

    registerEventListener(keycloakSessionFactory);
  }
```

And the call to `KeycloakModelUtils.runJobInTransaction` causes the problem. I also tried a for-loop around this block but it did not help. 

Here is the corresponding stacktrace

```
2022-09-24 10:14:35,133 ERROR [de.captaingoldfish.scim.sdk.keycloak.provider.RealmRoleInitializer] (main) Failed to initialize database for scim-sdk-server: Cannot invoke "javax.persistence.EntityManagerFactory.createEntityManager(javax.persistence.SynchronizationType)" because "emf" is null: java.lang.NullPointerException: Cannot invoke "javax.persistence.EntityManagerFactory.createEntityManager(javax.persistence.SynchronizationType)" because "emf" is null
        at org.keycloak.quarkus.runtime.storage.database.jpa.AbstractJpaConnectionProviderFactory.createEntityManager(AbstractJpaConnectionProviderFactory.java:107)
        at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.create(LegacyJpaConnectionProviderFactory.java:81)
        at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.create(LegacyJpaConnectionProviderFactory.java:65)
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:270)
        at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:64)
        at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:40)
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:270)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:153)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmsStream(RealmCacheSession.java:484)
        at de.captaingoldfish.scim.sdk.keycloak.provider.RealmRoleInitializer.setupRealmAccess(RealmRoleInitializer.java:111)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:250)
        at de.captaingoldfish.scim.sdk.keycloak.provider.RealmRoleInitializer.initializeRoles(RealmRoleInitializer.java:53)
        at de.captaingoldfish.scim.sdk.keycloak.provider.ScimEndpointProviderFactory.postInit(ScimEndpointProviderFactory.java:62)
        at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:42)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:302)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

Any suggestions on this?

### Version

18.0.0 - 19.0.2

### How to Reproduce?

Install the provider from https://github.com/Captain-P-Goldfish/scim-for-keycloak/releases with version kc-18-b1 (also compatible with keycloak 19!!!) and start the server over and over again until the problem occurs...
In my case it is hard to reproduce it. In the case of others it seems hard not to run into this issue. See https://github.com/Captain-P-Goldfish/scim-for-keycloak/issues/59

In my case I could almost reliably reproduce it now when doing this:

1. set cache to local
2. configure database (postgres seems to be a good candidate)
3. install provider
4. build server
5. start on windows
6. start on linux over wsl

the joke so far was that the problem occurs in my case almost always if I start directly on windows and then over wsl on my ubuntu subsystem or vice versa.

**Comment by hmlnarik** [comment]
The `isHotDeploying()` method signals falsely that the all "core" provider factories including datasource provider have been initialized. It seems this method does not account for Quarkus where hot deployment is not possible, and the provider factory of the SCIM extension is initialized at the same phase as regular provider factories (as confirmed by the `at  org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:96)` line).

That code has to be executed only after Keycloak has started and all factories have been initialized, i.e. after the `PostMigrationEvent` event.

**Comment by Captain-P-Goldfish** [comment]
thanks for the explanation.
I was hoping that transactions should be available during initialization. But in this case I will solve the problem differently.

**Comment by huguesn** [comment]
For anyone looking, I was able to resolve the issue by overriding `dependsOn` on my factory, to make sure it loads **after** the JPA Connection provider.

```java
@Override
public Set<Class<? extends Provider>> dependsOn() {
    // This is to avoid a race condition when JPA is loaded after this factory
    return Set.of(JpaConnectionProvider.class);
}
```
