### ISSUE TITLE
Custom Cache-Definitions for HotRod-Map-Storage

### ISSUE THREAD

**Issue by dominikschlosser** [keycloak/keycloak#14584]
### Description

Is there currently a way to customize the HotRod map storage cache definitions? Specifically, I would like to configure a cache persistence.
Configuring the caches in Infinispan itself unfortunately leads to the problem that I would have to disable the indexing feature due to missing proto-schema files.

Optimally, there would be an option to pass an infinispan.xml file so that Keycloak continues to create the caches itself incl. schema.

### Motivation

In principle, HotRod storage enables the use case of a write-through cache and, in our case, cross-site sessions via a cross-site database in the background. However, for this to work it must be possible to customize the Infinispan caches.

### Details

Infinispan-Exception when trying to configure a cache with indexing myself (Infinispan Version 12.1):

```
2022-09-30 08:29:07,004 ERROR (main) [org.infinispan.factories.ComponentRegistry] ISPN000538: Error stopping module org.infinispan.query.impl.LifecycleManager:users 
org.infinispan.commons.CacheConfigurationException: ISPN028022: The declared indexed type 'kc.HotRodAttributeEntity' is not known. Please register its proto schema file first
        at org.infinispan.query.remote.impl.LazySearchMapping.createMapping(LazySearchMapping.java:160)
        at org.infinispan.query.remote.impl.util.LazyRef.get(LazyRef.java:23)
        at org.infinispan.query.remote.impl.LazySearchMapping.mapping(LazySearchMapping.java:131)
        at org.infinispan.query.remote.impl.LazySearchMapping.close(LazySearchMapping.java:70)
        at org.infinispan.query.impl.LifecycleManager.cacheStopping(LifecycleManager.java:376)
        at org.infinispan.factories.ComponentRegistry.preStop(ComponentRegistry.java:251)
        at org.infinispan.factories.AbstractComponentRegistry.stop(AbstractComponentRegistry.java:305)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:265)
        at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:214)
        at org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:1015)
        at org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDelegatingCache.java:512)
        at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:698)
        at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:644)
        at org.infinispan.manager.DefaultCacheManager.internalGetCache(DefaultCacheManager.java:533)
        at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:511)
        at org.infinispan.security.actions.GetCacheAction.run(GetCacheAction.java:26)
        at org.infinispan.security.actions.GetCacheAction.run(GetCacheAction.java:14)
        at org.infinispan.security.Security.doPrivileged(Security.java:61)
        at org.infinispan.globalstate.impl.SecurityActions.doPrivileged(SecurityActions.java:30)
        at org.infinispan.globalstate.impl.SecurityActions.getCache(SecurityActions.java:39)
        at org.infinispan.globalstate.impl.GlobalConfigurationManagerImpl.start(GlobalConfigurationManagerImpl.java:94)
        at org.infinispan.globalstate.impl.CorePackageImpl$2.start(CorePackageImpl.java:59)
        at org.infinispan.globalstate.impl.CorePackageImpl$2.start(CorePackageImpl.java:48)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:604)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:595)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:564)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:787)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:354)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:750
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:718)
        at org.infinispan.server.SecurityActions.lambda$startCacheManager$1(SecurityActions.java:68)
        at org.infinispan.security.Security.doPrivileged(Security.java:56)
        at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:39)
        at org.infinispan.server.SecurityActions.startCacheManager(SecurityActions.java:71)
        at org.infinispan.server.Server.run(Server.java:363)
        at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:160)
        at org.infinispan.server.tool.Main.run(Main.java:98)
        at org.infinispan.server.Bootstrap.main(Bootstrap.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.infinispan.server.loader.Loader.run(Loader.java:106)
        at org.infinispan.server.loader.Loader.main(Loader.java:51)
```

**Comment by dominikschlosser** [comment]
After further testing, the issue seems to be a side-effect inside of infinispan when the cache-store cannot be initialized. The error-message kind of hides the real issue.
