### ISSUE TITLE
Unable to import realm via helm chart during startup

### ISSUE THREAD

**Issue by Hollerweger** [keycloak/keycloak#14600]
### Describe the bug

When I import a realm via helm chart and mount the realm to the import directory the importing and startup always fails.
Same realm file works via manual import (on UI) and also when running via docker directly (same mount path and start command).
All works fine if I just remove the import-realm command at startup and manually import the realm via UI.
I also checked the mounted realm file on the pod is 100% identical and also has full access right for all users.

Issue is that I couldn't find anything regarding the errors logged.
Adding --log-level=debug at startup does not seems to add any more valuable information.
Even when I start the pod with entrypoint /bin/bash sleep 36000 and then shell into the pod and run same command it works.
Also tested now with different realm jsons.

Error on first start with empty db:
```
2022-09-27 09:20:22,321 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled                                     │
│ 2022-09-27 09:20:22,403 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal                                                │
│ 2022-09-27 09:20:22,490 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'                     │
│ 2022-09-27 09:20:22,896 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final                                          │
│ 2022-09-27 09:20:23,097 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`                                                                            │
│ 2022-09-27 09:20:23,098 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups config │
│ 2022-09-27 09:20:23,214 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB         │
│ 2022-09-27 09:20:23,214 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB     │
│ 2022-09-27 09:20:23,214 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB         │
│ 2022-09-27 09:20:23,214 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB     │
│ 2022-09-27 09:20:25,222 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) keycloak-try-5545dbd6d5-996dw-62727: no members discovered after 2002 ms: creating cluster as coordinator    │
│ 2022-09-27 09:20:25,231 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-try-5545dbd6d5-996dw-62727|0] (1) [keycloak-try-5545 │
│ 2022-09-27 09:20:25,235 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-try-5545dbd6d5-996dw-62727`, physical addresses are `[10.0.14.17 │
│ 2022-09-27 09:20:25,994 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: keycloak-try-5545dbd6d5-996dw-62727, Site name: null               │
│ 2022-09-27 09:20:27,093 INFO  [org.infinispan.CLUSTER] (Thread-8) ISPN000080: Disconnecting JGroups channel `ISPN`                                                                                  │
│ 2022-09-27 09:20:28,534 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master. │
│ 2022-09-27 09:20:35,797 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode                                                │
│ 2022-09-27 09:20:35,797 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Cache container has been stopped and cannot be reused. Recreate the cache container.  
```
Error on second run on same db.
```
 2022-09-27 09:22:26,991 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)                                                              │
│ 2022-09-27 09:22:26,999 WARN  [org.keycloak.services] (main) KC-SERVICES0005: Unable to import realm test from file /opt/keycloak/bin/../data/import/test-realm.json.: org.infinispan.commons.Illeg │
│ alLifecycleStateException: ISPN000324: Cache 'realms' is in 'STOPPING' state and this is an invocation not belonging to an on-going transaction, so it does not accept new invocations. Either rest │
│ art it or recreate the cache container.                                                                                                                                                             │
│     at org.infinispan.interceptors.impl.InvocationContextInterceptor.ignoreCommand(InvocationContextInterceptor.java:100)                                                                           │
│     at org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:86)                                                                             │
│     at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:247)                                                                                        │
│     at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:297)                                                                                                               │
│     at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:101)                                                                                                                 │
│     at org.infinispan.cache.impl.CacheImpl.get(CacheImpl.java:542)                                                                                                                                  │
│     at org.infinispan.cache.impl.CacheImpl.get(CacheImpl.java:536)                                                                                                                                  │
│     at org.infinispan.cache.impl.AbstractDelegatingCache.get(AbstractDelegatingCache.java:439)                                                                                                      │
│     at org.infinispan.cache.impl.EncoderCache.get(EncoderCache.java:683)                                                                                                                            │
│     at org.keycloak.models.cache.infinispan.CacheManager.get(CacheManager.java:95)                                                                                                                  │
│     at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientScopeById(RealmCacheSession.java:1221)                                                                                       │
│     at org.keycloak.models.jpa.JpaRealmProvider.lambda$getClientScopes$21(JpaRealmProvider.java:929)                                                                                                │
│     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)                                                                                                          │
│     at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)                                                                                                                             │
│     at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)                                                                                                │
│     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)                                                                                                              │
│     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)                                                                                                       │
│     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)                                                                                                         │
│     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                                                                                                              │
│     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)                                                                                                             │
│     at org.hibernate.query.spi.StreamDecorator.collect(StreamDecorator.java:209)                                                                                                                    │
│     at org.keycloak.utils.ClosingStream.collect(ClosingStream.java:182)                                                                                                                             │
│     at org.keycloak.models.jpa.JpaRealmProvider.getClientScopes(JpaRealmProvider.java:932)                                                                                                          │
│     at org.keycloak.storage.ClientStorageManager.getClientScopes(ClientStorageManager.java:212)                                                                                                     │
│     at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientScopes(RealmCacheSession.java:1339)                                                                                          │
│     at org.keycloak.models.jpa.ClientAdapter.getClientScopes(ClientAdapter.java:366)                                                                                                                │
│     at org.keycloak.models.utils.ModelToRepresentation.toRepresentation(ModelToRepresentation.java:705)                                                                                             │
│     at org.keycloak.validation.DefaultClientValidationProvider.validatePairwiseInClientModel(DefaultClientValidationProvider.java:232)                                                              │
│     at org.keycloak.validation.DefaultClientValidationProvider.validate(DefaultClientValidationProvider.java:137)                                                                                   │
│     at org.keycloak.validation.ValidationUtil.validateClient(ValidationUtil.java:41)                                                                                                                │
│     at org.keycloak.validation.ValidationUtil.validateClient(ValidationUtil.java:28)                                                                                                                │
│     at org.keycloak.storage.datastore.LegacyExportImportManager.createClients(LegacyExportImportManager.java:474)                                                                                   │
│     at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:312)                                                                                     │
│     at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:127)                                                                                                  │
│     at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:558)                                                                                                               │
│     at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:496)                                                                                                               │
│     at org.keycloak.services.resources.KeycloakApplication.importRealm(KeycloakApplication.java:299)                                                                                                │
│     at org.keycloak.services.resources.KeycloakApplication.importRealms(KeycloakApplication.java:275)                                                                                               │
│     at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:208)       
│ 2022-09-27 09:22:27,017 INFO  [org.infinispan.CLUSTER] (Thread-8) ISPN000080: Disconnecting JGroups channel `ISPN`                                                                                  │
│ 2022-09-27 09:22:27,103 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode                                                │
│ 2022-09-27 09:22:27,103 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Cache container has been stopped and cannot be reused. Recreate the cache container.                                    
```

Error on third run on same db
```
│
│ 2022-09-27 09:25:18,203 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: keycloak.develop.dds.com, Strict HTTPS: │
│  true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true                                                                                    │
│ 2022-09-27 09:25:19,996 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider                                         │
│ 2022-09-27 09:25:22,509 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled                                     │
│ 2022-09-27 09:25:22,599 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal                                                │
│ 2022-09-27 09:25:22,691 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'                     │
│ 2022-09-27 09:25:23,115 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final                                          │
│ 2022-09-27 09:25:23,221 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`                                                                            │
│ 2022-09-27 09:25:23,221 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups config │
│ uration!                                                                                                                                                                                            │
│ 2022-09-27 09:25:23,306 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB         │
│ 2022-09-27 09:25:23,307 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB     │
│ 2022-09-27 09:25:23,307 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB         │
│ 2022-09-27 09:25:23,307 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB     │
│ 2022-09-27 09:25:25,315 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) keycloak-try-5545dbd6d5-996dw-34968: no members discovered after 2003 ms: creating cluster as coordinator    │
│ 2022-09-27 09:25:25,322 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-try-5545dbd6d5-996dw-34968|0] (1) [keycloak-try-5545 │
│ dbd6d5-996dw-34968]                                                                                                                                                                                 │
│ 2022-09-27 09:25:25,326 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-try-5545dbd6d5-996dw-34968`, physical addresses are `[10.0.14.17 │
│ 6:50548]`                                                                                                                                                                                           │
│ 2022-09-27 09:25:26,018 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: keycloak-try-5545dbd6d5-996dw-34968, Site name: null               │
│ 2022-09-27 09:25:27,014 INFO  [org.infinispan.CLUSTER] (Thread-8) ISPN000080: Disconnecting JGroups channel `ISPN`                                                                                  │
│ 2022-09-27 09:25:27,193 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode                                                │
│ 2022-09-27 09:25:27,193 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000323: Cache 'realmRevisions' is in 'TERMINATED' state and so it does not accept new  │
│ invocations. Either restart it or recreate the cache container.                                                                                                                                     │
│ 2022-09-27 09:25:27,193 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' t │
│ o see the details about the usage of the particular command.        
```

Errors on further runs:
```
2022-09-27 09:28:36,602 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) keycloak-try-5545dbd6d5-996dw-9281: no members discovered after 2002 ms: creating cluster as coordinator     │
│ 2022-09-27 09:28:36,612 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-try-5545dbd6d5-996dw-9281|0] (1) [keycloak-try-5545d │
│ 2022-09-27 09:28:36,616 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-try-5545dbd6d5-996dw-9281`, physical addresses are `[10.0.14.176 │
│ 2022-09-27 09:28:37,302 WARN  [org.infinispan.factories.GlobalComponentRegistry] (keycloak-cache-init) ISPN000126: Attempted to stop() from FAILED state, but caught exception: java.lang.IllegalSt │
│     at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)                                                                                                        │
│     at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:244)                                                                                                                             │
│     at org.infinispan.factories.GlobalComponentRegistry.removeShutdownHook(GlobalComponentRegistry.java:181)                                                                                        │
│     at org.infinispan.factories.AbstractComponentRegistry.internalStop(AbstractComponentRegistry.java:372)                                                                                          │
│     at org.infinispan.factories.AbstractComponentRegistry.stop(AbstractComponentRegistry.java:308)                                                                                                  │
│     at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:265)                                                                                                 │
│     at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:766)                                                                                                       │
│     at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:734)                                                                                                               │
│     at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:405)                                                                                                              │
│     at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:86)                                                                    │
│     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                                           │
│     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                                                                                    │
│     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                                    │
│     at java.base/java.lang.Thread.run(Thread.java:829)                                                     
```
### Version

Tested with 19.0.2 and 18.0.2

### Expected behavior

Import works on startup and detailed logs are shown in case of an error.

### How to Reproduce?

helm deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  # keep only last 2 replicate sets (default=10)
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: app-dds-keycloak-realm-import-try
          configMap:
            name: app-dds-keycloak-file-config-try
            items:
              - key: test-realm.json
                path: test-realm.json
        - name: app-dds-ldaps-trust-store-try
          configMap:
            name: app-dds-keycloak-file-config-try
            items:
              - key: ldap-rs-truststore.jks
                path: ldap-rs-truststore.jks
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/opt/keycloak/bin/kc.sh",
                     "start",
                     "--import-realm",
                     #"--log-level=debug",
                     #"--spi-truststore-file-file=/opt/keycloak/bin/ldapsTrustStore/ldap-rs-truststore.jks",
                     #"--spi-truststore-file-password=change-it",
                     #"--hostname-strict-https=false" # only needed for access via http
          ]
          env:
            # required because rs ldap has no subject set in certificate
            - name: JAVA_TOOL_OPTIONS
              value: "-Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KEYCLOAK_CREATE_ADMIN_USER
              value: "true"
            - name: KC_DB
              value: "mssql"
            - name: KC_TRANSACTION_XA_ENABLED
              value: "false"
            - name: KC_DB_URL
              value: "jdbc:sqlserver://{{ .Values.environmentConfig.server }}:{{ .Values.environmentConfig.port }};databaseName={{ .Values.environmentConfig.databaseName }}"
            - name: KC_DB_USERNAME
              value: {{ .Values.environmentConfig.databaseUser }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: DATABASE_PASSWORD
            - name: KC_HOSTNAME
              value: {{ .Values.environmentConfig.keycloakHost }}
            - name: KC_PROXY
              value: {{ .Values.environmentConfig.keycloakProxy }}
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.environmentConfig.keycloakUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: app-dds-keycloak-realm-import-try
              mountPath: /opt/keycloak/data/import
              readOnly: true
            - name: app-dds-ldaps-trust-store-try
              mountPath: /opt/keycloak/bin/ldapsTrustStore
              readOnly: true
          livenessProbe:
            initialDelaySeconds: {{ .Values.service.initialDelaySeconds }}
            httpGet:
              path: /health/live
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.service.initialDelaySeconds }}
            httpGet:
              path: /health/ready
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

```

file-configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-dds-keycloak-file-config-try
binaryData:
  test-realm.json: |-
    {{ .Files.Get (printf "%s" .Values.configmap.keycloak.realm_import_loc) | b64enc | indent 4 }}
  ldap-rs-truststore.jks: |-
    {{ .Files.Get (printf "%s" .Values.configmap.keycloak.ldap_rs_truststore_loc) | b64enc | indent 4 }}
```

**Comment by Hollerweger** [comment]
It seems after many restarts and retries (10 to 15) it actually works.
I can reproduce it again when I clean the db it needs again 10 to 15 times to start up successfully.

**Comment by Hollerweger** [comment]
Realm import works fine after prebuilding the image and then using the optimized image with "--optimized".
So seems that implicit auto build does not work together with --import-realm.

**Comment by lexcao** [comment]
> Seems that there is a bug that prevents to use implicit auto build together with --import-realm.

Yes, seems it could be resolved by https://github.com/keycloak/keycloak/issues/14369#issuecomment-1252839120
And I found this https://github.com/keycloak/keycloak/pull/14228

**Comment by Hollerweger** [comment]
> Realm import works fine after prebuilding the image and then using the optimized image with "--optimized". Seems that there is a bug that prevents to use implicit auto build together with --import-realm. Wasted two full days on this...

Seems this was just a lucky run. I have the issue now again even with the optimized image on 19.0.2.
Disabled auto import now and switched to manual import.

**Comment by Hollerweger** [comment]
> > Seems that there is a bug that prevents to use implicit auto build together with --import-realm.
> 
> Yes, seems it could be resolved by [#14369 (comment)](https://github.com/keycloak/keycloak/issues/14369#issuecomment-1252839120) And I found this #14228

I'm already running with --optimized and also with latest version. Issue is still appearing.

**Comment by pedroigor** [comment]
@Hollerweger Is the issue still happening?

**Comment by pedroigor** [comment]
Please, re-open if you have more details about how to reproduce it.

It has been a while and perhaps this issue is no longer happening when using latest versions.

We also had some improvements when importing realms at startup so that they are aligned with the `import` command. See https://github.com/keycloak/keycloak/pull/16282.
