### ISSUE TITLE
Database Connection to MariaDB using Unix Socket fails

### ISSUE THREAD

**Issue by Catty2014** [keycloak/keycloak#14608]
### Describe the bug

When trying to connect to mariadb with unix socket(/run/mysqld/mysqld.sock), the program fails.

### Version

19.0.2

### Expected behavior

Keycloak connects to database with unix socket correctly.

### Actual behavior

Keycloak exits with error.
```
Sep 27 20:55:30 my-server systemd[1]: Started Keycloak server.
Sep 27 20:55:30 my-server kc.sh[73767]: Changes detected in configuration. Updating the server image.
Sep 27 20:55:30 my-server kc.sh[73767]: Updating the configuration and installing your custom providers, if any. Please wait.
Sep 27 20:55:37 my-server kc.sh[73767]: 2022-09-27 20:55:37,233 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 5055ms
Sep 27 20:55:37 my-server kc.sh[73767]: Server configuration updated and persisted. Run the following command to review the configuration:
Sep 27 20:55:37 my-server kc.sh[73767]:         kc.sh show-config
Sep 27 20:55:37 my-server kc.sh[73767]: Next time you run the server, just run:
Sep 27 20:55:37 my-server kc.sh[73767]:         kc.sh start --optimized -cf=/etc/keycloak/keycloak.conf
Sep 27 20:55:40 my-server kc.sh[73757]: 2022-09-27 20:55:39,089 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: login.cattysteve.top, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
Sep 27 20:55:40 my-server kc.sh[73757]: 2022-09-27 20:55:40,262 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
Sep 27 20:55:40 my-server kc.sh[73757]: 2022-09-27 20:55:40,941 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Failed to create connection due to IllegalArgumentException
Sep 27 20:55:40 my-server kc.sh[73757]: 2022-09-27 20:55:40,943 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.lang.IllegalArgumentException: connect: The address can't be null
Sep 27 20:55:40 my-server kc.sh[73757]:         at java.base/java.net.Socket.connect(Socket.java:634)
Sep 27 20:55:40 my-server kc.sh[73757]:         at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:252)
Sep 27 20:55:40 my-server kc.sh[73757]:         at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:524)
Sep 27 20:55:40 my-server kc.sh[73757]:         at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1389)
Sep 27 20:55:40 my-server kc.sh[73757]:         at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
Sep 27 20:55:40 my-server kc.sh[73757]:         at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
Sep 27 20:55:40 my-server kc.sh[73757]:         at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:275)
Sep 27 20:55:40 my-server kc.sh[73757]:         at org.mariadb.jdbc.MariaDbDataSource.getXAConnection(MariaDbDataSource.java:453)
Sep 27 20:55:40 my-server kc.sh[73757]:         at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
Sep 27 20:55:40 my-server kc.sh[73757]:         at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
Sep 27 20:55:40 my-server kc.sh[73757]:         at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
Sep 27 20:55:40 my-server kc.sh[73757]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Sep 27 20:55:40 my-server kc.sh[73757]:         at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
Sep 27 20:55:40 my-server kc.sh[73757]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
Sep 27 20:55:40 my-server kc.sh[73757]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Sep 27 20:55:40 my-server kc.sh[73757]:         at java.base/java.lang.Thread.run(Thread.java:955)
Sep 27 20:55:41 my-server kc.sh[73757]: 2022-09-27 20:55:41,609 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
Sep 27 20:55:41 my-server kc.sh[73757]: 2022-09-27 20:55:41,615 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
Sep 27 20:55:41 my-server kc.sh[73757]: 2022-09-27 20:55:41,625 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
Sep 27 20:55:41 my-server kc.sh[73757]: 2022-09-27 20:55:41,822 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
Sep 27 20:55:41 my-server kc.sh[73757]: 2022-09-27 20:55:41,929 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
Sep 27 20:55:41 my-server kc.sh[73757]: 2022-09-27 20:55:41,929 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
Sep 27 20:55:42 my-server kc.sh[73757]: 2022-09-27 20:55:42,008 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
Sep 27 20:55:42 my-server kc.sh[73757]: 2022-09-27 20:55:42,009 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
Sep 27 20:55:42 my-server kc.sh[73757]: 2022-09-27 20:55:42,009 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
Sep 27 20:55:42 my-server kc.sh[73757]: 2022-09-27 20:55:42,009 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
Sep 27 20:55:44 my-server kc.sh[73757]: 2022-09-27 20:55:44,028 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) my-server-44033: no members discovered after 2003 ms: creating cluster as coordinator
Sep 27 20:55:44 my-server kc.sh[73757]: 2022-09-27 20:55:44,037 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [my-server-44033|0] (1) [my-server-44033]
Sep 27 20:55:44 my-server kc.sh[73757]: 2022-09-27 20:55:44,041 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `my-server-44033`, physical addresses are `[***]`
Sep 27 20:55:44 my-server kc.sh[73757]: 2022-09-27 20:55:44,486 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
Sep 27 20:55:44 my-server kc.sh[73757]: 2022-09-27 20:55:44,667 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
Sep 27 20:55:44 my-server kc.sh[73757]: 2022-09-27 20:55:44,668 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: connect: The address can't be null
Sep 27 20:55:44 my-server kc.sh[73757]: 2022-09-27 20:55:44,668 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
Sep 27 20:55:44 my-server systemd[1]: keycloak.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 20:55:44 my-server systemd[1]: keycloak.service: Failed with result 'exit-code'.
Sep 27 20:55:44 my-server systemd[1]: keycloak.service: Consumed 1min 29.649s CPU time.
```

### How to Reproduce?

Running `systemctl start keycloak` or run keycloak directly(`sudo -u keycloak /usr/bin/kc.sh -cf /etc/keycloak/keycloak.conf --verbose start`) could reproduce.
Relevant settings in keycloak.conf:
```
# Basic settings for running in production. Change accordingly before deploying the server.                 
                                                                 
# Database

# The database vendor.
db=mariadb

# The username of the database user.
db-username=keycloak

# The password of the database user.
#db-password=<mariadb-password>

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
db-url=jdbc:mariadb://localhost:3306/keycloak?localSocket=/var/run/mysqld/mysqld.sock
```

### Anything else?

MariaDB is configured not to listen on TCP(skip-networking).
When MariaDB listen on TCP, connection still fails.
Additionally, when using `db-url=jdbc:mariadb://localhost:3306/keycloak`, it works.

---
On [MariaDB Knowledge Base](https://mariadb.com/kb/en/about-mariadb-connector-j/), it says:
> JNA (net.java.dev.jna:jna) and JNA-PLATFORM (net.java.dev.jna:jna-platform) 4.2.1 or greater are also needed when you would like to connect to the server with Unix sockets or windows pipes.

Would it be relevant?

**Comment by ririsoft** [comment]
Hello,
Has this to be MySQL specific or can we have PostgreSQL connection with Unix Sockets too ?
