### ISSUE TITLE
Keycloak 18.0.0 - Upgrade to 19.0.2 - ISPN Cache error

### ISSUE THREAD

**Issue by DerGreul** [keycloak/keycloak#14657]
### Describe the bug

Dear community,

while patching our keycloak from 18.0.0 to 19.0.2 I experience the following error:

2022-09-29 16:16:07,980 WARN  [org.infinispan.statetransfer.InboundTransferTask] (jgroups-9,keycloak-16847) ISPN000210: Failed to request state of cache authenticationSessions from node birdkey-5239, segments {0-255}: org.infinispan.commons.CacheException: ExceptionResponse(java.io.EOFException)
        at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
        at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
        at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1495)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1397)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
        at org.jgroups.JChannel.up(JChannel.java:780)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
        at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
        at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
        at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
        at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
        at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
        at org.jgroups.protocols.Discovery.up(Discovery.java:300)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

After this messagt the start fails. Starting in dev-mode is possible.

We are not running a HA (like described in #12630  or #12718)  or distributed keycloak (yet), therefore we are not using ISPN Caching. I used the build option "--cache local" but that didn't solve the problem. 

Best regards,
Michael

### Version

18.0.0

**Comment by lexcao** [comment]
Hi, @DerGreul 
Could you please provide your startup scripts?

I think it seems related to https://github.com/keycloak/keycloak/issues/14369#issuecomment-1252839120

**Comment by DerGreul** [comment]
Hi @lexcao,

thank you for your reply.

Right now I'm just following the upgrade-guide:

https://www.keycloak.org/docs/latest/upgrading/index.html

> Procedure
> 1. Download the new server archive
> 
> 2. Move the downloaded archive to the desired location.
> 
> 3. Extract the archive. This step installs a clean instance of the latest Keycloak release.
> 
> 4. Copy conf/, providers/ and themes/ from the previous installation to the new installation.
> 
> 5. Re-build the server with bin/kc.[sh|bat] build unless you are using auto-build

After Build I try to start the Automatic database migration:

> kc.[sh|bat] start --spi-connections-jpa-default-migration-strategy=update

Here I run into the described error. 

I also tried the following without success:

> kc.sh start --optimized

Show-config:

> Current Mode: production
> Current Configuration:
>         kc.cache =  ispn (PersistedConfigSource)
>         kc.config.built =  true (SysPropConfigSource)
>         kc.db =  postgres (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.db-password =  ******* (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.db-url =  jdbc:postgresql://localhost:5432/keycloak (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.db-username =  xxx (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.health-enabled =  false (PersistedConfigSource)
>         kc.hostname =  auth.ucc.ovgu.de (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.http-enabled =  false (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-19.0.2.jar!/META-INF/keycloak.conf])
>         kc.http-relative-path =  / (PersistedConfigSource)
>         kc.https-certificate-file =  ${kc.home.dir}conf/keycloak.cert.pem (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.https-certificate-key-file =  ${kc.home.dir}conf/keycloak.priv.pem (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-19.0.2.jar!/META-INF/keycloak.conf])
>         kc.log-file =  ${kc.home.dir:default}${file.separator}data${file.separator}log${file.separator}keycloak.log (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-19.0.2.jar!/META-INF/keycloak.conf])
>         kc.metrics-enabled =  false (PersistedConfigSource)
>         kc.proxy =  reencrypt (PropertiesConfigSource[source=file:/opt/keycloak/bin/../conf/keycloak.conf])
>         kc.spi-map-storage-concurrenthashmap-dir =  ${kc.home.dir:default}${file.separator}data${file.separator}chm (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-19.0.2.jar!/META-INF/keycloak.conf])
>         kc.spi-map-storage-concurrenthashmap-key-type-authz-resource-servers =  string (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-19.0.2.jar!/META-INF/keycloak.conf])
>         kc.spi-map-storage-concurrenthashmap-key-type-realms =  string (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-19.0.2.jar!/META-INF/keycloak.conf])
>         kc.spi-map-storage-concurrenthashmap-key-type-single-use-objects =  string (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-19.0.2.jar!/META-INF/keycloak.conf])
>         kc.version =  19.0.2 (SysPropConfigSource)


Do I need to change  "kc.cache =  ispn (PersistedConfigSource)"?

Best regards,
Michael

**Comment by hmlnarik** [comment]
Adding @martin-kanis to check if this has any area/storage connotations.

**Comment by martin-kanis** [comment]
I don't see any relation to storage, therefore removing the label. The problem seems to be same as here https://github.com/keycloak/keycloak/issues/12718. @DerGreul Can you please go through the comments and check whether they help you?

**Comment by DerGreul** [comment]
Hello, 
sorry for the late response. #12718 didn't really help me.

My solution was:
- Delete all java-script from realms (it was not used anymore anyways)
- Export Database (postgresql)
- Create docker-instance 
- Import Database and upgrade to 20.0.1

Thank you a lot for your input and help.
