### ISSUE TITLE
X509/Validate Username Form settings button error:  Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by KenRoy-Octo** [keycloak/keycloak#14882]
### Describe the bug

When I add the X509/Validate Username Form step to my authentication flow and then click the settings button (i.e. "cog" icon) I get the following error in my browser:

"Cannot convert undefined or null to object"

The browser console shows:

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at convertToFormValues (index.0187f463.js:170:84473)
    at y (FlowDetails.5d3c40c1.js:1:8286)
    at FlowDetails.5d3c40c1.js:1:8603
    at f5 (index.0187f463.js:27:6884)
    at e.unstable_runWithPriority (index.0187f463.js:19:3947)
    at he (index.0187f463.js:23:38808)
    at ne (index.0187f463.js:27:6348)
    at o6 (index.0187f463.js:25:10821)
    at index.0187f463.js:23:39030

### Version

19.0.3

### Expected behavior

I expect to see the form described here:  
https://www.keycloak.org/docs/latest/server_admin/#_x509

### Actual behavior

 I get the following error in my browser:

"Cannot convert undefined or null to object"

### How to Reproduce?

1) Navigate to "Authentication" for a realm
2) Click the flow name to edit
3) Click "Add step"
4) Select "X509/VAlidate Username Form"
5) Click "Add"
6) Click the settings button (i.e. "cog" icon"

**Comment by KenRoy-Octo** [comment]
Additional testing with previous versions shows 19.0.0 and 19.0.1 work, but 19.0.2 and 19.0.3 do not work.

**Comment by KenRoy-Octo** [comment]
Works when disabling "admin2" feature (i.e. the old version of the interface still works but not v2)

**Comment by alfredsName** [comment]
> Works when disabling "admin2" feature (i.e. the old version of the interface still works but not v2)

how to disable?
