### ISSUE TITLE
Unable to do export using postgres in docker compose.

### ISSUE THREAD

**Issue by jerdie** [keycloak/keycloak#15208]
### Area

core

### Describe the bug

I have this error when running export:
```
 - quarkus.datasource.jdbc.driver is set to 'org.postgresql.xa.PGXADataSource' but it is build time fixed to 'org.h2.jdbcx.JdbcDataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
2022-10-28 10:17:09,019 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://keycloak19-postgresql-local:5432/keycloak
2022-10-28 10:17:09,020 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://keycloak19-postgresql-local:5432/keycloak
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
.
.
.

2022-10-28 10:17:12,329 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-10-28 10:17:12,463 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-10-28 10:17:12,463 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-10-28 10:17:12,463 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No suitable driver found for jdbc:postgresql://keycloak19-postgresql-local:5432/keycloak
2022-10-28 10:17:12,464 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

```

### Version

19.0.2

### Expected behavior

Should be able to export

### Actual behavior

Error in logs during export 

### How to Reproduce?

Please try:

```
services:

  keycloak19-local:
    image: 'quay.io/keycloak/keycloak:19.0.2'
    container_name: keycloak19-local
    volumes:
      - ./imports/keycloak-${KEYCLOAK_VERSION}:/opt/jboss/keycloak/imports
      - ./keycloak/standalone/deployments:/opt/jboss/keycloak/standalone/deployments
    ports:
      - "5501:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=12345678
      - KC_DB=postgres
      - KC_DB_SCHEMA=public
      - KC_DB_URL=jdbc:postgresql://keycloak19-postgresql-local:5432/keycloak
      - KC_DB_USERNAME=keycloak-pg-local
      - KC_DB_PASSWORD=12345678
      - KC_HOSTNAME_STRICT=false
    command:
      - export --dir /data
    # entrypoint: bash
    # stdin_open: true
    # tty: true
    volumes:
      - ./data:/data
    depends_on:
      - keycloak19-postgresql-local

  keycloak19-postgresql-local:
    image: 'postgres:alpine'
    container_name: keycloak19-postgresql-local
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak-pg-local
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./data/keycloak-postgres:/var/lib/postgresql/data

```

**Comment by jerdie** [comment]
created custom image and used `RUN /opt/keycloak/bin/kc.sh build` in Dockerfile

see: https://www.keycloak.org/server/containers

**Comment by mposolda** [comment]
Changing the label as this looks more related to quarkus distribution. But maybe it is already fixed in latest release?
@jerdie Any chance to try with latest Keycloak 21.0.1 (without your custom image).
