### ISSUE TITLE
db parameter not working in 19.0.3

### ISSUE THREAD

**Issue by alanosman** [keycloak/keycloak#15238]
### Area

authentication

### Describe the bug

Hi, 

I am new to Keycloak and somewhat successfully worked my way through Keycloak documentation, and examples to get Keycloak running on a server hosted on our development cluster at Amazon. Our DB is RDS, and we use MySQL.

Running on Ubuntu 22.04.1 LTS
Keycloak release 19.0.3

I have been successful at getting KC running in a Docker image. I have managed to configure the server to use our HTTPS certificate, and now I am attempting to configure it so it can access our own DB.  

However, I am struggling to try to get it to connect to our MySQL DB instance and receiving an error (below).  I have created an empty Keycloak DB and pointed the `db` fields in a sh scrip that I run to launch the docker container.

This script is along these lines.

```
docker run \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  -e KC_HTTPS_CERTIFICATE_FILE=/home/ubuntu/myappserver/ssl/server.crt.pem \
  -e KC_HTTPS_CERTIFICATE_KEY_FILE=/home/ubuntu/myappserver/ssl/server.key.pem \
  -e KC_HTTPS_PORT=8080 \
  -e KC_DB=mysql \
  -e KC_DB_PORT=3306 \
  -e KC_DB_DATABASE=KEYCLOAK-TEST \
  -e KC_DB_URL=jdbc:mysql://mycompany-appdb-qa.abc1234.us-east-1.rds.amazonaws.com:3306/KEYCLOAK-TEST \
  -e KC_DB_USERNAME=dbuser \
  -e KC_DB_PASSWORD=dbpassword \
  -v /home/ubuntu/myappserver/ssl/server.crt.pem:/home/ubuntu/myappserver/ssl/server.crt.pem \
  -v /home/ubuntu/myappserver/ssl/server.key.pem:/home/ubuntu/myappserver/ssl/server.key.pem \
  -p 8080:8080 \
  --name keycloak quay.io/keycloak/keycloak:19.0.3 \
  start --optimized --hostname dev.mycompany.com
```

I get this error.  I'm a little perplexed about where to go next with this.

```
2022-11-01 02:02:23,635 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: dev.mycompany.com, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2022-11-01 02:02:25,493 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-11-01 02:02:26,253 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.jdbc.driver is set to 'com.mysql.cj.jdbc.MysqlXADataSource' but it is build time fixed to 'org.h2.jdbcx.JdbcDataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
2022-11-01 02:02:26,540 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:mysql://mycompany-appdb-qa.caoptnj7gqij.us-east-1.rds.amazonaws.com:3306/KEYCLOAK-TEST
2022-11-01 02:02:26,548 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:mysql://mycompany-appdb-qa.caoptnj7gqij.us-east-1.rds.amazonaws.com:3306/KEYCLOAK-TEST
        at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
        at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

2022-11-01 02:02:27,584 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:mysql://mycompany-appdb-qa.caoptnj7gqij.us-east-1.rds.amazonaws.com:3306/KEYCLOAK-TEST
2022-11-01 02:02:27,668 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-11-01 02:02:27,690 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-11-01 02:02:27,703 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-11-01 02:02:28,010 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-11-01 02:02:28,155 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-11-01 02:02:28,155 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2022-11-01 02:02:28,257 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-11-01 02:02:28,258 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2022-11-01 02:02:28,258 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2022-11-01 02:02:28,259 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2022-11-01 02:02:30,275 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 7de4cae52c53-51502: no members discovered after 2006 ms: creating cluster as coordinator
2022-11-01 02:02:30,286 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [7de4cae52c53-51502|0] (1) [7de4cae52c53-51502]
2022-11-01 02:02:30,292 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `7de4cae52c53-51502`, physical addresses are `[172.17.0.2:43223]`
2022-11-01 02:02:31,398 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-11-01 02:02:31,477 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-11-01 02:02:31,478 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-11-01 02:02:31,478 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No suitable driver found for jdbc:mysql://mycompany-appdb-qa.caoptnj7gqij.us-east-1.rds.amazonaws.com:3306/KEYCLOAK-TEST
2022-11-01 02:02:31,478 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

19.0.3

### Expected behavior

should not have an error

### Actual behavior

see bug description

### How to Reproduce?

```
docker run \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  -e KC_HTTPS_CERTIFICATE_FILE=/home/ubuntu/myappserver/ssl/server.crt.pem \
  -e KC_HTTPS_CERTIFICATE_KEY_FILE=/home/ubuntu/myappserver/ssl/server.key.pem \
  -e KC_HTTPS_PORT=8080 \
  -e KC_DB=mysql \
  -e KC_DB_PORT=3306 \
  -e KC_DB_DATABASE=KEYCLOAK-TEST \
  -e KC_DB_URL=jdbc:mysql://mycompany-appdb-qa.abc1234.us-east-1.rds.amazonaws.com:3306/KEYCLOAK-TEST \
  -e KC_DB_USERNAME=dbuser \
  -e KC_DB_PASSWORD=dbpassword \
  -v /home/ubuntu/myappserver/ssl/server.crt.pem:/home/ubuntu/myappserver/ssl/server.crt.pem \
  -v /home/ubuntu/myappserver/ssl/server.key.pem:/home/ubuntu/myappserver/ssl/server.key.pem \
  -p 8080:8080 \
  --name keycloak quay.io/keycloak/keycloak:19.0.3 \
  start --optimized --hostname dev.mycompany.com
````

### Anything else?

I wasn't sure if this is a bug or if I am missing something, but the documentation is kind of tough to follow with so many configurations and options.  Maybe the docs should have clear steps you can follow depending on the environment you want to start with.  i.e. Configuring a Docker Server on AWS.  The term production is also confusing, considering that we are just attempting to set up a server for development testing.

**Comment by predictap-droscoe** [comment]
I think `start --optimized` might be preventing it from loading the driver, try running it with `start-dev` to get it to rebuild based on current settings on startup. If that works you can follow the guide [here](https://www.keycloak.org/server/containers) to build a custom image with mysql enabled.

**Comment by NingGelin** [comment]
I encountered the same problem because I didn't create a database

**Comment by OtenMoten** [comment]
> I think `start --optimized` might be preventing it from loading the driver, try running it with `start-dev` to get it to rebuild based on current settings on startup. If that works you can follow the guide [here](https://www.keycloak.org/server/containers) to build a custom image with mysql enabled.

That works for me. I tried to switch from `H2 `to `MariaDB`.

There was an error `that jdbc:h2` is expected, even I configured `KC_DB: mariadb`

The problem was that I started via `start --optimized`. Then I changed to `start `and it's rebuild.

After that I can successfully connect Keycloak with the database.

**Comment by mabartos** [comment]
@alanosman Thanks for creating this issue, and thanks y'all for the comments!

Yes, that's right; it's not possible to start the  Keycloak instance with the `--optimized` flag and required DB without executing the build phase of the server. It means that you can use either the `start` command without the `--optimized` flag, or just build your own image with the `build` command and specified DB and then start the instance also with the `--optimized` flag.
