### ISSUE TITLE
KeycloakErrorHandler throws NPE if session is missing

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#15278]
### Area

core

### Describe the bug

[KeycloakErrorHandler](https://github.com/keycloak/keycloak/blame/9f95b6ec63489f70df98617ece794e1ce2c9f0df/services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java#L61) is prone to throwing NullPointerExceptions if the current request does not have a session attached.

### Version

20.0.0

### Expected behavior

The KeycloakErrorHandler should be more robust to missing session context information.

### Actual behavior

An internal server error with status code 500 is shown instead of the actual error, e.g. FileNotFound.

### How to Reproduce?

1) Run Keycloak 20.0.0 with a custom metrics path prefix
```
docker run -it \
  -p 8080:8080 \
  -p 8443:8443 \
  -p 8787:8787 \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  -e DEBUG=true \
  -e DEBUG_PORT='0.0.0.0:8787' \
  quay.io/keycloak/keycloak:20.0.0 \
  --verbose \
  start \
  --cache=local \
  --metrics-enabled=true \
  --http-enabled=true \
  --http-relative-path=auth \
  --hostname-strict=false \
  --hostname-strict-https=false \
  --spi-events-listener-jboss-logging-success-level=info \
  --spi-events-listener-jboss-logging-error-level=warn \
  --features=preview \
  -Dquarkus.smallrye-metrics.path=/actuator/metrics
```
2) Try access the old metrics path http://localhost:8080/auth/metrics
3) Observe the NPE in the log
```
2022-11-02 10:08:58,479 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /auth/metrics failed, error id: fdaf3232-703a-4e55-8a2d-d52aef05a557-1: java.lang.NullPointerException
	at org.keycloak.services.error.KeycloakErrorHandler.getResponse(KeycloakErrorHandler.java:61)
	at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:56)
	at org.jboss.resteasy.core.ExceptionHandler.executeExceptionMapper(ExceptionHandler.java:136)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:309)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:258)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The actual exception is:
```
javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/metrics
```

The new path: `http://localhost:8080/actuator/metrics`.

### Anything else?

This is also reproducable with Keycloak 19.0.3

**Comment by ioemat** [comment]
I was about updating your fix to current main branch and then learned that it no longer can be reproduced with build from `main`.

Current builds return `404/not found` as expected - without throwing an NPE.

**Comment by thomasdarimont** [comment]
Just confirmed that this is no longer an issue with the nightly image (keycloak 21.0.0)
````docker run -it \
  -p 8080:8080 \
  -p 8443:8443 \
  -p 8787:8787 \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  -e DEBUG=true \
  -e DEBUG_PORT='0.0.0.0:8787' \
  quay.io/keycloak/keycloak:nightly \
  --verbose \
  start \
  --cache=local \
  --metrics-enabled=true \
  --http-enabled=true \
  --http-relative-path=auth \
  --hostname-strict=false \
  --hostname-strict-https=false \
  --spi-events-listener-jboss-logging-success-level=info \
  --spi-events-listener-jboss-logging-error-level=warn \
  --features=preview \
  -Dquarkus.smallrye-metrics.path=/actuator/metrics
````

**Comment by thomasdarimont** [comment]
Note that the custom quarkus metrics path doesn't work in he nightly image (1c79a56, keycloak 21.0.0).

The metrics are exposed via `/auth/metrics`,  however the path `/actuator/metrics` yields a 404 file not found

**Comment by ioemat** [comment]
@thomasdarimont 
This is probably because of the switch to [micrometer metrics](https://github.com/keycloak/keycloak/commit/3c6e2c3c1e291370c3df672c4651ec0ec2df4a1e).

Instead of `-Dquarkus.smallrye-metrics.path=/actuator/metrics`  you can use 
`-Dquarkus.micrometer.export.prometheus.path=/actuator/metrics` to achieve the same result.

Setting `quarkus.http.non-application-root-path` to `/actuator` also moves the metrics endpoint to `/actuator/metrics`, but of course affects e.g. also the health endpoints.

As mentioned in #17166, the issue described above is still there when setting `quarkus.http.non-application-root-path`.

Since the scope of my finding is similar but different, I created an own issue for that, but linked it here.
