### ISSUE TITLE
Multipod (kubernetes) upgrade from v19 to v20 fails

### ISSUE THREAD

**Issue by benzitohhh** [keycloak/keycloak#15326]
### Area

infinispan

### Describe the bug

During deployment there is a period of time when old (v19) and new (v20) pods are running simultaneously.

But old and new Infinispan clients/messages are incompatible, resulting in `ClassNotFoundException`:
```
ERROR [org.infinispan.CLUSTER] (jgroups-11,cipher-login-v2-67667bcbc4-rnggl-2946) ISPN000474: Error processing request 546503@cipher-login-v2-555cc56c57-zcjnx-6790: java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.entities.ActionTokenReducedKey$ExternalizerImpl
```

This prevents the new Keycloak pods from starting, and also prevents the old pods from rolling back (seems like Infinispan gets into a confused state).

We eventually had to kill all of our pods and start again.

### Version

19.0.3 and 20.0.0

### Expected behavior

Upgrading from two v19 pods to two v20 pods should run smoothly.

We would expect the new pods to start up gracefully, and then for the old pods to be removed.

### Actual behavior

When upgrading from two v19 pods to two v20 pods, it is possible that old and new pods are running simultaneously for a short period.

During this time, the old and new infinispan clients/messages are incompatible, resulting in the below kinds of Exception.

Also it seems that this gets Infinispan into a confused state, so rollback is not possible.

Here are the logs from a v20 pod trying to start up:
```
2022-11-03 05:16:24,004 ERROR [org.infinispan.CLUSTER] (jgroups-11,cipher-login-v2-67667bcbc4-rnggl-2946) ISPN000474: Error processing request 546503@cipher-login-v2-555cc56c57-zcjnx-6790: java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.entities.ActionTokenReducedKey$ExternalizerImpl
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.infinispan.marshall.exts.ClassExternalizer.readObject(ClassExternalizer.java:37)
	at org.infinispan.marshall.exts.ClassExternalizer.readObject(ClassExternalizer.java:12)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.marshall.core.GlobalMarshaller.readAnnotated(GlobalMarshaller.java:732)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:712)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.container.entries.MortalCacheEntry$Externalizer.readObject(MortalCacheEntry.java:127)
	at org.infinispan.container.entries.MortalCacheEntry$Externalizer.readObject(MortalCacheEntry.java:115)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.commons.marshall.MarshallUtil.lambda$unmarshallCollection$0(MarshallUtil.java:295)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:278)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
	at org.infinispan.marshall.exts.CollectionExternalizer.readObject(CollectionExternalizer.java:103)
	at org.infinispan.marshall.exts.CollectionExternalizer.readObject(CollectionExternalizer.java:28)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.statetransfer.StateChunk$Externalizer.readObject(StateChunk.java:88)
	at org.infinispan.statetransfer.StateChunk$Externalizer.readObject(StateChunk.java:65)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.commons.marshall.MarshallUtil.lambda$unmarshallCollection$0(MarshallUtil.java:295)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:278)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
	at org.infinispan.commands.statetransfer.StateResponseCommand.readFrom(StateResponseCommand.java:125)
	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:170)
	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:88)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1455)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1395)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:146)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1586)
	at org.jgroups.JChannel.up(JChannel.java:780)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
	at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
	at org.jgroups.protocols.Discovery.up(Discovery.java:300)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

And here are the logs from a v19 pod trying to start up again (roll back):
```
JAVA_OPTS already set in environment; overriding default settings with values: -Djgroups.dns.query=cipher-login-v2-headless-svc
2022-11-03 05:35:22,178 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2022-11-03 05:35:23,071 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-11-03 05:35:24,184 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-11-03 05:35:24,229 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-11-03 05:35:24,243 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-11-03 05:35:24,460 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-11-03 05:35:24,583 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2022-11-03 05:35:24,713 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [cipher-login-v2-555cc56c57-zcjnx-6790|24] (3) [cipher-login-v2-555cc56c57-zcjnx-6790, cipher-login-v2-67667bcbc4-rnggl-621, cipher-login-v2-b96757795-tpnml-32409]
2022-11-03 05:35:24,721 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `cipher-login-v2-b96757795-tpnml-32409`, physical addresses are `[10.1.6.11:7800]`
2022-11-03 05:36:21,921 INFO  [org.infinispan.CLUSTER] (jgroups-15,cipher-login-v2-b96757795-tpnml-32409) ISPN000094: Received new cluster view for channel ISPN: [cipher-login-v2-67667bcbc4-rnggl-621|25] (2) [cipher-login-v2-67667bcbc4-rnggl-621, cipher-login-v2-b96757795-tpnml-32409]
2022-11-03 05:36:21,925 INFO  [org.infinispan.CLUSTER] (jgroups-15,cipher-login-v2-b96757795-tpnml-32409) ISPN100001: Node cipher-login-v2-555cc56c57-zcjnx-6790 left the cluster
2022-11-03 05:36:22,075 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: cipher-login-v2-b96757795-tpnml-32409, Site name: null
2022-11-03 05:36:22,660 INFO  [io.quarkus] (main) Keycloak 19.0.3 on JVM (powered by Quarkus 2.7.6.Final) started in 61.737s. Listening on: http://0.0.0.0:8080/
2022-11-03 05:36:22,660 INFO  [io.quarkus] (main) Profile prod activated. 
2022-11-03 05:36:22,660 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-11-03 05:36:39,395 ERROR [org.infinispan.CLUSTER] (jgroups-6,cipher-login-v2-b96757795-tpnml-32409) ISPN000474: Error processing request 0@cipher-login-v2-67667bcbc4-rnggl-621: java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.entities.SingleUseObjectValueEntity$ExternalizerImpl
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.infinispan.marshall.exts.ClassExternalizer.readObject(ClassExternalizer.java:37)
	at org.infinispan.marshall.exts.ClassExternalizer.readObject(ClassExternalizer.java:12)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.marshall.core.GlobalMarshaller.readAnnotated(GlobalMarshaller.java:732)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:712)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.commands.triangle.SingleKeyBackupWriteCommand.readFrom(SingleKeyBackupWriteCommand.java:152)
	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:170)
	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:88)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1454)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1394)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
	at org.jgroups.JChannel.up(JChannel.java:780)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
	at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
	at org.jgroups.protocols.Discovery.up(Discovery.java:300)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-11-03 05:36:42,423 INFO  [org.infinispan.CLUSTER] (jgroups-6,cipher-login-v2-b96757795-tpnml-32409) ISPN000094: Received new cluster view for channel ISPN: [cipher-login-v2-b96757795-tpnml-32409|26] (1) [cipher-login-v2-b96757795-tpnml-32409]
2022-11-03 05:36:42,423 INFO  [org.infinispan.CLUSTER] (jgroups-6,cipher-login-v2-b96757795-tpnml-32409) ISPN100001: Node cipher-login-v2-67667bcbc4-rnggl-621 left the cluster
2022-11-03 05:36:42,435 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=offlineClientSessions] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 117
2022-11-03 05:36:42,442 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=authenticationSessions] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 115
2022-11-03 05:36:42,444 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=sessions] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 117
2022-11-03 05:36:42,446 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=org.infinispan.CONFIG] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 105
2022-11-03 05:36:42,448 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=work] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 104
2022-11-03 05:36:42,449 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=clientSessions] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 117
2022-11-03 05:36:42,451 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=org.infinispan.COUNTER] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 117
2022-11-03 05:36:42,452 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=offlineSessions] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 117
2022-11-03 05:36:42,454 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=org.infinispan.CLIENT_SERVER_TX_TABLE] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 105
2022-11-03 05:36:42,456 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=actionTokens] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 23
2022-11-03 05:36:42,457 INFO  [org.infinispan.CLUSTER] (non-blocking-thread--p2-t1) [Context=loginFailures] ISPN100007: After merge (or coordinator change), recovered members [cipher-login-v2-b96757795-tpnml-32409] with topology id 117
```

### How to Reproduce?

* Start two v19 pods (Kubernetes, Infinispan)
* Update to two v20 pods

**Comment by sschu** [comment]
Zero downtime updates are not supported currently, you will have to shutdown the old version completely and then bring up the new version. Zero downtime upgrades will be supported with the new store.

**Comment by benzitohhh** [comment]
> Zero downtime updates are not supported currently, you will have to shutdown the old version completely and then bring up the new version. Zero downtime upgrades will be supported with the new store.

Ah ok @sschu thanks for letting us know
