### ISSUE TITLE
Error when loading public keys

### ISSUE THREAD

**Issue by axi92** [keycloak/keycloak#15346]
### Area

oidc

### Describe the bug

Client type: OpenID Connect

```
2022-11-04 11:21:01,699 DEBUG [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (executor-thread-9) Trying to use proxy mapping from env vars
2022-11-04 11:21:01,699 DEBUG [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (executor-thread-9) httpProxy: null, noProxy: null
2022-11-04 11:21:01,704 WARN  [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (executor-thread-9) TruststoreProvider is disabled
2022-11-04 11:21:01,948 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-9) Uncaught server error: java.lang.RuntimeException: Error when loading public keys: java.lang.NullPointerException
	at org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider.getPublicKey(InfinispanPublicKeyStorageProvider.java:167)
	at org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider.getFirstPublicKey(InfinispanPublicKeyStorageProvider.java:126)
	at org.keycloak.keys.loader.PublicKeyStorageManager.getClientPublicKeyWrapper(PublicKeyStorageManager.java:62)
	at org.keycloak.jose.jws.DefaultTokenManager.getEncryptedToken(DefaultTokenManager.java:256)
	at org.keycloak.jose.jws.DefaultTokenManager.encodeAndEncrypt(DefaultTokenManager.java:231)
	at org.keycloak.protocol.oidc.TokenManager$AccessTokenResponseBuilder.build(TokenManager.java:1246)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.createTokenResponse(TokenEndpoint.java:472)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.codeToToken(TokenEndpoint.java:440)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider.getPublicKey(InfinispanPublicKeyStorageProvider.java:157)
	... 56 more
Caused by: java.lang.NullPointerException
	at java.base/java.net.URI$Parser.parse(URI.java:3104)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at org.keycloak.connections.httpclient.DefaultHttpClientFactory$1.get(DefaultHttpClientFactory.java:111)
	at org.keycloak.protocol.oidc.utils.JWKSHttpUtils.sendJwksRequest(JWKSHttpUtils.java:36)
	at org.keycloak.keys.loader.ClientPublicKeyLoader.loadKeys(ClientPublicKeyLoader.java:74)
	at org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider$WrapperCallable.call(InfinispanPublicKeyStorageProvider.java:227)
	at org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider$WrapperCallable.call(InfinispanPublicKeyStorageProvider.java:207)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider.getPublicKey(InfinispanPublicKeyStorageProvider.java:151)
	... 56 more

2022-11-04 11:21:01,952 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-9) JtaTransactionWrapper rollback
2022-11-04 11:21:01,954 FINE  [org.postgresql.jdbc.PgConnection] (executor-thread-9)   setAutoCommit = true
2022-11-04 11:21:01,954 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-9) Initiating JDBC connection release from afterTransaction
2022-11-04 11:21:01,957 DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (executor-thread-9) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
2022-11-04 11:21:01,957 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-9) JtaTransactionWrapper end
```

### Version

20.0.0

### Expected behavior

Keycloak can load the public key

### Actual behavior

Cant load public keys

### How to Reproduce?

I imported the settings from our keycloak 14 instance.

### Anything else?

This is the application that uses the client, at first it looked for me that it was an issue there.
There are also screenshots from my client configuration
https://github.com/greenpau/caddy-security/issues/177

**Comment by axi92** [comment]
I hate it when that happens, I am on this for 3 days now and you always find a solution when you are writing a ticket xD

I just created the client from scratch and it works. Looks like the import did not work.
I will try it on the prod environment and report my findings =)

**Comment by axi92** [comment]
Import failed for me, and new created client worked :+1:
