### ISSUE TITLE
Special characters (Umlaute) in cookie (KEYCLOAK_REMEMBER_ME) leads to 500 internal server error

### ISSUE THREAD

**Issue by Grillpfanne** [keycloak/keycloak#15383]
### Area

oidc

### Describe the bug

Username contains ß character. When selecting "remember me" while logging in, the KEYCLOAK_REMEMBER_ME cookie is written with this username.
This crashes the oidc flow with `
15:04:02,005 ERROR [io.undertow.request] (default task-229) UT005023: Exception handling request to /auth/realms/master/protocol/openid-connect/auth: java.lang.IllegalArgumentException: UT000173: An invalid control character [223] was present in the cookie value or attribute
`
Same errros can be found for 
`/auth/realms/master/login-actions/authenticate, /auth/realms/master/protocol/openid-connect/logout, /auth/realms/master/protocol/openid-connect/login-status-iframe.html`

### Version

12.0.4

### Expected behavior

OIDC login/logout works as normal.

### Actual behavior

OIDC flow breaks and Keycloak throws a 500 internal server error.

Logs:
` 
2022-11-07 16:04:3 at java.base/java.lang.Thread.run(Thread.java:829) 
2022-11-07 16:04:3 at org.jboss.xnio@3.8.2.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) 
2022-11-07 16:04:3 at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) 
2022-11-07 16:04:3 at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) 
2022-11-07 16:04:3 at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990) 
2022-11-07 16:04:3 at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:69) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.spec.ServletContextImpl.getSession(ServletContextImpl.java:948) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.spec.ServletContextImpl.getSession(ServletContextImpl.java:858) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.session.InMemorySessionManager.getSession(InMemorySessionManager.java:221) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.spec.ServletContextImpl$ServletContextSessionConfig.findSessionId(ServletContextImpl.java:1235) 
2022-11-07 16:04:3 at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.session.CodecSessionConfig.findSessionId(CodecSessionConfig.java:59) 
2022-11-07 16:04:3 at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.spec.SessionCookieConfigImpl.findSessionId(SessionCookieConfigImpl.java:61) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.session.SessionCookieConfig.findSessionId(SessionCookieConfig.java:83) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.HttpServerExchange.getRequestCookie(HttpServerExchange.java:1170) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.server.HttpServerExchange.requestCookies(HttpServerExchange.java:1189) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.util.Cookies.parseRequestCookies(Cookies.java:210) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.util.Cookies.parseRequestCookies(Cookies.java:219) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.util.Cookies.parseRequestCookies(Cookies.java:241) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.util.Cookies.parseCookie(Cookies.java:299) 
2022-11-07 16:04:3 at io.undertow.core@2.2.2.Final//io.undertow.util.LegacyCookieSupport.isHttpSeparator(LegacyCookieSupport.java:149) 
2022-11-07 16:04:3 
15:04:39,605 ERROR [io.undertow.request] (default task-229) UT005023: Exception handling request to /auth/realms/master/protocol/openid-connect/logout: java.lang.IllegalArgumentException: UT000173: An invalid control character [223] was present in the cookie value or attribute`

### How to Reproduce?

Use username with special character, e.g. ß, and tick the "remember me" box when logging in.

### Anything else?

I tried to find this bug on Github or in Keycloak changelogs, but wasn't able to. So I decided to file this Bug, even though I tested with an older Keycloak version.

**Comment by sschu** [comment]
Can you please check if it still persists in the current version?

**Comment by abstractj** [comment]
Thanks for taking the time to submit this issue. However, we were unable to reproduce the mentioned steps. We no longer support the version mentioned on this issue, and we strongly recommend people upgrade to the latest releases of Keycloak.

If you can reproduce the issue using the [latest releases of Keycloak](https://www.keycloak.org/downloads), please reopen this issue, including a reproducer.
