### ISSUE TITLE
cluster deployment bug

### ISSUE THREAD

**Issue by liubinwang2009** [keycloak/keycloak#15413]
### Area

infinispan

### Describe the bug

```
 org.infinispan.util.concurrent.TimeoutException: ISPN000299: Unable to acquire lock after 10 seconds for key 7c8af00f-79d6-429e-a8e7-86c83414ead4 and requestor GlobalTx:local:40208146. Lock is held by GlobalTx:local:40208116
	at org.infinispan.util.concurrent.locks.impl.DefaultLockManager$KeyAwareExtendedLockPromise.get(DefaultLockManager.java:288)
	at org.infinispan.util.concurrent.locks.impl.DefaultLockManager$KeyAwareExtendedLockPromise.lock(DefaultLockManager.java:261)
	at org.infinispan.interceptors.locking.PessimisticLockingInterceptor.localLockCommandWork(PessimisticLockingInterceptor.java:208)
	at org.infinispan.interceptors.locking.PessimisticLockingInterceptor.visitLockControlCommand(PessimisticLockingInterceptor.java:187)
	at org.infinispan.commands.control.LockControlCommand.acceptVisitor(LockControlCommand.java:117)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndHandle(BaseAsyncInterceptor.java:184)
	at org.infinispan.interceptors.impl.TxInterceptor.visitLockControlCommand(TxInterceptor.java:223)
	at org.infinispan.commands.control.LockControlCommand.acceptVisitor(LockControlCommand.java:117)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:55)
	at org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:54)
	at org.infinispan.interceptors.DDAsyncInterceptor.visitLockControlCommand(DDAsyncInterceptor.java:160)
	at org.infinispan.commands.control.LockControlCommand.acceptVisitor(LockControlCommand.java:117)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndExceptionally(BaseAsyncInterceptor.java:124)
	at org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:90)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:57)
	at org.infinispan.interceptors.impl.BatchingInterceptor.handleDefault(BatchingInterceptor.java:75)
	at org.infinispan.interceptors.DDAsyncInterceptor.visitLockControlCommand(DDAsyncInterceptor.java:160)
	at org.infinispan.commands.control.LockControlCommand.acceptVisitor(LockControlCommand.java:117)
	at org.infinispan.interceptors.DDAsyncInterceptor.visitCommand(DDAsyncInterceptor.java:50)
	at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:248)
	at org.infinispan.cache.impl.CacheImpl.lock(CacheImpl.java:1074)
	at org.infinispan.cache.impl.CacheImpl.lock(CacheImpl.java:1054)
	at org.infinispan.cache.impl.AbstractDelegatingAdvancedCache.lock(AbstractDelegatingAdvancedCache.java:286)
	at org.infinispan.cache.impl.EncoderCache.lock(EncoderCache.java:318)
	at org.infinispan.cache.impl.AbstractDelegatingAdvancedCache.lock(AbstractDelegatingAdvancedCache.java:286)
	at org.keycloak.models.cache.infinispan.CacheManager.addRevisioned(CacheManager.java:147)
	at org.keycloak.models.cache.infinispan.CacheManager.addRevisioned(CacheManager.java:133)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRoleById(RealmCacheSession.java:793)
	at org.keycloak.models.cache.infinispan.RealmAdapter.getRoleById(RealmAdapter.java:703)
	at org.keycloak.models.jpa.UserAdapter.getRoleMappings(UserAdapter.java:489)
	at org.keycloak.models.jpa.UserAdapter.getClientRoleMappings(UserAdapter.java:512)
	at org.keycloak.models.cache.infinispan.UserAdapter.getClientRoleMappings(UserAdapter.java:295)
	at org.keycloak.models.utils.ModelToRepresentation.toRepresentation(ModelToRepresentation.java:275)
	at org.keycloak.services.resources.admin.UserResource.getUser(UserResource.java:294)
	at sun.reflect.GeneratedMethodAccessor506.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:535)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:424)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:385)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:387)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
```
### Version

11.0.0-SNAPSHOT

### Expected behavior

The cluster deployment reports an error after running for a while.

### Actual behavior

nothing

### How to Reproduce?

nothing

**Comment by sschu** [comment]
Please update to the latest version to see if the issue persists. If yes, please provide steps to reproduce.

**Comment by mhajas** [comment]
From the provided description we are not able to effectively triage this. Therefore, I am closing this. Please comment or reopen if the issue still persists with the newest version and you are able to provide steps to reproduce.
