### ISSUE TITLE
Operator fails with unexpected CR content

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#15441]
### Area

operator

### Describe the bug

I do an upgrade from 18 to 20. This includes a breaking change in the CRDs, without a proper version upgrade of the CRDs!

Anyway, you can apply the new CRDs, and then the new operator starts up, and fails with an exception.

<details>

```
__ ____ __ _____ ___ __ ____ ______
--/ __ \/ / / / _ | / _ \/ //_/ / / / __/
-/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-11-10 09:58:10,940 WARN [io.qua.config] (main) Unrecognized configuration key "quarkus.operator-sdk.generate-csv" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-11-10 09:58:12,036 INFO [io.qua.ope.run.OperatorProducer] (main) Quarkus Java Operator SDK extension 4.0.4 (commit: d1a3d1e on branch: d1a3d1ef9b22414b740e9f4c0d74d62a673031e3) built on Fri Oct 21 09:02:30 GMT 2022
2022-11-10 09:58:12,079 INFO [io.jav.ope.Operator] (main) Registered reconciler: 'keycloakrealmimportcontroller' for resource: 'class org.keycloak.operator.crds.v2alpha1.realmimport.KeycloakRealmImport' for namespace(s): [drogue-dev]
2022-11-10 09:58:12,083 INFO [io.jav.ope.Operator] (main) Registered reconciler: 'keycloakcontroller' for resource: 'class org.keycloak.operator.crds.v2alpha1.deployment.Keycloak' for namespace(s): [drogue-dev]
2022-11-10 09:58:12,083 INFO [io.qua.ope.run.AppEventListener] (main) Starting operator.
2022-11-10 09:58:12,083 INFO [io.jav.ope.Operator] (main) Operator SDK 3.2.4 (commit: dfae8d5) built on Fri Oct 21 08:03:55 GMT 2022 starting...
2022-11-10 09:58:12,084 INFO [io.jav.ope.Operator] (main) Client version: 5.12.4
2022-11-10 09:58:12,086 INFO [io.jav.ope.pro.Controller] (main) Starting 'keycloakrealmimportcontroller' controller for reconciler: org.keycloak.operator.controllers.KeycloakRealmImportController_ClientProxy, resource: org.keycloak.operator.crds.v2alpha1.realmimport.KeycloakRealmImport
2022-11-10 09:58:12,104 WARN [io.fab.kub.cli.int.VersionUsageUtils] (main) The client is using resource type 'keycloakrealmimports' with unstable version 'v2alpha1'
2022-11-10 09:58:12,612 INFO [io.jav.ope.pro.Controller] (main) 'keycloakrealmimportcontroller' controller started, pending event sources initialization
2022-11-10 09:58:12,612 INFO [io.jav.ope.pro.Controller] (main) Starting 'keycloakcontroller' controller for reconciler: org.keycloak.operator.controllers.KeycloakController_ClientProxy, resource: org.keycloak.operator.crds.v2alpha1.deployment.Keycloak
2022-11-10 09:58:12,618 WARN [io.fab.kub.cli.int.VersionUsageUtils] (main) The client is using resource type 'keycloaks' with unstable version 'v2alpha1'
2022-11-10 09:58:12,651 ERROR [io.jav.ope.pro.eve.sou.inf.InformerWrapper] (main) Couldn't start informer for keycloaks.k8s.keycloak.org/v2alpha1 resources: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:229)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:331)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:300)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:560)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:521)
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:505)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:133)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:415)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:83)
at io.fabric8.kubernetes.client.informers.cache.Reflector.listSyncAndWatch(Reflector.java:96)
at io.fabric8.kubernetes.client.informers.cache.Reflector.start(Reflector.java:75)
at io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer.run(DefaultSharedIndexInformer.java:152)
at io.javaoperatorsdk.operator.processing.event.source.informer.InformerWrapper.start(InformerWrapper.java:40)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3603)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
```

<summary>Console log</summary>

</details>

### Version

20.0.1

### Expected behavior

I would expect the operator to ignore "invalid" CRs.

### Actual behavior

The operator crashes.

### How to Reproduce?

Perform an upgrade from 18 to 20. Or force in some "invalid" CR content.

**Comment by gedpal** [comment]
Hello, 
I also experience this doing fresh install of the Keycloak Operator 20.0.1 provided by Red Hat on OKD (4.11.0-0.okd-2022-11-19-050030)

**Comment by andre-nascimento-rh** [comment]
Hello, @ctron and @gedpal ,


Until version 19, the Keycloak Operator was in the "preview feature" stage. As disclosed in the release announcement for version 20 (https://www.keycloak.org/2022/11/keycloak-2000-released.html), the new Keycloak Operator for the Quarkus-based distribution is no longer a "preview" feature and some new features and improvements have been implemented, so some of which have resulted in breaking changes.

We're closing this issue, but if you have anything else to add, feel free to reopen it.

Thank you in advance.
