### ISSUE TITLE
make nginx certificate-lookup thread safe

### ISSUE THREAD

**Issue by Bukarim** [keycloak/keycloak#15493]
### Area

authentication

### Describe the bug

The keycloak throws a ConcurrentModificationException when many users try to get an access token at the same time (X.509 authentication)

### Version

9.0.3/16.1.1/19.0.3

### Expected behavior

many users can get an access token at the same time (X.509 authentication)

### Actual behavior

many users can't get an access token at the same time (X.509 authentication)
> ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-574) Uncaught server error: java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode (HashMap.java:1493)
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
at org.bouncycastle//org.bouncycastle.jce.provider. CertStoreCollectionSpi.engineGetCertificates (Unknown Source)
at java.base/java.security.cert.CertStore.getCertificates (CertStore.java:152)
at org.bouncycastle//org.bouncycastle.jcajce.PKIXCertStoreSelector.getCertificates (Unknown Source)
at org.bouncycastle//org.bouncycastle.jce.provider.CertPathValidatorUtilities.findCertificates (Unknown Source)
at org.bouncycastle//org.bouncycastle.jce.provider.CertPathValidatorUtilities.findIssuerCerts (Unknown Source)
at org.bouncycastle//org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi.build(Unknown Source)
at org.bouncycastle//org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi.engineBuild(Unknown Source)
at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
at org.keycloak.keycloak-services@19.0.3//org.keycloak.services.x509. NginxProxySslClientCertificateLookup.buildChain >>(NginxProxySslClientCertificateLookup.java:193)

### How to Reproduce?

 ```
/* load cert */
  private def getKeyStore(jksFile : File): KeyManagerFactory = {
    val clientKeystore: KeyStore = KeyStore.getInstance("JKS")
    val clientFis: FileInputStream = new FileInputStream(jksFile)
    clientKeystore.load(clientFis, PHRASE.toCharArray)
    clientFis.close()

    val kmf: KeyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm)
    kmf.init(clientKeystore, PHRASE.toCharArray)
    kmf
  }
/* setup request */
exec(http("getAccessToken")
      .post("/auth/realms/LAB/protocol/openid-connect/token")
      .header("content-type", "application/x-www-form-urlencoded")
      .formParam("client_id", "xxxxxxxxx")
      .formParam("client_secret", "xxxxxxxxxxx")
      .formParam("username", "xxxxxxxxx")
      .formParam("grant_type", "password")
      .check(jmesPath("access_token").saveAs("accessToken"))

/* setup simulation */
  setUp(logonScenario.inject(rampUsers(3) during (1 seconds)).protocols(httpProtocolLab)
  ).maxDuration(1 minutes)
```

**Comment by mposolda** [comment]
Thanks for the report. I am adding label "Help wanted" as Keycloak team won't have time to look at this in the near future. It would need to be community contribution to improve this. See "Contributors" section under https://www.keycloak.org/community for more details.
