### ISSUE TITLE
Failed to run scheduled task ClearExpiredAdminEvents Oracle

### ISSUE THREAD

**Issue by slominskir** [keycloak/keycloak#15528]
### Area

storage

### Describe the bug

A ScheduledTaskRunner task named ClearExpiredAdminEvents periodically runs and fails when Keycloak is configured using the Oracle database.  This is similar to the PostgreSQL issue https://github.com/keycloak/keycloak/issues/14294.

### Version

20.0.1

### Expected behavior

The ScheduledTaskRunner task ClearExpiredAdminEvents should not fail and fill the log with exceptions.

### Actual behavior

Here is the stacktrace log output:

```
2022-11-16 13:36:53,518 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 932, SQLState: 42000
2022-11-16 13:36:53,519 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) ORA-00932: inconsistent datatypes: expected - got NCLOB

2022-11-16 13:36:53,527 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredAdminEvents: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
        at org.hibernate.loader.Loader.scroll(Loader.java:2945)
        at org.hibernate.loader.hql.QueryLoader.scroll(QueryLoader.java:610)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.scroll(QueryTranslatorImpl.java:452)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performScroll(HQLQueryPlan.java:353)
        at org.hibernate.internal.SessionImpl.scroll(SessionImpl.java:1601)
        at org.hibernate.query.internal.AbstractProducedQuery.doScroll(AbstractProducedQuery.java:1588)
        at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1574)
        at org.hibernate.query.internal.AbstractProducedQuery.stream(AbstractProducedQuery.java:1598)
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.stream(CriteriaQueryTypeQueryAdapter.java:91)
        at org.hibernate.query.Query.getResultStream(Query.java:1140)
        at org.keycloak.events.jpa.JpaEventStoreProvider.clearExpiredAdminEvents(JpaEventStoreProvider.java:292)
        at org.keycloak.events.jpa.JpaEventStoreProviderFactory.invalidate(JpaEventStoreProviderFactory.java:69)
        at org.keycloak.services.DefaultKeycloakSessionFactory.lambda$invalidate$0(DefaultKeycloakSessionFactory.java:368)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.keycloak.services.DefaultKeycloakSessionFactory.invalidate(DefaultKeycloakSessionFactory.java:368)
        at org.keycloak.services.DefaultKeycloakSession.invalidate(DefaultKeycloakSession.java:123)
        at org.keycloak.services.scheduled.ClearExpiredAdminEvents.run(ClearExpiredAdminEvents.java:35)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:58)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:54)
        at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
        at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:54)
        at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00932: inconsistent datatypes: expected - got NCLOB

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:163)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1010)
        at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1271)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1149)
        at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1661)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1470)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3761)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3936)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1102)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:78)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
        ... 41 more
Caused by: Error : 932, Position : 178, Sql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=:1  and realmattri0_.VALUE<>:2 , OriginalSql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=? and realmattri0_.VALUE<>?, Error Msg = ORA-00932: inconsistent datatypes: expected - got NCLOB
```

### How to Reproduce?

I have created a Docker Compose reproducer GitHub project.

1. Grab project
```
git clone https://github.com/slominskir/keycloak_oracle
cd keycloak_oracle
```

2. Launch Compose
```
docker compose up
```

3. Login to admin console

http://localhost:8080

Login with username `admin` and password `admin`

4. Enable Admin Scheduled Events

Navigate admin console to `Realm Settings` > `Events` > `Admin event settings`

Click on the `Save events` toggle to enable it.

<img width="960" alt="Screenshot" src="https://user-images.githubusercontent.com/2642119/202205409-0ae79739-9757-4c41-ac31-0ba21901cc24.png">

**Note**: I've actually seen the scheduled task run and cause the exception without enabling Admin events.   This may be only with the ClusterAwareScheduledTaskRunner, see: [keycloak_cluster example](https://github.com/slominskir/keycloak_cluster)

4. Wait for scheduled task to run and observe logs

**Comment by slominskir** [comment]
More debug info:

Code in question: https://github.com/keycloak/keycloak/blob/6f7c62fc73a19d3e6dbc289da82eee36742ac5c6/model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java#L291-L292

This JPA criteria query results in essentially the following SQL:

```
select name, value from realm_attribute where name = 'adminEventsExpiration' and value <> '0';
```

You can execute the query directly in the reproducer compose project mentioned above by executing:

```
docker exec -it -u oracle oracle bash

sqlplus keycloak_owner@XEPDB1
```
Use password: `password`.

Now copy and paste query above to see error:

```
ORA-00932: inconsistent datatypes: expected - got NCLOB
```

You can *fix* the query by adding a to_char like so:

```
select name, value from realm_attribute where name = 'adminEventsExpiration' and to_char(value) <> '0';
```

**Comment by slominskir** [comment]
Looks like the [commit/fix](https://github.com/keycloak/keycloak/commit/cc8567e9f445e7d4ecc054bc979b51cc07a4513c) for https://github.com/keycloak/keycloak/issues/14294 was overwritten by the [commit/fix](https://github.com/keycloak/keycloak/commit/97c4495c4f1bd38a6ce04218de64b8fe8ed069cb#diff-1c6e7b13598b43d9773f9dd49148850934138f504dc8d8a95eec6b7b5eae3f66) for https://github.com/keycloak/keycloak/issues/12607

See: [JpaEventStoreProvider.java commit history](https://github.com/keycloak/keycloak/commits/791c457c32da32884ce723ed36a980f67bdfd4c1/model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java)

It's possible the Postgres fix of casting the `value` field to a long may have worked on Oracle too, though the inline comments of the latest commit suggest H2 DB wasn't happy with it.  At this point it appears BOTH Oracle and Postrgres have this similar issue.   Perhaps moving the `if not equal zero` to application code would be a good generic fix since it seems Hibernate can seamlessly query and load Postgres `text` and Oracle `nclob` columns only if you don't try to do comparisons on the field!

**Comment by ahus1** [comment]
Hi @slominskir - thanks for looking into this. I tested the SQL with an PostgreSQL 13.2 database and didn't see an error with the SQL `select name, value from realm_attribute where name = 'adminEventsExpiration' and value <> '0'` - which PostgreSQL version did you run?

Instead of letting Hibernate and Java do the work, I'd like to evaluate something different: Our setup allows named queries to be overwritten in a database specific way. I'll give that a try and will report back on this.

**Comment by ahus1** [comment]
Update: I now learned that our setup allows overrides only for those queries that don't return values, so it doesn't apply here.

**Comment by ahus1** [comment]
For those watching this issue, be aware that there might be more CLOB issues lingering around. Please follow #15639 for updates.

**Comment by ahus1** [comment]
Backport for KC20 created: #15650

**Comment by ahus1** [comment]
@vanitamk - yes, it was solved for 20.0.2 and also for 21.x and the following versions.

**Comment by vanitamk** [comment]
i have installed keycloak 20.0.1 and faced this issue, can i upgrade or have to install keycloak new version

**Comment by vanitamk** [comment]
when i faced NCLOB issue i try to change it to char(255) or VARCHAR2(4000), getting below issue
   [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: For input string: "900                                                                                                                                                                                                                                                            "

**Comment by ahus1** [comment]
@vanitamk - please upgrade Keycloak. Once you start a new version of Keycloak against an existing database, it will update the DB schema automatically and keep the data. Note that this works for all external databases listed in https://www.keycloak.org/server/db

**Comment by vanitamk** [comment]
Okay Thank you @ahus1, we are using oracle 19.3 version as external database. we try to install new version of keycloak, hope it will handle NCLOB issue automatically.
