### ISSUE TITLE
client id max length throws 401 error unauthorised client

### ISSUE THREAD

**Issue by yuyujiejie** [keycloak/keycloak#15617]
### Area

token-exchange

### Describe the bug

io.quarkus.keycloak policy enforcer cannot handle client-id more than 12 characters.

### Version

20.0.1

### Expected behavior

Have set up a confidential client in keycloak with the name "native-bendee" (13 characters) with authorization scopes, resources, policies and permissions set up according to keycloak documentation.
After enabling the `quarkus.keycloak.policy-enforcer.enable` to true, users with permitted roles should be able to access protected APIs with response code 200. 

### Actual behavior

Have set up a confidential client in keycloak with the name "native-bendee" (13 characters) with authorization scopes, resources, policies and permissions set up according to keycloak documentation.

After enabling the `quarkus.keycloak.policy-enforcer.enable` to true, users with permitted roles are calling protected APIs with response code 403 forbidden with the backend service throwing the 401 error. (stack trace below)

Stack trace below.
2022-11-22 17:55:04,731 ERROR [org.key.ada.aut.PolicyEnforcer] (executor-thread-2) Could not lazy load resource with path [/events] from server: java.lang.RuntimeException: Could not find resource
	at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:91)
	at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:232)
	at org.keycloak.authorization.client.resource.ProtectedResource.findByMatchingUri(ProtectedResource.java:291)
	at org.keycloak.adapters.authorization.PolicyEnforcer$PathConfigMatcher.matches(PolicyEnforcer.java:272)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.getPathConfig(AbstractPolicyEnforcer.java:351)
	at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:72)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:64)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer_Subclass.apply$$superforward1(Unknown Source)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer_Subclass.apply(Unknown Source)
	at io.quarkus.keycloak.pep.runtime.KeycloakPolicyEnforcerAuthorizer.apply(KeycloakPolicyEnforcerAuthorizer.java:28)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1$1.run(HttpAuthorizer.java:74)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 401 / Unauthorized / Response from server: {"error":"unauthorized_client","error_description":"Invalid client or Invalid client credentials"}
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:95)
	at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
	at org.keycloak.authorization.client.util.TokenCallable.clientCredentialsGrant(TokenCallable.java:123)
	at org.keycloak.authorization.client.util.TokenCallable.obtainTokens(TokenCallable.java:154)
	at org.keycloak.authorization.client.util.TokenCallable.call(TokenCallable.java:64)
	at org.keycloak.authorization.client.resource.ProtectedResource.createFindRequest(ProtectedResource.java:296)
	at org.keycloak.authorization.client.resource.ProtectedResource.access$300(ProtectedResource.java:38)
	at org.keycloak.authorization.client.resource.ProtectedResource$5.call(ProtectedResource.java:225)
	at org.keycloak.authorization.client.resource.ProtectedResource$5.call(ProtectedResource.java:222)
	at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:230)
	... 24 more

### How to Reproduce?

1) set up quarkus backend with below application.properties and keycloak confidential client and authz with below configs.
2) create account with "user" role
3) get access token by calling token endpoint
4) call protected endpoint with given access token
5) should get 401 invalid client on quarkus backend side

application.properties
quarkus.security.auth.enabled-in-dev-mode=true
quarkus.oidc.auth-server-url=${KC_HOSTNAME}
quarkus.oidc.client-id=dbatch-gui-backend-native
quarkus.oidc.credentials.secret=${KC_CLIENT_SECRET}
quarkus.oidc.tls.verification=none
quarkus.oidc.authentication.user-info-required=true
quarkus.oidc.token.issuer=any
quarkus.oidc.client-id=native-bendee
quarkus.oidc.credentials.secret=o3m6BCkmgVo9ktuFsHm0xmKrez6m6hoc
quarkus.keycloak.policy-enforcer.enable=true

confidential client configs
{
  "clientId": "native-bendee",
  "name": "dbatch backend",
  "description": "",
  "rootUrl": "http://localhost:8090",
  "adminUrl": "",
  "baseUrl": "",
  "surrogateAuthRequired": false,
  "enabled": true,
  "alwaysDisplayInConsole": false,
  "clientAuthenticatorType": "client-secret",
  "secret": "o3m6BCkmgVo9ktuFsHm0xmKrez6m6hoc",
  "redirectUris": [
    "/*"
  ],
  "webOrigins": [
    "*"
  ],
  "notBefore": 0,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": true,
  "directAccessGrantsEnabled": true,
  "serviceAccountsEnabled": true,
  "authorizationServicesEnabled": true,
  "publicClient": false,
  "frontchannelLogout": true,
  "protocol": "openid-connect",
  "attributes": {
    "saml.force.post.binding": "false",
    "saml.multivalued.roles": "false",
    "frontchannel.logout.session.required": "false",
    "post.logout.redirect.uris": "+",
    "oauth2.device.authorization.grant.enabled": "false",
    "backchannel.logout.revoke.offline.tokens": "false",
    "saml.server.signature.keyinfo.ext": "false",
    "use.refresh.tokens": "true",
    "oidc.ciba.grant.enabled": "false",
    "backchannel.logout.session.required": "true",
    "client_credentials.use_refresh_token": "false",
    "require.pushed.authorization.requests": "false",
    "saml.client.signature": "false",
    "saml.allow.ecp.flow": "false",
    "id.token.as.detached.signature": "false",
    "saml.assertion.signature": "false",
    "client.secret.creation.time": "1664936701",
    "saml.encrypt": "false",
    "saml.server.signature": "false",
    "exclude.session.state.from.auth.response": "false",
    "tls-client-certificate-bound-access-tokens": "false",
    "saml.artifact.binding": "false",
    "saml_force_name_id_format": "false",
    "acr.loa.map": "{}",
    "tls.client.certificate.bound.access.tokens": "false",
    "saml.authnstatement": "false",
    "display.on.consent.screen": "false",
    "token.response.type.bearer.lower-case": "false",
    "saml.onetimeuse.condition": "false",
    "request.uris": "",
    "consent.screen.text": "",
    "frontchannel.logout.url": "",
    "backchannel.logout.url": "",
    "login_theme": ""
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "protocolMappers": [
    {
      "name": "Client IP Address",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "clientAddress",
        "userinfo.token.claim": "true",
        "id.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "clientAddress",
        "jsonType.label": "String"
      }
    },
    {
      "name": "Client ID",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "clientId",
        "userinfo.token.claim": "true",
        "id.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "clientId",
        "jsonType.label": "String"
      }
    },
    {
      "name": "Client Host",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "clientHost",
        "userinfo.token.claim": "true",
        "id.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "clientHost",
        "jsonType.label": "String"
      }
    }
  ],
  "defaultClientScopes": [
    "web-origins",
    "acr",
    "roles",
    "profile",
    "email"
  ],
  "optionalClientScopes": [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt"
  ],
  "access": {
    "view": true,
    "configure": true,
    "manage": true
  }
}

authorization details export
{
  "allowRemoteResourceManagement": true,
  "policyEnforcementMode": "ENFORCING",
  "resources": [
    {
      "name": "Dbatch Environments",
      "ownerManagedAccess": false,
      "attributes": {},
      "_id": "16ac19d0-01be-4f63-8ccb-5d1a093c341d",
      "uris": [
        "/*"
      ],
      "scopes": [
        {
          "name": "view"
        },
        {
          "name": "update"
        },
        {
          "name": "delete"
        },
        {
          "name": "create"
        }
      ],
      "icon_uri": ""
    }
  ],
  "policies": [
    {
      "id": "fa6c99be-cc3f-4843-a8ac-57b3b69e1bdc",
      "name": "user policy",
      "description": "users can access",
      "type": "role",
      "logic": "POSITIVE",
      "decisionStrategy": "UNANIMOUS",
      "config": {
        "roles": "[{\"id\":\"user\",\"required\":false}]"
      }
    },
    {
      "id": "9ec39ce0-14f0-4694-9c55-4a733752eeba",
      "name": "admin policy",
      "description": "",
      "type": "role",
      "logic": "POSITIVE",
      "decisionStrategy": "UNANIMOUS",
      "config": {
        "roles": "[{\"id\":\"admin\",\"required\":false}]"
      }
    },
    {
      "id": "29c3b420-6fdc-4e30-b503-28e1498bbf4f",
      "name": "view",
      "description": "",
      "type": "scope",
      "logic": "POSITIVE",
      "decisionStrategy": "AFFIRMATIVE",
      "config": {
        "scopes": "[\"view\"]",
        "applyPolicies": "[\"user policy\",\"admin policy\"]"
      }
    },
    {
      "id": "ae131341-6ae9-4674-a0ac-f2bdafb42d2e",
      "name": "update",
      "description": "",
      "type": "scope",
      "logic": "POSITIVE",
      "decisionStrategy": "AFFIRMATIVE",
      "config": {
        "scopes": "[\"update\"]",
        "applyPolicies": "[\"user policy\",\"admin policy\"]"
      }
    },
    {
      "id": "6971731c-89e0-4051-86ba-951da5876748",
      "name": "create",
      "description": "",
      "type": "scope",
      "logic": "POSITIVE",
      "decisionStrategy": "AFFIRMATIVE",
      "config": {
        "scopes": "[\"create\"]",
        "applyPolicies": "[\"user policy\",\"admin policy\"]"
      }
    },
    {
      "id": "181aadaf-6fb9-4cea-a812-adfeeca102a1",
      "name": "delete",
      "description": "",
      "type": "scope",
      "logic": "POSITIVE",
      "decisionStrategy": "AFFIRMATIVE",
      "config": {
        "scopes": "[\"delete\"]",
        "applyPolicies": "[\"user policy\",\"admin policy\"]"
      }
    }
  ],
  "scopes": [
    {
      "id": "cd31077a-b885-40d4-9d05-843e02fb7fd7",
      "name": "view",
      "iconUri": ""
    },
    {
      "id": "23a0eae9-f3f2-4d83-890a-d86a6b393593",
      "name": "update",
      "iconUri": ""
    },
    {
      "id": "e1120617-dafe-45c8-8bd2-5dc51b4a222d",
      "name": "delete",
      "iconUri": ""
    },
    {
      "id": "ac1e1e1a-ba78-4fa4-950f-89810d688016",
      "name": "create",
      "iconUri": ""
    }
  ],
  "decisionStrategy": "AFFIRMATIVE"
}

### Anything else?

Policy enforcement works with client-id 12 characters or less.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by pedroigor** [comment]
@yuyujiejie AFAIK, the client id can have up tp 255 chars. Please, let me know if the issue is still happening with latest releases.
