### ISSUE TITLE
Password change sometimes triggers error

### ISSUE THREAD

**Issue by svenseeberg** [keycloak/keycloak#15656]
### Area

user-profile

### Describe the bug

When a user goes to Account Security > Sign in > Password > Update and enters a new password (+ confirmation) in about 20% of the cases an unhandled exception occurs. Interestingly, the password is changed. The error seems to have no relevance for the password update process. 

However, the user does not get an e-mail notification about the changed password. The fourth line of the trace may indicate that the error occured while sending the mail? The local Postfix does not get any incoming connection from the Keycloak application when the error occurs.

### Version

20.0.{1,2,3}

### Expected behavior

The error should be handled more gracefully, or the stack trace should be more helpful.

### Actual behavior

The following stack traces show up:
```
2022-11-23 17:21:30,084 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1052) Uncaught server error: java.lang.IllegalStateException: Cannot access delegate without a transaction
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:151)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:415)
    at org.keycloak.events.email.EmailEventListenerProvider.sendEmail(EmailEventListenerProvider.java:67)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
    at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
    at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
    at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:64)
    at org.keycloak.quarkus.runtime.integration.jaxrs.TransactionalResponseFilter.filter(TransactionalResponseFilter.java:47)
    at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:367)
    at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
    at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
    at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
    at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)

2022-11-23 17:21:30,084 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1052) Failed to create error page: java.lang.IllegalStateException: Cannot access delegate without a transaction
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:151)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:454)
    at org.keycloak.services.managers.RealmManager.getRealmByName(RealmManager.java:97)
    at org.keycloak.services.error.KeycloakErrorHandler.resolveRealm(KeycloakErrorHandler.java:143)
    at org.keycloak.services.error.KeycloakErrorHandler.getResponse(KeycloakErrorHandler.java:84)
    at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:56)
    at org.jboss.resteasy.core.ExceptionHandler.executeExceptionMapper(ExceptionHandler.java:136)
    at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:362)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:614)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
    at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)

2022-11-23 17:21:30,084 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (executor-thread-1052) MediaType not set on path /realms/myrealm/login-actions/required-action, with response status 500
2022-11-23 17:21:30,085 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1052) HTTP Request to /realms/myrealm/login-actions/required-action?session_code=MYSESSIONCODE&execution=UPDATE_PASSWORD&client_id=account-console&tab_id=tKJcyuMiHms failed, error id: 6e9198d6-6017-4d7d-909b-0be02c9858f4-81: org.jboss.resteasy.spi.UnhandledException: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
    at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:230)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:614)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
    at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
    at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
    at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
    at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
    at org.keycloak.headers.DefaultSecurityHeadersProvider.addHeaders(DefaultSecurityHeadersProvider.java:75)
    at org.keycloak.services.filters.KeycloakSecurityHeadersFilter.filter(KeycloakSecurityHeadersFilter.java:42)
    at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:367)
    at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
    at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
    at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
    at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:226)
    ... 32 more
```

### How to Reproduce?

Usually it is sufficient to repeatedly change the password until the error occurs.

### Anything else?
This does not happen in the admin back end.

We're running a custom SMS 2FA authentication provider (https://github.com/netzbegruenung/keycloak-2fa-sms-authenticator) and a custom theme. Not sure if this is relevant as it works 80% of the time. I suspect that this is some sort of race condition. The passwords are stored in a remote OpenLDAP database.

**Comment by svenseeberg** [comment]
It seems this is triggered by this part of the SMS 2FA plugin: https://github.com/netzbegruenung/keycloak-2fa-sms-authenticator/blob/main/src/main/java/netzbegruenung/keycloak/authenticator/PhoneNumberRequiredAction.java#L64-L114

However, I cannot yet tell whose fault it is. I will investigate further.

**Comment by pedroigor** [comment]
Changing to `core` as user profile does not handle password management.

**Comment by svenseeberg** [comment]
This seems to be related/similar: https://issues.redhat.com/browse/KEYCLOAK-3122

**Comment by svenseeberg** [comment]
I think this is caused by some sort of race condition in the Keycloak core, and not directly caused by the SMS 2FA plugin. This problem occurs while notifying the user about an updated password or user profile. The notification works most of the time and fails only in some cases. That means in most cases the transaction can still be accessed.

AFAICT this should not happen on a conceptual level.

**Comment by pedroigor** [comment]
@svenseeberg Indeed, it is weird behavior. I'm looking at it.

**Comment by pedroigor** [comment]
The email is sent during the commit phase and sometimes the transaction is closed before doing it.

During the commit phase, the [`EmailEventListenerProvider`](https://github.com/keycloak/keycloak/blob/a60cb65252aec21ea1899a73d5fc136ae5058383/services/src/main/java/org/keycloak/events/email/EmailEventListenerProvider.java#L54) enlist a "transaction" to run  after completion and at that time the JTA transaction is closed already.

Could you link the code to the extension you are using?

**Comment by pedroigor** [comment]
Also, can you confirm the realm is not in the cache when it fails?

**Comment by svenseeberg** [comment]
> Could you link the code to the extension you are using?

We have a 2FA SMS. The code is available on https://github.com/netzbegruenung/keycloak-2fa-sms-authenticator 

Initially I thought that this plugin may trigger the problem. However, maybe it is triggered by our Realm configuration that uses an OpenLDAP as a user directory. It seems more likely that the speed of the LDAP directory could be the cause of this race(?) condition.

I'll try to provide the answers for your questions. As we're no Keycloak experts, it may take some time. We're also trying to create a PR with a work around (catch the error and write it to the log file instead of showing the user the error message).

**Comment by pedroigor** [comment]
If you can force clearing the realm cache before sending the e-mail, then we might confirm if it is related to what I'm suspecting.

**Comment by svenseeberg** [comment]
> If you can force clearing the realm cache before sending the e-mail, then we might confirm if it is related to what I'm suspecting.

I'm not 100% sure if I fully understand the approach. With clearing the cache you mean the following command?
```
kcadm.sh create clear-realm-cache -r myrealm -s realm=myrealm
```

To validate, I would have to do this continuously while trying to update the password. So what I would do is the following:
1. Log in
2. Flush cache
3. update password
4. Check if error appears. If not, go back to step 2

Do you have any expectation how old the cache is allowed to be? I expect there will be at least 10 to 20 seconds between steps 2 and 3.

**Comment by hmlnarik** [comment]
Seems like that the DB transaction is closed before the email is sent, and the realm is only in cache (where it is stored partially). Then sending email triggered by commit (after DB commit) hits a field which is not cached, and the retrieval via the delegate is initiated which fails without active TX.
`EmailEventListenerProvider` in its current shape is flawed - it actually enlists the email transaction after completion (line 54), i.e. after commit phase, ie after all transactions are closed. But in the body of `sendEmail` it assumes the transaction is available instead of executing the method body in a fresh session (via `runJobInTransaction`) which would be a correct fix (even better if it was executed asynchronously).

**Comment by pedroigor** [comment]
@hmlnarik Thanks, Hynek. I appreciate the confirmation that sending an e-mail within a new transaction is more appropriate. I've the changes ready and will send a PR.
