### ISSUE TITLE
ERROR: Failed to start server in (production) mode after update from 19.0.3 quarkus to 20.0.1

### ISSUE THREAD

**Issue by RiskManagementGroup** [keycloak/keycloak#15738]
### Area

core

### Describe the bug

We are using the docker images from quay.io in kubernetes, and after updating from quay.io/keycloak/keycloak:19.0.3 to quay.io/keycloak/keycloak:20.0.1, keycloak fails to start with the error message:

```
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

Setting the log-level to debug I was able to find the message:

```
DEBUG [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (main) Exception clearing maxRows/queryTimeout [Statement is closed]
WARN [io.agroal.pool] (main) Datasource '': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
```

We are using PostgreSQL server.

I have also tried to run with migration-strategy set to manual, but that gives the same error.

### Version

20.0.1

### Expected behavior

upgrades from 19.0.3 to 20.0.1 without error

### Actual behavior

fails to start after upgrade to 20.0.1

### How to Reproduce?

I have not been able to reliably reproduce. I have tried setting up a minimal example for replication where I just install 19.0.3 on the kubernetes cluster in docker desktop and then upgrade to 20.0.1, but that worked ok.

### Anything else?

comparisons with the debug log from the simple scenario that works to the environment with the error, shows that the `JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)` warning is not present, but 3 other WARN messages are, so it could indicate that the error is related to this message.

**Comment by lexcao** [comment]
Are there any detailed logs that could help me debug?
```
Exception clearing maxRows/queryTimeout
```
Does not help enough.

**Comment by RiskManagementGroup** [comment]
@lexcao here are the logs from the kubernetes pod. I set the log-level to DEBUG:
[logs.txt](https://github.com/keycloak/keycloak/files/10120839/logs.txt)

**Comment by lexcao** [comment]
Hi, I have no clue on the logs.
Could you please share the start scripts you are using?

**Comment by mvicomoya** [comment]
I'm hitting this issue as well. This is what I get when I pass in the `--verbose` option:
```
keycloak  | 2022-12-09 00:16:30,374 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak  | 2022-12-09 00:16:30,374 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.NullPointerException
keycloak  | 	at org.keycloak.migration.migrators.MigrateTo20_0_0.addViewGroupsRole(MigrateTo20_0_0.java:33)
keycloak  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
keycloak  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
keycloak  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
keycloak  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
keycloak  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
keycloak  | 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
keycloak  | 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
keycloak  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
keycloak  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
keycloak  | 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
keycloak  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
keycloak  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak  | 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
keycloak  | 	at org.hibernate.query.spi.StreamDecorator.forEach(StreamDecorator.java:153)
keycloak  | 	at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
keycloak  | 	at org.keycloak.migration.migrators.MigrateTo20_0_0.migrate(MigrateTo20_0_0.java:19)
keycloak  | 	at org.keycloak.storage.datastore.LegacyMigrationManager.migrate(LegacyMigrationManager.java:133)
keycloak  | 	at org.keycloak.migration.MigrationModelManager.migrate(MigrationModelManager.java:33)
keycloak  | 	at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.migrateModel(LegacyJpaConnectionProviderFactory.java:219)
keycloak  | 	at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.initSchema(LegacyJpaConnectionProviderFactory.java:213)
keycloak  | 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:260)
keycloak  | 	at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.postInit(LegacyJpaConnectionProviderFactory.java:138)
keycloak  | 	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:104)
keycloak  | 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:42)
keycloak  | 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
keycloak  | 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
keycloak  | 	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
keycloak  | 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
keycloak  | 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
keycloak  | 	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
keycloak  | 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
keycloak  | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
keycloak  | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
keycloak  | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
keycloak  | 	at io.quarkus.runtime.Application.start(Application.java:101)
keycloak  | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
keycloak  | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
keycloak  | 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
keycloak  | 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
keycloak  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
keycloak  | 	at picocli.CommandLine.access$1300(CommandLine.java:145)
keycloak  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
keycloak  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
keycloak  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
keycloak  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
keycloak  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
keycloak  | 	at picocli.CommandLine.execute(CommandLine.java:2078)
keycloak  | 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
keycloak  | 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
keycloak  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
keycloak  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
keycloak  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

**Comment by lexcao** [comment]
Hi, there is a null pointer exception from the below code.

https://github.com/keycloak/keycloak/blob/e4804de9e39245ab65c2b0371ee5c42bbe682cc1/model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo20_0_0.java#L32-L33

Could you please check if the client `account-console` exists in your realm?

If you want to run the migration manual, you need to try this:
```
kc.[sh|bat] start --spi-connections-jpa-legacy-migration-strategy=manual
```
Please refer the this [upgrading doc](https://www.keycloak.org/docs/latest/upgrading/#_migrate_db)

**Comment by mvicomoya** [comment]
Thanks for the suggestion @lexcao.

My `master` realm does indeed have the `account-console` client, but my site's realm does not. It it supposed to?

I tried adding the `--spi-connections-jpa-legacy-migration-strategy=manual` to my docker `start` command options and I'm still hitting the same bug.

I don't see any logs that mention any dump for the corresponding SQL file. Without having looked at the code, I assume dumping the SQL file would happen AFTER the migration code runs, but it crashes before getting that far.

**Comment by lexcao** [comment]
> My master realm does indeed have the account-console client, but my site's realm does not. It it supposed to?

@mvicomoya 
The migration would iterator all the realms to check the `account-console` client.
Could you please try to add it back manually?

**Comment by mvicomoya** [comment]
Manually adding `account-console` client did the trick for me. Thanks for the suggestion. I was confused because it wasn't there originally (I upgraded from a legacy WildFly installation very recently).

**Comment by ajaiswal595** [comment]
> account-console

Here i found same issue

[https://github.com/keycloak/keycloak/issues/16074](https://github.com/keycloak/keycloak/issues/16074)

Why do we need to add it manually client "account-console"?
**Any document which describes the significance of "account-console".** 

As in my old version of Realm,  "account-console" client entry was not there but while migrating from 15 to 20 it is required to add entry manually either in a database or in keycloak client section which is not a smooth upgrade.

**Are we going to fix it for smooth upgrade?**

**Comment by sschu** [comment]
The account-console client was added in the migration to KC 9. You probably imported a realm configuration from a pre-9 Keycloak into a post-9 Keycloak so it is missing (or something like that).

**Comment by pedroigor** [comment]
@RiskManagementGroup @ajaiswal595 The last comment from @sschu makes a lot of sense to me and the error is clear.

As mentioned in the description, I was also not able to reproduce the error. I'm closing this one as it does not look like a bug but the database using a broken realm.
