### ISSUE TITLE
Upgrade from 16.0.0 to 20.0.1 fails: Migration throws NullPointerException

### ISSUE THREAD

**Issue by zak905** [keycloak/keycloak#15757]
### Area

dist/quarkus

### Describe the bug

I tried upgrading from Keycloak 16.0.0 to 20.0.0, but I was not able to because the migration `MigrateTo20_0_0` failed here: https://github.com/keycloak/keycloak/blob/main/model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo20_0_0.java#L33 and throws an Null pointer exception:

```
2022-11-29 20:29:08,863 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.NullPointerException
	at org.keycloak.migration.migrators.MigrateTo20_0_0.addViewGroupsRole(MigrateTo20_0_0.java:33)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.hibernate.query.spi.StreamDecorator.forEach(StreamDecorator.java:153)
	at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
	at org.keycloak.migration.migrators.MigrateTo20_0_0.migrate(MigrateTo20_0_0.java:19)
`asd	at org.keycloak.storage.datastore.LegacyMigrationManager.migrate(LegacyMigrationManager.java:133)
	at org.keycloak.migration.MigrationModelManager.migrate(MigrationModelManager.java:33)
	at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.migrateModel(LegacyJpaConnectionProviderFactory.java:219)vsdscd

```

This happens because Keycloak version 16.0.0 does not have a client named `account-console` by default. 

![auth imager200 io_auth_admin_master_console_](https://user-images.githubusercontent.com/6265563/204756504-722dc85d-6332-43ef-9ea2-238b64ecde17.png)

### Version

20.0.0

### Expected behavior

Keycloak upgrade from 16.0.0 should be smooth

### Actual behavior

upgrade fails

### How to Reproduce?

* run keycloak 16.0.0 with a database like postgres locally
* migrate to keycloak 20.0.0 

### Anything else?

I guess it's possible to work around this by creating manually a client named `account-console`, but this is just a hack. I think the case when `account-console` does not exist should be handled in the migration

**Comment by sschu** [comment]
This client was created in Keycloak 9 using a migration, see https://github.com/keycloak/keycloak/commit/3731e36ece3e7a6e7b9a4d6049bde10c0e417df0. If it does not exist in your KC16, somebody probably deleted it.

**Comment by zak905** [comment]
Thanks for the info. I double checked, and this is what actually happened: 
* The realm was imported from json using full import
* The json was from a version prior to 9 so it did not have an `account-console` client
* I  changed the `"keycloakVersion"` property manually in json to a version after 9, because I thought it should match the version of KC where the json is imported
* This caused the migration to be skipped

I guess this can be fixed using a partial realm import somehow. We can close this I guess.

**Comment by vramik** [comment]
Thanks both @zak905 and @sschu.
