### ISSUE TITLE
JPA map storage: verify if JsonbPostgreSQL95Dialect is required

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#15759]
It seems the `registerFunction` in the dialect is only needed for JPQL / HQL queries, and we only use the functions in `CriteriaBuilder.function` context. 

This issue is to verify whether the `JsonbPostgreSQL95Dialect` is needed at all.

**Comment by vramik** [comment]
note: there are following lines of code: https://github.com/keycloak/keycloak/blob/f6a2b334d1e0652dcaba76cf8fccdc464a3171cd/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java#L188-L190

**Comment by sguilhen** [comment]
It turns out the `JsonbPostgreSQL95Dialect` is needed. Without it, several tests fail with messages like this:

```
org.keycloak.models.ModelException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.keycloak.models.map.storage.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:84)
	at org.keycloak.models.map.storage.jpa.JpaMapKeycloakTransaction.read(JpaMapKeycloakTransaction.java:207)
   ...
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: -> record
  Hint: No operator matches the given name and argument type. You might need to add an explicit type cast.
  Position: 313
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	... 138 more
```
