### ISSUE TITLE
Unable to perform export when server was started with new storage

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#15782]
### Area

dist/quarkus

### Describe the bug

When keycloak is started with new storage

```bash
sh keycloak-20.0.1/bin/kc.sh start-dev --storage=jpa --db-url=$JDBC_URL --db-username=$USER --db-password=$PASS
```

there is following issue during an export:
```bash
sh keycloak-20.0.1/bin/kc.sh export --file /path/to/export1.json
2022-12-01 09:02:06,785 WARN  [org.keycloak.common.Profile] (main) Experimental feature enabled: map_storage
2022-12-01 09:02:06,799 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
2022-12-01 09:02:06,809 WARN  [org.keycloak.quarkus.runtime.configuration.mappers.StoragePropertyMappers] (main) Version seed for deployment state set with a random number. Caution: This can lead to unstable operations when serving resources from the cluster without a sticky loadbalancer or when restarting nodes. Set the '--storage-deployment-state-version-seed' option with a secret seed to ensure stable operations.
2022-12-01 09:02:07,417 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-12-01 09:02:07,862 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The server requested SCRAM-based authentication, but no password was provided.
2022-12-01 09:02:07,863 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: The server requested SCRAM-based authentication, but no password was provided.
	at org.postgresql.core.v3.ConnectionFactoryImpl.lambda$doAuthentication$4(ConnectionFactoryImpl.java:791)
	at org.postgresql.core.v3.AuthenticationPluginManager.withPassword(AuthenticationPluginManager.java:81)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:788)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:210)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-12-01 09:02:08,068 WARN  [org.keycloak.services.DefaultComponentFactoryProviderFactory] (main) No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.
2022-12-01 09:02:08,109 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The server requested SCRAM-based authentication, but no password was provided.
2022-12-01 09:02:08,110 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 08004
2022-12-01 09:02:08,110 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) The server requested SCRAM-based authentication, but no password was provided.
2022-12-01 09:02:08,152 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-12-01 09:02:08,152 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to acquire JDBC Connection
2022-12-01 09:02:08,152 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: The server requested SCRAM-based authentication, but no password was provided.
2022-12-01 09:02:08,152 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

```

It seems that export defaults to legacy store.

### Version

20.0.1

### Expected behavior

Export is performed successfully

### Actual behavior

There is an issue during an export.

### How to Reproduce?

- start keycloak with new storage
- stop keycloak
- export

**Comment by ahus1** [comment]
@vmuzikar - I stumbled across this today, and found that there is no CLI option for database related username and password for the export command. 

Instead, I needed to pass those options as environment variables: 

```
export KC_DB_PASSWORD=pass
export KC_DB_USERNAME=keycloak
```

I see that this is not in the export guide, so it would be great to allow those information to be passed on the CLI, and also update the docs. For a good UX on exports, this also relates to #15898.

**Comment by ahus1** [comment]
There is now PR #19059 which allows all runtime relevant options to be passed to the export and import and export command, and those options are shown in the `--help` and `--help-all` output. 

This issue remains open to update the docs once that PR has been merged.

**Comment by ahus1** [comment]
@mabartos - reassigning this to myself as I'm not finishing this last task of the export/import
