### ISSUE TITLE
Import of Wildfly supported Realm is failing in Keycloak 20.0.1

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#15826]
### Area

import-export

### Describe the bug

While starting the with old realm(Supported by wildfly destro 15.0.0) import option is failing for the quarkus distro 20.0.1

The command I'm providing to start is 

```sh
**./kc.sh -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=../realms-to-import -Dkeycloak.migration.strategy=IGNORE_EXISTING start --http-enabled true --https-key-store-file=./certs/keystore.ks --https-key-store-password=mypassword --db=postgres --db-url=jdbc:postgresql://localhost:5432/KCDB --db-username=postgres --db-password=password --hostname-strict=false --http-port 8443 --https-port 8080 --http-relative-path /auth**
```

```
ERROR [org.keycloak.storage.datastore.LegacyMigrationManager] (main) Failed to migrate json representation for version: 20.0.0: java.lang.NullPointerException
	at org.keycloak.migration.migrators.MigrateTo20_0_0.addViewGroupsRole(MigrateTo20_0_0.java:33)
	at org.keycloak.migration.migrators.MigrateTo20_0_0.migrateImport(MigrateTo20_0_0.java:24)
	at org.keycloak.storage.datastore.LegacyMigrationManager.migrate(LegacyMigrationManager.java:178)
	at org.keycloak.migration.MigrationModelManager.migrateImport(MigrationModelManager.java:37)
	at org.keycloak.storage.datastore.LegacyDatastoreProviderFactory.onEvent(LegacyDatastoreProviderFactory.java:94)
	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:92)
	at org.keycloak.storage.LegacyStoreMigrateRepresentationEvent.fire(LegacyStoreMigrateRepresentationEvent.java:45)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:610)
	at org.keycloak.exportimport.util.ImportUtils.importRealm(ImportUtils.java:111)
	at org.keycloak.exportimport.dir.DirImportProvider$4.runExportImportTask(DirImportProvider.java:138)
	at org.keycloak.exportimport.util.ExportImportSessionTask.run(ExportImportSessionTask.java:35)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:260)
	at org.keycloak.exportimport.dir.DirImportProvider.importRealm(DirImportProvider.java:134)
	at org.keycloak.exportimport.dir.DirImportProvider.importModel(DirImportProvider.java:76)
	at org.keycloak.exportimport.ExportImportManager.runImport(ExportImportManager.java:87)
	at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:211)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:43)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

After following this article
[https://keycloak.discourse.group/t/cant-import-realm-using-docker-image/259/24] at the last section

**Removing the Default Policy of type: js and Default Permission" of "type": "js"  also resolved my problem, but it is not functioning properly like earlier if we just hit "https://localhost:51111" then it redirects to the admin console login page.
But now It is landing on Keycloak welcome page.**

Is there any tool to upgrade the realm of Keycloak 15 to Keycloak 20 also why do we need to remove the  "name": "Default Policy" and "name": "Default Permission" of "type": "js"?

### Version

20.0.1

### Expected behavior

It should smoothly import and start

### Actual behavior

Import Realm having default policy and de

### How to Reproduce?

Start Keycloak 20.0.1 with Realm having  "name": "Default Policy" and "name": "Default Permission" of "type": "js".

Will throw an error unable to migrate.

**Comment by sschu** [comment]
Can't you just import the realm into a Wildfly Keycloak 15, update this to 20 and then import into the target Keycloak instance?

**Comment by ajaiswal595** [comment]
How to update to 20 from keycloak 15?

**Comment by sschu** [comment]
Backup your database and just connect the new Keycloak version to the same database.

**Comment by sschu** [comment]
It looks like in your master realm, you have deleted clients for managing other realms. For every realm, there is a client `<realm-name>-realm`used to assign roles to manage that realm. This client (and other clients generated by Keycloak) should not be deleted.

**Comment by ajaiswal595** [comment]
@sschu The client <realm-name>-realm is available in wildfly distro.

How can we migrate the realm,

**Comment by sschu** [comment]
The last stack trace looks like you are missing the client "account-console".

**Comment by ajaiswal595** [comment]
@sschu 

What is the significance of an account-console why do we need this?

As in Prior Keycloak (legacy) it was not required.

**Comment by sschu** [comment]
It represents the new account console that uses the account api. It is one of the Keycloak-internal clients so it should always exist with the default configuration.

**Comment by vramik** [comment]
> Also tried adding admin-console in client but it did not help as suggested here

@ajaiswal595 

The suggestion would be to export the `account-console` client from another realm (e.g. newly created one) and then import it to your realm, then it should be found here: https://github.com/keycloak/keycloak/blob/8abe984844c53f55294eedc18939f2b603a3a9d7/model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo20_0_0.java#L32

and the migration should succeed. Closing as not planned.
