### ISSUE TITLE
Keycloak 20.0.1 on Oracle Database - ORA-00932: inconsistent datatypes: expected - got NCLOB

### ISSUE THREAD

**Issue by GerhardMassenbichler** [keycloak/keycloak#15889]
### Area

core

### Describe the bug

**### Describe the bug**

I'm trying to set up Keycloak 20.0.1 (Quarkus) with an Oracle database. Keycloak should run in a Docker container and access an external Oracle database.

Keycloak starts fine and connects to the Oracle-Database, but the following error is repeatedly logged: 

`
2022-12-07 11:33:39,227 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 932, SQLState: 42000
2022-12-07 11:33:39,227 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) ORA-00932: inconsistent datatypes: expected - got NCLOB

2022-12-07 11:33:39,228 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredAdminEvents: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	at org.hibernate.loader.Loader.scroll(Loader.java:2945)
	at org.hibernate.loader.hql.QueryLoader.scroll(QueryLoader.java:610)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.scroll(QueryTranslatorImpl.java:452)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performScroll(HQLQueryPlan.java:353)
	at org.hibernate.internal.SessionImpl.scroll(SessionImpl.java:1601)
	at org.hibernate.query.internal.AbstractProducedQuery.doScroll(AbstractProducedQuery.java:1588)
	at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1574)
	at org.hibernate.query.internal.AbstractProducedQuery.stream(AbstractProducedQuery.java:1598)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.stream(CriteriaQueryTypeQueryAdapter.java:91)
	at org.hibernate.query.Query.getResultStream(Query.java:1140)
	at org.keycloak.events.jpa.JpaEventStoreProvider.clearExpiredAdminEvents(JpaEventStoreProvider.java:292)
	at org.keycloak.events.jpa.JpaEventStoreProviderFactory.invalidate(JpaEventStoreProviderFactory.java:69)
	at org.keycloak.services.DefaultKeycloakSessionFactory.lambda$invalidate$0(DefaultKeycloakSessionFactory.java:368)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.keycloak.services.DefaultKeycloakSessionFactory.invalidate(DefaultKeycloakSessionFactory.java:368)
	at org.keycloak.services.DefaultKeycloakSession.invalidate(DefaultKeycloakSession.java:123)
	at org.keycloak.services.scheduled.ClearExpiredAdminEvents.run(ClearExpiredAdminEvents.java:35)
	at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:58)
	at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:54)
	at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
	at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:54)
	at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:54)
	at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00932: inconsistent datatypes: expected - got NCLOB

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:163)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1010)
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1271)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1149)
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1661)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1470)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3761)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3936)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1102)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:78)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	... 41 more
Caused by: Error : 932, Position : 178, Sql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=:1  and realmattri0_.VALUE<>:2 , OriginalSql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=? and realmattri0_.VALUE<>?, Error Msg = ORA-00932: inconsistent datatypes: expected - got NCLOB

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)
	... 57 more
`

The problem seems to be that the database column REALM_ATTRIBUTE.VALUE is defined as NCLOB and in Oracle SQL it is not allowed to compare NCLOB/CLOB with the <> operator (unlike PostgresSQL).

### Version

20.0.1

### Expected behavior

No Errors in the Log: 
Perhaps Keycloak should query the NCLOB on the Oracle Database with the appropriate Oracle-Operator (eg. not like) oder the Database-Columns on Oracle should be varchar2(4000) instead of nclob if 4000 characters are enough. 

### Actual behavior

The Databasequery 

Sql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=:1  and realmattri0_.VALUE<>:2 , 
OriginalSql = select realmattri0_.NAME as name1_46_, realmattri0_.REALM_ID as realm_id3_46_, realmattri0_.VALUE as value2_46_ from REALM_ATTRIBUTE realmattri0_ where realmattri0_.NAME=? and realmattri0_.VALUE<>?, Error Msg = ORA-00932: inconsistent datatypes: expected - got NCLOB

fails because "<>" on OracleDB ist not allowed as operator with NCLOB.

### How to Reproduce?

Setup Keycloak 20.0.1 with OracleDatabase, start Keycloak, see Logs.

Here ist the Dockerfile: 

FROM  ubuntu:22.04

RUN apt-get update && \
    apt-get -y install wget curl zip openjdk-17-jre-headless net-tools && \
    update-ca-certificates

WORKDIR /opt
RUN wget https://github.com/keycloak/keycloak/releases/download/20.0.1/keycloak-20.0.1.zip
RUN unzip keycloak-20.0.1.zip
RUN mv keycloak-20.0.1 /opt/keycloak
RUN groupadd -g 1001 keycloak && \
    useradd -u 1001 -g 1001 -d /opt/keycloak -s /sbin/nologin keycloak
COPY themes/mytheme /opt/keycloak/themes/mytheme
COPY conf/cache-ispn-jdbc-ping.xml /opt/keycloak/conf/cache-ispn-jdbc-ping.xml
RUN chown -R keycloak:keycloak /opt/keycloak
WORKDIR /opt/keycloak

#SSH-Keys for testing
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
ENV KC_HTTP_ENABLED=true

##For complete doku of all parameters see: https://www.keycloak.org/server/all-config

# Enable health support: If the server should expose health check endpoints.
# If enabled, health checks are available at the '/health', '/health/ready' and '/health/live' endpoints.
ENV KC_HEALTH_ENABLED=true

# Enable metrics support: If the server should expose metrics.
# If enabled, metrics are available at the '/metrics' endpoint.
ENV KC_METRICS_ENABLED=true

#Hostname
ENV KC_HOSTNAME=localhost

#Logging
#ENV KC_LOG=gelf
#ENV KC_LOG_GELF_HOST=graylog.my.network
#ENV KC_LOG_GELF_PORT=12201
#ENV KC_LOG_LEVEL=info

# Configure a database vendor: Oracle DB inkl. RAC + Dataguard
ENV KC_DB=oracle
ENV KC_DB_USERNAME=KEYCLOAK
ENV KC_DB_PASSWORD=Test1234
ENV KC_DB_URL=jdbc:oracle:thin:@(<<<Oracle DB-Connect-String>>>>)

#Cluster Setup
ENV KC_CACHE_CONFIG_FILE=cache-ispn-jdbc-ping.xml

#Startup
USER 1001
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT /opt/keycloak/bin/kc.sh start --cache=ispn

**Comment by GenuineGuineapig** [comment]
Looks to be a duplicate to this one: https://github.com/keycloak/keycloak/issues/15561 (and thus is getting adressed here: https://github.com/keycloak/keycloak/issues/15528)
 
What I'm wondering is whether or not we can ignore this problem, or is it an actual blocker for production settings?

**Comment by GerhardMassenbichler** [comment]
Thank you for your quick response and please excuse, that i didn't found the duplicates. 

Yes, this issue is a duplicate to https://github.com/keycloak/keycloak/issues/15561 which themself ist a duplicate to https://github.com/keycloak/keycloak/issues/15528

A production setting should not throw any error the logs. In my case it is actual a blocker for production.
