### ISSUE TITLE
Failed to import realm with js policy in jar file

### ISSUE THREAD

**Issue by BiatBang** [keycloak/keycloak#15969]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I'm using keycloak 20.0.1 with quarkus image. I found an error when importing my realm with command:
```
/opt/keycloak/bin/kc.sh build --health-enabled=true
/opt/keycloak/bin/kc.sh start --optimized \
  --import-realm \
  --hostname=<hostname>
```

I have a realm with javascript policy. I built the policies into a jar file with following structure:
```
META_INF/
    keycloak-scripts.json
only-owner-policy.js
```

In the `keycloak-scripts.json`, I only have one policy:
```
{
  "policies": [
    {
      "name": "Only Owner Policy",
      "fileName": "only-owner-policy.js",
      "description": "Restrict only owner of the resource can access"
    }
  ]
}
```

In the realm json file, I have this in the client definiation:
```
"policies": [
  {
      "name": "Only Owner Policy",
      "type": "script-only-owner-policy.js",
      "logic": "POSITIVE",
      "decisionStrategy": "UNANIMOUS",
      "description": "Restrict only owner of the resource can access"
  }
]
```

Then in the keycloak console, I found error:
```
2022-12-13 02:00:26,281 WARN  [org.keycloak.services] (main) KC-SERVICES0005: Unable to import realm test from file /opt/keycloak/bin/../data/import/test-realm-init.json.: java.lang.RuntimeException: Could find policy provider with type [script-only-owner-policy.js]
	at org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:1238)
	at org.keycloak.authorization.AuthorizationProvider$3.create(AuthorizationProvider.java:350)
	at org.keycloak.models.utils.RepresentationToModel.importPolicies(RepresentationToModel.java:1164)
	at org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:1110)
	at org.keycloak.models.utils.RepresentationToModel.importAuthorizationSettings(RepresentationToModel.java:1057)
	at org.keycloak.storage.datastore.LegacyExportImportManager.lambda$importRealmAuthorizationSettings$8(LegacyExportImportManager.java:1431)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importRealmAuthorizationSettings(LegacyExportImportManager.java:1429)
	at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:425)
	at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:126)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:570)
	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:503)
	at org.keycloak.services.resources.KeycloakApplication.importRealm(KeycloakApplication.java:304)
	at org.keycloak.services.resources.KeycloakApplication.importRealms(KeycloakApplication.java:280)
	at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:213)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:43)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

I also tried:
- Using kc.sh build -> start -> import to import the realm json file
- change the js name to `script-only-owner-policy.js`
- manually upload the realm json file to admin console
- put the policy files in the structure like this: [https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-authz-uma-photoz/photoz-js-policies]()

None of these works. I wonder if there is anything I'm missing or this is a bug.

### Version

20.0.1

### Expected behavior

Realm correctly imported

### Actual behavior

Exception thrown:
`[org.keycloak.services] (main) KC-SERVICES0005: Unable to import realm daas from file /opt/keycloak/bin/../data/import/daas-realm-init.json.: java.lang.RuntimeException: Could find policy provider with type [script-only-owner-policy.js]`

### How to Reproduce?

use the files and then import the realm

**Comment by lexcao** [comment]
Could you please try to change this from `realm.json`?
```
"type": "script-only-owner-policy.js",
```
to 
```
"type" : "js",
```

**Comment by BiatBang** [comment]
I believe the javascript type is deprecated. I tried it and I got some error like `java.lang.RuntimeException: Script upload is disabled`. I checked the latest keycloak quick start tut, and the current usage is `"type": "script-<your-js-file>.js"`. https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-authz-uma-photoz

**Comment by BiatBang** [comment]
Is there any update on this topic?

**Comment by BiatBang** [comment]
Sorry I'm such a fool. There is a hidden space after file `keycloak-scripts.json `. After removing it everything works well.

**Comment by mposolda** [comment]
@BiatBang Thanks for the confirm. I am closing this then.
