### ISSUE TITLE
Health Check failure when KC_HTTP_RELATIVE_PATH set on 20.0.0

### ISSUE THREAD

**Issue by hean0224** [keycloak/keycloak#16002]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

New install of 20.0.0 (also effected 19.0.2).  I originally assumed it may be related to https://github.com/keycloak/keycloak/issues/15799, but my issue is not intermittent.

I have both KC_HEATLH_ENABLED = "true" and KC_HTTP_RELATIVE_PATH = "auth" set on container Environment variables in AWS ECS Task defintion.  Below is the failure I see in the logs.  I have my logging at INFO level, but I can bump it up and resend as needed.

```
> 2022-12-14 17:42:33,735 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /auth/health failed, error id: 7499d507-415c-42aa-930c-429a1c8bc2e0-6: java.lang.NullPointerException
>   | 2022-12-14T11:42:33.736-06:00 | at org.keycloak.services.error.KeycloakErrorHandler.getResponse(KeycloakErrorHandler.java:61)
>   | 2022-12-14T11:42:33.736-06:00 | at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:56)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.ExceptionHandler.executeExceptionMapper(ExceptionHandler.java:136)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:309)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:258)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
>   | 2022-12-14T11:42:33.736-06:00 | at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
>   | 2022-12-14T11:42:33.736-06:00 | at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
>   | 2022-12-14T11:42:33.736-06:00 | at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
>   | 2022-12-14T11:42:33.736-06:00 | at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
>   | 2022-12-14T11:42:33.736-06:00 | at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
>   | 2022-12-14T11:42:33.736-06:00 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>   | 2022-12-14T11:42:33.736-06:00 | at java.base/java.lang.Thread.run(Thread.java:829)
```
After removing KC_HTTP_RELATIVE_PATH = "auth" the health check works as expected.

Other KC environment setting.
```
KC_DB =	postgres
KC_DB_URL_DATABASE = postgres
KC_DB_URL_HOST = *.us-east-2.rds.amazonaws.com
KC_DB_URL_PORT = 5432
KC_DB_URL_PROPERTIES = ?currentSchema=auth
KC_DB_USERNAME = auth_owner
KC_HEALTH_ENABLED = true
KC_HOSTNAME = *.mydomain.com
KC_HTTP_ENABLED = false
KC_HTTP_RELATIVE_PATH = auth
KC_LOG_LEVEL = info
KC_PROXY = reencrypt
KC_DB_PASSWORD = *
KEYCLOAK_ADMIN_PASSWORD = *
```
Any ideas or releases I should attempt?  Note this does work with 18.0.0, but release notes state 19 did some work with health checks.

### Version

20.0.0

### Expected behavior

/auth/health return 200 and applicaton/json

### Actual behavior

/auth/health returns 500

### How to Reproduce?

Attempt to hit URL */auth/health through an AWS application load balancer on a new quay.io release of keycloak (19.0.2 and 20.0.0) with KC_HTTP_RELATIVE_PATH = "auth" and KC_HEALTH_ENABLED = "true"

**Comment by hean0224** [comment]
I reran the original with debug on.  There was some additional information about the orig of the error so added on here.

```
2022-12-14 19:15:27,890 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (vert.x-eventloop-thread-1) Recalculated absoluteURI to https://app.mydomain.com/auth/health
2022-12-14 19:15:27,901 DEBUG [io.vertx.ext.web.RoutingContext] (executor-thread-2) RoutingContext failure (500): java.lang.NullPointerException
	at org.keycloak.services.error.KeycloakErrorHandler.getResponse(KeycloakErrorHandler.java:61)
	at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:56)
	at org.jboss.resteasy.core.ExceptionHandler.executeExceptionMapper(ExceptionHandler.java:136)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:309)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:258)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by pedroigor** [comment]
@hean0224 I can't reproduce the issue. I'm running the server as follows to check the behavior on 20.0.0 and 19.0.2.

```
docker run --name keycloak-test -p 8080:8080 quay.io/keycloak/keycloak:19.0.2 start --hostname-strict=false --http-relative-path=/auth --health-enabled=true --http-enabled=true
```

Calling the `/auth/health` endpoint multiple times does not cause the error.

**Comment by evsasha** [comment]
It worked on 20.0.2

**Comment by pedroigor** [comment]
@hean0224 @evsasha I missed how the option was being set. Perhaps we should avoid this error and make sure the `http-relative-path` always start with `/`.

At the same time, we have this constraint very explicit in our docs:

```
--http-relative-path <path>                                                                                                                                                                   
                     Set the path relative to '/' for serving resources. The path must start with a                                                                                           
                       '/'. Default: /.

```

So, not sure.

I'm closing this one for now and waiting if you want to have this fixed in a separate issue as an enhancement.

**Comment by nrobert13** [comment]
hey guys,

does this actually work kin `20.0.3`? I'm running the keycloak with the operator but the probes are never succeeding, so the pods never become ready. I shelled into the pod and captured this:
```
bash-4.4$ env | grep -Ei "health|relative"
KC_HEALTH_ENABLED=true
KC_HTTP_RELATIVE_PATH=/auth
bash-4.4$ curl -k https://127.0.0.1:8443/auth/health/live
{"error":"RESTEASY003210: Could not find resource for full path: https://127.0.0.1:8443/auth/health/live"}
bash-4.4$ curl -k https://127.0.0.1:8443/auth/health
{"error":"RESTEASY003210: Could not find resource for full path: https://127.0.0.1:8443/auth/health"}
bash-4.4$ curl -k https://127.0.0.1:8443/health/live

{
    "status": "UP",
    "checks": [
    ]
}
bash-4.4$
```

**Comment by pedroigor** [comment]
@vmuzikar Is the operator respecting the value for `http-relative-path` during probing?

**Comment by nrobert13** [comment]
@pedroigor as far as I can tell, yes it does. the problem is actually in keycloak, I opened an issue, https://github.com/keycloak/keycloak/issues/16605

**Comment by pedroigor** [comment]
Not sure ... We have tests running for the distribution like this one https://github.com/keycloak/keycloak/blob/ced18f27223f98611d6f0b2a04721bedd7dd7a22/quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/HealthDistTest.java#L71.

**Comment by nrobert13** [comment]
hmm, then maybe the env variable `KC_HTTP_RELATIVE_PATH` is not taken into account for https? is there also `KC_HTTPS_RELATIVE_PATH` ? or otherwise why wouldn't I be able to login from admin-cli over `/auth`?

**Comment by pedroigor** [comment]
I'm pretty sure this works when using `https` scheme too as it has no relation with the HTTP listeners that are enabled.

But I'll double check.

**Comment by nrobert13** [comment]
@pedroigor , have you got the chance to look into this?

**Comment by sschu** [comment]
If anybody is interested, https://quarkus.io/blog/path-resolution-in-quarkus/ explains how the paths are resolved in Quarkus and why `auth` and `/auth` makes a difference.

**Comment by pedroigor** [comment]
@sschu Interesting...

@nrobert13 You're right there are two misbehaviors when using paths without slashes:

* A NPE when trying to close the session because requests to metrics and heath do not go through the session request lifecycle. This is the issue you are reporting.
* After fixing above, the metrics and health endpoints are appended to the `http-relative`path=auth` as `/auth/auth/metrics|health"

I'll create an issue and fix it. Sorry for the delay.

**Comment by pedroigor** [comment]
@nrobert13 But for now, you can just append `/` to your `http-relative-path`.

**Comment by nrobert13** [comment]
> @nrobert13 But for now, you can just append `/` to your `http-relative-path`.

@pedroigor I'm not entirely sure what you mean here. my relative path is `/auth` see the snippe above where:
```
KC_HTTP_RELATIVE_PATH=/auth
```

**Comment by pedroigor** [comment]
In the description you wrote:

```
KC_HTTP_RELATIVE_PATH = auth
```

Without slashes and I was able to reproduce the error you got when using that value.

**Comment by sschu** [comment]
At least if I start Keycloak locally, I cannot reproduce this:
```
➜  bulk git:(master) ✗ docker run -p 8080:8080  -e KC_HTTP_RELATIVE_PATH=/auth -e KC_METRICS_ENABLED=true -e KC_HEALTH_ENABLED=true -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.3 start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
2023-01-28 16:05:11,739 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 14711ms
2023-01-28 16:05:16,244 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2023-01-28 16:05:20,226 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-01-28 16:05:23,250 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-01-28 16:05:23,371 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-01-28 16:05:23,418 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-01-28 16:05:24,023 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
2023-01-28 16:05:25,176 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_185915, Site name: null
2023-01-28 16:05:25,209 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-01-28 16:05:28,611 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2023-01-28 16:05:32,988 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2023-01-28 16:05:36,395 INFO  [io.quarkus] (main) Keycloak 20.0.3 on JVM (powered by Quarkus 2.13.6.Final) started in 24.248s. Listening on: http://0.0.0.0:8080
2023-01-28 16:05:36,396 INFO  [io.quarkus] (main) Profile dev activated.
2023-01-28 16:05:36,397 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2023-01-28 16:05:37,411 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
2023-01-28 16:05:37,424 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
^Z
[1]  + 72782 suspended  podman run -p 8080:8080 -e KC_HTTP_RELATIVE_PATH=/auth -e  -e  -e  -e
➜  bulk git:(master) ✗ bg
[1]  + 72782 continued  podman run -p 8080:8080 -e KC_HTTP_RELATIVE_PATH=/auth -e  -e  -e  -e
➜  bulk git:(master) ✗ curl localhost:8080/auth/health

{
    "status": "UP",
    "checks": [
        {
            "name": "Keycloak database connections health check",
            "status": "UP"
        }
    ]
}
```
I also works for us in production. However, we don't use the operator - so it might be related to that.

**Comment by nrobert13** [comment]
@sschu thanks for looking into this. I cannot reproduce it in dev mode either, but here's in prod mode, with an empty postgres db:
```
 docker run --rm  --name mykeycloak -p 8080:8080 \
        -e KEYCLOAK_ADMIN=admin \
        -e KEYCLOAK_ADMIN_PASSWORD=change_me \
        -e KC_HEALTH_ENABLED=true \
        -e KC_HTTP_RELATIVE_PATH=/auth \
        -e KC_PROXY=passthrough \
        -e KC_CACHE_STACK=udp \
        -e KC_CACHE=ispn \
        -e KC_HTTP_ENABLED="true" \
        -e KC_HOSTNAME=login.example.com \
        -e KC_DB_USERNAME=keycloak \
        -e KC_DB_PASSWORD=keycloak \
        -e KC_DB_URL_HOST=host.docker.internal \
        keycloak/keycloak:20.0.3 \
        start --optimized
 ```

```
curl -s http://localhost:8080/auth/health
{"error":"RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/health"}
```

**Comment by nrobert13** [comment]
I added a docker-compose to the other [issue](https://github.com/keycloak/keycloak/issues/16605#issuecomment-1410908104), to make it easier to reproduce. I played around with the env variables, but couldn't find a combination to work in prod mode. An it's not only the `/health` endpoint, you can see there that I tried the admin-cli as well...

**Comment by pedroigor** [comment]
@nrobert13 Now it makes sense. You are using the `optimized` flag to avoid building the server configuration.

By doing this, you are not actually changing the root path because the `http-relative-path` option is a build option and it requires a `build` first to update the server configuration.

Try removing the `--optimized` option and it should work.

For more details about the `optimized` option, please see https://www.keycloak.org/server/configuration#_optimize_the_keycloak_startup.

In any case, we had a low-hanging fruit from this issue as per https://github.com/keycloak/keycloak/pull/16736.

**Comment by nrobert13** [comment]
@pedroigor yeah, the `--optimized` flag is set by the operator automatically if you provide `image`. So I moved `KC_HTTP_RELATIVE_PATH=/auth` into the Dockerfile for the custom image, and I run `build` in the Dockerfile. Now it works with `--optimized`. thanks a lot!

**Comment by hean0224** [comment]
> @hean0224 @evsasha I missed how the option was being set. Perhaps we should avoid this error and make sure the `http-relative-path` always start with `/`.
> 
> At the same time, we have this constraint very explicit in our docs:
> 
> ```
> --http-relative-path <path>                                                                                                                                                                   
>                      Set the path relative to '/' for serving resources. The path must start with a                                                                                           
>                        '/'. Default: /.
> ```
> 
> So, not sure.
> 
> I'm closing this one for now and waiting if you want to have this fixed in a separate issue as an enhancement.

This was the issue, Sorry for missing the update requiring the use of / in front of relative path.

**Comment by vmuzikar** [comment]
Please note that while this was fixed at the server side, the Operator issue with probes still remains and will be resolved with https://github.com/keycloak/keycloak/issues/16800.
