### ISSUE TITLE
java.lang.ClassFormatError: Incompatible magic value 0 in class file jdk/net/ExtendedSocketOptions

### ISSUE THREAD

**Issue by w4tsn** [keycloak/keycloak#16177]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I've updated my keycloak instance from 20.0.1 to 20.0.2 and now one of my two instances is not starting anymore with the error in the title of this report.

After downgrading the version to 20.0.1 it works again. Re-pull and removal / recreation of the containers did not resolve the issue.

The error log right after starting the server:

```
keycloak_1  | 2022-12-25 22:40:47,848 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: https://auth.darmstadt.social, Hostname: auth.darmstadt.social, Strict HTTPS: true, Path: /, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
keycloak_1  | 2022-12-25 22:40:49,182 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
keycloak_1  | 2022-12-25 22:40:49,461 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Failed to create connection due to ClassFormatError
keycloak_1  | 2022-12-25 22:40:49,944 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
keycloak_1  | 2022-12-25 22:40:49,963 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
keycloak_1  | 2022-12-25 22:40:49,974 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
keycloak_1  | 2022-12-25 22:40:50,182 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
keycloak_1  | 2022-12-25 22:40:50,294 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
keycloak_1  | 2022-12-25 22:40:50,295 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
keycloak_1  | 2022-12-25 22:40:50,381 ERROR [org.jgroups.JChannel] (keycloak-cache-init) JGRP000017: 4de99ca88240-12828: disconnect failed: java.lang.NullPointerException
keycloak_1  | 2022-12-25 22:40:50,505 ERROR [io.quarkus.runtime.StartupContext] (main) Running a shutdown task failed: java.lang.RuntimeException: Failed to start caches
keycloak_1  | 	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.getOrCreate(CacheManagerFactory.java:56)
keycloak_1  | 	at org.keycloak.quarkus.runtime.KeycloakRecorder$1.run(KeycloakRecorder.java:90)
keycloak_1  | 	at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:84)
keycloak_1  | 	at io.quarkus.runtime.StartupContext.close(StartupContext.java:73)
keycloak_1  | 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
keycloak_1  | 	at io.quarkus.runtime.Application.start(Application.java:101)
keycloak_1  | 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
keycloak_1  | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
keycloak_1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
keycloak_1  | 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
keycloak_1  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
keycloak_1  | 	at picocli.CommandLine.access$1300(CommandLine.java:145)
keycloak_1  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
keycloak_1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
keycloak_1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
keycloak_1  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
keycloak_1  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
keycloak_1  | 	at picocli.CommandLine.execute(CommandLine.java:2078)
keycloak_1  | 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
keycloak_1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
keycloak_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
keycloak_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak_1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
keycloak_1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
keycloak_1  | Caused by: java.util.concurrent.ExecutionException: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.remoting.transport.Transport
keycloak_1  | 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
keycloak_1  | 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
keycloak_1  | 	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.getOrCreate(CacheManagerFactory.java:54)
keycloak_1  | 	... 25 more
keycloak_1  | Caused by: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.remoting.transport.Transport
keycloak_1  | 	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:770)
keycloak_1  | 	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:734)
keycloak_1  | 	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:405)
keycloak_1  | 	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:86)
keycloak_1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
keycloak_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
keycloak_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak_1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
keycloak_1  | Caused by: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.remoting.transport.Transport
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:585)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
keycloak_1  | 	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:70)
keycloak_1  | 	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
keycloak_1  | 	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
keycloak_1  | 	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:354)
keycloak_1  | 	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
keycloak_1  | 	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:766)
keycloak_1  | 	... 7 more
keycloak_1  | Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.net.ext.ExtendedSocketOptions
keycloak_1  | 	at java.base/java.net.PlainDatagramSocketImpl.<clinit>(PlainDatagramSocketImpl.java:46)
keycloak_1  | 	at java.base/java.net.DefaultDatagramSocketImplFactory.createDatagramSocketImpl(DefaultDatagramSocketImplFactory.java:72)
keycloak_1  | 	at java.base/java.net.DatagramSocket.createImpl(DatagramSocket.java:333)
keycloak_1  | 	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:241)
keycloak_1  | 	at java.base/java.net.MulticastSocket.<init>(MulticastSocket.java:168)
keycloak_1  | 	at org.jgroups.util.DefaultSocketFactory.createMulticastSocket(DefaultSocketFactory.java:129)
keycloak_1  | 	at org.jgroups.protocols.UDP.createMulticastSocket(UDP.java:533)
keycloak_1  | 	at org.jgroups.protocols.UDP.createSockets(UDP.java:362)
keycloak_1  | 	at org.jgroups.protocols.UDP.start(UDP.java:292)
keycloak_1  | 	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:881)
keycloak_1  | 	at org.jgroups.JChannel.startStack(JChannel.java:985)
keycloak_1  | 	at org.jgroups.JChannel._preConnect(JChannel.java:849)
keycloak_1  | 	at org.jgroups.JChannel.connect(JChannel.java:358)
keycloak_1  | 	at org.jgroups.JChannel.connect(JChannel.java:352)
keycloak_1  | 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:554)
keycloak_1  | 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:478)
keycloak_1  | 	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
keycloak_1  | 	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
keycloak_1  | 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
keycloak_1  | 	... 25 more
keycloak_1  | 
keycloak_1  | ERROR: Failed to start server in (production) mode
keycloak_1  | ERROR: java.lang.ClassFormatError: Incompatible magic value 0 in class file jdk/net/ExtendedSocketOptions
keycloak_1  | ERROR: Incompatible magic value 0 in class file jdk/net/ExtendedSocketOptions
keycloak_1  | For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

20.0.2

### Expected behavior

The server starts as before when issuing `docker-compose up -d` in my case.

### Actual behavior

The server errors out and refuses to start with the aformentioned error message.

### How to Reproduce?

I have no idea.

### Anything else?

I have another instance which also runs 20.0.2, but I don't have issues there although I set them up similarly.

**Comment by Pepo48** [comment]
Hi @w4tsn, thanks for reporting the issue! It's difficult to reproduce the exact issue as you admitted that another instance with the similar configuration works properly. Thus I'm closing this one, since based on the provided description I can't replicate the issue nor the exact environment at the moment.

Please, feel free to reopen the issue again in case you'll find out more details that could help with the reproduction.
Thanks again!
