### ISSUE TITLE
Enabling "Verify Profile" required action causes NPE and locks out of keycloak 

### ISSUE THREAD

**Issue by Trojaner** [keycloak/keycloak#16176]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

NullPointerException when the verify profile action runs

### Version

20.0.2

### Expected behavior

The verify profile action should run and I should be able to log in.

### Actual behavior

After enabling the "Verify Profile" required action and logging out, I was no longer able to log in and got the "internal error occurred" message instead (while it tried to execute the verify profile action).

<details>
  <summary>**Stacktrace from log**</summary>

```
2022-12-24 22:09:02,399 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-148) Uncaught server error: java.lang.NullPointerException
--
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.forms.login.freemarker.model.AbstractUserProfileBean$Attribute.compareTo(AbstractUserProfileBean.java:207)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.forms.login.freemarker.model.AbstractUserProfileBean$Attribute.compareTo(AbstractUserProfileBean.java:97)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.TimSort.sort(TimSort.java:220)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.Arrays.sort(Arrays.java:1515)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.forms.login.freemarker.model.AbstractUserProfileBean.toAttributes(AbstractUserProfileBean.java:91)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.forms.login.freemarker.model.AbstractUserProfileBean.init(AbstractUserProfileBean.java:42)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.forms.login.freemarker.model.VerifyProfileBean.<init>(VerifyProfileBean.java:23)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createResponse(FreeMarkerLoginFormsProvider.java:287)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createResponse(FreeMarkerLoginFormsProvider.java:201)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.authentication.requiredactions.UpdateProfile.createResponse(UpdateProfile.java:100)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.authentication.requiredactions.VerifyUserProfile.requiredActionChallenge(VerifyUserProfile.java:89)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.services.managers.AuthenticationManager.executeAction(AuthenticationManager.java:1316)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.services.managers.AuthenticationManager.lambda$executionActions$18(AuthenticationManager.java:1264)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.services.managers.AuthenticationManager.executionActions(AuthenticationManager.java:1265)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.services.managers.AuthenticationManager.actionRequired(AuthenticationManager.java:1157)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.services.managers.AuthenticationManager.nextActionAfterAuthentication(AuthenticationManager.java:1001)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:993)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.services.resources.LoginActionsService.requiredActionGET(LoginActionsService.java:975)
Sun, Dec 25 2022 1:09:02 am | at jdk.internal.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
Sun, Dec 25 2022 1:09:02 am | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
Sun, Dec 25 2022 1:09:02 am | at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
Sun, Dec 25 2022 1:09:02 am | at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
Sun, Dec 25 2022 1:09:02 am | at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
Sun, Dec 25 2022 1:09:02 am | at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
Sun, Dec 25 2022 1:09:02 am | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Sun, Dec 25 2022 1:09:02 am | at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

### How to Reproduce?

1. Enable verify profile action and ensure you it will execute on you
2. NullPointerException occurs and you cannot verify profile or login

**Comment by Trojaner** [comment]
Affected line https://github.com/keycloak/keycloak/blob/5aae3842c40c8f5b8c6c80fa47e09c11f4a6d7e6/services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java#L207

**Comment by pedroigor** [comment]
@Trojaner Identity providers should not interfere when rendering the page.

Could you provide the steps and your user profile configuration to reproduce the error?

**Comment by pedroigor** [comment]
Feel free to open it if you have more details about how to reproduce the problem.
