### ISSUE TITLE
Admin CLI - unknown error

### ISSUE THREAD

**Issue by nrobert13** [keycloak/keycloak#16186]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/cli

### Describe the bug

Hello everyone,

I'm trying to migrate from 16.1.1 ( wildfly ) to the latest opertator managed version, but cannot reset the password for the admin user in the master realm.
I tried the following steps in the keycloak container:

5. the keycloak instance is coming up with an error
```
ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
```
6. tried to login as admin with the credential from the initial admin secret
```
bash-4.4$ /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin
Logging into http://localhost:8080 as user admin of realm master
Enter password: ********************************
Invalid user credentials [invalid_grant]
bash-4.4$
```
7. logged in with my own user with admin rights ( ldap user federation )
```
bash-4.4$ /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm my_realm --user my_user
Logging into http://localhost:8080 as user my_user of realm my_realm
Enter password: ********************
bash-4.4$
```
8. when I try to reset the admin password, I get `unknown error`
```
bash-4.4$ /opt/keycloak/bin/kcadm.sh set-password -r master --username admin --new-password admin -t -x
null [unknown_error]
org.keycloak.client.admin.cli.util.HttpResponseException: null [unknown_error]
	at org.keycloak.client.admin.cli.util.HeadersBodyStatus.checkSuccess(HeadersBodyStatus.java:61)
	at org.keycloak.client.admin.cli.util.HttpUtil.checkSuccess(HttpUtil.java:353)
	at org.keycloak.client.admin.cli.util.HttpUtil.doGetJSON(HttpUtil.java:377)
	at org.keycloak.client.admin.cli.util.HttpUtil.getAttrForType(HttpUtil.java:465)
	at org.keycloak.client.admin.cli.util.HttpUtil.getIdForType(HttpUtil.java:445)
	at org.keycloak.client.admin.cli.operations.UserOperations.getIdFromUsername(UserOperations.java:94)
	at org.keycloak.client.admin.cli.commands.SetPasswordCmd.process(SetPasswordCmd.java:116)
	at org.keycloak.client.admin.cli.commands.SetPasswordCmd.execute(SetPasswordCmd.java:68)
	at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:63)
	at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:48)
	at org.keycloak.client.admin.cli.aesh.AeshConsoleCallbackImpl.execute(AeshConsoleCallbackImpl.java:54)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: {"error":"unknown_error"}
	... 15 more
bash-4.4$
```
9. tried to get users, to see if the authentication worked, but it doesn't seem to have
```
bash-4.4$ /opt/keycloak/bin/kcadm.sh get users -r my_realm --offset 0 --limit 20 -x
null [unknown_error]
org.keycloak.client.admin.cli.util.HttpResponseException: null [unknown_error]
	at org.keycloak.client.admin.cli.util.HeadersBodyStatus.checkSuccess(HeadersBodyStatus.java:61)
	at org.keycloak.client.admin.cli.util.HttpUtil.checkSuccess(HttpUtil.java:353)
	at org.keycloak.client.admin.cli.commands.AbstractRequestCmd.process(AbstractRequestCmd.java:363)
	at org.keycloak.client.admin.cli.commands.AbstractRequestCmd.execute(AbstractRequestCmd.java:126)
	at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:63)
	at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:48)
	at org.keycloak.client.admin.cli.aesh.AeshConsoleCallbackImpl.execute(AeshConsoleCallbackImpl.java:54)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: {"error":"unknown_error"}
```
10. if I enter a wrong password for my own account I get proper error:
```
bash-4.4$ /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm my_realm --user my_user
Logging into http://localhost:8080 as user my_user of realm my_realm
Enter password: *********
Invalid user credentials [invalid_grant]
``` 
11. I can login with my own user over the web ui, but I cannot see any user in the master realm, so no admin user either.

### Version

20.0.2

### Expected behavior

the admin password either get's updated in the database with the one from the initial secret or able to reset it over the admin-cli.

### Actual behavior

cannot reset the admin user password

### How to Reproduce?

1. create a logical backup ( dump ) of the existing database ( postgres 13 ) from 16.1.1
2. create a new db instance
3. import the dump from #1
4. create a keycloak instance with the keycloak-operator ( 20.0.2 ) using the newly created database at #3
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
  namespace: iam-test
spec:
  instances: 1
  db:
    vendor: postgres
    host: db-host
    usernameSecret:
      name: db-credentials
      key: username
    passwordSecret:
      name: db-credentials
      key: password
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
    tlsSecret: keycloak-tls
  hostname:
    hostname: login.example.com
  ingress:
    enabled: false
```

**Comment by nrobert13** [comment]
looking into the [code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java#L99), it seems that the `admin` user is being created only if there are no other users in the master realm, regardless of the usernames.

**Comment by abstractj** [comment]
@nrobert13 would you be able to create a dump for us to reproduce the steps you mentioned? We need to ensure that have similar environments. That would be incredibly helpful.

**Comment by abstractj** [comment]
Thank you for taking the time to report the issue. However, we were unable to investigate the bug due to the lack of detailed steps to reproduce the problem.

We understand that it can be difficult to provide clear instructions, but without them, our team is unable to identify the issue. 

If you can provide more detailed steps or any additional context, it would be of great help. You are welcome to reopen this issue with the added details.
