### ISSUE TITLE
Keycloak does not accept custom FormAuthenticator

### ISSUE THREAD

**Issue by fredericoschardong** [keycloak/keycloak#16195]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I am trying to create my custom registration process and found two issues: 

1. The web interface breaks when you implement a `FormAuthenticator` and `FormAuthenticatorFactory` as shown at the end of the gif below:
![interface](https://user-images.githubusercontent.com/3732628/209884872-47eee429-f9bf-4665-8b95-cf2563aaf140.gif)
A new selector is created to allow for the selection of the available `FormAuthenticator`s. However, one can not select anything other than is selected by default.

2. Continuing from above, the custom `FormAuthenticator` is unusable as shown:
![error](https://user-images.githubusercontent.com/3732628/209885545-429b6487-a924-4022-bd78-328f9c760703.gif)
The error stack is:
```
2022-12-28 23:40:39,024 WARN  [org.keycloak.services] (executor-thread-45) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException
at org.keycloak.authentication.FormAuthenticationFlow.renderForm(FormAuthenticationFlow.java:307)
at org.keycloak.authentication.FormAuthenticationFlow.processFlow(FormAuthenticationFlow.java:285)
at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:381)
at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:250)
at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1017)
at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:879)
```

The [SPI](https://github.com/keycloak/keycloak/files/10316983/spi.zip) I created is just copies of `RegistrationPage.java` and `register.ftl`.

### Version

20.0.2

### Expected behavior

The web interface should allow for the selection of any `FormAuthenticator` and the newly implemented one should work.

### Actual behavior

As shown above.

### How to Reproduce?

Download the [SPI](https://github.com/keycloak/keycloak/files/10316983/spi.zip), load it to KC 20.0.2 and follow the steps shown on the GIFs above.

**Comment by mrpatrickpilch** [comment]
Potentially related https://github.com/keycloak/keycloak-ui/issues/3727

**Comment by mposolda** [comment]
duplicates #17945
@mrpatrickpilch Thanks for pointing that! I am closing as duplicate. Also this is likely already fixed
