### ISSUE TITLE
Custom ACR claim results in UnrecognizedPropertyException

### ISSUE THREAD

**Issue by MariuszCwikla** [keycloak/keycloak#16196]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

When I make following request with Javascript adapter

```
keycloak.login({
    acr: {
        value: "gold",
        transactionId: "1234"
    }
})
```

then:
- keycloak logs `UnrecognizedPropertyException` error
- and token is generated but with different acr level that was requested due to previous error

### Version

19.0.0

### Expected behavior

1. Keycloak should return requested "acr" claim in the token
2. Additionally keycloak should allow developer to return additional claims in the token. This is possible by implementing custom token mapper.

### Actual behavior

1. Following error is logged in the console

```
2022-12-29 19:07:40,710 WARN  [org.keycloak.protocol.oidc.utils.AcrUtils] (vert.x-worker-thread-4) Invalid claims parameter: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "transactionId" (class org.keycloak.representations.ClaimsRepresentation$ClaimValue), not marked as ignorable (3 known properties: "value", "values", "essential"])
 at [Source: (String)"{"id_token":{"acr":{"value":"gold","transactionId":"1234"}}}"; line: 1, column: 53] (through reference chain: org.keycloak.representations.ClaimsRepresentation["id_token"]->java.util.LinkedHashMap["acr"]->org.keycloak.representations.ClaimsRepresentation$ClaimValue["transactionId"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	...
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:75)
	at org.keycloak.protocol.oidc.utils.AcrUtils.getAcrValues(AcrUtils.java:62)
	at org.keycloak.protocol.oidc.mappers.AcrProtocolMapper.getAcr(AcrProtocolMapper.java:113)
	at org.keycloak.protocol.oidc.mappers.AcrProtocolMapper.setClaim(AcrProtocolMapper.java:86)
```
 
2. keycloak returns different acr than requested

### How to Reproduce?

Configure Step-Up flow according to official docs and issue request with additional claims in `acr`

### Anything else?

This can be fixed simply by adding `@JsonIgnoreProperties(ignoreUnknown = true)` to `ClaimsRepresentation`.
I can spare few minutes to prepare a Pull Request with such a fix.

I have small additional related questions.

1. If my understanding is correct then Request Objects or JAR (JWT secured authorization request) would be bit better for my use case but I can't see any official documentation regarding that. I have seen some PRs/discussions here on github, but I am not sure if this officially supported. To me it also looks like it's kind of supported by the keycloak server, but I don't see such support in the javascript adapter. Any comments on that?
a. Is Request Object/JAR supported by keycloak server?
b. Is Request Object/JAR supported javascript adapter?
2. Also it seems that `claims` parameter is supported by certain protocol mappers but seem to be undocummented and unsupported by javascript adapter either (`org.keycloak.protocol.oidc.mappers.ClaimsParameterTokenMapper` seem to be supporting more advanced claims parameter than "just" "acr" claim)

**Comment by pedroigor** [comment]
JAR is supported by the server but we don't have anything on the JS adapter side to help with JAR. 

The only thing related to claims I can see in JS adapter is https://github.com/keycloak/keycloak/issues/10154. But it is very specific to step-up and requesting `acr` claim. @mposolda Anything else we are missing?

The mapper you mentioned is basically setting claims in the token depending on the requested claims. Note that the format should be https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter. However, this mapper has a very narrow scope in terms of implementation as per https://github.com/keycloak/keycloak/pull/7232.

**Comment by mposolda** [comment]
@pedroigor As you mentioned, there is not any support for JAR on JS adapter. Regarding claims parameter in JS adapter, I've proposed something more flexible (See this link https://github.com/keycloak/keycloak/discussions/10120 and section "Keycloak.js support" and "Option 3" inside it), but it was agreed to go with something simpler specific only to `acr` claim.

Regarding "acr" claim format in keycloak.js, it is also documented here https://www.keycloak.org/docs/latest/securing_apps/index.html#javascript-adapter-reference (See "acr" parameter). The possible format is for example something like `{ values: ["silver", "gold"], essential: true }` . The format you're using is not considered supported ATM, so I don't think that this can be considered a bug IMO.

**Comment by MariuszCwikla** [comment]
Indeed, I do not consider this is not a bug per se (e.g. because it's not officially documented).
But would you consider implementing this "enhancement"?
I am also looking forward for the support for JAR in JS adapter.
