### ISSUE TITLE
LinkageError for FipsMode during startup

### ISSUE THREAD

**Issue by yalpertem** [keycloak/keycloak#16202]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

After upgrading from `19.0.3` to `20.0.2`, I'm getting an error during the startup as follows:

```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#setCryptoProvider threw an exception: 
java.lang.LinkageError: loader constraint violation: 
loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @75ed9710 
wants to load class org.keycloak.common.crypto.FipsMode.
A different class with the same name was previously loaded by java.net.URLClassLoader @2e377400. 
(org.keycloak.common.crypto.FipsMode is in unnamed module of loader java.net.URLClassLoader 
@2e377400, parent loader 'app')
...
at io.quarkus.deployment.recording.BytecodeRecorderImpl$$RecordingProxyProxy2.setCryptoProvider(Unknown Source)
at org.keycloak.quarkus.deployment.KeycloakProcessor.setCryptoProvider(KeycloakProcessor.java:607)
```

### Version

20.0.2

### Expected behavior

No runtime errors during the startup.

### Actual behavior

`java.lang.LinkageError` for `FipsMode` during the startup.

### How to Reproduce?

I couldn't find a way to reproduce the issue in a simple setup as I'm using Keycloak with some customizations like adding certificates via `keytool` and adding some custom SPI implementations (tried building the jar both with Java 11 and Java 17).

Using the base image `quay.io/keycloak/keycloak:20.0.2`

`.conf` file:

```
spi-user-profile-provider=custom-profile
spi-email-template-freemarker-enabled=false
spi-connections-jpa-default-migration-strategy=update
spi-events-listener-email-exclude-events=LOGIN_ERROR
http-enabled=true
hostname-strict=false
hostname-strict-https=false
features=
features-disabled=admin2
metrics-enabled=true
health-enabled=true
```

Run command:
```
/opt/keycloak/bin/kc.sh --verbose -cf /opt/keycloak/conf/keycloak.conf start-dev --debug --proxy edge
```

### Anything else?

I'm reading https://github.com/keycloak/keycloak/pull/14895 which introduced the `FipsMode` class but couldn't understand the reason yet.

**Comment by yalpertem** [comment]
My bad, fixed it by changing

```
	implementation "org.keycloak:keycloak-client-registration-api:$keycloakVersion"
```

to

```
	compileOnlyApi "org.keycloak:keycloak-client-registration-api:$keycloakVersion"
```

in my gradle config for the SPI implementation.
