### ISSUE TITLE
io.quarkus.builder.BuildException caused by java.lang.OutOfMemoryError: unable to create native thread

### ISSUE THREAD

**Issue by benediktneumayr** [keycloak/keycloak#16261]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Dear keycloak developers, I really appreciate the hard work, sweat and tears you put into creating such an amazing piece of software! However, I have to inform about a severe issue I encountered while trying to deploy keycloak using the official prebuilt docker images on a Ubuntu 20.04 LTS host using the most recent version of the docker daemon. The issue appears to be rooted in the quarkus build system and manifests itself as "java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached" error.  This means I can't even get the actual keycloak service up and running. The following is the output each time I start the container from scratch (`docker-compose run keycloak`):

<pre><code>Creating docker_keycloak_run ... done
Appending additional Java properties to JAVA_OPTS: -Xmx1500m -Xss1024k -Djava.net.preferIPv6Addresses=true -Djava.net.preferIPv4Stack=false
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
[21.495s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[21.498s][warning][os,thread] Failed to start the native thread for java.lang.Thread "build-31"
ERROR: Failed to run 'build' command.
Error details:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
        at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:71)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:183)
        at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:120)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:88)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.util.concurrent.RejectedExecutionException
        at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
        at org.jboss.threads.EnhancedQueueExecutor.rejectException(EnhancedQueueExecutor.java:2049)
        at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1713)
        at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:787)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:254)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
                at java.base/java.lang.Thread.start0(Native Method)
                at java.base/java.lang.Thread.start(Thread.java:802)
                at org.jboss.threads.JBossThread.start(JBossThread.java:558)
                at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1709)
                ... 15 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
        at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
        ... 26 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.util.concurrent.RejectedExecutionException
        at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
        at org.jboss.threads.EnhancedQueueExecutor.rejectException(EnhancedQueueExecutor.java:2049)
        at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1713)
        at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:787)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:254)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
                at java.base/java.lang.Thread.start0(Native Method)
                at java.base/java.lang.Thread.start(Thread.java:802)
                at org.jboss.threads.JBossThread.start(JBossThread.java:558)
                at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1709)
                ... 15 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        ... 28 more
Caused by: java.util.concurrent.RejectedExecutionException
        at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
        at org.jboss.threads.EnhancedQueueExecutor.rejectException(EnhancedQueueExecutor.java:2049)
        at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1713)
        at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:787)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:254)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:565)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Suppressed: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
                at java.base/java.lang.Thread.start0(Native Method)
                at java.base/java.lang.Thread.start(Thread.java:802)
                at org.jboss.threads.JBossThread.start(JBossThread.java:558)
                at org.jboss.threads.EnhancedQueueExecutor.doStartThread(EnhancedQueueExecutor.java:1709)
                ... 15 more
ERROR: 1</code></pre>

Originally, I tested against the latest (at the time of writing) nightly docker image (a2a45bee5728), but could reproduce the same error with the 20.0.2-1 and 19.0.3 version even after completely deleting and recreating the container associated with keycloak several times. While doing so, I kept a close watch at htop to check whether a memory exhaustion actually occurs. But this is not the case, only an almost constant 30% of the main memory were occupied throughout the quarkus build process. The maximum number of processes per user, as returned by `ulimit -u` is 62987, which should be more than enough. Similarly, `cat /proc/sys/kernel/threads-max` returns 1542610.

My configuration looks as follows: 
<pre><code>===The relevant docker-compose.yaml service section===
keycloak:
    image: quay.io/keycloak/keycloak:nightly
    command: --config-file=/config/keycloak.conf --verbose start
    expose:
      - "8080"
    volumes:
      - /var/docker/keycloak/config:/config
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JAVA_OPTS_APPEND: -Xmx1500m -Xss1024k -Djava.net.preferIPv6Addresses=true -Djava.net.preferIPv4Stack=false
    restart: unless-stopped</pre></code>

<pre><code>===keycloak.conf===
hostname=account.example.org
db=mysql
db-url-host=mysql
db-username=keycloak
db-password=notTheRealPass
proxy=edge</pre></code>

Note that the docker host runs inside some sort of VM: I am trying to install keycloak on my VPS, and my hoster (Strato) uses Virtuozzo to implement userland virtualization. This has never been a source of trouble, but even though keycloak might be a first, it certainly would be advantageous if keycloak were capable of running in even such an environment, since I think that this is a typical setup for many small organizations like ours.

Am I missing something obvious or did I just find a real bug?

### Version

The current (at the time of writing) nightly docker image (a2a45bee5728) 

### Expected behavior

The build process should proceed smoothly and the actual keycloak application should start up.

### Actual behavior

As layed out above in the bug description.

### How to Reproduce?

At the moment, I can't provide you a definite guide of how to reproduce this bug, but the excerpts of the configuration files provided in  the above bug description provide a starting point.

### Anything else?

If you need further details, don't hesitate to get back to me.

**Comment by pedroigor** [comment]
@benediktneumayr Ideally, you should avoid running a `build` when starting a container. You should favor instead using a pre-built container image with all the settings (mainly the build options) you need to start the server. 

Please, take a look at https://www.keycloak.org/server/containers#_creating_a_customized_and_optimized_container_image.

By following this approach, you are CPU and memory resources when starting the server as well as improve your start-up time.

I can easily reproduce the error you are facing by trying out different settings when running a container using docker:

```
docker run -it --rm --name keycloak --cpus="1" --memory=512m -p 8080:8080 -p 8443:8443 --network=host -e "JAVA_OPTS=-Xms64m -Xmx128m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=128m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8" quay.io/keycloak/keycloak:nightly start
```

While using a pre-built container image makes it possible to at least start the server with the same resource/heap settings.

**Comment by benediktneumayr** [comment]
Thank you so much for your prompt reply! I followed the guide you shared with me exactly, but in the beginning, I was unable to get past the build stage. Then I finally got the idea to stop all the docker containers (that were mostly idle) during the optimization phase, and that did the trick. Turns out quarkus needs every bit of resources it can squeeze out of my VPS.
I'll do some further testing if I can now build reliably, and if that's the case, I'll close the issue.

**Comment by benediktneumayr** [comment]
@pedroigor Once I got keycloak up and running, it works like a charm! I really like the way keycloak combines vast functionality with straightforward configuration. Since I can reliably build production images now, I will close this issue.
