### ISSUE TITLE
Keycloak have space in path , or keystore , truststore , or till js-provider if space it's failed

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#16319]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I'm running Keycloak in both mac and windows os and it's failing every where if 

**--https-key-store-file**      /Users/ajay/keycloak cert/keystore.ks
**--https-trust-store-file**.   /Users/ajay/keycloak cert/truststore.ks
And path till js-provider have space.

For ex:

Here is the path of Keycloak 

**/Users/ajaykumarjaiswal/driveE/keycloak spacepath/bin**

And i have placed one provider as js-policy.jar

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/8745632/211309300-99dbf390-9e49-4cb0-ab03-44cfcd4515e3.png">

Here is the error i'm getting 

`(base) ajaykumarjaiswal@C02Z45LWLVDR bin % ./kc.sh start-dev   
Updating the configuration and installing your custom providers, if any. Please wait.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2023-01-09 18:06:33,649 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

2023-01-09 18:06:33,718 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@2792b416 to QuarkusClassLoader Augmentation Class Loader: PROD

2023-01-09 18:06:33,719 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement@4735d6e5 to QuarkusClassLoader Augmentation Class Loader: PROD

...

2023-01-09 18:06:35,907 DEBUG [io.netty.util.internal.PlatformDependent0] (build-3) direct buffer constructor: unavailable: java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:288)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:282)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:333)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:88)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:132)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at io.vertx.core.http.HttpMethod.<clinit>(HttpMethod.java:192)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.<clinit>(VertxHttpRecorder.java:1511)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:274)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:378)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$57(ExtensionLoader.java:663)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:905)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

2023-01-09 18:06:35,907 DEBUG [io.netty.util.internal.PlatformDependent0] (build-3) java.nio.Bits.unaligned: available, true

2023-01-09 18:06:35,908 DEBUG [io.netty.util.internal.PlatformDependent0] (build-3) jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @16053510
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at io.netty.util.internal.PlatformDependent0$7.run(PlatformDependent0.java:410)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:401)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:333)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:88)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:132)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at io.vertx.core.http.HttpMethod.<clinit>(HttpMethod.java:192)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.<clinit>(VertxHttpRecorder.java:1511)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:274)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:378)
	at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFromClass$57(ExtensionLoader.java:663)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:905)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.RuntimeException: Failed to discover script providers
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:698)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadFactories(KeycloakProcessor.java:637)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:340)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: /Users/ajaykumarjaiswal/driveE/keycloak%20spacepath/lib/../providers/js-policy.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:260)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:679)
	... 13 more

ERROR: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.RuntimeException: Failed to discover script providers
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:698)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadFactories(KeycloakProcessor.java:637)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:340)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.NoSuchFileException: /Users/ajaykumarjaiswal/driveE/keycloak%20spacepath/lib/../providers/js-policy.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:260)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.loadDeployedScriptProviders(KeycloakProcessor.java:679)
	... 13 more

ERROR: Failed to discover script providers
ERROR: /Users/ajaykumarjaiswal/driveE/keycloak%20spacepath/lib/../providers/js-policy.jar
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
`

### Version

20.0.1

### Expected behavior

It should handle path in all environment

### Actual behavior

it's failing

### How to Reproduce?

keep spaces in the path of truststore , keystore , or till provider folder and add one javascript provider  then it will fail.

**Comment by sschu** [comment]
Have you tried adding double quotes around your file locations? Otherwise the shell will treat it as different parameters.

**Comment by ajaiswal595** [comment]
Yes I added double quotes it did not work,

Also we should handle it in the code.

Second js-provider is also failed, if we add others provider at the same place and remove js-provider it works.


So for the path of trust store, keystore and Java script provider need to fixed.

**Comment by ajaiswal595** [comment]
And we should handle it in the code

**Comment by ajaiswal595** [comment]
What about loading of java-script provider?

**Comment by sschu** [comment]
How to reproduce this?

**Comment by ajaiswal595** [comment]
@sschu  you can refer this issue [https://github.com/keycloak/keycloak/issues/11664](https://github.com/keycloak/keycloak/issues/11664)

How photoz-uma-js-policies.jar is created and placed into the provider directory.

If Space will be there in the path of Keycloak Home then you will get the error unable to find photoz-uma-js-policies.jar.
