### ISSUE TITLE
KeycloakDeployment failed to load URLs behind a proxy with required authentication 

### ISSUE THREAD

**Issue by vdeygas** [keycloak/keycloak#16400]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/java-cli

### Describe the bug

Given a desktop app using keycloak-installed-adapter behind a proxy.
This proxy required credentials.

Keycloak adapater is not able to resolve URLs because of no credential setted.
An HTTP 407 is returned by http proxy.

```
AdapterConfig adapterConfig = KeycloakDeploymentBuilder.loadAdapterConfig(is);
adapterConfig.setProxyUrl("http://127.0.0.1:3128");   // credentials required 
this.keycloak = new KeycloakInstalled(KeycloakDeploymentBuilder.build(adapterConfig));
this.keycloak.loginDesktop();
```
            
Stack trace :    

```
2023-01-11 16:03:19 DEBUG KeycloakDeployment:180 - Resolving URLs from http://jenkins-cms-01.lan.4dconcept.fr:8202/auth/realms/contentfactory-realm/.well-known/openid-configuration
2023-01-11 16:03:33 WARN  KeycloakDeployment:201 - Failed to load URLs from http://jenkins-cms-01.lan.4dconcept.fr:8202/auth/realms/contentfactory-realm/.well-known/openid-configuration
java.lang.Exception: Proxy Authentication Required
	at org.keycloak.adapters.KeycloakDeployment.getOidcConfiguration(KeycloakDeployment.java:233)
	at org.keycloak.adapters.KeycloakDeployment.resolveUrls(KeycloakDeployment.java:182)
        ...
```

### Version

20.0.2

### Expected behavior

Aibility to set the credentials for the given authentication scope (proxy)

### Actual behavior

An HTTP 407 is returned by http proxy.

### How to Reproduce?

see description above

**Comment by sschu** [comment]
I would say this is an enhancement, not a bug. Using proxies with authentication is just not supported (yet).

**Comment by shawkins** [comment]
Closing as out-of-date.
