### ISSUE TITLE
username and certificate conflict throws an exception and returns 500 http status code

### ISSUE THREAD

**Issue by Bukarim** [keycloak/keycloak#16490]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

If users try to get a token with an incorrect certificate, then:
- an AuthenticationFlowException is thrown:
`ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.keycloak.authentication.AuthenticationFlowException at org.keycloak.authentication.AuthenticationProcessor.setAutheticatedUser(AuthenticationProcessor.java:273)`

- HTTP status code 500 is returned:
`{
    "error": "unknown_error"
}`

### Version

9.0.3/16.1.1/19.0.3

### Expected behavior

If users try to get a token with an incorrect certificate, then:

- no Exception is thrown
- HTTP status code 401 is returned:
`{
    "error": "USER_CONFLICT",
    "error_description": "authentication failed, check your credentials"
}`

### Actual behavior

If users try to get a token with an incorrect certificate, then:
- an AuthenticationFlowException is thrown:
`ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.keycloak.authentication.AuthenticationFlowException at org.keycloak.authentication.AuthenticationProcessor.setAutheticatedUser(AuthenticationProcessor.java:273)`

- HTTP status code 500 is returned:
`{
    "error": "unknown_error"
}`

### How to Reproduce?

> curl -L -X POST 'https://localhost/auth/realms/the-Realm/protocol/openid-connect/token' 
-H 'Content-Type: application/x-www-form-urlencoded' 
--data-urlencode 'grant_type=the-password' 
--data-urlencode 'client_id=the-client' 
--data-urlencode 'client_secret=the-client-secret' 
--data-urlencode 'username=wrong-username' 
--cert-type P12 --cert the-right-certificate.p12:the-password

**Comment by rmartinc** [comment]
@Bukarim I see that you have sent a PR, but can you please paste the full exception? (I don't fully understand your problem...)

**Comment by Bukarim** [comment]
> @Bukarim I see that you have sent a PR, but can you please paste the full exception? (I don't fully understand your problem...)

@rmartinc this problem can be produced when using a username for some different user than the user present in the certificate.
`2023-01-27T11:02:02.257300000Z 2023-01-27 12:02:02,255 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: org.keycloak.authentication.AuthenticationFlowException
2023-01-27T11:02:02.257329500Z 	at org.keycloak.authentication.AuthenticationProcessor.setAutheticatedUser(AuthenticationProcessor.java:273)
2023-01-27T11:02:02.257332200Z 	at org.keycloak.authentication.AuthenticationProcessor$Result.setUser(AuthenticationProcessor.java:432)
2023-01-27T11:02:02.257334200Z 	at org.keycloak.authentication.authenticators.x509.ValidateX509CertificateUsername.authenticate(ValidateX509CertificateUsername.java:143)
2023-01-27T11:02:02.257346700Z 	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:446)
2023-01-27T11:02:02.257348900Z 	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:250)
2023-01-27T11:02:02.257351000Z 	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1017)
2023-01-27T11:02:02.257352900Z 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.resourceOwnerPasswordCredentialsGrant(TokenEndpoint.java:605)
2023-01-27T11:02:02.257354700Z 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:202)
2023-01-27T11:02:02.257356500Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-01-27T11:02:02.257358200Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2023-01-27T11:02:02.257360000Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2023-01-27T11:02:02.257361800Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2023-01-27T11:02:02.257363600Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2023-01-27T11:02:02.257365300Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2023-01-27T11:02:02.257367100Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
2023-01-27T11:02:02.257368900Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
2023-01-27T11:02:02.257370700Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
2023-01-27T11:02:02.257373100Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2023-01-27T11:02:02.257375000Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
2023-01-27T11:02:02.257376800Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
2023-01-27T11:02:02.257378500Z 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
2023-01-27T11:02:02.257380300Z 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
2023-01-27T11:02:02.257441700Z 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
2023-01-27T11:02:02.257444600Z 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
2023-01-27T11:02:02.257446300Z 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
2023-01-27T11:02:02.257474100Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2023-01-27T11:02:02.257475900Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2023-01-27T11:02:02.257481100Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2023-01-27T11:02:02.257483000Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2023-01-27T11:02:02.257508400Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2023-01-27T11:02:02.257510200Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2023-01-27T11:02:02.257512000Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2023-01-27T11:02:02.257513800Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
2023-01-27T11:02:02.257515600Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
2023-01-27T11:02:02.257517400Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
2023-01-27T11:02:02.257519200Z 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2023-01-27T11:02:02.257520900Z 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2023-01-27T11:02:02.257522700Z 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-01-27T11:02:02.257524900Z 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
2023-01-27T11:02:02.257526800Z 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
2023-01-27T11:02:02.257528600Z 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2023-01-27T11:02:02.257530400Z 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2023-01-27T11:02:02.257532100Z 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-01-27T11:02:02.257533800Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
2023-01-27T11:02:02.257535600Z 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
2023-01-27T11:02:02.257537400Z 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2023-01-27T11:02:02.257539100Z 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2023-01-27T11:02:02.257540800Z 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-01-27T11:02:02.257542600Z 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
2023-01-27T11:02:02.257544400Z 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
2023-01-27T11:02:02.257546100Z 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
2023-01-27T11:02:02.257547800Z 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
2023-01-27T11:02:02.257556300Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
2023-01-27T11:02:02.257558300Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2023-01-27T11:02:02.257560100Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2023-01-27T11:02:02.257561800Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2023-01-27T11:02:02.257563600Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2023-01-27T11:02:02.257565300Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-01-27T11:02:02.257567100Z 	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by rmartinc** [comment]
@Bukarim I still don't understand this completely. If I'm not missing something you have configured a new "direct grant" flow to use "X509/Validate Username". But if I'm following you all right, you have maintained the step "Username Validation", right? That's why the error is produced.

If you follow the [doc](https://www.keycloak.org/docs/latest/server_admin/index.html#adding-x-509-client-certificate-authentication-to-a-direct-grant-flow), it asks you to remove the "Username Validation" and "Password". Mainly you just need the the "X509/Validate Username" (only that step). With this conf I suppose the error cannot be generated as the username is not even checked, just the certificate is used to obtain the user.

**Comment by Bukarim** [comment]
Thanks for the tip, we've adjusted our flow and it's working as expected 🥇
