### ISSUE TITLE
Flaky test: org.keycloak.testsuite.admin.ComponentsTest#testConcurrencyWithChildren

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#16521]
This has been caused by MSSQL deadlock. See #16155 and [KEYCLOAK-3210](https://issues.redhat.com/browse/KEYCLOAK-3210).

## org.keycloak.testsuite.admin.ComponentsTest#testConcurrencyWithChildren
[Keycloak CI - Legacy Store IT (mssql)](https://github.com/keycloak/keycloak/actions/runs/3948116487/jobs/6757871365) / [Pull Request #16516](https://github.com/keycloak/keycloak/pull/16516)

```
java.lang.AssertionError: Did not create all components in time
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.admin.ComponentsTest.testConcurrency(ComponentsTest.java:74)
	at org.keycloak.testsuite.admin.ComponentsTest.testConcurrencyWithChildren(ComponentsTest.java:94)
...
```

**Comment by vramik** [comment]
Given the lack of failures, I propose closing this issue. If the issue occurs again, please feel free to re-open the issue.
