### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.session.UserSessionProviderOfflineModelTest#testOfflineSessionLazyLoading

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#16568]
## org.keycloak.testsuite.model.session.UserSessionProviderOfflineModelTest#testOfflineSessionLazyLoading
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/3970591532/jobs/6806604873) / [Pull Request #16560](https://github.com/keycloak/keycloak/pull/16560)

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.keycloak.testsuite.model.session.UserSessionProviderOfflineModelTest.lambda$testOfflineSessionLazyLoading$15(UserSessionProviderOfflineModelTest.java:325)
...
```

**Comment by stianst** [comment]
Duplicate of https://github.com/keycloak/keycloak/issues/16565
