### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.session.UserSessionInitializerTest#testUserSessionInitializerWithDeletingClient

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#16569]
## org.keycloak.testsuite.model.session.UserSessionInitializerTest#testUserSessionInitializerWithDeletingClient
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/3970591532/jobs/6806604873) / [Pull Request #16560](https://github.com/keycloak/keycloak/pull/16560)

```
java.lang.AssertionError: 
Count of offline sesions for client 'third-party'
Expected: is <1L>
     but: was <0L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
...
```

```
java.lang.AssertionError: 
Count of offline sesions for client 'third-party'
Expected: is <1L>
     but: was <0L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
...
```

**Comment by martin-kanis** [comment]
Closing as the issue seems to be gone.
