### ISSUE TITLE
Invalid Username or Password when calling oidc auth endpoint with ACR values

### ISSUE THREAD

**Issue by sashokbg** [keycloak/keycloak#16582]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Given I have already logged in
When I call the oidc auth endpoint a second time
Then an error page "invalid username and password" is shown.

Example URL:

http://localhost:7080/realms/my-realm/protocol/openid-connect/auth?response_type=code&client_id=my-client&scope=openid%20profile%20email&state=x3N7P5le0E6czyqkhH4TgLIbKDpcOSfbznrg6eLSu5A%3D&redirect_uri=http://localhost:8095/login/oauth2/code/keycloak2sensitive&nonce=kOUdToSmNrXsuxcsavFXtvSjljASKhWzHFpZLs2kJog&acr_values=sensitive

### Version

20.0.2

### Expected behavior

Given a redirect uri in the request
When I call the auth endpoint a second time
Then I am automatically redirected to the uri address

### Actual behavior

Read description please

### How to Reproduce?

Follow the guide for step up authentication: 

https://www.keycloak.org/docs/latest/server_admin/#_step-up-flow

Call the oidc endpoint twice

### Anything else?

Exception Logs:

```
my-local-stack-keycloak-1   | 2023-01-23 16:06:08,499 WARN  [org.keycloak.services] (executor-thread-548) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
my-local-stack-keycloak-1   | 	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1025)
my-local-stack-keycloak-1   | 	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:879)
my-local-stack-keycloak-1   | 	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:151)
my-local-stack-keycloak-1   | 	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:338)
my-local-stack-keycloak-1   | 	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:194)
my-local-stack-keycloak-1   | 	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
my-local-stack-keycloak-1   | 	at jdk.internal.reflect.GeneratedMethodAccessor349.invoke(Unknown Source)
my-local-stack-keycloak-1   | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
my-local-stack-keycloak-1   | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
my-local-stack-keycloak-1   | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
my-local-stack-keycloak-1   | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
my-local-stack-keycloak-1   | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
my-local-stack-keycloak-1   | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
my-local-stack-keycloak-1   | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
my-local-stack-keycloak-1   | 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
my-local-stack-keycloak-1   | 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
my-local-stack-keycloak-1   | 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
my-local-stack-keycloak-1   | 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
my-local-stack-keycloak-1   | 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
my-local-stack-keycloak-1   | 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
my-local-stack-keycloak-1   | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
my-local-stack-keycloak-1   | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
my-local-stack-keycloak-1   | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
my-local-stack-keycloak-1   | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
my-local-stack-keycloak-1   | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
my-local-stack-keycloak-1   | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
my-local-stack-keycloak-1   | 	at java.base/java.lang.Thread.run(Thread.java:829)

```

_No response_

**Comment by vickeybrown** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.  
It will be helpful if:

-   You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
-   If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
-   If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
-   If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here [https://www.keycloak.org/community](https://www.keycloak.org/community) for the details on how to contribute to Keycloak and eventually send the PR.
