### ISSUE TITLE
Support for native GSSAPI

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#16603]
This issue is to investigate if we should ever support GSS-Native in Keycloak for Kerberos integration. The reason is, that it *may* be FIPS compliant (to be doublechecked if it really is).

Related conversation between Alexander Bokovoy and myself:

1) Marek: Thanks, the PR is here if you want to take a look: https://github.com/keycloak/keycloak/pull/16478 . Still some test failures need to be figured, but you can take a look already...

This is related to FIPS as in the FIPS environment (on RHEL with FIPS enabled), the Kerberos functionality is not available due the SunJGSS security provider is not FIPS compliant yet and hence it is missing in the java.security. So the idea was to encapsulate all the Kerberos related functionality in Keycloak within a "feature", which is enabled by default, but disabled in FIPS environment. Nothing related to Kerberos protocol itself is changed in this PR and the typical environment should not be changed anyhow as long as Kerberos worked already before in such environment. 

2) Alexander's reply:
> Thanks for the details. I looked also at the referenced bugzilla
> https://bugzilla.redhat.com/show_bug.cgi?id=2051628 and there are few
> problems here.
>
> I think it should be working with a native GSS API
> (-Dsun.security.jgss.native=true) and this is the only one we support in
> RHEL -- we do not support Oracle's own SunJGSS. With native GSS API use
> it would load MIT Kerberos implementation which works with FIPS.
>
> I do not see Keycloak enforcing -Dsun.security.jgss.native=true
> anywhere.
>
> There is another problem, now FIPS specific. If you go by strict
> compliance, even AES128-CTS-HMAC-SHA1-96 and AES256-CTS-HMAC-SHA1-96
> aren't FIPS compliant because they use a non-FIPS KDF. The proper ones
> are encryption types present in RFC8009 but these aren't supported by
> Active Directory. So, in the end, many customers set up RHEL with FIPS
> and allow AES128-CTS-HMAC-SHA1-96 and AES256-CTS-HMAC-SHA1-96. It is not
> Red Hat's issue -- FIPS compliance is purely between those customers and
> their FIPS auditors.
>
> That still would need an appropriate crypto policy setting on the
> system, e.g. 'update-crypto-policies --set FIPS:AD-SUPPORT' on RHEL to
> allow use of AD-compatible encryption types in FIPS mode.

Forgot to add: I have looked at the PR itself and I think it is good
from the perspective of it only relying on ability to instantiate
GSSManager -- if that succeeds, it would use Kerberos. If not, it would
be disabled. If native GSS API would work with Keycloak in FIPS mode,
we'd get it enabled transparently and your PR would ensure it is used in
FIPS mode.

So from my perspective this looks good. 

3) Marek's reply:
Thanks Alexander, this is very useful info!

So if I understand you correctly, can you confirm if using native GSS API (property -Dsun.security.jgss.native=true) is FIPS compliant on RHEL 8.6 with OpenJDK 17.0.5? Just for the details, my java version is:

openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.5.0.8-2.el8_6) (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.5.0.8-2.el8_6) (build 17.0.5+8-LTS, mixed mode, sharing)

I can add that when "-Dsun.security.jgss.native=true" is used, the "GSSManager.getInstance().getMechs()" is able to find both KRB5 OID and Spnego OID. But what worries me a bit is the fact that this property does not seem to be officially documented though? At least in the java sources of "sun.security.jgss.GSSManagerImpl.USE_NATIVE_PROP" I can see comment stating "Undocumented property" .

Also I saw some issue when I've tried to test the real SPNEGO workflow. But I guess I need to install and setup some MIT Kerberos packages on my RHEL to be able to proceed?

Just for the reference (if you have some quick idea, hints or documentation), the exception currently thrown during spnego handshake on Keycloak side:
```
Caused by: GSSException: No valid credentials provided
    at java.security.jgss/sun.security.jgss.wrapper.NativeGSSFactory.getCredFromSubject(NativeGSSFactory.java:59)
    at java.security.jgss/sun.security.jgss.wrapper.NativeGSSFactory.getCredentialElement(NativeGSSFactory.java:112)
    at java.security.jgss/sun.security.jgss.GSSManagerImpl.getCredentialElement(GSSManagerImpl.java:174)
    at java.security.jgss/sun.security.jgss.GSSCredentialImpl.add(GSSCredentialImpl.java:439)
    at java.security.jgss/sun.security.jgss.GSSCredentialImpl.<init>(GSSCredentialImpl.java:89)
    at java.security.jgss/sun.security.jgss.GSSManagerImpl.createCredential(GSSManagerImpl.java:141)
    at org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator.establishContext(SPNEGOAuthenticator.java:165)
    at org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator$AcceptSecContext.run(SPNEGOAuthenticator.java:132)
    at org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator$AcceptSecContext.run(SPNEGOAuthenticator.java:122)
```

**Comment by mposolda** [comment]
Branch with some initial experiments is here: https://github.com/mposolda/keycloak/tree/16603-native-gssapi-experimental

In this branch, the `KerberosLdapTest#spnegoLoginTest` (and likely other kerberos tests) are failing with the exception above ( `GSSException: No valid credentials provided` ).
