### ISSUE TITLE
SAML tests in quarkus3 branch failing due to missing SAAJ factory

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#16711]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

SAML tests (e.g. `ArtifactBindingTest` fail on quarkus 3 branch due to missing SAAJ meta-factory:

```
Caused by: jakarta.xml.soap.SOAPException: Unable to create message factory for SOAP: Unable to create SAAJ meta-factory: Provider com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl not found
	at jakarta.xml.soap.MessageFactory.newInstance(MessageFactory.java:96)
	at org.keycloak.protocol.saml.profile.util.Soap$SoapMessageBuilder.<init>(Soap.java:120)
	... 142 more
```

### Version

quarkus3 branch

### Expected behavior

SAML tests should pass in the quarkus 3 branch

### Actual behavior

Tests such as `ArtifactBindingTest` fail on quarkus 3 branch

### How to Reproduce?

Run the mentioned tests using the quarkus 3 branch

**Comment by ahus1** [comment]
merged into Q3 branch, closing.
