### ISSUE TITLE
ISPN000559: Cannot marshall 'class org.infinispan.marshall.protostream.impl.MarshallableUserObject': java.io.NotSerializableException: org.keycloak.models.cache.infinispan.entities.NonExistentItem

### ISSUE THREAD

**Issue by ydhif** [keycloak/keycloak#16745]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

I have some trouble with infinispan embedded in keycloak quarkus.
When I ran a keycloak cluster on quarkus distribution everythnig's fine I have no problem when I use my application, but when I log into the administration interface and click on Clients I can see this error below :

2023-01-31 14:29:56,617 WARN  [org.infinispan.PERSISTENCE] (executor-thread-2) ISPN000559: Cannot marshall 'class org.infinispan.marshall.protostream.impl.MarshallableUserObject': java.io.NotSerializableException: org.keycloak.models.cache.infinispan.entities.NonExistentItem
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
        at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
        at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectToObjectStream(AbstractJBossMarshaller.java:75)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectToBuffer(AbstractJBossMarshaller.java:83)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectToByteBuffer(AbstractMarshaller.java:70)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectToByteBuffer(AbstractMarshaller.java:60)
        at org.infinispan.marshall.core.impl.DelegatingUserMarshaller.objectToByteBuffer(DelegatingUserMarshaller.java:58)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.write(MarshallableUserObject.java:150)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.write(MarshallableUserObject.java:100)
        at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:27)
        at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:301)
        at org.infinispan.protostream.WrappedMessage.write(WrappedMessage.java:242) 

...
Caused by: an exception which occurred:
        in object org.keycloak.models.cache.infinispan.entities.NonExistentItem@2da20a7d

2023-01-31 14:29:56,628 ERROR [org.infinispan.CLUSTER] (executor-thread-2) ISPN000073: Unexpected error while replicating: org.infinispan.commons.marshall.MarshallingException: org.keycloak.models.cache.infinispan.entities.NonExistentItem
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectToByteBuffer(AbstractInternalProtoStreamMarshaller.java:81)
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectToByteBuffer(AbstractInternalProtoStreamMarshaller.java:87)
        at org.infinispan.marshall.core.GlobalMarshaller.writeRawUnknown(GlobalMarshaller.java:637)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:626)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:617)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNonNullableObject(GlobalMarshaller.java:383)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNullableObject(GlobalMarshaller.java:351)
        at org.infinispan.marshall.core.BytesObjectOutput.writeObject(BytesObjectOutput.java:26)
        at org.infinispan.commands.triangle.SingleKeyBackupWriteCommand.writeTo(SingleKeyBackupWriteCommand.java:129)

I don't know where this come from. You can find here my keycloak config cache : 
<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

    <jgroups>
        <stack name="tcpping" extends="tcp">
            <TCP bind_port="{{ keycloak_cache_bind_port }}"
                 stack.combine="REPLACE"/>
            <TCPPING
                initial_hosts="{{ keycloak_cache_tcpping }}"
                port_range="0"
                stack.position="MPING"
                stack.combine="REPLACE"
            />
        </stack>
    </jgroups>
    <cache-container name="keycloak">
        <transport lock-timeout="60000" />
        <transport stack="tcpping" cluster="${infinispan.cluster.name:{{ instance_name }}}" node-name="${infinispan.node.name:{{ keycloak.node }}}" />
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authorization" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>

### Version

19.0.3 20.0.2

### Expected behavior

No errors when on client's realm.

### Actual behavior

2023-01-31 14:29:56,617 WARN  [org.infinispan.PERSISTENCE] (executor-thread-2) ISPN000559: Cannot marshall 'class org.infinispan.marshall.protostream.impl.MarshallableUserObject': java.io.NotSerializableException: org.keycloak.models.cache.infinispan.entities.NonExistentItem
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
        at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
        at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectToObjectStream(AbstractJBossMarshaller.java:75)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectToBuffer(AbstractJBossMarshaller.java:83)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectToByteBuffer(AbstractMarshaller.java:70)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectToByteBuffer(AbstractMarshaller.java:60)
        at org.infinispan.marshall.core.impl.DelegatingUserMarshaller.objectToByteBuffer(DelegatingUserMarshaller.java:58)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.write(MarshallableUserObject.java:150)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.write(MarshallableUserObject.java:100)
        at org.infinispan.protostream.impl.ProtobufTagMarshallerDelegate.marshall(ProtobufTagMarshallerDelegate.java:27)
        at org.infinispan.protostream.WrappedMessage.writeMessage(WrappedMessage.java:301)
        at org.infinispan.protostream.WrappedMessage.write(WrappedMessage.java:242) 

...
Caused by: an exception which occurred:
        in object org.keycloak.models.cache.infinispan.entities.NonExistentItem@2da20a7d

2023-01-31 14:29:56,628 ERROR [org.infinispan.CLUSTER] (executor-thread-2) ISPN000073: Unexpected error while replicating: org.infinispan.commons.marshall.MarshallingException: org.keycloak.models.cache.infinispan.entities.NonExistentItem
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectToByteBuffer(AbstractInternalProtoStreamMarshaller.java:81)
        at org.infinispan.marshall.protostream.impl.AbstractInternalProtoStreamMarshaller.objectToByteBuffer(AbstractInternalProtoStreamMarshaller.java:87)
        at org.infinispan.marshall.core.GlobalMarshaller.writeRawUnknown(GlobalMarshaller.java:637)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:626)
        at org.infinispan.marshall.core.GlobalMarshaller.writeUnknown(GlobalMarshaller.java:617)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNonNullableObject(GlobalMarshaller.java:383)
        at org.infinispan.marshall.core.GlobalMarshaller.writeNullableObject(GlobalMarshaller.java:351)
        at org.infinispan.marshall.core.BytesObjectOutput.writeObject(BytesObjectOutput.java:26)
        at org.infinispan.commands.triangle.SingleKeyBackupWriteCommand.writeTo(SingleKeyBackupWriteCommand.java:129)

### How to Reproduce?

You can probably use my cache.xml config file.

**Comment by ydhif** [comment]
I find out it's not possible to have a distributed cache on authorization. I will use session affinity. I close this issue.

**Comment by abhinavjuneja** [comment]
Was this issue resolved?
I am trying to have distributed-cache on realms. Getting the similar error:

```
Caused by: an exception which occurred:
        in field org.keycloak.models.cache.infinispan.entities.CachedRealm.cibaConfig
        in object org.keycloak.models.cache.infinispan.entities.CachedRealm@32dce272
        in object org.keycloak.models.cache.infinispan.entities.CachedRealm@32dce272
```
        
    ```
    
2023-07-28 06:58:22,259 WARN  [org.infinispan.PERSISTENCE] (jgroups-8,06e26bb46495-55456) ISPN000559: Cannot marshall 'class org.infinispan.marshall.protostream.impl.MarshallableUserObject': java.io.NotSerializableException: org.keycloak.models.cache.infinispan.DefaultLazyLoader
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1143)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1101)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:268)
        at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
        at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectToObjectStream(AbstractJBossMarshaller.java:75)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectToBuffer(AbstractJBossMarshaller.java:83)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectToByteBuffer(AbstractMarshaller.java:70)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectToByteBuffer(AbstractMarshaller.java:60)
        at org.infinispan.marshall.core.impl.DelegatingUserMarshaller.objectToByteBuffer(DelegatingUserMarshaller.java:58)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.write(MarshallableUserObject.java:150)
        at org.infinispan.marshall.protostream.impl.MarshallableUserObject$Marshaller.write(MarshallableUserObject.java:100) 
```
