### ISSUE TITLE
Unable to log in as Admin - JDBC resources leaked Error

### ISSUE THREAD

**Issue by rdocchio** [keycloak/keycloak#16781]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

Hi, hope you are doing great

When i try to log in with my admin user via GUI or API i get an unknown_error response

```
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d "username=$KEYCLOAK_USER&password=$KEYCLOAK_PASSWORD&client_id=admin-cli&grant_type=password" "$KEYCLOAK_HOST/realms/master/protocol/openid-connect/token"
{"error":"unknown_error"}
```
The logs in the server show this error:

```
2023-02-01 22:44:30,646 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NullPointerException
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.hibernate.query.spi.StreamDecorator.collect(StreamDecorator.java:209)
        at org.keycloak.utils.ClosingStream.collect(ClosingStream.java:182)
        at org.keycloak.models.cache.infinispan.entities.CachedUser.lambda$new$3(CachedUser.java:68)
        at org.keycloak.models.cache.infinispan.DefaultLazyLoader.get(DefaultLazyLoader.java:43)
        at org.keycloak.models.cache.infinispan.entities.CachedUser.getGroups(CachedUser.java:116)
        at org.keycloak.models.cache.infinispan.UserAdapter.getGroupsStream(UserAdapter.java:340)
        at org.keycloak.models.utils.KeycloakModelUtils.resolveAttribute(KeycloakModelUtils.java:517)
        at org.keycloak.protocol.oidc.mappers.UserAttributeMapper.setClaim(UserAttributeMapper.java:101)
        at org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.setClaim(AbstractOIDCProtocolMapper.java:132)
        at org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.transformAccessToken(AbstractOIDCProtocolMapper.java:82)
        at org.keycloak.protocol.oidc.TokenManager.lambda$transformAccessToken$4(TokenManager.java:745)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.keycloak.protocol.oidc.TokenManager.transformAccessToken(TokenManager.java:744)
        at org.keycloak.protocol.oidc.TokenManager.createClientAccessToken(TokenManager.java:534)
        at org.keycloak.protocol.oidc.TokenManager$AccessTokenResponseBuilder.generateAccessToken(TokenManager.java:1038)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.resourceOwnerPasswordCredentialsGrant(TokenEndpoint.java:627)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:200)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

2023-02-01 22:44:30,652 WARN  [io.agroal.pool] (executor-thread-1) Datasource '<default>': JDBC resources leaked: 2 ResultSet(s) and 2 Statement(s)
```

### Version

18.0.2

### Expected behavior

The /realms/master/protocol/openid-connect/token endpoint should respond with the access token to interact with the API

### Actual behavior

The endpoint response is 500 with errors

### How to Reproduce?

I'm Running two Keycloak Clusters sharing the same database in two Kubernetes Clusters working for Blue/Green Deployments.
I'm using Keycloak Bitnami Helm Chart

https://artifacthub.io/packages/helm/bitnami/keycloak/9.6.8

It worked ok until now. The steps that we've done until we came up with this issue were:

1. Yesterday we needed to assign a group to 5800 users in Keycloak, we issued the following command in the PostgreSQL Database (we did this in the past)
```
BEGIN
insert into user_group_membership (user_id, group_id) 
select ue.id, '$GROUP_UUID' from user_entity ue where not exists (select 1 from user_group_membership ugm where ugm.group_id = '$GROUP_UUID' and ugm.user_id = ue.id);
COMMIT
```
2. We weren't able to see the changes in the main Keycloak Cluster because of the cache, so we logged into the secondary Keycloak Cluster, and we could see the group assigned in some of the users but not in all of them.
3. We re deployed the secondary Keycloak Cluster to easily discard anything regarding the cache, but then we couldn't access to the Keycloak admin UI of the Secondary Cluster

```
The Browser started to redirect between 
https://auth.us-central1.utoppia.com/admin/master/console/
and
https://$KEYCLOAK_HOST/admin/master/console/#state=a205273e-6cf2-445f-84a1-2102ff02432c&session_state=b3039311-fdcf-45a4-818a-df3c3a61a639&code=56376274-d4ec-46bc-bbd0-d620cf776576.b3039311-fdcf-45a4-818a-df3c3a61a639.03ebd070-683f-45c8-8685-81effe8c591a
```
4. Today we logged into the Keycloak Main Cluster while this redirect loop was ocurring in the Secondary Keycloak Cluster and now we can't log in neither of both clusters

### Anything else?

Since this occurs even after i re deploy the Keycloak Cluster with an empty cache, i think that something inside the database is making this happen, but i couldnt find something regarding Sessions inside the database.

This happens only for the Admin User, all of our customers can log in without any problem but we lost administration of our Keycloak clusters

**Comment by rdocchio** [comment]
Update:

It seems this is related to the way i inserted the records into the user_group_membership. I made a test backing up the database and restoring it in another PostgreSQL database, The issue persisted even in the new database.

Then i deleted the user_group_memberships for that group_id and i was able to log in again.

Is there a way to safely insert data directly into the database? Is there any other alternative than send HTTP API requests to Keycloak for each user?

**Comment by abstractj** [comment]
@rdocchio thank you for submitting and reporting this issue, but unfortunately, we don't support or have the capacity to provide support third-party HELM charts. Please report the issue on Bitnami repository - [bitnami/charts](https://github.com/bitnami/charts).

We have several improvements and bug fixes on the latest releases, I'd suggest trying it without HELM charts and if the issue persists, please reopen adding more details.
