### ISSUE TITLE
users.create: UnhandledPromiseRejectionWarning: Error: Request failed with status code 500

### ISSUE THREAD

**Issue by merajsiddiqui** [keycloak/keycloak#16927]
When trying to create a new user in any `realm` it gives error

**To Reproduce**
```
import KcAdminClient from 'keycloak-admin';
const kcAdminClient = new KcAdminClient();
const setUp = async () => {
    await kcAdminClient.auth({
        username: 'XXX',
        password: 'XXX',
        grantType: 'password',
        clientId: 'admin-cli'
    });
    const users = await kcAdminClient.users.find(); //it works fine
    kcAdminClient.setConfig({realmName: 'Test'});
    let newUser =  {
                    username: 'meraj-node',
                    enabled: true,
                    emailVerified: false,
                    firstName: 'Meraj Ahmad',
                    lastName: 'Siddiqui',
                    email: 'meraj.siddiqui@gmail.com',
                    credentials :[{
                        value: "mypassword",
                        device: "macId",
                        temporary: false
                    }]
                };
    const u = await kcAdminClient.users.create( newUser)
    console.log(u)
}
setUp()
```
**Error :**
```
(node:21736) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/home/meraj/code/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/meraj/code/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/meraj/code/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:21736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
Should return some value instead of throwing error or should create user

**Enviroment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Keycloak 7.0.0
 - keycloak-admin: 1.12.0
 - node : 10.6.13

**Comment by edewit** [comment]
anything in the server log as to why this failed, because the code is right

**Comment by jonkoops** [comment]
Closing this issue die to lack of response from the author.
