### ISSUE TITLE
FIPS BouncyCastle Errors and Config

### ISSUE THREAD

**Issue by daurrutia** [keycloak/keycloak#17003]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

SOS @mposolda 

I'm seeing the error below when I'm using the following:
- custom built container image based on 20.0.1+
- bc-fips-1.0.2.3.jar    ---> /opt/keycloak/providers/
- bctls-fips-1.0.14.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.7.jar ---> /opt/keycloak/providers/
- bcfks keystore
- no modifications to java.security
- ` start --fips-mode=enabled`

But I don't see it (keycloak starts) when I use the following:
- custom built container image based on 20.0.0
- bc-fips-1.0.2.3.jar    ---> /opt/keycloak/providers/
- bctls-fips-1.0.12.2.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.5.jar ---> /opt/keycloak/providers/
- bcfks keystore
- no modifications to java.security
- ` start --fips-mode=enabled`

```
2023-02-11 02:02:14,467 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-02-11 02:02:14,467 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Unable to start HTTP server
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:758)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:318)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1866188241.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1866188241.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'int org.bouncycastle.asn1.ASN1Integer.intValueExact()'
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:724)
        ... 25 more
Caused by: java.lang.NoSuchMethodError: 'int org.bouncycastle.asn1.ASN1Integer.intValueExact()'
        at org.bouncycastle.asn1.cms.CCMParameters.<init>(Unknown Source)
        at org.bouncycastle.asn1.cms.CCMParameters.getInstance(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.decryptData(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at io.vertx.core.net.impl.KeyStoreHelper.loadKeyStore(KeyStoreHelper.java:237)
        at io.vertx.core.net.KeyStoreOptionsBase.getHelper(KeyStoreOptionsBase.java:187)
        at io.vertx.core.net.KeyStoreOptionsBase.getKeyManagerFactory(KeyStoreOptionsBase.java:205)
        at io.vertx.core.net.impl.SSLHelper.getKeyMgrFactory(SSLHelper.java:363)
        at io.vertx.core.net.impl.SSLHelper.lambda$init$0(SSLHelper.java:205)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Version

20.0.3

### Expected behavior

Keycloak starts with FIPS enabled.

### Actual behavior

Keycloak doesn't start.

### How to Reproduce?

- custom built container image based on 20.0.1+
- bc-fips-1.0.2.3.jar    ---> /opt/keycloak/providers/
- bctls-fips-1.0.14.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.7.jar ---> /opt/keycloak/providers/
- bcfks keystore
- no modifications to java.security
- ` start --fips-mode=enabled`

### Anything else?

Question: Are you placing the BCFIPS jars in /opt/keycloak/providers ?

Question: Are modifications to the java.security required? If so what modifications and how are you applying them to the keystore?

Question: Is there a known diff in the upgraded jars in 20.0.1 that requires a special configuration, differing from the jars used in 20.0.0?

Hoping to solidify "a right way" to configure the container for FIPS compliance.

Thanks for all your work on the project.

**Comment by mposolda** [comment]
@daurrutia Thanks, could you please try to use latest nightly build of Keycloak? It is here: https://github.com/keycloak/keycloak/releases/tag/nightly . You can download latest distribution and use that one. I think that should help to fix the issue.

- Yes BCFIPS jars are placed inside `/opt/keycloak/providers` . You can take a look at latest instructions here for the container: https://github.com/keycloak/keycloak/blob/main/docs/fips.md#keycloak-server-in-fips-mode-in-the-container , which also points to my "example project" on how to use Keycloak + FIPS on the container.
 
-  Right now, we have some modifications done to default java.security when running in our testsuite. We're testing with custom file `kc.java.security`, which overrides few properties from java defaults. This is missing in the `docs/fips.md` instructions right now. You can start the server with something like:  `kc.sh start all-the-other-parameters-here-based-on-the-fips-instructions -J-Djava.security.properties=$KEYCLOAK_SOURCES/testsuite/integration-arquillian/servers/auth-server/common/fips/kc.ava.security`. I hope we can get rid of this, but not yet 100% sure, so it is recommended to start with those properties.

- Lots of FIPS related changes in latest Keycloak main since 20.0.0 or 20.0.1. Highly recommended to test with latest nightly build as I've mentioned above

**Comment by daurrutia** [comment]
Thanks for replying Marek. Tried with `nightly` this is what I found:

I _can_ get `nightly` to start with the security properties flag and the newer jar files in pom.xml:
- custom built container image based on `nightly`
- bc-fips-1.0.2.3.jar ---> /opt/keycloak/providers/
- bctls-fips-1.0.14.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.7.jar ---> /opt/keycloak/providers/
- bcfks keystore
-  start --fips-mode=enabled
- `-Djava.security.properties=/opt/keycloak/tools/kc.java.security` <-- from `tests/`

I _can_ also get `nightly` to start with the security properties flag _and the older jar files_:
- custom built container image based on `nightly`
- bc-fips-1.0.2.3.jar ---> /opt/keycloak/providers/
- bctls-fips-1.0.12.2.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.5.jar ---> /opt/keycloak/providers/
- bcfks keystore
-  start --fips-mode=enabled
- `-Djava.security.properties=/opt/keycloak/tools/kc.java.security` <-- from `tests/`

I can get `nightly` to start if I drop the security properties flag, _but_ theres an ugly _error_ when making curl requests or an openssl s_client request:
- custom built container image based on `nightly`
- bc-fips-1.0.2.3.jar ---> /opt/keycloak/providers/
- bctls-fips-1.0.14.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.7.jar ---> /opt/keycloak/providers/
- bcfks keystore
-  start --fips-mode=enabled
- No `-Djava.security.properties=` config
- `keycloak_1  | 2023-02-14 21:51:56,019 INFO  [org.bouncycastle.jsse.provider.ProvTlsServer] (vert.x-eventloop-thread-6) Server raised fatal(2) handshake_failure(40) alert: Failed to process record: org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40); No selectable cipher suite`
- `keycloak_1  |   at org.bouncycastle.tls.AbstractTlsServer.getSelectedCipherSuite(AbstractTlsServer.java:453)`

---

I _cannot_ get `20.0.3` to start _with or without_ the security properties flag:
- custom built container image based on `20.0.3`
- bc-fips-1.0.2.3.jar ---> /opt/keycloak/providers/
- bctls-fips-1.0.14.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.7.jar ---> /opt/keycloak/providers/
- bcfks keystore
-  start --fips-mode=enabled
- `keycloak_1  | 2023-02-14 21:59:44,145 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Unable to start HTTP server`
- `keycloak_1  | Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'int org.bouncycastle.asn1.ASN1Integer.intValueExact()'`

---

I _can_ get `20.0.0` to start with the security properties flag (and the older jar files):
- custom built container image based on `nightly`
- bc-fips-1.0.2.3.jar ---> /opt/keycloak/providers/
- bctls-fips-1.0.12.2.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.5.jar ---> /opt/keycloak/providers/
- bcfks keystore
-  start --fips-mode=enabled
- `-Djava.security.properties=/opt/keycloak/tools/kc.java.security` <-- from `tests/`

I can also get `20.0.0` to start if I drop the security properties flag, _but_ there is the ugly _error_ when making curl requests or an openssl s_client request again.

**Comment by mposolda** [comment]
Thanks for the details!

The most important for those is only `nightly` stuff as this is what would be used in Keycloak 21. I think we will be able to have this working fine even without a requirement to using custom `kc.java.security` file. So I am leaving this open for now. Will update you later once the requirement of custom `kc.java.security` is removed.

**Comment by mposolda** [comment]
@daurrutia Do you please have a chance to re-test with latest nightly build? It should work fine even if you don't provide the `kc.java.security` file. The only thing, which won't work without that file, is SAML. So custom security file is still needed but just in case you need to use SAML clients or SAML identity providers. In this case, you can add only this single line with this option to your `kc.java.security` -> `fips.provider.7=XMLDSig`

**Comment by mposolda** [comment]
@daurrutia This should be fixed already, so I am resolving. Please re-open if you manage to test with latest Keycloak weekly and you still see the issue without providing your custom `kc.java.security`. Thanks!

**Comment by daurrutia** [comment]
Tested and working 

I can get `nightly` to start if I drop the security properties flag, _no errors_ when making curl requests or an openssl s_client request:

- custom built container image based on `nightly`
- bc-fips-1.0.2.3.jar ---> /opt/keycloak/providers/
- bctls-fips-1.0.14.jar ---> /opt/keycloak/providers/
- bcpkix-fips-1.0.7.jar ---> /opt/keycloak/providers/
- `bcfks` keystore
- start `--fips-mode=enabled`
- No `-Djava.security.properties= config`

Thanks for working on this.

**Comment by mposolda** [comment]
@daurrutia Cool, Thanks for doublecheck!
