### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.UserSessionProviderOfflineTest#testOnClientRemoved

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#17072]
## org.keycloak.testsuite.model.UserSessionProviderOfflineTest#testOnClientRemoved
[Keycloak CI - Base IT (6)](https://github.com/keycloak/keycloak/actions/runs/4148518129/jobs/7176652751) / [Pull Request #16876](https://github.com/keycloak/keycloak/pull/16876)

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.keycloak.testsuite.model.UserSessionProviderOfflineTest.assertSession(UserSessionProviderOfflineTest.java:454)
...
```

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.keycloak.testsuite.model.UserSessionProviderOfflineTest.assertSession(UserSessionProviderOfflineTest.java:454)
...
```

**Comment by stianst** [comment]
Closing as out of date since it's only happened once for quite some time ago.
