### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.UserSessionProviderTest#testRestartSession

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#17071]
## org.keycloak.testsuite.model.UserSessionProviderTest#testRestartSession
[Keycloak CI - Base IT (6)](https://github.com/keycloak/keycloak/actions/runs/4146413917/jobs/7172154915) / [Pull Request #16876](https://github.com/keycloak/keycloak/pull/16876)

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.keycloak.testsuite.model.UserSessionProviderTest.assertSession(UserSessionProviderTest.java:844)
...
```

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.keycloak.testsuite.model.UserSessionProviderTest.assertSession(UserSessionProviderTest.java:844)
...
```

**Comment by stianst** [comment]
Closing as out of date since it's only happened once for quite some time ago.
