### ISSUE TITLE
GitHub API rate limit exceeded when downloading Firefox driver

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#17075]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

We're frequently getting rate limited by GitHub when downloading the Firefox driver. The problem here is that Drone is downloading the Firefox driver through GitHub releases, which seems to be very frequent since we get the rate limit issue.

Most likely fix to this issue is to cache the Firefox driver.

```
2023-02-13T20:31:40.6809614Z -- [ERROR] org.keycloak.testsuite.webauthn.registration.passwordless.PwdLessUserVerRegTest.preferredNoVerification  Time elapsed: 0.039 s  <<< ERROR!
2023-02-13T20:31:40.6809851Z -- java.lang.RuntimeException: Could not create statement
2023-02-13T20:31:40.6810167Z -- 	at org.jboss.arquillian.junit.Arquillian.methodBlock(Arquillian.java:313)
2023-02-13T20:31:40.6810512Z -- 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2023-02-13T20:31:40.6810798Z -- 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2023-02-13T20:31:40.6811154Z -- 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2023-02-13T20:31:40.6811505Z -- 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2023-02-13T20:31:40.6811784Z -- 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-02-13T20:31:40.6812058Z -- 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-02-13T20:31:40.6812446Z -- 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-02-13T20:31:40.6812734Z -- 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-02-13T20:31:40.6813008Z -- 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-02-13T20:31:40.6813376Z -- 	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:166)
2023-02-13T20:31:40.6813697Z -- 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:350)
2023-02-13T20:31:40.6814053Z -- 	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
2023-02-13T20:31:40.6814350Z -- 	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:177)
2023-02-13T20:31:40.6814637Z -- 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
2023-02-13T20:31:40.6814882Z -- 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2023-02-13T20:31:40.6815155Z -- 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-02-13T20:31:40.6815418Z -- 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-02-13T20:31:40.6815700Z -- 	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
2023-02-13T20:31:40.6816054Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
2023-02-13T20:31:40.6816470Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:302)
2023-02-13T20:31:40.6816854Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
2023-02-13T20:31:40.6817210Z -- 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
2023-02-13T20:31:40.6817601Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
2023-02-13T20:31:40.6817947Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
2023-02-13T20:31:40.6818268Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
2023-02-13T20:31:40.6818591Z -- 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
2023-02-13T20:31:40.6819115Z -- Caused by: org.jboss.arquillian.graphene.enricher.exception.PageObjectInitializationException: Can not instantiate Page Object 
2023-02-13T20:31:40.6819408Z -- class org.keycloak.testsuite.auth.page.AuthServerContextRoot
2023-02-13T20:31:40.6819539Z --  declared in: 
2023-02-13T20:31:40.6819946Z -- org.keycloak.testsuite.webauthn.registration.passwordless.PwdLessUserVerRegTest
2023-02-13T20:31:40.6820047Z -- 
2023-02-13T20:31:40.6820488Z -- 	at org.jboss.arquillian.graphene.enricher.PageObjectEnricher.createPage(PageObjectEnricher.java:115)
2023-02-13T20:31:40.6820901Z -- 	at org.jboss.arquillian.graphene.enricher.PageObjectEnricher.enrich(PageObjectEnricher.java:55)
2023-02-13T20:31:40.6821307Z -- 	at org.jboss.arquillian.graphene.enricher.GrapheneEnricher.enrich(GrapheneEnricher.java:55)
2023-02-13T20:31:40.6821660Z -- 	at org.jboss.arquillian.junit.RulesEnricher.enrichInstances(RulesEnricher.java:85)
2023-02-13T20:31:40.6822064Z -- 	at org.jboss.arquillian.junit.RulesEnricher.enrichRulesAndTestInstance(RulesEnricher.java:66)
2023-02-13T20:31:40.6822388Z -- 	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
2023-02-13T20:31:40.6822821Z -- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-13T20:31:40.6823084Z -- 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-02-13T20:31:40.6823409Z -- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
2023-02-13T20:31:40.6823813Z -- 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
2023-02-13T20:31:40.6824176Z -- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
2023-02-13T20:31:40.6824722Z -- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
2023-02-13T20:31:40.6825309Z -- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:114)
2023-02-13T20:31:40.6825632Z -- 	at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
2023-02-13T20:31:40.6826065Z -- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-13T20:31:40.6826413Z -- 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-02-13T20:31:40.6826744Z -- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
2023-02-13T20:31:40.6827157Z -- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
2023-02-13T20:31:40.6827593Z -- 	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
2023-02-13T20:31:40.6827915Z -- 	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
2023-02-13T20:31:40.6828350Z -- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-13T20:31:40.6828606Z -- 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-02-13T20:31:40.6828930Z -- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
2023-02-13T20:31:40.6829288Z -- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
2023-02-13T20:31:40.6829720Z -- 	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
2023-02-13T20:31:40.6830032Z -- 	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
2023-02-13T20:31:40.6830459Z -- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-13T20:31:40.6830709Z -- 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-02-13T20:31:40.6831027Z -- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
2023-02-13T20:31:40.6831391Z -- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
2023-02-13T20:31:40.6831810Z -- 	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
2023-02-13T20:31:40.6832121Z -- 	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
2023-02-13T20:31:40.6832549Z -- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-13T20:31:40.6832799Z -- 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-02-13T20:31:40.6833120Z -- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
2023-02-13T20:31:40.6833475Z -- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
2023-02-13T20:31:40.6833782Z -- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
2023-02-13T20:31:40.6834093Z -- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
2023-02-13T20:31:40.6834561Z -- 	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.fireCustomLifecycle(EventTestRunnerAdaptor.java:159)
2023-02-13T20:31:40.6834874Z -- 	at org.jboss.arquillian.junit.Arquillian.methodBlock(Arquillian.java:260)
2023-02-13T20:31:40.6835027Z -- 	... 26 more
2023-02-13T20:31:40.6835486Z -- Caused by: java.lang.IllegalStateException: Something bad happened when Drone was trying to download and prepare a binary. For more information see the cause.
2023-02-13T20:31:40.6836057Z -- 	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.checkAndSetBinary(AbstractBinaryHandler.java:63)
2023-02-13T20:31:40.6836583Z -- 	at org.jboss.arquillian.drone.webdriver.factory.FirefoxDriverFactory.getCapabilities(FirefoxDriverFactory.java:107)
2023-02-13T20:31:40.6837081Z -- 	at org.jboss.arquillian.drone.webdriver.factory.FirefoxDriverFactory.createInstance(FirefoxDriverFactory.java:74)
2023-02-13T20:31:40.6837565Z -- 	at org.jboss.arquillian.drone.webdriver.factory.FirefoxDriverFactory.createInstance(FirefoxDriverFactory.java:40)
2023-02-13T20:31:40.6838027Z -- 	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
2023-02-13T20:31:40.6838486Z -- 	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
2023-02-13T20:31:40.6838925Z -- 	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
2023-02-13T20:31:40.6839297Z -- 	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
2023-02-13T20:31:40.6839831Z -- 	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:88)
2023-02-13T20:31:40.6840121Z -- 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-13T20:31:40.6840489Z -- 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-13T20:31:40.6840835Z -- 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-13T20:31:40.6841056Z -- 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-02-13T20:31:40.6841626Z -- Caused by: java.lang.IllegalStateException: GitHub API rate limit exceeded. To get the information about the latest release you need to wait till the rate limit is reset which will be: Mon Feb 13 20:32:05 UTC 2023.
2023-02-13T20:31:40.6842203Z -- 	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.GitHubSource.processEmptyResponse(GitHubSource.java:110)
2023-02-13T20:31:40.6842785Z -- 	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.GitHubSource.processResponsePayload(GitHubSource.java:92)
2023-02-13T20:31:40.6843321Z -- 	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.GitHubSource.getLatestRelease(GitHubSource.java:79)
2023-02-13T20:31:40.6843895Z -- 	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.downloadAndPrepare(AbstractBinaryHandler.java:175)
2023-02-13T20:31:40.6844456Z -- 	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.checkAndSetBinary(AbstractBinaryHandler.java:61)
2023-02-13T20:31:40.6844577Z -- 	... 12 more
```

### Version

main

### Expected behavior

Downloading of Firefox driver doesn't cause rate limiting issues

### Actual behavior

Downloading of Firefox driver fails frequently due to GitHub rate limiting

### How to Reproduce?

Example run that failed:
https://github.com/keycloak/keycloak/actions/runs/4167491983/jobs/7213276995

**Comment by stianst** [comment]
From the [Drone documentation](https://arquillian.org/arquillian-extension-drone/#_github_rate_limit):

![image](https://user-images.githubusercontent.com/2271511/218690045-7eadbfce-63dd-4794-9c12-16d95a08c7dc.png)

**Comment by miquelsi** [comment]
@stianst we already have this in https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml#L28-L29

I think we might be reaching even the limit for authenticated requests.

**Comment by stianst** [comment]
> @stianst we already have this in https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/resources/arquillian.xml#L28-L29
> 
> I think we might be reaching even the limit for authenticated requests.

I don't think those properties are initialized, they are probably just empty strings

**Comment by stianst** [comment]
Happened during testing of 21:
https://github.com/keycloak/keycloak/actions/runs/4250388170/jobs/7391525338

**Comment by stianst** [comment]
and here:
https://github.com/keycloak/keycloak/actions/runs/4237633096/jobs/7363928329

**Comment by ahus1** [comment]
To fix this, one should cache the following folders:

```
.arquillian/drone/firefox
.arquillian/drone/gh_cache
``` 

The second directory contains the information from the last fetch, which is used for checking if the contents are still up to date (and which avoid decrementing the API limit). 

Sample contents: 

```
{"lastModified":"Wed, 08 Feb 2023 11:56:05 GMT","asset":{"version":"v0.32.2","url":"https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux64.tar.gz"}}
``` 

At the moment we're running those tests on Chrome only, so it seems no longer be necessary, or do we want to run the tests with Firefox as well?

Passing on GitHub username and token doesn't work with the standard GitHub action GITHUB_TOKEN mechanism, as that one is passed on without a username, and uses only the token. AFAIK this is not supported by Drone [at the moment](https://github.com/arquillian/arquillian-extension-drone/blob/49c3824a9ca3a456e28fd887eb8d959152cd183a/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSource.java#L227-L230). Didn't open an issue for that, as I am not sure if we want to use it.

**Comment by stianst** [comment]
I think we're not using Firefox anymore? In either case apparently the Firefox (Geckodriver) driver is already installed on the runners:
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#browsers-and-drivers
