### ISSUE TITLE
Flaky test: org.keycloak.testsuite.forms.LoginTest#loginRememberMeExpiredIdle

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#17074]
## org.keycloak.testsuite.forms.LoginTest#loginRememberMeExpiredIdle
[Keycloak CI - FIPS IT (non-strict)](https://github.com/keycloak/keycloak/actions/runs/4169711760/jobs/7218051901) / [Pull Request #16876](https://github.com/keycloak/keycloak/pull/16876)

```
java.lang.AssertionError: Expected LoginPage but was Keycloak Account Management (https://localhost:8543/auth/realms/test/account)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:49)
	at jdk.internal.reflect.GeneratedMethodAccessor574.invoke(Unknown Source)
...
```

```
java.lang.AssertionError: Expected LoginPage but was Keycloak Account Management (https://localhost:8543/auth/realms/test/account)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:49)
	at jdk.internal.reflect.GeneratedMethodAccessor574.invoke(Unknown Source)
...
```

**Comment by stianst** [comment]
This was most likely caused by the PR itself, so closing.
