### ISSUE TITLE
Acquisition timeout while waiting for new connection

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#17161]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Originally reported as part of #16448.

Tracker of Agroal issue: https://issues.redhat.com/browse/AG-201

Occassionally, the following exception can be seen upon obtaining new connection in Keycloak:

```
2023-01-13 07:20:55,243 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Acquisition timeout while waiting for new connection
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:320)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:272)
	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:68)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:165)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:66)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:296)
	... 23 more
```

This is caused by Agroal issue AG-201.

### Version

20, main

### Expected behavior

no exception

### Actual behavior

exception

### How to Reproduce?

See #16448

**Comment by sschu** [comment]
I also copied the issue to Quarkus as suggested by @stianst (https://github.com/quarkusio/quarkus/issues/31246)

**Comment by stianst** [comment]
https://issues.redhat.com/browse/AG-201 is fixed in Agroal 1.17 and 2.1. For main/22 we will get this when upgrading to Quarkus 3.x, but for 21 we need to override the Agroal version to 1.17.

**Comment by vmuzikar** [comment]
I'm not able to link the PR to this issue for some reason.
The fix is here: https://github.com/keycloak/keycloak/pull/17642

**Comment by gaurang-ingale** [comment]
What is the solution for this when using docker? Using any image available on quay.io does not have this fix. Especially the tag 21.0 (fix merged branch) should have fixed it.

**Comment by sschu** [comment]
Why do you think that the fixed version is not in there?

**Comment by gaurang-ingale** [comment]
> Why do you think that the fixed version is not in there?

Thanks for the reply. Even though the error message was the same as in this Github issue, the problem turned out to not be in the docker image itself, but in my environment. The host's Linux kernel was causing problems with the docker installation and docker networks were not working as expected.

**Comment by steffenstolze** [comment]
@gaurang-ingale Could you provide some more details - I'm also deploying Keycloak as a container on AWS ECS Fargate and see the same warnings. Thanks!

**Comment by gaurang-ingale** [comment]
> @gaurang-ingale Could you provide some more details - I'm also deploying Keycloak as a container on AWS ECS Fargate and see the same warnings. Thanks!

Hey! 

In my case, I have a server running on Ubuntu Server 22.04 LTS as the host OS and was previously using Docker from the snap repository. After an OS upgrade, the snap Repo version of docker was having some issues so I tried switching to the official docker repository. 

The problem at the end was one with compatibility between docker and the host's kernel version, which is why I ended up needing to reboot into one of the previous kernel versions but stayed with the official docker repository. I am afraid I don't remember the exact version numbers anymore, but a later kernel upgrade fixed it.

**Comment by vksaamy** [comment]
My Keycloak version is 22.0.1 and deployed in containerized environment. I am getting acquisition timeout intermittently. The other workloads don't have this issue and connect through MySQL router to MySQL DB. I already set initial, min and max pool sizes through environment variables in the Kubernetes deployment manifest.

**Comment by nicksuslov** [comment]
Can't find fix for 24.0, same error

**Comment by paul-civitas** [comment]
Hello I encountered the same issue in keycloak 24. Upgrading to keycloak 25 resolved this issue.

**Comment by samyvenkat** [comment]
This issue is quite erratic and need to monitor whether the upgrade really fixes the issue.

**Comment by paul-civitas** [comment]
I was able to reproduce it consistently with loadtesting on verson 24, and it seems fully resolved on version 25 from my tests.

I hope you're also seeing a resolution!

**Comment by samyvenkat** [comment]
Thanks. Let me update and check.

**Comment by paul-civitas** [comment]
@samyvenkat also what does your database connections look like? Keycloak 25 has some nice connection pool settings that can prevent database connection exhaustion. I think database connections being exhausted can lead to issues, although I'm not sure exactly if it would be this same issue.

**Comment by samyvenkat** [comment]
The DB connection details have been configured with the environment variables as below:
- name: KC_DB
          value: {{ quote .Values.keycloak.env.kcDb }}          
        - name: KC_DB_POOL_INITIAL_SIZE
          value: 20
        - name: KC_DB_POOL_MIN_SIZE
          value: 20
        - name: KC_DB_POOL_MAX_SIZE
          value: 20
        - name: KC_METRICS_ENABLED
          value: {{ quote .Values.keycloak.env.kcMetricsEnabled }}
        - name: KC_HEALTH_ENABLED
          value: {{ quote .Values.keycloak.env.kcHealthEnabled }}
        - name: KC_DB_URL
          value: {{ quote .Values.keycloak.env.kcDbUrl }}
        - name: KC_DB_USERNAME
        - name: KC_DB_PASSWORD

The DB acquisition timeout is not happening always.

**Comment by samyvenkat** [comment]
Yes. During load testing no issue but when I want to deploy for some changes, the PODs can't come up with acquisition timeout error though there was no change in DB configuration. The error is quite erratic and not predictable. Sometimes our deployment got stuck and have to try few time deploying before the pod can come up successfully. When I list the PODs sometimes the POD have restarted with logs as acquisition timeout.

**Comment by vksaamy** [comment]
Added QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT as 10s as an environment variable in my Kubernetes deployment though I have been trying various fixes for long time. In my case it was Keycloak version 25.0.6 and using Quarkus framework.

The earlier versions were using Jboss and this fix will not be applicable if the issue exists in older versions.

**Comment by kkamkou** [comment]
That is `QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT`, set it to `100s`. (hello if u came from a search engine)

**Comment by vksaamy** [comment]
Sorry for the typo..corrected..
