### ISSUE TITLE
Keycloak 21.0.0 startup fails with JDK 19

### ISSUE THREAD

**Issue by heikkilamarko** [keycloak/keycloak#17264]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

Keycloak 21.0.0 startup fails on Windows Server 2019. 

Log:

```
2023-02-23 21:48:30,193 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2023-02-23 21:48:30,355 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-02-23 21:48:30,368 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-02-23 21:48:32,244 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:758)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:504)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:485)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:78)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:357)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:774)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:742)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:406)
	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
	at org.jgroups.stack.ProtocolStack.lambda$initComponents$7(ProtocolStack.java:861)
	at org.jgroups.util.Util.forAllComponents(Util.java:3368)
	at org.jgroups.stack.ProtocolStack.initComponents(ProtocolStack.java:839)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:795)
	at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:438)
	at org.jgroups.JChannel.init(JChannel.java:899)
	at org.jgroups.JChannel.<init>(JChannel.java:123)
	at org.jgroups.JChannel.<init>(JChannel.java:113)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:756)
	... 29 more

2023-02-23 21:48:32,385 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-02-23 21:48:32,386 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
2023-02-23 21:48:32,386 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: ISPN000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml
2023-02-23 21:48:32,386 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.commons.CacheConfigurationException: ISPN000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml
2023-02-23 21:48:32,387 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml
2023-02-23 21:48:32,387 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
2023-02-23 21:48:32,387 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

Keycloak 21.0.0
JDK 19.0.2

### Expected behavior

Keycloak starts without fatal errors.

### Actual behavior

Keycloak startup fails.

### How to Reproduce?

Try to run Keycloak 21.0.0 on Windows Server 2019.

### Anything else?

Keycloak 20.0.5. doesn't have this problem.

**Comment by ngerstle** [comment]
I'm seeing a similar error when testing an upgrade from 20.0.03 (working) to 21.0.0 in https://github.com/NixOS/nixpkgs/pull/219010 . 
This is testing on `Linux $host 6.2.0 #1-NixOS SMP PREEMPT_DYNAMIC Sun Feb 19 22:24:22 UTC 2023 x86_64 GNU/Linux`

**Comment by Jeroen-Van-Loocke** [comment]
I also have the exact same issue on Windows Server 2019 (1809).

**Comment by TimmiORG** [comment]
KC 21.0.1 -> https://github.com/keycloak/keycloak/issues/17248
Has fixed the issue for me.

The workaround was also working for me:
`Another workaround may be, if you have access to the database, to execute this statement:
update realm set admin_theme = 'keycloak' where admin_theme is null`

**Comment by Jeroen-Van-Loocke** [comment]
@TimmiORG Have tried this but it does not fix this issue.
This issue seems to be something very different and has nothing to do with an empty theme but rather seems to be an issue with the new way the Metrics endpoint is implemented.

**Comment by ngerstle** [comment]
I've retested with 21.0.1; and still see the same issue. attempting to set a local cache (with no success).
The configuration is pretty basic, run via s systemd unit.

[systemd](https://github.com/keycloak/keycloak/files/10889423/keycloak-systemd.txt)
[keycloak configuration](https://github.com/keycloak/keycloak/files/10889420/keycloak-config.txt)
[error log](https://github.com/keycloak/keycloak/files/10889422/keycloak-errors.txt)

**Comment by mhajas** [comment]
I was able to reproduce this when using the command:
```
./kc.sh start --hostname=localhost --http-enabled=true
```

when using JDK 19

**Comment by mhajas** [comment]
It seems it was reported also for ISPN and was fixed by adding `--preview-enabled` to java options: 
https://issues.redhat.com/browse/ISPN-14158

**Comment by mhajas** [comment]
Looking into this more, it seems this was already fixed in the newer JGroups version 
https://issues.redhat.com/browse/JGRP-2664

This issue should be fixed by https://github.com/keycloak/keycloak/pull/19402
