### ISSUE TITLE
Logout error with oidc Identity Provider configured

### ISSUE THREAD

**Issue by Akireken** [keycloak/keycloak#17261]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

I have configure an external oidc identity provider for my keycloak instance. The IdP is a FranceConnect, an french idp solution for all french citizen : https://franceconnect.gouv.fr/.

In order to initiate a logout, oidc defines that a id_token_hint need to be passed to the IdP. 

1. During logout, Keycloak try to refresh token if it's expired. 
2. FranceConnect doesn't support refresh_token and generate a response in html. 
3. This cause a parse exception
4. Logout process is completely stop even on Keycloak 

The error occurs exactly here [OIDCIdentityProvider.getIDTokenForLogout method](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L252).

Stacktrace of the error : 
```
2023-02-23 16:58:22,813 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
<html lang="fr" data-fr-scheme="light">
<head>
  <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="theme-color" content="#000091">
<link rel="apple-touch-icon" href="/favicon/apple-touch-icon.png?v=9c5b073e0">
<link rel="icon" href="/favicon/favicon.svg?v=9c5b073e0" type="image/svg+xml">
<link rel="shortcut icon" href="/favicon/favicon.ico?v=9c5b073e0" type="image/x-icon">
<link rel="manifest" href="/favicon/"[truncated 3793 chars]; line: 1, column: 2]
	at org.keycloak.broker.oidc.OIDCIdentityProvider.getIDTokenForLogout(OIDCIdentityProvider.java:262)
	at org.keycloak.broker.oidc.OIDCIdentityProvider.keycloakInitiatedBrowserLogout(OIDCIdentityProvider.java:168)
	at org.keycloak.services.managers.AuthenticationManager.browserLogout(AuthenticationManager.java:652)
	at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.initiateBrowserLogout(LogoutEndpoint.java:767)
	at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.doBrowserLogout(LogoutEndpoint.java:464)
	at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logout(LogoutEndpoint.java:318)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
<html lang="fr" data-fr-scheme="light">
<head>
  <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="theme-color" content="#000091">
<link rel="apple-touch-icon" href="/favicon/apple-touch-icon.png?v=9c5b073e0">
<link rel="icon" href="/favicon/favicon.svg?v=9c5b073e0" type="image/svg+xml">
<link rel="shortcut icon" href="/favicon/favicon.ico?v=9c5b073e0" type="image/x-icon">
<link rel="manifest" href="/favicon/"[truncated 3793 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:75)
	at org.keycloak.broker.oidc.OIDCIdentityProvider.getIDTokenForLogout(OIDCIdentityProvider.java:260)
	... 53 more

```

### Version

20.0.3

### Expected behavior

In case of an external oidc external identity provider configured, don't refresh token in case of logout or fallback actual id_token if error of parsing occured.

### Actual behavior

In case of an external oidc external identity provider configured, logout do a refresh token if it's expired. If error occured during parsing of response, logout of Keycloak and external IdP completely stop.

### How to Reproduce?

1. Configure FranceConnect as external oidc IdentityProvider.
2. Connect with FranceConnect.
3. Try to logout on keycloak after few minutes in a browser with url like <keycloak_url>/realms/<realm>/protocol/openid-connect/logout?id_token_hint=<id_token_hint>&post_logout_redirect_uri=<redirect_uri>
4. Screen with message "We are sorry...An internal server error has occurred" appeared.
FranceConnect partner account is not accessible for everyone.

### Anything else?

Same issue open previously with same conclusion, but never finished : https://issues.redhat.com/browse/KEYCLOAK-7209
Oidc specification that define the keycloak rules : https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

I'm ok to work on this issues. Already try the fix in local, it's work fine.

**Comment by sschu** [comment]
AFAIK there is an extension for that: https://github.com/InseeFr/Keycloak-FranceConnect

**Comment by Akireken** [comment]
Indeed, the extension add a work around but we choice to not use it because : 
- it will couple us with an external library which mean be subject to incompatibility (right now, the module is not compatible with our KC version since couple of month)
- we use a [terraform provider](https://registry.terraform.io/providers/mrparkers/keycloak/) for fully automated the keycloak configuration on all our environments (2 different cloud providers, multiple tenant on each) and the extension doesn't seem compatible

Moreover, the demand is legitime regardless the oidc specifications.

**Comment by mposolda** [comment]
duplicates #10164
So I am closing this. Please comment on that issue for further questions/concerns/suggestions regarding this.
