### ISSUE TITLE
When upgrading from v20.0.2 to v21.0.0 I get a NPE on Theme

### ISSUE THREAD

**Issue by kevin-cuijpers** [keycloak/keycloak#17313]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

After trying to start the application I got the error described on: https://github.com/keycloak/keycloak/issues/17248

So I executed following command on the db as suggested:
`update realm set admin_theme = 'keycloak' where admin_theme is null`

This worked and now my server starts, but when I log in on the admin section, I get an error:
2023-02-27 15:48:30,310 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: 
java.lang.NullPointerException: Cannot invoke "org.keycloak.theme.Theme.getImportName()" because "theme" is null
	at org.keycloak.theme.DefaultThemeManager.loadTheme(DefaultThemeManager.java:119)
	at org.keycloak.theme.DefaultThemeManager.getTheme(DefaultThemeManager.java:68)
	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.setThemes(ServerInfoAdminResource.java:182)
	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.getInfo(ServerInfoAdminResource.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Looking at the code I see that findTheme(parentName, type); can return null and there is no nullpointer check before theme.getImportName()

Can this also be corrected in v21.0.1?
 

### Version

21.0.0

### Expected behavior

After the upgrade you should be able to log into the admin console and manage your realms, clients, identity providers...

They are visible in the dropdown to the left, but on the right the error message is shown due to the theme not being found.

### Actual behavior

![error-in-admin](https://user-images.githubusercontent.com/68843812/221610741-cd567073-9554-447e-99d3-3df10b3aafaf.png)
![Source_code](https://user-images.githubusercontent.com/68843812/221610758-a2c1dd56-7203-4497-a46c-7bbe69cb9c51.png)

### How to Reproduce?

```
    private Theme findTheme(String name, Theme.Type type) {
        for (ThemeProvider p : getProviders()) {
            if (p.hasTheme(name, type)) {
                try {
                    return p.getTheme(name, type);
                } catch (IOException e) {
                    log.errorv(e, p.getClass() + " failed to load theme, type={0}, name={1}", type, name);
                }
            }
        }
        return null;
    }
```
So maybe getProviders() is empty or p.getTheme(name, type) returns null

**Comment by kevin-cuijpers** [comment]
I have now also tried to use a blank schema and create a new admin account and setup. It also produces the same error so this can be used as reproduction scenario:

- Install the new version
- create admin account on localhost:8080/auth/
- Log in with this admin account

**Comment by tarmotoimetaja** [comment]
Hi.
I got the same behavior with upgrade from 20.0.3 to 21.0.0.
DB workaround (descibed here: https://github.com/keycloak/keycloak/issues/17248) does not help. 
Made a test to create clean realm using Rest API's. No result.

**Comment by mposolda** [comment]
duplicates #17248 
So closing this as duplicate issue. Please continue discussion in the duplicated issue if you have further questions/concerns/feedback regarding this.

**Comment by gbatalski** [comment]
These are not the same issues

**Comment by kevin-cuijpers** [comment]
Please reopen because this is not a duplicate. I created another issue because the workaround there fixed only https://github.com/keycloak/keycloak/issues/17248 and NOT my issue I reported where Keycloak can be started, but the admin section is not working because of a NPE in the code I mentionned above.

**Comment by thomasdarimont** [comment]
@mposolda I can confirm this issue:
```
dev-acme-keycloak-1               | 07:31:22 ERROR traceId=, parentId=, spanId=, sampled= [or.ke.se.er.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.theme.Theme.getImportName()" because "theme" is null
dev-acme-keycloak-1               | 	at org.keycloak.theme.DefaultThemeManager.loadTheme(DefaultThemeManager.java:119)
dev-acme-keycloak-1               | 	at org.keycloak.theme.DefaultThemeManager.getTheme(DefaultThemeManager.java:68)
dev-acme-keycloak-1               | 	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.setThemes(ServerInfoAdminResource.java:182)
dev-acme-keycloak-1               | 	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.getInfo(ServerInfoAdminResource.java:103)
dev-acme-keycloak-1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dev-acme-keycloak-1               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
dev-acme-keycloak-1               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dev-acme-keycloak-1               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
dev-acme-keycloak-1               | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
dev-acme-keycloak-1               | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
dev-acme-keycloak-1               | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
dev-acme-keycloak-1               | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
dev-acme-keycloak-1               | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
dev-acme-keycloak-1               | 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
dev-acme-keycloak-1               | 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
dev-acme-keycloak-1               | 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
dev-acme-keycloak-1               | 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
dev-acme-keycloak-1               | 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
dev-acme-keycloak-1               | 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
dev-acme-keycloak-1               | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
dev-acme-keycloak-1               | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
dev-acme-keycloak-1               | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
dev-acme-keycloak-1               | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
dev-acme-keycloak-1               | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
dev-acme-keycloak-1               | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
dev-acme-keycloak-1               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

![image](https://user-images.githubusercontent.com/314690/221784602-8cb57f99-e5da-492c-9ca2-c86e26a4d2b4.png)

[theme = findTheme(parentName, type)](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/theme/DefaultThemeManager.java#L116) returns null.

**Comment by thomasdarimont** [comment]
Side note: I think we need a way to explicitly communicate compatibility with Keycloak versions in extensions.

**Comment by thomasdarimont** [comment]
In this case I'd avoid breaking the admin-console, but still tell the user that something is off.
Perhaps we should at least log a warn message in case if the theme is null and return? 
This would at least give some hints to the user that the old-theme is gone and keep the new admin-console working, with
the side-effect that the "extended" functionality that the extension provided to the old admin-console will be unavailable.

**Comment by tarmotoimetaja** [comment]
In my case I'm using default themes "keycloak" and "keycloak.v2".

**Comment by mposolda** [comment]
Thanks everyone for clarifying and re-opening this!

@thomasdarimont +1, I've did pretty much what you suggested and log the warning.

We were already doing that when some non-existing theme is set, but the theme does not exists. For example when you set theme called `address` in your deployment, but you forget to deploy that theme when you migrate to different environment (or upgrading).

**Comment by mposolda** [comment]
Slightly updated PR as per to what we discussed with @stianst .
Latest PR: https://github.com/keycloak/keycloak/pull/17350
Docs PR: https://github.com/keycloak/keycloak-documentation/pull/1788

The "incorrect themes" (those which use old admin console as parent or import) are displayed in server.log and there is fallback to default theme when those themes are used. But they are not shown in the response from "server-info" REST endpoint, so effectively not shown in the admin console and admin cannot choose and manually set those invalid themes.
