### ISSUE TITLE
Error updating old version (Keycloak 8) to Keycloak 20. NPE thrown due the realm.getDefaultRole()

### ISSUE THREAD

**Issue by mrodrigo-nexplore** [keycloak/keycloak#17312]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

I am trying to upgrade from version 8.3.0 (standalone) to version 20. For some reason I can't get it, I have been able to install one from scratch with the same configuration without any problem. But when it comes to upgrade an old one I can't do it, I have tried multiple combinations.

I use an external postgresql database.

My current config:

    env:
    - name: KC_HTTP_RELATIVE_PATH
      value: "/auth"
    - name: KC_CACHE
      value: "ispn"
    - name: KC_CACHE_STACK 
      value: "kubernetes"
    - name: KC_PROXY 
      value: "edge"
    - name: KC_DB
      value: "postgres"
    - name: KC_DB_URL_HOST
      value: "mydb.postgres.database.azure.com"
    - name: KC_DB_URL_PORT
      value: "5432"
    - name: KC_DB_URL_DATABASE
      value: "keycloak"
    - name: KC_DB_USERNAME
      value: "keycloak@mydb.postgres.database.azure.com"
    - name: KC_DB_PASSWORD 
      value: "my password"
    - name: KC_METRICS_ENABLED
      value: "false"
    - name: KC_HEALTH_ENABLED 
      value: "true"
    - name: KEYCLOAK_ADMIN 
      value: "keycloak"
    - name: KEYCLOAK_ADMIN_PASSWORD 
      value: "my password"
    - name: JDBC_PARAMS
      value: "sslmode=require"
    - name: JAVA_OPTS_APPEND
      value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0 -Djava.awt.headless=true
        -Djgroups.dns.query=keycloak-headless
    - name: DB_VENDOR 
      value: "postgres"
    - name: DB_ADDR 
      value: "mydb.postgres.database.azure.com"
    - name: DB_PORT
      value: "5432"
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_USER
      value: "keycloak"
    - name: DB_USER
      value: "keycloak@mydb.postgres.database.azure.com"
    - name: DB_PASSWORD
      value: "my password"

### Version

20.0.3

### Expected behavior

Update

### Actual behavior

bash-4.4$ cd opt/keycloak/bin/
bash-4.4$ ./kc.sh --verbose start --http-enabled=true --http-port=8080 --hostname-strict=false --hostname-strict-https=false --spi-connections-jpa-legacy-migration-strategy=update --spi-events-listener-jboss-logging-success-level=info --spi-events-listener-jboss-logging-error-level=warn --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
Appending additional Java properties to JAVA_OPTS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0 -Djava.awt.headless=true -Djgroups.dns.query=keycloak-headless
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2023-02-27 14:59:55,829 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 41687ms
Server configuration updated and persisted. Run the following command to review the configuration:

        kc.sh show-config

Next time you run the server, just run:

        kc.sh start --optimized --http-enabled=true --http-port=8080 --hostname-strict=false --hostname-strict-https=false --spi-connections-jpa-legacy-migration-strategy=update --spi-events-listener-jboss-logging-success-level=info --spi-events-listener-jboss-logging-error-level=warn --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true

2023-02-27 15:00:03,240 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2023-02-27 15:00:03,321 WARN  [org.keycloak.protocol.oidc.OIDCLoginProtocolFactory] (main) Deprecated switch 'legacy-logout-redirect-uri' is enabled. Please try to disable it and update your clients to use OpenID Connect compliant way for RP-initiated logout.
2023-02-27 15:00:09,634 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-02-27 15:00:14,935 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-02-27 15:00:15,130 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-02-27 15:00:15,229 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-02-27 15:00:16,652 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
2023-02-27 15:00:17,227 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2023-02-27 15:00:19,851 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-0-49035|0] (1) [keycloak-0-49035]
2023-02-27 15:00:19,869 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-0-49035`, physical addresses are `[10.XXX.0.87:7800]`
2023-02-27 15:00:22,135 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: keycloak-0-49035, Site name: null
2023-02-27 15:00:30,046 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
2023-02-27 15:00:30,232 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2023-02-27 15:00:30,438 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-02-27 15:00:30,441 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.NullPointerException
        at org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:266)
        at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:418)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.hibernate.query.spi.StreamDecorator.forEach(StreamDecorator.java:153)
        at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
        at org.keycloak.migration.migrators.MigrateTo12_0_0.migrate(MigrateTo12_0_0.java:38)
        at org.keycloak.storage.datastore.LegacyMigrationManager.migrate(LegacyMigrationManager.java:133)
        at org.keycloak.migration.MigrationModelManager.migrate(MigrationModelManager.java:33)
        at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.migrateModel(LegacyJpaConnectionProviderFactory.java:219)
        at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.initSchema(LegacyJpaConnectionProviderFactory.java:213)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:260)
        at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.postInit(LegacyJpaConnectionProviderFactory.java:138)
        at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:104)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:42)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)

### How to Reproduce?

In my case I am trying to update it through helm, although I have also tried it manually.

**Comment by AlbertLacambraNexplore** [comment]
Apply sequential migrations not solve it? Exist a broken migration?

**Comment by mrodrigo-nexplore** [comment]
> From quickly looking, I can see that NullPointerException is thrown on this line of `CachedRealm` :
> 
> ```
> defaultRoleId = model.getDefaultRole().getId();
> ```
> 
> AFAIK the "default role" was added in some late version of Keycloak and that's likely the reason why historic versions like Keycloak 8 are throwing exceptions.
> 
> I am adding to Keycloak 22 for now as we may investigate this and eventually add null checks etc.

Thanks for your reply @mposolda , I am in the middle of a migration and I have the broken environment with impossibility to go back to 8.3.0 by changing the ingress version. Is there any manual way to fix it until version 22 arrives?

**Comment by AlbertLacambraNexplore** [comment]
There is a way how we can "manually" create the DefaultRole into the DB so that it finds it during the migration? Can you/someone provide information about which tables to fill up?

**Comment by pedroigor** [comment]
@AlbertLacambraNexplore Set a role `id` to `REALM.DEFAULT_ROLE` table column.

@mposolda If the workaround works, do we still want to provide a fix for migrating from 8 version ?

**Comment by mrodrigo-nexplore** [comment]
> @AlbertLacambraNexplore Set a role `id` to `REALM.DEFAULT_ROLE` table column.
> 
> @mposolda If the workaround works, do we still want to provide a fix for migrating from 8 version ?

We try that, but still failing

**Comment by rmartinc** [comment]
@mrodrigo-nexplore I think that you have a realm with no default role or a wrong ID in it. Can you please try to guess the realm doing a query similar to this one in the database? (There should be at least one realm with null role name.)

```
SELECT realm.ID,realm.NAME,realm.DEFAULT_ROLE,role.NAME
from REALM realm LEFT OUTER JOIN KEYCLOAK_ROLE role ON realm.ID = role.REALM_ID
AND realm.DEFAULT_ROLE = role.ID;
```

Once you know the realm (or realms) affected, check if it needs to be maintained (it's not a test or something similar that can be deleted). If needed check if you have a role called `default-roles-{realm_name}` and obtain this ID from the database (KEYCLOAK_ROLE table) and set it to the DEFAULT_ROLE value in the realm column. If the role doesn't exist you need to create it before in the table KEYCLOAK_ROLE which is more complicated.

Currently the default role cannot be removed but probably this was less restrictive in version 8.
