### ISSUE TITLE
Upgrading from 20.0.5 to 21.0.0 - ssl error connecting to postgresql 

### ISSUE THREAD

**Issue by aresabalo** [keycloak/keycloak#17320]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Upgrading from 20.0.4 to 21.0.0, error connecting to postgresql. 
Log:

2023-02-27 23:04:22,206 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': SSL error: Certificates do not conform to algorithm constraints
2023-02-27 23:04:22,206 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: SSL error: Certificates do not conform to algorithm constraints
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:43)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:584)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:168)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at org.postgresql.Driver.connect(Driver.java:291)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: Certificates do not conform to algorithm constraints
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
	... 20 more
Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1573)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1498)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1442)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 32 more
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA1withRSA
	at java.base/sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:237)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1569)
	... 35 more

### Version

21.0.0

### Expected behavior

Connect without problems

### Actual behavior

Connection error

### How to Reproduce?

Test connection in 21.0.0 using ssl with postgres

**Comment by brecht-vermeersch** [comment]
I'm having the same issue with Azure MySQL and Azure Postgresql

**Comment by brecht-vermeersch** [comment]
![Screenshot 2023-03-01 at 13 15 55](https://user-images.githubusercontent.com/20967950/222136759-445fc2ce-8c69-4036-bf6b-761baf97e336.png)
Probably has something to do with this

**Comment by aresabalo** [comment]
workaround for azure postgresql12 flexible:

KC_DB_URL="jdbc:postgresql://host/db?&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"

**Comment by brecht-vermeersch** [comment]
I fixed it in docker by removing SHA1 from jdk.certpath.disabledAlgorithms in /etc/crypto-policies/back-ends/java.config

**Comment by ThomasAunvik** [comment]
Same issue for me regarding the certificate on Azure Postgresql.

It would seem that the Azure Database for Postgresql - ***Single Server***, is using the SHA256 DigiCertGlobalRootG2, for anyone using Single Server would not have this problem.

But for Flexible server, is still using the old SHA1 Root Certificate, causing this error.

**Comment by koureasstavros** [comment]
I have similar situation with Debezium and JDBC while connecting to Azure Flexible Server.

But why Certificate of Flexible Server is older that Single's server? Flexible Server isn't newer resource? It supports up to Postgre v14 while Single Server is still on v10.5

**Comment by vishnuprakash92** [comment]
> jdk.certpath.disabledAlgorithm

Can you explain how you accomplished this? I am trying to deploy via Docker

**Comment by dominiktopp** [comment]
@brecht-vermeersch thanks!
@vishnuprakash92 we solved this with following steps in Dockerfile
```
FROM quay.io/keycloak/keycloak:22.0.0

USER root
RUN ["sed", "-i", "s/SHA1, //g", "/usr/share/crypto-policies/DEFAULT/java.txt"]
USER 1000
```

**Comment by saikotaa** [comment]
@koureasstavros facing similar issue. trying to connect debezium to azure flexible server. how did you fix this?

**Comment by blaaahJS** [comment]
> workaround for azure postgresql12 flexible:
> 
> KC_DB_URL="jdbc:postgresql://host/db?&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"

What is sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory doing? Does it lower security in any way?

**Comment by daxnet** [comment]
> > workaround for azure postgresql12 flexible:
> > KC_DB_URL="jdbc:postgresql://host/db?&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"
> 
> What is sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory doing? Does it lower security in any way?

By doing so worked for me, regarding security, Hmm... not sure, but I think if I put pgsql in a private subnet then it should be fine.

**Comment by hitokiri** [comment]
@aresabalo 
  KC_DB_URL: "jdbc:postgresql://host:5432/keycloak_db?&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"

this work for me, thanks @aresabalo 

> workaround for azure postgresql12 flexible:
> 
> KC_DB_URL="jdbc:postgresql://host/db?&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"

**Comment by zeezeewhy** [comment]
today I find out the way I followed the other [thread](https://github.com/keycloak/keycloak/issues/17606#issuecomment-1472289443), which suggested adding the global ca failed with `Failed to obtain JDBC connection`. Checked the cert: 

```
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 10897 bytes and written 859 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Protocol: TLSv1.3
```

I then attempted revert my image to official image and ssl=require and it works fine now.


Could anyone of you impacted verify?

**Comment by NicolasGonzalezFarabollini** [comment]
> today I find out the way I followed the other [thread](https://github.com/keycloak/keycloak/issues/17606#issuecomment-1472289443), which suggested adding the global ca, used to work but today failed with `Failed to obtain JDBC connection`. Checked the cert:
> 
> ```
> Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1
> Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
> Peer signing digest: SHA256
> Peer signature type: RSA-PSS
> Server Temp Key: ECDH, prime256v1, 256 bits
> ---
> SSL handshake has read 10897 bytes and written 859 bytes
> Verification: OK
> ---
> New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
> Protocol: TLSv1.3
> ```
> 
> I then attempted revert my image to official image and ssl=require and it works fine now.
> 
> Could anyone of you impacted verify?

Indeed, this fixed the issue. We today had the exact same issue on a prod app. 

Tried certification in many ways. Not sure what caused this. Maybe something changed on the Azure postgresql service.

Thanks for this.
