### ISSUE TITLE
exceptions when building kc 21.0.0 with custom spi

### ISSUE THREAD

**Issue by alexted** [keycloak/keycloak#17370]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I started getting exceptions when building kc with [custom spi](https://github.com/SnuK87/keycloak-kafka):
```bash
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-1) Finished step "io.quarkus.deployment.steps.MainClassBuildStep#build" in 0 ms
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-6) Finished step "io.quarkus.deployment.steps.ReflectionDiagnosticProcessor#writeReflectionData" in 0 ms
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-1) Dependency of "io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar" finished; 1 remaining
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-6) Dependency of "io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar" finished; 0 remaining
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-1) Starting step "io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar"
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-1) Finished step "io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar" in 0 ms
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-1) Dependency of "io.quarkus.deployment.pkg.steps.JarResultBuildStep#jarOutput" finished; 0 remaining
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-1) Dependency of "io.quarkus.deployment.pkg.steps.AppCDSBuildStep#build" finished; 0 remaining
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-6) Starting step "io.quarkus.deployment.pkg.steps.JarResultBuildStep#jarOutput"
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-6) Finished step "io.quarkus.deployment.pkg.steps.JarResultBuildStep#jarOutput" in 0 ms
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-16) Starting step "io.quarkus.deployment.pkg.steps.AppCDSBuildStep#build"
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-6) End step completed; 1 remaining
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-16) Finished step "io.quarkus.deployment.pkg.steps.AppCDSBuildStep#build" in 0 ms
2023-03-01 12:16:31,767 TRACE [io.quarkus.builder] (build-16) End step completed; 0 remaining
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-16) Thread "Thread[build-16,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-30) Thread "Thread[build-30,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-21) Thread "Thread[build-21,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-20) Thread "Thread[build-20,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-15) Thread "Thread[build-15,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-10) Thread "Thread[build-10,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-11) Thread "Thread[build-11,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-6) Thread "Thread[build-6,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-26) Thread "Thread[build-26,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-5) Thread "Thread[build-5,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-12) Thread "Thread[build-12,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-17) Thread "Thread[build-17,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-1) Thread "Thread[build-1,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-9) Thread "Thread[build-9,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-19) Thread "Thread[build-19,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-7) Thread "Thread[build-7,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-24) Thread "Thread[build-24,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-22) Thread "Thread[build-22,5,]" exiting
2023-03-01 12:16:31,767 TRACE [org.jboss.threads] (build-2) Thread "Thread[build-2,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-23) Thread "Thread[build-23,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-3) Thread "Thread[build-3,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-25) Thread "Thread[build-25,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-29) Thread "Thread[build-29,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-4) Thread "Thread[build-4,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-28) Thread "Thread[build-28,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-27) Thread "Thread[build-27,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-18) Thread "Thread[build-18,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-8) Thread "Thread[build-8,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-14) Thread "Thread[build-14,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-13) Thread "Thread[build-13,5,]" exiting
2023-03-01 12:16:31,768 TRACE [org.jboss.threads] (build-31) Thread "Thread[build-31,5,]" exiting
ERROR: Failed to run 'build' command.
Error details:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:71)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:183)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:120)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:88)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#setCryptoProvider threw an exception: java.lang.LinkageError: loader constraint violation: loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @14faa38c wants to load class org.keycloak.common.crypto.FipsMode. A different class with the same name was previously loaded by java.net.URLClassLoader @614df0a4. (org.keycloak.common.crypto.FipsMode is in unnamed module of loader java.net.URLClassLoader @614df0a4, parent loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:495)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl$$RecordingProxyProxy6.setCryptoProvider(Unknown Source)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.setCryptoProvider(KeycloakProcessor.java:636)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
	... 26 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#setCryptoProvider threw an exception: java.lang.LinkageError: loader constraint violation: loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @14faa38c wants to load class org.keycloak.common.crypto.FipsMode. A different class with the same name was previously loaded by java.net.URLClassLoader @614df0a4. (org.keycloak.common.crypto.FipsMode is in unnamed module of loader java.net.URLClassLoader @614df0a4, parent loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:495)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl$$RecordingProxyProxy6.setCryptoProvider(Unknown Source)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.setCryptoProvider(KeycloakProcessor.java:636)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 28 more
Caused by: java.lang.LinkageError: loader constraint violation: loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @14faa38c wants to load class org.keycloak.common.crypto.FipsMode. A different class with the same name was previously loaded by java.net.URLClassLoader @614df0a4. (org.keycloak.common.crypto.FipsMode is in unnamed module of loader java.net.URLClassLoader @614df0a4, parent loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:495)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl$$RecordingProxyProxy6.setCryptoProvider(Unknown Source)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.setCryptoProvider(KeycloakProcessor.java:636)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
The command '/bin/sh -c /opt/keycloak/bin/kc.sh -v build' returned a non-zero code: 1
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

### Version

21.0.0

### Expected behavior

kc is successfully assembled with [custom spi](https://github.com/SnuK87/keycloak-kafka)

### Actual behavior

exceptions raises when building kc with [custom spi](https://github.com/SnuK87/keycloak-kafka)

### How to Reproduce?

run it:
```dockerfile
# stage 1: build keycloak-kafka plugin
FROM registry.tsdev.tech/gitlab/node-maven:java17 AS kafka-builder
WORKDIR /app
COPY modules/keycloak-kafka .
RUN mvn clean package

# stage 2: build keycloak-metrics plugin
#FROM registry.tsdev.tech/gitlab/node-maven:java11 AS metrics-builder
#WORKDIR /app
#COPY modules/keycloak-metrics-spi .
#RUN mvn clean package

# stage 3: apply plugins
FROM quay.io/keycloak/keycloak:21.0.0 as builder

ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

COPY --from=kafka-builder /app/target/keycloak-kafka-1.1.2-jar-with-dependencies.jar /opt/keycloak/providers/
#COPY --from=metrics-builder /app/target/keycloak-metrics-spi-2.5.3-SNAPSHOT.jar /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
COPY frontend/build_keycloak/target/company-keycloak-theme-0.1.0.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh -v build

USER keycloak

# stage 4: copy results to empty image
FROM quay.io/keycloak/keycloak:21.0.0

ENV KC_FEATURES=token-exchange

WORKDIR /opt/keycloak

COPY --from=builder /opt/keycloak/ /opt/keycloak/

```

### Anything else?

custom spi for example: https://github.com/SnuK87/keycloak-kafka
I don't know if it's related to the plugin or the keycloak, but the error with the fips mode confuses me - we don't use it and never haven't activated it.
https://github.com/keycloak/keycloak/issues/16202 is similar to my problem

**Comment by mposolda** [comment]
It seems that your module `keycloak-kafka-1.1.2-jar-with-dependencies.jar` contains some Keycloak classes (like for example `org.keycloak.common.crypto.FipsMode`). It will be good to cleanup your jar, so it doesn't contain any Keycloak classes (and Keycloak dependencies) inside it.

I am closing as I think that this is issue in your `app`. Please re-open once you manage to remove all the Keycloak dependencies and still seeing the issue.
