### ISSUE TITLE
OutOfMemoryError when running Model Tests in CI

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#17427]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Sometimes the model tests fail with an OOM error: 

> 2023-02-25T02:47:00.9801885Z [ERROR] java.lang.OutOfMemoryError: Java heap space
2023-02-25T02:47:01.2779542Z [ERROR] Terminating due to java.lang.OutOfMemoryError: Java heap space

> 2023-02-25T02:47:01.2881118Z [ERROR] Error occurred in starting fork, check output in log
2023-02-25T02:47:01.2881742Z [ERROR] Process Exit Code: 3
2023-02-25T02:47:01.2882072Z [ERROR] Crashed tests:
2023-02-25T02:47:01.2882533Z [ERROR] org.keycloak.testsuite.model.infinispan.CacheExpirationTest
2023-02-25T02:47:01.2883188Z [ERROR]    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:714)
2023-02-25T02:47:01.2883885Z [ERROR]    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
2023-02-25T02:47:01.2884579Z [ERROR]    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)

https://github.com/keycloak/keycloak/actions/runs/4267884712/jobs/7429994617

### Version

nightly

### Expected behavior

Tests should complete

### Actual behavior

Tests are flaky

### How to Reproduce?

Seems to randomly fail, hard to reproduce. 

### Anything else?

Increasing the heap size as a first measure.

**Comment by ahus1** [comment]
Analyzing the heap dump, this is where it happend: 

![image](https://user-images.githubusercontent.com/3957921/222670735-ae1f81f6-a1d5-4c23-a4d1-2c6128ba51ac.png)

**Comment by ahus1** [comment]
Backport created: #17434
