### ISSUE TITLE
Connection reset between kubernetes clusters

### ISSUE THREAD

**Issue by BiatBang** [keycloak/keycloak#17480]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Servers deployed:
Keycloak, on GKE cluster A
App 1, on GKE cluster B
App 2, on GKE cluster B

App 1 is getting data from App 2 with access token issued by the keycloak server. There is a scheduler in App 1. Every 27 minutes, App 1 will get a new access token, and the access token lifespan is 30 min. 
At the startup of the App 1, it can successfully get the token from keycloak. However, after 27 min, it always fails to get a new token, and the exception is:
```
Exception in thread "Timer-0" java.lang.RuntimeException: Error executing http method [POST]. Response : null
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:113)
	at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
	at org.keycloak.authorization.client.AuthzClient.obtainAccessToken(AuthzClient.java:210)
	at com.geotab.daas.gateway.service.MasterService.getAccessToken(MasterService.java:97)
	at com.geotab.daas.gateway.service.MasterService$1.run(MasterService.java:88)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1454)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1065)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:87)
       ...
```

The way we get a new token is by using the authzClient:
```
AccessTokenResponse accessTokenResponse = authzClient.obtainAccessToken();
```

This error only happens when we have keycloak and applications in different clusters. In test env, we deploy them in one cluster and no error ever happened. Also, before upgrade keycloak from 16 to 20, we haven't seen this error with multiple clusters.

### Version

20.0.3

### Expected behavior

Applications get access token correctly

### Actual behavior

Applications fail to get access token with authzClient

### How to Reproduce?

With the sample setup and code

**Comment by sschu** [comment]
If it works in the same cluster but does not work in a different cluster, then the problem is most likely in you cluster/network setup but not in Keycloak.

**Comment by mposolda** [comment]
Adding to Backlog. Without more details, it is not really clear if this is Keycloak issue or rather the network/environment issue (which appears rather that possibility). Keycloak team won't have time to look at this in the near future.

**Comment by stianst** [comment]
This will be down to environment issues, and most likely you can tune the http client to improve on things.

**Comment by WMartel** [comment]
@BiatBang I don't know if you're still dealing with this problem. Scouring the Internet, I see that this could possibly be related to the introduction of the parameter: max-connection-idle-time-millis. Searching the GitHub history, I couldn't find with high confidence which version it came with, my best guess is Keycloak 20, which could explain why it worked for you with Keycloak 16. I say could, because I don't know how Keycloak behaved with idle TCP connections, before this parameter was introduced.

I've seen reports here and there of similar errors being caused by a Nat Gateway on AWS terminating TCP requests with a reset instead of a FIN, causing applications to think the connections are still good, but when they try to use these connections, the request(s) fail. The parameter I mentioned can supposedly be lowered to an idel timeout lower than that of the AWS NAT Gateway, or whatever other network component is closing the requests, to make Keycloak proactively close and re-open these connections. We had a similar issue, but fixed it on the AWS side. I haven't been able to reproduce or confirm whether changing this parameter would have worked, but I've seen people online say that it did., so thought I'd comment here in case it can help you or anyone else that finds this thread by Googling, like I did.
