### ISSUE TITLE
ISPN000286: Issue when retrieving cluster listeners from pod_name: keycloak application fails to start

### ISSUE THREAD

**Issue by reachtoamrita** [keycloak/keycloak#17559]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

We have deployed keycloak application in clustered mode. We are using kubernetes and deploying 3 pods of keycloak in clustered mode. The below issue is seen
```
2023-03-08 18:01:36,819 WARN  [org.infinispan.statetransfer.StateConsumerImpl] (thread-15,ejb,common-services-auth-0) ISPN000286: Issue when retrieving cluster listeners from common-services-auth-2: org.infinispan.remoting.transport.jgroups.SuspectException: ISPN000400: Node common-services-auth-2 was suspected
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.ResponseCollectors.remoteNodeSuspected(ResponseCollectors.java:31)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleResponseCollector.targetNotFound(SingleResponseCollector.java:31)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleResponseCollector.targetNotFound(SingleResponseCollector.java:17)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.ValidSingleResponseCollector.addResponse(ValidSingleResponseCollector.java:23)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.addResponse(SingleTargetRequest.java:74)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:44)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1415)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1317)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Version

17.0.1 (wildfly)

### Expected behavior

The pod should start successfully

### Actual behavior

The pod restrted with the above mentioned error.
2023-03-08 18:01:36,819 WARN  [org.infinispan.statetransfer.StateConsumerImpl] (thread-15,ejb,common-services-auth-0) ISPN000286: Issue when retrieving cluster listeners from common-services-auth-2: org.infinispan.remoting.transport.jgroups.SuspectException: ISPN000400: Node common-services-auth-2 was suspected
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.ResponseCollectors.remoteNodeSuspected(ResponseCollectors.java:31)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleResponseCollector.targetNotFound(SingleResponseCollector.java:31)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleResponseCollector.targetNotFound(SingleResponseCollector.java:17)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.ValidSingleResponseCollector.addResponse(ValidSingleResponseCollector.java:23)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.addResponse(SingleTargetRequest.java:74)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:44)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1415)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1317)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
	at java.base/java.lang.Thread.run(Unknown Source)

### How to Reproduce?

Not Sure

**Comment by reachtoamrita** [comment]
Also, the below error is following the current error

ailed to connect to the controller: Timeout waiting for the system to boot.
2023-03-08 18:05:36,746 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 61) MSC000001: Failed to start service org.wildfly.clustering.infinispan.cache.keycloak.actionTokens: org.jboss.msc.service.StartException in service org.wildfly.clustering.infinispan.cache.keycloak.actionTokens: org.infinispan.commons.CacheException: Initial state transfer timed out for cache actionTokens on common-services-auth-0
	at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:66)
	at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Unknown Source)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

**Comment by sschu** [comment]
Have you tried the latest Keycloak version?

**Comment by reachtoamrita** [comment]
I am on keycloak 17.0.1 wildfly legacy version. Also, I am using k8s for pod deployment and it has 3 pods.

**Comment by sschu** [comment]
You should always first try to recreate the issue with the latest release. You actually confirmed you did that when opening the issue... ;)

**Comment by mhajas** [comment]
Thank you for the report @reachtoamrita, unfortunately, it is hard to triage this as it is missing steps to reproduce. 

- As suggested by @sschu, could you try the latest version?
- Are you spawning a clear cluster? Or there are already some long-time running instances that contain some data. It seems the failure is caused by Infinispan trying to transfer the state between the old nodes and the new one and the operation times out for some reason. Maybe there are too many items in caches.
- How long does it take for the pod to fail? Is it immediately after it starts, or there is some longer period of time before it fails?

**Comment by mhajas** [comment]
Closing due to inactivity. Please reopen if you are able to provide answers to the questions above.
