### ISSUE TITLE
Keycloak 21.0.1 startup fails on debian (Unable to use any JGroups configuration mechanisms)

### ISSUE THREAD

**Issue by linarphy** [keycloak/keycloak#17585]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

Cannot start keycloak after an upgrade from 20.0.6 to 21.0.1 with openjdk on debian bullseye (11, last version).

log below:
```
2023-03-11 18:47:16,630 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-03-11 18:47:16,826 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISP
N000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:758)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:504)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:485)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:357)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:774)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:742)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:406)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationExce
ption: Preview Features not enabled, need to run with --enable-preview
        at org.jgroups.stack.ProtocolStack.lambda$initComponents$7(ProtocolStack.java:861)
        at org.jgroups.util.Util.forAllComponents(Util.java:3368)
        at org.jgroups.stack.ProtocolStack.initComponents(ProtocolStack.java:839)
        at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:795)
        at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:438)
        at org.jgroups.JChannel.init(JChannel.java:899)
        at org.jgroups.JChannel.<init>(JChannel.java:123)
        at org.jgroups.JChannel.<init>(JChannel.java:113)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:756)
        ... 29 more
```

### Version

Keycloak: 21.0.1

### Expected behavior

Keycloak start.

### Actual behavior

Keycloak startup fails with a fatal error.

### How to Reproduce?

Upgrade from keycloak 20.0.6 to 21.0.1 with a near default configuration.

### Anything else?

Obviously linked to #17264 , but not on windows server (that's why I created a new issue, but it's maybe not the best solution so do not hesitate to delete it if needed).

**Comment by mhajas** [comment]
This indeed seems to be a duplicate of #17264 , however, @linarphy in the report, you are saying you are using OpenJDK 11, can you please double-check this? It seems this issue is present only when using JDK 19

**Comment by linarphy** [comment]
Sorry for the late answer, I was wrong with the openjdk version. I close this as it does not add anything ^^.
