### ISSUE TITLE
Support IDs with slash

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#17590]
### Description

File store will use IDs which can contain slashes (e.g. `account/delete-account`). The current admin console fails to load those:

`http://server/auth/admin/master/console/#/master/clients/account/roles/account/delete-account/details`

returns 404

These IDs are supported by REST API, and work in the admin UI too if replaced slash with `%2F`: `http://server/auth/admin/master/console/#/master/clients/account/roles/account%2Fdelete-account/details`

### Motivation

This is needed for admin console to work with arbitrary IDs. Specific example is the file store.

**Comment by edewit** [comment]
@hmlnarik we have updated the router and this should be fixed, how can we test this?

**Comment by hmlnarik** [comment]
@edewit Sorry for late response.

I have tried the most recent main and the slashes in ID do not work.

The file store now escapes slashes in IDs, so I think the issue priority can be lowered. The format of ID is in the control of the underlying store though, so this might represent an issue for custom implementations in the future.

If you wanted to try the IDs with slashes, you could run the file store per #16768 with the following custom change in https://github.com/keycloak/keycloak/blob/6014070431c31cd92d30a0f5200cfa6971134c43/model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java#L181-L182

```diff
diff --git a/model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java b/model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java
index 37fa7b6e9b..b395dabae0 100644
--- a/model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java
+++ b/model/map-file/src/main/java/org/keycloak/models/map/storage/file/FileMapStorage.java
@@ -178,8 +178,8 @@ public class FileMapStorage<V extends AbstractEntity & UpdatableEntity, M> imple
         }
 
         // Percent sign + Unix (/) and https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file reserved characters
-        private static final Pattern RESERVED_CHARACTERS = Pattern.compile("[%<:>\"/\\\\|?*=]");
-        public static final String ID_COMPONENT_SEPARATOR = ":";
+        private static final Pattern RESERVED_CHARACTERS = Pattern.compile("[%<:>\"\\\\|?*=]");
+        public static final String ID_COMPONENT_SEPARATOR = "/";
         private static final String ESCAPING_CHARACTER = "=";
         private static final Pattern ID_COMPONENT_SEPARATOR_PATTERN = Pattern.compile(Pattern.quote(ID_COMPONENT_SEPARATOR) + "+");
```

Then the process is as follows:
1. Get to the list of clients: http://localhost:8081/auth/admin/master/console/#/master/clients
2. Go to the roles tab in _master-realm_ client: http://localhost:8081/auth/admin/master/console/#/master/clients/master-realm/roles
3. Click one of the client roles, say _manage-clients_.

Actual, not working, link in the table is 
* http://localhost:8081/auth/admin/master/console/#/master/clients/master-realm/roles/master-realm/manage-clients/details

It should be a working link:

* http://localhost:8081/auth/admin/master/console/#/master/clients/master-realm/roles/master-realm%2fmanage-clients/details

**Comment by jonkoops** [comment]
@hmlnarik getting some exceptions when running the nightly server with the flags mentioned in #16768 . Do you know what is going on?

```log
Updating the configuration and installing your custom providers, if any. Please wait.
2023-04-24 13:17:00,468 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: admin-fine-grained-authz, declarative-user-profile
2023-04-24 13:17:01,212 WARN  [io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor] (build-38) Hibernate ORM is disabled because no JPA entities were found
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.RuntimeException: Failed to find provider map for role
	at org.keycloak.quarkus.deployment.KeycloakProcessor.checkProviders(KeycloakProcessor.java:805)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:369)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

ERROR: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.RuntimeException: Failed to find provider map for role
	at org.keycloak.quarkus.deployment.KeycloakProcessor.checkProviders(KeycloakProcessor.java:805)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureKeycloakSessionFactory(KeycloakProcessor.java:369)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

ERROR: Failed to find provider map for role
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

**Comment by hmlnarik** [comment]
> @hmlnarik getting some exceptions when running the nightly server with the flags mentioned in #16768 . Do you know what is going on?

I have never seen this exception, I have no clue.. I have tried this with the today's nightly and it works, could you please try again?

```
$ keycloak-999.0.0-SNAPSHOT$ bin/kc.sh start-dev --storage=file --storage-file-dir=data/file

Updating the configuration and installing your custom providers, if any. Please wait.
2023-05-16 10:44:52,294 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: map-storage
2023-05-16 10:44:53,879 WARN  [io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor] (build-9) Hibernate ORM is disabled because no JPA entities were found
2023-05-16 10:44:55,118 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 3160ms
2023-05-16 10:44:55,913 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: map-storage
2023-05-16 10:44:56,538 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2023-05-16 10:44:56,541 WARN  [org.keycloak.models.DeploymentStateProviderFactory] (main) Version seed for deployment state set with a random number. Caution: This can lead to unstable operations when serving resources from the cluster without a sticky loadbalancer or when restarting nodes. Set the 'storage-deployment-state-version-seed' option with a secret seed to ensure stable operations.
2023-05-16 10:44:57,340 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-05-16 10:44:57,409 WARN  [org.keycloak.services.DefaultComponentFactoryProviderFactory] (main) No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.
2023-05-16 10:44:57,412 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-05-16 10:44:57,516 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2023-05-16 10:44:58,275 INFO  [io.quarkus] (main) Keycloak 999.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.2.Final) started in 3.003s. Listening on: http://0.0.0.0:8080
2023-05-16 10:44:58,275 INFO  [io.quarkus] (main) Profile dev activated. 
2023-05-16 10:44:58,275 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, vertx]
2023-05-16 10:44:58,279 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
