### ISSUE TITLE
docker image 21.0.1 lacks a Javascript engine

### ISSUE THREAD

**Issue by kschubert** [keycloak/keycloak#17671]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Docker image 21.0.1 packs Java 17. Docker images of version 20 and below pack Java version 11 (or lower), which come with a built in Javascript engine. Java 17 doesn't include a Javascript engine, but the Dockerfile hasn't been adjusted accordingly. There are some policies within Keycloak that are implemented using Javascript. Keycloak crashes when it tries to execute these policies.

### Version

21.0.1

### Expected behavior

Keycloak is able to execute policies that are implemented using Javascript.

### Actual behavior

Keycloak crashes when trying to execute policies that are implemented using Javascript.
Stacktrace excerpt:
```
java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='284fe926-ab97-4df7-bd7d-36702b20e869', name='Default Policy', type='text/javascript', code='// by default, grants any permission associated with this policy
$evaluation.grant();
', description='A policy that grants access only for users within this realm'}
	at org.keycloak.scripting.DefaultScriptingProvider.getPreparedScriptEngine(DefaultScriptingProvider.java:114)
	at org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:74)
	at org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:37)
	at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.lambda$getEvaluatableScript$0(JSPolicyProviderFactory.java:111)
	at org.keycloak.authorization.policy.provider.js.ScriptCache.lambda$computeIfAbsent$0(ScriptCache.java:81)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at org.keycloak.authorization.policy.provider.js.ScriptCache.computeIfAbsent(ScriptCache.java:81)
	at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.getEvaluatableScript(JSPolicyProviderFactory.java:108)
	at org.keycloak.authorization.policy.provider.js.JSPolicyProvider.evaluate(JSPolicyProvider.java:46)
	at org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:56)
	at org.keycloak.authorization.policy.provider.permission.ResourcePolicyProvider.evaluate(ResourcePolicyProvider.java:47)
	at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.lambda$createPolicyEvaluator$0(DefaultPolicyEvaluator.java:117)

```

### How to Reproduce?

Start docker image:
`docker run -d -e "KEYCLOAK_ADMIN=admin" -e "KEYCLOAK_ADMIN_PASSWORD=admin" -e KC_HOSTNAME_STRICT=false -e KC_HOSTNAME_STRICT_HTTPS=false -p 8080:8080 --name keycloak "quay.io/keycloak/keycloak:21.0.1" start-dev`

Wait for Keycloak to be up and running.
Run this shell script:
```
#!/bin/bash

echo Login admin
RESPONSE=$(curl -s -d client_id=admin-cli -d username=admin -d password=admin -d grant_type=password http://localhost:8080/realms/master/protocol/openid-connect/token)
#echo response: $RESPONSE
ADMIN_TOKEN=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).access_token")
echo create realm
curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" --json '{"realm":"test_realm","enabled":true}' http://localhost:8080/admin/realms
echo create test user
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" --json '{"username":"test_user","enabled":true,"credentials":[{"type":"password","value":"test-pass","temporary":false}]}' -w '%header{Location}' http://localhost:8080/admin/realms/test_realm/users)
#echo response: $RESPONSE
TEST_USER=$(echo -n $RESPONSE | node -pe "require('fs').readFileSync('/dev/stdin').toString().split('/').pop().trim()")
echo create test client
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" --json '{"clientId":"test_auth_client","clientAuthenticatorType":"client-secret","redirectUris":["*"],"webOrigins":["*"],"bearerOnly":false,"serviceAccountsEnabled":true,"authorizationServicesEnabled":true,"publicClient":false,"protocol":"openid-connect"}' -w '%header{Location}' http://localhost:8080/admin/realms/test_realm/clients)
#echo response: $RESPONSE
TEST_AUTH_CLIENT=$(echo -n $RESPONSE | node -pe "require('fs').readFileSync('/dev/stdin').toString().split('/').pop().trim()")
echo get id of realm-management client
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" http://localhost:8080/admin/realms/test_realm/clients?clientId=realm-management)
#echo response: $RESPONSE
REALM_MGMT_CLIENT=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString())[0].id")
echo get id of realm mgmt role
RESPONSE=$(curl -s -H "Authorization: bearer ${ADMIN_TOKEN}" http://localhost:8080/admin/realms/test_realm/clients/${REALM_MGMT_CLIENT}/roles/realm-admin)
#echo response: $RESPONSE
REALM_MGMT_ROLE=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).id")
echo assign mgmt role to test user
curl -H "Authorization: bearer ${ADMIN_TOKEN}" --json "[{\"id\":\"${REALM_MGMT_ROLE}\",\"name\":\"realm-admin\",\"description\":\"role_realm-admin\",\"composite\":true,\"clientRole\":true,\"containerId\":\"${REALM_MGMT_CLIENT}\",\"attributes\":{}}]" http://localhost:8080/admin/realms/test_realm/users/${TEST_USER}/role-mappings/clients/${REALM_MGMT_CLIENT}
echo Login test user
RESPONSE=$(curl -s -d client_id=admin-cli -d username=test_user -d password=test-pass -d grant_type=password http://localhost:8080/realms/test_realm/protocol/openid-connect/token)
#echo response: $RESPONSE
TEST_USER_TOKEN=$(echo -n $RESPONSE | node -pe "JSON.parse(require('fs').readFileSync('/dev/stdin').toString()).access_token")
echo get uma ticket
curl -s -H "Authorization: bearer ${TEST_USER_TOKEN}" -d audience=test_auth_client -d grant_type=urn:ietf:params:oauth:grant-type:uma-ticket http://localhost:8080/realms/test_realm/protocol/openid-connect/token
```

The last line will output `{"error":"server_error","error_description":"Unexpected error while evaluating permissions"}`. Command `docker logs keycloak` will show the server error.

**Comment by hoepfnerj** [comment]
There is a guide in the docs how to add a script engine:
https://www.keycloak.org/docs/latest/server_development/#deploy-the-script-jar
It does work, but I think it is not a good solution to force the user to include several JARs to use this feature of Keycloak.

**Comment by JoniJnm** [comment]
Another way to reproduce the problem

1. Run the imagen: https://www.keycloak.org/server/containers#_trying_keycloak_in_development_mode
```
docker run --name mykeycloak -p 8080:8080 \
        -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me \
        quay.io/keycloak/keycloak:latest \
        start-dev
```
2. Open the dashboard and create a new client named "testing" with Authorization enabled
3. Go the the Authorization > Evaluate tab
4. Evaluate against the resource type `urn:testing:resources:default`
5. There will be a 500 error in the browser console and the exception in the container logs

Java 11 to 17 change: https://github.com/keycloak/keycloak/pull/15975

**Comment by Pepo48** [comment]
Hi @kschubert,

first of all, thanks for the issue report. Nashorn JavaScript Engine is removed since Java 15[1]. Thus, all we can do is to provide a workaround. The steps to overcome this for later versions of Java are described in our documentation[2].

I'm closing this issue, but feel free to reopen it if necessary or start a GH discussion.

Thanks!

[1] https://openjdk.org/jeps/372
[2] https://www.keycloak.org/docs/latest/server_development/#deploy-the-script-engine-on-java-15-and-later

**Comment by kschubert** [comment]
Hi @Pepo48,

I'm confused. I think you must have misunderstood what this issue is about. The docker image quay.io/keycloak/keycloak is non-functional. This docker image is provided by this repo's organization, isn't it ? If it is, then my question is: do you really plan to continue to provide a non-functional docker image ?

Best regards,
Kay

**Comment by JoniJnm** [comment]
@Pepo48 remove this if you don't want to include a javascript engine

https://github.com/keycloak/keycloak/blob/8bc5273792e3f843d125510aa62eee353279b1ea/services/src/main/java/org/keycloak/authorization/admin/ResourceServerService.java#L178-L198

**Comment by stianst** [comment]
Hi, I'm sorry about the way this was handled. We upgraded the container from Java 11 to 17, which stopped JavaScript providers working. This was done with no mention in the release/upgrades guides, which is not ideal.

I also fully appreciate that it's non-trivial to extend the container to include the Nashorn engine, but not fully sure if we can actually include it out of the box I'm afraid.

We'll look into this, and at least provide some improvements around the docs, but we'll also take a look and see if we can include the Nashorn engine, or at least make it easier to add it.

**Comment by fredplante** [comment]
This issue should be re-opened. Indeed the provided image are not functional now.

**Comment by Pepo48** [comment]
As you can see I escalated this yesterday and we're currently assessing the situation internally in order to meet the needs of our community.

I'll make sure that we get back to you in case of a progress.

Thank you all for raising this.

**Comment by ykun91** [comment]
encounter same issue when upgrade Keycloak from 19 to 21, using the docker image `quay.io/keycloak/keycloak:21.0`

for those who are looking for a quick workaround

### fastest way
**: just delete the `Default Policy`** (will delete the `Default Permission` also)
`Default Policy` is the what requires JS engine to execute, I confirmed just delete it will make authz server works.
but as its description, `Default Policy` is for `A policy that grants access only for users within this realm`, so delete it may have some bad effects.

### the official way
- download these jar files into a folder on your server
https://repo1.maven.org/maven2/org/openjdk/nashorn/nashorn-core/15.4/nashorn-core-15.4.jar
https://repo1.maven.org/maven2/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
https://repo1.maven.org/maven2/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar

- mount the folder into keycloak docker container with path `/opt/keycloak/providers`, run `kc.sh build` before `kc.sh start`, like following

```yaml
version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    working_dir: /opt/keycloak/bin
    entrypoint: ["sh", "-c", "./kc.sh build --db=$${KC_DB} && ./kc.sh start"]
    env_file:
      - keycloak.env
    networks:
      - <your_networks>
    volumes:
      - <the_folder_where_you_put_jar_files>:/opt/keycloak/providers
```

**Comment by mposolda** [comment]
We will fix this in Keycloak 22.  It seems to me that needed steps are:

- Make sure that nashorn and transitive asm* dependencies are inside quarkus distribution by default
- Update nashorn to 15.4 as that is the version productized in RH. Make sure that "asm" version is also updated to the version productized in RH
- Update testsuite - probably at least this step https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/servers/auth-server/quarkus/pom.xml#L268-L302 is not needed as we won't need to copy nashorn etc to the testsuite if it is in the distribution by default
- Update docs: This section can be likely removed entirely https://www.keycloak.org/docs/latest/server_development/index.html#deploy-the-script-engine-on-java-15-and-later

**Comment by JoniJnm** [comment]
the doc could be useful if someone isn't using this container
