### ISSUE TITLE
keycloak v21.0.1 cannot 'save' admin-cli client configs

### ISSUE THREAD

**Issue by cristinaaanguyen** [keycloak/keycloak#19217]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/cli

### Describe the bug

I am on v21.0.1 and I’ve restarted the server many times. When trying to press save after updating admin-cli, it doesn't work. The save button does nothing. I checked the inspector, and found an error. I'm also on the latest chrome and my local is using node v17.9.1

uncaught (in promise) TypeError: crypto.randomUUID is not a function
at Alerts.tsx:51:20
at Alerts.tsx:64:5
at ne (ClientDetails.tsx:363:7)

### Version

v21.0.1

### Expected behavior

It should save my changes.

### Actual behavior

My changes are not saved, error is returned: randomUUID not a function

### How to Reproduce?

Use keycloak v21.0.1 and try updating admin-cli client settings.

**Comment by cristinaaanguyen** [comment]
after toggling client authentication on under admin-cli settings, I saw the "client credentials" tab appear, which I was able to click and somehow that saved my settings.
