### ISSUE TITLE
DB Connection Error after Updating Keycloak 16->21 on mssql express edition

### ISSUE THREAD

**Issue by stefanwendelmann** [keycloak/keycloak#19250]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After Updating from 16.1.1 to 21.0.1 we could not start the Service.
The DB is a SQL Server Express:

Microsoft SQL Server 2019 (RTM-CU19) (KB5023049) - 15.0.4298.1 (X64)   Jan 27 2023 16:44:09   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

Running Environment 
OS: Ubuntu 20.04.6 LTS
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.1

Dockerfile:

```dockerfile
FROM quay.io/keycloak/keycloak:21.0 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
# docker,preview
ENV KC_FEATURES=authorization,account2,account-api,admin-fine-grained-authz,admin2,impersonation,token-exchange,client-policies,declarative-user-profile,dynamic-scopes
ENV KC_HTTP_RELATIVE_PATH="/auth"

# Configure a database vendor
ENV KC_DB=mssql

WORKDIR /opt/keycloak
# Deploy Theme and other service-provider jars
#COPY service-provider-jars/ /opt/keycloak/providers/
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build --transaction-xa-enabled=false

FROM quay.io/keycloak/keycloak:21.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=mssql
ENV KC_DB_URL=<URL>
ENV KC_DB_USERNAME=<User>
ENV KC_DB_PASSWORD=<PW>
ENV KC_HOSTNAME=localhost
ENV KC_HTTP_RELATIVE_PATH="/auth"
# Check for Prod
#ENV KC_PROXY=edge
#ENV KC_HTTP_RELATIVE_PATH=/auth
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

keycloak_run.sh

```shell
#!/bin/sh

docker pull <Docker-image>

docker stop keycloak
docker rm -f keycloak

docker run -m 1200m -d --restart always --name keycloak \
-e "KC_DB_URL=jdbc:sqlserver://<SQLSERVERHOST>\<SQLSERVERINSTANCE>;databaseName=<DBNAME>;trustServerCertificate=false;encrypt=false" \
-e KC_DB=mssql \
-e KC_DB_USERNAME=<USER> \
-e KC_DB_PASSWORD=<PW>\
--log-driver "json-file" --log-opt "tag={{.ImageName}}|{{.Name}}|" \
<Docker-image> \
start --optimized --hostname-strict=false --hostname-strict-https=false \
--proxy edge --hostname=<HOSTNAME>
```

### Version

21.0.1

### Expected behavior

Server starting.
We can run it on a SQL Server Standard edition in our Test environment.
Sadly our Prod Env only has a Express Edition atm.

### Actual behavior

Error / Start Message:

```
2023-03-22 14:14:28,380 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: admin-fine-grained-authz, declarative-user-profile, token-exchange
2023-03-22 14:14:28,381 WARN  [org.keycloak.common.Profile] (main) Experimental features enabled: dynamic-scopes
2023-03-22 14:14:28,847 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <maskiert>, Strict HTTPS: false, Path: <request>, Strict BackChannel:
false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2023-03-22 14:14:30,445 INFO  [org.infinispan.SERVER] (keycloak-cache-init) ISPN005054: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
2023-03-22 14:14:30,496 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-03-22 14:14:30,529 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-03-22 14:14:30,546 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-03-22 14:14:30,814 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-03-22 14:14:30,889 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2023-03-22 14:14:30,892 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: ffac4843-ba73-49c5-835f-89fa10b67625, name: ecc5415bb509-12385
2023-03-22 14:14:30,894 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2023-03-22 14:14:30,895 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
2023-03-22 14:14:30,895 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2023-03-22 14:14:30,895 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
2023-03-22 14:14:30,901 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.44410
2023-03-22 14:14:32,908 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) ecc5415bb509-12385: no members discovered after 2005 ms: creating cluster as coordinator
2023-03-22 14:14:32,917 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [ecc5415bb509-12385|0] (1) [ecc5415bb509-12385]
2023-03-22 14:14:32,924 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `ecc5415bb509-12385`, physical addresses are `[10.10.14.2:59946]`
2023-03-22 14:14:35,204 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Acquisition
timeout while waiting for new connection
        at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:320)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
        at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:272)
        at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:68)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:72)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:165)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:66)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:296)
        ... 23 more

2023-03-22 14:14:35,498 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue
as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2023-03-22 14:14:40,523 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2023-03-22 14:14:40,592 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-03-22 14:14:40,592 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2023-03-22 14:14:40,593 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Acquisition timeout while waiting for new connection
2023-03-22 14:14:40,593 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### How to Reproduce?

1. Spin up a SQL Server Express 2019
2. Create a Keycloak Docker Image with the Dockerfile above
3. Run the Keycloak Docker image with the Settings of the DB etc. like the shell script above

**Comment by sschu** [comment]
What happens when you directly use the Keycloak image to connect to MS SQL?

**Comment by stefanwendelmann** [comment]
@sschu what do you mean by directly use the keycloak image?

**Comment by nitishdb** [comment]
Setting `quarkus.datasource.jdbc.acquisition-timeout` in `quarkus.properties`, as mentioned in this [comment](https://github.com/keycloak/keycloak/issues/16448#issuecomment-1434726902) of #16448, worked for me.

KC 20.0.5, MSSQL docker image `mcr.microsoft.com/mssql/server:2019-latest`

**Comment by vramik** [comment]
@initshdb thanks for the info!

@stefanwendelmann would you be able to verify it with latest release (21.0.2)?

**Comment by vramik** [comment]
hey @stefanwendelmann, any update on this?

**Comment by stefanwendelmann** [comment]
Hey @vramik, 
i migrated all our environments to postgre to be ready for the future.

Sry i cannot test it anymore.
Feel free to ask, if you need more steps to reproduce it.
