### ISSUE TITLE
Hibernate 6: Entity in Key not returned when querying

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#19323]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After migrating from Hibernate 5 to Hibernate 6 in #17664, there is the exception:

```
Caused by: org.hibernate.HibernateException: identifier of an instance of org.keycloak.models.jpa.entities.FederatedIdentityEntity was altered from org.keycloak.models.jpa.entities.FederatedIdentityEntity$Key@3970c62a to org.keycloak.models.jpa.entities.FederatedIdentityEntity$Key@cf2e436d
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:93)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:175)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:134)
KcOidcBrokerTest ++ 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:221)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:90)
KcOidcBrokerTest ++ 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:38)
KcOidcBrokerTest ++ 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
KcOidcBrokerTest ++ 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1412)
```

### Version

quarkus3 branch

### Expected behavior

There shouldn't be this exception

### Actual behavior

An exception: The query returns the entity without the `user` set (it is `null`)

### How to Reproduce?

Run the test `KcOidcBrokerTest` with Quarkus

**Comment by vramik** [comment]
Reproducer: https://github.com/vramik/hibernate-test-case-templates/tree/kc-19323-entity-key-not-returned

**Comment by vramik** [comment]
Started zulip chat: https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/H5-.3EH6.20Entity.20in.20key.20not.20returned.20when.20querying.20with.20H6

**Comment by vramik** [comment]
Issue confirmed as bug by hibernate team. Jira created: https://hibernate.atlassian.net/browse/HHH-16387
