### ISSUE TITLE
Hibernate 6: UnsupportedOperationException: compare() not implemented for EntityType

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#19321]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After migrating from Hibernate 5 to Hibernate 6 in #17664, there is the exception:

```
ClientSecretRotationTest ++ 2023-03-21 20:34:33,086 WARN  [com.arjuna.ats.arjuna] (executor-thread-2) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff0a010129:9d5b:641a14ce:328, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@7e65c558 >: java.lang.UnsupportedOperationException: compare() not implemented for EntityType
ClientSecretRotationTest ++ 	at org.hibernate.type.EntityType.compare(EntityType.java:255)
ClientSecretRotationTest ++ 	at org.hibernate.type.ComponentType.compare(ComponentType.java:215)
ClientSecretRotationTest ++ 	at org.hibernate.type.Type.compare(Type.java:222)
ClientSecretRotationTest ++ 	at org.hibernate.action.internal.EntityAction.compareTo(EntityAction.java:160)
ClientSecretRotationTest ++ 	at org.hibernate.action.internal.EntityAction.compareTo(EntityAction.java:28)
ClientSecretRotationTest ++ 	at java.base/java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:321)
```

### Version

quarkus3 branch

### Expected behavior

Hibernate 6 update should work

### Actual behavior

The test fails.

### How to Reproduce?

Run ClientSecretRotationTest with Quarkus

**Comment by ahus1** [comment]
Bug confirmed in Hibernate via chat, created Hibernate issue: https://hibernate.atlassian.net/browse/HHH-16368

**Comment by ahus1** [comment]
Solution is part of Hibernate 6.2 release.

**Comment by ahus1** [comment]
The workaround has been reverted in the Quarkus 3 branch in PR #19486, therefore this is resolved.
