### ISSUE TITLE
Interal Error with OIDC Redirect URI as file protocol

### ISSUE THREAD

**Issue by WilSimpson** [keycloak/keycloak#19345]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I'm using the `keycloak-js` library in an `electron` desktop application. I use the library to authenticate the application before launching a game executable. In development, the application is hosted under `http://localhost:1212` and everything is performing as expected. In production, the application is hosted under `file://path/to/application/index.html`. Due to this the `redirect_uri` isn't a valid host name.

### Version

21.0.1

### Expected behavior

Allowed to have a redirect_uri be file protocol, (ie `file://`) 

### Actual behavior

[Internal error thrown](https://github.com/keycloak/keycloak/blob/main/common/src/main/java/org/keycloak/common/util/KeycloakUriBuilder.java#L429)
```
2023-03-26 23:34:57,807 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-255) Uncaught server error: java.lang.RuntimeException: empty host name
        at org.keycloak.common.util.KeycloakUriBuilder.buildString(KeycloakUriBuilder.java:429)
        at org.keycloak.common.util.KeycloakUriBuilder.buildFromValuesAsString(KeycloakUriBuilder.java:600)
        at org.keycloak.common.util.KeycloakUriBuilder.buildAsString(KeycloakUriBuilder.java:576)
        at org.keycloak.protocol.oidc.utils.RedirectUtils.decodeRedirectUri(RedirectUtils.java:171)
        at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:96)
        at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:63)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpointChecker.checkRedirectUri(AuthorizationEndpointChecker.java:129)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:168)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.access$300(AuthorizationEndpoint.java:69)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint$1.runInternal(AuthorizationEndpoint.java:140)
        at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:67)
        at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:44)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:299)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.processInRetriableTransaction(AuthorizationEndpoint.java:132)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:117)
        at jdk.internal.reflect.GeneratedMethodAccessor269.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Request to authorize via OIDC endpoint (ex `realms/<realm>/protocol/openid-connect/auth` and set the redirect_uri to be a file protocol.

### Anything else?

I'm happy to contribute but would like a direction on how the file protocol should be handled, if it can be handled at all.

**Comment by WilSimpson** [comment]
My current workaround is to have a redirect URI to a fake endpoint such as `http://localhost/keycloak-redirect` and intercept all requests made to this HTTP endpoint and redirect to the local file.

In electron that is
```typescript
const { session: { webRequest } } = mainWindow.webContents;
  const filter = {
    urls: [
      'http://localhost/keycloak-redirect*'
    ]
  };
  webRequest.onBeforeRequest(filter, async (details, callback) => {
    const index = details.url.indexOf('#');
    let params = "";
    if (index >= 0) {
      params = details.url.slice(index);
    }

    callback({
      cancel: false,
      redirectURL: resolveHtmlPath('index.html') + params,
    })
  });
```

I'm not sure what the reasoning is for not allowing a file protocol redirect uri, but if it's a security concern, then I'm happy to use this work-around.

**Comment by vickeybrown** [comment]
Hi! This is currently working as designed as pointing to local files is a security concern. You can find more information on authorizing Native Apps here - https://www.rfc-editor.org/rfc/rfc8252#section-7

**Comment by mohamedikram7** [comment]
> My current workaround is to have a redirect URI to a fake endpoint such as `http://localhost/keycloak-redirect` and intercept all requests made to this HTTP endpoint and redirect to the local file. However, this causes security concerns in chrome because it's redirecting http protocol to file protocol.
> 
> In electron that is
> 
> ```ts
> const { session: { webRequest } } = mainWindow.webContents;
>   const filter = {
>     urls: [
>       'http://localhost/keycloak-redirect*'
>     ]
>   };
>   webRequest.onBeforeRequest(filter, async (details, callback) => {
>     const index = details.url.indexOf('#');
>     let params = "";
>     if (index >= 0) {
>       params = details.url.slice(index);
>     }
> 
>     callback({
>       cancel: false,
>       redirectURL: resolveHtmlPath('index.html') + params,
>     })
>   });
> ```
> 
> I'm not sure what the reasoning is for not allowing a file protocol redirect uri, but if it's a security concern, then I'm happy to use an alternative method.

hi @WilSimpson im facing issue http://localhost/keycloak-redirect?state=a1370f631a3a4e83a72e99681585130f it is saying unsafe redirects how to resolve this

**Comment by WilSimpson** [comment]
@mohamedikram7 I solved it by loading the URL instead of redirecting. 

Here's some example code

```js
  const filter = {
    urls: [
      'http://localhost/keycloak-redirect*'
    ]
  };
  mainWindow.webContents.session.webRequest.onBeforeRequest(filter, async (details, callback) => {
    let params = details.url.slice(details.url.indexOf('#'));
    if (params.length <= 1) {
      params = "";
    }
    mainWindow!.loadURL(resolveHtmlPath('index.html') + params);
    callback({cancel: false});
  });

  // Hack to fix keycloak-redirect being canceled.
  mainWindow.webContents.session.webRequest.onErrorOccurred((details) => {
    if (details.url.match("http://localhost/keycloak-redirect*") && details.error === "net::ERR_ABORTED") {
      setTimeout(() => {
        let params = details.url.slice(details.url.indexOf('#'));
        if (params.length <= 1) {
          params = "";
        }
        mainWindow!.loadURL(resolveHtmlPath('index.html') + params);
      }, 100)
    }
  });
```
