### ISSUE TITLE
JWT Signed with Private Key client authentication throws error (with Azure Active Directory IDP)

### ISSUE THREAD

**Issue by hakku19** [keycloak/keycloak#19425]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Getting the following error when trying OIDC with Azure Active Directory via jwt signed with private key. 
No issues when using client id and secret.
I have added the realm's rsa key's public certificate on AAD

```
2023-03-30 09:58:46 2023-03-30 01:58:46,375 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-170) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: No access_token from server. error='invalid_client', error_description='AADSTS700027: The certificate with identifier used to sign the client assertion is not registered on application. [Reason - The key was not found., Please visit the Azure Portal, Graph Explorer or directly use MS Graph to see configured keys for app Id 'asdfghjk-e4e5-4056-9978-232728290ac'. Review the documentation at https://docs.microsoft.com/en-us/graph/deployments to determine the corresponding service endpoint and https://docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=http to build a query request URL, such as 'https://graph.microsoft.com/beta/applications/bbbda549-e4e5-40f9-9945-2327de4f0dac'].
2023-03-30 09:58:46 Trace ID: 16024889-5f9b-4569-a1a6-a14ea9jk51d00
2023-03-30 09:58:46 Correlation ID: ebac3d18-50ec-44a7-bdb2-245jhdd4185ba
2023-03-30 09:58:46 Timestamp: 2023-03-30 01:58:46Z', error_uri='https://login.microsoftonline.com/error?code=700027'
2023-03-30 09:58:46 at org.keycloak.broker.oidc.OIDCIdentityProvider.verifyAccessToken(OIDCIdentityProvider.java:524)
2023-03-30 09:58:46 at org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:367)
2023-03-30 09:58:46 at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:502)
2023-03-30 09:58:46 at jdk.internal.reflect.GeneratedMethodAccessor741.invoke(Unknown Source)
2023-03-30 09:58:46 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-30 09:58:46 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-03-30 09:58:46 at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2023-03-30 09:58:46 at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
2023-03-30 09:58:46 at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
2023-03-30 09:58:46 at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
2023-03-30 09:58:46 at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2023-03-30 09:58:46 at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2023-03-30 09:58:46 at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2023-03-30 09:58:46 at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2023-03-30 09:58:46 at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2023-03-30 09:58:46 at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2023-03-30 09:58:46 at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2023-03-30 09:58:46 at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
2023-03-30 09:58:46 at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
2023-03-30 09:58:46 at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-03-30 09:58:46 at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
2023-03-30 09:58:46 at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-03-30 09:58:46 at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
2023-03-30 09:58:46 at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2023-03-30 09:58:46 at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-03-30 09:58:46 at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:71)
2023-03-30 09:58:46 at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
2023-03-30 09:58:46 at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
2023-03-30 09:58:46 at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
2023-03-30 09:58:46 at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
2023-03-30 09:58:46 at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2023-03-30 09:58:46 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2023-03-30 09:58:46 at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2023-03-30 09:58:46 at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2023-03-30 09:58:46 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-03-30 09:58:46 at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-30 09:58:46 
2023-03-30 09:58:46 2023-03-30 01:58:46,429 WARN  [org.keycloak.events] (executor-thread-170) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=aaaaaaa-aaaa-aaaa-aaaa-aaaaaaa82ba2, clientId=abcd, userId=null, ipAddress=xxx.xx.x.x, error=identity_provider_login_failure, code_id=b1a0fghdg-5df7-43bc-91de-e4733ec90546, authSessionParentId=b1adfgs9-5df7-43bc-91de-e4733ec90546, authSessionTabId=xz8Z1z13FeM

```

### Version

18.0.0

### Expected behavior

Except OIDC method to work when using jwt signed with private key

### Actual behavior

OIDC authentication using jwt signed with private key fails with error

### How to Reproduce?

1. Add an open id connect provider in KC
2. Import Azure AD well know config into it
3. Choose jwt signed with private key option
4. Choose RS256 algorithm
5. Save
6. In Azure AD create the KC application as a client and upload the RSA certificate for from Keycloak's realm->keys page
7. Go to http://localhost:8180/realms/glx-connect/protocol/openid-connect/auth?client_id=<client-id-goes-here>
8. Click on the SSO(or the name given when setting up OIDC) button
9. This should prompt you to login to Azure AD, so login, click submit and will see the error - `Unexpected error when authenticating with identity provider`
10. Check KC logs and can see the detailed error.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. Anyone is welcome to send the PR with fixing it. See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by amitmun** [comment]
Looks like this is finally coming in v24!
https://github.com/keycloak/keycloak/issues/12946

**Comment by sschu** [comment]
@amitmun Thanks for pointing to the other issue. I will go ahead and close this as a duplicate. Feel free to reopen @hakku19 if this is not fixed with KC24.
