### ISSUE TITLE
Flaky test: org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest#cancelRegistration

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#19435]
## org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest#cancelRegistration
[Keycloak CI - WebAuthn IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/4562307896/jobs/8049586406) / [Pull Request #19429](https://github.com/keycloak/keycloak/pull/19429)

```
java.lang.AssertionError: Expected SigningInPage but was Sign in to test (https://localhost:8543/auth/realms/test/login-actions/authenticate?client_id=account-console&tab_id=IADh2n15_iU)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.page.AbstractPage.assertCurrent(AbstractPage.java:110)
	at jdk.internal.reflect.GeneratedMethodAccessor618.invoke(Unknown Source)
...
```

**Comment by stianst** [comment]
Closing since this has only happened once
