### ISSUE TITLE
ClientPolicies: Deserialization of `MultivaluedString ` config property doesn't work properly between new admin-ui and backend

### ISSUE THREAD

**Issue by patrick-primesign** [keycloak/keycloak#19469]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Hi!

Deserialization of `MultivaluedString ` config property doesn't work properly between new admin-ui and backend in case of ClientPolicies.

```
2023-03-31 11:25:43,818 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-4) Uncaught server error: java.lang.IllegalArgumentException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Role1##Role2')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.keycloak.services.clientpolicy.condition.ClientRolesCondition$Configuration["roles"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324)
        at org.keycloak.services.clientpolicy.ClientPoliciesUtil.getConditionProvider(ClientPoliciesUtil.java:369)
        at org.keycloak.services.clientpolicy.ClientPoliciesUtil.getEnabledClientPolicies(ClientPoliciesUtil.java:345)
        at org.keycloak.services.clientpolicy.DefaultClientPolicyManager.doPolicyOperation(DefaultClientPolicyManager.java:69)
        at org.keycloak.services.clientpolicy.DefaultClientPolicyManager.triggerOnEvent(DefaultClientPolicyManager.java:61)
```

### Version

21.0.2

### Expected behavior

Should be able to use `MultivaluedString` in the admin-ui without breaking the configuration or the admin-ui.

### Actual behavior

Sometimes (!) there are exceptions when there is access to `MultivaluedString` config properties in the backend.

### How to Reproduce?

master realm (for easier reproduction, but only do this in a test-environment) -> Realm-Settings -> Client policies -> Policies -> create a new Policy -> add condition client-roles -> add more than 1 role -> save and try again to login into the admin-ui.

or copy following json in the JSON editor of the policies and save it and try to login again into the admin-ui.
```
[
  {
    "name": "Test",
    "description": "",
    "enabled": true,
    "conditions": [
      {
        "condition": "client-roles",
        "configuration": {
          "is-negative-logic": false,
          "roles": "Role1##Role2"
        }
      }
    ],
    "profiles": []
  }
]
```

**Comment by ssilvert** [comment]
I have verified this using a test realm.  You can recreate this bug using just one role.

The problem is that the new admin UI is not sending the roles as an array.

Old console payload looks like this:
`{"policies":[{"name":"test","description":"","enabled":true,"conditions":[{"condition":"client-roles","configuration":{"is-negative-logic":false,"roles":["xxx"]}}],"profiles":[]}]}`

New console payload looks like this:
`{"policies":[{"name":"test","description":"","enabled":true,"conditions":[{"condition":"client-roles","configuration":{"is-negative-logic":false,"roles":"xxx"}}],"profiles":[]}]}`
