### ISSUE TITLE
Account Console "no access" with openldap user federation

### ISSUE THREAD

**Issue by andreasgremm** [keycloak/keycloak#19593]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

I use LDAP (openldap) user federation.
Accessing the account console leads to the "no access" error after user authenticated successfully.
Everything else (authentication, role mapping, ...)seems to work.
New users can register, role assignments can be done, ...

### Version

21.0.2

### Expected behavior

Account Information should be shown to the user.

### Actual behavior

User is able to login to the account console but then he gets an "error screen" stating that he has no access rights and should talk to an administrator.

### How to Reproduce?

Create a new realm.
Add user federation to the new realm with an openldap server.
Let a user from the federated user store login to the account console.
See the error screen.

### Anything else?

I have a lengthy logfile which I can provide.
One sequence in this logfile is:
```
2023-04-07 18:04:36,001 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-22) Error response 403: org.keycloak.services.ForbiddenException
        at org.keycloak.services.managers.Auth.requireOneOf(Auth.java:91)
        at org.keycloak.services.resources.account.AccountRestService.account(AccountRestService.java:141)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

                                                                                                                                           1837,9        96%

**Comment by ssilvert** [comment]
This doesn't look like a UI bug to me.  Switching to core.

**Comment by andreasgremm** [comment]
Hi Ricardo,

This is a screenshot form the user details:

Does this help?

Kind regards, Andreas

￼



￼

**Comment by rmartinc** [comment]
Hi @andreasgremm!

I don't see what you have attached, probably you need to access the github issues to attach it directly. But you need to access the role mapping tab, not the details. Check there the user has those roles assigned (uncheck the Hide inherited roles checkbox).

**Comment by andreasgremm** [comment]
![PastedGraphic-1](https://github.com/keycloak/keycloak/assets/10307483/f3c02b80-9072-4e59-bce7-39463a910960)
![PastedGraphic-2](https://github.com/keycloak/keycloak/assets/10307483/c0cb16de-eec0-4c3d-9716-fdc89ba62db0)
Hi ,
sure the role mapping tab :-). 

Attached the screenshots.

**Comment by rmartinc** [comment]
This user has the account manage-account and view-profile, so he should have access to the account application.

**Comment by rmartinc** [comment]
@andreasgremm I did a quick test and with apacheds as LDAP I have no problem to enter in the account console with users imported to keycloak. There should be something more here.

We need clear reproduction steps. Download a fresh keycloak 21.1.1 and in a new realm configure ldap taking detailed notes of the configuration you are doing. If you see the same error at the end, send us the details of your steps.

**Comment by mposolda** [comment]
@rmartinc Thanks for checking this!

Seems like a mis-configuration rather than Keycloak issue, (also even if it is proved to be bug, it doesn't look critical or like a regression), so preliminary adding it to Backlog.

**Comment by andreasgremm** [comment]
Hi,I will check a new installation and I am a friend of finding the error.Is there anything else important?The environment I have build is for testing purposes only.I don’t use ssl neither with keycloak nor between keycloak and openldap.When I call the account console it looks good for microseconds and then it changes to the error screen.Another observation is with the access token when I use it in another application. The token is always declared as expired. I need to check the validity without expiration checking.Is the expiration issue the reason for not being able to access the account console as a user?Regards,AndreasVon meinem Mobiltelefon gesendetAm 19.05.2023 um 11:21 schrieb Marek Posolda ***@***.***>:﻿
@rmartinc Thanks for checking this!
Seems like a mis-configuration rather than Keycloak issue, (also even if it is proved to be bug, it doesn't look critical or like a regression), so preliminary adding it to Backlog.

**Comment by andreasgremm** [comment]
After a long time with no chance to test further, today I ended up in the following findings:

- existing realm: login to account console not working

- upgraded to Keycloak 22.0.x (latest docker image at quay.io).
- created new realm with apacheds as user store
- login to account console worked

- created new realm with same openldap-server as user store as existing (not working) realm
- login to account console worked

- modified existing (not working) realm to be exactly the same as the new realm with openldap
- login to account console still not working 
=> there must have been something burned into the database which leads to the problem

=> As soon as I define a role-mapper in the new openldap-user based realm, which maps groups from ldap to roles, the login to the account console is no longer working. The default-role-<realmname> is no longer assigned to the user which leads to a denial of login to the account console as documented.
     As soon as the role-mapper is deleted the login to the account console is working again.

Question: is there a method to get the default-role-<realmname> assigned to the users alongside with a role-mapper which adds ldap-groups as roles to the users?

Kind regards,
Andreas

**Comment by rmartinc** [comment]
I'm closing this @andreasgremm as it's quite old and we don't know how to exactly reproduce it. If you find it is really a bug please re-open it or file a new issue.

**Comment by tamama** [comment]
I confirm this is not an issue for Keycloak 24 on my side.
