### ISSUE TITLE
NPE during /required-action API call - Cannot invoke "org.keycloak.models.UserModel.credentialManager()" because "user" is null

### ISSUE THREAD

**Issue by roman-svystun** [keycloak/keycloak#19941]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

During our performance tests a part (like 1-2%) of the user registration flows fail with the NullPointerException - 

```
keycloak-97f9465bd-nk6kj keycloak 2023-04-25 11:59:05,970 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-79) 
   Uncaught server error: java.lang.NullPointerException: 
   Cannot invoke "org.keycloak.models.UserModel.credentialManager()" because "user" is null
at org.keycloak.credential.PasswordCredentialProvider.getPassword(PasswordCredentialProvider.java:52)
at org.keycloak.authentication.requiredactions.UpdatePassword.evaluateTriggers(UpdatePassword.java:68)
at org.keycloak.services.managers.AuthenticationManager.evaluateRequiredAction(AuthenticationManager.java:1407)
at org.keycloak.services.managers.AuthenticationManager.lambda$evaluateRequiredActionTriggers$22(AuthenticationManager.java:1378)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
at org.keycloak.services.managers.AuthenticationManager.evaluateRequiredActionTriggers(AuthenticationManager.java:1378)
at org.keycloak.services.managers.AuthenticationManager.actionRequired(AuthenticationManager.java:1159)
at org.keycloak.services.managers.AuthenticationManager.nextActionAfterAuthentication(AuthenticationManager.java:1014)
at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:1014)
at org.keycloak.services.resources.LoginActionsService.requiredActionGET(LoginActionsService.java:996)
at jdk.internal.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
```

The Keycloak version is 21.1.0. The same issue can be observed in the 21.0.2, 21.0.1.

We use JMeter, the test plan is run from Windows agents. We are not able to reproduce the issue if the same JMeter test plan is executed from Linux machines. Maybe, there are slight differences in how random values are generated for registration requests. But, in any case, clients should not be getting 500 responses.

Because of the change of `terms_and_conditions` to `TERMS_AND_CONDITIONS` we can't easily verify if Keycloak version 20 has the same issue. But, as far as we can tell, back in the Keycloak 19, 20 days we never saw such an error.

Keycloak is run in a Kubernetes cluster with `cache-stack=kubernetes` and has 10 pods.

These are the enabled required actions:

![image](https://user-images.githubusercontent.com/20768687/234295662-5d9eadeb-25db-4f19-be0e-cf8ed27e4070.png)

### Version

21.1.0, 21.0.x

### Expected behavior

API calls to `https://auth-stg.liaisoncas.com/realms/realm/login-actions/required-action?execution=TERMS_AND_CONDITIONS&client_id=yyyy&tab_id=xx` should not fail with `NullPointerException`.
If user is not unauthorized, or not found, a 401 response should be returned.

### Actual behavior

API calls to `https://auth-stg.liaisoncas.com/realms/realm/login-actions/required-action?execution=TERMS_AND_CONDITIONS&client_id=yyyy&tab_id=xx` return status code 500 with the `NullPointerException` in the logs.

### How to Reproduce?

Run JMeter registration, required-action tests from a Windows machine.

### Anything else?

Infinispan configuration - 

```xml
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="90000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="90000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="90000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="7200000"/>
            <memory max-count="40000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
```

JVM Arguments customizations:

```
JAVA_OPTS="-XX:+UseContainerSupport -XX:InitialRAMPercentage=40 -XX:MaxRAMPercentage=97 -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512M -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
JAVA_OPTS_APPEND="--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED"
```

Upd: 
A possible workaround for us is to add a retry with a delay here - https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1156

Something like 

```java
UserModel user = authSession.getAuthenticatedUser();
if (user == null) {
    int count = 0;
    while ((user = authSession.getAuthenticatedUser()) == null && count < 2) {
        count++;
        logger.warn("User not found, attempting to search for it again");
        try {
            Thread.sleep(count * 50);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
```
With a 50ms delay, users are always found by the infinispan's `AuthenticationSessionAdapter`.

**Comment by martin-kanis** [comment]
@roman-svystun Thank you for the report! Do you know if it is also happening with only one pod? Can you also share exactly what steps are you executing during the  user registration flows?

**Comment by roman-svystun** [comment]
@martin-kanis 
At this point I cannot tell if the NPE happens with a single pod. We would need to test for that. But I think it does not happen.

The NPE happens right after calling
`POST realms/mi-realm/login-actions/registration...`
which responds with a 302 redirect and a location.

JMeter follows the redirect immediatelly, 
`GET realms/mi-realm/login-actions/required-action?execution=TERMS_AND_CONDITIONS...`

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L996

By immediatelly, I mean the GET call is made within millis after the POST. 
Keycloak pods are hidden behind a Traefik LB, so that the `GET` from redirect hits a different KC pod, before users were synchronized from the other KC pod/Inifinispan node (I think so).

This line
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1156

would call this
https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/AuthenticationSessionAdapter.java#L285

and a `null` would be returned by `session.users().getUserById(getRealm(), entity.getAuthUserId())`.

If we wait for up to 50ms, the user will be found.

**Comment by martin-kanis** [comment]
I am wondering if sticky sessions would help here. So a consequent request would end up on the same pod.  We don't want to add any delays to our code to allow synchronization. Maybe rather a null check and return more appropriate error message.
