### ISSUE TITLE
authenticator javaScript Provider always failed the login, user context is lost and break the login

### ISSUE THREAD

**Issue by Cracky5457** [keycloak/keycloak#20009]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I have a JavaScript provider, packaged in a jar and well usable on the keycloak instance

This provider use the variable `user` to get username and to check role with user.hasRole(role)

Unfortunately the user variable is always null. Even with a very basic script added to the default Browser flow. 

We was on keycloak 15 before and the script was exactly the same and working well, 
[bug-report-script.csv](https://github.com/keycloak/keycloak/files/11347350/bug-report-script.csv)

Other variable such as `context`, `client` works well

This is the output of my scripts we can see in logs that there is no probleme to use `client` but `user` is null

```
2023-04-27 21:34:56,173 INFO  [org.keycloak.authentication.authenticators.browser.ScriptBasedAuthenticator] (executor-thread-7) user null
2023-04-27 21:34:56,197 INFO  [org.keycloak.authentication.authenticators.browser.ScriptBasedAuthenticator] (executor-thread-7) Checking access to authentication for client 'My Website' through mandatory role 'feature:authenticate' for user 'anonymous'
2023-04-27 21:34:56,203 ERROR [org.keycloak.authentication.authenticators.browser.ScriptBasedAuthenticator] (executor-thread-7) org.keycloak.scripting.ScriptExecutionException: Could not execute script 'Check Feature Authenticate' problem was: TypeError: null has no such function "hasRole" in <eval> at line number 44
2023-04-27 21:34:56,203 WARN  [org.keycloak.services] (executor-thread-7) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
```

Also, in the the keycloak log I have

```
2023-04-28 16:54:38,525 WARN  [org.keycloak.events] (executor-thread-9) type=LOGIN_ERROR, realmId=hbp, clientId=xwiki, userId=null, ipAddress=127.0.0.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=https://wiki-dev.ebrains.eu/, code_id=dae8b423-f4cf-47aa-884f-84c2435dc579, response_mode=query
```

We can see that somehow, just switching the JavascripProvider from disabled to required and the user context is lost when going through the script

### Version

21.1.1

### Expected behavior

User variable should not be null in a javaScript Provider used in the authentication browser flow

### Actual behavior

is always null

### How to Reproduce?

Edit :You can use the docker image and instruction provided in the first answer of this issue

Or ...

- Build a jar with an authenticator 'check-role.js' JavaScript following javaScript Provider requirement https://www.keycloak.org/docs/latest/server_development/index.html#_script_providers

You can use the official demo one and just check the `user` variable null
https://github.com/keycloak/keycloak/blob/main/services/src/main/resources/scripts/authenticator-template.js

Or you can use mine in attachement, replace `csv`by `js`. Basically my scripts just check presence of a specific role for a user using `user.hasRole(role)` so this role need to be added in the client and assign to the user

- Duplicate the authenticator Browser flow
- Add Step at the very end with our script
- bind the flow to browser
- try to login using the test client in real test, this will fail in null pointer exception when the script use the `user` variable

### Anything else?

if there is no workaround, it is a critical/blocking issue for our company and a no go for the upgrade unfortunately.

**Comment by Cracky5457** [comment]
This issue becme more serious, I even wonder if it's a missconfiguration issue from somehow

I ran the last official tar.gz (21.1.1) 

I removed scripts and any custom providers, I'm just running a raw keycloak (but not with a fresh DB) with scripts not enabled and empty providers folder

When I login myself using the standard flow on our website it works.

If I try to get an access token with postman (very same client than on our website) it failed 

The code is well requested, then 

![Capture d’écran 2023-04-28 à 16 28 10](https://user-images.githubusercontent.com/12050544/235176179-690204c6-0584-4b36-ae7f-69fada33667c.png)

And on the server there is this warning

````2023-04-28 16:15:03,999 WARN  [org.keycloak.events] (executor-thread-13) type=CODE_TO_TOKEN_ERROR, realmId=hbp, clientId=xwiki, userId=null, ipAddress=82.66.17.213, error=invalid_client_credentials, grant_type=authorization_code````

Maybe it's somehow related to my Script Provider issue. userId is lost somewhere in the flow, I didn't forget to provide any username or something, with postman it open a regular browser login page, if you use postman you can try from Authorization tab and selecting OAuth 2.0

**Comment by Cracky5457** [comment]
I made a dockerfile with the official 21.1.1 release and 2 very basic javaScript provider into so you can reproduce this issue really easily

[kc-docker-with-js-provider.zip](https://github.com/keycloak/keycloak/files/11365681/kc-docker-with-js-provider.zip)

Step to reproduce :
- Download the zip above
- Build the image as you wish `docker build -t keycloak-js-provider:21.1.1 . --platform linux/amd64 --no-cache`
- Run it `docker run --name keycloak-js-provider -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin keycloak-js-provider:21.1.1 start-dev --http-relative-path /auth`
- Create a realm call "test" with the providen json (it's an empty realm with a test client a "toto" user and a role "feature:authenticate" to check in the jS Provier script
- Check that the JavaScript Provider Browser Flow is active and check the presence of the 2 javaScript provider (if absent, juste clone the browser flow, add the "Keycloak Authenticator Template" "Check Feature Authenticate" at the end of the flow and bindthis flow to browser

Then initiate a login with the user "toto" and password "toto"

Personnaly I'm using postman to easily trigger a login but any web resource triggering the browser flow will be nice 

You should end with this in the logs of your running local docker container 

```
2023-05-01 13:42:41,122 INFO  [org.keycloak.authentication.authenticators.browser.ScriptBasedAuthenticator] (executor-thread-30) Keycloak Authenticator Template trace auth for: anonymous
2023-05-01 13:42:41,141 WARN  [org.keycloak.services] (executor-thread-30) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1034)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:888)
	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:153)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:363)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:219)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.access$300(AuthorizationEndpoint.java:69)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint$1.runInternal(AuthorizationEndpoint.java:140)
	at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:67)
	at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:44)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:299)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.processInRetriableTransaction(AuthorizationEndpoint.java:132)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-05-01 13:42:41,198 WARN  [org.keycloak.events] (executor-thread-30) type=LOGIN_ERROR, realmId=e48ab7c0-0b7b-43d2-8785-ff2c6defd9ba, clientId=test, userId=null, ipAddress=172.17.0.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=http://localhost:8080, code_id=b87d81da-2a97-476e-af64-6916a122ff68, response_mode=query
```

**Comment by bonnm** [comment]
Mybe it has to do with some chanages in the username password form authenticators.

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/UsernamePasswordForm.java

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java

https://github.com/keycloak/keycloak/commit/d9c8cb30a5ec2f4a9589cdbfe50bf8c35d9853ad#diff-7868413639a878442407ec04374badcd7ee6abe2d4fe13315db437d6b7ea9c8b

Have to tried to move the Cookie and Forms authenticator (both marked as alternative) to a custom subflow (top level, marked as required) and add you script authententicator at the end of the flow (also top level, marked as required)?

**Comment by Cracky5457** [comment]
Thans @bonnm for the answer, indeed the commit you show could be the cause probably here

```
            return user;
        } else {
            // Normal login. In this case this authenticator is supposed to establish identity of the user from the provided username
            context.clearUser();
            return getUserFromForm(context, inputData);
        }
```

Unfortunately I tried to move my JavaScript auth provider to the top of the browser flow but it didn't changed anything. About puttin cookie and form authenticator in a custom subflow I didn't found how to do it so far. I'm still investigating.

**Comment by bonnm** [comment]
Your custom JS autrhenticator must be ordered after a context-establishing authenticator, try something like this (old console, my look different in new admin console)

![grafik](https://user-images.githubusercontent.com/105660959/236126648-0187527f-b42a-4339-b82a-3cf00f36eed1.png)

**Comment by Cracky5457** [comment]
Thanks for the workaround @bonnm indeed it works like this now

![Capture d’écran 2023-05-05 à 15 35 33](https://user-images.githubusercontent.com/12050544/236472814-146f625f-e37d-4ef1-ae2b-8f901933a73f.png)

They have to be directly under Username Password Form in a separate alternative flow.

Honestly I still think it should be consider as a regression from Keycloak 15. This imply a lot of limitation.

For exemple my scripts is checking some roles/email validation (we revalidate email on regular period for security), and here in my screenshot, all theses steps are ignored if there is an active session in the cookie and I don't like that, user having or not a role that is require as login can change in real time and the Form auth and so the check will be bypassed if there is already a cookie session.

**Comment by mposolda** [comment]
I've sent PR for clearify docs a bit about script authenticator.

@Cracky5457 Note that if you want your script authenticator to be always triggered at the end of the authentication (even during SSO re-authentication), it may be good to configure your flow for example like this:
```
- User-authentication-subflow REQUIRED
-- Cookie ALTERNATIVE
-- Identity-provider-redirect ALTERNATIVE
... other authenticators here ...
- Your-Script-Authenticator REQUIRED
```

For easier clarification, you can think about REQUIRED as logical condition `and` and about ALTERNATIVE as logical condition `or`. So perhaps you probably want something like this:
(Cookie OR Identity-provider-redirect OR (usernameAuth AND emailVerification)) AND check-is-guest-user

**Comment by Cracky5457** [comment]
@mposolda 

- User-authentication-subflow REQUIRED
-- Cookie ALTERNATIVE
-- Identity-provider-redirect ALTERNATIVE
... other authenticators here ...
- Your-Script-Authenticator REQUIRED

As explained in the ticket, if you put a javaScript authenticator at the end of the flow, the variable "user" is always null ans the script crash. Isn't it a regresssion ? This was working in version 15, now to have the user context it needs to be put after Username Password form and in that case your exemple is no longer valid.

**Comment by Cracky5457** [comment]
Thanks for the answer :) After many attempts with all my scripts I got it working finally. 

Indeed we need to be very careful on the schema, the tree visualisation help a lot, nice feature

**Comment by OberhambergerJohannes** [comment]
> Thanks for the answer :) After many attempts with all my scripts I got it working finally.
> 
> Indeed we need to be very careful on the schema, the tree visualisation help a lot, nice feature

Could you please clarify your answer? Could you please add a screenshot as I am currently facing the same issue?
