### ISSUE TITLE
Processing of env variable references in config file broken

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#20032]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

it seems that the env variables handling in keycloak.conf is broken in 21.1.1 - env variable references are not resolved anymore.

The following entry in keycloak.conf worked fine with 20.0.5:
````
   log-level=INFO,com.foo.bar:${FOO_LOG_LEVEL:info}
````
but fails in 21.1.1 with an error:
````
2023-04-28 14:42:47,958 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2023-04-28 14:42:47,958 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Invalid log category format: com.foo.bar:"${FOO_LOG_LEVEL:INFO}". The format is 'category:level' such as 'org.keycloak:debug'. The format is 'category:level' such as 'org.keycloak:debug'.
	at org.keycloak.quarkus.runtime.Messages.invalidLogCategoryFormat(Messages.java:65)
	at org.keycloak.quarkus.runtime.configuration.mappers.LoggingPropertyMappers.resolveLogLevel(LoggingPropertyMappers.java:178)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(PropertyMapper.java:208)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.getConfigValue(PropertyMapper.java:139)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.getValue(PropertyMappers.java:47)
	at org.keycloak.quarkus.runtime.configuration.PropertyMappingInterceptor.getValue(PropertyMappingInterceptor.java:51)
````

I think the problem was introduced by this commit: https://github.com/keycloak/keycloak/commit/9874da150e5003cf1b19bd2ab95f097cf3ffe4f0

### Version

21.1.1

### Expected behavior

Env Variable references should be correctly resolved or use the provided default.

### Actual behavior

Server fails to start with env variable references in keycloak.conf file.

### How to Reproduce?

Add a config entry like `log-level=INFO,com.foo.bar:${FOO_LOG_LEVEL:info}` to keycloak.conf and try to start the server.

**Comment by thomasdarimont** [comment]
I think this would be a good candidate for a 21.1.2 release.

**Comment by vmuzikar** [comment]
@thomasdarimont Thanks, I was able to reproduce and planned it for 21.1.2.

**Comment by vmuzikar** [comment]
Reopening for backport.
