### ISSUE TITLE
Keycloak docker image corrupts itself after a few hours of use

### ISSUE THREAD

**Issue by NicoloLazzaroni** [keycloak/keycloak#20041]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Hello,

I have a problem with keycloak latest docker image.

I run multiple keycloak instances over docker and had this issue 4 times in a week.

The images run perfectly until a day or so passes and then, when restarted after this yime passes, produce this error:

```
keycloak-public-1 | ERROR: Failed to run 'build' command.
keycloak-public-1 | ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-js-adapter-jar-21.1.1.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-js-adapter-jar-21.1.1.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-js-adapter-jar-21.1.1.jar
keycloak-public-1 | java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "value" is null
keycloak-public-1 |     at io.smallrye.config.ExpressionConfigSourceInterceptor.escapeDollarIfExists(ExpressionConfigSourceInterceptor.java:89)
keycloak-public-1 |     at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:61)
keycloak-public-1 |     at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:42)
keycloak-public-1 |     at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
keycloak-public-1 |     at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
keycloak-public-1 |     at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
keycloak-public-1 |     at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:324)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.printErrorHints(ExecutionExceptionHandler.java:102)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.dumpException(ExecutionExceptionHandler.java:92)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.error(ExecutionExceptionHandler.java:75)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.handleExecutionException(ExecutionExceptionHandler.java:45)
keycloak-public-1 |     at picocli.CommandLine.execute(CommandLine.java:2088)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
keycloak-public-1 |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak-public-1 |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak-public-1 |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak-public-1 |     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak-public-1 |     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
keycloak-public-1 |     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
keycloak-public-1 exited with code 1
```

As I use docker-compose I tried to delete the container and re-compose it but the error still occurs.

The only way to solve it is to delete keycloak's docker image and redownload it with docker-compose.

PS. This corruption seems to happen randomly and is not related to the restarts themselves, as I could restart docker and/or the keycloak containers with no problems before a day or so passed.

This is one of my docker-compose files:

```
version: '3'

services:
  keycloak:
      container_name: keycloak-public-1
      image: quay.io/keycloak/keycloak:latest
      networks:
        - keycloak
      command: start \
        --db=mariadb --features=token-exchange \
        --db-url=jdbc:mariadb://CENSORED:CENSORED/CENSORED --db-username=CENSORED --db-password='CENSORED' \
        --proxy=edge --features-disabled="admin-api,admin2" \
        --hostname-strict=false --spi-sticky-session-encoder-infinispanshould-attach-route=false \
        --spi-theme-welcome-theme=custom
      volumes:
       - /etc/keycloak/themes:/opt/keycloak/themes
      ports:
       - "127.0.0.1:CENSORED:8080"
networks:
  keycloak:
```

### Version

21.1.1

### Expected behavior

Keycloak should start normally.

### Actual behavior

Keycloak pops this error up:

```
keycloak-public-1 | ERROR: Failed to run 'build' command.
keycloak-public-1 | ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-js-adapter-jar-21.1.1.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-js-adapter-jar-21.1.1.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-js-adapter-jar-21.1.1.jar
keycloak-public-1 | java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "value" is null
keycloak-public-1 |     at io.smallrye.config.ExpressionConfigSourceInterceptor.escapeDollarIfExists(ExpressionConfigSourceInterceptor.java:89)
keycloak-public-1 |     at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:61)
keycloak-public-1 |     at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:42)
keycloak-public-1 |     at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
keycloak-public-1 |     at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
keycloak-public-1 |     at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
keycloak-public-1 |     at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:324)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.printErrorHints(ExecutionExceptionHandler.java:102)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.dumpException(ExecutionExceptionHandler.java:92)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.error(ExecutionExceptionHandler.java:75)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.handleExecutionException(ExecutionExceptionHandler.java:45)
keycloak-public-1 |     at picocli.CommandLine.execute(CommandLine.java:2088)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
keycloak-public-1 |     at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
keycloak-public-1 |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak-public-1 |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak-public-1 |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak-public-1 |     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak-public-1 |     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
keycloak-public-1 |     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
keycloak-public-1 exited with code 1
```

### How to Reproduce?

Run keycloak for a day or so and restart it.

### Anything else?

I am using docker-compose to run my containers.

These are the versions:
```

Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:32:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by mposolda** [comment]
Seems like this may be related to quarkus distribution, so sending to "cloud-native" team for now.

**Comment by mabartos** [comment]
@NicoloLazzaroni Thanks for reporting this issue. 

The issue should already be resolved in the main branch as it was related to the SmallRye Config included in the Quarkus. The fix was present in the later version of Quarkus, which wasn't included in Keycloak 21.1.1.
You can check the related PR here:  https://github.com/smallrye/smallrye-config/pull/907

There's also a PR related to the config values evaluation, which edits the order of used config values interceptors, thus the issue will completely disappear. 
You can check the PR here: #20462 

The fix should be included in the next release of Keycloak.

**Comment by NicoloLazzaroni** [comment]
Sadly a similar error now happears:

```
Jul 05 22:21:51 node2 docker-compose[2643983]: keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-account-ui-21.1.2.jar does not exist
Jul 05 22:21:51 node2 docker-compose[2643983]: keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-account-ui-21.1.2.jar
```

**Comment by sschu** [comment]
@NicoloLazzaroni I assume this will be in KC22.
