### ISSUE TITLE
Upgrading to Infinispan 14.0.8

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20067]
### Description

Infinispan 14.0.8 is the latest release. When attempting an upgrade as part of #20011 there was an exception 

```
Caused by: java.lang.RuntimeException: Component org.keycloak.models.KeycloakSessionFactory is already registered
    at org.infinispan.factories.impl.BasicComponentRegistryImpl.registerComponent(BasicComponentRegistryImpl.java:368)
    at org.infinispan.factories.AbstractComponentRegistry.registerComponentInternal(AbstractComponentRegistry.java:133)
    at org.infinispan.factories.AbstractComponentRegistry.registerComponent(AbstractComponentRegistry.java:125)
    at org.infinispan.factories.AbstractComponentRegistry.registerComponent(AbstractComponentRegistry.java:117)
    at org.keycloak.models.sessions.infinispan.initializer.InfinispanCacheInitializer.initCache(InfinispanCacheInitializer.java:68)
    at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$6.run(InfinispanUserSessionProviderFactory.java:342)
```

This issue is about to investigate it.

### Motivation

To be able to upgrade to the latest version of Infinispan to benefit from the latest bug fixes. The exception shown above might prevent this.

**Comment by ahus1** [comment]
The exception has changed from a `CacheConfigurationException` to a `RuntimeException`. The pull request will revisit this to avoid handling the exception.
