### ISSUE TITLE
KeyCloak unable to build FIPS package on deployment.

### ISSUE THREAD

**Issue by ramneekers** [keycloak/keycloak#20065]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dependencies

### Describe the bug

Based on the instructions provided here at https://www.keycloak.org/server/fips, we created a Dockerfile that incorporates the necessary dependencies for FIPs. We made three edits to the example file:
- the dockerfile downloads FIPS binaries from maven on build
- the security file is a one-liner, so it's written to via bash
- we use "start" instead of pre-building the server

Here's the Dockerfile provided.
```
FROM quay.io/keycloak/keycloak:latest as builder

# Install BouncyCastle FIPS packages directly from maven.
# Check the pom.xml file for KeyCloak to confirm that these versions are in use.
ARG BCFIPS_VERSION=1.0.2.3
ARG BCTLSFIPS_VERSION=1.0.14
ARG BCPKIXFIPS_VERSION=1.0.7
ARG MAVEN_HOME=https://repo1.maven.org/maven2

ADD $MAVEN_HOME/org/bouncycastle/bc-fips/$BCFIPS_VERSION/bc-fips-$BCFIPS_VERSION.jar /opt/keycloak/providers/
ADD $MAVEN_HOME/org/bouncycastle/bctls-fips/$BCTLSFIPS_VERSION/bctls-fips-$BCTLSFIPS_VERSION.jar /opt/keycloak/providers/
ADD $MAVEN_HOME/org/bouncycastle/bcpkix-fips/$BCPKIXFIPS_VERSION/bcpkix-fips-$BCPKIXFIPS_VERSION.jar /opt/keycloak/providers/

RUN echo "fips.provider.7=XMLDSig" > /opt/keycloak/conf/kc.java.security

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

WORKDIR /opt/keycloak

ENTRYPOINT [ "bin/kc.sh", "start", "--features=fips", '-Djava.security.properties=/opt/keycloak/conf/kc.java.security']
```

There's a `p12` keystore that is injected later into the container.
Deploying this container causes the following failure:

```
< SEVERAL LINES OF DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] >
023-05-01 22:42:59,102 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[/ runtime=true resources=null] to QuarkusClassLoader Deployment Class Loader: PROD
ERROR: Failed to run 'build' command.
ERROR: java.io.IOException: Failed to create a new filesystem for /opt/keycloak/lib/../providers/bc-fips-1.0.2.3.jar
ERROR: Failed to create a new filesystem for /opt/keycloak/lib/../providers/bc-fips-1.0.2.3.jar
ERROR: /opt/keycloak/lib/../providers/bc-fips-1.0.2.3.jar
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "value" is null
    at io.smallrye.config.ExpressionConfigSourceInterceptor.escapeDollarIfExists(ExpressionConfigSourceInterceptor.java:89)
    at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:61)
    at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:42)
    at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
    at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
    at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
    at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:324)
    at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.printErrorHints(ExecutionExceptionHandler.java:102)
    at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.dumpException(ExecutionExceptionHandler.java:92)
    at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.error(ExecutionExceptionHandler.java:75)
    at org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler.handleExecutionException(ExecutionExceptionHandler.java:45)
    at picocli.CommandLine.execute(CommandLine.java:2088)
    at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
    at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
    at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
    at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

### Version

latest

### Expected behavior

The container should be able to successfully load .jar files from /opt/keycloak/providers.

### Actual behavior

The container can't find a value to create a filesystem for /opt/keycloak/providers.

### How to Reproduce?

Build the Dockerfile into an image, optionally add a keystore, and deploy the container.

**Comment by ramneekers** [comment]
Issue discovered in BUILD. Linux user `keycloak` did not own downloaded binaries. After replacing `ADD` with `ADD --chown=keycloak:keycloak`, issue was fixed.
