### ISSUE TITLE
Keycloak 21.1.1: kcadm.sh : Exception in thread "main" java.lang.NullPointerException on startup

### ISSUE THREAD

**Issue by souravs17031999** [keycloak/keycloak#20120]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

Hi, 

I am running keycloak admin cli in docker by pulling JAR from https://repo1.maven.org/maven2/org/keycloak/keycloak-admin-cli/21.1.1/keycloak-admin-cli-21.1.1.jar and starting up the script kcadm.sh and it throws the following error on startup : 

```
Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "array" is null
at java.base/java.util.Arrays.stream(Arrays.java:5427)
at java.base/java.util.stream.Stream.of(Stream.java:1426)
at org.keycloak.client.admin.cli.util.ClassLoaderUtil.resolveClassLoader(ClassLoaderUtil.java:40)
at org.keycloak.client.admin.cli.KcAdmMain.main(KcAdmMain.java:46)
```

### Version

21.1.1

### Expected behavior

kc admin client script should start normally.

### Actual behavior

kc admin client script fails at startup.

### How to Reproduce?

1. Pull the JAR from https://repo1.maven.org/maven2/org/keycloak/keycloak-admin-cli/21.1.1/keycloak-admin-cli-21.1.1.jar
2. execute the JAR using kcadm.sh script.

### Anything else?

I tested with openjdk-11 and openjdk-17 and getting same issue.

**Comment by souravs17031999** [comment]
I found root cause, I was picking only the JARS (keycloak-admin-cli-<version>.jar) for my setup but since KC 21, now you also require some JARS in client/lib as per init startup script, so this was failing.

I will fix this on my end.

closing this.
