### ISSUE TITLE
Calling introspect endpoint with revoked refresh token throws NPE

### ISSUE THREAD

**Issue by dpulrichth** [keycloak/keycloak#20174]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

Attempting to use the introspect endpoint on a revoked refresh token leads to an exception and subsequent HTTP 400 error.

```
{
    "error": "invalid_request",
    "error_description": "Failed to introspect token."
}
```

Introspection works for access tokens (both active and revoked) and for active refresh tokens.

### Version

21.0.2

### Expected behavior

Revoked refresh tokens can be introspected.

### Actual behavior

Revoked refresh tokens cannot be introspected.

### How to Reproduce?

1. Get a refresh token
2. Revoke it using the /protocol/openid-connect/revoke endpoint
3. Introspect the revoked refresh token using the /protocol/openid-connect/token/introspect endpoint

### Anything else?

```
java.lang.RuntimeException: Error creating token introspection response.
	at org.keycloak.protocol.oidc.AccessTokenIntrospectionProvider.introspect(AccessTokenIntrospectionProvider.java:96)
	at org.keycloak.protocol.oidc.endpoints.TokenIntrospectionEndpoint.introspect(TokenIntrospectionEndpoint.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.UserSessionModel.getAuthenticatedClientSessionByClient(String)" because "userSession" is null
	at org.keycloak.protocol.oidc.TokenManager.validateTokenReuseForIntrospection(TokenManager.java:319)
	at org.keycloak.protocol.oidc.TokenManager.checkTokenValidForIntrospection(TokenManager.java:293)
	at org.keycloak.protocol.oidc.AccessTokenIntrospectionProvider.verifyAccessToken(AccessTokenIntrospectionProvider.java:118)
	at org.keycloak.protocol.oidc.AccessTokenIntrospectionProvider.introspect(AccessTokenIntrospectionProvider.java:56)
	... 51 more

```

**Comment by adrhine** [comment]
Hello @dpulrichth, I'm trying to reproduce this issue but having trouble doing so. Using KC 21.0.2, I am able to revoke access and refresh tokens like you mentioned. When introspecting a revoked refresh token, I get the following response:

```
{
    "active": false
}
```

Looks to me like this is consistent with the same kind of response in previous versions. I'm not seeing any errors in the logs when doing this. I confirmed this behavior for both users and service accounts (just to be thorough). Do you have any additional information about your setup or anything else that might help me reproduce this?

**Comment by mposolda** [comment]
@adrhine Thanks for doublecheck this!

Not sure if this is a valid issue based on @adrhine comment, and regardless of it, Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is reproducible and valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by dpulrichth** [comment]
@adrhine Thanks for trying to reproduce this. I've re-checked this on Keycloak 21.1.1 and it's still present for me. I'm running Keycloak on Windows 10, JRE 17.

In production we're using Keycloak as an Identity Broker with an external IdP. However, I can also reproduce this using a minimal setup without identity brokering. I'm using a confidential client.

I'll try to play around with this some more and see if I can find the root cause.

**Comment by mposolda** [comment]
I am closing as there is no further response and it seems that this might be already resolved. Please re-open if you're still able to reproduce with latest Keycloak main.

**Comment by dglozano** [comment]
We are also experiencing this. Introspection of refresh token works as long as there is an active session. If we logout from all sessions and try to introspect a refresh token, it returns 

```
{
    "error": "invalid_request",
    "error_description": "Failed to introspect token."
}
```

**Comment by MrKich** [comment]
Same here, Keycloak 21.0.5.
After client manually logged out - introspect endpoint returns 400 if refresh token revoke is enabled and 200 if disabled.
I don't think that "400 bad request" is correct code for this endpoint (even 401 is better, as with wrong client_secret parameter).
