### ISSUE TITLE
Test `InternationalizationTest` fails in CI

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#20307]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

When the test `InternationalizationTest` is executed with Chrome in our CI, it fails.

https://github.com/keycloak/keycloak/actions/runs/4939759509/jobs/8843057671?pr=20293
https://github.com/keycloak/keycloak/actions/runs/4945013478/jobs/8841461993?pr=20301

```
Error: OR] Failures: 
Error: OR] org.keycloak.testsuite.ui.account2.InternationalizationTest.userAttributeTest
Error: OR]   Run 1: InternationalizationTest.userAttributeTest:105 expected:<[English]> but was:<[und]>
Error: OR]   Run 2: InternationalizationTest.userAttributeTest:105 expected:<[English]> but was:<[und]>
Error: OR]   Run 3: InternationalizationTest.userAttributeTest:105 expected:<[English]> but was:<[und]>
```

Stack trace:
```
--------- org.keycloak.testsuite.ui.account2.InternationalizationTest output end  ---------
Error:  Tests run: 6, Failures: 3, Errors: 0, Skipped: 2, Time elapsed: 43.433 s <<< FAILURE! - in org.keycloak.testsuite.ui.account2.InternationalizationTest
Error: OR] org.keycloak.testsuite.ui.account2.InternationalizationTest.userAttributeTest  Time elapsed: 8.489 s  <<< FAILURE!
-- org.junit.ComparisonFailure: expected:<[English]> but was:<[und]>
-- 	at org.junit.Assert.assertEquals(Assert.java:117)
-- 	at org.junit.Assert.assertEquals(Assert.java:146)
-- 	at org.keycloak.testsuite.ui.account2.InternationalizationTest.userAttributeTest(InternationalizationTest.java:105)
-- 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-- 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
-- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
-- 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
-- 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
-- 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
-- 	at org.jboss.arquillian.junit.Arquillian$8$1.invokeMethod(Arquillian.java:325)
-- 	at org.jboss.arquillian.junit.MethodInvoker$1.invoke(MethodInvoker.java:18)
-- 	at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
-- 	at org.keycloak.testsuite.arquillian.ModelTestExecutor.execute(ModelTestExecutor.java:51)
-- 	at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source)
-- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
-- 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
-- 	at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:50)
-- 	at jdk.internal.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
-- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:[568](https://github.com/keycloak/keycloak/actions/runs/4939759509/jobs/8843057671?pr=20293#step:4:569))
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
-- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
-- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:118)
-- 	at jdk.internal.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
-- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
-- 	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
-- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
-- 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
-- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
-- 	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
-- 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
-- 	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:139)
-- 	at org.jboss.arquillian.junit.MethodInvoker.invoke(MethodInvoker.java:15)
-- 	at org.jboss.arquillian.junit.Arquillian$8.evaluate(Arquillian.java:332)
-- 	at org.jboss.arquillian.junit.Arquillian$4.evaluate(Arquillian.java:204)
-- 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:350)
-- 	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
-- 	at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:215)
-- 	at org.jboss.arquillian.junit.Arquillian$7$1.invoke(Arquillian.java:279)
```

### Version

999

### Expected behavior

Test is ok

### Actual behavior

Test is NOT ok

### How to Reproduce?

```
mvn -f testsuite/integration-arquillian/tests/other/base-ui/pom.xml test -Dtest=InternationalizationTest -Dbrowser=chrome
```

**Comment by mabartos** [comment]
I was able to reproduce the issue with Chrome 113.0.5672.63, but after upgrading to 113.0.5672.92, the test passes.
