### ISSUE TITLE
Map storage with CockroachDB broken since 21.1.0

### ISSUE THREAD

**Issue by korden32** [keycloak/keycloak#20326]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Since 21.1.0 (also tested with nightly) I can't run Keycloak with `storage=jpa` and CockroachDB v22.2.6, it throws PSQLException syntax error when I try to open admin console after initial password setup.
21.0.2 worked fine.

### Version

21.1.1

### Expected behavior

21.0.2 works just fine and loading admin console when navigating to /admin/

### Actual behavior

Web shows "An internal server error has occurred" when navigating to /admin/
Console shows
```
2023-05-12 07:58:28,189 WARN  [com.arjuna.ats.jta] (executor-thread-3) ARJUNA016041: prepare on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff7f000101:9285:645df192:78, node_name=quarkus, branch_uid=0:ffff7f000101:9285:645df192:7b, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.BaseXAResource@6769eb4d) failed with exception XAException.XAER_RMFAIL: org.postgresql.xa.PGXAException: Error preparing transaction. prepare xid=< formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff7f000101:9285:645df192:78, node_name=quarkus, branch_uid=0:ffff7f000101:9285:645df192:7b, subordinatenodename=null, eis_name=0 >
        at org.postgresql.xa.PGXAConnection.prepare(PGXAConnection.java:365)
        at io.agroal.narayana.BaseXAResource.prepare(BaseXAResource.java:108)
        at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelPrepare(XAResourceRecord.java:214)
        at com.arjuna.ats.arjuna.coordinator.BasicAction.doPrepare(BasicAction.java:2678)
        at com.arjuna.ats.arjuna.coordinator.BasicAction.doPrepare(BasicAction.java:2628)
        at com.arjuna.ats.arjuna.coordinator.BasicAction.prepare(BasicAction.java:2162)
        at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1508)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
        at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
        at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
        at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
        at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:502)
        at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:469)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:300)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.processInRetriableTransaction(AuthorizationEndpoint.java:132)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:370)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:370)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: ERROR: at or near "131077_AAAAAAAAAAAAAP//fwABAQAAkoVkXfGSAAAAeHF1YXJrdXM=_AAAAAAAAAAAAAP//fwABAQAAkoVkXfGSAAAAewAAAAAAAAAA": syntax error
  Detail: source SQL:
PREPARE TRANSACTION '131077_AAAAAAAAAAAAAP//fwABAQAAkoVkXfGSAAAAeHF1YXJrdXM=_AAAAAAAAAAAAAP//fwABAQAAkoVkXfGSAAAAewAAAAAAAAAA'
                    ^
  Hint: try \h PREPARE
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
        at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:270)
        at org.postgresql.xa.PGXAConnection.prepare(PGXAConnection.java:357)
        ... 61 more

2023-05-12 07:58:28,190 WARN  [com.arjuna.ats.arjuna] (executor-thread-3) ARJUNA012073: BasicAction.End() - prepare phase of action-id 0:ffff7f000101:9285:645df192:78 failed.
```

### How to Reproduce?

- run Keycloak with CockroachDB
```
db=postgres
db-username=keycloak
db-password=12345
db-url=jdbc:postgresql://localhost:26257/keycloak

storage=jpa
storage-hotrod-host=127.0.0.1
storage-hotrod-port=11222
storage-hotrod-username=keycloak
storage-hotrod-password=12345
storage-area-action-token=hotrod
storage-area-auth-session=hotrod
storage-area-single-use-object=hotrod
storage-area-user-session=hotrod
```
also tried `storage-jpa-db=cockroach` option

- open web interface, set admin account & password
- try to open admin console

**Comment by hmlnarik** [comment]
I can confirm this issue in the case of Infinispan / CockroachDB mixed setup. CockroachDB does not support XA: https://github.com/cockroachdb/cockroach/pull/22359, but Keycloak needs it for Infinispan since #13280.

There will be optimizations related to CRDB in Keycloak 22, e.g. #20474 which may allow running Keycloak without Infinispan altogether with the new map store. Would this be a viable solution for you?

**Comment by gpooleoneiro** [comment]
@hmlnarik does this mean there's no current way of using ispn cache with map-storage and cockroachdb? 

I've managed to have success with the legacy storage and cockroach, using the image https://quay.io/repository/phasetwo/keycloak-crdb?tab=info as discussed here https://github.com/keycloak/keycloak/issues/10430. 

However whenever I use the map-storage i receive the error 
`No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.`
As discussed here https://github.com/keycloak/keycloak/issues/13536

Is enabling map-storage to be used alongside cockroach and ispn cache something that's on the roadmap? Or would you recommend reverting to the legacy storage?

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.

**Comment by gpooleoneiro** [comment]
@ahus1 thanks for pointing this out to me. I've quickly skimmed #[24111](https://github.com/keycloak/keycloak/issues/24111) and it looks like an internal roadmap of keycloak removing map storage. Is there a user guide for migrating away from map storage, moving users, clients, realms etc. to keycloaks original storage type ?

**Comment by ahus1** [comment]
It was an experimental feature, so we don't expect users to run in production with it. Therefore, no migration guidelines exist. 

You might consider exporting and then importing any data you might have in the map store.
