### ISSUE TITLE
Entering a single space in a regex password policy makes admin interface unusable.

### ISSUE THREAD

**Issue by simonpahl** [keycloak/keycloak#20411]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Given a single space as input in a regex password policy the admin interface becomes no longer usable

### Version

21.1.1

### Expected behavior

The admin console is still usable after entering a space as regex password policy.

### Actual behavior

The admin console is not usable after entering a space as regex password policy.

### How to Reproduce?

In the admin console enter a single space as regex password policy and save.

### Anything else?

I had to fix the realms password policy via the database.
`update REALM set PASSWORD_POLICY=NULL where ID="<REALM_ID>";`

**Comment by abstractj** [comment]
@simonpahl could you please provide all the steps to reproduce, plus the regex you mentioned? I was unable to reproduce the issue running Keycloak 21.1.1.

**Comment by simonpahl** [comment]
1) Start server for example with:
`services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - "8080:8080"
    command:
      - "start-dev"
`
2) log in the admin console
3) pick any realm 
4) navigate to Authentication -> Policies -> Password policy
5) add Regular Expression
6) enter a single space (" " value between the quotes)
7) hit save

It will result in that the realm will have a password policy like "regexPattern" in the database.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

Some details:
- Keycloak has many ways how admin can break the whole instance by doing some strange things. Using password policy with some "hardcoded" value or with single space character falls into this category. I don't see how we can avoid this - perhaps add some warning into the tooltip of regex policy and documentation for regex policy.

**Comment by sschu** [comment]
I could at least reproduce it, it happens when loading the realm:

2023-05-17 11:26:25,780 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: org.keycloak.models.ModelException: Invalid config for regexPattern: Config required
	at org.keycloak.models.PasswordPolicy$Builder.build(PasswordPolicy.java:194)
	at org.keycloak.models.PasswordPolicy.parse(PasswordPolicy.java:63)
	at org.keycloak.models.jpa.RealmAdapter.getPasswordPolicy(RealmAdapter.java:878)
	at org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:231)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:418)
	at org.keycloak.models.jpa.JpaRealmProvider.getRealmByName(JpaRealmProvider.java:160)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:454)
	at org.keycloak.services.managers.RealmManager.getRealmByName(RealmManager.java:98)
	at org.keycloak.services.resources.admin.AdminRoot.authenticateRealmAdminRequest(AdminRoot.java:168)
	at org.keycloak.services.resources.admin.AdminRoot.getRealmsAdmin(AdminRoot.java:214)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.constructLocator(ResourceLocatorInvoker.java:107)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTargetFromLocator(ResourceLocatorInvoker.java:87)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTarget(ResourceLocatorInvoker.java:76)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:137)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mposolda** [comment]
We can possibly have some validation `if (configurationRegex.trim().isEmpty()) { rejectTheConfiguration }` .

**Comment by ashwanth511** [comment]
can you assign me this bug , can i  work on this ?

**Comment by pedro-hos** [comment]
Hi team, I have added a simple validation on RegexPatternsPasswordPolicyProvider to avoid white spaces on regex
