### ISSUE TITLE
Admin UI - unable to load user's groups when large number of groups defined for the realm

### ISSUE THREAD

**Issue by michalmsk** [keycloak/keycloak#20489]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have a Keycloak instance with ~18k defined groups in flat structure - every group on the same root level.  
When I go to security admin console (admin UI) -> Users -> select sample user and go to "Groups" tab, only "loading" circle is displayed and no groups at all.  

![image](https://github.com/keycloak/keycloak/assets/47423695/2be865b9-ce64-445a-aed4-f99ac7b36321)

Looking at network requests - I can see two requests:  
![image](https://github.com/keycloak/keycloak/assets/47423695/9ff3ba2b-0f63-4175-968f-59aab45b132c)

1. https://mydomain/auth/admin/realms/myrealm/users/12345679/groups?first=0&max=11
2. https://mydomain/auth/admin/realms/myrealm/groups

The second requests takes "forever" to complete (~5 minutes in my case), seems to be performance problem with getting all realm groups. Anyway this request seems to be pointless because "Groups" tab displays only first 10 groups by default and results are paginated.

### Version

21.1.1

### Expected behavior

User's groups in admin UI should be displayed in acceptable time, independently from groups count for whole realm.
Probably: API request to get all realm groups should not be executed on User's groups tab.

### Actual behavior

User's groups in Admin UI are not displayed, because UI calls API to get all realm's groups. Request finished after ~5 minutes when there are ~18k groups defined.

### How to Reproduce?

Fill any Keycloak instance (version 21.1.1) with 18k groups on root level (optional).
Go to security admin console -> Users -> select any user and go to "Groups" tab. Open browser's developer tools (F12) and open Network tab. Refresh page, you'll see there are two requests for user's group: one with max=11 parameter, and second request getting all realm groups.
When you have ~18k groups in the realm then no user's groups will be displayed at all because UI waits till requests for all groups finish.

**Comment by ssilvert** [comment]
Are you using fine-grained authorization?  If so, then you are probably seeing this issue: https://github.com/keycloak/keycloak/issues/19954

If not, you should see improvement in the latest nightly build due to this partial fix: https://github.com/keycloak/keycloak/pull/19991

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by michalmsk** [comment]
I am not using fine-grained authorization. I will check the latest nightly build, thanks.

**Comment by michalmsk** [comment]
Hi,
I ran latest nightly build on localhost, added 18500 groups and problem still exists:
![image](https://github.com/keycloak/keycloak/assets/47423695/24c0945b-c174-42c4-856d-0c7e274e857c)

On server-side logs I've got a lot of warnings/errors related to db:  
```
2023-05-23 12:59:43,077 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff0a912045:d5cb:646c9aab:168 in state  RUN
2023-05-23 12:59:43,078 INFO  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012404: Action id 0:ffff0a912045:d5cb:646c9aab:168 - thread executor-thread-2 at time 12:57:43.066 had stackTrace org.hibernate.persister.entity.AbstractEntityPersister.getPropertyValues(AbstractEntityPersister.java:4082)
org.hibernate.persister.entity.EntityPersister.getValues(EntityPersister.java:910)
org.hibernate.event.internal.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:177)
(...)
2023-05-23 12:59:43,079 INFO  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012404: Action id 0:ffff0a912045:d5cb:646c9aab:168 - thread executor-thread-2 at time 12:58:13.079 had stackTrace org.hibernate.persister.entity.AbstractEntityPersister.getPropertyValues(AbstractEntityPersister.java:4082)
(...)
2023-05-23 12:59:43,087 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012108: CheckedAction::check - atomic action 0:ffff0a912045:d5cb:646c9aab:168 aborting with 1 threads active!
2023-05-23 12:59:43,092 WARN  [org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorTrackingImpl] (Transaction Reaper Worker 0) HHH000451: Transaction afterCompletion called by a background thread; delaying afterCompletion processing until the original thread can handle it. [status=4]
2023-05-23 12:59:43,093 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffff0a912045:d5cb:646c9aab:168
2023-05-23 12:59:43,115 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-2) SQL Error: 0, SQLState: null
2023-05-23 12:59:43,116 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-2) Connection is closed
2023-05-23 12:59:43,118 WARN  [com.arjuna.ats.arjuna] (executor-thread-2) ARJUNA012077: Abort called on already aborted atomic action 0:ffff0a912045:d5cb:646c9aab:168
2023-05-23 12:59:43,135 WARN  [org.keycloak.services.DefaultKeycloakSession] (executor-thread-2) Unable to close provider org.keycloak.connections.jpa.DefaultJpaConnectionProvider: org.keycloak.models.ModelException: org.hibernate.HibernateException: Transaction was rolled back in a different thread
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:64)
        at com.sun.proxy.$Proxy71.close(Unknown Source)
```

**Comment by ssilvert** [comment]
> Are you using fine-grained authorization? If so, then you are probably seeing this issue: #19954
> 
> If not, you should see improvement in the latest nightly build due to this partial fix: #19991
> 

I just realized this has nothing to do with the issues above.  We're talking about the Users section, not the Group section.  Sorry I jumped to conclusions.

@edewit Can you take a look?  I am attaching a json that you can use with partial import to create 10,000 groups at the root.  But I'm not sure if that's enough.

[groups-10000.zip](https://github.com/keycloak/keycloak/files/11547617/groups-10000.zip)

**Comment by eatikrh** [comment]
I tested Keycloak version 22 (master branch on May 22) with 10K groups under a parent group "org" with no fine grained autz. I  observed that the performance problem still persists. This group structure is how we use groups too keep track of attributes related "Company Single Signon."

**Comment by eatikrh** [comment]
[group_test_realm.json.zip](https://github.com/keycloak/keycloak/files/11548395/group_test_realm.json.zip)
