### ISSUE TITLE
Error : public Certificate of LDAP after upgrade

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#20485]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

We have migrated from legacy(wildfly distro) to Quarkus distro 20.0.5.

As we configured SSL based ldaps which require a public certificate and was imported in truststore Keycloak legacy was working fine but when we migrated to Keycloak latest (quarkus) getting below error while starting the keyclaok.

**Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**

The workaround is we can import the ldap certificate in jdk cacerts but it is tedious job for few people .

Could you guys ( @pedroigor @sschu @stianst @dasniko  )please help me with this?

### Version

20.0.5

### Expected behavior

It should start with no execuses.

### Actual behavior

It is failing with error 

```
2023-05-22 14:45:10,906 INFO  [org.keycloak.truststore.SSLSocketFactory] (main) No truststore provider found - using default SSLSocketFactory
2023-05-22 14:45:11,156 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 8 ResultSet(s) and 8 Statement(s)
2023-05-22 14:45:11,187 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2023-05-22 14:45:11,422 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2023-05-22 14:45:11,422 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: org.keycloak.models.ModelException: LDAP Query failed
        at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:176)                             at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getFirstResult(LDAPQuery.java:183)
        at org.keycloak.storage.ldap.LDAPStorageProvider.loadLDAPUserByUuid(LDAPStorageProvider.java:839)                       at org.keycloak.storage.ldap.LDAPStorageProvider.loadAndValidateUser(LDAPStorageProvider.java:498)
        at org.keycloak.storage.ldap.LDAPStorageProvider.validate(LDAPStorageProvider.java:171)                                 at org.keycloak.storage.UserStorageManager.importValidation(UserStorageManager.java:124)                                at org.keycloak.storage.UserStorageManager.getUserById(UserStorageManager.java:317)
        at org.keycloak.models.cache.infinispan.UserCacheSession.getUserById(UserCacheSession.java:216)                         at org.keycloak.models.jpa.JpaUserProvider.lambda$searchForUserStream$5(JpaUserProvider.java:902)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)                                  at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)                                                     at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)                                      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)                               at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)                                     at org.hibernate.query.spi.StreamDecorator.forEach(StreamDecorator.java:153)                                            at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.keycloak.exportimport.util.ExportUtils.exportRealm(ExportUtils.java:219)
        at org.keycloak.exportimport.util.ExportUtils.exportRealm(ExportUtils.java:73)
        at org.keycloak.exportimport.dir.DirImportProvider.importModel(DirImportProvider.java:76)
        at org.keycloak.exportimport.ExportImportManager.runImport(ExportImportManager.java:87)
        at org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:211)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.startup(QuarkusKeycloakApplication.java:43)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
        at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@2b3ee95e
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
        at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:172)
        ... 70 more
Caused by: org.keycloak.models.ModelException: Could not query server using DN [DC=mycompany,DC=com] and filter [(&(objectClass=*)(objectGUID=\14\0c\14\c8\95\94\ac\45\ba\ee\0a\90\26\7a\bd\2d))]
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.lookupById(LDAPOperationManager.java:442)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:261)
        ... 71 more
Caused by: javax.naming.CommunicationException: blrdev001939.mycompany.com:636 [Root exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]
        at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:252)
        at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
        at java.naming/com.sun.jndi.ldap.LdapClientFactory.createPooledConnection(LdapClientFactory.java:71)
        at java.naming/com.sun.jndi.ldap.pool.Connections.createConnection(Connections.java:185)
        at java.naming/com.sun.jndi.ldap.pool.Connections.getAvailableConnection(Connections.java:151)
        at java.naming/com.sun.jndi.ldap.pool.Pool.getOrCreatePooledConnection(Pool.java:189)
        at java.naming/com.sun.jndi.ldap.pool.Pool.getPooledConnection(Pool.java:148)
        at java.naming/com.sun.jndi.ldap.LdapPoolManager.getLdapClient(LdapPoolManager.java:340)
        at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1608)
        at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2847)
        at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:266)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:226)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:284)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:185)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:115)
        at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
        at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
        at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:711)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:706)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.lookupById(LDAPOperationManager.java:410)
        ... 72 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
        at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:364)
        at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:231)
        ... 96 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 109 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 115 more

Killed  exitValue: 128
Killed  exitValue: 128
```

### How to Reproduce?

Configure ldaps and import the ldap certificate into truststore for wildfly distro and access user from ldaps so you will be sure ldap is working fine.

Then upgrade keycloak Quarkus on top of Wildfly distro then it will fail.

**Comment by rubendevgo** [comment]
@we are having the same issue, can you explain me your workaround ?

**Comment by ajaiswal595** [comment]
> @we are having the same issue, can you explain me your workaround ?

@rubendevgo The workaround : Basically we have to import the ldaps certificates to the jdk/lib/security/cacert .

Or if you have existing Truststore file where the certificates are you can copy all the certificates to jdk cacert file 

keytool -importkeystore -srckeystore keycloak-truststore.ks -destkeystore jdk/lib/security/cacerts -srcstorepass truststore_password -deststorepass changeit -v

change the path accordingly for keycloak truststore and jdk cacert.


**But this is a workaround, not the actual solution.**

**Comment by rubendevgo** [comment]
@ajaiswal595 The workaround did not work for me, I'm running keycloak in a container and I used this command in my dockerfile to import the ldap.cer to the jdk cacerts: 

keytool -import -alias ldapcert -file /opt/keycloak/ldap.cer -trustcacerts -keystore /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el9_1.x86_64/lib/security/cacerts -storepass changeit -noprompt

**Comment by ajaiswal595** [comment]
> @ajaiswal595 The workaround did not work for me, I'm running keycloak in a container and I used this command in my dockerfile to import the ldap.cer to the jdk cacerts:
> 
> keytool -import -alias ldapcert -file /opt/keycloak/ldap.cer -trustcacerts -keystore /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el9_1.x86_64/lib/security/cacerts -storepass changeit -noprompt

What is the error you are getting after importing the certificate?

**Comment by rubendevgo** [comment]
@ajaiswal595 It´s working now, the issue was  related to the fact that the certificate we are using was created in a server with a higher encryption standard than the one supported by Keycloak. We resolve the problem adding a new RSA SHA256 certificate.
