### ISSUE TITLE
Export for MAP STORAGE feature not supported

### ISSUE THREAD

**Issue by avanlangup** [keycloak/keycloak#20509]
### Description

I am running KC 21.1.x with map storage enabled. But I am not allowed to export my realms.
When is it foreseen to be implemented ?

### Motivation

I want to setup local machine by importing existing realms  

### Details

Uncaught server error: org.keycloak.models.ModelException: exporting for map storage is currently not supported
	at org.keycloak.models.map.datastore.MapExportImportManager.exportRealm(MapExportImportManager.java:485)
	at org.keycloak.services.resources.admin.RealmAdminResource.partialExport(RealmAdminResource.java:1105)

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
