### ISSUE TITLE
Keycloak Unable to start in Production

### ISSUE THREAD

**Issue by akashsuresh** [keycloak/keycloak#20523]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

When I attempt to start Keycloak in production mode, I get the following Null Pointer exception: Please find the stack trace

`ERROR: Unexpected error when starting the server in (production) mode
Error details:
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:98)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:94)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.NullPointerException
	at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.init(DefaultHostnameProvider.java:255)
	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.<init>(QuarkusKeycloakSessionFactory.java:83)
	at org.keycloak.quarkus.runtime.KeycloakRecorder.configSessionFactory(KeycloakRecorder.java:84)
	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory957950182.deploy_4(Unknown Source)
	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory957950182.deploy(Unknown Source)`

### Version

21.1.1

### Expected behavior

Should start normally

### Actual behavior

Null pointer exception

### How to Reproduce?

`
KEYCLOAK_USER=keycloak
KEYCLOAK_HOME=/home/${KEYCLOAK_USER}
KEYCLOAK_CONFIG_DIR="${KEYCLOAK_HOME}/config"
KEYCLOAK_REL_DIR="${KEYCLOAK_HOME}/bin"
KEYCLOAK_VERSION="21.1.1"
KEYCLOAK_VERSION_DIR="${KEYCLOAK_REL_DIR}/${KEYCLOAK_VERSION}"
KEYCLOAK_CONFIG_PATH="${KEYCLOAK_CONFIG_DIR}/keycloak.conf"
KEYCLOAK_ENV_PATH="${KEYCLOAK_CONFIG_DIR}/keycloak.service.env"

sudo -u ${KEYCLOAK_USER} env "$(cat ${KEYCLOAK_ENV_PATH})" ${KEYCLOAK_VERSION_DIR}/bin/kc.sh --verbose --config-file=${KEYCLOAK_CONFIG_PATH} start --optimized

`

### Anything else?

None

**Comment by akashsuresh** [comment]
I have done the steps and I am still getting the same error. Is there something I am missing?

**Comment by akashsuresh** [comment]
The error is at this line. 
`noProxy = Configuration.getConfigValue("kc.proxy").getValue().equals("false");`

**Comment by vmuzikar** [comment]
@isaacjensen That sounds like a different issue with building Keycloak from source. Could you please create a separate issue for it? Thanks.

**Comment by isaacjensen** [comment]
@vmuzikar can no longer reproduce. must have been something in my local env. did a fresh clone, all working with alternative method too. no need for an issue

**Comment by abstractj** [comment]
@vmuzikar based on the latest comments it seems safe to close this issue.
