### ISSUE TITLE
Denial of Service/100% CPU usage: CRLUtils in infinite loop if more than one CRL list is used from different CAs

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak#20725]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

X.509 login flow is used and CRL check is configured and activated.
It is working with one CRL list from one CA.
But possible client certificates are comming from two different CAs, thus two CRL lists are configured.

In CRLUtils we catch the path to `findCRLSignatureCertificateInTruststore()` and there we are in an infinite loop if more than one CRL list is used from different CAs.
We never break the `while (true) {}` loop, CPU usage is 100% and keycloak does not longer respond - a denial of service.
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/utils/CRLUtils.java#L121

As a proof of failure I added some debug outputs:
```
    private static X509Certificate findCRLSignatureCertificateInTruststore(KeycloakSession session, X509Certificate[] certs, X500Principal crlIssuerPrincipal) throws GeneralSecurityException {

        ......
        X509Certificate currentCRLAnchorCertificate = crlSignatureCertificate;
        X500Principal currentCRLAnchorPrincipal = crlIssuerPrincipal;
        long loop = 1;
        while (true) {
        	log.debugf("Loop nr. '%s' / Checking trust anchor of the CRL issuer '%s' in the CA chain. Anchor is '%s'", loop, certificateCAPrincipals, currentCRLAnchorPrincipal);
        	loop++;
            if (certificateCAPrincipals.contains(currentCRLAnchorPrincipal)) {
                log.tracef("Found trust anchor of the CRL issuer '%s' in the CA chain. Anchor is '%s'", crlIssuerPrincipal, currentCRLAnchorPrincipal);
                break;
            }
        ......
            if (loop > 10000) {
            	throw new GeneralSecurityException("Infinite loop detected, break out!");
            }
        }

        return crlSignatureCertificate;
    }
```

Starting the X.509 login I see 10000 log lines repeating the same check and my `throw new GeneralSecurityException("Infinite loop detected, break out!");`

keycloak logfile:
```
2023-06-01 14:16:48,511 DEBUG [org.keycloak.services:368] [executor-thread-0] Loading CRL from /opt/keycloak-21.1.1/bin/../conf/crl_ca_1.pem
2023-06-01 14:16:48,514 DEBUG [org.keycloak.services:368] [executor-thread-0] Loading CRL from /opt/keycloak-21.1.1/bin/../conf/crl_ca_2.pem
2023-06-01 14:16:48,517 DEBUG [org.keycloak.utils.CRLUtils:123] [executor-thread-0] Loop nr. '1' / Checking trust anchor of the CRL issuer '[OID.2.5.4.97=abcd, CN=xxxxxxx]' in the CA chain. Anchor is 'CN=yyyyyy'

.....

2023-06-01 14:16:48,723 DEBUG [org.keycloak.utils.CRLUtils:123] [executor-thread-0] Loop nr. '9999' / Checking trust anchor of the CRL issuer '[OID.2.5.4.97=abcd, CN=xxxxxxx]' in the CA chain. Anchor is 'CN=yyyyyy'
2023-06-01 14:16:48,723 DEBUG [org.keycloak.utils.CRLUtils:123] [executor-thread-0] Loop nr. '10000' / Checking trust anchor of the CRL issuer '[OID.2.5.4.97=abcd, CN=xxxxxxx]' in the CA chain. Anchor is 'CN=yyyyyy'
2023-06-01 14:16:48,723 ERROR [org.keycloak.services:94] [executor-thread-0] Infinite loop detected, break out!: java.security.GeneralSecurityException: Infinite loop detected, break out!
        at org.keycloak.utils.CRLUtils.findCRLSignatureCertificateInTruststore(CRLUtils.java:142)
        at org.keycloak.utils.CRLUtils.check(CRLUtils.java:75)
        at org.keycloak.authentication.authenticators.x509.CertificateValidator.checkRevocationStatusUsingCRL(CertificateValidator.java:737)
        at org.keycloak.authentication.authenticators.x509.CertificateValidator.checkRevocationStatus(CertificateValidator.java:770)
        at org.keycloak.authentication.authenticators.x509.X509ClientCertificateAuthenticator.authenticate(X509ClientCertificateAuthenticator.java:87)
```

### Version

21.1.1

### Expected behavior

Multiple CRL lists are checked correctly against the certificate in use with no infinite loop

### Actual behavior

infinite loop with CPU usage 100%

### How to Reproduce?

Enable and configure more that one CRL list and have a truststore containing both signing CAs

### Anything else?

My issue is not 100% related to #19918 because in the other issue keycloak complains about missing truststore,
which I catched at the beginning too.
But was fixed by usage of `spi-truststore-file-file` instead of `https-trust-store-file`

It looks like in discussion #20468 the same infinite loop was triggered.

Fianally the result of discussion #12310 and it's PR #14961 is not clear,
because to have a working truststore for CRL check, the `spi-truststore-file-file` needs to be used!!!!!!
But in discussion and PR it's stated as configuration for outgoing HTTPS connections.

**Comment by pedroigor** [comment]
Could you please share the options you are using to configure and start the server? I would like to know if you are using a specific `X509ClientCertificateLookup` provider and if you are running behind a proxy.

As you are changing code, could you try replacing that `while` block with:

```
for (X500Principal caPrincipal : certificateCAPrincipals) {
            if (caPrincipal.equals(currentCRLAnchorPrincipal)) {
                log.tracef("Found trust anchor of the CRL issuer '%s' in the CA chain. Anchor is '%s'", crlIssuerPrincipal, currentCRLAnchorPrincipal);
                break;
            }

            // Try to see the anchor
            currentCRLAnchorPrincipal = currentCRLAnchorCertificate.getIssuerX500Principal();

            currentCRLAnchorCertificate = intermediateCerts.get(currentCRLAnchorPrincipal);
            if (currentCRLAnchorCertificate == null) {
                currentCRLAnchorCertificate = rootCerts.get(currentCRLAnchorPrincipal);
            }
            if (currentCRLAnchorCertificate == null) {
                throw new GeneralSecurityException("Certificate for CRL issuer '" + crlIssuerPrincipal + "' available in the truststore, but doesn't have trust anchors with the CA chain.");
            }
        }
```

**Comment by psytester** [comment]
The new code block works as expected. 👍 
I added some debug output again to see how often the `findCRLSignatureCertificateInTruststore()`is called.

Result looks good for me, one call per CA:
```
2023-06-02 09:17:44,762 DEBUG [org.keycloak.services:368] [executor-thread-1] Loading CRL from /opt/keycloak-21.1.1/bin/../conf/crl_ca_1.pem
2023-06-02 09:17:44,767 DEBUG [org.keycloak.services:368] [executor-thread-1] Loading CRL from /opt/keycloak-21.1.1/bin/../conf/crl_ca_2.pem
2023-06-02 09:17:44,769 DEBUG [org.keycloak.utils.CRLUtils:116] [executor-thread-1] Number of entries in certificateCAPrincipals: '2'
2023-06-02 09:17:44,769 DEBUG [org.keycloak.utils.CRLUtils:119] [executor-thread-1] Number of entries in certificateCAPrincipals after removal of checked certificate itself: '1'
2023-06-02 09:17:44,769 DEBUG [org.keycloak.utils.CRLUtils:125] [executor-thread-1] Checking trust anchor of the CRL issuer 'OID.2.5.4.97=abcd, CN=xxxxxxx' in the CA chain. Anchor is 'CN=ca 2'
2023-06-02 09:17:44,770 DEBUG [org.keycloak.utils.CRLUtils:116] [executor-thread-1] Number of entries in certificateCAPrincipals: '2'
2023-06-02 09:17:44,770 DEBUG [org.keycloak.utils.CRLUtils:119] [executor-thread-1] Number of entries in certificateCAPrincipals after removal of checked certificate itself: '1'
2023-06-02 09:17:44,770 DEBUG [org.keycloak.utils.CRLUtils:125] [executor-thread-1] Checking trust anchor of the CRL issuer 'OID.2.5.4.97=abcd, CN=xxxxxxx' in the CA chain. Anchor is 'CN=ca 1'
```

Yes, my setup is keycloak running behind a reverse proxy with proxy=edge mode, here is my related config:
```
# HTTP
# Truststore
# https truststore is NOT used for CRL check!
https-trust-store-file=${kc.home.dir}/conf/ca_truststore.jks
https-trust-store-password=123456
https-trust-store-type=JKS
# spi truststore IS used for CRL check!
spi-truststore-file-file=${kc.home.dir}/conf/ca_truststore.jks
spi-truststore-file-password=123456

# The proxy address forwarding mode if the server is behind a reverse proxy.
# https://www.keycloak.org/server/reverseproxy
# edge == Enables communication through HTTP between the proxy and Keycloak.
# This mode is suitable for deployments with a highly secure internal network
# where the reverse proxy keeps a secure connection (HTTP over TLS) with clients while communicating with Keycloak using HTTP.
proxy=edge

https-client-auth=request

# issue 17059: Keycloak behind reverse proxy with mTLS for X.509 login flow --> Possible vulnerability to bypass or spoof the X.509 credentials
spi-x509cert-lookup-provider=apache
spi-x509cert-lookup-apache-ssl-client-cert=SECRET_HEADER_SSL_CLIENT_CERT
spi-x509cert-lookup-apache-ssl-cert-chain-prefix=SECRET_HEADER_SSL_CLIENT_CERT_CHAIN
spi-x509cert-lookup-apache-certificate-chain-length=1

hostname-strict=false
hostname-strict-https=false

http-enabled=true
```

**Comment by pedroigor** [comment]
@psytester I'll provide a fix.

I'll also try to use your configuration to update our guides about revocation checks when running X509 authentication.
