### ISSUE TITLE
Keycloak instance not able to send emails

### ISSUE THREAD

**Issue by regmibijay** [keycloak/keycloak#20769]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

I have created a docker container with latest image from `quay.io/keycloak/keycloak:latest` . Then I created a custom realm and went to `Realm settings` and then to `Email` tab and filled in following fields:

Template
- From
- From display name

Connection & Authentication
Host: smtp.strato.de
Port: 465
Encryption: Enable SSL + StartTLS
Username: myusername
Password: mypassword

(Strato is a domain registrar and my MX provider, settings validated [here](https://www.strato.de/faq/mail/so-lauten-die-strato-e-mail-server/))

Then I saved settings and clicked on `Test connection`

### Version

latest

### Expected behavior

Test email would be sent to pre-saved admin account email address.

### Actual behavior

Test email could not be sent with following error log

```
org.keycloak.email.EmailException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.strato.de, 465; timeout 10000;
  nested exception is:
        java.net.SocketTimeoutException: Connect timed out
        at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:154)
        at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:61)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:281)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:275)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendSmtpTestEmail(FreeMarkerEmailTemplateProvider.java:129)
        at org.keycloak.services.resources.admin.RealmAdminResource.testSMTPConnection(RealmAdminResource.java:938)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.strato.de, 465; timeout 10000;
  nested exception is:
        java.net.SocketTimeoutException: Connect timed out
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2210)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
        at javax.mail.Service.connect(Service.java:342)
        at javax.mail.Service.connect(Service.java:222)
        at javax.mail.Service.connect(Service.java:243)
        at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:146)
        ... 53 more
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:333)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
        ... 58 more
```

### How to Reproduce?

Template
- From
- From display name

Connection & Authentication
Host: smtp.strato.de
Port: 465
Encryption: Enable SSL + StartTLS
Username: anyusername
Password: anypassword

**Comment by sschu** [comment]
Since the error clearly indicates it cannot open a socket connection to the target address and port, I would assume this has to do something with your network environment. Maybe you cannot connect to the Internet directly and need a proxy?

**Comment by regmibijay** [comment]
I checked it with `ping` in my docker host and since the ubi9 is minimal without network tools, I can not find way to test it inside docker container itself. My network settings do not block the host or port.

**Comment by regmibijay** [comment]
Thanks for getting back and checking, I have not worked with ubi images before so I felt helpless in debugging this is hence posted it here in hope of someone being able to help me further. I looked into installing package manager since the docker host is in very confined environment behind reverse proxy etc. but was not very successful.
