### ISSUE TITLE
Unstable WebAuthn tests with Firefox in GHA

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#20777]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

The WebAuthn tests executed in our GHA CI, where Firefox is used as the browser, are unstable. During Selenium initialization and Arquillian Drone, it's not possible to create a new browser session. It does not fail for specific test cases, but rather in a random fashion. 

```
Error: OR] org.keycloak.testsuite.webauthn.registration.UserVerificationRegisterTest.discouragedAny  Time elapsed: 9.958 s  <<< ERROR!
-- java.lang.RuntimeException: Could not create statement
-- 	at org.jboss.arquillian.junit.Arquillian.methodBlock(Arquillian.java:313)
-- 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
-- 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
-- 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
-- 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
-- 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
-- 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
-- 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
-- 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
-- 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
-- 	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:166)
-- 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:350)
-- 	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
-- 	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:177)
-- 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
-- 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
-- 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
-- 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
-- 	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
-- Caused by: java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.firefox.FirefoxDriver(FirefoxOptions): org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
-- 	at org.jboss.arquillian.drone.webdriver.factory.SecurityActions.newInstance(SecurityActions.java:166)
-- 	at org.jboss.arquillian.drone.webdriver.factory.FirefoxDriverFactory.createInstance(FirefoxDriverFactory.java:76)
-- 	at org.jboss.arquillian.drone.webdriver.factory.FirefoxDriverFactory.createInstance(FirefoxDriverFactory.java:40)
-- 	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
-- 	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
-- 	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
-- 	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
-- 	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:88)
-- 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
-- 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
-- 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
-- 	at java.base/java.lang.Thread.run(Thread.java:833)
-- Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
-- 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:577)
-- 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:246)
-- 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
-- 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
-- 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
-- 	at jdk.internal.reflect.GeneratedConstructorAccessor198.newInstance(Unknown Source)
-- 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
-- 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
-- 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
-- 	at org.jboss.arquillian.drone.webdriver.factory.SecurityActions.newInstance(SecurityActions.java:144)
-- 	... 11 more
-- Caused by: org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!
-- Build info: version: '4.1.0', revision: '87802e897b'
-- System info: host: 'fv-az178-867', ip: '10.1.0.17', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1038-azure', java.version: '17.0.7'
-- Driver info: driver.version: FirefoxDriver
-- 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:145)
-- 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
-- 	... 20 more
-- Caused by: java.io.UncheckedIOException: java.net.ConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:51828
-- 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:80)
-- 	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:82)
-- 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
-- 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
-- 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
-- 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
-- 	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
-- 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
-- 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
-- 	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:82)
-- 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
-- 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
-- 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
-- 	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:82)
-- 	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
-- 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
-- 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
-- 	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
-- 	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
-- 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
-- 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
-- 	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:82)
-- 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
-- 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
-- 	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:108)
-- 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
-- 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
-- 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
-- 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
-- 	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
-- 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
-- 	... 21 more
-- Caused by: java.net.ConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:51828
-- 	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
-- 	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
-- 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
-- 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
-- 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
-- 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
-- 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
-- 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
-- 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
-- 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
-- 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
-- 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
-- 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
-- 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
-- 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
-- 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
-- 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
-- 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
-- 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
-- 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
-- 	... 1 more
-- Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:51828
-- Caused by: java.net.ConnectException: Connection refused
-- 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
-- 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
-- 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
-- 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
-- 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
-- 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
-- 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
-- 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
-- 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
-- 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
-- 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
-- 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
-- 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Affected jobs:
https://github.com/keycloak/keycloak/actions/runs/5158977687/jobs/9293505571?pr=20759
https://github.com/keycloak/keycloak/actions/runs/5152038678/jobs/9277954672

### Version

999

**Comment by jonkoops** [comment]
@mabartos perhaps we need to download the right version of Firefox? Seems like inconsistencies in browser versions can be the culprit.

**Comment by ahus1** [comment]
Failed for me today as well: https://github.com/keycloak/keycloak/actions/runs/5554718098/jobs/10145270350

**Comment by stianst** [comment]
Quite a few failures caused by WebAuthn here:
https://stianst.github.io/keycloak-dashboard/tests#failed-job-webauthn-it

Also, see failed PR runs here:
https://stianst.github.io/keycloak-dashboard/workflows

**Comment by rmartinc** [comment]
I thought this was already taken by @mabartos. I'm also looking into it. This is a mess. I'm going to try to do a summary of what I've seen:

* The firefox driver starts the `geckodriver` like this: `geckodriver --port=xxx --websocket-port=yyy`.
* If the `port` is already taken it fails with the message we are seeing in the CI:

```
./geckodriver --port=8080 --websocket-port=9999
/home/rmartinc/Desktop/geckodriver: error: Address in use (os error 98)
```

* The selenium tries to find a free socket using this [class](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/net/PortProber.java). It gets a random port  (from 32768 to 60999, ephemeral ports in linux) and checks it's free in "localhost".
* AFAIK this cannot be changed in any way. The port is always selected this way. Besides there are several `geckodriver` instances running at the same time, so the port should be changing.

Knowing that, there are two issues here:

1. I think that the test to see if it's free doesn't work because it mixes `127.0.0.1` and `::1`. The ubuntu box in GHA uses localhost to ::1 and the geckodriver starts on 127.0.0.1, so it's not checking the same address.
2. Removing the `::1 localhost` from the `/etc/hosts` and just using `127.0.0.1`  I see the failures decreases but not to 0. In my tests it failed 3 on 50 runs (it's better than 14 in 50 as @stianst got a few days ago, but it still fails). So I really think that the box is using a lot of short connections and we can test a port, and then it's used when the geckodriver is really started. I still think that is incredible to get the same port having 30000 ports, but I have no more ideas.

I have did a dirty trick t o see if I'm right. I have re-defined one class of the selenium project in the webauthn test classes. This way my class is found first and used instead of the one in selenium. This class is selecting the class from the non-ephemeral ports. To not conflict with short living connections. With this one I have run 20 tests (+10 before) without issues (see [this](https://github.com/rmartinc/keycloak/actions/runs/5681043024/job/15396798645)).

WDYT? I don't see anything to do this normally without a hack.

**Comment by mabartos** [comment]
@rmartinc Thanks for your comprehensive investigation. 

I believe these issues might be related to this:
https://github.com/SeleniumHQ/selenium/pull/11085
https://github.com/SeleniumHQ/selenium/pull/10990

Currently, I'm working on the component upgrades for WebAuthn, and it seems when we upgrade Selenium to >=4.5.1, the problem will disappear.

**Comment by rmartinc** [comment]
Ahh! I checked in current selenium and (don't know why) I though it was the same. :smile: Too much time with this.

**Comment by mabartos** [comment]
After an offline discussion with @rmartinc, we've decided to assign this issue to me, as it'll be fixed by upgrading Selenium to >=4.5.1, and I have some experience with that. I can also discuss it with our QE team. 

These upgrades are quite tricky to do as also the Arquillian Drone and Arquillian Graphene must be upgraded.

**Comment by rmartinc** [comment]
Thanks @mabartos! Reviewing the selenium issues yesterday I think that you are totally right and this will be fixed upgrading selenium to 4.5.1 or newer. But, as you commented to me, this will also need modifications in the arquillian drone and graphene projects (current projects work with selenium 4.3.0 and changes are needed for sure to upgrade to 4.5.1 or newer). Thanks again!

**Comment by mabartos** [comment]
There is an initiative around upgrading the Arquillian components:
https://github.com/arquillian/arquillian-extension-drone/pull/401
https://github.com/arquillian/arquillian-graphene/pull/241

Maybe one day, we will move to the WebDriverManager, and certain problems will be solved :))

**Comment by jonkoops** [comment]
Alternatively: https://playwright.dev/java/ :stuck_out_tongue:

**Comment by stianst** [comment]
Temporarily disabling WebAuthn firefox tests in https://github.com/keycloak/keycloak/pull/22071

Remember to re-enable when this issue is finally resolved

**Comment by mabartos** [comment]
This issue will be fixed after resolving #22074. After that, please enable these tests again; tracked in #22075

**Comment by mposolda** [comment]
Update: Since March 2024, there are almost no failures in WebAuthn tests in GHA.

**Comment by mabartos** [comment]
As WebAuthn tests with Firefox were stable for some time, I think this issue is not relevant anymore. Closing now.

Solved by: https://github.com/keycloak/keycloak/issues/29778
