### ISSUE TITLE
Single sign-on with CONFIDENTIAL client seems to have a client-id character limit

### ISSUE THREAD

**Issue by NielDB** [keycloak/keycloak#20808]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

We are seeing an issue when doing a user login using on a front-end application. This application uses a CONFIDENTIAL client in Keycloak with the following client-id: "app-test-myapplicationname".

When doing a user login we get the following error:  "ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-1) failed to turn code into token: javax.net.ssl.SSLException: Connection reset".

If we change the client-id to "app-test-myapp" and keep all other config the same, everything seems to work fine.
There seems to be some kind of character limit defined for these clients for single sign on.

Also, this issue only happens with CONFIDENTIAL clients, PUBLIC clients do not have this issue.

### Version

18.0.7

### Expected behavior

CODE_TO_TOKEN call should not fail based on client-id length.

### Actual behavior

10:22:56,993 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-1) failed to turn code into token: javax.net.ssl.SSLException: Connection reset

    at sun.security.ssl.Alert.createSSLException(Alert.java:127)

    at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)

    at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)

    at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)

    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1563)

    at sun.security.ssl.SSLSocketImpl.access$400(SSLSocketImpl.java:73)

    at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973)

    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)

    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)

    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)

    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)

    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)

    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)

    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)

    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)

    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)

    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)

    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)

    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)

    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)

    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

    at org.keycloak.adapters.ServerRequest.invokeAccessCodeToToken(ServerRequest.java:110)

    at org.keycloak.adapters.OAuthRequestAuthenticator.resolveCode(OAuthRequestAuthenticator.java:335)

    at org.keycloak.adapters.OAuthRequestAuthenticator.authenticate(OAuthRequestAuthenticator.java:280)

    at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:138)

    at org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticationProcessingFilter.attemptAuthentication(KeycloakAuthenticationProcessingFilter.java:154)

    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231)

    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)

    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

    at org.keycloak.adapters.springsecurity.filter.KeycloakPreAuthActionsFilter.doFilter(KeycloakPreAuthActionsFilter.java:96)

    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

    at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:118)

    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

    at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)

    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)

    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)

    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)

    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)

    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

    at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)

    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)

    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)

    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)

    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)

    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)

    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)

    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)

    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)

    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)

    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)

    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)

    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)

    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)

    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)

    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)

    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)

    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)

    at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)

    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)

    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)

    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

    at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)

    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)

    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)

    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)

    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)

    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)

    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)

    at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)

    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)

    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)

    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)

    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)

    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)

    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)

    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)

    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)

    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)

    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)

    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)

    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)

    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)

    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)

    at java.lang.Thread.run(Thread.java:750)

    Suppressed: java.net.SocketException: Connection reset by peer: socket write error

        at java.net.SocketOutputStream.socketWrite0(Native Method)

        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)

        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)

        at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)

        at sun.security.ssl.TransportContext.fatal(TransportContext.java:355)

        ... 98 more

Caused by: java.net.SocketException: Connection reset

    at java.net.SocketInputStream.read(SocketInputStream.java:210)

    at java.net.SocketInputStream.read(SocketInputStream.java:141)

    at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)

    at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)

    at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1341)

    at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)

    at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:957)

    ... 93 more

### How to Reproduce?

1. Create a new client with a client id = app-test-myapplicationname
    Set Access Type = confidential
    Set Standard Flow Enabled = on
    Configure redirect url
2. Configure your application to use Keycloak single sign on with this client
3. Try doing a user login on the application
4. Change the client-id to app-test-myapp
5. Try doing a user login on the application again

**Comment by rmartinc** [comment]
Hi @NielDB !

I have tested this in my laptop and it's working for me. I can use "app-test-myapplicationname" clientId without any issue. I'm using last version. You are just pasting the adapter output, is there any error in the server? (Because it seems that it's the keycloak server the one closing the connection).

So I think there is something more here that we are missing. With this information we cannot do more in the issue.

**Comment by mposolda** [comment]
Adding to Backlog as it's related to adapters and looks like corner case with some special configuration. Keycloak team likely won't have time to look at this in the near future.
