### ISSUE TITLE
Unable to build from 21.1.1 tag

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#20934]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I am unable to build the current keycloak release from the `21.1.1` tag. 

### Version

21.1.1

### Expected behavior

Build completes successfully.

### Actual behavior

Failure building the js adapter:
```
[INFO] --- frontend:1.12.1:npm (npm-build) @ keycloak-js-adapter-jar ---
[INFO] Running 'npm run build --workspace=keycloak-js' in /usr/src/keycloak/js
[INFO] 
[INFO] > keycloak-js@21.1.1 build
[INFO] > wireit
[INFO] 
[INFO] ???? [build] Running command "rollup --config --configPlugin typescript"
[INFO] node:internal/modules/cjs/loader:1078
[INFO]   throw err;
[INFO]   ^
[INFO] 
[INFO] Error: Cannot find module '/usr/src/keycloak/js/node_modules/.pnpm/rollup@3.21.4/node_modules/rollup/dist/bin/rollup'
[INFO]     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
[INFO]     at Module._load (node:internal/modules/cjs/loader:920:27)
[INFO]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[INFO]     at node:internal/main/run_main_module:23:47 {
[INFO]   code: 'MODULE_NOT_FOUND',
[INFO]   requireStack: []
[INFO] }
[INFO] 
[INFO] Node.js v18.15.0
[INFO] ??? [build] Failed with exit status 1
[INFO] npm ERR! Lifecycle script `build` failed with error: 
[INFO] npm ERR! Error: command failed 
[INFO] npm ERR!   in workspace: keycloak-js@21.1.1 
[INFO] npm ERR!   at location: /usr/src/keycloak/js/libs/keycloak-js 
```

### How to Reproduce?

I tried locally, but for the purpose of eliminating any local problems, I reproduced using maven docker image.

Per https://github.com/keycloak/keycloak/blob/main/docs/building.md make a `settings.xml` file with the following content:
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <mirrors>
    <mirror>
      <id>jboss-public-repository-group-https</id>
      <mirrorOf>jboss-public-repository-group</mirrorOf>
      <name>Jboss public https</name>
      <url>https://repository.jboss.org/nexus/content/groups/public/</url>
    </mirror>
  </mirrors>
</settings>
```

Clone the keycloak repo and checkout the 21.1.1 tag:
```bash
git clone https://github.com/keycloak/keycloak.git
cd keycloak
git fetch --all --tags
git checkout 21.1.1
```

Run the build using the maven docker image
```bash
docker run -it --name keycloak-build -v "$(pwd)":/usr/src/keycloak -v $HOME/.m2/settings.xml:/usr/share/maven/ref/settings.xml -w /usr/src/keycloak maven:3.9.2-amazoncorretto-17-debian mvn clean install -DskipTests
```

**Comment by reda-alaoui** [comment]
@xgp how did you solve it?

**Comment by xgp** [comment]
@reda-alaoui I just checked it out to a clean dir and tried again. I believe node or the maven frontend plugin is leaving something in a bad state (perhaps in node_modules dir) which causes subsequent builds to fail. However, I lacked the time to get to the root of the problem.

**Comment by reda-alaoui** [comment]
@xgp Thank you! I'll try that.

**Comment by Varshaa21** [comment]
@reda-alaoui, Could you get it working? I am facing a similar issue here. Checking out new repo or cleaning the existing repo doesn't seem to work. I have tried on both 22.0.0 and on 21.1.2. Seeing the same issue - 

**[INFO] ???ƒ [build] Running command "rollup --config --configPlugin typescript"
[INFO] [!] (plugin typescript) RollupError: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?**
[INFO]     at error (C:\#Code\keycloak\js\node_modules\.pnpm\rollup@3.26.2\node_modules\rollup\dist\shared\rollup.js:349:30)
[INFO]     at Object.error (C:\#Code\keycloak\js\node_modules\.pnpm\rollup@3.26.2\node_modules\rollup\dist\shared\rollup.js:1715:20)
[INFO]     at preflight (C:\#Code\keycloak\js\node_modules\.pnpm\@rollup+plugin-typescript@11.1.2_rollup@3.26.2_tslib@2.6.0_typescript@5.1.6\node_modules\@rollup\plugin-typescript\dist\cjs\index.js:526:17)
[INFO]     at Object.buildStart (C:\#Code\keycloak\js\node_modules\.pnpm\@rollup+plugin-typescript@11.1.2_rollup@3.26.2_tslib@2.6.0_typescript@5.1.6\node_modules\@rollup\plugin-typescript\dist\cjs\index.js:776:13)
[INFO]     at C:\#Code\keycloak\js\node_modules\.pnpm\rollup@3.26.2\node_modules\rollup\dist\shared\rollup.js:1908:40
[INFO]     at async Promise.all (index 0)
[INFO]     at PluginDriver.hookParallel (C:\#Code\keycloak\js\node_modules\.pnpm\rollup@3.26.2\node_modules\rollup\dist\shared\rollup.js:1836:9)
[INFO]     at C:\#Code\keycloak\js\node_modules\.pnpm\rollup@3.26.2\node_modules\rollup\dist\shared\rollup.js:26930:13
[INFO]     at catchUnfinishedHookActions (C:\#Code\keycloak\js\node_modules\.pnpm\rollup@3.26.2\node_modules\rollup\dist\shared\rollup.js:26188:16)
[INFO]     at rollupInternal (C:\#Code\keycloak\js\node_modules\.pnpm\rollup@3.26.2\node_modules\rollup\dist\shared\rollup.js:26927:5)
[INFO]
[INFO]
[INFO] â?? [build] Failed with exit status 1
[INFO] â??ELIFECYCLEâ?? Command failed with exit code 1.

**Comment by reda-alaoui** [comment]
@Varshaa21 I followed the recommandations of `xgp` and it worked.
