### ISSUE TITLE
Facing JGroups NPE issues when running Keycloak in EKS

### ISSUE THREAD

**Issue by trixpan** [keycloak/keycloak#21119]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

We are running JGroups via Keycloak, via Infinispan, however we are hitting some issues which seem to be linked to the following NPE
 
```
[org.infinispan.remoting.transport.jgroups.JGroupsTransport] (jgroups-28,keycloak-b6bb6f754-q8g8p-17553) keycloak-b6bb6f754-q8g8p-17553 sending response for request 319962 to keycloak-7575ccf9cb-pxh4g-54580: null
java.lang.NullPointerException
        at org.jgroups.protocols.FD_SOCK2.getPhysicalAddresses(FD_SOCK2.java:445)
        at org.jgroups.protocols.FD_SOCK2.connectTo(FD_SOCK2.java:395)
        at org.jgroups.protocols.FD_SOCK2.connectToNextPingDest(FD_SOCK2.java:376)
        at org.jgroups.protocols.FD_SOCK2.handle(FD_SOCK2.java:347)
        at org.jgroups.protocols.FD_SOCK2.handle(FD_SOCK2.java:31)
        at org.jgroups.util.ProcessingQueue.process(ProcessingQueue.java:55)
        at org.jgroups.util.ProcessingQueue.add(ProcessingQueue.java:35)
        at org.jgroups.protocols.FD_SOCK2.handleView(FD_SOCK2.java:364)
        at org.jgroups.protocols.FD_SOCK2.down(FD_SOCK2.java:227)
        at org.jgroups.protocols.FailureDetection.down(FailureDetection.java:149)
        at org.jgroups.protocols.VERIFY_SUSPECT2.down(VERIFY_SUSPECT2.java:84)
        at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:619)
        at org.jgroups.protocols.UNICAST3.down(UNICAST3.java:611)
        at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:260)
        at org.jgroups.protocols.pbcast.GMS.installView(GMS.java:676)
        at org.jgroups.protocols.pbcast.ServerGmsImpl.handleViewChange(ServerGmsImpl.java:66)
        at org.jgroups.protocols.pbcast.ParticipantGmsImpl.handleViewChange(ParticipantGmsImpl.java:112)
        at org.jgroups.protocols.pbcast.GMS.handle(GMS.java:991)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:855)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:246)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:470)
        at org.jgroups.protocols.pbcast.NAKACK2.deliverBatch(NAKACK2.java:1010)
        at org.jgroups.protocols.pbcast.NAKACK2.removeAndDeliver(NAKACK2.java:943)
        at org.jgroups.protocols.pbcast.NAKACK2.handleMessageBatch(NAKACK2.java:915)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:747)
        at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:119)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:193)
        at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:202)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:288)
        at org.jgroups.protocols.Discovery.up(Discovery.java:314)
        at org.jgroups.protocols.RED.up(RED.java:119)
        at org.jgroups.protocols.TP.passBatchUp(TP.java:1204)
        at org.jgroups.util.MaxOneThreadPerSender$BatchHandlerLoop.passBatchUp(MaxOneThreadPerSender.java:289)
        at org.jgroups.util.SubmitToThreadPool$BatchHandler.run(SubmitToThreadPool.java:150)
        at org.jgroups.util.MaxOneThreadPerSender$BatchHandlerLoop.run(MaxOneThreadPerSender.java:278)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
### Version

21.1.1

### Expected behavior

cluster to not NPE when a host goes missing

### Actual behavior

crash loop due to NPE above.

### How to Reproduce?

unclear at this stage but consistently happening. Upstream bug has been confirmed and fixed

https://issues.redhat.com/browse/JGRP-2707

**Comment by mabartos** [comment]
@trixpan Thanks for creating this issue!

It means the fix will be included in the following versions of JGroups 5.2.15. We don't explicitly include the JGroup dependency in our project but rather depend on the one provided by ISPN. Thus, we need to wait for the next Infinispan release.

Maybe someone from the @keycloak/store team can provide another perspective on that.

**Comment by trixpan** [comment]
@mabartos aware of that.  First the fixed JGroups needs to be released, then Infinispan. Eventually it will make into Keycloak. The issue is affecting us atm and causing unhealthy pods back to front, so the faster that happens, the better. :-)

**Comment by sschu** [comment]
This is probably a duplicate of https://github.com/keycloak/keycloak/issues/21092.

**Comment by trixpan** [comment]
@sschu maybe. Had not seen that bug.  Guess it was opened between me reaching out to the JGroups project and #21092 being opened. :-)

**Comment by trixpan** [comment]
duplicate
