### ISSUE TITLE
ARJUNA016102: The transaction is not active

### ISSUE THREAD

**Issue by JeanMars** [keycloak/keycloak#21146]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

Hi,
not sure this is a bug or even a problem, but would like to check.
Using Keycloak 19.0.3 (sorry can't update), and LDAP integration, I see logs like:
```
2023-06-18 14:10:38,533 INFO  [org.keycloak.storage.ldap.LDAPStorageProviderFactory] (Timer-0) Sync all users from LDAP to local store: realm: TEST_REALM, federation provider: ldap
2023-06-18 14:15:38,377 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA011817: TransactionReaper::check processing TX 0:ffff0a590002:9237:2586bd24:974513 in state  RUN
2023-06-18 14:15:38,387 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA011818: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffff0a590002:9237:2586bd24:974513
2023-06-18 14:26:25,125 INFO  [org.keycloak.storage.ldap.LDAPStorageProviderFactory] (Timer-0) Sync all users finished: 0 imported users, 4850 updated users
2023-06-18 14:26:25,167 WARN  [com.arjuna.ats.arjuna] (Timer-0) ARJUNA012077: Abort called on already aborted atomic action 0:ffff0a590002:9237:2586bd24:974513
2023-06-18 14:26:25,168 ERROR [org.keycloak.storage.managers.UserStorageSyncManager] (Timer-0) Error occurred during full sync of users: java.lang.RuntimeException: javax.transaction.RollbackException: ARJUNA016102: The transaction is not active! Uid is 0:ffff0a121002:9237:2586bd24:974513
        at org.keycloak.transaction.JtaTransactionWrapper.handleException(JtaTransactionWrapper.java:78)
        at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:92)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:256)
        at org.keycloak.storage.managers.UserStorageSyncManager.syncAllUsers(UserStorageSyncManager.java:94)
        at org.keycloak.storage.managers.UserStorageSyncManager$4.run(UserStorageSyncManager.java:206)
        at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: javax.transaction.RollbackException: ARJUNA016102: The transaction is not active! Uid is 0:ffff0a121002:9237:2586bd24:974513
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1285)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:105)
        at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
        ... 7 more
```
I thought it was due to the important number of users (~5000) but using:
- JAVA_OPTS_APPEND="-Dquarkus.transaction-manager.default-transaction-timeout=180"
but same outcome and maybe more:
WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffff0a590004:57ea:413404574:364
WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff0a590004:57ea:413404574:36a in state  RUN
WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012095: Abort of action id 0:ffff0a590004:57ea:413404574:36a invoked while multiple threads active within it.
WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012381: Action id 0:ffff0a590004:57ea:413404574:36a completed with multiple threads - thread executor-thread-2 was in progress with java.base@11.0.17/jdk.internal.misc.Unsafe.park(Native Method)

Apart from that, it's running OK so maybe it's not an issue but would like to make sure.

### Version

19.0.3

### Expected behavior

Note sure

### Actual behavior

Note sure

### How to Reproduce?

Note sure

**Comment by sschu** [comment]
It still looks like a transaction timeout. Can you try increasing the timeout even more? We use 5 minutes as default timeout and would increase it even more if we know there is a long-running operation.

**Comment by JeanMars** [comment]
Thanks, will try again. But I noted that moving from 1 min to 3 min did not increase the number of users reported in sync.

**Comment by JeanMars** [comment]
Hi,
looks like it's not a bug; increasing timeout solves the issue. Will do more test but If I don't report before next Tuesday, please close that ticket.

**Comment by JeanMars** [comment]
Hi,
I confirm this has been solved by simply increasing the timeout to 3600; looks OK for ~25,000 users on a realm.
Thanks for your responses!
