### ISSUE TITLE
NullPointerException on DefaultAuthenticationFlow

### ISSUE THREAD

**Issue by luandrea** [keycloak/keycloak#21324]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

I have configured a microsoft authentication with OIDC.
I open the browser to https://myhost.com/auth/realms/my-test-realm/account/ , click on Sign in.
I get redirected correctly to Microsoft login, do it successfully.
When I return back to Keycloak I get this error on the browser: failed to initialize keycloak

The user is correctly imported into Keycloak users list.

Looking at the log I see this stacktrace:

`2023-06-29 17:55:43,991 DEBUG [org.keycloak.authentication.DefaultAuthenticationFlow] (executor-thread-11) check execution: 'auth-username-password-form', requirement: 'REQUIRED'
2023-06-29 17:55:43,991 ERROR [org.keycloak.services] (executor-thread-11) KC-SERVICES0015: Unexpected error when authenticating client: java.lang.NullPointerException
        at org.keycloak.authentication.DefaultAuthenticationFlow.isProcessed(DefaultAuthenticationFlow.java:68)
        at org.keycloak.authentication.DefaultAuthenticationFlow.isProcessed(DefaultAuthenticationFlow.java:63)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:373)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:249)
        at org.keycloak.authentication.AuthenticationProcessor.authenticateClient(AuthenticationProcessor.java:897)
        at org.keycloak.protocol.oidc.utils.AuthorizeClientUtil.authorizeClient(AuthorizeClientUtil.java:50)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.checkClient(TokenEndpoint.java:265)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequestInternal(TokenEndpoint.java:213)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.access$100(TokenEndpoint.java:131)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$1.runInternal(TokenEndpoint.java:185)
        at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:67)
        at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:44)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:299)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:178)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`

### Version

21.1.1

### Expected behavior

I expect to be redirected correctly to the account page with as an authenticated user.

### Actual behavior

failed to initialize keycloak

### How to Reproduce?

I configured our Microsoft endpoints with OIDC using Discovery endpoint.

**Comment by luandrea** [comment]
Hi all, the problem was that I created a test flow and I bound it to the Client authentication flow.
This test flow only had Username and password form and OTP, both as required.

Resetting the Client authentication flow to the flow "clients" solved the issue.

Maybe a more talking error would help.
