### ISSUE TITLE
Intermittent ConcurrentModificationException during JBoss EAP startup with Keycloak adapter

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#21367]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/jee

### Describe the bug

Already reported in Jira: https://issues.redhat.com/browse/KEYCLOAK-7254

When the Keycloak subsystem is used to configure client deployment the following exception is intermittently thrown:

```
(MSC service thread 1-4) MSC000001: Failed to start service org.wildfly.security.http-server-mechanism-factory."some-client.war": org.jboss.msc.service.StartException in service org.wildfly.security.http-server-mechanism-factory."some-client.war": Failed to start service
at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
at org.jboss.dmr.ObjectModelValue.asPropertyList(ObjectModelValue.java:161)
at org.jboss.dmr.ModelNode.asPropertyList(ModelNode.java:529)
at org.keycloak.subsystem.adapter.extension.KeycloakAdapterConfigService.setJSONValues(KeycloakAdapterConfigService.java:267)
at org.keycloak.subsystem.adapter.extension.KeycloakAdapterConfigService.getJSON(KeycloakAdapterConfigService.java:261)
at org.keycloak.subsystem.adapter.extension.KeycloakHttpAuthenticationFactoryService.start(KeycloakHttpAuthenticationFactoryService.java:50)
at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
... 6 more
```

### Version

18.0.2

### Expected behavior

No CME is thrown

### Actual behavior

CME is intermittently thrown

### How to Reproduce?

-

### Anything else?

- There was a PR already created for this but it was not finished https://github.com/keycloak/keycloak/pull/5202
- war files associated with the error message do not need to be deployed to the server group.

**Comment by mposolda** [comment]
Considering that we are going to remove OIDC adapters (which are already deprecated), this looks like very low priority.
