### ISSUE TITLE
Not able to start Keycloak in Docker Swarm

### ISSUE THREAD

**Issue by maddin79** [keycloak/keycloak#21464]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Hello,

we really liked Keycloak so far and worked a long time with version 16. But now we want to upgrade to the newest version and we can not start the server in our Docker Swarm environment. I searched now for two days and tried everything what I could find, but still the same error "- No value present". 
Sorry, but I must say for such a Server, with the switch to a new deployment system, the documentation on that is really bad. 

### Version

21.1.2

### Expected behavior

Starting the server

### Actual behavior

I followed the advice in the documentation to build a optimized version and start it with kc.sh --optimized. The result is: 

```
ERROR: Failed to start server in (production) mode
Error details:
io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors have prevented the application from starting. The errors are:
  - No value present
  - No value present
```

And that is even with the --verbose option. Does not look really verbose to me. If I remove the --optimized flag I get the following error:

```
2023-07-05 14:24:42,072 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation
2023-07-05 14:24:42,297 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3f0846c6
2023-07-05 14:24:42,297 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3f0846c6
2023-07-05 14:24:42,369 DEBUG [io.quarkus.runtime.util.ContainerRuntimeUtil] (main) Failure to read info output from docker: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at io.quarkus.runtime.util.ContainerRuntimeUtil.getRootlessStateFor(ContainerRuntimeUtil.java:71)
	at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<init>(ContainerRuntimeUtil.java:111)
	at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<clinit>(ContainerRuntimeUtil.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3837)
	at java.base/java.lang.Class.getEnumConstants(Class.java:3812)
	at io.quarkus.runtime.configuration.HyphenateEnumConverter.<init>(HyphenateEnumConverter.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:822)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:865)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigValue(BuildTimeConfigurationReader.java:776)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigGroup(BuildTimeConfigurationReader.java:722)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:361)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:322)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:29)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:322)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:195)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)

	... 55 more
2023-07-05 14:24:42,373 DEBUG [io.quarkus.runtime.util.ContainerRuntimeUtil] (main) Failure to read info output from podman: java.io.IOException: Cannot run program "podman": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at io.quarkus.runtime.util.ContainerRuntimeUtil.getRootlessStateFor(ContainerRuntimeUtil.java:71)
	at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<init>(ContainerRuntimeUtil.java:111)
	at io.quarkus.runtime.util.ContainerRuntimeUtil$ContainerRuntime.<clinit>(ContainerRuntimeUtil.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3837)
	at java.base/java.lang.Class.getEnumConstants(Class.java:3812)
	at io.quarkus.runtime.configuration.HyphenateEnumConverter.<init>(HyphenateEnumConverter.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:822)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.getConverter(BuildTimeConfigurationReader.java:865)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigValue(BuildTimeConfigurationReader.java:776)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.readConfigGroup(BuildTimeConfigurationReader.java:722)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:361)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:322)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:29)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:322)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:195)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)

	... 55 more
ERROR: Failed to run 'build' command.
Error details:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:184)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:121)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:89)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.keycloak.quarkus.runtime.configuration.mappers.DatabasePropertyMappers.isDevModeDatabase(DatabasePropertyMappers.java:187)
	at org.keycloak.quarkus.runtime.configuration.mappers.DatabasePropertyMappers.resolveUsername(DatabasePropertyMappers.java:166)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(PropertyMapper.java:208)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.getConfigValue(PropertyMapper.java:114)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.getValue(PropertyMappers.java:47)
	at org.keycloak.quarkus.runtime.configuration.PropertyMappingInterceptor.getValue(PropertyMappingInterceptor.java:43)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:324)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.lambda$run$2(BuildTimeConfigurationReader.java:473)
	at io.smallrye.config.Expressions.withoutExpansion(Expressions.java:29)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:473)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:322)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:29)
	at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:322)
	at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:195)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)

	... 26 more
```

Why the heck is it now locking for docker or podman? I could not find any hint in the right direction. Tried everything what I could find on the internet. No change in the behavior. There is not even a hint how to debug this.

The fun starts when I create a local docker compose file. Then it works and I can reach the server on my computer. 

### How to Reproduce?

As I said, the image is build from the suggestions in the documentation. The used database is PostgreSQL and we use a Traefik as proxy (works fine with the 16 version). The docker compose file for the tests looks like this:

```
version: '3.8'

services:
  
  keycloak:
    image: our.docker.repository/keycloak
    networks:
      traefik_public:
      keycloak-demo-net:  
        aliases:
          - keycloak
    environment:
      - KC_DB=keycloak
      - KC_DB_URL=our.postgres.server
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN=admin
      - KC_HOSTNAME=hostname
      - KC_HOSTNAME_ADMIN_URL=https://hostname/admin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.auth.rule=Host(`hostname`)
        - traefik.http.routers.auth.entrypoints=https
        - traefik.http.services.auth.loadbalancer.server.port=8080
        - traefik.http.routers.auth.service=auth
        - traefik.http.routers.auth.tls.certresolver=le
    secrets:
      - source: keycloak_demo_db_pw
        target: keycloak_demo_db_pw
        mode: 0440
      - source: keycloak_demo_admin_pw
        target: keycloak_demo_admin_pw
        mode: 0440

networks:
  traefik_public:
    external: true
  keycloak-demo-net:
    external: true

secrets:
  keycloak_demo_admin_pw:
    external: true
  keycloak_demo_db_pw:
    external: true
```

### Anything else?

Any help or hint is highly appreciated. Maybe I overlook something really simple.... 

Thanks in advance...

Cheers
Martin

**Comment by sschu** [comment]
The error looks like some part of the DB configuration is missing. You can ignore the parts about docker and podman - this is just a debug message because internally it seems to be checking if docker or podman are available but it is not related to your problem (except for the fact that having another problems increases the log level to trace so you see these messages).

**Comment by vmuzikar** [comment]
@maddin79 Thanks for reporting this and sorry you are facing issues. Could you please provide your dockerfile that you used for building a custom image? Note that any build options need to be present at the image build time, i.e. in the dockerfile.

Also, I noticed your DB vendor (`KC_DB`) is set to an invalid value `keycloak`.

I believe this issue is just a misconfiguration, hence I'm gonna close it for now. Feel free to reopen if that's not the case.
