### ISSUE TITLE
Flaky test: org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest#displayAvailableAuthenticators

### ISSUE THREAD

**Issue by ghost** [keycloak/keycloak#21575]
## org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest#displayAvailableAuthenticators
[Keycloak CI - WebAuthn IT (firefox)]()

```
java.lang.AssertionError: Expected SigningInPage but was Keycloak Account Management (https://localhost:8543/auth/realms/test/account/#/security/signingin&state=1f325e75-b8bd-4277-9444-40934c03db69&session_state=1f03e319-efa0-4c64-a8d5-c1723b3eff23&code=e6724d93-d374-4716-a5df-63b8f0cd6efc.1f03e319-efa0-4c64-a8d5-c1723b3eff23.972959cb-83d7-4e62-a842-9a25bfab19ee)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.page.AbstractPage.assertCurrent(AbstractPage.java:110)
	at jdk.internal.reflect.GeneratedMethodAccessor538.invoke(Unknown Source)
...
```

**Comment by mabartos** [comment]
WebAuthn tests should be stable so far after upgrading the Selenium dependency: https://github.com/keycloak/keycloak/issues/29778

Closing for now.
