### ISSUE TITLE
Issue while creating Client Based Policy.

### ISSUE THREAD

**Issue by sabinayakc** [keycloak/keycloak#21747]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/client/node

### Describe the bug

I am trying to create a client based policy but can't seem to make it work. 

Here is my code.
```
const createdPolicy = await this.keycloakAdminClient.clients.createPolicy(
        {
          id: clientUniqueId,
          type: 'client',
        },
        {
          name: "Test-Policy",
          type: 'client',
          resources: ["XXASAS"],
          logic: Logic.POSITIVE,
          decisionStrategy: DecisionStrategy.UNANIMOUS,
          description: "Test",
          config: {
            clients: ["XXXYYZZ"],
          }
        },
      );
```

and the error message:

Console:
```
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 500,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Internal Server Error',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  },
  responseData: { error: 'unknown_error' }
 ```
 
 Keycloak:
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "config" (class org.keycloak.representations.idm.authorization.ClientPolicyRepresentation), not marked as ignorable (13 known properties: "resources", "clients", "scopesData", "name", "decisionStrategy", "policies", "owner", "type", "id", "description", "logic", "scopes", "resourcesData"])
2023-07-17 08:17:20  at [Source: (String)"{"name":"test1-policy","type":"client","resources":["62795599-06c8-4835-8965-f55ac94e98da"],"logic":"POSITIVE","decisionStrategy":"UNANIMOUS","description":"Test","config":{"clients":["9eda5184-d1c8-4cdf-862d-5d062209ea7a"],"resources":["62795599-06c8-4835-8965-f55ac94e98da"]}}"; line: 1, column: 174] (through reference chain: org.keycloak.representations.idm.authorization.ClientPolicyRepresentation["config"])
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2036)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
2023-07-17 08:17:20     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
2023-07-17 08:17:20     at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:75)
2023-07-17 08:17:20     at org.keycloak.authorization.admin.PolicyTypeService.doCreateRepresentation(PolicyTypeService.java:79)
2023-07-17 08:17:20     ... 61 more
```

### Version

22.0.0

### Expected behavior

Should be able to create a client based policy. 

### Actual behavior

500 Internal Server error while creating a client based policy.

### How to Reproduce?

- Create two clients with authorization enabled.
- Create a policy that allows client A access to default resource of clientB

### Anything else?

Works using POSTMAN 
<img width="710" alt="image" src="https://github.com/keycloak/keycloak/assets/13154166/57b796ca-81fe-412c-8588-9e9a83a1c944">

**Comment by PhilKes** [comment]
I think something got mixed up here.
If you create a client policy like you want to in the UI, the following request is sent:


http://0.0.0.0:8080/admin/realms/master/clients/{clientUniqueId}/authz/resource-server/policy/client

Request-Body:
```json
{
  "name": "Test-Policy",
  "description": "",
  "clients": ["XXXYYZZ"],
  "logic": "POSITIVE"
}
```

The `PolicyRepresentation` is created from the JSON by
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/services/src/main/java/org/keycloak/authorization/admin/PolicyTypeService.java#L77
with `representationType`=`org.keycloak.representations.idm.authorization.ClientPolicyRepresentation` which does not have `config` field like you used, instead there is the `clients` field with the Set of clients directly:
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/core/src/main/java/org/keycloak/representations/idm/authorization/ClientPolicyRepresentation.java#L28

So your request should look like this:
```js
const createdPolicy = await this.keycloakAdminClient.clients.createPolicy(
        {
          id: clientUniqueId,
          type: 'client',
        },
        {
          name: "Test-Policy",
          type: 'client',
          resources: ["XXASAS"],
          logic: Logic.POSITIVE,
          decisionStrategy: DecisionStrategy.UNANIMOUS,
          description: "Test",
          clients: ["XXXYYZZ"],
        },
      );
```

But in the `PolicyRepresentation` interface used in the node client the `clients` field is missing:
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/js/libs/keycloak-admin-client/src/defs/policyRepresentation.ts#L26-L40

So the fix would be to add the `clients` field to this interface, right @mposolda ?
