### ISSUE TITLE
Flaky test: org.keycloak.testsuite.script.DeployedScriptAuthenticatorTest#loginShouldWorkWithScriptAuthenticator

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#21779]
## org.keycloak.testsuite.script.DeployedScriptAuthenticatorTest#loginShouldWorkWithScriptAuthenticator
[Keycloak CI - Java Distribution IT (windows-latest - temurin - 19)]() / [Pull Request #21675](https://github.com/keycloak/keycloak/pull/21675)

```
java.lang.AssertionError: expected:<201> but was:<404>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
...
```

```
jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:242)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:41)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:136)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
...
```

**Comment by mposolda** [comment]
Looks that all of those have same cause and should be likely worked/investigated together:

https://github.com/keycloak/keycloak/issues/21780
https://github.com/keycloak/keycloak/issues/21779
https://github.com/keycloak/keycloak/issues/21778

**Comment by stianst** [comment]
Failed 3 times in a row in https://github.com/keycloak/keycloak/actions/runs/5595202024 causing the job to error.
