### ISSUE TITLE
Expose Keycloak config errors in the Keycloak CR status field

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#21816]
### Description

At startup, Keycloak performs several config validations ensuring all required options are specified and that the options values have correct format. In case the validations fail, an exception is thrown. Exceptions are also thrown in other misconfiguration cases such as wrong DB credentials.

The Operator should be able to expose this kind of errors and expose them in the CR's status.

We should avoid implementing server config validations at the Operator level as the Operator does not know what config options has been already preset in a Keycloak custom image. Server config validations need to be done at the server level.

### Details

Implementation requires discussion.

We might need to try and interpret the server log and look for known exception types. Other way might be to send some message with failure details to the Operator (a new log handler?).

We might also need to improve the exceptions format (and possibly types) for the startup failures due to misconfiguration.

**Comment by vmuzikar** [comment]
Related to https://github.com/keycloak/keycloak/issues/13608

**Comment by shawkins** [comment]
Without the verbose option the errors seem to appear on a single line:

```
ERROR: Strict hostname resolution configured but no hostname setting provided
```

With the verbose option the message is embedded in the stacktrace:

```
ERROR: Unexpected error when starting the server in (production) mode
Error details:
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
...
Caused by: java.lang.RuntimeException: Strict hostname resolution configured but no hostname setting provided
        at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.init(DefaultHostnameProvider.java:238)
        at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.<init>(QuarkusKeycloakSessionFactory.java:83)
```

> We might need to try and interpret the server log and look for known exception types.

We could scrape the pod logs in KeycloakDeployment.checkForPodErrors.

Would that require users of pod template overrides specifying the start command also supply the verbose option to make this functionality work, or would try to account for both verbose and non-verbose logs?

> Other way might be to send some message with failure details to the Operator (a new log handler?).

Seems like we could use kubernetes events for this.  The only drawback would be the short retention time, but once added to the keycloak status they could be retained if the status aggregation logic knows to not clear them.

> We might also need to improve the exceptions format (and possibly types) for the startup failures due to misconfiguration.

That seems good too.  It seems a little problematic to parse a semi-structured format and scraping for exception messages.

**Comment by vmuzikar** [comment]
> Would that require users of pod template overrides specifying the start command also supply the verbose option to make this functionality work, or would try to account for both verbose and non-verbose logs?

We use `--verbose` by default, we don't make it configurable. Pod templates are an escape hatch for scenarios we don't support with the Operator. If someone overrides `--verbose` there, they are on their own, error propagation won't work for them.

> Seems like we could use kubernetes events for this. The only drawback would be the short retention time, but once added to the keycloak status they could be retained if the status aggregation logic knows to not clear them.

I see another drawback of this "push" approach – Keycloak would need to have a service account to access K8s API to create Events. Or did you mean Events would be created by the Operator (base on logs scraping)? That might work (in addition to just setting Status).

**Comment by shawkins** [comment]
This issue is somewhat blocked by #13608 as most of the configuration that is actually supplied comes from the env.  The only thing that will be caught currently is missing configuration, such as not specifying hostname-strict as shown here.
