### ISSUE TITLE
v22.0.1 - Windows: kcadm.bat gives Java Exception

### ISSUE THREAD

**Issue by ncphins** [keycloak/keycloak#21851]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/cli

### Describe the bug

I have installed v22.0.1 and when trying to run the kcadm.bat to import realms (and other items) the batch file will not run. Even running it by itself (to display the help) will give a Java Exception.

PS C:\Development\Test\manual_installs\keycloak-nightly\bin> .\kcadm.bat
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/WindowsAnsiOutputStream
        at org.jboss.aesh.console.settings.SettingsImpl.getTerminal(SettingsImpl.java:381)
        at org.jboss.aesh.console.Console.init(Console.java:190)
        at org.jboss.aesh.console.Console.<init>(Console.java:118)
        at org.jboss.aesh.console.AeshConsoleImpl.<init>(AeshConsoleImpl.java:98)
        at org.jboss.aesh.console.AeshConsoleBuilder.create(AeshConsoleBuilder.java:160)
        at org.keycloak.client.admin.cli.KcAdmMain.main(KcAdmMain.java:74)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.WindowsAnsiOutputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

Java Version: 
openjdk 17.0.8 2023-07-18 LTS
OpenJDK Runtime Environment Zulu17.44+15-CA (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.44+15-CA (build 17.0.8+7-LTS, mixed mode, sharing)

Windows Version:
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎6/‎9/‎2022
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

Running on the same machine with the same version of Java using Keycloak 21.1.2 does not show this error.

The server seems to be running fine with this version of Java. I can access the server, login, configure, etc.

### Version

22.0.1

### Expected behavior

The admin cli will run as expected.

### Actual behavior

PS C:\Development\Test\manual_installs\keycloak-nightly\bin> .\kcadm.bat
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/WindowsAnsiOutputStream
        at org.jboss.aesh.console.settings.SettingsImpl.getTerminal(SettingsImpl.java:381)
        at org.jboss.aesh.console.Console.init(Console.java:190)
        at org.jboss.aesh.console.Console.<init>(Console.java:118)
        at org.jboss.aesh.console.AeshConsoleImpl.<init>(AeshConsoleImpl.java:98)
        at org.jboss.aesh.console.AeshConsoleBuilder.create(AeshConsoleBuilder.java:160)
        at org.keycloak.client.admin.cli.KcAdmMain.main(KcAdmMain.java:74)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.WindowsAnsiOutputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

### How to Reproduce?

Install v22.0.1 on Windows and go to the bin folder, run "kcadm.bat".

**Comment by Pepo48** [comment]
@ncphins thanks for the issue report. I tried to looked at it quickly and I couldn't reproduce it on our Windows environment (a VM with Windows Server 2022 installed).
I tested it with 22.0.0, 22.0.1 and with the latest nightly.
![image](https://github.com/keycloak/keycloak/assets/12138171/ba8e7174-74a3-4ed2-9343-35bb5ce747bd)


 (cc: @vmuzikar)

**Comment by ncphins** [comment]
I sort of figured it was not an easily reproducible or it would not have made it in the release. But I am seeing it on everything after 22.

Let me see if I can figure out something here.

![image](https://github.com/keycloak/keycloak/assets/50498893/369672a7-732f-45f2-8b00-25d03383b878)

**Comment by Pepo48** [comment]
in order to scratch JDK from the list of possible culprits, I tried it even with the Azul Zulu Builds of OpenJDK ver. 17.0.8 2023-07-18 LTS, but still no luck with reproducing the issue.

**Comment by ncphins** [comment]
I must be missing something or doing something wrong. I tried a fresh Windows Server 2019 machine and I see the same. I guess we can close this. I have no idea what I am doing wrong. I have never really had issues installing up until 22.

![image](https://github.com/keycloak/keycloak/assets/50498893/d34e11da-c1d9-4312-8819-edac984a5349)

**Comment by Pepo48** [comment]
It's difficult to investigate the issue since I'm not able to reproduce it, but if you wan't you can try build the distribution from the source code on your own directly on the affected machine and see if it helps:
```mvn clean install -Pwindows-properties-cli,app-server-wildfly,distribution -DskipTests -Dlog4j.skipJansi=true```

The first two profiles are just a workaround, because we currently have some other problems with building the project on Windows platform. From what I understand, the issue could be connected to Log4j and the coloured output (but again, it's just a guess).

**Comment by JPA2015** [comment]
I get the same Exception when starting kcadm from v22.0.1 on Windows Server 2022 Standard (21H2), openjdk 17.0.7 2023-04-18.
I just tried with v21.1.2 too, and with this version kcadm works normally.

**Comment by Pepo48** [comment]
update: I was finally able to reproduce it on my personal W11 laptop. I tried to build the dist with `-Dlog4j.skipJansi=true` property, but it doesn't resolve the issue.

**Comment by ncphins** [comment]
Ok. I hoped it was just a config error on my part, but I guess not. I built locally (with the skipJansi flag set) and still see the issue as well. I can build a branch if you need me too. Let me know if there is anything I can help with.

**Comment by cedric-c84-eu** [comment]
The issue could be that the `aesh` version (0.66.19) in `keycloak-admin-cli-22.0.1.jar` is too old for the new `jansi` version (2.4.0, previously 1.16) used in this JAR.

**Comment by Pepo48** [comment]
After the investigation I found out that `org.fusesource.jansi` dependency is the culprit. The Quarkus Platform BOM that we introduced in #21426 contains `jansi` version 2.4.0. `WindowsAnsiOutputStream` isn't though present in this version, therefore the override to ver. 1.18 is needed to solve the exception.

I am going to sent a PR with the necessary change.

**Comment by Pepo48** [comment]
Reopening due to the backport.

**Comment by ncphins** [comment]
I pulled the latest from main this AM and built. The admin CLI works fine on my Windows machine now. Thanks for all the support!

**Comment by edge929** [comment]
Stumbled upon this same issue with 22.0.1. Jansi removed WindowsAnsiOutputStream after 1.18. Will take 22.0.2 before we go to production.
