### ISSUE TITLE
Unable to use `<` as part of a password

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#21951]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/cli

### Describe the bug

Using a `<` as part of the password doesn't work.

### Version

22.0.0

### Expected behavior

Should work.

### Actual behavior

Shows an error and doesn't work:

```
bash-5.1$ /opt/keycloak/bin/kcadm.sh config --password '<'
aesh: syntax error near unexpected token 'newline'
```

### How to Reproduce?

Execute:

```
/opt/keycloak/bin/kcadm.sh config --password '<'
```

**Comment by ctron** [comment]
Playing a bit more with this, trying to work around the issue, it turns out that some Jave component is the reason for this:

```
+ java -cp /opt/keycloak/bin/client/keycloak-admin-cli-22.0.0.jar --add-opens=java.base/java.security=ALL-UNNAMED -Dkc.lib.dir=/opt/keycloak/bin/client/lib org.keycloak.client.admin.cli.KcAdmMain config --config /tmp/kcadm.config credentials config --server http://keycloak:8080 --realm master --user admin --password XXXXX
Exception in thread "Aesh Process Loop 1206051975" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at org.jboss.aesh.console.Console.parseOperations(Console.java:931)
at org.jboss.aesh.console.Console.processOperationResult(Console.java:802)
at org.jboss.aesh.console.Console.processInternalOperation(Console.java:780)
at org.jboss.aesh.console.Console.execute(Console.java:738)
at org.jboss.aesh.console.Console.access$900(Console.java:73)
at org.jboss.aesh.console.Console$6.run(Console.java:647)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
```
