### ISSUE TITLE
error when signing in with terms & conditions enabled: "Unexpected error when handling authentication request to identity provider."

### ISSUE THREAD

**Issue by andrewzah** [keycloak/keycloak#21967]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

2023-07-24 18:43:12,468 WARN  [org.keycloak.services] (executor-thread-31) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: Unable to find factory for Required Action: TERMS_AND_CONDITIONS did you forget to declare it in a META-INF/services file?

### Version

18.0.2 on quarkus

### Expected behavior

I should be able to log in.

### Actual behavior

The page displays "Unexpected error when handling authentication request to identity provider.".

### How to Reproduce?

Enable terms and conditions.

### Anything else?

Keycloak 18.0.2 previously was working for us with a custom otp-form.ftl and terms.ftl. Now it no longer works and simply gives this error trace. I did not verify this on the latest nightly, as I cannot upgrade past 18.x for now here. I can't log into the admin console on 22.x so it doesn't matter anyway.

```
keycloak-keycloak-1  | 2023-07-25 19:38:40,407 WARN  [org.keycloak.services] (executor-thread-2) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: Unable to find factory for Required Action: TERMS_AND_CONDITIONS did you forget to declare it in a META-INF/services file?
keycloak-keycloak-1  |  at org.keycloak.services.managers.AuthenticationManager.toRequiredActionFactory(AuthenticationManager.java:1411)
keycloak-keycloak-1  |  at org.keycloak.services.managers.AuthenticationManager.lambda$evaluateRequiredActionTriggers$18(AuthenticationManager.java:1373)
keycloak-keycloak-1  |  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
keycloak-keycloak-1  |  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak-keycloak-1  |  at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
keycloak-keycloak-1  |  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
keycloak-keycloak-1  |  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak-keycloak-1  |  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
keycloak-keycloak-1  |  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
keycloak-keycloak-1  |  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak-keycloak-1  |  at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
keycloak-keycloak-1  |  at org.keycloak.services.managers.AuthenticationManager.evaluateRequiredActionTriggers(AuthenticationManager.java:1374)
keycloak-keycloak-1  |  at org.keycloak.services.managers.AuthenticationManager.nextRequiredAction(AuthenticationManager.java:1079)
keycloak-keycloak-1  |  at org.keycloak.authentication.AuthenticationProcessor.nextRequiredAction(AuthenticationProcessor.java:1136)
keycloak-keycloak-1  |  at org.keycloak.authentication.AuthenticationProcessor.authenticationComplete(AuthenticationProcessor.java:1126)
keycloak-keycloak-1  |  at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:998)
keycloak-keycloak-1  |  at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:321)
keycloak-keycloak-1  |  at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:292)
keycloak-keycloak-1  |  at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:276)
keycloak-keycloak-1  |  at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:349)
```

**Comment by andrewzah** [comment]
Nevermind, this was an issue with a custom provider. https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-21-0-2

> If any of your custom extensions relies on this attribute, you may need to adjust your code to check both attributes terms_and_conditions and TERMS_AND_CONDITIONS.

Also, the admin console was fixed for 22.x by setting `KC_HOSTNAME_ADMIN_URL`. and /realms/{realm}/account became accessible after setting Clients > Account Console > Web Origins to `+`.
