### ISSUE TITLE
KC21 Unable to login due to ClassCastException with SessionEntityWrapper

### ISSUE THREAD

**Issue by avanlangup** [keycloak/keycloak#22055]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

During login, I have errors due to ClassCastException when trying to read session from Infinispan external cache.

KC 21.1.1 and ISPN remote server 14.0.9.Final-1

 

### Version

21.1.1

### Expected behavior

User is able to login in admin console

### Actual behavior

`
 ERROR  [o.k.s.e.KeycloakErrorHandler:61] (executor-thread-0) Uncaught server error:  java.lang.ClassCastException: class org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity cannot be cast to class org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper  (org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity and org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @19e0dffe) at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.get(InfinispanChangelogBasedTransaction.java:128) at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionEntity(InfinispanUserSessionProvider.java:325) at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:258) at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:253)

`

### How to Reproduce?

Prerequisite: Configure remote ISPN server for session caches

Login in master realm with admin user

### Anything else?

Due to numerous issues with map storage and hotrod, we are trying to setup legacy store with external ISPN

**Comment by avanlangup** [comment]
Similar to https://github.com/keycloak/keycloak/issues/14438

**Comment by avanlangup** [comment]
ISPN configuration
[cache.txt](https://github.com/keycloak/keycloak/files/12191023/cache.txt)

**Comment by avanlangup** [comment]
Found the same topic on older version : https://stackoverflow.com/questions/75652382/classcastexceptions-running-keycloak-with-remote-infinispan-cache

**Comment by avanlangup** [comment]
i removed some attributes from transport like cluster and node names
