### ISSUE TITLE
com.mysql.cj.jdbc.MysqlXAException: XAER_RMERR: Fatal error occurred in the transaction branch

### ISSUE THREAD

**Issue by jean-christophe-manciot** [keycloak/keycloak#22083]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

The exception described below seems to come from a discrepancy between mysql-server version and the mysql-connector-java version.

mysql-connector-java is not supported anymore on Ubuntu since bionic and installing the right version from the [official Oracle package](https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-binary-installation.html) does not change anything.

I suspect that there is a special way to hook that mysql-connector-j jar into keycloak as there was for the [deprecated wildfly client adapter](https://medium.com/@hasnat.saeed/install-and-configure-mysql-jdbc-driver-on-jboss-wildfly-e751a3be60d3).
Updating the ```CLASSPATH``` environment variable has no effect.

### Version

22.0.1

### Expected behavior

No exception

### Actual behavior

```
2023-07-28 12:58:30,192 DEBUG [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) Database ->
       name : MySQL
    version : 8.0.33-0ubuntu0.23.04.2
      major : 8
      minor : 0
2023-07-28 12:58:30,193 DEBUG [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) Driver ->
       name : MySQL Connector/J
    version : mysql-connector-java-8.0.30 (Revision: 1de2fe873fe26189564c030a343885011412976a)
      major : 8
      minor : 0
2023-07-28 12:58:30,193 DEBUG [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) JDBC version : 4.2
2023-07-28 12:58:30,227 WARN  [com.arjuna.ats.jta] (Periodic Recovery) ARJUNA016027: Local XARecoveryModule.xaRecovery got XA exception XAException.XAER_RMERR: com.mysql.cj.jdbc.MysqlXAException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
	at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:344)
	at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:189)
	at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:117)
	at io.agroal.narayana.RecoveryXAResource.recover(RecoveryXAResource.java:31)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoveryFirstPass(XARecoveryModule.java:735)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:249)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:191)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:770)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)
Caused by: java.sql.SQLException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:168)
	... 7 more
```

### How to Reproduce?

On MySQL external server on Ubuntu 23.04:
- mysql-server 8.0.33-0ubuntu0.23.04.2

On keycloak server 22.0.1:
Building with:
```
bin/kc.sh build --cache-config-file="cache-ispn-tcpping.xml"
```
and starting with:
```
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD='my-password' 
KC_EXTERNAL_ADDR=192.168.122.21 
KC_BIND_ADDR=192.168.122.21 
KC_BIND_PORT=7800 
KC_INITIAL_HOSTS='"192.168.122.21[7800],192.168.122.22[7800]"'

bin/kc.sh start --optimized &
```

**Comment by jean-christophe-manciot** [comment]
@pedroigor 

I also tried to drop the following jar files in the providers directory before the build, but the same exception pops up: 
- libintl-0.21.jar
- mysql-connector-j-8.0.33.jar

However, the MySQL and MySQL Connector/J versions do not appear in the debug log.

**Comment by rmartinc** [comment]
Hi!
I haven't tested this but it can be the same that it's reported in [this stackoverflow thread](https://stackoverflow.com/questions/56831529/configuring-a-xa-datasource-to-mysql-8-db-with-spring-boot-and-bitronix-jta-mana). Can you please try what happens if you add XA_RECOVER_ADMIN grant to the database user?

**Comment by jean-christophe-manciot** [comment]
That exception is gone.

**Comment by jean-christophe-manciot** [comment]
This special privilege requirement should be added in the [keycloak doc](https://www.keycloak.org/server/db) regarding MySQL 8.0+.
