### ISSUE TITLE
UI Users page reports 'I.config.enabled is undefined' when adding UserStorageProvider

### ISSUE THREAD

**Issue by justin-stephenson** [keycloak/keycloak#22087]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In keycloak 22.0.1, adding a custom User Storage provider causes the 'Users' and 'Groups' admin console pages to generate an error.

![image](https://github.com/keycloak/keycloak/assets/13416969/37f09a8b-7ba5-4f91-a2d0-79e37ad13a6b)

The provider was added on the command line:

~~~
[justin@fedora bin]$ ./kcadm.sh create components \        
        -r master \                                        
        -s name=scimipa \                                  
        -s providerId=scim \                               
        -s providerType=org.keycloak.storage.UserStorageProvider \                                                     
...
<snip>
...
        -s 'config.extraattrs=["mail:mail, sn:sn, givenname:givenname"]' \                                             
        -s 'config.users_dn=["ou=people,dc=ipa,dc=test"]' \                                                            
        -s 'config.addintgdomain=["True"]'                  
Created new component with id '289071b8-9278-465c-9a64-7f809c204d33' 
~~~

Browser console shows the following errors:

![image](https://github.com/keycloak/keycloak/assets/13416969/5784d3c9-4aab-4147-bc1a-b0de74ce29d5)

### Version

22.0.1

### Expected behavior

Properly display the Users and other pages

### Actual behavior

See error above.

### How to Reproduce?

The only change made was adding my custom user storage provider[1] with Keycloak ` ./kcadm.sh create components` which returns successfully.

[1] https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/

**Comment by agagancarczyk** [comment]
hi @justin-stephenson Thank you for reporting this issue. 

Upon investigating the issue, I noticed that you were attempting to create a provider with the providerId "scim." Unfortunately, we do not support this particular provider at the moment. 

In order to verify this finding I constructed the following simple command with your `providerId=scim` which resulted in a null [HTTP 400 Bad Request] error.

`./kcadm.sh create components -r master -s name=scimipa -s providerId=scim -s providerType=org.keycloak.storage.UserStorageProvider -s parentId=3d9c572b-8f33-483f-98a6-8bb421667867 -s 'config.priority=["1"]' -s 'config.editMode=["WRITABLE"]'
`
If you substitute `providerId=scim` with `providerId=scim` in the above command, a new component will be successfully created.

To determine the list of supported providers, you can use the following command:

`kcadm.sh get serverinfo -r master --fields 'identityProviders(*)'
`

For more information please refer to our [Keycloak documentation](https://www.keycloak.org/docs/latest/server_admin/#storage-provider-operations). 

Please let me know if this helps and if there is anything else I can help you with this issue.

**Comment by justin-stephenson** [comment]
Hi @agagancarczyk Thank you for investigating this issue.

This custom plugin is being built and deployed into the `$keycloak/providers` directory (https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/blob/main/redeploy-plugin.sh). This is done as described in https://www.keycloak.org/docs/latest/server_development/#packaging-and-deployment

I can see the 'scim' providerId visible in the below output, the `kcadm.sh create components` command completes successfully but then the error is seen on the 'Users' and 'Groups' admin UI pages.
~~~
[justin@fedora bin]$ ./kcadm.sh get serverinfo -r master | less
...
<snip>
...
    "storage" : {
      "internal" : false,
      "providers" : {
        "scim" : {
          "order" : 0
        },
        "ldap" : {
          "order" : 0
        },
        "kerberos" : {
          "order" : 0
        }
      }
    },
~~~

**Comment by edewit** [comment]
@justin-stephenson couldn't you add the `enabled` property to `config`?

**Comment by justin-stephenson** [comment]
@edewit Thank you, that seemed to help address the original issue (though it was not required to add this parameter in keycloak 20 and earlier).

However, I now see the following error when I search for a user at the `Users` page. Should I file a separate ticket for this?

![image](https://github.com/keycloak/keycloak/assets/13416969/2d198b94-3e69-4a49-a1fe-b9a73ea121d8)

![image](https://github.com/keycloak/keycloak/assets/13416969/8b28c8c0-88cd-4198-a74e-89e58ba0b5bc)

**Comment by justin-stephenson** [comment]
And below is the associated traceback when the `b.map is not a function` error page is displayed.
~~~
2023-08-07 10:47:28,433 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /admin/realms/master/ui-ext/brute-force-user?briefRepresentation=true&first=0&max=11&q=&search=testuser1 failed, error id: 0c92e3c8-83ac-4e8c-aefe-631a1d67c0ef-1: java.lang.NoClassDefFoundError: org/keycloak/storage/user/UserLookupProvider$Streams
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)                                                                                                                        
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)                                                                                                                 
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:105)                                                                                                
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)                                                                                                 
        at java.base/java.lang.Class.forName0(Native Method)                                                                                                                                  
        at java.base/java.lang.Class.forName(Class.java:467)                                                                                                                                  
        at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)                                                                         
        at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)                                                                                           
        at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)                                                                                          
        at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)                                                                                                 
        at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)                                                                                           
        at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)                                                                                          
        at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117)                                                                         
        at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95)                                                                              
        at java.base/java.lang.Class.getGenericInterfaces(Class.java:1211)                                                                                                                    
        at org.keycloak.common.util.reflections.Types.findInterfaceParameterizedTypes(Types.java:541)                                                                                         
        at org.keycloak.common.util.reflections.Types.findParameterizedTypes(Types.java:479)                                                                                                  
        at org.keycloak.common.util.reflections.Types.getActualTypeArgumentsOfAnInterface(Types.java:460)                                                                                     
        at org.keycloak.common.util.reflections.Types.supports(Types.java:632)                                                                                                                
        at org.keycloak.storage.AbstractStorageManager.getStorageProviderInstance(AbstractStorageManager.java:225)
        at org.keycloak.storage.AbstractStorageManager.lambda$getEnabledStorageProviders$0(AbstractStorageManager.java:98)                                                                    
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)                                                                                                
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)                                                                                                                         
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)                                                                                                        
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)                                                                                                                
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)                                                                                                                
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)      
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)  
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)                                                                                                                    
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)                     
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)        
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)    
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)   
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)                     
        at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:71)                    
        at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:15)                    
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479) 
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:399)                                                                                                                    
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1568)                      
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1061)                              
        at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:332)                                                                                                                   
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:74)                                                                                                 
        at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251)                                                                                                         
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:73)                                                                                                          
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:224)                                                                                                 
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:207)                                                                                                     
        at org.keycloak.quarkus.runtime.integration.jaxrs.TransactionalResponseInterceptor.aroundWriteTo(TransactionalResponseInterceptor.java:42)                                                                                            
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:231)                                                                                                 
        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:161)                                                                                                  
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:68)                                                                                              
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:87)                                                                                                    
        at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:68)                                                                                                       
        at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:166)     
        at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:365)                                                                                                              
        at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:243)                  
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:100)              
        at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:73)               
        at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:518)                 
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:458)                        
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)               
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)           
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)                                                                                                        
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)                    
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)                        
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)                 
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)           
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)              
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)              
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)                                        
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)                   
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)                                  
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)   
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)   
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)                                        
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)                   
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)                                  
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)                                                                                                     
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)                      
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)                           
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)                     
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)                                        
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)                    
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                       
        at java.base/java.lang.Thread.run(Thread.java:833)                                                             
Caused by: java.lang.ClassNotFoundException: org.keycloak.storage.user.UserLookupProvider$Streams                      
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)                     
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)                  
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)                                             
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)                         
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)                          
        ... 87 more          
~~~

**Comment by justin-stephenson** [comment]
Original issue is the same as https://github.com/keycloak/keycloak/discussions/20340

**Comment by edewit** [comment]
@justin-stephenson a `ClassNotFoundException` ? can you try and create it in the UI instead with this command line ?

**Comment by justin-stephenson** [comment]
> @justin-stephenson a `ClassNotFoundException` it might be due to the fact that you have build your provider against [keycloak 19](https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/blob/main/pom.xml#L30) ?

Thank you, my mistake. please disregard this `b.map is not a function` error.

**Comment by edewit** [comment]
So all is good, can we close this issue?

**Comment by justin-stephenson** [comment]
@edewit Yes.
