### ISSUE TITLE
Group with multiple parents error is not propagated to UI

### ISSUE THREAD

**Issue by sutr90** [keycloak/keycloak#22092]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

While working with LDAP federation where the users are imported from Active Directory, if the LDAP server has groups with multiple parents, then Keycloak generates following error:

```
2023-07-29 15:53:34,198 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager] (executor-thread-37) Creating LdapContext using properties: [{java.naming.security.authentication=simple, java.naming.ldap.attributes.binary=objectGUID, java.naming.provider.url=ldap://common01-dc.int.getmanta.com:389, com.sun.jndi.ldap.connect.pool=false, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.security.credentials=**************************************, java.naming.security.principal=CN=licensemanager_admin,OU=Users,OU=Accounts,DC=int,DC=getmanta,DC=com}]
2023-07-29 15:53:34,250 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-37) Uncaught server error: org.keycloak.models.ModelException: Couldn't resolve groups from LDAP. Fix LDAP or skip preserve inheritance. Details: Group 'app_LicenseManager_DEV_Admins' detected to have multiple parents. This is not allowed in Keycloak. Parents are: [app_LicenseManager_DEV_TrialLicensesReaders, app_LicenseManager_DEV_CustomerLicensesReaders, app_LicenseManager_DEV_PartnerLicensesReaders]
        at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:187)
        at org.keycloak.services.resources.admin.UserStorageProviderResource.syncMapperData(UserStorageProviderResource.java:255)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.keycloak.storage.ldap.mappers.membership.group.GroupTreeResolver$GroupTreeResolveException: Group 'app_LicenseManager_DEV_Admins' detected to have multiple parents. This is not allowed in Keycloak. Parents are: [app_LicenseManager_DEV_TrialLicensesReaders, app_LicenseManager_DEV_CustomerLicensesReaders, app_LicenseManager_DEV_PartnerLicensesReaders]
        at org.keycloak.storage.ldap.mappers.membership.group.GroupTreeResolver.resolveGroupTree(GroupTreeResolver.java:62)
        at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:183)
        ... 44 more
```

But this shows up in the UI only as **unknown_error**:
![image](https://github.com/keycloak/keycloak/assets/1327101/9d24d32e-f0ce-4927-adbd-cec0aaa66101)

### Version

22.0.1

### Expected behavior

The error message, as it is pretty clear from the log, is shown in the UI pop-up.

### Actual behavior

Error message only displays **unknown_error**. 

### How to Reproduce?

Create LDAP federation in Keycloak, against server that has multiple parents groups.
Create new group mapper.
Try to sync the groups from LDAP to Keycloak.

**Comment by ahus1** [comment]
I agree that this should receive a better error handling. 

@jonkoops - could you describe what kind of response the front end would expect / would be happy to handle? A pointer to an example in the backend where this is already done would be helpful. 

Thanks!

**Comment by jonkoops** [comment]
@ahus1 I don't believe we have a generic API error implementation on the Java-side of things (I sure wish we did). So we use the [following code](https://github.com/keycloak/keycloak/blob/108fefe90b20bc862b9e19feb4ba84906765198c/js/apps/admin-ui/src/components/alert/Alerts.tsx#L82-L96) to handle all the edge cases the API returns.

**Comment by ahus1** [comment]
I had a look at the Java code and the `unknown_error` results from the following code which expects `WebApplicationException` to provide a more meaningful response:

https://github.com/keycloak/keycloak/blob/ccbddb22581e45d5060aa12bfe26dc386487f6d2/services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java#L120-L126

To create such an exception, there is `ErrorResponseException` and a builder class `ErrorResponse` which could be used here. To create such an `ErrorResponse`, IMHO the code in `UserStorageProviderResource` would need to catch `ModelException`s, take the message put it into `ErrorResponse`. 

Updating the global exception handling to convert all `ModelException`s might be a bit too much, as for non-admin endpoints the exceptions might reveal too much information. For authenticated admins, those `ModelExceptions` would be ok to be shown. 

I marked it as "help wanted" as it is a good issue for the community to pick up. Usually we ask for a test case, still if someone would provide a PR which contains only the code change and a visual proof that some tested it manually.
