### ISSUE TITLE
After upgrade from 20.0.3 to 22.0.1 Keycloak java client fail on DefaultCryptoProvider

### ISSUE THREAD

**Issue by ranm1986** [keycloak/keycloak#22173]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dependencies

### Describe the bug

Hi
We have a hybrid env that can work with and without keycloak.
Everything worked fine on version 20.0.3.
Now we trying to update to version 22.0.1 but we fail on DefaultCryptoProvider exception even though we don't use FIPS mode

```
java.util.ServiceConfigurationError: org.keycloak.common.crypto.CryptoProvider: Provider org.keycloak.crypto.def.DefaultCryptoProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_382]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[?:1.8.0_382]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[?:1.8.0_382]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_382]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_382]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_382]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_382]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_382]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_382]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_382]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_382]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_382]
	at org.keycloak.common.crypto.CryptoIntegration.detectProvider(CryptoIntegration.java:56) ~[keycloak-common.jar:22.0.1]
	at org.keycloak.common.crypto.CryptoIntegration.init(CryptoIntegration.java:32) ~[keycloak-common.jar:22.0.1]
	at org.keycloak.adapters.KeycloakDeploymentBuilder.build(KeycloakDeploymentBuilder.java:212) ~[keycloak-adapter-core.jar:22.0.1]
	at org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolver.resolve(KeycloakSpringBootConfigResolver.java:41) ~[keycloak-spring-boot-adapter-core.jar:22.0.1]
	at org.keycloak.adapters.springsecurity.config.KeycloakSpringConfigResolverWrapper.resolve(KeycloakSpringConfigResolverWrapper.java:40) ~[keycloak-spring-security-adapter.jar:22.0.1]
	at org.keycloak.adapters.AdapterDeploymentContext.resolveDeployment(AdapterDeploymentContext.java:89) ~[keycloak-adapter-core.jar:22.0.1]
	at org.keycloak.adapters.PreAuthActionsHandler.preflightCors(PreAuthActionsHandler.java:100) ~[keycloak-adapter-core.jar:22.0.1]
	at org.keycloak.adapters.PreAuthActionsHandler.handleRequest(PreAuthActionsHandler.java:75) ~[keycloak-adapter-core.jar:22.0.1]
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:177) ~[spring-boot-container-bundle.jar:22.0.1]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core.jar:9.0.74]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core.jar:9.0.74]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
Caused by: java.lang.NoSuchFieldError: id_alg_AEADChaCha20Poly1305
	at org.bouncycastle.jcajce.provider.symmetric.ChaCha$Mappings.configure(Unknown Source) ~[bcprov-jdk15on.jar:1.70.0]
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(Unknown Source) ~[bcprov-jdk15on.jar:1.70.0]
	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source) ~[bcprov-jdk15on.jar:1.70.0]
	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source) ~[bcprov-jdk15on.jar:1.70.0]
	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source) ~[bcprov-jdk15on.jar:1.70.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_382]
	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source) ~[bcprov-jdk15on.jar:1.70.0]
	at org.keycloak.crypto.def.DefaultCryptoProvider.<init>(DefaultCryptoProvider.java:57) ~[keycloak-crypto-default.jar:22.0.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_382]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_382]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_382]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_382]
	... 31 more
```

this is our keycloak dependencies:

```
<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-spring-security-adapter</artifactId>
				<version>${keycloak.version}</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-core</artifactId>
				<version>${keycloak.version}</version>
				<exclusions>
					<exclusion>
						<groupId>org.bouncycastle</groupId>
						<artifactId>bcpkix-jdk15on</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-adapter-core</artifactId>
				<version>${keycloak.version}</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-admin-client</artifactId>
				<version>${keycloak.version}</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-common</artifactId>
				<version>${keycloak.version}</version>
				<exclusions>
					<exclusion>
						<groupId>org.bouncycastle</groupId>
						<artifactId>bcpkix-jdk15on</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-server-spi</artifactId>
				<version>${keycloak.version}</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-server-spi-private</artifactId>
				<version>${keycloak.version}</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-services</artifactId>
				<version>${keycloak.version}</version>
				<exclusions>
					<exclusion>
						<groupId>log4j</groupId>
						<artifactId>log4j</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.slf4j</groupId>
						<artifactId>slf4j-log4j12</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.bouncycastle</groupId>
						<artifactId>bcpkix-jdk15on</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-ldap-federation</artifactId>
				<version>${keycloak.version}</version>
			</dependency>

```

This is happen even without running against the keycloak server.
Do we have an option to skip the CryptoIntegration.init? Or there is another issue? 

Thanks.

### Version

22.0.3

### Expected behavior

Client should run without exceptionsThe client

### Actual behavior

DefaultCryptoProvider when starting the application 

### How to Reproduce?

1. create a spring application 
2. add relevant dependencies
3. try to execute API request

### Anything else?

Thanks a lot,

**Comment by mabartos** [comment]
I guess it's more related to the Core team. Moving there.

**Comment by mposolda** [comment]
I am adding to Backlog for now. It is the question if this is Keycloak bug at all - seems rather like the dependencies in your project should be somehow tweaked to make sure that BouncyCastle works as expected.

**Comment by ranm1986** [comment]
@mposolda Is there any way to configure the spring boot keycloak client to use custom CryptoProvider?
today the KeycloakDeploymentBuilder#KeycloakDeployment build(AdapterConfig adapterConfig)
init the CryptoIntegration with DefaultCryptoProvider
Maybe there is a way to override it?

**Comment by Dhiraj-Jain** [comment]
We are facing the same issue. We are putting latest bc jars in providers and they were working in 21.1.1 but since upgrading to v22, this error is observed when we deploy keycloak. Please let us know what we can do here.

![Screenshot 2023-10-17 102511](https://github.com/keycloak/keycloak/assets/64320631/870f1f89-19f1-46f6-9978-b07003e4c652)

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
