### ISSUE TITLE
Keycloak SAML Adapter subsystem does not support Wildfly 29 

### ISSUE THREAD

**Issue by APUSStefanie** [keycloak/keycloak#22172]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/jee-saml

### Describe the bug

I installed with the new Wildfly 29 Galleon Release the keycloak saml adapter. 
The sso login works fine if I use the configuration within the WAR (keycloak-saml.xml in WEB-INF).
We have different customers and test/prod stages, so we want to use the subsystem xmlns="urn:jboss:domain:keycloak-saml:1.4" for configuring IDP and SP. 

When I gave the configuration back to the subsystem (we already had this on our old wildfly 23) I got an exception during deployment. 

Caused by: java.lang.NoSuchMethodError: 'org.jboss.as.controller.AttributeMarshaller org.jboss.as.controller.SimpleAttributeDefinition.getAttributeMarshaller()'
	at org.keycloak.keycloak-saml-wildfly-jakarta-subsystem@22.0.1//org.keycloak.subsystem.adapter.saml.extension.KeycloakSubsystemParser.writeSps(KeycloakSubsystemParser.java:501)
	at org.keycloak.keycloak-saml-wildfly-jakarta-subsystem@22.0.1//org.keycloak.subsystem.adapter.saml.extension.KeycloakAdapterConfigDeploymentProcessor.getXML(KeycloakAdapterConfigDeploymentProcessor.java:99)
	at org.keycloak.keycloak-saml-wildfly-jakarta-subsystem@22.0.1//org.keycloak.subsystem.adapter.saml.extension.KeycloakAdapterConfigDeploymentProcessor.addKeycloakSamlAuthData(KeycloakAdapterConfigDeploymentProcessor.java:71)
	at org.keycloak.keycloak-saml-wildfly-jakarta-subsystem@22.0.1//org.keycloak.subsystem.adapter.saml.extension.KeycloakAdapterConfigDeploymentProcessor.deploy(KeycloakAdapterConfigDeploymentProcessor.java:57)
	at org.jboss.as.server@21.1.0.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)
	... 8 more

It seems in the code is a method called, which is not anymore existing in the current Wildfly 29 version. 

According to the wildfly and keycloak adapter docoumentation, those two versions should be compatible. 

### Version

SAML Adapter 22.0.1

### Expected behavior

Configuration for SAML can be done again in subsystem xmlns="urn:jboss:domain:keycloak-saml:1.4"

### Actual behavior

Exception during deployment

### How to Reproduce?

* Set up Wildfly 29 with SAML 
* Use  subsystem xmlns="urn:jboss:domain:keycloak-saml:1.4" for SAML configuration
* Deploy a war 

### Anything else?

https://www.wildfly.org/news/2023/07/21/WildFly29-Released/
https://docs.wildfly.org/29/WildFly_Elytron_Security.html#Keycloak_SAML_Integration

**Comment by mposolda** [comment]
@pedroigor @pskopek Adding you for triage of this

**Comment by pedroigor** [comment]
We are compiling using 27. I don't remember what is our policy around the WF version we support when using the SAML adapter but docs suggest we are supporting the latest, as mentioned by @APUSStefanie.

If so, shall we bump the version to WF latest (e.g.: 29)?

Or perhaps we can change our policy to match WF with the latest EAP version?

**Comment by pedroigor** [comment]
Should be fixed by https://github.com/keycloak/keycloak/issues/22593.
