### ISSUE TITLE
Flaky test: org.keycloak.testsuite.forms.LoginTest#loginDifferentUserAfterDisabledUserThrownOut

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#22230]
## org.keycloak.testsuite.forms.LoginTest#loginDifferentUserAfterDisabledUserThrownOut
[Keycloak CI - Forms IT (firefox)](https://github.com/keycloak/keycloak/actions/runs/5658326788/job/15329918867) / [Pull Request #21963](https://github.com/keycloak/keycloak/pull/21963)

```
java.lang.AssertionError: Expected LoginPage but was Keycloak Account Management (https://localhost:8543/auth/realms/test/account/#/)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:47)
	at org.keycloak.testsuite.pages.LoginPage.open(LoginPage.java:236)
...
```

**Comment by ahus1** [comment]
## Unreported flaky test detected
If the below flaky tests below are affected by the changes, please review and update the changes accordingly. Otherwise, a maintainer should report the flaky tests prior to merging the PR.

### org.keycloak.testsuite.forms.LoginTest#loginDifferentUserAfterDisabledUserThrownOut

[Keycloak CI - Forms IT (firefox)](https://github.com/keycloak/keycloak/actions/runs/5736191799/job/15545755315)


```
java.lang.AssertionError: Expected LoginPage but was Keycloak Account Management (https://localhost:8543/auth/realms/test/account/#/)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:47)
	at org.keycloak.testsuite.pages.LoginPage.open(LoginPage.java:236)
...
```

**Comment by ahus1** [comment]
## Unreported flaky test detected

### org.keycloak.testsuite.forms.LoginTest#loginDifferentUserAfterDisabledUserThrownOut

[Keycloak CI - Forms IT (firefox)](https://github.com/keycloak/keycloak/actions/runs/5736191799/job/15545755315) / PR #22029


```
java.lang.AssertionError: Expected LoginPage but was Keycloak Account Management (https://localhost:8543/auth/realms/test/account/#/)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:47)
	at org.keycloak.testsuite.pages.LoginPage.open(LoginPage.java:236)
...
```

**Comment by lhanusov** [comment]
outdated
