### ISSUE TITLE
Unable to start the keycloak server both dev & production

### ISSUE THREAD

**Issue by nmanthena18** [keycloak/keycloak#22270]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I am unable to to start the keycloak server here is error logs.

`ERROR: java.nio.file.FileSystemException: F:\workspace\keycloak\keycloak-22\lib\quarkus\generated-bytecode.jar: The process cannot access the file because it is being used by another process
`

**Full logs:**

`$ ./bin/kc.sh build --db mysql
Updating the configuration and installing your custom providers, if any. Please wait.
2023-08-05 16:00:52,102 WARN  [io.quarkus.arc.processor.BeanArchives] (build-4) Failed to index org.keycloak.models.map.storage.jpa.JpaMapStorageProviderFactory: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@436390f4
2023-08-05 16:00:52,107 INFO  [io.quarkus.arc.processor.IndexClassLookupUtils] (build-4) Class for name: org.keycloak.models.map.storage.jpa.JpaMapStorageProviderFactory was not found in Jandex index. Please ensure the class is part of the index.
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: F:\workspace\keycloak\keycloak-22\lib\quarkus\generated-bytecode.jar: The process cannot access the file because it is being used by another process
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1623)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.FileSystemException: F:\workspace\keycloak\keycloak-22\lib\quarkus\generated-bytecode.jar: The process cannot access the file because it is being used by another process
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
        at java.base/java.nio.file.Files.delete(Files.java:1151)
        at io.quarkus.bootstrap.util.IoUtils.createOrEmptyDir(IoUtils.java:114)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:600)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:223)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        ... 6 more

ERROR: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: F:\workspace\keycloak\keycloak-22\lib\quarkus\generated-bytecode.jar: The process cannot access the file because it is being used by another process
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1623)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.nio.file.FileSystemException: F:\workspace\keycloak\keycloak-22\lib\quarkus\generated-bytecode.jar: The process cannot access the file because it is being used by another process
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
        at java.base/java.nio.file.Files.delete(Files.java:1151)
        at io.quarkus.bootstrap.util.IoUtils.createOrEmptyDir(IoUtils.java:114)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:600)
        at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:223)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        ... 6 more
`

### Version

22.0.0

### Expected behavior

it should work for production / dev

### Actual behavior

`ERROR: F:\workspace\keycloak\keycloak-22\lib\quarkus\generated-bytecode.jar: The process cannot access the file because it is being used by another process
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
`

### How to Reproduce?

Download the 21.0.0/22.0.0 

execute commands:
./bin/kc.sh build --db postgres or ./kc.sh start-dev

after rerun couple of time you will get this error .

**Comment by rmartinc** [comment]
Possible duplicated of #21625. Have you tried with 22.0.1?

**Comment by mposolda** [comment]
duplicates #21625 
So I am closing this. Please check with latest Keycloak 22.0.1.
@rmartinc Thanks for doublecheck
