### ISSUE TITLE
Keycloak v22.0.1 java.lang.ClassNotFoundException: javax.ws.rs.core.UriBuilder

### ISSUE THREAD

**Issue by Slixe** [keycloak/keycloak#22322]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I'm using a custom IDP cas plugin to connect to my CAS Server V3 but when any request is done, I'm getting such error:

```
2023-08-08 15:24:08,554 ERROR [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /auth/realms/master/protocol/cas/logout?service=http%3A%2F%2Flocalhost%3A8000%2F failed, error id: 34eb8ba4-847b-45a9-bdf2-eafeb23cbcb4-4: java.lang.NoClassDefFoundError: javax/ws/rs/core/UriBuilder
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
        at org.jboss.resteasy.util.GetRestful.hasJAXRSAnnotations(GetRestful.java:98)
        at org.jboss.resteasy.util.GetRestful.isSubResourceClass(GetRestful.java:35)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:155)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.UriBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        ... 34 more
```

It looks like one of the librairie used/provided by Keycloak is still using the javax package instead of jakarta.       

### Version

22.0.1

### Expected behavior

To not have such errors

that all librairies used are using jakarta package and not the javax.

### Actual behavior

javax package is used instead of the jakarta package in librairies.

### How to Reproduce?

Install following plugin:
https://github.com/RoboJackets/keycloak-cas

Then create a new IDP with CAS, and just go on http://localhost:8080/auth/realms/master/protocol/cas and you will have a Server error printed.

**Comment by Slixe** [comment]
> @Slixe Have you made sure you are using the latest version of the plugin? The one at mavencentral is definitely outdated (https://central.sonatype.com/artifact/io.github.johnjcool/keycloak-cas-services/4.8.3.Final). I could not find an up-to-date version of it although the change to jakarta was done in the source code 3 weeks ago ([RoboJackets/keycloak-cas@5bd7848](https://github.com/RoboJackets/keycloak-cas/commit/5bd78488e915c95120edc8ce931b317337c60af4)).
> 
> I suspect this is the cause of the issue, it's not something in Keycloak as I could not find a reference to `javax.ws.rs.core.UriBuilder`there.

Hey thanks for your answer but no, I’m not using a custom one not from maven but from github as I linked directly in the issue. And it has been moved from javax to jakarta.

So the problem don’t come from the plugin in my opinion.

**Comment by pedroigor** [comment]
I tried to install the plugin (building from source) and I was able to create a broker in the master realm. Not sure why, but the theme (as mentioned in the plugin docs) is not available in the administration console.

Trying to reach out `http://localhost:8080/auth/realms/master/protocol/cas` gives a `404`. Removing the `/auth` has no effect.

I agree with @sschu that it is not expected any reference on the server-side to `javax` but `jarkarta`.

**Comment by Slixe** [comment]
Theme was the old way to display the configuration in old admin system (so v16 for example) now it’s directly through the Java code (config) which is exposed. So no need to deploy to select the theme anymore.

For the 404 part I’m curious, did you created the custom provider ? Is the plugin well loaded ? Gonna try again and add more screenshots tomorrow to be sure. 

Thanks for your help.

**Comment by kberzinch** [comment]
👋🏻 CAS identity provider maintainer here, I can confirm the identity provider works on Keycloak 22.0.1. We are using it in production right now, mounted into `quay.io/keycloak/keycloak:22.0.1` with no changes to the image itself. 

We forked that from a very old version that was built against Keycloak 8.x, and have been keeping the Java code up to date, but not the docs. Seeing as this is the second time it's been mentioned in the Keycloak issue tracker, it may be time to do some more housekeeping 😄 

I'm not sure how routes are registered in Keycloak, but at any rate, the login path is `/realms/{realm}/broker/cas/login` and the callback URL that consumes the service ticket from CAS (equivalent to a code from an OAuth IdP) is `/realms/{realm}/broker/cas/endpoint`.

**Comment by Slixe** [comment]
I'm building it using `mvn package` and I put the jar file into providers folder than I run `kc.sh build` and I start it, and when I'm going on the URL: http://localhost:8080/auth/realms/master/protocol/cas/login I get the javax error.
