### ISSUE TITLE
"Unexpected end of stream" with MariaDB in Docker Container.

### ISSUE THREAD

**Issue by Splitframe** [keycloak/keycloak#22339]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

Keycloak running in a Docker Container according to this https://www.keycloak.org/server/containers manual.
With this Dockerfile and compose file:
```dockerfile
FROM quay.io/keycloak/keycloak:22.0 as builder

# Configure a database vendor
ENV KC_DB=mariadb

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:22.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
```docker-compose
networks:
  devLocal:
    external: true

services:
  keycloak:
    container_name: keycloak
    command: "start-dev --import-realm"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - devLocal
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./devRealm:/opt/keycloak/data/import
      - ./themes:/opt/keycloak/themes
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mariadb/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: ****
      KC_HOSTNAME: localhost
```
MariaDB running in a Docker Container with compose file:
```docker-compose
networks:
  devLocal:
    external: false
    name: devLocal

services:
  mariadb:
#    image: mariadb:10.3.3
    image: mariadb:latest
    container_name: mariadb
    command: --init-file /data/application/init.sql
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/data/application
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - devLocal
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ****
      MYSQL_DATABASE: ****
```

### Version

22.0 and nightly

### Expected behavior

Connect to database and create/migrate structure and data.

### Actual behavior

Crash with error message:

```
2023-08-09 09:30:09,781 ERROR [org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService] (main) Database error during release lock: liquibase.exception.DatabaseException: java.sql.SQLNonTransientConnectionException: (conn=5) Socket error
2023-08-09T09:30:09.783393212Z 	at liquibase.database.jvm.JdbcConnection.commit(JdbcConnection.java:275)
2023-08-09T09:30:09.783401377Z 	at liquibase.database.AbstractJdbcDatabase.commit(AbstractJdbcDatabase.java:1167)
2023-08-09T09:30:09.783415924Z 	at org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService.releaseLock(CustomLockService.java:271)
2023-08-09T09:30:09.783423669Z 	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$releaseLock$3(LiquibaseDBLockProvider.java:133)
2023-08-09T09:30:09.783425893Z 	at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:999)
2023-08-09T09:30:09.783427807Z 	at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.releaseLock(LiquibaseDBLockProvider.java:128)
2023-08-09T09:30:09.783429700Z 	at org.keycloak.models.dblock.DBLockGlobalLockProvider.releaseLock(DBLockGlobalLockProvider.java:88)
2023-08-09T09:30:09.783431814Z 	at org.keycloak.models.dblock.DBLockGlobalLockProvider.withLock(DBLockGlobalLockProvider.java:79)
2023-08-09T09:30:09.783433748Z 	at org.keycloak.models.locking.GlobalLockProvider.withLock(GlobalLockProvider.java:45)
2023-08-09T09:30:09.783435772Z 	at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.update(LegacyJpaConnectionProviderFactory.java:292)
2023-08-09T09:30:09.783437705Z 	at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.createOrUpdateSchema(LegacyJpaConnectionProviderFactory.java:261)
2023-08-09T09:30:09.783439639Z 	at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.postInit(LegacyJpaConnectionProviderFactory.java:129)
2023-08-09T09:30:09.783454457Z 	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:105)
2023-08-09T09:30:09.783456591Z 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.createSessionFactory(QuarkusKeycloakApplication.java:45)
2023-08-09T09:30:09.783459456Z 	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:125)
2023-08-09T09:30:09.783463273Z 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
2023-08-09T09:30:09.783468423Z 	at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_c9888fa6c2aa9208d4625ee9d83de6fd77e22c83.notify(Unknown Source)
2023-08-09T09:30:09.783470557Z 	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
2023-08-09T09:30:09.783472400Z 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
2023-08-09T09:30:09.783474234Z 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
2023-08-09T09:30:09.783476087Z 	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
2023-08-09T09:30:09.783477961Z 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
2023-08-09T09:30:09.783479794Z 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
2023-08-09T09:30:09.783481668Z 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
2023-08-09T09:30:09.783483531Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-08-09T09:30:09.783485365Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2023-08-09T09:30:09.783487188Z 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
2023-08-09T09:30:09.783489432Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
2023-08-09T09:30:09.783491236Z 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:98)
2023-08-09T09:30:09.783493069Z 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
2023-08-09T09:30:09.783494933Z 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
2023-08-09T09:30:09.783496756Z 	at picocli.CommandLine.access$1500(CommandLine.java:148)
2023-08-09T09:30:09.783498569Z 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
2023-08-09T09:30:09.783500473Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
2023-08-09T09:30:09.783502286Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
2023-08-09T09:30:09.783504100Z 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
2023-08-09T09:30:09.783508197Z 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
2023-08-09T09:30:09.783510171Z 	at picocli.CommandLine.execute(CommandLine.java:2170)
2023-08-09T09:30:09.783512205Z 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:100)
2023-08-09T09:30:09.783514279Z 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
2023-08-09T09:30:09.783585242Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-08-09T09:30:09.783693305Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-08-09T09:30:09.783720085Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-08-09T09:30:09.783756223Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-08-09T09:30:09.783800226Z 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
2023-08-09T09:30:09.783831033Z 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
2023-08-09T09:30:09.783873672Z Caused by: java.sql.SQLNonTransientConnectionException: (conn=5) Socket error
2023-08-09T09:30:09.783988758Z 	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:293)
2023-08-09T09:30:09.784034543Z 	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:359)
2023-08-09T09:30:09.784091460Z 	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:895)
2023-08-09T09:30:09.784128460Z 	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:811)
2023-08-09T09:30:09.784195526Z 	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:730)
2023-08-09T09:30:09.784223308Z 	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:654)
2023-08-09T09:30:09.784257642Z 	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:511)
2023-08-09T09:30:09.784297196Z 	at org.mariadb.jdbc.Connection.commit(Connection.java:209)
2023-08-09T09:30:09.784325339Z 	at io.agroal.pool.wrapper.ConnectionWrapper.commit(ConnectionWrapper.java:203)
2023-08-09T09:30:09.784347611Z 	at liquibase.database.jvm.JdbcConnection.commit(JdbcConnection.java:272)
2023-08-09T09:30:09.784436067Z 	... 45 more
2023-08-09T09:30:09.784465632Z Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
2023-08-09T09:30:09.784555821Z 	at org.mariadb.jdbc.client.socket.impl.PacketReader.readReusablePacket(PacketReader.java:68)
2023-08-09T09:30:09.784644718Z 	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:115)
2023-08-09T09:30:09.784679722Z 	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:872)
2023-08-09T09:30:09.784755976Z 	... 52 more
```

### How to Reproduce?

Run both keycloak and mariaDB on seperate docker container in a shared docker network (on windows).

### Anything else?

When running mariaDB natively on the host machine it works with no issues (keycloak 22.0, mariaDB 11.2)
When running mariaDB in version 10.3.3 there is also no problem.

It might have to do something with https://github.com/keycloak/keycloak/issues/9392
This issue is already quite old though. The issue mentions a problem with external custom provider.
I don't know exactly what was meant by this, I just used keycloak according to the manual posted on the keycloak
website and only default configurations for both keycloak and mariaDB.

**Comment by sguilhen** [comment]
I would perhaps need to run the tests in a Windows machine, but on Linux the setup works without any issues using `latest` MariaDB image and both Keycloak 22.0 and 23.0 images. My compose for MariaDB is slightly different in that I had to remove a couple of lines shown in the issue description for the container to start without errors:

```
networks:
  devLocal:
    external: false
    name: devLocal

services:
  mariadb:
#    image: mariadb:10.3.3
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - devLocal
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'keycloak'
      MYSQL_USER: 'keycloak'
      MYSQL_PASSWORD: '****'
      MYSQL_ROOT_PASSWORD: '****'
```

**Comment by sguilhen** [comment]
I wasn't able to reproduce the issue, even on Windows, so I'm closing this. If the issue still persists in latest Keycloak version, please-reopen.
