### ISSUE TITLE
PERMISSION_TOKEN_ERROR: org.keycloak.services.CorsErrorResponseException: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by lc-spxl** [keycloak/keycloak#22377]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

Using a client with resource,scopes and permission set and working on evaluation. Using with token from code I get this error in Keycloack logs

```
2023-08-10 19:07:48,472 DEBUG [org.keycloak.authorization.authorization.AuthorizationTokenService] (executor-thread-155) PERMISSION_TOKEN_ERROR: org.keycloak.services.CorsErrorResponseException: HTTP 500 Internal Server Error
	at org.keycloak.authorization.authorization.AuthorizationTokenService.authorize(AuthorizationTokenService.java:257)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.permissionGrant(TokenEndpoint.java:987)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequestInternal(TokenEndpoint.java:228)
```

I cannot find any relevant discussion on this, so for my understanding this could be a bug

### Version

21.0.2

### Expected behavior

Scope should pass as happeing in evaluate page in admin ui

### Actual behavior

Got 403

### How to Reproduce?

I am using keycloack node for express and the kubernetes operator

### Anything else?

Thank you

**Comment by pedroigor** [comment]
@lc-spxl You should not get a `500` status code but I can't reproduce this without more details and a reproducer. We have enough coverage for this scenario so it must be something specific to how you have configured your client or how you are sending the authorization request to the token endpoint.

If you can provide more details and a reproducer, feel free to re-open the issue.
