### ISSUE TITLE
Issue with the jakarta admin client

### ISSUE THREAD

**Issue by Writtscher** [keycloak/keycloak#22391]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

Hi. We are updating an older service to java 17 and are going to use the keycloak-admin-client-jakarta. Since we are still on keycloak 19 we'd like to use the `org.keycloak:keycloak-admin-client-jakarta:19.0.3`.

But there is an issue with that library.
```
Could not find jackson-jaxrs-base-2.15.2-jakarta.jar (com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.15.2).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.15.2/jackson-jaxrs-base-2.15.2-jakarta.jar
```

If you browse the artifactory 
`https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.15.2/`
you cannot find the `jackson-jaxrs-base-2.15.2-jakarta.jar` file but you find `jackson-jaxrs-base-2.15.2.jar`.

There is also a quarkus keycloak admin client but I cannot find which version works with our keycloak version.

I am so confused. I hope someone can help me to resolve that issue because I am stuck and cannot find a solution for it.

### Version

> 19.0.3

### Expected behavior

It should just work.

### Actual behavior

Does not work.

### How to Reproduce?

Simple gradle setup with the mentioned dependency.

**Comment by rmartinc** [comment]
Hi @Writtscher!

I have done a tree dependency of the keycloak-admin-client-jakarta dependency and I don't see the dependency you are mentioning:

```
[INFO] \- org.keycloak:keycloak-admin-client-jakarta:jar:19.0.3:compile
[INFO]    +- org.keycloak:keycloak-core:jar:19.0.3:compile
[INFO]    +- org.keycloak:keycloak-common:jar:19.0.3:compile
[INFO]    +- org.jboss.resteasy:resteasy-client:jar:6.0.0.Final:compile
[INFO]    |  +- org.jboss.resteasy:resteasy-client-api:jar:6.0.0.Final:compile
[INFO]    |  +- org.jboss.resteasy:resteasy-core-spi:jar:6.0.0.Final:compile
[INFO]    |  |  +- jakarta.annotation:jakarta.annotation-api:jar:2.0.0:compile
[INFO]    |  |  \- jakarta.validation:jakarta.validation-api:jar:3.0.0:compile
[INFO]    |  +- org.jboss.resteasy:resteasy-core:jar:6.0.0.Final:compile
[INFO]    |  |  +- jakarta.activation:jakarta.activation-api:jar:2.0.0:compile
[INFO]    |  |  \- com.ibm.async:asyncutil:jar:0.1.0:compile
[INFO]    |  +- org.jboss.logging:jboss-logging:jar:3.4.2.Final:compile
[INFO]    |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO]    |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO]    |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO]    |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO]    |  +- commons-io:commons-io:jar:2.9.0:compile
[INFO]    |  +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_3.0_spec:jar:1.0.0.Final:compile
[INFO]    |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO]    +- org.jboss.resteasy:resteasy-multipart-provider:jar:6.0.0.Final:compile
[INFO]    |  +- com.sun.mail:jakarta.mail:jar:2.0.1:compile
[INFO]    |  +- org.apache.james:apache-mime4j-dom:jar:0.8.3:compile
[INFO]    |  |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile
[INFO]    |  \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile
[INFO]    +- org.jboss.resteasy:resteasy-jackson2-provider:jar:6.0.0.Final:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:jakarta:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:jakarta:2.12.3:compile
[INFO]    |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:jakarta:2.12.3:compile
[INFO]    |  \- com.github.java-json-tools:json-patch:jar:1.13:compile
[INFO]    |     +- com.github.java-json-tools:msg-simple:jar:1.2:compile
[INFO]    |     |  \- com.github.java-json-tools:btf:jar:1.3:compile
[INFO]    |     \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile
[INFO]    \- org.jboss.resteasy:resteasy-jaxb-provider:jar:6.0.0.Final:compile
[INFO]       +- jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1:compile
[INFO]       +- com.sun.xml.bind:jaxb-impl:jar:3.0.1:compile
[INFO]       \- com.sun.xml.bind:jaxb-core:jar:3.0.1:compile
[INFO]          \- com.sun.activation:jakarta.activation:jar:2.0.1:compile
```

I see `com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:jakarta:2.12.3` but no -jakarta here. Try starting with a simple project with just the `keycloak-admin-client-jakarta` inside and check if it works.

**Comment by Writtscher** [comment]
I can provide a simple repository to test. The project setup is very minimalistic but it does not work

https://github.com/Writtscher/keycloak-jakarta-issue-sample/tree/main

When I import / reload the gradle project to update the dependencies I get the error:

```
* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: Could not find jackson-jaxrs-base-2.15.2-jakarta.jar (com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.15.2).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.15.2/jackson-jaxrs-base-2.15.2-jakarta.jar
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:439)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:139)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:43)
	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:64)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.runAction(AbstractClientProvidedBuildActionRunner.java:131)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:104)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:84)
	at org.gradle.internal.buildtree.DefaultBuildTreeModelCreator.fromBuildModel(DefaultBuildTreeModelCreator.java:57)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$fromBuildModel$2(DefaultBuildTreeLifecycleController.java:89)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$5(DefaultBuildTreeLifecycleController.java:113)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$5(StateTransitionController.java:166)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:247)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:166)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	at org.gradle.internal.model.StateTransitionController.transition(StateTransitionController.java:166)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.runBuild(DefaultBuildTreeLifecycleController.java:110)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.fromBuildModel(DefaultBuildTreeLifecycleController.java:81)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner.runClientAction(AbstractClientProvidedBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner.run(ClientProvidedPhasedActionRunner.java:53)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:49)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:136)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:122)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:40)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find jackson-jaxrs-base-2.15.2-jakarta.jar (com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.15.2).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.15.2/jackson-jaxrs-base-2.15.2-jakarta.jar
```

**Comment by rmartinc** [comment]
@Writtscher Yes, I have reproduced it now using a spring-boot application. It seems the problem is tat the version 19.0.3 uses an old resteasy client which in turn uses an old jackson that doesn't work with jakarta varians (it needs to be [2.13 to work with jakarta variants](https://stackoverflow.com/questions/70856341/gradle-build-looking-for-a-non-existent-jackson-provider-dependencies)). Right now in keycloak we are using last resteasy client so it's working in recent releases and we are not affected by this anymore.

I could make a spring boot application work with 19.0.3 forcing the usage of a new resteasy client this way:

```
        implementation("org.keycloak:keycloak-admin-client-jakarta:19.0.3") {
            exclude(group = "org.jboss.resteasy", module = "*")
        }
        implementation("org.jboss.resteasy:resteasy-client:6.2.4.Final")
        implementation("org.jboss.resteasy:resteasy-multipart-provider:6.2.4.Final")
        implementation("org.jboss.resteasy:resteasy-jackson2-provider:6.2.4.Final")
        implementation("org.jboss.resteasy:resteasy-jaxb-provider:6.2.4.Final")
```

But I don't know if this is going to introduce new issues. I did just a simple test that connect to a 19.0.3 keycloak server.

**Comment by Writtscher** [comment]
Thank you. This worked for us. So it is good to know that older versions of resteasy do not work with the latest spring version. It seems this works for us and there are no other problems.

This is a temporary fix as we plan to update our keycloak anyways.

**Comment by rmartinc** [comment]
Thanks @Writtscher! Good to hear that exclusions worked for you.

I'm going to close tihs issue as we are not affected by this in version 22.0.x.
