### ISSUE TITLE
java.lang.NoSuchMethodError: 'javax.persistence.EntityManager org.keycloak.connections.jpa.JpaConnectionProvider.getEntityManager()'

### ISSUE THREAD

**Issue by sy6sy2** [keycloak/keycloak#22529]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/jee

### Describe the bug

Using a module with line `this.entityManager = session.getProvider(JpaConnectionProvider.class).getEntityManager();` conclude to a runtime error.

### Version

22.0.1

### Expected behavior

No runtime error.
It worked fine with v19.

### Actual behavior

If using a Keycloak module using `this.entityManager = session.getProvider(JpaConnectionProvider.class).getEntityManager();` line in the code then we obtain a runtime error during the load of the auth webpage.

### How to Reproduce?

Try to use a Keycloak module the `this.entityManager = session.getProvider(JpaConnectionProvider.class).getEntityManager();` line in the code.

### Anything else?

Log:

```
development-authentification-1  | 2023-08-17 15:53:32,655 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NoSuchMethodError: 'javax.persistence.EntityManager org.keycloak.connections.jpa.JpaConnectionProvider.getEntityManager()'
development-authentification-1  | 	at com.gwidgets.providers.RegisterEventListenerProvider.<init>(RegisterEventListenerProvider.java:28)
development-authentification-1  | 	at com.gwidgets.providers.RegisterEventListenerProviderFactory.create(RegisterEventListenerProviderFactory.java:12)
development-authentification-1  | 	at com.gwidgets.providers.RegisterEventListenerProviderFactory.create(RegisterEventListenerProviderFactory.java:9)
development-authentification-1  | 	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:195)
development-authentification-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
development-authentification-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
development-authentification-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
development-authentification-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
development-authentification-1  | 	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:146)
development-authentification-1  | 	at jdk.proxy2/jdk.proxy2.$Proxy51.getProvider(Unknown Source)
development-authentification-1  | 	at org.keycloak.events.EventBuilder.lambda$getEventListeners$0(EventBuilder.java:84)
development-authentification-1  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
development-authentification-1  | 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
development-authentification-1  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
development-authentification-1  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
development-authentification-1  | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
development-authentification-1  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
development-authentification-1  | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
development-authentification-1  | 	at org.keycloak.events.EventBuilder.getEventListeners(EventBuilder.java:93)
development-authentification-1  | 	at org.keycloak.events.EventBuilder.<init>(EventBuilder.java:68)
development-authentification-1  | 	at org.keycloak.events.EventBuilder.<init>(EventBuilder.java:56)
development-authentification-1  | 	at org.keycloak.services.resources.RealmsResource.getProtocol(RealmsResource.java:113)
development-authentification-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
development-authentification-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
development-authentification-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
development-authentification-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
development-authentification-1  | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.constructLocator(ResourceLocatorInvoker.java:105)
development-authentification-1  | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTargetFromLocator(ResourceLocatorInvoker.java:86)
development-authentification-1  | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTarget(ResourceLocatorInvoker.java:75)
development-authentification-1  | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:126)
development-authentification-1  | 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
development-authentification-1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
development-authentification-1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
development-authentification-1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
development-authentification-1  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
development-authentification-1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
development-authentification-1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
java:147)
development-authentification-1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
development-authentification-1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
development-authentification-1  | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
development-authentification-1  | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
development-authentification-1  | 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
development-authentification-1  | 	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
development-authentification-1  | 	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
development-authentification-1  | 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
development-authentification-1  | 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
development-authentification-1  | 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
development-authentification-1  | 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
development-authentification-1  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
development-authentification-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
development-authentification-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
development-authentification-1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
development-authentification-1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
development-authentification-1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
development-authentification-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by akbar1214** [comment]
I think possibly it is because keycloak migrated from javax to jakarta. Can you check the same ?

**Comment by sy6sy2** [comment]
How am I supposed to check that?
