### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.ConcurrentHashMapStorageTest#testStorageSeparation

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#22645]
## org.keycloak.testsuite.model.ConcurrentHashMapStorageTest#testStorageSeparation
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/5948540024/job/16133021538) / [Pull Request #22639](https://github.com/keycloak/keycloak/pull/22639)

```
org.keycloak.models.locking.LockAcquiringTimeoutException: Lock [org.keycloak.models.RealmModel] already acquired by keycloak instance [null] at the time [null]
	at org.keycloak.models.map.lock.MapGlobalLockProvider.withLock(MapGlobalLockProvider.java:94)
	at org.keycloak.models.locking.GlobalLockProvider.withLock(GlobalLockProvider.java:45)
	at org.keycloak.models.map.storage.jpa.JpaMapStorageProviderFactory.update(JpaMapStorageProviderFactory.java:549)
	at org.keycloak.models.map.storage.jpa.JpaMapStorageProviderFactory.validateAndUpdateSchema(JpaMapStorageProviderFactory.java:471)
...
```

**Comment by ahus1** [comment]
Already backported to KC22 in September
