### ISSUE TITLE
ClientIdAndSecretCredentialsProvider throws NPE

### ISSUE THREAD

**Issue by devjos** [keycloak/keycloak#22685]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/jee

### Describe the bug

I am using the `keycloak-servlet-filter-adapter` and since version 21.1.0 it throws a NullPointerException (see below). The last working version is 21.0.2. 

```
java.lang.NullPointerException: null
        at org.keycloak.protocol.oidc.client.authentication.ClientIdAndSecretCredentialsProvider.setClientCredentials(ClientIdAndSecretCredentialsProvider.java:53)
        at org.keycloak.protocol.oidc.client.authentication.ClientCredentialsProviderUtils.setClientCredentials(ClientCredentialsProviderUtils.java:91)
        at org.keycloak.adapters.AdapterUtils.setClientCredentials(AdapterUtils.java:106)
        at org.keycloak.adapters.ServerRequest.invokeAccessCodeToToken(ServerRequest.java:106)
        at org.keycloak.adapters.OAuthRequestAuthenticator.resolveCode(OAuthRequestAuthenticator.java:335)
        at org.keycloak.adapters.OAuthRequestAuthenticator.authenticate(OAuthRequestAuthenticator.java:280)
        at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:138)
        at org.keycloak.adapters.servlet.KeycloakOIDCFilter.doFilter(KeycloakOIDCFilter.java:204)
        [....]
```

I looked in the source code and found that `DeploymentDelegate` within `AdapterDeploymentContext` does not overwrite `getAdapterConfig()`, and returns `null` instead. Is this on purpose? Or am I missing something here?

### Version

21.1.0

### Expected behavior

No NPE is thrown.

### Actual behavior

NPE is thrown

### How to Reproduce?

Configure a  `keycloak-servlet-filter-adapter` and use the `KeycloakOIDCFilter`

Our configuration looks as below

```
{
  "realm": "master",
  "auth-server-url" : "/auth",
  "ssl-required": "external",
  "resource": "<resource-name>",
  "credentials": {
    "secret": "<secret>"
  },
  "confidential-port": 0
}
```

**Comment by devjos** [comment]
How can I help in moving this forward?
