### ISSUE TITLE
Server image build fails when jersey-client is in providers folder

### ISSUE THREAD

**Issue by vassilijakovlev-kodality** [keycloak/keycloak#22741]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dependencies

### Describe the bug

Adding jersey-client (v. 3.1.3) with corresponding dependencies to providers/ folder results in a server image build failure.

### Version

22.0.1

### Expected behavior

In order to provide runtime dependency for jakarta.ws.rs.client.ClientBuilder Keycloak should start without an error having jersey-client and sub-dependencies provided in providers/ folder.

### Actual behavior

Server build image results in an error:

```
./kc.sh -v build
Updating the configuration and installing your custom providers, if any. Please wait.
ERROR: Failed to run 'build' command.
Error details:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:81)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:100)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Declaring class of a managed bean is generic, its scope must be @Dependent: org.glassfish.jersey.inject.hk2.InjectionResolverWrapper
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1298)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1161)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:271)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:141)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:419)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:336)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
	... 24 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Declaring class of a managed bean is generic, its scope must be @Dependent: org.glassfish.jersey.inject.hk2.InjectionResolverWrapper
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1298)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1161)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:271)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:141)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:419)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
	... 26 more
Caused by: jakarta.enterprise.inject.spi.DefinitionException: Declaring class of a managed bean is generic, its scope must be @Dependent: org.glassfish.jersey.inject.hk2.InjectionResolverWrapper
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1298)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1161)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:271)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:141)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:419)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### How to Reproduce?

Add the following dependencies to providers/ folder:
```
jersey-client-3.1.3.jar
jersey-common-3.1.3.jar
jersey-hk2-3.1.3.jar
```

Execute build command:
`./kc.sh -v build`

Observe the error.

**Comment by vmuzikar** [comment]
Keycloak is built on RESTEasy. It's possible there are some conflicts with that.

Could you please elaborate a bit on your use case and limitations of RESTEasy that prevent you from using it? Thanks.

**Comment by vassilijakovlev-kodality** [comment]
Yes, switcing to RESTEAsy is a valid option for me. But still I have to add resteasy-client to providers folder, otherwise there are no ClientBuilder implementations available.

Also, it seems that the initial problem is caused by incompatibility of HK2 and CDI.
