### ISSUE TITLE
Deep link format for redirect uri parameter is not parsed correctly

### ISSUE THREAD

**Issue by ebespali** [keycloak/keycloak#22778]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Hi!
We have noticed that "redirect uri" parameter is no longer parsed correctly if it's in "deep link" format, example: cell.sso://oauth2redirect

We have an "*" in client settings for "Valid redirect URIs" parameter but still getting an error in log:
2023-08-28 14:44:32,444 WARN  [org.keycloak.events] (executor-thread-2) type=LOGIN_ERROR, realmId=cell, clientId=my-cell-app-android, userId=null, ipAddress=x.x.x.x, error=invalid_redirect_uri, redirect_uri=cell.sso://oauth2redirect

Update: DEBUG mode shows:
2023-08-29 14:38:08,309 DEBUG [org.keycloak.protocol.oidc.utils.RedirectUtils] (executor-thread-32) Invalid URI **because scheme is not allowed**: cell.sso://oauth2redirect

Setting "Valid redirect URIs" parameter to exact value cell.sso://oauth2redirect along with "*" seems to fix this issue but logout flow not working still:
2023-08-28 17:35:32,825 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-67) Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "redirectUri" is null
	at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:146)
	at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRealmRedirectUri(RedirectUtils.java:54)
	at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logout(LogoutEndpoint.java:245)
	at jdk.internal.reflect.GeneratedMethodAccessor526.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43
	
Logout url looks as
https://sso-test.cell.com.ua/auth/realms/cell/protocol/openid-connect/logout?redirect_uri=https://sso-test.cell.com.ua/auth/realms/cell/protocol/openid-connect/auth?redirect_uri=cell.sso://oauth2redirect&client_id=my-cell-app-android&response_type=code&ui_locales=uk&state=4gymDiO8wvpF3Gz0d0DaQw&nonce=8o8NHt7CIKVsVo1u8giKzQ&scope=openid offline_access&code_challenge=gOu6ZP8Lb4nICu3tqoami2RmCaj91cGA7lP9J4fvox4&code_challenge_method=S256

with redirect_uri parameter in deep link format, but it seems like keycloak is not sees it.

 

### Version

22.0.1

### Expected behavior

"redirect uri" parameter is parsed correctly

### Actual behavior

2023-08-28 14:44:32,444 WARN  [org.keycloak.events] (executor-thread-2) type=LOGIN_ERROR, realmId=cell, clientId=my-cell-app-android, userId=null, ipAddress=x.x.x.x, error=invalid_redirect_uri, redirect_uri=cell.sso://oauth2redirect

### How to Reproduce?

Create client with "Valid redirect URIs" parameter in deep link format.

**Comment by mposolda** [comment]
@ebespali I think that this might be already fixed in latest Keycloak main and in latest Keycloak nightly. Can you please try with latest Keycloak main and/or with latest Keycloak nightly build?

**Comment by ebespali** [comment]
@mposolda, thanks for answer!
Tried on "nightly" Keycloak docker image tag, still can reproduce this:
2023-08-29 16:17:04,977 INFO  [io.quarkus] (main) Keycloak 999.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.4.Final) started in 20.644s. Listening on: http://0.0.0.0:8080

full stacktrace:
2023-08-29 16:20:35,318 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "redirectUri" is null
	at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:146)
	at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRealmRedirectUri(RedirectUtils.java:54)
	at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logout(LogoutEndpoint.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:115)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by pedro-hos** [comment]
@ebespali I was able to create a client with `cell.sso://oauth2redirect` in a Valid redirect URI in our latest code. Can you please share your client, so I can try to reproduce it. 

I used the following to test:

```{json}
{
    "id": "45ff5209-5f32-4f0c-a51c-48c3b1ea3c43",
    "clientId": "deeplink",
    "name": "",
    "description": "",
    "rootUrl": "",
    "adminUrl": "",
    "baseUrl": "",
    "surrogateAuthRequired": false,
    "enabled": true,
    "alwaysDisplayInConsole": false,
    "clientAuthenticatorType": "client-secret",
    "redirectUris": [
        "cell.sso://oauth2redirect"
    ],
    "webOrigins": [],
    "notBefore": 0,
    "bearerOnly": false,
    "consentRequired": false,
    "standardFlowEnabled": true,
    "implicitFlowEnabled": false,
    "directAccessGrantsEnabled": true,
    "serviceAccountsEnabled": false,
    "publicClient": true,
    "frontchannelLogout": true,
    "protocol": "openid-connect",
    "attributes": {
        "oidc.ciba.grant.enabled": "false",
        "oauth2.device.authorization.grant.enabled": "false",
        "display.on.consent.screen": "false",
        "backchannel.logout.session.required": "true",
        "backchannel.logout.revoke.offline.tokens": "false"
    },
    "authenticationFlowBindingOverrides": {},
    "fullScopeAllowed": true,
    "nodeReRegistrationTimeout": -1,
    "defaultClientScopes": [
        "web-origins",
        "acr",
        "roles",
        "profile",
        "email"
    ],
    "optionalClientScopes": [
        "address",
        "phone",
        "offline_access",
        "microprofile-jwt"
    ],
    "access": {
        "view": true,
        "configure": true,
        "manage": true
    }
}
```

**Comment by ebespali** [comment]
@pedro-hos, let me clarify, the issue is not with client creation, the issues are:

1) We have an "*" in client settings for "Valid redirect URIs" parameter but still getting an error in log:
2023-08-28 14:44:32,444 WARN [org.keycloak.events] (executor-thread-2) type=LOGIN_ERROR, realmId=cell, clientId=my-cell-app-android, userId=null, ipAddress=x.x.x.x, error=invalid_redirect_uri, redirect_uri=cell.sso://oauth2redirect
this can be fixed by adding separate paramater for Valid redirect URIs equal to exact value of redirect uri, see screenshot below:
<img width="934" alt="Screenshot 2023-09-11 at 17 36 51" src="https://github.com/keycloak/keycloak/assets/64463776/8847ca6d-2298-4326-a7c6-bb8966d338d2">
this behavior appeared in version 22, in previous versions having "*" in client settings for "Valid redirect URIs" was sufficient without explicitly adding "cell.sso://oauth2redirect".

2) legacy logout not working:
2023-08-28 17:35:32,825 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-67) Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "redirectUri" is null
at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:146)
at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRealmRedirectUri(RedirectUtils.java:54)
at org.keycloak.protocol.oidc.endpoints.LogoutEndpoint.logout(LogoutEndpoint.java:245)
at jdk.internal.reflect.GeneratedMethodAccessor526.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43

Logout url looks as:
https://sso-test.cell.com.ua/auth/realms/cell/protocol/openid-connect/logout?redirect_uri=https://sso-test.cell.com.ua/auth/realms/cell/protocol/openid-connect/auth?redirect_uri=cell.sso://oauth2redirect&client_id=my-cell-app-android&response_type=code&ui_locales=uk&state=4gymDiO8wvpF3Gz0d0DaQw&nonce=8o8NHt7CIKVsVo1u8giKzQ&scope=openid offline_access&code_challenge=gOu6ZP8Lb4nICu3tqoami2RmCaj91cGA7lP9J4fvox4&code_challenge_method=S256

As you can see, redirect_uri parameter is present in logout url but still we are getting an error:
2023-08-28 17:35:32,825 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-67) Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "redirectUri" is null

**Comment by rmartinc** [comment]
Hi @ebespali!

In keycloak 21.1.2 we added a change that custom schemes are not allowed via general valid URL `*`. It was a security issue. So now you need something more specific like `cell.sso:*` for example. It was explained in the [release notes](https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-21-1-2).

Regarding the NPE at logout, I cannot reproduce it in my env (I tested with this URL `curl 'http://localhost:8080/realms/master/protocol/openid-connect/logout?redirect_uri=custom%3A%2F%2Flala&state=7d4c058a-37a5-4ccb-a075-35442dfbda9e` and setting `--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true`). Can you please comment the exact steps to reproduce it?

Regards!

**Comment by ebespali** [comment]
@rmartinc, thanks for you answer!

Regarding custom schemes via "*", thanks for additional clarification, sorry for missing that out.

Regarding logout, after additional investigation, we have found that problem is arived when logout url contains whitespace.
For example, there is a whitespice in url we are using for logout:
https://sso-test.cell.com.ua/auth/realms/cell/protocol/openid-connect/logout?redirect_uri=https://sso-test.cell.com.ua/auth/realms/cell/protocol/openid-connect/auth?redirect_uri=cell.sso://oauth2redirect&client_id=my-cell-app-android&response_type=code&ui_locales=uk&state=4gymDiO8wvpF3Gz0d0DaQw&nonce=8o8NHt7CIKVsVo1u8giKzQ**&scope=openid** **offline_access&**code_challenge=gOu6ZP8Lb4nICu3tqoami2RmCaj91cGA7lP9J4fvox4&code_challenge_method=S256

beetwen &scope=openid  and  offline_access&, and it seems like keycloak didn't like that.

We have been worked out this issue by replacing whitespace in logout url with another symbol, so there is no whitespace in url that is passed to keycloak.

Can you please check with url that contains whitespace itself?
Thanks in advance!

**Comment by rmartinc** [comment]
The space is in a query parameter in the URL to redirect to, right? Note that the encoding here is a bit tricky. First the url to redirect should be properly encoded and then encoded again for the parameter. So, for example:

Correct final URL to redirect: `http://localhost:8081/sample-rhsso/?v=p1%20p2` (here the URL should be OK, the space is bad, as it's not valid URL, so it's encoded as %20)

Now you have to encode that parameter in another parameter `redirect_uri` or `post_logout_redirect_uri` fror the logout. So it should encoded again: `http%3A%2F%2Flocalhost%3A8081%2Fsample-rhsso%2F?v%3Dp1%2520p2`

Nevertheless, the error should not be a NPE, that's not good. But I think the problem is that the `redirectUri` cannot be parsed as a valid URI (because the space in it) and a null is returned.

Have you tried that?

**Comment by ebespali** [comment]
@rmartinc, thanks for this hint, we will try it out)

But i must say that we have this logout url(with space) since many versions ago(like 12.0), and it has worked correctly at least till version 20.0.3.
Maybe there were some changes in recent versions that may cause different behaviour?
Thanks!

**Comment by rmartinc** [comment]
Yep, there have been several changes in that part included a security issue. I think that it started to fail in 21.1.0 so probably since this [commit](https://github.com/keycloak/keycloak/commit/709c6b5a473000635f4cbe4db1b0ae120a1cf87d#diff-8a42999224cc18191469006d9c48d36f83917774badfe5b103e259380318043cR135-R136). The `redirectUri` returned is the original one but normalized. And now, because you are sending an invalid URI it throws the exception when creating the URI.

@mposolda I think it's OK if we don't allow an invalid URI as a valid redirect URI, but we should check it before and don't throw that horrible exception. I let the decision to you. :smiley: I can work on it if you are busy.

**Comment by mposolda** [comment]
@rmartinc Yes, I agree with you. Thanks for looking at this! Re-assigned to you.

**Comment by mposolda** [comment]
Adding to Keycloak 22.0.4 since this is probably a regression...

**Comment by rmartinc** [comment]
Submitted PR for 22.0: https://github.com/keycloak/keycloak/pull/23442

**Comment by tomekit** [comment]
I am not sure if this is expected, but if: `*`  wildcard is used then e.g. `app.com://oauth2redirect` redirect_uri isn't accepted.
If `app.com://oauth2redirect` is explicitly added then it works fine. 

This issue was also  mentioned in one of the above comments: https://github.com/keycloak/keycloak/issues/22778#issuecomment-1717566997

Version: 22.0.4

**Comment by lindseypeng** [comment]
im still experiencing this issue . 
What I've already tried (no change in behavior):
- Fully reinstalling the app
- Resetting the macOS Launch Services database (lsregister -kill -r -domain local -domain system -domain user), then relaunching
- Running `gh auth login` and `claude /login` in Terminal to confirm my Mac can complete other OAuth browser callbacks normally
- Multiple browsers, in case it was a default-browser handoff issue
Details:
- macOS version: 13.6.4 (22G513)
- Conductor version: Version 0.70.2 (0.70.2)

<img width="1521" height="622" alt="Image" src="https://github.com/user-attachments/assets/96b25634-8b0a-46d5-b616-ea92998c77d1" />
