### ISSUE TITLE
Flaky test: org.keycloak.testsuite.forms.RegisterWithUserProfileTest#testRegisterUserSuccess_attributeNotRequiredAndSelectedByScopeCanBeSet

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#22854]
## org.keycloak.testsuite.forms.RegisterWithUserProfileTest#testRegisterUserSuccess_attributeNotRequiredAndSelectedByScopeCanBeSet
[Keycloak CI - Forms IT (chrome)]() / [Pull Request #21915](https://github.com/keycloak/keycloak/pull/21915)

```
java.lang.IllegalArgumentException: No enum constant org.keycloak.testsuite.pages.AppPage.RequestType.
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.keycloak.testsuite.pages.AppPage$RequestType.valueOf(AppPage.java:56)
	at org.keycloak.testsuite.pages.AppPage.getRequestType(AppPage.java:49)
	at jdk.internal.reflect.GeneratedMethodAccessor552.invoke(Unknown Source)
...
```

**Comment by stianst** [comment]
Closing since this hasn't happened for quite some time.
