### ISSUE TITLE
Custom account theme no longer works in 22.0.1

### ISSUE THREAD

**Issue by RobKenis** [keycloak/keycloak#22885]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

I have been using a custom theme for account using the following theme.properties

```
parent=base
import=common/keycloak

scripts=account.js
styles=css/account.css
stylesCommon=node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css

##### css classes for form buttons
# main class used for all buttons
kcButtonClass=btn
# classes defining priority of the button - primary or default (there is typically only one priority button for the form)
kcButtonPrimaryClass=btn-primary
kcButtonDefaultClass=btn-default
# classes defining size of the button
kcButtonLargeClass=btn-lg
```

After upgrading from 21.0.1 to 22.0.1, I run into issues when loading the account page. I have looked for documentation to migrate themes using account V1 to V2 or V3 but no luck so far.

### Version

22.0.1

### Expected behavior

The account page loads with my custom theme.

### Actual behavior

```
2023-09-01 07:37:18,827 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
    at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)
    at org.keycloak.services.resources.account.AccountConsole.getMainPage(AccountConsole.java:151)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
    at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
    at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
    at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
    at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
    at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
    at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
    at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
    at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@184eefae.
    at freemarker.template.Configuration.getTemplate(Configuration.java:2957)
    at freemarker.template.Configuration.getTemplate(Configuration.java:2777)
    at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.getTemplate(DefaultFreeMarkerProvider.java:66)
    at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:39)
    ... 44 more
```

### How to Reproduce?

Create a custom theme for account with following theme.properties

```
parent=base
import=common/keycloak
```

**Comment by jonkoops** [comment]
@ssilvert I believe this is a duplicate as we had another listed for this, but I can't seem to find it. Do you know of one?

**Comment by RobKenis** [comment]
@jonkoops These seem related, but don't provide a fix/workaround:
- https://github.com/keycloakify/keycloakify/issues/389
- https://github.com/keycloak/keycloak/issues/21654
- https://github.com/keycloak/keycloak/issues/19738

**Comment by jonkoops** [comment]
Yeah, it boils down to that the old Account Console your theme is based on no longer exists. Because the new Account Console is rendered on the client rather than the server the only template that still exists is `index.ftl`, which is not present in your custom theme.

**Comment by RobKenis** [comment]
@jonkoops Are custom themes already supported or are we stuck with upgrading until further releases?

**Comment by jonkoops** [comment]
I am not sure what you mean by that, custom themes are supported AFAIK. They just have to follow the same conventions as the `base` they extend. Either way, this situation is not ideal right now, and I believe there is work out there that intends to mitigate this to a degree. I doubt however that we will be restoring the same templates as the old theme provided.

**Comment by Cracky5457** [comment]
I encounter the very same error

```
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@184eefae.
    at freemarker.template.Configuration.getTemplate(Configuration.java:2957)
    at freemarker.template.Configuration.getTemplate(Configuration.java:2777)
    at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.getTemplate(DefaultFreeMarkerProvider.java:66)
    at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:39)
    ... 44 more
```


Worst, If I decide to switch to default "keycloak v2" theme to avoid this exception, I encounter a 403 forbidden issue. Is it the same for you ?

<img width="1484" alt="Capture d’écran 2023-09-11 à 14 35 54" src="https://github.com/keycloak/keycloak/assets/12050544/c86a50f6-c569-4798-8b20-91c2dad897ca">





I

**Comment by ssilvert** [comment]
This PR will allow the old account console to be restored.  Account console V1 still won't ship with Keycloak, but you will be able to add it back in yourself and allow your V1 customizations to run again.
https://github.com/keycloak/keycloak/pull/22317

**Comment by ssilvert** [comment]
@Cracky5457 Probably, your user does not have access to the account v2 console.  He should have `account->manage-account` and `account->view-profile roles`.  These roles are usually inherited from the `default-roles-<realmname>` role.
