### ISSUE TITLE
Keycloak 22.0.1: NPE in Edit Identity Provider Mapper on second Save

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#22890]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Saving an Identity Provider Mapper second time fails.

### Version

22.0.1

### Expected behavior

Just save should occur again.

### Actual behavior

Error is shown 'Error creating mapper.'
![изображение](https://github.com/keycloak/keycloak/assets/1285898/eb7f77eb-27d2-4b63-b65c-d25890171aca)

```
2023-09-01 16:06:42,308 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-52) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.jpa.entities.IdentityProviderMapperEntity.setIdentityProviderAlias(String)" because "entity" is null
	at org.keycloak.models.jpa.RealmAdapter.updateIdentityProviderMapper(RealmAdapter.java:1417)
	at org.keycloak.models.cache.infinispan.RealmAdapter.updateIdentityProviderMapper(RealmAdapter.java:1152)
	at org.keycloak.services.resources.admin.IdentityProviderResource.update(IdentityProviderResource.java:418)
```

### How to Reproduce?

Identity Providers -> Mappers -> Add mapper

Input any Name, Mapper type (e.g. Hardcoded Role), Select Role.

Press Save (UI shows 'Mapper saved successfully.').
Press Save again.

### Anything else?

This bug was reported already and marked as fixed (https://github.com/keycloak/keycloak/issues/21358)
however reproduced again in 22.0.1

**Comment by ssilvert** [comment]
@edewit I'm assigning to you since you fixed the same or similar issue #21358

**Comment by lrozenblyum** [comment]
Hello @edewit! Is it planned to be also included to the 22.* (backported)?

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.
