### ISSUE TITLE
EventListenerProvider hooked to transaction while accessing userAttributes is causing ConcurrentModificationException

### ISSUE THREAD

**Issue by kvnlin** [keycloak/keycloak#22902]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

We have custom implementation of EventListenerProvider where we are using EventListenerTransaction

According to [documentation](https://www.keycloak.org/docs-api/22.0.1/javadocs/org/keycloak/events/EventListenerProvider.html) it suggesting to hook to transaction manager after complication.

Here is example
```
    private final EventListenerTransaction transaction = new EventListenerTransaction(
            this::handleAdminEvent,
            this::handleClientEvent
    );
```
then in constructor we have
```
        this.keycloakSession
                .getTransactionManager()
                .enlistAfterCompletion(this.transaction);
```
this is the handleClientEvent block

```
private void handleClientEvent(Event event) {
  RealmModel realm = session.realms().getRealm(event.getRealmId());
  UserModel user = session.users().getUserById(realm, event.getUserId());
  Map<String, List<String>> userAttrs = user.getAttributes();
}
```
  
Anytime EventBuilder.error is called it causes a ConcurrentModificationException.

Uncaught server error: java.util.ConcurrentModificationException
	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:144)
	at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:502)
	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:469)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:274)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
	at org.keycloak.events.EventBuilder.send(EventBuilder.java:237)
	at org.keycloak.events.EventBuilder.error(EventBuilder.java:224)
On the other hand EventBuilder.success works fine.

This seems related to - https://github.com/keycloak/keycloak/issues/21297

### Version

22.0.1

### Expected behavior

Event listener should works in transactional mode regardless of how event has been dispatched and when accessing user attributes.

### Actual behavior

Event listener in transactional mode crash app when triggered type of event is kind of error and the event handler accesses something that requires the delegate e.g. providing invalid credentials will trigger event LOGIN_ERROR and accessing user attributes.

### How to Reproduce?

Make event listener to run in transaction and trigger any error event while accessing something that requires the delegate in the event handler e.g. LOGIN_ERROR & access user attributes.

Below simplified custom event listener that is crashing

```
public class CustomEventListenerProvider implements EventListenerProvider {
    private final KeycloakSession keycloakSession;

    private final EventListenerTransaction transaction = new EventListenerTransaction(
            this::handleAdminEvent,
            this::handleClientEvent
    );

    public CustomEventListenerProvider(
            KeycloakSession keycloakSession
    ) {
        this.keycloakSession = keycloakSession;

        this.keycloakSession
                .getTransactionManager()
                .enlistAfterCompletion(this.transaction);
    }

    @Override
    public void onEvent(Event event) {
            transaction.addEvent(event);
       
    }

    @Override
    public void onEvent(AdminEvent event, boolean includeRepresentation) {
            transaction.addAdminEvent(event, includeRepresentation);
    }

    @Override
    public void close() {
    }

    private void handleClientEvent(Event event) {
      RealmModel realm = this.keycloakSession.realms().getRealm(event.getRealmId());
      UserModel user = this.keycloakSession.users().getUserById(realm, event.getUserId());
      Map<String, List<String>> userAttrs = user.getAttributes();
    }
    
    private void handleAdminEvent(AdminEvent event, boolean includeRepresentation) {
      // http request
    }
```

**Comment by pedroigor** [comment]
@kvnlin Not again ... It should be fixed. Will try to reproduce it based on the fix we did here https://github.com/keycloak/keycloak/pull/20793.

**Comment by kvnlin** [comment]
@pedroigor its a slightly different issue from the original one. If you don't try and access anything that requires the delegate it works, but if you try and access something like user attributes in the event handler that's when the issue comes up.

**Comment by pedroigor** [comment]
The concurrency issue is about your provider being invoked when the cache/store-related providers (e.g.: `UserCacheSession`) are not yet bound to a session so they try to enlist a transaction to the same transaction manager when the thread is already iterating over the listeners.

**Comment by kvnlin** [comment]
@pedroigor we only recently started using Keycloak and the functionality hasn't worked on any of the 21.x.x or 22.x.x versions we've been on. Is there any way around this? Attempting to do this outside of the transactional pattern leads to "Cannot access delegate without a transaction" errors intermittently.

**Comment by pedroigor** [comment]
In your case, make sure you are accessing data from the session within the `onEvent` methods and not when handling events from your `EventListenerTransaction`.

```
@Override
    public void onEvent(Event event) {
        RealmModel realm = session.realms().getRealm(event.getRealmId());
        UserModel user = session.users().getUserByUsername(realm, "alice");
        Map<String, String> details = event.getDetails();
        details.put("user.attributes", user.getAttributes().toString());
        tx.addEvent(event);
    }
```

You can also try creating a wrapper around the `Event` if using the details map is not enough.

**Comment by kvnlin** [comment]
@pedroigor doing things this way though leads to the "Cannot access delegate without a transaction" error if we try accessing the attributes of a user from outside of the transaction for `LOGIN_ERROR` events

**Comment by pedroigor** [comment]
I see. I meant something like this https://github.com/pedroigor/keycloak/commit/efd11819d9dc8ffd0c2e1f90fb3ab8f265810439.

Does not look like a bug because after completion transactions are not supported to run in a transactional context as they run after the original transaction is completed. That is why you need to make you are populating the event with any additional information from the session when the `EventListenerProvider#onEvent` method is called.

This behavior is expected.

**Comment by kvnlin** [comment]
@pedroigor got it thanks for the example. 

I'll give that a try and see if it resolves things and report back.

Thanks again for the help!

**Comment by pedroigor** [comment]
Thanks.

I'm marking this one as an improvement in docs so that we make it clear that you can't rely on transactional providers when registering after completion tasks.

**Comment by mshivanna** [comment]
I have a similar issue and I am accessing the data from session within the onEvent. We run 22.0.5 version of keycloak 
```
  @Override
  public void onEvent(Event event) {
            RealmModel realm = session.realms().getRealm(event.getRealmId());
	    UserModel user = session.users().getUserById(realm, event.getUserId());
            Map<String, String> details = event.getDetails();
	    details.put("Namespace", user.getAttributes().get("Namespace").get(0).toString());
            schedule(new SenderTask(ModelToRepresentation.toRepresentation(event), getBackOff()),0l,TimeUnit.MILLISECONDS);
  }
```
