### ISSUE TITLE
KeycloakErrorHandler  NullPointerException String.toLowe rCase() because message is null

### ISSUE THREAD

**Issue by prjmax** [keycloak/keycloak#22958]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

Getting a KeycloakErrorHandler  NullPointerException String.toLowe rCase() because message is null when Invoking Get token endpoint (/auth/realms/my-realm/protocol/openid-connect/token) in bulk as part of Performance testing, with ~ 200/minute

I'm getting this error randomly in some of the calls

2023-08-31 06:24:31,104 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3683) Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.toLowe
rCase()" because "message" is null
at org.keycloak.connections.jpa.PersistenceExceptionConverter.lambda$convert$0(PersistenceExceptionConverter.java:84)
at java.base/java.util.function.Predicate.lambda$or$2(Predicate.java:101)
at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:94)
at org.keycloak.connections.jpa.JpaExceptionConverter.convert(JpaExceptionConverter.java:33)
at org.keycloak.transaction.JtaTransactionWrapper.lambda$handleException$0(JtaTransactionWrapper.java:65)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
at org.keycloak.transaction.JtaTransactionWrapper.handleException(JtaTransactionWrapper.java:67)
at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:92)
at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:56)
at org.keycloak.quarkus.runtime.integration.jaxrs.TransactionalResponseFilter.filter(TransactionalResponseFilter.java:48)
at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:329)
at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:243)
at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:100)
at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:73)
at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:518)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:458)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
at io.quarkus.resteasy.

### Version

22.0.1

### Expected behavior

The endpoint should return the tokens

### Actual behavior

it is returning a 500 error with KeycloakErrorHandler  NullPointerException

### How to Reproduce?

Disable Brute force detection on the realm to test (my-realm)
Invoke Get token call with valid credentials in bulk as part of Performance testing within the rate limiting of 200/minute

### Anything else?

Keycloak is deployed in EKS
using PostgreSQL DB

**Comment by viniprince39** [comment]
Hi,

We configured Quarakus Keycloak on RHEL server. We are facing the same issur. And Not able to find the PersistencrExceptionconverter.java file or folder at all. Can you please suggest on how to fix it?
