### ISSUE TITLE
Flaky test: org.keycloak.testsuite.forms.RegisterTest#testEmailAsUsernameWhenEditUserNameDisabled

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#22973]
## org.keycloak.testsuite.forms.RegisterTest#testEmailAsUsernameWhenEditUserNameDisabled
[Keycloak CI - Forms IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/6074512479/job/16479266803) / [Pull Request #22945](https://github.com/keycloak/keycloak/pull/22945)

```
java.lang.IllegalArgumentException: No enum constant org.keycloak.testsuite.pages.AppPage.RequestType.
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.keycloak.testsuite.pages.AppPage$RequestType.valueOf(AppPage.java:56)
	at org.keycloak.testsuite.pages.AppPage.getRequestType(AppPage.java:49)
	at jdk.internal.reflect.GeneratedMethodAccessor553.invoke(Unknown Source)
...
```

**Comment by pedroigor** [comment]
Closing because it seems more stable. Perhaps after https://github.com/keycloak/keycloak/pull/25902.
