### ISSUE TITLE
NullpointerException when using encrypted SAML assertions

### ISSUE THREAD

**Issue by mfredenhagen** [keycloak/keycloak#22974]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

When setting up an Identity provider of type SAMLv2.0 and enabling `Want Assertions encrypted`, a NullpointerException is thrown. 

Stacktrace from latest nightly release:
```
2023-09-05 08:57:48,673 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: org.keycloak.broker.provider.IdentityBrokerException: Could not process response from SAML identity provider.
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:596)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleSamlResponse(SAMLEndpoint.java:679)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.execute(SAMLEndpoint.java:278)
	at org.keycloak.broker.saml.SAMLEndpoint.postBinding(SAMLEndpoint.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.runBlockingCode(QuarkusRequestFilter.java:121)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$handle$0(QuarkusRequestFilter.java:83)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.protocol.saml.SAMLDecryptionKeysLocator.getKeys(SAMLDecryptionKeysLocator.java:164)
	at org.keycloak.saml.processing.core.util.XMLEncryptionUtil.decryptElementInDocument(XMLEncryptionUtil.java:285)
	at org.keycloak.saml.processing.core.saml.v2.util.AssertionUtil.decryptAssertion(AssertionUtil.java:612)
	at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:449)
	... 50 more
```

### Version

21.1.2, where we observed this after upgrading from 20.0.5

### Expected behavior

No exception, instead, usage of the right key.
This worked in Keycloak v20.1.5 before introducing separate keys for signing and encryption.

### Actual behavior

Unable to login with the configured SAML v2.0 identity provider.

### How to Reproduce?

1. Configure a SAML v2.0 identity provider
2. enable `Want Assertions encrypted`
3. Configure the chosen identity provider to encrypt assertions with the key provided in serviceProviderConfig document via link `SAML 2.0 Service Provider Metadata`
4. try to login and get 
<img width="514" alt="image" src="https://github.com/keycloak/keycloak/assets/11857880/df7e6340-8c8e-43da-8f40-19329f0fbe77">

### Anything else?

Here a patch to fix this:
```
Subject: [PATCH] Ensure only wrapped keys intended for public key cryptography are used for SAML decryption

Otherwise, symmetric keys are selected as well and forcing a NullPointerException
when reading private key while mapping the keyStream.
---
Index: core/src/main/java/org/keycloak/crypto/KeyWrapper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/main/java/org/keycloak/crypto/KeyWrapper.java b/core/src/main/java/org/keycloak/crypto/KeyWrapper.java
--- a/core/src/main/java/org/keycloak/crypto/KeyWrapper.java	(revision 8286b8b31fcfe9822b5f6f7693e76547b1960d87)
+++ b/core/src/main/java/org/keycloak/crypto/KeyWrapper.java	(date 1693901491498)
@@ -195,4 +195,8 @@
         key.isDefaultClientCertificate = this.isDefaultClientCertificate;
         return key;
     }
+
+    public boolean isForPublicKeyCryptography() {
+        return publicKey != null && privateKey != null;
+    }
 }
Index: services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java b/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java
--- a/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java	(revision 8286b8b31fcfe9822b5f6f7693e76547b1960d87)
+++ b/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java	(date 1693901046818)
@@ -152,6 +152,7 @@
 
         // Map keys to PrivateKey
         return keysStream
+                .filter(KeyWrapper::isForPublicKeyCryptography) // required to get encoded private key safely
                 .map(KeyWrapper::getPrivateKey)
                 .map(Key::getEncoded)
                 .map(encoded -> {
```

I also found that setting `encryptionAlgorithm` config parameter to `RSA-OAEP` (the algorithm from the used key) via Rest-API (note: there is no possibility to set this via UI!) on IdentityProviderRepresentation avoids SamlEndpoint.handleLoginResponse throwing an NPE. But the check (in the patch) is a good defensive strategy for avoiding the NPE.

**Comment by rmartinc** [comment]
Hi @mfredenhagen!

I'm not following you completely. The identity provider uses for decryption the realm keys. Your fix means that there is a generated/imported a RSA-OAEP in the realm with no private key, right? How have you done that? Maybe something related to the upgrade, but I don't see how to reach that state.

And the other question, in the identity provider you can select the encryption algorithm in the console. It's the option `Encryption algorithm` a bit above the `Want Assertions encrypted` (RSA-OAEP and RSA1_5). Or are you talking in another place different to the identity provider?

![Screenshot from 2023-09-07 14-37-04](https://github.com/keycloak/keycloak/assets/26901232/faaaf432-ccb2-4167-847f-3280a393b0d9)

**Comment by mfredenhagen** [comment]
Hi @rmartinc ,
The key that causes trouble is an AES key for ENC usage -> 
<img width="1436" alt="image" src="https://github.com/keycloak/keycloak/assets/11857880/67b21f92-551d-4b82-96da-07318492d9bb">
and I don't have an input field for `Encryption algorithm` (see [screen recording](https://drive.google.com/file/d/13jDsL3m7lMdXlp8eekxda6mseEVuXOy3/view?usp=sharing) for reproducing steps including missing input field in UI).

**Comment by rmartinc** [comment]
Thanks for the video @mfredenhagen!

I detected that the option only is shown if you set `Want AuthnRequests signed` to ON. It should be toggle when you have `Want Assertions encrypted` to ON. That's an issue with the console for sure.

But regarding the NPE, I still don't understand why the keys are not filtered by the algorithm in the SAML response. In the [SAMLDecryptionKeysLocator](https://github.com/keycloak/keycloak/blob/22.0.2/services/src/main/java/org/keycloak/protocol/saml/SAMLDecryptionKeysLocator.java#L147) the keys are always filtered by the alg set in the document. So theoretically it will never return the AES key if the alg (`http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p` or whatever) is set there. Can you paste the saml response from the IdP? I'm interested in the `EncryptedAssertion` element. You can redact the cipher or certificate values if needed.

**Comment by rmartinc** [comment]
The problem was that the `EncryptedKey` in that case is not inside the `EncryptedData` and the key locator cannot filter the list by the algorithm. I think it's better if we try to locate the correct alg. Because theoretically it can be any other public/private pair (EC for example), although now all the valid algs are RSA based. Nevertheless I added a `nonNull` filter to remove keys without private keys just in case.

@mfredenhagen Can you please test with this [branch](https://github.com/rmartinc/keycloak/tree/issue-22974)? Or cherry-picking the last [commit on it](https://github.com/rmartinc/keycloak/commit/3f41a0dd0d3f44cb7e61d5f1afef0fe5f7f83e1a)?

I think I have created a test similar to your response but it would be wonderful if you can test with the real IdP. If you see it correct I will send a PR.

**Comment by mfredenhagen** [comment]
Hi @rmartinc I have tested it with our Okta IdP, and it is working :-) The UI piece isn't included, and therefore, the encryptionAlgorithm config value, too. How is this supposed to work? Is it considered a fallback in case the encrypted key isn't specified?

**Comment by rmartinc** [comment]
@mfredenhagen Thanks for testing!

For the UI I will create another issue with the UI team. It's easy but they can think if they want to add tests or whatever.

And yes, it's a fallback, if you receive an encrypted assertion the default behavior tries to decrypt with the keys that are valid for the specified algorithm. I don't think it's very common but the same provider can even handle different algs/keys.

**Comment by jonkoops** [comment]
@rmartinc this might be something we want to backport to 22, WDYT?
