### ISSUE TITLE
Flaky test: org.keycloak.testsuite.forms.RegisterWithUserProfileTest#testRegisterUserSuccess_attributeRequiredAndSelectedByScopeMustBeSet

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#23068]
## org.keycloak.testsuite.forms.RegisterWithUserProfileTest#testRegisterUserSuccess_attributeRequiredAndSelectedByScopeMustBeSet
[Keycloak CI - Forms IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/6083955912/job/16505397733) / [Pull Request #22979](https://github.com/keycloak/keycloak/pull/22979)

```
java.lang.IllegalArgumentException: No enum constant org.keycloak.testsuite.pages.AppPage.RequestType.
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.keycloak.testsuite.pages.AppPage$RequestType.valueOf(AppPage.java:56)
	at org.keycloak.testsuite.pages.AppPage.getRequestType(AppPage.java:49)
	at jdk.internal.reflect.GeneratedMethodAccessor553.invoke(Unknown Source)
...
```

**Comment by stianst** [comment]
Closing since this hasn't happened for quite some time.
