### ISSUE TITLE
Upgrading custom build Keycloak to 22.x breaks JWT validation of admin user

### ISSUE THREAD

**Issue by boonen** [keycloak/keycloak#23421]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

We use a 0-CVE approach to Keycloak (as described here: https://www.codecentric.de/wissens-hub/blog/keycloak-x-but-secure-without-vulnerable-libraries). When upgrading from 21.x to 22.x the authorization of the admin user fails (both when using the UI console and the API). That is: we can login using the username and password, but when using the Access Token as Bearer token the application returns a HTTP 403 unauthorized exception.

Inspection of the logs says that the JWT validation fails, but the reason remains unclear. I have copied the relevant log lines here:

```
2023-09-21 11:04:04,901 DEBUG [org.keycloak.events] (executor-thread-1) type=LOGIN, realmId=e14bd7e7-3c04-478d-8558-0e83a87d1c68, clientId=security-admin-console, userId=18077cd2-00f4-4acb-9052-e8c4b550d8b9, ipAddress=192.168.112.1, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=http://localhost:8080/admin/master/console/, consent=no_consent_required, code_id=fc6ab9bd-b826-4e93-9984-66af4902a814, username=admin, response_mode=fragment, authSessionParentId=fc6ab9bd-b826-4e93-9984-66af4902a814, authSessionTabId=IEP0XM_aezM
...
2023-09-21 11:04:05,167 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (executor-thread-2) AUTHENTICATE CLIENT
2023-09-21 11:04:05,168 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-2) client authenticator: client-secret
2023-09-21 11:04:05,169 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-2) client authenticator SUCCESS: client-secret
2023-09-21 11:04:05,169 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-2) Client security-admin-console authenticated by client-secret
2023-09-21 11:04:05,169 DEBUG [org.keycloak.protocol.oidc.utils.RedirectUtils] (executor-thread-2) replacing relative valid redirect with: http://localhost:8080/admin/master/console/*
2023-09-21 11:04:05,169 DEBUG [org.keycloak.protocol.oidc.utils.RedirectUtils] (executor-thread-2) replacing relative valid redirect with: http://localhost:8080/admin/master/console/*
2023-09-21 11:04:05,170 DEBUG [org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider] (executor-thread-2) getUserSessionWithPredicate(fc6ab9bd-b826-4e93-9984-66af4902a814): found in local cache
2023-09-21 11:04:05,172 DEBUG [org.keycloak.protocol.oidc.utils.PkceUtils] (executor-thread-2) PKCE supporting Client, codeVerifier = lzyAGiKZR7Oyiong6QkyMjpC2gCNmCsdK13DW5iVqRQswqs7KFEkY34FLqssDneJI8DiHsr17RiErnWqDWf2SoW2qEdMVHXr
2023-09-21 11:04:05,172 DEBUG [org.keycloak.protocol.oidc.utils.PkceUtils] (executor-thread-2) PKCE codeChallengeMethod = S256
2023-09-21 11:04:05,172 DEBUG [org.keycloak.protocol.oidc.utils.PkceUtils] (executor-thread-2) PKCE verification success. codeVerifierEncoded = SCR7d2dKS29VchLiVrzjdOc-rhEnmv10hhiab1ZEhwo, codeChallenge = SCR7d2dKS29VchLiVrzjdOc-rhEnmv10hhiab1ZEhwo
...
2023-09-21 11:04:05,349 DEBUG [org.keycloak.events] (executor-thread-2) type=CODE_TO_TOKEN, realmId=e14bd7e7-3c04-478d-8558-0e83a87d1c68, clientId=security-admin-console, userId=18077cd2-00f4-4acb-9052-e8c4b550d8b9, ipAddress=192.168.112.1, token_id=21bc9439-1e55-430c-9121-2ac0da8c601e, grant_type=authorization_code, refresh_token_type=Refresh, scope='openid profile email', refresh_token_id=cd2dca26-565b-4f73-b4c3-ed9ead5c1537, code_id=fc6ab9bd-b826-4e93-9984-66af4902a814, client_auth_method=client-secret
...
2023-09-21 11:04:05,397 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-6) Error response 401: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
    at org.keycloak.services.resources.admin.AdminRoot.authenticateRealmAdminRequest(AdminRoot.java:168)
    at org.keycloak.services.resources.admin.AdminRoot.getRealmsAdmin(AdminRoot.java:218)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.constructLocator(ResourceLocatorInvoker.java:105)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTargetFromLocator(ResourceLocatorInvoker.java:86)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTarget(ResourceLocatorInvoker.java:75)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:126)
    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
    at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
    at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
    at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
    at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
    at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
    at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
    at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
    at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

A full list of dependencies that are in use can be found here: [keycloak-22.0.3_0-cve_dependencies.txt](https://github.com/keycloak/keycloak/files/12682820/keycloak-22.0.3_0-cve_dependencies.txt).

### Version

22.0.3

### Expected behavior

Access token that is issued to the admin user can be used to access the UI console and the API.

### Actual behavior

Token validation fails without a clear reason in the log file.

### How to Reproduce?

1. Build a 0-CVE version of Keycloak using the code in this repository: https://github.com/MaikKingma/keycloak-configAsCode-demo/tree/Keycloak-version-upgrade
2. Run the Docker images using Docker Compose file
3. Try to log in as admin user at http://localhost:8080/admin
4. The result is a HTTP 403 of all endpoints (note that the Bearer token is present), e.g. 
<img width="775" alt="image" src="https://github.com/keycloak/keycloak/assets/24561/4786e566-133a-4b75-a906-5f5b0544f1d9">

**Comment by pedroigor** [comment]
Glad you found a fix and to see how Quarkus helps to customize the server distribution. It comes with a cost though as we only support the distribution available from our site.

**Comment by MaikKingma** [comment]
> Glad you found a fix and to see how Quarkus helps to customize the server distribution. It comes with a cost though as we only support the distribution available from our site.

I am not sure what you refer to here. It is the official Keycloak distribution we are using:
```
        <dependency>
            <!-- Keycloak Distribution -->
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-quarkus-dist</artifactId>
            <type>zip</type>
        </dependency>
```
