### ISSUE TITLE
Can not view or update user profile attribute in user details

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#23434]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Since upgrading to KC 22.0.3 I am not able to see the user profile attribute values on the user details page even though they are returned by the API: 

![image](https://github.com/keycloak/keycloak/assets/1793007/90b189c0-4c58-4aac-b87c-d73fe5b84281)

![image](https://github.com/keycloak/keycloak/assets/1793007/011aa5c3-9257-493c-b9f2-cc1e45e7b410)

When I try to update the value this is not updated in the request payload and the old value is send again:
![image](https://github.com/keycloak/keycloak/assets/1793007/defa130b-3925-4f6a-8eba-ce922848fa65)
![image](https://github.com/keycloak/keycloak/assets/1793007/25cf6359-39e4-442a-9b80-67d2c95db4e9)

Looks like this is a Frontend issue. The mapping between the form and the model seem to be broken.

### Version

22.0.3

### Expected behavior

Form for user profile attributes is filled with old values on opening the user details screen.
When updating user profile attributes and pressing the save button the updated values are send.

### Actual behavior

Form for user profile attributes is **NOT** filled with old values on opening the user details screen. Its just empty.
When updating user profile attributes and pressing the save button the updated values are **NOT** send. Instead the old ones are send.

### How to Reproduce?

1. Enable user profile feature, add a custom user profile attribute: e.g. birthdate - validator not necessary. Do not set it to required as otherwise you are at the moment not able to create a user (there is a separate story for that one).
2. Create a user
3. On the details screen of the user update the birthdate and press save.
4. Reload the page: The birthdate is empty.

**Comment by antikalk** [comment]
This is most likely related to https://github.com/keycloak/keycloak/issues/22982

**Comment by antikalk** [comment]
> Yes, this looks like a duplicate of #22982. @antikalk could you try the latest [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly) and let us know if this issue was fixed already?

Just tried it out with the nightly. I am facing a different issue with that one: The form is not send at all due to a javascript error happening on form submit once I add a custom attribute to my realm: 
![image](https://github.com/keycloak/keycloak/assets/1793007/a9786838-9f01-4ab5-9850-2d3dc32e2f87)
In the network tab I see no request to the backend being made and there is no visible feedback at all.

Steps I did:

1. Create new Realm
2. Enable User Profile
3. Create new User -> works
4. Update user (e.g. firstName) ->  works
5. Go to User Profile settings and add a custom attribute, e.g. alias: 
```json
...
{
      "name": "alias",
      "displayName": "",
      "selector": {
        "scopes": [
          "acr",
          "address",
          "role_list",
          "roles",
          "web-origins",
          "profile",
          "phone",
          "microprofile-jwt",
          "email",
          "offline_access"
        ]
      },
      "permissions": {
        "edit": [
          "user",
          "admin"
        ],
        "view": [
          "user",
          "admin"
        ]
      },
      "annotations": {},
      "validations": {}
    }
...
```
(note that there is no validator configured)
6. Try to give the user an alias in the user details -> the javascript error occurs. It does not matter which field I edit or if I edit anything at all - the error occurs on submit regardless.

**Comment by ssilvert** [comment]
I think the problem described by the OP is at least related to https://github.com/keycloak/keycloak/issues/23327.

Assigning to @agagancarczyk

**Comment by edewit** [comment]
this will be fixed with #23537

**Comment by sebastianSchmidt86** [comment]
With the nightly build I now can view all already set user attributes, but on "Save" I get the following error:

```
UserProfileFields.tsx:29 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'errors')
    at ea (UserProfileFields.tsx:29:53)
    at z (EditUser.tsx:132:11)
    at index.esm.mjs:2147:19
```

**Comment by jonkoops** [comment]
@sebastianSchmidt86 we're aware of this problem and working on a fix.

**Comment by jonkoops** [comment]
This has been fixed in #23537
