### ISSUE TITLE
Document not found error when in NextJS with client-side component (NOT SSR)

### ISSUE THREAD

**Issue by moaazassali** [keycloak/keycloak#23494]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/javascript

### Describe the bug

I am creating a keycloak object imported from keycloak-js under keycloak.ts and doing export default keycloak. I then import this keycloak object into my main page in NextJS and try to just console.log() it within useEffect(). Both the keycloak.ts file and the page.tsx file under /app are marked with "use client", meaning that they are client-side components and not rendered with SSR. Not only that, but the keycloak object is being logged within useEffect() which only runs on the client side... Despite all of that, I am getting the following error when trying to log the object or really just use it for anything else. This error only appears on the NextJS terminal server-side and not the client-side.

```
⨯ node\_modules/keycloak-js/dist/keycloak.js (716:0) @ new Keycloak
⨯ ReferenceError: document is not defined
    at eval (./src/keycloak.ts:8:18)
    at (ssr)/./src/keycloak.ts (/<parent directory>/.next/server/app/page.js:195:1)
    at __webpack_require__ (/<parent directory>/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/page.tsx:10:67)
    at (ssr)/./src/app/page.tsx (/<parent directory>/.next/server/app/page.js:162:1)
    at __webpack_require__ (/<parent directory>/.next/server/webpack-runtime.js:33:43)
null
```
Some observations I made/tested:
- I exported a random test object under test.ts and logged it and that didn't cause any error, so this issue is specific to keycloak only.

- If I initialize the object also in the useEffect() and not export it from a separate file, I don't get this error, but I want it to be globally accessible so I need it in a separate file. I could assign it to a global state, but that's just a workaround and doesn't fix the real issue.

- The keycloak object is actually logged correctly on the client side, so it seems to be working, but I just get this document not found error in my NextJS terminal window.

### Version

22.0.3

### Expected behavior

I expect not to get this "document not found" error since I am using a client-side component.

### Actual behavior

I get "document not found" error whenever I use the keycloak object in any way including just logging it to the console on the client side.

### How to Reproduce?

1- Create NextJS project.
2- run `npm install keycloak-js`
3- Create a file called keycloak.ts with this code:
```
"use client";
import Keycloak from "keycloak-js";

const keycloak = new Keycloak({
  url: "http://localhost:8080",
  realm: "realm",
  clientId: "client-id",
});
export default keycloak;
```

4- Modify page.tsx directly under /app to this:
```
"use client";
import { useEffect } from "react";
import keycloak from "@/keycloak";

let initialized = false;

export default function Home() {
  useEffect(() => {
    if (!initialized) {
      console.log(keycloak);
      initialized = true;
    }
  }, []);

  return <main></main>;
}
```

**Comment by moaazassali** [comment]
It seems like NextJS loads all files on the server-side regardless as an "initial state" for the page, which then gets updated/hydrated with the reactivity like useState, useEffect and others. This per-rendering also seems to include any initial state. One solution I already mentioned is to initialize the keycloak instance within useEffect() but then we need to keep passing it as a prop to other pages. So, instead use a global state management library like zustand or redux. I am using redux and this is what worked for me:

```
import { create } from "zustand";
import Keycloak from "keycloak-js";

interface AuthStore {
  keycloak: Keycloak | null;
  initialized: boolean;
  initializeKeycloack: () => void;
}

const useAuthStore = create<AuthStore>((set) => ({
  keycloak: null,
  initialized: false,

  initializeKeycloack: () =>
    set((state) => {
      if (!state.initialized) {
        const keycloak = new Keycloak({
          url: "http://192.168.70.129:8080",
          realm: "recdeck",
          clientId: "frontend",
        });
        keycloak.init({});
        return { keycloak, initialized: true };
      }
      return {};
    }),
}));

export default useAuthStore;
```

Also, the initialized field is needed because you have to consider the case where the user starts at the main page, goes to another page then back to the main page. In that case, `useEffect()` will run again when the user is back to the main page, which will cause `keycloak.init()` to run again too, leading to the error "Keycloak instance can only be initialized once". So, we have to ensure that we don't run `keycloak.init()` again later using the initialized field.
