### ISSUE TITLE
Use theme.properties from jar file if config key is not present

### ISSUE THREAD

**Issue by arnold-maderthaner** [keycloak/keycloak#23530]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

If I use a login theme different to the default once included and provide my own theme.properites only this properties file is used. If I don't have all necessary keys inside my theme.properties then the login process might fail because the inbuilt FTL templates fail.

As Example if I dont have the kcWebAuthnKeyIcon setting in my theme.properties file then the login will fail with:

2023-09-26 13:31:36,735 SEVERE [freemarker.runtime] (executor-thread-24) Error executing FreeMarker template: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> properties.kcWebAuthnKeyIcon  [in template "webauthn-register.ftl" at line 8, column 24]

### Version

22.0.3

### Expected behavior

It would be great if it would fallback to the inbuilt theme.properties to not crash.

### Actual behavior

Following Exception is thrown:
```
 2023-09-26 13:31:36,735 SEVERE [freemarker.runtime] (executor-thread-24) Error executing FreeMarker template: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> properties.kcWebAuthnKeyIcon  [in template "webauthn-register.ftl" at line 8, column 24]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${properties.kcWebAuthnKeyIcon}  [in template "webauthn-register.ftl" at line 8, column 22]
        ~ Reached through: #nested "header"  [in template "template.ftl" in macro "registrationLayout" at line 74, column 40]
        ~ Reached through: @layout.registrationLayout; section  [in template "webauthn-register.ftl" at line 4, column 5]
----
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
        at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
        at freemarker.core.Environment.visit(Environment.java:335)
        at freemarker.core.Environment.visit(Environment.java:377)
        at freemarker.core.Environment.invokeNestedContent(Environment.java:621)
        at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)
        at freemarker.core.Environment.visit(Environment.java:335)
        at freemarker.core.Environment.visit(Environment.java:341)
        at freemarker.core.Environment.visit(Environment.java:377)
        at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)
        at freemarker.core.Environment.invokeMacro(Environment.java:813)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
        at freemarker.core.Environment.visit(Environment.java:335)
        at freemarker.core.Environment.visit(Environment.java:341)
        at freemarker.core.Environment.process(Environment.java:314)
        at freemarker.template.Template.process(Template.java:383)
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)
        at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.processTemplate(FreeMarkerLoginFormsProvider.java:549)
        at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createForm(FreeMarkerLoginFormsProvider.java:342)
        at org.keycloak.authentication.requiredactions.WebAuthnRegister.requiredActionChallenge(WebAuthnRegister.java:165)
        at org.keycloak.services.managers.AuthenticationManager.executeAction(AuthenticationManager.java:1334)
        at org.keycloak.services.managers.AuthenticationManager.lambda$executionActions$18(AuthenticationManager.java:1281)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.keycloak.services.managers.AuthenticationManager.executionActions(AuthenticationManager.java:1282)
        at org.keycloak.services.managers.AuthenticationManager.actionRequired(AuthenticationManager.java:1170)
        at org.keycloak.services.managers.AuthenticationManager.nextActionAfterAuthentication(AuthenticationManager.java:1017)
        at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:1069)
        at org.keycloak.services.resources.LoginActionsService.requiredActionGET(LoginActionsService.java:1051)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

provide own theme (fe login/theme.properties) without kcWebAuthnKeyIcon in theme.properties file

**Comment by pedroigor** [comment]
@ssilvert Not sure if we have plans to support this. Wdyt?

**Comment by brecht-vermeersch** [comment]
i have the same error when installing customized the login theme. It probably needs a default value so that it doesn't cause an error

**Comment by ssilvert** [comment]
@arnold-maderthaner @brecht-vermeersch If you just declare `parent=keycloak` in your theme.properties then it should inherit all the theme.properties settings from the keycloak theme and use those as the defaults.  

Does that help you?  
Or maybe for some reason that is not working for kcWebAuthnKeyIcon?

**Comment by brecht-vermeersch** [comment]
https://github.com/keycloak/keycloak/blob/60f80ce0c8fe3e72489422bb177992998021c40b/themes/src/main/resources/theme/base/login/webauthn-register.ftl#L8

<span class="${properties.kcWebAuthnKeyIcon}"></span>

to

<span class="${properties.kcWebAuthnKeyIcon!}"></span>

**Comment by ssilvert** [comment]
@brecht-vermeersch Thanks.  In that case, it's a bug and not an enhancement.
