### ISSUE TITLE
Unable to find org.keycloak.models.map.storage.jpa.authSession.entity.JpaRootAuthenticationSessionEntity with id

### ISSUE THREAD

**Issue by z0mb1ek** [keycloak/keycloak#23588]
### Before reporting an issue

- [X] I have searched existing issues

### Area

authentication

### Describe the bug

Hi. I see error in console:
```
2023-09-29 00:24:00,491 WARN  [org.keycloak.services] (executor-thread-37) KC-SERVICES0013: Failed authentication: org.keycloak.models.ModelException: jakarta.persistence.EntityNotFoundException: Unable to find org.keycloak.models.map.storage.jpa.authSession.entity.JpaRootAuthenticationSessionEntity with id 9e8d559f-54cc-45d0-9608-150e41988c9e
	at org.keycloak.models.map.storage.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:84)
	at org.keycloak.models.map.storage.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
	at jdk.proxy2/jdk.proxy2.$Proxy69.getReference(Unknown Source)
	at org.keycloak.models.map.storage.jpa.JpaMapStorage.delete(JpaMapStorage.java:265)
	at org.keycloak.models.map.authSession.MapRootAuthenticationSessionProvider.removeRootAuthenticationSession(MapRootAuthenticationSessionProvider.java:142)
	at org.keycloak.services.managers.AuthenticationSessionManager.removeAuthenticationSession(AuthenticationSessionManager.java:219)
	at org.keycloak.services.managers.AuthenticationSessionManager.removeTabIdInAuthenticationSession(AuthenticationSessionManager.java:236)
	at org.keycloak.protocol.oidc.OIDCLoginProtocol.sendError(OIDCLoginProtocol.java:332)
	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:131)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:356)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:226)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.access$300(AuthorizationEndpoint.java:71)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint$1.runInternal(AuthorizationEndpoint.java:143)
	at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:64)
	at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:41)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:413)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.processInRetriableTransaction(AuthorizationEndpoint.java:135)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:119)
	at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: jakarta.persistence.EntityNotFoundException: Unable to find org.keycloak.models.map.storage.jpa.authSession.entity.JpaRootAuthenticationSessionEntity with id 9e8d559f-54cc-45d0-9608-150e41988c9e
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder$JpaEntityNotFoundDelegate.handleEntityNotFound(FastBootEntityManagerFactoryBuilder.java:235)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.doGetReference(IdentifierLoadAccessImpl.java:148)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$getReference$0(IdentifierLoadAccessImpl.java:81)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:107)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.getReference(IdentifierLoadAccessImpl.java:81)
	at org.hibernate.internal.SessionImpl.getReference(SessionImpl.java:2512)
	at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.keycloak.models.map.storage.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:60)
	... 58 more

2023-09-29 00:24:00,495 WARN  [org.keycloak.events] (executor-thread-37) type=LOGIN_ERROR, realmId=21f53194-d044-4040-8e63-032c329a00a0, clientId=security-admin-console, userId=null, ipAddress=127.0.0.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=https://panel-dev.widdimo.ru/auth/admin/master/console/, code_id=9e8d559f-54cc-45d0-9608-150e41988c9e, response_mode=fragment
```

### Version

22.0.3-0

### Expected behavior

see login page

### Actual behavior

see error: `Unexpected error when handling authentication request to identity provider.`

### How to Reproduce?

- change SSO Session Idle to 2 minutes in master realm
- logout
- login
- close browser tab
- wait 2 minutes and 1 second
- go to /admin url

### Anything else?

I use latest CRDB version and flags:
```
KC_TRANSACTION_XA_ENABLED: "false"
KC_TRANSACTION_JTA_ENABLED: "false"
KC_STORAGE: jpa
```
docker image is **keycloak/keycloak:22.0.3-0**

If i don't close the browser tab and only try to use any ui tab all is ok and  keycloak send me redirect to login page. This bug is only with closing browser tab action

**Comment by z0mb1ek** [comment]
But if I delete KEYCLOAK_IDENTITY cookie it starts working

**Comment by z0mb1ek** [comment]
nightly build fix this trouble

**Comment by vramik** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), there is no longer plan to develope the Map Store, and it will be removed from Keycloak's code base. Follow https://github.com/keycloak/keycloak/issues/24111 for the removal steps.
