### ISSUE TITLE
[keycloak 22.0.3] keycloak cli export fail when cache enabled

### ISSUE THREAD

**Issue by CaptainKrby** [keycloak/keycloak#23595]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

I'm using Bitnami's chart, which pulls the Keycloak 22.0.3 version. 

I can't import/export with the kc.sh tool with the cache enabled because I'm getting a BindException: No available port to bind to in range [7800 .. 7800] error.

I have browsed issues referring to this same problem including this PR: [keycloak/keycloak#19645.](https://github.com/keycloak/keycloak/pull/19645)

### Version

22.0.3

### Expected behavior

Import and export with the infinispan cache active.

### Actual behavior

I have BindException :

````
keycloak@keycloak-valid-0:/opt/bitnami/keycloak/bin$ ./kc.sh export --dir=/var/tmp —realm=my-realm --users-per-file=100
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=keycloak-valid-headless.keycloak-valid.svc.k8s-valid.local
2023-09-22 07:59:04,199 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: https://keycloak-valid.corp.net/auth, Hostname: keycloak-valid.corp.net, Strict HTTPS: true, Path: /auth, Strict BackChannel: false, Admin URL: https://keycloak-valid.corp.net/auth, Admin: keycloak-valid.corp.net, Port: -1, Proxied: true
2023-09-22 07:59:06,578 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-09-22 07:59:07,603 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-09-22 07:59:07,769 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-09-22 07:59:08,095 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2023-09-22 07:59:08,098 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: ba17675f-dc75-4c95-8d11-319eaf9b8620, name: keycloak-valid-0-22723
2023-09-22 07:59:08,103 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheException: Unable to start JGroups Channel
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:622)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:489)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:84)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.BindException: No available port to bind to in range [7800 .. 7800]
        at org.jgroups.util.Util.bind(Util.java:4095)
        at org.jgroups.util.Util.createServerSocket(Util.java:4071)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:68)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:43)
        at org.jgroups.protocols.TCP.start(TCP.java:111)
        at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:905)
        at org.jgroups.JChannel.startStack(JChannel.java:921)
        at org.jgroups.JChannel._preConnect(JChannel.java:799)
        at org.jgroups.JChannel.connect(JChannel.java:322)
        at org.jgroups.JChannel.connect(JChannel.java:316)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:620)
        ... 28 more

2023-09-22 07:59:08,149 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2023-09-22 07:59:08,198 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: Unable to start JGroups Channel
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No available port to bind to in range [7800 .. 7800]
2023-09-22 07:59:08,199 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
````

### How to Reproduce?

````
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--hostname-strict-https=false"
  - "--import-realm »
 ````

**Comment by jruhe-adesso** [comment]
I can confirm the bug

```
bash-5.1$ /opt/keycloak/bin/kc.sh show-config
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=keycloak-infinispan
Current Mode: production
Current Configuration:
        kc.cache-stack =  kubernetes (PersistedConfigSource)
        kc.config.built =  true (SysPropConfigSource)
        kc.db =  oracle (KcEnvVarConfigSource)
        kc.db-password =  ******* (KcEnvVarConfigSource)
        kc.db-url =  jdbc:oracle:thin:@s-t0056-db.sys.xxx:2255:T0056 (KcEnvVarConfigSource)
        kc.db-username =  keycloak (KcEnvVarConfigSource)
        kc.db.password =  xxxx (KcEnvVarConfigSource)
        kc.db.url =  jdbc:oracle:thin:@s-t0056-db.sys.xxx:2255:T0056 (KcEnvVarConfigSource)
        kc.db.username =  keycloak (KcEnvVarConfigSource)
        kc.health-enabled =  true (PersistedConfigSource)
        kc.hostname =  gis-qs.xxx (KcEnvVarConfigSource)
        kc.http-relative-path =  /auth (PersistedConfigSource)
        kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-22.0.3.jar!/META-INF/keycloak.conf])
        kc.log-file =  ${kc.home.dir:default}${file.separator}data${file.separator}log${file.separator}keycloak.log (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-22.0.3.jar!/META-INF/keycloak.conf])
        kc.log-level =  INFO,org.keycloak.events:DEBUG (KcEnvVarConfigSource)
        kc.log.level =  INFO,org.keycloak.events:DEBUG (KcEnvVarConfigSource)
        kc.metrics-enabled =  true (PersistedConfigSource)
        kc.optimized =  true (PersistedConfigSource)
        kc.provider.file.keycloak-saml-attribute-mapper-22.0.3-1.1.jar.last-modified =  1695108185828 (PersistedConfigSource)
        kc.provider.file.offboarding-provider-22.0.3-1.1.jar.last-modified =  1695108185828 (PersistedConfigSource)
        kc.proxy =  edge (KcEnvVarConfigSource)
        kc.spi-map-storage-concurrenthashmap-dir =  ${kc.home.dir:default}${file.separator}data${file.separator}chm (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-22.0.3.jar!/META-INF/keycloak.conf])
        kc.spi-map-storage-concurrenthashmap-key-type-authz-resource-servers =  string (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-22.0.3.jar!/META-INF/keycloak.conf])
        kc.spi-map-storage-concurrenthashmap-key-type-realms =  string (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-22.0.3.jar!/META-INF/keycloak.conf])
        kc.spi-map-storage-concurrenthashmap-key-type-single-use-objects =  string (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-22.0.3.jar!/META-INF/keycloak.conf])
        kc.version =  22.0.3 (SysPropConfigSource)
		
		
bash-5.1$ /opt/keycloak/bin/kc.sh export --optimized --users different_files --users-per-file 100 --dir tmp
Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=keycloak-infinispan
2023-10-04 17:33:21,442 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: gis-qs.xxx, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2023-10-04 17:33:25,737 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-10-04 17:33:26,341 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-10-04 17:33:26,456 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-10-04 17:33:27,125 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2023-10-04 17:33:27,127 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 44ba9454-afab-4e1a-97dd-baf35ea90023, name: keycloak-70-d2675-16432
2023-10-04 17:33:27,130 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheException: Unable to start JGroups Channel
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:622)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:489)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:84)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.BindException: No available port to bind to in range [7800 .. 7800]
        at org.jgroups.util.Util.bind(Util.java:4095)
        at org.jgroups.util.Util.createServerSocket(Util.java:4071)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:68)
        at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:43)
        at org.jgroups.protocols.TCP.start(TCP.java:111)
        at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:905)
        at org.jgroups.JChannel.startStack(JChannel.java:921)
        at org.jgroups.JChannel._preConnect(JChannel.java:799)
        at org.jgroups.JChannel.connect(JChannel.java:322)
        at org.jgroups.JChannel.connect(JChannel.java:316)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:620)
        ... 28 more

2023-10-04 17:33:29,029 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2023-10-04 17:33:29,064 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2023-10-04 17:33:29,064 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
2023-10-04 17:33:29,064 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: Unable to start JGroups Channel
2023-10-04 17:33:29,065 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2023-10-04 17:33:29,065 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start JGroups Channel
2023-10-04 17:33:29,065 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No available port to bind to in range [7800 .. 7800]
2023-10-04 17:33:29,065 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
bash-5.1$
```

**Comment by jruhe-adesso** [comment]
No fix regarding this issue mentioned in release notes of 22.0.4.

**Comment by ahus1** [comment]
I seems that both reporters in this issue run the export on a pod that is already running Keycloak. The existing Keycloak conflicts with the new started instance which is try to export the data.

The two most straight-forwards ways to export data:

1. Run Keycloak for example as a Job in a new container and connect it to the same database
2. Run Keycloak outside of Kubernetes and still connect to the same database - this is assumed in the documentation provided in https://www.keycloak.org/server/importExport 

When doing so, and following the docs, those will not connect to Infinispan, as the default of `kc.cache` is set to `local`.

When running in the same container as Keycloak, you have the choice of disabling Infinispan by setting `kc.cache` to `local`.

That being said, the recommended approach to have a consistent export of a realm is to first shutdown Keycloak. I'm not sure if this works in your case. 

As a follow-up, I think we need to enhance the docs and probably also the handling of Keycloak in Kubernetes to create exports from the CLI.

**Comment by jruhe-adesso** [comment]
Thank you for your suggestions. Problem is, that my approach worked in 20.0.3 and is no longer working in 22.0.3. I must admit, that a lot has changed between 20.0.3 and 22.03 releases. I need some time to also figure out, what we have done to get 22.0.3 running.  

> When running in the same container as Keycloak, you have the choice of disabling Infinispan by setting kc.cache to local.

kc.cache is a build option and cannot be changed when running a second instance of an --optimized build.

**Comment by jruhe-adesso** [comment]
@ahus1 Thank you for your recommendations
In my opinion, the biggest deficit of Keycloak is the lack of the ability to update a realm gracefully (I don't have a solution either). I'm pretty sure that every serious project considers Realm as code (in git) that is the target of changes and these changes are tied to deployments. The problem now is that a deployment cannot automatically import a realm via _kc import_ without completely losing dynamic parts of the realm, users and groups. For our Keycloaks running in Openshift, we have therefore developed the following method in the form of a local bash script:
1. (the new realm was delivered with the deployment into the keycloak pods but not imported)
2. the script triggers _kc export_ on a keycloak pod
3. the exported realm (with users and service accounts) and the deployed realm (with service accounts) are downloaded
4. Groups and users of the exported realm are merged into the previously downloaded deployed realm
5. the merged realm (with users and service accounts) is uploaded to a Keycloak pod
6. _kc import_ is executed on the pod
7. Keycloak pods are restarted

I understand that I have to be disconnected from Infinispan during export in my case, but what exactly do you mean by your comment "the recommended approach to have a consistent export of a realm is to first shutdown Keycloak"? What can happen if exported from running, cached instances?"

**Comment by ahus1** [comment]
Hi @jruhe-adesso - with export and import from the command line there could be the following problems when things happen while Keycloak is still running: 

* When export while Keycloak is running, there are different modes of exporting. In one of those this is that users are exported in chunks. Those chunks are exported in separate transactions. Modifying Keycloak's user base during that time will give you an inconsistent export. This might not be a problem in your scenario, though.

* When you run an import an the Keycloak is not connected to the Infinispan cluster, the import will fail to invalidate cached data in the other running Keycloak instances, and you'll see old data in the UI and when logging in. So I recommend to either shut down Keycloak when running an import from the command line, or configure it in a way that the import connects to Infinispan. If you choose to configure it to join the other Keycloak Pod in Infinispan, it will become a full member of that cluster and some state will be replicated to that new node. This will put some stress on the existing nodes both when the node joins and when it leaves as the contents of the cache rebalance. So this is again not something I would recommend.

Reading my description above and your procedure, if you want to stay with it, I recommend running this in a separate Pod one-off Pod not run additional workloads in a Keycloak pod. A Kubernetes Job might be the right thing for that.  

Looking at the procedure itself, there might be different options to achieve what you did there: Keycloak has a REST API where you can do a partial import to an existing realm. This happens at runtime, no additional Pods need to be started, and caches are invalidated as expected. 

See below for a screenshot where to find it on the Realm tab in the upper right menu.

![image](https://github.com/keycloak/keycloak/assets/3957921/3220b28c-f0a2-4867-93bf-75a083acaf81)

It has a best effort to create and update existing entities. It will never remove entities. Please give it a try if this functionality is sufficient for you.

If the number of entities is limited, you might instead use the Keycloak CLI to delete and re-create or update the entities in a scripted way, which also uses Keycloak's REST API.

If you are looking at a as-code approach for incremental updates, have a look at the Keycloak Terraform provider which is community maintained and also uses Keycloak REST API.

**Comment by ahus1** [comment]
I'm now closing this issue as it degressed quite a lot from the original topic. 

The answer to the original question is: 

* To use the CLI export/import, shutdown Keycloak first, and use separate Pod for this, not the regular Keycloak pod
* To export/import at runtime, consider the Keycloak's REST APIs for partial import, the REST APIs for the different entities, or the community provides Terraform provider.

**Comment by jruhe-adesso** [comment]
Thank you for your input!
