### ISSUE TITLE
r.map is not a function when trying to associate the 11th client role to a user

### ISSUE THREAD

**Issue by juienpro** [keycloak/keycloak#23688]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the admin UI, when I try to associate a newly created Client Role to a user, I am not able to go to the next page or to change the display to show the first 20 client roles. A search is not working too. 

Instead, the message "r.map is not a function" appears.

https://github.com/keycloak/keycloak/assets/121452426/78e071c4-cc74-4fa6-a81e-ef541f463a19

Sometimes, the `r.Map is not a function` message appears directly when we switch from "filterByRoles" to "filterByClients".

https://github.com/keycloak/keycloak/assets/121452426/2d858563-96c6-4014-a156-d3cdb0058de9

Browsers tested: Firefox & Chromium

**Server Logs**

```
2023-10-04 08:28:29,837 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-191) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RoleModel.getId()" because "role" is null
	at org.keycloak.models.cache.infinispan.UserAdapter.hasRole(UserAdapter.java:357)
	at org.keycloak.services.resources.admin.permissions.RolePermissions.checkAdminRoles(RolePermissions.java:245)
	at org.keycloak.services.resources.admin.permissions.RolePermissions.canMapRole(RolePermissions.java:292)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
```

### Version

22.0.3

### Expected behavior

The client roles should be displayed.

### Actual behavior

r.map is not a function message.

### How to Reproduce?

- Docker install
- Create a new realm / new client / new user
- Create a new client role
- Associate this client role to the user

### Anything else?

Seems partly linked to #23404 and #21010

However my installation is nearly fresh, with very few data (one realm, one client, one additional client role, 2 user accounts).

Note: I didn't try the nighty build yet, sorry for that. Feel free to let me know if this would be relevant.

**Comment by ssilvert** [comment]
@juienpro This is working fine for me with recent code.  I can see that there is something else wrong in that your message bundles are not getting applied.  That's why all the labels in the UI are just camelCase keys.

You definitely shouldn't be getting a NullPointerException on the back end with such a simple setup.

You mentioned the other two issues, which have to do with a setup that has thousands of clients.  You don't have thousands of clients, right?

**Comment by jonkoops** [comment]
I see a lot of HTTP errors in the console there, it seems like the requests are getting blocked. Perhaps you are running a proxy or some other network layer that is preventing this traffic from coming through?

**Comment by ssilvert** [comment]
@juienpro I'm going to close this one.  We can reopen if you have additional information.

**Comment by jonkoops** [comment]
Closing due to lack of activity.
