### ISSUE TITLE
Docker image does not start with ispn cache

### ISSUE THREAD

**Issue by fschick** [keycloak/keycloak#23747]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

Docker container doesn't start when cache is set to `ispn`. Neither in production (`start`) nor in dev mode (`start-dev --cache=ispn`)

### Version

22.0.4

### Expected behavior

The docker container starts without exception.

### Actual behavior

The following exception is thrown.
```
Updating the configuration and installing your custom providers, if any. Please wait.
2023-10-05 14:53:12,372 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 8230ms
2023-10-05 14:53:13,453 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2023-10-05 14:53:14,709 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-10-05 14:53:15,253 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-10-05 14:53:15,341 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-10-05 14:53:15,447 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-10-05 14:53:15,513 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2023-10-05 14:53:15,515 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 5d3ac6ca-55d6-462f-b516-e582714a6865, name: e7c98a287233-31410
2023-10-05 14:53:15,519 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2023-10-05 14:53:15,519 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
2023-10-05 14:53:15,519 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2023-10-05 14:53:15,519 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
2023-10-05 14:53:15,524 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.17922
2023-10-05 14:53:15,556 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [3b0474093733-18091|47] (2) [3b0474093733-18091, e7c98a287233-31410]
2023-10-05 14:53:15,595 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `e7c98a287233-31410`, physical addresses are `[172.17.0.13:33458]`
2023-10-05 14:53:15,615 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-10-05 14:53:15,820 ERROR [org.infinispan.CLUSTER] (jgroups-9,e7c98a287233-31410) ISPN000475: Error processing response for request 2 from 3b0474093733-18091: java.io.EOFException
        at org.infinispan.marshall.core.AbstractBytesObjectInput.checkPosLength(AbstractBytesObjectInput.java:261)
        at org.infinispan.marshall.core.AbstractBytesObjectInput.readByte(AbstractBytesObjectInput.java:107)
        at org.infinispan.commons.marshall.MarshallUtil.unmarshallSize(MarshallUtil.java:426)
        at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:271)
        at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
        at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:86)
        at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:70)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
        at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
        at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
        at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
        at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
        at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1571)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1479)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1681)
        at org.jgroups.JChannel.up(JChannel.java:733)
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:936)
        at org.jgroups.protocols.FRAG2.up(FRAG2.java:139)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
        at org.jgroups.protocols.pbcast.GMS.up(GMS.java:845)
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:226)
        at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1083)
        at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:822)
        at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:804)
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:453)
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:680)
        at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
        at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
        at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:188)
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
        at org.jgroups.protocols.Discovery.up(Discovery.java:294)
        at org.jgroups.stack.Protocol.up(Protocol.java:340)
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1184)
        at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:107)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-10-05 14:53:16,516 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
```

### How to Reproduce?

Run 
```
docker run --rm -e KC_CACHE=ispn quay.io/keycloak/keycloak:nightly start-dev
```

Docker host:
```
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye
```

Docker version:
```
Docker version 24.0.6, build ed223bc
```

### Anything else?

Seems to be the root cause for #23542.

**Comment by fschick** [comment]
What do you mean with "You seem to have multiple nodes running"? It's a Hyper-V with Debian 11 and docker installed. I'll try to reproduce it with a fresh Debian installation.

**Comment by fschick** [comment]
I'm also unable to reproduce the issue with a fresh install of Debian / Docker. Can you give me a hint where the information "You seem to have multiple nodes running" is coming from?

**Comment by fschick** [comment]
OK, tried out. With "node" you mean a "container" in docker, right? In my head, docker containers are independent from each other. Not sure, what's going on... At least, no issue if unsupported.

**Comment by sschu** [comment]
When you launch multiple Keycloak instances/containers, they form an Infinispan cluster. I called one cluster member node.
That line in your log `2023-10-05 14:53:15,556 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [3b0474093733-18091|47] (2) [3b0474093733-18091, e7c98a287233-31410]` indicated there are multiple nodes in your cluster.

**Comment by fschick** [comment]
Thank you. It's clear now.
