### ISSUE TITLE
Compiling on Mac Errors with :java: java.lang.ClassNotFoundException: org.keycloak.models.map.processor.GenerateEntityImplementationsProcessor

### ISSUE THREAD

**Issue by anandlingaraj** [keycloak/keycloak#23806]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Compiling Nightly 
java: java.lang.ClassNotFoundException: org.keycloak.models.map.processor.GenerateEntityImplementationsProcessor

java: java.lang.ClassNotFoundException: org.keycloak.models.map.processor.GenerateEntityImplementationsProcessor
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.keycloak.models.map.processor.GenerateEntityImplementationsProcessor
	at org.jetbrains.jps.javac.JavacMain.lookupAnnotationProcessors(JavacMain.java:327)
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:231)
	at org.jetbrains.jps.javac.ExternalJavacProcess.compile(ExternalJavacProcess.java:195)
	at org.jetbrains.jps.javac.ExternalJavacProcess.access$400(ExternalJavacProcess.java:30)
	at org.jetbrains.jps.javac.ExternalJavacProcess$CompilationRequestsHandler$1.run(ExternalJavacProcess.java:268)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: org.keycloak.models.map.processor.GenerateEntityImplementationsProcessor
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.jetbrains.jps.javac.LazyClassLoader.findClass(LazyClassLoader.java:58)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.jetbrains.jps.javac.JavacMain.lookupAnnotationProcessors(JavacMain.java:309)
	... 7 more

### Version

22.0.4

### Expected behavior

Unable to compile

### Actual behavior

error compiling

### How to Reproduce?

Donwload and compile in Mac Intel x86, Ventura 13.6

**Comment by sschu** [comment]
I cannot test on X86 mac but on ARM M2 it works.

**Comment by douglaspalmer** [comment]
What command are you using to compile?

**Comment by douglaspalmer** [comment]
Works for me on Intel Core i5 with Ventura and on Apple M2 Pro with Sonoma. I would guess that your problem lies with your Java version. Both of my machines are running OpenJDK 17. Try switching java versions and running `mvn clean install -DskipTests`
