### ISSUE TITLE
Keycloak Operator fails to install realm authentication flow because "flow is null"

### ISSUE THREAD

**Issue by ildrummer** [keycloak/keycloak#23980]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

I am using the Keycloak Operator to install a realm with authentication flows.  The Realm Import manifest uses the format specified by the [Realm CRDs](https://www.keycloak.org/operator/installation#_installing_by_using_kubectl_without_operator_lifecycle_manager) and values pulled from an export of a realm with hand-configured authentication flows.  When the realm import pod created by the Operator runs, it fails on the following error:
`ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Cannot invoke "org.keycloak.models.AuthenticationFlowModel.getId()" because "flow" is null`

This result is consistent regardless of what type of authentication flow I try to create and whether I attempt to create one or multiple flows or flow executions.

### Version

Discovered on 21.1.2, consistent on 22.0.4

### Expected behavior

The Keycloak Operator should install the realm without any errors in the logs.  Upon accessing the Keycloak Administrator Console, the realm Authentication page should display the desired Authentication flow with details available in subsequent pages.

### Actual behavior

The kubernetes cluster reports the realm installation pod failing:
```
$ kubectl -n keycloak get pods   
NAME                                     READY   STATUS      RESTARTS   AGE
keycloak-0                                                1/1     Running     0          10m
keycloak-operator-5b7c596f49-8hj4l       1/1     Running     0          19m
keycloak-postgres-1                                 1/1     Running     0          12m
keycloak-realm-0-test-realm-96r9j           0/1     Error       0          10m
keycloak-realm-0-test-realm-cfhxv           0/1     Error       0          9m55s
```

The pod logs show an internal null-pointer-style error.

```
$ k logs -f pod/keycloak-realm-2-conflict-w6v4z
Defaulted container "keycloak" out of: keycloak, wait-for-db (init)
Updating the configuration and installing your custom providers, if any. Please wait.
2023-10-13 17:21:45,552 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 24123ms
Server configuration updated and persisted. Run the following command to review the configuration:

        kc.sh show-config

2023-10-13 17:21:48,535 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2023-10-13 17:21:53,252 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-10-13 17:21:54,740 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-10-13 17:21:54,932 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-10-13 17:21:55,216 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-10-13 17:21:57,029 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2023-10-13 17:21:57,035 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-10-13 17:22:00,614 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml
2023-10-13 17:22:01,533 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_751571, Site name: null
2023-10-13 17:22:05,539 INFO  [org.keycloak.exportimport.singlefile.SingleFileImportProvider] (main) Full importing from file /mnt/realm-import/test-realm.json
2023-10-13 17:22:06,332 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2023-10-13 17:22:06,339 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Cannot invoke "org.keycloak.models.AuthenticationFlowModel.getId()" because "flow" is null
2023-10-13 17:22:06,339 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### How to Reproduce?

Here is the realm manifest that is installed (with Helm) at the same time as the Keycloak server.
```
---
# Source: keycloak/templates/realms.yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: keycloak-realm-2-conflict
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    enabled: true
    realm: test-realm
    displayName: Test Realm
    
    authenticationFlows:
      - alias: X.509 browser
        description: Browser-based authentication
        providerId: basic-flow
        topLevel: true
        builtIn: false
        authenticationExecutions:
          - requirement: ALTERNATIVE
            priority: 10
            authenticator: auth-cookie
            authenticatorFlow: false
            autheticatorFlow: false
            userSetupAllowed: false
```

When I manually create this authentication flow and export the realm config, every piece is consistent between my Helm chart-generated manifest and the exported config apart from the ID.
```
{
      "id": "bda9d9a9-89f0-4c76-99f3-86028e861d08",
      "alias": "X.509 Browser",
      "description": "X.509 certificate browser authentication",
      "providerId": "basic-flow",
      "topLevel": true,
      "builtIn": false,
      "authenticationExecutions": [
        {
          "authenticator": "auth-cookie",
          "authenticatorFlow": false,
          "requirement": "ALTERNATIVE",
          "priority": 0,
          "autheticatorFlow": false,
          "userSetupAllowed": false
        }
      ]
    },
```

### Anything else?

Without the `authenticationFlows` field, the realm installs just fine.  This is the only major Keycloak realm configuration item I've found that does not install.

This may be related to https://github.com/keycloak/keycloak/issues/17443.

**Comment by vmuzikar** [comment]
@shawkins Could you please triage this? Might be a REST API issue.

**Comment by shawkins** [comment]
@vmuzikar @ildrummer sorry for the delay in replying.  This does not appear to be an operator issue as it can be reproduced directly against the keycloak server.  

The underlying exception (seen with --verbose) on main is:

```
java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticationFlowModel.getId()" because "flow" is null
        at org.keycloak.models.utils.KeycloakModelUtils.deepFindAuthenticationExecutions(KeycloakModelUtils.java:594)
        at org.keycloak.models.utils.DefaultAuthenticationFlows.firstBrokerLoginFlow(DefaultAuthenticationFlows.java:609)
        at org.keycloak.storage.datastore.LegacyExportImportManager.importAuthenticationFlows(LegacyExportImportManager.java:1357)
        at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:312)
```

Looking backwards through the logic it's expecting a browserFlow to be explicitly set on the realm, or for a flow to exist with the alias of browser.  If neither exist a null is being passed into deepFindAuthenticationExecutions.

Moving over to the store team to further diagnose if a validation is needed or some other logic adjustment.

**Comment by ildrummer** [comment]
Thank you for doing that deep dive to find the root issue. I will play around with the two alternatives you mentioned and follow up with solutions that work until this issue is complete.

**Comment by ildrummer** [comment]
@shawkins I just got a chance to test an authentication flow named "browser".  That allowed the realm to install but causes runtime server issues.

```
2023-12-01 15:23:58,017 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticationFlowModel.getAlias()" because "f" is null
        at org.keycloak.admin.ui.rest.model.AuthenticationMapper.lambda$convertToModel$2(AuthenticationMapper.java:43)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.keycloak.admin.ui.rest.model.AuthenticationMapper.convertToModel(AuthenticationMapper.java:43)
        at org.keycloak.admin.ui.rest.AuthenticationManagementResource.lambda$listIdentityProviders$1(AuthenticationManagementResource.java:66)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.keycloak.admin.ui.rest.AuthenticationManagementResource.listIdentityProviders(AuthenticationManagementResource.java:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

![image](https://github.com/keycloak/keycloak/assets/67486026/79a6395a-bbf5-4532-a494-d9501cfe3a96)


Going to investigate the `browserFlow` setting next.

**Comment by ildrummer** [comment]
Same result when I provide a value for `browserFlow` to the operator.
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  ...
spec:
  keycloakCRName: keycloak
  realm:
    ...
    authenticationFlows:
    - alias: browser-x.509
      authenticationExecutions:
      - authenticator: auth-cookie
        authenticatorFlow: false
        autheticatorFlow: false
        priority: 10
        requirement: ALTERNATIVE
        userSetupAllowed: false
      builtIn: false
      description: Browser-based X.509 authentication
      providerId: basic-flow
      topLevel: true
    browserFlow: browser-x.509
```

I get the same result when the signle authentication flow is named `browser` rather than `browser-x.509` and `browserFlow: browser` is set.

**Comment by ildrummer** [comment]
Yes, I've been trying that without success.  Just re-tested after carefully looking at a realm export and the only settings in the export were `browserFlow` and the authentication flows array.  

I think we've stalled out until the store team has a chance to investigate.

**Comment by jcputney** [comment]
We're running into this issue as well, is there any update on a fix?

**Comment by Romain7495** [comment]
Same issue, runing keycloak `24.0.1`

**Comment by shawkins** [comment]
@Romain7495 can you provide the full stacktraces? The f is null seems to match what was already seen here.

The getGroups NPE could be the same as what was supposed to be addressed by https://github.com/keycloak/keycloak/issues/25183 - however that was rereported by another user on that issue as well, so it probably needs reopened or a new issue created. cc @pedroigor

**Comment by Romain7495** [comment]
@shawkins thanks for your reply, I will deep dive into your issue link.

I have created https://github.com/keycloak/keycloak/issues/27611 to explain more whith screenshots.

here is the full stacktrace 
```
2024-03-06 16:48:30,684 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-17) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticationFlowModel.getAlias()" because "f" is null
	at org.keycloak.admin.ui.rest.model.AuthenticationMapper.lambda$convertToModel$1(AuthenticationMapper.java:46)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.admin.ui.rest.model.AuthenticationMapper.convertToModel(AuthenticationMapper.java:46)
	at org.keycloak.admin.ui.rest.AuthenticationManagementResource.lambda$listIdentityProviders$1(AuthenticationManagementResource.java:58)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.admin.ui.rest.AuthenticationManagementResource.listIdentityProviders(AuthenticationManagementResource.java:59)
	at org.keycloak.admin.ui.rest.AuthenticationManagementResource$quarkusrestinvoker$listIdentityProviders_da866ba3c00c15b6bcfefe4cfabdb4f2f2dbe255.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
	```

**Comment by shawkins** [comment]
I've opened a pr to address the NPEs and in general what appear to be the root problem when starting from an import.

We'll see what the other devs think about what's the best way to address NPEs with existing realms.

> I have created https://github.com/keycloak/keycloak/issues/27611 to explain more whith screenshots.

Thanks That one may end up representing the need to still fix getGroups NPE.

**Comment by ReneZeidler** [comment]
I encountered the same issue on a test instance and figured out the root cause.

I've previously used nightly versions on this test instance, which disables database migrations by setting the `migration_model.VERSION` to `999.0.0` (you can check your database for this value). This is of course expected, because automatic migrations between nightly versions are not a supported scenario, and you're on your own if you try to reuse the same database between different nightly versions.

In this case, the migration to 24.0.0 that did not run binds the first broker login flow to each realm. https://github.com/keycloak/keycloak/blob/e40227fa50dfdd34f1c413858a81138819324e2f/model/storage-private/src/main/java/org/keycloak/migration/migrators/MigrateTo24_0_0.java#L110-L120
Manually running this migration fixes the NPE.

**Comment by bilias** [comment]
I also have a nightly VERSION on my production MIGRATION_MODEL.
How did you manually run the migrations;

```
+-------+---------+-------------+
| ID    | VERSION | UPDATE_TIME |
+-------+---------+-------------+
| c1u7t | 20.0.1  |  1669633706 |
| nbat7 | 20.0.3  |  1673592544 |
| xh4ug | 999.0.0 |  1674467665 |
| yi2n6 | 20.0.2  |  1670944365 |
+-------+---------+-------------+
```

**Comment by ReneZeidler** [comment]
> How did you manually run the migrations?

Stop Keycloak, remove the 999.0.0 row from the migration_model table. Then, when you start Keycloak, it will run all migrations between the last entry in the table (20.0.3 in your case) and the installed version.

Since this might break things, be sure to make a backup of your database before doing this.

**Comment by Romain7495** [comment]
@bilias @ReneZeidler you can find the `24.0.1` release note here: https://github.com/keycloak/keycloak/blob/release/24.0/docs/documentation/release_notes/topics/24_0_1.adoc
