### ISSUE TITLE
Flaky test: org.keycloak.testsuite.cli.registration.KcRegTest#testNoArgs

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#24010]
## org.keycloak.testsuite.cli.registration.KcRegTest#testNoArgs
[Keycloak CI - Base IT (4)](https://github.com/keycloak/keycloak/actions/runs/6531006458/job/17731851380) / [Pull Request #24005](https://github.com/keycloak/keycloak/pull/24005)

```
org.junit.ComparisonFailure: stdout one but last line expected:<[Use 'kcreg.sh help <command>' for more information about a given command.]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.keycloak.testsuite.cli.registration.KcRegTest.testNoArgs(KcRegTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
...
```

**Comment by stianst** [comment]
Closing since this hasn't happened for quite some time.
