### ISSUE TITLE
Unable to locate entity descriptor: org.keycloak.examples.domainextension.jpa.Company

### ISSUE THREAD

**Issue by fateson** [keycloak/keycloak#24144]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

 examples/providers/domain-extension run error 
Unable to locate entity descriptor: org.keycloak.examples.domainextension.jpa.Company

### Version

22.04

### Expected behavior

success

### Actual behavior

Caused by: org.hibernate.UnknownEntityTypeException: Unable to locate entity descriptor: org.keycloak.examples.domainextension.jpa.Company
        at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.getEntityDescriptor(MappingMetamodelImpl.java:437)
        at org.hibernate.internal.SessionImpl.requireEntityPersister(SessionImpl.java:2276)
        at org.hibernate.internal.SessionImpl.byId(SessionImpl.java:1173)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2403)
        ... 51 more

### How to Reproduce?

step：
1: copy domain-extension-example.jar to providers 
2：run  dist/bin  kc.sh  start-dev
3:   GET http://localhost:8080/realms/master/example/companies/10086

**Comment by tmq77** [comment]
Do U check your maven dependency package whether or not support jdk17 ? i have the same problem when i use the caffeine cache, and i upgrade the ver to 3.x, it is working
