### ISSUE TITLE
emf is null when fetching realms in providerFactory

### ISSUE THREAD

**Issue by RobKenis** [keycloak/keycloak#24351]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

We have built a custom ProviderFactory which is loaded at Keycloak startup. In the `postInit` method, we invoke following code

```
@Override
    public void postInit(KeycloakSessionFactory factory) {
        try {
            LOGGER.info("Fetching master realm");
            KeycloakModelUtils.runJobInRetriableTransaction(factory, session -> {
                RealmModel masterRealm = session.realms().getRealmByName(MASTER_REALM);
                if (masterRealm == null) {
                    LOGGER.warn("Master realm not found");
                    return null;
                }
}, MAX_RETRIES, RETRY_DELAY);
        } catch (Exception e) {
            LOGGER.error("Failed to fetch master realm", e);
        }
```

Sometimes we notice following error

```
2023-10-27 10:16:39,560 ERROR [c.t.k.spi.admin.impl.SetAdminCredentialsProviderFactoryImpl] (main) Failed to set admin credentials: java.lang.NullPointerException: Cannot invoke "javax.persistence.EntityManagerFactory.createEntityManager(javax.persistence.SynchronizationType)" because "emf" is null
    at org.keycloak.quarkus.runtime.storage.database.jpa.AbstractJpaConnectionProviderFactory.createEntityManager(AbstractJpaConnectionProviderFactory.java:107)
    at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.create(LegacyJpaConnectionProviderFactory.java:81)
    at org.keycloak.quarkus.runtime.storage.legacy.database.LegacyJpaConnectionProviderFactory.create(LegacyJpaConnectionProviderFactory.java:65)
    at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:271)
    at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:64)
    at org.keycloak.models.jpa.JpaRealmProviderFactory.create(JpaRealmProviderFactory.java:40)
    at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:271)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmDelegate(RealmCacheSession.java:153)
    at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:454)
    at c.t.k.spi.admin.impl.SetAdminCredentialsProviderFactoryImpl.lambda$postInit$0(SetAdminCredentialsProviderFactoryImpl.java:50)
    at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:299)
    at c.t.k.spi.admin.impl.SetAdminCredentialsProviderFactoryImpl.postInit(SetAdminCredentialsProviderFactoryImpl.java:49)
    at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:105)
    at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.createSessionFactory(QuarkusKeycloakApplication.java:41)
    at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:124)
    at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver.onStartupEvent(QuarkusLifecycleObserver.java:37)
    at org.keycloak.quarkus.runtime.integration.QuarkusLifecycleObserver_Observer_onStartupEvent_b0e82415b143738dc1f986a5fa4668e83d0a5dea.notify(Unknown Source)
    at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
    at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
    at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
    at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
    at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
    at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
    at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
    at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
    at io.quarkus.runtime.Application.start(Application.java:101)
    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
    at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:102)
    at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:82)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

### Version

21.0.1

### Expected behavior

The EMF is initialized before invoking the `postInit` method on my ProviderFactory

### Actual behavior

The EMF is null when invoking my `postInit` method

### How to Reproduce?

Create a class that implements `import org.keycloak.provider.ProviderFactory;` and use the code snippet above in the `postInit` method.

Final values are set to the following values
```
    private static final String MASTER_REALM = "master";

    private static final int MAX_RETRIES = 5;
    private static final int RETRY_DELAY = 2000;
```

**Comment by martin-kanis** [comment]
@RobKenis Thanks for the report. `21.0.1` is quite old and there were some changes in `AbstractJpaConnectionProviderFactory`. Can you please try if you still have this problem in the latest Keycloak?

**Comment by martin-kanis** [comment]
Closing as outdated. Feel free to reopen if this still occurs in the newest Keycloak release.
