### ISSUE TITLE
Flaky test: org.keycloak.testsuite.forms.RegisterTest#registerUserSuccessTermsAcceptance

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#24407]
## org.keycloak.testsuite.forms.RegisterTest#registerUserSuccessTermsAcceptance
[Keycloak CI - Forms IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/6698770221/job/18202064961) / [Pull Request #24225](https://github.com/keycloak/keycloak/pull/24225)

```
java.lang.IllegalArgumentException: No enum constant org.keycloak.testsuite.pages.AppPage.RequestType.
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.keycloak.testsuite.pages.AppPage$RequestType.valueOf(AppPage.java:60)
	at org.keycloak.testsuite.pages.AppPage.getRequestType(AppPage.java:49)
	at jdk.internal.reflect.GeneratedMethodAccessor558.invoke(Unknown Source)
...
```

**Comment by stianst** [comment]
Closing since this hasn't happened for quite some time.
