### ISSUE TITLE
NPE when logging in with TransientUser

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#24455]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

I've create a github identity provider with TransientUser feature turned on, when I log in I get a NPE

### Version

nightly

### Expected behavior

Be able to log in

### Actual behavior

```
2023-11-01 10:13:46,639 WARN  [org.keycloak.events] (executor-thread-17) type=IDENTITY_PROVIDER_FIRST_LOGIN_ERROR, realmId=d050a7ed-3e03-43f1-8bb0-f490c1faded3, clientId=security-admin-console, userId=null, ipAddress=0:0:0:0:0:0:0:1, error=invalid_user_credentials, identity_provider=github, auth_method=openid-connect, redirect_uri=http://localhost:8180/admin/test/console/, identity_provider_identity=edewit, code_id=2b7313b4-3c06-41db-aac8-39cd7b3019e6
2023-11-01 10:13:46,644 WARN  [org.keycloak.events] (executor-thread-17) type=IDENTITY_PROVIDER_FIRST_LOGIN_ERROR, realmId=d050a7ed-3e03-43f1-8bb0-f490c1faded3, clientId=security-admin-console, userId=null, ipAddress=0:0:0:0:0:0:0:1, error=invalid_user_credentials, identity_provider=github, auth_method=openid-connect, redirect_uri=http://localhost:8180/admin/test/console/, identity_provider_identity=edewit, code_id=2b7313b4-3c06-41db-aac8-39cd7b3019e6, authSessionParentId=2b7313b4-3c06-41db-aac8-39cd7b3019e6, authSessionTabId=Nw4zmz5TRyc
2023-11-01 10:14:01,790 WARN  [org.keycloak.services] (executor-thread-14) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "id" is null
	at org.keycloak.models.light.LightweightUserAdapter.<init>(LightweightUserAdapter.java:84)
	at org.keycloak.authentication.authenticators.broker.IdpCreateUserIfUniqueAuthenticator.authenticateImpl(IdpCreateUserIfUniqueAuthenticator.java:78)
	at org.keycloak.authentication.authenticators.broker.AbstractIdpAuthenticator.authenticate(AbstractIdpAuthenticator.java:76)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:445)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:271)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:380)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:249)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1037)
	at org.keycloak.services.resources.LoginActionsService$2.authenticateOnly(LoginActionsService.java:877)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:894)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:383)
	at org.keycloak.services.resources.LoginActionsService.brokerLoginFlow(LoginActionsService.java:907)
	at org.keycloak.services.resources.LoginActionsService.firstBrokerLoginGet(LoginActionsService.java:792)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$firstBrokerLoginGet_7740895ae1600a88809add5c32d725c3dfcd8338.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Create a github identity provider enable Transient User feature set "Do not store users" to true and login with this identity provider

**Comment by hmlnarik** [comment]
Confirmed. This works for Keycloak identity provider but does not for github.

**Comment by sankarequiwiz** [comment]
ddd
