### ISSUE TITLE
NullPointerException when key is not available in the database

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#24485]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When there is a key component without `privateKey` available in the database, there might be NullPointerException thrown when listing keys of the particular realm.

I was able to reproduce this just by manually removing some `privateKey` from the DB. So steps like:
- Create realm
- Run manually some SQL command similar to this in your DB:
```
delete from COMPONENT_CONFIG where NAME='privateKey' and COMPONENT_ID='59b6ecde-03a0-42e7-9b0f-39b5bda3b2e0'; # Replace with proper component ID, which refers to some key in your realm
```
- Login to admin console, go to your realm and list keys. There is exception like this in server.log:
```
java.lang.NullPointerException: Cannot invoke "java.security.Key.getEncoded()" because "key" is null
	at org.keycloak.common.util.KeyUtils.createKeyId(KeyUtils.java:78)
	at org.keycloak.keys.AbstractRsaKeyProvider.createKeyWrapper(AbstractRsaKeyProvider.java:78)
	at org.keycloak.keys.AbstractRsaKeyProvider.createKeyWrapper(AbstractRsaKeyProvider.java:68)
	at org.keycloak.keys.ImportedRsaKeyProvider.loadKey(ImportedRsaKeyProvider.java:54)
	at org.keycloak.keys.AbstractRsaKeyProvider.<init>(AbstractRsaKeyProvider.java:55)
	at org.keycloak.keys.ImportedRsaKeyProvider.<init>(ImportedRsaKeyProvider.java:38)
	at org.keycloak.keys.GeneratedRsaKeyProviderFactory.create(GeneratedRsaKeyProviderFactory.java:46)
	at org.keycloak.keys.DefaultKeyManager.lambda$getProviders$10(DefaultKeyManager.java:259)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.keys.DefaultKeyManager.getProviders(DefaultKeyManager.java:268)
	at org.keycloak.keys.DefaultKeyManager.getKeysStream(DefaultKeyManager.java:149)
	at org.keycloak.services.resources.admin.KeyResource.getKeyMetadata(KeyResource.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
```

This issue is just about improve error handling a bit, so instead of NullPointerException, we have some more meaningful exception message in the server.log (possibly displaying the affected realm, the affected key provider from the realm with some info about it etc). Also with instructions that admin should probably manually fix or delete the particular key in the particular realm.

### Version

nightly

### Expected behavior

Better exception message in server.log

### Actual behavior

NullPointerException in server.log

### How to Reproduce?

See above. It is corner case, but it is proved to happened for some deployments...

**Comment by mposolda** [comment]
Adding to 24 for now, but we can eventually postpone...

**Comment by mposolda** [comment]
@douglaspalmer Could you please look at this when you have some free cycles? It is not very clear how to reproduce/test this. But probably it can be tested by creating component in the DB and somehow remove the `privateKey` property from this key component.
