### ISSUE TITLE
Flakey operator tests in ClusteringTest

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#24550]
### Description

testKeycloakCacheIsConnected and testKeycloakScaleAsExpected will occasionally fail.  See https://github.com/keycloak/keycloak/actions/runs/6755081352/job/18363279296

The underlying issue seems to be a timing issue with liquibase, which cases a keycloak pod to crash loop:

```
WARN: example-kc-0 failed to become ready ---
2023-11-04T13:40:29.1808418Z conditions:
2023-11-04T13:40:29.1809039Z - lastTransitionTime: "2023-11-04T13:31:07Z"
2023-11-04T13:40:29.1809740Z   status: "True"
2023-11-04T13:40:29.1810352Z   type: "Initialized"
2023-11-04T13:40:29.1811035Z - lastTransitionTime: "2023-11-04T13:31:07Z"
2023-11-04T13:40:29.1811850Z   message: "containers with unready status: [keycloak]"
2023-11-04T13:40:29.1812643Z   reason: "ContainersNotReady"
2023-11-04T13:40:29.1813228Z   status: "False"
2023-11-04T13:40:29.1813695Z   type: "Ready"
2023-11-04T13:40:29.1814316Z - lastTransitionTime: "2023-11-04T13:31:07Z"
2023-11-04T13:40:29.1815140Z   message: "containers with unready status: [keycloak]"
2023-11-04T13:40:29.1815926Z   reason: "ContainersNotReady"
2023-11-04T13:40:29.1816490Z   status: "False"
2023-11-04T13:40:29.1816994Z   type: "ContainersReady"
2023-11-04T13:40:29.1817733Z - lastTransitionTime: "2023-11-04T13:31:07Z"
2023-11-04T13:40:29.1818402Z   status: "True"
2023-11-04T13:40:29.1818969Z   type: "PodScheduled"
2023-11-04T13:40:29.1819496Z containerStatuses:
2023-11-04T13:40:29.1820615Z - containerID: "docker://71e867358cff474ae356c5e3f6c6e358eaf8120367db94b0096d2ed2f96c93f3"
2023-11-04T13:40:29.1821791Z   image: "custom-keycloak:0.0.1-0dcc84"
2023-11-04T13:40:29.1823762Z   imageID: "docker://sha256:c9e2ea9b206276d617b66bdb7db55f8c61f70edd064b01e5e0bf833ca6384bc4"
2023-11-04T13:40:29.1824890Z   lastState:
2023-11-04T13:40:29.1825334Z     terminated:
2023-11-04T13:40:29.1826273Z       containerID: "docker://71e867358cff474ae356c5e3f6c6e358eaf8120367db94b0096d2ed2f96c93f3"
2023-11-04T13:40:29.1827526Z       exitCode: 1
2023-11-04T13:40:29.1828168Z       finishedAt: "2023-11-04T13:39:39Z"
2023-11-04T13:40:29.1828794Z       reason: "Error"
2023-11-04T13:40:29.1829392Z       startedAt: "2023-11-04T13:39:16Z"
2023-11-04T13:40:29.1830028Z   name: "keycloak"
2023-11-04T13:40:29.1830513Z   ready: false
2023-11-04T13:40:29.1830968Z   restartCount: 6
2023-11-04T13:40:29.1831451Z   started: false
2023-11-04T13:40:29.1832341Z   state:
2023-11-04T13:40:29.1832747Z     waiting:
2023-11-04T13:40:29.1834593Z       message: "back-off 5m0s restarting failed container=keycloak pod=example-kc-0_keycloak-test-60f136cf-61f5-4d47-984b-e329c62d9689(d5b8ba25-a810-418f-b91a-b67c6e4e1b4e)"
2023-11-04T13:40:29.1836397Z       reason: "CrashLoopBackOff"
2023-11-04T13:40:29.1837003Z hostIP: "192.168.49.2"
2023-11-04T13:40:29.1837497Z phase: "Running"
2023-11-04T13:40:29.1837973Z podIP: "10.244.0.10"
2023-11-04T13:40:29.1838456Z podIPs:
2023-11-04T13:40:29.1838918Z - ip: "10.244.0.10"
2023-11-04T13:40:29.1839416Z qosClass: "BestEffort"
2023-11-04T13:40:29.1840012Z startTime: "2023-11-04T13:31:07Z"
2023-11-04T13:40:29.1840458Z 
2023-11-04T13:40:29.1841933Z Nov 04, 2023 1:40:29 PM org.keycloak.operator.testsuite.integration.BaseOperatorTest logFailed
2023-11-04T13:40:29.1843838Z WARN: example-kc-0 not ready log: at liquibase.Liquibase.update(Liquibase.java:215)
2023-11-04T13:40:29.1845199Z 	at liquibase.Liquibase.update(Liquibase.java:197)
2023-11-04T13:40:29.1846308Z 	at liquibase.Liquibase.update(Liquibase.java:183)
2023-11-04T13:40:29.1848383Z 	at org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider.updateChangeSet(QuarkusJpaUpdaterProvider.java:192)
2023-11-04T13:40:29.1851591Z 	at org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:107)
2023-11-04T13:40:29.1853342Z 	... 41 more
2023-11-04T13:40:29.1860250Z Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final::mhajas@redhat.com:
2023-11-04T13:40:29.1864284Z      Reason: liquibase.exception.DatabaseException: ERROR: relation "resource_uris" already exists [Failed SQL: (0) CREATE TABLE public.RESOURCE_URIS (RESOURCE_ID VARCHAR(36) NOT NULL, VALUE VARCHAR(255) NOT NULL)]
2023-11-04T13:40:29.1867226Z 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:122)
2023-11-04T13:40:29.1869248Z 	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:87)
2023-11-04T13:40:29.1870876Z 	at liquibase.Scope.lambda$child$0(Scope.java:197)
2023-11-04T13:40:29.1871913Z 	at liquibase.Scope.child(Scope.java:206)
2023-11-04T13:40:29.1872883Z 	at liquibase.Scope.child(Scope.java:196)
2023-11-04T13:40:29.1873715Z 	at liquibase.Scope.child(Scope.java:175)
2023-11-04T13:40:29.1925631Z 	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:86)
2023-11-04T13:40:29.1927655Z 	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:102)
2023-11-04T13:40:29.1976239Z 	at liquibase.command.CommandScope.execute(CommandScope.java:213)
2023-11-04T13:40:29.1977325Z 	... 52 more
2023-11-04T13:40:29.1981830Z Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final::mhajas@redhat.com:
2023-11-04T13:40:29.1986537Z      Reason: liquibase.exception.DatabaseException: ERROR: relation "resource_uris" already exists [Failed SQL: (0) CREATE TABLE public.RESOURCE_URIS (RESOURCE_ID VARCHAR(36) NOT NULL, VALUE VARCHAR(255) NOT NULL)]
2023-11-04T13:40:29.1989111Z 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:768)
2023-11-04T13:40:29.2083467Z 	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:120)
2023-11-04T13:40:29.2085362Z 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:70)
2023-11-04T13:40:29.2087022Z 	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:110)
2023-11-04T13:40:29.2088762Z 	at liquibase.Scope.lambda$child$0(Scope.java:197)
2023-11-04T13:40:29.2089682Z 	at liquibase.Scope.child(Scope.java:206)
2023-11-04T13:40:29.2090632Z 	at liquibase.Scope.child(Scope.java:196)
2023-11-04T13:40:29.2091580Z 	at liquibase.Scope.child(Scope.java:175)
2023-11-04T13:40:29.2092672Z 	at liquibase.Scope.child(Scope.java:263)
2023-11-04T13:40:29.2094580Z 	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:100)
2023-11-04T13:40:29.2096382Z 	at liquibase.Scope.lambda$child$0(Scope.java:197)
2023-11-04T13:40:29.2097605Z 	at liquibase.Scope.child(Scope.java:206)
2023-11-04T13:40:29.2098826Z 	at liquibase.Scope.child(Scope.java:196)
2023-11-04T13:40:29.2100863Z 	at liquibase.Scope.child(Scope.java:175)
2023-11-04T13:40:29.2102105Z 	at liquibase.Scope.child(Scope.java:263)
2023-11-04T13:40:29.2103330Z 	at liquibase.Scope.child(Scope.java:267)
2023-11-04T13:40:29.2105952Z 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:74)
2023-11-04T13:40:29.2107089Z 	... 60 more
2023-11-04T13:40:29.2180467Z Caused by: liquibase.exception.DatabaseException: ERROR: relation "resource_uris" already exists [Failed SQL: (0) CREATE TABLE public.RESOURCE_URIS (RESOURCE_ID VARCHAR(36) NOT NULL, VALUE VARCHAR(255) NOT NULL)]
2023-11-04T13:40:29.2183357Z 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:467)
2023-11-04T13:40:29.2203339Z 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
2023-11-04T13:40:29.2204698Z 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:180)
2023-11-04T13:40:29.2206612Z 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1291)
2023-11-04T13:40:29.2208324Z 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1273)
2023-11-04T13:40:29.2209736Z 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:728)
2023-11-04T13:40:29.2210578Z 	... 76 more
2023-11-04T13:40:29.2211646Z Caused by: org.postgresql.util.PSQLException: ERROR: relation "resource_uris" already exists
2023-11-04T13:40:29.2213584Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
2023-11-04T13:40:29.2215337Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
2023-11-04T13:40:29.2216912Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
2023-11-04T13:40:29.2218353Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
2023-11-04T13:40:29.2219627Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
2023-11-04T13:40:29.2220893Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
2023-11-04T13:40:29.2222261Z 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
2023-11-04T13:40:29.2223622Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
2023-11-04T13:40:29.2224885Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
2023-11-04T13:40:29.2226218Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-11-04T13:40:29.2261481Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-11-04T13:40:29.2263535Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-11-04T13:40:29.2265151Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-11-04T13:40:29.2266519Z 	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
2023-11-04T13:40:29.2268041Z 	at jdk.proxy2/jdk.proxy2.$Proxy74.execute(Unknown Source)
2023-11-04T13:40:29.2269267Z 	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
2023-11-04T13:40:29.2271495Z 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:461)
2023-11-04T13:40:29.2272780Z 	... 81 more
```

This is occurring often enough to warrant further investigation.

cc @vmuzikar @keycloak/store

**Comment by shawkins** [comment]
My guess at what is happening here - testKeycloakCacheIsConnected immediately scales the cluster to three instances once it is ready.  However the readiness check does not take into acount an on-going migration, so it's certainly possible that the next scaled up pod is competing in some way with the current one - I'm not sure what locking or even xa transaction should be applicable here.  

Once the state of the migration has been corrupted, since the database is shared with all tests in the class, subsequent tests like testKeycloakScaleAsExpected fail as well.

@keycloak/store can someone on the team confirm what is supposed to happen if another keycloak process is started during a migration?

**Comment by vramik** [comment]
Thanks @shawkins.

> @keycloak/store can someone on the team confirm what is supposed to happen if another keycloak process is started during a migration?

AFAIU once one keycloak node succesfuly obtains a lock here: https://github.com/keycloak/keycloak/blob/6750b05d24c76d3bbb3985e923f4d3f9ae9021f4/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java#L145 and starts a migration, then other nodes should not be able to start another migration process till the lock is not released. Not sure what is actually causing the issue.

**Comment by shawkins** [comment]
@vramik thank you for the pointer.  Let me do some debugging around that locally and see if anything jumps out.

**Comment by shawkins** [comment]
@vramik I couldn't recreate the situation locally with a few attempts, and debugging seemed to show the expected flow.  A potentially relevent issue is https://github.com/liquibase/liquibase/issues/1755 - it looks like in some situations already liquibase will re-run migrations even when it's not needed.  That one is referencing an upgrade scenario that shouldn't apply there though.

I'll just leave things as-is at this point with the operator tests and update this issue when there are further occurances.

**Comment by shawkins** [comment]
Based upon the investigation into #35261 we know that the pod will not be ready while a migration is running.
