### ISSUE TITLE
Keycloak cannot find templates from base theme, if overriding messages

### ISSUE THREAD

**Issue by savv** [keycloak/keycloak#24598]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

I followed the instructions [here](https://www.keycloak.org/docs/latest/server_development/#emails) to override some of the email messages.

Unfortunately, after selecting `mytheme` and trying to send an email, I get the following error: `2023-11-07 10:42:48,706 ERROR [org.keycloak.services] (executor-thread-19) KC-SERVICES0026: Failed to send password reset email: org.keycloak.email.EmailException: Failed to template email`

### Version

22.0.5

### Expected behavior

I expected to receive an email with my overridden messages.

### Actual behavior

Error / stack trace:
```
2023-11-07 10:42:48,706 ERROR [org.keycloak.services] (executor-thread-19) KC-SERVICES0026: Failed to send password reset email: org.keycloak.email.EmailException: Failed to template email
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:242)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:257)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:252)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:206)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendPasswordReset(FreeMarkerEmailTemplateProvider.java:117)
	at org.keycloak.authentication.authenticators.resetcred.ResetCredentialEmail.authenticate(ResetCredentialEmail.java:101)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:445)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:249)
	at org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:179)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:157)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:986)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:378)
	at org.keycloak.services.resources.LoginActionsService.processResetCredentials(LoginActionsService.java:717)
	at org.keycloak.services.resources.LoginActionsService.resetCredentials(LoginActionsService.java:507)
	at org.keycloak.services.resources.LoginActionsService.resetCredentialsPOST(LoginActionsService.java:423)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to Reproduce?

Follow the instructions here: https://www.keycloak.org/docs/latest/server_development/#emails

E.g. with Docker, by creating a file `/opt/keycloak/themes/mytheme/email/messages/messages_en.properties`, and adding the following contents:

```
passwordResetSubject=My password recovery
passwordResetBody=Reset password link: {0}
passwordResetBodyHtml=<a href="{0}">Reset password</a>
```

### Anything else?

This is happening with keycloak X. According to this thread, this was fixed, but perhaps not for the email templates:

https://keycloak.discourse.group/t/ftl-templates-in-theme-resources-templates-not-loading-in-keycloak-x/13484

**Comment by rmartinc** [comment]
I have deployed a `mytheme.jar` (following the instructions in the documentation) in my keycloak `providers` folder, and the email for credentials reset shows the modified email. My changes:

```
jar tvf ../mytheme.jar 
     0 Tue Nov 07 12:50:48 CET 2023 META-INF/
    61 Tue Nov 07 12:50:48 CET 2023 META-INF/MANIFEST.MF
    85 Tue Nov 07 12:37:56 CET 2023 META-INF/keycloak-themes.json
     0 Tue Nov 07 12:38:08 CET 2023 theme/
     0 Tue Nov 07 12:38:08 CET 2023 theme/mytheme/
     0 Tue Nov 07 12:39:32 CET 2023 theme/mytheme/email/
     0 Tue Nov 07 12:50:46 CET 2023 theme/mytheme/email/messages/
  6193 Tue Nov 07 12:50:46 CET 2023 theme/mytheme/email/messages/messages_en.properties
    12 Tue Nov 07 12:39:32 CET 2023 theme/mytheme/email/theme.properties

cat META-INF/keycloak-themes.json 
{
    "themes": [{
        "name" : "mytheme",
        "types": [ "email" ]
    }]
}
cat theme/mytheme/email/theme.properties
parent=base
```

And the [messages_en.properties](https://github.com/keycloak/keycloak/blob/22.0.5/themes/src/main/resources/theme/base/email/messages/messages_en.properties) is the default one in keycloak changing the `executeActions*` texts.

Can you please test with a similar jar?

**Comment by savv** [comment]
I had forgotten theme.properties. My apologies.
