### ISSUE TITLE
LDAP integration with MTLS is not working

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#24674]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Hi Team, 
We are trying to integrate LDAP in MTLS mode and were not able to successfully integrate it. Every time we enable startTLS button, the communication fails. When tried with the LDAP search query using the same certs integrated with keycloak, the query returns the data. Also, we implemented a Java client to query LDAP using the same certs, it's working fine.
So we tried to check open-source GitHub discussions and stories but looks like there is no success anywhere.

Errors:
654b4791 conn=13302 fd=12 ACCEPT from IP=IP:PORT (IP=0.0.0.0:PORT)
TLS: can't accept: A TLS fatal alert has been received..
654b4792 conn=13302 fd=12 closed (TLS negotiation failure)

"level":"ERR","log":{"message":"{\"host\":\"ckey1-ckey-0\",\"version\":\"1.1\",\"short_message\":\"KC-SERVICES0055: Error when authenticating to LDAP: LDAP connection has been closed\",\"full_message\":\"KC-SERVICES0055: Error when authenticating to LDAP: LDAP connection has been closed\",\"timestamp\":1.699466713409E9,\"level\":3,\"facility\":\"keycloak\",\"_LoggerName\":\"org.keycloak.services\",\"_SourceSimpleClassName\":\"LDAPServerCapabilitiesManager\",\"_StackTrace\":\"javax.naming.NamingException: LDAP connection has been closed\\n\\tat java.naming/com.sun.jndi.ldap.LdapRequest.getReplyBer(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.Connection.readReply(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapClient.ldapBind(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapClient.authenticate(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapCtx.connect(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapCtx.<init>(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(Unknown Source)\\n\\tat java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(Unknown Source)\\n\\tat java.naming/javax.naming.spi.NamingManager.getInitialContext(Unknown Source)\\n\\tat java.naming/javax.naming.InitialContext.getDefaultInitCtx(Unknown Source)\\n\\tat java.naming/javax.naming.InitialContext.init(Unknown Source)\\n\\tat java.naming/javax.naming.ldap.InitialLdapContext.<init>(Unknown Source)\\n\\tat org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)\\n\\tat org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)\\n\\tat org.keycloak.services.managers.LDAPServerCapabilitiesManager.testLDAP(LDAPServerCapabilitiesManager.java:139)\\n\\tat org.keycloak.services.resources.admin.TestLdapConnectionResource.testLDAPConnection(TestLdapConnectionResource.java:93)\\n\\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\\n\\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\\n\\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\\n\\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\\n\\tat org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)\\n\\tat org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)\\n\\tat org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)\

### Version

12.0.x

### Expected behavior

LDAP with MTLS communication should work successfully.

### Actual behavior

Keycloak should communicate with LDAP in MTLS mode successfully.

### How to Reproduce?

Integrate LDAP with keycloak in MTLS mode.

**Comment by pravsjv** [comment]
We have even tried with latest version, but no success. Is there any specific guide that can be followed for this integration or do you suggest any steps to follow.

**Comment by HaritSharma16** [comment]
Is there any test case already running in the keycloak test regression covering MTLS communication of LDAP and KEYCLOAK, If yes then please attach a reference to that test case.

**Comment by HaritSharma16** [comment]
We have tested the same LDAP server with few sample java programs, as given below:

import java.util.Hashtable;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.NamingException;
import javax.naming.directory.DirContext;
import javax.naming.directory.InitialDirContext;
public class LDAPClient {
    public static void main(String[] args) {
        // Enable JNDI and JSSE logging
        Logger logger = Logger.getLogger("");
        ConsoleHandler consoleHandler = new ConsoleHandler();
        consoleHandler.setLevel(Level.ALL);
        consoleHandler.setFormatter(new java.util.logging.SimpleFormatter());
        logger.addHandler(consoleHandler);
        logger.setLevel(Level.ALL);
        String ldapUrl = "ldaps://10.91.103.222:30288";
        String bindDN = "cn=admin,dc=example,dc=org";
        String bindPassword = "Not@SecurePassw0rd";

        System.setProperty("javax.net.ssl.keyStore", "/home/cloud-user/ldap_mtls/keystore.jks");
        System.setProperty("javax.net.ssl.keyStorePassword", "testing");
        System.setProperty("javax.net.ssl.trustStore", "/home/cloud-user/ldap_mtls/truststore.jks");
        System.setProperty("javax.net.ssl.trustStorePassword", "testing");

        Hashtable<String, String> env = new Hashtable<>();
        env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
        env.put(Context.PROVIDER_URL, ldapUrl);
        env.put(Context.SECURITY_AUTHENTICATION, "simple");
        env.put(Context.SECURITY_PRINCIPAL, bindDN);
        env.put(Context.SECURITY_CREDENTIALS, bindPassword);

        try {
            DirContext context = new InitialDirContext(env);
            System.out.println("LDAP Connection Successful");
            context.close();
        } catch (NamingException e) {
            System.err.println("LDAP Connection Failed: " + e.getMessage());
        }
    }
}

We saw the connection was successful and corresponding log at ldap server side is as below:

65a903a9 conn=1002 fd=12 ACCEPT from IP=172.16.100.13:62652 (IP=0.0.0.0:636)
65a903aa conn=1002 fd=12 TLS established tls_ssf=256 ssf=256
65a903aa conn=1002 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
65a903aa conn=1002 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
65a903aa conn=1002 op=0 RESULT tag=97 err=0 text=
65a903aa conn=1002 op=1 UNBIND

Then we tried to create a new user with following program:

import javax.naming.NameAlreadyBoundException;
import java.util.Hashtable;
import javax.naming.Context;
import javax.naming.NamingException;
import javax.naming.directory.*;

public class LdapCreateUser {
    public static void main(String[] args) {
        String ldapUrl = "ldaps://10.91.103.222:30288";
        String bindDN = "cn=admin,dc=example,dc=org";
        String bindPassword = "Not@SecurePassw0rd";

        System.setProperty("javax.net.ssl.keyStore", "/home/cloud-user/ldap_mtls/keystore.jks");
        System.setProperty("javax.net.ssl.keyStorePassword", "testing");
        System.setProperty("javax.net.ssl.trustStore", "/home/cloud-user/ldap_mtls/truststore.jks");
        System.setProperty("javax.net.ssl.trustStorePassword", "testing");

        Hashtable<String, String> env = new Hashtable<>();
        env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
        env.put(Context.PROVIDER_URL, ldapUrl);
        env.put(Context.SECURITY_AUTHENTICATION, "simple");
        env.put(Context.SECURITY_PRINCIPAL, bindDN);
        env.put(Context.SECURITY_CREDENTIALS, bindPassword);

        try {
            DirContext context = new InitialDirContext(env);

            // Create the organizational unit (OU) for users if it doesn't exist
            Attributes ouAttrs = new BasicAttributes();
            ouAttrs.put("objectClass", "organizationalUnit");
            ouAttrs.put("ou", "users");

            try {
                context.createSubcontext("ou=users,dc=example,dc=org", ouAttrs);
                System.out.println("Organizational unit 'ou=users' created successfully.");
            } catch (NameAlreadyBoundException e) {
                System.out.println("Organizational unit 'ou=users' already exists.");
            }

            // Create attributes for the new user
            Attributes userAttrs = new BasicAttributes();
            userAttrs.put(new BasicAttribute("objectclass", "inetOrgPerson"));
            userAttrs.put(new BasicAttribute("cn", "John Doe"));
            userAttrs.put(new BasicAttribute("sn", "Doe"));
            userAttrs.put(new BasicAttribute("givenName", "John"));
            userAttrs.put(new BasicAttribute("uid", "jdoe"));
            userAttrs.put(new BasicAttribute("userPassword", "password123"));

            // Specify the DN for the new user entry
            String newUserDN = "uid=jdoe,ou=users,dc=example,dc=org";

            // Add the new user entry to the directory
            context.createSubcontext(newUserDN, userAttrs);

            System.out.println("User created successfully.");

            context.close();
        } catch (NamingException e) {
            System.err.println("LDAP Operation Failed: " + e.getMessage());
        }
    }
}

We got a successful output and following log at ldap server side:

65a903ba conn=1007 fd=12 ACCEPT from IP=172.16.100.13:12906 (IP=0.0.0.0:636)
65a903ba conn=1007 fd=12 TLS established tls_ssf=256 ssf=256
65a903ba conn=1007 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
65a903ba conn=1007 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
65a903ba conn=1007 op=0 RESULT tag=97 err=0 text=
65a903ba conn=1007 op=1 ADD dn="ou=users,dc=example,dc=org"
65a903ba conn=1007 op=1 RESULT tag=105 err=0 text=
65a903ba conn=1007 op=2 ADD dn="uid=jdoe,ou=users,dc=example,dc=org"
65a903ba conn=1007 op=2 RESULT tag=105 err=0 text=

then we tried to query the same user which is created using below program:

import javax.naming.NamingException;
import javax.naming.NameAlreadyBoundException;
import java.util.Hashtable;
import javax.naming.Context;
import javax.naming.NamingEnumeration;
import javax.naming.directory.*;

public class LdapQueryUser {
    public static void main(String[] args) {
        String ldapUrl = "ldaps://10.91.103.222:30288";
        String bindDN = "cn=admin,dc=example,dc=org";
        String bindPassword = "Not@SecurePassw0rd";

        System.setProperty("javax.net.ssl.keyStore", "/home/cloud-user/ldap_mtls/keystore.jks");
        System.setProperty("javax.net.ssl.keyStorePassword", "testing");
        System.setProperty("javax.net.ssl.trustStore", "/home/cloud-user/ldap_mtls/truststore.jks");
        System.setProperty("javax.net.ssl.trustStorePassword", "testing");

        Hashtable<String, String> env = new Hashtable<>();
        env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
        env.put(Context.PROVIDER_URL, ldapUrl);
        env.put(Context.SECURITY_AUTHENTICATION, "simple");
        env.put(Context.SECURITY_PRINCIPAL, bindDN);
        env.put(Context.SECURITY_CREDENTIALS, bindPassword);

        try {
            DirContext context = new InitialDirContext(env);

            // Specify the search base and filter
            String searchBase = "ou=users,dc=example,dc=org";
            String searchFilter = "(uid=jdoe)";

            // Specify the search controls
            SearchControls searchControls = new SearchControls();
            searchControls.setSearchScope(SearchControls.SUBTREE_SCOPE);

            // Perform the search
            NamingEnumeration<SearchResult> results = context.search(searchBase, searchFilter, searchControls);

            // Iterate through the search results
            while (results.hasMore()) {
                SearchResult result = results.next();
                Attributes attributes = result.getAttributes();
                System.out.println("User found:");
                System.out.println("CN: " + attributes.get("cn").get());
                System.out.println("SN: " + attributes.get("sn").get());
                System.out.println("GivenName: " + attributes.get("givenName").get());
                // Add other attributes as needed
            }

            context.close();
        } catch (NamingException e) {
            System.err.println("LDAP Operation Failed: " + e.getMessage());
        }
    }
}



Again we got succesful output:

[root@tc0056node02 ldap_mtls]# java LdapQueryUser
User found:
CN: John Doe
SN: Doe
GivenName: John


And following are the log at ldap server side:

65a903c4 conn=1010 fd=12 ACCEPT from IP=172.16.100.13:29819 (IP=0.0.0.0:636)
65a903c4 conn=1010 fd=12 TLS established tls_ssf=256 ssf=256
65a903c4 conn=1010 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
65a903c4 conn=1010 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
65a903c4 conn=1010 op=0 RESULT tag=97 err=0 text=
65a903c4 conn=1010 op=1 SRCH base="ou=users,dc=example,dc=org" scope=2 deref=3 filter="(uid=jdoe)"
65a903c4 conn=1010 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
65a903c4 conn=1010 op=2 UNBIND

Where as from keycloak when we add a ldap provider in user federation, test connection button works but when i do test connection it throws following error:

2024-01-18 11:33:44,620 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager] (executor-thread-5) Creating LdapContext using properties: [{java.naming.security.authentication=simple, java.naming.security.principal=cn=admin,dc=example,dc=org, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.ldap.factory.socket=org.keycloak.truststore.SSLSocketFactory, java.naming.security.credentials=**************************************, java.naming.provider.url=ldaps://10.91.103.222:30288}]
2024-01-18 11:33:44,671 ERROR [org.keycloak.services] (executor-thread-5) KC-SERVICES0055: Error when authenticating to LDAP: LDAP connection has been closed: javax.naming.NamingException: LDAP connection has been closed
        at java.naming/com.sun.jndi.ldap.LdapRequest.getReplyBer(Unknown Source)
        at java.naming/com.sun.jndi.ldap.Connection.readReply(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapClient.ldapBind(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapClient.authenticate(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapCtx.connect(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(Unknown Source)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(Unknown Source)
        at java.naming/javax.naming.spi.NamingManager.getInitialContext(Unknown Source)
        at java.naming/javax.naming.InitialContext.getDefaultInitCtx(Unknown Source)
        at java.naming/javax.naming.InitialContext.init(Unknown Source)
        at java.naming/javax.naming.ldap.InitialLdapContext.<init>(Unknown Source)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
        at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
        at org.keycloak.services.managers.LDAPServerCapabilitiesManager.testLDAP(LDAPServerCapabilitiesManager.java:139)
        at org.keycloak.services.resources.admin.TestLdapConnectionResource.testLDAPConnection(TestLdapConnectionResource.java:93)
        at org.keycloak.services.resources.admin.TestLdapConnectionResource$quarkusrestinvoker$testLDAPConnection_53600405a1d6ba020ad8536bd54994b827f01e74.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2024-01-18 11:33:44,672 DEBUG [org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext] (executor-thread-5) Restarting handler chain for exception exception: org.keycloak.services.ErrorResponseException: HTTP 500 Internal Server Error
        at org.keycloak.services.ErrorResponse.error(ErrorResponse.java:43)
        at org.keycloak.services.ErrorResponse.error(ErrorResponse.java:36)
        at org.keycloak.services.resources.admin.TestLdapConnectionResource.testLDAPConnection(TestLdapConnectionResource.java:97)
        at org.keycloak.services.resources.admin.TestLdapConnectionResource$quarkusrestinvoker$testLDAPConnection_53600405a1d6ba020ad8536bd54994b827f01e74.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2024-01-18 11:33:44,672 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-5) JtaTransactionWrapper rollback

where are at ldap server side logs are as below:

65a90dfe conn=1620 fd=12 ACCEPT from IP=172.16.100.13:12056 (IP=0.0.0.0:636)
TLS: can't accept: Certificate is required..
65a90dfe conn=1620 fd=12 closed (TLS negotiation failure)
65a90e01 conn=1621 fd=12 ACCEPT from IP=172.16.100.13:63628 (IP=0.0.0.0:636)
TLS: can't accept: Certificate is required..
65a90e01 conn=1621 fd=12 closed (TLS negotiation failure)
65a90e02 conn=1622 fd=12 ACCEPT from IP=172.16.100.13:31857 (IP=0.0.0.0:636)
TLS: can't accept: Certificate is required..
65a90e02 conn=1622 fd=12 closed (TLS negotiation failure)
65a90e06 conn=1623 fd=12 ACCEPT from IP=172.16.100.16:36158 (IP=0.0.0.0:389)
65a90e06 conn=1624 fd=14 ACCEPT from IP=172.16.100.16:36156 (IP=0.0.0.0:389)


So from above analysis we see KEYCLOAK<->LDAP mtls communication is failing where as other side samplejavaApp<->ldap mtls communication is success.

**Comment by pravsjv** [comment]
@pedroigor Can you please help us here if you have any insight into this As well the Issue is marked as closed(couldn't reopen), but still we are not able to successfully integrate LDAP with MTLS.

**Comment by tiborauer** [comment]
Any update on integrating LDAP with mTLS?
