### ISSUE TITLE
Keycloak build broken when opening code in vscode/eclipse due to `maven-replacer-plugin` not executed correctly

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#24782]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The Javascript build uses `maven-replacer-plugin` to search & replace strings in HTML resources ([link](https://github.com/search?q=repo%3Akeycloak%2Fkeycloak%20maven-replacer-plugin&type=code)).

This plugin is not executed as part of normal maven lifecycle when building the code in vscode or Eclipse. The files created by this plugin will be missing from build output and Keycloak will fail to run.

For more information see [here](https://eclipse.dev/m2e/documentation/m2e-execution-not-covered.html). M2Eclipse project is the maven implementation for both Eclipse and [JDT Language Server](https://github.com/eclipse-jdtls/eclipse.jdt.ls) used by [vscode-java](https://github.com/redhat-developer/vscode-java).

### Version

main

### Expected behavior

It should be possible to open project in vscode/eclipse and run the app in debugger.

### Actual behavior

When opening the project in vscode/Eclipse, the plugin is left unexecuted. Some Keycloak UI related files will be missing from the build. Keycloak fails to run.

### How to Reproduce?

1. Compile the code initially on command line `mvn clean install -DskipTests`
2. Open the project in vscode (or Eclipse). I wait for vscode-java to compile the workspace.
3. Try to run the project either via [IDELauncher](https://github.com/keycloak/keycloak/blob/main/quarkus/README.md#running-from-your-ide) class or [quarkus:dev mode](https://github.com/keycloak/keycloak/blob/main/quarkus/README.md#contributing) via command line 
4. Observe it fails to run 
 
Following error is printed

```
2023-11-08 16:47:42,745 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)
        at org.keycloak.services.resources.admin.AdminConsole.getMainPage(AdminConsole.java:352)
        at org.keycloak.services.resources.admin.AdminConsole$quarkusrestinvoker$getMainPage_d508fd32a638b899af4d52f90082abf4f245fdb3.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@774f875a.
        at freemarker.template.Configuration.getTemplate(Configuration.java:2957)
        at freemarker.template.Configuration.getTemplate(Configuration.java:2777)
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.getTemplate(DefaultFreeMarkerProvider.java:66)
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:45)
        ... 12 more
```

This is because `maven-replacer-plugin` was not run. It would have produced this file.

### Anything else?

Some possible solutions:

(a) One alternative is to replace the plugin with something compatible with Eclipse project's maven implementation. The `maven-replacer-plugin` is [outdated](https://repo1.maven.org/maven2/com/google/code/maven-replacer-plugin/maven-replacer-plugin/). It has not been maintained for ~10 years. This is the [archived home page](https://code.google.com/archive/p/maven-replacer-plugin/) for the project at google code (note that it was the old code hosting service at google, but the plugin was not developed by Google).

(b) Another alternative could be to add tag `<?m2e execute?>` to the `execution` in relevant `pom.xml`. This gives hint to m2eclipse to run it always. Note that it is not possible to rely on the execution to be done via command line before build inside IDE, since opening the project in vscode will trigger the `clean` build phase and therefore it wipe out the previously correctly created target files.

**Comment by jonkoops** [comment]
Yeah, this definitely has room for improvement. Ideally I would like something else than a replacer plugin, like Vite spitting out a manifest that we can read from a template or something in that direction. That way all the rendering takes place in a neat and contained FreeMarker template.

If we don't want to go that route right now out of complexity, then we're certainly open for other approaches such

**Comment by jonkoops** [comment]
Yeah, this definitely has room for improvement. Ideally I would like something else than a replacer plugin, like Vite spitting out a manifest that we can read from a template or something in that direction. That way all the rendering takes place in a neat and contained FreeMarker template.

If we don't want to go that route right now out of complexity, then we're certainly open for other approaches such as using a different plugin. Feel free to submit a PR and I will make sure it gets reviewed quickly.

**Comment by jonkoops** [comment]
Also of note, the Admin Console uses the same replacer plugin, so I have attached the label for that as well.

**Comment by jonkoops** [comment]
#19750 is essentially the same issue, but I will keep this open for bookkeeping purposes.

**Comment by maulikam** [comment]
I'm suggesting we consider the gmavenplus-plugin as a new direction. It's well-maintained and seems capable of giving us a stronger and more reliable way to manage tasks like string replacement in our build process. Moving to gmavenplus-plugin could help us avoid these kinds of build errors in the future.

I'd really value your thoughts on this. Do you think switching to gmavenplus-plugin would make our Keycloak project's build process more stable and efficient?

**Comment by jonkoops** [comment]
As mentioned before we want to get rid of `maven-replacer-plugin` entirely, see #19750

**Comment by jonkoops** [comment]
@tsaarni is there anything currently preventing development on Keycloak using VSCode?
