### ISSUE TITLE
Flaky test: WatchedSecretsTest#testSecretsAreWatched

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#24790]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Error when running operator tests in an OCP cluster:

```
2023-11-12 21:40:15  [ERROR] org.keycloak.operator.testsuite.integration.WatchedSecretsTest.testSecretsAreWatched  Time elapsed: 323.455 s  <<< ERROR!
2023-11-12 21:40:15  java.lang.RuntimeException: [example-kc] did not restart before an exception occurred
2023-11-12 21:40:15  	at org.keycloak.operator.testsuite.integration.WatchedSecretsTest.testDeploymentRestarted(WatchedSecretsTest.java:200)
2023-11-12 21:40:15  	at org.keycloak.operator.testsuite.integration.WatchedSecretsTest.testSecretsAreWatched(WatchedSecretsTest.java:75)
```

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment]
Addressed by #24797
