### ISSUE TITLE
Error in base64 decoding saml message

### ISSUE THREAD

**Issue by jeffgus** [keycloak/keycloak#24880]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

I am using Tableau Server with Keycloak. Both are current versions. I can login to Tableau with Keycloak and it works just fine. The problem is if I provide a link to a site within Tableau (instead of the main page). Tableau appears to add additional tags in the SAML request which causes Keycloak to throw a parse error:

`
2023-11-21 11:09:49,306 ERROR [org.keycloak.saml.common] (executor-thread-40) Error in base64 decoding saml message.: java.lang.RuntimeException: PL00066: Parser : Expected start tag:Extensions.  Found <Extensions>
	at org.keycloak.saml.common.DefaultPicketLinkLogger.parserExpectedTag(DefaultPicketLinkLogger.java:451)
	at org.keycloak.saml.common.util.StaxParserUtil.validate(StaxParserUtil.java:887)
	at org.keycloak.saml.common.parsers.AbstractStaxParser.validateStartElement(AbstractStaxParser.java:122)
	at org.keycloak.saml.common.parsers.AbstractStaxParser.parse(AbstractStaxParser.java:55)
	at org.keycloak.saml.processing.core.parsers.saml.protocol.SAMLRequestAbstractParser.parseCommonElements(SAMLRequestAbstractParser.java:71)
	at org.keycloak.saml.processing.core.parsers.saml.protocol.SAMLAuthNRequestParser.processSubElement(SAMLAuthNRequestParser.java:85)
	at org.keycloak.saml.processing.core.parsers.saml.protocol.SAMLAuthNRequestParser.processSubElement(SAMLAuthNRequestParser.java:38)
	at org.keycloak.saml.common.parsers.AbstractStaxParser.parse(AbstractStaxParser.java:97)
	at org.keycloak.saml.processing.core.parsers.saml.SAMLParser.parse(SAMLParser.java:123)
	at org.keycloak.saml.common.parsers.AbstractParser.parse(AbstractParser.java:98)
	at org.keycloak.saml.common.parsers.AbstractParser.parse(AbstractParser.java:102)
	at org.keycloak.saml.processing.api.saml.v2.request.SAML2Request.getSAML2ObjectFromDocument(SAML2Request.java:193)
	at org.keycloak.saml.processing.api.saml.v2.request.SAML2Request.getSAML2ObjectFromStream(SAML2Request.java:180)
	at org.keycloak.saml.SAMLRequestParser.parseRequestPostBinding(SAMLRequestParser.java:83)
	at org.keycloak.protocol.saml.SamlService$PostBindingProtocol.extractRequestDocument(SamlService.java:783)
	at org.keycloak.protocol.saml.SamlService$BindingProtocol.handleSamlRequest(SamlService.java:266)
	at org.keycloak.protocol.saml.SamlService$BindingProtocol.execute(SamlService.java:702)
	at org.keycloak.protocol.saml.SamlService.postBinding(SamlService.java:885)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)`

At first I thought it might be due to the older version of Keycloak I am running for one of our test environments. I tried again with the latest Keycloak 22.0.5 and I still get the error.

The additional tags in the request are:

`
  </ds:Signature>
  <md:Extensions xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
    <sitesaml:siteLuid xmlns:sitesaml="urn:tableau:sitesaml">7ac9aebd-0a58-45cc-88a2-0dc7d9b0e982</sitesaml:siteLuid>
  </md:Extensions>
</saml2p:AuthnRequest>
`

The "md:Extensions" tags do not appear when I login normally in Tableau. I don't see any place where I can configure Tableau to set or not set sending these additional tags. Even if I could, should these tags cause Keycloak to throw an error?

### Version

22.0.5

### Expected behavior

Do not throw a stack trace when addtional tags are passed in the SAML call.

### Actual behavior

When I link to a sub-site in Tableau, Keycloak throws a stack trace and I get this error:

`We're sorry...
Invalid Request`

### How to Reproduce?

Make sure one is NOT logged in to the realm. Click on a link to a subsite within Tableau. The login will fail. Logging in using the main Tableau site link works.

### Anything else?

The error does not happen if the user is already logged in to the realm.

**Comment by jeffgus** [comment]
Thank you for the quick response. I will open a ticket with Tableau.

**Comment by jeffgus** [comment]
Tableau has acknowledged the issue and is currently investigating the issue. 
Closing ticket.
