### ISSUE TITLE
keycloak22.0.4 I got Unable to locate persister  excetpion when i test the example(domain-extension)

### ISSUE THREAD

**Issue by tmq77** [keycloak/keycloak#24921]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

When i create a sample company, I got a ModelException

Below is the exception:   Unable to locate persister 

```
 [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-10) Uncaught server error: org.keycloak.models.ModelException: java.lang.IllegalArgumentException: Unable to locate persister: org.keycloak.examples.domainextension.jpa.Company
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:64)
        at jdk.proxy2/jdk.proxy2.$Proxy76.persist(Unknown Source)
        at org.keycloak.examples.domainextension.spi.impl.ExampleServiceImpl.addCompany(ExampleServiceImpl.java:77)
        at org.keycloak.examples.domainextension.rest.CompanyResource.createCompany(CompanyResource.java:39)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)

```

it seems that the entity is not register to the jpa manager, i try it all the day and have no idea, btw the source is juts clone from the keycloak github repository

**below is my running code ↓**

https://github.com/keycloak/keycloak/tree/22.0.4/examples/providers/domain-extension

### Version

22.0.4

### Expected behavior

persist the company success

### Actual behavior

Uncaught server error: org.keycloak.models.ModelException: java.lang.IllegalArgumentException: Unable to locate persister: org.keycloak.examples.domainextension.jpa.Company

### How to Reproduce?

just  build the source  to a jar and copy it to my docker container

**Comment by tmq77** [comment]
i found the reason ,  my cache dependency is conflict !!
```
<dependency>
        <groupId>com.github.ben-manes.caffeine</groupId>
        <artifactId>caffeine</artifactId>
        <version>2.9.3</version>
</dependency>
```
