### ISSUE TITLE
Newer Oracle JDBC drivers can't be installed via `/providers` directory

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#25046]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Due to a [bug in Jandex](https://github.com/smallrye/jandex/issues/338) Keycloak cannot "sideload" newer Oracle drivers (confirmed affected version is 23.3.0.23.09). As a temporary solution we [downgraded](https://github.com/keycloak/keycloak/pull/25045) the driver in Keycloak as well. The proper fix for this should come from Jandex. After that we can upgrade the driver back again.

### Version

22,23

### Expected behavior

Server starts with the sideloaded driver.

### Actual behavior

```
     [exec] ERROR: Build failure: Build failed due to errors
     [exec] 	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.Type.internHashCode()" because "this.type" is null
     [exec] 	at org.jboss.jandex.FieldInternal.internHashCode(FieldInternal.java:133)
     [exec] 	at org.jboss.jandex.StrongInternPool$FieldInternPool.hashCode(StrongInternPool.java:742)
     [exec] 	at org.jboss.jandex.StrongInternPool$FieldInternPool.hashCode(StrongInternPool.java:730)
     [exec] 	at org.jboss.jandex.StrongInternPool.hash(StrongInternPool.java:163)
     [exec] 	at org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:255)
     [exec] 	at org.jboss.jandex.NameTable.intern(NameTable.java:117)
     [exec] 	at org.jboss.jandex.ClassInfo.setFields(ClassInfo.java:1193)
     [exec] 	at org.jboss.jandex.Indexer.indexWithSummary(Indexer.java:2502)
     [exec] 	at org.jboss.jandex.Indexer.index(Indexer.java:2452)
     [exec] 	at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:125)
     [exec] 	at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:94)
     [exec] 	at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:58)
     [exec] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep$2.apply(ApplicationArchiveBuildStep.java:303)
     [exec] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep$2.apply(ApplicationArchiveBuildStep.java:299)
     [exec] 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
     [exec] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.handleJarPath(ApplicationArchiveBuildStep.java:299)
     [exec] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.createApplicationArchive(ApplicationArchiveBuildStep.java:207)
     [exec] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:153)
     [exec] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:105)
     [exec] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
     [exec] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     [exec] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
     [exec] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
     [exec] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
     [exec] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
     [exec] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
     [exec] 	at java.base/java.lang.Thread.run(Thread.java:840)
     [exec] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
     [exec]
     [exec] ERROR: Cannot invoke "org.jboss.jandex.Type.internHashCode()" because "this.type" is null
     [exec] For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### How to Reproduce?

Easiest way to reproduce is:
```
mvn clean install -DskipTests -Dproduct
```

### Anything else?

This is a follow-up from https://github.com/keycloak/keycloak/issues/24983

**Comment by ahus1** [comment]
With https://github.com/quarkusio/quarkus/pull/37351, the fix is available in Quarkus 3.6.1

**Comment by mabartos** [comment]
@vmuzikar Is it still relevant?

**Comment by vmuzikar** [comment]
Seems we're already using the newer driver version:
https://github.com/keycloak/keycloak/blob/1e12b15890e02fbc7b73a490b7509812fb5e38b7/pom.xml#L173

Closing this.
