### ISSUE TITLE
Syncing Users from multiple configured LDAPs fails

### ISSUE THREAD

**Issue by Soufian20** [keycloak/keycloak#25129]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

For high availability, we set up a keycloak cluster with multiple keycloak instances running in docker containers and also running with the distributed cache ispn.

Our users are stored in an LDAP cluster, and the LDAP instances in the cluster syncing with each other the users.

So now as the picture shows, we configured our LDAPs in the keycloak user federation
![grafik](https://github.com/keycloak/keycloak/assets/38558643/762855af-4b90-4d3b-b478-a23cc7331464)

That works fine, we can see our LDAP users in keycloak after the sync but after LDAP1 goes down the periodic sync between keycloak and LDAP fails with an Connection refused error. To fix that we have to manually reorder the LDAP urls in the settings starting with a LDAP instance, for example LDAP2, that is fine.

Keycloak Logs
```log
2023-11-29 11:31:46,277 ERROR [org.keycloak.storage.managers.UserStorageSyncManager] (Timer-0) Error occurred during sync of changed users: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:171)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncImpl(LDAPStorageProviderFactory.java:553)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncSince(LDAPStorageProviderFactory.java:512)
	at org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:155)
	at org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:148)
	at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
	at org.keycloak.storage.managers.UserStorageSyncManager$3.run(UserStorageSyncManager.java:148)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
	at org.keycloak.storage.managers.UserStorageSyncManager.syncChangedUsers(UserStorageSyncManager.java:138)
	at org.keycloak.storage.managers.UserStorageSyncManager$5.run(UserStorageSyncManager.java:237)
	at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@6f30f17c
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:167)
	... 14 more
Caused by: javax.naming.CommunicationException: ldap3:389 [Root exception is java.net.ConnectException: Connection refused]
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:253)
	at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.initPagination(LDAPQuery.java:201)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.searchPaginated(LDAPOperationManager.java:293)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:277)
	... 15 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:346)
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:232)
	... 33 more
```

### Version

22.0.5

### Expected behavior

While syncing with LDAP, keycloak syncs with the next configured LDAP if a LDAP instance goes down

### Actual behavior

While syncing with LDAP, keycloak tries only with the first configured LDAP and fails with it if the instance is down

### How to Reproduce?

Configure multiple ldaps in one keycloak user federation with the sync settings
![grafik](https://github.com/keycloak/keycloak/assets/38558643/fd33286a-d146-4803-99b3-3f7295a8e9fb)
 

### Anything else?

If more information are needed i can provide more

**Comment by martin-kanis** [comment]
The similar problem was described here https://github.com/keycloak/keycloak/issues/23913, and I think the same applies here. When a LDAP instance is not available we don't want to bypass it because of potential conflicts. I know you said you sync users across the LDAP cluster, but in general those LDAP instances could have distinct set of users, and if we bypass one of them we create a room for conflicts. i.e if you try to create a local user which is available in the currently down LDAP.  

~invalid
