### ISSUE TITLE
Cannot create MULTIVALUED_STRING_TYPE Config in Provider Extension

### ISSUE THREAD

**Issue by LachlanNewman** [keycloak/keycloak#25128]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I am trying to create a keycloak extension that will map a set of string as an array to a claim.
below is the code for my extension 
```java
public class JsonRemoteClaim extends AbstractOIDCProtocolMapper
		implements OIDCAccessTokenMapper, OIDCIDTokenMapper, UserInfoTokenMapper {

	public static final String PROVIDER_ID = "oidc-rest-api-mapper";

	private static final List<ProviderConfigProperty> configProperties = new ArrayList<>();

	static final String VALUES = "values";

	static {
        ProviderConfigProperty property;

        property = new ProviderConfigProperty();
        property.setName(VALUES);
        property.setLabel("Values");
        property.setType(ProviderConfigProperty.MULTIVALUED_STRING_TYPE);
        property.setHelpText("Values to Add to claim");
        configProperties.add(property);

		OIDCAttributeMapperHelper.addTokenClaimNameConfig(configProperties);
		OIDCAttributeMapperHelper.addIncludeInTokensConfig(configProperties, JsonRemoteClaim.class);
	}

	@Override
	public String getId() {
		return PROVIDER_ID;
	}

	@Override
	public String getDisplayCategory() {
		return TOKEN_MAPPER_CATEGORY;
	}

	@Override
	public String getDisplayType() {
		return "Array Value Mapper";
	}

	@Override
	public String getHelpText() {
		return "Add Array of Values to Claim ";
	}

	@Override
	public List<ProviderConfigProperty> getConfigProperties() {
		return configProperties;
	}

	@Override
	protected void setClaim(
			IDToken token,
			ProtocolMapperModel mappingModel,
			UserSessionModel userSession,
			KeycloakSession keycloakSession,
			ClientSessionContext clientSessionCtx) {

        final String values = mappingModel.getConfig().get(VALUES);
		OIDCAttributeMapperHelper.mapClaim(token, mappingModel, values);
	}
}
```

However when i try to create a mapper in keycloak i get the following.
<img width="1235" alt="Screenshot 2023-11-29 at 1 06 50 pm" src="https://github.com/keycloak/keycloak/assets/20869723/9a989f30-0f40-4c0d-a952-6f78a04c4307">

Also when i enable debug logs im seeing the following error
```
Error response 400: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
2023-11-29 13:16:44  at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 285] (through reference chain: org.keycloak.representations.idm.ProtocolMapperRepresentation["config"]->java.util.LinkedHashMap["values"])
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:46)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:623)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2079)
2023-11-29 13:16:44     at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1229)
2023-11-29 13:16:44     at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:184)
2023-11-29 13:16:44     at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:99)
2023-11-29 13:16:44     at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:60)
2023-11-29 13:16:44     at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
2023-11-29 13:16:44     at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:192)
2023-11-29 13:16:44     at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:87)
2023-11-29 13:16:44     at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:116)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
2023-11-29 13:16:44     at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
2023-11-29 13:16:44     at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
2023-11-29 13:16:44     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
2023-11-29 13:16:44     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
2023-11-29 13:16:44     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
2023-11-29 13:16:44     at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
2023-11-29 13:16:44     at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
2023-11-29 13:16:44     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
2023-11-29 13:16:44     at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
2023-11-29 13:16:44     at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
2023-11-29 13:16:44     at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
2023-11-29 13:16:44     at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
2023-11-29 13:16:44     at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
2023-11-29 13:16:44     at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
2023-11-29 13:16:44     at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-11-29 13:16:44     at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
2023-11-29 13:16:44     at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
2023-11-29 13:16:44     at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
2023-11-29 13:16:44     at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
2023-11-29 13:16:44     at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2023-11-29 13:16:44     at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
2023-11-29 13:16:44     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2023-11-29 13:16:44     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2023-11-29 13:16:44     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2023-11-29 13:16:44     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2023-11-29 13:16:44     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2023-11-29 13:16:44     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-11-29 13:16:44     at java.base/java.lang.Thread.run(Thread.java:833)
```

### Version

22.0.1

### Expected behavior

Should successfully map the list of values to the desired claim.

### Actual behavior

Throws error defined above.

### How to Reproduce?

Follow the code above and build the keycloak image with the provided extension.

**Comment by LachlanNewman** [comment]
@mschallar but im not using `.` in the properties name https://github.com/keycloak/keycloak/issues/24927#issuecomment-1823928855

**Comment by gim-** [comment]
I've encountered the same issue when I tried to utilize `MULTIVALUED_STRING_TYPE` for config.

Apparently Keycloak mapper representation expects only String values: https://github.com/keycloak/keycloak/blob/22.0.5/core/src/main/java/org/keycloak/representations/idm/ProtocolMapperRepresentation.java#L38

I've tried testing it with other type such as `MAP_TYPE` and it appears that it gets sent as inline JSON from the frontend.
<img width="466" alt="Screenshot 2024-01-14 at 11 39 43" src="https://github.com/keycloak/keycloak/assets/1240012/9e886528-1e17-4a5c-a146-973ce3d9b0c1">

Unlike `MULTIVALUED_STRING_TYPE` which is sent as part of the request JSON:
<img width="465" alt="Screenshot 2024-01-14 at 11 43 11" src="https://github.com/keycloak/keycloak/assets/1240012/3d215114-958f-412c-9317-4838135c2554">

**Comment by mposolda** [comment]
This is probably valid issue, but Keycloak team probably won't have time to look at this soon. Especially due the fact that using this SPI is not officially recommended (it is private SPI). Anyone is welcome to investigate/fix this. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details on how to contribute.

It looks indeed as some issue with the `MULTIVALUED_STRING_TYPE`. Not sure if it is related to admin UI or server-side or both.
