### ISSUE TITLE
Javascript CI - admin ui (3, firefox) realm tests failures

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#25211]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

CI failure:
  1) Realm tests
       Should delete Test Disabled realm:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'Test-Disabled' within the element: <div#realm-select.pf-c-dropdown.pf-m-expanded.keycloak__realm_selector__dropdown> but never did.
      at goToRealm (webpack://admin-ui/./cypress/support/pages/admin-ui/SidebarPage.ts:38:0)
      at  (webpack://admin-ui/./cypress/e2e/realm_test.spec.ts:59:0)
      at __webpack_modules__</setRunnable/runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:138938:43)
      at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:157835:21)
      at __webpack_modules__</Runnable.prototype.run (http://localhost:8080/__cypress/runner/cypress_runner.js:157822:13)
      at __webpack_modules__</create/onRunnableRun (http://localhost:8080/__cypress/runner/cypress_runner.js:163746:30)
      at finallyHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:4072:23)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1701:18)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:24)
      at __webpack_modules__</Async.prototype._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:16)
      at __webpack_modules__</Async/this.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)

  2) Realm tests
       should create realm from new a realm:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `.pf-c-alert__title`, but never found it. Queried from:

              > cy.findByTestId(global-alerts)
      at checkNotificationMessage (webpack://admin-ui/./cypress/support/pages/admin-ui/Masthead.ts:89:0)
      at  (webpack://admin-ui/./cypress/e2e/realm_test.spec.ts:70:0)
      at __webpack_modules__</setRunnable/runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:138938:43)
      at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:157835:21)
      at __webpack_modules__</Runnable.prototype.run (http://localhost:8080/__cypress/runner/cypress_runner.js:157822:13)
      at __webpack_modules__</create/onRunnableRun (http://localhost:8080/__cypress/runner/cypress_runner.js:163746:30)
      at finallyHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:4072:23)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
      at __webpack_modules__</module.exports/Promise.prototype._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1701:18)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:2407:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:2400:24)
      at __webpack_modules__</Async.prototype._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2416:16)
      at __webpack_modules__</Async/this.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:2286:14)

### Version

999.0.0-SNAPSHOT

### Expected behavior

should pass

### Actual behavior

fails on 2 tests

### How to Reproduce?

check link: https://github.com/keycloak/keycloak/actions/runs/7053868434/job/19202061958

**Comment by ssilvert** [comment]
@lhanusov Is this issue still relevant?  Are you waiting on help from the UI team?

**Comment by edewit** [comment]
The tests on the builds seem to work... your link is that from an PR?

**Comment by jonkoops** [comment]
Looks like the [last nightly run](https://cloud.cypress.io/projects/j4yhox/runs/10875/specs?utm_source=github) passed, so I am closing this issue.
