### ISSUE TITLE
Advanced Attribute to Group SAML mapper: attributes with the same key cause failure to log-in

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#25369]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

Advanced Attribute to Group SAML mapper causes failure for a user to log-in when there exist configured attributes with the same key

### Version

22.0.5

### Expected behavior

1 of 2 expectations are possible:
- either validation should prevent saving attributes with the same key
- or mapper should work successfully. There are reasons why it makes sense: since the mapper doesn't allow fine-grained tuning of attribute name vs friendly name (as described in the #24644), it may be needed to have a mapper that matches a user when: there exist an attribute with the name 1 and value 2, and simultaneously there is an attribute with the Friendly name 1 and value 3

### Actual behavior

User that has an assertion matching the mapper cannot log-in. **An internal server error has occurred** is shown.

### How to Reproduce?

Create a mapper like this
![изображение](https://github.com/keycloak/keycloak/assets/1285898/a93980b4-e141-4d8d-8534-80874adfb1cb)

Let the SAML assertion contain an attribute with the Name=1, Value=3

The keycloak.log contains an exception:
```
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Duplicate key 1 (attempted merging values 3 and 2)
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.keycloak.models.IdentityProviderMapperModel.getConfigMap(IdentityProviderMapperModel.java:101)
        at org.keycloak.broker.saml.mappers.AdvancedAttributeToGroupMapper.applies(AdvancedAttributeToGroupMapper.java:118
```

**Comment by rmartinc** [comment]
@lrozenblyum Could this be a duplicate of https://github.com/keycloak/keycloak/issues/22638? Have you tested with the last version?

**Comment by lrozenblyum** [comment]
Thanks @rmartinc for pointing this out. Sorry for reporting a duplicate. Indeed it should be treated by #22638 because the fix that applied there is expected to affect all 'advanced' claim mappers (including that one that I was reporting - the 'to Group' mapper).
