### ISSUE TITLE
Issue with keycloak start after upgrading to v23.0.1

### ISSUE THREAD

**Issue by nidhin077** [keycloak/keycloak#25580]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Hi, 

I'm attempting to update the keycloak from version 21.1.1 to version 23.0.1. During the upgrade, I ran across an issue, which I attempted to fix in a few different ways but was unsuccessful. Please review the issue message and Dockerfile I used for the build, and let me know if there is a quick solution. I've attached both. 

```
Updating the configuration and installing your custom providers, if any. Please wait.
2023-12-14 10:46:03,548 WARN  [org.keycloak.services] (build-42) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
2023-12-14 10:46:04,452 WARN  [org.keycloak.services] (build-42) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2023-12-14 10:46:04,452 WARN  [org.keycloak.services] (build-42) KC-SERVICES0047: eventlistener (com.medigy.tracer.CustomEventListenerProviderFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2023-12-14 10:46:12,665 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 11359ms
Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config

Next time you run the server, just run:

	kc.sh start --optimized 

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.NoSuchFieldError: FIPS
	at org.keycloak.config.SecurityOptions.<clinit>(SecurityOptions.java:14)
	at org.keycloak.config.HttpOptions.<clinit>(HttpOptions.java:84)
	at org.keycloak.quarkus.runtime.configuration.mappers.HttpPropertyMappers.getHttpPropertyMappers(HttpPropertyMappers.java:28)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.<clinit>(PropertyMappers.java:30)
	at org.keycloak.quarkus.runtime.cli.Picocli.addOptionsToCli(Picocli.java:424)
	at org.keycloak.quarkus.runtime.cli.Picocli.addCommandOptions(Picocli.java:404)
	at org.keycloak.quarkus.runtime.cli.Picocli.createCommandLine(Picocli.java:367)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:92)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
```
	... 6 more

Dockerfile

```

FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs git wget unzip -y; dnf --installroot /mnt/rootfs clean all


FROM quay.io/keycloak/keycloak:22.0.5
COPY --from=ubi-micro-build /mnt/rootfs /
USER root
WORKDIR /tmp
RUN wget https://github.com/wadahiro/keycloak-discord/releases/download/v0.4.1/keycloak-discord-0.4.1.jar
RUN mv keycloak-discord-0.4.1.jar /opt/keycloak/providers
RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip
RUN unzip apache-maven-3.8.8-bin.zip
WORKDIR /tmp/keycloak-listner-for-telemetry
RUN /tmp/apache-maven-3.8.8/bin/mvn clean install
RUN mv /tmp/keycloak-listner-for-telemetry/target/keycloak-metric-event-listener.jar /opt/keycloak/providers/keycloak-metric-event-listener.jar
RUN wget https://github.com/aerogear/keycloak-metrics-spi/releases/download/3.0.0/keycloak-metrics-spi-3.0.0.jar
RUN mv  keycloak-metrics-spi-3.0.0.jar /opt/keycloak/providers/
```

### Version

23.0.1

### Expected behavior

Keycloak should work without any error

### Actual behavior

Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config

Next time you run the server, just run:

	kc.sh start --optimized 

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.NoSuchFieldError: FIPS
	at org.keycloak.config.SecurityOptions.<clinit>(SecurityOptions.java:14)
	at org.keycloak.config.HttpOptions.<clinit>(HttpOptions.java:84)
	at org.keycloak.quarkus.runtime.configuration.mappers.HttpPropertyMappers.getHttpPropertyMappers(HttpPropertyMappers.java:28)
	at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.<clinit>(PropertyMappers.java:30)
	at org.keycloak.quarkus.runtime.cli.Picocli.addOptionsToCli(Picocli.java:424)
	at org.keycloak.quarkus.runtime.cli.Picocli.addCommandOptions(Picocli.java:404)
	at org.keycloak.quarkus.runtime.cli.Picocli.createCommandLine(Picocli.java:367)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:92)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	... 6 more

### How to Reproduce?

Try to upgrade the keycloak to 23.0.1 using a docker container

**Comment by shawkins** [comment]
@nidhin077 in the dockerfile you are showing keycloak:22.0.5 - do you mean that you see this behavior with both 22 and 23?

This seems like a classloading issue - is it possible that keycloak-listner-for-telemetry is overriding built-in keycloak classes?

**Comment by mposolda** [comment]
Switching to the cloud-native team for triage and to evaluate if this is valid bug. As this looks like a classloading issue specific to the usage of the custom docker image.

**Comment by nidhin077** [comment]
> @nidhin077 in the dockerfile you are showing keycloak:22.0.5 - do you mean that you see this behavior with both 22 and 23?
> 
> This seems like a classloading issue - is it possible that keycloak-listner-for-telemetry is overriding built-in keycloak classes?

Everything appears to be functioning now that the problem with the Keycloak Listner Telemetry has been resolved.
