### ISSUE TITLE
Keycloak 22.0.4 ModelException for POST request for Company in domain-extension example

### ISSUE THREAD

**Issue by choicespecs** [keycloak/keycloak#25622]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Duplicate of this issue https://github.com/keycloak/keycloak/issues/24921

code is keycloak example domain-extension https://github.com/keycloak/keycloak/tree/22.0.4/examples/providers/domain-extension

Running example query given (is outdated as well but running correct query)

`curl -i --request POST http://localhost:8080/realms/master/example/companies --data "{ \"name\": \"foo company\" }" --header "Content-type: application/json"`

return this exemption
```
[org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-10) Uncaught server error: org.keycloak.models.ModelException: java.lang.IllegalArgumentException: Unable to locate persister: org.keycloak.examples.domainextension.jpa.Company
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:64)
        at jdk.proxy2/jdk.proxy2.$Proxy76.persist(Unknown Source)
        at org.keycloak.examples.domainextension.spi.impl.ExampleServiceImpl.addCompany(ExampleServiceImpl.java:77)
        at org.keycloak.examples.domainextension.rest.CompanyResource.createCompany(CompanyResource.java:39)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
```

Tried adding dependency provided by ticket but does not solve and cannot understand how user did solve issue.

### Version

22.0.4

### Expected behavior

Add Company

### Actual behavior

 [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-10) Uncaught server error: org.keycloak.models.ModelException: java.lang.IllegalArgumentException: Unable to locate persister: org.keycloak.examples.domainextension.jpa.Company

### How to Reproduce?

Create jar for domain-extension-example

Create docker container & run provided within https://www.keycloak.org/server/containers and add jar to providers directory given instructions.

Keycloak Dockerfile is similar to the example provided except postgres instance is created through docker

`docker run -d --name keycloak-postgres -e POSTGRES_DB=keycloak -e POSTGRES_USER=keycloak -e POSTGRES_PASSWORD=password 5432:5432 postgres:latest`

### Anything else?

Example code: https://github.com/keycloak/keycloak/tree/22.0.4/examples/providers/domain-extension

Duplicate Ticket: https://github.com/keycloak/keycloak/issues/24921

Keycloak docker example: https://www.keycloak.org/server/containers

**Comment by ahus1** [comment]
It seems that this is unfortunately out of date. I'd be happy to see a community PR for this to update it.

**Comment by stianst** [comment]
This example has not been actively maintained for a long time, and for that reason has now been removed.
