### ISSUE TITLE
Admin not accessible in 21.0, 22.0.5, 23.0, 23.0.4 - throw docker -  Template not found for name "index.ftl".

### ISSUE THREAD

**Issue by cedriclombardot** [keycloak/keycloak#25644]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Got the following log

```

17/12/2023 19:16:28Changes detected in configuration. Updating the server image.
17/12/2023 19:16:28Updating the configuration and installing your custom providers, if any. Please wait.
17/12/2023 19:16:362023-12-17 18:16:28,864 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: account3, admin-fine-grained-authz, client-secret-rotation, declarative-user-profile, recovery-codes, scripts, token-exchange, update-email
17/12/2023 19:16:362023-12-17 18:16:32,352 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: account3, admin-fine-grained-authz, client-secret-rotation, declarative-user-profile, recovery-codes, scripts, token-exchange, update-email
17/12/2023 19:16:462023-12-17 18:16:46,066 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 14772ms
17/12/2023 19:16:46Server configuration updated and persisted. Run the following command to review the configuration:
17/12/2023 19:16:46
17/12/2023 19:16:46	kc.sh show-config
17/12/2023 19:16:46
17/12/2023 19:16:46Next time you run the server, just run:
17/12/2023 19:16:46
17/12/2023 19:16:46	kc.sh start --optimized --hostname-strict=false
17/12/2023 19:16:46
17/12/2023 19:16:522023-12-17 18:16:47,643 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: account3, admin-fine-grained-authz, client-secret-rotation, declarative-user-profile, recovery-codes, scripts, token-exchange, update-email
17/12/2023 19:16:522023-12-17 18:16:48,448 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: keycloak.donkeyschool.net, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
17/12/2023 19:16:522023-12-17 18:16:51,914 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
17/12/2023 19:16:522023-12-17 18:16:52,469 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
17/12/2023 19:16:522023-12-17 18:16:52,735 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
17/12/2023 19:16:522023-12-17 18:16:52,995 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
17/12/2023 19:16:532023-12-17 18:16:53,297 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
17/12/2023 19:16:532023-12-17 18:16:53,299 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 9e36bc2c-dae2-4bff-b637-ccfaac95d311, name: 5626b714d958-5467
17/12/2023 19:16:532023-12-17 18:16:53,312 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
17/12/2023 19:16:532023-12-17 18:16:53,313 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
17/12/2023 19:16:532023-12-17 18:16:53,313 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
17/12/2023 19:16:532023-12-17 18:16:53,313 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
17/12/2023 19:16:532023-12-17 18:16:53,485 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.20958
17/12/2023 19:16:542023-12-17 18:16:54,178 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
17/12/2023 19:16:552023-12-17 18:16:55,515 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 5626b714d958-5467: no members discovered after 2023 ms: creating cluster as coordinator
17/12/2023 19:16:552023-12-17 18:16:55,531 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [5626b714d958-5467|0] (1) [5626b714d958-5467]
17/12/2023 19:16:552023-12-17 18:16:55,599 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `5626b714d958-5467`, physical addresses are `[10.42.125.131:36494]`
17/12/2023 19:16:552023-12-17 18:16:55,633 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
17/12/2023 19:17:002023-12-17 18:17:00,173 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
17/12/2023 19:17:002023-12-17 18:17:00,283 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 5626b714d958-5467, Site name: null
17/12/2023 19:17:022023-12-17 18:17:02,115 INFO  [io.quarkus] (main) Keycloak 22.0.5 on JVM (powered by Quarkus 3.2.7.Final) started in 15.823s. Listening on: http://0.0.0.0:8080
17/12/2023 19:17:022023-12-17 18:17:02,115 INFO  [io.quarkus] (main) Profile prod activated.
17/12/2023 19:17:022023-12-17 18:17:02,116 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, vertx]
17/12/2023 19:17:022023-12-17 18:17:02,555 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
17/12/2023 19:17:02	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)
17/12/2023 19:17:02	at org.keycloak.services.resources.admin.AdminConsole.getMainPage(AdminConsole.java:354)
17/12/2023 19:17:02	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17/12/2023 19:17:02	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
17/12/2023 19:17:02	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17/12/2023 19:17:02	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
17/12/2023 19:17:02	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
17/12/2023 19:17:02	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
17/12/2023 19:17:02	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
17/12/2023 19:17:02	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
17/12/2023 19:17:02	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
17/12/2023 19:17:02	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
17/12/2023 19:17:02	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
17/12/2023 19:17:02	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
17/12/2023 19:17:02	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
17/12/2023 19:17:02	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
17/12/2023 19:17:02	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
17/12/2023 19:17:02	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
17/12/2023 19:17:02	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
17/12/2023 19:17:02	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
17/12/2023 19:17:02	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
17/12/2023 19:17:02	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
17/12/2023 19:17:02	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
17/12/2023 19:17:02	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
17/12/2023 19:17:02	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
17/12/2023 19:17:02	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
17/12/2023 19:17:02	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
17/12/2023 19:17:02	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
17/12/2023 19:17:02	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
17/12/2023 19:17:02	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
17/12/2023 19:17:02	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
17/12/2023 19:17:02	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
17/12/2023 19:17:02	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
17/12/2023 19:17:02	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
17/12/2023 19:17:02	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
17/12/2023 19:17:02	at java.base/java.lang.Thread.run(Thread.java:840)
17/12/2023 19:17:02Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
17/12/2023 19:17:02The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@1d23bd37.
17/12/2023 19:17:02	at freemarker.template.Configuration.getTemplate(Configuration.java:2957)
17/12/2023 19:17:02	at freemarker.template.Configuration.getTemplate(Configuration.java:2777)
17/12/2023 19:17:02	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.getTemplate(DefaultFreeMarkerProvider.java:66)
17/12/2023 19:17:02	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:39)
17/12/2023 19:17:02	... 42 more
17/12/2023 19:17:02


```

### Version

21.0, 22.0.5, 23.0, 23.0.4 

### Expected behavior

Don't know why my file does not run anymore 

### Actual behavior

500 on /admin/master/console/

### How to Reproduce?

My docker image : 

https://github.com/donkeycode/docker-public-images/blob/master/keycloak/Dockerfile

With env

      KC_FEATURES: declarative-user-profile,preview,web-authn,recovery-codes,admin-api,account-api,impersonation,admin2
      KC_PROXY: edge

### Anything else?

My login page / reset page also appear without css
If i go back to 20.0 page appear but with no css

**Comment by jcBeaupre** [comment]
By any chance, can you confirm that you are not using the base theme on Admin UI?

Stack trace seems pretty similar to: https://github.com/keycloak/keycloak/issues/21421

**Comment by cedriclombardot** [comment]
True my admin theme is "base"

**Comment by cedriclombardot** [comment]
Updating to "keycloak.v2" it works
