### ISSUE TITLE
Failed to generate certificate for key provider 'rsa-generated' in realm 'xxx'. Details: id_alg_zlibCompress

### ISSUE THREAD

**Issue by williamyuan86** [keycloak/keycloak#25811]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

after upgrade to 23.0.3, I got this error when I try to create realm. 
2023-12-28 09:20:42,010 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-17) Uncaught server error: org.keycloak.component.ComponentValidationException: Failed to generate certificate
        at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.generateCertificate(AbstractGeneratedRsaKeyProviderFactory.java:125)
        at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.generateKeys(AbstractGeneratedRsaKeyProviderFactory.java:113)
        at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.validateConfiguration(AbstractGeneratedRsaKeyProviderFactory.java:86)
        at org.keycloak.models.jpa.RealmAdapter.importComponentModel(RealmAdapter.java:2036)
        at org.keycloak.models.jpa.RealmAdapter.addComponentModel(RealmAdapter.java:2016)
        at org.keycloak.models.utils.DefaultKeyProviders.createRsaKeyProvider(DefaultKeyProviders.java:62)
        at org.keycloak.models.utils.DefaultKeyProviders.createProviders(DefaultKeyProviders.java:39)
        at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:458)
        at org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:128)
        at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:571)
        at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:504)
        at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:54)
        at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:91)
        at org.keycloak.storage.ImportRealmFromRepresentationEvent.fire(ImportRealmFromRepresentationEvent.java:50)
        at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:161)
        at org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:143)
        at org.keycloak.services.resources.admin.RealmsAdminResource$quarkusrestinvoker$importRealm_6d35df38bd8803a41904a3ba2b8d4b916b587fb6.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NoSuchFieldError: id_alg_zlibCompress
        at org.bouncycastle.asn1.cms.CMSObjectIdentifiers.<clinit>(Unknown Source)
        at org.bouncycastle.operator.DefaultSignatureNameFinder.<clinit>(Unknown Source)
        at org.bouncycastle.operator.jcajce.OperatorHelper.<clinit>(Unknown Source)
        at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source)
        at org.keycloak.crypto.def.BCCertificateUtilsProvider.createSigner(BCCertificateUtilsProvider.java:185)
        at org.keycloak.crypto.def.BCCertificateUtilsProvider.generateV1SelfSignedCertificate(BCCertificateUtilsProvider.java:168)
        at org.keycloak.crypto.def.BCCertificateUtilsProvider.generateV1SelfSignedCertificate(BCCertificateUtilsProvider.java:154)
        at org.keycloak.common.util.CertificateUtils.generateV1SelfSignedCertificate(CertificateUtils.java:63)
        at org.keycloak.keys.AbstractGeneratedRsaKeyProviderFactory.generateCertificate(AbstractGeneratedRsaKeyProviderFactory.java:118)
        ... 26 more

### Version

23.0.3

### Expected behavior

When I create realm, It should create successfully.

### Actual behavior

the unknown error was promoted

### How to Reproduce?

use docker-compose start a new keycloak

### Anything else?

no

**Comment by Roboskeletron** [comment]
I`m having the same issue. @williamyuan86  how have you soleved it?
