### ISSUE TITLE
Brute Force Defense Issue with Permanent Lockout

### ISSUE THREAD

**Issue by alaa60** [keycloak/keycloak#26127]
### Describe the bug

I'm experiencing an issue with Keycloak's brute force security feature in versions 23.0.3 and above, specifically when the "Permanent lockout" option is enabled in brute force detection.

The error arises when the "Permanent lockout" option is enabled, and an event listener SPI I've implemented is active. In this scenario, reaching the maximum login attempts results in a `ContextNotActiveException` error. Notably, this behavior is not observed in versions prior to 23.0.3. Additionally, if the custom SPI is disabled, the permanent lockout feature does not engage correctly even after hitting the maximum login attempts.

`2024-01-11 14:09:01,127 ERROR [org.keycloak.services] (Brute Force Protector) KC-SERVICES0052: Failed processing type: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.vertx.http.runtime.CurrentVertxRequest, id=d3fea7e849828428a20dd77c1de969b46fc0d001]
        - you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:55)
        at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
        at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.getCurrent(Unknown Source)
        at org.keycloak.quarkus.runtime.integration.resteasy.ResteasyVertxProvider.getContextData(ResteasyVertxProvider.java:33)
        at org.keycloak.common.util.Resteasy.getContextData(Resteasy.java:62)
        at org.keycloak.services.DefaultKeycloakContext.getContextObject(DefaultKeycloakContext.java:102)
        at org.keycloak.services.DefaultKeycloakContext.getHttpRequest(DefaultKeycloakContext.java:150)
        at org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:79)
        at org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:86)
        at local.test.sso.user_registration_completer.UserRegistrationEventListenerProviderFactory.create(UserRegistrationEventListenerProviderFactory.java:13)
        at local.test.sso.user_registration_completer.UserRegistrationEventListenerProviderFactory.create(UserRegistrationEventListenerProviderFactory.java:9)
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:195)
        at org.keycloak.events.EventBuilder.lambda$getEventListeners$0(EventBuilder.java:84)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.keycloak.events.EventBuilder.getEventListeners(EventBuilder.java:93)
        at org.keycloak.events.EventBuilder.<init>(EventBuilder.java:68)
        at org.keycloak.events.EventBuilder.<init>(EventBuilder.java:56)
        at org.keycloak.services.managers.DefaultBruteForceProtector.failure(DefaultBruteForceProtector.java:180)
        at org.keycloak.services.managers.DefaultBruteForceProtector.run(DefaultBruteForceProtector.java:272)
        at java.base/java.lang.Thread.run(Thread.java:840)`

### Version

23.0.3 and later

### Expected behavior

After the maximum login attempts are reached, the system should enforce the permanent lockout as configured, without causing any system errors, and custom SPI implementations should not affect this functionality.

### Actual behavior

A `ContextNotActiveException` error occurs when the lockout threshold is reached with the custom SPI enabled. Additionally, disabling the SPI results in the permanent lockout feature not functioning as expected.

### How to Reproduce?

1. Upgrade to Keycloak version 23.0.3 or later.
2. Enable "Permanent lockout" under "Brute Force Detection" in the realm settings.
3. Perform login attempts to reach the maximum threshold for lockout.

**Comment by douglaspalmer** [comment]
I am unable to reproduce this with HEAD of main. The USER_DISABLED_BY_PERMANENT_LOCKOUT event is being generated correctly (line 180 in DefaultBruteForceProtector. The issue must lie within your SPI.
