### ISSUE TITLE
Keycloak fails to start due to infinispan BootstrapMethodError when using ec2 cache stack

### ISSUE THREAD

**Issue by adam-carruthers** [keycloak/keycloak#26258]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

Ran into the following exception when starting Keycloak within Docker running on ECS (using the cache stack `ec2` to connect) - not EKS and no kubernetes

```
Appending additional Java properties to JAVA_OPTS: -Djgroups.s3.region_name=eu-west-2 -Djgroups.s3.bucket_name=<<< redacted >>>
"The following build time non-cli properties were found, but will be ignored during run time: kc.cache, kc.cache-stack"
"SLF4J: The requested version 2.0.6 by your slf4j binding is not compatible with [1.6, 1.7]"
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
"2024-01-16 14:38:31,518 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <<< redacted >>>, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true"
"2024-01-16 14:38:34,033 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly"
"2024-01-16 14:38:34,593 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal"
"2024-01-16 14:38:34,770 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'"
"2024-01-16 14:38:36,276 INFO  [org.jgroups.protocols.aws.S3_PING] (keycloak-cache-init) Using Amazon S3 ping in region eu-west-2 with bucket '<<< redacted >>>' and prefix ''"
"2024-01-16 14:38:36,759 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests."
"2024-01-16 14:38:36,876 INFO  [org.jgroups.protocols.aws.S3_PING] (keycloak-cache-init) Found bucket <<< redacted >>>"
"2024-01-16 14:38:36,882 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `ec2`"
"2024-01-16 14:38:36,884 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: <<< redacted >>>, name: ip-<<< redacted >>>"
"2024-01-16 14:38:36,891 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.57800"
"2024-01-16 14:38:39,061 WARN  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) ip-<<< redacted >>>: JOIN(ip-<<< redacted >>>) sent to ip-<<< redacted >>> timed out (after 2000 ms), on try 0"
"2024-01-16 14:39:00,509 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [ip-<<< redacted >>>|4] (4) [ip-<<< redacted >>>, ip-<<< redacted >>>, ip-<<< redacted >>>, ip-<<< redacted >>>]"
"2024-01-16 14:39:00,562 ERROR [org.jgroups.JChannel] (keycloak-cache-init) JGRP000016: exception in channelConnected callback: java.lang.BootstrapMethodError: bootstrap method initialization exception"
"2024-01-16 14:39:00,562 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `ip-<<< redacted >>>`, physical addresses are `[<<< redacted >>>]`"
"2024-01-16 14:39:00,563 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@63d993b2, status=FAILED} failed to start"
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:584)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:43)
	at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:78)
	at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:70)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:485)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:63)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:49)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	... 22 more
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class org.jgroups.protocols.relay.RELAY2; not a subtype of implementation type class org.jgroups.protocols.relay.RELAY
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:273)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:340)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134)
	... 31 more
"2024-01-16 14:39:00,565 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000080: Disconnecting JGroups channel `ISPN`"
"2024-01-16 14:39:00,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode"
"2024-01-16 14:39:00,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches"
"2024-01-16 14:39:00,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@63d993b2, status=FAILED} failed to start"
"2024-01-16 14:39:00,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@63d993b2, status=FAILED} failed to start"
"2024-01-16 14:39:00,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport, instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@63d993b2, status=FAILED} failed to start"
"2024-01-16 14:39:00,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: bootstrap method initialization exception"
"2024-01-16 14:39:00,726 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Invalid receiver type class org.jgroups.protocols.relay.RELAY2; not a subtype of implementation type class org.jgroups.protocols.relay.RELAY"
"2024-01-16 14:39:00,727 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command."
```

This seems very similar to https://github.com/keycloak/keycloak/issues/21092 - however that issue was fixed with an upgrade to infinispan to v14.0.14. This issue seems to have been caused by the upgrade of infinispan to v14.0.21.Final in https://github.com/keycloak/keycloak/issues/25287 https://github.com/keycloak/keycloak/pull/25289 . Keycloak works for us in v.23.0.1

### Version

23.0.4

### Expected behavior

Keycloak should start without any infinispan error.

### Actual behavior

Keycloak container fails to start due to an infinispan error.

### How to Reproduce?

We run keycloak on ECS, with 3 running tasks.

Here are the environment variables we give the containers (note that a lot of the values reference external RDS clusters and Route53 hosted zones and S3 buckets) - I don't know how to make a clustered Keycloak config work without them.

```
        {
          "name"  = "KC_DB_URL_DATABASE"
          "value" = "keycloak"
        },
        {
          "name"  = "KC_DB_URL_HOST"
          "value" = "${aws_rds_cluster.keycloak.endpoint}"
        },
        {
          "name"  = "KC_DB_URL_PORT"
          "value" = "${tostring(aws_rds_cluster.keycloak.port)}"
        },
        {
          "name"  = "KC_PROXY"
          "value" = "edge"
        },
        {
          "name"  = "KC_HOSTNAME"
          "value" = "${aws_route53_record.keycloak.name}"
        },
        {
          "name"  = "KC_LOG_LEVEL"
          "value" = "INFO,org.keycloak.events:debug"
        },
        {
          "name"  = "JAVA_OPTS_APPEND"
          "value" = "-Djgroups.s3.region_name=${var.region} -Djgroups.s3.bucket_name=${module.keycloak_cluster_cache.id}"
        },
        {
          "name"  = "KC_CACHE"
          "value" = "ispn"
        },
        {
          "name"  = "KC_CACHE_STACK"
          "value" = "ec2"
        }
```

And Dockerfile

```
ARG KEYCLOAK_VERSION=23.0.4

FROM public.ecr.aws/docker/library/maven:3.8.4-openjdk-17-slim as maven-builder
COPY native-s3-ping/pom.xml ./
RUN mvn package

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION as builder

ARG METRICS_VERSION=3.0.0
ADD --chown=keycloak:keycloak https://github.com/aerogear/keycloak-metrics-spi/releases/download/$METRICS_VERSION/keycloak-metrics-spi-$METRICS_VERSION.jar /opt/keycloak/providers/keycloak-metrics-spi-$METRICS_VERSION.jar

COPY --from=maven-builder --chown=keycloak target/s3-native-ping-bundle-*-jar-with-dependencies.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build --cache-stack=ec2 --db=mysql --health-enabled=true

ARG KEYCLOAK_VERSION
FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
```

with native-s3-ping/pom.xml as

<details>

<summary>native-s3-ping/pom.xml</summary>

```
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.group</groupId>
    <artifactId>s3-native-ping-bundle</artifactId>
    <version>1</version>

    <properties>
        <aws.sdk.version>2.20.65</aws.sdk.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-core</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-s3</artifactId>
                <version>${aws.sdk.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jgroups.aws</groupId>
            <artifactId>jgroups-aws</artifactId>
            <version>3.0.0.Final</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>copy-deps</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

</details>

**Comment by mhajas** [comment]
Thank you for the answer @pruivo. From your comment, it seems this is not a bug in Keycloak. I will leave this issue opened and wait for a response from @adam-carruthers. 

However, I don't think this is a blocker for Keycloak 24.0.0 so I will remove the 24 milestone and move this to triage backlog.

**Comment by ferdinandmehlan** [comment]
Hello,

We have a very similar setup in running a keycloak cluster in ECS and using the `ec2` cache stack for discovery.
The last keycloak version working for us is 23.0.1

The  AWS SDK and jgroups dependencies should be up to date. We are using:

```
org.jgroups.aws:jgroups-aws:3.0.0.Final
software.amazon.awssdk:s3:2.23.17
software.amazon.awssdk:protocol-core:2.23.17
```

And the do pull the following jgroups version:

```
org.jgroups:jgroups:5.2.14.Final
```

@pruivo I'm not sure I understand you correctly, Does the 5.2.14.Final Version of jgroups have problems and a downgrade to 5.2.12.Final can help?

**Comment by pruivo** [comment]
@ferdinandmehlan Forgive me if I wasn't clear.
 I'm saying to not include the jgroups.jar classes into `s3-native-ping-bundle-*-jar-with-dependencies.jar` so it uses the JGroups classes shipped with Keycloak.

**Comment by ferdinandmehlan** [comment]
Thank you for your clarification. By excluding the JGroups dependency which is pulled by org.jgroups.aws:jgroups-aws our setup now works again with the Keycloak version 23.0.6
