### ISSUE TITLE
KC-SERVICES0013 - ClassCastException - RootAuthenticationSessionEntity cannot be cast to class

### ISSUE THREAD

**Issue by taaho** [keycloak/keycloak#26290]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

keycloadk-23.0.4 &  ( infinispan 14.0.21  or below version, or 15.0 dev version - all makes error)

when adding below area("here") code about authenticationSessions, it makes error
- to clustering authenticationSessions distributed-cache,
- adding it to keycloak-23.0.4/server/conf/infinispan.xml,   infinispan-server-15.0.0.Dev06$ vi server/conf/infinispan.xml
- make error

`    <distributed-cache name="sessions">
      <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>

    <distributed-cache name="actionTokens">
      <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>

    // here
    <distributed-cache name="authenticationSessions">
      <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
     // here

    <distributed-cache name="offlineSessions">
      <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    <distributed-cache name="offlineClientSessions">
      <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>  
`

- this is error -
2024-01-18 14:28:24,957 WARN  [org.keycloak.services] (executor-thread-1) KC-SERVICES0013: Failed authentication: java.lang.ClassCastException: class org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity cannot be cast to class org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper (org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity and org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @2db0f6b2)
        at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.get(InfinispanChangelogBasedTransaction.java:128)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionEntity(InfinispanUserSessionProvider.java:339)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:267)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:262)
        at org.keycloak.authentication.AuthenticationProcessor.lambda$attachSession$0(AuthenticationProcessor.java:1067)
        at org.keycloak.utils.LockObjectsForModification.lockObjectsForModification(LockObjectsForModification.java:77)
        at org.keycloak.utils.LockObjectsForModification.lockUserSessionsForModification(LockObjectsForModification.java:67)
        at org.keycloak.authentication.AuthenticationProcessor.attachSession(AuthenticationProcessor.java:1067)
        at org.keycloak.services.managers.AuthenticationManager.finishedRequiredActions(AuthenticationManager.java:1085)
        at org.keycloak.authentication.AuthenticationProcessor.authenticationComplete(AuthenticationProcessor.java:1134)
        at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:996)
        at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:362)
        at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:333)
        at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:325)
        at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:390)
        at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)

when removing authenticationSessions code blok,
 it works find.

why java.lang.ClassCastException occurs?

### Version

keycloak-23.0.4

### Expected behavior

sending data  good. 
    <distributed-cache name="authenticationSessions">
      <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>

### Actual behavior

2024-01-18 14:28:24,957 WARN  [org.keycloak.services] (executor-thread-1) KC-SERVICES0013: Failed authentication: java.lang.ClassCastException: class org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity cannot be cast to class org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper (org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity and org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @2db0f6b2)
        at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.get(InfinispanChangelogBasedTransaction.java:128)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionEntity(InfinispanUserSessionProvider.java:339)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:267)
        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:262)
        at org.keycloak.authentication.AuthenticationProcessor.lambda$attachSession$0(AuthenticationProcessor.java:1067)
        at org.keycloak.utils.LockObjectsForModification.lockObjectsForModification(LockObjectsForModification.java:77)
        at org.keycloak.utils.LockObjectsForModification.lockUserSessionsForModification(LockObjectsForModification.java:67)
        at org.keycloak.authentication.AuthenticationProcessor.attachSession(AuthenticationProcessor.java:1067)
        at org.keycloak.services.managers.AuthenticationManager.finishedRequiredActions(AuthenticationManager.java:1085)
        at org.keycloak.authentication.AuthenticationProcessor.authenticationComplete(AuthenticationProcessor.java:1134)
        at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:996)
        at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:362)
        at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:333)
        at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:325)
        at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:390)
        at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)

### How to Reproduce?

add below block at infinispan/server/conf/infinispan.xml(keycloak),  keycloak-23.0.4/conf/cache-ispn.xml
`    // here
    <distributed-cache name="authenticationSessions">
      <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
     // here
`

**Comment by taaho** [comment]
miss-matching distributed-cache &  cache   name error.
