### ISSUE TITLE
LDAP sync mistakenly thinks group contains group when it contains user

### ISSUE THREAD

**Issue by tomqwpl** [keycloak/keycloak#26354]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When attempting to synchronise users from ldap, with the "groups" mapper enabled, ldap sync thinks a group has another group as a member, when it has a user.

### Version

23.0.4

### Expected behavior

The groups synchronize correctly

### Actual behavior

LDAP sync fails with the following exception:
```
2024-01-20 12:15:40 2024-01-20 12:15:40,049 INFO  [org.keycloak.services] (executor-thread-17) KC-SERVICES0087: Syncing data for mapper 'groups' of type 'group-ldap-mapper'. Direction: fedToKeycloak
2024-01-20 12:15:40 2024-01-20 12:15:40,250 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-17) Uncaught server error: org.keycloak.models.ModelException: Couldn't resolve groups from LDAP. Fix LDAP or skip preserve inheritance. Details: Group 'Administrator' referenced as member of group 'Domain Admins' doesn't exist
2024-01-20 12:15:40     at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:186)
2024-01-20 12:15:40     at org.keycloak.services.resources.admin.UserStorageProviderResource.syncMapperData(UserStorageProviderResource.java:255)
2024-01-20 12:15:40     at org.keycloak.services.resources.admin.UserStorageProviderResource$quarkusrestinvoker$syncMapperData_7d7259fd8f486e4638b0a2f1d3b37905909372a0.invoke(Unknown Source)
2024-01-20 12:15:40     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-01-20 12:15:40     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-01-20 12:15:40     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
2024-01-20 12:15:40     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2024-01-20 12:15:40     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-01-20 12:15:40     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-01-20 12:15:40     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-01-20 12:15:40     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-01-20 12:15:40     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-01-20 12:15:40     at java.base/java.lang.Thread.run(Thread.java:840)
2024-01-20 12:15:40 Caused by: org.keycloak.storage.ldap.mappers.membership.group.GroupTreeResolver$GroupTreeResolveException: Group 'Administrator' referenced as member of group 'Domain Admins' doesn't exist
2024-01-20 12:15:40     at org.keycloak.storage.ldap.mappers.membership.group.GroupTreeResolver.getParentsTree(GroupTreeResolver.java:124)
2024-01-20 12:15:40     at org.keycloak.storage.ldap.mappers.membership.group.GroupTreeResolver.resolveGroupTree(GroupTreeResolver.java:53)
2024-01-20 12:15:40     at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:182)
2024-01-20 12:15:40     ... 12 more
2024-01-20 12:15:40 
```

### How to Reproduce?

I have a samba directory set up using the  nowsci/samba-domain docker image.
Out of the box, the LDAP structure looks like this:
![image](https://github.com/keycloak/keycloak/assets/42344626/8b0347da-c910-47c8-b517-f467b96ae78c)

When configuring the LDAP sync, I set the "Users DN" to `CN=Users,DC=corp,DC=example,DC=com`.

I then configure the groups-ldap-mapper. For "groups DN" I also set "CN=Users,DC=corp,DC=example,DC=com", and I suspect that's where the issue lies here. 

The sync error says "Group 'Administrator' referenced as member of group 'Domain Admins' doesn't exist". But "Administrator" isn't a group, it's a user.
The definition of DomainAdmins is as follows:
![image](https://github.com/keycloak/keycloak/assets/42344626/ea4c4a67-023f-4ae9-84ae-187ccb30033f)

Although I haven't tried it, I'm expecting that if I move the groups out into their own OU, the sync will work. However that's now how Samba directory comes out of the box, at least when started from this docker image.

**Comment by tomqwpl** [comment]
Indeed, moving the groups to a separate ou, not under the users DN makes the sync work.

**Comment by pedroigor** [comment]
There are so many settings to configure a group mapper that I'm unsure if one of those can help you here. Perhaps enabling `Ignore Missing Groups` can help but it sounds like a workaround.

We could also try to check the object classes when building the group hierarchy so that only entries with the object classes specified in `Group Object Classes` are recognized as a group.

**Comment by dune89** [comment]
> There are so many settings to configure a group mapper that I'm unsure if one of those can help you here. Perhaps enabling `Ignore Missing Groups` can help but it sounds like a workaround.
> 
> We could also try to check the object classes when building the group hierarchy so that only entries with the object classes specified in `Group Object Classes` are recognized as a group.

I can confirm that enabling "Ignore Missing Groups" in that mapper is a workaround.
