### ISSUE TITLE
We are using Keycloak v11.0.x with Cluster deployment and Randomly Keycloak Error Page showing to end users (500 Internal Server Error Page)

### ISSUE THREAD

**Issue by patelharigopal** [keycloak/keycloak#26437]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

We are using Keycloak v11.0.3 with Cluster 2 node deployment and Randomly Keycloak Error Page showing to users, we checked in Keycloak Log and erorr is "TimeoutException"
```
2023-10-26 00:00:10,788 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p19-t1) ISPN000136: Error executing command PutKeyValueCommand on Cache 'work', writing keys [task::ClearExpiredClientInitialAccessTokens]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 120541 from master:server-one
	at org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:169)
	at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
	at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Version

11.0.3

### Expected behavior

User never show this Keyclock error page

### Actual behavior

Keyclock showing a 500 Error Page to user

### How to Reproduce?

This is a Random issue

**Comment by jonkoops** [comment]
Closing this issue as it was reported against an older version of Keycloak, as mentioned in our issue template, we only accept issues reported against the latest version of Keycloak.
