### ISSUE TITLE
Workflow failure: User Federation Tests - LDAPSyncTest

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#26441]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

The following tests are failing when executed in MSAD and MSAD2019

```
java.lang.RuntimeException: org.keycloak.testsuite.runonserver.RunOnServerException: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.testsuite.client.KeycloakTestingClient$Server.fetch(KeycloakTestingClient.java:135)
	at org.keycloak.testsuite.federation.ldap.LDAPSyncTest.test05MissingLDAPUsernameSync(LDAPSyncTest.java:358)

```

```
java.lang.RuntimeException: org.keycloak.testsuite.runonserver.RunOnServerException: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.testsuite.client.KeycloakTestingClient$Server.fetch(KeycloakTestingClient.java:135)
	at org.keycloak.testsuite.federation.ldap.LDAPSyncTest.test09MembershipUsingDifferentAttributes(LDAPSyncTest.java:512)
```

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by miquelsi** [comment]
This is a problem with the MSAD instances, not a test error as such. Closing.
