### ISSUE TITLE
LOGIN_ERROR when redirect uri is "file://..."

### ISSUE THREAD

**Issue by nicolasguilhem** [keycloak/keycloak#26492]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Login request ends with "400 Bad request" when redirect uri is "file://...".

Use case is : authentication is done using keycloak js adapter with silent sso in electron application installed on local machine (that why redirect uri is "file://...").

Stack trace is : 

>>>
 ```
2024-01-25 11:29:32,677 WARN  [org.keycloak.events] (default task-23) type=LOGIN_ERROR, realmId=FA-EDTSPC, clientId=fa-ihm-spc, userId=null, ipAddress=10.250.4.241, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=file:///assets/silent-check-sso.html, code_id=15c8fc25-3add-47c1-a8cc-c267f7a278ec, response_mode=fragment, authSessionParentId=15c8fc25-3add-47c1-a8cc-c267f7a278ec, authSessionTabId=8Ih13_11Uis
2024-01-25 11:30:43,736 WARN  [org.keycloak.services] (default task-27) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: Failed to create URI: null
        at org.keycloak.keycloak-common@11.0.2//org.keycloak.common.util.KeycloakUriBuilder.buildFromValues(KeycloakUriBuilder.java:594)
   at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
        at io.undertow.core@2.1.3.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
        at io.undertow.core@2.1.3.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: empty host name
        at org.keycloak.keycloak-common@11.0.2//org.keycloak.common.util.KeycloakUriBuilder.buildString(KeycloakUriBuilder.java:429)
        at org.keycloak.keycloak-common@11.0.2//org.keycloak.common.util.KeycloakUriBuilder.buildFromValues(KeycloakUriBuilder.java:590)
        ... 80 more
 
```
>>>

### Version

11.0.2

### Expected behavior

Login success

### Actual behavior

400 BAD request on login

### How to Reproduce?

Login with keycloak using keycloak js adapter with silent sso and redirect uri as "file://..."

**Comment by jonkoops** [comment]
This issue was reported for an older version of Keycloak, as stated in the issue template we only accept issues tested against the latest version of Keycloak.
