### ISSUE TITLE
Keycloak UI meets "Internal Sever Error" after save "Refresh Token Max Reuse" number

### ISSUE THREAD

**Issue by yanpzhan** [keycloak/keycloak#26597]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When save "Refresh Token Max Reuse" number, the UI page went blank with error: "Internal Sever Error" 
![Screenshot from 2024-01-30 00-21-33](https://github.com/keycloak/keycloak/assets/7313189/13040ab7-7b7c-40e0-b85a-2a759153a653)
![Screenshot from 2024-01-30 00-38-55](https://github.com/keycloak/keycloak/assets/7313189/d058cfaa-8c31-45f0-8ef6-29f418537e8e)

### Version

23.0.5

### Expected behavior

Should save successfully without error.Internal Sever Error

### Actual behavior

The page went to blank with error "Internal Sever Error".
See logs in keycloak pod:
2024-01-30 10:18:01,057 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-17) Uncaught server error: java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:678)
	at java.base/java.lang.Integer.valueOf(Integer.java:999)
	at org.keycloak.models.jpa.RealmAdapter.lambda$getUserActionTokenLifespans$2(RealmAdapter.java:593)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.keycloak.models.jpa.RealmAdapter.getUserActionTokenLifespans(RealmAdapter.java:593)
	at org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:241)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.prepareCachedRealm(RealmCacheSession.java:438)
	at org.keycloak.models.cache.infinispan.RealmCacheManager.computeSerialized(RealmCacheManager.java:142)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:420)
	at org.keycloak.models.jpa.JpaRealmProvider.getRealmByName(JpaRealmProvider.java:162)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.prepareCachedRealmByName(RealmCacheSession.java:480)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.lambda$getRealmByName$0(RealmCacheSession.java:472)
	at org.keycloak.models.cache.infinispan.RealmCacheManager.computeSerialized(RealmCacheManager.java:142)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:472)
	at org.keycloak.services.managers.RealmManager.getRealmByName(RealmManager.java:98)
	at org.keycloak.services.resources.RealmsResource.resolveRealmAndUpdateSession(RealmsResource.java:180)
	at org.keycloak.services.resources.RealmsResource.getProtocol(RealmsResource.java:105)
	at org.keycloak.services.resources.RealmsResource$quarkusrestinvoker$getProtocol_b2af2a2de155d6f3564a200a8d3634cdf6f57aa2.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

### How to Reproduce?

1. Login with admin.
2. Go to "Realm Settings"->"Tokens" tab, enable "Revoke Refresh Token", set number for "Refresh Token Max Reuse", click "Save".

**Comment by antikalk** [comment]
For me it also look like all realm related calls are failing afterwards. This also includes loading the list of realms. This could be a rather serious issue...

**Comment by ssilvert** [comment]
I have reproduced this on the nightly build.  Also note that having zero for `Refresh token max reuse` does not matter.  I tried a value of 1 and still got a corrupted database.

This is not a UI issue.  Transferring to core.

**Comment by dasniko** [comment]
I can also confirm this and that it's not related to `Refresh token max reuse`. Instead, I experienced same/similar behavior as @antikalk reported:
I found doubled entries for all `actionTokenGeneratedByUserLifespan.*` attributes for one realm in the database after I modified the related page in UI (`Tokens`). Then, I first deleted the doubled entries, with no success. After I deleted all `actionTokenGeneratedByUserLifespan.*` realm attributes, it was successful and the realm related requests start working again.

**Comment by iliuta** [comment]
Quite similar to this one:
https://github.com/keycloak/keycloak/issues/26665

**Comment by antikalk** [comment]
> I have reproduced this on the nightly build. Also note that having zero for `Refresh token max reuse` does not matter. I tried a value of 1 and still got a corrupted database.
> 
> This is not a UI issue. Transferring to core.

As @iliuta has pointed out in #26665 this issue was introduced with KC 23.0.5. It might be that it was undesirably introduced with this commit on the UI: https://github.com/keycloak/keycloak/commit/d9b2b7f82e14f7b60f18e2b23ee57a81aac798c1

Now that the values are send with the correct attribute name, the attributes need to have a correct value whereas an empty string seems to break the reading of the realm from the DB.

**Comment by iliuta** [comment]
In my humble opinion, no matter what attribute names the UI uses to send data to the API, this should not result in a corrupted database at all. At most, the API should respond with a 400 HTTP code and do nothing with the database. What should I do if I want to fine tune access token life span on a production server with hundreds of users live? How do I repair this?

**Comment by antikalk** [comment]
@dasniko yes this line is where the error occurs when an empty value is stored in the database:

https://github.com/keycloak/keycloak/blob/f2ff485b7fb96b6ea3ed598a6a3abff0f4b7bdda/model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java#L593

Values that can not be parsed to an Integer should just simply be ignored here.

**Comment by antikalk** [comment]
When the database got "corrupted" and you have direct access to the database, running this script can help you out for now:

```sql
delete from realm_attribute where name LIKE 'actionTokenGeneratedByUserLifespan.%' and value = '';
```

Hoping for a 23.0.6 hotfix though...
