### ISSUE TITLE
KC 22 + KC 23: NullPointerException "keyManagerFactory required for servers"

### ISSUE THREAD

**Issue by stekaa** [keycloak/keycloak#26603]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

After Upgrading from 21 to 22 and later to 23 from time to time there happen NullPointerExceptions when accessing keycloak (f.e. the webgui "welcome to keycloak"). 

`
2024-01-30 15:18:34,128 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: my.domain, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: my.domain, Admin: my.domain, Port: -1, Proxied: true
2024-01-30 15:18:36,388 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2024-01-30 15:18:36,532 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-01-30 15:18:36,655 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-01-30 15:18:36,755 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2024-01-30 15:18:36,758 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 8b9ca5f1-ec7a-41d0-9585-01a70bc53111, name: some-name
2024-01-30 15:18:36,770 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.21986
2024-01-30 15:18:38,785 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) some-name: no members discovered after 2005 ms: creating cluster as coordinator
2024-01-30 15:18:38,794 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [some-name|0] (1) [some-name]
2024-01-30 15:18:38,814 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `some-name`, physical addresses are `[xx.xx.xx.xx:37522]`
2024-01-30 15:18:38,822 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-01-30 15:18:39,281 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: some-name, Site name: null
2024-01-30 15:18:39,284 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-01-30 15:18:40,434 INFO  [io.quarkus] (main) Keycloak 23.0.5 on JVM (powered by Quarkus 3.2.10.Final) started in 7.406s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8080
2024-01-30 15:18:40,435 INFO  [io.quarkus] (main) Profile prod activated.
2024-01-30 15:18:40,435 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
2024-01-30 15:18:46,057 WARN  [io.netty.channel.ChannelInitializer] (vert.x-eventloop-thread-0) Failed to initialize a channel. Closing: [id: 0x9e3ca3a8, L:/127.0.0.1:8080 - R:/127.0.0.1:33500]: io.vertx.core.VertxException: java.lang.NullPointerException: keyManagerFactory required for servers
        at io.vertx.core.net.impl.SslContextProvider.createServerContext(SslContextProvider.java:134)
        at io.vertx.core.net.impl.SslContextProvider.createServerContext(SslContextProvider.java:102)
        at io.vertx.core.net.impl.SslChannelProvider.sslServerContext(SslChannelProvider.java:87)
        at io.vertx.core.net.impl.SslChannelProvider.createServerSslHandler(SslChannelProvider.java:148)
        at io.vertx.core.net.impl.SslChannelProvider.createServerHandler(SslChannelProvider.java:143)
        at io.vertx.core.http.impl.HttpServerWorker.configurePipeline(HttpServerWorker.java:134)
        at io.vertx.core.http.impl.HttpServerWorker.accept(HttpServerWorker.java:127)
        at io.vertx.core.http.impl.HttpServerWorker.accept(HttpServerWorker.java:50)
        at io.vertx.core.net.impl.TCPServerBase.lambda$listen$6(TCPServerBase.java:270)
        at io.vertx.core.net.impl.ServerChannelLoadBalancer.initChannel(ServerChannelLoadBalancer.java:61)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: keyManagerFactory required for servers
        at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:480)
        at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:179)
        at io.vertx.core.spi.tls.DefaultSslContextFactory.createContext(DefaultSslContextFactory.java:120)
        at io.vertx.core.spi.tls.DefaultSslContextFactory.create(DefaultSslContextFactory.java:89)
        at io.vertx.core.net.impl.SslContextProvider.createServerContext(SslContextProvider.java:126)
        ... 28 more
`

### Version

23.0.5

### Expected behavior

delivering website without any erros

### Actual behavior

java.lang.NullPointerException with 502 proxy error from webserver

### How to Reproduce?

Install 23.0.5, build keycloak, start keycloak (--optimized). Running a monitoring job which calls URL each minute. 10 out of 60 attempts produce the error. 

### Anything else?

Running Keycloak on SLES15 with openjdk 17.0.9 behind apache proxy

Unfortunately, I couldn't find any information about what is meant by "keyManagerFactory" and how to activate/install it.

Thank you in advance for any troubleshooting tips. If additional information is needed, I'LL try to provide it.

**Comment by shawkins** [comment]
> Unfortunately, I couldn't find any information about what is meant by "keyManagerFactory" and how to activate/install it.

This should be from the keycloak option https-certificate-key-file, which maps to the quarkus property quarkus.http.ssl.certificate.key-files. 

@stekaa @dwEntropy presumably you have https enabled correct? What environment are you on, what did you supply for the key file option, and do you see any logs related to the keycloak or quarkus options?

**Comment by shawkins** [comment]
Closing due to lack of feedback.

**Comment by stekaa** [comment]
Sorry for late reply. Github didn't inform about your answers :-/

Yes, I have enabled https (certificate and private key files in PEM format. Setting parameter https-certificate-file and https-certificate-key-file in my *.conf file). I didn't set paramter https-key-store-file, because keycloak shouldn't use java keystore. 

I set parameter https-port to 8080, because keycloak works behind apache proxy. 

Parameter http-enabled is still set to true, but this shouldn't have any effect. 

my environment as written before: Running Keycloak on SLES15 with openjdk 17.0.9 behind apache proxy

After starting keycloak-Service (log-level=info) there are only these logs:
`
2024-03-06 14:35:16,456 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: server.mydomain.de, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: https://server.mydomain.de, Admin: server.mydomain.de, Port: -1, Proxied: true
2024-03-06 14:35:20,334 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2024-03-06 14:35:20,614 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-03-06 14:35:20,819 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-03-06 14:35:20,943 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2024-03-06 14:35:20,948 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: 860929b8-3823-47f2-8517-b12513c5f884, name: server-28537
2024-03-06 14:35:20,964 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.44659
2024-03-06 14:35:21,002 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-03-06 14:35:22,974 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) server-28537: no members discovered after 2005 ms: creating cluster as coordinator
2024-03-06 14:35:22,981 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [server-28537|0] (1) [server-28537]
2024-03-06 14:35:22,994 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `server-28537`, physical addresses are `[10.10.10.10:60195]`
2024-03-06 14:35:23,001 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-03-06 14:35:23,469 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: server-28537, Site name: null
2024-03-06 14:35:24,889 INFO  [io.quarkus] (main) Keycloak 23.0.5 on JVM (powered by Quarkus 3.2.10.Final) started in 12.864s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8080
2024-03-06 14:35:24,889 INFO  [io.quarkus] (main) Profile prod activated.
2024-03-06 14:35:24,889 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
`

If you need any further information, please let me know.

Please remember: most of the time there are no errors. 502 only happens from time to time. So my configuration should be correct basically.

**Comment by stekaa** [comment]
@shawkins: thank You very much for this hint.

We are running keycloak in proxy mode passthrough. So I disabled http. In addition there was a missconfiguration in our apache proxy configuration. proxypass was using http instead of https (weired).

Since the error only occurs sporadically, I check the behavior during the day.

**Comment by stekaa** [comment]
During the day no more NullPointerExceptions. Thanks again for Your help and hints!

**Comment by shawkins** [comment]
> During the day no more NullPointerExceptions. Thanks again for Your help and hints!

Great, we'll evaluate if there's some validation the server should be doing to help call this out sooner.

**Comment by shawkins** [comment]
Captured an upstream issue on this and will leave this closed on our side.
