### ISSUE TITLE
Unhandled exception in vertx causes HTTP endpoint to become unresponsive

### ISSUE THREAD

**Issue by breakwaterlabs** [keycloak/keycloak#26671]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

Under certain situations, the web interface can crash and become unresponsive until the container is restarted. This manifests with the error below.

Note that this is a transcription, but the full logs will be posted shortly.

```
2024-01-30 10:31:43,257 WARN [io.netty.channel.DefaultChannelPipeline] (vert.x-eventloop-thread-0) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: java.net.SocketException: Connection reset
   at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
   at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
   at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254)
   at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
   at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.base/java.lang.Thread.run(Thread.java:840)

2024-01-30 10:31:49,475 WARN <--- identical to prior io.netty.channel.DefaultChannelPipeline error--->

2024-01-30 10:31:51,007 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-68) Uncaught server error: java.lang.NullPointerException
   at io.vertx.core.net. impl.HostAndPortImpl.<init>(HostAndPortImpl.java:141)
   at io.vertx.core.net.HostAndPort.create(HostAndPort.java:20)
   at io.vertx.ext.web.impl.ForwardedParser.calculate(ForwardedParser.java:137)
   at io.vertx.ext.web.impl.ForwardedParser.scheme(ForwardedParser.java:70)
   at io.vertx.ext.web.impl.HttpServerRequestWrapper.scheme(HttpServerRequestWrapper.java:178)
   at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.getRequestScheme(VertxResteasyReactiveRequestContext.java:189)
   at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getScheme(ResteasyReactiveRequestContext.java:463)
   at org.jboss.resteasy.reactive.server.jaxrs.UriInfoImpl.getBaseUri(UriInfoImpl.java:128)
   at org.keycloak.urls.HostnameProvider.getScheme(HostnameProvider.java:51)
   at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.fromFrontEndUrl(DefaultHostnameProvider.java:177)
   at org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider.getScheme(DefaultHostnameProvider.java:86)
   at org.keycloak.models.KeycloakUriInfo.<init>(KeycloakUriInfo.java:50)
   at org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:79)
   at org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:86)
   at org.keycloak.services.resources.WelcomeResource.getWelcomePage(WelcomeResource.java:87)
   at org.keycloak.services.resources.WelcomeResource$quarkusrestinvoker$getWelcomePage_abcd01234567890012345678900123456789012345.invoke(Unknown Source)
   at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
   at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
   at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
   at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
   at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.base/java.lang.Thread.run(Thread.java:840)

2024-01-30 10:32:02,163 WARN <--- identical to prior io.netty.channel.DefaultChannelPipeline error--->
```

### Version

23.0.3

### Expected behavior

If an error occurs in the underlying HTTP server, it should be caught and handled gracefully-- if necessary, by killing and reinitializing the HTTP listener.

### Actual behavior

The server never recovers and HTTP remains unresponsive.

### How to Reproduce?

This is still being investigated, but there are two primary suspects at the moment:

VDI is in use, and it is possible that a VDI instance was killed while it had an active HTTP connection to keycloak. We have attempted to replicate this by hard stopping a client while it was connected to keycloak and were unsuccessful.

There is a security scan that checks for HTTP vulnerabilities (e.g. log4shell) that shows up as causing errors several days prior to this. It is possible that the requests it is sending are to blame, and we will update as we find more.

### Anything else?

As indicated above, the issue is not so much preventing "whatever the cause is" from bringing the HTTP server down, but that keycloak does not catch the exception and gracefully recover. The complete logs will be posted shortly (this is a transcription) which may provide more details on what that root cause is, and a corresponding bug should probably be filed against vertx both because of the crash itself and because it fails to handle the error.

**Comment by abstractj** [comment]
@stianst @jonkoops maybe this issue should be reassigned to the Cloud team?

**Comment by shawkins** [comment]
We'll probably need to tackle the issues here individually:
- the npe with HostAndPortImpl. @breakwaterlabs if possible can you provide all of the headers for your request? We have seen similar issues like https://github.com/quarkusio/quarkus/issues/37045 and it's easier to track down knowing what was sent.
- the server becoming unresponsive. That seems unexpected - @breakwaterlabs are you getting additional logs about vertx threads being blocked? Would it be possible to provide a thread dump? cc @vietj @cescoffier - does this sound familiar and is there any significance to the connection resets?
