### ISSUE TITLE
Overwriting Action Tokens Lifespan results in KeyCloak Admin Console crashing

### ISSUE THREAD

**Issue by finnwessel** [keycloak/keycloak#26733]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After overriding the “Forgot password” Action Token lifespan, KeyCloak first returns a 204 response code, but fails to read the config afterward.

### Version

23.0.5

### Expected behavior

KeyCloak sets the lifetime for the Forgot Password Action Token, can read and use this configuration.

### Actual behavior

The PUT request to `http://localhost:8080/admin/realms/master` succeeds with 204 status code.
The following GET request to  `http://localhost:8080/realms/master` fails with a 500 status code.

The Admin Console becomes unreachable (displays the Internal Server Error Page).

`http://localhost:8080/admin/master/console/` returns 500 response code.

Error-Log in Console:

```
2024-02-02 10:58:35,282 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.NumberFormatException: For input string: ""
2024-02-02T10:58:35.283273748Z 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
2024-02-02T10:58:35.283276032Z 	at java.base/java.lang.Integer.parseInt(Integer.java:678)
2024-02-02T10:58:35.283277655Z 	at java.base/java.lang.Integer.valueOf(Integer.java:999)
2024-02-02T10:58:35.283279175Z 	at org.keycloak.models.jpa.RealmAdapter.lambda$getUserActionTokenLifespans$2(RealmAdapter.java:593)
2024-02-02T10:58:35.283280709Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2024-02-02T10:58:35.283282213Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2024-02-02T10:58:35.283283824Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2024-02-02T10:58:35.283285334Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2024-02-02T10:58:35.283286846Z 	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
2024-02-02T10:58:35.283288356Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-02-02T10:58:35.283289867Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2024-02-02T10:58:35.283291375Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2024-02-02T10:58:35.283292885Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2024-02-02T10:58:35.283294408Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2024-02-02T10:58:35.283295925Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2024-02-02T10:58:35.283297427Z 	at org.keycloak.models.jpa.RealmAdapter.getUserActionTokenLifespans(RealmAdapter.java:593)
2024-02-02T10:58:35.283298941Z 	at org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:241)
2024-02-02T10:58:35.283300643Z 	at org.keycloak.models.cache.infinispan.RealmCacheSession.prepareCachedRealm(RealmCacheSession.java:438)
2024-02-02T10:58:35.283302193Z 	at org.keycloak.models.cache.infinispan.RealmCacheManager.computeSerialized(RealmCacheManager.java:142)
2024-02-02T10:58:35.283303727Z 	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:420)
2024-02-02T10:58:35.283313136Z 	at org.keycloak.models.jpa.JpaRealmProvider.getRealmByName(JpaRealmProvider.java:162)
2024-02-02T10:58:35.283315438Z 	at org.keycloak.models.cache.infinispan.RealmCacheSession.prepareCachedRealmByName(RealmCacheSession.java:480)
2024-02-02T10:58:35.283317042Z 	at org.keycloak.models.cache.infinispan.RealmCacheSession.lambda$getRealmByName$0(RealmCacheSession.java:472)
2024-02-02T10:58:35.283318570Z 	at org.keycloak.models.cache.infinispan.RealmCacheManager.computeSerialized(RealmCacheManager.java:142)
2024-02-02T10:58:35.283320104Z 	at org.keycloak.models.cache.infinispan.RealmCacheSession.getRealmByName(RealmCacheSession.java:472)
2024-02-02T10:58:35.283321632Z 	at org.keycloak.services.managers.RealmManager.getRealmByName(RealmManager.java:98)
2024-02-02T10:58:35.283323113Z 	at org.keycloak.services.resources.admin.AdminRoot.authenticateRealmAdminRequest(AdminRoot.java:172)
2024-02-02T10:58:35.283324639Z 	at org.keycloak.services.resources.admin.AdminRoot.getRealmsAdmin(AdminRoot.java:218)
2024-02-02T10:58:35.283326151Z 	at org.keycloak.services.resources.admin.AdminRoot$quarkusrestinvoker$getRealmsAdmin_45154ef53be93bae0f6a8d488a99e593258b537a.invoke(Unknown Source)
2024-02-02T10:58:35.283327793Z 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-02-02T10:58:35.283329350Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-02-02T10:58:35.283330931Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
2024-02-02T10:58:35.283332473Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2024-02-02T10:58:35.283333987Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-02-02T10:58:35.283335463Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-02-02T10:58:35.283336943Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-02-02T10:58:35.283338414Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-02-02T10:58:35.283339931Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-02-02T10:58:35.283341444Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-02-02T10:58:35.283342938Z 
```

### How to Reproduce?

Docker compose file used for deployment.

```yml
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14
    container_name: keycloak_postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
    container_name: keycloak_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
```
Steps in UI:
1. Access the admin dashboard with credentials `admin` & `admin`.
2. Access realm settings.
3. Select Tab `Tokens` (`http://localhost:8080/admin/master/console/#/master/realm-settings/tokens`) and scroll down to `Override Action Tokens`.
4. Set Lifetime for Forgot password token to 5 minutes. 

![Screenshot from 2024-02-02 11-57-03](https://github.com/keycloak/keycloak/assets/38720948/49e41d59-7296-4fd1-8d36-fbb8c34332b6)

Thereafter, you should get a success notification, but reloading the admin dashboard and any other action fails.

**Comment by finnwessel** [comment]
Duplicate of [#26597](https://github.com/keycloak/keycloak/issues/26597)
