### ISSUE TITLE
Workflow failure: Operator CI in OpenShift

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#26774]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

The Operator testsuite is failing when running in an OCP cluster:

```
2024-02-04 21:18:56  [ERROR] Errors: 
2024-02-04 21:18:56  [ERROR]   ClusteringTest » Runtime java.lang.RuntimeException: Failed to start quarkus
2024-02-04 21:18:56  [ERROR]   KeycloakDeploymentTest » NullPointer Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:56  [ERROR]   KeycloakIngressTest » NullPointer Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:56  [ERROR]   KeycloakServicesTest » NullPointer Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:56  [ERROR]   KeycloakTruststoresTests » NullPointer Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:56  [ERROR]   PodTemplateTest » NullPointer Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:56  [ERROR]   RealmImportTest » NullPointer Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:56  [ERROR]   WatchedSecretsTest » NullPointer Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:56  [INFO] 
2024-02-04 21:18:56  [ERROR] Tests run: 66, Failures: 0, Errors: 8, Skipped: 26
```

The root cause seems to be:

```
2024-02-04 21:18:52  java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2024-02-04 21:18:52  	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
2024-02-04 21:18:52  	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:706)
2024-02-04 21:18:52  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-02-04 21:18:52  	Suppressed: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2024-02-04 21:18:52  		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:915)
2024-02-04 21:18:52  		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:907)
2024-02-04 21:18:52  		at io.quarkus.test.junit.QuarkusTestExtension.interceptAfterAllMethod(QuarkusTestExtension.java:901)
2024-02-04 21:18:52  		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-02-04 21:18:52  		at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
2024-02-04 21:18:52  		... 1 more
2024-02-04 21:18:52  Caused by: java.lang.RuntimeException: Failed to start quarkus
2024-02-04 21:18:52  	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2024-02-04 21:18:52  	at io.quarkus.runtime.Application.start(Application.java:101)
2024-02-04 21:18:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-02-04 21:18:52  	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
2024-02-04 21:18:52  	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
2024-02-04 21:18:52  	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:605)
2024-02-04 21:18:52  	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
2024-02-04 21:18:52  	... 1 more
2024-02-04 21:18:52  Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to read configuration properties
2024-02-04 21:18:52  	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
2024-02-04 21:18:52  	... 8 more
2024-02-04 21:18:52  Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
2024-02-04 21:18:52  	SRCFG00050: operator.image in EnvConfigSource does not map to any root
2024-02-04 21:18:52  	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:73)
2024-02-04 21:18:52  	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:86)
2024-02-04 21:18:52  	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:724)
2024-02-04 21:18:52  	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
2024-02-04 21:18:52  	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
2024-02-04 21:18:52  	... 9 more
```
For a full log go to https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/302/execution/node/69/log/

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment]
@vmuzikar this is another variation of that issue - in our gha olm tests we didn't see operator.image being added as an env property. It will require yet another workaround, such as a new property on the Config class, or we'll need to move #26414 forward.

**Comment by vmuzikar** [comment]
Resolved by renaming `OPERATOR_IMAGE` parameter/env var in the QE pipeline. This does not affect upstream.
