### ISSUE TITLE
Workflow failure: Operator IT on OpenShift

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#26790]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
2024-02-05 15:55:47  [ERROR] org.keycloak.operator.testsuite.integration.WatchedSecretsTest.testSecretChangesArePropagated  Time elapsed: 76.867 s  <<< ERROR!
2024-02-05 15:55:47  org.awaitility.core.ConditionTimeoutException: Condition with org.keycloak.operator.testsuite.integration.WatchedSecretsTest was not fulfilled within 1 minutes.
2024-02-05 15:55:47  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
2024-02-05 15:55:47  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
2024-02-05 15:55:47  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
2024-02-05 15:55:47  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
2024-02-05 15:55:47  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:908)
2024-02-05 15:55:47  	at org.keycloak.operator.testsuite.integration.WatchedSecretsTest.testSecretChangesArePropagated(WatchedSecretsTest.java:92)
2024-02-05 15:55:47  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-02-05 15:55:47  	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
2024-02-05 15:55:47  	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
2024-02-05 15:55:47  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-02-05 15:55:47  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

For full log see https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/303/execution/node/69/log/

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment]
@miquelsi is this happening all the time or just occassionally?

If it's occassionally, let's see if we get more information from the event logging added by #26864 - there isn't enough to go by on just the log above.

**Comment by miquelsi** [comment]
@shawkins yes this is happening constantly for days now. You can see the latest log in https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/310/execution/node/69/log/

**Comment by shawkins** [comment]
The most suspisuous thing in the logs is:

```
2024-02-11 15:38:24  WARN: Event last seen 2024-02-11T20:36:27Z repeated 1 times - Warning SyncLoadBalancerFailed postgres-db.17b2e94c4e61e5d4 Error syncing load balancer: failed to ensure load balancer: error creating LB floatingip: Resource not found: [POST https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13696/v2.0/floatingips], error message: {"NeutronError": {"type": "ExternalGatewayForFloatingIPNotFound", "message": "External network 0e212597-e475-4c4a-a4fa-db71f84ec04c is not reachable from subnet a40c02bd-e365-4922-80a6-5b58a4fe66d6.  Therefore, cannot associate Port 212d41c2-2cbc-4e25-87c1-649ff534e6a9 with a Floating IP.", "detail": ""}}: {"NeutronError": {"type": "ExternalGatewayForFloatingIPNotFound", "message": "External network 0e212597-e475-4c4a-a4fa-db71f84ec04c is not reachable from subnet a40c02bd-e365-4922-80a6-5b58a4fe66d6.  Therefore, cannot associate Port 212d41c2-2cbc-4e25-87c1-649ff534e6a9 with a Floating IP.", "detail": ""}}
```
That could be making the pg instance not reachable - it would still be good to have logs from a failed container start that confirm that.

**Comment by miquelsi** [comment]
Issue still occurring. See https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/318/execution/node/69/log/

**Comment by shawkins** [comment]
@miquelsi @vmuzikar I wasn't sure if the previous pr would actually address this - but it did clean up the log and will help with some unnecessary resource allocation on openshift. With the cleaner log in this issue the problem is just with how the test is written - it's possible that each polling the test does to obtain the current log, it won't actually be available / contain the expected error because the pod is crash looping. We'll have to change the test logic to make this more foolproof.
