### ISSUE TITLE
Disabling "Reset OTP" in "Reset credentials" flow throws error on "forgot password"

### ISSUE THREAD

**Issue by mschnitzler** [keycloak/keycloak#26834]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

According to the [server administration guide](https://www.keycloak.org/docs/latest/server_admin/#enabling-forgot-password) it is recommended to disable "reset OTP" in the "reset credentials" flow if the OTP should not be reset by email.
However, if the user clicks the link in the "reset password" mail an error is thrown.

### Version

23.0.6

### Expected behavior

The form to set a new password should be displayed. However, I'm not sure if the user should have to provide the OTP in the next step or if the user should already be logged without OTP in that case.

### Actual behavior

An error message is displayed. The log shows the following error:

```
2024-02-06 15:48:33,534 WARN  [org.keycloak.services] (executor-thread-34) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1039)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:885)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:364)
	at org.keycloak.authentication.actiontoken.ActionTokenContext.processFlow(ActionTokenContext.java:160)
	at org.keycloak.authentication.actiontoken.resetcred.ResetCredentialsActionTokenHandler.handleToken(ResetCredentialsActionTokenHandler.java:67)
	at org.keycloak.authentication.actiontoken.resetcred.ResetCredentialsActionTokenHandler.handleToken(ResetCredentialsActionTokenHandler.java:39)
	at org.keycloak.services.resources.LoginActionsService.handleActionToken(LoginActionsService.java:650)
	at org.keycloak.services.resources.LoginActionsService.executeActionToken(LoginActionsService.java:509)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$executeActionToken_035bd2a6e85ccb740354c6ef1893bd855922beec.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-02-06 15:48:33,537 WARN  [org.keycloak.events] (executor-thread-34) type="RESET_PASSWORD_ERROR", realmId="fbc63abe-050a-4ae2-997b-b407f8371e20", clientId="account-console", userId="04018efd-5574-4011-9ad0-6576f2476f1d", ipAddress="172.17.0.1", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", token_id="a8b8431a-27fe-41f2-ba3a-f5a8ef4c6ea6", action="reset-credentials", response_type="code", redirect_uri="http://localhost:8080/realms/test/account/#/", remember_me="false", code_id="3bfc3946-4120-4be4-b3ec-06236052c2ca", response_mode="fragment", username="test1"
```

### How to Reproduce?

1. Set up a realm with mail settings (to receive the "reset password" mail)
2. Enable "forget password" for the realm.
3. Follow the [instructions in the server administration guide](https://www.keycloak.org/docs/latest/server_admin/#enabling-forgot-password) to disable "reset OTP":
  - set "reset OTP" requirement to "disabled" in "reset credentials" flow
  - ensure "update password" is "enabled" in "required actions"
 4. Create a user and configure OTP for that user. Verify the login and log off again.
 5. Click the login form's "forgot password" link and provide user name to receive the "reset password" mail.
 6. Click the link in the "reset password" mail ---> error

**Comment by rmartinc** [comment]
Hi @mschnitzler!

I think the documentation is not OK, to disable the reset OTP just set to `Disabled` the `Reset - Conditional OTP` (the sub-workflow). If you just disabled the last step `Reset OTP` then there is one condition and no real executor step, so the flow executes nothing and it finished with no success (so it's failed).

Please test that disabling the sub-workflow instead of the step works for you, check the OTP is not reset and maintains the same too.

If that works for you, can you please send a PR to change the documentation?

It would be modifying this [line](https://github.com/keycloak/keycloak/blob/main/docs/documentation/server_admin/topics/login-settings/forgot-password.adoc?plain=1#L41), changing `set the `Reset - Conditional OTP` sub-workflow requirement to *Disabled*`.

**Comment by rmartinc** [comment]
@mschnitzler Perfect, thanks!

Regarding your question, the reset OTP toggle is just that, if the reset credentials should also reset the OTP or just the password (if enabled, the user is requested to change password and setup OTP again in the action). It does not perform anything else. Reset credential is one of the [action tokens](https://www.keycloak.org/docs/latest/server_development/#_action_token_handler_spi) managed by keycloak. The login just checks the token (no OTP or other second factor authentication for it).

**Comment by rmartinc** [comment]
@mschnitzler My previous comment was wrong. I forgot that the reset-credentials flow is also executed on login. So I think you can do exactly what you wanted.

1. Duplicate the reset credentials workflow.
2. In the copy set Reset OTP to Disabled (or remove it).
3. Add step OTP Form instead of it as Required.
4. Action, Bind flow this new flow to the reset credentials flow.

![Screenshot from 2024-02-08 12-32-06](https://github.com/keycloak/keycloak/assets/26901232/e52a9803-2cba-4861-b95a-a4bc25c13706)

This way the OTP is not reset (disabled) but OTP form is executed if configured for the reset credentials action. Give it a try. And sorry for my previous misleading comment.

**Comment by it-1313** [comment]
Hello,

thanks, I have a question in this regard to see whether I can have the "perfect" login/reset flow. 

I don't understand the last step "... if configured for the reset credentials action". In Authentication -> required actions, I don't have a reset credentials action. I have "Configure OTP" and this is enabled, and also a default action.
<img width="2190" height="965" alt="Image" src="https://github.com/user-attachments/assets/961a3fd9-9023-417a-9510-f866144d5250" />


I also don't understand what "condition - user configured -> conditional" actually means -> this flow is executed if "configure OTP" is a "required user action" for a specific user (configured for the user under "Users")? What would "Alternative" mean then? If I create another subflow on the same level as "Copy of reset credentials Reset - Conditional OTP"?

I have exactly the same flow, and bind it to the reset credentials flow:
<img width="2036" height="900" alt="Image" src="https://github.com/user-attachments/assets/dbd6c7e8-ec3e-423c-8371-817f7f78cbcd" />


I'm not sure I can achieve 100% what I would like to. So far I have:
1) login requires OTP (through "configure OTP" as a required user action for all existing users and setting it as default action for new users)
2) password reset does not require OTP reset (makes life a lot easier for users, otherwise they end up with multiple OTPs in their authenticator and don't know which one to use).

however, I'm still missing:
3) optionally reset also OTP during password reset if a user lost the OTP
