### ISSUE TITLE
Group not found in list after creation

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#26983]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

ConcurrencyTest#createGroup started failing on the 27th October 2023, which was the day after https://github.com/keycloak/keycloak/commit/69497382d8cc6c622e815184d9bc27cb0dc6a400 was merged.

The error is that a newly created group is not found in the group list:
```
2024-02-13T07:58:05.2629139Z ConcurrencyTest ++ java.lang.AssertionError: Group g-79 [affcccbf-f981-43a0-8f85-48dd664a9c87]  not found in group list
2024-02-13T07:58:05.2630974Z ConcurrencyTest ++ 	at org.junit.Assert.fail(Assert.java:89)
2024-02-13T07:58:05.2631978Z ConcurrencyTest ++ 	at org.junit.Assert.assertTrue(Assert.java:42)
2024-02-13T07:58:05.2633037Z ConcurrencyTest ++ 	at org.junit.Assert.assertFalse(Assert.java:65)
2024-02-13T07:58:05.2634509Z ConcurrencyTest ++ 	at org.keycloak.testsuite.admin.concurrency.ConcurrencyTest$CreateGroup.run(ConcurrencyTest.java:248)
2024-02-13T07:58:05.2637014Z ConcurrencyTest ++ 	at org.keycloak.testsuite.admin.concurrency.AbstractConcurrencyTest.lambda$run$0(AbstractConcurrencyTest.java:94)
2024-02-13T07:58:05.2638885Z ConcurrencyTest ++ 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-02-13T07:58:05.2640522Z ConcurrencyTest ++ 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-02-13T07:58:05.2642345Z ConcurrencyTest ++ 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-02-13T07:58:05.2643793Z ConcurrencyTest ++ 	at java.base/java.lang.Thread.run(Thread.java:840)
```

The mentioned PR also introduced a hack to retry listing the groups after the group was created:
https://github.com/keycloak/keycloak/blob/ee126f73e532baaabd8c82b94df8c70031ff650b/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/concurrency/ConcurrencyTest.java#L238-L248

However, this should not be needed the group should be available immediately. As a side-note the retry mechanism above has no wait in-between the retries, so will just pull the endpoint many times in a row.

### Version

main

### Expected behavior

Groups are available in the list after they have been created

### Actual behavior

Groups are not available in the list even after retrying several times

### How to Reproduce?

Run ConcurrencyTest.createGroup, or view results from https://github.com/keycloak/keycloak/issues/24337

**Comment by alice-wondered** [comment]
I've gained a lot more understanding of the infinispan workings on this project and discovered a pretty hidden bug while trying to resolve this issue. 

The issue relating specifically to that bug is linked above and should help to update the solution for this issue to preserve the pagination cache entry as well

**Comment by stianst** [comment]
.
