### ISSUE TITLE
Keycloak admin console page loading indefinitely.

### ISSUE THREAD

**Issue by Krishna-PriyaV** [keycloak/keycloak#26982]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I am trying to upgrade Keycloak from version 20.0.0 to 23.0.4.
When I try to access admin console page from welcome page, it's loading indefinitely and can't login to keycloak.

![image](https://github.com/keycloak/keycloak/assets/129741076/7d051f24-43ca-41ca-8689-b0d42bfc1adf)

I have tried the following Docker image and ec2 container for 23.0.4.

**Docker File:**

```dockerfile
FROM public.ecr.aws/docker/library/maven:3.8.4-openjdk-17-slim as maven-builder
COPY native-s3-pom.xml ./
RUN mvn package -f native-s3-pom.xml
FROM quay.io/keycloak/keycloak:23.0.4 as keycloak-builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

ENV KC_DB=mysql
ENV KC_FEATURES=preview,token-exchange,admin-fine-grained-authz
ENV KC_CACHE_STACK=ec2
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV PROXY_ADDRESS_FORWARDING=true
ENV KC_PROXY=edge
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=false

COPY --from=maven-builder --chown=keycloak /s3-native-ping-bundle-*-jar-dependencies.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:23.0.4
COPY --from=keycloak-builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=keycloak-builder /opt/keycloak/providers/* /opt/keycloak/providers/
COPY themes /opt/keycloak/themes/
COPY keycloak.conf /opt/keycloak/conf/

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh show-config

ENV KC_DB=mysql
ENV KC_DB_URL=<url>
ENV KC_DB_USERNAME=<usernm>
ENV KC_DB_PASSWORD=<pswrd>
ENV KC_HOSTNAME=myurl.com
ENV KC_HOSTNAME_STRICT=false

ENTRYPOINT ["/opt/keycloak/bin/kc.sh" , "start-dev" , "--hostname-strict-https=false"]
```

**Logs:**

```
February 08, 2024 at 22:04 (UTC+5:30)	2024-02-08 16:34:17,334 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-2) Failed to find ADMIN theme keycloak-extended, using built-in themes	
February 08, 2024 at 22:03 (UTC+5:30)	2024-02-08 16:33:50,882 WARN [io.vertx.core.impl.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2191 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
February 08, 2024 at 22:03 (UTC+5:30)	at java.base@17.0.10/java.util.AbstractList.subList(AbstractList.java:499)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.theme.beans.MessageFormatterMethod.exec(MessageFormatterMethod.java:47)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.MethodCall._eval(MethodCall.java:62)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Expression.eval(Expression.java:101)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.ListLiteral.getModelList(ListLiteral.java:92)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.MethodCall._eval(MethodCall.java:60)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Expression.eval(Expression.java:101
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.BuiltInsForOutputFormatRelated$AbstractConverterBI.calculateResult(BuiltInsForOutputFormatRelated.java:50)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.MarkupOutputFormatBoundBuiltIn._eval(MarkupOutputFormatBoundBuiltIn.java:40)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Expression.eval(Expression.java:101)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.visit(Environment.java:335)
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.visit(Environment.java:377)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.invokeNestedContent(Environment.java:621)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.visit(Environment.java:335)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.visit(Environment.java:341)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.visit(Environment.java:377)
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:877)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.invokeMacro(Environment.java:813)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.visit(Environment.java:335)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.visit(Environment.java:341)
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.core.Environment.process(Environment.java:314)	
February 08, 2024 at 22:03 (UTC+5:30)	at freemarker.template.Template.process(Template.java:383)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.services.error.KeycloakErrorHandler.getResponse(KeycloakErrorHandler.java:107)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.services.error.KeycloakErrorHandler$1.run(KeycloakErrorHandler.java:62)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.services.error.KeycloakErrorHandler$1.run(KeycloakErrorHandler.java:59)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:382)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:365)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.keycloak.services.error.KeycloakErrorHandler.toResponse(KeycloakErrorHandler.java:58)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.jboss.resteasy.reactive.server.core.RuntimeExceptionMapper.mapException(RuntimeExceptionMapper.java:99)
February 08, 2024 at 22:03 (UTC+5:30)	at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.mapExceptionIfPresent(ResteasyReactiveRequestContext.java:337)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.jboss.resteasy.reactive.server.handlers.ExceptionHandler.handle(ExceptionHandler.java:15)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)	
February 08, 2024 at 22:03 (UTC+5:30)	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:382)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:375)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:82)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:65)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:177)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:153)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:179)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:174)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:124)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)	
February 08, 2024 at 22:03 (UTC+5:30)	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)	
```

### Version

23.0.4

### Expected behavior

Admin console page will be load and user can enter username and password when we click on admin console button from keycloak welcome page.

### Actual behavior

It gets stuck on the Loading the admin console page.

### How to Reproduce?

- Use the above Dockerfile to build an image and run the keycloak

### Anything else?
When I comment copy theme line in docker file (COPY themes /opt/keycloak/themes/), admin console page will be load and user can login to keycloak, but custom themes wont be present in the themes dropdown.
_No response_

**Comment by hmlnarik** [comment]
> `February 08, 2024 at 22:04 (UTC+5:30)	2024-02-08 16:34:17,334 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-2) Failed to find ADMIN theme keycloak-extended, using built-in themes`

This is due to invalid `keycloak-extended` theme configured for admin console. Keycloak project does not provide or support `keycloak-extended` theme, please reach out to its authors to check compatibility with Keycloak 23.

Please note that if the theme is based on admin console theme v1, this has been removed in [Keycloak 22](https://www.keycloak.org/docs/latest/release_notes/index.html#account-console-v1-removal).

**Comment by Krishna-PriyaV** [comment]
> > `February 08, 2024 at 22:04 (UTC+5:30)	2024-02-08 16:34:17,334 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-2) Failed to find ADMIN theme keycloak-extended, using built-in themes`
> 
> This is due to invalid `keycloak-extended` theme configured for admin console. Keycloak project does not provide or support `keycloak-extended` theme, please reach out to its authors to check compatibility with Keycloak 23.
> 
> Please note that if the theme is based on admin console theme v1, this has been removed in [Keycloak 22](https://www.keycloak.org/docs/latest/release_notes/index.html#account-console-v1-removal).

Thank you for the response.. I updated the copy theme's path to exact folder name of the custom themes in docker file.
It's working fine now.
