### ISSUE TITLE
Workflow failure: Operator CI - KeycloakTruststoresTests#testTrustroreExists

### ISSUE THREAD

**Issue by wojnarfilip** [keycloak/keycloak#27080]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Recently there were some failures in Operator CI both in GHA and Jenkins

```
Error:  Errors: 
Error:    KeycloakTruststoresTests.testTrustroreExists:63 » ConditionTimeout Assertion condition defined as a org.keycloak.operator.testsuite.utils.K8sUtils 
expected: true
 but was: false within 5 minutes.
[INFO] 
Error:  Tests run: 112, Failures: 0, Errors: 1, Skipped: 1
```

GHA job: https://github.com/keycloak/keycloak/actions/runs/7923983529/job/21634994332
Jenkins job: https://keycloak-jenkins.com/view/OpenShift/job/rhbk-operator-test-pipeline/314/

### Version

latest

### Regression

- [ ] The issue is a regressions

### Expected behavior

.

### Actual behavior

.

### How to Reproduce?

.

**Comment by shawkins** [comment]
The pod seems to be having trouble finding / mounting secrets:

```
2024-02-16T00:44:02.3616540Z WARN: Event last seen 2024-02-16T00:43:51Z repeated 1 times - Warning Failed example-kc-0.17b431108f7f7beb Error: secret "example-kc-initial-admin" not found
2024-02-16T00:44:02.3618444Z Feb 16, 2024 12:44:02 AM org.keycloak.operator.testsuite.integration.BaseOperatorTest logEvents
2024-02-16T00:44:02.3621358Z INFO: Event last seen 2024-02-16T00:41:45Z repeated 1 times - Normal Scheduled example-kc-0.17b4311073f675b0 Successfully assigned keycloak-test-7924d2e7-484a-48e9-95f9-a2fbb33376ee/example-kc-0 to minikube
2024-02-16T00:44:02.3625728Z Feb 16, 2024 12:44:02 AM org.keycloak.operator.testsuite.integration.BaseOperatorTest logEvents
2024-02-16T00:44:02.3628145Z INFO: Event last seen 2024-02-16T00:41:45Z repeated 1 times - Normal SuccessfulCreate example-kc.17b4311073c257fe create Pod example-kc-0 in StatefulSet example-kc successful
2024-02-16T00:44:02.3630178Z Feb 16, 2024 12:44:02 AM org.keycloak.operator.testsuite.integration.BaseOperatorTest logEvents
2024-02-16T00:44:02.3633909Z WARN: Event last seen 2024-02-16T00:41:03Z repeated 1 times - Warning FailedMount example-kc-0.17b43106b13262fa Unable to attach or mount volumes: unmounted volumes=[truststore-secret-xyz], unattached volumes=[truststore-secret-xyz keycloak-tls-certificates kube-api-access-2qgv6]: timed out waiting for the condition
2024-02-16T00:44:02.3636194Z Feb 16, 2024 12:44:02 AM org.keycloak.operator.testsuite.integration.BaseOperatorTest logEvents
2024-02-16T00:44:02.3637623Z WARN: Event last seen 2024-02-16T00:40:04Z repeated 1 times - Warning FailedMount example-kc-0.17b430ea1d0807a0 MountVolume.SetUp failed for volume "truststore-secret-xyz" : secret "xyz" not found
2024-02-16T00:44:02.3638856Z Feb 16, 2024 12:44:02 AM org.keycloak.operator.testsuite.integration.BaseOperatorTest logEvents
2024-02-16T00:44:02.3639892Z INFO: Event last seen 2024-02-16T00:39:35Z repeated 1 times - Normal Sync example-kc-ingress.17b430ea467a80e9 Scheduled for sync
2024-02-16T00:44:02.3640818Z Feb 16, 2024 12:44:02 AM org.keycloak.operator.testsuite.integration.BaseOperatorTest logEvents
2024-02-16T00:44:02.3642378Z WARN: Event last seen 2024-02-16T00:39:01Z repeated 1 times - Warning FailedMount example-kc-0.17b430ea58a7e51e MountVolume.SetUp failed for volume "keycloak-tls-certificates" : failed to sync secret cache: timed out waiting for the condition
```

For example-kc-initial-admin to not exist there would have to be some odd case preventing KeycloakAdminSecretDependentResource from running - but there are no logs to that effect. I don't think this issue is indicative of a problem in the operator.

**Comment by shawkins** [comment]
@wojnarfilip if this reoccurs, let's reopen to triage further. As of now it appears to be a one off environmental issue, and not directly related to operator / keycloak logic.

**Comment by shawkins** [comment]
Occurred for me also https://github.com/keycloak/keycloak/actions/runs/8111402105/job/22170832812

**Comment by shawkins** [comment]
Trying locally with a remote test doesn't seem to be reproducible - we will keep reconciling every minute and even if the secret is deleted the operator will respond to that event and recreate the secret. Also ran a test 50 times, and still didn't reproduce this.

At the very least we need the operator log to determine what could possibly be going wrong here - it seems possible that there are unseen errors there.

Similar to: #26836 but that log makes no mention of the initial-admin secret in the status.

**Comment by shawkins** [comment]
> Similar to: https://github.com/keycloak/keycloak/issues/26836 but that log makes no mention of the initial-admin secret in the status.

That appears to be occurring on the realm secret instead.

@vmuzikar @ahus1 this could be related to a kube issue. The exact same problem reported here https://github.com/kubernetes/kubernetes/issues/105204#issuecomment-1760617515 - the "not registered" version of this appears to have been re-reported a couple of times. So another thing to try, and should probably be done anyway, is to move up the kuberenetes version in the operator-ci. It seems to be at 4.11 currently.

**Comment by vmuzikar** [comment]
@shawkins Makes sense to me to upgrade k8s version.

**Comment by shawkins** [comment]
https://github.com/keycloak/keycloak/actions/runs/8282314485/job/22668539756 confirms this is an operator rather than a kube issue - the initial admin secret is not listed.

**Comment by shawkins** [comment]
The only way I can recreate this issue is if the initial KeycloakAdminSecretDependentResource reconconciliation is stalled completely - such that it prevents any other reconciliations from the KeycloakController. Might need to trigger a threaddump as well.

**Comment by shawkins** [comment]
After including the threaddump and some additional logging the only conclusion is that we're missing a delete event. The sequence would be something like:
- the test is run in such as way as to have resources, in particular secrets, that overlap with a previous test.
- the cache state includes the old entry prior to garbage collection by the time we start reconciling the new
- the resource is deleted, but we don't process / receive the delete event so the entry stays in cache - and thus we don't try to recreate the secret.

I've still had no luck reproducing this locally, but it is happening with some regularity with gha.

**Comment by shawkins** [comment]
https://productionresultssa11.blob.core.windows.net/actions-results/5e4515c9-d3a4-4e17-8227-f8c85705c0da/workflow-job-run-c7d9db75-631a-5a4c-bfea-e177da40dcb7/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-22T15%3A09%3A43Z&sig=%2FT6sq49RZVVp9v83Zx8d6uKvUI7hdIh5gwchEqH1hrk%3D&sp=r&spr=https&sr=b&st=2024-03-22T14%3A59%3A38Z&sv=2021-12-02 shows a failure with potentially related behavior.

This time we we did get an operator log with an error:

```
2024-03-22T14:40:57.4018875Z WARN: keycloak-operator log: .event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:64)
2024-03-22T14:40:57.4021108Z 	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:450)
2024-03-22T14:40:57.4023044Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-03-22T14:40:57.4024631Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-03-22T14:40:57.4025822Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-22T14:40:57.4038982Z Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.96.0.1:443/apis/k8s.keycloak.org/v2alpha1/namespaces/keycloak-test-a5428271-7dba-4620-92fc-463efc276f07/keycloaks/example-kc/status. Message: Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "example-kc": StorageError: invalid object, Code: 4, Key: /registry/k8s.keycloak.org/keycloaks/keycloak-test-a5428271-7dba-4620-92fc-463efc276f07/example-kc, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 21af1eb9-a2ee-464a-994f-cffdf7cdaa82, UID in object meta: . Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=k8s.keycloak.org, kind=keycloaks, name=example-kc, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "example-kc": StorageError: invalid object, Code: 4, Key: /registry/k8s.keycloak.org/keycloaks/keycloak-test-a5428271-7dba-4620-92fc-463efc276f07/example-kc, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 21af1eb9-a2ee-464a-994f-cffdf7cdaa82, UID in object meta: , metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
```

That shows we're trying to take action against a version of the resource that no longer exists, so the cache is not up-to-date at that point. However since there isn't any more debug logging enabled there's no clear picture of how things went from there.

**Comment by shawkins** [comment]
To finish off the thought from the previous comment - the operator is expected to recover gracefully from that situation as soon as it gets the relevant delete event. With more targeted logging of the delete events that the operator sdk is seeing from https://github.com/keycloak/keycloak/actions/runs/8398312611/job/23003088982 we see
```
2024-03-23T01:53:10.8550477Z 2024-03-23 01:47:29,625 INFO  [org.key.ope.con.KeycloakAdminSecretDependentResource$DeleteLogger] (-555943503-pool-9-thread-25) Delete example-kc-initial-admin 6c33d05c-08ae-47b0-a3c6-1122cee02aec false
2024-03-23T01:53:10.8552298Z 2024-03-23 01:47:29,640 INFO  [org.key.ope.con.KeycloakAdminSecretDependentResource$DeleteLogger] (-555943503-pool-9-thread-25) Delete example-kc-initial-admin 6c33d05c-08ae-47b0-a3c6-1122cee02aec false
2024-03-23T01:53:10.8554099Z 2024-03-23 01:47:30,143 INFO  [org.key.ope.con.KeycloakAdminSecretDependentResource$DeleteLogger] (-555943503-pool-9-thread-25) Delete example-kc-count0-realm 46f01e97-f899-4150-9fc8-fe892920ff36 false
2024-03-23T01:53:10.8555878Z 2024-03-23 01:47:30,157 INFO  [org.key.ope.con.KeycloakAdminSecretDependentResource$DeleteLogger] (-555943503-pool-9-thread-25) Delete example-kc-count0-realm 46f01e97-f899-4150-9fc8-fe892920ff36 false
2024-03-23T01:53:10.8557661Z 2024-03-23 01:47:30,241 INFO  [org.key.ope.con.KeycloakAdminSecretDependentResource$DeleteLogger] (-555943503-pool-9-thread-27) Delete example-kc-count0-realm 4bd485de-7dfb-4438-913d-046acfbaa826 false
2024-03-23T01:53:10.8559448Z 2024-03-23 01:47:30,243 INFO  [org.key.ope.con.KeycloakAdminSecretDependentResource$DeleteLogger] (-555943503-pool-9-thread-28) Delete example-kc-count0-realm 4bd485de-7dfb-4438-913d-046acfbaa826 false
```
There are two informers running against secrets - one for each controller, so we see double the secret events in general. What is shown here, which is not in the local log where all the tests passed, is the deletion of two example-kc-count0-realm secrets in rapid succession:

46f01e97-f899-4150-9fc8-fe892920ff36 followed closely by 4bd485de-7dfb-4438-913d-046acfbaa826. This seems very strange. Fabric8 does not correlate cache state to uid and as far as I know, neither does the operator sdk. Even if it did, it's still not clear how this would leave an entry in cache for example-kc-count0-realm.

**Comment by shawkins** [comment]
https://github.com/shawkins/keycloak/actions/runs/8411633344/job/23031519044 and the logging above seem to suggest that this is an operator sdk issue.

```
2024-03-24T20:13:51.5320388Z Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.96.0.1:443/apis/k8s.keycloak.org/v2alpha1/namespaces/keycloak-test-c3e8b9f0-740f-494f-9e14-f0d5b7497e55/keycloakrealmimports/example-count0-kc/status. Message: Operation cannot be fulfilled on keycloakrealmimports.k8s.keycloak.org "example-count0-kc": StorageError: invalid object, Code: 4, Key: /registry/k8s.keycloak.org/keycloakrealmimports/keycloak-test-c3e8b9f0-740f-494f-9e14-f0d5b7497e55/example-count0-kc, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 87edc274-67fa-4734-8e66-e58cc1f10ebf, UID in object meta: . Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=k8s.keycloak.org, kind=keycloakrealmimports, name=example-count0-kc, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on keycloakrealmimports.k8s.keycloak.org "example-count0-kc": StorageError: invalid object, Code: 4, Key: /registry/k8s.keycloak.org/keycloakrealmimports/keycloak-test-c3e8b9f0-740f-494f-9e14-f0d5b7497e55/example-count0-kc, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 87edc274-67fa-4734-8e66-e58cc1f10ebf, UID in object meta: , metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
2024-03-24T20:13:51.5328156Z 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)
2024-03-24T20:13:51.5329393Z 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:640)
2024-03-24T20:13:51.5330724Z 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:589)
2024-03-24T20:13:51.5464619Z 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549)
2024-03-24T20:13:51.5466210Z 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
2024-03-24T20:13:51.5467562Z 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
2024-03-24T20:13:51.5468745Z 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
2024-03-24T20:13:51.5469698Z 	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:143)
2024-03-24T20:13:51.5470655Z 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
2024-03-24T20:13:51.5471563Z 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
2024-03-24T20:13:51.5472453Z 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
2024-03-24T20:13:51.5473279Z 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
2024-03-24T20:13:51.5474160Z 	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
2024-03-24T20:13:51.5475072Z 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
2024-03-24T20:13:51.5475975Z 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
2024-03-24T20:13:51.5476852Z 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
2024-03-24T20:13:51.5477683Z 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
2024-03-24T20:13:51.5478527Z 	at io.fabric8.kubernetes.client.vertx.VertxHttpRequest.lambda$null$1(VertxHttpRequest.java:122)
2024-03-24T20:13:51.5479292Z 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276)
2024-03-24T20:13:51.5479942Z 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:258)
2024-03-24T20:13:51.5480631Z 	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
2024-03-24T20:13:51.5481424Z 	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
2024-03-24T20:13:51.5482328Z 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:418)
2024-03-24T20:13:51.5483429Z 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
2024-03-24T20:13:51.5484142Z 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134)
2024-03-24T20:13:51.5484929Z 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:705)
2024-03-24T20:13:51.5485713Z 	at io.vertx.core.impl.ContextImpl.lambda$execute$4(ContextImpl.java:322)
2024-03-24T20:13:51.5486445Z 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
2024-03-24T20:13:51.5487294Z 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
2024-03-24T20:13:51.5488215Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
2024-03-24T20:13:51.5488982Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
2024-03-24T20:13:51.5490005Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-03-24T20:13:51.5490786Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-03-24T20:13:51.5491534Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-03-24T20:13:51.5492086Z 	... 1 more
2024-03-24T20:13:51.5492216Z 
2024-03-24T20:13:51.5493481Z 2024-03-24 20:02:31,000 INFO  [org.key.ope.con.KeycloakRealmImportController] (ReconcilerExecutor-keycloakrealmimportcontroller-72) --- Reconciling Keycloak Realm: example-count0-kc in namespace: keycloak-test-c3e8b9f0-740f-494f-9e14-f0d5b7497e55
2024-03-24T20:13:51.5495638Z 2024-03-24 20:02:31,023 INFO  [org.key.ope.con.KeycloakRealmImportController] (ReconcilerExecutor-keycloakrealmimportcontroller-72) --- Realm reconciliation finished successfully
2024-03-24T20:13:51.5496924Z Secret exists example-kc-count0-realm 83fef663-477c-43c1-bc8d-542b58f55947 example-kc-initial-admin
```
This line confirms "Secret exists example-kc-count0-realm 83fef663-477c-43c1-bc8d-542b58f55947 example-kc-initial-admin" that the operator is referencing 83fef663-477c-43c1-bc8d-542b58f55947 in temporary cache, but it is not in the underlying informer cache. That line is repeated while the operator fails to resolve properly. 

It does seem to be a timing issue then with delete handling such that it's possible to set the temporary cache entry when it is not valid.

**Comment by shawkins** [comment]
Unfortunately while better, this code alone is not fool-proof - https://github.com/keycloak/keycloak/actions/runs/8616646009/job/23614992451?pr=28411 - the other option we have is to fully bounce the operator - let's see how often this is happening before we make an additional change.
