### ISSUE TITLE
Account theme that works in 21.1.2 does not work with 23.0.6

### ISSUE THREAD

**Issue by farcop** [keycloak/keycloak#27099]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

We have custom account theme that wasn't change, and it works with keycloak 21.1.2 and prior versions well, but now we make decision to update keycloak to 23 and all others themes works (login, email) but account theme fails with stack listed below:

```
2024-02-17 07:34:20,417 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-29) Uncaught server error: org.keycloak.theme.FreeMarkerException: Failed to process template index.ftl
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)
	at org.keycloak.services.resources.account.AccountConsole.getMainPage(AccountConsole.java:161)
	at org.keycloak.services.resources.account.AccountConsole$quarkusrestinvoker$getMainPage_d508fd32a638b899af4d52f90082abf4f245fdb3.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@776c1b40.
	at freemarker.template.Configuration.getTemplate(Configuration.java:2957)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2777)
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.getTemplate(DefaultFreeMarkerProvider.java:66)
	at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:45)
	... 12 more
```

After time of searching I found this https://github.com/keycloakify/keycloakify/issues/389 and this https://github.com/keycloak/keycloak/issues/22318 
All of that issues was closed as resolved, and as I expect that themes works in keycloak 23 like before 21 and older releases).
@xgp 
@garronej

We deliver our custom themes directly to the file system in the folder `themes` as described here https://www.keycloak.org/docs/latest/server_development/#_themes

### Version

23.0.6

### Regression

- [ ] The issue is a regressions

### Expected behavior

Custom account theme works without changes.

### Actual behavior

Custom account theme fails after 21.1.2 release.

### How to Reproduce?

I haven't figured out how to provide our custom theme yet.

**Comment by xgp** [comment]
The change in https://github.com/keycloak/keycloak/issues/22318 brings back *the ability* to port account v1 themes to recent (>=23) versions of Keycloak. In order to fully port one of those themes (e.g. one that inherits from `base` or `keycloak` account theme), you must implement it yourself, as those base themes and a compatible implementation of `AccountResourceProvider` are no longer in the Keycloak distribution.

One such example of porting the `base` account v1 theme is here: https://github.com/p2-inc/keycloak-account-v1

**Comment by farcop** [comment]
@xgp Thanks for answer!
I think it needs to add more info with samples how to migrate old shemes to new one.

**Comment by xgp** [comment]
Great idea. Please add that.

**Comment by farcop** [comment]
I have no idea how to port theme.
Breaking changes was made without documentation changes.
Sorry.

**Comment by xgp** [comment]
Ah. I see. Well, the repo I linked above, and the Keycloakify project present pretty good examples for how to do it. However, as for a step-by-step guide, AFAIK there is none. For that, you should check with the Keycloak maintainers. @garronej and I are unaffiliated, just solving our own problems.

**Comment by garronej** [comment]
@farcop First of all, I'm sorry to hear you're encountering issues with Keycloakify, but rest assured, there's an easy fix. The issue arises from the method you're using to load your theme into Keycloak.

We directly deliver our custom themes to the file system, within the themes folder, as described here.

Starting with Keycloakify 9, the Keycloakify theme also includes Java classes that need to be imported. Simply copying build_keycloak/src into your Keycloak instance won't work.

I've made an effort to document all the breaking changes in the migration guides: https://docs.keycloakify.dev/migration-guides/v8-to-v9

However, I didn't specifically address your method of loading the theme. The official supported way to load a Keycloakify theme into Keycloak is to import the generated jar with one of the method documented [here](https://docs.keycloakify.dev/importing-your-theme-in-keycloak#docker). I'll be sure to update this section of the documentation.

In your situation, the solution is to follow the instructions for [Bare metal](https://docs.keycloakify.dev/importing-your-theme-in-keycloak#bare-metal).

Please let me know if you encounter any further issues. We have a Discord channel you can join at https://discord.gg/kYFZG7fQmn. There's a live debug voice room available where you can share your screen. I'm here to help you work through this.

**Comment by farcop** [comment]
@xgp @garronej Guys, could you clarify would I have to build jar instead of put files in `themes` folder?

**Comment by garronej** [comment]
To make things easy for you, you can just load [this jar](https://github.com/keycloakify/keycloakify-starter/releases/download/v6.0.3/keycloak-theme.jar) into your Keycloak by following [this instructions](https://docs.keycloakify.dev/importing-your-theme-in-keycloak#bare-metal).  

You also need to edit the `src/main/resources/theme/<your theme>/account/theme.property` like this:  

```diff
-parent=keycloak
+parent=parent=account-v1
```  

If you do that you can still copy over the theme directory yes.

**Comment by farcop** [comment]
@garronej Thank you! Its works!
But I have at server logs
```
2024-02-18 11:26:58,166 WARN  [org.keycloak.theme.DefaultThemeManager] (executor-thread-7) Not found parent theme 'keycloak' of theme 'keycloakify-starter_retrocompat'. Unable to load ACCOUNT theme 'keycloakify-starter_retrocompat' due to this.
2024-02-18 11:26:58,167 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-7) Failed to find ACCOUNT theme keycloakify-starter_retrocompat, using built-in themes
```

**Comment by garronej** [comment]
Good for you!  

Yes this log is expected, Keycloakify bundle a retrocompat version of the account theme it generate so it can work on both Keycloak prior to 22 and later to 23.  

However since you're not using Keycloakify here and all you want is the account-v1 I made a JAR just for you that only contain what you need:  

https://github.com/keycloakify/keycloakify/releases/download/v0.0.1/account-v1.jar

**Comment by farcop** [comment]
@garronej Yeah! That works too. Thank you!
Could you share source code of [account-v1.jar](https://github.com/keycloakify/keycloakify/releases/download/v0.0.1/account-v1.jar) and can I use that code?

**Comment by garronej** [comment]
@farcop Sure you can use the JAR. The Java comes from [keycloak-account-v1](https://github.com/p2-inc/keycloak-account-v1) and the FreeMarker part has been [repackaged/slightly modified by Keycloakify](https://github.com/keycloakify/keycloakify/blob/main/src/bin/keycloakify/generateTheme/bringInAccountV1.ts).  
Anyway Keycloakify is MIT, Keycloak is Apache-2.0 and I assume the work of @xgp is also under a permisive license.
