### ISSUE TITLE
Social login - paypal test fails

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#27197]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Social login / social_login / org.keycloak.testsuite.broker.SocialLoginTest.paypalLogin fails with next error message:

`java.lang.AssertionError: Expected AppPage but was Sign in to social (https://127.0.0.1:8543/auth/realms/social/broker/paypal/endpoint?code=C21AALy2du9qgRYspA0IKWNY1leZGaDjmwovxEaIUqVcS75Q-W5hHGZi2abbURPVwmFRaN870WAv9yK4gqq92DpLCjpl1j_Kg&scope=openid+profile+email&state=JbKIwLHhMXAefslhIJkwa_hwzM2kjQWItTs1HK1VwnU.WmrMJVSwciY.ZZMa52JKQ4KpJa0Rdgx7_w)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.keycloak.testsuite.pages.AbstractPage.assertCurrent(AbstractPage.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.intercept(GrapheneContextualHandler.java:263)
	at org.keycloak.testsuite.pages.AppPage$$EnhancerByGraphene$$a93053e2.assertCurrent(<generated>)
	at org.keycloak.testsuite.broker.SocialLoginTest.paypalLogin(SocialLoginTest.java:426)`

https://keycloak-jenkins.com/view/Keycloak/job/universal-test-pipeline-server/3491/testReport/junit/org.keycloak.testsuite.broker/SocialLoginTest/Run_tests___Social_login___social_login___paypalLogin/

### Version

latest

### Regression

- [ ] The issue is a regressions

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by tondrusk** [comment]
I tried to execute the test locally and also manually configure the IdP. Looking into the console, the login flow failed with

```
2024-02-27 13:40:22,871 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-2) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: Could not obtain user profile from paypal.
	at org.keycloak.social.paypal.PayPalIdentityProvider.doGetFederatedIdentity(PayPalIdentityProvider.java:81)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.getFederatedIdentity(AbstractOAuth2IdentityProvider.java:306)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:529)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_fef2d69ce31937f365a37fb3083f9247bc4c56d2.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: No identifier provider for identity.
	at org.keycloak.broker.provider.BrokeredIdentityContext.<init>(BrokeredIdentityContext.java:55)
	at org.keycloak.social.paypal.PayPalIdentityProvider.extractIdentityFromProfile(PayPalIdentityProvider.java:61)
	at org.keycloak.social.paypal.PayPalIdentityProvider.doGetFederatedIdentity(PayPalIdentityProvider.java:79)
	... 13 more

2024-02-27 13:40:22,876 WARN  [org.keycloak.events] (executor-thread-2) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="6b0d81ae-8265-43d6-8c7b-5a4adf51f7dd", clientId="security-admin-console", userId="null", ipAddress="127.0.0.1", error="identity_provider_login_failure", code_id="a2659897-6930-4af5-a0e5-09fc53f8423f"
```
and the browser is returning status code 502 Bad Gateway. I remember having some issues with the `localhost` keyword in PayPal app configuration which had to be changed to `127.0.0.1` but for unknown reasons the login flow started failing.

To better describe the situation, first, the PayPal IdP button is clicked and the login flow is redirected to PayPal login page. After inserting the login credentials, it is not able to successfully get back to Keycloak without throwing the error mentioned above and the browser shows this:

![image](https://github.com/keycloak/keycloak/assets/67582554/5e91630c-8e36-479d-88f9-6701100f0336)

**Comment by tondrusk** [comment]
Resolved internally.

**Comment by tondrusk** [comment]
Resolved internally.
