### ISSUE TITLE
Testsuite of Keycloak Core fails on Windows because of wrong file encoding

### ISSUE THREAD

**Issue by ghbugfinder** [keycloak/keycloak#27267]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Following the Building from source guide on Windows (which out of the box doesn't use UTF-8 as default file encoding) the build fails during the testsuite of Keycloak Core.

### Version

999.0.0-SNAPSHOT

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests should succeed.

Either the build scripts should default to automatically use the necessary UTF-8 file encoding or the documentation should state that something like
set JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
might have to be done before starting the build.

### Actual behavior

...
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] The encoding used to copy filtered properties files have not been set. This means that the same encoding will be used to copy filtered properties files as when copying other filtered resources. This might not be what you want! Run your build with --debug to see which files might be affected. Read more at https://maven.apache.org/plugins/maven-resources-plugin/examples/filtering-properties-files.html
...
[ERROR] Failures:
[ERROR]   SdJwtTest.testA1_Example2_with_nested_disclosure_and_decoy_claims:77 expected:<{"_sd":["IZOyJn0D17aK845iZ8i5hDloSkartiUlvp_hKjNbAt8","Lsx_tw-UwEZ_HsK8QcIDkCn5Wvfe5BmvcnWQB6ikqqo","QNQd3_y8o6qtdJguQDuA3zdfdYz-WgLSaje06s2UmWM","UWzvCBURYx4dSkeBCptgLtudFbLgnJoBgmaHB-76lOg","cx4toEb1qARkAf8NuD0ATk3oM6m8a0q8nAVFDtBdfoo","oUuE90DUCx3Xu_H5zQMBEqAdbMrlAZ7QoK5zIJ_B1mA","qd2G5TGH-6M1qNy8ouhXfsE7U6vWDOnp2FUvovAaW74","uNHoWYhXsZhVJCNE2Dqy-zqt7t69gJKy5QaFv7GrMX4"]}> but was:<{"_sd":["HNiX73yXiuLJblNcYiKhLQ2HEyiYBNO2DP3KnQnfn6o","IZOyJn0D17aK845iZ8i5hDloSkartiUlvp_hKjNbAt8","QNQd3_y8o6qtdJguQDuA3zdfdYz-WgLSaje06s2UmWM","UWzvCBURYx4dSkeBCptgLtudFbLgnJoBgmaHB-76lOg","ezSvJ3hwK7Z5sDyl-wsv7GN6oMFe7dQvatHng0FBHjA","hLAoieH93sM-dcjOC3cubRBsPyWnp8oYJEKve_3xMHc","oUuE90DUCx3Xu_H5zQMBEqAdbMrlAZ7QoK5zIJ_B1mA","uNHoWYhXsZhVJCNE2Dqy-zqt7t69gJKy5QaFv7GrMX4"]}>
[ERROR]   SdJwtUtilsTest.testBase64urlEncodedObjectNoWhiteSpacedJsonArray:98 expected:<...mZhbWlseV9uYW1lIiwiT[cO2Yml1cyJd]> but was:<...mZhbWlseV9uYW1lIiwiT[fZiaXVzIl0]>
[ERROR]   SdJwtUtilsTest.testBase64urlEncodedObjectWhiteSpacedJsonArray:77 expected:<...YW1pbHlfbmFtZSIsICJN[w7ZiaXVzIl0]> but was:<...YW1pbHlfbmFtZSIsICJN[9mJpdXMiXQ]>
[ERROR]   UndisclosedClaimTest.testToBase64urlEncoded:56 expected:<...mZhbWlseV9uYW1lIiwiT[cO2Yml1cyJd]> but was:<...mZhbWlseV9uYW1lIiwiT[fZiaXVzIl0]>
...
[INFO] Keycloak Core ...................................... FAILURE [ TIME_MANUALLY_DELETED s]
...

### How to Reproduce?

Follow the docs/building.md using ./mvnw clean install -Pdistribution on a fresh Windows system (which doesn't use UTF-8 file encoding) in the Git CMD/Git Bash.

Install JDK 17.0.10
Install Git 2.44.0 (can't remember which settings I used)
Start Git CMD
git clone https://github.com/keycloak/keycloak.git
cd keycloak
./mvnw clean install -Pdistribution

**Comment by ghbugfinder** [comment]
Forgot to mention the failed test:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project keycloak-core: There are test failures.

**Comment by calebTree** [comment]
In my situation the test from the goal `org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test` that failed was:
```
-------------------------------------------------------------------------------
Test set: org.keycloak.test.broker.saml.XPathAttributeMapperTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.038 s <<< FAILURE! - in org.keycloak.test.broker.saml.XPathAttributeMapperTest
org.keycloak.test.broker.saml.XPathAttributeMapperTest.testInvalidXml  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError: expected java.lang.RuntimeException to be thrown, but nothing was thrown
        at org.junit.Assert.assertThrows(Assert.java:1028)
        at org.junit.Assert.assertThrows(Assert.java:981)
        at org.keycloak.test.broker.saml.XPathAttributeMapperTest.testInvalidXml(XPathAttributeMapperTest.java:52)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```
I am brand new to this repo so I haven't fixed the test yet. The actual test is here:
`keycloak/services/src/test/java/org/keycloak/test/broker/saml/XPathAttributeMapperTest.java:52`

I am still working on `pnpm` builds failing and haven't successfully compiled yet.
