### ISSUE TITLE
keycloak 23.0.4: Hitting "java.security.UnrecoverableKeyException: Password verification failed" when we try to communicate with the host Kubernetes server API(Openshift 4.12)

### ISSUE THREAD

**Issue by satsrini** [keycloak/keycloak#27371]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

**Issue**:  Hitting "_java.security.UnrecoverableKeyException: Password verification failed_" when we try to communicate from keycloak 
server pod to the host Kubernetes Server API (Openshift 4.12)

**Use case:**
 In our product, we deploy keycloak server using bitnami helm chart - [Keycloak 23.0.4](https://github.com/bitnami/charts/tree/6b632870dcf2138fbf87a9eab5b73d80a3d3b0ed/bitnami/keycloak)
 
 In our product, we create a custom **K8EventPublisher** and **K8EventListener** by implementing _org.keycloak.events.EventListenerProviderFactory and org.keycloak.events.EventListenerProvider_ respectively.
 The above java classes are loaded onto the keycloak server pod dynamically at keycloak helm chart deployment time.
 
 We register the above mentioned K8EventPublisher from keycloak admin console UI - 
 _keycloak admin console --> [realm] --> Realm setings --> Events_
 
 Once we register, we get a handle through the overridden method of 
 
` org.keycloak.events.EventListenerProviderFactory.create()`
 
 In the above method we have written the following code to communicate with the  Kubernetes server API (Openshift 4.12) upon which this keycloak server pod is hosted.
 
```
 io.kubernetes.client.openapi.ApiClient client = io.kubernetes.client.util.ClientBuilder.cluster().build();

 gradle:    implementation 'io.kubernetes:client-java:18.0.1'
```
 
 We then use the above ApiClient to create Namespaced Events.
 
 **Issue in Detail:**
 
 The above mentioned use case was working fine when we used [Keycloak v21.1.2](https://github.com/bitnami/charts/tree/df638697464307b86eaea802a0721b5678ec6553/bitnami/keycloak)
 But when we upgrade to [Keycloak v23.0.4](https://github.com/bitnami/charts/tree/6b632870dcf2138fbf87a9eab5b73d80a3d3b0ed/bitnami/keycloak),
 this line of code 
 
` ApiClient client = ClientBuilder.cluster().build();`
 
 is throwing the below exception.
 
```
 2024-02-12 15:34:29,813 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.security.KeyStoreException: problem accessing trust store
        at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
        at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282)
        at okhttp3.internal.platform.Platform.platformTrustManager(Platform.kt:80)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:237)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)
        at io.kubernetes.client.openapi.ApiClient.initHttpClient(ApiClient.java:97)
        at io.kubernetes.client.openapi.ApiClient.initHttpClient(ApiClient.java:87)
        at io.kubernetes.client.openapi.ApiClient.<init>(ApiClient.java:78)
        at io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:423)
        at com.myorg.myprd.keycloak.events.K8EventClient.eventClientFromEnv(K8EventClient.java:36)
        at com.myorg.myprd.keycloak.events.KeycloakK8EventPublisherFactory.create(KeycloakK8EventPublisherFactory.java:26)
        at com.myorg.myprd.keycloak.events.KeycloakK8EventPublisherFactory.create(KeycloakK8EventPublisherFactory.java:13)
        at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:195)
        at org.keycloak.models.KeycloakBeanProducer_ProducerMethod_getKeycloakSession_5e84845135ceb04ddba6a5e518c0329028840943_ClientProxy.getProvider(Unknown Source)
        at org.keycloak.services.resources.admin.AdminEventBuilder.lambda$addListeners$0(AdminEventBuilder.java:136)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.keycloak.services.resources.admin.AdminEventBuilder.addListeners(AdminEventBuilder.java:135)
        at org.keycloak.services.resources.admin.AdminEventBuilder.refreshRealmEventsConfig(AdminEventBuilder.java:119)
        at org.keycloak.services.resources.admin.RealmAdminResource.updateRealmEventsConfig(RealmAdminResource.java:744)
        at org.keycloak.services.resources.admin.RealmAdminResource$quarkusrestinvoker$updateRealmEventsConfig_1a25b71babbdc90beef8a1aac5d7e99372804124.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:813)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:242)
        at java.base/java.security.KeyStore.load(KeyStore.java:1473)
        at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:390)
        at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:336)
        at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:57)
        at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
        ... 38 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:811)
        ... 44 more
 
```
 
 **Confirmations:**
   1. all Kubernetes server API credentials(ca.crt,token, service-ca.crt) are correctly mounted inside the pod in _/var/run/secrets/kubernetes.io/serviceaccount_
 2. We deployed a sample java code inside the running keycloak server pod(which has the above issue) to execute the below
 code and it ran fine successfully. It was able to communicate to the host kubernetes API server. 
	`ApiClient client = ClientBuilder.cluster().build();`
	This proves that the environment inside the keycloak server pod is fine.

3.We compiled the entire project in JDK 17.

4. We are hitting the above issue when we use either of the following settings.
```
      a. Values.serviceAccount.automountServiceAccountToken: true
      b. Values.serviceAccount.automountServiceAccountToken: false
```
 
 Please let us know if you need more details from our end.

### Version

23.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

Inside the keycloak server pod, when the following lines of code gets executed by invoking through keycloak admin console UI - 
 _keycloak admin console --> [realm] --> Realm setings --> Events_ , connection to the hosted Kubernetes Server API should be successful.

` io.kubernetes.client.openapi.ApiClient client = io.kubernetes.client.util.ClientBuilder.cluster().build();`

### Actual behavior

Inside the keycloak server pod, when the following lines of code gets executed by invoking through keycloak admin console UI - 
 _keycloak admin console --> [realm] --> Realm setings --> Events_ , 

` io.kubernetes.client.openapi.ApiClient client = io.kubernetes.client.util.ClientBuilder.cluster().build();`

we are hitting 

`Caused by: java.security.UnrecoverableKeyException: Password verification failed`

and hence not able to connect to the hosted Kubernetes API server.

### How to Reproduce?

**Steps to Reproduce:**
a. helm chart  [Keycloak 23.0.4](https://github.com/bitnami/charts/tree/6b632870dcf2138fbf87a9eab5b73d80a3d3b0ed/bitnami/keycloak) 
b. Openshift 4.12 Kubernetes `Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+a34b9e9"`
c. create a custom **K8EventPublisher** and **K8EventListener** by implementing _org.keycloak.events.EventListenerProviderFactory and org.keycloak.events.EventListenerProvider_ respectively.
 Keycloak client version used : 23.0.4
d. ` org.keycloak.events.EventListenerProviderFactory.create()`
 
 In the above overridden method, write the following code to communicate with the  Kubernetes server API (Openshift 4.12) upon which this keycloak server pod is hosted.
 
```
 io.kubernetes.client.openapi.ApiClient client = io.kubernetes.client.util.ClientBuilder.cluster().build();

 gradle:    implementation 'io.kubernetes:client-java:18.0.1'
```
e. compile it in JDK 17
f. deploy the keycloak helm chart.
g.Register the above mentioned K8EventPublisher from keycloak admin console UI - 
 _keycloak admin console --> [realm] --> Realm setings --> Events_
 
 f.After pressing the Save Button, we will see the below error in keycloak server pod logs and hence the custome K8EventPublisher  will not be saved.
 
` Caused by: java.security.UnrecoverableKeyException: Password verification failed`
**Note:** the full stack trace is provided in the description

### Anything else?

This same issue comes even when use higher versions of _io.kubernetes:client-java_ as mentioned below

```
 io.kubernetes.client.openapi.ApiClient client = io.kubernetes.client.util.ClientBuilder.cluster().build();
 gradle:    implementation 'io.kubernetes:client-java:19.0.0'
``` 
```
 io.kubernetes.client.openapi.ApiClient client = io.kubernetes.client.util.ClientBuilder.cluster().build();
 gradle:    implementation 'io.kubernetes:client-java:20.0.0'
```

**Comment by satsrini** [comment]
This issue is getting closed, since this occurs primarily because of this issue https://github.com/keycloak/keycloak/issues/27392

**Comment by satsrini** [comment]
This issue is getting closed, since this occurs primarily because of this issue https://github.com/keycloak/keycloak/issues/27392
