### ISSUE TITLE
LDAP synchronisation thread killed and not restartable after network outage

### ISSUE THREAD

**Issue by SebastEnn** [keycloak/keycloak#27394]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I'm working for a company with a self hosted datacenter.
A few days ago we had an internal network outage. For a few minutes no server was able to communicate to any other.
We're using Keycloak with our own ldap database as federation and have set it up to sync all changed users every 4 seconds.

In that timespan of the network outage, the Keycloak server couldn't reach the ldap database, resulting in an _java.net.UnknownHostException_ in the Keycloak log. Each try every 4 seconds resulted that way.
After one minute of this going on, the _Transaction Reaper_ (com.arjuna.ats.arjuna) kicked in and cancelled the thread responsible for the ldap synchronisation.

I tried to disable and reenable the periodic sync in the federation settings, expecting it would restart the sync service as it would normally do - It didn't. Now I can only manually sync the ldap database or I have to restart the Keycloak server, which would kill all existing user sessions.

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak starts the ldap sync thread up again after disabling and reenabling periodic sync.

### Actual behavior

Keycloak doesn't start the ldap sync thread up again after disabling and reenabling periodic sync.

### How to Reproduce?

- Start a Keycloak sever
- Add a basic realm
- Add an ldap database for user federation and enable periodic sync of changed users with a low amount of seconds
  - The host in the connection url has to be non-existant. This will result in an UnknownHostException.

**Comment by SebastEnn** [comment]
I tried to reproduce the problem both on 22.0.5 and on 23.0.7 (latest), but I'm not able to get the thread killed.

If necessary I can provide the logs of the thread being killed.

**Comment by jonkoops** [comment]
If the problem is not reproducible there is very little we can do, please attach logs if you have them.

**Comment by SebastEnn** [comment]
The following log only includes the last _UnknownHostException_ before the thread is being killed.

<details>
  <summary>Keycloak Log</summary>

  ```
2024-02-23 11:34:11,126 ERROR [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager] (Timer-0) Could not query server using DN [ou=Groups,dc=my-dc,dc=com] and filter [(&(objectclass=groupOfNames))]: javax.naming.CommunicationException: servername:389 [Root exception is java.net.UnknownHostException: servername]
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:253)
	at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:709)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:704)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:253)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:279)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:167)
	at org.keycloak.storage.ldap.LDAPUtils.loadAllLDAPObjects(LDAPUtils.java:309)
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.getAllLDAPGroups(GroupLDAPStorageMapper.java:412)
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:172)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory$1.lambda$run$0(LDAPStorageProviderFactory.java:530)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory$1.run(LDAPStorageProviderFactory.java:528)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncMappers(LDAPStorageProviderFactory.java:520)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncSince(LDAPStorageProviderFactory.java:500)
	at org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:155)
	at org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:148)
	at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
	at org.keycloak.storage.managers.UserStorageSyncManager$3.run(UserStorageSyncManager.java:148)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
	at org.keycloak.storage.managers.UserStorageSyncManager.syncChangedUsers(UserStorageSyncManager.java:138)
	at org.keycloak.storage.managers.UserStorageSyncManager$5.run(UserStorageSyncManager.java:237)
	at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.net.UnknownHostException: servername
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:346)
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:232)
	... 44 more

2024-02-23 11:34:11,126 ERROR [org.keycloak.storage.managers.UserStorageSyncManager] (Timer-0) Error occurred during sync of changed users: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:171)
	at org.keycloak.storage.ldap.LDAPUtils.loadAllLDAPObjects(LDAPUtils.java:309)
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.getAllLDAPGroups(GroupLDAPStorageMapper.java:412)
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:172)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory$1.lambda$run$0(LDAPStorageProviderFactory.java:530)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory$1.run(LDAPStorageProviderFactory.java:528)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncMappers(LDAPStorageProviderFactory.java:520)
	at org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncSince(LDAPStorageProviderFactory.java:500)
	at org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:155)
	at org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:148)
	at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
	at org.keycloak.storage.managers.UserStorageSyncManager$3.run(UserStorageSyncManager.java:148)
	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
	at org.keycloak.storage.managers.UserStorageSyncManager.syncChangedUsers(UserStorageSyncManager.java:138)
	at org.keycloak.storage.managers.UserStorageSyncManager$5.run(UserStorageSyncManager.java:237)
	at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@362ee1b4
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:167)
	... 24 more
Caused by: javax.naming.CommunicationException: servername:389 [Root exception is java.net.UnknownHostException: servername]
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:253)
	at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:709)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:704)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:253)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:279)
	... 25 more
Caused by: java.net.UnknownHostException: servername
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:346)
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:232)
	... 44 more

2024-02-23 11:39:15,125 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffffac170003:9fb1:65674652:1ba42e9 in state  RUN
2024-02-23 11:39:15,126 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffffac170003:9fb1:65674652:1ba42ea in state  RUN
2024-02-23 11:39:15,126 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffffac170003:9fb1:65674652:1ba42e9
2024-02-23 11:39:15,126 INFO  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012404: Action id 0:ffffac170003:9fb1:65674652:1ba42ea - thread Timer-0 at time 11:37:15.128 had stackTrace java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
java.base@17.0.9/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
java.base@17.0.9/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
java.base@17.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
java.base@17.0.9/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
java.naming@17.0.9/com.sun.jndi.ldap.LdapRequest.getReplyBer(LdapRequest.java:120)
java.naming@17.0.9/com.sun.jndi.ldap.Connection.readReply(Connection.java:444)
java.naming@17.0.9/com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:365)
java.naming@17.0.9/com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214)
java.naming@17.0.9/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2896)
java.naming@17.0.9/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
java.naming@17.0.9/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
java.naming@17.0.9/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
java.naming@17.0.9/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
java.naming@17.0.9/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
java.naming@17.0.9/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
java.naming@17.0.9/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
java.naming@17.0.9/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
java.naming@17.0.9/javax.naming.InitialContext.init(InitialContext.java:236)
java.naming@17.0.9/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:709)
org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:704)
org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:253)
org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:279)
org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:167)
org.keycloak.storage.ldap.LDAPUtils.loadAllLDAPObjects(LDAPUtils.java:309)
org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.getAllLDAPGroups(GroupLDAPStorageMapper.java:412)
org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:172)
org.keycloak.storage.ldap.LDAPStorageProviderFactory$1.lambda$run$0(LDAPStorageProviderFactory.java:530)
org.keycloak.storage.ldap.LDAPStorageProviderFactory$1$$Lambda$1651/0x00007faf97cb7b30.accept(Unknown Source)
java.base@17.0.9/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
java.base@17.0.9/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
org.keycloak.storage.ldap.LDAPStorageProviderFactory$1.run(LDAPStorageProviderFactory.java:528)
org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
org.keycloak.models.utils.KeycloakModelUtils$$Lambda$1353/0x00007faf97b29178.run(Unknown Source)
org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncMappers(LDAPStorageProviderFactory.java:520)
org.keycloak.storage.ldap.LDAPStorageProviderFactory.syncSince(LDAPStorageProviderFactory.java:500)
org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:155)
org.keycloak.storage.managers.UserStorageSyncManager$3$1.call(UserStorageSyncManager.java:148)
org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)
org.keycloak.storage.managers.UserStorageSyncManager$3.run(UserStorageSyncManager.java:148)
org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:262)
org.keycloak.models.utils.KeycloakModelUtils$$Lambda$1353/0x00007faf97b29178.run(Unknown Source)
org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:261)
org.keycloak.storage.managers.UserStorageSyncManager.syncChangedUsers(UserStorageSyncManager.java:138)
org.keycloak.storage.managers.UserStorageSyncManager$5.run(UserStorageSyncManager.java:237)
org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
java.base@17.0.9/java.util.TimerThread.mainLoop(Timer.java:566)
java.base@17.0.9/java.util.TimerThread.run(Timer.java:516)
  ```
</details>

**Comment by SebastEnn** [comment]
I guess this is the Thread/Timer that got killed and doesnt start up again:
[org.keycloak.storage.ldap.LDAPStorageProviderFactory] (Timer-0)

**Comment by SebastEnn** [comment]
I did some digging through the code.

I think this is the chain that gets called when I save my ldap provider:
[bootstrapPeriodic](https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L59) 
[refreshPeriodicSyncForProvider](https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L70C29-L70C59) 
[UserStorageSyncTask task = new UserStorageSyncTask](https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L219)

And this [task](https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L241) is then supposed to run [syncChangedUsers](https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L265C25-L265C41) with the interval given [here](https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L220C43-L220C63).
The timer instance is from [BasicTimerProvider](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java) which has some logic to repeat itself in [schedule](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/timer/basic/BasicTimerProvider.java#L49C17-L49C25).

My guess is, that the entire BasicTimerProvider instance (and maybe it's superior TimerThread) got killed, so there was no chance to restart it within the timer.

**Comment by pedroigor** [comment]
@SebastEnn AFAIK, the periodic sync tasks are only refreshed/updated when you change the sync settings. Changing the connection URL has no effect. Something odd that we need to improve.

However, I was not able to reproduce your behavior and I was able to recover from using an invalid host and `UnknownHostException` exceptions by re-enabling periodic sync (disable, save, enable, sabe).

The provider was also able to recover from an invalid host in the connection URL once the periodic sync is refreshed.

For this, reason, I'm marking this issue as ~missing-info.

**Comment by SebastEnn** [comment]
> Changing the connection URL has no effect. Something odd that we need to improve.

Now that you mention it: That's true. During my testing I also notices that changing the url doesn't update the sync process. I guess you'll open an issue for this bug (if not already).


During discussion with some colleagues were where thinking this could have been an issue with the server resources.

Anyway - since we're not able to reproduce, I'm gonna close this issue. If we experience it again I'll come back to this.
Also, if other people experience this, _they'll probably find this issue and comment_.

(Sidenote: As a workaround we'll be running two Keycloak instances, so if this occurs again, we can safely restart both servers one after the other without losing sessions as they're getting synced with ISPN)

**Comment by pedroigor** [comment]
@SebastEnn Thanks. Created https://github.com/keycloak/keycloak/issues/27554.
