### ISSUE TITLE
Email sent fails with SMTPAddressFailedException: 550 I cannot deliver mail for <test@mcuma.com>

### ISSUE THREAD

**Issue by Alice5698** [keycloak/keycloak#27456]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

I am using own smtp mail server for email settings. And keycloak sends test or verification email only to email from this exact server - email comes fine at the email user@myserver.com, and Fails to send email to ANY other mail service like gmail or whatever. 

There is no any error msg, i got only "Failed to send email" and in terminal i got exception 

```
org.keycloak.email.EmailException: jakarta.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	org.eclipse.angus.mail.smtp.SMTPAddressFailedException: 550 I cannot deliver mail for <xoboleh977@mcuma.com>

	at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:161)
	at org.keycloak.email.DefaultEmailSenderProvider.send(DefaultEmailSenderProvider.java:66)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:277)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:271)
	at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendSmtpTestEmail(FreeMarkerEmailTemplateProvider.java:128)
	at org.keycloak.services.resources.admin.RealmAdminResource.testSMTPConnection(RealmAdminResource.java:1006)
	at org.keycloak.services.resources.admin.RealmAdminResource$quarkusrestinvoker$testSMTPConnection_7654a7bca79f5deb190fcf6743c79883b24faf44.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
```

I have tried to send email form my server to any adresses with other client, or web-ui - it always goes fine. Just keycloak unable to do that.

### Version

23

### Regression

- [ ] The issue is a regression

### Expected behavior

Email sent fine to any domains, or at least error reason is displayed.

### Actual behavior

Email is sent only to the same domain as smtp server

### How to Reproduce?

Put into email settings address and port and credentials of an own email server, for test email point any gmail adress, press "test connection" button

**Comment by jonkoops** [comment]
The 550 error means that the mail server blocked your Keycloak's message and sent it back. This is not an issue with Keycloak itself, but your mail server.
