### ISSUE TITLE
21.1.1 to 23.0.6,show no physical address for ip

### ISSUE THREAD

**Issue by huangjy6688** [keycloak/keycloak#27470]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

logs info:
2024-03-01 19:02:33,659 INFO  [org.jgroups.protocols.aws.S3_PING] (keycloak-cache-init) found bucket s3
2024-03-01 19:02:33,664 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `ec2`
2024-03-01 19:02:33,669 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: a45220e3-ec3c-49a4-a6f8-7f2a9d911615, name: ip-10-19-76-38-25533
2024-03-01 19:02:33,677 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.57800
2024-03-01 19:02:33,811 WARN  [org.jgroups.protocols.TCP] (TQ-Bundler-7,ip-10-19-76-51-29754) JGRP000032: ip-10-19-76-51-29754: no physical address for a45220e3-ec3c-49a4-a6f8-7f2a9d911615, dropping message
2024-03-01 19:02:33,822 INFO  [org.infinispan.CLUSTER] (jgroups-997,ip-10-19-76-51-29754) ISPN000094: Received new cluster view for channel ISPN: [ip-10-19-76-51-29754|34] (3) [ip-10-19-76-51-29754, ip-10-19-76-69-49518, a45220e3-ec3c-49a4-a6f8-7f2a9d911615]
2024-03-01 19:02:33,822 INFO  [org.infinispan.CLUSTER] (jgroups-997,ip-10-19-76-51-29754) ISPN100000: Node a45220e3-ec3c-49a4-a6f8-7f2a9d911615 joined the cluster
2024-03-01 19:02:33,823 INFO  [org.infinispan.CLUSTER] (jgroups-997,ip-10-19-76-51-29754) ISPN100000: Node a45220e3-ec3c-49a4-a6f8-7f2a9d911615 joined the cluster
2024-03-01 19:02:33,832 INFO  [org.infinispan.CLUSTER] (jgroups-1020,ip-10-19-76-69-49518) ISPN000094: Received new cluster view for channel ISPN: [ip-10-19-76-51-29754|34] (3) [ip-10-19-76-51-29754, ip-10-19-76-69-49518, ip-10-19-76-38-25533]
2024-03-01 19:02:33,832 INFO  [org.infinispan.CLUSTER] (jgroups-1020,ip-10-19-76-69-49518) ISPN100000: Node ip-10-19-76-38-25533 joined the cluster
2024-03-01 19:02:33,833 INFO  [org.infinispan.CLUSTER] (jgroups-1020,ip-10-19-76-69-49518) ISPN100000: Node ip-10-19-76-38-25533 joined the cluster
2024-03-01 19:02:34,143 INFO  [org.jgroups.protocols.aws.S3_PING] (keycloak-cache-init) using Amazon S3 ping in region ap-east-1 with bucket 's3' and prefix ''
2024-03-01 19:02:34,479 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2024-03-01 19:02:34,487 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-03-01 19:02:34,658 INFO  [org.jgroups.protocols.aws.S3_PING] (keycloak-cache-init) found bucket s3
2024-03-01 19:02:34,661 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `ec2`
2024-03-01 19:02:34,663 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: d33b33a9-dea7-4e2c-b820-0a93c8df6cd4, name: ip-10-19-76-109-34831
2024-03-01 19:02:34,670 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.57800
2024-03-01 19:02:35,754 WARN  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) ip-10-19-76-38-25533: JOIN(ip-10-19-76-38-25533) sent to ip-10-19-76-51-29754 timed out (after 2000 ms), on try 0
2024-03-01 19:02:35,846 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [ip-10-19-76-51-29754|34] (3) [ip-10-19-76-51-29754, ip-10-19-76-69-49518, ip-10-19-76-38-25533]
2024-03-01 19:02:35,850 INFO  [org.infinispan.CLUSTER] (jgroups-997,ip-10-19-76-51-29754) ISPN000094: Received new cluster view for channel ISPN: [ip-10-19-76-51-29754|35] (4) [ip-10-19-76-51-29754, ip-10-19-76-69-49518, ip-10-19-76-38-25533, ip-10-19-76-109-34831]
2024-03-01 19:02:35,850 INFO  [org.infinispan.CLUSTER] (jgroups-997,ip-10-19-76-51-29754) ISPN100000: Node ip-10-19-76-109-34831 joined the cluster
2024-03-01 19:02:35,850 INFO  [org.infinispan.CLUSTER] (jgroups-997,ip-10-19-76-51-29754) ISPN100000: Node ip-10-19-76-109-34831 joined the cluster
2024-03-01 19:02:35,852 INFO  [org.infinispan.CLUSTER] (jgroups-1019,ip-10-19-76-69-49518) ISPN000094: Received new cluster view for channel ISPN: [ip-10-19-76-51-29754|35] (4) [ip-10-19-76-51-29754, ip-10-19-76-69-49518, ip-10-19-76-38-25533, d33b33a9-dea7-4e2c-b820-0a93c8df6cd4]
2024-03-01 19:02:35,852 INFO  [org.infinispan.CLUSTER] (jgroups-1019,ip-10-19-76-69-49518) ISPN100000: Node d33b33a9-dea7-4e2c-b820-0a93c8df6cd4 joined the cluster
2024-03-01 19:02:35,852 INFO  [org.infinispan.CLUSTER] (jgroups-1019,ip-10-19-76-69-49518) ISPN100000: Node d33b33a9-dea7-4e2c-b820-0a93c8df6cd4 joined the cluster
2024-03-01 19:02:35,878 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [ip-10-19-76-51-29754|35] (4) [ip-10-19-76-51-29754, 55b83201-8245-4a22-ac88-d3ad6fbcdb32, a45220e3-ec3c-49a4-a6f8-7f2a9d911615, ip-10-19-76-109-34831]
2024-03-01 19:02:35,935 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `ip-10-19-76-38-25533`, physical addresses are `[10.19.76.38:7800]`
2024-03-01 19:02:35,960 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-03-01 19:02:35,997 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `ip-10-19-76-109-34831`, physical addresses are `[10.19.76.109:7800]`
2024-03-01 19:02:36,021 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-03-01 19:02:36,158 INFO  [org.infinispan.CLUSTER] (jgroups-6,ip-10-19-76-38-25533) ISPN000094: Received new cluster view for channel ISPN: [ip-10-19-76-51-29754|35] (4) [ip-10-19-76-51-29754, ip-10-19-76-69-49518, ip-10-19-76-38-25533, ip-10-19-76-109-34831]
2024-03-01 19:02:36,166 INFO  [org.infinispan.CLUSTER] (jgroups-6,ip-10-19-76-38-25533) ISPN100000: Node ip-10-19-76-109-34831 joined the cluster
2024-03-01 19:02:36,167 INFO  [org.infinispan.CLUSTER] (jgroups-6,ip-10-19-76-38-25533) ISPN100000: Node ip-10-19-76-109-34831 joined the cluster
2024-03-01 19:02:36,241 ERROR [org.infinispan.CLUSTER] (jgroups-9,ip-10-19-76-109-34831) ISPN000475: Error processing response for request 2 from ip-10-19-76-51-29754: java.io.EOFException
	at org.infinispan.marshall.core.AbstractBytesObjectInput.checkPosLength(AbstractBytesObjectInput.java:261)
	at org.infinispan.marshall.core.AbstractBytesObjectInput.readByte(AbstractBytesObjectInput.java:107)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallSize(MarshallUtil.java:426)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:271)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
	at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:86)
	at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:70)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
	at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1559)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1468)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1642)
	at org.jgroups.JChannel.up(JChannel.java:733)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:936)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:139)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:845)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:226)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1083)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:822)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:804)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:453)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:680)
	at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:188)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
	at org.jgroups.protocols.Discovery.up(Discovery.java:294)
	at org.jgroups.stack.Protocol.up(Protocol.java:340)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1184)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:107)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

### Version

23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

inspn is ok 

### Actual behavior

ip error

### How to Reproduce?

21.1.1 to 23.0.6

**Comment by stianst** [comment]
There's not enough information here to take a look at this, can you add steps to reproduce?

~missing-info

**Comment by stianst** [comment]
~missing-information

**Comment by huangjy6688** [comment]
ADD --chown=keycloak:keycloak https://repo1.maven.org/maven2/org/jgroups/aws/jgroups-aws/2.0.1.Final/jgroups-aws-2.0.1.Final.jar /opt/keycloak/providers/jgroups-aws-2.0.1.Final.jar
ADD --chown=keycloak:keycloak https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.12.410/aws-java-sdk-core-1.12.410.jar  /opt/keycloak/providers/aws-java-sdk-core-1.12.410.jar
ADD --chown=keycloak:keycloak https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.12.410/aws-java-sdk-s3-1.12.410.jar   /opt/keycloak/providers/aws-java-sdk-s3-1.12.410.jar
ADD --chown=keycloak:keycloak https://repo1.maven.org/maven2/joda-time/joda-time/2.12.2/joda-time-2.12.2.jar  /opt/keycloak/providers/joda-time-2.12.2.jar

ENV JAVA_OPTS_APPEND="-Djgroups.s3.bucket_name  .....

RUN /opt/keycloak/bin/kc.sh build --cache=ispn  --cache-stack=ec2

db=mysql


21.1.1 Upgrade 23.0.6

mysql 
lower_case_table_names = 0  ---> Upgrade failed

I set lower_case_table_names = 1  ---> Upgrade Successful

**Comment by shawkins** [comment]
@huangjy6688 can you confirm that by "Upgrade failed" you see jgroups error above, and by "Upgrade Successful" everything is functioning correctly? 

Also are you explicitly setting lower_case_table_names = 0, or is this simply the default on your system?

This does seem to imply that keycloak is issuing nominally ansi compliant queries that need "ower_case_table_names = 1".

May need to also involve @team/core-shared

**Comment by pedroigor** [comment]
@huangjy6688 Thanks for the additional information. It is still not clear how to reproduce it and how migrating/upgrading the database schema has to do with the issue description.

If you can help us reproduce this using a raw container image and a MySQL database, we appreciate.
