### ISSUE TITLE
LdapSyncTest failures running with external Active Directory

### ISSUE THREAD

**Issue by pdrozd** [keycloak/keycloak#27499]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

The data in AD are not properly cleaned by the test (test05MissingLDAPUsernameSync) and it causes the other tests failures. 

```
java.lang.RuntimeException: org.keycloak.testsuite.runonserver.RunOnServerException: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.testsuite.client.KeycloakTestingClient$Server.fetch(KeycloakTestingClient.java:135)
	at org.keycloak.testsuite.federation.ldap.LDAPSyncTest.test05MissingLDAPUsernameSync(LDAPSyncTest.java:358)
```

```
java.lang.RuntimeException: org.keycloak.testsuite.runonserver.RunOnServerException: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.testsuite.client.KeycloakTestingClient$Server.fetch(KeycloakTestingClient.java:135)
	at org.keycloak.testsuite.federation.ldap.LDAPSyncTest.test09MembershipUsingDifferentAttributes(LDAPSyncTest.java:512)
```

### Version

24

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests should pass

### Actual behavior

Tests are failing

### How to Reproduce?

Run the ldap testsuite with external AD

**Comment by ahus1** [comment]
@pdrozd - I see this issue is marked for backporting to KC24. Please create the necessary backports for KC24 and KC22. Thanks!
