### ISSUE TITLE
Custom Browser Flow not working anymore

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#27548]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Newly created authentication flows do not work but throw exception and show error message in logs.

### Version

24.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Flow shows Login Form with username and password.

### Actual behavior

Shows error:

![image](https://github.com/keycloak/keycloak/assets/12183470/89a0a576-3008-487a-b84c-1e68ceb5a4fb)

with stacktrace in logs:

```
2024-03-05 11:58:02,597 WARN  [org.keycloak.services] (executor-thread-16) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: Unknown flow provider type
        at org.keycloak.authentication.AuthenticationProcessor.createFlowExecution(AuthenticationProcessor.java:879)
        at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1026)
        at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:884)
        at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:152)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:337)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:202)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:113)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint$quarkusrestinvoker$buildGet_4b690b27439f19dd29733dc5fd4004f24de0adb6.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

`flow.getProviderId()` seems to return an empty string ("").

### How to Reproduce?

- Setup a fresh Keycloak instance
- Create a new Authentication flow of type "Basic flow"
- Add a single authenticator "Username Password Form"
- Bind the flow to the user flow
- Try to login into a client, eg. admin console

**Comment by sventorben** [comment]
This seems to be an issue within Keycloak admin console (frontend), because the request does not contain the providerId:

![image](https://github.com/keycloak/keycloak/assets/12183470/53f5a304-252e-4e26-bad5-e2276aa786c5)

**Comment by sventorben** [comment]
I assume this is caused by this empty string default value: https://github.com/keycloak/keycloak/blob/24.0.1/js/apps/admin-ui/src/authentication/form/CreateFlow.tsx#L72

**Comment by spantaleev** [comment]
I got bitten by this regression as well.

Until v24.0.2 comes around, one could work around this issue in 2 ways:

1. *Either* during initial flow creation by changing **Flow type** to another value (e.g. *Client flow*) and then back to *Basic flow*. This would make the *Basic flow* value "stick" and your flow will be created correctly.

2. *Or* later on, if you've already ended up with a corrupted flow in your database

- updating the `provider_id` flow in the `authentication_flow` database table to a a value of `basic-flow` for your new flow. Example SQL query: `UPDATE authentication_flow SET provider_id = 'basic-flow' WHERE alias = 'browser-custom-flow';`. You may also update all flows that have an empty `provider_id` value: `UPDATE authentication_flow SET provider_id = 'basic-flow' WHERE provider_id = '';`
- restarting Keycloak for the change to take effect
