### ISSUE TITLE
Refresh periodic syncs when changing the LDAP connection settings

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#27554]
### Description

The periodic sync task is only refreshed/restarted when there are changes to the periodic sync options and changing the connection URL has no effect.

Ideally, the task should run with the latest connection settings set to the provider and force a re-start of the periodic sync task whenever these settings are updates.

At the very least, we should consider adding the `Connection URL` to the list of settings that forces the task to re-start.

### Discussion

https://github.com/keycloak/keycloak/issues/27394

### Motivation

Improve how the LDAP periodic sync task is run based on the latest settings from the provider.

**Comment by ajit2548** [comment]
We had a DC failure recently( technically may be similar to issue mentioned in https://github.com/keycloak/keycloak/issues/27394).

After restoration, keycloak server was unable to attend any call to LDAP server. 

We have the stack trace as:
`Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@3f233b6f
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:167)
	... 63 more
Caused by: org.keycloak.models.ModelException: Could not query server using DN [DC=DUMMY,DC=DUMMY,DC=DUMMY,DC=DUMMY] and filter [(&(objectClass=*)(objectGUID=\06\c6\ed\35\0c\31\e2\46\a9\c4\92\25\79\47\73\2c))]
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.lookupById(LDAPOperationManager.java:442)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:261)
	... 64 more
Caused by: javax.naming.NamingException: LDAP connection has been closed
	at java.naming/com.sun.jndi.ldap.LdapRequest.getReplyBer(LdapRequest.java:133)
	at java.naming/com.sun.jndi.ldap.Connection.readReply(Connection.java:442)
	at java.naming/com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:365)
	at java.naming/com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2896)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxIns`

It only resolved after manual restart of keycloak server.

I hope above issue also will be addressed as part of this.

**Comment by ajit2548** [comment]
Do you have any ETA?
