### ISSUE TITLE
dropping KC_PROXY=edge causes startup error 

### ISSUE THREAD

**Issue by tobhv** [keycloak/keycloak#27597]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

upgrade guide recommends to switch to environment variable KC_PROXY_HEADERS instead of using KC_PROXY=edge
i added KC_PROXY_HEADERS=xforwarded and removed KC_PROXY but then keycloak shows this error:
```
keycloak_1  | 2024-03-06 10:54:12,177 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak_1  | 2024-03-06 10:54:12,177 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
```
workaround: keep KC_PROXY=edge in place.
but then keycloak warns:
```
The following used options or option values are DEPRECATED and will be removed in a future release:
keycloak_1  |   - proxy: Use proxy-headers.
```

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

desired setup: let reverse proxy (nginx in my case) do tls decryption and forward traffic unencrypted to docker container.
configured with some environment variables activated for reverse proxy config:
```
KC_HOSTNAME_URL=https://openid.appelo.org # note: KC_HOSTNAME also works fine.
KC_METRICS_ENABLED=true
KC_PROXY_HEADERS=xforwarded
```

### Actual behavior

starting up the docker container gives:
```
keycloak_1  | 2024-03-06 10:54:08,838 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
keycloak_1  | 2024-03-06 10:54:08,900 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: https://***REMOVED_FQDN***, Hostname: ***REMOVED_FQDN***, Strict HTTPS: true, Path: /, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
keycloak_1  | 2024-03-06 10:54:09,050 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
keycloak_1  | 2024-03-06 10:54:09,275 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
keycloak_1  | 2024-03-06 10:54:09,285 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: c77e8b79-a8f6-43c9-b1a8-b30e31ee487d, name: fc017e573d2a-15843
keycloak_1  | 2024-03-06 10:54:09,298 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
keycloak_1  | 2024-03-06 10:54:09,298 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
keycloak_1  | 2024-03-06 10:54:09,299 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
keycloak_1  | 2024-03-06 10:54:09,299 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
keycloak_1  | 2024-03-06 10:54:09,310 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.19790
keycloak_1  | 2024-03-06 10:54:11,063 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
keycloak_1  | 2024-03-06 10:54:11,327 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) fc017e573d2a-15843: no members discovered after 2013 ms: creating cluster as coordinator
keycloak_1  | 2024-03-06 10:54:11,338 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [fc017e573d2a-15843|0] (1) [fc017e573d2a-15843]
keycloak_1  | 2024-03-06 10:54:11,365 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `fc017e573d2a-15843`, physical addresses are `[172.27.0.2:35326]`
keycloak_1  | 2024-03-06 10:54:11,402 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
keycloak_1  | 2024-03-06 10:54:12,153 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
keycloak_1  | 2024-03-06 10:54:12,177 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak_1  | 2024-03-06 10:54:12,177 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
keycloak_1  | 2024-03-06 10:54:12,177 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
looks like keycloak wants to activate https now for itself? i do not want that.
running with verbose switch gives same output plus stack trace:
```
verbose error output:

 at org.keycloak.quarkus.runtime.Messages.httpsConfigurationNotSet(Messages.java:48)
 at org.keycloak.quarkus.runtime.configuration.mappers.HttpPropertyMappers.getHttpEnabledTransformer(HttpPropertyMappers.java:142)
 at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(PropertyMapper.java:215)
 at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.getConfigValue(PropertyMapper.java:125)
 at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.getValue(PropertyMappers.java:48)
 at org.keycloak.quarkus.runtime.configuration.PropertyMappingInterceptor.getValue(PropertyMappingInterceptor.java:86)
 at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
 at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:395)
 at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:302)
 at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$vertx$http$runtime$HttpConfiguration(Unknown Source)
 at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
 at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
 at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
 at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
 at io.quarkus.runtime.Application.start(Application.java:101)
 at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
 at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
 at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:117)
 at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:33)
 at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
 at picocli.CommandLine.access$1500(CommandLine.java:148)
 at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
 at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
 at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
 at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
 at picocli.CommandLine.execute(CommandLine.java:2170)
 at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:125)
 at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
 at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
```

### How to Reproduce?

to reproduce no reverse proxy is needed. just build, start your keycloak docker container on some linux box with mentioned environment variables at "actual behavior". again: just adding KC_PROXY=edge allows container to startup. 
docker file i use to build is here:
```
ARG QUAY_REGISTRY
ARG REGISTRY
ARG KC_VER
FROM ${QUAY_REGISTRY}/keycloak/keycloak:${KC_VER} as builder
# support metrics and health check
ENV KC_METRICS_ENABLED=true
ENV KC_HEALTH_ENABLED=true
# configure mariadb as the db to be supported
ENV KC_DB=mariadb
# support secrets 
ENV KC_VAULT=file
RUN /opt/keycloak/bin/kc.sh build

#use redhat image that supports installing packages
FROM ${REGISTRY}/redhat/ubi9-minimal

COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY rootfs /
USER root
RUN microdnf upgrade -y;\
    microdnf install -y --nodocs --setopt=install_weak_deps=0 \
    java-17-openjdk-headless \
    glibc-langpack-en \
    jq \
    shadow-utils;\
    chmod +x /usr/local/bin/health.sh; \
    useradd -s /sbin/nologin keycloak; \
    microdnf remove libsemanage shadow-utils -y; \
    microdnf clean all;\
    rm -rf \
    /var/lib/dnf
USER keycloak
HEALTHCHECK CMD /usr/local/bin/health.sh
WORKDIR /opt/keycloak
ENV KC_METRICS_ENABLED=true
ENV KC_HEALTH_ENABLED=true
ENV LANG en_US.UTF-8
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
```

### Anything else?

- changing KC_HOSTNAME_URL to KC_HOSTNAME gives same behavior.
- setting KC_HOSTNAME_STRICT to false does not help as well.

**Comment by shawkins** [comment]
See the migration note https://www.keycloak.org/docs/latest/upgrading/index.html 

"kc.sh --proxy edge" is to be replaced by "kc.sh --proxy-headers forwarded|xforwarded --http-enabled true"

@vmuzikar do you want to consider a more verbose deprecation message?

**Comment by vmuzikar** [comment]
@shawkins IMHO the [migration table](https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option) is quite verbose already. Do you have anything else in mind?

**Comment by shawkins** [comment]
@vmuzikar I mean the message:

```
The following used options or option values are DEPRECATED and will be removed in a future release:
keycloak_1  |   - proxy: Use proxy-headers.
```

It does not mention needing to set other options, just proxy-headers. Maybe a blanket addendem to all deprecation messages could mention checking the migration guide just as a catch all.

**Comment by tobhv** [comment]
thx. indeed KC_HTTP_ENABLED fixes this. 
i looked at various places but did not find it initially.. (sorry).
but: this guide lacks the http-enabled switch and the fact that it's mandatory in case of tls decryption at the reverse proxy: https://www.keycloak.org/server/reverseproxy
and i interpreted http-enabled in https://www.keycloak.org/server/all-config as a switch to just activate http protocol (including https) which i assumed was already working. but your response is very fast so kudo's for that.!
do i need to close this issue or will you handle closure ?

**Comment by vmuzikar** [comment]
> Maybe a blanket addendem to all deprecation messages could mention checking the migration guide just as a catch all.

@shawkins That's a good idea. Something like:
```
The following used options or option values are DEPRECATED and will be removed in a future release:
keycloak_1  |   - proxy: Use proxy-headers.
Consult the migration guide for details.
```

**Comment by shawkins** [comment]
@tobhv we'll let this be closed by https://github.com/keycloak/keycloak/pull/27613

**Comment by ahus1** [comment]
@shawkins - as you've created the original PR, may I ask you to create also the backport for KC24? Thanks!
