### ISSUE TITLE
Flaky test: org.keycloak.testsuite.admin.concurrency.ConcurrencyTest#testAllConcurrently

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#27676]
## org.keycloak.testsuite.admin.concurrency.ConcurrencyTest#testAllConcurrently
[Keycloak CI - Base IT (1)](https://github.com/keycloak/keycloak/actions/runs/8190075358/job/22396634109) / [Pull Request #27667](https://github.com/keycloak/keycloak/pull/27667)

```
java.lang.RuntimeException: There were failures in threads. Failures count: 1
	at org.keycloak.testsuite.admin.concurrency.AbstractConcurrencyTest.run(AbstractConcurrencyTest.java:122)
	at org.keycloak.testsuite.admin.concurrency.AbstractConcurrencyTest.run(AbstractConcurrencyTest.java:63)
	at org.keycloak.testsuite.admin.concurrency.AbstractConcurrencyTest.run(AbstractConcurrencyTest.java:59)
	at org.keycloak.testsuite.admin.concurrency.ConcurrencyTest.concurrentTest(ConcurrencyTest.java:61)
...
```

**Comment by pedroigor** [comment]
Noticed random failures after https://github.com/keycloak/keycloak/pull/27577.

**Comment by pedroigor** [comment]
Didn't notice enough failures to indicate it is something related to the changes mentioned [in the description](https://github.com/keycloak/keycloak/issues/27676#issuecomment-1984232782).
