### ISSUE TITLE
User Creation - REST API & Admin-CLI

### ISSUE THREAD

**Issue by citestsco** [keycloak/keycloak#27802]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/java-cli

### Describe the bug

Hi Guys,

Recently in my company we've created new KeyCloak instance for another site.
We wish to replicate the users from old KeyCloak to the new one.
Although nothing works, i've tried Admin-CLI & REST API but yet i receive the same error.
I am running KeyCloak version 24.0.1 under docker container.

Trying to import bulk of hundreds of users , but yet receiving some error which i couldn't find anything related on documents  or google.

Please help.
Thanks.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Successfully import bulk of users from JSON file.

### Actual behavior

JSON users templates:
[ {
  "username" : "user_imporddt",
  "email" : "somi@com.com"
} ]

JSON 2:
[ {
  "id" : "f4aa7a4b-a347-415e-a3c0-10da30ad8d9c",
  "username" : "user_import",
  "email" : "somi@com.com",
  "emailVerified" : true,
  "createdTimestamp" : 1710169762684,
  "enabled" : true,
  "totp" : false,
  "disableableCredentialTypes" : [ ],
  "requiredActions" : [ ],
  "notBefore" : 0,
  "access" : {
    "manageGroupMembership" : true,
    "view" : true,
    "mapRoles" : true,
    "impersonate" : true,
    "manage" : true
  }
} ]

The command executed with Admin-CLI:
kcadm.sh create users --realm tclient < temp.json
Error Received:
For more on this error consult the server log at the debug level. [unknown_error]

The POST request sent via REST API:
curl -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
    "username": "user1",
    "email": "user1@example.com",
    "enabled": true
  }' \
  "http://localhost:8080/auth/admin/realms/tclient/users"
Error received:
{"error":"Unable to find matching target resource method","error_description":"For more on this error consult the server log at the debug level."}

Same JSON's were used in both methods.

Java error:
 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-258) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.idm.UserRepresentation.getUsername()" because "rep" is null
        at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:131)
        at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)

### How to Reproduce?

Try to import users from JSON file

### Anything else?

HELP
I NEED HELP

**Comment by mposolda** [comment]
Please use user-forum when asking for support and not report bugs here.
