### ISSUE TITLE
Keycloak Failed to make identity provider oauth callback

### ISSUE THREAD

**Issue by gilamarko** [keycloak/keycloak#27862]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I have configured Azure AD as IDP on Keycloak, everything works fine. When I enable the Access Token is JWT the authentication fails and the user is not registered with this error message on UI Unexpected error when authenticating with identity provider

This is the stacktrace

```
2024-03-13T13:05:09.867220707Z 2024-03-13 13:05:09,865 DEBUG [org.keycloak.social.user_profile_dump] (executor-thread-40) User Profile JSON Data for provider Azure-Ad: {"sub":"eD-SqwDp9fqwe5PNfzA754EJnML9eV5XqZi7fAN0EL0","name":"Name Name","family_name":"Name","given_name":"Name","picture":"https://graph.microsoft.com/v1.0/me/photo/$value","email":"myemail@email.com"}
2024-03-13T13:05:09.867227507Z 2024-03-13 13:05:09,865 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-40) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: token signature validation failed
2024-03-13T13:05:09.867233607Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.parseTokenInput(OIDCIdentityProvider.java:676)
2024-03-13T13:05:09.867238907Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:693)
2024-03-13T13:05:09.867244107Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.processAccessTokenResponse(OIDCIdentityProvider.java:259)
2024-03-13T13:05:09.867259007Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.extractIdentity(OIDCIdentityProvider.java:545)
2024-03-13T13:05:09.867263907Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:393)
2024-03-13T13:05:09.867268907Z 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:553)
2024-03-13T13:05:09.867273908Z 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_fef2d69ce31937f365a37fb3083f9247bc4c56d2.invoke(Unknown Source)
2024-03-13T13:05:09.867279508Z 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-03-13T13:05:09.867285208Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-03-13T13:05:09.867290608Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-03-13T13:05:09.867296108Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
2024-03-13T13:05:09.867301208Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-03-13T13:05:09.867306408Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-03-13T13:05:09.867312608Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-03-13T13:05:09.867317808Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-03-13T13:05:09.867322808Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-03-13T13:05:09.867328309Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-13T13:05:09.867333709Z 
2024-03-13T13:05:09.868729934Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) new JtaTransactionWrapper
2024-03-13T13:05:09.868748034Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) was existing? true
2024-03-13T13:05:09.868891836Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) JtaTransactionWrapper  commit
2024-03-13T13:05:09.868903437Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) JtaTransactionWrapper end
2024-03-13T13:05:09.868908437Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) JtaTransactionWrapper resuming suspended
2024-03-13T13:05:09.868977538Z 2024-03-13 13:05:09,868 WARN  [org.keycloak.events] (executor-thread-40) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="d7b12b12-cd9d-404f-1aa4-2d95f538b4b0", clientId="my-shop-fe", userId="null", ipAddress="12.123.123.12", error="identity_provider_login_failure", code_id="b240e0f9-1432-4046-a874-718651efc5f0"
```

### Version

24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

I expected this to work and be able to use mappers for extracting information from access_token.

### Actual behavior

Exception is thrown

```
2024-03-13T13:05:09.867220707Z 2024-03-13 13:05:09,865 DEBUG [org.keycloak.social.user_profile_dump] (executor-thread-40) User Profile JSON Data for provider Azure-Ad: {"sub":"eD-SqwDp9fqwe5PNfzA754EJnML9eV5XqZi7fAN0EL0","name":"Name Name","family_name":"Name","given_name":"Name","picture":"https://graph.microsoft.com/v1.0/me/photo/$value","email":"myemail@email.com"}
2024-03-13T13:05:09.867227507Z 2024-03-13 13:05:09,865 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-40) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: token signature validation failed
2024-03-13T13:05:09.867233607Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.parseTokenInput(OIDCIdentityProvider.java:676)
2024-03-13T13:05:09.867238907Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:693)
2024-03-13T13:05:09.867244107Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.processAccessTokenResponse(OIDCIdentityProvider.java:259)
2024-03-13T13:05:09.867259007Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.extractIdentity(OIDCIdentityProvider.java:545)
2024-03-13T13:05:09.867263907Z 	at org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:393)
2024-03-13T13:05:09.867268907Z 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:553)
2024-03-13T13:05:09.867273908Z 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_fef2d69ce31937f365a37fb3083f9247bc4c56d2.invoke(Unknown Source)
2024-03-13T13:05:09.867279508Z 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-03-13T13:05:09.867285208Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-03-13T13:05:09.867290608Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-03-13T13:05:09.867296108Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
2024-03-13T13:05:09.867301208Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-03-13T13:05:09.867306408Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-03-13T13:05:09.867312608Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-03-13T13:05:09.867317808Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-03-13T13:05:09.867322808Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-03-13T13:05:09.867328309Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-13T13:05:09.867333709Z 
2024-03-13T13:05:09.868729934Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) new JtaTransactionWrapper
2024-03-13T13:05:09.868748034Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) was existing? true
2024-03-13T13:05:09.868891836Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) JtaTransactionWrapper  commit
2024-03-13T13:05:09.868903437Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) JtaTransactionWrapper end
2024-03-13T13:05:09.868908437Z 2024-03-13 13:05:09,868 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-40) JtaTransactionWrapper resuming suspended
2024-03-13T13:05:09.868977538Z 2024-03-13 13:05:09,868 WARN  [org.keycloak.events] (executor-thread-40) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="d7b12b12-cd9d-404f-1aa4-2d95f538b4b0", clientId="my-shop-fe", userId="null", ipAddress="12.123.123.12", error="identity_provider_login_failure", code_id="b240e0f9-1432-4046-a874-718651efc5f0"
```

### How to Reproduce?

Using Keycloak 24.0.0 and setting up azure ad as IDP and enabling the Access Token is JWT. When the user tries to log the mentioned behavior is happening.

**Comment by mposolda** [comment]
I am not sure if this is bug. I guess it doesn't work because accessToken coming from AzureAD is not JWT?

The switch `Access Token is JWT` can be used just if access-token coming from 3rd party IDP (which is Azure AD) is in the JWT format. Access token is JWT in many cases (like for example KEycloak access tokens are JWT), but it is not guaranteed as per OAuth2/OIDC specification, Access token can be opaque string without any restrictions on the format.

**Comment by gilamarko** [comment]
From what I see having debug logs enabled, the token is a JWT
```
2024-03-13 13:22:21 2024-03-13 11:22:21,360 DEBUG [org.apache.http.wire] (executor-thread-55) http-outgoing-9 << "{"token_type":"Bearer","scope":"openid profile email","expires_in":4821,"ext_expires_in":4821,"access_token":"mytoken"}"
```

```
{
  "aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/279985bd-2077-4d9d-9797-42238cfc06e2/",
  "iat": 1710328642,
  "nbf": 1710328642,
  "exp": 1710333764,
  "acct": 0,
  "acr": "1",
  "aio": "ATQAy/8WAAAALdAlAKLp5TZZQcd2KKR6NLuJXniEoKI2KTUTKu2GNghDnj1UJbTijnedRNgg2a4X",
  "amr": [
    "pwd"
  ],
  "app_displayname": "app-registration",
  "appid": "2debd8ef-c775-42cd-a3a7-6f572abb2525",
  "appidacr": "1",
  "family_name": "Name",
  "given_name": "Name",
  "idtyp": "user",
  "ipaddr": "62.103.170.91",
  "name": "Name Name",
  "oid": "737313f6-8cab-4859-9b29-6e9b66d877c3",
  "onprem_sid": "S-1-5-21-832780979-4291355995-1262236316-8038",
  "platf": "3",
  "puid": "100320026633C4E3",
  "rh": "0.AYIAvYWZJ3cgnU2Xl0IjjPwG4gMAAAAAAAAAwAAAAAAAAACCACc.",
  "scp": "openid profile email",
  "signin_state": [
    "inknownntwk"
  ],
  "sub": "td_lgnKhtynwPzLnLrd2PMJCsw9vBSyNZwbpCPlwSN4",
  "tenant_region_scope": "EU",
  "tid": "279985bd-2077-4d9d-9797-42238cfc06e2",
  "unique_name": "maemail@email.com",
  "upn": "maemail@email.com",
  "uti": "l952Jz9-AUeqkTK1_LYeAA",
  "ver": "1.0",
  "wids": [
    "b79fbf4d-3ef9-1231-8223-76b194e85509"
  ],
  "xms_st": {
    "sub": "LzkfkGC-R1M_O5qw5LOuUUhp_YfYDuc1TnE2asdaLSs"
  },
  "xms_tcdt": 1420699837,
  "xms_tdbr": "EU"
}
```

**Comment by rmartinc** [comment]
I think that the signature validation is failing for the access token. Maybe the token is not signed or it's signed with an unknown key or any other error. Add trace to oidc with startup option `--log-level=INFO,org.keycloak.broker:TRACE` and check if there is some debug message about signatures before. 

Can you paste the full access token received in raw? Does it work if the option `Validate Signatures` is set to OFF in the identity provider?

**Comment by serge378** [comment]
> I had the same issue, but disabling the Validate Signatures **AND** in Azure AD manifest settings, I had to set the `accessTokenAcceptedVersion: 2`. Is this helpful?

Just set the `accessTokenAcceptedVersion: 2` and use V2.0 endpoint URLs  on keycloak side.
That works for me.
