### ISSUE TITLE
Keycloak continues to send data after the TCP connection is terminated by MySQL triggering MySQL resets and 'Network response was not OK' in the GUI

### ISSUE THREAD

**Issue by jean-christophe-manciot** [keycloak/keycloak#28105]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

With a standalone keycloak server using a MySQL server located on the same local Linux bridge without any network traffic interference, no TCP connection termination initiated by MySQL is respected by keycloak which continues to send data without opening a new TCP connection despite acknowledging the TCP 'FIN'.
This triggers TCP resets from MySQL and falied GUI requests with the error message  'Network response was not OK'.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

no 'Network response was not OK' error messages in the GUI when the network is dedicated tp kc <--> MySQL

### Actual behavior

1. Log into a kerycloak server (as admin)
2. Click on 'Realm Roles' for instance on the left
3. Wait for 5 seconds
4. Click on 'Clients' for instance on the left
5. Notice the following error:
![keycloak PeriodicRecovery consequences in GUI 1](https://github.com/keycloak/keycloak/assets/13176858/84a0daaf-462d-4907-aac5-4133c2bea03b)

In the MySQL log, the keycloak error matches this error:
```
{ "prio" : 3, "err_code" : 10914, "subsystem" : "Server", "source_file" : "sql_connect.cc", "function" : "end_connection", "msg" : "Aborted connection 161 to db: 'keycloak' user: 'keycloak' host: 'keycloak.example.com' (Got an error reading communication packets).", "time" : "2024-03-20T14:20:41.848940Z", "ts" : 1710943624589, "thread" : 161, "err_symbol" : "ER_ABORTING_USER_CONNECTION", "SQL_state" : "HY000", "label" : "Note" }
```

In wireshark, the typical sequence is shown below where:
- 192.168.122.11 is the MySQL server
- 192.168.122.21 is the keycloak server
![Wireshark typical trace](https://github.com/keycloak/keycloak/assets/13176858/77fb83eb-cb65-40e8-84af-2a1510881741)

### How to Reproduce?

After purging keycloak server and the keycloak database from the MySQL server:

1. Creating keycloak database and user on the external mysql server
2. Downloading keycloak server 24.0.1
3. Setting up:
- [conf/keycloak.conf](https://github.com/keycloak/keycloak/files/14668930/keycloak.conf.txt)
- [conf/quarkus.properties](https://github.com/keycloak/keycloak/files/14668943/quarkus.properties.txt)
4. Building with:
```
bin/kc.sh build
```
5. Starting with:
```
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD='my-password' 

bin/kc.sh start --proxy-headers=xforwarded &
```

### Environment
```
keycloak 24.0.1

2024-03-19 17:46:46,596 DEBUG [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) Database ->
       name : MySQL
    version : 8.0.35-0ubuntu0.23.04.1
      major : 8
      minor : 0
2024-03-19 17:46:46,596 DEBUG [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) Driver ->
       name : MySQL Connector/J
    version : mysql-connector-j-8.3.0 (Revision: 805f872a57875f311cb82487efcfb070411a3fa0)
      major : 8
      minor : 3
```
All connections with MySQL server are encrypted with TLS 1.3:
```
tls-version="TLSv1.3"
require_secure_transport=ON
```

### Anything else?

1. As indicated in the official [kc database doc](https://www.keycloak.org/server/db), ```Do NOT use the --optimized flag for the start command if you want to use a particular DB (except the H2)```
2. I honestly do not know why the MySQL server closes the TCP connection after 5 seconds of inactivity:
    - the [wait_timeout](https://dev.mysql.com/doc/refman/8.3/en/server-system-variables.html#sysvar_wait_timeout) parameter is set to 8 hours on MySQL:
    ```
        +--------------------------+----------+
        | Variable_name            | Value    |
        +--------------------------+----------+
        | innodb_lock_wait_timeout | 600      |
        | lock_wait_timeout        | 31536000 |
        | mysqlx_wait_timeout      | 28800    |
        | wait_timeout             | 28800    |
        +--------------------------+----------+
    ```
    - there is not a single MySQL timeout parameter set to 5s. 
 3. In any case, the keycloak server should reopen the TCP connection after each termination.

**Comment by jean-christophe-manciot** [comment]
I am aware of the following MySQL docs:
  + [Lost connection to MySQL server](https://dev.mysql.com/doc/refman/8.0/en/error-lost-connection.html)
  + [Communication Errors and Aborted Connections](https://dev.mysql.com/doc/refman/8.0/en/communication-errors.html)

In the latter paper, the following paragraph fits the situation:
```
If a client successfully connects but later disconnects improperly or is terminated, the server increments the [Aborted_clients](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Aborted_clients) status variable, and logs an Aborted connection message to the error log.
```
Indeed:
```
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| Aborted_clients        | 36    |
| Mysqlx_aborted_clients | 0     |
+------------------------+-------+
```
despite very high MySQL settings:
- [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout): 8 hours
- [interactive_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_interactive_timeout): 8 hours
- [max_allowed_packet](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet): 1G

**Comment by sschu** [comment]
From what I remember about TCP connection closing, whoever is receiving a FIN is not required to immediately respond with a FIN packet itself. It is just a signal from one party to the other that it does not want to send any data anymore but instead close the connection. Only when the receiver confirms it and sends a FIN packet, the connection is really closed. Before that, the receiver can still send some data. 

In your example, is there an ongoing transaction or is the connection idle? To me, it looks like Keycloak is sending another 109 bytes. If this was data from an ongoing transaction, it would actually be fine if Keycloak at least wants to finish it and the connection reset by MySQL is the problem.

You also write "I honestly do not know why the MySQL server closes the TCP connection after 5 seconds of inactivity:". That behaviour does not seem right to me. There will definitely be times without activity longer than 5 seconds especially if there is no activity in Keycloak.

It would be ideal if you could replicate the issue using a container setup with a Keycloak and a MySQL container.

**Comment by jean-christophe-manciot** [comment]
> In your example, is there an ongoing transaction or is the connection idle? To me, it looks like Keycloak is sending another 109 bytes. If this was data from an ongoing transaction, it would actually be fine if Keycloak at least wants to finish it and the connection reset by MySQL is the problem.

1. Keycloak requires the data to MySQL to answer the admin request to refresh a GUI page
2. the admin gets the info and waits for 5 s
3. MySQL **closes the connection**
4. the admin tries to get another page
5. keycloak requests the data to MySQL **without reopening the TCP connection which has been closed by MySQL**
6. MySQL sends a RESET
7. the admin gets the error message on the screen
8. the admin refreshes the GUI
9. keycloak reopens the TCP connection (SYN/SYN-ACK/ACK) and gets the data from MySQL
10. ... endless cycle of errors

**Comment by jean-christophe-manciot** [comment]
> You also write "I honestly do not know why the MySQL server closes the TCP connection after 5 seconds of inactivity:". That behaviour does not seem right to me. There will definitely be times without activity longer than 5 seconds especially if there is no activity in Keycloak.

I agree that this is not efficient at all, but keycloak should try to reopen the TCP connection each time it is closed by the MySQL server for whatever reason.

**Comment by shawkins** [comment]
This is similar to #24493 and should be addressed by tweaking the datasource pool configuration. The connections will need to be validated as they are obtained from the pool - try using a [quarkus.datasource.jdbc.validation-query-sql](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus-datasource-jdbc-validation-query-sql)

**Comment by sschu** [comment]
You say "5. keycloak requests the data to MySQL without reopening the TCP connection which has been closed by MySQL". MySQL cannot close the connection by just sending a FIN. Closing a connection is a three-way handshake. When MySQL sends a FIN, the connection is still half-open. 

You could say Keycloak should agree to closing the connection by responding with a FIN.  But this depends on what Keycloak is currently doing with the connection in that moment. It should probably rather respond with a FIN instead of trying to start a new transaction for a new request (and this is what your example sounds like). But if it is currently in the middle of a transaction, it is fine if Keycloak tries to finish the transaction even if MySQL wants to close the connection.

**Comment by sschu** [comment]
@shawkins I don't think #24493 is related. That one talks about being connected to a read-only replica instead of the primary copy. All connections are intact, just writes are not possible and Keycloak cannot work with that.

**Comment by shawkins** [comment]
@sschu I don't mean to imply it's the same situation, just that it could have a similar fix. If step 5 is happening after the connection has been returned to the pool, then if you validate the connection when getting it from the pool, you'll end up with a fresh connection instead.

**Comment by jean-christophe-manciot** [comment]
Hmm... Could it be that the 5s timeout discussed above is caused by the default value of [quarkus.datasource.jdbc.acquisition-timeout](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus-datasource-jdbc-acquisition-timeout)? This is becoming stranger & stranger.

**Comment by jean-christophe-manciot** [comment]
Thanks again to @shawkins, I have just found a **workaround which masks the previous issue** by maintaining at least 5 always-on connections with MySQL server:
```
quarkus.datasource.jdbc.acquisition-timeout=600
quarkus.datasource.jdbc.background-validation-interval=5
quarkus.datasource.jdbc.validation-query-sql=SELECT 1
quarkus.datasource.jdbc.initial-size=5
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.transaction-manager.enable-recovery=true
quarkus.transaction-manager.default-transaction-timeout=600
```

The GUI errors are gone but I can see the same erratic TCP behavior from Keycloak with:
- numerous RESETs in wireshark trace 
- numerous 'Communications link failures' in keycloak logs

**Comment by jean-christophe-manciot** [comment]
> > Hmm... Could it be that the 5s timeout discussed above is caused by the default value of [quarkus.datasource.jdbc.acquisition-timeout](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus-datasource-jdbc-acquisition-timeout)? This is becoming stranger & stranger.
> 
> Do you see any argoal messages in the logs about that? Or perhaps try at a debug level.

Not a single one:
```
/var/log/keycloak# grep -IPRi --include='*' argoal
/var/log/keycloak# 
```

**Comment by shawkins** [comment]
> But that was after I modified the quarkus properties and reinstalled Keycloak from scratch...

Well at least there's progress.

It seems like you'll still want to understand better why connections are taking so long to create.

> The GUI errors are gone but I can see the same erratic TCP behavior from Keycloak with

By Keycloak do you mean something in the application layer or the MySQL driver? It seems like this would be an issue for the driver - that may require further tweaking the datasource via url properties.

**Comment by jean-christophe-manciot** [comment]
If I revert back to the old configuration and start over from scratch, it's the same: nothing about ```argoal```
```
/var/log/keycloak# grep -IPRi --include='*' argoal
/var/log/keycloak# 
```

**Comment by shawkins** [comment]
> If I revert back to the old configuration and start over from scratch, it's the same: nothing about argoal

Ok. If you can please include any stacktraces or the full messages about "Communications link failures" so that we'll have that captured with this issue.

**Comment by jean-christophe-manciot** [comment]
> It seems like you'll still want to understand better why connections are taking so long to create.

Not exactly. I'd like to help troubleshoot and solve this issue .

> It seems like this would be an issue for the driver - that may require further tweaking the datasource via url properties.

I agree.

> Ok. If you can please include any stacktraces or the full messages about "Communications link failures" so that we'll have that captured with this issue.

I realize I should have looked for agroal not argoal.... Here's an excerpt:
```
2024-03-21 16:29:44,924 DEBUG [liquibase.changelog.ChangeSet] (main) Table CLIENT_AUTH_FLOW_BINDINGS created
2024-03-21 16:29:45,257 WARN  [io.quarkus.agroal.runtime.DataSources] (agroal-11) Connection validation failed: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 5,059 milliseconds ago. The last packet sent successfully to the server was 5,061 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:770)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653)
	at com.mysql.cj.jdbc.StatementWrapper.execute(StatementWrapper.java:529)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
	at io.quarkus.agroal.runtime.DataSources$3.isValid(DataSources.java:404)
	at io.agroal.pool.ConnectionHandler.isValid(ConnectionHandler.java:246)
	at io.agroal.pool.ConnectionPool.performValidation(ConnectionPool.java:350)
	at io.agroal.pool.ConnectionPool$ValidationTask$ValidateConnectionTask.run(ConnectionPool.java:726)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 5,059 milliseconds ago. The last packet sent successfully to the server was 5,061 milliseconds ago.
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1050)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:658)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:730)
	... 13 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
	... 19 more

2024-03-21 16:29:45,263 WARN  [io.quarkus.agroal.runtime.DataSources] (agroal-11) Connection validation failed: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 5,075 milliseconds ago. The last packet sent successfully to the server was 5,078 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:770)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653)
	at com.mysql.cj.jdbc.StatementWrapper.execute(StatementWrapper.java:529)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
	at io.quarkus.agroal.runtime.DataSources$3.isValid(DataSources.java:404)
	at io.agroal.pool.ConnectionHandler.isValid(ConnectionHandler.java:246)
	at io.agroal.pool.ConnectionPool.performValidation(ConnectionPool.java:350)
	at io.agroal.pool.ConnectionPool$ValidationTask$ValidateConnectionTask.run(ConnectionPool.java:726)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 5,075 milliseconds ago. The last packet sent successfully to the server was 5,078 milliseconds ago.
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1050)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:658)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:730)
	... 13 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
	... 19 more

2024-03-21 16:29:45,265 WARN  [io.quarkus.agroal.runtime.DataSources] (agroal-11) Connection validation failed: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 5,074 milliseconds ago. The last packet sent successfully to the server was 5,076 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:770)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653)
	at com.mysql.cj.jdbc.StatementWrapper.execute(StatementWrapper.java:529)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
	at io.quarkus.agroal.runtime.DataSources$3.isValid(DataSources.java:404)
	at io.agroal.pool.ConnectionHandler.isValid(ConnectionHandler.java:246)
	at io.agroal.pool.ConnectionPool.performValidation(ConnectionPool.java:350)
	at io.agroal.pool.ConnectionPool$ValidationTask$ValidateConnectionTask.run(ConnectionPool.java:726)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 5,074 milliseconds ago. The last packet sent successfully to the server was 5,076 milliseconds ago.
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:582)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1050)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:658)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:730)
	... 13 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
	... 19 more

2024-03-21 16:29:45,407 DEBUG [jdk.event.security] (agroal-11)  TLSHandshake: mysql.example.com:3306, TLSv1.3, TLS_AES_256_GCM_SHA384, -647526145

```

**Comment by shawkins** [comment]
> I realize I should have looked for agroal not argoal.... Here's an excerpt

Sorry that was my typo that started that.

> The last packet successfully received from the server was 5,059 milliseconds ago. The last packet sent successfully to the server was 5,061 milliseconds ago.

I'm not an expert in the mysql driver, but I don't see anything promising in https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html that would address that.

It seems like "quarkus.datasource.jdbc.background-validation-interval=5" should help aliviate this - but will put a lot of unnecessary load on your database. Quarkus documents that as taking an interval, does it default to seconds?

Finally this situation is very similar to https://vanwilgenburg.wordpress.com/2013/04/17/mysql-8hr-timeout/ - on the server what is @@GLOBAL.wait_timeout set to?

**Comment by jean-christophe-manciot** [comment]
> I'm not an expert in the mysql driver, but I don't see anything promising in https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html that would address that.

If I'm not mistaken, Keycloak 24.0.1 uses JDBC 3.8.1. Isn't time to upgrade to JDBC 4.x?

> It seems like "quarkus.datasource.jdbc.background-validation-interval=5" should help aliviate this - but will put a lot of unnecessary load on your database. Quarkus documents that as taking an interval, does it default to seconds?

I don't think that checking every 5s is a putting "a lot of unnecessary load on your database".

> Finally this situation is very similar to https://vanwilgenburg.wordpress.com/2013/04/17/mysql-8hr-timeout/ - on the server what is @@GLOBAL.wait_timeout set to?

8 hours

**Comment by jean-christophe-manciot** [comment]
> Finally this situation is very similar to https://vanwilgenburg.wordpress.com/2013/04/17/mysql-8hr-timeout/ - on the server what is @@GLOBAL.wait_timeout set to?

The context is not detailed and I don't see any usable solution in this post. Anyway, I don't think this issue comes from MySQL.

**Comment by shawkins** [comment]
> If I'm not mistaken, Keycloak 24.0.1 uses JDBC 3.8.1. Isn't time to upgrade to JDBC 4.x?

What version are you referring to here? The JDBC spec (it supports the latest, which is 4.3, the MySQL driver (it's at version 8.3.0)

> I don't think that checking every 5s is a putting "a lot of unnecessary load on your database".

It will be every 5 seconds for each idle connection, which looks like it could be 20 of them. As long as that 

> 8 hours

Nowhere close to 5 seconds. 

> The context is not detailed and I don't see any usable solution in this post.

Just that clients were seeing those similar packet messages after a period of time and a validation query keep the exception as a pool level concern.

> Anyway, I don't think this issue comes from MySQL.

Maybe look again at what could be happening in between at the network layer.

Does it seem like we'll need a resolution here (additional docs?) on the keycloak side?

**Comment by jean-christophe-manciot** [comment]
> What version are you referring to here? The JDBC spec (it supports the latest, which is 4.3), the MySQL driver (it's at version 8.3.0), or something else?

My bad; I just saw lib/lib/main/io.quarkus.quarkus-jdbc-mysql-3.8.1.jar.

> > 8 hours

> Nowhere close to 5 seconds.

So? It just means that MySQL server won't be the one closing the connection due to inactivity before 8 hours: ```The number of seconds the server waits for activity on a noninteractive connection before closing it.``` This confirms that the issue comes from keycloak driver.

**Comment by shawkins** [comment]
> This confirms that the issue comes from keycloak driver.

Unforutnately it does not. You have it narrowed down to the driver or below. It would be great to test any other mysql client from the machine where your keycloak instance resides. In particular I would bet that any other MySQL JDBC you try would exhibit the same behavior - clarifying that this is not a Keycloak specific issue.

**Comment by jean-christophe-manciot** [comment]
Yes, that's what I meant and we should report this bug to the JDBC mysql driver forum.

**Comment by shawkins** [comment]
Sounds good. I'll close this on the Keycloak side, then feel free to reopen if there is more documentation or some other resolution that seems good here.

**Comment by jean-christophe-manciot** [comment]
As promised, here is the bug report on Oracle site: [MySQL Connector/J never participates in the TCP connection terminations](https://bugs.mysql.com/bug.php?id=114453&thanks=sub)

**Comment by shawkins** [comment]
Thank you, that will help drive toward a better solution.
