### ISSUE TITLE
Occasional NotAuthorizedException since Keycloak 24.0

### ISSUE THREAD

**Issue by nils-christian** [keycloak/keycloak#28130]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

Hi,

Since Keycloak 24.0, we encountered flaky tests. This seems to match a flaky test reported in https://github.com/keycloak/keycloak/issues/27973.

We are using 
* Keycloak-Container: quay.io/keycloak/keycloak:24.0
* Keycloak-Admin-Client: 24.0.1
* Keycloak-Testcontainers: 3.3.0
* Testcontainers: 1.19.7

Please take a look at the following test:
```
@RepeatedTest( 1000)
	void test( ) {
		try ( final KeycloakContainer keycloakContainer = new KeycloakContainer( "quay.io/keycloak/keycloak:24.0" ) ) {
			keycloakContainer.start( );
			try ( final Keycloak keycloak = keycloakContainer.getKeycloakAdminClient( ) ) {
				final RealmRepresentation realm = new RealmRepresentation( );
				realm.setId( "realm" );
				realm.setRealm( "realm"  );
				realm.setDisplayName( "realm"  );
				realm.setEnabled( true );

				keycloak.realms( ).create( realm );
			}
		}
	}
```

As you can see, the test starts a container and creates a realm. Up to 23.0 this worked reliably. However, since 24.0 this test case fails in some cases with an NotAuthorizedException.

The full stack trace:

```
12:57:55.591 [docker-java-stream-1974148964] INFO tc.quay.io/keycloak/keycloak:24.0 -- STDOUT: 2024-03-21 11:57:55,590 WARN  [org.keycloak.events] (executor-thread-1) type="LOGIN_ERROR", realmId="2b9489d8-4c23-48d9-87f9-c2421f51f0d9", clientId="admin-cli", userId="null", ipAddress="172.17.0.1", error="user_not_found", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="admin"

jakarta.ws.rs.ProcessingException: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized

	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:652)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:424)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)
	at jdk.proxy2/jdk.proxy2.$Proxy37.create(Unknown Source)
	at com.example.demo.LeTest.test(LeTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:238)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:216)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:59)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:136)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)
	at jdk.proxy2/jdk.proxy2.$Proxy35.grantToken(Unknown Source)
	at org.keycloak.admin.client.token.TokenManager.grantToken(TokenManager.java:99)
	at org.keycloak.admin.client.token.TokenManager.getAccessToken(TokenManager.java:75)
	at org.keycloak.admin.client.token.TokenManager.getAccessTokenString(TokenManager.java:70)
	at org.keycloak.admin.client.resource.BearerAuthFilter.filter(BearerAuthFilter.java:52)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:644)
```

Thank you and best regards

  Nils

### Version

24.0

### Regression

- [X] The issue is a regression

### Expected behavior

Creation of a realm should always work.

### Actual behavior

Creation of the realm fails sometimes.

### How to Reproduce?

See the above example.

**Comment by nils-christian** [comment]
Hi @mposolda,

This is the TRACE output during the login failure:

```
2024-04-12 06:16:48,179 TRACE [org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess] (executor-thread-1) Executing query to retrieve ResultSet : select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.USERNAME=? and ue1_0.REALM_ID=?
2024-04-12 06:16:48,179 DEBUG [org.hibernate.SQL] (executor-thread-1) select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.USERNAME=? and ue1_0.REALM_ID=?
2024-04-12 06:16:48,180 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImple.getStatus: jakarta.transaction.Status.STATUS_ACTIVE
2024-04-12 06:16:48,180 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-1) Registering statement [wrapped[ prep924: select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.USERNAME=? and ue1_0.REALM_ID=? ]]
2024-04-12 06:16:48,180 TRACE [org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl] (executor-thread-1) Registering last query statement [wrapped[ prep924: select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.USERNAME=? and ue1_0.REALM_ID=? ]]
2024-04-12 06:16:48,180 TRACE [org.hibernate.orm.jdbc.bind] (executor-thread-1) binding parameter (1:NVARCHAR) <- [admin]
2024-04-12 06:16:48,180 TRACE [org.hibernate.orm.jdbc.bind] (executor-thread-1) binding parameter (2:VARCHAR) <- [bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2]
2024-04-12 06:16:48,180 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-1) Registering result set [io.agroal.pool.wrapper.ResultSetWrapper@75c18631]
2024-04-12 06:16:48,180 TRACE [org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor] (executor-thread-1) LogicalConnection#afterStatement
2024-04-12 06:16:48,180 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-1) Releasing result set [io.agroal.pool.wrapper.ResultSetWrapper@75c18631]
2024-04-12 06:16:48,180 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-1) Closing result set [io.agroal.pool.wrapper.ResultSetWrapper@75c18631]
2024-04-12 06:16:48,180 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-1) Releasing statement [wrapped[ prep924: select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.USERNAME=? and ue1_0.REALM_ID=? {1: 'admin', 2: 'bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2'} ]]
2024-04-12 06:16:48,180 TRACE [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-1) Closing prepared statement [wrapped[ prep924: select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.USERNAME=? and ue1_0.REALM_ID=? {1: 'admin', 2: 'bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2'} ]]
2024-04-12 06:16:48,180 TRACE [org.hibernate.engine.internal.StatefulPersistenceContext] (executor-thread-1) Initializing non-lazy collections
2024-04-12 06:16:48,181 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImple.getStatus: jakarta.transaction.Status.STATUS_ACTIVE
2024-04-12 06:16:48,181 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImple.getStatus: jakarta.transaction.Status.STATUS_ACTIVE
2024-04-12 06:16:48,181 TRACE [org.keycloak.models.cache.infinispan.UserCacheSession] (executor-thread-1) model from delegate null
2024-04-12 06:16:48,182 TRACE [org.keycloak.services.DefaultKeycloakSession] (executor-thread-1) Created session @ 4797ba38
    org.keycloak.services.DefaultKeycloakSession.<init>(DefaultKeycloakSession.java:91)
    org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSession.<init>(QuarkusKeycloakSession.java:29)
    org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.create(QuarkusKeycloakSessionFactory.java:129)
    org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:375)
    org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:269)
    org.keycloak.events.EventBuilder.send(EventBuilder.java:246)
    org.keycloak.events.EventBuilder.error(EventBuilder.java:233)
    org.keycloak.authentication.authenticators.directgrant.ValidateUsername.authenticate(ValidateUsername.java:74)
    org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:442)
    org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
    org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1027)
    org.keycloak.protocol.oidc.grants.ResourceOwnerPasswordCredentialsGrantType.process(ResourceOwnerPasswordCredentialsGrantType.java:107)
    org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:139)
    org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
2024-04-12 06:16:48,182 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImpleManager.suspend
2024-04-12 06:16:48,182 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::removeChildThread () action 0:ffffac110003:920d:6618d1cb:25 removing 2
2024-04-12 06:16:48,182 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::removeChildThread () action 0:ffffac110003:920d:6618d1cb:25 removing 2 result = true
2024-04-12 06:16:48,182 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) new JtaTransactionWrapper
2024-04-12 06:16:48,183 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) was existing? true
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.jta] (executor-thread-1) BaseTransaction.begin
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) StateManager::StateManager( 2, 0 )
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::BasicAction()
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::Begin() for action-id 0:ffffac110003:920d:6618d1cb:2b
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::actionInitialise() for action-id 0:ffffac110003:920d:6618d1cb:2b
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) ActionHierarchy::ActionHierarchy(1)
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) ActionHierarchy::add(0:ffffac110003:920d:6618d1cb:2b, 1)
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::addChildThread () action 0:ffffac110003:920d:6618d1cb:2b adding Thread[executor-thread-1,5,main]
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::addChildThread () action 0:ffffac110003:920d:6618d1cb:2b adding Thread[executor-thread-1,5,main] result = true
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) TransactionReaper::insert ( BasicAction: 0:ffffac110003:920d:6618d1cb:2b status: ActionStatus.RUNNING, 300 )
2024-04-12 06:16:48,183 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) ReaperElement::ReaperElement ( BasicAction: 0:ffffac110003:920d:6618d1cb:2b status: ActionStatus.RUNNING, 300 )
2024-04-12 06:16:48,183 TRACE [org.infinispan.interceptors.impl.InvocationContextInterceptor] (executor-thread-1) Invoked realms with command GetKeyValueCommand {key=bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2, flags=[]} and InvocationContext [SingleKeyNonTxInvocationContext{isLocked=false, key=null, cacheEntry=null, origin=null, lockOwner=null}]
2024-04-12 06:16:48,183 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Exists in context? null 
2024-04-12 06:16:48,183 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Retrieved from container ImmortalCacheEntry{key=bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2, value=org.keycloak.models.cache.infinispan.entities.CachedRealm@311d2611, internalMetadata=null}
2024-04-12 06:16:48,183 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Wrap bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2 for read. Entry=ImmortalCacheEntry{key=bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2, value=org.keycloak.models.cache.infinispan.entities.CachedRealm@311d2611, internalMetadata=null}
2024-04-12 06:16:48,183 TRACE [org.infinispan.interceptors.impl.CallInterceptor] (executor-thread-1) Invoking: GetKeyValueCommand
2024-04-12 06:16:48,183 TRACE [org.infinispan.interceptors.impl.InvocationContextInterceptor] (executor-thread-1) Invoked realmRevisions with command GetKeyValueCommand {key=bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2, flags=[]} and InvocationContext [SingleKeyNonTxInvocationContext{isLocked=false, key=null, cacheEntry=null, origin=null, lockOwner=null}]
2024-04-12 06:16:48,183 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Exists in context? null 
2024-04-12 06:16:48,183 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Retrieved from container ImmortalCacheEntry{key=bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2, value=72, internalMetadata=null}
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Creating new entry for key bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Wrap bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2 for read. Entry=RepeatableReadEntry(52224867){key=bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2, value=72, oldValue=72, isCreated=false, isChanged=false, isRemoved=false, isExpired=false, isCommited=false, skipLookup=false, metadata=EmbeddedMetadata{version=null}, oldMetadata=EmbeddedMetadata{version=null}, internalMetadata=null}
2024-04-12 06:16:48,184 TRACE [org.infinispan.interceptors.impl.CallInterceptor] (executor-thread-1) Invoking: GetKeyValueCommand
2024-04-12 06:16:48,184 TRACE [org.keycloak.models.cache.infinispan.RealmCacheSession] (executor-thread-1) by id cache hit: master
2024-04-12 06:16:48,184 TRACE [org.infinispan.interceptors.impl.InvocationContextInterceptor] (executor-thread-1) Invoked realms with command GetKeyValueCommand {key=7081efd8-3740-4f85-87ff-74b6569a305c, flags=[]} and InvocationContext [SingleKeyNonTxInvocationContext{isLocked=false, key=null, cacheEntry=null, origin=null, lockOwner=null}]
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Exists in context? null 
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Retrieved from container ImmortalCacheEntry{key=7081efd8-3740-4f85-87ff-74b6569a305c, value=org.keycloak.models.cache.infinispan.entities.CachedClient@496e6148, internalMetadata=null}
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Wrap 7081efd8-3740-4f85-87ff-74b6569a305c for read. Entry=ImmortalCacheEntry{key=7081efd8-3740-4f85-87ff-74b6569a305c, value=org.keycloak.models.cache.infinispan.entities.CachedClient@496e6148, internalMetadata=null}
2024-04-12 06:16:48,184 TRACE [org.infinispan.interceptors.impl.CallInterceptor] (executor-thread-1) Invoking: GetKeyValueCommand
2024-04-12 06:16:48,184 TRACE [org.infinispan.interceptors.impl.InvocationContextInterceptor] (executor-thread-1) Invoked realmRevisions with command GetKeyValueCommand {key=7081efd8-3740-4f85-87ff-74b6569a305c, flags=[]} and InvocationContext [SingleKeyNonTxInvocationContext{isLocked=false, key=null, cacheEntry=null, origin=null, lockOwner=null}]
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Exists in context? null 
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Retrieved from container ImmortalCacheEntry{key=7081efd8-3740-4f85-87ff-74b6569a305c, value=57, internalMetadata=null}
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Creating new entry for key 7081efd8-3740-4f85-87ff-74b6569a305c
2024-04-12 06:16:48,184 TRACE [org.infinispan.container.impl.EntryFactoryImpl] (executor-thread-1) Wrap 7081efd8-3740-4f85-87ff-74b6569a305c for read. Entry=RepeatableReadEntry(2522776f){key=7081efd8-3740-4f85-87ff-74b6569a305c, value=57, oldValue=57, isCreated=false, isChanged=false, isRemoved=false, isExpired=false, isCommited=false, skipLookup=false, metadata=EmbeddedMetadata{version=null}, oldMetadata=EmbeddedMetadata{version=null}, internalMetadata=null}
2024-04-12 06:16:48,184 TRACE [org.infinispan.interceptors.impl.CallInterceptor] (executor-thread-1) Invoking: GetKeyValueCommand
2024-04-12 06:16:48,184 TRACE [org.keycloak.models.cache.infinispan.RealmCacheSession] (executor-thread-1) client by id cache hit: admin-cli
2024-04-12 06:16:48,184 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImple.getStatus: jakarta.transaction.Status.STATUS_ACTIVE
2024-04-12 06:16:48,184 TRACE [org.keycloak.services.DefaultKeycloakSession] (executor-thread-1) Closing session @ 4797ba38 (transaction active)
    org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:363)
    org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
    org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:269)
    org.keycloak.events.EventBuilder.send(EventBuilder.java:246)
    org.keycloak.events.EventBuilder.error(EventBuilder.java:233)
    org.keycloak.authentication.authenticators.directgrant.ValidateUsername.authenticate(ValidateUsername.java:74)
    org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:442)
    org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
    org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1027)
    org.keycloak.protocol.oidc.grants.ResourceOwnerPasswordCredentialsGrantType.process(ResourceOwnerPasswordCredentialsGrantType.java:107)
    org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:139)
    org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImple.getStatus: jakarta.transaction.Status.STATUS_ACTIVE
2024-04-12 06:16:48,185 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper  commit
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.jta] (executor-thread-1) BaseTransaction.commit
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImple.commitAndDisassociate
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::End() for action-id 0:ffffac110003:920d:6618d1cb:2b
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::End() result for action-id (0:ffffac110003:920d:6618d1cb:2b) is (TwoPhaseOutcome.PREPARE_OK) node id: (quarkus)
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::removeChildThread () action 0:ffffac110003:920d:6618d1cb:2b removing 2
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::removeChildThread () action 0:ffffac110003:920d:6618d1cb:2b removing 2 result = true
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) TransactionReaper::remove ( BasicAction: 0:ffffac110003:920d:6618d1cb:2b status: ActionStatus.COMMITTED )
2024-04-12 06:16:48,185 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper end
2024-04-12 06:16:48,185 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper resuming suspended
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.jta] (executor-thread-1) TransactionImpleManager.resume
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::addChildThread () action 0:ffffac110003:920d:6618d1cb:25 adding Thread[executor-thread-1,5,main]
2024-04-12 06:16:48,185 TRACE [com.arjuna.ats.arjuna] (executor-thread-1) BasicAction::addChildThread () action 0:ffffac110003:920d:6618d1cb:25 adding Thread[executor-thread-1,5,main] result = true
2024-04-12 06:16:48,187 TRACE [org.keycloak.events] (executor-thread-1) type="LOGIN_ERROR", realmId="bd7c271d-8152-45e8-a5c0-3e9a2d74bcb2", clientId="admin-cli", userId="null", ipAddress="172.17.0.1", error="user_not_found", auth_method="openid-connect", grant_type="password", client_auth_method="client-secret", username="admin", requestUri="http://localhost:54083/realms/master/protocol/openid-connect/token", cookies=[], stackTrace=
    org.keycloak.events.log.JBossLoggingEventListenerProvider.logEvent(JBossLoggingEventListenerProvider.java:126)
    org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
    org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
    org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
    org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
    org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
    org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:384)
    org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:269)
    org.keycloak.events.EventBuilder.send(EventBuilder.java:246)
    org.keycloak.events.EventBuilder.error(EventBuilder.java:233)
    org.keycloak.authentication.authenticators.directgrant.ValidateUsername.authenticate(ValidateUsername.java:74)
    org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:442)
    org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
    org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1027)
    org.keycloak.protocol.oidc.grants.ResourceOwnerPasswordCredentialsGrantType.process(ResourceOwnerPasswordCredentialsGrantType.java:107)
    org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:139)
    org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
2024-04-12 06:16:48,188 DEBUG [org.keycloak.authentication.DefaultAuthenticationFlow] (executor-thread-1) authenticator FAILED: direct-grant-validate-username
2024-04-12 06:16:48,188 TRACE [org.keycloak.models.sessions.infinispan.InfinispanKeycloakTransaction] (executor-thread-1) Adding cache operation: REPLACE on 864a3cbd-f605-40e5-ac61-e282ba3e0d53. Lifespan 1,800 SECONDS.
2024-04-12 06:16:48,188 TRACE [org.keycloak.authentication.DefaultAuthenticationFlow] (executor-thread-1) Set execution status: Execution: direct-grant-validate-username, status: FAILED
2024-04-12 06:16:48,188 TRACE [org.keycloak.models.sessions.infinispan.InfinispanKeycloakTransaction] (executor-thread-1) Adding cache operation: REPLACE on 864a3cbd-f605-40e5-ac61-e282ba3e0d53. Lifespan 1,800 SECONDS.
```

Is it possible, that the regression is only regarding the time it takes for the admin user to be created? In the meantime we are using code that waits up to one minute until the access to _keycloak.realms( ).findAll( )_ is possible without exception and this seems to solve the issue. However, given that we never encountered the issue with the previous Keycloak versions I still assume this to be some kind of regression.

Best regards

  Nils

**Comment by mposolda** [comment]
Thanks for the additional info!

As you pointed, this seems to be just the possible insufficient waiting time. I think this is rather the issue in the `Keycloak-Testcontainers` rather than Keycloak issue. The `KeycloakContainer` should probably return from it's `start` method once the Keycloak is fully started (including the admin user fully initialized). And it seems that it returns too early without checking that Keycloak server is really fully bootstrapped. So I suggest to rather report this issue to the `Keycloak-Testcontainers` project.
