### ISSUE TITLE
Can't login as an admin "Unexpected error when handling authentication request to identity provider." / "Unable to acquire JDBC Connection"

### ISSUE THREAD

**Issue by DanielKucal** [keycloak/keycloak#28153]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Admin UI stopped working:
<img width="503" alt="image" src="https://github.com/keycloak/keycloak/assets/8938562/954f3124-be7d-465f-8c97-afbbd770df1e">
Tapping on "« Back to Application" gives the same error over and over again.

When trying to access root Keycloak URL the following error appears:
<img width="498" alt="image" src="https://github.com/keycloak/keycloak/assets/8938562/9917088b-5669-4563-9a62-8d9091108288">

After clearing cookies, I am able to see login form again, but "Internal server error" on root page continues and login doesn't work (thinks for a while and then says "Unexpected error when handling authentication request to identity provider.").

### Version

24.0.1 (docker image quay.io/keycloak/keycloak:latest)

### Regression

- [ ] The issue is a regression

### Expected behavior

I'd expect it to not break randomly.

### Actual behavior

Admin UI breaks (rest seems to continue working), in docker console I can see those error logs:

```
2024-03-21 21:44:12,904 WARN  [org.keycloak.events] (executor-thread-159) type="LOGIN_ERROR", realmId="5610bcef-e0e8-452d-b939-d2ea764d417f", clientId="security-admin-console", userId="null", ipAddress="172.17.0.1", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="http://127.0.0.1:8080/admin/master/console/", code_id="443f6f64-09f5-4c90-9221-7952a63143b4", username="admin"

2024-03-21 21:50:34,798 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-168) SQL Error: 0, SQLState: null

2024-03-21 21:50:34,801 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-168) Acquisition timeout while waiting for new connection

2024-03-21 21:50:34,805 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-168) Uncaught server error: jakarta.ws.rs.WebApplicationException: HTTP 500 Internal Server Error

at org.keycloak.services.resources.WelcomeResource.createWelcomePage(WelcomeResource.java:232)

at org.keycloak.services.resources.WelcomeResource.getWelcomePage(WelcomeResource.java:92)

at org.keycloak.services.resources.WelcomeResource$quarkusrestinvoker$getWelcomePage_3d46f4348f9016709ff9c5ca428ac29847ab83d6.invoke(Unknown Source)

at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)

at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)

at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)

at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)

at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)

at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)

at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)

at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

at java.base/java.lang.Thread.run(Thread.java:840)

Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection [Acquisition timeout while waiting for new connection] [n/a]

at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)

at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)

at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:116)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:143)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:54)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:153)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:155)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.lambda$list$0(JdbcSelectExecutor.java:85)

at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:231)

at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)

at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)

at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)

at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)

at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)

at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:202)

at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)

at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:209)

at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$2(ConcreteSqmSelectQueryPlan.java:137)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:362)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:303)

at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:509)

at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427)

at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:564)

at org.keycloak.models.jpa.JpaUserProvider.getUsersCount(JpaUserProvider.java:599)

at org.keycloak.storage.UserStorageManager.getUsersCount(UserStorageManager.java:440)

at org.keycloak.models.cache.infinispan.UserCacheSession.getUsersCount(UserCacheSession.java:558)

at org.keycloak.storage.user.UserCountMethodsProvider.getUsersCount(UserCountMethodsProvider.java:47)

at org.keycloak.services.managers.ApplianceBootstrap.isNoMasterUser(ApplianceBootstrap.java:58)

at org.keycloak.services.resources.WelcomeResource.shouldBootstrap(WelcomeResource.java:256)

at org.keycloak.services.resources.WelcomeResource.createWelcomePage(WelcomeResource.java:181)

... 12 more

Caused by: java.sql.SQLException: Acquisition timeout while waiting for new connection

at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:321)

at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:249)

at io.agroal.pool.DataSource.getConnection(DataSource.java:86)

at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)

at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:46)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:113)

... 43 more

Caused by: java.util.concurrent.TimeoutException

at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:298)

... 48 more


2024-03-21 21:51:47,963 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-168) SQL Error: 0, SQLState: null

2024-03-21 21:51:47,964 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-168) Acquisition timeout while waiting for new connection

2024-03-21 21:51:47,966 WARN  [org.keycloak.services] (executor-thread-168) KC-SERVICES0013: Failed authentication: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection [Acquisition timeout while waiting for new connection] [n/a]

at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)

at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)

at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:116)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:143)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:54)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:153)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:155)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.lambda$list$0(JdbcSelectExecutor.java:85)

at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:231)

at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)

at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)

at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)

at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)

at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)

at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:202)

at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)

at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:209)

at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$2(ConcreteSqmSelectQueryPlan.java:137)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:362)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:303)

at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:509)

at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427)

at org.hibernate.query.Query.getResultList(Query.java:120)

at org.keycloak.models.jpa.JpaUserProvider.getUserByUsername(JpaUserProvider.java:531)

at org.keycloak.storage.UserStorageManager.getUserByUsername(UserStorageManager.java:380)

at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByUsername(UserCacheSession.java:270)

at org.keycloak.models.utils.KeycloakModelUtils.findUserByNameOrEmail(KeycloakModelUtils.java:247)

at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUserFromForm(AbstractUsernameFormAuthenticator.java:189)

at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.getUser(AbstractUsernameFormAuthenticator.java:168)

at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validateUserAndPassword(AbstractUsernameFormAuthenticator.java:149)

at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.validateForm(UsernamePasswordForm.java:55)

at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.action(UsernamePasswordForm.java:48)

at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:151)

at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:987)

at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:364)

at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:335)

at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:327)

at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:392)

at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)

at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)

at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)

at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)

at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)

at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)

at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)

at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)

at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

at java.base/java.lang.Thread.run(Thread.java:840)

Caused by: java.sql.SQLException: Acquisition timeout while waiting for new connection

at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:321)

at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:249)

at io.agroal.pool.DataSource.getConnection(DataSource.java:86)

at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)

at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:46)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:113)

... 50 more

Caused by: java.util.concurrent.TimeoutException

at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:298)

... 55 more


2024-03-21 21:51:47,984 WARN  [org.keycloak.events] (executor-thread-168) type="LOGIN_ERROR", realmId="5610bcef-e0e8-452d-b939-d2ea764d417f", clientId="security-admin-console", userId="null", ipAddress="172.17.0.1", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="http://127.0.0.1:8080/admin/master/console/", code_id="443f6f64-09f5-4c90-9221-7952a63143b4", username="admin"

2024-03-21 21:55:57,566 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 0, SQLState: null

2024-03-21 21:55:57,569 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) Acquisition timeout while waiting for new connection

2024-03-21 21:55:57,575 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredEvents: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection [Acquisition timeout while waiting for new connection] [n/a]

at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)

at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)

at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:116)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:143)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:54)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:153)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)

at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:155)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.lambda$list$0(JdbcSelectExecutor.java:85)

at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:231)

at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)

at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)

at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)

at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)

at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)

at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:202)

at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)

at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:209)

at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)

at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$2(ConcreteSqmSelectQueryPlan.java:137)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:362)

at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:303)

at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:509)

at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427)

at org.hibernate.query.Query.getResultList(Query.java:120)

at org.keycloak.events.jpa.JpaEventStoreProvider.clearExpiredEvents(JpaEventStoreProvider.java:94)

at org.keycloak.services.scheduled.ClearExpiredEvents.run(ClearExpiredEvents.java:39)

at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:56)

at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner$1.call(ClusterAwareScheduledTaskRunner.java:52)

at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:78)

at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)

at org.keycloak.services.scheduled.ScheduledTaskRunner.lambda$run$0(ScheduledTaskRunner.java:59)

at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:257)

at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:379)

at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:256)

at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:53)

at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)

at java.base/java.util.TimerThread.mainLoop(Timer.java:566)

at java.base/java.util.TimerThread.run(Timer.java:516)

Caused by: java.sql.SQLException: Acquisition timeout while waiting for new connection

at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:321)

at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:249)

at io.agroal.pool.DataSource.getConnection(DataSource.java:86)

at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)

at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:46)

at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:113)

... 38 more

Caused by: java.util.concurrent.TimeoutException

at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:298)

... 43 more
```

### How to Reproduce?

Not sure if this is relevant, but the circumstances were as follows: I've tried adding user attribute in "Attributes" tab with the same as existing property defined in Realm, which failed (that's good).  After that I've just refreshed the page and started to see the errors.

### Anything else?
Keycloak running by `start-dev`
Database server version: 10.6.17-MariaDB-cll-lve - MariaDB Server

After image restart:
```
2024-03-21 22:10:57,664 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_974663, Site name: null

2024-03-21 22:11:02,711 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode

2024-03-21 22:11:02,711 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection

2024-03-21 22:11:02,711 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Acquisition timeout while waiting for new connection
```

Edit: After third restart and a quarter, started to work again.

**Comment by ssilvert** [comment]
@DanielKucal So you were adding a User Profile attribute that has the same name as a realm attribute?  Which name?

Since this is a server-side error, I'm going to switch this to the core team.

**Comment by pedroigor** [comment]
@DanielKucal I'm a bit confused about the steps to reproduce the issue. That error you are facing is kinda a weird one and I'm wondering if isn't the case of adjusting the database pool configuration according to your needs. See https://www.keycloak.org/server/db.

What is the attribute you are trying to add to a user?

**Comment by DanielKucal** [comment]
> So you were adding a User Profile attribute that has the same name as a realm attribute? Which name?

> What is the attribute you are trying to add to a user?

@ssilvert exactly, it was a custom name surely not used by Keycloak - "credits"

Here's the exact configuration of the attribute:
<img width="795" alt="image" src="https://github.com/keycloak/keycloak/assets/8938562/c4693626-bebd-40ad-a280-a3aafad51803">
BTW is there a way to set default value?

> See https://www.keycloak.org/server/db.

I've read that page, but it doesn't mention anything specific for MariaDB except that it was tested with v10.11. The database server I'm currently using is out of my control and has been recently updated from 10.6.16 to 10.6.17, but everything seems to work except this issue.

**Comment by pedroigor** [comment]
@DanielKucal It does not seem related to the attribute. If you can provide the exact steps to reproduce the problem with the arguments you are using to start the server it should help to continue the investigation.

Otherwise, we can't do much.

We do have tests creating attributes like you are doing and lots of them. Not sure what might be but something related to how your database connection pool is configured.

> BTW is there a way to set default value?

Not yet. Please, create an issue/enhancement because I think it makes sense.
