### ISSUE TITLE
Since KC 24.0.1 NotAuthorizedException: HTTP 401 Unauthorized with invalidToken on userinfo endpoint

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak#28183]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

Since update on 03. March to Keycloak 24.0.1 (comming from 23.0.7) we have now since two days a lot of `jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized` due to `invalidToken`
Our Application has not been changed in that area, but the error is seen.

Keycloak is running as cluster with Infinispan enabled and no Infinispan configuration was changed since months.

The error disappeard after stopping one node. It makes no sence to me, since load balancer routes a session to same node always.
But having a "single node" was the strange fix.

### Version

24.0.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

token handling works correctly (as before in all versions <24.0.1)
```
2024-03-22 21:03:31,556 TRACE [org.keycloak.events:130] [executor-thread-333] type="USER_INFO_REQUEST", realmId="5ab0d9b5-2896-4b38-874b-8b32bdf9d528", clientId="<client_id>", userId="cd9066f4-86a5-4044-9125-7b46529f6558", ipAddress="10.x.x.x", auth_method="validate_access_token", signature_required="false", username="useraccount@test.de", requestUri="https://<keycloakdomain>/auth/realms/<realm_name>/protocol/openid-connect/userinfo", cookies=[]
```

### Actual behavior

In the log file you can see that the LOGIN was successful, then our application calls userinfo and this fails.

```
2024-03-22 20:26:15,010 DEBUG [org.keycloak.authentication.DefaultAuthenticationFlow:568] [executor-thread-338] Authentication successful of the top flow 'browser'
2024-03-22 20:26:15,010 DEBUG [org.keycloak.locale.LocaleSelectorProvider:57] [executor-thread-338] Setting locale for user useraccount@test.de to de
2024-03-22 20:26:15,012 DEBUG [org.keycloak.services.managers.AuthenticationSessionManager:174] [executor-thread-338] Removing root authSession '2116aa8d-5611-4893-a5aa-7f49535cbe74'. Expire restart cookie: true
2024-03-22 20:26:15,013 DEBUG [org.keycloak.protocol.oidc.OIDCLoginProtocol:218] [executor-thread-338] redirectAccessCode: state: rENTP69mHW06n-dEdReM_vEeGA162ZxJ7YZqnopsPeA=
2024-03-22 20:26:15,014 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:89] [executor-thread-338] JtaTransactionWrapper  commit
2024-03-22 20:26:15,014 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:152] [executor-thread-338] JtaTransactionWrapper end

2024-03-22 20:26:15,014 TRACE [org.keycloak.events:130] [executor-thread-338] type="LOGIN", realmId="<realm_name>", clientId="<client_id>", userId="af9a39bd-b8d9-401e-98a2-021c9e71a3a9", ipAddress="10.x.x.x", auth_method="openid-connect", auth_type="code", response_type="code",
redirect_uri="https://<keycloakdomain>/login/oauth2/code/keycloak", consent="no_consent_required", code_id="2116aa8d-5611-4893-a5aa-7f49535cbe74", username="useraccount@test.de", response_mode="query", authSessionParentId="2116aa8d-5611-4893-a5aa-7f49535cbe74",
authSessionTabId="x-okw4WR8eM", requestUri="https://<keycloakdomain>/auth/realms/<realm_name>/login-actions/authenticate?session_code=w5e5u5KyyLCijKJyfVhmJalFOghwKKjccUItsn-nNOI&execution=9ddaeb3d-23a0-4e5c-9d50-b716781825d1&client_id=<client_id>&tab_id=x-okw4WR8eM",
cookies=[KEYCLOAK_LOCALE=de, SESSION=62e56f04-16b8-45dc-8978-ffec332b743c, AUTH_SESSION_ID_LEGACY=2116aa8d-5611-4893-a5aa-7f49535cbe74.atp-keycloak-1-43685, KC_RESTART=eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3YTRjMTU1MS1jZDZiLTRiYTktYmIyZC1lNzEyYzBkNzIwMjMifQ.eyJjaWQiOiJhcGktc2VydmVyIi
wicHR5Ijoib3BlbmlkLWNvbm5lY3QiLCJydXJpIjoiaHR0cHM6Ly9teS5kLXRydXN0Lm5ldC9sb2dpbi9vYXV0aDIvY29kZS9rZXljbG9hayIsImFjdCI6IkFVVEhFTlRJQ0FURSIsIm5vdGVzIjp7InNjb3BlIjoib3BlbmlkIiwiaXNzIjoiaHR0cHM6Ly9teS5kLXRydXN0Lm5ldC9hdXRoL3JlYWxtcy9hbnRyYWdzcG9ydGFsIiwicmVzcG9uc2VfdHlwZSI6ImNvZGUiLCJy
ZWRpcmVjdF91cmkiOiJodHRwczovL215LmQtdHJ1c3QubmV0L2xvZ2luL29hdXRoMi9jb2RlL2tleWNsb2FrIiwic3RhdGUiOiJyRU5UUDY5bUhXMDZuLWRFZFJlTV92RWVHQTE2Mlp4SjdZWnFub3BzUGVBPSIsIm5vbmNlIjoiMHVPOXU5QjZhS1d4NjFSQnZGd0tkaGd1YWtiOVkzOU1WZk9MTll1NnZjdyJ9fQ.AV0DKzFMKw2XL9leUFPUCZVYFWLrHQsijnjubsQXsI69lqX
lmJ4iEVhPbq8Aenv_arwS3l5J3z7_IKI2qb1acw, AUTH_SESSION_ID=2116aa8d-5611-4893-a5aa-7f49535cbe74.atp-keycloak-1-43685]

2024-03-22 20:26:15,014 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:48] [Brute Force Protector] new JtaTransactionWrapper
2024-03-22 20:26:15,014 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:49] [Brute Force Protector] was existing? false
2024-03-22 20:26:15,014 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:89] [Brute Force Protector] JtaTransactionWrapper  commit
2024-03-22 20:26:15,014 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:152] [Brute Force Protector] JtaTransactionWrapper end
2024-03-22 20:26:15,076 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:48] [executor-thread-338] new JtaTransactionWrapper
2024-03-22 20:26:15,076 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:49] [executor-thread-338] was existing? false

2024-03-22 20:26:15,077 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser:193] [executor-thread-338] Recalculated absoluteURI to https://<keycloakdomain>/auth/realms/<realm_name>/protocol/openid-connect/userinfo
2024-03-22 20:26:15,079 DEBUG [org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider:511] [executor-thread-338] getUserSessionWithPredicate(2116aa8d-5611-4893-a5aa-7f49535cbe74): found in local cache
2024-03-22 20:26:15,079 DEBUG [org.keycloak.services.util.UserSessionUtil:100] [executor-thread-338] Stale token for user session
2024-03-22 20:26:15,079 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:48] [executor-thread-338] new JtaTransactionWrapper
2024-03-22 20:26:15,079 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:49] [executor-thread-338] was existing? true
2024-03-22 20:26:15,079 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:89] [executor-thread-338] JtaTransactionWrapper  commit
2024-03-22 20:26:15,079 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:152] [executor-thread-338] JtaTransactionWrapper end
2024-03-22 20:26:15,079 DEBUG [org.keycloak.transaction.JtaTransactionWrapper:155] [executor-thread-338] JtaTransactionWrapper resuming suspended
2024-03-22 20:26:15,079 TRACE [org.keycloak.events:130] [executor-thread-338] type="USER_INFO_REQUEST_ERROR", realmId="<realm_name>", clientId="<client_id>", userId="null", ipAddress="10.1.92.50", error="invalid_token", auth_method="validate_access_token", requestUri="https://<keycloakdomain>/auth/realms/<realm_name>/protocol/openid-connect/userinfo", cookies=[]
2024-03-22 20:26:15,079 DEBUG [WebApplicationException:328] [executor-thread-338] Restarting handler chain for exception exception: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
        at jdk.internal.reflect.GeneratedConstructorAccessor118.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.keycloak.utils.OAuth2Error.build(OAuth2Error.java:144)
        at org.keycloak.utils.OAuth2Error.invalidToken(OAuth2Error.java:155)
        at org.keycloak.services.util.UserSessionUtil.checkTokenIssuedAt(UserSessionUtil.java:102)
        at org.keycloak.services.util.UserSessionUtil.findValidSession(UserSessionUtil.java:45)
        at org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.issueUserInfo(UserInfoEndpoint.java:226)
        at org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.issueUserInfoGet(UserInfoEndpoint.java:126)
        at org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint$quarkusrestinvoker$issueUserInfoGet_a1820fb001f701bf80f4a3047e1da7b1fcae7669.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to Reproduce?

Login and call userinfo endpoint on a two node keycloak cluster

### Anything else?

Belive me, I'm not happy not to see how to force this error.
If you need some more debug data, give me a hint.

**Comment by mposolda** [comment]
Not sure what is going on here, but the error is caused by the fact that issued-at claim on the acccess token (claim `iat`) has earlier time than userSession startup time.

Can you doublecheck if both your cluster nodes have time in sync?

**Comment by psytester** [comment]
@mposolda your hint was awesome for the root cause 👍
but also embarrassing for me not to have checked this simple part first 😒 

Issue is solved, chronyd service was not running.
```
# chronyc tracking
506 Cannot talk to daemon
```

```
# timedatectl
.......
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
```

Node 1 and 2 have a time drift of **10 seconds** 😱
Chrony is running again, after reboot both nodes are in time synch and problem is solved

Node 1 is getting event type="LOGIN"
Node 2 is getting event type="CODE_TO_TOKEN"
Node 1 is getting event type="USER_INFO_REQUEST"

**Comment by Hasnainzahi** [comment]
getting this error when i run my juint test jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
 at de.volkswohlbund.ciam.geraetemanager.authenticator.webview.DeviceIdManagerResourceProvider.checkAuthBearer([DeviceIdManagerResourceProvider.java:111](command:_java.test.openStackTrace?%5B%22%5Ctat%20de.volkswohlbund.ciam.geraetemanager.authenticator.webview.DeviceIdManagerResourceProvider.checkAuthBearer(DeviceIdManagerResourceProvider.java%3A111)%22%2C%22ciam%22%5D))
 at de.volkswohlbund.ciam.geraetemanager.authenticator.webview.DeviceIdManagerResourceProviderTest.setup([DeviceIdManagerResourceProviderTest.java:83](command:_java.test.openStackTrace?%5B%22%5Ctat%20de.volkswohlbund.ciam.geraetemanager.authenticator.webview.DeviceIdManagerResourceProviderTest.setup(DeviceIdManagerResourceProviderTest.java%3A83)%22%2C%22ciam%22%5D))
 at java.base/java.util.ArrayList.forEach([ArrayList.java:1511](command:_java.test.openStackTrace?%5B%22%5Ctat%20java.base%2Fjava.util.ArrayList.forEach(ArrayList.java%3A1511)%22%2C%22ciam%22%5D))
 at java.base/java.util.ArrayList.forEach([ArrayList.java:1511](command:_java.test.openStackTrace?%5B%22%5Ctat%20java.base%2Fjava.util.ArrayList.forEach(ArrayList.java%3A1511)%22%2C%22ciam%22%5D))
