### ISSUE TITLE
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.keycloak.representations.idm.UserRepresentation`: Simple User Update via REST API

### ISSUE THREAD

**Issue by sdibi24** [keycloak/keycloak#28252]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

We are using our self created Client to Create / Read / Update / Disable Users via the REST-API.

In version 23.0.7 it is was working like a charm. In version 24.0.1 and 24.0.2 it is not working anymore and throws the following errors.

The Problem affects user Management Actions in which the __Attributes__ are used.

**The Example Request**

PUT {{baseUrl}}/admin/realms/{{realm}}/users/{{userId}}
```json
{
  "enabled":false,
  "attributes":
    {"disableReason":["test"]
  }
}
```
Throws an error 

```json
{
  "field": "email",
  "errorMessage": "error-user-attribute-required",
  "params": [
    "email"
  ]
}
```

__Logs and Exception Message__
```
2024-03-28 09:08:26 2024-03-28 08:08:26,755 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-12) new JtaTransactionWrapper
2024-03-28 09:08:26 2024-03-28 08:08:26,755 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-12) was existing? false
2024-03-28 09:08:26 2024-03-28 08:08:26,757 DEBUG [org.keycloak.services.resources.admin.AdminRoot] (executor-thread-12) authenticated admin access for: service-account-admin-cli
2024-03-28 09:08:26 2024-03-28 08:08:26,757 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-12) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
2024-03-28 09:08:26 2024-03-28 08:08:26,757 DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-12) Hibernate RegisteredSynchronization successfully registered with JTA platform
2024-03-28 09:08:26 2024-03-28 08:08:26,759 DEBUG [org.hibernate.orm.sql.exec] (executor-thread-12) Skipping reading Query result cache data: cache-enabled = false, cache-mode = NORMAL
2024-03-28 09:08:26 2024-03-28 08:08:26,760 DEBUG [org.hibernate.orm.results] (executor-thread-12) Initializer list:
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).attributes -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).attributes)@859809920 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.attributes))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).federatedIdentities -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).federatedIdentities)@1574435504 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.federatedIdentities))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).credentials -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).credentials)@1368229076 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.credentials))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u) -> EntityResultInitializer(org.keycloak.models.jpa.entities.UserEntity(u))@159068473 (SingleTableEntityPersister(org.keycloak.models.jpa.entities.UserEntity))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).requiredActions -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).requiredActions)@1204740926 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.requiredActions))
2024-03-28 09:08:26 
2024-03-28 09:08:26 2024-03-28 08:08:26,760 DEBUG [org.hibernate.SQL] (executor-thread-12) select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from public.USER_ENTITY ue1_0 where ue1_0.USERNAME=? and ue1_0.REALM_ID=?
2024-03-28 09:08:26 2024-03-28 08:08:26,760 FINE  [org.postgresql.jdbc.PgConnection] (executor-thread-12)   setAutoCommit = false
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading.entity] (executor-thread-12) (EntityResultInitializer) Hydrated EntityKey (org.keycloak.models.jpa.entities.UserEntity(u)): 7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).attributes#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).credentials#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).federatedIdentities#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).requiredActions#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading.entity] (executor-thread-12) (EntityResultInitializer) Created new entity instance [org.keycloak.models.jpa.entities.UserEntity(u)#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac] : 2021510561
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [1] - [1710932182788]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [2] - [someemail@arad.de]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [3] - [someemail@arad.de]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [4] - [true]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [5] - [false]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [6] - [null]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [7] - [null]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [8] - [null]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [9] - [0]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [10] - [development]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [11] - [null]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [12] - [someemail@arad.de]
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading.entity] (executor-thread-12) (EntityResultInitializer) Done materializing entityInstance : org.keycloak.models.jpa.entities.UserEntity(u)#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.orm.results.loading] (executor-thread-12) Calling top-level assembler (0 / 1) : org.hibernate.sql.results.graph.entity.internal.EntityAssembler@39c02f81
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (executor-thread-12) Processing flush-time cascades
2024-03-28 09:08:26 2024-03-28 08:08:26,761 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (executor-thread-12) Dirty checking collections
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-12) Skipping uninitialized bytecode-lazy collection: [org.keycloak.models.jpa.entities.UserEntity.attributes#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-12) Skipping uninitialized bytecode-lazy collection: [org.keycloak.models.jpa.entities.UserEntity.credentials#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-12) Skipping uninitialized bytecode-lazy collection: [org.keycloak.models.jpa.entities.UserEntity.federatedIdentities#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-12) Skipping uninitialized bytecode-lazy collection: [org.keycloak.models.jpa.entities.UserEntity.requiredActions#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (executor-thread-12) Flushed: 0 insertions, 0 updates, 0 deletions to 1 objects
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.event.internal.AbstractFlushingEventListener] (executor-thread-12) Flushed: 0 (re)creations, 0 updates, 0 removals to 4 collections
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-12) Listing entities:
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-12) org.keycloak.models.jpa.entities.UserEntity{lastName=null, federatedIdentities=<uninitialized>, realmId=development, credentials=<uninitialized>, createdTimestamp=1710932182788, serviceAccountClientLink=null, enabled=false, notBefore=0, emailConstraint=someemail@arad.de, emailVerified=true, firstName=null, requiredActions=<uninitialized>, federationLink=null, attributes=<uninitialized>, id=7bbc90e9-d211-40dc-8bb8-e0eea267f2ac, email=someemail@arad.de, username=someemail@arad.de}
2024-03-28 09:08:26 2024-03-28 08:08:26,762 DEBUG [org.hibernate.orm.sql.exec] (executor-thread-12) Skipping reading Query result cache data: cache-enabled = false, cache-mode = NORMAL
2024-03-28 09:08:26 2024-03-28 08:08:26,763 DEBUG [org.hibernate.orm.results] (executor-thread-12) Initializer list:
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).attributes -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).attributes)@2054637557 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.attributes))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).federatedIdentities -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).federatedIdentities)@659945932 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.federatedIdentities))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).credentials -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).credentials)@1614636722 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.credentials))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u) -> EntityResultInitializer(org.keycloak.models.jpa.entities.UserEntity(u))@1480192275 (SingleTableEntityPersister(org.keycloak.models.jpa.entities.UserEntity))
2024-03-28 09:08:26       org.keycloak.models.jpa.entities.UserEntity(u).requiredActions -> DelayedCollectionInitializer(org.keycloak.models.jpa.entities.UserEntity(u).requiredActions)@414272782 (PluralAttribute(org.keycloak.models.jpa.entities.UserEntity.requiredActions))
2024-03-28 09:08:26 
2024-03-28 09:08:26 2024-03-28 08:08:26,763 DEBUG [org.hibernate.SQL] (executor-thread-12) select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from public.USER_ENTITY ue1_0 where ue1_0.EMAIL=? and ue1_0.REALM_ID=?
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results.loading.entity] (executor-thread-12) (EntityResultInitializer) Hydrated EntityKey (org.keycloak.models.jpa.entities.UserEntity(u)): 7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).attributes#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).credentials#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).federatedIdentities#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results] (executor-thread-12) Extracted JDBC value [0] - [7bbc90e9-d211-40dc-8bb8-e0eea267f2ac]
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results.loading.org.hibernate.orm.results.loading.collection] (executor-thread-12) (DelayedCollectionInitializer) Current row collection key : org.keycloak.models.jpa.entities.UserEntity(u).requiredActions#7bbc90e9-d211-40dc-8bb8-e0eea267f2ac
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [org.hibernate.orm.results.loading] (executor-thread-12) Calling top-level assembler (0 / 1) : org.hibernate.sql.results.graph.entity.internal.EntityAssembler@c077b03
2024-03-28 09:08:26 2024-03-28 08:08:26,765 DEBUG [WebApplicationException] (executor-thread-12) Restarting handler chain for exception exception: org.keycloak.services.ErrorResponseException: HTTP 500 Internal Server Error
2024-03-28 09:08:26     at org.keycloak.services.ErrorResponse.errors(ErrorResponse.java:52)
2024-03-28 09:08:26     at org.keycloak.services.ErrorResponse.errors(ErrorResponse.java:47)
2024-03-28 09:08:26     at org.keycloak.services.resources.admin.UserResource.validateUserProfile(UserResource.java:254)
2024-03-28 09:08:26     at org.keycloak.services.resources.admin.UserResource.updateUser(UserResource.java:200)
2024-03-28 09:08:26     at org.keycloak.services.resources.admin.UserResource$quarkusrestinvoker$updateUser_06a139c72250da7941838b1def60a9f82f9ef70d.invoke(Unknown Source)
2024-03-28 09:08:26     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-03-28 09:08:26     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-03-28 09:08:26     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-03-28 09:08:26     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
2024-03-28 09:08:26     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-03-28 09:08:26     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-03-28 09:08:26     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-03-28 09:08:26     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-03-28 09:08:26     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-03-28 09:08:26     at java.base/java.lang.Thread.run(Thread.java:840)
```

__If i Supply a valid Email-Address it is working__

PUT {{baseUrl}}/admin/realms/{{realm}}/users/{{userId}}
```json
{
  "email": "someEmail@arad.de",
  "enabled":false,
  "attributes":
    {"disableReason":["blub"]
  }
}
```

__If i don't use the Attributes it is also working__

PUT {{baseUrl}}/admin/realms/{{realm}}/users/{{userId}}
```json
{
  "enabled":false
}
```

As stated in the docs 

### Version

24.0.x

### Regression

- [X] The issue is a regression

### Expected behavior

After the PUT Request Example the user should be disabled.

### Actual behavior

The Api Raises an Error 400 (Bad Request)

```
{
  "field": "email",
  "errorMessage": "error-user-attribute-required",
  "params": [
    "email"
  ]
}
```

### How to Reproduce?

Create a User and try to disable it via Admin Api:

{{baseUrl}}/admin/realms/{{realm}}/users/bbcd56b4-f071-4222-9615-787df5df92a5

__does not Work__
```Javascript
{
  "enabled":false,
  "attributes":
    {"disableReason":["test"]
  }
}
```

**Comment by shawkins** [comment]
The trailing comma is not valid json, instead use:

```
{
   "enabled": false
}
```

**Comment by sdibi24** [comment]
Thanks Shawkins, i made a mistake while documenting the issue. I Updated the Issue Details and Headline

**Comment by shawkins** [comment]
@sdibi24 I believe this is the same issue as #28220 - it appears in prior releases that PUT behaved more like a JSON merge patch. I don't know what the original rationale was, but I'd expect that to require the PATCH verb, not PUT. Closing this issue. Please chime in on #28220 - it needs higher priority.
