### ISSUE TITLE
Creating a new realm fails on fresh instance

### ISSUE THREAD

**Issue by keeganwhite** [keycloak/keycloak#28299]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

## UI ERROR SHOWN
![Screenshot from 2024-03-29 16-22-13](https://github.com/keycloak/keycloak/assets/34510640/f70e49d1-056c-4738-bc8b-531c99b773bc)

## Console Error 
![image](https://github.com/keycloak/keycloak/assets/34510640/79921453-e592-44f0-b899-d73e8a29246f)

## Explanation
On a fresh keycloak instance, I try and create a new realm which indicates it is successful. However, when selecting it from the menu I see the error shown above and my keycloak logs show this:

```
docker logs inethi-keycloak
Updating the configuration and installing your custom providers, if any. Please wait.
2024-03-27 11:44:33,490 WARN  [org.key.qua.run.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
2024-03-27 11:44:41,068 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 6862ms
2024-03-27 11:44:41,769 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
2024-03-27 11:44:42,333 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: keycloak.inethilocal.net, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2024-03-27 11:44:42,498 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-03-27 11:44:42,553 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-03-27 11:44:44,246 WARN  [io.quarkus.agroal.runtime.DataSources] (JPA Startup Thread) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2024-03-27 11:44:44,992 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2024-03-27 11:44:46,143 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml

UPDATE SUMMARY
Run:                        121
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:          121

2024-03-27 11:44:48,865 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_652550, Site name: null
2024-03-27 11:44:48,992 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-03-27 11:44:49,006 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2024-03-27 11:44:50,922 INFO  [io.quarkus] (main) Keycloak 24.0.1 on JVM (powered by Quarkus 3.8.1) started in 9.705s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8443
2024-03-27 11:44:50,922 INFO  [io.quarkus] (main) Profile dev activated. 
2024-03-27 11:44:50,922 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2024-03-27 11:44:51,588 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
2024-03-27 11:44:51,592 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
2024-03-29 14:16:44,989 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-27) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getMasterAdminClient()" because "realm" is null
	at org.keycloak.services.resources.admin.AdminConsole.addMasterRealmAccess(AdminConsole.java:256)
	at org.keycloak.services.resources.admin.AdminConsole.whoAmI(AdminConsole.java:234)
	at org.keycloak.services.resources.admin.AdminConsole$quarkusrestinvoker$whoAmI_eaeea38b34c9e4843e24a94ba86a1ba4c8cf0402.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
here are my build scripts. This is an opensource project I maintain so there is no sensitive data here just the defaul settings for our users:
```
- name: Deploy Keycloak Stack
  hosts: localserver
  become: true
  gather_facts: no

  vars:
    KEYCLOAK_ADMIN_USER: "admin"
    KEYCLOAK_TRAEFIK_API_RULE: "keycloak"
    POSTGRES_KEYCLOAK_TRAEFIK_API_RULE: "postgres-keycloak"
    KEYCLOAK_USER: "inethi"
    POSTGRES_VOLUME: "/mnt/data/keycloak-postgres"
    TRAEFIK_ENTRYPOINT: "websecure"
    inethiDN: "inethicloud.net"
    INETHI_NETWORK: "inethi-bridge-traefik"
    CONF_MASTER_PASSWORD: "iNethi2023#"
    keycloak_volume: "/mnt/data/keycloak"
    ACME_JSON: "/mnt/data/traefikssl/letsencrypt/acme.json"
    DOMAIN: "inethicloud.net"
    CERT_PATH: "/mnt/data/keycloak/certs/tls.crt"
    KEY_PATH: "/mnt/data/keycloak/certs/tls.key"
    KEYSTORE_PATH: "/mnt/data/keycloak/certs/"
    TRUSTSTORE_PATH: "/mnt/data/keycloak/certs/"
    KEYSTORE_PASSWORD: "iNethi2023#"


  tasks:
    - name: Install necessary packages
      apt:
        name:
          - jq
          - openssl
          - openjdk-11-jre-headless
        state: present

    - name: Create directory for keycloak volume
      file:
        path: "{{ keycloak_volume }}/"
        state: directory
        mode: '0755'
    - name: Create directory for postgress volume
      file:
        path: "{{ POSTGRES_VOLUME }}/"
        state: directory
        mode: '0777'
    - name: Create directory for certificates
      file:
        path: "{{ keycloak_volume }}/certs"
        state: directory
        mode: '0755'

    - name: Extract certificate and key from acme.json
      shell: |
        ACME_JSON="/mnt/data/traefikssl/letsencrypt/acme.json"
        CERT_DIR="/mnt/data/keycloak/certs"
        DOMAIN="inethicloud.net"
        
        jq -r '.letsencrypt.Certificates[] | select(.domain.main == "inethicloud.net") | .certificate' $ACME_JSON | base64 -d > $CERT_DIR/cert.pem
        jq -r '.letsencrypt.Certificates[] | select(.domain.main == "inethicloud.net") | .key' $ACME_JSON | base64 -d > $CERT_DIR/privkey.pem

      args:
        executable: /bin/bash
    - name: Generate keystore from certificate and key
      shell: |
        CERT_DIR="/mnt/data/keycloak/certs"
        KEYSTORE_PASSWORD="iNethi2023#"
        openssl pkcs12 -export -in $CERT_DIR/cert.pem -inkey $CERT_DIR/privkey.pem -out $CERT_DIR/keystore.p12 -name keycloak -password pass:$KEYSTORE_PASSWORD
        keytool -importkeystore -deststorepass $KEYSTORE_PASSWORD -destkeypass $KEYSTORE_PASSWORD -destkeystore $CERT_DIR/keystore.jks -srckeystore $CERT_DIR/keystore.p12 -srcstoretype PKCS12 -alias keycloak -srcstorepass $KEYSTORE_PASSWORD -noprompt
      args:
        executable: /bin/bash

    - name: Create Postgres container for Keycloak
      docker_container:
        name: inethi-keycloak-postgres
        image: docker.io/bitnami/postgresql
        restart_policy: unless-stopped
        env:
          POSTGRESQL_DATABASE: "keycloak"
          POSTGRESQL_USERNAME: "{{ KEYCLOAK_ADMIN_USER }}"
          POSTGRESQL_PASSWORD: "{{ CONF_MASTER_PASSWORD }}"
        volumes:
          - "{{ POSTGRES_VOLUME }}:/bitnami/postgresql"
        labels:
          traefik.enable: "true"
          traefik.http.routers.postgres-keycloak.rule: "Host(`{{ POSTGRES_KEYCLOAK_TRAEFIK_API_RULE }}.{{ inethiDN }}`)"
          traefik.http.routers.postgres-keycloak.entrypoints: "{{ TRAEFIK_ENTRYPOINT }}"
        networks:
          - name: "{{ INETHI_NETWORK }}"
    - name: Wait (3 min) for Keycloak Database
      pause:
        seconds: 180

    - name: Create Keycloak container
      docker_container:
        image: quay.io/keycloak/keycloak:24.0.1
        name: inethi-keycloak
        restart_policy: unless-stopped
        state: started
        command:
          - start-dev
          - --verbose
        env:
          KEYCLOAK_ADMIN: "{{ KEYCLOAK_ADMIN_USER }}"
          KEYCLOAK_ADMIN_PASSWORD: "{{ CONF_MASTER_PASSWORD }}"
          KEYCLOAK_USER: "{{ KEYCLOAK_USER }}"

          KEYCLOAK_PASSWORD: "{{ CONF_MASTER_PASSWORD }}"
          KEYCLOAK_DATABASE_VENDOR: "postgresql"
          KC_DB_URL: " jdbc:postgresql://inethi-keycloak-postgres/keycloak"
          KEYCLOAK_DATABASE_NAME: "keycloak"
          KC_DB_USERNAME: "{{ KEYCLOAK_ADMIN_USER }}"
          KC_DB: 'postgres'
          KC_DB_PASSWORD: "{{ CONF_MASTER_PASSWORD }}"

          KC_HOSTNAME: "{{ KEYCLOAK_TRAEFIK_API_RULE }}.{{ inethiDN }}"
          KC_HOSTNAME_STRICT: "true"
          KC_HOSTNAME_STRICT_HTTPS: "true"
          KC_PROXY: "edge"

          KC_HTTPS_KEY_STORE_FILE: "/opt/keycloak/certs/keystore.jks"
          KC_HTTPS_KEY_STORE_PASSWORD: "iNethi2023#"


        volumes:
          - "{{ KEYSTORE_PATH }}:/opt/keycloak/certs/"

        labels:
          traefik.enable: "true"
          traefik.http.routers.keycloak.rule: "Host(`{{ KEYCLOAK_TRAEFIK_API_RULE }}.{{ inethiDN }}`)"
          traefik.http.routers.keycloak.entrypoints: "{{ TRAEFIK_ENTRYPOINT }}"
          traefik.http.services.keycloak.loadbalancer.server.port: "8080"
        networks:
          - name: "{{ INETHI_NETWORK }}"
    - name: Wait (1 min) for Keycloak to be up and initialised
      pause:
        seconds: 60
```

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

I want to create a realm and be able to select it.

### Actual behavior

There is an error displayed on the UI described above.

### How to Reproduce?

It is a fresh install with my build script provided above.

**Comment by keeganwhite** [comment]
the errors were the spaces between the words. Error messages should indicate this not say it was created successfully in the top right.
![image](https://github.com/keycloak/keycloak/assets/34510640/6c2555f1-9ed0-4511-9eea-84f7ce36c358)
