### ISSUE TITLE
WARN - Event object wasn't available in remote cache after event was received

### ISSUE THREAD

**Issue by nekobrain** [keycloak/keycloak#28303]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

We ran into an issue while configuring a Keycloak cluster that uses a remote Infinispan cluster (we are using Infinispan version 14.0.21.Final); we are using Terraform to do so, using [this provider](https://github.com/mrparkers/terraform-provider-keycloak). 
Please find the relevant configurations below.
Terraform:
```
terraform {
  required_version = ">= 0.14.11, < 2.0.0"
  required_providers {
    keycloak = {
      source  = "mrparkers/keycloak"
      version = "4.4.0"
    }
  }
}

provider "keycloak" {
  client_id      = "admin-cli"
  username       = "foo"
  password       = "bar"
  url            = "https://localhost:8081"
  base_path      = "/foo"
  client_timeout = 60
}

resource "keycloak_realm" "foo_realm" {
  realm                    = "foo"
  display_name             = "foo realm"
  enabled                  = true
  login_with_email_allowed = true
}

resource "keycloak_authentication_flow" "foo_browser_flow" {
  realm_id    = keycloak_realm.foo_realm.id
  alias       = "foo-browser"
  description = "Browser based authentication for clients"
  provider_id = "basic-flow"
}

resource "keycloak_authentication_execution" "foo_browser_cookie_execution" {
  realm_id          = keycloak_realm.foo_realm.id
  parent_flow_alias = keycloak_authentication_flow.foo_browser_flow.alias
  authenticator     = "auth-cookie"
  requirement       = "ALTERNATIVE"
}


resource "keycloak_authentication_subflow" "foo_browser_subflow_authentication" {
  depends_on        = [keycloak_authentication_execution.foo_browser_cookie_execution]
  realm_id          = keycloak_realm.foo_realm.id
  alias             = "foo-browser-subflow-authentication"
  description       = "foo: lorem ipsum"
  parent_flow_alias = keycloak_authentication_flow.foo_browser_flow.alias
  provider_id       = "basic-flow"
  requirement       = "ALTERNATIVE"
}
```

Our setup is the following:
- 3-node Keycloak cluster
- 3-node Infinispan cluster
- Postgres as a backend for Keycloak
- Infinispan is configured with a persisting store (Postgres)

Please find the configs for Keycloak and Infinispan below. 

Keycloak:

```<?xml version="1.0" encoding="UTF-8"?>
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>

        <local-cache-configuration name="local-cache-cfg">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
        </local-cache-configuration>

        <local-cache name="realms" configuration="local-cache-cfg">
            <memory max-count="10000"/>
        </local-cache>

        <local-cache name="users" configuration="local-cache-cfg">
            <memory max-count="10000"/>
        </local-cache>


        <local-cache name="keys" configuration="local-cache-cfg">
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>

        <local-cache name="authorization" configuration="local-cache-cfg">
            <memory max-count="10000"/>
        </local-cache>

        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>

        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="sessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>

                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="clientSessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="offlineSessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="offlineClientSessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="loginFailures"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="actionTokens" owners="2">
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
            <remote-store cache="actionTokens" xmlns="urn:infinispan:config:store:remote:14.0"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <replicated-cache name="work">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="work"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </replicated-cache>
    </cache-container>
</infinispan>
```
Infinispan:

```<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:infinispan:config:14.0"
        xsi:schemaLocation="urn:infinispan:config:14.0 https://infinispan.org/schemas/infinispan-config-14.0.xsd urn:infinispan:server:14.0 https://infinispan.org/schemas/infinispan-server-14.0.xsd">
    <!-- see https://docs.jboss.org/infinispan/14.0/configdocs/infinispan-config-14.0.html -->

    <jgroups>
        <!-- TCP local cluster with JDBCPING discovery -->
        <stack name="dns-ping">
            <dns.DNS_PING dns_query="${jgroups.dns.query}" />
            <FD_SOCK stack.combine="REMOVE"/>
            <pbcast.GMS join_timeout="30000" />
            <RSVP timeout="60000" resend_interval="500" ack_on_delivery="true" />
        </stack>
    </jgroups>

    <cache-container name="default" statistics="true">
        <metrics gauges="true" histograms="false" />
        <!-- TODO configure custom jgroups stack: +auth +encryption -->
        <serialization marshaller="org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller">
            <allow-list>
                <class>org.keycloak.cluster.infinispan.WrapperClusterEvent</class>
                <regex>.*</regex>
            </allow-list>
        </serialization>
        <transport
                cluster="${infinispan.cluster.name:kcispn}"
                stack="${infinispan.cluster.stack:kubernetes}"
                node-name="${env.POD_NAME}"/>

        <replicated-cache-configuration name="replicated-cache-cfg"
                                        xmlns:jdbc="urn:infinispan:config:store:jdbc:14.0"
                                        mode="SYNC"
                                        statistics="true"
                                        segments="256"
                                        unreliable-return-values="false">
            <encoding media-type="application/x-jboss-marshalling"/>
            <transaction mode="NON_XA"
                            locking="OPTIMISTIC"/>
        <persistence passivation="false">
            <jdbc:string-keyed-jdbc-store shared="true" preload="false">
                <jdbc:data-source jndi-url="jdbc/datasource"/>
                <jdbc:string-keyed-table drop-on-exit="false" create-on-start="true" prefix="ispn">
                    <jdbc:id-column name="id" type="VARCHAR(255)"/>
                    <jdbc:data-column name="data" type="bytea"/>
                    <jdbc:timestamp-column name="ts" type="BIGINT"/>
                    <jdbc:segment-column name="seg" type="INT"/>
                </jdbc:string-keyed-table>
            </jdbc:string-keyed-jdbc-store>
        </persistence>
        </replicated-cache-configuration>

        <distributed-cache-configuration name="distributed-cache-cfg"
                                            xmlns:jdbc="urn:infinispan:config:store:jdbc:14.0"
                                            mode="SYNC"
                                            owners="2"
                                            remote-timeout="60000"
                                            statistics="true"
                                            segments="256"
                                            unreliable-return-values="false">
            <encoding media-type="application/x-jboss-marshalling"/>
            <locking isolation="REPEATABLE_READ"
                        striping="false"
                        acquire-timeout="10000"
                        concurrency-level="32"/>

            <transaction mode="NON_XA"
                            locking="OPTIMISTIC"/>

            <expiration lifespan="-1"
                        max-idle="-1"
                        interval="60000" />

            <memory max-count="-1" when-full="NONE" storage="HEAP"/>

            <partition-handling when-split="ALLOW_READ_WRITES" />

            <persistence passivation="false">
                <jdbc:string-keyed-jdbc-store shared="true" preload="false">
                    <jdbc:data-source jndi-url="jdbc/datasource"/>
                    <jdbc:string-keyed-table drop-on-exit="false" create-on-start="true" prefix="ispn">
                        <jdbc:id-column name="id" type="VARCHAR(255)"/>
                        <jdbc:data-column name="data" type="bytea"/>
                        <jdbc:timestamp-column name="ts" type="BIGINT"/>
                        <jdbc:segment-column name="seg" type="INT"/>
                    </jdbc:string-keyed-table>
                </jdbc:string-keyed-jdbc-store>
            </persistence>

            <state-transfer enabled="true"
                            timeout="240000"
                            chunk-size="240000"
                            await-initial-transfer="true"/>
        </distributed-cache-configuration>

        <replicated-cache name="work" configuration="replicated-cache-cfg">
        </replicated-cache>

        <distributed-cache name="sessions" configuration="distributed-cache-cfg">
        </distributed-cache>

        <distributed-cache name="authenticationSessions" configuration="distributed-cache-cfg">
        </distributed-cache>

        <distributed-cache name="offlineSessions" configuration="distributed-cache-cfg">
        </distributed-cache>

        <distributed-cache name="clientSessions" configuration="distributed-cache-cfg">
        </distributed-cache>

        <distributed-cache name="offlineClientSessions" configuration="distributed-cache-cfg">
        </distributed-cache>

        <distributed-cache name="loginFailures" configuration="distributed-cache-cfg">
        </distributed-cache>

        <distributed-cache name="actionTokens" configuration="distributed-cache-cfg">
            <memory max-count="-1">
            </memory>
            <expiration interval="300000" max-idle="-1"/>
        </distributed-cache>

    </cache-container>

    <server xmlns="urn:infinispan:server:14.0">

        <interfaces>
            <interface name="public">
                <any-address/>
            </interface>
        </interfaces>

        <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
            <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
        </socket-bindings>

        <security>
            <security-realms>
                <security-realm name="default">
                    <!--  Uncomment to enable TLS on the realm  -->
                    <properties-realm groups-attribute="Roles">
                        <user-properties path="users.properties" relative-to="infinispan.server.config.path"
                                            plain-text="true"/>
                        <group-properties path="groups.properties" relative-to="infinispan.server.config.path"/>
                    </properties-realm>
                </security-realm>
            </security-realms>
        </security>

    <data-sources>
        <data-source name="KeycloakDS" jndi-name="jdbc/datasource" statistics="true">
            <connection-factory driver="org.postgresql.Driver"
                                username="${env.DB_USERNAME}"
                                password="${env.DB_PASSWORD}"
                                url="jdbc:postgresql://${env.DB_HOSTNAME}/${env.DB_DATABASE}?ApplicationName=${env.DB_APP_NAME}"
                                new-connection-sql="SELECT 1" transaction-isolation="READ_COMMITTED">
            </connection-factory>
            <connection-pool initial-size="${env.CONN_POOL_INITIAL_SIZE}" max-size="${env.CONN_POOL_MAX_SIZE}"  min-size="${env.CONN_POOL_MIN_SIZE}" background-validation="1000" idle-removal="1" blocking-timeout="1000" leak-detection="10000"/>
        </data-source>
    </data-sources>

        <!-- see https://docs.jboss.org/infinispan/14.0/configdocs/infinispan-server-14.0.html#endpoints -->
        <endpoints>
            <endpoint socket-binding="default" security-realm="default">
                <hotrod-connector name="hotrod" security-realm="default"/>
                <rest-connector>
                    <authentication mechanisms="BASIC"/>
                </rest-connector>
            </endpoint>
        </endpoints>
    </server>
</infinispan>
```

All referenced environment variables are correctly evaluated at run time.

This is the chain of events that we get:

```
POST /admin/realms/foo-realm/authentication/flows/foo-browser-with-product-events-cookie/executions/execution -> 201 created
```

```
PUT /admin/realms/foo-realm/authentication/flows/foo-browser-with-product-events-cookie/executions -> 404 not found
```

This is the stack trace corresponding to the 404:

```
jakarta.ws.rs.NotFoundException: Illegal execution
	at org.keycloak.services.resources.admin.AuthenticationManagementResource.updateExecutions(AuthenticationManagementResource.java:721)
	at org.keycloak.services.resources.admin.AuthenticationManagementResource$quarkusrestinvoker$updateExecutions_1fb26a2fba65839d9e0fe9f9233d954e611af6dd.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

When this happens, we can see a sudden increase in warning messages from Keycloak, as it is visible from the following logs:

![image](https://github.com/keycloak/keycloak/assets/17787120/0dc4f0c4-67f3-431c-84c4-2b5d28fd06c5)

```
Event object wasn't available in remote cache after event was received. Event key: 4af1c45f-a0ac-4fee-be2e-f8467e73af92
```

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

The flows and subflows are created according to what is specified in the Terraform file.

### Actual behavior

On subsequent PUT calls, Keycloak returns a 404 error even though the resource was successfully created as the logs provided in the bug description show.

### How to Reproduce?

Apply the provided Terraform file on a Keycloak clustered deployment with an external Infinispan (see provided config files to configure Infinispan and Keycloak).

### Anything else?

If the `work` cache is hosted in the embedded cache or we have a single Keycloak node, the Terraform apply runs without any error. See the following config file as a reference for this case:
```
<?xml version="1.0" encoding="UTF-8"?>
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>

        <local-cache-configuration name="local-cache-cfg">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
        </local-cache-configuration>

        <local-cache name="realms" configuration="local-cache-cfg">
            <memory max-count="10000"/>
        </local-cache>

        <local-cache name="users" configuration="local-cache-cfg">
            <memory max-count="10000"/>
        </local-cache>


        <local-cache name="keys" configuration="local-cache-cfg">
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>

        <local-cache name="authorization" configuration="local-cache-cfg">
            <memory max-count="10000"/>
        </local-cache>

        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>

        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="sessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>

                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="clientSessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="offlineSessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="offlineClientSessions"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                            cache="loginFailures"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <distributed-cache name="actionTokens" owners="2">
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
            <remote-store cache="actionTokens" xmlns="urn:infinispan:config:store:remote:14.0"
                            purge="false"
                            preload="false"
                            shared="true"
                            segmented="false"
                            connect-timeout="${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT:2000}"
                            raw-values="true"
                            marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}" port="${infinispan.bind.port:11222}"/>
                <security>
                    <authentication>
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                                password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                                realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <!-- !!! PLEASE NOTE !!! -->
        <!-- WORK CACHE IS NOT REMOTE ANYMORE -->
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
    </cache-container>
</infinispan>
```

**Comment by nekobrain** [comment]
We tested with Keycloak v 24.0.3 and the issue is still present.

**Comment by ahus1** [comment]
@pruivo - could you please help me to understand what is happening here? This is what I assume to happen: 

* Keycloak puts an event in the work remote work cache only
  https://github.com/keycloak/keycloak/blob/9e4fc3f49151cd32bb84dbe8e5bd57a1050d6a69/model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java#L164 
* Infinispan notifies Keycloak about a change and Keycloak fetches the entry from the remote Infinispan asynchronosly, but apparently `null` is returned. 
   https://github.com/keycloak/keycloak/blob/9e4fc3f49151cd32bb84dbe8e5bd57a1050d6a69/model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanNotificationsManager.java#L238-L242

I know that in other places we sometimes retry until we get the right event version - still, we don't retry if there is no entry at all in those other places. Not sure if it applies here, and if we should retry for a moment even if there is no entry.

https://github.com/keycloak/keycloak/blob/de04684dd026999295350d720b8285450e8a24e0/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionListener.java#L177-L188

Thanks!

**Comment by pruivo** [comment]
@ahus1 What's happening is that the KC node is listening to changes from an ISPN node (backup owner) which applied the update faster than the primary owner of the key. Keycloak should invest in some server-side code to send the value in the event... 

A more interesting question for @nekobrain is why such a complex architecture? What problem does the external Infinispan + Postgres fix that Keycloak itself can't?

**Comment by ahus1** [comment]
> Keycloak should invest in some server-side code to send the value in the event...

@pruivo - could you please prepare a PR with such code as a fix for this? I know we're heading for a simplified solution in the future, still I assume we would need a fix for KC24 in the meantime. Thanks!

**Comment by nekobrain** [comment]
First of all, thanks to anyone who is looking into this issue, your effort is much appreciated. I would just like to point out that we are not running a single-site deployment, but a multi-region one to be safe in case of disaster.

@pruivo regarding your question about the complexity of our architecture:
- We have the need to rollout Keycloak at a pretty high frequency (about once a day) and we have found that having an external Infinispan helped us mitigate the downtime (referring to Infinispan state issues while rolling out, for example) we were facing when rolling out Keycloak with an embedded Infinispan. Think of this as a "workaround". Please see these [two](https://github.com/keycloak/keycloak/discussions/21067#discussioncomment-6254291) [issues](https://github.com/keycloak/keycloak/issues/14455) to have a more comprehensive picture of the problems we were facing.
- Sessions are way too valuable for us for them to be stored in volatile memory, especially in case of a disaster scenario which would require us to fail over to a secondary region, hence our choice of plugging Infinispan to a Postgres database.
- We use the Infinispan database as a way to replicate our sessions since our Postgres database itself (AWS Aurora) is replicated too, so when we fail over sessions are restored from the existing data in Postgres.

If you need further details about the architecture we are running please don't hesitate to ask.

**Comment by pruivo** [comment]
I wasn't aware it was a multi-region architecture because cross-site is not enabled in Infinispan. How is that working for you, if the updates on one region are not propagated to the other?

**Comment by ahus1** [comment]
@nekobrain - something @pruivo and me discussed about your current setup: The two owner plus the primary writing to the database increases the likelihood of the message. Maybe you could reduce the chances of the message if you change the number of owners to 1 for the work cache as the data is stored in the database. Given the nature of the data stored in the work cache as it is only about cluster wide locks and invalidating Keycloak's embedded caches, you might even choose to not have it as a remote cache at all like you have it set up in your second example.

**Comment by nekobrain** [comment]
@pruivo as stated in my previous comment, Infinispan is backed by a Postgres database which is in turn replicated across regions (all of this is happening thanks to AWS Aurora).
@ahus1 thank you for your insights and suggestions, we are going to try and remove the Postgres backing for the work cache.
I am not sure what do you exactly mean when suggesting to only have 1 owner for the work cache, since wouldn't this make the whole point of having it replicated moot?
In the meantime, thanks again for taking the time to look into this, we are going to try all that has come up in your latest comments.

**Comment by pruivo** [comment]
@nekobrain I'm surprised that it works at all. 
Infinispan does not contact the DB if it has the data in memory and when you write to the DB directly, it won't invalidate the Infinispan caches. You'll end up reading stale data from Infinispan. Even the events Keycloak writes into the `work` cache won't reach the other region. 
Are you sure everything works as expected?

**Comment by ahus1** [comment]
> I am not sure what do you exactly mean when suggesting to only have 1 owner for the work cache, since wouldn't this make the whole point of having it replicated moot?

Sorry, I forgot the work cache is the only replicated cache. Please then disregard the first part of my comment. 

Maybe you could describe more about your disaster recovery setup: In the [Keycloak HA guide](https://www.keycloak.org/high-availability/introduction), we describe a setup where the second site is running Keycloak and Infinispan instances, and uses an Infinispan X-Site setup to keep everything in sync and up-to-date.   

If instead of the setup described above you only start Keycloak and Infinispan on the other site once the first site fails, then there is no need set up X-Site for Infinispan. If this is the case, the second part of my statement should still hold true: Given the nature of the data stored in the work cache as it is only about cluster wide locks and invalidating Keycloak's embedded caches, you might even choose to not have it as a remote cache at all like you have it set up in your second example.

**Comment by ahus1** [comment]
@pruivo - please create a backport for KC24. Thanks!

**Comment by pruivo** [comment]
backport: https://github.com/keycloak/keycloak/pull/29323

**Comment by ahus1** [comment]
@nekobrain - a change is now available in Keycloak's nightly release and it will also be part of the next patch release 24.0.4 once it is released.

If you have the time and the environment, please give the nightly release a try to see if this resolves your problem, your feedback would help us a lot.

Please note that once you install a nightly Keycloak release in an environment, you won't be able to upgrade to a later version of Keycloak (either a released version or a newer nightly release). So you might want to take a database backup of that test environment before trying it out, or use an ephemeral environment.

**Comment by nekobrain** [comment]
Hello @ahus1 @pruivo, thank you again for taking the time to fix this, I can confirm that using version 24.0.4 along with removing the Postgres backing for the replicated cache solves the problems we were experiencing.
We tried to just remove the Postgres backing without updating to the new version, but this alone does not work.
Thanks again for your help!

**Comment by ahus1** [comment]
@nekobrain - this is great news! I'm wondering if you also tested 24.0.4 with the PostgreSQL backing?

**Comment by ahus1** [comment]
@nekobrain - thank you for clarifying. I agree with your analysis. Again, thank you for the feedback.
