### ISSUE TITLE
Js Policy is not working with 24.x.x version

### ISSUE THREAD

**Issue by mihirvadalia** [keycloak/keycloak#28337]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

Js Policy which was working in 23.x.x version of keycloak, stopps working in 24.x.x version of keycloak after updating keycloak version.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Js Policy should work.

I tried with simple plain JS Policy like below, but that is also not working. So I suspect something is wrong with Keycloak build. I might be wrong but if any one have any idea please share it.

js-policy:
`$evaluation.grant();`

### Actual behavior

**Exception:** Found interface org.objectweb.asm.FieldVisitor, but class was expected

```
2024-04-01 23:48:56 2024-04-01 18:18:56,612 ERROR [org.keycloak.authorization.admin.PolicyEvaluationService] (executor-thread-2) Error while evaluating permissions: java.lang.RuntimeException: Failed to evaluate permissions
2024-04-01 23:48:56     at org.keycloak.authorization.policy.evaluation.DecisionPermissionCollector.onError(DecisionPermissionCollector.java:182)
2024-04-01 23:48:56     at org.keycloak.authorization.permission.evaluator.UnboundedPermissionEvaluator.evaluate(UnboundedPermissionEvaluator.java:53)
2024-04-01 23:48:56     at org.keycloak.authorization.admin.PolicyEvaluationService.evaluate(PolicyEvaluationService.java:147)
2024-04-01 23:48:56     at org.keycloak.authorization.admin.PolicyEvaluationService.evaluate(PolicyEvaluationService.java:134)
2024-04-01 23:48:56     at org.keycloak.authorization.admin.PolicyEvaluationService$quarkusrestinvoker$evaluate_f45b422a732bbaae48d590c45f101b32244d4ec0.invoke(Unknown Source)
2024-04-01 23:48:56     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-04-01 23:48:56     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-04-01 23:48:56     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-04-01 23:48:56     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
2024-04-01 23:48:56     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-04-01 23:48:56     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-04-01 23:48:56     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-04-01 23:48:56     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-04-01 23:48:56     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-04-01 23:48:56     at java.base/java.lang.Thread.run(Thread.java:840)
2024-04-01 23:48:56 Caused by: java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.FieldVisitor, but class was expected
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.ClassEmitter.field(ClassEmitter.java:606)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.ClassEmitter.field(ClassEmitter.java:619)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.ClassEmitter.defineCommonStatics(ClassEmitter.java:270)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.ClassEmitter.<init>(ClassEmitter.java:210)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.Compiler.createCompileUnit(Compiler.java:766)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.Compiler.createCompileUnit(Compiler.java:774)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.Compiler.addCompileUnit(Compiler.java:759)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.CompilationPhase$SplittingPhase.transform(CompilationPhase.java:117)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1531)
2024-04-01 23:48:56     at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:785)
2024-04-01 23:48:56     at org.openjdk.nashorn.api.scripting.NashornScriptEngine.asCompiledScript(NashornScriptEngine.java:486)
2024-04-01 23:48:56     at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compile(NashornScriptEngine.java:178)
2024-04-01 23:48:56     at org.keycloak.scripting.DefaultScriptingProvider.tryCompile(DefaultScriptingProvider.java:85)
2024-04-01 23:48:56     at org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:77)
2024-04-01 23:48:56     at org.keycloak.scripting.DefaultScriptingProvider.prepareEvaluatableScript(DefaultScriptingProvider.java:37)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.lambda$getEvaluatableScript$0(JSPolicyProviderFactory.java:110)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.provider.js.ScriptCache.lambda$computeIfAbsent$0(ScriptCache.java:81)
2024-04-01 23:48:56     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
2024-04-01 23:48:56     at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.provider.js.ScriptCache.computeIfAbsent(ScriptCache.java:81)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.getEvaluatableScript(JSPolicyProviderFactory.java:107)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.provider.js.JSPolicyProvider.evaluate(JSPolicyProvider.java:49)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:62)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.provider.permission.ScopePolicyProvider.evaluate(ScopePolicyProvider.java:55)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.lambda$createPolicyEvaluator$0(DefaultPolicyEvaluator.java:117)
2024-04-01 23:48:56     at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
2024-04-01 23:48:56     at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache$1.accept(StoreFactoryCacheSession.java:966)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache$1.accept(StoreFactoryCacheSession.java:961)
2024-04-01 23:48:56     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2024-04-01 23:48:56     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2024-04-01 23:48:56     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2024-04-01 23:48:56     at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2024-04-01 23:48:56     at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
2024-04-01 23:48:56     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-04-01 23:48:56     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2024-04-01 23:48:56     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2024-04-01 23:48:56     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2024-04-01 23:48:56     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2024-04-01 23:48:56     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2024-04-01 23:48:56     at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
2024-04-01 23:48:56     at org.keycloak.authorization.jpa.store.JPAPolicyStore.findByResource(JPAPolicyStore.java:223)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.lambda$findByResource$4(StoreFactoryCacheSession.java:961)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1074)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1063)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.findByResource(StoreFactoryCacheSession.java:959)
2024-04-01 23:48:56     at org.keycloak.authorization.AuthorizationProvider$3.findByResource(AuthorizationProvider.java:408)
2024-04-01 23:48:56     at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.evaluate(DefaultPolicyEvaluator.java:71)
2024-04-01 23:48:56     at org.keycloak.authorization.permission.evaluator.UnboundedPermissionEvaluator.lambda$evaluate$0(UnboundedPermissionEvaluator.java:49)
2024-04-01 23:48:56     at org.keycloak.authorization.permission.Permissions.lambda$all$0(Permissions.java:78)
2024-04-01 23:48:56     at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
2024-04-01 23:48:56     at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache$1.accept(StoreFactoryCacheSession.java:686)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache$1.accept(StoreFactoryCacheSession.java:681)
2024-04-01 23:48:56     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2024-04-01 23:48:56     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2024-04-01 23:48:56     at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2024-04-01 23:48:56     at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
2024-04-01 23:48:56     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-04-01 23:48:56     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2024-04-01 23:48:56     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2024-04-01 23:48:56     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2024-04-01 23:48:56     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2024-04-01 23:48:56     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2024-04-01 23:48:56     at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
2024-04-01 23:48:56     at org.keycloak.authorization.jpa.store.JPAResourceStore.findByOwnerFilter(JPAResourceStore.java:129)
2024-04-01 23:48:56     at org.keycloak.authorization.jpa.store.JPAResourceStore.findByOwner(JPAResourceStore.java:103)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache.lambda$findByOwner$4(StoreFactoryCacheSession.java:681)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache.cacheQuery(StoreFactoryCacheSession.java:826)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache.cacheQuery(StoreFactoryCacheSession.java:811)
2024-04-01 23:48:56     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$ResourceCache.findByOwner(StoreFactoryCacheSession.java:679)
2024-04-01 23:48:56     at org.keycloak.authorization.AuthorizationProvider$4.findByOwner(AuthorizationProvider.java:499)
2024-04-01 23:48:56     at org.keycloak.authorization.permission.Permissions.all(Permissions.java:76)
2024-04-01 23:48:56     at org.keycloak.authorization.permission.evaluator.UnboundedPermissionEvaluator.evaluate(UnboundedPermissionEvaluator.java:48)
2024-04-01 23:48:56     ... 13 more
```

### How to Reproduce?

Use plain keycloak instance and apply simple js policy with `$evaluation.grant();`.

After that do setup of Policy and Permission in Client Authorizations Tab.

Go to Evaluate tab and select any user and click "Evaluate"

### Anything else?

I was running this js-policy from 23 version and when I updated to 24 version. this exception coming up. I am not sure what is wrong but I think something is wrong with Keycloak build. Ca nsomeone try this and verify if this is working in your case?

**Comment by pedroigor** [comment]
@mihirvadalia What is the JRE version you are using?

**Comment by mihirvadalia** [comment]
@pedroigor I am using a docker container to run Keycloak.

If you are asking for my machine's JRE version, I am using 17.

**Comment by mihirvadalia** [comment]
@pedroigor You are correct about standalone deployment.

Default JS Policy is working in Standalone Keycloak Deployment.

But only in Docker (quay.io/keycloak/keycloak:24.0.2), it is giving me Exception provided in previous message.

It seems there might be an issue with the Keycloak Docker Image. Could you assist me with this, or is there any way I can help you further?

**Comment by pedroigor** [comment]
@mihirvadalia Thanks for the investigation. Sure we can and I'll ask @keycloak/cloud-native-maintainers to have a look on it.

**Comment by shawkins** [comment]
I was not able to reproduce this starting from: docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:24.0.2 start-dev

Would it be possible to provide complete reproduction steps when you are using Docker?

It seems very odd as the image is using java 17 as well. I wouldn't expect an error like this unless code created for a later vm is being run on an older one - which is not the case. Or if an extremely old version of asm is being brought into play - but nothing like that exists in the image.
