### ISSUE TITLE
Expected start tag:UIInfo. error while loading SAML's metadata

### ISSUE THREAD

**Issue by Nexodedev** [keycloak/keycloak#28461]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

I want to use the belnet federation as an IDP for my keycloak.
I already gave them my metadata IDP file and they accepted it.
But when i try to use the federation's descriptor's file in my realm, it doesn't accept it.
Even when i don't use the descriptor but i try to import it from the file i downloaded, same error.
![Capture2](https://github.com/keycloak/keycloak/assets/99415532/43f44d82-f96c-4de1-90f8-36fe7b536e23)
![Capture](https://github.com/keycloak/keycloak/assets/99415532/72a30b95-da02-4275-9565-075377646355)
https://federation.belnet.be/metadata/federation-metadata.xml
So i went to the logs to see what is happening.
And here are the logs.
```
keycloak-1  | 2024-04-05 07:05:39,711 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.RuntimeException: PL00066: Parser : Expected start tag:UIInfo.  Found <UIInfo>
keycloak-1  |   at org.keycloak.saml.common.DefaultPicketLinkLogger.parserExpectedTag(DefaultPicketLinkLogger.java:451)
keycloak-1  |   at org.keycloak.saml.common.util.StaxParserUtil.validate(StaxParserUtil.java:887)
keycloak-1  |   at org.keycloak.saml.common.parsers.AbstractStaxParser.validateStartElement(AbstractStaxParser.java:122)
keycloak-1  |   at org.keycloak.saml.common.parsers.AbstractStaxParser.parse(AbstractStaxParser.java:55)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLExtensionsParser.processSubElement(SAMLExtensionsParser.java:56)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLExtensionsParser.processSubElement(SAMLExtensionsParser.java:33)
keycloak-1  |   at org.keycloak.saml.common.parsers.AbstractStaxParser.parse(AbstractStaxParser.java:97)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLRoleDecriptorTypeParser.processSubElement(SAMLRoleDecriptorTypeParser.java:39)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLSSODescriptorTypeParser.processSubElement(SAMLSSODescriptorTypeParser.java:40)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLSPSSODescriptorParser.processSubElement(SAMLSPSSODescriptorParser.java:62)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLSPSSODescriptorParser.processSubElement(SAMLSPSSODescriptorParser.java:16)
keycloak-1  |   at org.keycloak.saml.common.parsers.AbstractStaxParser.parse(AbstractStaxParser.java:97)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLEntityDescriptorParser.processSubElement(SAMLEntityDescriptorParser.java:87)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLEntityDescriptorParser.processSubElement(SAMLEntityDescriptorParser.java:40)
keycloak-1  |   at org.keycloak.saml.common.parsers.AbstractStaxParser.parse(AbstractStaxParser.java:97)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLEntitiesDescriptorParser.processSubElement(SAMLEntitiesDescriptorParser.java:71)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.metadata.SAMLEntitiesDescriptorParser.processSubElement(SAMLEntitiesDescriptorParser.java:33)
keycloak-1  |   at org.keycloak.saml.common.parsers.AbstractStaxParser.parse(AbstractStaxParser.java:97)
keycloak-1  |   at org.keycloak.saml.processing.core.parsers.saml.SAMLParser.parse(SAMLParser.java:123)
keycloak-1  |   at org.keycloak.saml.common.parsers.AbstractParser.parse(AbstractParser.java:93)
keycloak-1  |   at org.keycloak.saml.processing.core.saml.v2.util.SAMLMetadataUtil.parseEntityDescriptorType(SAMLMetadataUtil.java:110)
keycloak-1  |   at org.keycloak.broker.saml.SAMLIdentityProviderFactory.parseConfig(SAMLIdentityProviderFactory.java:74)
keycloak-1  |   at org.keycloak.services.resources.admin.IdentityProvidersResource.importFrom(IdentityProvidersResource.java:161)
keycloak-1  |   at org.keycloak.services.resources.admin.IdentityProvidersResource$quarkusrestinvoker$importFrom_a2928105606b1cfb77befafeb917cf58b5abe0c4.invoke(Unknown Source)
keycloak-1  |   at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-1  |   at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-1  |   at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1  |   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak-1  |   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak-1  |   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak-1  |   at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak-1  |   at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak-1  |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1  |   at java.base/java.lang.Thread.run(Thread.java:840)

```
And the part i don't understand is that UIInfo is writed right as i see in the metadata's file.
I walked in the whole file to look every UIInfo and didn't see something strange.
I checked too the namespaces and they looked to be right.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

When i create a new IDP and give it the descriptor i should get autocompletion of the metadata's fields.

### Actual behavior

Error and not autocompletation. See the part "Describe the bug" with the error message and the logs from the error.

### How to Reproduce?

Go to your realm>Identity providers>new provider and in the field SAML entity descriptor put https://federation.belnet.be/metadata/federation-metadata.xml (with Use entity descriptor fixed on ON)

### Anything else?

You can find the metadata file at :

https://federation.belnet.be/metadata/federation-metadata.xml (production)

**Comment by jonkoops** [comment]
I tried getting the XML from https://federation.belnet.be/metadata/federation-metadata.xml, and the endpoint is very slow and returns inconsistent and sometimes returns invalid XML (as you can see in the stack trace). Hence, this is not a bug in Keycloak, but an issue with the provider you are trying to integrate.
