### ISSUE TITLE
[LDAPStorageProvider] NPE if user is cached but has been deleted in ldap

### ISSUE THREAD

**Issue by Juern-Univention** [keycloak/keycloak#28523]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

If a user tries to log in with an account that was previously cached by Keycloak, but has been deleted or recreated in the meantime, a `java.lang.NullPointerException` is logged and the user is getting an error message `Unexpected error when handling authentication request to identity provider.`

Error: `2024-04-08 15:27:43,364 WARN  [org.keycloak.services] (executor-thread-45) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.storage.ldap.idm.model.LDAPObject.getDn()" because "user" is null`

<details><summary>Full traceback</summary>

```
2024-04-08 15:27:43,364 WARN  [org.keycloak.services] (executor-thread-45) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.storage.ldap.idm.model.LDAPObject.getDn()" because "user" is null
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.validatePassword(LDAPIdentityStore.java:358)
	at org.keycloak.storage.ldap.LDAPStorageProvider.validPassword(LDAPStorageProvider.java:779)
	at org.keycloak.storage.ldap.LDAPStorageProvider.isValid(LDAPStorageProvider.java:865)
	at org.keycloak.credential.UserCredentialManager.lambda$validate$11(UserCredentialManager.java:255)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at org.keycloak.credential.UserCredentialManager.validate(UserCredentialManager.java:255)
	at org.keycloak.credential.UserCredentialManager.isValid(UserCredentialManager.java:71)
	at org.keycloak.models.SubjectCredentialManager.isValid(SubjectCredentialManager.java:45)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validatePassword(AbstractUsernameFormAuthenticator.java:230)
	at org.keycloak.authentication.authenticators.browser.AbstractUsernameFormAuthenticator.validateUserAndPassword(AbstractUsernameFormAuthenticator.java:151)
	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.validateForm(UsernamePasswordForm.java:55)
	at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.action(UsernamePasswordForm.java:48)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:151)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:987)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:364)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:335)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:327)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:392)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

</details>

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

- No NullPointerException in the logs
- A clear warning is logged that describes that a cached user was not found in the storage provider, including its identifier.
- The user trying to log in gets the usual `Invalid username or password.` message, instead of this error `Unexpected error when handling authentication request to identity provider.`
- [Optional?] Proper cache invalidation if the user was not found, though I have no idea how complicated that might. This is useful if a user was deleted and recreated. In that case it will be found in the cache by the username but not in the ldap because its `entryUUID` changed

### Actual behavior

A  `java.lang.NullPointerException` is printed in the logs if a user tries to log in with an account that has been cached in Keycloak but deleted in LDAP. The user is shown an error message `Unexpected error when handling authentication request to identity provider.`

### How to Reproduce?

- Add an LDAP user federation provider
- Make sure `Synchronization` is disabled in the provider settings
- Make sure the `Cache` is enabled in the provider settings
- Create an LDAP user
- Log in to Keycloak with that user
- Log out
- Delete the user in LDAP
- Log in to Keycloak with that user -> You should now see the `java.lang.NullPointerException` in the logs

<details><summary>My LDAP provider settings if it helps:</summary>

```
{
    "id": "e8ebe00c-af2a-424c-8c21-3f4058cd830f",
    "name": "ldap",
    "providerId": "ldap",
    "providerType": "org.keycloak.storage.UserStorageProvider",
    "parentId": "f826d050-fc1a-4be1-ba6c-aab369c6ae45",
    "config": {
        "pagination": [
            "true"
        ],
        "fullSyncPeriod": [
            "-1"
        ],
        "startTls": [
            "false"
        ],
        "connectionPooling": [
            "false"
        ],
        "usersDn": [
            "dc=school,dc=test"
        ],
        "cachePolicy": [
            "MAX_LIFESPAN"
        ],
        "useKerberosForPasswordAuthentication": [
            "false"
        ],
        "importEnabled": [
            "false"
        ],
        "enabled": [
            "true"
        ],
        "bindCredential": [
            "**********"
        ],
        "bindDn": [
            "uid=sys-idp-user,cn=users,dc=school,dc=test"
        ],
        "usernameLDAPAttribute": [
            "uid"
        ],
        "changedSyncPeriod": [
            "-1"
        ],
        "vendor": [
            "other"
        ],
        "uuidLDAPAttribute": [
            "entryUUID"
        ],
        "connectionUrl": [
            "ldap://10.207.15.183:7389"
        ],
        "allowKerberosAuthentication": [
            "false"
        ],
        "syncRegistrations": [
            "false"
        ],
        "authType": [
            "simple"
        ],
        "krbPrincipalAttribute": [
            "krb5PrincipalName"
        ],
        "customUserSearchFilter": [
            "(|(memberOf=cn=Domain Admins,cn=groups,dc=school,dc=test)(memberOf=cn=DC Backup Hosts,cn=groups,dc=school,dc=test))"
        ],
        "searchScope": [
            "2"
        ],
        "useTruststoreSpi": [
            "always"
        ],
        "usePasswordModifyExtendedOp": [
            "false"
        ],
        "maxLifespan": [
            "300000"
        ],
        "trustEmail": [
            "false"
        ],
        "userObjectClasses": [
            "person"
        ],
        "rdnLDAPAttribute": [
            "uid"
        ],
        "editMode": [
            "READ_ONLY"
        ],
        "validatePasswordPolicy": [
            "false"
        ]
    }
}
```

</detail>

### Anything else?

Thank you very much for logging into this.

**Comment by sguilhen** [comment]
Was able to reproduce and sent a PR with the fix. There were a few places where the user returned from LDAP is not checked for null value.
