### ISSUE TITLE
Error creating new realm 

### ISSUE THREAD

**Issue by amrutha2692** [keycloak/keycloak#28626]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

I encountered an error while attempting to create a new realm in Keycloak. The error message indicates a not-null constraint violation related to the "social" column in the database.

Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "social" violates not-null constraint
  Detail: Failing row contains (f1ca2609-751b-4f23-b3ba-6210f990d03f, 0, 0, 0, null, null, null, f, f, 0, null, test, 0, null, f, f, f, null, null, 0, 0, null, f, null, 0, f, null, f, f, f, f, 0, 0, 0, 0, null, null, null, null, null, null, null, 0, f, 0, f, f, null, 0, f, 0, 0, null).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
        at jdk.proxy2/jdk.proxy2.$Proxy70.executeUpdate(Unknown Source)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:275)

### Version

Keycloak - Version 23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The realm creation process should complete successfully without encountering any errors.

### Actual behavior

Encounter a not-null constraint violation error related to the "social" column in the database.

### How to Reproduce?

Keycloak version: 23.0.6
Database type and version: psql (PostgreSQL) 12.18 
Operating system: ubuntu20.04.1

**Comment by amrutha2692** [comment]
https://github.com/keycloak/keycloak/issues/10432
https://github.com/keycloak/keycloak/issues/13301

Similar issue reported.
