### ISSUE TITLE
docker-v2 authentication fails with KC-SERVICES0097: Invalid request: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.ClientModel.getClientScopes(boolean)" because "this.client" is null

### ISSUE THREAD

**Issue by xepa** [keycloak/keycloak#28649]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Using the default `docker-v2` setup for keycloak, downloading the docker-compose config files, I have started the docker containers.  On a `docker login <url>` I now see the following `received unexpected HTTP status: 500 Internal Server Error`

Looking at the debug logs in keycloak I see
```
keycloak  | 2024-04-11 20:04:00,973 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (executor-thread-10) Recalculated absoluteURI to https://<domain>/auth/realms/Test/protocol/docker-v2/auth?account=test&client_id=docker&offline_token=true&service=docker-v2
keycloak  | 2024-04-11 20:04:00,974 WARN  [org.keycloak.services] (executor-thread-10) KC-SERVICES0097: Invalid request: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.ClientModel.getClientScopes(boolean)" because "this.client" is null
keycloak  | 	at org.keycloak.protocol.oidc.rar.parsers.ClientScopeAuthorizationRequestParser.parseScopes(ClientScopeAuthorizationRequestParser.java:74)
keycloak  | 	at org.keycloak.services.util.AuthorizationContextUtil.getAuthorizationRequestContextFromScopes(AuthorizationContextUtil.java:57)
keycloak  | 	at org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor.parseRequest(AuthorizationEndpointRequestParserProcessor.java:109)
keycloak  | 	at org.keycloak.protocol.docker.DockerEndpoint.build(DockerEndpoint.java:69)
keycloak  | 	at org.keycloak.protocol.docker.DockerEndpoint$quarkusrestinvoker$build_a0e8245c51fd7c419b3b5b83634b474c47ceb703.invoke(Unknown Source)
keycloak  | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak  | 	at java.base/java.lang.Thread.run(Thread.java:840)
keycloak  |
keycloak  | 2024-04-11 20:04:00,974 DEBUG [org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext] (executor-thread-10) Restarting handler chain for exception exception: java.lang.IllegalStateException: Attempted to define event error without first setting the event type
keycloak  | 	at org.keycloak.events.EventBuilder.error(EventBuilder.java:226)
keycloak  | 	at org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor.parseRequest(AuthorizationEndpointRequestParserProcessor.java:116)
keycloak  | 	at org.keycloak.protocol.docker.DockerEndpoint.build(DockerEndpoint.java:69)
keycloak  | 	at org.keycloak.protocol.docker.DockerEndpoint$quarkusrestinvoker$build_a0e8245c51fd7c419b3b5b83634b474c47ceb703.invoke(Unknown Source)
keycloak  | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak  | 	at java.base/java.lang.Thread.run(Thread.java:840)
keycloak  |
keycloak  | 2024-04-11 20:04:00,974 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-10) Uncaught server error: java.lang.IllegalStateException: Attempted to define event error without first setting the event type
keycloak  | 	at org.keycloak.events.EventBuilder.error(EventBuilder.java:226)
keycloak  | 	at org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor.parseRequest(AuthorizationEndpointRequestParserProcessor.java:116)
keycloak  | 	at org.keycloak.protocol.docker.DockerEndpoint.build(DockerEndpoint.java:69)
keycloak  | 	at org.keycloak.protocol.docker.DockerEndpoint$quarkusrestinvoker$build_a0e8245c51fd7c419b3b5b83634b474c47ceb703.invoke(Unknown Source)
keycloak  | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak  | 	at java.base/java.lang.Thread.run(Thread.java:840)
```
I am not quite certain when it broke but I can remember that is used to work.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Login works as expected

### Actual behavior

Internal server error

### How to Reproduce?

Config docker-v2 auth .. download the composer config and run .. then login

**Comment by rmartinc** [comment]
Hi @xepa!

The line with the NPE is [this one](https://github.com/keycloak/keycloak/blob/24.0.2/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthorizationEndpointRequestParserProcessor.java#L109), so I suppose DYNAMIC_SCOPES is enabled in your env, right?

If you disable DYNAMIC_SCOPES does it work? I think it's missing adding the client into the session context, but just to be sure.

**Comment by rmartinc** [comment]
I could make the test fail when I added the DYNAMIC_SCOPES feature. So I'm sending a PR for this. But please check if it works for you without that feature enabled.
