### ISSUE TITLE
Constantly increasing direct buffer memory usage at Keycloak versions 20 and  21

### ISSUE THREAD

**Issue by id956729** [keycloak/keycloak#28695]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

We run our keycloak instances in docker container with infinispan jdbc-ping-tcp cache config.
We have next issue when buffer memory reach it's limit controlled via -XX:MaxDirectMemorySize, 4G it reach in ~1-1.5 week.
```
java.lang.OutOfMemoryError: Direct buffer memory
	        at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
	        at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	        at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
	        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:701)
	        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:676)
	        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:215)
	        at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:180)
	        at io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
```

![DirrectBufferMemory](https://github.com/keycloak/keycloak/assets/165378907/624cf29d-7f90-4096-8103-c030a7c01a3b)

 We tried debug and find the reason, next java opts not working maybe case such container is limited -XX:HeapDumpPath=/tmp/outofmem/hhdump.hprof -XX:+HeapDumpOnOutOfMemoryError
 I was able to attach tools for heap dump from build openjdk in dockerfile and can gather heap dumps, but still can't find a reason, here some report but it looks like common
 https://heaphero.io/heap-report-wc.jsp?p=NzF2RkpzRGxGSUk1YWpkTDFNV3JQcElOUDdESTQvYXdUUDU0MjFyTGtCbXZrL3ZvVDk2UjVOZ0lENVZiQWY2RHNPc29MTXZaTU5xOHgvVW9wazE0MXc9PQ==
 
 We upgraded version 20.0.5 > 21.1.2 but it's the same, we can't update to latest cause we have some providers that can't work with latest versions.
 Needed help for troubleshoot this behavior

### Version

20.0.5 and 21.1.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Refreshed buffer memory via garbage collectot etc.

### Actual behavior

Constantly increasing buffer memory usage, refreshed just after restart container

### How to Reproduce?

It's constantly on our deployment

**Comment by id956729** [comment]
![DirrectBufferMemory](https://github.com/keycloak/keycloak/assets/165378907/a118fac9-15ec-4dab-a854-2c5deaf3d637)
