### ISSUE TITLE
Keycloak 24.0.2 - Enlisted connection used without active transaction

### ISSUE THREAD

**Issue by nicolabeghin** [keycloak/keycloak#28725]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

After upgrading from Keycloak 24.0.1 to 24.0.2 we get `Enlisted connection used without active transaction` when performing simple JTA database queries. This wasn't happening with Keycloak 24.0.1.

    ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffffac121b02:98d7:661d0095:ed, node_name=quarkus, branch_uid=0:ffffac121b02:98d7:661d0095:f8, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@7353c9ff) failed with exception code XAException.XAER_RMERR: javax.transaction.xa.XAException: Error trying to transactionRollback local transaction: Enlisted connection used without active transaction
    	at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
    	at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
    	at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:89)
    	at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelAbort(XAResourceRecord.java:338)
    	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:644)
    	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:398)
    	at io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:120)
    	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:257)
    	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
    	at io.agroal.api.AgroalDataSource_aXsljFDRQH0VZ1zd1FnWzMmdtx8_Synthetic_ClientProxy.getConnection(Unknown Source)
    	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
    	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:46)
    	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:113)
    	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:143)
    	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:54)
    	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:153)
    	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:183)
    	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:155)
    	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.lambda$list$0(JdbcSelectExecutor.java:85)
    	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:231)
    	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)
    	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)
    	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)
    	at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
    	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
    	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:202)
    	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
    	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:209)
    	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)
    	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)
    	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)
    	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$2(ConcreteSqmSelectQueryPlan.java:137)
    	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:362)
    	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:303)
    	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:509)
    	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427)
    	at org.hibernate.query.Query.getResultList(Query.java:120)
    	at org.keycloak.multipleds.storage.user.entities.UserDAO.findStreamByUsername(UserDAO.java:56)
    	at org.keycloak.multipleds.storage.user.entities.UserDAO.findByUsername(UserDAO.java:26)
    	at org.keycloak.multipleds.storage.user.MultipleDSUserStorageProvider.validate(MultipleDSUserStorageProvider.java:107)
    	at org.keycloak.storage.UserStorageManager.importValidation(UserStorageManager.java:130)
    	at org.keycloak.storage.UserStorageManager.getUserById(UserStorageManager.java:369)
    	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserById(UserCacheSession.java:218)
    	at org.keycloak.models.jpa.JpaUserProvider.lambda$searchForUserStream$6(JpaUserProvider.java:761)
    	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
    	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
    	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
    	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
    	at org.keycloak.utils.ClosingStream.forEach(ClosingStream.java:128)
    	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
    	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
    	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
    	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
    	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
    	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
    	at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:71)
    	at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:15)
    	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
    	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
    	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
    	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
    	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
    	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter.writeResponse(FullyFeaturedServerJacksonMessageBodyWriter.java:79)
    	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:216)
    	at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:184)
    	at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:28)
    	at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
    	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
    	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
    	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
    	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    	at java.base/java.lang.Thread.run(Thread.java:840)
    Caused by: java.sql.SQLException: Enlisted connection used without active transaction
    	at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:381)
    	at io.agroal.pool.ConnectionHandler.transactionRollback(ConnectionHandler.java:352)
    	at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:86)
    	... 84 more

### Version

24.0.2

### Regression

- [X] The issue is a regression

Reported also in `user-storage-jpa` quickstart tests failing in CI/CD https://github.com/keycloak/keycloak-quickstarts/actions/runs/8385258829

### Expected behavior

When performing JDBC queries we shouldn't get `Enlisted connection used without active transaction`

### Actual behavior

When performing JDBC queries we get `Enlisted connection used without active transaction`

### How to Reproduce?

Setup a simple `jakarta.persistence.EntityManager` in your `UserStorageProvider` and perform a JTA query

https://github.com/nicolabeghin/keycloak-multiple-ds-user-storage/blob/master/src/main/java/org/keycloak/multipleds/storage/user/entities/UserDAO.java#L59

### Anything else?

Issue does not happen with Keycloak 24.0.1 - could be due to Quarkus update 3.8.3 as per https://www.keycloak.org/2024/03/keycloak-2402-released ? 
ref. https://github.com/keycloak/keycloak/issues/28084

**Comment by mabartos** [comment]
@nicolabeghin Thanks for creating this issue.

As you pointed out, Quarkus has been upgraded from 3.8.1 to 3.8.3, and even the transitive Agroal dependency has been upgraded from 2.1 to 2.3 version. So potentially, there might be some problems directly in the Agroal.

[@barreiro](https://github.com/barreiro) Does it ring any bell? As you were dealing with similar issues, you might have some hints.

**Comment by barreiro** [comment]
@mabartos No, it doesn't ring. AFAICT there are no direct changes in Agroal 2.3 that could cause this exception.

Essentially, what that exception does is prevent a connection that was acquired within the scope of a transaction to be used outside that transaction.

**Comment by nicolabeghin** [comment]
Any suggestion on how to approach this or where to look at for a possible fix? 

https://github.com/keycloak/keycloak-quickstarts [CI/CD](https://github.com/keycloak/keycloak-quickstarts/actions) is failing since a month (March 22nd, 2024)
<img width="1084" alt="image" src="https://github.com/keycloak/keycloak/assets/2743637/5eebcbf2-1099-4d10-b2d5-fd2001b1d9eb">
<img width="1074" alt="image" src="https://github.com/keycloak/keycloak/assets/2743637/323cf060-0524-483b-902e-332c7f562c61">

thanks
nicola

**Comment by shawkins** [comment]
@barreiro @mabartos this due to a change in agroal-narayana from 2.1 to 2.3. In 2.1 LocalXAResource now implements LastResource - https://github.com/agroal/agroal/commit/e5cafc2fd1d6da27e11814d99d46d6b6d1fd0e41#diff-d6c0a87c07c761a760bb2d43218139307a1c0ce42c9f62437a699cf03f1d9707R23

 In 2.3 this means the XAResourceRecord.equals method will return true for the two h2 datasources and causes the enlistResource to fail because the AddOutcome is AR_DUPLICATE.

There seems to be some differences in 24 and main due to the changes related to the default for --transactions-xa-enabled. In main with the default of --transactions-xa-enabled=false, this error is immediately reproducible as both datasources use LocalXAResource. Is this expected? If quarkus.datasource.jdbc.transactions=enabled and you use two non-xa datasources should that always fail?

If --transactions-xa-enabled=true is true on main, the error does not occur because the keycloak datasource will be xa and use BaseXAResource instead.

**Comment by nicolabeghin** [comment]
@shawkins tried both on top of latest stable Keycloak 24.0.3:

during Docker build by using environment variable [KC_TRANSACTION_XA_ENABLED](https://www.keycloak.org/server/db)

    ENV KC_TRANSACTION_XA_ENABLED=true

and also explicitly

    RUN /opt/keycloak/bin/kc.sh build --transaction-xa-enabled=true

but unfortunately same error as before

**Comment by shawkins** [comment]
@barreiro create https://github.com/quarkusio/quarkus/issues/40343 to track this upstream

**Comment by nicolabeghin** [comment]
> @nicolabeghin do you see the log message "2024-04-29 08:01:58,672 WARN [io.quarkus.agroal.runtime.DataSources] (JPA Startup Thread: keycloak-default) Datasource enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly"?

I confirm:

> [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly

**Comment by shawkins** [comment]
@nicolabeghin not sure what is going on in your case then, unless there are more datasources in play. Locally with 24.0.3 if xa is enabled and there is only 1 other non-xa datasource, then this scenario works fine for me.

**Comment by nicolabeghin** [comment]
> @nicolabeghin not sure what is going on in your case then, unless there are more datasources in play. Locally with 24.0.3 if xa is enabled and there is only 1 other non-xa datasource, then this scenario works fine for me.

I'm following the `user-storage-jpa` quickstart, with `persistence.xml`: as far as I understand this is the whole point? Nothing fancy from that https://github.com/keycloak/keycloak-quickstarts/blob/latest/extension/user-storage-jpa/src/main/resources/META-INF/persistence.xml

Maybe something to change in `persistence.xml` to specify that additional connections should not be performed with XA?

**Comment by shawkins** [comment]
> I'm following the user-storage-jpa quickstart, with persistence.xml: as far as I understand this is the whole point?

I should clarify, I'm not actually using the persistence unit in what I'm doing - the exception can be reproduced without it. See https://github.com/quarkusio/quarkus/issues/40343 for a distilled version of this problem. 

The implication is that the persistence unit is bringing in yet another non-xa datasource - which would be unexpected. A resolution from a previous issue was to not use the persistence.xml mechanism at all, and instead convert the example to use just quarkus properties - #27320 that would at least simplify things a bit.

On the small quarkus reproducer, if you add quarkus.datasource.first.jdbc.transactions=xa to the configuration (similar to what transactions-xa-enabled=true is doing) it will work. 

Similarly you can also try adding quarkus.datasource.user-store.jdbc.transactions=xa to the quickstart.

**Comment by nicolabeghin** [comment]
> Similarly you can also try adding quarkus.datasource.user-store.jdbc.transactions=xa to the quickstart.

I confirm it works with `quarkus.datasource.user-store.jdbc.transactions=xa`!! thanks a lot @shawkins 💯

**Comment by shawkins** [comment]
@pedroigor @vmuzikar with a confirmed workaround, I'll drop the priority to important.

~priority-important

**Comment by shawkins** [comment]
@vmuzikar that is correct

**Comment by shawkins** [comment]
Now associated with https://github.com/quarkusio/quarkus/issues/39283 - I've added a comment to the pr about how this is affecting us.

**Comment by diogoideguchi** [comment]
I'm currently testing a User SPI implementation based on the quickstart (https://github.com/b1-systems/keycloak-user-storage-test) and found the same issue on Keycloak 26.3.0 (Quarkus 3.20.1). 

keycloak     | 2025-07-07 16:35:15,996 WARN  [com.arjuna.ats.jta] (executor-thread-6) ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffffac180003:a661:686bf6ed:1d4, node_name=quarkus, branch_uid=0:ffffac180003:a661:686bf6ed:1db, subordinatenodename=null, eis_name=0 > **(io.agroal.narayana.LocalXAResource@27e3c32b) failed with exception code XAException.XAER_RMERR: javax.transaction.xa.XAException: Error trying to transactionRollback local transaction: Enlisted connection used without active transaction**
keycloak     |  at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
keycloak     |  at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:8)
keycloak     |  at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:89)
keycloak     |  at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelAbort(XAResourceRecord.java:318)
keycloak     |  at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:664)
keycloak     |  at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:408)
keycloak     |  at io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:125)
keycloak     |  at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:297)
keycloak     |  at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
keycloak     |  at io.agroal.api.AgroalDataSource_zYePm2bVsv10cJFbrl2B06JL9W4_Synthetic_ClientProxy.getConnection(Unknown Source)
keycloak     |  at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
keycloak     |  at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:46)
keycloak     |  at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:126)
keycloak     |  at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:156)
keycloak     |  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:56)
keycloak     |  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$4.doPrepare(StatementPreparerImpl.java:151)
keycloak     |  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:180)
keycloak     |  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:153)
keycloak     |  at org.hibernate.sql.exec.internal.StandardStatementCreator.createStatement(StandardStatementCreator.java:49)
keycloak     |  at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:235)
keycloak     |  at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:171)
keycloak     |  at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.<init>(JdbcValuesResultSetImpl.java:74)
keycloak     |  at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.resolveJdbcValuesSource(JdbcSelectExecutorStandardImpl.java:355)
keycloak     |  at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:137)
keycloak     |  at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:102)
keycloak     |  at org.hibernate.sql.exec.spi.JdbcSelectExecutor.scroll(JdbcSelectExecutor.java:195)
keycloak     |  at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$2(ConcreteSqmSelectQueryPlan.java:187)
keycloak     |  at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:442)
keycloak     |  at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performScroll(ConcreteSqmSelectQueryPlan.java:370)
keycloak     |  at org.hibernate.query.sqm.internal.QuerySqmImpl.doScroll(QuerySqmImpl.java:456)
keycloak     |  at org.hibernate.query.spi.AbstractSelectionQuery.scroll(AbstractSelectionQuery.java:242)
keycloak     |  at org.hibernate.query.spi.AbstractSelectionQuery.stream(AbstractSelectionQuery.java:259)
keycloak     |  at org.hibernate.query.spi.AbstractSelectionQuery.getResultStream(AbstractSelectionQuery.java:253)
keycloak     |  at de.linuxfoo.keycloak.storage.user.UserStorageTestProvider.searchForUserStream(UserStorageTestProvider.java:337)
keycloak     |  at org.keycloak.storage.UserStorageManager.lambda$searchForUserStream$33(UserStorageManager.java:598)
keycloak     |  at org.keycloak.storage.UserStorageManager.lambda$query$14(UserStorageManager.java:396)
keycloak     |  at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
keycloak     |  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak     |  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak     |  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
keycloak     |  at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
keycloak     |  at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
keycloak     |  at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
keycloak     |  at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
keycloak     |  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
keycloak     |  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak     |  at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
keycloak     |  at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
keycloak     |  at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
keycloak     |  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
keycloak     |  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak     |  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
keycloak     |  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
keycloak     |  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak     |  at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
keycloak     |  at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:71)
keycloak     |  at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:15)
keycloak     |  at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
keycloak     |  at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:422)
keycloak     |  at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1579)
keycloak     |  at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1285)
keycloak     |  at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
keycloak     |  at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter.writeResponse(FullyFeaturedServerJacksonMessageBodyWriter.java:106)
keycloak     |  at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter_ClientProxy.writeResponse(Unknown Source)
keycloak     |  at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:218)
keycloak     |  at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:186)
keycloak     |  at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:28)
keycloak     |  at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
keycloak     |  at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
keycloak     |  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak     |  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:638)
keycloak     |  at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
keycloak     |  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
keycloak     |  at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
keycloak     |  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
keycloak     |  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
keycloak     |  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
keycloak     |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak     |  at java.base/java.lang.Thread.run(Thread.java:1583)
keycloak     | Caused by: java.sql.SQLException: Enlisted connection used without active transaction
keycloak     |  at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:391)
keycloak     |  at io.agroal.pool.ConnectionHandler.transactionRollback(ConnectionHandler.java:362)
keycloak     |  at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:86)
keycloak     |  ... 76 more

The only way I found it to work is to build with --transaction-xa-enabled=true and adding quarkus.transaction-manager.enable-recovery=true and quarkus.datasource.user-store.jdbc.transactions=xa to quarkus.properties.
