### ISSUE TITLE
Assigning a client role to a federated user should result in an error event

### ISSUE THREAD

**Issue by CallumQ** [keycloak/keycloak#28903]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

We have a class which implements the `EventListenerProvider` class and converts the Keycloak AdminEvents & Events into valid ATNA audit messages. We also have an LDAP user federation provider configured. If you attempt to associate a Client Role to one of the LDAP users, we correctly see the following warning logged by Keycloak:

```
2024-04-18 22:37:59,649 WARN  [org.keycloak.services.resources.admin.ClientRoleMappingsResource] (executor-thread-2) Not possible to write 'role mapping for role delete-account' when updating user 'callum quigley': org.keycloak.storage.ReadOnlyException: Not possible to write 'role mapping for role delete-account' when updating user 'callum quigley'
        at org.keycloak.models.utils.ReadOnlyUserModelDelegate.readOnlyException(ReadOnlyUserModelDelegate.java:146)
        at org.keycloak.models.utils.ReadOnlyUserModelDelegate.grantRole(ReadOnlyUserModelDelegate.java:141)
        at org.keycloak.models.utils.UserModelDelegate.grantRole(UserModelDelegate.java:180)
        at org.keycloak.models.utils.UserModelDelegate.grantRole(UserModelDelegate.java:180)
        at org.keycloak.models.utils.UserModelDelegate.grantRole(UserModelDelegate.java:180)
        at org.keycloak.models.utils.UserModelDelegate.grantRole(UserModelDelegate.java:180)
        at org.keycloak.models.utils.UserModelDelegate.grantRole(UserModelDelegate.java:180)
        at org.keycloak.storage.adapter.UpdateOnlyChangeUserModelDelegate.grantRole(UpdateOnlyChangeUserModelDelegate.java:140)
        at org.keycloak.services.resources.admin.ClientRoleMappingsResource.addClientRoleMapping(ClientRoleMappingsResource.java:172)
        at org.keycloak.services.resources.admin.ClientRoleMappingsResource$quarkusrestinvoker$addClientRoleMapping_e892ae5b6266e480261037b36aabdf3bb6b5f517.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

However, the corresponding event for this operation is logged without an error string. Below I've printed out the contents of the event:
```
2024-04-18 22:37:59,556 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Error: null
2024-04-18 22:37:59,556 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Operation Type: CREATE
2024-04-18 22:37:59,556 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Realm Id: b44380dd-f854-44ae-ad96-8756b0a11b71
2024-04-18 22:37:59,557 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Resource Path: users/f:36a2907f-3b58-4f12-81f8-1c236b13d767:Callum Quigley/role-mappings/realm
2024-04-18 22:37:59,557 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Resource Type: REALM_ROLE_MAPPING
2024-04-18 22:37:59,557 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Time: 1713479879552
2024-04-18 22:37:59,557 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Auth Details: e71c7e41-1ed1-47d9-a185-88774349ed58
2024-04-18 22:37:59,557 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Auth Details: 49e0e3c8-a0c9-4b9c-a06d-007a9d99ef24
2024-04-18 22:37:59,557 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Auth Details: e8456a2c-20a0-40cb-8b27-b503e3911389
2024-04-18 22:37:59,558 INFO  [com.canon.coau.atna.AtnaEventListenerProvider] (executor-thread-2) Auth Details: 172.21.0.1
```

We have also attempted to make use of the `KeycloakTransactionManager.enlistAfterCompletion` method, but it appears that the event is triggered before or on a different transaction than the related LDAP operation.

Is this the expected behaviour? 

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

`Event.error` should contain some error string related to the failed operation

### Actual behavior

`Event.error` is empty

### How to Reproduce?

1. Create an implementation of `EventListenerProvider` that prints the result of the `getError` method in both the `onEvent` methods.
2. Configure Keycloak to have an LDAP user federation provider.
3. ensure that "Import users" is disabled for the user federation configuration.
4. In the Keycloak admin UI, navigate to the users tab and select a user that is provided via the configured LDAP.
5. Navigate to the "Role mapping" tab, and click "Assign role".
6. Select Filter by clients from the dropdown, and then assign a client role to the LDAP provided user. I use the `delete-account` role from the `account` client.
7. You should now see the above stack trace warning, as well as the empty null print statement for the `onEvent` method

### Anything else?

While looking for potentially related issues, we came across issue #28255 which says:

> Taking the LDAP provider as an example, a user is created to the local storage but it fails to create the user in LDAP when there are failures executing the LDAP transaction enlisted after completion. This happens because JPA and LDAP transactions are isolated (no 2-phase commit protocol) and JPA transactions are committed first.

We suspect this might mean that the LDAP operation where we attempt to associate the client role to the LDAP provided user is performed in a separate transaction from the event log itself. 

This could be totally unrelated, but it sounded close enough and could explain why the event is logged without any errors.

**Comment by pedroigor** [comment]
The message you see is because the UI is also sending a request to `/role-mappings/realm` and at that endpoint an event is fired even though no realm roles are sent in the request. See https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/RoleMapperResource.java#L251.

We should not fire that event when no role was granted to a user.

We appreciate if you can collaborate with a fix so that we check if the `roles` parameter in that method is null or empty. If so, just return.

Not sure why the UI is calling that endpoint when adding a client role but fixing in the server side should be enough. @ssilvert Is it something we also want to fix in the UI?
