### ISSUE TITLE
error trying to test smtp connection

### ISSUE THREAD

**Issue by lucaskitinha** [keycloak/keycloak#29062]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

Hi, Im trying to test smtp connection in keycloak using java, im using this method keycloakService.getKeycloakClient().testSMTPConnection(emailConfig);, where emailConfig is a map.

When i try to test the connection in the admin console works perfectly, but when i try with java i only get this error

`org.keycloak.services.ErrorResponseException: HTTP 500 Internal Server Error
        at org.keycloak.services.ErrorResponse.error(ErrorResponse.java:43)
        at org.keycloak.services.ErrorResponse.error(ErrorResponse.java:36)
        at org.keycloak.services.resources.admin.RealmAdminResource.testSMTPConnection(RealmAdminResource.java:1003)
        at org.keycloak.services.resources.admin.RealmAdminResource$quarkusrestinvoker$testSMTPConnection_0bc3cac9c894e7b29eb4c1f2d80a099cba7bdf38.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-04-24 18:58:01,052 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-10) Failed to send email
 null`
 
 I looked it up at the api doc, and for this request i need to send a map in the body
 
![image](https://github.com/keycloak/keycloak/assets/83738150/c7928b45-ab16-4ab5-8dd5-039daa6c34fa)
I need help to figure out what i need to put in these settings for work

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Send the email

### Actual behavior

errro
2024-04-24 18:58:01,052 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-10) Failed to send email

### How to Reproduce?

try test smtp connection with java application

**Comment by rmartinc** [comment]
Hi @lucaskitinha!

If you see in version 24.0.3 line 1003 is [this one](https://github.com/keycloak/keycloak/blob/24.0.3/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L1003). So probably your admin user has no email to send the email test message. You have to check the response message to see the error if you are using that endpoint. You can check first using the admin console (to see what teh console is sending in the call) or even curl, and the change to Java. And please don't use github issues for these type of questions. Issues are more for code bugs and enhancements, not for help.

Best regards!
