### ISSUE TITLE
RealmResourceProvider still not working in version 24.0.3

### ISSUE THREAD

**Issue by suochensheng** [keycloak/keycloak#29121]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Our team is now facing the same problem.
 always got **405 Method Not Allowed** in **RealmResourceProvider** implement when we  follow the upgrading official guidance from v22 to v24.0.3 :https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-24-0-2

- Upgrading your custom JAX-RS resources
- Deprecated methods from data providers and models

**What we have tried**

1. Firstly we try the solution from official site : [RealmResourceProvider is not working as expected since version 23.0.0](https://github.com/keycloak/keycloak/issues/25882)
2. Verify beans.xml: Double-check that the META-INF/beans.xml file is indeed present in the JAR file where your custom providers are packaged. Ensure that it's an empty file (with no content between the <beans> tags) and that it's correctly placed in the META-INF directory within the JAR.
3. Check Provider Annotation: If you are using RealmResourceSPI or AdminRealmResourceSpi, ensure that your JAX-RS resource classes are annotated with @Provider. This annotation is necessary for the JAX-RS runtime to recognize the class as a REST resource provider.
4. Review @Consumes and @Produces Annotations: Make sure that your JAX-RS methods are correctly annotated with @Consumes and @Produces to specify the expected media types for input and output. This is important for the JAX-RS runtime to correctly process requests and responses.

**We also review the following code**

Provider Annotation: Ensure that your resource class is annotated with @Provider. This annotation is necessary for Keycloak to recognize the class as a JAX-RS resource provider.
import javax.ws.rs.ext.Provider;

Resource Path: Verify that the path you are using to access this resource is correct. The @Path("") annotation at the class level or method level will determine the URL at which this resource is available. If you have a @Path annotation at the class level, it will be combined with the method-level @Path.

**Error message**

```
2024-04-28 11:37:39,055 DEBUG [WebApplicationException] (executor-thread-5) Restarting handler chain for exception exception: jakarta.ws.rs.WebApplicationException: HTTP 405 Method Not Allowed
        at org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler.handle(ResourceLocatorHandler.java:71)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2024-04-28 11:37:39,055 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Error response 405: jakarta.ws.rs.WebApplicationException: HTTP 405 Method Not Allowed
        at org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler.handle(ResourceLocatorHandler.java:71)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

```

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

After deploying SPI , I would expect a GET HTTP call  "http://localhost:9000/auth/realms/TestRealm/check"  to return 200 with "Hello test xxxx" (given that the realm name is TestRealm)

### Actual behavior

I am getting a HTTP 405 status with the following response:

`{"error":"HTTP 405 Method Not Allowed"}`

![image](https://github.com/keycloak/keycloak/assets/4319553/fb9f75f8-91a8-438a-b1ef-47572214f9d7)

![image](https://github.com/keycloak/keycloak/assets/4319553/5f93641a-2fc1-4fb5-8e9c-2c0fd9ff1d70)

### How to Reproduce?

Just try the follow SPI demo with realm resource provider.
[Uploading api-key-module.zip…]()

### Anything else?

review and try the suggestions according to the bug discussed in keycloak github, all failed:

[RealmResourceProvider is not working as expected since version 23.0.0](https://github.com/keycloak/keycloak/issues/25882)
[Rest custom JAX-RS resource in kc 23: Method not allowed](https://github.com/keycloak/keycloak/issues/26088)
[Add a META-INF/beans.xml file to enable support for JAX-RS](https://github.com/keycloak/keycloak/issues/17891)

**Comment by suochensheng** [comment]
java and keycloak version , I follow the demo from https://github.com/keycloak/keycloak/issues/25882.
 ![image](https://github.com/keycloak/keycloak/assets/4319553/17ec868e-a976-44c8-b8d6-bf64fcd78007)

**Comment by shawkins** [comment]
@stianst @pedroigor @vmuzikar this was addressed by #25038 not sure if it's worth considering a backport at this point.

**Comment by suochensheng** [comment]
[api-key-module.zip](https://github.com/keycloak/keycloak/files/15371789/api-key-module.zip)

still no solution... demo code attached , FYI.

**Comment by Vumpik** [comment]
@suochensheng Hey. did you found some solution? I am also stuck on this with the same steps done and cant figure it out. :)

Thanks

**Comment by suochensheng** [comment]
> @suochensheng Hey. did you found some solution? I am also stuck on this with the same steps done and cant figure it out. :)
> 
> Thanks

Unfortunately, the official solution doesn't work. https://www.keycloak.org/docs/latest/upgrading/index.html#migration-changes.  So, we decide to stay on v21 for now.

**Comment by suochensheng** [comment]
I found why this issue ocurred , due to the annotation issue.

**Comment by suochensheng** [comment]
> @Vumpik I don't think there is a workaround, you cannot use custom classes annotated by the Provider annotation in KC 24.

Yes , the following code works actually , We should avoid to use custom classes annotated by the Provider annotation in KC 24.



```
@AutoService(RealmResourceProviderFactory.class)
public class TestResourceProviderFactory implements RealmResourceProviderFactory {

	public static final String PROVIDER_ID = "test-resource";

	@Override
	public RealmResourceProvider create(KeycloakSession keycloakSession) {
		return new MyResourceProvider(keycloakSession);
	}

	@Override
	public void init(Config.Scope scope) {
	}

	@Override
	public void postInit(KeycloakSessionFactory keycloakSessionFactory) {
	}

	@Override
	public void close() {
	}

	@Override
	public String getId() {
		return PROVIDER_ID;
	}
}



@RequiredArgsConstructor
public class TestResourceProvider implements RealmResourceProvider {

	private final KeycloakSession session;

	@Override
	public Object getResource() {
		return this;
	}

	@Override
	public void close() {
	}

	@GET
	@Path("test")
	@Produces(MediaType.APPLICATION_JSON)
	public Response helloAnonymous() {
		return Response.ok(Map.of("test", session.getContext().getRealm().getName())).build();
	}

	
}

```
