### ISSUE TITLE
LDAP - GroupToGroup Mapper throws "ENTRY_EXISTS" Error

### ISSUE THREAD

**Issue by robson90** [keycloak/keycloak#29142]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Dear Keycloak Team, 

Here is the setup of one of our Customers:
![Bildschirmfoto 2024-04-29 um 12 12 51](https://github.com/keycloak/keycloak/assets/39960884/156b65f9-3226-4910-973e-9aaff9dfc6b8)

Description:
As you can see, they have 2 Realms. Realm A and Realm B. Realm B is connected to a LDAPStore. Where the users are synced to. 

When a Users tries to log in, he is federated to Realm A where he authinticates. An Attribute Mapper puts in an Attribute. On Realm B that Attribute is taken to set a specific group. The Mode of that group Mapper is "FORCE". So it is updated everytime. After that happens, that join into the respective group is propagated towards LDAP. Where a group-to-group Mapper is implemented. So the group membership is persistet in LDAP.

When a User logs in for the first time, everything is fine. It is working as expected.

When a User tries to Log in for the second Time, it is working until the group-to-group mapper for the LDAP is considered. Because the group Mapper at Realm B is in mode "FORCE" it "rejoins" the same group. Then the LDAPIdentityStore tries to set the respective group to that User and fails.

Error:
```
2024-04-24 12:53:52,713 ERROR
[org.keycloak.broker.oidc.AbstractAuth2IdentityProvider] (executor-thread-2) Failed to make identity provider oauth callback: org. keycloak models .Mode
tribute for DN [CN=<SOME_CN>,OU=keycloak-groups, OU=User-INT,DC=test,DC=<SOME_DC> ,DC=de]
at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.addMemberToGroup(LDAPIdentityStore.java: 121)
at org.keycloak.storage. ldap.LDAPUtils.addMember(LDAPUtils.java:234)
at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.addGroupMappingInLDAP(GroupLDAPStorageMapper.java: 613)
at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper$LDAPGroupMappingsUserDelegate.joinGroup(GroupLDAPStorageMapper.java: 718)
at org.keycloak.models.utils.UserModelDelegate. joinGroup (UserModelDelegate. java:239)
at org.keycloak.broker.oidc.mappers.AbstractClaimToGroupMapper.updateBrokeredUser(AbstractClaimToGroupMapper-java: 66)
at org.keycloak.broker.provider.IdentityProviderMapperSyncModeDelegate.delegateUpdateBrokeredUser (IdentityProviderMapperSyncModeDelegate.java: 25)
at org.keycloak.services.resources.IdentityBrokerService.lambda$updateFederatedIdentity$2(IdentityBrokerService.java: 1009)
at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
at org.keycloak.services.resources.IdentityBrokerService.updateFederatedIdentity(IdentityBrokerService.java:1006)
at org.keycloak.services.resources.IdentityBrokerService.authenticated(IdentityBrokerService.java:612)
at org.keycloak.broker.oidc.AbstractAuth2IdentityProvider$Endpoint.authResponse(Abstract0Auth2IdentityProvider.java:541)
at
org.keycloak.broker.oidc.AbstractAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_fef2d69ce31937f365a37fb3083f9247bc4c56d2. invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java: 29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext. invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
at org-jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
at org-jboss. threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor-java:2513)
at org-jboss.threads. EnhancedQueueExecutor$ThreadBody. run (EnhancedQueueExecutor.java: 1538)
at org-jboss.threads.DelegatingRunnable.run (DelegatingRunnable-java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java: 29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java: 840)
Caused by: javax.naming-NameAlreadyBoundException: [LDAP: error code 68 - 00000562: UpdErr: DSID-031A11DA, problem 6005 (ENTRY_EXISTS), data 0
]; remaining name
'CN=<SOME_CN>OU=keycloak-groups,OU=User-INT,DC=test,DC=<SOME_DC> ,DC=de'
at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3255)
at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3206)
at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2997)
at java.naming/com.sun.jndi.ldap.LdapCtx.C_modifyAttributes(LdapCtx.java:1504)
at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_modifyAttributes(ComponentDirContext.java:277)
at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java: 192)
at java.naming/javax.naming.directory.InitialDirContext.modifyAttributes(InitialDirContext.java:201)
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The LDAPIdentityStore accepts that the User is already in that group.

### Actual behavior

The LDAPIdentityStore takes the Excetions that is thrown from Error Code 68 
maps to -> `NameAlreadyBoundException` by 
`om.sun.jndi.ldap.LDAPTCtx`:3255

LDAPIdentityStore gets that Exception and throws another Exception.
`org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore`:113 `addMemberToGroup()`

### How to Reproduce?

Please take a look at the Picture in the description for the Setup. I dont think it is necessary to have 2 Realms, the error should always come up, if a User is "rejoined" to a group where he already is member of.

### Anything else?

Unfortunately I was not able to get the Integration Tests running myself. So I did not succeed in writing a Test for that scenario. I was able to determine the Code Line where I would implement the change.
`org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore`:120
Instead of only catching `AttributeInUseException` I assume it could be good to catch the `NameAlreadyBoundException`
See: https://github.com/keycloak/keycloak/compare/main...robson90:keycloak:fix-LDAPIdentityStore
I did ran the Github Actions and there was no error. If the change is accepted Iam happy to create a real PR toward this project.

If there are any question, do not hesitate.

**Comment by robson90** [comment]
the main Branch is synced to my fork and it seems, that it is not fixed.

**Comment by sguilhen** [comment]
@robson90 Thanks for the report. I think your proposed fix is fine for this case - please go ahead and open a PR.

**Comment by robson90** [comment]
Hey @sguilhen , as proposed here my PR: https://github.com/keycloak/keycloak/pull/29217

Thanks for the fast response on this Issue. Much appreciated 👍

**Comment by sguilhen** [comment]
Hi @robson90 , thanks for raising the PR. Just a question out of curiosity: are you running into this error with MSAD? Or are you using some other LDAP  vendor?

**Comment by robson90** [comment]
@sguilhen Im very sorry for the late reply. They are using Microsot´s Active Directory LDAPv3
