### ISSUE TITLE
Upgraded docker to 24, now unable to browse "authentication" page in one of my realms.

### ISSUE THREAD

**Issue by dsputnikk** [keycloak/keycloak#29287]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have 2 realms additional realms (master, Realm A and Realm B)

Everything working on 23.x as expected.

I then upgrade my docker file to image: keycloak/keycloak:24.0 (from 23.0).

master and Realm A work fine.

Realm B - mostly works fine but when I visit the "Authentication" page I get "Network response was not OK, Press here to refresh and continue"

Meanwhile in console I get:

```
2024-05-05 20:49:45,933 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-15) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticationFlowModel.getAlias()" because "f" is null
keycloak_1                          |   at org.keycloak.admin.ui.rest.model.AuthenticationMapper.lambda$convertToModel$1(AuthenticationMapper.java:46)
keycloak_1                          |   at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
keycloak_1                          |   at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
keycloak_1                          |   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
keycloak_1                          |   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak_1                          |   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
keycloak_1                          |   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak_1                          |   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
keycloak_1                          |   at org.keycloak.admin.ui.rest.model.AuthenticationMapper.convertToModel(AuthenticationMapper.java:46)
keycloak_1                          |   at org.keycloak.admin.ui.rest.AuthenticationManagementResource.lambda$listIdentityProviders$1(AuthenticationManagementResource.java:58)
keycloak_1                          |   at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
keycloak_1                          |   at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak_1                          |   at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
keycloak_1                          |   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
keycloak_1                          |   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak_1                          |   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
keycloak_1                          |   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak_1                          |   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
keycloak_1                          |   at org.keycloak.admin.ui.rest.AuthenticationManagementResource.listIdentityProviders(AuthenticationManagementResource.java:59)
keycloak_1                          |   at org.keycloak.admin.ui.rest.AuthenticationManagementResource$quarkusrestinvoker$listIdentityProviders_da866ba3c00c15b6bcfefe4cfabdb4f2f2dbe255.invoke(Unknown Source)
keycloak_1                          |   at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak_1                          |   at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak_1                          |   at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak_1                          |   at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak_1                          |   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak_1                          |   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak_1                          |   at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak_1                          |   at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak_1                          |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak_1                          |   at java.base/java.lang.Thread.run(Thread.java:840)
```

If I roll back to 23.0 in docker-compose - it starts working fine.

### Version

24

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect to be able to browse and configure the Authentication settings for Realm B, just like with Realm A or master

### Actual behavior

Realm B's Authentication settings are unavailable to me.

### How to Reproduce?

1) Have two realms additional realms configured?
2) Upgrade docker to 24
3) attempt to browse Realm B's Authentication settings
4) Error..

**Comment by mposolda** [comment]
duplicates #23980

This was already fixed in Keycloak 24.0.2 release. Please update to latest version of Keycloak 24 release and you should be good.
