### ISSUE TITLE
realm_settings_user_profile_enabled fails randomly

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#29507]
realm_settings_user_profile_enabled fails randomly.

https://github.com/keycloak/keycloak/actions/runs/9075500150/job/24936390676 failed with
```
  1) User profile tabs
       Attribute groups sub tab tests
         Deletes an attributes group:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `.pf-v5-c-menu__content`, but never found it.
      at ListingPage.clickMenuDelete (webpack://admin-ui/./cypress/support/pages/admin-ui/ListingPage.ts:170:0)
      at ListingPage.deleteItem (webpack://admin-ui/./cypress/support/pages/admin-ui/ListingPage.ts:221:0)
      at Context.eval (webpack://admin-ui/./cypress/e2e/realm_settings_user_profile_enabled.spec.ts:114:0)
```
The test specs were run in this order:
```
1  cypress/e2e/user_fed_ldap_hardcoded_mapper_test.spec.ts
2  cypress/e2e/client_scopes_test.spec.ts                 
3  cypress/e2e/realm_settings_general_tab_test.spec.ts    
4  cypress/e2e/realm_settings_client_policies_test.spec.ts
5  cypress/e2e/realm_user_registration.spec.ts            
6  cypress/e2e/realm_settings_client_profiles_test.spec.ts
7  cypress/e2e/realm_settings_user_profile_enabled.spec.ts
```

**Comment by stianst** [comment]
@hmlnarik please set a priority - see https://github.com/keycloak/keycloak/blob/main/docs/bug-triage.md

**Comment by hmlnarik** [comment]
https://github.com/keycloak/keycloak/actions/runs/9156839064/job/25172142302?pr=29691

Order of specs:
```
1  cypress/e2e/clients_test.spec.ts                       
2  cypress/e2e/identity_providers_test.spec.ts            
3  cypress/e2e/realm_settings_user_profile_enabled.spec.ts
4  cypress/e2e/client_scopes_test.spec.ts                 
5  cypress/e2e/partial_export_test.spec.ts                
6  cypress/e2e/client_registration_policies.spec.ts       
7  cypress/e2e/sessions_test.spec.ts                      
```

**Comment by hmlnarik** [comment]
https://github.com/keycloak/keycloak/actions/runs/9166745493/job/25222542670?pr=29713

```
1  cypress/e2e/users_test.spec.ts                         
2  cypress/e2e/realm_roles_test.spec.ts                   
3  cypress/e2e/identity_providers_oidc_test.spec.ts       
4  cypress/e2e/clients_saml_advanced.spec.ts              
5  cypress/e2e/realm_settings_events_test.spec.ts         
6  cypress/e2e/realm_settings_user_profile_enabled.spec.ts
7  cypress/e2e/partial_import_test.spec.ts                
```
