### ISSUE TITLE
Conditional flow fails when OTP and Webauthn are on the same flow

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#29515]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

I am trying to create a flow where the user is offered the option to have a second factor either by using OTP or Webauthn.

My flow looks like this:

<img width="1462" alt="Screenshot 2024-05-14 at 14 44 49" src="https://github.com/keycloak/keycloak/assets/6791923/eb12160c-2ee4-41fd-bc97-babc91d3c303">

However, this leads to this after the user enters the password: 

<img width="538" alt="Screenshot 2024-05-14 at 14 45 13" src="https://github.com/keycloak/keycloak/assets/6791923/56647132-69bf-415d-b238-621959313ba0">

When I remove Webauthn, it works fine with OTP. When I remove OTP, it works fine with Webauthn. 
It should be possible to have both showing up so the user chooses, shouldn't it? I remember having it this way before.

### Version

24.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

The user should see the two authenticators as a list so that he would choose which 2FA to use.

### Actual behavior

The user bypasses the list and get an error regarding wrong password.

### How to Reproduce?

Add webauthn authenticator and OTP form as alternative on a required subflow after the Conditional OTP

**Comment by oculos** [comment]
This is what the logs show:

```
024-05-14 14:46:02,936 WARN  [org.keycloak.events] (executor-thread-106) type="LOGIN_ERROR", realmId="b604ebf8-5e7d-474f-b8c4-5c612aeeb612", clientId="account-console", userId="null", ipAddress="12.20.1.27", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="https://mydomain.no/realms/webguest/account/", code_id="76bcffs9-0640-4f57-a2f7-5bdf176c7710", username="francis@myemail.eu"
2024-05-14 14:46:14,674 WARN  [org.keycloak.services] (executor-thread-107) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:993)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:364)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:335)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:327)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:392)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by rmartinc** [comment]
I don't understand what you are trying to do here. If you want to allow alternative login between otp and webauthn but only if configured, you should configure it like this:

![Screenshot from 2024-05-16 18-56-09](https://github.com/keycloak/keycloak/assets/26901232/cf133319-1263-4606-8f51-856155de9307)

The sub-flow is conditional  (it uses a condition), you need the condition defined inside the flow as required and then the other two authenticators are set as alternative (one or the other). Your configuration now requires one or other auth no matter if the user has them configured or not, if the user has none configured the login will fail as you are showing in the image.

**Comment by oculos** [comment]
Thanks @rmartinc . I made a mistake and didn't set the "conditional" on the subflow. 
When I put OTP Form as required, it forces the user to configure OTP. 
What I am trying to accomplish is to allow the user to choose to configure (or use) OTP or Webauthn.

**Comment by rmartinc** [comment]
Yes, if the authenticator is set to requires it forces the configuration. You can also configure the requires action as default (for example configure OTP) to make the user to configure OTP in the first interaction with keycloak.
Closing the issue now. Regards!

**Comment by oculos** [comment]
But is it possible to require one or the other? I manage to require OTP or I manage to require Webauthn, but ai don’t know if it is possible for the use to configure at least one of them. __Francis Augusto ***@***.***: +47 45 17 14 91Oslo, NorwaySent from a mobile device / Enviado a partir de dispositivo móvelOn 17 May 2024, at 08:56, Ricardo Martin ***@***.***> wrote:﻿
Yes, if the authenticator is set to required it forces the configuration. You can also configure the requires action as default (for example configure OTP) to make the user to configure OTP in the first interaction with keycloak.
Closing the issue now. Regards!
