### ISSUE TITLE
The EmailEventListenerProvider throws an exception on brute force lockout events

### ISSUE THREAD

**Issue by stustison** [keycloak/keycloak#29542]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Configuring both the Brute Force Lockout and Email Event Listener in order to send emails for lockout events, will result in an exception being thrown:

```
ERROR [org.keycloak.services] (Brute Force Protector) KC-SERVICES0052: Failed processing type: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.vertx.http.runtime.CurrentVertxRequest, id=0_6n6EmChCiiDdd8HelptG_A0AE]
- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
at io.quarkus.arc.impl.ClientProxies.notActive(ClientProxies.java:70)
at io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:30)
at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.arc$delegate(Unknown Source)
at io.quarkus.vertx.http.runtime.CurrentVertxRequest_ClientProxy.getCurrent(Unknown Source)
at java.base/java.util.Optional.map(Optional.java:260)
at org.keycloak.quarkus.runtime.integration.resteasy.ResteasyVertxProvider.getContextData(ResteasyVertxProvider.java:44)
at org.keycloak.common.util.Resteasy.getContextData(Resteasy.java:62)
at org.keycloak.services.DefaultKeycloakContext.getContextObject(DefaultKeycloakContext.java:101)
at org.keycloak.services.DefaultKeycloakContext.getHttpRequest(DefaultKeycloakContext.java:149)
at org.keycloak.events.email.EmailEventListenerProvider.sendEmail(EmailEventListenerProvider.java:74)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
at org.keycloak.services.managers.DefaultBruteForceProtector.run(DefaultBruteForceProtector.java:302)
at java.base/java.lang.Thread.run(Thread.java:840)
```

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Lockout event emails are sent when lockout events occur and the email event listener is configured to send them.

### Actual behavior

Exception is thrown.

### How to Reproduce?

Configure the Brute Force Detection
Configure the Email Event Listener (`spi-events-listener-email-include-events=user_disabled_by_permanent_lockout` in keycloak.conf)
Configure email settings to point to a valid server
Force a user to be locked out by failing login attempts

**Comment by rmartinc** [comment]
Yes, this is a known issue in the brute force. The root reason is the brute force is executed off-thread and then the resteasy information is not associated to the request. Currently the only way of workaround this is extending the brute force like commented in #23162. I'm taking this one but this is not easy, setting to version 26.0 for teh moment.
