### ISSUE TITLE
Cypress failing on video recording

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak#29554]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

[Admin UI error log](https://github.com/keycloak/keycloak/actions/runs/9087911360/job/24976678776)

Cypress failing at the start of the tests due to some problem with the recording

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Warning: We failed capturing this video.

This error will not affect or change the exit code.

Error: Insufficient frames captured to create video.
    at ChildProcess.<anonymous> (<embedded>:2684:16306)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
An error was thrown in your plugins file while executing the handler for the after:spec event.

The error we received was:

Error: ENOENT: no such file or directory, unlink '/home/runner/work/keycloak/keycloak/js/apps/admin-ui/cypress/videos/realm_user_registration.spec.ts.mp4'
    at Object.unlink (node:internal/fs/sync:93:18)
    at Object.unlinkSync (node:fs:1853:17)
    at afterSpecRemoveSuccessfulVideos (file:///home/runner/work/keycloak/keycloak/js/apps/admin-ui/cypress.config.js:38:16)
    at Object.handler (file:///home/runner/work/keycloak/keycloak/js/apps/admin-ui/cypress.config.js:52:15)
    at invoke (/home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:185:18)
    at /home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:59:14
    at tryCatcher (/home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.attempt.Promise.try (/home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:58:23)
    at RunPlugins.execute (/home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:164:21)
    at EventEmitter.<anonymous> (/home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:56:12)
    at EventEmitter.emit (node:events:514:28)
    at process.<anonymous> (/home/runner/.cache/Cypress/13.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:[83](https://github.com/keycloak/keycloak/actions/runs/9087911360/job/24976678776#step:11:84):21)
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Pass

### Actual behavior

Fail

### How to Reproduce?

Run test recording video

**Comment by jonkoops** [comment]
@hmlnarik since you recently updated the Cypress config in relation to this, do you believe this might have something to do with those changes?

**Comment by hmlnarik** [comment]
@jonkoops Yes, the failure shows that the `after:spec` handler is actually called as it should. Firefox is unable to record videos, so the `unlinkSync` fails. It should now be fixed with #29560
