### ISSUE TITLE
Passkeys conditional UI authenticator: NullPointerException when filling some random username

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#29585]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

- Enable passkeys preview feature

- Configure Passkeys conditional UI authenticator according to latest documentation: https://github.com/keycloak/keycloak/blob/main/docs/documentation/server_admin/topics/authentication/passkeys.adoc#passkey-authentication-with-conditional-ui

- Try to authenticate as user to the passkeys realm and make sure the screen with `PasskeysConditionalUIAuthenticator` is shown
 
- Fill some random username like "abc" of some non-existing user and press enter

- There is screen "Unexpected error when handling authentication request to identity provider." and the exception in server.log:

```
2024-05-16 08:06:22,618 WARN  [org.keycloak.services] (executor-thread-44) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "String.replace(char, char)" because "base64Url" is null
	at org.keycloak.common.util.Base64Url.encodeBase64UrlToBase64(Base64Url.java:58)
	at org.keycloak.common.util.Base64Url.decode(Base64Url.java:32)
	at org.keycloak.authentication.authenticators.browser.WebAuthnAuthenticator.action(WebAuthnAuthenticator.java:151)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:151)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1029)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:368)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:339)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:331)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:397)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)

```

### Version

latest main from 2024-05-16

### Regression

- [ ] The issue is a regression

### Expected behavior

Some more friendly error like `Invalid username` and no NullPointerException in the log (maybe just single line warning or something like that)

### Actual behavior

Unfriendly page with unexpected error and NullPointerException in the server.log

### How to Reproduce?

See above

**Comment by mposolda** [comment]
Ideally, the passkeys username form should be able to handle all these situations gracefully:

1) Username of non-existing user is manually filled
2) Username of existing user is manually filled, but this user does not have passkeys credential

It would be very nice if the authenticator is configured as ALTERNATIVE together with other authenticators (like for example password authenticator similarly like this):
```
PasskeysConditionalUIAuthenticator  ALTERNATIVE
PasswordForm                        ALTERNATIVE
```
Then the scenario is like:
- When user authenticates with passkey successfully, the PasskeysConditionalUIAuthenticator is marked as "success" and hence no need to provide password
- When user fills username of existing user without passkey (point 2 from above), the user is set in the authenticationContext, but user is not considered authenticated, so he would be switched to password form where he would need to provide the password

This would be ideal experience IMO, but not sure if it is feasible to easily do it with current authentication SPI (maybe some changes in the SPI may be needed).

**Comment by embesozzi** [comment]
The main purpose of using WebAuthn Conditional UI is to assist in the transition from password-based authentication to passwordless (passkeys). Therefore, I agree to use passwords as a fallback (alternative)

https://github.com/embesozzi/keycloak-webauthn-conditional-mediation/blob/main/src/main/java/com/twogenidentity/keycloak/authenticator/WebAuthnConditionalMediationAuthenticator.java#L39

This is how I ended up implementing it [here](https://github.com/embesozzi/keycloak-workshop-stepup-mfa-biometrics).

**Comment by thomasdarimont** [comment]
I just stumpled upon this issue and submitted a fix: https://github.com/keycloak/keycloak/pull/37425 inspired by @embesozzi's implementation.
