### ISSUE TITLE
Passkeys conditional UI authenticator: NullPointerException when authenticated as removed user

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#29586]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

- Enable passkeys preview feature

- Configure Passkeys conditional UI authenticator according to latest documentation: https://github.com/keycloak/keycloak/blob/main/docs/documentation/server_admin/topics/authentication/passkeys.adoc#passkey-authentication-with-conditional-ui

- Open authentication for the passkeys realm and click "Register" to register new user

- Register user `john` and create passkeys credential for him (should be done during authentication automatically when registration is configured as specified in the docs). Then logout

- In another window, login as `admin` to the `master` realm. Then go to the `passkeys` realm and remove user `john` from this realm

- Go back to the first window and refresh login here to show the page with `PasskeysConditionalUIAuthenticator`

- Authenticate with passkeys for user `john` . My phone (or other authenticator) gives me hint to authenticate as that user as passkeys credential is still saved for him

- After passkeys flow is finished, there is page displayed to the user `Unexpected error when handling authentication request to identity provider.` and the exception in the server.log:

```
2024-05-16 09:13:26,864 WARN  [org.keycloak.services] (executor-thread-45) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.UserModel.credentialManager()" because "user" is null
	at org.keycloak.authentication.authenticators.browser.WebAuthnAuthenticator.action(WebAuthnAuthenticator.java:217)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:151)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1029)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:368)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:339)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:331)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:397)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)
```

### Version

latest main from 2024-05-16

### Regression

- [ ] The issue is a regression

### Expected behavior

Some more friendly error like `User does not exists` and no NullPointerException in the log (maybe just single line warning or something like that)

### Actual behavior

Unfriendly page with unexpected error and NullPointerException in the server.log

### How to Reproduce?

See above

**Comment by thomasdarimont** [comment]
I sent small bugfix that checks if the user exists after a lookup by webauthn userHandle (userId) #37427.
