### ISSUE TITLE
Updating a client protocol mappers through Admi CLI (kcadm) resets the client service account roles

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#29878]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

I tried to update the protocol mappers of a client using the Admin CLI like this : 

`kcadm update clients/<client_id> -f client-protocol-mappers.json`

With the json file containing the id of the client and the updated protocol mappers. Here is a simple example : 
```
{
  "id" : "1c8c3cb0-4496-4ef3-bf14-93a40c67dc6f",
  "protocolMappers" : [ {
    "id" : "25c9005f-4348-4a13-8c39-4dd5bb3cb30d",
    "name" : "given name",
    "protocol" : "openid-connect",
    "protocolMapper" : "oidc-usermodel-property-mapper",
    "consentRequired" : false,
    "config" : {
      "userinfo.token.claim" : "true",
      "user.attribute" : "firstName",
      "id.token.claim" : "false",
      "access.token.claim" : "true",
      "claim.name" : "given_name",
      "jsonType.label" : "String"
    }
  }, {
    "id" : "d3a75456-fc69-432f-9a80-5825703ff84b",
    "name" : "family name",
    "protocol" : "openid-connect",
    "protocolMapper" : "oidc-usermodel-property-mapper",
    "consentRequired" : false,
    "config" : {
      "userinfo.token.claim" : "true",
      "user.attribute" : "lastName",
      "id.token.claim" : "false",
      "access.token.claim" : "true",
      "claim.name" : "family_name",
      "jsonType.label" : "String"
    }
  } ]
}
```

Everything works fine and the protocol mappers are correctly updated for my client.
All other client configuration values still have correctly the same values as before the Admin CLI command was executed (Client name, description, redirect URIs, theme, keys, credentials, etc...), except the configuration of the service account roles which got reset to the default values.

Before : 
![image](https://github.com/keycloak/keycloak/assets/11772429/e8f16c1d-0564-40ac-866b-b0fc6ecb9eca)

After updating the protocol mappers : 
![image](https://github.com/keycloak/keycloak/assets/11772429/b0145bc4-fc80-4040-a0f6-95c191931f94)

As you can see no more roles (except the default 'default-roles-<realm>' role) are associated to the service account.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Only the protocol mappers of the client should be updated

### Actual behavior

Protocol mappers of the client are correctly updated but the service account roles are reset

### How to Reproduce?

Create a client in the management console.
Associate roles to the service account of the client (through the 'Service account roles' tab)
Execute kcadm update clients/<client_id> -f client-protocol-mappers.json
Refresh the page showing the roles associated to the service account of the client -> Roles are no more associated.

**Comment by omasseau** [comment]
I noticed this about the service-account : 

If after updating the client (here named 'gateway') protocol mappers, I do something on the service-account, for example associate a new role to it, like this : 
`kcadm add-roles --uusername service-account-gateway --rolename user`

Then it returns this error : 
`User not found for username: service-account-gateway`

If I then go in the 'Service accounts roles' tab of the client in the management console and just after retry the script : 
`kcadm add-roles --uusername service-account-gateway --rolename user`

Then it works.

So it seems that updating the client protocols mappers, actually also deletes the service-account, which is automatically recreated on the fly when accessing the 'Service accounts roles' in the management console

**Comment by shawkins** [comment]
@omasseau can you try kcadm update with the --merge option? When supplying a file the default is to overwrite.

**Comment by shawkins** [comment]
~priority-low

**Comment by omasseau** [comment]
> @omasseau can you try kcadm update with the --merge option? When supplying a file the default is to overwrite.

@shawkins When trying with the --merge option : 
`kcadm update --merge clients/<client_id> -f client-protocol-mappers.json`
-->
I get this error :
`null [RESTEASY003065: Cannot consume content type]`

**Comment by omasseau** [comment]
> @omasseau can you provide a full stacktrace? Check the server log, and/or include -x with the kcadm command.

Here is the generated stacktrace when adding the -x option : 

`kcadm update --merge clients/<client_id> -f client-protocol-mappers.json -x`

```
null [RESTEASY003065: Cannot consume content type]
org.keycloak.client.admin.cli.util.HttpResponseException: null [RESTEASY003065: Cannot consume content type]
        at org.keycloak.client.admin.cli.util.HeadersBodyStatus.checkSuccess(HeadersBodyStatus.java:61)
        at org.keycloak.client.admin.cli.util.HttpUtil.checkSuccess(HttpUtil.java:353)
        at org.keycloak.client.admin.cli.commands.AbstractRequestCmd.process(AbstractRequestCmd.java:363)
        at org.keycloak.client.admin.cli.commands.AbstractRequestCmd.execute(AbstractRequestCmd.java:126)
        at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:63)
        at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:48)
        at org.keycloak.client.admin.cli.aesh.AeshConsoleCallbackImpl.execute(AeshConsoleCallbackImpl.java:54)
        at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: {"error":"RESTEASY003065: Cannot consume content type"}
        ... 11 more
```

**Comment by shawkins** [comment]
I didn't see the content type error locally, but that may be coming from a proxy. The root issue I believe is that the content is null for this type of merge - to be addressed by #30539

**Comment by talbert83** [comment]
I have the same issue and --merge didn't help either. Actually I was updating the client using the -b and -s options and as the OP wrote everything else was preserved, only the service account is reset, so I don't think this is the intended behaviour.
The documentation says

> By default, the update command performs a get and then merges the new attribute values with existing values.

and --merge is not mentioned anywhere.

**Comment by talbert83** [comment]
@omasseau, have you found a way around this without manual intervention? As you said, updating the client and then re-assigning the roles in the same script is not an option, because the user is not found.

**Comment by omasseau** [comment]
@talbert83 A good to know 🙂. I will try.
In the meantime I created a small command line java program which uses the Keycloak java admin api to resolve my problem. It is not as flexible as a simple cli script (need to compile and package the executable jar each time I want add new things to update) but it works (and you can do maybe more complex stuffs is heavy logic is needed)
