### ISSUE TITLE
LDAP Group Mapper throws exception when admin event logging is enabled

### ISSUE THREAD

**Issue by cpuschma** [keycloak/keycloak#29947]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When admin events logging is enabled in a realm, the LDAP Group Mapper fails with an exception trying to create log the admin event

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Any groups matching the criteria are imported

### Actual behavior

The process semi-fails. Some groups are imported, but the operation fails in the Admin UI and prints a stacktrace in the console

### How to Reproduce?

1. Create a realm (or use the default one)
2. Enable "Save events" under Realm settings -> Events -> Admin event settings
3. Create a LDAP federation under User federation
4. Open the newly created LDAP federation, go to mappers and create a new mapper of type "group-ldap-mapper"
5. Open the new mapper, click on action in the top right corner and click "Sync LDAP groups to Keycloak"

### Anything else?

```
May 28 23:35:48 X000VV31 kc.sh[579622]: 2024-05-28 23:35:48,181 INFO  [org.keycloak.services] (executor-thread-795) KC-SERVICES0087: Syncing data for mapper 'group-ldap-mapper' of type 'group-ldap-mapper'. Direction: fedToKeycloak
May 28 23:35:49 X000VV31 kc.sh[579622]: 2024-05-28 23:35:49,764 WARN  [io.agroal.pool] (executor-thread-795) Datasource '<default>': Closing open connection(s) prior to commit
May 28 23:35:49 X000VV31 kc.sh[579622]: 2024-05-28 23:35:49,765 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-795) SQL Error: 0, SQLState: null
May 28 23:35:49 X000VV31 kc.sh[579622]: 2024-05-28 23:35:49,765 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-795) Connection is closed
May 28 23:35:49 X000VV31 kc.sh[579622]: 2024-05-28 23:35:49,766 WARN  [com.arjuna.ats.arjuna] (executor-thread-795) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff0a2dc5ac:b65b:66228c9e:303227, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@2b13b03f >: org.hibernate.exception.GenericJDBCException: could not prepare statement [Connection is closed] [insert into ADMIN_EVENT_ENTITY (AUTH_CLIENT_ID,IP_ADDRESS,AUTH_REALM_ID,AUTH_USER_ID,ERROR,OPERATION_TYPE,REALM_ID,REPRESENTATION,RESOURCE_PATH,RESOURCE_TYPE,ADMIN_EVENT_TIME,ID) values (?,?,?,?,?,?,?,?,?,?,?,?)]
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.MutationStatementPreparerImpl$StatementPreparationTemplate.prepareStatement(MutationStatementPreparerImpl.java:117)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.MutationStatementPreparerImpl.prepareStatement(MutationStatementPreparerImpl.java:38)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.ModelMutationHelper.standardStatementPreparation(ModelMutationHelper.java:145)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.ModelMutationHelper.lambda$standardPreparation$0(ModelMutationHelper.java:118)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementDetailsStandard.resolveStatement(PreparedStatementDetailsStandard.java:87)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.JdbcValueBindingsImpl.lambda$beforeStatement$0(JdbcValueBindingsImpl.java:88)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.spi.BindingGroup.forEachBinding(BindingGroup.java:51)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.JdbcValueBindingsImpl.beforeStatement(JdbcValueBindingsImpl.java:85)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:104)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:40)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:52)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:175)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:113)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2873)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:632)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:499)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:363)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1403)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:484)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2319)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1976)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:52)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:351)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:69)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:138)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:55)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.closeSession(CloseSessionHandler.java:69)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.filter(CloseSessionHandler.java:65)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.lang.Thread.run(Thread.java:840)
May 28 23:35:49 X000VV31 kc.sh[579622]: Caused by: java.sql.SQLException: Connection is closed
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.agroal.pool.wrapper.ConnectionWrapper.lambda$static$0(ConnectionWrapper.java:51)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at jdk.proxy3/jdk.proxy3.$Proxy61.prepareStatement(Unknown Source)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:647)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.MutationStatementPreparerImpl$1.doPrepare(MutationStatementPreparerImpl.java:48)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.MutationStatementPreparerImpl$StatementPreparationTemplate.prepareStatement(MutationStatementPreparerImpl.java:106)
May 28 23:35:49 X000VV31 kc.sh[579622]:         ... 52 more
May 28 23:35:49 X000VV31 kc.sh[579622]: 2024-05-28 23:35:49,770 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-795) Uncaught server error: org.keycloak.models.ModelException: java.sql.SQLException: Connection is closed
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.connections.jpa.JpaExceptionConverter.convert(JpaExceptionConverter.java:31)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.transaction.JtaTransactionWrapper.lambda$handleException$0(JtaTransactionWrapper.java:65)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.transaction.JtaTransactionWrapper.handleException(JtaTransactionWrapper.java:67)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:92)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:55)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.closeSession(CloseSessionHandler.java:69)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.filter(CloseSessionHandler.java:65)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.lang.Thread.run(Thread.java:840)
May 28 23:35:49 X000VV31 kc.sh[579622]: Caused by: java.sql.SQLException: Connection is closed
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.agroal.pool.wrapper.ConnectionWrapper.lambda$static$0(ConnectionWrapper.java:51)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at jdk.proxy3/jdk.proxy3.$Proxy61.prepareStatement(Unknown Source)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:647)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.MutationStatementPreparerImpl$1.doPrepare(MutationStatementPreparerImpl.java:48)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.MutationStatementPreparerImpl$StatementPreparationTemplate.prepareStatement(MutationStatementPreparerImpl.java:106)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.MutationStatementPreparerImpl.prepareStatement(MutationStatementPreparerImpl.java:38)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.ModelMutationHelper.standardStatementPreparation(ModelMutationHelper.java:145)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.ModelMutationHelper.lambda$standardPreparation$0(ModelMutationHelper.java:118)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementDetailsStandard.resolveStatement(PreparedStatementDetailsStandard.java:87)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.JdbcValueBindingsImpl.lambda$beforeStatement$0(JdbcValueBindingsImpl.java:88)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.spi.BindingGroup.forEachBinding(BindingGroup.java:51)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.JdbcValueBindingsImpl.beforeStatement(JdbcValueBindingsImpl.java:85)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:104)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:40)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:52)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:175)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:113)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2873)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:632)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:499)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:363)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1403)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:484)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2319)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1976)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:52)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:351)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:69)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:138)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
May 28 23:35:49 X000VV31 kc.sh[579622]:         at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
May 28 23:35:49 X000VV31 kc.sh[579622]:         ... 16 more
```

**Comment by raff897** [comment]
it seems that can be linked to this issue (due to stack trace) :  
#29784

**Comment by raff897** [comment]
@cpuschma do you set batch size in LDAP provider?

**Comment by sguilhen** [comment]
@cpuschma I followed the steps on my keycloak (latest nightly) and I was unable to reproduce it - I can synchronize the users and the event is properly recorded. Can you share all your ldap and group mapper settings, just so I can ensure I'm using a similar setup?

**Comment by pedroigor** [comment]
I'm also not able to reproduce locally using nightly. Can you also check nightly to see if it works?

**Comment by pedroigor** [comment]
Also not able to reproduce. Perhaps this one https://github.com/keycloak/keycloak/issues/29784 should help but not sure if I understood correctly the discussions in there.

**Comment by wzrdtales** [comment]
seeing the same error. it happens when you click the synchronize to keycloak button on the group mapper page while the admin events are activated

**Comment by wzrdtales** [comment]
i did, latest version. just enable the group mapper on msad and check the table. that is reproduction.

**Comment by wzrdtales** [comment]
MSAD, bind type simple, edit mode writeable, search scope subtree, import users, sync registrations, period changed users sync, cache policy default

group mapper

![image](https://github.com/keycloak/keycloak/assets/1786821/3b39e607-d058-4cd4-804a-99fcc4e18b69)
