### ISSUE TITLE
KC operator HA via having > 1 pod

### ISSUE THREAD

**Issue by aladdin-atypon** [keycloak/keycloak#30005]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Once KC operator is scaled to 2 to provide HA during k8s upgrade, keycloak instances can't get up, KC logs doesn't provide something valuable aboyt the reason why it has been shut down, but from one of the two operator logs:

```
keycloak-operator 2024-05-30 11:37:18,581 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-61) Trying to fetch existing Deployment from the API
keycloak-operator 2024-05-30 11:37:18,585 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-61) Found config secrets names: []
keycloak-operator 2024-05-30 11:37:18,597 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-61) Existing Deployment found, updating specs
keycloak-operator 2024-05-30 11:37:18,787 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-61) --- Reconciliation finished successfully
keycloak-operator 2024-05-30 11:37:18,795 ERROR [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-61) --- Error reconciling: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.100.0.1/apis/k8s.keycloak.org/v2alpha1/namespaces/dev0/keycloaks/rex-keycloak/status. Message: Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "rex-keycloak": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=k8s.keycloak.org, kind=keycloaks, name=rex-keycloak, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "rex-keycloak": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:684)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:664)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:615)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:558)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:521)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:345)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:325)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleUpdate(BaseOperation.java:649)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$1(HasMetadataOperation.java:195)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:200)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replaceStatus(HasMetadataOperation.java:146)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher$CustomResourceFacade.updateStatus(ReconciliationDispatcher.java:389)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.updateStatusGenerationAware(ReconciliationDispatcher.java:222)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:151)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:117)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:88)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:61)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:395)
keycloak-operator     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
keycloak-operator     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak-operator     at java.base/java.lang.Thread.run(Thread.java:829)
keycloak-operator 
keycloak-operator 2024-05-30 11:37:18,802 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-keycloakcontroller-61) Error during error status handling.: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.100.0.1/apis/k8s.keycloak.org/v2alpha1/namespaces/dev0/keycloaks/rex-keycloak/status. Message: Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "rex-keycloak": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=k8s.keycloak.org, kind=keycloaks, name=rex-keycloak, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "rex-keycloak": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:684)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:664)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:615)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:558)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:521)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:345)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:325)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleUpdate(BaseOperation.java:649)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$1(HasMetadataOperation.java:195)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:200)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replaceStatus(HasMetadataOperation.java:146)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher$CustomResourceFacade.updateStatus(ReconciliationDispatcher.java:389)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleErrorStatusHandler(ReconciliationDispatcher.java:195)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:119)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:88)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:61)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:395)
keycloak-operator     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
keycloak-operator     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak-operator     at java.base/java.lang.Thread.run(Thread.java:829)
keycloak-operator 
keycloak-operator 2024-05-30 11:37:18,804 ERROR [io.jav.ope.pro.eve.ReconciliationDispatcher] (ReconcilerExecutor-keycloakcontroller-61) Error during event processing ExecutionScope{ resource id: ResourceID{name='rex-keycloak', namespace='dev0'}, version: 488634504} failed.: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.100.0.1/apis/k8s.keycloak.org/v2alpha1/namespaces/dev0/keycloaks/rex-keycloak/status. Message: Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "rex-keycloak": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=k8s.keycloak.org, kind=keycloaks, name=rex-keycloak, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on keycloaks.k8s.keycloak.org "rex-keycloak": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:684)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:664)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:615)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:558)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:521)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:345)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleUpdate(OperationSupport.java:325)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleUpdate(BaseOperation.java:649)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$1(HasMetadataOperation.java:195)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:200)
keycloak-operator     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replaceStatus(HasMetadataOperation.java:146)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher$CustomResourceFacade.updateStatus(ReconciliationDispatcher.java:389)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.updateStatusGenerationAware(ReconciliationDispatcher.java:222)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:151)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:117)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:88)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:61)
keycloak-operator     at io.javaoperatorsdk.operator.processing.event.EventProcessor$ReconcilerExecutor.run(EventProcessor.java:395)
keycloak-operator     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
keycloak-operator     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak-operator     at java.base/java.lang.Thread.run(Thread.java:829)
keycloak-operator 
keycloak-operator 2024-05-30 11:37:18,805 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-60) --- Reconciling Keycloak: rex-keycloak in namespace: dev0
keycloak-operator 2024-05-30 11:37:18,809 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-60) Trying to fetch existing Deployment from the API
keycloak-operator 2024-05-30 11:37:18,814 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-60) Found config secrets names: []
keycloak-operator 2024-05-30 11:37:18,825 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-60) Existing Deployment found, updating specs
keycloak-operator 2024-05-30 11:37:18,953 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-60) --- Reconciliation finished successfully
keycloak-operator 2024-05-30 11:37:18,966 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-55) --- Reconciling Keycloak: rex-keycloak in namespace: dev0
keycloak-operator 2024-05-30 11:37:18,969 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-55) Trying to fetch existing Deployment from the API
keycloak-operator 2024-05-30 11:37:18,974 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-55) Found config secrets names: []
keycloak-operator 2024-05-30 11:37:18,984 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-55) Existing Deployment found, updating specs
keycloak-operator 2024-05-30 11:37:19,152 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-55) --- Reconciliation finished successfully
keycloak-operator 2024-05-30 11:37:19,165 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-40) --- Reconciling Keycloak: rex-keycloak in namespace: dev0
keycloak-operator 2024-05-30 11:37:19,169 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-40) Trying to fetch existing Deployment from the API
keycloak-operator 2024-05-30 11:37:19,172 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-40) Found config secrets names: []
keycloak-operator 2024-05-30 11:37:19,182 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-40) Existing Deployment found, updating specs
keycloak-operator 2024-05-30 11:37:19,308 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-40) --- Reconciliation finished successfully
keycloak-operator 2024-05-30 11:37:19,321 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-52) --- Reconciling Keycloak: rex-keycloak in namespace: dev0
keycloak-operator 2024-05-30 11:37:19,325 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-52) Trying to fetch existing Deployment from the API
keycloak-operator 2024-05-30 11:37:19,329 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-52) Found config secrets names: []
keycloak-operator 2024-05-30 11:37:19,339 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-52) Existing Deployment found, updating specs

```

### Version

21.1.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The keycloak pods should be up and running since the operators are deployed using deployment hence should be stateless.

### Actual behavior

The keycloak pods keep restarting.

### How to Reproduce?

Just scale the operator to two pods.

**Comment by shawkins** [comment]
Please try to reproduce on a later version. Later operators will log if a keycloak pod is unhealthy and why.

Otherwise if you want to further debug on version 21, you will need to get the pod logs from the keycloak pods and their yaml showing their status (could also be from kubectl describe pod).

~priority-low

**Comment by igor-sidorov** [comment]
Can keycloak-operator have multiple running pods in one namespace?

**Comment by shawkins** [comment]
@igor-sidorov newer versions of the operator support having multiple keycloak crs in the same namespace. All versions support having multiple instances per keycloak.

**Comment by igor-sidorov** [comment]
[keycloak-0-1717141917293750000.log](https://github.com/user-attachments/files/15510380/keycloak-0-1717141917293750000.log)
When we set deployment of keycloak-operator, not keycloak, to 2 replicas all keycloak pods start constantly terminating and start with attached log.

**Comment by shawkins** [comment]
@igor-sidorov @aladdin-atypon are you working on the same issue / project - if not @igor-sidorov you should move your thread to a separate issue.

In the log you provided:

```
{"timestamp":"2024-05-31T07:51:43.089Z","sequence":8480,"loggerClassName":"org.keycloak.services.ServicesLogger_$logger","loggerName":"org.keycloak.services","level":"ERROR","message":"KC-SERVICES0010: Failed to add user 'rexclient' to realm 'master': user with username exists","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2024-05-31T07:51:48.088Z","sequence":8481,"loggerClassName":"org.jboss.logging.Logger","loggerName":"com.wiley.rex.keycloak.resource.provider.KeyCloakUserApiProvider","level":"INFO","message":"Close is called","threadName":"Shutdown thread","threadId":24,"mdc":{},"ndc":"","hostName":"keycloak-0","processName":"QuarkusEntryPoint","processId":1}
```

What is adding the rexclient user? 

Please also include the pod yaml / description showing the status. Also check your kubernetes events - are the pods failing a health check?
