### ISSUE TITLE
Unable to Start keycloak-24.0.5 in DEV Mode With Openjdk 17.0.11

### ISSUE THREAD

**Issue by hahmad92** [keycloak/keycloak#30249]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I am trying to run keycloak-24.0.5 on windows 11 with Openjdk 17.0.11 using command bin\kc.bat start-dev. I get following exception on startup and than the process ends.  Below is the logs of Keycloak and my java version. Before this i was running Keycloak 21 and it was working fine. 

```
D:\keycloak-24.0.5>bin\kc.bat start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
2024-06-07 15:00:07,192 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index jakarta.jms.XAConnection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,192 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index jakarta.jms.XASession: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,192 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index jakarta.jms.XAConnectionFactory: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,202 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index io.mashona.logwriting.ArrayStore: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,212 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index org.apache.activemq.artemis.core.journal.RecordInfo: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,213 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index org.apache.activemq.artemis.core.journal.Journal: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,224 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index org.apache.tools.ant.Task: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,241 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index org.springframework.core.io.DefaultResourceLoader: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,241 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index org.springframework.core.io.ResourceLoader: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,251 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index org.springframework.core.io.Resource: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:07,281 WARN  [io.qua.dep.ind.IndexWrapper] (build-83) Failed to index jakarta.jms.Connection: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD for keycloak@6105f8a3
2024-06-07 15:00:10,453 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 6678ms
2024-06-07 15:00:12,693 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2024-06-07 15:00:14,463 WARN  [io.quarkus.agroal.runtime.DataSources] (JPA Startup Thread) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2024-06-07 15:00:15,054 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-06-07 15:00:15,104 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-06-07 15:00:19,545 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: java.lang.NullPointerException: Cannot invoke "org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(java.sql.SQLException, String)" because the return value of "org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.sqlExceptionHelper()" is null
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doTheWork(JtaIsolationDelegate.java:186)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.lambda$delegateWork$1(JtaIsolationDelegate.java:75)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInSuspendedTransaction(JtaIsolationDelegate.java:107)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.delegateWork(JtaIsolationDelegate.java:72)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:276)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:52)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:276)
        at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:70)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:157)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
        at java.base/java.lang.Thread.run(Thread.java:840)

2024-06-07 15:00:19,849 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': IO Exception: "D:/keycloak-24.0.5/data/h2/keycloakdb.mv.db" [90028-224]
2024-06-07 15:00:25,300 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': IO Exception: "D:/keycloak-24.0.5/data/h2/keycloakdb.mv.db" [90028-224]
2024-06-07 15:00:25,305 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-06-07 15:00:25,305 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2024-06-07 15:00:25,305 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Acquisition timeout while waiting for new connection
2024-06-07 15:00:25,305 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
D:\keycloak-24.0.5>java --version
openjdk 17.0.11 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)

D:\keycloak-24.0.5>
```

### Version

keycloak-24.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

The application should startup with JDK 17 without any issue.

### Actual behavior

On startup i encounter exception and process quits. 

### How to Reproduce?

1. Download the keycloak-24.0.5 in zip format.
2. Extract the zip
3. Use JDK openjdk 17.0.11 2024-04-16 version
4. Try Running bin\kc.bat start-dev

**Comment by shawkins** [comment]
@hahmad92 the underlying issue is likely hilighted by the log:

```
2024-06-07 15:00:25,300 WARN [io.agroal.pool] (agroal-11) Datasource '': IO Exception: "D:/keycloak-24.0.5/data/h2/keycloakdb.mv.db"
```

It does not appear the h2 driver is able to create / write to the database file. You can try increasing the log level to see if there is more detail on what is happening, or see if there is a permission or other issue preventing usage of the data directory.

**Comment by codespearhead** [comment]
@hahmad92 The fact that you're using the D partition instead of the C partition leads me to agree with [shawkins](https://github.com/shawkins)'s suspicion that [your current user doesn't have write access](https://kb.uwec.edu/articles/drives-establishing-windows-file-and-folder-level-permissions#Granting) to `D:/keycloak-24.0.5/data/h2/`. 

Keycloak Dev Mode works as expected on Docker.

```dockerfile
# docker build --progress=plain -t keycloak-image-30249 .

FROM eclipse-temurin:17.0.11_9-jdk-ubi9-minimal as base_os

FROM base_os as download_keycloak_zip
RUN curl -fSL https://github.com/keycloak/keycloak/releases/download/24.0.3/keycloak-24.0.3.zip -O

FROM base_os as install_unzip
RUN microdnf install -y unzip

FROM install_unzip as extract_keycloak_zip
COPY --from=download_keycloak_zip keycloak-24.0.3.zip keycloak-24.0.3.zip
RUN unzip keycloak-24.0.3.zip

FROM base_os as install_kc_dependencies
RUN microdnf install -y findutils

FROM install_kc_dependencies as run_keycloak_dev_mode
COPY --from=extract_keycloak_zip keycloak-24.0.3 /opt/keycloak
WORKDIR /opt/keycloak
ENV PATH="/opt/keycloak/bin:$PATH"
EXPOSE 8080
CMD ["kc.sh", "start-dev"]
```

```bash
# docker run --rm keycloak-image-30249

Updating the configuration and installing your custom providers, if any. Please wait.
2024-06-10 15:38:22,753 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 17633ms
2024-06-10 15:38:26,688 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2024-06-10 15:38:27,242 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-06-10 15:38:27,411 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-06-10 15:38:31,298 WARN  [io.quarkus.agroal.runtime.DataSources] (JPA Startup Thread) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2024-06-10 15:38:32,976 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-06-10 15:38:33,023 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_39787, Site name: null
2024-06-10 15:38:35,177 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml

UPDATE SUMMARY
Run:                        124
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:          124

2024-06-10 15:38:40,244 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2024-06-10 15:38:43,811 INFO  [io.quarkus] (main) Keycloak 24.0.3 on JVM (powered by Quarkus 3.8.3) started in 20.723s. Listening on: http://0.0.0.0:8080
2024-06-10 15:38:43,812 INFO  [io.quarkus] (main) Profile dev activated. 
2024-06-10 15:38:43,813 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2024-06-10 15:38:43,821 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```
