### ISSUE TITLE
Infinispan Timeouts with 24.0.5 when logging into Admin Console

### ISSUE THREAD

**Issue by ncphins** [keycloak/keycloak#30260]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I upgraded to the 24.0.5 release today, and I am seeing timeouts with infinispan when logging into the Admin Console. the startup looks fine (to me) with the cluster recognized. However, **as soon as I try to login to the console**, it times out (hangs "Loading the Admin UI").

If I drop back to 24.0.4, I see the same config at startup but I do not see any timeouts. I admit, I do not know a ton about the caching. We have a few test servers running on virtual machines. We are not really running a cluster. But we have never had any of these timeouts until 24.0.5. 

I have tried with an existing database (used with 24.0.4) and a fresh database with nothing in it (starting from scratch). Both show the same issue.

If I build with "--cache=local" I do not see the issues (of course).

I pulled the latest this morning and built and I do not see the issue there. BUT, the cluster is not getting setup with the nightly build (based on analysis os the startup logs). A new cluster is being created for some reason. So I do not believe it is a valid test.

Bottomline:
24.0.4 - Works
24.0.5 - Timeouts

Here is the stack from the errors (there are multiple). It is always waiting on that single server, which is reachable. Now, maybe that is simply the first and it never attempts the others. I am not sure. The server it reports the timeout on is running Keycloak 24.0.3.

`2024-06-07 09:26:21,162 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([kctest-51345]). Id=246
	at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:258)
	at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:323)
	at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:111)
	at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:93)
	at org.infinispan.cache.impl.CacheImpl.computeInternal(CacheImpl.java:334)
	at org.infinispan.cache.impl.CacheImpl.computeInternal(CacheImpl.java:325)
	at org.infinispan.cache.impl.CacheImpl.computeIfPresent(CacheImpl.java:312)
	at org.infinispan.cache.impl.EncoderCache.computeIfPresent(EncoderCache.java:710)
	at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.replace(InfinispanChangelogBasedTransaction.java:233)
	at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.runOperationInCluster(InfinispanChangelogBasedTransaction.java:216)
	at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.commitImpl(InfinispanChangelogBasedTransaction.java:172)
	at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
	at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
	at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:55)
	at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.closeSession(CloseSessionHandler.java:69)
	at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.filter(CloseSessionHandler.java:65)
	at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks ([kcjmptest-51345]). Id=246
	at org.infinispan.util.concurrent.CommandAckCollector.createTimeoutException(CommandAckCollector.java:228)
	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:281)
	at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:261)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
	Suppressed: org.infinispan.commons.util.logging.TraceException
		at org.infinispan.interceptors.impl.SimpleAsyncInvocationStage.get(SimpleAsyncInvocationStage.java:39)
		at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:249)
		at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:323)
		at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:111)
		at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:93)
		at org.infinispan.cache.impl.CacheImpl.computeInternal(CacheImpl.java:334)
		at org.infinispan.cache.impl.CacheImpl.computeInternal(CacheImpl.java:325)
		at org.infinispan.cache.impl.CacheImpl.computeIfPresent(CacheImpl.java:312)
		at org.infinispan.cache.impl.EncoderCache.computeIfPresent(EncoderCache.java:710)
		at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.replace(InfinispanChangelogBasedTransaction.java:233)
		at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.runOperationInCluster(InfinispanChangelogBasedTransaction.java:216)
		at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.commitImpl(InfinispanChangelogBasedTransaction.java:172)
		at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
		at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
		at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
		at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
		at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:55)
		at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.closeSession(CloseSessionHandler.java:69)
		at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.filter(CloseSessionHandler.java:65)
		at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
		at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
		at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		... 1 more`

### Version

24.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

I expect I can login to the admin console without any timeouts.

### Actual behavior

The login never succeeds due to multiple timeouts waiting on the infinispan cache.

### How to Reproduce?

Well...

I have a few virtual machine running Keycloak 24.0.3 and 24.0.4. 
Install 24.0.5 and run.
Try to login to the Admin Console.

### Anything else?

I do not feel like this is a great bug report due to the number of unknowns. But, I have went back and forth between 24.0.4 and 24.0.5 many times over the past 2 days. Same DB (or a fresh db), same config, same machine. And I only see this with 24.0.5.

**Comment by ncphins** [comment]
We tried this on 3 different machines here and saw the same results. 24.0.4 worked fine. 24.0.5 times out on all the machines.

**Comment by mabartos** [comment]
@pruivo Could you please check it, as it might be related to this issue https://github.com/keycloak/keycloak/pull/29081?

**Comment by pruivo** [comment]
@ncphins , If I understand the description, you're running KC 24.0.3, 24.0.4, 24.0.5 in the same cluster? If so, 24.0.5 is not compatible with 24.0.3 but it should be compatible with 24.0.4

24.0.5 -> uses new algorithm
24.0.4 -> accepts both
24.0.3 -> only works with the old.

**Comment by ncphins** [comment]
I guess I was a little surprised that I could not login to the admin console if this occurred. That seemed a little odd. The incompatibility or timeouts are one thing but the fact the login fails/hangs with the loading still sort of seems like a bug, albeit one I can work around.

**Comment by pruivo** [comment]
I just wanted to let you know that you didn't miss anything. Having different versions of Keycloak in the same cluster is not a supported use case, so we don't document this type of change. Currently, it is pure luck if version `x` works with version `x+1`. 

Can you double-check the  KC 24.0.3 logs? I'm not 100% sure that we log these errors but, if we do, it should have a serialization or marshaling exception. 

I can help set up Infinispan to separate clusters. Create another discussion and ping me there directly. I will need the `cache-ispn.xml` (if you modified it), and the `--cache-stack` configuration (if set).

**Comment by ncphins** [comment]
Ok. I will re-run the test and get the logs from the 24.0.3 machine tomorrow AM and add the info here. The server I am testing 24.0.5 is being used for testing today so I cannot update the Keycloak install.

I will start a discussion and ping you. We have not updated the cache-isn.xml file at all.

**Comment by ncphins** [comment]
I was asked to check the logs of the 24.0.3 machine to see if I see any exceptions. There is a single exception that is seen multiple times in the logs. More than likely when I restart the 24.0.5 machine (prior to assigning the different port).

We have fixed the issue (with help from @pruivo ) on our end by configuring the test servers such that they do not attempt to cluster. So as far as we are concerned this issue can be closed. But in case this exceptions helps or points to an issue on the Keycloak side, I am adding it here.
```
2024-06-27 15:52:21,877 ERROR [org.infinispan.CLUSTER] (jgroups-1347,kcjmptest-27128) ISPN000474: Error processing request 0@humphreytest-39392: java.lang.NullPointerException: Cannot invoke "org.infinispan.commons.marshall.AdvancedExternalizer.readObject(java.io.ObjectInput)" because "ext" is null
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:710)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.cache.impl.BiFunctionMapper$Externalizer.readObject(BiFunctionMapper.java:80)
	at org.infinispan.cache.impl.BiFunctionMapper$Externalizer.readObject(BiFunctionMapper.java:59)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.commands.triangle.SingleKeyBackupWriteCommand.readFrom(SingleKeyBackupWriteCommand.java:152)
	at org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:116)
	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:166)
	at org.infinispan.marshall.exts.CacheRpcCommandExternalizer.readObject(CacheRpcCommandExternalizer.java:85)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1528)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1468)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1663)
	at org.jgroups.JChannel.up(JChannel.java:734)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:936)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:139)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:253)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:261)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:846)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:226)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1086)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:825)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:807)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:456)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:680)
	at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:189)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
	at org.jgroups.protocols.Discovery.up(Discovery.java:294)
	at org.jgroups.stack.Protocol.up(Protocol.java:340)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1184)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:107)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
