### ISSUE TITLE
In base config, name is not required but breaks token generation

### ISSUE THREAD

**Issue by estani** [keycloak/keycloak#30266]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

I get the token for the admin user in the master realm and tried to list the users in some other realm, which didn't work throwing a NPE.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

No NPE and/or a better description of what is happening.

### Actual behavior

I get the token correctly, but when accessing: http://localhost:8080/admin/realms/some_realm/users?first=0&max=10 I get:
```
{
	"error": "unknown_error",
	"error_description": "For more on this error consult the server log at the debug level."
}
```

The logs:
```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-79) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.idm.UserRepresentation.getUsername()" because "rep" is null
        at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:131)
        at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to Reproduce?

Install the default docker, get admin token try to list the users

### Anything else?

Yes! Though not sure this has anything to do with the error, it might.
I started the docker container, created a realm, two clients and two users (nothing fancy).
Exported the configuration for both master and my new realm.
Restarted the server from scratch (same 24.0.4 version).
Imported the master realm, which showed an error (not clear what).
Imported the other without issues.

**Comment by estani** [comment]
Following this up, I've isolated this into just this compose.yaml:
```yaml
services:  
  pg:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: somePass
      POSTGRES_USER: someUser

  kc:
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: someUser
      KC_DB_PASSWORD: somePass
      KC_DB_URL: jdbc:postgresql://pg:5432/keycloak
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    command: ["start-dev"]

volumes:
  keycloak_data:
  postgres_data:
```
Got the token e.g. with
```sh
token=$(curl --request POST \
  --url http://localhost:8080/realms/master/protocol/openid-connect/token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data client_id=admin-cli \
  --data grant_type=password \
  --data username=admin \
  --data password=admin | jq -r ".access_token")
```

Called the Api with:
```sh
curl --request POST \
  --url 'http://localhost:8080/admin/realms/master/users?first=0&max=1' \
  --header "Authorization: Bearer $token"
```

Response:
```json
{"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."}
```

docker compose logs:
```
kc-1  | 2024-06-09 10:00:14,438 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.idm.UserRepresentation.getUsername()" because "rep" is null
kc-1  |         at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:131)
kc-1  |         at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
kc-1  |         at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
kc-1  |         at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
kc-1  |         at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
kc-1  |         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
kc-1  |         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
kc-1  |         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
kc-1  |         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
kc-1  |         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
kc-1  |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
kc-1  |         at java.base/java.lang.Thread.run(Thread.java:840)
```

Using a Mac with M1 (should not make any difference... but just in case)

**Comment by rmartinc** [comment]
@estani You are creating (not searching) a user because you are sending a POST instead of a GET. Search needs a GET.

```bash
curl --url 'http://localhost:8080/admin/realms/master/users?first=0&max=1' \
  --header "Authorization: Bearer $token"
```

Maybe we should check for empty representation and give a better error in create.

**Comment by estani** [comment]
Yes, sorry I tried too many things. But I've tried it again and had the same response. I don't see any log entries now... but this happened to me already, sometimes it seems that the errors are cached and not logged if they already happened.

**Comment by rmartinc** [comment]
Sometime you need to add a trace for some errors: `--log-level=INFO,org.keycloak.services.error:TRACE`.
I'm moving to priority low and help wanted. If someone wants to check if the user is null in the creation please just send a PR, if not this will be auto-closed.

**Comment by estani** [comment]
As soon as I added that log level, the logs showed the real error:
```
keycloak  | 2024-06-11 08:56:02,022 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Error response 403: org.keycloak.services.ForbiddenException
keycloak  |     at org.keycloak.services.resources.admin.permissions.UserPermissions.requireQuery(UserPermissions.java:282)
keycloak  |     at org.keycloak.services.resources.admin.UsersResource.getUsers(UsersResource.java:274)
keycloak  |     at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$getUsers_ecf451e248ab234ac2209c65a15ce9019c82b17d.invoke(Unknown Source)
keycloak  |     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak  |     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak  |     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak  |     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak  |     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak  |     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak  |     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak  |     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak  |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak  |     at java.base/java.lang.Thread.run(Thread.java:840)
```

makes little sense though, that the error message changed. I think at some point I must have fixed the error (perhaps by adding a first name to the user, or changing the realm configuration to use the e-mail as username.) but the caching was not cleared.

In any case I'm closing this now, as I won't follow it. If someone has the error, feel free to request the reopening of it.
