### ISSUE TITLE
The "Quarkus development mode" instructions in quarkus/README.md throw a ForkJoinPool error

### ISSUE THREAD

**Issue by lf-** [keycloak/keycloak#30276]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The development mode instructions in quarkus/README.md throw this exception:

```
2024-06-08 15:49:56,942 ERROR [org.keycloak.quarkus.runtime.KeycloakMain] (Quarkus Main Thread) The ForkJoinPool has been initialized with the wrong thread factory. The property 'java.util.concurrent.ForkJoinPool.common.threadFactory' should be set on the Java CLI to ensure Java's ForkJoinPool will always be initialized with 'null' even if there are Java agents which might initialize logging or other capabilities earlier than the main method.
2024-06-08 15:49:56,942 ERROR [io.quarkus.runner.bootstrap.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: The ForkJoinPool has been initialized with the wrong thread factory
        at org.keycloak.quarkus.runtime.KeycloakMain.ensureForkJoinPoolThreadFactoryHasBeenSetToQuarkus(KeycloakMain.java:117)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:60)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
```

### Version

86101b3d1d8af4080a1e07b91cb64425b1e607cd

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that the dev server command in the documentation should work.

### Actual behavior

```
[INFO] --- compiler:3.8.1:compile (default-compile) @ keycloak-quarkus-server-app ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus:3.8.5:dev (default-cli) @ keycloak-quarkus-server-app ---
[INFO] Invoking resources:3.2.0:testResources (default-testResources) @ keycloak-quarkus-server-app
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /home/jade/src/co/keycloak/quarkus/server/src/test/resources
[INFO] Invoking compiler:3.8.1:testCompile (default-testCompile) @ keycloak-quarkus-server-app
[INFO] No sources to compile
[WARNING] [io.quarkus.bootstrap.resolver.maven.workspace.WorkspaceLoader] Module(s) under /home/jade/src/co/keycloak/testsuite/integration-arquillian/tests/other/adapters/jboss/relative will be handled as thirdparty dependencies because /home/jade/src/co/keycloak/testsuite/integration-arquillian/tests/other/adapters/jboss/relative/pom.xml does not exist
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Live reload was disabled for the following project artifacts:
- org.keycloak:keycloak-quarkus-server:999.0.0-SNAPSHOT
- org.keycloak:keycloak-services:999.0.0-SNAPSHOT
- org.keycloak:keycloak-js-adapter-jar:999.0.0-SNAPSHOT
- org.keycloak:keycloak-common:999.0.0-SNAPSHOT
- org.keycloak:keycloak-core:999.0.0-SNAPSHOT
- org.keycloak:keycloak-crypto-default:999.0.0-SNAPSHOT
- org.keycloak:keycloak-crypto-fips1402:999.0.0-SNAPSHOT
- org.keycloak:keycloak-server-spi:999.0.0-SNAPSHOT
- org.keycloak:keycloak-server-spi-private:999.0.0-SNAPSHOT
- org.keycloak:keycloak-themes:999.0.0-SNAPSHOT
- org.keycloak:keycloak-saml-core-public:999.0.0-SNAPSHOT
- org.keycloak:keycloak-saml-core:999.0.0-SNAPSHOT
- org.keycloak:keycloak-model-jpa:999.0.0-SNAPSHOT
- org.keycloak:keycloak-model-infinispan:999.0.0-SNAPSHOT
- org.keycloak:keycloak-model-storage:999.0.0-SNAPSHOT
- org.keycloak:keycloak-model-storage-private:999.0.0-SNAPSHOT
- org.keycloak:keycloak-model-storage-services:999.0.0-SNAPSHOT
- org.keycloak:keycloak-authz-policy-common:999.0.0-SNAPSHOT
- org.keycloak:keycloak-kerberos-federation:999.0.0-SNAPSHOT
- org.keycloak:keycloak-sssd-federation:999.0.0-SNAPSHOT
- org.keycloak:keycloak-ldap-federation:999.0.0-SNAPSHOT
- org.keycloak:keycloak-config-api:999.0.0-SNAPSHOT
- org.keycloak:keycloak-account-ui:999.0.0-SNAPSHOT
- org.keycloak:keycloak-admin-ui:999.0.0-SNAPSHOT
- org.keycloak:keycloak-rest-admin-ui-ext:999.0.0-SNAPSHOT
- org.keycloak:keycloak-quarkus-server-deployment:999.0.0-SNAPSHOT
The artifacts above appear to be either dependencies of non-reloadable application dependencies or Quarkus extensions
Listening for transport dt_socket at address: 5005
2024-06-08 15:49:56,942 ERROR [org.keycloak.quarkus.runtime.KeycloakMain] (Quarkus Main Thread) The ForkJoinPool has been initialized with the wrong thread factory. The property 'java.util.concurrent.ForkJoinPool.common.threadFactory' should be set on the Java CLI to ensure Java's ForkJoinPool will always be initialized with 'null' even if there are Java agents which might initialize logging or other capabilities earlier than the main method.
2024-06-08 15:49:56,942 ERROR [io.quarkus.runner.bootstrap.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: The ForkJoinPool has been initialized with the wrong thread factory
        at org.keycloak.quarkus.runtime.KeycloakMain.ensureForkJoinPoolThreadFactoryHasBeenSetToQuarkus(KeycloakMain.java:117)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:60)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
```

### How to Reproduce?

1. Get clean checkout of keycloak; run `git clean -fxd`, or so.
2. Follow "building the project the first time" section in quarkus/README.md:
```
    ../mvnw -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
```
3. Run the command from the "Contributing" section of the same file:
```
    ../mvnw -f server/pom.xml compile quarkus:dev -Dquarkus.args="start-dev"
```

Get the exception shown above, and then:

```
2024-06-08 15:49:57,119 INFO  [io.quarkus.deployment.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2024-06-08 15:51:10,616 INFO  [io.quarkus.deployment.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Instrumentation based restart enabled

--
Tests paused
Press [e] to edit command line args (currently 'start-dev'), [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>
```

### Anything else?

This is on a:

openjdk 21.0.3 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9)
OpenJDK 64-Bit Server VM (build 21.0.3+9, mixed mode, sharing)

On Arch Linux.

**Comment by codespearhead** [comment]
@lf- I cannot reproduce the issue.

I tried on WSL with and OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing), as well as with the following Dockerfile that emulates your current setup:

```bash
# docker build --progress=plain -t keycloak-image .

FROM archlinux:base-devel-20240101.0.204074 as base-os

FROM base-os as install-deps
RUN pacman -Sy --noconfirm git jdk21-openjdk
ENV JAVA_HOME /usr/lib/jvm/java-21-openjdk

FROM install-deps as clone-keycloak
RUN git clone --depth 1 https://github.com/keycloak/keycloak.git

FROM install-deps as checkout-keycloak
COPY --from=clone-keycloak /keycloak /keycloak
RUN cd keycloak && git fetch --depth 1 origin 86101b3d1d8af4080a1e07b91cb64425b1e607cd
RUN cd keycloak && git checkout 86101b3d1d8af4080a1e07b91cb64425b1e607cd

FROM install-deps as compile-keycloak
COPY --from=checkout-keycloak /keycloak /keycloak
RUN cd keycloak/quarkus && ../mvnw -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests

FROM install-deps as run-keycloak
COPY --from=compile-keycloak /keycloak /keycloak
CMD ["sh", "-c", "git --version && java -version && cd keycloak/quarkus && java -jar server/target/lib/quarkus-run.jar start-dev"]
```

```bash
# docker run --rm keycloak-image
git version 2.45.2
openjdk version "21.0.3" 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9)
OpenJDK 64-Bit Server VM (build 21.0.3+9, mixed mode, sharing)
2024-06-10 03:06:04,514 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-06-10 03:06:05,972 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-06-10 03:06:08,007 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml

UPDATE SUMMARY
Run:                        133
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:          133

2024-06-10 03:06:12,430 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_59390, Site name: null
2024-06-10 03:06:12,674 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2024-06-10 03:06:15,622 INFO  [io.quarkus] (main) Keycloak 999.0.0-SNAPSHOT on JVM (powered by Quarkus 3.8.5) started in 18.898s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
2024-06-10 03:06:15,624 INFO  [io.quarkus] (main) Profile dev activated. 
2024-06-10 03:06:15,624 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
2024-06-10 03:06:15,632 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```
