### ISSUE TITLE
Failed to evaluate permissions when fetchRoles is enabled on role policies

### ISSUE THREAD

**Issue by Romain7495** [keycloak/keycloak#30444]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

Hello

I just tried the feature implemented by @pedroigor  in this ticket https://github.com/keycloak/keycloak/issues/20736  and documented [here](https://www.keycloak.org/docs/latest/authorization_services/#_policy_rbac). The goal is to evaluate roles server side.

Here is the stacktrace: 
```
2024-06-14 13:16:24,428 ERROR [org.keycloak.authorization.authorization.AuthorizationTokenService] (executor-thread-1332) Unexpected error while evaluating permissions: java.lang.RuntimeException: Failed to evaluate permissions
	at org.keycloak.authorization.policy.evaluation.DecisionPermissionCollector.onError(DecisionPermissionCollector.java:182)
	at org.keycloak.authorization.permission.evaluator.IterablePermissionEvaluator.evaluate(IterablePermissionEvaluator.java:71)
	at org.keycloak.authorization.permission.evaluator.IterablePermissionEvaluator.evaluate(IterablePermissionEvaluator.java:87)
	at org.keycloak.authorization.authorization.AuthorizationTokenService.evaluatePermissions(AuthorizationTokenService.java:291)
	at org.keycloak.authorization.authorization.AuthorizationTokenService.authorize(AuthorizationTokenService.java:227)
	at org.keycloak.protocol.oidc.grants.PermissionGrantType.process(PermissionGrantType.java:187)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:140)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException
```

It result with a 500, then NOT_AUTHORIZED

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Expected behaviour is to evalueate the role server side and do not return a 500

### Actual behavior

We are receiving from keycloak when evaluating permissions if `fetchRoles` feature is enabled on role policy
```
{
        "code": "E_UNAUTHORIZED",
        "message": "Missing or invalid authentication token",
        "data": {}
}
```

### How to Reproduce?

1. Create a role policy with `fetchRoles` enabled like this 
![image](https://github.com/keycloak/keycloak/assets/15386726/039cf5e6-4c18-4479-a651-2854690bc05a)

2. Evaluate this permissions with a user that have this role assigned
3. You will have an error:  `E_UNAUTHORIZED` and `Missing or invalid authentication token`
4. Now disable the fetchRoles feature and ensure you have roles mapping enabled in your jwt 
5. It works 

### Anything else?

Can I help debug this issue ? I can provide more logs if needed. Thanks in advance

**Comment by pedroigor** [comment]
@Romain7495 If you can give more details about the NPE from the issue description, I appreciate it. Otherwise, I'm not sure why it is happening.

The only think I can think of is the role being null when running the role policy but it does not seem to be the case.

Are you able to expand the stack trace you shared with more details about the NPE?

**Comment by Romain7495** [comment]
@pedroigor I will enable debug log and come back to you

**Comment by Romain7495** [comment]
ok @pedroigor I think it comes from 
```
2024-06-18 14:04:17,272 ERROR [org.keycloak.authorization.authorization.AuthorizationTokenService] (executor-thread-149) Unexpected error while evaluating permissions: java.lang.RuntimeException: Failed to evaluate permissions
	at org.keycloak.authorization.policy.evaluation.DecisionPermissionCollector.onError(DecisionPermissionCollector.java:182)
	at org.keycloak.authorization.permission.evaluator.IterablePermissionEvaluator.evaluate(IterablePermissionEvaluator.java:71)
	at org.keycloak.authorization.permission.evaluator.IterablePermissionEvaluator.evaluate(IterablePermissionEvaluator.java:87)
	at org.keycloak.authorization.authorization.AuthorizationTokenService.evaluatePermissions(AuthorizationTokenService.java:291)
	at org.keycloak.authorization.authorization.AuthorizationTokenService.authorize(AuthorizationTokenService.java:227)
	at org.keycloak.protocol.oidc.grants.PermissionGrantType.process(PermissionGrantType.java:187)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:140)
	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.UserModel.hasRole(org.keycloak.models.RoleModel)" because "user" is null
	at org.keycloak.authorization.policy.provider.role.RolePolicyProvider.hasRole(RolePolicyProvider.java:79)
	at org.keycloak.authorization.policy.provider.role.RolePolicyProvider.evaluate(RolePolicyProvider.java:62)
	at org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:62)
	at org.keycloak.authorization.policy.provider.permission.ScopePolicyProvider.evaluate(ScopePolicyProvider.java:55)
	at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.lambda$createPolicyEvaluator$0(DefaultPolicyEvaluator.java:117)
	at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1077)
	at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.cacheQuery(StoreFactoryCacheSession.java:1052)
	at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession$PolicyCache.findByResource(StoreFactoryCacheSession.java:948)
	at org.keycloak.authorization.AuthorizationProvider$3.findByResource(AuthorizationProvider.java:408)
	at org.keycloak.authorization.policy.evaluation.DefaultPolicyEvaluator.evaluate(DefaultPolicyEvaluator.java:71)
	at org.keycloak.authorization.permission.evaluator.IterablePermissionEvaluator.evaluate(IterablePermissionEvaluator.java:66)
	... 16 more
	```
	
with `"org.keycloak.models.UserModel.hasRole(org.keycloak.models.RoleModel)" because "user" is null`

**Comment by pedroigor** [comment]
I see. How the subject token you are sending to the token endpoint look like?

**Comment by Romain7495** [comment]
@pedroigor looks like this
```
{
  "exp": 1718729576,
  "iat": 1718729276,
  "auth_time": 1718717914,
  "jti": "xxx-xxx-xxx-xxx-xxxx",
  "iss": "https://sso.dev.smood.ch/realms/smood-dev",
  "sub": "xxx-xxx-xxx-xxx-xxxxa",
  "typ": "Bearer",
  "azp": "admin-desk",
  "sid": "xxx-xxx-xxx-xxx-xxxx",
  "acr": "0",
  "allowed-origins": [
    "xxx"
  ],
  "resource_access": {
    "admin-desk": {
      "roles": [
        "admin-desk.bug-reports.get",
        "admin-desk.employees.personal-info.edit",
        "admin-desk.employees.security.edit",
        "admin-desk.employees.smood-info.edit",
        "admin-desk.employees.permissions.edit",
        "admin-desk.employees.create",
        "admin-desk.employees.security.get",
        "admin-desk.employees.list",
        "admin-desk.bug-reports.edit",
        "admin-desk.employees.permissions.get",
        "admin-desk.employees.personal-info.get",
        "admin-desk.employees.get",
        "admin-desk.employees.smood-info.get"
      ]
    }
  },
  "scope": "openid email smood profile",
  "googleId": "xxxxx",
  "email_verified": true,
  "name": "Romain LABAT",
  "preferred_username": "romain.labat@smood.ch",
  "id": "xxxxxx",
  "locale": "en",
  "given_name": "Romain",
  "family_name": "LABAT",
  "picture": "xxx",
  "email": "r.xxx@smood.ch"
}
```

**Comment by Romain7495** [comment]
Yes this is a valid user, this is mine.

<img width="1440" alt="image" src="https://github.com/keycloak/keycloak/assets/15386726/263dad26-1576-4a80-8471-02de4e5c4498">

**Comment by pedroigor** [comment]
If you are able to debug the server, would you mind adding a breakpoint at https://github.com/keycloak/keycloak/blob/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProvider.java#L79?

The `identity.getId` should return the UID for that user and resolve to a `UserModel`. If you can help look at that, it should be the last piece of the puzzle. I'm really clueless about what is going on ...

**Comment by Romain7495** [comment]
I never did that with the real database and all the ecosystem. Should be complicated to reproduce. I will check what I can do

**Comment by Romain7495** [comment]
@pedroigor what do you think if : 

- we had a printf line of code with all needed informations
- build keycloak artifact
- build a docker image (https://github.com/keycloak/keycloak/blob/main/quarkus/container/Dockerfile)
- and then I can easily rebuild an optimized keycloak image that I can run in our ecosystem 

I know it's long story, or maybe add debug logging for keycloak `25.0.1` ?

**Comment by pedroigor** [comment]
Thanks. Works for me if you are printing out the value of `identity.getId` and the realm name. I just want to check if the value matches what is in the token and see how to reproduce locally.

We do have tests for this scenario and I'm really curious what we are missing in terms of coverage.

**Comment by Romain7495** [comment]
@pedroigor I didn't manage to build a debug image that have a different version of `999-snapshot` to not break migration in my dev environment, when I am modifying the version in the pom.xml it fails, 
Do you have some helpers script to build the tarball ? Then the docker part is ok

**Comment by Romain7495** [comment]
@pedroigor I understand the issue. 

The call with sub that is matching a user is working as expected: 
```
    {
     "exp": 1718729576,
     "iat": 1718729276,
     "auth_time": 1718717914,
     "jti": "xxx-xxx-xxx-xxx-xxxx",
     "iss": "https://sso.dev.smood.ch/realms/smood-dev",
     "sub": "xxx-xxx-xxx-xxx-xxxxa",
     "typ": "Bearer",
     "azp": "admin-desk",
     "sid": "xxx-xxx-xxx-xxx-xxxx",
     "acr": "0",
     "allowed-origins": [
       "xxx"
     ],
     "resource_access": {
       "admin-desk": {
         "roles": [
           "admin-desk.bug-reports.get",
           "admin-desk.employees.personal-info.edit",
           "admin-desk.employees.security.edit",
           "admin-desk.employees.smood-info.edit",
           "admin-desk.employees.permissions.edit",
           "admin-desk.employees.create",
           "admin-desk.employees.security.get",
           "admin-desk.employees.list",
           "admin-desk.bug-reports.edit",
           "admin-desk.employees.permissions.get",
           "admin-desk.employees.personal-info.get",
           "admin-desk.employees.get",
           "admin-desk.employees.smood-info.get"
         ]
       }
     },
     "scope": "openid email smood profile",
     "googleId": "xxxxx",
     "email_verified": true,
     "name": "Romain LABAT",
     "preferred_username": "romain.labat@smood.ch",
     "id": "xxxxxx",
     "locale": "en",
     "given_name": "Romain",
     "family_name": "LABAT",
     "picture": "xxx",
     "email": "r.xxx@smood.ch"
    }
```

The call with `clientId=api-monolith` causes NPE when roles policies with `fetchRoles` is enable. This is an api to api call. And for this we have a client uma policies, not a role policy. 
![image](https://github.com/keycloak/keycloak/assets/15386726/c2a40c44-72e7-428e-af8c-4a234132b702)

Maybe we can just add a condition if `clientId` is set, don't try to resolve to `UserModel ` or juste check the policy type (role policy only)

Here is the jwt template: 
```
{
  "exp": 0,
  "iat": 0,
  "jti": "xxxxxxxx",
  "iss": "https://sso.dev.smood.ch/realms/smood-dev",
  "sub": "c5aac969-2ca5-42e4-8c97-a079faf2e65c",
  "typ": "Bearer",
  "azp": "api-monolith",
  "acr": "1",
  "resource_access": {
    "api-monolith": {
      "roles": [
        "uma_protection"
      ]
    }
  },
  "scope": "xxx",
  "clientId": "api-monolith",
  "clientHost": "xxxx",
  "email_verified": false,
  "preferred_username": "service-account-api-monolith",
  "clientAddress": "xxxx"
}
```

**Comment by pedroigor** [comment]
@Romain7495 I see, now it makes sense. I think what you are suggesting will work and we can also check if the client maps to a service account ?

**Comment by pedroigor** [comment]
Btw, the `clientId` claim and others are being set by some protocol mapper on your side? AFAIK, we don't set that claim in tokens, the `azp` claim maps to the same information.

**Comment by Romain7495** [comment]
@pedroigor I just created a fresh realm, with fresh client, and I have all thoses mapper created by default in dedicated client scope
![image](https://github.com/keycloak/keycloak/assets/15386726/cccebe89-99d4-41b4-8bea-eecb0d44afb7)

Should it be related to one of preview features that are enabled in our dev environment ? (`ENV KC_FEATURES=preview` set before building optimized image)

**Comment by Romain7495** [comment]
@pedroigor other point to address 
In version `21.1.0`, keycloak stops to create `clientId` claim to be compliant with OAuth2 specifications as described [here](https://www.keycloak.org/docs/latest/upgrading/index.html#change-of-the-default-client-id-mapper-of-service-account-client)

Should I support both `clientId` and `client_id` as keeping `clientId` should not break existing config ?

**Comment by pedroigor** [comment]
True. I missed that those claims are added only to service accounts.

I think we can also support service accounts and make it work with "fetch roles". Let me try something here on top of your PR.

**Comment by pedroigor** [comment]
@Romain7495 Updated the PR. We can continue discussions there. Thanks for your help.
