### ISSUE TITLE
Auth fetch failed

### ISSUE THREAD

**Issue by moisesrodriguez** [keycloak/keycloak#30587]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-js

### Describe the bug

node: 22-alpine
keycloak/keycloak-admin-client: 25.0.0
keycloak: 25.0.0
keycloak hostname settings:
![CleanShot 2024-06-19 at 12 27 27@2x](https://github.com/keycloak/keycloak/assets/3869040/a9e73024-779e-4e83-8753-0e9b20ecc79c)

When trying to authenticate with the js admin client I keep getting the error `TypeError: fetch failed`. This happens with the js admin client. When I do a curl in my terminal with the same parameters I get a response. Example:
![CleanShot 2024-06-19 at 11 25 15@2x](https://github.com/keycloak/keycloak/assets/3869040/f46654b6-2ab1-4b43-8fbc-a67ae5fb2942)

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Get a response with the following:
```
{
  "access_token": "xxxx",
  "expires_in": 60,
  "refresh_expires_in": 1800,
  "refresh_token": "xxxxx",
  "token_type": "Bearer",
  "not-before-policy": 0,
  "session_state": "49287f0b-fe87-4f19-ad36-402d065a685d",
  "scope": "email profile"
}
```

### Actual behavior

I get the following error:
```
TypeError: fetch failed
    at node:internal/deps/undici/undici:13193:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchWithError (file:///usr/src/app/node_modules/@keycloak/keycloak-admin-client/lib/utils/fetchWithError.js:13:22)
    at getToken (file:///usr/src/app/node_modules/@keycloak/keycloak-admin-client/lib/utils/auth.js:50:22)
    at KeycloakAdminClient.auth (file:///usr/src/app/node_modules/@keycloak/keycloak-admin-client/lib/client.js:67:47)
    at AdminCreateUserService.create (/usr/src/app/src/core/admin/user/create-user.service.ts:35:4)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

### How to Reproduce?

```
import KcAdminClient from '@keycloak/keycloak-admin-client';
...
const kcAdminClient = new KcAdminClient({
  baseUrl: baseUrl,
  realmName: realm,
});
await kcAdminClient.auth({
  username: username,
  password: password,
  clientId: clientId,
  grantType: 'password',
});
```

In debugging the error in `utils/auth.js` I printed this:
![CleanShot 2024-06-18 at 20 32 01@2x](https://github.com/keycloak/keycloak/assets/3869040/6b85cac5-5897-4d7f-abcf-1b6c47acd6ec)

And this in `utils/fetchWithError.js`
![CleanShot 2024-06-18 at 20 32 11@2x](https://github.com/keycloak/keycloak/assets/3869040/ec384316-8487-4916-8b34-ed351237b33d)

And I can see in the logs the correct values from `utils/auth.js` but I don't see in `utils/fetchWithErrors.js` the headers:
![CleanShot 2024-06-18 at 20 31 00@2x](https://github.com/keycloak/keycloak/assets/3869040/31666493-1c3c-4a09-b5fd-03d1a7f831d1)

I tried passing the headers in the `requestOptions` still same error `fetch failed`

**Comment by moisesrodriguez** [comment]
I found my issue, there is nothing wrong with `keycloak-admin-client`. I have everything dockerized and I was not noticing I was trying to reach keycloak via `localhost:8080` but that would be localhost of the container not the host, the solution is to use keycloak's IP container address. And that is easily done using docker compose keycloak service name.
