### ISSUE TITLE
Network response was not OK.

### ISSUE THREAD

**Issue by laopaoer-wallet** [keycloak/keycloak#30604]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

Add the SAML provider with azure.

SAML entity descriptor url : 

https://login.microsoftonline.com/91d944d5-a6b0-49c3-b5ef-a3456c79a0b1/federationmetadata/2007-06/federationmetadata.xml?appid=b02218c5-d76e-4c29-8a9a-fae224d41669

Error:Network response was not OK

![image](https://github.com/keycloak/keycloak/assets/75466368/433ad000-7b09-4dc7-8406-45fe04e754a8)

<img width="1082" alt="image" src="https://github.com/keycloak/keycloak/assets/75466368/27fa4c4a-c476-4742-ad60-c761caca8a71">

### Version

25.0.0

**Comment by vramik** [comment]
I was able to reproduce the issue. It seems that the Stax parser doesn't count with following start of the descriptor.

```xml
<?xml
version="1.0" encoding="utf-8"?>
<EntityDescriptor ID="_013d627c-b61b-45f1-b247-ebcabb101641" entityID="https://sts.windows.net/91d944d5-a6b0-49c3-b5ef-a3456c79a0b1/" xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
...
```

There is a stacktrace from console:

```
2024-06-20 12:17:08,609 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-166) Uncaught server error: java.lang.RuntimeException: Could not parse IdP SAML Metadata
	at org.keycloak.broker.saml.SAMLIdentityProviderFactory.parseConfig(SAMLIdentityProviderFactory.java:173)
	at org.keycloak.services.resources.admin.IdentityProvidersResource.importFrom(IdentityProvidersResource.java:160)
	at org.keycloak.services.resources.admin.IdentityProvidersResource$quarkusrestinvoker$importFrom_a2928105606b1cfb77befafeb917cf58b5abe0c4.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: ParsingException [location=null]org.keycloak.saml.common.exceptions.ParsingException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at org.keycloak.saml.common.DefaultPicketLinkLogger.parserException(DefaultPicketLinkLogger.java:421)
	at org.keycloak.saml.common.util.StaxParserUtil.peek(StaxParserUtil.java:770)
	at org.keycloak.saml.processing.core.parsers.saml.SAMLParser.parse(SAMLParser.java:111)
	at org.keycloak.saml.processing.core.saml.v2.util.SAMLMetadataUtil.parseEntityDescriptorType(SAMLMetadataUtil.java:110)
	at org.keycloak.broker.saml.SAMLIdentityProviderFactory.parseConfig(SAMLIdentityProviderFactory.java:73)
	... 12 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:277)
	at org.keycloak.saml.common.util.StaxParserUtil.peek(StaxParserUtil.java:768)
	... 15 more
```

Assigning the `core-clients` team as the issue relates to saml.

**Comment by ben-wallis** [comment]
Came across this in 25.0.1 too, also with Azure SAML metadata

**Comment by ZiggiZagga** [comment]
> I had the same issue afer upgrading from version 24.0.4 to version 25.0.0. I had to assig query-realms role mapping to my user, to make things works as expected. ![keycloak_role_mapping](https://private-user-images.githubusercontent.com/75372480/347340666-1ddc0282-2941-49d1-a6d2-e73d08a3cf8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDM2MjAsIm5iZiI6MTcyMDYwMzMyMCwicGF0aCI6Ii83NTM3MjQ4MC8zNDczNDA2NjYtMWRkYzAyODItMjk0MS00OWQxLWE2ZDItZTczZDA4YTNjZjhhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzllNGJiN2ZkNzBmZjRhMzVlN2Q3YTRjNWE4YWU1YTU1MDAyN2I5YTU0MGFhZWFkNzY5Nzk2NzIyNWE2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6zoSeGON-N4GyC4ulDGKWPjIKN-t4ysH250RV7hY6M)

**Comment by antoineroux** [comment]
I have the same issue with Keycloak 25.0.0.

**Comment by andreasnacke1887** [comment]
I have the same issue with Keycloak 25.0.2

**Comment by jskeycloakuser** [comment]
It seems, like setting "Use metadata descriptor URL" in the IDP to true the certificate validation in the SSO process fails, which leads to unsuccessful logins.
Issue occurs on 25.0.2

**Comment by megan-parkes-sonocent** [comment]
Hi, we were also seeing this issue with Azure AD/Entra ID when importing via SAML entity descriptor URL and when importing config from a file.
The issue for us was a unicode byte order mark issue, to fix we removed the BOM encoding from the file, and reimported via the file import which seemed to stop the error.
