### ISSUE TITLE
ConcurrentModificationException in HashMap.compute() via RealmAdapter.getComponentsStream() while creating users concurrently via kcadm.sh

### ISSUE THREAD

**Issue by famod** [keycloak/keycloak#30627]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Just got the following Exception while running my realm init script which is executing `kcadm.sh` many times:
```
2024-06-20 15:16:58,169 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.util.ConcurrentModificationException
 	at java.base/java.util.HashMap.compute(HashMap.java:1325)
 	at org.keycloak.common.util.MultivaluedMap.getList(MultivaluedMap.java:63)
 	at org.keycloak.models.cache.infinispan.RealmAdapter.getComponentsStream(RealmAdapter.java:1656)
 	at org.keycloak.models.RealmModel.getStorageProviders(RealmModel.java:538)
 	at org.keycloak.storage.AbstractStorageManager.getStorageProviderModels(AbstractStorageManager.java:245)
 	at org.keycloak.storage.AbstractStorageManager.getEnabledStorageProviders(AbstractStorageManager.java:94)
 	at org.keycloak.storage.AbstractStorageManager.mapEnabledStorageProvidersWithTimeout(AbstractStorageManager.java:134)
 	at org.keycloak.storage.UserStorageManager.getUserByEmail(UserStorageManager.java:425)
 	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByEmail(UserCacheSession.java:419)
 	at org.keycloak.userprofile.validator.DuplicateEmailValidator.validate(DuplicateEmailValidator.java:70)
 	at org.keycloak.userprofile.AttributeValidatorMetadata.validate(AttributeValidatorMetadata.java:80)
 	at org.keycloak.userprofile.DefaultAttributes.validate(DefaultAttributes.java:169)
 	at org.keycloak.userprofile.DefaultUserProfile.validate(DefaultUserProfile.java:76)
 	at org.keycloak.services.resources.admin.UserResource.validateUserProfile(UserResource.java:256)
 	at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:146)
 	at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.base/java.lang.Thread.run(Thread.java:1583)a
```
Some executions are happening concurrently to reduce init runtime.

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Concurrent user creation works just fine.

### Actual behavior

Sporadic `ConcurrentModificationException`.

### How to Reproduce?

```bash
kcadm.sh create users ... &
kcadm.sh create users ... &
kcadm.sh create users ... &
kcadm.sh create users ... &
# ...
wait
```

### Anything else?

Using `--cache=local`.
Never seen this in KC 24 or below.

Interestingly, the keycloak-github-bot reported a flaky test in the same area: #30234

**Comment by vramik** [comment]
Hello @famod, thank you for the report. As far as I remember, this is kind of known issue. 

@sguilhen do you remember some context about concurrency when working with componens?

**Comment by famod** [comment]
It would be very helpful to know whether this is "just" a one time init issue, meaning: Can this only happen for the very first user creation calls on a freshly started KC instance?
In that case I could try creating users in parallel only after the first user was created (assuming that StorageProvider lookup is then done and "cached").

**Comment by sguilhen** [comment]
@vramik I remember having to lock realms for modifications when attempting to use CockroachDB, this error is different and seems to be introduced by https://github.com/keycloak/keycloak/pull/29536

**Comment by pedroigor** [comment]
@famod Should be fixed by one of the changes here https://github.com/keycloak/keycloak/issues/29394.

See the field declaration in [25.0.1](https://github.com/keycloak/keycloak/blob/25.0.1/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java#L126). And in [upstream](https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedRealm.java#L128).

@famod Do you mind testing a nightly build (assuming they are updated with the latest main)?

**Comment by pedroigor** [comment]
@vramik I'm also wondering if we should make other fields in `CachedRealm` using a concurrent map because instances of it are accessed concurrently.

If @famod can confirm the fix above works we should consider backporting it to 25. Perhaps you can also review other places with the same symptoms?

**Comment by pedroigor** [comment]
I also think we can close https://github.com/keycloak/keycloak/issues/30234. It does not seem to be flaky anymore.

**Comment by famod** [comment]
Thanks @pedroigor!

Sadly, I won't have time this week to test anything.

**Comment by vramik** [comment]
@famod thanks for the info. I'll close the issue for now as it might be already fixed, please feel free to re-open once you get a change to verify it. Thank you
