### ISSUE TITLE
Keycloak only displaying KeyDescriptor use="signing" and no use="encryption"

### ISSUE THREAD

**Issue by eduardfrankford** [keycloak/keycloak#30863]
### Description

We are currently experiencing an issue with our SAML integration where the Identity Provider (IDP) is unable to decrypt messages. Our SAML metadata only includes a KeyDescriptor for signing, and it is essential to also include a KeyDescriptor for encryption to ensure proper decryption of messages.

Here the encryption key is missing: https://keycloak.sharing-codeability.uibk.ac.at/auth/realms/gitsearch/protocol/saml/descriptor

Which results in the following exception:

```
2024-06-27 10:17:47,825 WARN  [org.keycloak.broker.saml.SAMLEndpoint] (executor-thread-13) Not possible to decrypt SAML assertion. Please check realm keys of usage ENC in the realm 'gitsearch' and make sure there is a key able to decrypt the assertion encrypted by identity provider 'idp_uibk_ac_at_idp_shibboleth': org.keycloak.saml.common.exceptions.ProcessingException: PL00102: Processing Exception:
        at org.keycloak.saml.common.DefaultPicketLinkLogger.processingError(DefaultPicketLinkLogger.java:165)
        at org.keycloak.saml.processing.core.util.XMLEncryptionUtil.decryptElementInDocument(XMLEncryptionUtil.java:308)
        at org.keycloak.saml.processing.core.saml.v2.util.AssertionUtil.decryptAssertion(AssertionUtil.java:612)
        at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleLoginResponse(SAMLEndpoint.java:475)
        at org.keycloak.broker.saml.SAMLEndpoint$Binding.handleSamlResponse(SAMLEndpoint.java:697)
        at org.keycloak.broker.saml.SAMLEndpoint$Binding.execute(SAMLEndpoint.java:288)
        at org.keycloak.broker.saml.SAMLEndpoint.postBinding(SAMLEndpoint.java:193)
        at org.keycloak.broker.saml.SAMLEndpoint$quarkusrestinvoker$postBinding_e2ae3e4e98121b36952f2279cd4bb60100612099.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Cannot decrypt element in document
```

**Comment by jonkoops** [comment]
This was filed as an enhancement, which it most certainly is not, if you are looking to ask a question use [the forums](https://github.com/keycloak/keycloak/discussions/categories/q-a). Or if you are trying to report a bug, please report it with the right template.
