### ISSUE TITLE
Upon logging in a new session is created even though old one is not expired

### ISSUE THREAD

**Issue by salmanazmat666** [keycloak/keycloak#31020]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Our application is using Keycloak for authentication, and we have set the `User Session Count Limiter` in the browser flow. 
If I log into the app via keycloak, I usually just close the browser after using app without logging out. Now, when logging in the app the next day, keycloak asks for username/password at the log in screen and upon providing credentials it shows error that the session count limit is exceeded. I look into the cookies that are used during the log in flow, and I noticed that even though the old session cookie is not expired yet, the keycloak is setting new session cookie with different session id.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should use the old session id stored in the cookie instead of creating new session.

### Actual behavior

Keycloak is setting new session cookie with new session id. Or in other words, it is trying to create new session while old session is not expired yet.

### How to Reproduce?

- Implement confidential auth code client
- Update the browser flow to include the  `User Session Count Limiter` step and set he max count to 1.
- Now log in, using the auth code flow, and then just close the browser.
- Now try logging in the next day, you should receive error.

See following pictures for settings.

Session Settings
![image](https://github.com/keycloak/keycloak/assets/10860229/2fe5f2dc-82c8-43e9-92a0-3308330a8cfb)

Token Settings
![image](https://github.com/keycloak/keycloak/assets/10860229/7d51d98c-cfd7-4d96-95de-2568a9b26b47)

Browser Flow Settings
![image](https://github.com/keycloak/keycloak/assets/10860229/42121650-3d44-420d-af31-8bcc3c33cb05)

### Anything else?

Please see following pictures for the request sent to load the log in page.

![Pasted Graphic 2](https://github.com/keycloak/keycloak/assets/10860229/bec0f25e-d0cc-4bda-8f4d-e35739112cfe)
![Payload](https://github.com/keycloak/keycloak/assets/10860229/c1018a5d-e067-4bde-9872-1b5e96789931)
![Pasted Graphic](https://github.com/keycloak/keycloak/assets/10860229/0a0eb5ce-b506-40a6-b3c8-49b5e84058bc)

**Comment by rmartinc** [comment]
@salmanazmat666 Please check before with the last version 25.0.1. It's something that saves us a lot of time.

**Comment by alvinthen** [comment]
I'm getting this after upgraded to 25.0.1. With a User Session Count Limiter, when logging in with any account using the same browser (after the expiry of previous session), Keycloak returns "An internal server error has occurred". The logs below is repeated many times until it failed

<img width="554" alt="image" src="https://github.com/keycloak/keycloak/assets/771989/5dfdc9d3-405f-41fa-94f1-8e017487fe4e">


<details><summary>Details</summary>
<p>
2024-07-04 08:37:49,198 INFO  [org.keycloak.authentication.authenticators.sessionlimits.UserSessionLimitsAuthenticator] (executor-thread-13) Too many sessions related to the current client for this user. Session count: 7
2024-07-04 08:37:49,198 INFO  [org.keycloak.authentication.authenticators.sessionlimits.UserSessionLimitsAuthenticator] (executor-thread-13) Terminating oldest session
2024-07-04 08:37:49,198 INFO  [org.keycloak.authentication.authenticators.sessionlimits.UserSessionLimitsAuthenticator] (executor-thread-13) Logging out oldest session
2024-07-04 08:37:49,291 INFO  [org.hibernate.orm.jdbc.batch] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) HHH100503: On release of batch it still contained JDBC statements
2024-07-04 08:37:49,291 ERROR [org.hibernate.orm.jdbc.batch] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) HHH100501: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '8be78595-103d-413a-93ca-5d8c61329eed-0' for key 'OFFLINE_USER_SESSION.PRIMARY'], SQL: insert into OFFLINE_USER_SESSION (BROKER_SESSION_ID,CREATED_ON,DATA,LAST_SESSION_REFRESH,REALM_ID,USER_ID,version,OFFLINE_FLAG,USER_SESSION_ID) values (?,?,?,?,?,?,?,?,?)
2024-07-04 08:37:49,291 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) SQL Error: 1062, SQLState: 23000
2024-07-04 08:37:49,291 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) Duplicate entry '8be78595-103d-413a-93ca-5d8c61329eed-0' for key 'OFFLINE_USER_SESSION.PRIMARY'
2024-07-04 08:37:49,291 WARN  [com.arjuna.ats.arjuna] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff0a588113:a781:66865e0d:1289, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@1418702e >: org.hibernate.exception.ConstraintViolationException: could not execute batch [Duplicate entry '8be78595-103d-413a-93ca-5d8c61329eed-0' for key 'OFFLINE_USER_SESSION.PRIMARY'] [insert into OFFLINE_USER_SESSION (BROKER_SESSION_ID,CREATED_ON,DATA,LAST_SESSION_REFRESH,REALM_ID,USER_ID,version,OFFLINE_FLAG,USER_SESSION_ID) values (?,?,?,?,?,?,?,?,?)]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:97)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:294)
	at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupSingleTable.forEachStatement(PreparedStatementGroupSingleTable.java:59)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.performExecution(BatchImpl.java:264)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.execute(BatchImpl.java:242)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:188)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:662)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:499)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:363)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:488)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2329)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1986)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
	at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:52)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:351)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:69)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:138)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1271)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
	at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:90)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
	at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:408)
	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:373)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:393)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:262)
	at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.lambda$process$3(PersistentSessionsWorker.java:88)
	at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:102)
	at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:93)
	at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.process(PersistentSessionsWorker.java:85)
	at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.run(PersistentSessionsWorker.java:69)
Caused by: java.sql.BatchUpdateException: Duplicate entry '8be78595-103d-413a-93ca-5d8c61329eed-0' for key 'OFFLINE_USER_SESSION.PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:223)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:813)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:416)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:802)
	at io.agroal.pool.wrapper.StatementWrapper.executeBatch(StatementWrapper.java:340)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:279)
	... 35 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '8be78595-103d-413a-93ca-5d8c61329eed-0' for key 'OFFLINE_USER_SESSION.PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:792)
	... 39 more


</p>
</details>
