### ISSUE TITLE
Keycloak 25 not able to start from command line

### ISSUE THREAD

**Issue by udayrachati** [keycloak/keycloak#31134]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

I was using key cloak 24.0.2 its working fine 

Later i download the key cloak 25.0.1  ,but i am not able to start the sever

i have updated JDK 21 also

kc.bat build 
kc.bat start
error

```
2024-07-08 20:42:54,752 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
2024-07-08 20:42:59,449 INFO  [org.infinispan.CONTAINER] (Thread-5) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-07-08 20:42:59,939 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-07-08 20:43:00,276 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000078: Starting JGroups channel `ISPN`
2024-07-08 20:43:00,281 INFO  [org.jgroups.JChannel] (Thread-5) local_addr: 875282e2-10b5-4adf-9645-065f49508a88, name: WIN-H658ABQSVG2-35313
2024-07-08 20:43:00,358 INFO  [org.jgroups.protocols.FD_SOCK2] (Thread-5) server listening on *.37163
2024-07-08 20:43:00,811 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2024-07-08 20:43:00,841 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-07-08 20:43:02,368 INFO  [org.jgroups.protocols.pbcast.GMS] (Thread-5) WIN-H658ABQSVG2-35313: no members discovered after 2006 ms: creating cluster as coordinator
2024-07-08 20:43:02,375 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000094: Received new cluster view for channel ISPN: [WIN-H658ABQSVG2-35313|0] (1) [WIN-H658ABQSVG2-35313]
2024-07-08 20:43:02,406 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000079: Channel `ISPN` local address is `WIN-H658ABQSVG2-35313`, physical addresses are `[192.168.164.223:52699]`
2024-07-08 20:43:02,812 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: WIN-H658ABQSVG2-35313, Site name: null
2024-07-08 20:43:04,019 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-07-08 20:43:04,031 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-07-08 20:43:04,067 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-07-08 20:43:04,071 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2024-07-08 20:43:04,072 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.lang.IllegalStateException: Unable to start the management interface
2024-07-08 20:43:04,073 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start the management interface
2024-07-08 20:43:04,074 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Address already in use: bind
2024-07-08 20:43:04,077 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

able to start the key cloak server

### Actual behavior

```
2024-07-08 20:42:54,752 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
2024-07-08 20:42:59,449 INFO  [org.infinispan.CONTAINER] (Thread-5) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-07-08 20:42:59,939 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-07-08 20:43:00,276 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000078: Starting JGroups channel `ISPN`
2024-07-08 20:43:00,281 INFO  [org.jgroups.JChannel] (Thread-5) local_addr: 875282e2-10b5-4adf-9645-065f49508a88, name: WIN-H658ABQSVG2-35313
2024-07-08 20:43:00,358 INFO  [org.jgroups.protocols.FD_SOCK2] (Thread-5) server listening on *.37163
2024-07-08 20:43:00,811 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2024-07-08 20:43:00,841 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-07-08 20:43:02,368 INFO  [org.jgroups.protocols.pbcast.GMS] (Thread-5) WIN-H658ABQSVG2-35313: no members discovered after 2006 ms: creating cluster as coordinator
2024-07-08 20:43:02,375 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000094: Received new cluster view for channel ISPN: [WIN-H658ABQSVG2-35313|0] (1) [WIN-H658ABQSVG2-35313]
2024-07-08 20:43:02,406 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000079: Channel `ISPN` local address is `WIN-H658ABQSVG2-35313`, physical addresses are `[192.168.164.223:52699]`
2024-07-08 20:43:02,812 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: WIN-H658ABQSVG2-35313, Site name: null
2024-07-08 20:43:04,019 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-07-08 20:43:04,031 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-07-08 20:43:04,067 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-07-08 20:43:04,071 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2024-07-08 20:43:04,072 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.lang.IllegalStateException: Unable to start the management interface
2024-07-08 20:43:04,073 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start the management interface
2024-07-08 20:43:04,074 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Address already in use: bind
2024-07-08 20:43:04,077 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### How to Reproduce?

download key cloak 25.0.1 
open bin folder in cmd prompt
run kc.bat build and then run kc.bat start-dev/start

**Comment by shawkins** [comment]
The management port is already in use:

```
2024-07-08 20:43:04,073 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start the management interface
2024-07-08 20:43:04,074 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Address already in use: bind
```

Double check what port you have that on, should be 9000 by default, and what else could be using that port.

**Comment by udayrachati** [comment]
i am using default configuration and i have tried with different ports including 9000 , still same issue, 
with same setup(machine/pc ) i have used key cloak 24.0.2 its working fine

**Comment by shawkins** [comment]
The management port was not separate in release 24. You can try using --verbose to get the full stacktrace to see if that sheds any more light. Otherwise it does seem to be something unique to your environment / configuration - you may need to use show config in case there are environment variables being picked up.

**Comment by shawkins** [comment]
~priority-low

**Comment by blacklight** [comment]
I can confirm the exact same issue on Keycloak 25 on Arch+Manjaro. Full stdout with `--verbose`:

```
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Unable to start HTTP server
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:834)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:315)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:139)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:119)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:99)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unable to start the management interface
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:760)
        ... 25 more
Caused by: java.lang.IllegalStateException: Unable to start the management interface
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.lambda$initializeManagementInterface$2(VertxHttpRecorder.java:629)
        at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:316)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:426)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:375)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:557)
        ... 4 more
```

Downgrading to Keycloak 24 fixes the issue, thus it's very unlikely to be an actual network misconfiguration on my side - the Keycloak port(s) are not in use by any other processes on my machine.

It sounds like a regression *at the very least* on the Arch package side, but I don't have much time to investigate if the fault lies with the 25.x branch or with the Arch package specifically.

**Comment by shawkins** [comment]
> Downgrading to Keycloak 24 fixes the issue, thus it's very unlikely to be an actual network misconfiguration on my side - the Keycloak port(s) are not in use by any other processes on my machine.

See above - the management port was not separate in KC 24.

**Comment by shawkins** [comment]
#32198 - will improve this by making it clear what port is being used. In this case we're assuming that it is 9000.

**Comment by jstandard** [comment]
I'm seeing the same problem.  Running `sudo lsof -i -n -P | grep 9000` on my machine reveals ZScalar is using the port 9000.

**Comment by shawkins** [comment]
> Reverting to Keycloak 24...

That isn't required, you are free to select whatever management port you want.

**Comment by jstandard** [comment]
>  you are free to select whatever management port you want.
Thanks!

[Configuring the Management Interface](https://www.keycloak.org/server/management-interface)
...you can use the Keycloak option `http-management-port`

**Comment by mabartos** [comment]
We need to obtain more information about this from those who face the issue.

1. Give us your system info (`uname -a`)
2. Did you check port `9000` is not occupied on your machine? (`netstat -tnlp | grep 9000`)

Thanks!

**Comment by pgillet** [comment]
In my case, I had to set `--legacy-observability-interface=true` to fix this issue.

See [Management port for metrics and health endpoints](https://www.keycloak.org/docs/latest/upgrading/index.html#management-port-for-metrics-and-health-endpoints) and [https://www.keycloak.org/server/management-interface](https://www.keycloak.org/server/management-interface)
