### ISSUE TITLE
Upgrade to Keycloak from 15.0 to 25.0 failed with error 

### ISSUE THREAD

**Issue by June3Ningxu** [keycloak/keycloak#31188]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Hello,
I found the issue when upgrade from Keycloak 15.0 to 25.0

the log is show as below
```
  | 2024-07-10T11:52:26.414Z | 2024-07-10 11:52:26,413 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com encountered an exception.
  | 2024-07-10T11:52:26.420Z | UPDATE SUMMARY
  | 2024-07-10T11:52:26.420Z | Run: 133
  | 2024-07-10T11:52:26.420Z | Previously run: 0
  | 2024-07-10T11:52:26.420Z | Filtered out: 0
  | 2024-07-10T11:52:26.420Z | -------------------------------
  | 2024-07-10T11:52:26.420Z | Total change sets: 133
  | 2024-07-10T11:52:26.471Z | 2024-07-10 11:52:26,470 INFO [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
  | 2024-07-10T11:52:26.537Z | 2024-07-10 11:52:26,537 INFO [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
  | 2024-07-10T11:52:26.613Z | 2024-07-10 11:52:26,613 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
  | 2024-07-10T11:52:26.615Z | 2024-07-10 11:52:26,613 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Failed to update database
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:122)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:85)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.storage.legacy.database.QuarkusJpaConnectionProviderFactory.update(QuarkusJpaConnectionProviderFactory.java:282)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.storage.legacy.database.QuarkusJpaConnectionProviderFactory.createOrUpdateSchema(QuarkusJpaConnectionProviderFactory.java:248)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.storage.legacy.database.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:125)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:105)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.createSessionFactory(QuarkusKeycloakApplication.java:64)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:91)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.onStartupEvent(QuarkusKeycloakApplication.java:51)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication_Observer_onStartupEvent_GNZ8m5QenZ9h9VNelo7awjUZFDE.notify(Unknown Source)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.runtime.Application.start(Application.java:101)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:139)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:35)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine.access$1500(CommandLine.java:148)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
  | 2024-07-10T11:52:26.615Z | at picocli.CommandLine.execute(CommandLine.java:2170)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:119)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:99)
  | 2024-07-10T11:52:26.615Z | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  | 2024-07-10T11:52:26.615Z | at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
  | 2024-07-10T11:52:26.615Z | at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
  | 2024-07-10T11:52:26.615Z | Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
  | 2024-07-10T11:52:26.615Z | Reason: liquibase.exception.DatabaseException: Duplicate foreign key constraint name 'FK_11B7SGQW18I532811V7O2DV76' [Failed SQL: (1826) ALTER TABLE keycloak.CLIENT_SESSION_ROLE ADD CONSTRAINT FK_11B7SGQW18I532811V7O2DV76 FOREIGN KEY (CLIENT_SESSION) REFERENCES keycloak.CLIENT_SESSION (ID)]
  | 2024-07-10T11:52:26.615Z | at liquibase.command.CommandScope.execute(CommandScope.java:253)
  | 2024-07-10T11:52:26.615Z | at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.lambda$child$0(Scope.java:186)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:195)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:185)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:164)
  | 2024-07-10T11:52:26.615Z | at liquibase.Liquibase.runInScope(Liquibase.java:1419)
  | 2024-07-10T11:52:26.615Z | at liquibase.Liquibase.update(Liquibase.java:234)
  | 2024-07-10T11:52:26.615Z | at liquibase.Liquibase.update(Liquibase.java:212)
  | 2024-07-10T11:52:26.615Z | at liquibase.Liquibase.update(Liquibase.java:194)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider.updateChangeSet(QuarkusJpaUpdaterProvider.java:192)
  | 2024-07-10T11:52:26.615Z | at org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:107)
  | 2024-07-10T11:52:26.615Z | ... 36 more
  | 2024-07-10T11:52:26.615Z | Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
  | 2024-07-10T11:52:26.615Z | Reason: liquibase.exception.DatabaseException: Duplicate foreign key constraint name 'FK_11B7SGQW18I532811V7O2DV76' [Failed SQL: (1826) ALTER TABLE keycloak.CLIENT_SESSION_ROLE ADD CONSTRAINT FK_11B7SGQW18I532811V7O2DV76 FOREIGN KEY (CLIENT_SESSION) REFERENCES keycloak.CLIENT_SESSION (ID)]
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:151)
  | 2024-07-10T11:52:26.615Z | at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.lambda$child$0(Scope.java:186)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:195)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:185)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:164)
  | 2024-07-10T11:52:26.615Z | at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
  | 2024-07-10T11:52:26.615Z | at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
  | 2024-07-10T11:52:26.615Z | at liquibase.command.CommandScope.execute(CommandScope.java:217)
  | 2024-07-10T11:52:26.615Z | ... 47 more
  | 2024-07-10T11:52:26.615Z | Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
  | 2024-07-10T11:52:26.615Z | Reason: liquibase.exception.DatabaseException: Duplicate foreign key constraint name 'FK_11B7SGQW18I532811V7O2DV76' [Failed SQL: (1826) ALTER TABLE keycloak.CLIENT_SESSION_ROLE ADD CONSTRAINT FK_11B7SGQW18I532811V7O2DV76 FOREIGN KEY (CLIENT_SESSION) REFERENCES keycloak.CLIENT_SESSION (ID)]
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.ChangeSet.execute(ChangeSet.java:797)
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.lambda$child$0(Scope.java:186)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:195)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:185)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:164)
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.lambda$child$0(Scope.java:186)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:195)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:185)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:164)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:252)
  | 2024-07-10T11:52:26.615Z | at liquibase.Scope.child(Scope.java:256)
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
  | 2024-07-10T11:52:26.615Z | ... 55 more
  | 2024-07-10T11:52:26.615Z | Caused by: liquibase.exception.DatabaseException: Duplicate foreign key constraint name 'FK_11B7SGQW18I532811V7O2DV76' [Failed SQL: (1826) ALTER TABLE keycloak.CLIENT_SESSION_ROLE ADD CONSTRAINT FK_11B7SGQW18I532811V7O2DV76 FOREIGN KEY (CLIENT_SESSION) REFERENCES keycloak.CLIENT_SESSION (ID)]
  | 2024-07-10T11:52:26.615Z | at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
  | 2024-07-10T11:52:26.615Z | at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
  | 2024-07-10T11:52:26.615Z | at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
  | 2024-07-10T11:52:26.615Z | at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1291)
  | 2024-07-10T11:52:26.615Z | at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1273)
  | 2024-07-10T11:52:26.615Z | at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
  | 2024-07-10T11:52:26.615Z | ... 70 more
  | 2024-07-10T11:52:26.615Z | Caused by: java.sql.SQLException: Duplicate foreign key constraint name 'FK_11B7SGQW18I532811V7O2DV76'
  | 2024-07-10T11:52:26.615Z | at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
  | 2024-07-10T11:52:26.615Z | at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  | 2024-07-10T11:52:26.615Z | at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:770)
  | 2024-07-10T11:52:26.615Z | at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653)
  | 2024-07-10T11:52:26.615Z | at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:220)
  | 2024-07-10T11:52:26.615Z | at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)

```

I check the table, the table already have the primary key as CLIENT_SESSION, so it occurs fail
how can i fix it?
```
mysql> show create table CLIENT_SESSION_ROLE;
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table               | Create Table                                                                                                                                                                                        |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CLIENT_SESSION_ROLE | CREATE TABLE `CLIENT_SESSION_ROLE` (
  `ROLE_ID` varchar(255) NOT NULL,
  `CLIENT_SESSION` varchar(36) NOT NULL,
  PRIMARY KEY (`CLIENT_SESSION`,`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

### Version

v15.0

### Regression

- [ ] The issue is a regression

### Expected behavior

it should upgrade successfully

### Actual behavior

it occurs exception while migration the database

### How to Reproduce?

I run the keycloak service in AWS ECS Fargate
and the database is mysql 8.0.37
upgrade from v15 to v25.0

**Comment by jonkoops** [comment]
Try moving from major version to major version, so from 15.x to 16.x, 17.x etc.
