### ISSUE TITLE
Quarkus trace log causing authentication request to fail with server error with special characters in the cookie

### ISSUE THREAD

**Issue by xiechangning20** [keycloak/keycloak#31202]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Quarkus trace log causing authentication request to fail with server error with special characters in the cookie
[org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-509) Uncaught server error: java.lang.IllegalArgumentException: control character in cookie value

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Able to authenticate with special characters present in the cookie

### Actual behavior

Unable to authenticate due to the error

### How to Reproduce?

1. Add cookie in the browser with value such as "é"
![image](https://github.com/keycloak/keycloak/assets/59653172/1a1f7d80-18f6-4b5b-a16c-13d0cfdeb93c)

2. Configure the quarkus logging as the following to log the cookie

```
quarkus.log.handler.console."EVENTS".enable=true
quarkus.log.handler.console."EVENTS".level=TRACE
quarkus.log.handler.console."EVENTS".format=[Keycloak] [Audit] %d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5p [%c] (%t) %s%e%n
quarkus.log.category."org.keycloak.events".level=TRACE
quarkus.log.category."org.keycloak.events".handlers=EVENTS
quarkus.log.category."org.keycloak.events".use-parent-handlers=false
```

3. Perform authentication action such as login into Keycloak Admin

4.  Will see similar error message as following
![image](https://github.com/keycloak/keycloak/assets/59653172/61c9bfde-513a-4e26-b058-9ed9f854f673)

5. From console will see it attempts to log the cookie value but throw an exception possibly due to incorrect cookie encoding
```
   [Keycloak] [Application] 2024-07-15T13:21:35.586Z ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-15) Uncaught server error: java.lang.IllegalArgumentException: control character in cookie value
2024-07-15T13:21:35.587297722Z 	at org.jboss.resteasy.reactive.common.headers.ServerCookie.maybeQuote2(ServerCookie.java:236)
2024-07-15T13:21:35.587299908Z 	at org.jboss.resteasy.reactive.common.headers.ServerCookie.appendCookieValue(ServerCookie.java:165)
2024-07-15T13:21:35.587301372Z 	at org.jboss.resteasy.reactive.common.headers.CookieHeaderDelegate.toString(CookieHeaderDelegate.java:20)
2024-07-15T13:21:35.587310700Z 	at org.jboss.resteasy.reactive.common.headers.CookieHeaderDelegate.toString(CookieHeaderDelegate.java:11)
2024-07-15T13:21:35.587312011Z 	at jakarta.ws.rs.core.Cookie.toString(Cookie.java:192)
2024-07-15T13:21:35.587313135Z 	at org.keycloak.events.log.JBossLoggingEventListenerProvider.setKeycloakContext(JBossLoggingEventListenerProvider.java:190)
2024-07-15T13:21:35.587314281Z 	at org.keycloak.events.log.JBossLoggingEventListenerProvider.logEvent(JBossLoggingEventListenerProvider.java:123)
2024-07-15T13:21:35.587315454Z 	at java.base/java.lang.Iterable.forEach(Unknown Source)
2024-07-15T13:21:35.587316578Z 	at org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
2024-07-15T13:21:35.587317707Z 	at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
2024-07-15T13:21:35.587318898Z 	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
2024-07-15T13:21:35.587320016Z 	at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
2024-07-15T13:21:35.587321162Z 	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
```

### Anything else?

Probably need similar encoding update like the following
https://github.com/keycloak/keycloak/pull/14560

Or parse the cookie value into UTF-8 Encoding

**Comment by xiechangning20** [comment]
Update:
Verified in the latest version: 25.0.1

**Comment by mposolda** [comment]
I afraid this is very low priority and Keycloak team does not prioritize this at the moment. There are few workarounds for this:

- Do not use custom cookies with strange characters. If support for strange characters is needed, the cookie can be possibly encoded somehow? (Maybe like Base64 format or something like that)

- Do not use trace logging (as the corresponding error is shown just when TRACE logging is enabled in `JBossLoggingEventListenerProvider`)

- Do not use `JBossLoggingEventListenerProvider` and track the events the other way
