### ISSUE TITLE
`Unexpected error when authenticating with identity provider` when using `Automatically set existing user` with the Google provider

### ISSUE THREAD

**Issue by cyanic-selkie** [keycloak/keycloak#31320]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

As per the docs, I created the following first broker login flow for the Google provider:

```
Create User If Unique - Alternative
Automatically set existing user - Alternative
```

The goal of this is to let users link their new Google accounts (which were deleted, then recreated with the same email) to their existing keycloak accounts.

However, when one such user tries to log in, they get the following error:

> Unexpected error when authenticating with identity provider

Edit: As it turns out, this error happens even when using the default reauthentication flow with email/password.

### Version

23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The new user Google account should link to the existing Keycloak account.

### Actual behavior

When one such user tries to log in, they get the error:
> Unexpected error when authenticating with identity provider

### How to Reproduce?

Set the following flow for the Google provider:

```
Create User If Unique - Alternative
Automatically set existing user - Alternative
```

Create a user, log in to a service using Keycloak, delete the Google account, recreate the Google account, log in again.

### Anything else?
Stack trace:
```
2024-07-16 11:09:42,578 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-159) SQL Error: 0, SQLState: 23505
2024-07-16 11:09:42,578 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-159) ERROR: duplicate key value violates unique constraint "constraint_40"
  Detail: Key (identity_provider, user_id)=(google, 48f05b52-904a-48c3-8ba6-4016a57705b1) already exists.
2024-07-16 11:09:42,578 WARN  [org.keycloak.events] (executor-thread-159) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="84f80bff-f7ac-4987-bbf5-c116671bcb8a", clientId="client-name", userId="48f05b52-904a-48c3-8ba6-4016a57705b1", ipAddress="<ip-address>", error="identityProviderUnexpectedErrorMessage", identity_provider="google", identity_provider_identity="test@domain.com", code_id="3962aa4b-cf0c-4bb7-bceb-502065219ba5", username="test@domain.com"
2024-07-16 11:09:42,578 ERROR [org.keycloak.services.resources.IdentityBrokerService] (executor-thread-159) identityProviderUnexpectedErrorMessage: org.keycloak.models.ModelDuplicateException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "constraint_40"
  Detail: Key (identity_provider, user_id)=(google, 48f05b52-904a-48c3-8ba6-4016a57705b1) already exists.
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:95)
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:64)
	at jdk.proxy2/jdk.proxy2.$Proxy67.flush(Unknown Source)
	at org.keycloak.models.jpa.JpaUserProvider.addFederatedIdentity(JpaUserProvider.java:171)
	at org.keycloak.storage.UserStorageManager.addFederatedIdentity(UserStorageManager.java:572)
	at org.keycloak.models.cache.infinispan.UserCacheSession.addFederatedIdentity(UserCacheSession.java:835)
	at org.keycloak.services.resources.IdentityBrokerService.afterFirstBrokerLogin(IdentityBrokerService.java:693)
	at org.keycloak.services.resources.IdentityBrokerService.afterFirstBrokerLogin(IdentityBrokerService.java:645)
	at org.keycloak.services.resources.IdentityBrokerService$quarkusrestinvoker$afterFirstBrokerLogin_2875cf30d412fd2f366643b0cfdc1bbfd26a9393.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "constraint_40"
  Detail: Key (identity_provider, user_id)=(google, 48f05b52-904a-48c3-8ba6-4016a57705b1) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at jdk.internal.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
	at jdk.proxy2/jdk.proxy2.$Proxy77.executeUpdate(Unknown Source)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:275)
	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:107)
	at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:40)
	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:52)
	at org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:171)
	at org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:112)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2790)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:102)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:635)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:502)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:364)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1412)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1398)
	at jdk.internal.reflect.GeneratedMethodAccessor526.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
	... 17 more
```

**Comment by cyanic-selkie** [comment]
@sschu Thanks! Updating to Keycloak version `>=25`, and updating the authorization flow to include the `Confirm Override Existing Link` worked.

Is there a plan to include an `Automatically Override Existing Link` authenticator?

**Comment by sschu** [comment]
I am not aware of any plans but I could imagine it is not hard to implement based on the existing one.

**Comment by sschu** [comment]
@daviddelannoy At least that's what we do internally, we have a custom authenticator that we can either configure to delete the IDP link or even the whole user in case a different IDP link already exists.
