### ISSUE TITLE
Every admin console login causes `Cannot invoke "org.keycloak.models.RealmModel.getMasterAdminClient()" because "realm" is null`

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#31400]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Every login to the admin console causes the following exception
```
2024-07-18 08:05:50,850 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getMasterAdminClient()" because "realm" is null
	at org.keycloak.services.resources.admin.AdminConsole.addMasterRealmAccess(AdminConsole.java:283)
	at org.keycloak.services.resources.admin.AdminConsole.whoAmI(AdminConsole.java:255)
	at org.keycloak.services.resources.admin.AdminConsole$quarkusrestinvoker$whoAmI_eaeea38b34c9e4843e24a94ba86a1ba4c8cf0402.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Expect no error.

### Actual behavior

Exception above, although everything else seems to work fine.

### How to Reproduce?

run `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HTTP_RELATIVE_PATH=/auth quay.io/keycloak/keycloak:25.0.2 start-dev`

go to `http://localhost:8080/auth/` and login as `admin:admin`

see the logs for the above exception

**Comment by ssilvert** [comment]
@xgp I'm not seeing this with 25.0.2.  The only difference is I'm not using Docker.

Is this an upgrade or a clean install?

**Comment by xgp** [comment]
@ssilvert Upgrade from `25.0.1`

**Comment by ssilvert** [comment]
@xgp OK.  We will need some way to reproduce.  Also, changing to core team since this is a back end NPE.

**Comment by xgp** [comment]
@ssilvert Thanks. In reproducing this, it seems to only happen when starting a previous version, loading the admin console, upgrading to `25.0.2`, and then trying to continue navigating, using and logging out/in of the admin console in the same tab. Perhaps some issue with cached assets in the react app? In any case, if you just open a new tab or do a hard refresh, the error goes away. Since there appears to be no adverse consequences, and it's just a log message that you can get to go away, I'm just going to close it.
