### ISSUE TITLE
AdvancedClaimToGroupMapper throws Exception if no claims are configured

### ISSUE THREAD

**Issue by Nikos410** [keycloak/keycloak#31575]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

Hello! 

If you configure an external ID profider and add an `AdvancedClaimToGroupMapper` without adding any claims, the login fails with the message "Unexpected error when authenticating with identity provider". In the Keycloak log message `java.lang.IllegalArgumentException: argument "content" is null` can be found.

### Version

24.0.3 / 25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The login should succeed, the mapper should have no effect since no claims are configured. Also, it might be sensible to validate the configuration to prevent saving an incomplete configuration

### Actual behavior

The login fails with the message "Unexpected error when authenticating with identity provider". From the keycloak log:
```
24.7.2024, 07:57:30 2024-07-24 05:57:30,436 WARN [org.keycloak.events] (executor-thread-77195) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="REDACTED", clientId="REDACTED", userId="null", ipAddress="REDACTED", error="identity_provider_login_failure", identity_provider="REDACTED", redirect_uri="REDACTED", identity_provider_identity="REDACTED", code_id="REDACTED" - 33d2b259
24.7.2024, 07:57:35 2024-07-24 05:57:35,071 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-77195) Failed to make identity provider oauth callback: java.lang.IllegalArgumentException: argument "content" is null
24.7.2024, 07:57:35 at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:5054)
24.7.2024, 07:57:35 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3828)
24.7.2024, 07:57:35 at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:83)
24.7.2024, 07:57:35 at org.keycloak.models.IdentityProviderMapperModel.getConfigMap(IdentityProviderMapperModel.java:101)
24.7.2024, 07:57:35 at org.keycloak.broker.oidc.mappers.AdvancedClaimToGroupMapper.applies(AdvancedClaimToGroupMapper.java:103)
24.7.2024, 07:57:35 at org.keycloak.broker.oidc.mappers.AbstractClaimToGroupMapper.updateBrokeredUser(AbstractClaimToGroupMapper.java:64)
24.7.2024, 07:57:35 at org.keycloak.broker.provider.IdentityProviderMapperSyncModeDelegate.delegateUpdateBrokeredUser(IdentityProviderMapperSyncModeDelegate.java:25)
24.7.2024, 07:57:35 at org.keycloak.services.resources.IdentityBrokerService.lambda$updateFederatedIdentity$2(IdentityBrokerService.java:1010)
24.7.2024, 07:57:35 at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
24.7.2024, 07:57:35 at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
24.7.2024, 07:57:35 at org.keycloak.services.resources.IdentityBrokerService.updateFederatedIdentity(IdentityBrokerService.java:1007)
24.7.2024, 07:57:35 at org.keycloak.services.resources.IdentityBrokerService.authenticated(IdentityBrokerService.java:613)
24.7.2024, 07:57:35 at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:565)
24.7.2024, 07:57:35 at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_fef2d69ce31937f365a37fb3083f9247bc4c56d2.invoke(Unknown Source)
24.7.2024, 07:57:35 at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
24.7.2024, 07:57:35 at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
24.7.2024, 07:57:35 at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
24.7.2024, 07:57:35 at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
24.7.2024, 07:57:35 at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
24.7.2024, 07:57:35 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
24.7.2024, 07:57:35 at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
24.7.2024, 07:57:35 at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
24.7.2024, 07:57:35 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
24.7.2024, 07:57:35 at java.base/java.lang.Thread.run(Thread.java:840)
24.7.2024, 07:57:35 - 2a6c3409
```

### How to Reproduce?

Configure an external id provider and add an `AdvancedClaimToGroupMapper` without adding any claims, like this:
![image](https://github.com/user-attachments/assets/76fe0d4a-ad80-4f8a-9273-5728a8b87175)

Try to login in using the external IDP

### Anything else?

Should I try to implement a fix for this issue? At first glance, it should be sufficient to add a null check [here](https://github.com/keycloak/keycloak/blob/9f2eddead8a6cf06de9be8c3038dded4daf3a727/server-spi/src/main/java/org/keycloak/models/IdentityProviderMapperModel.java#L98) to prevent passing a null object to `JsonSerialization.readValue`, Like this:

```java
public Map<String, String> getConfigMap(String configKey) {
        String configMap = config.get(configKey);
        if (configMap == null) {
            return emptyMap();
        }

        try {
            List<StringPair> map = JsonSerialization.readValue(configMap, MAP_TYPE_REPRESENTATION);
            return map.stream().collect(Collectors.toMap(StringPair::getKey, StringPair::getValue));
        } catch (IOException e) {
            throw new RuntimeException("Could not deserialize json: " + configMap, e);
        }
    }
```

I can open a PR and try to implement a test case for this, if you want :)

**Comment by martin-kanis** [comment]
@Nikos410 Thanks for reporting this. A PR with the `null` check and a testcase would be welcomed :)
