### ISSUE TITLE
GroupModel.getSubGroupsStream() -> "Cannot access delegate without a transaction"

### ISSUE THREAD

**Issue by xXAvoraXx** [keycloak/keycloak#31800]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I am developing a custom event publisher that listens to keycloak events. When groups are deleted, I need to access the information of subgroups and when I use the getSubGroupsStream() api for this, I get the following error.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

fetch to subGroups.

### Actual behavior

Error ->

```
java.lang.IllegalStateException: Cannot access delegate without a transaction
java.lang.IllegalStateException: Cannot access delegate without a transaction
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getGroupDelegate(RealmCacheSession.java:169)
	at org.keycloak.models.cache.infinispan.GroupAdapter.getGroupModel(GroupAdapter.java:286)
	at org.keycloak.models.cache.infinispan.DefaultLazyLoader.get(DefaultLazyLoader.java:42)
	at org.keycloak.models.cache.infinispan.entities.CachedGroup.getSubGroups(CachedGroup.java:82)
	at org.keycloak.models.cache.infinispan.GroupAdapter.getSubGroupsStream(GroupAdapter.java:228)
	at com.twogenidentity.keycloak.event.EventParser.getSubGroupsInRealm(EventParser.java:204)
	at com.twogenidentity.keycloak.utils.OpenFgaHelper.toGroupClientWriteRequest(OpenFgaHelper.java:160)
	at com.twogenidentity.keycloak.utils.OpenFgaHelper.toClientWriteRequest(OpenFgaHelper.java:207)
	at com.twogenidentity.keycloak.service.OpenFgaClientHandler.publish(OpenFgaClientHandler.java:61)
	at com.twogenidentity.keycloak.OpenFgaEventListenerProvider.onEvent(OpenFgaEventListenerProvider.java:40)
	at org.keycloak.services.resources.admin.AdminEventBuilder.send(AdminEventBuilder.java:290)
	at org.keycloak.services.resources.admin.AdminEventBuilder.success(AdminEventBuilder.java:272)
	at org.keycloak.services.resources.admin.GroupResource.deleteGroup(GroupResource.java:159)
	at org.keycloak.services.resources.admin.GroupResource$quarkusrestinvoker$deleteGroup_667dc37b48fffd7ca38c3c80e6fa502e6dc0a9eb.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

    public Iterable<GroupModel> getSubGroupsInRealm(String groupId) {
        RealmModel realm = session.getContext().getRealm();
        GroupModel group = realm.getGroupById(groupId);

        try {
            List<GroupModel> subGroups = group.getSubGroupsStream().collect(Collectors.toList());
            return subGroups;
        } catch (Exception e) {
            LOG.debugf("Error: %s", e);
            e.printStackTrace();
        }

        return null;
    }

### Anything else?

```
package com.twogenidentity.keycloak;


import dev.openfga.sdk.errors.FgaInvalidParameterException;
import com.twogenidentity.keycloak.service.OpenFgaClientHandler;
import org.keycloak.Config.Scope;
import org.keycloak.events.EventListenerProvider;
import org.keycloak.events.EventListenerProviderFactory;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.KeycloakSessionFactory;

public class OpenFgaEventListenerProviderFactory implements EventListenerProviderFactory {

	private static final String PROVIDER_ID = "openfga-events-publisher";
	private OpenFgaEventListenerProvider instance;
	private Scope config;
	private OpenFgaClientHandler client;

	@Override
	public EventListenerProvider create(KeycloakSession session) {
		if (client == null) {
			try {
				client = new OpenFgaClientHandler(config);
			} catch (FgaInvalidParameterException e) {
				throw new RuntimeException(e);
			}
			instance = new OpenFgaEventListenerProvider(client, session);
		}
		return instance;
	}

	@Override
	public String getId() {
		return PROVIDER_ID;
	}

	@Override
	public void init(Scope config) {
		this.config = config;

	}

	@Override
	public void postInit(KeycloakSessionFactory arg0) {
		// ignore
	}

	@Override
	public void close() {
		// ignore
	}
}

package com.twogenidentity.keycloak;

import dev.openfga.sdk.errors.FgaInvalidParameterException;
import com.twogenidentity.keycloak.event.EventParser;
import com.twogenidentity.keycloak.service.OpenFgaClientHandler;
import org.jboss.logging.Logger;
import org.keycloak.events.Event;
import org.keycloak.events.EventListenerProvider;
import org.keycloak.events.admin.AdminEvent;
import org.keycloak.models.KeycloakSession;

import java.util.concurrent.ExecutionException;

public class OpenFgaEventListenerProvider implements EventListenerProvider {
	private static final Logger LOG = Logger.getLogger(OpenFgaEventListenerProvider.class);
	private OpenFgaClientHandler client;
	private KeycloakSession session;

	public OpenFgaEventListenerProvider(OpenFgaClientHandler client, KeycloakSession session) {
		this.client = client;
		this.session = session;
	}

	@Override
	public void onEvent(Event event) {
		LOG.debug("Discarding onEvent() type: " + event.getType().toString());
	}

	@Override
	public void onEvent(AdminEvent adminEvent, boolean includeRepresentation) {
		LOG.debugf("Admin event received onEvent(): %s ", adminEvent.toString());

		try {
			EventParser event = new EventParser(adminEvent, session);
			LOG.debugf("Event parsed: %s ", event.toString());
			if(event.isGroupEvent() || event.isRoleEvent() || event.isUserEvent()){
				client.publish(adminEvent.getId(), event);
			}
		} catch (IllegalArgumentException e) {
			LOG.warn(e.getMessage());
		}
		catch (ExecutionException | InterruptedException e) {
			throw new RuntimeException(e);
		} catch (FgaInvalidParameterException e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public void close() {
		// ignore
	}
}

```

_No response_

**Comment by mhajas** [comment]
Without the rest of the code, it is hard to tell where exactly your issue is.

It seems you are either not using the same `KeycloakSession` as the code that produced the event or there was a `commit` call before the `getSubGroupsInRealm` was called. 

Can you share more details? 

> I found this solution but I dont know is a good solution or not.
> 
> ```
>     public Iterable<GroupModel> getSubGroupsInRealm(String groupId) {
> 
>         var groups = new ArrayList<GroupModel>();
> 
>         KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(), s -> {
>                 RealmModel realm = session.realms().getRealm(event.getRealmId());
>                 List<GroupModel> subGroups = s.groups().getGroupById(realm, groupId).getSubGroupsStream().collect(Collectors.toList());
>                 groups.addAll(subGroups);
>         });
> 
>         return groups;
>     }
> ```

This should work. What it essentially does is it creates a new Keycloak session and executes the query there, however, with what you shared I don't see any problem why it should not work in the original session.

**Comment by xXAvoraXx** [comment]
> Without the rest of the code, it is hard to tell where exactly your issue is.
> 
> It seems you are either not using the same `KeycloakSession` as the code that produced the event or there was a `commit` call before the `getSubGroupsInRealm` was called.
> 
> Can you share more details?
> 
> > I found this solution but I dont know is a good solution or not.
> > ```
> >     public Iterable<GroupModel> getSubGroupsInRealm(String groupId) {
> > 
> >         var groups = new ArrayList<GroupModel>();
> > 
> >         KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(), s -> {
> >                 RealmModel realm = session.realms().getRealm(event.getRealmId());
> >                 List<GroupModel> subGroups = s.groups().getGroupById(realm, groupId).getSubGroupsStream().collect(Collectors.toList());
> >                 groups.addAll(subGroups);
> >         });
> > 
> >         return groups;
> >     }
> > ```
> 
> This should work. What it essentially does is it creates a new Keycloak session and executes the query there, however, with what you shared I don't see any problem why it should not work in the original session.

The source code is available here. All I did was to create a new method in the EventParser class. The rest of the code is all the same.
https://github.com/embesozzi/keycloak-openfga-event-publisher

**Comment by mhajas** [comment]
I checked the code and it seems there are also some changes done in the [`OpenFgaHelper.java`](https://github.com/embesozzi/keycloak-openfga-event-publisher/blob/main/src/main/java/com/twogenidentity/keycloak/utils/OpenFgaHelper.java).

Based on the exception from the report:
```
at com.twogenidentity.keycloak.utils.OpenFgaHelper.toGroupClientWriteRequest(OpenFgaHelper.java:160)
at com.twogenidentity.keycloak.utils.OpenFgaHelper.toClientWriteRequest(OpenFgaHelper.java:207)
```

Your class has more lines and an additional method `toGroupClientWriteRequest`. Can you share that code as well?

**Comment by xXAvoraXx** [comment]
> I checked the code and it seems there are also some changes done in the [`OpenFgaHelper.java`](https://github.com/embesozzi/keycloak-openfga-event-publisher/blob/main/src/main/java/com/twogenidentity/keycloak/utils/OpenFgaHelper.java).
> 
> Based on the exception from the report:
> 
> ```
> at com.twogenidentity.keycloak.utils.OpenFgaHelper.toGroupClientWriteRequest(OpenFgaHelper.java:160)
> at com.twogenidentity.keycloak.utils.OpenFgaHelper.toClientWriteRequest(OpenFgaHelper.java:207)
> ```
> 
> Your class has more lines and an additional method `toGroupClientWriteRequest`. Can you share that code as well?

  ```
  private ClientWriteRequest toGroupClientWriteRequest(ClientWriteRequest client, EventParser event)
            throws FgaInvalidParameterException, InterruptedException, ExecutionException {
        List<ClientTupleKey> tuples = new ArrayList<ClientTupleKey>();

        List<ClientTupleKey> coreGroupTuples = new ArrayList<ClientTupleKey>();

        String groupId = (event.isWriteOperation() ? event.getEventObjectId() : event.getEventUserId());

        coreGroupTuples.add(new ClientTupleKey()
                .user("parent_group:" + groupId)
                .relation("assignee")
                ._object("group:" + groupId));
        coreGroupTuples.add(new ClientTupleKey()
                .user("member_group:" + groupId)
                .relation("assignee")
                ._object("group:" + groupId));

        tuples.addAll(coreGroupTuples);

        if (event.isWriteOperation()) {

            if (event.isEventUserChildOfObject()) {

                tuples.add(new ClientTupleKey()
                        .user("parent_group:" + event.getEventUserId()) // ebeveyn Id resourcePath içerisinde
                        .relation("parent")
                        ._object("parent_group:" + event.getEventObjectId()));

                tuples.add(new ClientTupleKey()
                        .user("member_group:" + event.getEventObjectId())
                        .relation("assignee")
                        ._object("member_group:" + event.getEventUserId()));
            }

            tuples.forEach(tuple -> modelHelper.isRelationAvailableInModel(tuple));

            client.writes(tuples);
        } else if (event.isDeleteOperation()) {


            GroupModel parentGroup = event.findGroupParentInRealm(groupId);

            if (parentGroup != null) {
                
                Iterable<GroupModel> subgroups = event.getSubGroupsByParentId(parentGroup.getId());
            }

        }

        return client;
    }

    public ClientWriteRequest toClientWriteRequest(EventParser event)
            throws FgaInvalidParameterException, InterruptedException, ExecutionException {

        ClientWriteRequest client = new ClientWriteRequest();

        if (event.isGroupEvent() && event.getEventObjectType() == "group") {
            return toGroupClientWriteRequest(client, event);
        }

        return toSingleClientWriteRequest(event, client);
    }

    private ClientWriteRequest toSingleClientWriteRequest(EventParser event, ClientWriteRequest client) {
        String eventUserType = event.getEventUserType();
        String eventUserId = event.getEventUserId();

        String eventObjectType = event.getEventObjectType();
        String eventObjectId = event.getEventObjectId();

        String relation = getRelationFromModel(eventObjectType, eventUserType, event);

        ClientTupleKey tuple = new ClientTupleKey()
                .user(eventUserType + ":" + eventUserId)
                .relation(relation)
                ._object(eventObjectType + ":" + eventObjectId);

        if (modelHelper.isRelationAvailableInModel(tuple)) {
            LOG.debugf("Tuple %s %s %s", tuple.getUser(), tuple.getRelation(), tuple.getObject());

            if (event.isWriteOperation()) {
                client.writes(List.of(tuple));
            } else if (event.isDeleteOperation()) {
                client.deletes(List.of(tuple));
            }
        } else {
            LOG.warnf("Relation %s not found in model for key: %s", relation, eventObjectType + eventUserType);
        }

        return client;
    }


// EventParser --> event.getSubGroupsByParentId

    public Iterable<GroupModel> getSubGroupsByParentId(String groupId) {

        List<GroupModel> groups = new ArrayList<GroupModel>();

        KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(), s -> {
                RealmModel realm = session.realms().getRealm(event.getRealmId());
                List<GroupModel> subGroups = s.groups().getGroupById(realm, groupId).getSubGroupsStream().collect(Collectors.toList());
                groups.addAll(subGroups);
        });

        return groups;
    }

```

**Comment by mhajas** [comment]
Thank you for sharing the additional code. I can't see any issue that could cause the failure you encountered.

If I understand correctly, you sent me the version of the method that is working without the exception, however, the failing method was:
```
public Iterable<GroupModel> getSubGroupsInRealm(String groupId) {
    RealmModel realm = session.getContext().getRealm();
    GroupModel group = realm.getGroupById(groupId);

    try {
        List<GroupModel> subGroups = group.getSubGroupsStream().collect(Collectors.toList());
        return subGroups;
    } catch (Exception e) {
        LOG.debugf("Error: %s", e);
        e.printStackTrace();
    }

    return null;
}
```

Can you please try to get back to the failing version of the method and replace: 
```
RealmModel realm = session.getContext().getRealm();
```
with 
```
RealmModel realm = session.realms().getRealm(event.getRealmId());
```

**Comment by xXAvoraXx** [comment]
I tried `RealmModel realm = session.realms().getRealm(event.getRealmId());` but not working.

```
2024-08-01 14:00:38,761 DEBUG [com.twogenidentity.keycloak.event.EventParser] (executor-thread-5) Error: java.lang.IllegalStateException: Cannot access delegate without a transaction
java.lang.IllegalStateException: Cannot access delegate without a transaction
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getGroupDelegate(RealmCacheSession.java:169)
	at org.keycloak.models.cache.infinispan.GroupAdapter.getGroupModel(GroupAdapter.java:286)
	at org.keycloak.models.cache.infinispan.DefaultLazyLoader.get(DefaultLazyLoader.java:42)
	at org.keycloak.models.cache.infinispan.entities.CachedGroup.getSubGroups(CachedGroup.java:82)
	at org.keycloak.models.cache.infinispan.GroupAdapter.getSubGroupsStream(GroupAdapter.java:228)
	at com.twogenidentity.keycloak.event.EventParser.getSubGroupsByParentId(EventParser.java:224)
	at com.twogenidentity.keycloak.utils.OpenFgaHelper.deleteGroupRelations(OpenFgaHelper.java:162)
	at com.twogenidentity.keycloak.utils.OpenFgaHelper.toGroupClientWriteRequest(OpenFgaHelper.java:100)
	at com.twogenidentity.keycloak.utils.OpenFgaHelper.startRequest(OpenFgaHelper.java:52)
	at com.twogenidentity.keycloak.service.OpenFgaClientHandler.publish(OpenFgaClientHandler.java:54)
	at com.twogenidentity.keycloak.OpenFgaEventListenerProvider.onEvent(OpenFgaEventListenerProvider.java:37)
	at org.keycloak.services.resources.admin.AdminEventBuilder.send(AdminEventBuilder.java:290)
	at org.keycloak.services.resources.admin.AdminEventBuilder.success(AdminEventBuilder.java:272)
	at org.keycloak.services.resources.admin.GroupResource.deleteGroup(GroupResource.java:159)
	at org.keycloak.services.resources.admin.GroupResource$quarkusrestinvoker$deleteGroup_667dc37b48fffd7ca38c3c80e6fa502e6dc0a9eb.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mhajas** [comment]
Thanks for trying it out and sharing the output. Unfortunately, from the top of my head,d I can't see any issue with the code you provided. 

The last thing I can do is try it out locally and debug what is happening. Could you provide something that would help me run this locally? The best thing would be if you push the whole source code of the extension to a Github repository.

**Comment by xXAvoraXx** [comment]
The source code is available here. Install the event publisher below, then define the following method in the EventParser.java class and try to call it, you will get an error.

https://github.com/embesozzi/keycloak-openfga-event-publisher



Try deleting a group with child groups and call the following method.
```
public Iterable<GroupModel> getSubGroupsInRealm(String groupId) {
    RealmModel realm = session.getContext().getRealm();
    GroupModel group = realm.getGroupById(groupId);

    try {
        List<GroupModel> subGroups = group.getSubGroupsStream().collect(Collectors.toList());
        return subGroups;
    } catch (Exception e) {
        LOG.debugf("Error: %s", e);
        e.printStackTrace();
    }

    return null;
}
```

**Comment by mhajas** [comment]
The reason for the exception is how the `OpenFgaEventListenerProviderFactory` initializes the provider.

This method:
https://github.com/embesozzi/keycloak-openfga-event-publisher/blob/57c578b64d528f813cfa7a14bf4baf165317cd17/src/main/java/com/twogenidentity/keycloak/OpenFgaEventListenerProviderFactory.java#L19-L30

Is caching the provider instance including the instance of `KeycloakSession` from the first call. If you change it to the following it will work.
```java
	@Override
	public EventListenerProvider create(KeycloakSession session) {
		if (client == null) {
			try {
				client = new OpenFgaClientHandler(config);
			} catch (FgaInvalidParameterException e) {
				throw new RuntimeException(e);
			}
		}
		return new OpenFgaEventListenerProvider(client, session);
	}
```

Since this is not an issue in the Keycloak codebase I am closing.
