### ISSUE TITLE
Failure to generate Ed448 token

### ISSUE THREAD

**Issue by berlix** [keycloak/keycloak#31931]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Keycloak's OIDC `token` endpoint returns a `500` error when trying to obtain an Ed448 token, and Keycloak's logs show a `NullPointerException`.

### Version

Verified on 25.0.1 and 25.0.2. Have not tried any other versions.

### Regression

I do not know if this issue is a regression.

### Expected behavior

The OIDC `token` endpoint returns an Ed448 token if so configured.

### Actual behavior

The OIDC `token` endpoint returns a `500` error with the following body:

```
{"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."}
```

Keycloak emits this `NullPointerException` on its logs:

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.crypto.HashProvider.hash(String)" because "hashProvider" is null
        at org.keycloak.protocol.oidc.TokenManager$AccessTokenResponseBuilder.generateOIDCHash(TokenManager.java:1304)
        at org.keycloak.protocol.oidc.TokenManager$AccessTokenResponseBuilder.build(TokenManager.java:1253)
        at org.keycloak.protocol.oidc.grants.OAuth2GrantTypeBase.createTokenResponse(OAuth2GrantTypeBase.java:147)
        at org.keycloak.protocol.oidc.grants.AuthorizationCodeGrantType.process(AuthorizationCodeGrantType.java:207)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:140)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

1. Start with a fresh Keycloak install based on Docker image `quay.io/keycloak/keycloak:25.0.2` (I use Postgres for persistence, though that's probably irrelevant).
2. Using the Keycloak web console, configure the `master` realm to use EdDSA for tokens, create a key provider for EdDSA with Ed448, and move it to the top of the list of providers.
3. Log out of the web console.
4. Open the browser's developer tools and its Network tab.
5. Attempt to log back into the Keycloak web console. Observe the response from the `token` endpoint in the browser's developer tools. Find the `NullPointerException` in the Keycloak logs.

### Anything else?

Note that this issue seems to affect only EdDSA with Ed448. Unaffected are EdDSA with Ed25519, as well as the various RS/PS/ES algorithms.

**Comment by rmartinc** [comment]
@berlix Yes, you are right, the SHAKE256 hash provider is missing, which is the one that uses Ed448. I suppose we didn't test the ID token with Ed448. You can use Ed25519 for the moment (it uses SHA512).
