### ISSUE TITLE
UMA does not work when using lightweight token

### ISSUE THREAD

**Issue by PRIESt512** [keycloak/keycloak#31989]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I am using quarkus version 3.13.1
Based on the documentation (https://quarkus.io/guides/security-openid-connect-dev-services) enabled the parameter quarkus.keycloak.policy-enforcer.enable=true

For the client I enabled "Always use lightweight access token".
As a result, the application does not start.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

At this point I think the app should launch correctly.

### Actual behavior

Stacktrace:

```
Caused by: org.keycloak.authorization.client.AuthorizationDeniedException: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 403 / Forbidden / Response from server: {"error":"invalid_scope","error_description":"Requires uma_protection scope."}
	at org.keycloak.authorization.client.util.Throwables.handleAndWrapHttpResponseException(Throwables.java:96)
	at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:42)
	at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:87)
	at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:182)
Caused by: org.keycloak.authorization.client.AuthorizationDeniedException: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 403 / Forbidden / Response from server: {"error":"invalid_scope","error_description":"Requires uma_protection scope."}
```

### How to Reproduce?

Perform keycloak settings based on [docs](https://quarkus.io/guides/security-openid-connect-dev-services)

For the client, please specify -> Always use lightweight access token

### Anything else?

I'm not sure I understand the problem correctly. Maybe I need to adjust something.

**Comment by Jukien** [comment]
Hi, I don't know if it is the same issue but I have the same error when I disable **Add to access token** for _client roles_ mapper of the _Roles_ client scope.

Keycloak v25.0.6
Spring Boot v3.3.4

![image](https://github.com/user-attachments/assets/ad4383e7-9f56-484c-9ef9-859d32975092)

```
Caused by: org.keycloak.authorization.client.AuthorizationDeniedException: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 403 / Forbidden / Response from server: {"error":"invalid_scope","error_description":"Requires uma_protection scope."}
	at org.keycloak.authorization.client.util.Throwables.handleAndWrapHttpResponseException(Throwables.java:96) ~[keycloak-authz-client-25.0.6.jar:25.0.6]
	at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:42) ~[keycloak-authz-client-25.0.6.jar:25.0.6]
	at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:87) ~[keycloak-authz-client-25.0.6.jar:25.0.6]
	at org.keycloak.authorization.client.resource.ProtectedResource.find(ProtectedResource.java:182) ~[keycloak-authz-client-25.0.6.jar:25.0.6]
	at org.keycloak.authorization.client.resource.ProtectedResource.findAll(ProtectedResource.java:247) ~[keycloak-authz-client-25.0.6.jar:25.0.6]
	... 81 common frames omitted
Caused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 403 / Forbidden
```

**Comment by vmuzikar** [comment]
@PRIESt512 Thank you for the report however you seem to be having issues with the Dev Services in Quarkus. I'd suggest opening the issue [there](https://github.com/quarkusio/quarkus/issues).

@Jukien If the issue is still valid, please open a separate bug report. That'd help us with tracking it more easily. Thank you.

**Comment by mvmn** [comment]
Worked for me with realm roles mapper
