### ISSUE TITLE
error message "Address already in use" should state which address/port in particular

### ISSUE THREAD

**Issue by ecerulm** [keycloak/keycloak#32198]
### Description

On  keycloack 25.0.2
```
KEYCLOAK_ADMIN=admin KEYCLOAK_ADMIN_PASSWORD=admin bin/kc.sh start-dev
2024-08-16 13:42:03,529 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-08-16 13:42:04,285 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-08-16 13:42:04,366 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_625156, Site name: null
2024-08-16 13:42:05,298 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-08-16 13:42:05,347 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-08-16 13:42:05,347 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2024-08-16 13:42:05,348 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.lang.IllegalStateException: Unable to start the management interface
2024-08-16 13:42:05,348 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start the management interface
2024-08-16 13:42:05,348 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Address already in use
2024-08-16 13:42:05,348 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

the error `ERROR: Address already in use` I guess it's correct but it does not help me to find what in particular is failing. 

I eventually figured out that keycloak by default is using :8080 and :9000 so it had to be one of those.  So running `bin/kc.sh start-dev --http-management-port 9002` got rid of the problem. 

But I think the error message should be improve like  this 

```
2024-08-16 13:42:05,348 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Address already in use (0.0.0.0:9000) 

```

or 
```
2024-08-16 13:42:05,348  INFO [io.quarkus] (main) Trying management interface on http://0.0.0.0:9000.
2024-08-16 13:42:05,348 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Address already in use
```

### Motivation

Well, it will save some time and confusion specially for beginners, that may not understand that keycloack is using other ports beside 8080.

**Comment by shawkins** [comment]
You should be able to see the port in question using the verbose option correct? 

This would ideally be addressed from the quarkus side as we're just relaying the exception message.

**Comment by Dessa** [comment]
> You should be able to see the port in question using the verbose option correct?

unfortunately, no, this is all i get, although maybe its because im not running dev? not sure.

```
2024-08-18 03:19:56,995 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-08-18 03:19:56,995 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Unable to start HTTP server
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:834)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:315)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:139)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:119)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:99)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unable to start the management interface
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:760)
        ... 23 more
Caused by: java.lang.IllegalStateException: Unable to start the management interface
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder.lambda$initializeManagementInterface$2(VertxHttpRecorder.java:629)
        at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:316)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:565)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:426)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:375)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:557)
        ... 4 more
```

**Comment by Pramodnm** [comment]
Had same issue, not sure why 9000 port it was trying to use.

**Comment by ecerulm** [comment]
> Had same issue, not sure why 9000 port it was trying to use.

@Pramodnm, Keycloak will use port 9000 for the management interface: https://www.keycloak.org/server/management-interface



> You should be able to see the port in question using the verbose option correct?

@shawkins. If you meant `bin/kc.sh start-dev -v` then no, it does not print any mention of port 9000. It just says`Unable to start the management interface` like before, but it's even harder to understand with the stacktrace printout:

``` KEYCLOAK_ADMIN=admin KEYCLOAK_ADMIN_PASSWORD=admin bin/kc.sh start-dev -v
2024-08-18 18:11:22,403 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-08-18 18:11:22,795 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-08-18 18:11:22,804 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_498252, Site name: null
2024-08-18 18:11:23,382 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-08-18 18:11:23,403 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-08-18 18:11:23,403 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Unable to start HTTP server
	...
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unable to start the management interface
  ...
Caused by: java.lang.IllegalStateException: Unable to start the management interface
  ...
Caused by: java.net.BindException: Address already in use
  ...
```

The original message already had the same information; 

```
ERROR: Failed to start server in (development) mode
ERROR: Unable to start HTTP server
ERROR: java.lang.IllegalStateException: Unable to start the management interface
ERROR: Unable to start the management interface
ERROR: Address already in use
```

which already say that `Unable to start the management interface`, it's just that is not clear management interface means 9000 without looking at the documentation. 

> This would ideally be addressed from the quarkus side as we're just relaying the exception message.

Yes, I guess that ideally this could be handled on Quarkus (I've opened https://github.com/quarkusio/quarkus/issues/42614 )

But I assume that Keycloak can catch this Exception and since Keycloak knows what ports it's trying to use could at least print something like `ERROR while listening on ports 8080 or 9000`, or print something before starting the server altogether like 

```
Trying to start management interface on port :9000
ERROR: Failed to start server in (development) mode
ERROR: Unable to start HTTP server
ERROR: java.lang.IllegalStateException: Unable to start the management interface
ERROR: Unable to start the management interface
ERROR: Address already in use
```

**Comment by shawkins** [comment]
> @shawkins. If you meant bin/kc.sh start-dev -v then no, it does not print any mention of port 9000. It just saysUnable to start the management interface like before, but it's even harder to understand with the stacktrace printout:

Yes, that is what I meant. It's unfortunate that it doesn't make it clearer.

> Yes, I guess that ideally this could be handled on Quarkus (I've opened https://github.com/quarkusio/quarkus/issues/42614 )

It looks like there is already a fix - thanks @gsmet

Moving out of triage - as we'll just wait for the upstream fix.
