### ISSUE TITLE
Keycloak Authorization Error - StackOverflowError During Permission Evaluation

### ISSUE THREAD

**Issue by chornthorn** [keycloak/keycloak#32326]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

I'm encountering an unexpected error while evaluating permissions in Keycloak, which leads to a java.lang.StackOverflowError. The error occurs when I send a request to the Keycloak server using the following cURL command:

``` bash
curl --location 'https://keycloak.dev.prometeus-kc.com/realms/prometeus-kc/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Bearer <token-here>' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:uma-ticket' \
--data-urlencode 'audience=hr'
```

This issue is causing a significant disruption in our authentication flow. The stack trace indicates that the problem is occurring in the AuthorizationTokenService, specifically in the evaluateAllPermissions function:

```java
2024-08-22 05:11:05,397 ERROR [org.keycloak.authorization.authorization.AuthorizationTokenService] (executor-thread-26) Unexpected error while evaluating permissions: java.lang.RuntimeException: Failed to evaluate permissions
    at org.keycloak.authorization.policy.evaluation.DecisionPermissionCollector.onError(DecisionPermissionCollector.java:182)
    ...
Caused by: java.lang.StackOverflowError
    at org.keycloak.models.cache.infinispan.authorization.PolicyAdapter.getAssociatedPolicies(PolicyAdapter.java:203)
    at org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:49)
    ...
```

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

When making a request to the Keycloak server using the aforementioned cURL command, the server should successfully evaluate permissions without throwing any errors. The AuthorizationTokenService should be able to evaluate all permissions, and the process should not result in a java.lang.StackOverflowError. The response should contain the appropriate authorization information based on the provided token and request parameters. This behavior is critical to ensure the smooth operation of our authentication and authorization flow.

### Actual behavior

When making a request to the Keycloak server using the aforementioned cURL command, the server throws a java.lang.StackOverflowError during the permission evaluation process.

As a result of this error, the Keycloak server returns a HTTP 500 status code with the following response:

```json
{
    "error": "server_error",
    "error_description": "Unexpected error while evaluating permissions"
}
```

### How to Reproduce?

How to Reproduce:

Setup Keycloak Server: Install and set up a Keycloak server with the necessary realms, clients, roles, and permissions. Ensure that the server is running and accessible.

Configure Authorization: Enable and configure the authorization settings for a client in the Keycloak server. Set up a policy with associated policies, creating a recursive relationship.

Generate Access Token: Use a client that has been granted the necessary permissions to generate an access token.

Send Request: Make a request to the Keycloak server using the generated access token. The request should be made to the /protocol/openid-connect/token endpoint of the Keycloak server. Here is an example of such a request using cURL:

```bash
curl --location 'https://keycloak.dev.prometeus-kc.com/realms/prometeus-kc/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Bearer {access-token}' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:uma-ticket' \
--data-urlencode 'audience=hr'
```
Observe Error: Upon sending the request, the server will return a HTTP 500 status code with the following response:

```json
{
    "error": "server_error",
    "error_description": "Unexpected error while evaluating permissions"
}
```

### Anything else?

Note: Some clients of Keycloak are working as expected, but others are not

**Comment by pedroigor** [comment]
@chornthorn In order to understand what is causing the error we need a reproducer. In a regular configuration, we cannot reproduce this and I suspect it might be related to how permissions and policies are configured.
