### ISSUE TITLE
Failed imports in Keycloak JavaScript resources when creating a customized theme

### ISSUE THREAD

**Issue by JCHEG** [keycloak/keycloak#32365]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I’ve developed a custom theme using the following theme.properties configuration:
```properties
parent=base
import=common/keycloak  
styles=css/styles.css  
scripts=js/vue-2.7.14.min.js  
```
Everything works as expected (just like in my previous version using Keycloak 23.0.1), except for the import of the rfc4648 module in the files located at:

    themes/src/main/resources/theme/base/login/resources/js/webauthnAuthenticate.js
    themes/src/main/resources/theme/base/login/resources/js/webauthnRegister.js

The browser console shows the following error:
```
TypeError: Failed to resolve module specifier "rfc4648". Relative references must start with either "/", "./", or "../".
```

### Version

25.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

This issue prevents the registration and usage of a YubiKey during the WebAuthn authentication flow.

### Actual behavior

When I click the register button, nothing happens, and the browser console displays the error:
```SHELL
TypeError: Failed to resolve module specifier "rfc4648". Relative references must start with either "/", "./", or "../".
```

### How to Reproduce?

To replicate, create a theme using the following properties:
```properties
parent=base
import=common/keycloak  
styles=css/styles.css  
scripts=js/vue-2.7.14.min.js  
```

**Comment by JCHEG** [comment]
The corrsponding stack Trace
```
2024-08-23 18:39:05,009 DEBUG [org.keycloak.authentication.requiredactions.WebAuthnRegister] (executor-thread-6) invalid cert path: com.webauthn4j.validator.exception.CertificateException: invalid cert path
	at com.webauthn4j.validator.attestation.trustworthiness.certpath.CertPathTrustworthinessValidatorBase.validate(CertPathTrustworthinessValidatorBase.java:66)
	at com.webauthn4j.validator.AttestationValidator.validate(AttestationValidator.java:121)
	at com.webauthn4j.validator.RegistrationDataValidator.validate(RegistrationDataValidator.java:192)
	at com.webauthn4j.WebAuthnRegistrationManager.validate(WebAuthnRegistrationManager.java:209)
	at org.keycloak.authentication.requiredactions.WebAuthnRegister.processAction(WebAuthnRegister.java:244)
	at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:1156)
	at org.keycloak.services.resources.LoginActionsService.requiredActionPOST(LoginActionsService.java:1090)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$requiredActionPOST_02b0bc04a277d23515b0317d630ef043b756d133.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:157)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at com.webauthn4j.validator.attestation.trustworthiness.certpath.CertPathTrustworthinessValidatorBase.validate(CertPathTrustworthinessValidatorBase.java:62)
	... 17 more

2024-08-23 18:39:05,010 WARN  [org.keycloak.events] (executor-thread-6) type="CUSTOM_REQUIRED_ACTION_ERROR", realmId="XXXXXXXXX", realmName="XXXXXXXXX", clientId="XXXXXXXXX", userId="XXXXXXXXX", ipAddress="10.0.6.200", error="invalid_registration", credential_type="webauthn", auth_method="openid-connect", web_authn_registration_error_detail="invalid cert path", custom_required_action="webauthn-register", response_type="code", web_authn_registration_error="webauthn-error-registration", redirect_uri="https://admin.com/index.php", remember_me="false", code_id="ad6c8577-12e2-489b-8f21-3f2573dd28a6", response_mode="query", username="login"
```

**Comment by ThoreKr** [comment]
I'm facing the same issue in the base login.v2 theme (and my custom extension of it)

**Comment by jonkoops** [comment]
You are likely overriding `template.ftl` in your theme, and are missing the some code from the `base` theme. Try copying [the import map](https://github.com/keycloak/keycloak/blob/aac5a2a4f2072ab61f5f08f08781f089b6f68660/themes/src/main/resources/theme/base/login/template.ftl#L33-L390) from that template into yours.

**Comment by ThoreKr** [comment]
@jonkoops is there a separate bug report for login v2?

Because anything related to webauthn (registration/login) fails with the same error for me.

**Comment by jonkoops** [comment]
@ThoreKr seems you are correct, there is no such import defined for the v2 of the login. Could you report this as a separate issue? Note, this has already been fixed in `main` and will be fixed for Keycloak 26, but this does affect Keycloak 25.

**Comment by yours-fusky** [comment]
In case anyone end up here while updating older keycloak themese. You are probably missing this part in your `template.ftl` in your theme
```
<script type="importmap">
        {
            "imports": {
                "rfc4648": "${url.resourcesCommonPath}/vendor/rfc4648/rfc4648.js"
            }
        }
    </script>
```
