### ISSUE TITLE
Failed authentication: org.keycloak.authentication.AuthenticationFlowException: authenticator: reset-otp

### ISSUE THREAD

**Issue by anhnmt** [keycloak/keycloak#32479]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

![image](https://github.com/user-attachments/assets/b3c1de0c-318b-4fe6-9362-634fedcb62f3)

This error occurs when the user has their OTP deleted in some way and when they reset the OTP using the password reset link, an error will be returned.

### Version

23.0.5-25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

When the user clicks on the reset password link => reset password => reset OTP (if not available, ignore)

### Actual behavior

When the user clicks on the password reset link => reset password => reset OTP (no OTP will return an error)

```
2024-08-29 08:01:57,511 WARN  [org.keycloak.services] (executor-thread-6) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: authenticator: reset-otp
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:429)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:377)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1071)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:909)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:378)
	at org.keycloak.authentication.actiontoken.ActionTokenContext.processFlow(ActionTokenContext.java:162)
	at org.keycloak.authentication.actiontoken.resetcred.ResetCredentialsActionTokenHandler.handleToken(ResetCredentialsActionTokenHandler.java:67)
	at org.keycloak.authentication.actiontoken.resetcred.ResetCredentialsActionTokenHandler.handleToken(ResetCredentialsActionTokenHandler.java:39)
	at org.keycloak.services.resources.LoginActionsService.handleActionToken(LoginActionsService.java:684)
	at org.keycloak.services.resources.LoginActionsService.executeActionToken(LoginActionsService.java:547)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$executeActionToken_9df1a4d2415343036325c212be507b468d007d81.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

Set OTP required
![image](https://github.com/user-attachments/assets/f750ec5d-a591-4a28-a684-d8cc33ba1c37)

Set Remove all OTP
![image](https://github.com/user-attachments/assets/55da7cc4-5047-4e2e-bcd7-5ecf87af2baf)

**Comment by graziang** [comment]
Hi @anhnmt, this is because to execute "Reset OTP" Authenticator an OTP must be configured on the user or `isUserSetupAllowed` should return true to set the required action. 
In your case, a workaround could be to set the "Reset - Conditional OTP" flow to Conditional as default to Reset the OTP only if is configured on the user.

**Comment by anhnmt** [comment]
@graziang 
![image](https://github.com/user-attachments/assets/4e51af29-a8d1-4718-bf87-fb782c2fd2bf)

I followed you and the error went away, but the flow is no longer the same:

Expected behavior
When the user clicks on the password reset link => scans the OTP code => changes password => redirects to the home page

Actual behavior
When the user clicks on the password reset link => change password => redirected to the home page (the step of scanning the OTP code has been lost)
