### ISSUE TITLE
[CI] BruteForceTest.testPermanentLockout failures

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#32516]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The `BruteForceTest` started failing in CI.

It seems after introducing these changes: https://github.com/keycloak/keycloak/commit/ecbd856176fa81203be0fe07464299d39883e9f8

@douglaspalmer Could you please check it? Thanks!

Seen in GHA:
https://github.com/keycloak/keycloak/actions/runs/10628253826/job/29464461097
https://github.com/keycloak/keycloak/actions/runs/10617941940/job/29465833971?pr=32309

```
BruteForceTest ++ 08:00:12,981 INFO  [org.keycloak.testsuite.forms.BruteForceTest] [BruteForceTest] testPermanentLockout() STARTED
BruteForceTest ++ Aug 30, 2024 8:00:13 AM org.jboss.arquillian.drone.webdriver.factory.HtmlUnitDriverFactory setClientOptions
BruteForceTest ++ INFO: Setting HtmlDriver web client options: {htmlunitCssEnabled=false, htmlunitHistoryPageCacheLimit=1}
BruteForceTest ++ 08:00:13,006 INFO  [org.keycloak.testsuite.drone.KeycloakDronePostSetup] Configuring driver settings. implicitWait=2000, pageLoadTimeout=10000
BruteForceTest ++ 08:00:13,006 INFO  [org.keycloak.testsuite.drone.KeycloakDronePostSetup] Check HtmlUnit driver TLS settings
BruteForceTest ++ 08:00:13,068 DEBUG [org.keycloak.testsuite.forms.BruteForceTest] loading test realms
BruteForceTest ++ 08:00:13,068 DEBUG [org.keycloak.testsuite.forms.BruteForceTest] Adding test realm for import from testrealm.json
BruteForceTest ++ 08:00:13,068 INFO  [org.keycloak.testsuite.forms.BruteForceTest] importing test realms
BruteForceTest ++ 08:00:13,068 DEBUG [org.keycloak.testsuite.forms.BruteForceTest] Modifying login theme to keycloak.v2
BruteForceTest ++ 08:00:13,068 DEBUG [org.keycloak.testsuite.forms.BruteForceTest] --importing realm: test
BruteForceTest ++ 2024-08-30 08:00:14,322 WARN  [org.keycloak.events] (executor-thread-14) type="LOGIN_ERROR", realmId="test", realmName="test", clientId="test-app", userId="be18f403-77f1-43c3-bec0-dc1169f8e8d7", ipAddress="127.0.0.1", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="https://localhost:8543/auth/realms/master/app/auth", code_id="86e30d14-487f-4da0-b68f-bd428e0499a1", username="test-user@localhost"
BruteForceTest ++ 2024-08-30 08:00:16,370 WARN  [org.keycloak.events] (executor-thread-14) type="LOGIN_ERROR", realmId="test", realmName="test", clientId="test-app", userId="be18f403-77f1-43c3-bec0-dc1169f8e8d7", ipAddress="127.0.0.1", error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="https://localhost:8543/auth/realms/master/app/auth", code_id="86e30d14-487f-4da0-b68f-bd428e0499a1", username="test-user@localhost"
BruteForceTest ++ 08:00:18,563 INFO  [org.keycloak.testsuite.util.URLUtils] starting navigation
BruteForceTest ++ 08:00:18,563 INFO  [org.keycloak.testsuite.util.URLUtils] current URL:  https://localhost:8543/auth/realms/test/login-actions/authenticate?execution=fd28f473-160c-43f0-97a9-3f5b46c8e4d9&client_id=test-app&tab_id=6PTpk_F-Mcs&client_data=eyJydSI6Imh0dHBzOi8vbG9jYWxob3N0Ojg1NDMvYXV0aC9yZWFsbXMvbWFzdGVyL2FwcC9hdXRoIiwicnQiOiJjb2RlIiwic3QiOiI1OGQ4ZThiNS00ZGNjLTQ2NTgtODQ3My0xN2Y5NWI4ZmVhOWEifQ
BruteForceTest ++ 08:00:18,563 INFO  [org.keycloak.testsuite.util.URLUtils] navigating to https://localhost:8543/auth/realms/test/testing/blank
BruteForceTest ++ 08:00:18,571 INFO  [org.keycloak.testsuite.util.URLUtils] new current URL:  https://localhost:8543/auth/realms/test/testing/blank
BruteForceTest ++ 08:00:18,571 INFO  [org.keycloak.testsuite.util.URLUtils] navigation complete
BruteForceTest ++ 08:00:18,571 INFO  [org.keycloak.testsuite.forms.BruteForceTest] deleting cookies in 'test' realm
BruteForceTest ++ 08:00:18,571 INFO  [org.keycloak.testsuite.forms.BruteForceTest] calling all TestCleanup
BruteForceTest ++ 08:00:18,576 ERROR [org.keycloak.testsuite.forms.BruteForceTest] [BruteForceTest] testPermanentLockout() FAILED
BruteForceTest ++ 08:00:18,576 INFO  [org.keycloak.testsuite.forms.BruteForceTest] [BruteForceTest] testPermanentLockout() FINISHED
BruteForceTest ++ 
BruteForceTest ++ 
BruteForceTest ++ 08:00:18,576 INFO  [org.keycloak.testsuite.arquillian.AuthServerTestEnricher] removing test realms after test class
BruteForceTest ++ 08:00:18,721 INFO  [org.keycloak.testsuite.arquillian.AuthServerTestEnricher] removed realms: test, 
BruteForceTest ++ 08:00:18,722 INFO  [org.htmlunit.javascript.JavaScriptEngine] execute() called after the shutdown of the Javascript engine and therefore not processed
BruteForceTest ++ 08:00:18,722 INFO  [org.htmlunit.javascript.JavaScriptEngine] execute() called after the shutdown of the Javascript engine and therefore not processed

--------- org.keycloak.testsuite.forms.BruteForceTest output end  ---------
Error:  Tests run: 29, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 100.518 s <<< FAILURE! - in org.keycloak.testsuite.forms.BruteForceTest
Error: OR] org.keycloak.testsuite.forms.BruteForceTest.testPermanentLockout  Time elapsed: 4.45 s  <<< FAILURE!
-- java.lang.AssertionError: Event expected
-- 	at org.junit.Assert.fail(Assert.java:89)
-- 	at org.junit.Assert.assertTrue(Assert.java:42)
-- 	at org.junit.Assert.assertNotNull(Assert.java:713)
-- 	at org.keycloak.testsuite.AssertEvents.poll(AssertEvents.java:87)
-- 	at org.keycloak.testsuite.forms.BruteForceTest.testPermanentLockout(BruteForceTest.java:570)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
-- 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
-- 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
-- 	at org.jboss.arquillian.junit.Arquillian$8$1.invokeMethod(Arquillian.java:319)
-- 	at org.jboss.arquillian.junit.MethodInvoker$1.invoke(MethodInvoker.java:18)
-- 	at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
-- 	at org.keycloak.testsuite.arquillian.ModelTestExecutor.execute(ModelTestExecutor.java:49)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
-- 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
-- 	at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:50)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
-- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
-- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:118)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
-- 	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:139)
-- 	at org.jboss.arquillian.junit.MethodInvoker.invoke(MethodInvoker.java:15)
-- 	at org.jboss.arquillian.junit.Arquillian$8.evaluate(Arquillian.java:326)
-- 	at org.jboss.arquillian.junit.Arquillian$4.evaluate(Arquillian.java:198)
-- 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:344)
-- 	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:48)
-- 	at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:209)
-- 	at org.keycloak.testsuite.AssertEvents$1.evaluate(AssertEvents.java:79)
-- 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
-- 	at org.jboss.arquillian.junit.Arquillian$7$1.invoke(Arquillian.java:273)
-- 	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.execute(ClientBeforeAfterLifecycleEventExecuter.java:88)
-- 	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.on(ClientBeforeAfterLifecycleEventExecuter.java:66)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
-- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
-- 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:114)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
-- 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
-- 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
-- 	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.fireCustomLifecycle(EventTestRunnerAdaptor.java:159)
-- 	at org.jboss.arquillian.junit.Arquillian$7.evaluate(Arquillian.java:267)
-- 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
-- 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
-- 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
-- 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
-- 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
-- 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
-- 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
-- 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
-- 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
-- 	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:160)
-- 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:344)
-- 	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:48)
-- 	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:171)
-- 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
-- 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
-- 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
-- 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
-- 	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:109)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
-- 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
-- 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

### Version

999

### Regression

- [X] The issue is a regression

### Expected behavior

Test pass

### Actual behavior

Test do not pass

### How to Reproduce?

execute the `BruteForceTest#testPermanentLockout` test

**Comment by mabartos** [comment]
Resolved by: https://github.com/keycloak/keycloak/pull/32499
