### ISSUE TITLE
Invalid client data in /login-actions/authenticate causes an uncaught server error and a HTTP 500 response code

### ISSUE THREAD

**Issue by Wnt** [keycloak/keycloak#32515]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When a client requests `/login-actions/authenticate` with invalid length `client_data` parameter, it causes an uncaught server error and results in an HTTP 500 response code.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

When such request is handled, the server should respond with HTTP 400 (invalid request). This could be achieved by e.g.:

Catching the `Illegal base64url string` exception thrown from [encodeBase64UrlToBase64](https://github.com/keycloak/keycloak/blob/ecbd856176fa81203be0fe07464299d39883e9f8/common/src/main/java/org/keycloak/common/util/Base64Url.java#L57) in [decodeClientDataFromParameter](https://github.com/keycloak/keycloak/blob/ecbd856176fa81203be0fe07464299d39883e9f8/server-spi-private/src/main/java/org/keycloak/protocol/ClientData.java#L99) and then gracefully responding with HTTP 400.

Or first check the parameter for validity (length and characters in allowed range) and only do the conversion if the validation is OK.

### Actual behavior

Server respoinds with HTTP 500 error and an error is logged.

Here's the stack trace
```
org.keycloak.services.error.KeycloakErrorHandler Unexpected error when authenticating client: java.lang.RuntimeException: Illegal base64url string!
	at org.keycloak.common.util.Base64Url.encodeBase64UrlToBase64(Base64Url.java:71)
	at org.keycloak.common.util.Base64Url.decode(Base64Url.java:32)
	at org.keycloak.protocol.ClientData.decodeClientDataFromParameter(ClientData.java:104)
	at org.keycloak.services.resources.SessionCodeChecks.<init>(SessionCodeChecks.java:99)
	at org.keycloak.services.resources.LoginActionsService.checksForCode(LoginActionsService.java:207)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:329)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticate_d833d327ad1940df8a3a3360cd1b0c741f4e7726.invoke(LoginActionsService.java:Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.run(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

Example request:
`GET /login-actions/authenticate?client_id=my-users&tab_id=3N9L4_Ydops&client_data=eyJydSI6Imh0dHBzOi8vZXhhb`
Note that the length of client data is 25 characters, and 25 % 4 = 1. This causes an error being thrown from `encodeBase64UrlToBase64`:
```java
public static String encodeBase64UrlToBase64(String base64Url) {
    String s = base64Url.replace('-', '+'); // 62nd char of encoding
    s = s.replace('_', '/'); // 63rd char of encoding
    switch (s.length() % 4) // Pad with trailing '='s
    {
        case 0:
            break; // No pad chars in this case
        case 2:
            s += "==";
            break; // Two pad chars
        case 3:
            s += "=";
            break; // One pad char
        default:
            throw new RuntimeException(
                    "Illegal base64url string!");
    }

    return s;
}
```

**Comment by charb29** [comment]
Hi, I would like to contribute to fix this issue! I've read the contribution guidelines... where should I start?

**Comment by thomasdarimont** [comment]
Sorry @charb29 I didn't see you comment. Perhaps you want to give the suggested fix from #32515 a try.

Side note:
You can run the `org.keycloak.Keycloak`  class from the keycloak-junit5 module to spin up a local Keycloak server.
I use the following CLI arguments in the launch configuration:
````
--verbose
start-dev
--features=preview
--cache=local
--http-enabled=true
--http-port=8081
--http-relative-path=auth
--proxy-headers=xforwarded
--db=dev-file
--db-url="jdbc:h2:file:../keycloak-data/data/keycloak_26_0x_v2_master;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=VALUE"
--spi-events-listener-jboss-logging-success-level=info
--spi-events-listener-jboss-logging-error-level=warn
--log-level=info
```

**Comment by thomasdarimont** [comment]
@Wnt I gave this a spin and moved the parsing from SessionCode checks into the place where the ClientData is actually used the first time and wrapped the parsing in a try / catch block as you suggested. The catch block handles produces the proper invalid_request response. Btw. I can trigger a bad request with `...&client_data=@`.

Would the fix work for you?

**Comment by charb29** [comment]
@thomasdarimont I'll reproduce the issue and try the suggested fix. I'll start working on it Friday.

**Comment by marcellorutter** [comment]
Please, forgive me if I write on this thread that's closed.

I have the same issue on KC v. 25.0.6. Right now I'm not able to upgrade to 26.x.
Is there a chance to have the bugfix #32515 also applied on v. 25.0.6?

Thank you very much for any answer/suggestion.

**Comment by ahus1** [comment]
@mrutter - we don't publish any releases or images for the 25.x release stream, actually only for the 26.4 release stream for the community, and additional 26.2 updates for customers of Red Hat build of Keycloak. 

If you depend on 25.x, you would need to backport it yourself and build your own image.
