### ISSUE TITLE
Issues when exporting Realms

### ISSUE THREAD

**Issue by Pinny3** [keycloak/keycloak#32599]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Since we move to a new database environment I want to export all the realms (including users) using kc.sh. 

Our keycloak is running within a Kubernetes Pod. So within this pod I tried the command

` /opt/keycloak/bin/kc.sh export --dir /tmp/export`

But this returns me the error

```
2024-09-02 17:25:51,581 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheException: Unable to start JGroups Channel
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:610)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:481)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:63)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:49)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:43)
	at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:78)
	at org.infinispan.metrics.impl.CorePackageImpl$3.start(CorePackageImpl.java:70)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:779)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:747)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:411)
	at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.startCacheManager(CacheManagerFactory.java:96)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.BindException: No available port to bind to in range [7800 .. 7800]
	at org.jgroups.util.Util.bind(Util.java:4095)
	at org.jgroups.util.Util.createServerSocket(Util.java:4071)
	at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:68)
	at org.jgroups.blocks.cs.TcpServer.<init>(TcpServer.java:43)
	at org.jgroups.protocols.TCP.start(TCP.java:111)
	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:905)
	at org.jgroups.JChannel.startStack(JChannel.java:921)
	at org.jgroups.JChannel._preConnect(JChannel.java:799)
	at org.jgroups.JChannel.connect(JChannel.java:322)
	at org.jgroups.JChannel.connect(JChannel.java:316)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:608)
	... 28 more
```
	
Then I tried to setup another docker container running the same Keycloak version and connect to the database of the productive keycloak and trigger the command again within my local Docker container. This time I got the back the error after approx. 5 minutes:

```
2024-09-02 17:41:14,265 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012108: CheckedAction::check - atomic action 0:ffffac120002:9967:66d5f728:85 aborting with 1 threads active!
2024-09-02 17:41:14,315 WARN  [com.arjuna.ats.arjuna] (main) ARJUNA012077: Abort called on already aborted atomic action 0:ffffac120002:9967:66d5f728:85
2024-09-02 17:41:14,334 WARN  [org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorTrackingImpl] (Transaction Reaper Worker 0) HHH000451: Transaction afterCompletion called by a background thread; delaying afterCompletion processing until the original thread can handle it. [status=4]
2024-09-02 17:41:14,335 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffffac120002:9967:66d5f728:85
2024-09-02 17:41:14,345 WARN  [org.keycloak.services.DefaultKeycloakSession] (main) Unable to close provider org.keycloak.connections.jpa.DefaultJpaConnectionProvider: org.keycloak.models.ModelException: org.hibernate.HibernateException: Transaction was rolled back in a different thread
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:64)
	at jdk.proxy2/jdk.proxy2.$Proxy76.close(Unknown Source)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProvider.close(DefaultJpaConnectionProvider.java:44)
	at org.keycloak.services.DefaultKeycloakSession.lambda$close$2(DefaultKeycloakSession.java:378)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:384)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:378)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:259)
	at org.keycloak.exportimport.util.MultipleStepsExportProvider.exportRealmImpl(MultipleStepsExportProvider.java:93)
	at org.keycloak.exportimport.util.MultipleStepsExportProvider.exportModel(MultipleStepsExportProvider.java:63)
	at org.keycloak.exportimport.ExportImportManager.runExport(ExportImportManager.java:163)
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:156)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.onStartupEvent(QuarkusKeycloakApplication.java:46)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication_Observer_onStartupEvent_67d48587b481b764f44181a34540ebd3d495c2c7.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:117)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:33)
	at org.keycloak.quarkus.runtime.cli.command.AbstractExportImportCommand.run(AbstractExportImportCommand.java:47)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:119)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: org.hibernate.HibernateException: Transaction was rolled back in a different thread
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorTrackingImpl.processAnyDelayedAfterCompletion(SynchronizationCallbackCoordinatorTrackingImpl.java:90)
	at org.hibernate.internal.SessionImpl.delayedAfterCompletion(SessionImpl.java:605)
	at org.hibernate.internal.AbstractSharedSessionContract.close(AbstractSharedSessionContract.java:375)
	at org.hibernate.internal.SessionImpl.closeWithoutOpenChecks(SessionImpl.java:412)
	at org.hibernate.internal.SessionImpl.close(SessionImpl.java:397)
	at jdk.internal.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
	... 43 more
```

I found out that this is because the numbers of groups and users within one realm is quite large, since other realms were exported successfully...

So, I have a problem now. How can I export all the data?

Our configuration looks like this:

```
> bash-5.1$ /opt/keycloak/bin/kc.sh show-config   
> Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=lisa-development-keycloak-headless
> Current Mode: production
> Current Configuration:
> 	kc.cache =  ispn (KcEnvVarConfigSource)
> 	kc.cache-stack =  kubernetes (KcEnvVarConfigSource)
> 	kc.cache.stack =  kubernetes (KcEnvVarConfigSource)
> 	kc.config.built =  true (SysPropConfigSource)
> 	kc.db =  dev-file (PersistedConfigSource)
> 	kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-23.0.7.jar!/META-INF/keycloak.conf])
> 	kc.log-file =  ${kc.home.dir:default}${file.separator}data${file.separator}log${file.separator}keycloak.log (PropertiesConfigSource[source=jar:file:///opt/keycloak/lib/lib/main/org.keycloak.keycloak-quarkus-server-23.0.7.jar!/META-INF/keycloak.conf])
> 	kc.provider.file.aws-mysql-jdbc-1.1.15.jar.last-modified =  1717660003000 (PersistedConfigSource)
> 	kc.provider.file.bcprov-jdk18on-1.73.jar.last-modified =  1681268115000 (PersistedConfigSource)
> 	kc.provider.file.ebuch-sso-authenticator.jar.last-modified =  1724234061000 (PersistedConfigSource)
> 	kc.provider.file.jcip-annotations-1.0-1.jar.last-modified =  1360753048000 (PersistedConfigSource)
> 	kc.provider.file.keycloak-metrics-spi-5.0.0.jar.last-modified =  1706606703000 (PersistedConfigSource)
> 	kc.provider.file.lisa-keycloak-mapper.jar.last-modified =  1724234054000 (PersistedConfigSource)
> 	kc.provider.file.nimbus-jose-jwt-9.15.2.jar.last-modified =  1632821117000 (PersistedConfigSource)
> 	kc.spi-connections-infinispan-quarkus-stack =  kubernetes (KcEnvVarConfigSource)
> 	kc.version =  23.0.7 (SysPropConfigSource)
```

Any help will be appreciated.

	

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Export is working properly.

### Actual behavior

see in the bug description

### How to Reproduce?

see in the bug description

**Comment by Pinny3** [comment]
Okay, will check on Monday and come back with an update.

**Comment by pct-cclausen** [comment]
I think I have the same problem.

Exporting worked fine in our development/staging environment. In the rollout we've now tested to import ~13k users into the keycloak instance and after that suddenly exporting the realm does not work anymore in any of these configurations:

- Using Keycloak 24.0.2 with `export --realm portal --users different_files --users-per-file 50 --file /realm/realm.json`
- Using  Keycloak 25.0.4 with ` export --realm portal --file /realm/realm.json`

Is 13k users really that much?

Both versions stop after exactly 5 minutes, down to the millisecond, and report "Transaction was rolled back in a different thread"

Some sort of timeout somewhere maybe? Probably relates to https://github.com/keycloak/keycloak/issues/20703
which says performance of exporting users is bad for same_file, which is why I tried to do the different_files options in 24.0.2, but maybe that is ignored with --file. 
So I tried: 

-realm portal --dir /realm/ 

with keycloak 25.0.4

This means the users are not in the same file, but it is finished successfully after less than 3 minutes.

Maybe the documentation of the "export everything into a single file" option should state a big warning that it is not really feasible for larger instances, where large means anything above a few hundred users?

**Comment by vmuzikar** [comment]
@Pinny3 The original exception (`No available port to bind to in range`) was most likely caused by not shutting down the deployment before doing the export as documented.

Could you please try the dir export against the latest Keycloak version?

@pct-cclausen There's a warning right at the beginning of the [Import/Export guide](https://www.keycloak.org/server/importExport). ;)
> Exporting and importing into single files can produce large files, so if your database contains more than 500 users, export to a directory and not a single file. Using a directory performs better as the directory provider uses a separate transaction for each "page" (a file of users).
