### ISSUE TITLE
Remove deprecated event types for password/otp update or removal

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#32685]
### Description

In this PR https://github.com/keycloak/keycloak/pull/29028/files , there was introduction of generic events `UPDATE_CREDENTIAL` and `REMOVE_CREDENTIAL` . 

For backwards compatibility, the legacy events specific to password and OTP are still triggered in addition to `UPDATE_CREDENTIAL` and `REMOVE_CREDENTIAL` . But they can be removed in Keycloak 27 as they are deprecated since Keycloak 26 (as mentioned in the Keycloak 26 release notes in the mentioned PR). So this task is about removing those events: `UPDATE_PASSWORD`, `UPDATE_PASSWORD_ERROR`, `UPDATE_TOTP`, `UPDATE_TOTP_ERROR`, `REMOVE_TOTP`, `REMOVE_TOTP_ERROR`

**Comment by dingsoyr** [comment]
Hi..

After upgrading to Keycloak 26.0.2 i get an error in the logs related to the new credential templates. When e.g. a user is updating his/her passord the error is:

```
2024-10-28 10:05:43,747 SEVERE [freemarker.runtime] (executor-thread-3) Error executing FreeMarker template: freemarker.core.NonHashException: For "." left-hand operand: Expected a hash, but this has evaluated to a sequence (wrapper: f.t.SimpleSequence):
==> event.details  [in template "text/event-update_credential.ftl" at line 2, column 36]

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${msg("eventUpdateCredentialBody", ev...  [in template "text/event-update_credential.ftl" at line 2, column 1]
----
        at freemarker.core.Dot._eval(Dot.java:48)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DefaultToExpression._eval(DefaultToExpression.java:96)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.ListLiteral.getModelList(ListLiteral.java:98)
        at freemarker.core.MethodCall._eval(MethodCall.java:60)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
        at freemarker.core.Environment.visit(Environment.java:335)
        at freemarker.core.Environment.process(Environment.java:314)
        at freemarker.template.Template.process(Template.java:383)
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:233)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:262)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:257)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:211)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendEvent(FreeMarkerEmailTemplateProvider.java:108)
        at org.keycloak.events.email.EmailEventListenerProvider$1.run(EmailEventListenerProvider.java:97)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:274)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:393)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:273)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:263)
        at org.keycloak.events.email.EmailEventListenerProvider.sendEmail(EmailEventListenerProvider.java:75)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
        at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:46)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
        at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:414)
        at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:379)
        at org.keycloak.models.KeycloakBeanProducer_ProducerMethod_getKeycloakSession_XoSEUTXOsE3bpqXlGMAykCiECUM_ClientProxy.close(Unknown Source)
        at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:60)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.closeSession(CloseSessionFilter.java:67)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.filter(CloseSessionFilter.java:63)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)

2024-10-28 10:05:43,748 ERROR [org.keycloak.events.email.EmailEventListenerProvider] (executor-thread-3) Failed to send type mail: org.keycloak.email.EmailException: Failed to template email
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:247)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:262)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:257)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.send(FreeMarkerEmailTemplateProvider.java:211)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.sendEvent(FreeMarkerEmailTemplateProvider.java:108)
        at org.keycloak.events.email.EmailEventListenerProvider$1.run(EmailEventListenerProvider.java:97)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:274)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:393)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:273)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:263)
        at org.keycloak.events.email.EmailEventListenerProvider.sendEmail(EmailEventListenerProvider.java:75)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
        at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:46)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
        at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:414)
        at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:379)
        at org.keycloak.models.KeycloakBeanProducer_ProducerMethod_getKeycloakSession_XoSEUTXOsE3bpqXlGMAykCiECUM_ClientProxy.close(Unknown Source)
        at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:60)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.closeSession(CloseSessionFilter.java:67)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.filter(CloseSessionFilter.java:63)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.keycloak.email.EmailException: Failed to template plain text email.
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:235)
        ... 31 more
Caused by: org.keycloak.theme.FreeMarkerException: Failed to process template text/event-update_credential.ftl
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)
        at org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:233)
        ... 31 more
Caused by: freemarker.core.NonHashException: For "." left-hand operand: Expected a hash, but this has evaluated to a sequence (wrapper: f.t.SimpleSequence):
==> event.details  [in template "text/event-update_credential.ftl" at line 2, column 36]

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${msg("eventUpdateCredentialBody", ev...  [in template "text/event-update_credential.ftl" at line 2, column 1]
----
        at freemarker.core.Dot._eval(Dot.java:48)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DefaultToExpression._eval(DefaultToExpression.java:96)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.ListLiteral.getModelList(ListLiteral.java:98)
        at freemarker.core.MethodCall._eval(MethodCall.java:60)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:104)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
        at freemarker.core.Environment.visit(Environment.java:335)
        at freemarker.core.Environment.process(Environment.java:314)
        at freemarker.template.Template.process(Template.java:383)
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)
        ... 32 more
```

Using the "keycloak" email theme.

The same type of error also occurs when the event-remove_credential.ftl is triggered, eg when removing OTP from an account.

**Comment by MaryWichmann** [comment]
Hello, I am getting the same error as @dingsoyr. This event is also not possible to turn off in the Keycloak admin GUID.
To avoid these errors I added the missing .ftl files, we're using a custom theme. But then faced the next issue: both the event-update_credential email and the old event-update_totp are sent. Same happens for resetting the user password. 
The old password event is possible to turn off via "Send reset password" event, but a similar function for the totp event is not present.
We're facing two choices: Have errors in our logs, or send duplicate emails to our users. 
It feels like something is missing from this release, as well as information regarding handling of these events.

**Comment by dingsoyr** [comment]
Can confirm the same behaviour as @MaryWichmann in regards of duplicate emails.

**Comment by ahus1** [comment]
This issue about eventually removing the old events in a future, while the latest discussion is about a bug in KC26 which needs to be handled in a different issue. I've created #34687 for this. Please continue the discussion over there to have it fixed for KC26.

**Comment by kodburn** [comment]
Any updates or timeframes on this? Duplicate emails are a pretty big problem and there is no workaround.

**Comment by jappurohit041-ncsu-edu** [comment]
Hello,
any updates or timeframes on this ?  `--spi-events-listener-email-include-events` does not seem to work as well.
