### ISSUE TITLE
Flaky test: org.keycloak.testsuite.url.HostnameV2Test

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#32784]
## org.keycloak.testsuite.url.HostnameV2Test
[Keycloak CI - Base IT (6)](https://github.com/keycloak/keycloak/actions/runs/10736079092/job/29774956758) / [Pull Request #32519](https://github.com/keycloak/keycloak/pull/32519)

```
jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:242)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:41)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:136)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
...
```

**Comment by vmuzikar** [comment]
Caused by: https://github.com/keycloak/keycloak/issues/32785
