### ISSUE TITLE
Network response was not OK

### ISSUE THREAD

**Issue by lamenawuer** [keycloak/keycloak#32794]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

All of the sudden, when trying to look for a user profile I get this error:
![image](https://github.com/user-attachments/assets/eb15c563-c926-4ea2-8a5b-22d17d459a49)

Upon taking a look at the logs I see this:
```
2024-09-11 06:43:38,250 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2849) Uncaught server error: java.lang.IllegalStateException: Duplicate key modifyTimestamp (attempted merging values org.keycloak.userprofile.AttributeMetadata@c933017c and org.keycloak.userprofile.AttributeMetadata@c933017c)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
```

I have no clue how to solve this... I would greatly appreciate any help as this is a production instance

My Keycloak setup is as follows:
2 virtual machines running a keycloak container each that talk to each other via a shared cache infinispan. The database is a postgresql running in a virtual machine. The users in my realm are connected via ldap, and I have other realms where this ldap is connected and the user profile can be seen just fine.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

User profile can be seen and modifed

### Actual behavior

User profile does not load and instead this message shows up
![image](https://github.com/user-attachments/assets/eb15c563-c926-4ea2-8a5b-22d17d459a49)

### How to Reproduce?

I don't know how to reproduce this error, like I said above I have other realms with the same ldap instance connected and the user profiles can be seen

**Comment by lamenawuer** [comment]
So one major version behind is unsupported? Are you serious? It dates from June 2024 for God's sake

**Comment by jonkoops** [comment]
We only support the latest major, future majors will likely have a longer lifecyle, there is commercial support available if you want LTS.

**Comment by krax13** [comment]
I am using the latest version (25.0.5), but I have the same issue when I try to open an AD user:

![image](https://github.com/user-attachments/assets/aa747cb8-26e8-4397-8309-728a0c5e5d86)

I got 404 not found error in web console, but that user exist in AD.

**Comment by krax13** [comment]
I couldn't find any problem with mappers:
![image](https://github.com/user-attachments/assets/5bc2c0f7-ea91-416f-a696-e69f372bcf2a)

Started the keycloak with DEBUG logging, and seeing a User not found error:

2024-09-17 15:35:16,326 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager] (executor-thread-31) Creating LdapContext using properties: [{java.naming.security.authentication=simple, java.naming.ldap.attributes.binary=objectGUID, java.naming.provider.url=ldap://########.local, com.sun.jndi.ldap.connect.pool=false, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.security.credentials=**************************************, java.naming.security.principal=CN=########,OU=#########,OU=#########,DC=########,DC=local}]
2024-09-17 15:35:16,331 DEBUG [WebApplicationException] (executor-thread-31) Restarting handler chain for exception exception: jakarta.ws.rs.NotFoundException: User not found
        at org.keycloak.services.resources.admin.UsersResource.user(UsersResource.java:222)
        at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$user_ff3051a872bbc076abe0c6efce9738c76352e827.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)

2024-09-17 15:35:16,331 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-31) Error response 404: jakarta.ws.rs.NotFoundException: User not found
        at org.keycloak.services.resources.admin.UsersResource.user(UsersResource.java:222)
        at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$user_ff3051a872bbc076abe0c6efce9738c76352e827.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)

I don't know if it is a problem, but I don't use cache and sync option in User federation --> LDAP settings.
![image](https://github.com/user-attachments/assets/da1c9b92-fc63-4d0f-a08d-20b6953a1784)

**Comment by sguilhen** [comment]
@krax13 do you see this issue with every AD user you click on? With your settings, users are not imported into Keycloak - they're rather always fetched from LDAP. So you're able to retrieve them but once you click on the user you get the error?

I've tried reproducing this locally but wasn't able to. Every user I click on gets to the user details page just fine. In your case, something is causing the user to not be found in LDAP (search is performed using the configured Username LDAP attribute, so you need to check whether that is correctly configured). 

Can you look into the URL of the request when you click on the user? It should look something like `/admin/{realm}/console/#/{realm}/users/f:9fd872b4-8dc9-4052-b4d4-ead2ca3911bd:testuser/settings`

The id starts with `f`, followed by a UUID, followed by the username. Then check if that username exists in LDAP because it is the value that will be used when searching.

**Comment by krax13** [comment]
It doesn't affect all AD users, just that one.
I have searched some other AD users, but those are working.
I can retrieve all users from AD with a technical user, so I can search users in the WebUI without problem.
I will check the user's attributes in AD.

**Comment by krax13** [comment]
It seems to be solved by changing to "cn" the username attributes under mapper:
![image](https://github.com/user-attachments/assets/5d82b346-15a8-4839-b1c2-65f2c681d591)

and Username LDAP attribute settings under realm:
![image](https://github.com/user-attachments/assets/733b01aa-3a49-47c4-aa34-c74abf6853fd)

There was a displayName attribute before cn. I do not know what was the problem with it.
