### ISSUE TITLE
offline-sessions API fails with 500 when using mssql as db

### ISSUE THREAD

**Issue by dhvanish** [keycloak/keycloak#32832]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

2024-09-11 19:23:16,479 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-93) SQL Error: 207, SQLState: S0001
2024-09-11 19:23:16,479 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-93) Invalid column name 'version'.
2024-09-11 19:23:16,481 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-93) Uncaught server error: org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [select puse1_0.OFFLINE_FLAG,puse1_0.USER_SESSION_ID,puse1_0.BROKER_SESSION_ID,puse1_0.CREATED_ON,puse1_0.DATA,puse1_0.LAST_SESSION_REFRESH,puse1_0.REALM_ID,puse1_0.USER_ID,puse1_0.version from OFFLINE_USER_SESSION puse1_0 join OFFLINE_CLIENT_SESSION pcse1_0 on puse1_0.USER_SESSION_ID=pcse1_0.USER_SESSION_ID and puse1_0.OFFLINE_FLAG=pcse1_0.OFFLINE_FLAG and pcse1_0.CLIENT_ID=? where puse1_0.OFFLINE_FLAG=? and puse1_0.REALM_ID=? order by puse1_0.USER_SESSION_ID offset ? rows fetch first ? rows only] [Invalid column name 'version'.] [n/a]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:91)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:264)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:167)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:218)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:98)
	at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:51)
	at org.hibernate.query.internal.ScrollableResultsIterator.hasNext(ScrollableResultsIterator.java:33)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.utils.ClosingStream.collect(ClosingStream.java:182)
	at org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.loadUserSessionsWithClientSessions(JpaUserSessionPersisterProvider.java:473)
	at org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.loadUserSessionsStream(JpaUserSessionPersisterProvider.java:405)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionsStream(InfinispanUserSessionProvider.java:484)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getOfflineUserSessionsStream(InfinispanUserSessionProvider.java:865)
	at org.keycloak.services.resources.admin.ClientResource.getOfflineUserSessions(ClientResource.java:614)
	at org.keycloak.services.resources.admin.ClientResource$quarkusrestinvoker$getOfflineUserSessions_5ba8eace62300c8c288f227736907ea5fb1324bd.invoke(Unknown Source)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The API should not fail and return the client user sessions

### Actual behavior

The API fails with 500 error

### How to Reproduce?

Login to Keycloak which is connected to mssql database
Go to any realm and click on Clients
Click any client and then click on sessions tab

**Comment by dhvanish** [comment]
this was fixed in 25.0.4
