### ISSUE TITLE
Keycloak panicking when attempt to encrypt JWT

### ISSUE THREAD

**Issue by sredxny** [keycloak/keycloak#32919]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I have running keycloak:25.0.5 in a docker container. I did configure my realm and then added a new client, this client works perfectly until I set a `ID token encryption key management algorithm` and `ID token encryption content encryption algorithm`, the client is defined as:

```
{
  "clientId": "myclient",
  "name": "me",
  "description": "my app",
  "rootUrl": "",
  "adminUrl": "",
  "baseUrl": "",
  "surrogateAuthRequired": false,
  "enabled": true,
  "alwaysDisplayInConsole": false,
  "clientAuthenticatorType": "client-secret",
  "secret": "[any-secret]",
  "redirectUris": [
    "http://myapp/auth/keycloak/openid-connect/callback",
  ],
  "webOrigins": [
    "/*"
  ],
  "notBefore": 0,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": true,
  "directAccessGrantsEnabled": true,
  "serviceAccountsEnabled": true,
  "authorizationServicesEnabled": true,
  "publicClient": false,
  "frontchannelLogout": true,
  "protocol": "openid-connect",
  "attributes": {
    "request.object.signature.alg": "any",
    "id.token.encrypted.response.alg": "RSA-OAEP",
    "authorization.encrypted.response.enc": "A128CBC-HS256",
    "oauth2.device.authorization.grant.enabled": "false",
    "use.jwks.url": "false",
    "backchannel.logout.revoke.offline.tokens": "false",
    "use.refresh.tokens": "true",
    "oidc.ciba.grant.enabled": "true",
    "id.token.signed.response.alg": "ES256",
    "backchannel.logout.session.required": "true",
    "client_credentials.use_refresh_token": "false",
    "require.pushed.authorization.requests": "false",
    "request.object.encryption.enc": "any",
    "client.secret.creation.time": "1726089993",
    "request.object.encryption.alg": "RSA-OAEP",
    "client.introspection.response.allow.jwt.claim.enabled": "false",
    "user.info.encrypted.response.enc": "A128CBC-HS256",
    "access.token.signed.response.alg": "ES256",
    "client.use.lightweight.access.token.enabled": "false",
    "jwt.credential.public.key": "-----BEGIN PUBLIC KEY-----\n[public-key-here]\n-----END PUBLIC KEY-----\n",
    "tls.client.certificate.bound.access.tokens": "false",
    "acr.loa.map": "{}",
    "display.on.consent.screen": "false",
    "id.token.encrypted.response.enc": "A128CBC-HS256",
    "token.response.type.bearer.lower-case": "false"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "protocolMappers": [
    {
      "name": "Client IP Address",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "clientAddress",
        "id.token.claim": "true",
        "introspection.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "clientAddress",
        "jsonType.label": "String"
      }
    },
    {
      "name": "Client ID",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "client_id",
        "id.token.claim": "true",
        "introspection.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "client_id",
        "jsonType.label": "String"
      }
    },
    {
      "name": "Client Host",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-usersessionmodel-note-mapper",
      "consentRequired": false,
      "config": {
        "user.session.note": "clientHost",
        "id.token.claim": "true",
        "introspection.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "clientHost",
        "jsonType.label": "String"
      }
    }
  ],
  "defaultClientScopes": [
    "web-origins",
    "acr",
    "roles",
    "profile",
    "basic",
    "email"
  ],
  "optionalClientScopes": [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt"
  ],
  "access": {
    "view": true,
    "configure": true,
    "manage": true
  }
}
```

I did added my publick key via Clients > myclient > Keys > import -> then added my public key file, this is succesful. Then when I run the flow again (that used to work without encryption) Keycloak just panics as next:

```
2024-09-13 10:21:46 2024-09-13 13:21:46,761 WARN  [org.keycloak.keys.loader.ClientPublicKeyLoader] (executor-thread-262) Unable to retrieve publicKey of client 'myclient' for the specified purpose other than verifying signature
2024-09-13 10:21:46 2024-09-13 13:21:46,763 WARN  [org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider] (executor-thread-262) PublicKey wasn't found in the storage. Requested kid: 'null' . Available kids: '[]'
2024-09-13 10:21:46 2024-09-13 13:21:46,763 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-262) Uncaught server error: java.lang.RuntimeException: can not get encryption KEK
2024-09-13 10:21:46     at org.keycloak.jose.jws.DefaultTokenManager.getEncryptedToken(DefaultTokenManager.java:270)
2024-09-13 10:21:46     at org.keycloak.jose.jws.DefaultTokenManager.encodeAndEncrypt(DefaultTokenManager.java:234)
2024-09-13 10:21:46     at org.keycloak.protocol.oidc.TokenManager$AccessTokenResponseBuilder.build(TokenManager.java:1265)
2024-09-13 10:21:46     at org.keycloak.protocol.oidc.grants.ResourceOwnerPasswordCredentialsGrantType.process(ResourceOwnerPasswordCredentialsGrantType.java:158)
2024-09-13 10:21:46     at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:140)
2024-09-13 10:21:46     at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
2024-09-13 10:21:46     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-09-13 10:21:46     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-09-13 10:21:46     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-09-13 10:21:46     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
2024-09-13 10:21:46     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-09-13 10:21:46     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-09-13 10:21:46     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-09-13 10:21:46     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-09-13 10:21:46     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-09-13 10:21:46     at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak doesnt panics and performs the flow, or at least displays a proper error message. 

### Actual behavior

Application pacnicking

### How to Reproduce?

- Run Keycloak 25.0.5
- Register a new realm
- Register a client under that realm
- enable client authentication for that client
- Add a public key via Clients>client>Keys>import key
- Call the token endpoint via curl like this:

```
curl --location 'http://127.0.0.1:8585/realms/myrealm/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'username=myuser@mail.com' \
--data-urlencode 'password=123456' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'client_id=myclient' \
--data-urlencode 'client_secret=[the-client-secret]' \
--data-urlencode 'scope=openid'
```
- At this point keycloak just panics

**Comment by SushmitaGoswami** [comment]
Can I take this please?

**Comment by SushmitaGoswami** [comment]
Sure. Thanks for your help!

**Comment by jonkoops** [comment]
Thanks for that! I'll assign a priority so this issue is triaged.
