### ISSUE TITLE
Improper handling of groups with same RDN in ldap-group-mapper

### ISSUE THREAD

**Issue by StephaneChatty** [keycloak/keycloak#33255]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When two LDAP groups have the same RDN in two different parent groups, the current tree-building algorithms mixes them up, improperly creates a group that has two parents, and crashes the whole mapping process. It seems that relying on a map to facilitate the retrieval of groups is at the core of the issue.

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Take an LDAP directory with two groups sn=c:sn=b1:dc=a1 and sn=c:sn=b2:dc=a2.  Map it to Keycloak groups. This should create a subgroup named c in b1 and another with the same name in b2.

### Actual behavior

The LDAP group mapper fails and shows an error message about group c having two parents b1 and b2.

### How to Reproduce?

Create an LDAP directory with two groups sn=c:sn=b1:dc=a and sn=c:sn=b2:dc=a. Configure the LDAP group mapper with `Group Name LDAP Attribute = sn` and the appropriate value for `Membership User LDAP Attribute`. Launch the LDAP-to-Keycloak group synchronization. Look at the logs when the UI shows an error message.

### Anything else?

2024-09-24 21:33:16,138 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.keycloak.models.ModelException: Couldn't resolve groups from LDAP. Fix LDAP or skip preserve inheritance. Details: Group 'c' detected to have multiple parents. This is not allowed in Keycloak. Parents are: [b1, b2]
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:186)
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.findKcGroupOrSyncFromLDAP(GroupLDAPStorageMapper.java:390)
	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper$LDAPGroupMappingsUserDelegate.lambda$getLDAPGroupMappingsConverted$0(GroupLDAPStorageMapper.java:772)
...

**Comment by StephaneChatty** [comment]
That would be dc=a. In practice, the dn is much longer: something that dc=a,dc=z,dc=y. But I hope that the simplification I made is irrelevant.

**Comment by sguilhen** [comment]
Yeah, just to confirm the setup is what I imagined. Thanks!

**Comment by sguilhen** [comment]
@StephaneChatty Would you be able to provide a sample LDIF with the group structure you've used? I've tried to reproduce but I'm probably using a different structure because it led me to a different error when importing the groups.

**Comment by StephaneChatty** [comment]
I might need to read up the topic of exporting to LDIF but no problem of course.

**Comment by sguilhen** [comment]
Hi @StephaneChatty sorry for the delayed response - wasn't able to get to this sooner. Are you by any chance using Active Directory?

I ask because on OpenLdap the entries with multiple CNs (or SNs) are considered by Keycloak as a single entry with a multi-valued CN, and it picks the first one, discarding the others. So I go an error that is different than the one you're hitting here.

If you are on AD, then the sn=b1,dc=a and sn=b2,dc=a are also groups right?

**Comment by StC-OSM** [comment]
Funny, I was just preparing to write a message with my own findings. 

> Are you by any chance using Active Directory?
I have asked colleagues who know what LDAP server we are using. I don't know myself how to find it. If it possible to do it with ldapsearch, I'll be happy to do it.

> the sn=b1,dc=a and sn=b2,dc=a are also groups right?
They are.

I have read the code. An exception is raised at `federation/ldap//src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupTreeResolver.java:62`. This is because at line 118 of the same file there has been a call to` list.add('b1')` and `list.add('b2')` for the same value of `list` (the one that is associated to `'c' ` in the TreeMap `result`). That is because at `federation/ldap//src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java:245` there have been two calls to `subgroupNames.add('c')`, when dealing with `sn=c,sn=b1,sn=a` from group `b1` then with `sn=c,sn=b2,sn=a` from group `b2`

My understanding is that it it will not be straightforward to fix this, because with the standard LDAP attributes and the available parameters defined in the config of the LDAP group mapper, there is no information available when dealing with two `c` groups to determine which corresponds to `sn=c,sn=b1,sn=a` in group `b1` and to `sn=c,sn=b2,sn=a` in group `b2`. In our LDAP base there is a `ourParentDN` attribute that contains what we need, but I don't know if such an attribute is commonplace.

**Comment by StephaneChatty** [comment]
Funny, I was just preparing to write a message with my own findings. 

> Are you by any chance using Active Directory?

I have asked colleagues who know what LDAP server we are using. I don't know myself how to find it. If it possible to do it with ldapsearch, I'll be happy to do it.

> the sn=b1,dc=a and sn=b2,dc=a are also groups right?

They are.

I have read the code. An exception is raised at `federation/ldap//src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupTreeResolver.java:62`. This is because at line 118 of the same file there has been a call to` list.add('b1')` and one to `list.add('b2')` for the same value of `list` (the one that is associated to `'c' ` in the TreeMap `result`). That is because at `federation/ldap//src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java:245` there have been two calls to `subgroupNames.add('c')`, when dealing with `sn=c,sn=b1,dc=a` from group `b1` then with `sn=c,sn=b2,dc=a` from group `b2`

My understanding is that it it will not be straightforward to fix this, because with the standard LDAP attributes and the available parameters defined in the config of the LDAP group mapper, there is no information available when dealing with two `c` groups to determine which corresponds to `sn=c,sn=b1,dc=a` in group `b1` and to `sn=c,sn=b2,dc=a` in group `b2`. In our LDAP base there is a `ourParentDN` attribute that contains what we need (`sn=b1,dc=a` and `sn=b2,dc=a`, respectively), but I don't know if such an attribute is commonplace.

**Comment by StephaneChatty** [comment]
Apparently we are using Sun Microsystem's Directory Proxy Server.

**Comment by sguilhen** [comment]
> My understanding is that it it will not be straightforward to fix this, because with the standard LDAP attributes and the available parameters defined in the config of the LDAP group mapper, there is no information available when dealing with two `c` groups to determine which corresponds to `sn=c,sn=b1,dc=a` in group `b1` and to `sn=c,sn=b2,dc=a` in group `b2`. In our LDAP base there is a `ourParentDN` attribute that contains what we need (`sn=b1,dc=a` and `sn=b2,dc=a`, respectively), but I don't know if such an attribute is commonplace.

Yeah, that is my feeling too. I asked about the directory service because the attr names are not commonplace.

I need to reproduce this again - perhaps with AD will be easier - to see if there's anything we can add to the mapper so it is able to differentiate the groups. As it stands now, this scenario doesn't seem to be supported.

**Comment by sguilhen** [comment]
I've dug into the code a bit deeper, and turns out that the group mapper makes the assumption that all groups coming from LDAP have unique names. This is seen not only when importing users, where it doesn't distinguish between different groups (with different UUIDs) with the same name, but also when searching for members, adding new groups, etc.

So the scope of the fix is not restricted to importing, where we should not only take the name but also the LDAP ID of the group into consideration. If we're preserving the inheritance, than it should be acceptable to have groups with the same name under different parents. 

We also need to fix things like `getGroupMembers` that currently fail if the LDAP search finds more than one group with the same name, even if they have different parents, because it expects to find a single group. We likely need to store the LDAP_ID of the group as an attribute, just like we do for users, to be able to query this exact group in operations like this.

Also, when adding groups, the code currently checks if LDAP already has a group with the same name - again ignoring the path/different parents, and if it finds one it tries to update it instead of creating a new one.

**Comment by StephaneChatty** [comment]
OK, so that would rely on an attribute that would provide a unique ID for the group and that we would provide in configuration of the group mapper, just like the "UUID LDAP attribute" for users? I am not sure that have such an attribute in our LDAP. I am afraid that we need to create it by combining an already available attribute and one that contains the DN of the group's parent.

Would it help, or would it just create additional work for you, if we invested some time here in trying to find a fix that works for us?

**Comment by ReilySiegel** [comment]
I can confirm that this issue exists even if I manually set up multiple ldap-group-mappers to put the groups on different paths. Has anyone found a workaround?
