### ISSUE TITLE
mvnclean install failed to start server

### ISSUE THREAD

**Issue by mchen-10** [keycloak/keycloak#33364]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When running mvnw clean install I am getting a "Failed to start server" error

```
[ERROR] Errors:
[ERROR]   ManagementDistTest.testManagementDifferentRelativePath(LaunchResult) » Runtime Failed to start the server
[ERROR]   ManagementDistTest.testManagementRootRedirects(LaunchResult,KeycloakDistribution) » Runtime Failed to start the server
[ERROR]   ManagementHttpsDistTest.simpleHttpsStartDev(LaunchResult) » Runtime Failed to start the server
[INFO]
[ERROR] Tests run: 130, Failures: 0, Errors: 3, Skipped: 2
```

Seems to keep looping through these 3 tests indefinitely (ran it over night). 

All three seem to stem from the RawKeyCloakDistribution class - code snippet is from ManagementDistTest

```
[ERROR] Tests run: 8, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 15,380.678 s <<< FAILURE! - in org.keycloak.it.cli.dist.ManagementDistTest
[ERROR] org.keycloak.it.cli.dist.ManagementDistTest.testManagementRootRedirects(LaunchResult,KeycloakDistribution)  Time elapsed: 8,019.398 s  <<< ERROR!
java.lang.RuntimeException: Failed to start the server
	at org.keycloak.it.utils.RawKeycloakDistribution.run(RawKeycloakDistribution.java:181)
	at org.keycloak.it.junit5.extension.KeycloakDistributionDecorator.run(KeycloakDistributionDecorator.java:46)
	at org.keycloak.it.junit5.extension.CLITestExtension.beforeEach(CLITestExtension.java:106)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.keycloak.it.utils.RawKeycloakDistribution was not fulfilled within 1 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at org.keycloak.it.utils.RawKeycloakDistribution.threadDump(RawKeycloakDistribution.java:404)
	at org.keycloak.it.utils.RawKeycloakDistribution.waitForReadiness(RawKeycloakDistribution.java:351)
	at org.keycloak.it.utils.RawKeycloakDistribution.waitForReadiness(RawKeycloakDistribution.java:336)
	at org.keycloak.it.utils.RawKeycloakDistribution.run(RawKeycloakDistribution.java:171)
	... 4 more

[ERROR] org.keycloak.it.cli.dist.ManagementDistTest.testManagementDifferentRelativePath(LaunchResult)  Time elapsed: 6,310.488 s  <<< ERROR!
java.lang.RuntimeException: Failed to start the server
	at org.keycloak.it.utils.RawKeycloakDistribution.run(RawKeycloakDistribution.java:181)
	at org.keycloak.it.junit5.extension.KeycloakDistributionDecorator.run(KeycloakDistributionDecorator.java:46)
	at org.keycloak.it.junit5.extension.CLITestExtension.beforeEach(CLITestExtension.java:106)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.keycloak.it.utils.RawKeycloakDistribution was not fulfilled within 1 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at org.keycloak.it.utils.RawKeycloakDistribution.threadDump(RawKeycloakDistribution.java:404)
	at org.keycloak.it.utils.RawKeycloakDistribution.waitForReadiness(RawKeycloakDistribution.java:351)
	at org.keycloak.it.utils.RawKeycloakDistribution.waitForReadiness(RawKeycloakDistribution.java:336)
	at org.keycloak.it.utils.RawKeycloakDistribution.run(RawKeycloakDistribution.java:171)
	... 4 more
```

### Version

main branch commit d57050656ec8cb2f97973ec9913c0265d4812944

### Regression

- [ ] The issue is a regression

### Expected behavior

Expected to run mvnw clean install successfully

### Actual behavior

error described above

### How to Reproduce?

run mvnw clean install - i am using. a macOS  M1 Sonoma 14.6.1

### Anything else?

log that seems to appear right before test failure log 

```
Updating the configuration and installing your custom providers, if any. Please wait.
2024-09-27 07:20:18,739 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 3600ms
2024-09-27 07:20:21,562 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
2024-09-27 07:20:21,654 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for sessions to 10000 entries.
2024-09-27 07:20:21,654 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for clientSessions to 10000 entries.
2024-09-27 07:20:21,654 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineSessions to 10000 entries.
2024-09-27 07:20:21,654 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineClientSessions to 10000 entries.
2024-09-27 07:20:21,831 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2024-09-27 07:20:22,339 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-09-27 07:20:22,350 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_149135, Site name: null
2024-09-27 07:20:22,905 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml

UPDATE SUMMARY
Run:                        143
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:          143

2024-09-27 07:35:32,326 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-09-27 07:35:32,647 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2024-09-27 07:35:33,594 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-09-27 07:35:33,740 INFO  [io.quarkus] (main) Keycloak 999.0.0-SNAPSHOT on JVM (powered by Quarkus 3.14.4) started in 7.264s. Listening on: http://0.0.0.0:8080 and https://0.0.0.0:8443. Management interface listening on https://0.0.0.0:9000.
2024-09-27 07:35:33,740 INFO  [io.quarkus] (main) Profile dev activated.
2024-09-27 07:35:33,740 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, keycloak, micrometer, narayana-jta, opentelemetry, reactive-routes, rest, rest-jackson, smallrye-context-propagation, smallrye-health, vertx]
2024-09-27 07:35:33,744 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

**Comment by mchen-10** [comment]
resolved by skipping test  - after digging on running test suites following below steps helped me initially build then run tests

https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/HOW-TO-RUN.md

**Comment by codespearhead** [comment]
What JDK version, OS and processor do you have?

**Comment by mchen-10** [comment]
> What JDK version, OS and processor do you have?

jdk: OpenJDK Runtime Environment Homebrew (build 22.0.2)
OS: MacOS Sonoma 14.6.1

**Comment by codespearhead** [comment]
If you have an M1 processor, be sure you're using an ARM distribution of the JDK. Otherwise the JVM will be emulated by Rosetta, which could result in degraded performance at best, and cryptic errors at worst [1].

From what I can tell [2], Homebrew only installs the x64 distribution of the JDK.

[1] https://medium.com/@billynewport/fixing-poor-performance-using-java-with-vscode-on-macbook-21e70ecd28d2
[2] https://formulae.brew.sh/cask/temurin@21

**Comment by codespearhead** [comment]
If you have an M1 processor, be sure you're using an ARM64 (aka aarch64) distribution of the JDK. Otherwise the JVM will be emulated by Rosetta, which could result in degraded performance at best, and cryptic errors at worst [1].

Judging from [2], Homebrew only installs the x64 distribution of the JDK.

In that case, you can download the appropriate JDK here [3] and try again.

[1] https://medium.com/@billynewport/fixing-poor-performance-using-java-with-vscode-on-macbook-21e70ecd28d2
[2] https://formulae.brew.sh/cask/temurin@21
[3] https://adoptium.net/temurin/releases/?os=mac&arch=aarch64&package=jdk&version=21

**Comment by mchen-10** [comment]
I have tried a few different versions, most of which are aarch64 JDKs - screenshot of java versions
<img width="1433" alt="Screenshot 2024-10-02 at 9 02 55 PM" src="https://github.com/user-attachments/assets/d4a96bad-099a-4af7-a77e-f00d18602814">

Unfortunately when I get to the following step, it still fails - do I need to be running anything locally when running the test?
```
mvn -f testsuite/integration-arquillian/pom.xml clean install
```
Here is a sample test report attached
<details>
  <summary>
sampleLog-PwdLessPubKeySignRegTest
  </summary>
classname=&quot;org.keycloak.testsuite.webauthn.registration.passwordless.PwdLessPubKeySignRegTest&quot; time=&quot;0.113&quot;&gt;
    &lt;error message=&quot;HTTP 500 Internal Server Error&quot; type=&quot;jakarta.ws.rs.InternalServerErrorException&quot;&gt;&lt;![CDATA[jakarta.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:250)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:41)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:136)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:102)
	at jdk.proxy2/jdk.proxy2.$Proxy193.remove(Unknown Source)
	at org.keycloak.testsuite.AbstractKeycloakTest.importRealm(AbstractKeycloakTest.java:506)
	at org.keycloak.testsuite.AbstractKeycloakTest.importTestRealms(AbstractKeycloakTest.java:376)
	at org.keycloak.testsuite.AbstractKeycloakTest.beforeAbstractKeycloakTest(AbstractKeycloakTest.java:188)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.jboss.arquillian.junit.Arquillian$StatementLifecycleExecutor.invoke(Arquillian.java:372)
	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.execute(ClientBeforeAfterLifecycleEventExecuter.java:88)
	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.on(ClientBeforeAfterLifecycleEventExecuter.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:114)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.before(EventTestRunnerAdaptor.java:115)
	at org.jboss.arquillian.junit.Arquillian$4.evaluate(Arquillian.java:194)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:344)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:48)
	at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:209)
	at org.keycloak.testsuite.AssertEvents$1.evaluate(AssertEvents.java:79)
	at org.jboss.arquillian.junit.Arquillian$7$1.invoke(Arquillian.java:273)
	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.execute(ClientBeforeAfterLifecycleEventExecuter.java:88)
	at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.on(ClientBeforeAfterLifecycleEventExecuter.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:114)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.fireCustomLifecycle(EventTestRunnerAdaptor.java:159)
	at org.jboss.arquillian.junit.Arquillian$7.evaluate(Arquillian.java:267)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:160)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:344)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:48)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:171)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:109)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]&gt;&lt;/error&gt;
</details>

**Comment by codespearhead** [comment]
> Do I need to be running anything locally when running the test?

No [1].

> Here is a sample test report attached.

Perhaps related to [2]. Tell us the output of those two commands:

```bash
mvn -f testsuite/integration-arquillian/pom.xml clean install -Dtest=PwdLessPubKeySignRegTest
```

```bash
mvn -f testsuite/integration-arquillian/pom.xml clean install -Dtest=PubKeySignRegisterTest 
```

[1] https://github.com/keycloak/keycloak/blob/51fd133f051f2f4159cfc7dd7417bb2b7ea7472f/testsuite/integration-arquillian/HOW-TO-RUN.md?plain=1#L14
[2] https://github.com/keycloak/keycloak/issues/33369

**Comment by mabartos** [comment]
@mchen-10 Thanks for creating the issue. However, I'm not able to reproduce it. Please, try it with the latest upstream main branch.

In order to build the whole Keycloak from the source, just skip the whole tests execution:
```
./mvnw clean install -DskipTests
```

When you want to execute specific tests, just use the `-Dtest=<TEST-NAME>` property, as @codespearhead mentioned.
