### ISSUE TITLE
Unable to update/query local user profile if LDAP connection fails

### ISSUE THREAD

**Issue by amolai** [keycloak/keycloak#33380]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I have integrated keycloak with my application, and have added a LDAP connection. When the LDAP Connection is correctly added things work smooth and as expected. However, if there is an issue with LDAP Connection then user profile update/ user query fails even for Local users(Realm users). 

**On version 25.0.2 and 25.0.6**
I created a "test" user but only provided username and password. When tried to login through the keycloak login ui, it got redirected to required-action screen and asked for email, firstname and lastname. Upon entering these fields got a error on the screen and below logs in the logs.  

`2024-09-30 06:57:00,676 INFO  [org.keycloak.storage.ldap.LDAPIdentityStoreRegistry] (executor-thread-4) Creating new LDAP Store for the LDAP storage provider: 'ldap_test', LDAP Configuration: {pagination=[false], fullSyncPeriod=[-1], startTls=[false], usersDn=[ou=myldap,o=test.com], connectionPooling=[true], cachePolicy=[DEFAULT], useKerberosForPasswordAuthentication=[false], importEnabled=[true], enabled=[true], changedSyncPeriod=[-1], usernameLDAPAttribute=[mail], vendor=[other], uuidLDAPAttribute=[uid], connectionUrl=[ldaps://myldap.test.com:626], allowKerberosAuthentication=[false], syncRegistrations=[false], authType=[none], krbPrincipalAttribute=[krb5PrincipalName], customUserSearchFilter=[(|(dept=00E640)(dept=B2C))], debug=[false], searchScope=[2], useTruststoreSpi=[undefined], usePasswordModifyExtendedOp=[false], trustEmail=[false], userObjectClasses=[organizationalPerson], rdnLDAPAttribute=[mail], editMode=[READ_ONLY], validatePasswordPolicy=[false], batchSizeForSync=[1000]}, binaryAttributes: []
2024-09-30 06:58:13,617 ERROR [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager] (executor-thread-7) Could not query server using DN [ou=myldap,o=test.com] and filter [(&(|(dept=00E640)(dept=B2C))(mail=test@admin.com)(objectclass=organizationalPerson))]: javax.naming.InterruptedNamingException: Interrupted while waiting for the connection pool lock
	at java.naming/com.sun.jndi.ldap.pool.Connections.grabLock(Connections.java:366)
	at java.naming/com.sun.jndi.ldap.pool.Pool.getPooledConnection(Pool.java:140)
	at java.naming/com.sun.jndi.ldap.LdapPoolManager.getLdapClient(LdapPoolManager.java:341)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1608)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:74)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:93)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:709)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:704)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:255)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:278)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:174)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getFirstResult(LDAPQuery.java:185)
	at org.keycloak.storage.ldap.LDAPStorageProvider.queryByEmail(LDAPStorageProvider.java:745)
	at org.keycloak.storage.ldap.LDAPStorageProvider.getUserByEmail(LDAPStorageProvider.java:752)
	at org.keycloak.storage.UserStorageManager.lambda$getUserByEmail$20(UserStorageManager.java:426)
	at org.keycloak.utils.ServicesUtils.lambda$timeBoundOne$1(ServicesUtils.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.keycloak.storage.UserStorageManager.getUserByEmail(UserStorageManager.java:426)
	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByEmail(UserCacheSession.java:419)
	at org.keycloak.userprofile.validator.DuplicateEmailValidator.validate(DuplicateEmailValidator.java:70)
	at org.keycloak.userprofile.AttributeValidatorMetadata.validate(AttributeValidatorMetadata.java:80)
	at org.keycloak.userprofile.DefaultAttributes.validate(DefaultAttributes.java:169)
	at org.keycloak.userprofile.DefaultUserProfile.validate(DefaultUserProfile.java:76)
	at org.keycloak.userprofile.DefaultUserProfile.update(DefaultUserProfile.java:104)
	at org.keycloak.authentication.requiredactions.UpdateProfile.processAction(UpdateProfile.java:75)
	at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:1156)
	at org.keycloak.services.resources.LoginActionsService.requiredActionPOST(LoginActionsService.java:1090)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$requiredActionPOST_02b0bc04a277d23515b0317d630ef043b756d133.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-09-30 06:58:13,619 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: org.keycloak.models.ModelException: LDAP Query failed
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:178)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getFirstResult(LDAPQuery.java:185)
	at org.keycloak.storage.ldap.LDAPStorageProvider.queryByEmail(LDAPStorageProvider.java:745)
	at org.keycloak.storage.ldap.LDAPStorageProvider.getUserByEmail(LDAPStorageProvider.java:752)
	at org.keycloak.storage.UserStorageManager.lambda$getUserByEmail$20(UserStorageManager.java:426)
	at org.keycloak.utils.ServicesUtils.lambda$timeBoundOne$1(ServicesUtils.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.keycloak.storage.UserStorageManager.getUserByEmail(UserStorageManager.java:426)
	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByEmail(UserCacheSession.java:419)
	at org.keycloak.userprofile.validator.DuplicateEmailValidator.validate(DuplicateEmailValidator.java:70)
	at org.keycloak.userprofile.AttributeValidatorMetadata.validate(AttributeValidatorMetadata.java:80)
	at org.keycloak.userprofile.DefaultAttributes.validate(DefaultAttributes.java:169)
	at org.keycloak.userprofile.DefaultUserProfile.validate(DefaultUserProfile.java:76)
	at org.keycloak.userprofile.DefaultUserProfile.update(DefaultUserProfile.java:104)
	at org.keycloak.authentication.requiredactions.UpdateProfile.processAction(UpdateProfile.java:75)
	at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:1156)
	at org.keycloak.services.resources.LoginActionsService.requiredActionPOST(LoginActionsService.java:1090)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$requiredActionPOST_02b0bc04a277d23515b0317d630ef043b756d133.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@3f9d2d87
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:294)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:174)
	... 38 more
Caused by: javax.naming.InterruptedNamingException: Interrupted while waiting for the connection pool lock
	at java.naming/com.sun.jndi.ldap.pool.Connections.grabLock(Connections.java:366)
	at java.naming/com.sun.jndi.ldap.pool.Pool.getPooledConnection(Pool.java:140)
	at java.naming/com.sun.jndi.ldap.LdapPoolManager.getLdapClient(LdapPoolManager.java:341)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1608)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:74)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:93)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:709)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.execute(LDAPOperationManager.java:704)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.search(LDAPOperationManager.java:255)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:278)
	... 39 more
`

Similar behavior is observered in 23.0.5

Additionally the following API also fails for both the version if the LDAP is wrongly configured

URI : https://<hostname>/admin/realms/myrealm/users?first=0&max=11&search=*

### Version

25.0.2 and 23.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

1. If LDAP connection fails then atleast the local users from realm should be fetched 
2. Local user profile update must be allowed

### Actual behavior

Exception is generated as shown above and 504 gateway timeout is observed

![image](https://github.com/user-attachments/assets/5f48ebc9-cae9-4950-b655-3b3d82541189)

### How to Reproduce?

For 25.0.2/25.0.6
1. Create a test user without adding mandatory fields(email, firstname and lastname). This could done from admin ui
2. Add an invalid LDAP connection - enable it
3. Try to login using the test user, a required action screen will appear. Update the data and submit. 
4. The screen will error out

For 23.0.5
1. For user add a required action like UPDATE_PROFILE and repeat the above steps (since email etc is not valid in 23.0.5)

**Comment by pedroigor** [comment]
When there is a LDAP provider in a realm, certain operations on users will end up reaching out the LDAP and failing even though the user is a local user.

We need to review how we run LDAP and other user providers to make sure they don't impact local users. A similar behavior happens when searching for users where if the LDAP configuration is broken searching for users will fail.

**Comment by amolai** [comment]
@pedroigor Thanks for responding. If possible, please update here whenever this will be taken up for fixing.

**Comment by pedroigor** [comment]
As mentioned in https://github.com/keycloak/keycloak/issues/33380#issuecomment-2385949989 we should be discussing improvements to error handling when failing to execute operations in LDAP.

Some possible improvements can be:

* Allow configuring the LDAP provider not to fail requests when not possible to execute operations in LDAP and handle situations where the local account will be unsynced with LDAP until the connection is restored
* Improve error message to make more explicit that the system is in a failing state (LDAP connection not working) so that they can not proceed with authentication


IMO, querying users through the User API is a separate issue because we need to discuss how we'll be handling errors when fetching users from multiple user storage providers. Today, we just fail if a single user storage provider fails and that prevents querying not only federated users but also local users. For that, we can discuss improvements to the UI to allow searching local vs federated users or change how we iterate over providers to still be able to fetch users from local and other user providers that are in a healthy state.

**Comment by sguilhen** [comment]
Failing this particular update profile operation is not really wrong. However, returning 504 with a generic error message doesn't seem the best way to inform users of what the problem is.

What is happening is that when you update a user's e-mail, Keycloak validates this e-mail to guarantee it's not already associated with another user. If you have a federation configured (LDAP for example), and this federation is not reachable for whatever reason, Keycloak can't guarantee that there are no users associated with the new e-mail because it was unable to verify this with one of the providers.

We could include a switch in the provider, something like "Ignore provider on failure", that would basically skip the provider in case of connection failures and allow operations to proceed. But this could have unintended consequences if, for example, you allow a user to update an e-mail while LDAP was out, and then find out there exists another user in LDAP with the same e-mail when it gets back up. So it would have to be used carefully.

**Comment by ghost** [comment]
Are there any updates on this issue? Is this planned for the upcoming releases?

**Comment by martin-kanis** [comment]
This issue should be fixed by recent LDAP improvements: #42276 #43639 #42589
