### ISSUE TITLE
Keycloak ISPN cache failure after realm is updated

### ISSUE THREAD

**Issue by 40pyd** [keycloak/keycloak#33402]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

We have configured the 24.0.3 keycloak HA cluster with ISPN cache enabled (no external ISPN server, just horizontal model) and only 2 nodes available. When both Keycloak instances are successfully started the server log files on both sides contain the cache initialization information showing both nodes are connected to cluster. The issue appears after performing following reproduction steps:

Open the admin console on one of the nodes
Create new realm - the success message is shown
Create new user federation - the success message is shown
Sync all user of newly created user federation - the success message is shown
Switch to Realm settings tab, change one of properties on General subtab (even Display name will do) and click Save button - the error message is shown stating the Realm cannot be saved
The log file contains the following error message:
```
2024-09-30 05:46:33,052 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread–p4-t1) ISPN000136: Error executing command PutKeyValueCommand on Cache ‘work’, writing keys [task::ClearExpiredEvents]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 1086 from PCADAPP02-43383 after 15 seconds
at org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:179)
at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:88)
at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-30 05:46:33,052 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredEvents: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 1086 from PCADAPP02-43383 after 15 seconds
at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:258)
at org.infinispan.cache.impl.InvocationHelper.doInvoke(InvocationHelper.java:323)
at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:111)
at org.infinispan.cache.impl.InvocationHelper.invoke(InvocationHelper.java:93)
at org.infinispan.cache.impl.CacheImpl.putIfAbsent(CacheImpl.java:1334)
at org.infinispan.cache.impl.CacheImpl.putIfAbsent(CacheImpl.java:1328)
at org.infinispan.cache.impl.CacheImpl.putIfAbsent(CacheImpl.java:1324)
at org.infinispan.cache.impl.CacheImpl.putIfAbsent(CacheImpl.java:236)
at org.infinispan.cache.impl.AbstractDelegatingCache.putIfAbsent(AbstractDelegatingCache.java:118)
at org.infinispan.cache.impl.AbstractDelegatingCache.putIfAbsent(AbstractDelegatingCache.java:118)
at org.infinispan.cache.impl.EncoderCache.putIfAbsent(EncoderCache.java:207)
at org.keycloak.cluster.infinispan.InfinispanClusterProviderFactory.lambda$putIfAbsentWithRetries$1(InfinispanClusterProviderFactory.java:149)
at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:102)
at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:89)
at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:80)
at org.keycloak.cluster.infinispan.InfinispanClusterProviderFactory.putIfAbsentWithRetries(InfinispanClusterProviderFactory.java:143)
at org.keycloak.cluster.infinispan.InfinispanClusterProvider.tryLock(InfinispanClusterProvider.java:144)
at org.keycloak.cluster.infinispan.InfinispanClusterProvider.executeIfNotExecuted(InfinispanClusterProvider.java:74)
at org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner.runTask(ClusterAwareScheduledTaskRunner.java:52)
at org.keycloak.services.scheduled.ScheduledTaskRunner.lambda$run$0(ScheduledTaskRunner.java:59)
at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:257)
at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:379)
at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:256)
at org.keycloak.services.scheduled.ScheduledTaskRunner.run(ScheduledTaskRunner.java:53)
at org.keycloak.timer.basic.BasicTimerProvider$1.run(BasicTimerProvider.java:53)
at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
at java.base/java.util.TimerThread.run(Timer.java:516)
```
The contents of our ispn-config.xml file:
![image](https://github.com/user-attachments/assets/d3388e4a-d4fd-401d-82b5-f2715a4ed16a)

The list of approaches we already unsuccessfully used:

1. Change cache-stack from UDP to TCP (known issue)
2. Configure ISPN caches as per instruction (some local, some distributed, work → replicated)
3. Adding the JDGROUPS configuration element and using it as container stack
4. Applying mode=“SYNC” to all caches, to ‘work’ cache
5. Adding ‘socket-binding’ element with ‘MPING’ and DB connection configuration
6. Adding <transaction-mode=“NON_XA” and locking=“OPTIMISTIC” />
7. Changing caches owners to 2 + combination of mode=“SYNC” on ‘work’ cache and all caches
8. Changing caches owners to 1 + combination of mode=“SYNC” on ‘work’ cache and all caches
9. Removed ‘work’ cache at all
10. Using User Federation with “NO CACHE” configured
11. Increasing the “remote timeout” to 60 sec
12. Increasing the “cache timeout” to 60 sec
13. Applying simple cache=“true” parameter to all local caches (realms, users, authorization, etc.)
14. Use latest Keycloak 25.0.6 (with latest infinispan) on both nodes
15. Use ‘work’ cache as local
16. Decrease ‘locking-timeout’ on both nodes from 60000 to 10000
17. Decrease ‘locking-timeout’ on one of nodes from 60000 to 0
18. The ‘work’ cache as replicated without any additional parameters

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

The realm is updated and the updates are shared between nodes

### Actual behavior

The realm update fails with an error message shown in the console and error message added to server log

### How to Reproduce?

1. Start both Keycloak instances in cluster
2. Open the admin console on one of the nodes
3. Create new realm - the success message is shown
4. Create new user federation - the success message is shown
5. Sync all user of newly created user federation - the success message is shown
6. Switch to Realm settings tab, change one of properties on General subtab (even Display name will do) and click Save button - the error message is shown stating the Realm cannot be saved

**Comment by ahus1** [comment]
@mhajas / @pruivo - I heard you're investigating a similar issue. Can you please have a look (at least triaging this issue)? Thanks!

**Comment by pruivo** [comment]
@40pyd Hey! I've downloaded KC 24.0.3 and followed the steps provided, but it's never failed. 

Can you share more information? What are your realm settings? How many realms do you have? What is the provider's type and configuration (timeouts, sync period)?

Can you upload the logs from both nodes + thread dumps from the time closer to the issue? 

Thank you!

**Comment by sschu** [comment]
Furthermore, shouldn't the work cache be a replicated cache since local cache invalidations need to be processed on all nodes?

**Comment by pruivo** [comment]
@sschu Yes, to be on the safe side, it should be replicated.
A distributed cache will work too if you set `owners` > `number of nodes in your cluster`; it is error prone if you scale your cluster above the `owners` and cause data to be staled.

**Comment by ahus1** [comment]
@pruivo - do we want to add a safety check to Keycloak that it would log a warning, and (for the next major release) even make Keycloak not start with such a setting as it is known to cause trouble?

**Comment by pruivo** [comment]
I give it a thought and I have 3 alternatives that we can choose from:

1. Prevent Keycloak from starting.
2. Remove the `work` cache from the XML configuration and always configure it internally.
3. Use cluster listener when a distributed cache is configured. 

@ahus1 should I open a GHI for further discussion?

**Comment by 40pyd** [comment]
Hello everyone, thank you for jumping on this issue. We managed to resolved it with the following changes applied:
1. Explicitly specify the ispn configuration file in keycloak config, not sure why by without that even breaking changes in ispn config file are not reflected during runtime
2.  Changing 'work' cache type to 'replicated-cache' and more important adding 'transaction' with 'NON_XA' mode 
This issue can now be closed

**Comment by pruivo** [comment]
@40pyd can you elaborate, please? 

Regarding number 1, are you saying if you modify the `cache-ispn.xml` file, the file isn't read?

Regarding number 2, the `work` cache is replicated by default, see [1]. Also, Keycloak does not start Infinispan transactions, and enabling them brings no benefit. 

[1] 
https://github.com/keycloak/keycloak/blob/af53af1506daa87d2c0c13cbdab5b50a87771f19/quarkus/runtime/src/main/resources/cache-ispn.xml#L69-L71

**Comment by ahus1** [comment]
@pruivo / @40pyd - with the file not being read unless it is specified on the CLI is something I reported here: #31492 - please upvote it there.

**Comment by ahus1** [comment]
@pruivo - please create a PR that safeguards Keycloak that the work cache is always a replicated cache. If this isn't the case, Keycloak shouldn't start. 

With the latest comment from the author, and the other issue about the file not being read, this should resolve all there is for this issue.

**Comment by pruivo** [comment]
> @pruivo - please create a PR that safeguards Keycloak that the work cache is always a replicated cache. If this isn't the case, Keycloak shouldn't start.
> 
> With the latest comment from the author, and the other issue about the file not being read, this should resolve all there is for this issue.

Done: https://github.com/keycloak/keycloak/issues/33702
