### ISSUE TITLE
Keyclaok 26 fails to start

### ISSUE THREAD

**Issue by sebhoss** [keycloak/keycloak#33608]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

After updating to Keycloak 26 we get the following stack trace:

```console
2024-10-05 05:44:03,157 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
2024-10-05 05:44:03,816 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2024-10-05 05:44:04,051 WARN  [org.jgroups.stack.Configurator] (ForkJoinPool.commonPool-worker-1) JGRP000014: ThreadPool.thread_dumps_threshold has been deprecated: ignored
2024-10-05 05:44:04,073 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2024-10-05 05:44:04,074 INFO  [org.jgroups.JChannel] (ForkJoinPool.commonPool-worker-1) local_addr: 3b448b6a-996c-4362-83ff-9b0651fbb081, name: keycloak-bc68ffcfb-bjhcd-14267
2024-10-05 05:44:04,082 INFO  [org.jgroups.protocols.FD_SOCK2] (ForkJoinPool.commonPool-worker-1) server listening on *.57800
2024-10-05 05:44:04,139 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000094: Received new cluster view for channel ISPN: [keycloak-6586bdc88c-6m7g8-47985|150] (3) [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267]
2024-10-05 05:44:04,210 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000079: Channel `ISPN` local address is `keycloak-bc68ffcfb-bjhcd-14267`, physical addresses are `[10.24.156.148:7800]`
2024-10-05 05:44:04,450 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=org.infinispan.CONFIG] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 633
2024-10-05 05:44:04,476 INFO  [org.infinispan.LIFECYCLE] (non-blocking-thread--p2-t5) [Context=org.infinispan.CONFIG] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 633
2024-10-05 05:44:04,546 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) [Context=actionTokens] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 670
2024-10-05 05:44:04,560 INFO  [org.infinispan.LIFECYCLE] (non-blocking-thread--p2-t14) [Context=actionTokens] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 670
2024-10-05 05:44:04,623 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=authenticationSessions] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 661
2024-10-05 05:44:04,630 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) [Context=authenticationSessions] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 661
2024-10-05 05:44:04,774 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=clientSessions] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 663
2024-10-05 05:44:04,780 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) [Context=clientSessions] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 663
2024-10-05 05:44:04,817 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=loginFailures] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 662
2024-10-05 05:44:04,827 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=loginFailures] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 662
2024-10-05 05:44:04,855 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=offlineClientSessions] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 667
2024-10-05 05:44:04,860 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) [Context=offlineClientSessions] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 667
2024-10-05 05:44:04,887 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=offlineSessions] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 673
2024-10-05 05:44:04,890 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) [Context=offlineSessions] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 673
2024-10-05 05:44:04,923 INFO  [org.infinispan.LIFECYCLE] (jgroups-11,keycloak-bc68ffcfb-bjhcd-14267) [Context=sessions] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology id 662
2024-10-05 05:44:04,926 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) [Context=sessions] ISPN100010: Finished rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], topology id 662
2024-10-05 05:44:04,951 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) [Context=work] ISPN100002: Starting rebalance with members [keycloak-6586bdc88c-6m7g8-47985, keycloak-6586bdc88c-89ld8-16888, keycloak-bc68ffcfb-bjhcd-14267], phase READ_OLD_WRITE_ALL, topology 

2024-10-05 05:44:05,151 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: keycloak-bc68ffcfb-bjhcd-14267, Site name: null
2024-10-05 05:44:06,308 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 3 ResultSet(s) and 0 Statement(s)
2024-10-05 05:44:06,383 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (jgroups-5,keycloak-bc68ffcfb-bjhcd-14267) ISPN000136: Error executing command PutKeyValueCommand on Cache 'actionTokens', writing keys [loaded.revoked]: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from keycloak-6586bdc88c-89ld8-16888, see cause for remote stack trace
	at org.infinispan.remoting.transport.ResponseCollectors.wrapRemoteException(ResponseCollectors.java:26)
	at org.infinispan.remoting.transport.ValidSingleResponseCollector.withException(ValidSingleResponseCollector.java:37)
	at org.infinispan.remoting.transport.impl.SingleTargetRequest.addResponse(SingleTargetRequest.java:75)
	at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
	at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1556)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1457)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1649)
	at org.jgroups.JChannel.up(JChannel.java:748)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:941)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:139)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:853)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:235)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1144)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:880)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:862)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:474)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:669)
	at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:190)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
	at org.jgroups.protocols.Discovery.up(Discovery.java:296)
	at org.jgroups.stack.Protocol.up(Protocol.java:360)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1230)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:95)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Unsupported protocol version 152
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.infinispan.marshall.exts.ThrowableExternalizer.newThrowableInstance(ThrowableExternalizer.java:286)
	at org.infinispan.marshall.exts.ThrowableExternalizer.readGenericThrowable(ThrowableExternalizer.java:264)
	at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:239)
	at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:44)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.remoting.responses.ExceptionResponse$Externalizer.readObject(ExceptionResponse.java:49)
	at org.infinispan.remoting.responses.ExceptionResponse$Externalizer.readObject(ExceptionResponse.java:41)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1548)
	... 25 more

2024-10-05 05:44:06,493 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-10-05 05:44:06,507 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-10-05 05:44:06,550 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-10-05 05:44:06,550 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000217: Received exception from keycloak-6586bdc88c-89ld8-16888, see cause for remote stack trace
2024-10-05 05:44:06,550 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unsupported protocol version 152
```

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak should start

### Actual behavior

Does not start

### How to Reproduce?

We are using the official Keycloak docker image to start and run it with multiple replicas in Kubernetes. I can provide the YAML manifests if that is required. This instance was updated from the latest 25.x version to 26

**Comment by sschu** [comment]
@sebhoss It looks like you are doing a rolling upgrade of Keycloak. This is not supported. You need to stop all pods and then restart.

**Comment by sebhoss** [comment]
oh yeah we are doing a rolling upgrade. Would the correct way in Kubernetes be to use the Recreate strategy then? Because I dont want to update multiple instances all by hand..?

**Comment by sebhoss** [comment]
Ok using Recreate fixes this - however we now have a small downtime everytime there is a Keycloak update. We used a Deployment with rolling upgrades because we wanted to have zero downtimes which worked fine for past version updates (I think we started with 23 and updated to every version up until 26 now). I guess that's not possible for every new version though?

**Comment by sschu** [comment]
@sebhoss Zero downtime updates are not supported for two reasons: a) Incompatibilities in the distributed caches (e.g. due to changed Infinispan version like in this case) and b) database incompatibilities because Keycloak updates contain database migrations. So sometimes it can work, but generally it is not supported and there is normally a downtime to update Keycloak.

**Comment by sebhoss** [comment]
@sschu Ok thanks - sorry for the trouble
