### ISSUE TITLE
Keycloak 26.0.0 fails to start ERROR: Session not bound to a realm

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#33637]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When I start keycloak 26.0.0 it fails with an error 

        kc.sh show-config

Next time you run the server, just run:

        kc.sh start --https-key-store-file=keycloak-26.0.0/certs/keystore.ks --https-trust-store-file=keycloak-26.0.0/certs/truststore.ks --http-enabled=false --http-port=5553 --https-port=5555 --hostname-strict=false --hostname=A02YKJRE1VZG --https-key-store-type=JKS --https-trust-store-type=JKS --https-trust-store-type=JKS --vault-file=/Users/ajaykumarjaiswal/.mytest/certificates/mytest-keystore.p12 --log-level=INFO --log=console,file --log-file=../data/log/server.log --cache=local --log-console-format='%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n' --log-file-format='%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n' --spi-theme-welcome-theme=mytest.v2 --optimized

'2024-10-07 16:52:42,791 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following run time options were found, but will be ignored during build time: kc.spi-realm-restapi-extension-mytest-identity-provider-vault-password, kc.spi-admin-realm, kc.spi-hostname-v2-hostname-strict, kc.spi-vault-keystore-pass, kc.spi-hostname-v2-hostname, kc.spi-realm-restapi-extension-mytest-auth-provider-vault-password, kc.spi-realm-restapi-extension-mytest-auth-provider-vault-keystore, kc.spi-vault-keystore-file, kc.spi-realm-restapi-extension-mytest-identity-provider-vault-keystore, kc.spi-theme-welcome-theme

''2024-10-07 16:52:42,791 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
        - legacy-observability-interface
Consult the Release Notes for details.
''2024-10-07 16:52:43,657 INFO  [org.keycloak.url.HostnameV2ProviderFactory] (main) If hostanme is specified, hostname-strict is effectively ignored
''2024-10-07 16:52:45,112 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
''2024-10-07 16:52:45,324 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for sessions to 10000 entries.
''2024-10-07 16:52:45,325 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for clientSessions to 10000 entries.
''2024-10-07 16:52:45,325 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineSessions to 10000 entries.
''2024-10-07 16:52:45,326 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineClientSessions to 10000 entries.
''2024-10-07 16:52:45,858 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
''2024-10-07 16:52:46,687 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
''2024-10-07 16:52:46,714 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_920638, Site name: null
''2024-10-07 16:52:47,092 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
''2024-10-07 16:52:47,221 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory keycloak-26.0.0/bin/../realms-to-import
''2024-10-07 16:52:47,808 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: IGNORE_EXISTING
''2024-10-07 16:52:47,810 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully
''2024-10-07 16:52:47,812 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
''2024-10-07 16:52:47,818 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
''2024-10-07 16:52:47,828 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
''2024-10-07 16:52:47,891 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
''2024-10-07 16:52:47,891 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Session not bound to a realm
''2024-10-07 16:52:47,891 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
'

**2024-10-07 16:26:31,796 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
''2024-10-07 16:26:31,796 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Session not bound to a realm**

```
class MyProviderFactory implements RealmResourceProviderFactory, ProviderEventListener {

@Override
    public void onEvent(ProviderEvent event) {
        if (event instanceof PostMigrationEvent postMigrationEvent) {
            KeycloakModelUtils.runJobInTransaction(postMigrationEvent.getFactory(), new MyCustomProvider());
        }
    }
    ...
    ...
}
    


class MyCustomProvider extends implements KeycloakSessionTask
{

 @Override
    public void run(KeycloakSession session) {
        session.getProvider(DatastoreProvider.class).realms().getRealmsStream().forEach(this::migrateRealmComponents);
    }
    
    
private void migrateRealmComponents(RealmModel realm) {
        realm.getIdentityProvidersStream()
}
...
...
...
}
```

it breaks here

<img width="767" alt="image" src="https://github.com/user-attachments/assets/116de579-cf81-4e69-9d56-482301ea1a99">

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

It should start seamless

### Actual behavior

It's failing to start

### How to Reproduce?

dfsfsdf

### Anything else?

26.0.0 is latest , And this error is not there on internet as of now.

**Comment by sschu** [comment]
This is not easily reproducible as it contains some parameters/files specific to your environment. Can you please try to transform this into a minimal example that I can reproduce locally?

**Comment by shawkins** [comment]
> 2024-10-07 16:52:42,791 WARN [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following run time options were found, but will be ignored during build time: kc.spi-realm-restapi-extension-mytest-identity-provider-vault-password

Will be addressed by https://github.com/keycloak/keycloak/issues/33638 - it is not related to any other issues that you are seeing. It also should only be emitted on a non-optimized start, so if you are running different commands than the ones shown, please include them.

> 024-10-07 16:52:42,791 WARN [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
- legacy-observability-interface

This should only be emitted if legacy-observability-interface is used as an option - which is not shown in the command given. Again, if you are running different commands than the ones shown, please include them.

**Comment by ajaiswal595** [comment]
> This is not easily reproducible as it contains some parameters/files specific to your environment. Can you please try to transform this into a minimal example that I can reproduce locally?

It breaks in my provider

private void migrateRealmComponents(RealmModel realm) {
        realm.getIdentityProvidersStream()
}

<img width="767" alt="image" src="https://github.com/user-attachments/assets/ac3420a7-a056-4787-997b-2ed5e355199d">

**Comment by ajaiswal595** [comment]
> > 2024-10-07 16:52:42,791 WARN [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following run time options were found, but will be ignored during build time: kc.spi-realm-restapi-extension-mytest-identity-provider-vault-password
> 
> Will be addressed by #33638 - it is not related to any other issues that you are seeing. It also should only be emitted on a non-optimized start, so if you are running different commands than the ones shown, please include them.
> 
> > 024-10-07 16:52:42,791 WARN [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
> 
> * legacy-observability-interface
> 
> This should only be emitted if legacy-observability-interface is used as an option - which is not shown in the command given. Again, if you are running different commands than the ones shown, please include them.

can you please check [https://github.com/keycloak/keycloak/issues/33637#issuecomment-2396802897](https://github.com/keycloak/keycloak/issues/33637#issuecomment-2396802897)

**Comment by ajaiswal595** [comment]
I updated the description and comments.

**Comment by stianst** [comment]
Please update the description to provide a better detail of what the problem is. I think perhaps reading through it you have a custom provider of sorts, and it's causing some issues. We also need steps to reproduce, but here you've simply written `dfsfsdf`.

~missing-info

**Comment by akoyl** [comment]
I have the  same issue with v26.0.0
2024-10-12 15:36:53,836 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-39) Uncaught server error: java.lang.IllegalArgumentException: Session not bound to a realm
        at org.keycloak.models.cache.infinispan.organization.InfinispanOrganizationProvider.getRealm(InfinispanOrganizationProvider.java:336)
        at org.keycloak.models.cache.infinispan.organization.InfinispanOrganizationProvider.count(InfinispanOrganizationProvider.java:289)
        at org.keycloak.storage.UserStorageManager.isReadOnlyOrganizationMember(UserStorageManager.java:943)
        at org.keycloak.storage.UserStorageManager.importValidation(UserStorageManager.java:117)
        at org.keycloak.storage.UserStorageManager.getUserById(UserStorageManager.java:389)
        at org.keycloak.models.cache.infinispan.UserCacheSession.getUserById(UserCacheSession.java:222)
        at com.invio.keycloak.even.listener.InvioUserEventListenerProviderFactory$1$1.lambda$commitImpl$0(InvioUserEventListenerProviderFactory.java:70)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:263)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:392)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:262)
        at com.invio.keycloak.even.listener.InvioUserEventListenerProviderFactory$1$1.commitImpl(InvioUserEventListenerProviderFactory.java:65)
        at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:46)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
        at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:414)
        at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:379)
        at org.keycloak.models.KeycloakBeanProducer_ProducerMethod_getKeycloakSession_XoSEUTXOsE3bpqXlGMAykCiECUM_ClientProxy.close(Unknown Source)
        at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:60)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.closeSession(CloseSessionFilter.java:67)
        at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.filter(CloseSessionFilter.java:63)
        at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)


**It breaks in my provider :**
         void userAdded(String realmId, String clientId, String userId) {
            session
                  .getTransactionManager()
                  .enlistAfterCompletion(
                        new AbstractKeycloakTransaction() {
                           @Override
                           protected void commitImpl() {
                              KeycloakModelUtils.runJobInTransaction(
                                    factory,
                                    (s) -> {
                                       RealmModel realm = s.realms().getRealm(realmId);
                                       **UserModel user = s.users().getUserById(realm, userId);    <----- HERE**
                                       getUserChangedHandler().onUserAdded(s, realm, user, clientId);
                                    });
                           }

                           @Override
                           protected void rollbackImpl() {}
                        });
         }

**Comment by ajaiswal595** [comment]
@akoyl 

Have you got the solution?

**Comment by akoyl** [comment]
@ajaiswal595 

No, not yet. I've tried many different things, but nothing worked.
I'm getting this error  when trying to get UserModel 
e.g.  UserModel user = session.users().getUserById(realm, userId);  

Tha same code works on v25.0.6

**Comment by Kavalinaveen** [comment]
I tried with version 26.0.2 i am getting the same issue and with latest keycloak also same issue 
2024-11-05T23:46:11.242+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:11,240 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-11-05T23:46:11.844+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:11,842 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_626611, Site name: null
2024-11-05T23:46:12.027+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:12,026 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-11-05T23:46:12.118+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:12,116 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory /opt/keycloak/bin/../data/import
2024-11-05T23:46:12.127+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:12,125 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2024-11-05T23:46:14.617+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:14,615 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: OVERWRITE_EXISTING
2024-11-05T23:46:20.512+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:20,511 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'voltacabs' imported
2024-11-05T23:46:20.701+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:20,700 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-11-05T23:46:20.723+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:20,722 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-11-05T23:46:20.839+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:20,838 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-11-05T23:46:20.840+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:20,839 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Session not bound to a realm
2024-11-05T23:46:20.840+05:30  INFO 119660 --- [ream--701245566] tc.keycloak/keycloak:latest              : STDOUT: 2024-11-05 18:16:20,839 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
2024-11-05T23:47:35.174+05:30 ERROR 119660 --- [           main] tc.keycloak/keycloak:latest              : Could not start container

**Comment by dnk** [comment]
in my case it was caused by "organization" feature.
after disabling "organization" feature error is gone

**Comment by ghenadiibatalski** [comment]
Same issue exists in 26.0.5

**Comment by ghenadiibatalski** [comment]
@akoyl for workaround see here https://github.com/keycloak/keycloak/issues/34398#issuecomment-2455107651

**Comment by shogunassar** [comment]
I fixed it by adding session context like this:
```
 KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(),  **session.getContext()**,  s -> {
               
            });
```

Before:
 ```
KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(),s -> {
               
            });
```
After (Fix):
```
 KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(),  session.getContext(), s -> {
               

            });
```

**Comment by TomJKing** [comment]
@stianst Is this issue confirmed as a bug, or are the workarounds mentioned in the comments ( [#34398 (comment)](https://github.com/keycloak/keycloak/issues/34398#issuecomment-2455107651) and [#33637 (comment](https://github.com/keycloak/keycloak/issues/33637#issuecomment-2525503080)) the accepted answer? 

The issue appears to have been automatically closed by the bot so not sure how to resolve this issue which I've also encountered on version 26.7

**Comment by tukez** [comment]
This is still a valid bug, can this be reopened? The API does not currently make sense, requiring the session to be bound to a realm should not be required, the example by @akoyl demonstrates this. https://github.com/keycloak/keycloak/issues/33637#issuecomment-2408553189

**Comment by olivierboudet** [comment]
In my case, I have this error when importing a json realm (with authorizations enabled)

```
2025-02-10 10:24:44,098 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.IllegalArgumentException: Session not bound to a realm
	at org.keycloak.models.cache.infinispan.idp.InfinispanIdentityProviderStorageProvider.getRealm(InfinispanIdentityProviderStorageProvider.java:423)
	at org.keycloak.models.cache.infinispan.idp.InfinispanIdentityProviderStorageProvider.count(InfinispanIdentityProviderStorageProvider.java:269)
	at org.keycloak.models.IdentityProviderStorageProvider.isIdentityFederationEnabled(IdentityProviderStorageProvider.java:201)
	at org.keycloak.models.jpa.RealmAdapter.isIdentityFederationEnabled(RealmAdapter.java:1321)
	at org.keycloak.models.cache.infinispan.UserCacheSession.fullyInvalidateUser(UserCacheSession.java:849)
	at org.keycloak.models.cache.infinispan.UserCacheSession.addUser(UserCacheSession.java:838)
	at org.keycloak.services.managers.ClientManager.enableServiceAccount(ClientManager.java:163)
	at org.keycloak.services.managers.RealmManager.setupClientServiceAccountsAndAuthorizationOnImport(RealmManager.java:818)
```

**Comment by ajaiswal595** [comment]
Hi all, this is marked as Not planned, and would not resolve the issues.

Considering it occurs for many upgrades for different people we should analyse and fix the issue.

It doesn't even let Keycloak start, so we should keep it as a high priority, please reopen and work on it.

**Comment by mirko-vetrano** [comment]
This is breaking my integration tests with testcontainers-keycloak, but the same procedure is working fine using keycloak directly. I'm using Keycloak 26.0.2 and I can confirm the issue is still there. I'm importing a realm too, like others said before. I may try to generate a new realm.json file (to find out if the issue is related to that specific format, I'm using it from Keycloak 21) but this will require a lot of time, I hoped for a fastest migration process from 25.0.6.

**Comment by mgpradeepa** [comment]
As @mirko-vetrano  mentions, the name of the realm and the name of the file being uploaded as <name>-realm.json should be identical. This solved the problem and the testcontainers worked.

**Comment by forwardmeasure** [comment]
It's a terrible decision, no matter the technical constraints< - why in the world should the file name matter when the realm name is in the JSON?. And to not update the documentation to reflect this is really not on, especially when so many companies use Keycloak as an integral part of their core infrastructure. At least 3 of my customers got tripped up by this.

**Comment by aDecoy** [comment]
So is keycloak just ok with the program not working?

**Comment by mabartos** [comment]
Hello, could you please verify if the issue still occurs in Keycloak 26.3.x? As Keycloak 26.0.0 is not supported anymore, we don't provide any fixes there.


@keycloak/core-iam @pedroigor Could you please retriage it once we have confirmation that the issue still exists in 26.3.x? As it seems the issue is related to the Organization feature: https://github.com/keycloak/keycloak/issues/34398#issuecomment-2455107651, https://github.com/keycloak/keycloak/issues/33637#issuecomment-2466412559

**Comment by aDecoy** [comment]
For me, the error was observed in keycloak:26.1.0. 

Workaround for others: 
Dont import realm in the Dockerfile when you build the keycloak application (aka. dont copy the realm.json file into /opt/keycloak/data/import) . 
Instead import it with the GUI after having startet the container with only the default realm.

**Comment by pedroigor** [comment]
We should probably document this, as we have seen others with the same issue. We did not advertise this change in the design of custom providers properly.

Basically, providers should be updated to make the realm available from the `KeycloakContext`. For instance:

```
private void migrateRealmComponents(KeycloakSession session, RealmModel realm) {
        session.getContext().setRealm(realm);
        realm.getIdentityProvidersStream()
}
```

FTR, some of the new SPIs are favoring a simpler API where the `RealmModel` is assumed to be available from the `KeycloakContext` bound to a `KeycloakSession` instead of propagating it as method parameters. Having the realm model as method parameters while also available from the context is error-prone and redundant.

Most of the time, you won't need to worry about setting the realm into the context if you are operating on multiple realms but the realm bound to the session that was used to create the provider.

**Comment by sguilhen** [comment]
I think we need to separate the issues described here - some seem to be related to custom providers, others by various different import issues.

For the custom providers, we need to fix the documentation to make it clear that every API call should happen in the context of a realm - i.e. the realm must be available in the context. For requests hitting the Rest API this is handled automatically by Keycloak, but custom providers creating new sessions must be aware of that.

For the import issues we seem to have two different ones - some related to a requirement that file names follow a specific pattern - I'm not aware of that personally but perhaps @shawkins can shed some light - and some related to failures to import previously exported realms from data/import.

For this second group, we will need to investigate and it would be helpful to have a sample export that displays the issue. AFAIK  the import mechanism was updated to always have the realm set in the session context, but we might have missed something.
