### ISSUE TITLE
max_age is wrongly handled Keycloak oidc Identity Provider leading to exception

### ISSUE THREAD

**Issue by brunomedeirosdedalus** [keycloak/keycloak#33641]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

The error happens when an application redirects the user to the Keycloak login page passing the parameter max_age=0 and kc_idp_hint with a alias of a Keycloak Identity Provider. Sometimes, the reauthentication fails with the exception 

```
2024-10-07 12:16:14,001 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-81) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: User not re-authenticated by the target OpenID Provider
	at org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:385)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:557)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_ab908fbdd086ee82e140d8a818c077362a2d04b4.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Whenever the application redirects the user to a Keycloak Identity Provider with max_age=0 the re-autentication should always be successful as long as the user explicitly authenticated.  

### Actual behavior

Once in a while the authentication fails even thought the user inserted the correct credentials.

### How to Reproduce?

- Create a Realm A;
- Create a Realm B;
- In Realm B, add a user federation (e.g., DB or LDAP) , preferably a bit slow;
- In Realm A create a Identity Provider of type Keycloak oidc, where you configure realm B to do identity Brokering against realm A (ie., to allow users to authenticate in realm A using the credentials store in realm B)
- Go to Realm A login page;
- Setup an application to login with Keycloak
- In this application add functionality that would force the user to reauthenticate using max_age=0 to simulate escalation of privileges 
- Go to the application then get redirect to the Realm A login page;
- Click on the IdP previously configured;
- login with a user;
- Then click on the application functionality that would force the user to reauthenticate again
- Re-authenticate, once in a while the authentication might fail

### Anything else?

I had a bit of a look at the source code myself and the problem seems to be in this part of the code:

https://github.com/keycloak/keycloak/blame/main/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L460

So the line

`if (authTimeInt + maxAgeInt < Time.currentTime())`

doesn't this mean that if someone passes max_age=0 (to tell the IdP to force authentication), then we only have 1 second between the time that the IDP reauthenticated and the time that the previous line of code is executed?

That seems semantically incorrect, because the user did re-authenticate.

Shouldn't we instead, check the timestamp of when we send the request to the IdP and then compare that time against the
authTimeInt + maxAgeInt and if it is lower, store that information and then check afterwards that indeed an authentication has happend?

Also shouldn't we also factor the 'Allowed clock skew' ?

**Comment by jonkoops** [comment]
Perhaps this has been fixed since #32764? Could you take a look at the latest version of Keycloak?

**Comment by brunomedeirosdedalus** [comment]
@jonkoops Thanks for the quick reply. Yes, I will have a look at it, and let you know the result.

**Comment by pedroigor** [comment]
> Shouldn't we instead, check the timestamp of when we send the request to the IdP and then compare that time against the
authTimeInt + maxAgeInt and if it is lower, store that information and then check afterwards that indeed an authentication has happend?

At that point, the authentication already happened at the IdP. Keycloak is processing the response once the user is authenticated.

The behavior looks correct to me because if the elapsed time since the ID token is issued (`auth_time` claim) plus the `max_age` is less then current time, it should fail. Perhaps the message is not so accurate because the user was authenticated in the IdP.

**Comment by brunomedeirosdedalus** [comment]
> > Shouldn't we instead, check the timestamp of when we send the request to the IdP and then compare that time against the
> > authTimeInt + maxAgeInt and if it is lower, store that information and then check afterwards that indeed an authentication has happend?
> 
> At that point, the authentication already happened at the IdP. Keycloak is processing the response once the user is authenticated.
> 
> The behavior looks correct to me because if the elapsed time since the ID token is issued (`auth_time` claim) plus the `max_age` is less then current time, it should fail. Perhaps the message is not so accurate because the user was authenticated in the IdP.

@pedroigor  Thanks for replying, but I can reproduce the issue, so there is something there. I can provide more information if you want, but first  please consider the following flow:
- A User is redirect to Keycloak to the IdP A with max_age=0;
- IdP A reads max_age=0, which means the IdP will force re-autentication, the user reauthenticate successfully, and you get auth_time set to 1728505221 (for example)
- Afterwards on Keycloak there will be that code checking that auth_time + maxAgeInt < Time.currentTime() then we have 1728505221 + 0 < Time.currentTime() if the current time 1728505222 (1 second after it will fail) even thought the user did re-authenticated. This happens only because the checking is done later than the actual authentication from the IdP.

or am I wrong?

**Comment by pedroigor** [comment]
I see now ... Thanks.

IMO, we can just ignore the check if `max_age` is `0`?

**Comment by brunomedeirosdedalus** [comment]
In my case, I workaround it by creating my own extension of KeycloakOIDCIdentityProvider which ignores that check. The rational was that since I know in my case that my external IdP is my own Keycloak (I am doing Identity Brokering between realms within the same Keycloak), I am positive that the external IdP (i.e., keycloak) forced the user to re-authenticate.

> IMO, we can just ignore the check if `max_age` is `0`?

If I understand the code correctly, I think you still have the same issue, because if max_age = 'x' (with x > 0), if the time passed between the external IdP setting the auth_time and the event 'auth_time + maxAgeInt < Time.currentTime()' happening is greater than 'X' the validation still fails, even thought the user authenticated on the external IdP.

I think the solution is to save the time before calling the external IdP, and compare with that one.

**Comment by pedroigor** [comment]
I meant ignore the check completley so it won't run that comparison. My point being that `0` means that you just want to check that the broker was able to exchange the code (re-authentication) and ignore the elapsed time since `authtime + maxage`.

**Comment by brunomedeirosdedalus** [comment]
Ok, but if you ignored, how do we know if the external IdP really force the user to re-authenticated or not? For OIDC compliant IdP, based on the OIDC standard we know that: https://openid.net/specs/openid-connect-core-1_0.html in section 15.1.  Mandatory to Implement Features for All OpenID Providers  tells that max_age must be implemented. So for OIDC compliant IdP we could theoretically ignore the check (albeit a bit risky).

**Comment by pedroigor** [comment]
@brunomedeirosdedalus I'm assuming that the response from the IdP with a `code` and the fact the broker is processing a token response from the IdP is already indicating that re-authentication happened. Not sure though if this is a correct assumption when `max_age` is `0`.

What we can also do is compare the current `auth_time` with the `auth_time` from the ID Token issued by the IdP.

In any case, I'm marking this one to `normal` to get more insight and feedback from others.

**Comment by brunomedeirosdedalus** [comment]
> @brunomedeirosdedalus I'm assuming that the response from the IdP with a `code` and the fact the broker is processing a token response from the IdP is already indicating that re-authentication happened. Not sure though if this is a correct assumption when `max_age` is `0`.
> 
> What we can also do is compare the current `auth_time` with the `auth_time` from the ID Token issued by the IdP.
> 
> In any case, I'm marking this one to `normal` to get more insight and feedback from others.

Thanks, for having a look. IMO, if your assumption is enough indication that the user re-authenticated, then we could skip the checking since it is up to the external IdP to act upon the max_age passed by the user. If we want to check something, we just need to check that the token that we got from IdP has a auth_time higher than the previous auth_time (more or less what you suggested if I am not wrong).

**Comment by brunomedeirosdedalus** [comment]
To be honest, I think there is no perfect solution since we don't know the exact time when the external IdP does its own checking that `auth_time + max_age < current time`. To be perfect, we would need to know that 'current time'.

I think that an acceptable alternative would be to use the current time as being the time before initiating the authentication and not after, because at least we don't run into the cases where we discard users that did re-authenticated.

I had a brief look at the code, and I came up with the following draft:

```
    @Override
    protected UriBuilder createAuthorizationUrl(AuthenticationRequest request) {
        (...)

        String maxAge = request.getAuthenticationSession().getClientNote(OIDCLoginProtocol.MAX_AGE_PARAM);

        if (getConfig().isPassMaxAge() && maxAge != null) {
            uriBuilder.queryParam(OIDCLoginProtocol.MAX_AGE_PARAM, maxAge);
            // We store when we called the external IdP
            authenticationSession.setClientNote("IDP_TIME_INIT_AUTH", String.valueOf(Time.currentTime()));
        }

        return uriBuilder;
    }
```
and then:

```
    @Override
    protected boolean isAuthTimeExpired(JsonWebToken idToken, AuthenticationSessionModel authSession) {
       (...)     

        String timeIdpCall = authSession.getClientNote("IDP_TIME_INIT_AUTH");
        int timeWhenAuthStarted = Integer.parseInt(timeIdpCall); 

        if (authTimeInt + maxAgeInt < timeWhenAuthStarted) {
            logger.warn("Invalid auth_time claim. User not re-authenticated by the target OP.");
            return true;
        }

        return false;
    }
```
So if the time of the authentication plus the max age is still before the time that we initiated the authentication then the IdP failed to enforce reauthentication of the user.

**Comment by Karan-EVBG** [comment]
This still is an open issue and blocking my re-authentication use case

**Comment by Karan-EVBG** [comment]
I'm facing the same problem (same keycloak version), when I am forcing re-authentication by passing max-age:0.

However I observed Keycloak debug logs and I see below error instead of the one reported:
`ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-100) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: Token is no longer valid`


Passing maxAge:5 makes it work for now for me, but this should still be fixed in the library as suggestions given earlier, the age of token should be checked from the time request was sent instead of after the token is received.

Can we re-open this ticket?
