### ISSUE TITLE
Uncaught server error: java.lang.NoSuchMethodError: 'jakarta.ws.rs.core.Response org.keycloak.services.cors.Cors.build()'

### ISSUE THREAD

**Issue by Hirutsu** [keycloak/keycloak#33679]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

2024-10-08 07:53:40,125 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-154) Uncaught server error: java.lang.NoSuchMethodError: 'jakarta.ws.rs.core.Response org.keycloak.services.cors.Cors.build()'
        at ru.factoringplus.keycloak.provider.RowiTokenExchangeProvider.exchangeClientToOIDCClient(RowiTokenExchangeProvider.java:373)
        at ru.factoringplus.keycloak.provider.RowiTokenExchangeProvider.exchangeClientToClient(RowiTokenExchangeProvider.java:298)
        at ru.factoringplus.keycloak.provider.RowiTokenExchangeProvider.tokenExchange(RowiTokenExchangeProvider.java:198)
        at ru.factoringplus.keycloak.provider.RowiTokenExchangeProvider.exchange(RowiTokenExchangeProvider.java:94)
        at org.keycloak.protocol.oidc.grants.TokenExchangeGrantType.process(TokenExchangeGrantType.java:62)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:140)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

200 and return token

### Actual behavior

500 Internal Error

### How to Reproduce?

upgrade keycloak to 25.0.05

**Comment by Hirutsu** [comment]
sry, my bad. Area is authorization and authentication

**Comment by Hirutsu** [comment]
The problem was with plugins and custom themes
![image](https://github.com/user-attachments/assets/87cf5b8a-eb12-4945-9ac2-b11192ce9522)
