### ISSUE TITLE
Using lightweight token in combination with DYNAMIC_SCOPES-feature failes

### ISSUE THREAD

**Issue by kepeder** [keycloak/keycloak#33684]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I'm trying to create a realm using a token issued with `admin-cli`-client / another custom client with the `Always use lightweight access token` toggle enabled. This results in an 500 exception which in my Docker logs looks like this: 

```
keycloak-1  | 2024-10-08 09:29:23,055 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-33) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.ClientModel.getClientScopes(boolean)" because "this.client" is null
keycloak-1  | 	at org.keycloak.protocol.oidc.rar.parsers.ClientScopeAuthorizationRequestParser.parseScopes(ClientScopeAuthorizationRequestParser.java:74)
keycloak-1  | 	at org.keycloak.services.util.AuthorizationContextUtil.getAuthorizationRequestContextFromScopes(AuthorizationContextUtil.java:57)
keycloak-1  | 	at org.keycloak.services.util.AuthorizationContextUtil.getAuthorizationRequestContextFromScopesWithClient(AuthorizationContextUtil.java:67)
keycloak-1  | 	at org.keycloak.services.util.AuthorizationContextUtil.getClientScopesStreamFromAuthorizationRequestContextWithClient(AuthorizationContextUtil.java:90)
keycloak-1  | 	at org.keycloak.protocol.oidc.TokenManager.attachAuthenticationSession(TokenManager.java:624)
keycloak-1  | 	at org.keycloak.services.util.UserSessionUtil.createTransientSessionForClient(UserSessionUtil.java:96)
keycloak-1  | 	at org.keycloak.services.util.UserSessionUtil.findValidSession(UserSessionUtil.java:40)
keycloak-1  | 	at org.keycloak.services.util.UserSessionUtil.findValidSession(UserSessionUtil.java:34)
keycloak-1  | 	at org.keycloak.services.resources.admin.permissions.MgmtPermissions.initIdentity(MgmtPermissions.java:119)
keycloak-1  | 	at org.keycloak.services.resources.admin.permissions.MgmtPermissions.<init>(MgmtPermissions.java:107)
keycloak-1  | 	at org.keycloak.services.resources.admin.permissions.AdminPermissions.realms(AdminPermissions.java:46)
keycloak-1  | 	at org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:142)
keycloak-1  | 	at org.keycloak.services.resources.admin.RealmsAdminResource$quarkusrestinvoker$importRealm_aa9defcbd5e1fb410aecd3ab57b280946687671e.invoke(Unknown Source)
keycloak-1  | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-1  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-1  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
keycloak-1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
keycloak-1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
keycloak-1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
keycloak-1  |

```

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Realm to be created

### Actual behavior

This is the HTTP response:
```
HTTP/1.1 500 Internal Server Error
content-length: 94
connection: close
Content-Type: application/json
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

{"error":"unknown_error","error_description":"For more on this error consult the server log."}
```

### How to Reproduce?

1. Initialize Keycloak 26.0.0 into an empty Postgresql DB.
2. Edit the admin-cli client with generating a client-secret.
3. Generate a token in token-endpoint.
4. POST /auth/admin/realms with that token and payload `{"realm":"internal","enabled":true}`.

Keycloak is set up with these features: `token-exchange,dynamic-scopes`

### Anything else?

The token looks like this:
```
{
  "exp": 1728380407,
  "iat": 1728380347,
  "jti": "923fe1b3-51a2-44b5-8f4f-5a79b2712d59",
  "iss": "http://localhost:8080/auth/realms/master",
  "sub": "bfe79a21-f4b5-466c-9ee2-ddc0d6d807a3",
  "typ": "Bearer",
  "azp": "admin-cli",
  "scope": "profile email"
}
```

The user info for the service-account:
```
{
  "id": "bfe79a21-f4b5-466c-9ee2-ddc0d6d807a3",
  "username": "service-account-admin-cli",
  "emailVerified": false,
  "createdTimestamp": 1728378974706,
  "enabled": true,
  "totp": false,
  "disableableCredentialTypes": [],
  "requiredActions": [],
  "notBefore": 0
}
```

Role-mappings:
```
{
    "realmMappings": [
        {
            "id": "218ecd39-e5a0-4586-bb75-bcf69521144e",
            "name": "default-roles-master",
            "description": "${role_default-roles}",
            "composite": true,
            "clientRole": false,
            "containerId": "72e35120-93f4-4046-afbb-4fbead579205"
        },
        {
            "id": "5f7c1213-e689-4dc0-8b36-81addb66cab4",
            "name": "admin",
            "description": "${role_admin}",
            "composite": true,
            "clientRole": false,
            "containerId": "72e35120-93f4-4046-afbb-4fbead579205"
        }
    ]
}
```

**Comment by binchen-lin** [comment]
Same affected. Kindly ask for a fix.
