### ISSUE TITLE
Keycloak 25 does not start until QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY is set to false

### ISSUE THREAD

**Issue by mgx0** [keycloak/keycloak#33698]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Hi there,

We have had a Keycloak 24 running fine (upgraded from older versions as they have been rolled out). Kubernetes, readonly filesystem with these writable folders:
- /opt/keycloak/data/tmp
- /tmp
- /opt/keycloak/lib/quarkus

After upgrading to Keycloak 25, we are getting this exception right after start

`WARN  [io.quarkus.narayana.jta.runtime.NarayanaJtaRecorder] (main) The recovery manager has already been shutdown: java.lang.NullPointerException: Cannot invoke "com.arjuna.ats.arjuna.recovery.RecoveryManager.terminate()" because "**this._recoveryManager**" is null`

when I set QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY to "false", it runs fine. Just a warning that the transaction manager recovery is disabled.

could anyone point me in some direction, where to look at and what's wrong? I feel I'm alone with this issue.

here's the full log:

```
2024-10-08 15:30:29,687 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following run time options were found, but will be ignored during build time: kc.spi-hostname-v2-hostname
2024-10-08 15:30:32,356 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
2024-10-08 15:30:32,870 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2024-10-08 15:30:33,090 WARN  [org.jgroups.stack.Configurator] (ForkJoinPool.commonPool-worker-1) JGRP000014: ThreadPool.thread_dumps_threshold has been deprecated: ignored
2024-10-08 15:30:33,098 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000078: Starting JGroups channel `ISPN` with stack `udp`
2024-10-08 15:30:33,101 INFO  [org.jgroups.JChannel] (ForkJoinPool.commonPool-worker-1) local_addr: 0aaec279-1f79-4aed-b392-88f7791ea802, name: keycloak-0-13459
2024-10-08 15:30:33,106 WARN  [org.jgroups.protocols.UDP] (ForkJoinPool.commonPool-worker-1) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 16.78MB
2024-10-08 15:30:33,106 WARN  [org.jgroups.protocols.UDP] (ForkJoinPool.commonPool-worker-1) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 16.78MB
2024-10-08 15:30:33,112 INFO  [org.jgroups.protocols.FD_SOCK2] (ForkJoinPool.commonPool-worker-1) server listening on *.31400
2024-10-08 15:30:35,117 INFO  [org.jgroups.protocols.pbcast.GMS] (ForkJoinPool.commonPool-worker-1) keycloak-0-13459: no members discovered after 2003 ms: creating cluster as coordinator
2024-10-08 15:30:35,129 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000094: Received new cluster view for channel ISPN: [keycloak-0-13459|0] (1) [keycloak-0-13459]
2024-10-08 15:30:35,191 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000079: Channel `ISPN` local address is `keycloak-0-13459`, physical addresses are `[10.42.12.193:46936]`
2024-10-08 15:30:42,560 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-10-08 15:30:42,575 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-10-08 15:30:42,575 WARN  [io.quarkus.narayana.jta.runtime.NarayanaJtaRecorder] (main) The recovery manager has already been shutdown: java.lang.NullPointerException: Cannot invoke "com.arjuna.ats.arjuna.recovery.RecoveryManager.terminate()" because "this._recoveryManager" is null
	at com.arjuna.ats.jbossatx.jta.RecoveryManagerService.stop(RecoveryManagerService.java:58)
	at io.quarkus.narayana.jta.runtime.NarayanaJtaRecorder.lambda$handleShutdown$2(NarayanaJtaRecorder.java:204)
	at io.quarkus.runtime.StartupContext.runAllAndClear(StartupContext.java:79)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:70)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:146)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:57)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
ERROR: Failed to start server in (production) mode
ERROR: ARJUNA048006: cannot create new instance of com.arjuna.ats.internal.arjuna.objectstore.ShadowNoFileLockStore
ERROR: ARJUNA012225: FileSystemStore::setupStore - cannot access root of object store: /opt/keycloak/bin/../data/transaction-logs/ShadowNoFileLockStore/defaultStore/
```

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

that it does not crash on exception

### Actual behavior

it crashes when QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY is set to true

### How to Reproduce?

no idea, it's doing it on my environments, but haven't found anyone with this problem

this keycloak instance is having a federated ApacheDS AM26 directory, which is known for it's instability. We're currently working on decommissioning it and moving the users into Keycloak

### Anything else?

shall I plan on having QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY enabled or is it not worth the effort?

everything else seems to be working, but I'm afraid it will raise some errors if I keep the recovery disabled

**Comment by mgx0** [comment]
is it related to this solution? https://github.com/keycloak/keycloak/issues/15255#issuecomment-1709254038

**Comment by shawkins** [comment]
Your issue is this: "ARJUNA012225: FileSystemStore::setupStore - cannot access root of object store: /opt/keycloak/bin/../data/transaction-logs/ShadowNoFileLockStore/defaultStore/"

This is the same as #33307

Are you running in such a way as the data directory is not writable?

**Comment by mgx0** [comment]
/opt/keycloak/data/tmp
/tmp
/opt/keycloak/lib/quarkus

Above dirs are writable. I realized after posting this issue (i updated the description with writable paths after that) that it might be due some read-only FS.

could the solution be setting path to a writable directory at envvar QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY ?

does this directory need to be persistent across reboots? I guess yes, right?

**Comment by shawkins** [comment]
> does this directory need to be persistent across reboots? I guess yes, right?

If xa recovery is actually going to be used yes.

Any other solution that disables recovery or makes the directory transient is certainly fine if you have no datasources which are configured for XA.

**Comment by mgx0** [comment]
Well i have to talk to our DB guys if XA is being used or not - i don't really know what it is. We're using postgres DB, the same instance we've been using for years, if it could point to an answer to this. Anyway I believe it's safer to create a writable folder and use it for the directory and leave the Recovery enabled, whether the XA recovery is enabled or not. Is that correct please?On 8 Oct 2024, at 18:05, Steven Hawkins ***@***.***> wrote:﻿

does this directory need to be persistent across reboots? I guess yes, right?

If xa recovery is actually going to be used yes.
Any other solution that disables recovery or makes the directory transient is certainly fine if you have no datasources which are configured for XA.

**Comment by mgx0** [comment]
ok i believe i can find out if XA is enabled or not and act accordingly. thanks a lot @shawkins !
