### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header Issue while invoking Account POST API 

### ISSUE THREAD

**Issue by amolai** [keycloak/keycloak#33762]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

We have a UI screen where we are providing a button to a user to update their details and we make a call to the POST Account  API using the bearer token, but we get the following error.

I am trying invoke the post API to update user profile  and I get the following error 
`Access to fetch at 'https://<keycloak-url>/realms/<realm>/account/' from origin 'https://<application-url>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

The POST URL is like this 

URL : 
https://<keycloak-url>/realms/zsecuritycompliance/account/

METHOD: POST
Payload: 
{"firstName":"1test111","lastName":"1test11","email":"test@test.commv","id":"d5165958-e58f-4d36-96c4-14d502f4255e"}

### Version

25.0.2, 25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Expecting the POST query to work fine

### Actual behavior

Getting 405 method not allowed
 ```
2024-10-10 05:42:08,839 DEBUG [WebApplicationException] (executor-thread-2) Restarting handler chain for exception exception: jakarta.ws.rs.WebApplicationException: HTTP 405 Method Not Allowed
	at org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler.handle(ResourceLocatorHandler.java:71)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-10-10 05:42:08,839 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Error response 405: jakarta.ws.rs.WebApplicationException: HTTP 405 Method Not Allowed
	at org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler.handle(ResourceLocatorHandler.java:71)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
### How to Reproduce?

Invoke the POST account api from any UI application with bearer token

**Comment by rmartinc** [comment]
Hi @amolai!

The console uses cors so you have to configure the `Web origins` option in the client you are using. For example, you can add `*` to allow any origin and test (or add your specific origin for production). The token should also have `account` in the audience to access the account console. For example, doing that with a client `test-oidc` in en my env:

```bash
curl -v http://localhost:8080/realms/master/account \
  -H 'Origin: http://localhost:8080' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json;charset=utf-8' \
  -H 'Authorization: Bearer ...\
  --data '{"firstName":"ricky","lastName":"ricky","email":"ricky@lala.com"}'
* Host localhost:8080 was resolved.
...
> Content-Length: 65
> 
< HTTP/1.1 204 No Content
< Access-Control-Allow-Origin: http://localhost:8080
< Access-Control-Allow-Credentials: true
< Cache-Control: no-cache
< Referrer-Policy: no-referrer
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
```

As you see the cors headers are returned and allowing the origin passed. You can also add trace to some categories to get more information in the server log `--log-level INFO,org.keycloak.services.error:TRACE,org.keycloak.services.cors:TRACE`.
