### ISSUE TITLE
NPE thrown in whoami endpoint

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#33907]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When accessing the admin console with a selected realm that doesn't exist, the whoami endpoint returns a 500 Internal Server Error. There is an NPE thrown here: https://github.com/keycloak/keycloak/blob/10aca5552314d6e5c9226f3c6d0107861c38c693/services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java#L294 because realm is null.

I did not yet test this with the latest release, but by having a look at the code in main the issue could still be there.

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Something meaningful is returned

### Actual behavior

500 is returned due to NPE

### How to Reproduce?

Access admin console with `/admin/master/console/#/nonExistingRealm`.

**Comment by codespearhead** [comment]
I confirm that this issue is reproducible on `Keycloak 26.0.0`.

![issue-33907](https://github.com/user-attachments/assets/77c2fa82-e081-44a6-81fa-f4130c5ed7b5)

```bash
HTTP/1.1 404 Not Found
Content-Type: application/json

http://localhost:8080/admin/realms/nonExistingRealm

{"error":"Realm not found."}
```

```bash
HTTP/1.1 500 Internal Server Error
Content-Type: application/json

http://localhost:8080/admin/master/console/whoami?currentRealm=nonExistingRealm

{"error":"unknown_error","error_description":"For more on this error consult the server log."}
```

```bash
2024-10-14 18:25:37,464 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
2024-10-14 18:26:05,395 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getMasterAdminClient()" because "realm" is null
        at org.keycloak.services.resources.admin.AdminConsole.addMasterRealmAccess(AdminConsole.java:296)
        at org.keycloak.services.resources.admin.AdminConsole.whoAmI(AdminConsole.java:268)
        at org.keycloak.services.resources.admin.AdminConsole$quarkusrestinvoker$whoAmI_eaeea38b34c9e4843e24a94ba86a1ba4c8cf0402.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
