### ISSUE TITLE
Updating `keycloak-js` to version 26.0.0 breaks Typescript compilation.

### ISSUE THREAD

**Issue by kino90** [keycloak/keycloak#34002]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

I'm using `keycloak-js` on this project from time, and I had no problems at all, until updating to `26.0.0`

Importing the lib using 

```typescript
import Keycloak, { KeycloakConfig } from 'keycloak-js';
``` 

throws a Typescript error `TS2307: Cannot find module keycloak-js or its corresponding type declarations.` which makes it impossible to build the application (without using a `@ts-ignore` comment)

---

As an extra: WebStorm also suggests me to import both Keycloak and KeycloakConfig from `keycloak-js/lib/keycloak` but that breaks the build even in a worst way

```
transforming...
189✓ 19 modules transformed.
190x Build failed in 219ms
191error during build:
192[commonjs--resolver] Missing "./lib/keycloak" specifier in "keycloak-js" package
193    at e (file:///code/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:48775:25)
194    at n (file:///code/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:48775:627)
195    at o (file:///code/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:48775:1297)
196    at resolveExportsOrImports (file:///code/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:49465:20)
197    at resolveDeepImport (file:///code/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:49484:31)
198    at tryNodeResolve (file:///code/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:49209:20)
199    at Object.resolveId (file:///code/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:48959:28)
200    at file:///code/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
201    at async PluginDriver.hookFirstAndGetPlugin (file:///code/node_modules/rollup/dist/es/shared/node-entry.js:19674:28)
202    at async resolveId (file:///code/node_modules/rollup/dist/es/shared/node-entry.js:18355:26)
```

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

`import Keycloak, { KeycloakConfig } from 'keycloak-js';` should work as did in the previous versions

### Actual behavior

it breaks the build with error `TS2307: Cannot find module keycloak-js or its corresponding type declarations.`

### How to Reproduce?

Just import Keycloak from `keycloak-js` and try to build it with `npx tsc --noEmit`

**Comment by jonkoops** [comment]
Duplicate of #33778
