### ISSUE TITLE
Unhandled exception when trying to remove a client-scope

### ISSUE THREAD

**Issue by Phil91** [keycloak/keycloak#34130]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I've setup a keycloak instance, when I try to delete a client-scope from client `admin-cli` I'll receive a 500 from the server, in the keycloak logs there is the following error. For all other clients e.g. account the deletion is successful:

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-13) Uncaught server error: java.lang.IllegalStateException: Cannot access delegate without a transaction
 at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientDelegate(RealmCacheSession.java:157)
 at org.keycloak.models.cache.infinispan.ClientAdapter.isUpdated(ClientAdapter.java:69)
 at org.keycloak.models.cache.infinispan.ClientAdapter.getAttribute(ClientAdapter.java:300)
 at org.keycloak.models.utils.SessionExpirationUtils.getClientAttributeTimeout(SessionExpirationUtils.java:206)
 at org.keycloak.models.utils.SessionExpirationUtils.calculateClientSessionMaxLifespanTimestamp(SessionExpirationUtils.java:116)
 at org.keycloak.models.sessions.infinispan.util.SessionTimeouts.getClientSessionLifespanMs(SessionTimeouts.java:94)
 at org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.commitImpl(InfinispanChangelogBasedTransaction.java:165)
 at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
 at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
 at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:407)
 at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:372)
 at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:55)
 at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.closeSession(CloseSessionHandler.java:69)
 at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionHandler.filter(CloseSessionHandler.java:65)
 at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
 at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
 at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
 at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
 at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
 at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
 at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:840)
```

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

My expectation would be that I receive a 200 or 204 from the server after the deletion of the client-scope was successful

### Actual behavior

When executing the `DELETE: admin/realms/master/clients/{clientId}/default-client-scopes/{clientScopeId} the server response is a 500 error. But the role is removed in the frontend.

### How to Reproduce?

Setup keycloak with the following clients:

![image](https://github.com/user-attachments/assets/0a5e63f2-c4fc-4865-a5ad-73b630b9b7b0)

Client `admin-cli` should have the following client scopes:

![image](https://github.com/user-attachments/assets/7582bd1f-445e-47bc-b00d-3affed111f9b)

Login via postman using client_id = `admin-cli`:

![image](https://github.com/user-attachments/assets/c2ac6bd8-c8b5-42d1-b6c4-50e4a91c19be)

Try to delete e.g. the client-scope `acr` from the client (happens for all other client scopes as well):

![image](https://github.com/user-attachments/assets/c523a867-9e7a-42d6-bf4e-742283282b35)

**Comment by Phil91** [comment]
I've tested the bug in version 25.0.6 as well

**Comment by jonkoops** [comment]
The latest release is 26.0.2.

**Comment by Phil91** [comment]
sorry, tested with 26.0.2 as well, error is the following:

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.lang.IllegalStateException: Cannot access delegate without a transaction
 at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientDelegate(RealmCacheSession.java:199)
 at org.keycloak.models.cache.infinispan.ClientAdapter.isUpdated(ClientAdapter.java:69)
 at org.keycloak.models.cache.infinispan.ClientAdapter.getAttribute(ClientAdapter.java:300)
 at org.keycloak.models.utils.SessionExpirationUtils.getClientAttributeTimeout(SessionExpirationUtils.java:206)
 at org.keycloak.models.utils.SessionExpirationUtils.calculateClientSessionMaxLifespanTimestamp(SessionExpirationUtils.java:116)
 at org.keycloak.models.sessions.infinispan.util.SessionTimeouts.getClientSessionLifespanMs(SessionTimeouts.java:106)
 at org.keycloak.models.sessions.infinispan.util.SessionTimeouts.getClientSessionLifespanMs(SessionTimeouts.java:102)
 at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsChangelogBasedTransaction.commitImpl(PersistentSessionsChangelogBasedTransaction.java:203)
 at org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:46)
 at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
 at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:414)
 at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:379)
 at org.keycloak.models.KeycloakBeanProducer_ProducerMethod_getKeycloakSession_XoSEUTXOsE3bpqXlGMAykCiECUM_ClientProxy.close(Unknown Source)
 at org.keycloak.quarkus.runtime.transaction.TransactionalSessionHandler.close(TransactionalSessionHandler.java:60)
 at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.closeSession(CloseSessionFilter.java:67)
 at org.keycloak.quarkus.runtime.integration.jaxrs.CloseSessionFilter.filter(CloseSessionFilter.java:63)
 at org.jboss.resteasy.reactive.server.handlers.ResourceResponseFilterHandler.handle(ResourceResponseFilterHandler.java:25)
 at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
 at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
 at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
 at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
 at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
 at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
 at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Phil91** [comment]
we would really need this fix. @stianst @jonkoops could you reopen the issue?
