### ISSUE TITLE
Setting custom template for email results in error saying AxiosError: Request failed with status code 500 at IncomingMessage.emit (node:events:531:35) at async $$ACTION_2 () digest: "1027113178"

### ISSUE THREAD

**Issue by myselfuser1** [keycloak/keycloak#34177]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

I am callign this api to send user an email verification for keycloak , 
```
await axios.put(
      `${process.env.KEYCLOAK_URL!}/auth/admin/realms/${process.env
        .REALM_NAME!}/users/${userId}/send-verify-email`,
      {},
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        params: params, // Optional: Query parameters for redirect URI
      }
    )
```

now the email which i get is like this

```
 Someone has created a CCash account with this email address. If this was you, click the link below to verify your email address
Link to e-mail address verification
This link will expire within 12 hours.

If you didn't create this account, just ignore this message.
```

I need to customize this email, i have created a custom theme, i already created `email-verification.ftl `in `themes/custom-theme/email/html ` and  also created  email-verification.ftl  in `themes/custom-theme/email/text `, i also created `messages_en.properties`

this is my project structure

<img width="373" alt="Screenshot 2024-10-22 at 11 42 05 AM" src="https://github.com/user-attachments/assets/47930f3f-6d54-4f8b-8a29-53bb567dc823">

Code in my  `email-verification.ftl` html file

```
<#ftl output_format="HTML">
<html>
<head>
    <style type="text/css">
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .email-container {
            max-width: 600px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .logo {
            text-align: center;
            margin-bottom: 30px;
        }
        .button {
            display: inline-block;
            padding: 12px 24px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            margin: 20px 0;
        }
        .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="logo">
            <!-- You can add your logo here -->
            <h2>${kcSanitize(msg("emailVerificationTitle"))}</h2>
        </div>
        
        <p>Hello ${kcSanitize(user.firstName)!},</p>
        
        <p>Thank you for creating a CCash account. To ensure the security of your account, please verify your email address by clicking the button below:</p>
        
        <div style="text-align: center;">
            <a href="${link}" class="button">Verify Email Address</a>
        </div>
        
        <p>This verification link will expire in ${kcSanitize(linkExpirationFormatter(linkExpiration))}.</p>
        
        <p>If you did not create this account, please ignore this email or contact our support team if you have concerns.</p>
        
        <div class="footer">
            <p>This is an automated message, please do not reply to this email.</p>
            <p>© ${.now?string('yyyy')} CCash. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
```

Code in my  `email-verification.ftl` text file

```
<#ftl output_format="plaintext">
${msg("emailVerificationTitle")}

Hello ${user.firstName!},

Thank you for creating a CCash account. To ensure the security of your account, please verify your email address by clicking or copying the link below:

${link}

This verification link will expire in ${linkExpirationFormatter(linkExpiration)}.

If you did not create this account, please ignore this email or contact our support team if you have concerns.

-------------------
This is an automated message, please do not reply to this email.
© ${.now?string('yyyy')} CCash. All rights reserved.
```

My code in message_en.properties

```
emailVerificationSubject=Verify your email for CCash
emailVerificationTitle=Verify Your CCash Account
emailVerificationBody=Someone has created a CCash account with this email address. If this was you, click the link below to verify your email address.
emailVerificationBodyHtml=<p>Someone has created a CCash account with this email address. If this was you, click the link below to verify your email address.</p>
emailVerificationLinkText=Verify Email Address
emailVerificationExpirationNote=This link will expire within {0}.
emailVerificationIgnoreMessage=If you didn't create this account, just ignore this message.
emailVerificationGreeting=Hello {0}
emailVerificationBodyFooter=This is an automated message, please do not reply to this email.
emailVerificationBodyFooterHtml=<p>This is an automated message, please do not reply to this email.</p>
```

Also updated the email theme in keycloak but i keep getting error saying 

```
POST /en/rolespermission 500 in 2249ms
 ⨯ AxiosError: Request failed with status code 500
    at IncomingMessage.emit (node:events:531:35)
    at async $$ACTION_2 (./src/actions/User.ts:356:9)
digest: "1027113178", 
```

if i revert it back to base theme in keycloak side then everything works fine

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

User should received my customized email which i set in my custom theme

### Actual behavior

I get error saying 

```
 ⨯ AxiosError: Request failed with status code 500
    at IncomingMessage.emit (node:events:531:35)
    at async $$ACTION_2 (./src/actions/User.ts:356:9)
digest: "1027113178"
```

as soon as i call the api to send user verification email so the email is never received by the user

### How to Reproduce?

Create a custom theme and use the code which i provided above and then set the email template to custom theme in keycloak side and try hitting the send verification email api

**Comment by myselfuser1** [comment]
i forgot theme.properties
