### ISSUE TITLE
jar built from 26.0.0 and 26.0.1 source fails to 'java.lang.NoClassDefFoundError: oracle/sql/CharacterSet'

### ISSUE THREAD

**Issue by andresebastienzigo** [keycloak/keycloak#34198]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

I've tried to compile the source code and to run the built jar of versions 26.0.0 and 26.0.1

The quarkus-run.jar file built can't be executed and returns the following error :
```
# cmd : java -jar quarkus/server/target/lib/quarkus-run.jar start-dev --verbose
ERROR: Unexpected error when starting the server in (development) mode
Error details:
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:156)
	at org.keycloak.quarkus.runtime.cli.Picocli.start(Picocli.java:987)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:53)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:151)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:139)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:116)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.lang.NoClassDefFoundError: oracle/sql/CharacterSet
	at io.quarkus.jdbc.oracle.runtime.OracleInitRecorder.setupCharSets(OracleInitRecorder.java:21)
	at io.quarkus.deployment.steps.ExtendedCharactersSupport$preinitializeCharacterSets1608602642.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ExtendedCharactersSupport$preinitializeCharacterSets1608602642.deploy(Unknown Source)
	... 28 more
Caused by: java.lang.ClassNotFoundException: oracle.sql.CharacterSet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:114)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:72)
```

During the building of quarkus-run.jar, the two following errors occur :
```
[WARNING] [io.quarkus.deployment.steps.RegisterForReflectionBuildStep] Failed to load Class oracle.jdbc.xa.OracleXADataSource
java.lang.ClassNotFoundException: oracle.jdbc.xa.OracleXADataSource
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:42)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:225)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:210)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:205)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:533)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:481)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:533)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:481)
    at java.lang.Class.forName0 (Native Method)
    at java.lang.Class.forName (Class.java:534)
    at java.lang.Class.forName (Class.java:513)
    at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.registerClass (RegisterForReflectionBuildStep.java:132)
    at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.build (RegisterForReflectionBuildStep.java:85)
    at java.lang.invoke.MethodHandle.invokeWithArguments (MethodHandle.java:733)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:856)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:256)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith (EnhancedQueueExecutor.java:2516)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2495)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1521)
    at java.lang.Thread.run (Thread.java:1583)
    at org.jboss.threads.JBossThread.run (JBossThread.java:483)

[WARNING] [io.quarkus.deployment.steps.RegisterForReflectionBuildStep] Failed to load Class oracle.jdbc.datasource.impl.OracleDataSource
java.lang.ClassNotFoundException: oracle.jdbc.datasource.impl.OracleDataSource
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:42)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:225)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:210)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:205)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:533)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:481)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:533)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:481)
    at java.lang.Class.forName0 (Native Method)
    at java.lang.Class.forName (Class.java:534)
    at java.lang.Class.forName (Class.java:513)
    at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.registerClass (RegisterForReflectionBuildStep.java:132)
    at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.build (RegisterForReflectionBuildStep.java:85)
    at java.lang.invoke.MethodHandle.invokeWithArguments (MethodHandle.java:733)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:856)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:256)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith (EnhancedQueueExecutor.java:2516)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2495)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1521)
    at java.lang.Thread.run (Thread.java:1583)
    at org.jboss.threads.JBossThread.run (JBossThread.java:483)
```

Those two errors have been mentioned in a previous issue (https://github.com/keycloak/keycloak/issues/33627) but the fix doesn't seem to change the result on my side. I've verified manually that the patch is indeed in the two versions that I've tried to compile (26.0.0 and 26.0.1) and it is. I've also tried to modify the current dependence in the file `quarkus/server/pom.xml` :
```xml
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc11</artifactId>
            <scope>provided</scope>
        </dependency>
```
by :
```xml
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <scope>provided</scope>
        </dependency>
```
as mentioned in the post of the issue, without success.

I've tried to build on a just installed Debian, so previous configurations specific to my machine doesn't seem to be the issue here.

I've also tried to link a Postgres database (using command line arguments `--db psotgres --db-url-host 127.0.0.1 --db-username myuser --db-password mypassword`), which doesn't alter the result when executing the jar.

Version of tools used on the machine :
- Debian 12
- java 21.0.5
- mvn 3.8.7 (but I've used the mvnw script as recommended to launch the build)

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should start normally after the build, or at least return error regarding the database engine indicated.

### Actual behavior

The jar execution stop after a second at return an error linked to Oracle SQL, even when linked to a non oracle database.

### How to Reproduce?

Install Debian 12.

Install Java 21.0.5 (`apt install openjdk-21-jdk`)
Install maven 3.8.7 (default when using `apt install maven`)

Git clone Keycloak 26.0.0 or 26.0.1 and follow the instructions under `docs/building.md`

**Comment by andresebastienzigo** [comment]
I've had misunderstood the patch described in the previously raised issue (https://github.com/keycloak/keycloak/issues/33627)

This can be fixed by **adding** (and not replacing anything) the following lines :
```xml
<dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
        </dependency>
```

In the `quarkus/server/pom.xml` file, resulting in the following file :
```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>keycloak-quarkus-parent</artifactId>
        <groupId>org.keycloak</groupId>
        <version>999.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    
    <name>Keycloak Quarkus Server App</name>
    <artifactId>keycloak-quarkus-server-app</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-quarkus-server</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <!-- Necessary for proper execution of IDELauncher -->
        <!-- Can be removed as part of the https://github.com/keycloak/keycloak/issues/22455 enhancement -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-vertx-http-dev-ui-resources</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- this dependency is necessary to start the IDELauncher -->
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc11</artifactId>
            <scope>provided</scope>
	</dependency>
	<dependency>
	    <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
	</dependency>
    </dependencies>

    <properties>
        <!-- define this as a property, so it can still be overwritten on the CLI -->
        <!-- direct the auto-created files to the target folder, so they are cleaned by "mvn clean" -->
        <kc.home.dir>${project.build.directory}/kc</kc.home.dir>
    </properties>

    <build>
        <finalName>keycloak</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemProperties>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemProperties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.build.version}</version>
                <configuration>
                    <finalName>keycloak</finalName>
                    <systemProperties>
                        <kc.home.dir>${kc.home.dir}</kc.home.dir>
                        <java.util.concurrent.ForkJoinPool.common.threadFactory>io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory</java.util.concurrent.ForkJoinPool.common.threadFactory>
                    </systemProperties>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>snyk-quarkus</id>
            <dependencies>
                <dependency>
                    <groupId>org.keycloak</groupId>
                    <artifactId>keycloak-quarkus-server-deployment</artifactId>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
```

This issue can be closed / deleted.

**Comment by mabartos** [comment]
Caused by the https://github.com/quarkusio/quarkus/pull/41998#issuecomment-2587549767.

**Comment by mabartos** [comment]
Will be completely resolved once https://github.com/keycloak/keycloak/issues/36501 is done.
