### ISSUE TITLE
NullPointerException in ConditionalOtpFormAuthenticator.java

### ISSUE THREAD

**Issue by pereng** [keycloak/keycloak#34298]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When using a flow with 
- `[Required] Username Form` 
- `[Required] Password Form` 
- `[Conditional] Subflow`
  -  `[Required] Condition - user configured` 
  - `[Required] Conditional OTP Form`

... you get an NPE when the user has configured OTP:

```
WARN  [org.keycloak.services] (executor-thread-38) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticatorConfigModel.getConfig()" because the return value of "org.keycloak.authentication.AuthenticationFlowContext.getAuthenticatorConfig()" is null
```

The error does not ooccur if using `Username Password Form` instead, but the example above is a simplified version of a more complex flow. 

A partial realm export with an authentication flow where with the problem is appended.

[test-conditional-otp-realm-export.json](https://github.com/user-attachments/files/17503765/test-conditional-otp-realm-export.json)

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

To be able to log in by entering username in first form, then password in the second form, then finally, if configured, OTP in the third form.

### Actual behavior

- Entering username in first form successfully.
- Entering password in second form succefully.
- If OTP has been configured for the account the authentication flow ends with error message `We are sorry... Unexpected error when handling authentication request to identity provider.`

NullPointerException in server Log:

```
2024-10-24 10:23:09,238 WARN  [org.keycloak.services] (executor-thread-40) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticatorConfigModel.getConfig()" because the return value of "org.keycloak.authentication.AuthenticationFlowContext.getAuthenticatorConfig()" is null
	at org.keycloak.authentication.authenticators.browser.ConditionalOtpFormAuthenticator.authenticate(ConditionalOtpFormAuthenticator.java:109)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:465)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:269)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:400)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:269)
	at org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:174)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:152)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1034)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:378)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:349)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:341)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:407)
	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### How to Reproduce?

- Use provided partial realm export. 
- Use authentication flow `OTP` as default browser flow
- Create a user and set a password for the user
- Login to Account Console with the newly created user
- Configure OTP in Account Console
- Sign out and back in.
- Once hte password has been submitted the error occurs

**Comment by LMonert** [comment]
Can confirm this for Version 26.0.2 as well. I tried to create a new flow by duplicating the browser flow and ran into the same problem. 
For my usecase: I tried to add WebAuthn as an OTP alternative if the user has any of the two configured. The flow only works if I remove the OTP step which seems to be causing the issue in my case. WebAuthn only works just fine.
This is a problem because creating a flow including OTP seems to be impossible currently.

**Comment by rmartinc** [comment]
@pereng The reason is the `Conditional OTP Form` authentication needs configuration. I think we can make it work with no configuration at all like the others authenticators. But my feeling here is that you are really trying to use the `OTP Form` and not the conditional one (check the original browser flow to see how it's configured). The conditional one is used when OTP needs to be executed for a specific role or similar. I'll try to send a PR anyway to fix the NPE.
