### ISSUE TITLE
Keycloak with PostgreSQL becomed unresponsive with XAException.XAER_RMERR and An I/O error occurred while sending to the backend

### ISSUE THREAD

**Issue by aemaem** [keycloak/keycloak#34403]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

After some time Keycloak becomes unresponsive. Connections to e.g. the `/token` endpoints time out.

I then see several warnings and errors in the log:
```
2024-10-28 13:29:24,948 WARN  [com.arjuna.ats.jta] (Transaction Reaper Worker 0) ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff6464cae4:8c9b:671f796f:128f, node_name=quarkus, branch_uid=0:ffff6464cae4:8c9b:671f796f:1292, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@48db684e) failed with exception code XAException.XAER_RMERR: javax.transaction.xa.XAException: Error trying to transactionRollback local transaction: This connection has been closed.
...
2024-10-28 13:29:24,948 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-25) JDBC exception executing SQL [select re1_0.ID from KEYCLOAK_ROLE re1_0 where re1_0.CLIENT_ROLE=false and re1_0.NAME=? and re1_0.REALM_ID=?] [n/a]: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
...
2024-10-28 13:29:24,948 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012113: TransactionReaper::doCancellations worker Thread[#48,Transaction Reaper Worker 0,5,main] missed interrupt when cancelling TX 0:ffff6464cae4:8c9b:671f796f:128f -- exiting as zombie (zombie count decremented to 0)
``` 

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should still be responsive without heavy load.

When I open our app at https://my.app the `keycloak-js` client automatically redirects to Keycloak, which then opens the login of the configured identity provider. If already logged in, then it is again automatically redirected to https://my.app to be automatically logged in.

### Actual behavior

When I open our app at https://my.app the `keycloak-js` client automatically redirects to Keycloak, which can be seen by the blue loading indicator. However, if it is stuck, then the loading indicator never goes away. The logs just show the following:

```
2024-10-28 13:29:17,335 DEBUG [io.quarkus.micrometer.runtime.binder.vertx.VertxHttpServerMetrics] (vert.x-eventloop-thread-0) requestRouted null HttpRequestMetric [initialPath=/health/live, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@691bfc1f]
2024-10-28 13:29:17,335 DEBUG [io.quarkus.micrometer.runtime.binder.vertx.VertxHttpServerMetrics] (vert.x-eventloop-thread-0) requestRouted /health/live HttpRequestMetric [initialPath=/health/live, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@691bfc1f]
2024-10-28 13:29:17,335 DEBUG [io.quarkus.micrometer.runtime.binder.vertx.VertxHttpServerMetrics] (vert.x-eventloop-thread-0) responseEnd io.vertx.core.http.impl.Http1xServerResponse@14789934, HttpRequestMetric [initialPath=/health/live, currentRoutePath=/health/live, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@691bfc1f]
2024-10-28 13:29:24,948 DEBUG [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-25) Exception clearing maxRows/queryTimeout [This statement has been closed.]
2024-10-28 13:29:24,948 WARN  [io.agroal.pool] (Transaction Reaper Worker 0) Datasource '<default>': JDBC resources leaked: 0 ResultSet(s) and 1 Statement(s)
2024-10-28 13:29:24,948 WARN  [com.arjuna.ats.jta] (Transaction Reaper Worker 0) ARJUNA016045: attempted rollback of < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff6464cae4:8c9b:671f796f:128f, node_name=quarkus, branch_uid=0:ffff6464cae4:8c9b:671f796f:1292, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@48db684e) failed with exception code XAException.XAER_RMERR: javax.transaction.xa.XAException: Error trying to transactionRollback local transaction: This connection has been closed.
	at io.agroal.narayana.XAExceptionUtils.xaException(XAExceptionUtils.java:20)
	...
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at io.agroal.narayana.LocalXAResource.rollback(LocalXAResource.java:86)
	... 8 more

2024-10-28 13:29:24,948 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-25) JDBC exception executing SQL [select re1_0.ID from KEYCLOAK_ROLE re1_0 where re1_0.CLIENT_ROLE=false and re1_0.NAME=? and re1_0.REALM_ID=?] [n/a]: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
...
2024-10-28 13:29:24,948 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-25) SQL Error: 0, SQLState: 08006
2024-10-28 13:29:24,948 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-25) An I/O error occurred while sending to the backend.
2024-10-28 13:29:24,948 WARN  [io.agroal.pool] (Transaction Reaper Worker 0) Datasource '<default>': This connection has been closed.
2024-10-28 13:29:24,948 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012110: TransactionReaper::check successfuly marked TX 0:ffff6464cae4:8c9b:671f796f:128f as rollback only
2024-10-28 13:29:24,948 WARN  [org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorTrackingImpl] (Transaction Reaper Worker 0) HHH000451: Transaction afterCompletion called by a background thread; delaying afterCompletion processing until the original thread can handle it. [status=4]
2024-10-28 13:29:24,948 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012113: TransactionReaper::doCancellations worker Thread[#48,Transaction Reaper Worker 0,5,main] missed interrupt when cancelling TX 0:ffff6464cae4:8c9b:671f796f:128f -- exiting as zombie (zombie count decremented to 0)
2024-10-28 13:29:24,948 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-25) Initiating JDBC connection release from afterTransaction
2024-10-28 13:29:24,948 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff6464cae4:8c9b:671f796f:129c in state  RUN
2024-10-28 13:29:24,948 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff6464cae4:8c9b:671f796f:12ab in state  TRACE
2024-10-28 13:29:24,948 DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (executor-thread-25) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
2024-10-28 13:29:24,949 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 1) ARJUNA012095: Abort of action id 0:ffff6464cae4:8c9b:671f796f:12ab invoked while multiple threads active within it.
2024-10-28 13:29:24,949 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-25) Initiating JDBC connection release from afterTransaction
2024-10-28 13:29:24,949 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-25) Initiating JDBC connection release from afterTransaction
2024-10-28 13:29:24,949 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff6464cae4:8c9b:671f796f:12b5 in state  TRACE
2024-10-28 13:29:24,949 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff6464cae4:8c9b:671f796f:12b9 in state  TRACE
2024-10-28 13:29:24,949 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffff6464cae4:8c9b:671f796f:12c4 in state  TRACE
2024-10-28 13:29:24,950 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 1) ARJUNA012381: Action id 0:ffff6464cae4:8c9b:671f796f:12ab completed with multiple threads - thread Timer-0 was in progress with java.base/sun.nio.ch.Net.poll(Native Method)
``` 

### How to Reproduce?

I am running the Keyloak container `quay.io/keycloak/keycloak:26.0.2` as an [Azure Container App](https://learn.microsoft.com/en-us/azure/container-apps/overview). The database is a **PostgreSQL** running as [Azure CosmosDB for PostgreSQL](https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/introduction) which in fact uses [Citus](https://github.com/citusdata/citus) extension and [PgBouncer](https://www.pgbouncer.org/) for connection pooling.

Entire logging information can be found here: 
[keycloak-issue.log](https://github.com/user-attachments/files/17547774/keycloak-issue.log)

##### Keycloak setup

**Start command:** `/opt/keycloak/bin/kc.sh start`
**Resources:** `2 CPU cores` and `4 Gi memory`
**Config:**
```shell
KC_LOG_LEVEL=debug
KC_CACHE=local
KC_HEALTH_ENABLED=true
KC_METRICS_ENABLED=true
KC_HTTP_ENABLED=true
KC_PROXY_HEADERS=xforwarded
KC_HOSTNAME=https://my.dns
KC_DB=postgres
KC_DB_URL=jdbc:postgresql://myhost.postgres.cosmos.azure.com:6432/keycloak
KC_DB_USERNAME=citus
KC_DB_PASSWORD=foo
KC_DB_POOL_MIN_SIZE=50
KC_DB_POOL_MAX_SIZE=50
KC_BOOTSTRAP_ADMIN_USERNAME=admin
KC_BOOTSTRAP_ADMIN_PASSWORD=admin

QUARKUS_DATASOURCE_JDBC_VALIDATION_QUERY_SQL=select 1
QUARKUS_DATASOURCE_JDBC_BACKGROUND_VALIDATION_INTERVAL=10
QUARKUS_DATASOURCE_JDBC_FOREGROUND_VALIDATION_INTERVAL=10
``` 

### Anything else?

There are _5 realms_, where each realm has an external OpenID Connect identity provider configured. Each realm has _2 clients_ to our main application for frontend and backend. Backend client is configured with [UMA](https://www.keycloak.org/docs/26.0.2/authorization_services/index.html#_getting_started_overview) where just a hand full of resources, scopes, policies and permission are configured (for now).

Our backend is Python ([FastAPI](https://fastapi.tiangolo.com/)) with the [python-keycloak](https://github.com/marcospereirampj/python-keycloak) library for communication with Keycloak. 

Our frontend is a React app with [keycloak-js](https://www.keycloak.org/securing-apps/javascript-adapter) client which is being exported and served as an [Azure Static Web App](https://learn.microsoft.com/en-us/azure/static-web-apps/overview).

**Comment by shawkins** [comment]
From Keycloak's perspective the sequence is roughly:

- a presumed healthy connection is obtained from the pool and associated with the current transaction
- hibernate begins to use connection, however it fails with "2024-10-28 13:29:24,948 DEBUG [org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl] (executor-thread-25) Exception clearing maxRows/queryTimeout [This statement has been closed.]" - that appears to be because the connection is already closed.
- the transaction manager tries to clean things up, but of course the connection is already closed

You have some connection validation enabled, which helps prevent unhealthy connections from being in the pool, but at first glance it does appear like this connection is unhealthy - keycloak should not be proactively closing the connection, so this should be happening because of something on the remote side. Can you check pgBouncer / pg logs to see why the connection is being closed?

cc @yrodiere

**Comment by aemaem** [comment]
@shawkins Thanks for your response. We are still investigating what caused this issue.

Because of a bug in Azure, not showing any logs of the PostgreSQL instance, I am not able to provide the necessary information.

What we currently did, whas to move the Keycloak instance to dedicated VMs. For now everything works fine. Still I am wondering, why the health endpoint was reponsive but the API not.

If we encouter further issues on that, I will hopefully provider additional logs from the database side.
