### ISSUE TITLE
quarkus-next: StackOverflowError causes build failure

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#34454]
### Description

```
Exception in thread "main" java.lang.StackOverflowError
	at io.quarkus.paths.OpenContainerPathTree.isAbsolutePath(OpenContainerPathTree.java:30)
	at io.quarkus.paths.OpenContainerPathTree.ensureResourcePath(OpenContainerPathTree.java:34)
	at io.quarkus.paths.OpenContainerPathTree.ensureResourcePath(OpenContainerPathTree.java:120)
	at io.quarkus.paths.OpenContainerPathTree.accept(OpenContainerPathTree.java:138)
	at io.quarkus.paths.ArchivePathTree$OpenArchivePathTree.accept(ArchivePathTree.java:322)
	at io.quarkus.paths.PathTree.acceptAll(PathTree.java:169)
	at io.quarkus.paths.SharedArchivePathTree$CallerOpenPathTree.acceptAll(SharedArchivePathTree.java:177)
	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.lambda$getResources$3(PathTreeClassPathElement.java:120)
	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.apply(PathTreeClassPathElement.java:136)
	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.getResources(PathTreeClassPathElement.java:119)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:254)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:278)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.getResources(QuarkusClassLoader.java:212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1203)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:133)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.buildSources(SmallRyeConfig.java:876)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:806)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:86)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:771)
	at io.quarkus.runtime.configuration.QuarkusConfigFactory.getConfigFor(QuarkusConfigFactory.java:27)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:78)
```
Full log: https://github.com/keycloak/keycloak/actions/runs/11564800764/job/32190698080

First time recorded: https://github.com/quarkusio/quarkus/commits/main/?since=2024-10-23&until=2024-10-24&after=8077229fef0c73ccb74bbb15c1a08ac0533719a8+34

Additional info:
Quarkus version 3.16.0.CR1 works without build failures.

**Comment by mabartos** [comment]
SmallRye Config 3.9.x    -  OK
SmallRye Config 3.10.x  -  NOK

When ignoring `org.keycloak.quarkus.runtime.configuration.PropertyMappingInterceptor`, everything works as expected. So it needs to be investigated.
