### ISSUE TITLE
Upgrade from 24.0.5 to higer version failes with ERROR: rel ation "org" already exists

### ISSUE THREAD

**Issue by xundeenergie** [keycloak/keycloak#34499]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Upgrading from 24.0.5 failes with following output:

```
/opt/kc-latest: # sudo -u keycloak bin/kc.sh start --spi-connections-liquibase-default-index-creation-threshold=300000                                                                                             
2024-10-30 13:04:16,256 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager                                                              
2024-10-30 13:04:18,434 INFO  [org.infinispan.CONTAINER] (Thread-5) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'                                          
2024-10-30 13:04:19,350 WARN  [org.jgroups.stack.Configurator] (Thread-5) JGRP000014: ThreadPool.thread_dumps_threshold has been deprecated: ignored                                                               
2024-10-30 13:04:19,375 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000078: Starting JGroups channel `ISPN` with stack `udp`                                                                                     
2024-10-30 13:04:19,377 INFO  [org.jgroups.JChannel] (Thread-5) local_addr: e1edd657-8599-4c8c-a5a7-e9d047f04342, name: ldap-48980                                                                                 
2024-10-30 13:04:19,406 WARN  [org.jgroups.protocols.UDP] (Thread-5) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB                                      
2024-10-30 13:04:19,407 WARN  [org.jgroups.protocols.UDP] (Thread-5) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB                                  
2024-10-30 13:04:19,407 WARN  [org.jgroups.protocols.UDP] (Thread-5) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB                                      
2024-10-30 13:04:19,407 WARN  [org.jgroups.protocols.UDP] (Thread-5) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB                                  
2024-10-30 13:04:19,458 INFO  [org.jgroups.protocols.FD_SOCK2] (Thread-5) server listening on *.18039                                                                                                              
2024-10-30 13:04:21,491 INFO  [org.jgroups.protocols.pbcast.GMS] (Thread-5) ldap-48980: no members discovered after 2012 ms: creating cluster as coordinator                                                       
2024-10-30 13:04:21,513 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000094: Received new cluster view for channel ISPN: [ldap-48980|0] (1) [ldap-48980]                                                          
2024-10-30 13:04:21,674 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000079: Channel `ISPN` local address is `ldap-48980`, physical addresses are `[10.0.0.2:33575]`                                              
2024-10-30 13:04:22,607 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: ldap-48980, Site name: null                                                       
2024-10-30 13:04:25,954 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Updating database. Using changelog META-INF/jpa-changelog-master.xml                      
2024-10-30 13:04:28,138 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-25.0.0.xml::25.0.0-org::keycloak encountered an exception.: liquibase.exception.DatabaseException: ERROR: rel
ation "org" already exists [Failed SQL: (0) CREATE TABLE public.ORG (ID VARCHAR(255) NOT NULL, ENABLED BOOLEAN NOT NULL, REALM_ID VARCHAR(255) NOT NULL, GROUP_ID VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL
, DESCRIPTION VARCHAR(4000), CONSTRAINT "ORG_pkey" PRIMARY KEY (ID))]                                                                                                                                              
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:476)                                                                                                       
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83)                                                                                                                                       
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:185)                                                                                                                                      
        at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)                                                                                                                                  
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1189)                                                                                                               
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:775)                                                                                                                                               
        at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)                                                                                                                 
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)                                                                                                                                  
        at liquibase.changelog.ChangeLogIterator.lambda$run$0(ChangeLogIterator.java:131)                                                                                                                          
        at liquibase.Scope.lambda$child$0(Scope.java:191)                                                                                                                                                          
        at liquibase.Scope.child(Scope.java:200)                                                                                                                                                                   
        at liquibase.Scope.child(Scope.java:190)                                                                                                                                                                   
        at liquibase.Scope.child(Scope.java:169)                                                                                                                                                                   
        at liquibase.changelog.ChangeLogIterator.lambda$run$1(ChangeLogIterator.java:120)                                                                                                                          
        at liquibase.Scope.lambda$child$0(Scope.java:191)                                                                                                                                                          
        at liquibase.Scope.child(Scope.java:200)                                                                                                                                                                   
        at liquibase.Scope.child(Scope.java:190)                                                                                                                                                                   
        at liquibase.Scope.child(Scope.java:169)                                                                                                                                                                   
        at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:111)                                                                                                      [215/7293]
        at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
        at liquibase.command.CommandScope.execute(CommandScope.java:220)
        at liquibase.Liquibase.lambda$update$0(Liquibase.java:216)
        at liquibase.Scope.lambda$child$0(Scope.java:191)
        at liquibase.Scope.child(Scope.java:200)
        at liquibase.Scope.child(Scope.java:190)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Liquibase.runInScope(Liquibase.java:1290)
        at liquibase.Liquibase.update(Liquibase.java:205)
        at liquibase.Liquibase.update(Liquibase.java:188)
        at liquibase.Liquibase.update(Liquibase.java:175)
        at org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider.updateChangeSet(QuarkusJpaUpdaterProvider.java:191)
        at org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:106)
        at org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:84)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.update(QuarkusJpaConnectionProviderFactory.java:281)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.createOrUpdateSchema(QuarkusJpaConnectionProviderFactory.java:263)
        at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:124)
        at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:105)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.createSessionFactory(QuarkusKeycloakApplication.java:67)
        at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:90)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.onStartupEvent(QuarkusKeycloakApplication.java:52)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication_Observer_onStartupEvent_GNZ8m5QenZ9h9VNelo7awjUZFDE.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:146)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:57)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)                                                                                                                           
Caused by: org.postgresql.util.PSQLException: ERROR: relation "org" already exists                                                                                                                                 
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)                                                                                                              
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)                                                                                                                    
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:356)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:341)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:317)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:312)
        at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:220)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
        ... 78 more


UPDATE SUMMARY
Run:                          6
Previously run:             124
Filtered out:                 0
-------------------------------
Total change sets:          144

2024-10-30 13:04:28,186 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 3 ResultSet(s) and 0 Statement(s)
2024-10-30 13:04:28,188 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 14 ResultSet(s) and 0 Statement(s)
2024-10-30 13:04:28,249 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2024-10-30 13:04:28,297 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-10-30 13:04:28,374 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-10-30 13:04:28,375 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2024-10-30 13:04:28,375 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for
 changeset META-INF/jpa-changelog-25.0.0.xml::25.0.0-org::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "org" already exists [Failed SQL: (0) CREATE TABLE public.ORG (ID VARCHAR(255) NOT NULL, ENABLED BOOLEAN NOT NULL, REALM_ID VARCHAR(255) NOT NU
LL, GROUP_ID VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(4000), CONSTRAINT "ORG_pkey" PRIMARY KEY (ID))]
2024-10-30 13:04:28,375 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-25.0.0
.xml::25.0.0-org::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "org" already exists [Failed SQL: (0) CREATE TABLE public.ORG (ID VARCHAR(255) NOT NULL, ENABLED BOOLEAN NOT NULL, REALM_ID VARCHAR(255) NOT NU
LL, GROUP_ID VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(4000), CONSTRAINT "ORG_pkey" PRIMARY KEY (ID))]
2024-10-30 13:04:28,377 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-25.0.0.xml::25.0.0-org::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "org" already exists [Failed SQL: (0) CREATE TABLE public.ORG (ID VARCHAR(255) NOT NULL, ENABLED BOOLEAN NOT NULL, REALM_ID VARCHAR(255) NOT NU
LL, GROUP_ID VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(4000), CONSTRAINT "ORG_pkey" PRIMARY KEY (ID))]
2024-10-30 13:04:28,378 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: relation "org" already exists [Failed SQL: (0) CREATE TABLE public.ORG (ID VARCHAR(255) NOT NULL, E
NABLED BOOLEAN NOT NULL, REALM_ID VARCHAR(255) NOT NULL, GROUP_ID VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(4000), CONSTRAINT "ORG_pkey" PRIMARY KEY (ID))]
2024-10-30 13:04:28,378 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: relation "org" already exists
2024-10-30 13:04:28,379 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the detail
s about the usage of the particular command.

```

What I've done?

I had a running keycloak server and just downloaded the zip for 26.0.4.
Copied over keycloak.conf and my 3 provider-files to the new directory.
Run after that the build-command and started the server from commandline as you see in the first line. That's all.

I tried it also with keycloak 25.something and it failes with the same failure.
Using Postgresql 15

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Just upgrade to the latest keycloak-server

### Actual behavior

Upgrade from 24.0.5 fails to every newer version with the error mentioned above

### How to Reproduce?

Download the new keycloak-zip, unpack it, copy over keycloak.conf and providers and restart the server

### Anything else?

My keycloak-server is a single-node instance with 3 custom providers and no further customization.
Just to keep it simple.

I also tried the upgrade without my custom providers. It failes also with the same error.

**Comment by xundeenergie** [comment]
now i dropped the relation "revoked_token", because it was already empty and started the server again.

It could start. But when i open the admin-page in browser i get an CSP-error

![grafik](https://github.com/user-attachments/assets/82f788c5-a32d-4ab3-a783-348ed9c38093)
`Content-Security-Policy: Die Einstellungen der Seite haben das Laden einer Ressource (frame-src) auf http://kc.schuerz.at/realms/master/protocol/openid-connect/3p-cookies/step1.html blockiert, da sie gegen folgende Direktive verstößt: "frame-src 'self'"`

But the page opened before with 25.0.0. without any problems.

**Comment by xundeenergie** [comment]
Now i had to delete the relation "revoked_token" (was empty already), that keycloak could start.

Why do this relations exist and the migration after upgrading the server is complaining about???

**Comment by sguilhen** [comment]
I couldn't reproduce the issue locally, after running the migration tests a hundred times with postgres. Somehow in your env the tables were previously created and Liquibase's databasechangelog wasn't updated - otherwise Liquibase would detect the changes were already applied and would skip them.

I'll leave this issue a low priority to see if more people hit the same problem.

**Comment by aabulimiti** [comment]
I experienced the exact same issue when upgrading to latest Keycloak. I had to drop `org`, `org_domain` and `revoked_token` tables before KC successfully starts up.

**Comment by fouringiz** [comment]
i found a solution here

https://github.com/keycloak/keycloak/issues/23268#issuecomment-1722244919
