### ISSUE TITLE
Flaky test: org.keycloak.testsuite.saml.ArtifactBindingWithResolutionServiceTest#testReceiveArtifactLoginFullWithPost

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#34542]
## org.keycloak.testsuite.saml.ArtifactBindingWithResolutionServiceTest#testReceiveArtifactLoginFullWithPost
[Keycloak CI - Base IT (6)](https://github.com/keycloak/keycloak/actions/runs/11608099131/job/32322839665) / [Pull Request #34507](https://github.com/keycloak/keycloak/pull/34507)

```
jakarta.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:250)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:41)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:136)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)
...
```

**Comment by douglaspalmer** [comment]
Has not reoccured in 3 weeks.

**Comment by stianst** [comment]
https://github.com/stianst/keycloak/actions/runs/12647502858/job/35240235237

**Comment by rmartinc** [comment]
I cannot reproduce this, I have executed the full class 450 times without any issues [here](https://github.com/rmartinc/keycloak/actions/runs/12667821626). Besides the error in the two failed executions are the same but in different lines. The error is that the transaction is marked as not active [here](https://github.com/keycloak/keycloak/blob/26.0.7/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java#L119), one failure is just doing an update to prepare the client and the other is performing  the test login. The transaction is marked as active when it is [enlisted](https://github.com/keycloak/keycloak/blob/26.0.7/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java#L108) in the constructor, so the only option is that some other thing executed commit or rollback later. Don't know why this error happens in this test and not in others but it seems not related to this specific test (IMHO this should happen more). I think I will just close this because without more info and not able to reproduce it, I have no idea what is happening here.

**Comment by rmartinc** [comment]
I'm closing this as I cannot reproduce. If something else is rolling back the transaction we have to detect that other thread. Other option is adding `volatile` to the [transactionActive property](https://github.com/keycloak/keycloak/blob/26.0.7/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java#L92) just in case other thread is changing it (although at least in one of the failures I don't expect anything modifying this). Please re-open if you see this again.
