### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by DavidGerald-Milligan** [keycloak/keycloak#34576]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When upgrading from 25.0.6 to 26.0.5 using a .jks keystore I get an error about a missing key file when keycloak starts.

### Version

26.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

I expected keycloak to start without error

### Actual behavior

As before the upgrade I provide the following options in keycloak.con

https-key-store-file
https-key-store-password
https-key-store-type
https-certificate-file

Stack trace from the log

ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.IllegalArgumentException: You must specify the key files when specifying the certificate files        
at io.quarkus.vertx.http.runtime.options.TlsUtils.computeKeyStoreOptions(TlsUtils.java:34)
at io.quarkus.vertx.http.runtime.options.HttpServerOptionsUtils.applySslConfigToHttpServerOptions(HttpServerOptionsUtils.java:158)
at io.quarkus.vertx.http.runtime.options.HttpServerOptionsUtils.createSslOptions(HttpServerOptionsUtils.java:95)
at io.quarkus.vertx.http.runtime.VertxHttpRecorder.initializeMainHttpServer(VertxHttpRecorder.java:755)
at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:856)
at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:355)
at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1753087980.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1753087980.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:146)
at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:57)
at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
at picocli.CommandLine.execute(CommandLine.java:2174)
at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)
at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)
at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)

### How to Reproduce?

I generate keystore and cert as follows

$JRE_HOME/bin/keytool -genkey -noprompt -alias test-cert -dname "CN=myname, OU=myorganisational.unit, O=myorganisation, L=mycity, S=myprovince, C=GB" -storepass changeit -keypass changeit -keyalg RSA -keystore /test-keystore/KeyStore.jks -keysize 2048
$JRE_HOME/bin/keytool -certreq -alias test-cert -storepass changeit -keypass changeit -keystore /test-keystore/KeyStore.jks -file /test-keystore/test-cert.csr

And set cfg as follows
https-key-store-file=/test-keystore/KeyStore.jk
https-key-store-password=changeit
https-key-store-type=JKS
https-certificate-file=/test-keystore/test-cert.csr

**Comment by shawkins** [comment]
This is a validation that was added by quarkus in https://github.com/quarkusio/quarkus/commit/0fddc5041e74a86635666f97ad7a861809275343

The expectation seems to be that if you specify the cert in pem format, then you'll specify the key that way as well, and vice versa.

The comment on that commit implies that what you were doing shouldn't have worked.

If it did, then we'll at least need to see about adding an upgrade note.

cc @Pepo48 @cescoffier

**Comment by DavidGerald-Milligan** [comment]
@shawkins 
keycloak 25.0.6
<quarkus.version>3.8.5</quarkus.version>

keycloak 26.0.0
<quarkus.version>3.15.1</quarkus.version>

The validation you highlight was only added in 3.9.0.CR1

**Comment by shawkins** [comment]
After an offline discussion with @cescoffier we should probably move forward with an upgrade note that this is no longer possible - as there is no desire in quarkus for it to be allowed again. It is considered to be something that worked accidentally which was not spelled out as supported by keycloak nor quarkus.

@vmuzikar @stianst are you good with an upgrade note / doc change here?
