### ISSUE TITLE
400 response on refresh token request with valid token

### ISSUE THREAD

**Issue by franck102** [keycloak/keycloak#34587]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

A request to the TokenEndpoint.refreshTokenGrant endpoint fails with a 400 status with what should be a valid refresh token.

### Version

23.0.7 on JVM (powered by Quarkus 3.2.10.Final)

### Regression

- [ ] The issue is a regression

### Expected behavior

The call should succeed and return a new access token.

### Actual behavior

Keycloak returns a 400 response and logs the errors below.

The token was obtained 8h ago, and the session has been idle since then.
I don't understand the log entry about CORS headers, the request was made from an allowed origin.

Keycloak shows an active user session for the user under 

```
authority: macbook:8448
:method: POST
:path: /auth/realms/totem/protocol/openid-connect/token
:scheme: https
origin: https://macbook:8080
referer: https://macbook:8080/
sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
```

  "revokeRefreshToken": false,
  "refreshTokenMaxReuse": 0,
  "accessTokenLifespan": 600,
  "accessTokenLifespanForImplicitFlow": 900,
  "ssoSessionIdleTimeout": 172800,
  "ssoSessionMaxLifespan": 604800,
  "ssoSessionIdleTimeoutRememberMe": 0,
  "ssoSessionMaxLifespanRememberMe": 0,

```
2024-11-02 17:02:59,251 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (executor-thread-1) AUTHENTICATE CLIENT
 2024-11-02 17:02:59,252 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-1) client authenticator: client-secret
 2024-11-02 17:02:59,252 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-1) client authenticator SUCCESS: client-secret
 2024-11-02 17:02:59,253 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (executor-thread-1) Client easypass-public authenticated by client-secret
 2024-11-02 17:02:59,261 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) new JtaTransactionWrapper
 2024-11-02 17:02:59,262 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) was existing? true
 2024-11-02 17:02:59,262 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper  commit
 2024-11-02 17:02:59,263 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper end
 2024-11-02 17:02:59,263 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper resuming suspended

 2024-11-02 17:02:59,264 WARN  [org.keycloak.events] (executor-thread-1)
   type="REFRESH_TOKEN_ERROR",
   realmId="e383ce81-bb7c-4fed-90b1-6b6ed8b0d21a",
   clientId="easypass-public",
   userId="null",
   ipAddress="10.0.0.2",
   error="invalid_token",
   grant_type="refresh_token",
   client_auth_method="client-secret"

 2024-11-02 17:02:59,266 DEBUG [org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext] (executor-thread-1) Restarting handler chain for exception exception: org.keycloak.services.CorsErrorResponseException: HTTP 500 Internal Server Error
 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.refreshTokenGrant(TokenEndpoint.java:590)
 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:209)
 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.base/java.lang.Thread.run(Thread.java:840)

 2024-11-02 17:02:59,270 DEBUG [org.keycloak.services.resources.Cors] (executor-thread-1) Added CORS headers to response
 2024-11-02 17:02:59,270 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper  commit
 2024-11-02 17:02:59,271 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-1) JtaTransactionWrapper end
```

### How to Reproduce?

- Setup the realm configuration with long session idle expiration times, revoke refresh token disabled
- Use PKCE to obtain an access & a refresh token
- Wait 6 hours with no requests to Keycloak
- Call the TokenEndpoint.refreshTokenGrant

### Anything else?

Some pointers as to whether this is CORS - related, or OIDC related would be very helpful; the logs don't provide much insight.

**Comment by franck102** [comment]
Here is a client-side log if that helps. I am using oidc-client-ts version 3.0.1.

The refresh will usually succeed if the window is left open; but fails with a 400 especially if the window has been hidden (e.g. minimized).

[frontend.log](https://github.com/user-attachments/files/17610092/frontend.log)

**Comment by franck102** [comment]
When I get the initial access token Keycloak sets the KEYCLOAK_IDENTITY and KEYCLOAK_SESSION on the macbook:8081 origin.
When I make the refresh request for macbook:8448 the browser doesn't include those cookies since the origin doesn't match... is that the problem?

**Comment by himanshi1099** [comment]
Can I raise PR for same?

**Comment by distante** [comment]
This seams to still be an issue on 26.0.7

**Comment by mposolda** [comment]
Not sure if this is valid issue. It would be useful if exact steps to reproduce are added (including what is exactly configured in the realm etc).

Anyway, it is low priority (in case it is valid issue). It is recommended to rather configure Idle timeout to be some shorter value (EG. 30 minutes) and then make sure that refresh token is refreshed at least once per 30 minutes instead of having so long timeouts.
