### ISSUE TITLE
[Javascript CI] - Admin UI E2E - Client Scopes test

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#34649]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
  1) Client Scopes test
       Accessibility tests for client scopes
         Check a11y violations on client scope details:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `.pf-v5-c-tabs `, but never found it.
      at _TabPage_getTab (webpack://@keycloak/keycloak-admin-ui/./cypress/support/pages/admin-ui/components/TabPage.ts:36:0)
      at clickTab (webpack://@keycloak/keycloak-admin-ui/./cypress/support/pages/admin-ui/components/TabPage.ts:16:0)
      at goToMappersTab (webpack://@keycloak/keycloak-admin-ui/./cypress/support/pages/admin-ui/manage/client_scopes/client_scope_details/ClientScopeDetailsPage.ts:29:0)
      at  (webpack://@keycloak/keycloak-admin-ui/./cypress/e2e/client_scopes_test.spec.ts:380:0)
```

https://github.com/keycloak/keycloak/actions/runs/11675036541/job/32509019198

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by miquelsi** [comment]
Duplicate of #34391
