### ISSUE TITLE
Accessing keycloak user group throws Duplicate key value violates unique constraint "sibling_names" exception

### ISSUE THREAD

**Issue by Shuvankar-klarna** [keycloak/keycloak#34650]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

For user federation we have configured LDAP and our allows periodic sync from the LDAP server to keycloak. But we have noticed that when there is concurrent request to read keycloak groups, It throws error. It looks like whenever we try to read keycloak groups it also tries to sync and when there are multiple call it throws exception.

```
ERROR: duplicate key value violates unique constraint "sibling_names"
  Detail: Key (realm_id, parent_group, name)=(<realmId>,  , <groupname>) already exists.

```

### Version

23.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Any concurrent operation to get keycloak user group should return user groups

### Actual behavior

It throws error
 `ERROR: duplicate key value violates unique constraint \"sibling_names\"\n  Detail: Key (realm_id, parent_group, name)=(<realm_id>,  ,<groupname>) already exists.`

`org.keycloak.models.ModelException: org.hibernate.exception.JDBCConnectionException: could not execute statement [An I/O error occurred while sending to the backend.] [insert into KEYCLOAK_GROUP (NAME,PARENT_GROUP,REALM_ID,ID) values (?,?,?,?)]\n\tat org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)\n\tat org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:64)\n\tat jdk.proxy2/jdk.proxy2.$Proxy75.flush(Unknown Source)\n\tat org.keycloak.models.jpa.JpaRealmProvider.createGroup(JpaRealmProvider.java:731)\n\tat org.keycloak.storage.GroupStorageManager.createGroup(GroupStorageManager.java:123)\n\tat org.keycloak.models.cache.infinispan.RealmCacheSession.createGroup(RealmCacheSession.java:1095)\n\tat org.keycloak.models.cache.infinispan.RealmAdapter.createGroup(RealmAdapter.java:1416)\n\tat org.keycloak.models.RealmModel.createGroup(RealmModel.java:628)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.createKcGroup(GroupLDAPStorageMapper.java:805)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.updateKeycloakGroupTreeEntry(GroupLDAPStorageMapper.java:320)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.updateKeycloakGroupTree(GroupLDAPStorageMapper.java:299)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.syncDataFromFederationProviderToKeycloak(GroupLDAPStorageMapper.java:184)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.findKcGroupOrSyncFromLDAP(GroupLDAPStorageMapper.java:388)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper$LDAPGroupMappingsUserDelegate.lambda$getLDAPGroupMappingsConverted$0(GroupLDAPStorageMapper.java:770)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)\n\tat java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)\n\tat java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)\n\tat java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper$LDAPGroupMappingsUserDelegate.getLDAPGroupMappingsConverted(GroupLDAPStorageMapper.java:772)\n\tat org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper$LDAPGroupMappingsUserDelegate.getGroupsStream(GroupLDAPStorageMapper.java:703)\n\tat org.keycloak.models.cache.infinispan.entities.CachedUser.lambda$new$3(CachedUser.java:74)\n\tat org.keycloak.models.cache.infinispan.DefaultLazyLoader.get(DefaultLazyLoader.java:43)\n\tat org.keycloak.models.cache.infinispan.entities.CachedUser.getGroups(CachedUser.java:130)\n\tat org.keycloak.models.cache.infinispan.UserAdapter.getGroupsStream(UserAdapter.java:395)\n\tat org.keycloak.models.utils.RoleUtils.getDeepUserRoleMappings(RoleUtils.java:193)\n\tat org.keycloak.protocol.oidc.TokenManager.getAccess(TokenManager.java:614)\n\tat org.keycloak.services.util.DefaultClientSessionContext.loadRoles(DefaultClientSessionContext.java:274)\n\tat org.keycloak.services.util.DefaultClientSessionContext.getRolesStream(DefaultClientSessionContext.java:142)\n\tat org.keycloak.utils.RoleResolveUtil.getAndCacheResolvedRoles(RoleResolveUtil.java:105)\n\tat org.keycloak.utils.RoleResolveUtil.getAllResolvedClientRoles(RoleResolveUtil.java:95)\n\tat org.keycloak.protocol.oidc.mappers.UserClientRoleMappingMapper.setClaim(UserClientRoleMappingMapper.java:120)\n\tat org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.transformUserInfoToken(AbstractOIDCProtocolMapper.java:79)\n\tat org.keycloak.protocol.oidc.TokenManager$3.applyMapper(TokenManager.java:791)\n\tat org.keycloak.protocol.oidc.TokenManager$3.applyMapper(TokenManager.java:788)\n\tat org.keycloak.protocol.oidc.TokenManager$TokenCollector.lambda$accumulator$3(TokenManager.java:928)\n\tat java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)\n\tat java.base/java.util.ArrayList.forEach(Unknown Source)\n\tat java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)\n\tat java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)\n\tat java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)\n\tat java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)\n\tat java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)\n\tat java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)\n\tat org.keycloak.protocol.oidc.TokenManager.transformUserInfoAccessToken(TokenManager.java:788)\n\tat org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.issueUserInfo(UserInfoEndpoint.java:271)\n\tat org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.issueUserInfoGet(UserInfoEndpoint.java:126)\n\tat org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint$quarkusrestinvoker$issueUserInfoGet_a1820fb001f701bf80f4a3047e1da7b1fcae7669.invoke(Unknown Source)\n\tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.hibernate.exception.JDBCConnectionException: could not execute statement [An I/O error occurred while sending to the backend.] [insert into KEYCLOAK_GROUP (NAME,PARENT_GROUP,REALM_ID,ID) values (?,?,?,?)]\n\tat org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:98)\n\tat org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)\n\tat org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:278)\n\tat org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.performNonBatchedMutation(AbstractMutationExecutor.java:107)\n\tat org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:40)\n\tat org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:52)\n\tat org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:171)\n\tat org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:112)\n\tat org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2790)\n\tat org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:102)\n\tat org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:635)\n\tat org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:502)\n\tat org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:364)\n\tat org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)\n\tat org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)\n\tat org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1412)\n\tat org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1398)\n\tat jdk.internal.reflect.GeneratedMethodAccessor472.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)\n\t... 61 more\nCaused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:395)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)\n\tat jdk.internal.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)\n\tat jdk.proxy2/jdk.proxy2.$Proxy82.executeUpdate(Unknown Source)\n\tat io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)\n\tat org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:275)\n\t... 79 more\nCaused by: java.net.SocketTimeoutException: Read timed out\n\tat java.base/sun.nio.ch.NioSocketImpl.timedRead(Unknown Source)\n\tat java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)\n\tat java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)\n\tat java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)\n\tat java.base/java.net.Socket$SocketInputStream.read(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)\n\tat java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)\n\tat org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)\n\tat org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)\n\tat org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)\n\tat org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)\n\tat org.postgresql.core.PGStream.receiveChar(PGStream.java:465)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)\n\t... 90 more\n"`

### How to Reproduce?

Setup LDAP user federation with below settings and try to access keycloak group (multiple request concurrently)via api like 
evaluate-scopes/generate-example-id-token?userId=<<>>

Following are the LDAP settings
```
LDAP Edit mode: READ_ONLY
Synchronization settings:
Import users: ON
Periodic full sync: ON
BATCH size: 1000
Periodic changed user sync: ON
Changed user sync period: 0
```

**Comment by pedroigor** [comment]
I did not manage to reproduce when trying to follow a similar invocation but issuing a token for a specific user that will force import groups from LDAP.

Can you also tell us if you see this when running in a cluster?

**Comment by lrozenblyum** [comment]
We've faced a similar issue with an exception during loading data from KC users when synchronization with LDAP was ongoing
```
2025-03-25 03:08:51,596 DEBUG [org.keycloak.storage.ldap.LDAPStorageProvider] (executor-thread-83) Imported new user from LDAP to Keycloak DB. Username: [ldap_at_sma_03], Email: [null], LDAP_ID: [8e3a3b28-a25c-103e-9132-9d1272992bec], LDAP Entry DN: [uid=ldap_at_sma_03,ou=at_users,dc=secure,dc=com]               2025-03-25 03:08:51,599 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-86) Error response 400: com.fasterxml.jackson.databind.JsonMappingException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_ru8tt6t700s9v50bu18ws5ha6"                      Detail: Key (realm_id, username)=(57fe0335-2027-4c3a-8889-85487c84a798, ldap_at_sma_01) already exists.                                                            at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._wrapAsIOE(DefaultSerializerProvider.java:508)                                               at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:481)                                               at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:399)                                           at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1568)                                                                    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1061)                                                                            at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:332)                                          at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:74)                        at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251)                                at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:73)                                 at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:224)                        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:207)                            at org.keycloak.quarkus.runtime.integration.jaxrs.TransactionalResponseInterceptor.aroundWriteTo(TransactionalResponseInterceptor.java:42)                   at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:231)                        at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:161)                         at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:68)                     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:87)                           at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:68)                              at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:166)                                                   at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:365)                                     at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:243)                                                                at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:100)                                                            at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:73)                                                             at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:518)                                                               at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:458)                                                                      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)                                                             at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)  
```

I guess there is some hard-to-reproduce race condition that synchronization of users/groups may be invoked both automatically by periodic sync and manually due to API call to read data
