### ISSUE TITLE
[Keycloak JavaScript CI] - Admin UI E2E (3, chrome) - realm_settings_general_tab_test

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#34751]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
  1) Realm settings general tab tests
       Test all general tab switches:
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `load-ee67659d-0072-4759-836c-c1db77813546`. No request ever occurred.

https://on.cypress.io/wait
      at cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:75898:18)
      at Object.errByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:75952:10)
      at checkForXhr (http://localhost:8080/__cypress/runner/cypress_runner.js:135185:84)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:135211:28)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://localhost:8080/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://localhost:8080/__cypress/runner/cypress_runner.js:143587:68)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:143528:14)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://localhost:8080/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (webpack://@keycloak/keycloak-admin-ui/./cypress/support/pages/admin-ui/Masthead.ts:87:0)
```

https://github.com/keycloak/keycloak/actions/runs/11702668022/job/32592178063

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by stianst** [comment]
Causing issues with release readiness here: https://github.com/keycloak/keycloak-private/actions/runs/11816495566

**Comment by ssilvert** [comment]
This was backported to 26.0, but it looks like the comment linking it was incorrect.  I'm not exactly sure which release(s) it was included in.
