### ISSUE TITLE
calling openid-connect/auth with previous version valid cookies generate internal server error

### ISSUE THREAD

**Issue by randreoni** [keycloak/keycloak#34750]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

after upgrading keycloak to version 25 from a previous version (upgraded from 11 to 16 then 25), the previously valid cookies sent by browser cause the following exception:

```
2024-11-07 14:07:01,521 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-33) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.UserSessionModel.setLastSessionRefresh(int)" because the return value of "org.keycloak.services.managers.AuthenticationManager$AuthResult.getSession()" is null
        at org.keycloak.services.managers.AuthenticationManager.authenticateIdentityCookie(AuthenticationManager.java:867)
        at org.keycloak.services.managers.UserSessionCrossDCManager.getUserSessionIfExistsRemotely(UserSessionCrossDCManager.java:74)
        at org.keycloak.protocol.AuthorizationEndpointBase.createAuthenticationSession(AuthorizationEndpointBase.java:190)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:191)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:113)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint$quarkusrestinvoker$buildGet_4b690b27439f19dd29733dc5fd4004f24de0adb6.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

keycloak should reject those cookies and inform the browser to initiate a new login process

### Actual behavior

keycloak generate an internal server error

### How to Reproduce?

- setup a keycloak 11
- authenticate to an application using a public oidc client with a browser
- upgrade the keycloak instance to version 25 (realistically passing through version 16 because some db migrations seems directly incompatibles between version 11 and 25)
- reusing the same cookies from the previous keycloak version, try to authenticate to the application
- the authentication process fail because of this server error, so to create a new valid authentication session the user has to delete all the old cookies manually

**Comment by randreoni** [comment]
same behaviour with the last keycloak version 26.0.5, updated the affected version
