### ISSUE TITLE
Cannot start the server when passing the DB password in an env variable

### ISSUE THREAD

**Issue by jean-christophe-manciot** [keycloak/keycloak#34757]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

If I start the server with the database password in an environment variable, it cannot connect to the SQL database.
If I build the server with the database password set in the ```conf/keycloak.conf```, and start the optimized server, then it can connect to the same database with the same password.

This issue defeats the security purpose of setting the password in an env variable vs a clear text file.

### Version

26.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The server should start correctly.

### Actual behavior

```
2024-11-07 16:23:44,455 DEBUG [io.quarkus.agroal.runtime.DataSources] (main) Started datasource <default> connected to jdbc:mysql://<url>:<port>/<db_name>
...
2024-11-07 16:23:44,945 DEBUG [jdk.event.security] (agroal-11)  TLSHandshake: <url>:<port>, TLSv1.3, TLS_AES_256_GCM_SHA384, 2184588656
...repeated several times
...
2024-11-07 16:23:45,222 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (JPA Startup Thread) unable to obtain isolated JDBC connection [n/a]: java.sql.SQLException: Access denied for user '<user>'@'<url>' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
````

### How to Reproduce?

1. download 26.0.4 and extract
2. install ojdbc17-23.6.0.24.10.jar into providers
3. install orai18n-23.6.0.24.10.jar into providers
4. set keycloak.conf (without the db password) and quarkus.properties into conf
5. bin/kc.sh build --features="client-secret-rotation,passkeys,recovery-codes"
6. KEYCLOAK_ADMIN=admin KEYCLOAK_ADMIN_PASSWORD='admin_password' KC_DB_PASSWORD='db_password'
7. bin/kc.sh --verbose start --optimized &

**Comment by shawkins** [comment]
@jean-christophe-manciot it may matter what the contents of the password are - see using special characters in values https://www.keycloak.org/server/configuration

**Comment by jean-christophe-manciot** [comment]
Anyway, it could be a strange bash side-effect, or whatever, I think I should close this as a ```non issue```.
