### ISSUE TITLE
keycloak 401 Unauthorized on "Manage Account" on Keycloak 25.0.6

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#34771]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When migrating from keycloak 15  to keycloak 25.0.6

I'm able to login with admin UI but when I'm clicking to go manage account getting error in UI

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/2c2b078e-a7ee-4f28-bf12-51fa7430c488">

But there was no error log in server.log.
So I enabled the debug log and saw the below errors

`''2024-11-08 12:41:03,412 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-4) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
''2024-11-08 12:41:03,412 DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-4) Hibernate RegisteredSynchronization successfully registered with JTA platform
''2024-11-08 12:41:03,422 DEBUG [WebApplicationException] (executor-thread-4) Restarting handler chain for exception exception: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.keycloak.services.resources.account.AccountLoader.getAccountRestService(AccountLoader.java:135)
	at org.keycloak.services.resources.account.AccountLoader.getAccountService(AccountLoader.java:91)
	at org.keycloak.services.resources.account.AccountLoader$quarkusrestinvoker$getAccountService_265aa1aaf86cc2a5ca4d1c819f2a826c7dc11dc0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

''2024-11-08 12:41:03,422 DEBUG [WebApplicationException] (executor-thread-6) Restarting handler chain for exception exception: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.keycloak.services.resources.account.AccountLoader.getAccountRestService(AccountLoader.java:135)
	at org.keycloak.services.resources.account.AccountLoader.getAccountService(AccountLoader.java:91)
	at org.keycloak.services.resources.account.AccountLoader$quarkusrestinvoker$getAccountService_265aa1aaf86cc2a5ca4d1c819f2a826c7dc11dc0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

''2024-11-08 12:41:03,423 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-4) Error response 401: jakarta.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.keycloak.services.resources.account.AccountLoader.getAccountRestService(AccountLoader.java:135)
	at org.keycloak.services.resources.account.AccountLoader.getAccountService(AccountLoader.java:91)
	at org.keycloak.services.resources.account.AccountLoader$quarkusrestinvoker$getAccountService_265aa1aaf86cc2a5ca4d1c819f2a826c7dc11dc0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

### Version

keycloak 25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

I should be getting the manage account page.

### Actual behavior

Getting error 401 in ui and debug log in server log.

### How to Reproduce?

Upgrade from keycloak 15 to keycloak 25.0.6.

### Anything else?

Please look in this issue and advice me the solution.

**Comment by geraldh** [comment]
Hi,
same problem here - with 26.0.5
I upgraded from 25.0.6 - and now I get an 401 on loading supportedLocales
- when I create a new local account in the master realm - and login with this account - the user account console works
- when I create a new local account in other existing realm / or try to login with an existing user into this realm - I get an 401 on  supportedLocales
- I tried to change localization settings - didn't help

**Comment by geraldh** [comment]
I'm running behind a nginx reverse proxy - but to exclude the possibility of troubles with nginx - I configured the keycloak server to run on the default :8443 port and connected to this port directly - with a reverse proxy - same result.
I'll go back to the 25.0.6 snapshot and try the upgrade to 26.0.5 once again - in the next days.

**Comment by jonkoops** [comment]
@geraldh make sure you are following the latest convention as outlined in the [reverse proxy guide](https://www.keycloak.org/server/reverseproxy)

**Comment by geraldh** [comment]
@jonkoops - yes - keycloak behind a reverse proxy - you can find many problem reports.
To save me from reverse proxy troubles - I configured certs in keycloak.conf and started keycloak with:

```KC_HOSTNAME=https://keycloak...:8443 KC_HOSTNAME_ADMIN=https://keycloak...:8443 KC_LOG_LEVEL=debug /srv/keycloak/bin/kc.sh start --log=file,console --log-file=/var/log/keycloak/keycloak.log --verbose```

Problem persists - account console works in master realm - fails on my other realm

![network-trace-account-console](https://github.com/user-attachments/assets/96bd42fa-8032-4d9c-ab1c-d73f2ab29642)

**Comment by geraldh** [comment]
@jonkoops - I restored the 25.0.6 VM - the problem was already present in our 25.0.6 installation.
I'll recreate our realm - hopefully this will solve this problem.
Thanks,
Gerald

**Comment by moritzknecht** [comment]
Adding "manage-account", "manage-account-links" and "view-groups" roles to account-console-dedicated fixed this issue for me

<img width="913" alt="Bildschirmfoto 2024-11-11 um 13 40 24" src="https://github.com/user-attachments/assets/773c977c-83b1-4231-87aa-4bb7c1101533">

**Comment by geraldh** [comment]
@moritzknecht - thanks - yes this fixes the problem - but I still do not know "why" and "when" our installation started to misbehave.
I'll setup a new server and compare the user account console settings with our current installation.

**Comment by willwill96** [comment]
Anyone have a solution? I ran into the same issue with the latest keycloak image on localhost. I tried adding `manage-account-links` to the `account-console-dedicated` scope, but it seems that role does not exist in the latest version.

**Comment by Madmess** [comment]
We have the same problem after upgrate to Keycloak 26.0.7 
Role `manage-account-links` is missing

**Comment by jonkoops** [comment]
If you are able to reliably reproduce this issue in a way that we can verify locally then please file a new bug report detailing how to do so. If we are not able to reproduce the issue then it is not possible to provide a fix.
