### ISSUE TITLE
[Keycloak CI] - Quarkus IT - StartCommandDistTest and BuildAndStartDistTest

### ISSUE THREAD

**Issue by wojnarfilip** [keycloak/keycloak#34844]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Reference run: https://github.com/keycloak/keycloak/actions/runs/11788271091/job/32835219908

DefaultCacheManager fails to start due to unavailable ports ?

```
-- 2024-11-12 00:32:12,059 ERROR [org.infinispan.CONFIG] (main) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheException: Unable to start JGroups Channel
-- 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:583)
-- 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:456)
-- 	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:64)
-- 	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$2.start(CorePackageImpl.java:49)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
-- 	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
-- 	at org.infinispan.factories.GlobalComponentRegistry.preStart(GlobalComponentRegistry.java:307)
-- 	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:241)
-- 	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:778)
-- 	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:746)
-- 	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:412)
-- 	at org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory.startEmbeddedCacheManager(CacheManagerFactory.java:366)
-- 	at org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory.lambda$new$1(CacheManagerFactory.java:127)
-- 	at org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory.getOrCreateEmbeddedCacheManager(CacheManagerFactory.java:163)
-- 	at org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory_Uq0wIYR2uOCznFEYZOJeeAi-Obg_Synthetic_ClientProxy.getOrCreateEmbeddedCacheManager(Unknown Source)
-- 	at org.keycloak.quarkus.runtime.storage.infinispan.QuarkusCacheManagerProvider.getEmbeddedCacheManager(QuarkusCacheManagerProvider.java:32)
-- 	at org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory.lazyInit(DefaultInfinispanConnectionProviderFactory.java:210)
-- 	at org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory.create(DefaultInfinispanConnectionProviderFactory.java:118)
-- 	at org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory.create(DefaultInfinispanConnectionProviderFactory.java:99)
-- 	at org.keycloak.services.DefaultKeycloakSession.getOrCreateProvider(DefaultKeycloakSession.java:184)
-- 	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:173)
-- 	at org.keycloak.models.cache.infinispan.InfinispanCacheRealmProviderFactory.lazyInit(InfinispanCacheRealmProviderFactory.java:55)
-- 	at org.keycloak.models.cache.infinispan.InfinispanCacheRealmProviderFactory.create(InfinispanCacheRealmProviderFactory.java:47)
-- 	at org.keycloak.models.cache.infinispan.InfinispanCacheRealmProviderFactory.create(InfinispanCacheRealmProviderFactory.java:37)
-- 	at org.keycloak.services.DefaultKeycloakSession.getOrCreateProvider(DefaultKeycloakSession.java:184)
-- 	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:173)
-- 	at org.keycloak.storage.datastore.DefaultDatastoreProvider.getRealmProvider(DefaultDatastoreProvider.java:156)
-- 	at org.keycloak.storage.datastore.DefaultDatastoreProvider.realms(DefaultDatastoreProvider.java:234)
-- 	at org.keycloak.services.DefaultKeycloakSession.realms(DefaultKeycloakSession.java:258)
-- 	at org.keycloak.migration.migrators.MigrateTo1_2_0.migrate(MigrateTo1_2_0.java:69)
-- 	at org.keycloak.storage.datastore.DefaultMigrationManager.migrate(DefaultMigrationManager.java:157)
-- 	at org.keycloak.migration.MigrationModelManager.migrate(MigrationModelManager.java:33)
-- 	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.migrateModel(QuarkusJpaConnectionProviderFactory.java:202)
-- 	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.initSchema(QuarkusJpaConnectionProviderFactory.java:197)
-- 	at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:274)
-- 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:393)
-- 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:273)
-- 	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:263)
-- 	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:130)
-- 	at org.keycloak.services.DefaultKeycloakSessionFactory.initializeProviders(DefaultKeycloakSessionFactory.java:167)
-- 	at org.keycloak.services.DefaultKeycloakSessionFactory.initProviderFactories(DefaultKeycloakSessionFactory.java:144)
-- 	at org.keycloak.services.DefaultKeycloakSessionFactory.initProviderFactories(DefaultKeycloakSessionFactory.java:125)
-- 	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:87)
-- 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.createSessionFactory(QuarkusKeycloakApplication.java:67)
-- 	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:89)
-- 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.onStartupEvent(QuarkusKeycloakApplication.java:52)
-- 	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication_Observer_onStartupEvent_GNZ8m5QenZ9h9VNelo7awjUZFDE.notify(Unknown Source)
-- 	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
-- 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
-- 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
-- 	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
-- 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
-- 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
-- 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
-- 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
-- 	at io.quarkus.runtime.Application.start(Application.java:101)
-- 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
-- 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
-- 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:149)
-- 	at org.keycloak.quarkus.runtime.cli.Picocli.start(Picocli.java:913)
-- 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:45)
-- 	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
-- 	at picocli.CommandLine.access$1500(CommandLine.java:148)
-- 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
-- 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
-- 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
-- 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
-- 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
-- 	at picocli.CommandLine.execute(CommandLine.java:2174)
-- 	at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:142)
-- 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:130)
-- 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:109)
-- 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
-- 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
-- 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
-- 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
-- Caused by: java.lang.IllegalStateException: fv-az836-282-12038: failed to find an available port in ports [57800, 57801, 57802, 57803]
-- 	at org.jgroups.protocols.FD_SOCK2.createServer(FD_SOCK2.java:330)
-- 	at org.jgroups.protocols.FD_SOCK2.start(FD_SOCK2.java:163)
-- 	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:910)
-- 	at org.jgroups.JChannel.startStack(JChannel.java:936)
-- 	at org.jgroups.JChannel._preConnect(JChannel.java:814)
-- 	at org.jgroups.JChannel.connect(JChannel.java:328)
-- 	at org.jgroups.JChannel.connect(JChannel.java:321)
-- 	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:581)
-- 	... 81 more
```

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

- 

### Actual behavior

- 

### How to Reproduce?

-

**Comment by pruivo** [comment]
@wojnarfilip @shawkins The easier fix is to add `-Djgroups.bind.port=0` to the `@Launch` command; JGroups will use random ports.
If the test does not require clustering, adding `--cache=local` may be even better!

**Comment by shawkins** [comment]
This may eventually be addressed by https://github.com/keycloak/keycloak/pull/34272 as well.

@pruivo could we go as far to assume --cache=local the default for all the distribution tests. Only the ClusterConfig* tests look like they need to override it.

**Comment by pruivo** [comment]
@shawkins I'm not sure as I don't have a deep knowledge of the KC test suite. But after a quick look at the code, it seems like `ClusterConfigDistTest` is the only one looking for clustering-related logs.
