### ISSUE TITLE
NPE when no subject_issuer is used for token exchange

### ISSUE THREAD

**Issue by bastianccm** [keycloak/keycloak#34869]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

The commit aeb1951abad784bb51a0f2bc1f77fed7d33e14b4 changed the loading of identity providers by introducing `DefaultTokenExchangeProvider`::`locateExchangeExternalTokenByAlias`.

Before Keycloak 26 it was possible to omit the `subject_issuer` in an external token exchange, with Keycloak 26 this now results in a NPE because the issuer cannot be loaded.

### Version

26.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

Either the token exchange works, or there is an error message returned such as Unauthorised?

### Actual behavior

A NPE is thrown and the server returns:
```json
{
  "error": "unknown_error",
  "error_description": "For more on this error consult the server log."
}
```

### How to Reproduce?

Trigger an external token to internal token exchange using a permitted client for this token exchange, an external IDP and a valid access token issued by that external IDP.

```http
POST http://localhost:8080/realms/master/protocol/openid-connect/token
Content-type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:token-exchange
&client_id=<client id>
&subject_token=<valid jwt>
&subject_token_type=urn:ietf:params:oauth:token-type:jwt
&audience=<client id>
```

### Anything else?

```
keycloak-1    | 2024-11-12 13:51:40,824 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.IdentityProviderModel.getProviderId()" because "model" is null
keycloak-1    | 	at org.keycloak.services.resources.IdentityBrokerService.lambda$getIdentityProviderFactory$4(IdentityBrokerService.java:1334)
keycloak-1    | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
keycloak-1    | 	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1808)
keycloak-1    | 	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:720)
keycloak-1    | 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
keycloak-1    | 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
keycloak-1    | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
keycloak-1    | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak-1    | 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
keycloak-1    | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak-1    | 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
keycloak-1    | 	at org.keycloak.services.resources.IdentityBrokerService.getIdentityProviderFactory(IdentityBrokerService.java:1336)
keycloak-1    | 	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.locateExchangeExternalTokenByAlias(DefaultTokenExchangeProvider.java:699)
keycloak-1    | 	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchangeExternalToken(DefaultTokenExchangeProvider.java:521)
keycloak-1    | 	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.tokenExchange(DefaultTokenExchangeProvider.java:164)
keycloak-1    | 	at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchange(DefaultTokenExchangeProvider.java:130)
keycloak-1    | 	at org.keycloak.protocol.oidc.grants.TokenExchangeGrantType.process(TokenExchangeGrantType.java:62)
keycloak-1    | 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:151)
keycloak-1    | 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7.invoke(Unknown Source)
keycloak-1    | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-1    | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-1    | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1    | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
keycloak-1    | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
keycloak-1    | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
keycloak-1    | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
keycloak-1    | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
keycloak-1    | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
keycloak-1    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1    | 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by frelibert** [comment]
The problem arises also when using an external provider for which the issuer is not equal to the alias of the configured provider. This used to work as the code looped all providers and validated if the issuer was equal to the alias or if the method isIssuer returned true. Now this is split in 2 loops but the first loop (find provider by alias) throws a nullpointer because there is no model found for the given issuer when searching for it as an alias and that null reference is passed anyway to a submethod which throws the nullpointer. 
An if should be added to verify if a model was found or not. If not, the code should pass on to the next loop to try to find the provider based on the isIssuer method.

**Comment by ybasket** [comment]
> The problem arises also when using an external provider for which the issuer is not equal to the alias of the configured provider. This used to work as the code looped all providers and validated if the issuer was equal to the alias or if the method isIssuer returned true. Now this is split in 2 loops but the first loop (find provider by alias) throws a nullpointer because there is no model found for the given issuer when searching for it as an alias and that null reference is passed anyway to a submethod which throws the nullpointer. An if should be added to verify if a model was found or not. If not, the code should pass on to the next loop to try to find the provider based on the isIssuer method.

@frelibert As someone also affected by that bug, thanks for looking into it! 
I saw you seem to have coded something already, is it intended that the PR only goes against your fork and not this repo? Would love to see a fix released :)

**Comment by srparker200** [comment]
> > The problem arises also when using an external provider for which the issuer is not equal to the alias of the configured provider. This used to work as the code looped all providers and validated if the issuer was equal to the alias or if the method isIssuer returned true. Now this is split in 2 loops but the first loop (find provider by alias) throws a nullpointer because there is no model found for the given issuer when searching for it as an alias and that null reference is passed anyway to a submethod which throws the nullpointer. An if should be added to verify if a model was found or not. If not, the code should pass on to the next loop to try to find the provider based on the isIssuer method.
> 
> @frelibert As someone also affected by that bug, thanks for looking into it! I saw you seem to have coded something already, is it intended that the PR only goes against your fork and not this repo? Would love to see a fix released :)

I took the patch offered by @frelibert into a local build, and it successfully resolves the NPE when mapping the issuer. Thankyou so much!

However, I encountered a subsequent issue where OIDCIdentityProvider:isTokenTypeSupported attempts to validate the token type using the type attribute on JsonWebToken, which is null.

I believe this occurs because the issuing IDP does not set the optional typ header parameter, which is mapped to type in JWSHeader.

Skipping this check allows the exchange to complete successfully.

**Comment by ybasket** [comment]
@srparker200 That issue with missing "typ" claim should be resolved by either https://github.com/keycloak/keycloak/pull/35075 or https://github.com/keycloak/keycloak/pull/33344, maybe worth trying one of them on your local build, too.

**Comment by pmentz** [comment]
@frelibert Your issue (NPE because issuer differs from IdP alias) is probably covered by #36053 which was fixed in 26.1. Not sure if this whole issue is covered by that fix.

**Comment by ybasket** [comment]
> [@frelibert](https://github.com/frelibert) Your issue (NPE because issuer differs from IdP alias) is probably covered by [#36053](https://github.com/keycloak/keycloak/issues/36053) which was fixed in 26.1. Not sure if this whole issue is covered by that fix.

I briefly tested the new release yesterday, it resolved the problem at least for me (though I still ran into what would be solved by #35075). So I guess this issue can indeed be closed.
