### ISSUE TITLE
500 Internal Server Error when Updating Scopes for a Resource using Keycloak Admin API

### ISSUE THREAD

**Issue by mhryrehman** [keycloak/keycloak#34913]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When attempting to update scopes for a specific resource using the Keycloak Admin API, I receive a 500 Internal Server Error. After analyzing the logs, I found a NullPointerException in the stack trace.
### Note: 
Please note that I am passing a valid resourceId, and the scopes included in the request are new (i.e., they did not previously exist for this resource). Additionally, the token used in the request includes all necessary roles, such as manage-users and manage-authorization. I tried latest version(26.0.5) of keycloak as well but got same issue.
### Logs:
2024-11-13 16:39:54 2024-11-13 11:39:54,860 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NullPointerException
2024-11-13 16:39:54     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
2024-11-13 16:39:54     at org.keycloak.models.cache.infinispan.authorization.stream.InResourcePredicate.<init>(InResourcePredicate.java:39)
2024-11-13 16:39:54     at org.keycloak.models.cache.infinispan.authorization.stream.InResourcePredicate.create(InResourcePredicate.java:44)
2024-11-13 16:39:54     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheManager.resourceUpdated(StoreFactoryCacheManager.java:86)
2024-11-13 16:39:54     at org.keycloak.models.cache.infinispan.authorization.StoreFactoryCacheSession.registerResourceInvalidation(StoreFactoryCacheSession.java:269)
2024-11-13 16:39:54     at org.keycloak.models.cache.infinispan.authorization.ResourceAdapter.setName(ResourceAdapter.java:105)
2024-11-13 16:39:54     at org.keycloak.models.utils.RepresentationToModel.toModel(RepresentationToModel.java:1496)
2024-11-13 16:39:54     at org.keycloak.authorization.admin.ResourceSetService.update(ResourceSetService.java:169)
2024-11-13 16:39:54     at org.keycloak.authorization.admin.ResourceSetService$quarkusrestinvoker$update_3af157bf25db0d0c12baa49c86af097ce480be11.invoke(Unknown Source)
2024-11-13 16:39:54     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-11-13 16:39:54     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-11-13 16:39:54     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-11-13 16:39:54     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
2024-11-13 16:39:54     at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
2024-11-13 16:39:54     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
2024-11-13 16:39:54     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
2024-11-13 16:39:54     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
2024-11-13 16:39:54     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
2024-11-13 16:39:54     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-11-13 16:39:54     at java.base/java.lang.Thread.run(Thread.java:1583)

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The resource's scopes should be updated successfully without any errors.

### Actual behavior

The API returns a 500 Internal Server Error, and the logs indicate a NullPointerException.

2024-11-13 16:39:54 2024-11-13 11:39:54,860 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NullPointerException
2024-11-13 16:39:54     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
2024-11-13 16:39:54     at org.keycloak.models.cache.infinispan.authorization.stream.InResourcePredicate.<init>(InResourcePredicate.java:39)

### How to Reproduce?

To update scopes send a PUT request to the endpoint **http://172.16.102.238:8080/admin/realms/testing/clients/{clientId}/authz/resource-server/resource/{resourceId}**, with payload {
    "scopes": [
        {
            "name": "delete-scope"
        }
    ]
}
Observe that a 500 Internal Server Error is returned.

### Anything else?

Please note that I am passing a valid resourceId, and the scopes included in the request are new (i.e., they did not previously exist for this resource). Additionally, the token used in the request includes all necessary roles, such as manage-users and manage-authorization.

**Comment by martin-kanis** [comment]
@mhryrehman Hi, but you are not providing `id` of the authorization scope, only name. Check how admin console sends the request.

**Comment by martin-kanis** [comment]
We could improve this by returning BAD REQUEST.
