### ISSUE TITLE
CreateUserIfUnique does not find duplicate anymore

### ISSUE THREAD

**Issue by ch-lepp** [keycloak/keycloak#34934]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I've recently upgraded from v25.0.1 to the current v26.0.5

Since then, the Create-User-If-Unique SPI does'nt find duplicates anymore.
[context.getSession().users().getUserByUsername(context.getRealm(), username)](https://github.com/keycloak/keycloak/blob/26.0.5/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpCreateUserIfUniqueAuthenticator.java#L140) seems to return a null value.

Through debugging I figured out, that the username is written in lowercase into the database while the username attribute at that point in the code contains a String with capital letters in it.
But I dont think that this is the underlying issue here...

The result of the failure is the following exception in the keycloak log:
```
2024-11-13 15:48:06,049 WARN  [org.keycloak.services] (executor-thread-11) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
        at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1082)
        at org.keycloak.services.resources.LoginActionsService$1.authenticateOnly(LoginActionsService.java:919)
        at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:912)
        at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:380)
        at org.keycloak.services.resources.LoginActionsService.brokerLoginFlow(LoginActionsService.java:951)
        at org.keycloak.services.resources.LoginActionsService.firstBrokerLoginGet(LoginActionsService.java:823)
        at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$firstBrokerLoginGet_4319965f5ab7d0aadd2e5b5f2cde702e4aaaf535.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

26.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

Create-User-If-Unique should properly identify users with duplicate usernames.

### Actual behavior

Create-User-If-Unique doesn't find already existing users with the same username and instead produces an exception.

### How to Reproduce?

1. Have an external IDP with a username mapper configured as well as a firts-login-flow using the create-user-if-unique SPI.
2. Log into the system using the external IDP, Logout again
3. Log into the keycloak admin console and delete the linking of the newly created user with the external idp
4. Log into the system using the external IDP and the same user as in step 2

**Comment by mposolda** [comment]
@ch-lepp Could you please confirm if this happens only for users with the IDP usernames in uppercase (or mixed-cases) but does not happen for IDP users in lowercase. Is it correct? Any example of IDP username for whom you are seeing this?

**Comment by ch-lepp** [comment]
@mposolda Thx for looking into the issue.

The error also occurs using only usernames with all lowercase letters.


The error also occurs when searching for other attributes than the username.
Additionally to the Create-User-If-Unique SPI I also use a custom SP that contains the following line of code:
`Optional<UserModel> existingUser = context.getSession().users().searchForUserStream(context.getRealm(), params).findFirst();`
**params** containing custom user attributes in that example.

This custom SPI of ours does also not properly work anymore since the Keycloak update.
Its the same issue: existingUser is empty even though a user with the fitting params definitely exists...

**Comment by ch-lepp** [comment]
@martin-kanis  thx to you too for looking into the issue.

The username mapper we have configured for our IDP has the following properties:
- Mapper Type: Username Template Importer
- Template: ExternalUser${CLAIM.mycustomclaim}
- Sync Mode Override: Import
- Target: LOCAL

An example of a generated username by this username mapper would be "ExternalUser023752037207235423".

We also use another mapper for this IDP with the follwing properties:
- Mapper Type: Attribute Importer
- Claim: mycustomclaim
- User Attribute Name: customclaim
- Sync Mode Override: Force

Searching for a user by this custom attribute also fails with the described error...

**Comment by martin-kanis** [comment]
@ch-lepp In step 3, when I unlink the user from the IDP, user still exists in the realm. Then when I try to link the user again, it fails because the user with the same email exists in the realm. 
Did I miss some steps when reproducing or our configuration is different?

**Comment by ch-lepp** [comment]
Hmm, I am a bit confused by your question...

First things first:
In our Keycloak we also have the "log in with email" option active. So duplicate emails are not allowed in our system either.

However:
The external IDP does not provide any email address. So new users coming from the external IDP are created in Keycloak with an empty email address.

In any case:
In step 4 of my repro, Keycloak is not supposed to create a new user but should link the already existing user again. So the duplicate email error should play no role whatsoever.
The fact, that you run into this issue, kind of proves, that keycloak malefunctions here and tries to create a new user when a fitting user already exists...

**Comment by ch-lepp** [comment]
Oh boy  -  I figured out a (temporary) solution....

So I have a first broker login flow consisting only of the "create-user-if-unique" and the "automatically-set-existing-user" SPI.
Both are configured as "alternative".

The error is triggered when the two SPIs have the wrong order.
If I move the "create-user-if-unique" SPI before the "automatically-set-existing-user" SPI, everything works as expected...

So the solution has become way less urgent for me, since I can simply set the order of the two SPIs accordingly.
But it would still be nice, if you could have a look into it, since the order didnt matter in previous keycloak releases...

**Comment by martin-kanis** [comment]
@ch-lepp I'm glad you found the solution to the problem.
