### ISSUE TITLE
syslog /dev/log not working?

### ISSUE THREAD

**Issue by f1-outsourcing** [keycloak/keycloak#34972]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

this in keycloak.conf:
log=syslog
log-level=WARN

generates this error

LogManager error of type WRITE_FAILURE: Error writing to TCP stream
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:589)
        at java.base/sun.nio.ch.Net.connect(Net.java:578)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:751)
        at java.base/java.net.Socket.connect(Socket.java:686)
        at java.base/java.net.Socket.<init>(Socket.java:555)
        at java.base/java.net.Socket.<init>(Socket.java:356)
        at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:273)
        at org.jboss.logmanager.handlers.ClientSocketFactory$1.createSocket(ClientSocketFactory.java:122)
        at org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector.run(TcpOutputStream.java:376)
        at java.base/java.lang.Thread.run(Thread.java:1583)

### Version

26.0.5?

### Regression

- [ ] The issue is a regression

### Expected behavior

I think the default for syslog is writing to /dev/log not?

### Actual behavior

nothing logged

### How to Reproduce?

change config

### Anything else?

ps. searching not working in issues?

**Comment by shawkins** [comment]
The documentation mentions "When the Syslog handler is enabled, the host is using localhost as host value. The Default port is 514."

**Comment by f1-outsourcing** [comment]
Yes but there is no syslog on localhost, I am putting /dev/log in containers.
