### ISSUE TITLE
Error on first login with identity provider when using federated Active Directory

### ISSUE THREAD

**Issue by aadamovicienc** [keycloak/keycloak#35010]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I have a Keycloak 26.0.5 server deployed that is linked to a google IdP and federated with an Active Directory environment.

If I create a user in Keycloak UI, the user gets written into LDAP.

If I login into a client using the IdP, it does not create the user in AD and fails with the following error:

KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.storage.ldap.idm.model.LDAPDn.toString()" because the return value of "org.keycloak.storage.ldap.idm.model.LDAPObject.getDn()" is null
at org.keycloak.storage.ldap.mappers.msad.MSADUserAccountControlStorageMapper$MSADUserModelDelegate.setEnabled(MSADUserAccountControlStorageMapper.java:252)
at org.keycloak.authentication.authenticators.broker.IdpCreateUserIfUniqueAuthenticator.authenticateImpl(IdpCreateUserIfUniqueAuthenticator.java:87)
at org.keycloak.authentication.authenticators.broker.AbstractIdpAuthenticator.authenticate(AbstractIdpAuthenticator.java:76)
at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:465)
at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:291)
at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:400)
at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:269)
at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1074)
at org.keycloak.services.resources.LoginActionsService$1.authenticateOnly(LoginActionsService.java:919)
at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:912)
at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:380)
at org.keycloak.services.resources.LoginActionsService.brokerLoginFlow(LoginActionsService.java:951)
at org.keycloak.services.resources.LoginActionsService.firstBrokerLoginGet(LoginActionsService.java:823)
at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$firstBrokerLoginGet_4319965f5ab7d0aadd2e5b5f2cde702e4aaaf535.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:1583)

This is working in my development environment with Keycloak version 25.0.6.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

On first login with the IdP if the user does not exist it gets created in Keycloak and synced into the federated Active Directory.

### Actual behavior

During first login with IdP the user does not get created and the login errors out.

### How to Reproduce?

Link Keycloak to and identity provider. Federate Keycloak to Active Directory. Create a SAML client and try to login.

### Anything else?

Attached the keycloak DEBUG log.
[keycloak.log](https://github.com/user-attachments/files/17784076/keycloak.log)

**Comment by pedroigor** [comment]
I tried to reproduce using the following steps but without success:

* Create a realm `ldap`
* Create a LDAP federation in `ldap` realm
* Create a broker in `ldap` realm. The broker is just another realm.

When authenticating using the user through the broker, the user is created in LDAP without any error.

I'm not sure what might be causing the errors in the logs mainly because the DN should always be set to LDAP objects wrapping an user from LDAP.

Anything else we are missing to reproduce the problem?
