### ISSUE TITLE
Instance can't join infinispan and stop with unknow reason on Kubernetes

### ISSUE THREAD

**Issue by adthonb** [keycloak/keycloak#35014]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

I upgraded Keycloak to version 25.0.0 with 3 instances of StatefulSets on Kubernetes. The first instance starts normally but the next instance of StatefulSets has an Infinispan error. This make container loop to restart.

This error message from the next Keycloak instance:
```
Appending additional Java properties to JAVA_OPTS
2024-11-16 15:15:48,234 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
        - hostname
Consult the Release Notes for details.
2024-11-16 15:16:33,827 INFO  [org.infinispan.CONTAINER] (Thread-5) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-11-16 15:16:35,639 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: java.lang.NullPointerException: Cannot throw exception because the return value of "java.util.function.BiFunction.apply(Object, Object)" is null
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doTheWork(JtaIsolationDelegate.java:202)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.lambda$delegateWork$3(JtaIsolationDelegate.java:91)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInSuspendedTransaction(JtaIsolationDelegate.java:123)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.delegateWork(JtaIsolationDelegate.java:88)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:276)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:107)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:52)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:276)
        at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:70)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:157)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-11-16 15:16:40,535 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2024-11-16 15:16:40,539 INFO  [org.jgroups.JChannel] (Thread-5) local_addr: a860fb1d-fa78-414e-bc88-96f3b36f6ffc, name: keycloak-1-63238
2024-11-16 15:16:40,929 INFO  [org.jgroups.protocols.FD_SOCK2] (Thread-5) server listening on *.57800
2024-11-16 15:16:42,135 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000094: Received new cluster view for channel ISPN: [keycloak-0-15809|1] (2) [keycloak-0-15809, keycloak-1-63238]
2024-11-16 15:16:43,829 INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000079: Channel `ISPN` local address is `keycloak-1-63238`, physical addresses are `[10.37.0.15:7800]`
2024-11-16 15:16:49,149 INFO  [org.infinispan.LIFECYCLE] (jgroups-8,keycloak-1-63238) [Context=org.infinispan.CONFIG] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:49,729 INFO  [org.infinispan.LIFECYCLE] (non-blocking-thread--p2-t1) [Context=org.infinispan.CONFIG] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:50,528 INFO  [org.infinispan.LIFECYCLE] (jgroups-10,keycloak-1-63238) [Context=actionTokens] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:50,634 INFO  [org.infinispan.LIFECYCLE] (non-blocking-thread--p2-t2) [Context=actionTokens] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:51,142 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-1-63238) [Context=authenticationSessions] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:51,235 INFO  [org.infinispan.LIFECYCLE] (jgroups-6,keycloak-1-63238) [Context=authenticationSessions] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:52,025 INFO  [org.infinispan.LIFECYCLE] (jgroups-6,keycloak-1-63238) [Context=clientSessions] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:52,040 INFO  [org.infinispan.LIFECYCLE] (jgroups-6,keycloak-1-63238) [Context=clientSessions] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:52,634 INFO  [org.infinispan.LIFECYCLE] (jgroups-10,keycloak-1-63238) [Context=loginFailures] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:52,732 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-11-16 15:16:52,738 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-1-63238) [Context=loginFailures] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:53,131 INFO  [org.infinispan.LIFECYCLE] (jgroups-10,keycloak-1-63238) [Context=offlineClientSessions] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:53,150 INFO  [org.infinispan.LIFECYCLE] (jgroups-10,keycloak-1-63238) [Context=offlineClientSessions] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:53,725 INFO  [org.infinispan.LIFECYCLE] (jgroups-5,keycloak-1-63238) [Context=offlineSessions] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:53,827 INFO  [org.infinispan.LIFECYCLE] (jgroups-8,keycloak-1-63238) [Context=offlineSessions] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:54,226 INFO  [org.infinispan.LIFECYCLE] (jgroups-8,keycloak-1-63238) [Context=sessions] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:54,243 INFO  [org.infinispan.LIFECYCLE] (jgroups-8,keycloak-1-63238) [Context=sessions] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:54,728 INFO  [org.infinispan.LIFECYCLE] (jgroups-6,keycloak-1-63238) [Context=work] ISPN100002: Starting rebalance with members [keycloak-0-15809, keycloak-1-63238], phase READ_OLD_WRITE_ALL, topology id 2
2024-11-16 15:16:54,736 INFO  [org.infinispan.LIFECYCLE] (non-blocking-thread--p2-t2) [Context=work] ISPN100010: Finished rebalance with members [keycloak-0-15809, keycloak-1-63238], topology id 2
2024-11-16 15:16:55,946 ERROR [org.infinispan.CONFIG] (Thread-5) ISPN000660: DefaultCacheManager start failed, stopping any running components: java.lang.IllegalStateException: Shutdown in progress
        at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:67)
        at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:250)
        at org.infinispan.factories.GlobalComponentRegistry.addShutdownHook(GlobalComponentRegistry.java:254)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:373)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:243)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:778)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:746)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:412)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.lambda$startEmbeddedCacheManager$3(CacheManagerFactory.java:154)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-11-16 15:16:55,947 WARN  [org.infinispan.factories.GlobalComponentRegistry] (Thread-5) ISPN000126: Attempted to stop() from FAILED state, but caught exception: java.lang.IllegalStateException: Shutdown in progress
        at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:83)
        at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:281)
        at org.infinispan.factories.GlobalComponentRegistry.removeShutdownHook(GlobalComponentRegistry.java:210)
        at org.infinispan.factories.AbstractComponentRegistry.internalStop(AbstractComponentRegistry.java:388)
        at org.infinispan.factories.AbstractComponentRegistry.stop(AbstractComponentRegistry.java:324)
        at org.infinispan.factories.AbstractComponentRegistry.componentFailed(AbstractComponentRegistry.java:278)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:259)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:778)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:746)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:412)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.lambda$startEmbeddedCacheManager$3(CacheManagerFactory.java:154)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-11-16 15:16:57,840 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
```

My custom Dockerfile:
```
FROM quay.io/keycloak/keycloak:25.0.0 AS builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak

# Install theme
COPY --chown=keycloak:keycloak themes /opt/keycloak/themes

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:25.0.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

My k8s manifest:
```
apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  labels:
    app: keycloak
    version: 25.0.0
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
    version: 25.0.0
spec:
  serviceName: keycloak-headless
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: keycloak
          image: myrepo/keycloak:25.0.0
          imagePullPolicy: Always
          args: ["start", "--optimized"]
          envFrom:
          - secretRef:
              name: keycloak-secret
          env:
          - name: KC_HOSTNAME
            value: https://mydomain/kc
          - name: KC_CACHE_STACK
            value: kubernetes
          - name: KC_PROXY_HEADERS
            value: xforwarded
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: JAVA_OPTS_APPEND
            value: -Djgroups.dns.query=keycloak-headless.default.svc.cluster.local
          resources:
            limits:
              cpu: 500m
              memory: 750Mi
          ports:
          - name: http
            containerPort: 8080
          - name: metrics
            containerPort: 9000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: metrics
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 1
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /health/live
              port: metrics
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 1
            timeoutSeconds: 5
            initialDelaySeconds: 60
      imagePullSecrets:
      - name: private-docker-repo
```

**Kubernetes version: v1.31.2**

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The next instance of StatefulSets can start normally.

### Actual behavior

Next instance can't start and is left infinispan.

### How to Reproduce?
- Scale down the replica to 0
- Upgrade from v24.0.0
- Apply my manifest to the Kubernetes cluster and wait until the second Pod starts.

**Comment by shawkins** [comment]
How is the database username and password configured?

> 2024-11-16 15:16:35,639 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata

A warning/error like this  usually means a problem with the username or password that is being obscurred by hibernate.

> DefaultCacheManager start failed, stopping any running components: java.lang.IllegalStateException: Shutdown in progress

This is probably not indicative of an infinispan issue. The prior logs show it joining the cluster and seeing an existing member.

**Comment by adthonb** [comment]
> How is the database username and password configured?

The database configured with `keycloak-secret` Secret on `KC_DB_URL` key:
```
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KC_DB_URL: jdbc:postgresql://pgbouncer.postgres-operator.svc.cluster.local:5432/keycloak?user=dbuser&password=secret-urlencoded
```

The above Secret works on v24 but not v25

Now, I can solved the issue with those changes:
1. I had change `keycloak-secret` Secret to
```
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KC_DB_URL_HOST: pgbouncer.postgres-operator.svc.cluster.local
  KC_DB_PASSWORD: dbpassword
  KC_DB_USER: dbuser
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: adminpass
```

2. I add the resource request and limit to STS:
```
...
      containers:
          resources:
            requests:
              memory: "1500M"
              cpu: "500m"
            limits:
              memory: "2G"
              cpu: "1000m"
```

Maybe you can close this issue. Thank you for your information to explain the logs.

**Comment by adthonb** [comment]
After spend a hour to diagnose the issue. I found Keycloak can't connect through PgBouncer with `pool_mode: transaction`

**Comment by yrodiere** [comment]
Hey,

> I believe KC 26 with the newer version of quarkus will provide a better hibernate error to make the situation clearer. cc @yrodiere

I'm not sure why you are saying that, as I couldn't find a report for this specific error, much less a fix... it seems caused by the exception converter returning `null`, which certainly looks like a bug, possibly caused by [this line](https://github.com/hibernate/hibernate-orm/blob/c931c86896958e4b2f4986a17c6a9c0c17d266f1/hibernate-core/src/main/java/org/hibernate/exception/internal/SQLStateConversionDelegate.java#L124).
Did you have a specific reported issue in mind? https://hibernate.atlassian.net/browse/HHH-18313 is not it, it's a different issue.
Unless you did have a specific issue/patch in mind (which I didn't find), or you use a custom SQLExceptionHelper/converter (which seems unlikely), we should probably report this at https://hibernate.atlassian.net/browse/HHH...
