### ISSUE TITLE
PersistentSessionsWorker: retry with 0 backoff ms.

### ISSUE THREAD

**Issue by rvanderboom** [keycloak/keycloak#35047]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

We released keycloak 26 and functional and performance wise everything is good.

However around once a day a duplicate insert session happens , which results in 20.000 error messages in a 10 second time frame.

We have reduced this number by overwriting PersistentSessionsWorker, with a back-off time of 100ms instead of "0" (during 5 instead of 10) which is in the code:

   Retry.executeWithBackoff((iteration) -> {
   ....
   }, Duration.of(10L, ChronoUnit.SECONDS), 0);
   
   
   
   The duplicate itself concerns 1 specific session id (1 of the 10.000 ?) around once a day, and doesn't seem to be a functional big issue: 
   
   HHH100501: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry 'b9f91c53-ec37-4aaf-b54d-12f793c58d09-1' for key 'OFFLINE_USER_SESSION.PRIMARY'], SQL: insert into OFFLINE_USER_SESSION (BROKER_SESSION_ID,CREATED_ON,DATA,LAST_SESSION_REFRESH,REALM_ID,USER_ID,VERSION,OFFLINE_FLAG,USER_SESSION_ID) values (?,?,?,?,?,?,?,?,?)
   
   
   (repeated 20.000 times of same entry id.)
   
   
   
   

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

when retry a insert session statement or others, use a backoff time > 0ms to avoid a bulk of same error messages.

### Actual behavior

To many error messages because of back-off delay 0ms.

### How to Reproduce?

generate a sql exception (like duplicate insert).

**Comment by mposolda** [comment]
Adding iam team as it is related to user sessions. However not sure if this is rather "sre" team? Leaving to you to eventually decide.

**Comment by twobiers** [comment]
Think this is related to my issue #35602. The cause you spot makes sense to me.

**Comment by ahus1** [comment]
The intent of the back-off of 0 ms was that when there is a concurrent write or deadlock happening, it has been resolved the moment the call returns, and then there is no need to wait. 

When there is a PK violation, it probably needs to be handled differently, and I wonder how this can happen in the first place: can there be two concurrent requests to create an offline session for the same online user ID? Even if we would back-off, the problem will not go away by changing anything around retries.

**Comment by ahus1** [comment]
@pedroigor - I was only looking at the logs, I didn't try to reproduce it.

**Comment by pedroigor** [comment]
@rvanderboom Can you please share more from the stacktrace?

**Comment by rvanderboom** [comment]
mm no we do not see the stacktrac of #35602, only :

HHH100501: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?], SQL: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?


We still have them all day long, but since the 0 backoff ms, only a few retries, so around 1 exception per minute, that includes the retries between 2-5 times...

We don't have any complains so not able to give it prio to find out what its caused, but maybe in a multithreaded environment , if its about versioning/optimistic locks, maybe its an expected behaviour... ?

**Comment by gpcmol** [comment]
The issue we have seems to be similar.
We run Keycloak 26.0.7 on kubernetes with cloud-native postgres.

These are the ENV vars:
KC_CACHE_STACK: "kubernetes"
CACHE_OWNERS_COUNT: "2"
CACHE_OWNERS_AUTH_SESSIONS_COUNT: "2"

We have 3 instances of cloudnative-pg/postgresql:15.10

In the logging we see a log of these exceptions (224 between 2025-01-06 20:36:57,524 and 2025-01-08 09:19:25,147):
```
2025-01-06 20:37:26,789 ERROR [org.hibernate.orm.jdbc.batch] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) HHH100501: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?], SQL: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?
2025-01-06 20:37:26,789 WARN  [com.arjuna.ats.arjuna] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff0ae960fb:b131:6757092c:4a791f, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@3f33a1b4 >: jakarta.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?
	at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:221)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:95)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1433)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:491)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2354)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1978)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
	at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:52)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:348)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:66)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1290)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
	at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
	at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:100)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
	at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:396)
	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:361)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:439)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:312)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:302)
	at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.lambda$process$3(PersistentSessionsWorker.java:89)
	at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:102)
	at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:93)
	at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.process(PersistentSessionsWorker.java:86)
	at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.run(PersistentSessionsWorker.java:69)
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?
	at org.hibernate.jdbc.Expectations.checkBatched(Expectations.java:80)
	at org.hibernate.jdbc.Expectation$RowCount.verifyOutcome(Expectation.java:174)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.checkRowCounts(BatchImpl.java:321)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:285)
	at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupSingleTable.forEachStatement(PreparedStatementGroupSingleTable.java:67)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.performExecution(BatchImpl.java:264)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.execute(BatchImpl.java:242)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:188)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:674)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:511)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:414)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1429)
	... 26 more
```

The behaviour in our metrics of the db wal is the following:
![image](https://github.com/user-attachments/assets/87b7053b-7e90-44ed-8c1f-b725f7300cef)

orange (db-wal-1) and yellow (db-wal-2) are trying to sync with db-wal-3 (blue), but can't, since there is some lock.

Probably some issue is introduced when keeping the offline sessions in DB instead of in cache.

**Comment by ahus1** [comment]
The "Batch update returned unexpected row count ... OFFLINE_USER_SESSION" is an expected behavior in an environment where a user session is updated concurrently. 

In the future, we might see fewer log entries with a more recent version of Hibernate. Keycloak has a retry mechanism, and those retries will usually succeed, and the caller will not see any problems except for a short delay due to the retry. 
The number of log entries will depend on the number of concurrent requests. 

The "Duplicate entry ..." is a bigger problem, as there a retry won't work. This will IMHO happen if there is a concurrent request to create an offline session for a given online session. Expect a PR related to this issue.

**Comment by ahus1** [comment]
@gpcmol - when showing three WALs, are you running PostgreSQL in a mode where multiple nodes accepts writes to the database? I'm not familiar with the cloudnative-pg setup and its concepts, so you might need to explain a bit more for me here.

**Comment by gpcmol** [comment]
Thanks for verifying, @ahus1. We connect to the only writer db.
We have 3 pods: one ro, one r and 1 rw. When something is going wrong, there is an election mechanism that selects a new writer when needed. The promise is to be 100% available.

I'll have a look into issues regarding the cloudnative postgres.

**Comment by ahus1** [comment]
@gpcmol - thank you for sharing this. Can you elaborate on the "one ro, one r". I'd be happy to learn the differences between "ro" and "r". 

With persistent sessions, you should be fine when using a single-master approach with your database, as it would avoid conflicts that would arise with multi-master approaches. From your previous comment it seems you're using a single-master approach, please confirm.

**Comment by gpcmol** [comment]
Yes, we're using single master.

rw = read and write instance
ro = read from the read-only instance
r = read from any instance

the issue we're having looks like this: https://github.com/cloudnative-pg/cloudnative-pg/issues/6544
(so non keycloak related)

**Comment by ahus1** [comment]
@gpcmol - ok, let's assume that the WAL log is unrelated to Keycloak and also unrelated to the errors you see until new evidence arises.

**Comment by ZIRAKrezovic** [comment]
Sorry to bump this.

Pull request #36310 should be part of 26.1.0, but it does not seem to fix the problem completely. With keycloak-26.1.0 (official docker image) I still get the issue, last one few hours ago

My setup is quite simple - single PostgreSQL instance run in docker

Timestamps are in UTC+1 (CET)

```
2025-01-22 14:25:47,054 INFO  [org.hibernate.orm.jdbc.batch] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) HHH100503: On release of batch it still contained JDBC statements
2025-01-22 14:25:47,055 ERROR [org.hibernate.orm.jdbc.batch] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) HHH100501: Exception executing batch [org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?], SQL: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?
2025-01-22 14:25:47,055 WARN  [com.arjuna.ats.arjuna] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffff0afe0012:acd9:678a1500:12387, org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@3c9bdffa >: jakarta.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?
        at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:221)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:95)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1433)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:491)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2354)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1978)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:336)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
        at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
        at com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:52)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:348)
        at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:66)
        at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:135)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1290)
        at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:104)
        at io.quarkus.narayana.jta.runtime.NotifyingTransactionManager.commit(NotifyingTransactionManager.java:70)
        at org.keycloak.transaction.JtaTransactionWrapper.commit(JtaTransactionWrapper.java:101)
        at org.keycloak.services.DefaultKeycloakTransactionManager.lambda$commitWithTracing$0(DefaultKeycloakTransactionManager.java:169)
        at org.keycloak.tracing.NoopTracingProvider.trace(NoopTracingProvider.java:59)
        at org.keycloak.tracing.NoopTracingProvider.trace(NoopTracingProvider.java:69)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commitWithTracing(DefaultKeycloakTransactionManager.java:168)
        at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:136)
        at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:396)
        at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:361)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:463)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:336)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:326)
        at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.lambda$process$5(PersistentSessionsWorker.java:110)
        at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:102)
        at org.keycloak.common.util.Retry.executeWithBackoff(Retry.java:93)
        at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.lambda$process$7(PersistentSessionsWorker.java:107)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:337)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:456)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:336)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:326)
        at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.process(PersistentSessionsWorker.java:91)
        at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.run(PersistentSessionsWorker.java:76)
Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update OFFLINE_USER_SESSION set BROKER_SESSION_ID=?,CREATED_ON=?,DATA=?,LAST_SESSION_REFRESH=?,REALM_ID=?,USER_ID=?,VERSION=? where OFFLINE_FLAG=? and USER_SESSION_ID=? and VERSION=?
        at org.hibernate.jdbc.Expectations.checkBatched(Expectations.java:80)
        at org.hibernate.jdbc.Expectation$RowCount.verifyOutcome(Expectation.java:174)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.checkRowCounts(BatchImpl.java:321)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:285)
        at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupSingleTable.forEachStatement(PreparedStatementGroupSingleTable.java:67)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.performExecution(BatchImpl.java:264)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.execute(BatchImpl.java:242)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:188)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:674)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:511)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:414)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1429)
        ... 35 more

2025-01-22 14:25:47,058 ERROR [org.keycloak.transaction.JtaTransactionWrapper] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) Exception during transaction operation. Request context: Non-HTTP task, Transaction: TransactionImple < ac, BasicAction: 0:ffff0afe0012:acd9:678a1500:12386 status: ActionStatus.ABORTED >
```

**Comment by ahus1** [comment]
@ZIRAKrezovic - this issue was about an almost unlimited number of retries, which is now resolved. 

What you see in your log is Keycloak retrying a concurrent update to the database, possibly only a single retry for a given request. Unfortunately the retry is very verbose due to the logging of the different libraries involved here, which makes it look worse.

If you want to go into a more detailed analysis, possibly analyzing the concurrent requests that are happening, please create a new bug issue and reference it here.

**Comment by robvanderboom** [comment]
thanks for resolving, great !
