### ISSUE TITLE
Client-initiated account linking fails when user already has a federated identity

### ISSUE THREAD

**Issue by lucyydotp** [keycloak/keycloak#35059]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

Attempting to link an identity provider account via client-initiated account linking fails when a user already has a federated identity from the provider, throwing this exception:

```
keycloak-1  | 2024-11-18 18:44:59,608 INFO  [org.hibernate.orm.jdbc.batch] (executor-thread-1) HHH100503: On release of batch it still contained JDBC statements
keycloak-1  | 2024-11-18 18:44:59,609 ERROR [org.hibernate.orm.jdbc.batch] (executor-thread-1) HHH100501: Exception executing batch [org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_40 ON PUBLIC.FEDERATED_IDENTITY(IDENTITY_PROVIDER, USER_ID) VALUES ( /* key:28 */ 'lucy-test-github', '209cda49-89c5-4cf4-bdbb-aa976c155bb8')"; SQL statement:
keycloak-1  | insert into FEDERATED_IDENTITY (REALM_ID,TOKEN,FEDERATED_USER_ID,FEDERATED_USERNAME,IDENTITY_PROVIDER,USER_ID) values (?,?,?,?,?,?) [23505-230]], SQL: insert into FEDERATED_IDENTITY (REALM_ID,TOKEN,FEDERATED_USER_ID,FEDERATED_USERNAME,IDENTITY_PROVIDER,USER_ID) values (?,?,?,?,?,?)
keycloak-1  | 2024-11-18 18:44:59,609 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-1) SQL Error: 23505, SQLState: 23505
keycloak-1  | 2024-11-18 18:44:59,609 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-1) Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_40 ON PUBLIC.FEDERATED_IDENTITY(IDENTITY_PROVIDER, USER_ID) VALUES ( /* key:28 */ 'lucy-test-github', '209cda49-89c5-4cf4-bdbb-aa976c155bb8')"; SQL statement:
keycloak-1  | insert into FEDERATED_IDENTITY (REALM_ID,TOKEN,FEDERATED_USER_ID,FEDERATED_USERNAME,IDENTITY_PROVIDER,USER_ID) values (?,?,?,?,?,?) [23505-230]
keycloak-1  | 2024-11-18 18:44:59,613 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-1) Failed to make identity provider oauth callback: org.keycloak.models.ModelDuplicateException: Duplicate resource error
keycloak-1  | 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:103)
keycloak-1  | 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:68)
keycloak-1  | 	at jdk.proxy2/jdk.proxy2.$Proxy62.flush(Unknown Source)
keycloak-1  | 	at org.keycloak.models.jpa.JpaUserProvider.addFederatedIdentity(JpaUserProvider.java:175)
keycloak-1  | 	at org.keycloak.storage.UserStorageManager.addFederatedIdentity(UserStorageManager.java:632)
keycloak-1  | 	at org.keycloak.models.cache.infinispan.UserCacheSession.addFederatedIdentity(UserCacheSession.java:857)
keycloak-1  | 	at org.keycloak.services.resources.IdentityBrokerService.performAccountLinking(IdentityBrokerService.java:994)
keycloak-1  | 	at org.keycloak.services.resources.IdentityBrokerService.authenticated(IdentityBrokerService.java:572)
keycloak-1  | 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:568)
keycloak-1  | 	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_ab908fbdd086ee82e140d8a818c077362a2d04b4.invoke(Unknown Source)
keycloak-1  | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-1  | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-1  | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
keycloak-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
keycloak-1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
keycloak-1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
keycloak-1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
keycloak-1  | Caused by: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_40 ON PUBLIC.FEDERATED_IDENTITY(IDENTITY_PROVIDER, USER_ID) VALUES ( /* key:28 */ 'lucy-test-github', '209cda49-89c5-4cf4-bdbb-aa976c155bb8')"; SQL statement:
keycloak-1  | insert into FEDERATED_IDENTITY (REALM_ID,TOKEN,FEDERATED_USER_ID,FEDERATED_USERNAME,IDENTITY_PROVIDER,USER_ID) values (?,?,?,?,?,?) [23505-230]
keycloak-1  | 	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1277)
keycloak-1  | 	at io.agroal.pool.wrapper.StatementWrapper.executeBatch(StatementWrapper.java:340)
keycloak-1  | 	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:279)
keycloak-1  | 	at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupSingleTable.forEachStatement(PreparedStatementGroupSingleTable.java:67)
keycloak-1  | 	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.performExecution(BatchImpl.java:264)
keycloak-1  | 	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.execute(BatchImpl.java:242)
keycloak-1  | 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:188)
keycloak-1  | 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:674)
keycloak-1  | 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:511)
keycloak-1  | 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:414)
keycloak-1  | 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
keycloak-1  | 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
keycloak-1  | 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1429)
keycloak-1  | 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1415)
keycloak-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
keycloak-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
keycloak-1  | 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:66)
keycloak-1  | 	... 19 more
keycloak-1  |
keycloak-1  | 2024-11-18 18:44:59,615 WARN  [org.keycloak.events] (executor-thread-1) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="0000175f-702e-4b99-9c99-c807a7158c1d", realmName="my-realm", clientId="my-client-id", userId="null", ipAddress="my-ip-address", error="identity_provider_login_failure", identity_provider="lucy-test-github", redirect_uri="http://example.com", identity_provider_identity="my-federated-username", code_id="e98b0c7d-7ad5-4145-ad25-6305010bd4c9"
```

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The previously linked account is unlinked and replaced with the newly linked one.

### Actual behavior

The above exception is thrown, and a generic "Unexpected error when authenticating with identity provider" page is shown to the client.

### How to Reproduce?

- Create an identity provider (I can reproduce with GitHub and a custom OAuth2 provider)
- Link an account through client-initiated account linking
- Attempt to link a second account the same way 

### Anything else?

I haven't tested this with a SAML client so this might be OAuth specific

**Comment by pedroigor** [comment]
Looks like the users you are trying to federate share the same ID ? Is that the case?

**Comment by lucyydotp** [comment]
I don't believe so - here I'm federating the same keycloak user with different github accounts. I'll test with a fresh instance shortly to confirm. Regardless, we will likely end up in this situation in production (people linking the same federated account to multiple keycloak users) so handling this more gracefully would be very beneficial.

**Comment by sguilhen** [comment]
@lucyydotp I haven't triaged this one yet - just to clarify, you're hitting this issue when linking multiple accounts from the same provider (e.g. multiple google accounts belonging to the same user), right?

**Comment by sguilhen** [comment]
Yeah, that will be a problem with the current constraint we have in the federated_identity table:
```
keycloak=# \d federated_identity 
                      Table "public.federated_identity"
       Column       |          Type          | Collation | Nullable | Default 
--------------------+------------------------+-----------+----------+---------
 identity_provider  | character varying(255) |           | not null | 
 realm_id           | character varying(36)  |           |          | 
 federated_user_id  | character varying(255) |           |          | 
 federated_username | character varying(255) |           |          | 
 token              | text                   |           |          | 
 user_id            | character varying(36)  |           | not null | 
Indexes:
    "constraint_40" PRIMARY KEY, btree (identity_provider, user_id)
    "idx_fedidentity_feduser" btree (federated_user_id)
    "idx_fedidentity_user" btree (user_id)
Foreign-key constraints:
    "fk404288b92ef007a6" FOREIGN KEY (user_id) REFERENCES user_entity(id)

```

The PK constraint prohibits a user to be linked to the same identity provider more than once.

@pedroigor I wonder if the PK shouldn't include also the `federated_user_id` - not sure if there's a broader reason to prevent linking multiple accounts from the same provider.

**Comment by sguilhen** [comment]
After discussing with @pedroigor we decided to add this as a enhancement. Having more than 1 account linked with the same provider is currently not supported and we think this could be achieved by relaxing the PK constraint, possibly including the `federated_user_id` in the primary key to allow for multiple accounts from the same provider.

Adding to the backlog, contributions are most welcome.

**Comment by d00rsfan** [comment]
May be `INSERT INTO ... ON CONFLICT ... constraint_40 ...  DO NOTHING` will be enough?

**Comment by ldeluigi** [comment]
Please, re-open this @sguilhen @lucyydotp

**Comment by sblommers** [comment]
Having this issue on 26.1.5

**Comment by dp-carrier** [comment]
Also experiencing this issue in 26.4.4 and it might be a blocker for our adoption of KeyCloak.

**Comment by boutros** [comment]
This problem also occurs when the federated user ID changes. 

We hit this regularly in production. To solve it an admin have to manually unlink the account so that it can be linked again.

**Comment by wschomburg** [comment]
We also have this issue in production with customers when the federated user ID changes. Since the user has a new ID, the link in our user object no longer matches. Removing the link in our keycloak solves the problem and on next login, the new link will be created. Don't think the link should be updated automatically without user interaction, but such guided user flow would be great. Something like "Your account is already connected to another remote identity, please reach out to your user administrators." or "Your account is already connected to another remote identity, you have to verify linking again." and then a new linking email will be sent, which will override the existing link.

**Comment by sguilhen** [comment]
I wonder now if just relaxing the PK constraint to allow multiple accounts from the same provider to be linked is enough. While it would allow linking all the different accounts from the same provider, scenarios like federated id changes will result in another account being linked while the old one (with the old id) never being removed unless the admin notices and removes the old link.

So there seems to me we have two distinct use cases - one where people want to allow the linking of multiple accounts if the user happens to have more than one in the provider, and another one where the federated id can change and people would like keycloak to somehow override the previous linked account. 

Dropping the constraint solves the first use case, but more changes would be needed to support the second one - most likely we would need some sort of confirmation when linking about what to do if we detect the user already has an account linked. Should we add a new identity or should we replace the previous one? And what if the user already has a couple of identities, which one should be replaced?

**Comment by wschomburg** [comment]
Maybe a good error message for the user would be a starting point for the second use case. Currently, the users will receive the generic identityProviderUnexpectedErrorMessage message. Would be great to have the possibility to configure a dedicated error message for the linking error. We could then point the user in the right direction to solve the error, something like "Your user is already linked to another account of your company's SSO, please contact your user administrator to fix the error." 
This will help the customer user help desk to solve the error.

**Comment by sguilhen** [comment]
Yeah, I would rather focus on displaying a more meaningful message than to relax the constraint and allow multiple accounts linked from the same provider. The reason is that several places in the codebase assume that a user has a single federated identity with a particular idp, and messing with that can lead to side-effects I cannot anticipate at this moment.

One way around this - not ideal - would be to create another idp with a different alias pointing to the same provider, and have the user link the account using the other idp.

**Comment by boutros** [comment]
I agree that a better error message is certainly a good improvement.
It would make it easier and quicker for help desk to diagnose and resolve the problem user is having.

**Comment by wschomburg** [comment]
Would be great if you could introduce an IDENTITY_PROVIDER_EXISTING_LINKING_ERROR message (just an example) for this issue and use this instead of the general IDENTITY_PROVIDER_UNEXPECTED_ERROR message when there is already a different link to the IDP stored in Keycloak. And catching the stack trace would also be great. A warning in the logs should be enough, as we identified the issue and handled it right. 
Changing the unexpected error to a known problem will help the user to address it.

**Comment by sguilhen** [comment]
@wschomburg I've opened https://github.com/keycloak/keycloak/issues/45322 to track the work around a dedicated message when the user is already linked to the IDP and sent a PR for that.

This issue is about providing a way to override a previous existing account - probably would need some configuration at the IDP level to handle this without breaking compatibility.

@pedroigor The issue has received a significant number of votes, so we need to discuss ways to fix it. For now we don't have bandwidth to pick this one up, but we could point the way for anyone willing to contribute a fix to allow overriding the existing federated identity.

**Comment by Oluwatobi-Mustapha** [comment]
Hi @sguilhen @pedroigor,

If you’re okay with it, I’d like to fix this issue.

I’m currently working on #47431, and while reading the related discussions on federated identity behavior, I noticed a connection in user state and impact with #35059: both involve users who already have federated identities linked and affect customer-facing sign-in/linking journeys. In #47431 this impacts IdP visibility on login; in #35059 this impacts client-initiated linking when a conflicting link already exists.

Permission to proceed?

**Comment by sguilhen** [comment]
> Hi [@sguilhen](https://github.com/sguilhen) [@pedroigor](https://github.com/pedroigor),
> 
> If you’re okay with it, I’d like to fix this issue.
> 
> I’m currently working on [#47431](https://github.com/keycloak/keycloak/issues/47431), and while reading the related discussions on federated identity behavior, I noticed a connection in user state and impact with [#35059](https://github.com/keycloak/keycloak/issues/35059): both involve users who already have federated identities linked and affect customer-facing sign-in/linking journeys. In [#47431](https://github.com/keycloak/keycloak/issues/47431) this impacts IdP visibility on login; in [#35059](https://github.com/keycloak/keycloak/issues/35059) this impacts client-initiated linking when a conflicting link already exists.
> 
> Permission to proceed?

Sure, go ahead! Thanks for picking it up!

**Comment by Oluwatobi-Mustapha** [comment]
Hi @sguilhen, appreciate you for assigning this.

Before I open a PR, I want to confirm scope for [#35059](https://github.com/keycloak/keycloak/issues/35059).

My understanding:
- Your work in [#45322](https://github.com/keycloak/keycloak/issues/45322) and [#45323](https://github.com/keycloak/keycloak/pull/45323) already handled the generic error-message part.
- So the fix for this issue [here](https://github.com/keycloak/keycloak/issues/35059#issuecomment-3730122520) should now focus on handling existing links cleanly during client-initiated linking, so it stays consistent with your scope clarification 
- I also confirmed from earlier discussion that relaxing PK alone may not solve all cases, and multiple areas assume one link per provider alias.

My proposed implementation:
- Keep the current invariant of one federated link per (user, provider alias).
- Do not relax DB PK / do not support multiple links for the same provider alias.
- Add a controlled “replace existing link” path for client-initiated linking when the authenticated user already has a link for that provider and the incoming broker identity differs.
- Preserve current behavior/message when replacement is not allowed.

Tests I plan to add:
1. With an existing link and replacement disabled, linking fails with the expected known message.
2. With an existing link and replacement enabled, the old link is replaced with the new federated identity, and linking succeeds.
3. Verify relevant broker events for the replacement path.
4. Cover both AIA `idp_link` flow and legacy client-initiated linking path.

Does this direction match what you want for this issue before I implement?

**Comment by sguilhen** [comment]
Hi @Oluwatobi-Mustapha  , sorry for the delayed response. Let me address the questions you have
> My understanding:
> 
> * Your work in [#45322](https://github.com/keycloak/keycloak/issues/45322) and [#45323](https://github.com/keycloak/keycloak/pull/45323) already handled the generic error-message part.
> * So the fix for this issue [here](https://github.com/keycloak/keycloak/issues/35059#issuecomment-3730122520) should now focus on handling existing links cleanly during client-initiated linking, so it stays consistent with your scope clarification
> * I also confirmed from earlier discussion that relaxing PK alone may not solve all cases, and multiple areas assume one link per provider alias.

Correct. Relaxing the PK won't be enough and might introduce unwanted side effects as many parts of codebase operate under the assumption that there is only one federated identity per IDP.

> 
> My proposed implementation:
> 
> * Keep the current invariant of one federated link per (user, provider alias).
> * Do not relax DB PK / do not support multiple links for the same provider alias.
> * Add a controlled “replace existing link” path for client-initiated linking when the authenticated user already has a link for that provider and the incoming broker identity differs.
> * Preserve current behavior/message when replacement is not allowed.

Looks good to me!

> 
> Tests I plan to add:
> 
> 1. With an existing link and replacement disabled, linking fails with the expected known message.
> 2. With an existing link and replacement enabled, the old link is replaced with the new federated identity, and linking succeeds.
> 3. Verify relevant broker events for the replacement path.
> 4. Cover both AIA `idp_link` flow and legacy client-initiated linking path.
> 
> Does this direction match what you want for this issue before I implement?

Yes, it does - your plan seems fine to me. Thanks again for picking this one up.

**Comment by Oluwatobi-Mustapha** [comment]
On it.

**Comment by pedroigor** [comment]
@Oluwatobi-Mustapha I'm wondering if this issue is related to https://github.com/keycloak/keycloak/issues/26201 and https://www.keycloak.org/docs/latest/server_admin/#_override_existing_broker_link. Can you please confirm it covers the same requirement?

**Comment by sguilhen** [comment]
I think it does - I didn't find #26201 when we were discussing this, and the approach we've decided to take was to add an option to the IDP to allow replacing the linked identity, which seems to be exactly what the new authenticator does.

**Comment by Oluwatobi-Mustapha** [comment]
Yes, @pedroigor. I think it covers the same requirement.

#26201 and the “Override existing broker link” authenticator handle replacing an existing broker link during the first broker login flow, with user confirmation.

#35059 is the same underlying case, but through client-initiated account linking, where the user is already authenticated. So PR the pr i created (#48176) extends that same replacement behavior to the client-initiated linking path while keeping the default behavior unchanged unless replacement is enabled.

**Comment by sguilhen** [comment]
Ok, so it turns out Keycloak already has a mechanism for overriding existing IDP links - `IdpConfirmOverrideLinkAuthenticator` (added in #26201), which handles this during the `first-broker-login` flow. This PR adds a second, independent mechanism for the `client-initiated linking` path.

While the two paths are complementary and cover different entry points, the underlying operation is the same - replacing a user's existing federated identity link for a given IDP. The concern is that these two mechanisms are completely independent with no connection between them.

This means an admin has to discover and configure two different mechanisms for the same logical operation, and can end up with inconsistent behavior - e.g., override works when the user logs in through the IDP but fails when they try client-initiated linking, or vice versa.

I think we should consider whether the IDP-level config introduced here (`allowLinkingWithExistingFederatedIdentity`) should also govern the `first-broker-login` path, so there's a single toggle for "this IDP allows replacing existing links." The authenticator could then check this flag rather than requiring a separate flow configuration. At minimum, if we keep both mechanisms, the interaction should be documented so admins understand the two configuration surfaces.

@pedroigor would you add anything?
