### ISSUE TITLE
Failed to start the server / Store IT (MySQL)

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#35071]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

In https://github.com/keycloak/keycloak/actions/runs/11892812274/job/33137433869 Store IT (mysql) failed with the following:

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 301.409 s <<< FAILURE! - in org.keycloak.test.tmp.PlaceHolderTest
Error:  org.keycloak.test.tmp.PlaceHolderTest.testHello  Time elapsed: 301.386 s  <<< ERROR!
java.lang.RuntimeException: Failed to start the server
	at org.keycloak.it.utils.RawKeycloakDistribution.run(RawKeycloakDistribution.java:184)
	at org.keycloak.test.framework.server.DistributionKeycloakTestServer.start(DistributionKeycloakTestServer.java:33)
	at org.keycloak.test.framework.server.AbstractKeycloakTestServerSupplier.getValue(AbstractKeycloakTestServerSupplier.java:72)
	at org.keycloak.test.framework.server.AbstractKeycloakTestServerSupplier.getValue(AbstractKeycloakTestServerSupplier.java:18)
	at org.keycloak.test.framework.injection.Registry.deployRequestedInstances(Registry.java:183)
	at org.keycloak.test.framework.injection.Registry.beforeEach(Registry.java:127)
	at org.keycloak.test.framework.KeycloakIntegrationTestExtension.beforeEach(KeycloakIntegrationTestExtension.java:29)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.keycloak.it.utils.RawKeycloakDistribution was not fulfilled within 1 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at org.keycloak.it.utils.RawKeycloakDistribution.threadDump(RawKeycloakDistribution.java:389)
	at org.keycloak.it.utils.RawKeycloakDistribution.waitForReadiness(RawKeycloakDistribution.java:336)
	at org.keycloak.it.utils.RawKeycloakDistribution.waitForReadiness(RawKeycloakDistribution.java:321)
	at org.keycloak.it.utils.RawKeycloakDistribution.run(RawKeycloakDistribution.java:174)
	... 8 more
	Suppressed: org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.keycloak.it.utils.RawKeycloakDistribution was not fulfilled within 1 minutes.
		at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
		at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
		at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
		at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
		at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
		at org.keycloak.it.utils.RawKeycloakDistribution.threadDump(RawKeycloakDistribution.java:389)
		at org.keycloak.it.utils.RawKeycloakDistribution.stop(RawKeycloakDistribution.java:222)
		at org.keycloak.it.utils.RawKeycloakDistribution.run(RawKeycloakDistribution.java:180)
		... 8 more
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Test passes

### Actual behavior

Test failed once

### How to Reproduce?

Unsure, as it has only happened once so far

**Comment by stianst** [comment]
Happened one time, but not again. Unsure why, but we'll look into it more if it happens again.
