### ISSUE TITLE
Flaky test: org.keycloak.testsuite.adapter.servlet.SAMLClockSkewAdapterTest#testTokenTimeIsValid

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#35088]
## org.keycloak.testsuite.adapter.servlet.SAMLClockSkewAdapterTest#testTokenTimeIsValid
[Keycloak CI - Base IT]() / [Pull Request #35057](https://github.com/keycloak/keycloak/pull/35057)

```
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "org.openqa.selenium.WebDriver.getPageSource()" is null
	at org.keycloak.testsuite.auth.page.WelcomePage.isPasswordSet(WelcomePage.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:143)
...
```

**Comment by pedroigor** [comment]
@mposolda Changing to core-clients, please let me me know if you think otherwise.
