### ISSUE TITLE
Flaky test: org.keycloak.testsuite.cluster.GroupInvalidationClusterTest#crudWithoutFailover

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#35172]
## org.keycloak.testsuite.cluster.GroupInvalidationClusterTest#crudWithoutFailover
[Keycloak CI - Clustering IT](https://github.com/keycloak/keycloak/actions/runs/11933375362/job/33260539562) / [Pull Request #35145](https://github.com/keycloak/keycloak/pull/35145)

```
jakarta.ws.rs.WebApplicationException: Create method returned status Forbidden (Code: 403); expected status: Created (201). Response body: {"error":"HTTP 403 Forbidden"}
	at org.keycloak.testsuite.admin.ApiUtil.getCreatedId(ApiUtil.java:63)
	at org.keycloak.testsuite.cluster.GroupInvalidationClusterTest.createEntity(GroupInvalidationClusterTest.java:66)
	at org.keycloak.testsuite.cluster.GroupInvalidationClusterTest.createEntity(GroupInvalidationClusterTest.java:28)
	at org.keycloak.testsuite.cluster.AbstractInvalidationClusterTest.createEntityOnCurrentFailNode(AbstractInvalidationClusterTest.java:109)
...
```

**Comment by vramik** [comment]
I've run 200 iterations of the whole test class without any failure. I'm putting the labels to see whether it's still the issue. Last failure seems to be 3 weeks old.
