### ISSUE TITLE
`kc.sh export` fails with PostgreSQL

### ISSUE THREAD

**Issue by nefarius** [keycloak/keycloak#35181]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Since updating to 25.0 (also tested in latest) my setup with PostgreSQL still works, however the `kc.sh export` commands do not with this database connection error:
```
2024-11-21 10:44:05,282 WARN  [io.agroal.pool] (JPA Startup Thread) Datasource '<default>': Driver does not support the provided URL: jdbc:postgresql://db-container:5432/keycloak
2024-11-21 10:44:05,307 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Driver does not support the provided URL: jdbc:postgresql://db-container:5432/keycloak
2024-11-21 10:44:05,308 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (JPA Startup Thread) SQL Error: 0, SQLState: null
2024-11-21 10:44:05,308 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (JPA Startup Thread) Driver does not support the provided URL: jdbc:postgresql://db-container:5432/keycloak
2024-11-21 10:44:05,309 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: org.hibernate.exception.GenericJDBCException: unable to obtain isolated JDBC connection [Driver does not support the provided URL: jdbc:postgresql://db-container:5432/keycloak] [n/a]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doTheWork(JtaIsolationDelegate.java:202)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.lambda$delegateWork$3(JtaIsolationDelegate.java:91)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInSuspendedTransaction(JtaIsolationDelegate.java:123)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.delegateWork(JtaIsolationDelegate.java:88)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:321)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:130)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:82)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:52)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
        at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
        at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:290)
        at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:72)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:73)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:154)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: Driver does not support the provided URL: jdbc:postgresql://db-container:5432/keycloak
        at io.agroal.pool.ConnectionFactory.connectionSetup(ConnectionFactory.java:241)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        ... 1 more
```

#### `Dockerfile`

```Dockerfile
ARG KEYCLOAK_VERSION=25.0


# Builds https://github.com/p2-inc/keycloak-events
FROM maven:3-amazoncorretto-21-debian-bookworm AS keycloak-events

RUN apt update && apt install git -y && \
    git clone https://github.com/p2-inc/keycloak-events.git && \
    cd keycloak-events && \
    mvn clean install -Dmaven.test.skip=true -Ddockerfile.skip -DdockerCompose.skip -Djib.skip


# Builds https://github.com/aerogear/keycloak-metrics-spi
FROM maven:3-amazoncorretto-21-debian-bookworm AS keycloak-metrics

RUN apt update && apt install git -y && \
    git clone https://github.com/aerogear/keycloak-metrics-spi.git && \
    cd keycloak-metrics-spi && \
    mvn clean install -Dmaven.test.skip=true -Ddockerfile.skip -DdockerCompose.skip -Djib.skip


# Build KC
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} AS builder

ENV TZ=Europe/Vienna
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange,hostname-v2
ENV KC_DB=postgres

COPY --from=keycloak-metrics /keycloak-metrics-spi/target/keycloak-metrics-spi-*.jar /opt/keycloak/providers/keycloak-metrics.jar
COPY --from=keycloak-events /keycloak-events/target/keycloak-events-*.jar /opt/keycloak/providers/keycloak-events.jar

# Pre-Build KC
RUN /opt/keycloak/bin/kc.sh build --features=token-exchange,admin-fine-grained-authz


# Final image
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

# Launch optimized instance
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--http-enabled=true", "--proxy-headers=forwarded", "--hostname-backchannel-dynamic=true","--optimized"]
```

#### `docker-compose.yml`

```yaml
  my-service-postgres:
    image: postgres:14
    container_name: my-service-postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      TZ: Europe/Vienna
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: blah

  my-service-keycloak:
    image: nefarius.azurecr.io/my-service-keycloak:25.0
    container_name: my-service-keycloak
    restart: unless-stopped
    volumes:
      - ./data/kc/exports:/data
    environment:
      KC_DB_URL: jdbc:postgresql://my-service-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: blah
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: blah
      KC_HOSTNAME: https://my-service-public-url/
      KC_HOSTNAME_ADMIN: https://my-service-public-url/
    depends_on:
      - my-service-postgres

```

### Version

25.0

### Regression

- [X] The issue is a regression

### Expected behavior

Exporting a realm [as per documentation](https://www.keycloak.org/server/importExport#_exporting_a_realm_to_a_directory) should work via PSQL DB.

### Actual behavior

`Datasource '<default>': Driver does not support the provided URL: jdbc:postgresql:...`

### How to Reproduce?

Configure and run KC 25.x as per docs using a PostgreSQL DB instance and try the `export` or `import` commands.

**Comment by mabartos** [comment]
@shawkins Could you please check it?

**Comment by shawkins** [comment]
From what image is the export command being run? It appears to me that it's being run from an image that does not have the database configured, so it's default to h2 instead.

If that's the case, this relates to #23805 which would make the error much more explicit.

**Comment by nefarius** [comment]
It's run via `docker exec` in the exact same instance that the working booted server is running in, with all the same DB ENVARs set.

**Comment by shawkins** [comment]
@nefarius run a show-config in the same way and see what the db is set to.

**Comment by nefarius** [comment]
> @nefarius run a show-config in the same way and see what the db is set to.

Here you go:

```bash
19:53:32-devserver:/apps/myservice-keycloak$ docker exec -it test-myservice-keycloak ./bin/kc.sh show-config
Current Mode: production
Current Configuration:
        kc.config.args =  show-config (SysPropConfigSource)
        kc.config.built =  true (SysPropConfigSource)
        kc.db =  dev-file (Persisted)
        kc.db-password =  ******* (ENV)
        kc.db-url =  jdbc:postgresql://test-myservice-postgres:5432/keycloak (ENV)
        kc.db-username =  keycloak (ENV)
        kc.hostname =  https://myservicemyservice.example.com/ (ENV)
        kc.hostname-admin =  https://myservicemyservice.example.com/ (ENV)
        kc.log-console-output =  default (classpath keycloak.conf)
        kc.provider.file.keycloak-events.jar.last-modified =  1732180748000 (Persisted)
        kc.provider.file.keycloak-metrics.jar.last-modified =  1732180710000 (Persisted)
        kc.run-in-container =  true (ENV)
        kc.spi-hostname-v2-hostname =  https://myservicemyservice.example.com/ (ENV)
        kc.spi-hostname-v2-hostname-admin =  https://myservicemyservice.example.com/ (ENV)
        kc.version =  26.0.5 (SysPropConfigSource)
```

**Comment by nefarius** [comment]
Weird that db url and db password is apparently set twice, just with a slightly different separator...

**Comment by nefarius** [comment]
It is fixed by one small Dockerfile adjustment:

``` Dockerfile
# Final image
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
ENV KC_DB=postgres
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

# Launch optimized instance
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--http-enabled=true", "--proxy-headers=forwarded", "--hostname-backchannel-dynamic=true","--optimized"]
```

This same setup has worked in PROD since version 20.x apparently with that ENVAR missing in either Dockerfile and compose file and `start` worked without complaining for some reason.

Oh well, sorry for that and thanks for your time and insights!

**Comment by shawkins** [comment]
Glad that it's working now.

> Weird that db url and db password is apparently set twice, just with a slightly different separator...

That is fixed in KC 26.
