### ISSUE TITLE
Double click on social provider link causes page has expired error

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#35278]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Double click on social provider link causes page has expired error. 

The server throws the following error:
```
ERROR [org.keycloak.services.resources.IdentityBrokerService] (executor-thread-13) unexpectedErrorHandlingRequestMessage: jakarta.ws.rs.WebApplicationException: HTTP 200 OK
	at org.keycloak.services.resources.IdentityBrokerService.parseSessionCode(IdentityBrokerService.java:1161)
	at org.keycloak.services.resources.IdentityBrokerService.performLogin(IdentityBrokerService.java:380)
	at org.keycloak.services.resources.IdentityBrokerService$quarkusrestinvoker$performLogin_639fa76256feb47da66621dcdd20f8de386404c5.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The second click is not possible or is not causing an error

### Actual behavior

The second click causes an error

### How to Reproduce?

1. Add a social provider with some random client ID/secret
2. Quickly double click on the social provider link on the login form
3. Page has expired error page is shown

**Comment by athenacykes** [comment]
> why would you double click on links?

Sometimes the network may be slow and user will be stuck at the login screen while waiting for the redirection. If, before the successful redirection, the user becomes impatient and clicked a second time, it will trigger this bug and it will look like it's Keycloak causing a login error.

I am the person who reported this issue via RH support. I discovered this behavior when we got reported that Keycloak is having issue while the actual root cause is that there is some network issue on some of our Android-based devices, causing the devices unable to connect to the Social Provider (timed out) and it appears as the device showing the login screen after the first click / touch. After the user clicks / touches a second time, it shows "Page has expired" and the redirection attempt is also cancelled.

Also we were observing logs like this since RH-SSO 7.4 and we opened RH case tickets before and have no luck finding the true root cause. It seems that the double click is the real root cause behind this kind of error logs.

Finally I think that the clicking and touching on a mobile device are different events - we may need to treat them both.

**Comment by sguilhen** [comment]
Interestingly if you setup a Keycloak OIDC Provider, double clicking works fine. Adding one of the social providers lead to the expired message.

**Comment by rmartinc** [comment]
> Interestingly if you setup a Keycloak OIDC Provider, double clicking works fine. Adding one of the social providers lead to the expired message.

I think the reason is just that social links are slower than internal localhost links. In my case with a saml idp and a oidc idp pointing to the same keycloak, but in another realm, I cannot double-click. But using a google provider I have the time to double-click, first click returns a redirect to google and, doing the redirect, the second click is received. Don't know, we can disable or similar the link after the first click but this is a PITA. The real problem is that the external IdP is slow, if the user becomes impatient I suppose the external idP should take several seconds to respond.

**Comment by sguilhen** [comment]
> > Interestingly if you setup a Keycloak OIDC Provider, double clicking works fine. Adding one of the social providers lead to the expired message.
> 
> I think the reason is just that social links are slower than internal localhost links. In my case with a saml idp and a oidc idp pointing to the same keycloak, but in another realm, I cannot double-click. But using a google provider I have the time to double-click, first click returns a redirect to google and, doing the redirect, the second click is received. Don't know, we can disable or similar the link after the first click but this is a PITA. The real problem is that the external IdP is slow, if the user becomes impatient I suppose the external idP should take several seconds to respond.

Yeah, I think this is exactly why we see differences.

The root cause seems to be `AuthenticationSessionModelParser#verifyCode`  finds out that code from authSession and code from the request don't match in the second click. Not sure how to best handle this at the backend without breaking necessary checks like this one.

@edewit is there anything we could do on the frontend - perhaps disable the link once it has been clicked, or ignoring subsequent clicks somehow?

**Comment by mposolda** [comment]
@sguilhen We had the similar issue before for the "Login link" as well many years ago. And it was fixed that by after the click, the button is disabled, so double-click is prevented. The related commit is here: https://github.com/keycloak/keycloak/commit/986540ab . Can we do something similar for social buttons as well?

Or even do something "generic" to make sure that after submitting the form (or clicking the link), then all other links on the page would become disabled. But not 100% sure if this is really needed (In theory, similar issue can happen if user clicks on "Login to google" link and then in 0.1 seconds later, he would click on the different link like "Login to Facebook" link if the initial redirect to Google did not took place yet. But this issue is maybe just theoretic, not sure...)

**Comment by mposolda** [comment]
@martin-kanis @sguilhen +1 . Maybe there is some possible fix on the server-side, but I am not sure. Also I afraid a bit of the risk of introducing security holes. For example checking for the single-time use of the code is by design and it is used to prevent reply attacks. I don't think we should relax on the requirement of preventing single-use just to handle some corner case scenarios like double-click the button.

@jonkoops Is it ok for you to reconsider and handle on the UI side or is it really bad practice to prevent double-click on the UI? When googling on "prevent doubleclick", I can see that people seem to often use JS for preventing this?

**Comment by jonkoops** [comment]
It is not a bad practice to disable double-clicking, my concern with the implementation as it was in #35509 was that it broke how links are supposed to work by handing the navigation entirely in JavaScript. Since that implementation removed the `href` attribute it would no longer be possible to open the link in a new tab, copy the link, and screen readers would also not be able to announce the link (see [the MDN article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#onclick_events) on this subject).

Normally, we'd add a [`disabled` attribute](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#enabling-and-disabling-form-controls:-the-disabled-attribute) to an element when it is clicked, preventing future navigations. This is what we do for buttons in some forms, as introduced by the aforementioned commit (986540ab). However, links do not have this attribute natively. This means that we'll have to work around it by removing the `href` when the link is clicked, which then disables any future navigation.

Unfortunately, when the `href` of a link is removed, it will no longer be announced by assistive technologies such as screen readers ([source](https://www.scottohara.me/blog/2021/05/28/disabled-links.html)). This means that we will have to use ARIA attributes to make it discoverable again as a link that is disabled. For example:

**Before click**
```html
<a href="/login/google">Sign in with Google</a>
```

**After click**
```html
<a role="link" aria-disabled="true">Sign in with Google</a>
```

Additionally, we'd also have to disable the button visually during navigation. It looks like PatternFly [can do this for us](https://v5-archive.patternfly.org/components/button/html/#aria-disabled).

If the implementation is done as outlined here, I would have no objections against it. But I still feel that we should be able to handle navigations like these without client side modifications. For example, a user might click the wrong button and quickly click another to correct themselves, which I consider a valid scenario.

**Comment by mposolda** [comment]
@jonkoops Thanks! I am not 100% sure if this is something, which we can handle on the server-side securely... So ATM my vote is to handle this on client side in a proper way you suggested in the last comment.

Regarding this point:

> For example, a user might click the wrong button and quickly click another to correct themselves, which I consider a valid scenario.

If user clicks on the `Login with Google`, the redirect to Google would be already in progress. If he clicks `Login with Facebook` in the meantime, it can break things similar way like double-click. In the comment above https://github.com/keycloak/keycloak/issues/35278#issuecomment-2739699492 , I suggested to handle this by actually disable all the social buttons (instead of just the clicked button). Not 100% sure if this is really needed as people likely see the issues most often during double-click...

**Comment by jonkoops** [comment]
We can start by just removing the `href` from the link that was clicked, and see if that covers it for now. The question is, can we perhaps apply this to all links on the page? Or, do we want to selectively apply this to only some links?

**Comment by martin-kanis** [comment]
Thanks for the discussion! Based on that I'm moving the issue back to UI team.

**Comment by ssilvert** [comment]
This is login, right?  The UI team doesn't handle login.
