### ISSUE TITLE
Events unaccessible in admin UI after update from keycloak 26.0.5 to 26.0.6

### ISSUE THREAD

**Issue by hgfi** [keycloak/keycloak#35294]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After upgrading keycloak from version 26.0.5 to 26.0.6, I cannot access the events tab in the admin UI, it show an error
![image](https://github.com/user-attachments/assets/12b96376-b78a-47f2-b897-be24d2c8a765)

The web browser console show this:
![image](https://github.com/user-attachments/assets/5f9cd593-4676-4927-9961-7d714be9c876)

And the keycloak debug logs show this:
`2024-11-25 13:33:03,641 DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-2) org.keycloak.events.jpa.AdminEventEntity{authIpAddress=XXX.XXX.XXX.XXX, realmId=local, authClientId=404eed8b-75be-4a66-bb23-a43563559ae0, resourcePath=users/5229b2e4-748e-4fba-be61-828e591d7304, error=null, representation={"id":"5229b2e4-748e-4fba-be61-828e591d7304","username":"test_user","firstName":"test","lastName":"test_user","email":"test@test.local","emailVerified":false,"attributes":{"att":["att1"]},"enabled":true,"federatedIdentities":[]}, authRealmId=efeccb14-c1a4-41e5-ba10-2dbdd43eea9d, authUserId=e36b6b53-5774-4a9c-a8ee-9c9cff4f098d, operationType=UPDATE, id=efddfb5c-31d8-420d-8698-e34704be342b, time=1727269149065, detailsJson=null, resourceType=USER}
2024-11-25 13:33:03,641 DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (executor-thread-2) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
2024-11-25 13:33:03,644 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-2) Initiating JDBC connection release from beforeTransactionCompletion
2024-11-25 13:33:03,645 FINE  [org.postgresql.jdbc.PgConnection] (executor-thread-2)   setAutoCommit = true
2024-11-25 13:33:03,645 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-2) Initiating JDBC connection release from afterTransaction
2024-11-25 13:33:03,645 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-2) JtaTransactionWrapper end. Request Context: HTTP GET /admin/realms/local/admin-events
2024-11-25 13:33:03,647 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Error response Bad Request: com.fasterxml.jackson.databind.JsonMappingException: argument "content" is null
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._wrapAsIOE(DefaultSerializerProvider.java:531)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:504)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1574)
        at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1275)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
        at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.FullyFeaturedServerJacksonMessageBodyWriter.writeResponse(FullyFeaturedServerJacksonMessageBodyWriter.java:80)
        at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:217)
        at org.jboss.resteasy.reactive.server.core.ServerSerialisers.invokeWriter(ServerSerialisers.java:185)
        at org.jboss.resteasy.reactive.server.core.serialization.FixedEntityWriter.write(FixedEntityWriter.java:28)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:34)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:5060)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3830)
        at org.keycloak.events.jpa.JpaEventStoreProvider.convertAdminEvent(JpaEventStoreProvider.java:226)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
        at org.keycloak.utils.ClosingStream.forEachOrdered(ClosingStream.java:134)
        at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:71)
        at com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:15)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
        ... 19 more
`

This happen on all realms, even master.
This doesn't happen in 26.0.5.

I've seen in the release notes that changes were made to keycloak events, maybe this is related:
https://www.keycloak.org/docs/26.0.6/release_notes/#admin-events-might-include-now-additional-details-about-the-context-when-the-event-is-fired

For now I've rolled back the database and keycloak instance to 26.0.5 since this is our user's test platform. I can to more test if needed.

### Version

26.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

Event tab is accessible.

### Actual behavior

Event tab shows "unknown_error".

### How to Reproduce?

- Install version 26.0.5, populate database with multiple realms and users.
- Generate some events
- Notice event tab is working
- Update to 26.0.6
- Event tab no longer working

### Anything else?

I've tested this on a new instance with only the master realm, the upgrade works and the event tab is accessible without errors.

**Comment by hgfi** [comment]
Duplicate of #35288 
Took too long to write this. Closing.
