### ISSUE TITLE
Unable to migrate from 25.0.6 to 26.0.0 or 26.0.6 : database not upgrading

### ISSUE THREAD

**Issue by ckaspro** [keycloak/keycloak#35533]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Upon upgrading keycloak, no database migration is happening. I am unable to force a manual upgrade via "--spi-connections-jpa-quarkus-migration-strategy=manual" as well: the same error occurrs, no sql- file is being created.

Before that update, the releases have been updated via the extra command "--spi-connections-jpa-legacy-migration-strategy=update" - which has been working until now. Also this statement does not work anymore.

The error is: _"Persistence unit 'keycloak-default' was configured to run with a database version of at least '12.0.0', but the actual version is '11.16.0'. Consider upgrading your database"_

The start- output is as follows:
`INFO  [org.keycloak.url.HostnameV2ProviderFactory] (main) If hostanme is specified, hostname-strict is effectively ignored
INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
INFO  [org.infinispan.CONTAINER] (Thread-5) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
WARN  [org.jgroups.stack.Configurator] (Thread-5) JGRP000014: ThreadPool.thread_dumps_threshold has been deprecated: ignored
INFO  [org.infinispan.CLUSTER] (Thread-5) ISPN000078: Starting JGroups channel `ISPN` with stack `udp`
INFO  [org.jgroups.JChannel] (Thread-5) local_addr: b22bc48d-79ec-4f9c-a82b-eed560de0623, name: keycloak3-43746
INFO  [org.jgroups.protocols.FD_SOCK2] (Thread-5) server listening on *.28891
INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
ERROR: Failed to start server in (production) mode
Error details:
jakarta.persistence.PersistenceException: [PersistenceUnit: keycloak-default] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:73)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:154)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Persistence unit 'keycloak-default' was configured to run with a database version of at least '12.0.0', but the actual version is '11.16.0'. Consider upgrading your database. Alternatively, rebuild your application with 'quarkus.datasource.db-version=11.16.0' (but this may disable some features and/or impact performance negatively).
	at io.quarkus.hibernate.orm.runtime.service.QuarkusRuntimeInitDialectFactory.checkActualDbVersion(QuarkusRuntimeInitDialectFactory.java:70)
	at io.quarkus.hibernate.orm.runtime.observers.QuarkusSessionFactoryObserverForDbVersionCheck.sessionFactoryCreated(QuarkusSessionFactoryObserverForDbVersionCheck.java:15)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:323)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:87)
	... 6 more
`

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The database should be upgraded by default, and keycloak should start with the newly provided version - or an update- sql script should be produced.

### Actual behavior

The keycloak startup is cancelled, and an error message thrown, stating that the database version does not match

### How to Reproduce?

As per [documentation](https://www.keycloak.org/docs/26.0.0/upgrading/#_install_new_version):

- download and verify new version
- copy over configs and providers
- correct permissions
- build with
  - JDK_HOME="/opt/java/jdk-21.0.2"
  - sudo -u keycloak  JAVA_HOME=$JDK_HOME /srv/keycloak_service/current/bin/kc.sh build --vault=file --features=scripts --db postgres
  - sudo -u keycloak  JAVA_HOME=$JDK_HOME /srv/keycloak_service/current/bin/kc.sh start --vault=file --features=scripts --db postgres

Hint: building/starting with only kc.sh build / kc.sh start fails as well, as well as trying to use root to start the server

**Comment by vramik** [comment]
Thank you @ckaspro for reporting the issue. 

From the description it seems there are no command line options specifying jdbc-url (or db-url-host) etc. How did you configure those? Also could you double check the version of postgres you use? From the log it seems that the version might be the issue.

~missing-info

**Comment by ckaspro** [comment]
Thank you, the attributes for database- host and credentials are located in the keycloak.conf - file.

The PostgreSQL- Database Server is 14.15 (psql --version: "psql (PostgreSQL) 14.15")

**Comment by vramik** [comment]
Thank you @ckaspro, I've tested it locally with following steps. 

- updated `keycloak.conf`: added `db-username`, `db-password`, `db-url` properties
- executed `./kc.sh build`
- executed `./kc.sh start --http-enabled=true --hostname-strict=false --db=postgres`

I have the `psql (PostgreSQL) 15.4 (Debian 15.4-1.pgdg120+1)` and server started successfully. Therefore I'm not unfortunately able to reproduce the issue. Could you please check the steps? Without additional info there is not much I can do.

**Comment by ckaspro** [comment]
Sorry, you are totally right, there are two database servers connected to the server :/

The one that keycloak is using is, as you mentioned, running 11.16.

I was under the impression, that "with a database version of ..." actually referred to the version of the keycloak database (of some internal versioning theme), not the version of the database server.

So this will be the issue then, I suppose - sorry for the confusion. Does it potentially make sense to put a mention of this dependency to the v26.0.x upgrade guides?

**Comment by vramik** [comment]
Happy to see it works for you after all.

> So this will be the issue then, I suppose - sorry for the confusion. Does it potentially make sense to put a mention of this dependency to the v26.0.x upgrade guides?

Not sure, what would you suggest to mention there? Feel free to open new `enhancement` issue where it can be discussed.

I'm closing this issue as it turned out not to be a bug. Thank you
