### ISSUE TITLE
Integrate support for Windows Integrated Security

### ISSUE THREAD

**Issue by Monolith-681** [keycloak/keycloak#35589]
### Description

Our team currently tries to get Windows Integrated Security working with Keycloak. We use an on-premise Setup and run Keycloak locally on the machine our software also runs on.

Integrated Security allows for authentication without the need to explicitly enter a user id and password.
This feature can be used to provide a database connection via JDBC string, which in our case we would like to do.

For reference, a standard jdbc string we currently use looks like this:

`jdbc:sqlserver://localhost:1433;database=exampleDatabase;TrustServerCertificate=True`.
Also we set the KC_DB_USERNAME and the KC_DB_PASSWORD options.

We would like to use integrated security like this
`jdbc:sqlserver://localhost:1433;database=exampleDatabase;TrustServerCertificate=True;IntegratedSecurity=True`.
Now we can omit the username and password options.

This works in general, the connection is established. However we run into an issue where the Liquibase configuration on startup tries to set a default schema and fails because the user used with Integrated Security is the dbo user, which uses the dbo schema. It is not possible to change the default schema on the dbo user, so we run into the following exception on Keycloak startup:

`ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Cannot use default schema name Keycloak on Microsoft SQL Server because the login schema of the current user (dbo) is different and MSSQL does not support setting the default schema per session.
        at liquibase.database.core.MSSQLDatabase.setDefaultSchemaName(MSSQLDatabase.java:144)
        at org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusLiquibaseConnectionProvider.getLiquibase(QuarkusLiquibaseConnectionProvider.java:123)
        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:69)
        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$2(LiquibaseDBLockProvider.java:93)
        at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:952)
        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:91)
        at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:141)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:257)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:379)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:256)
        at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:135)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.onStartupEvent(QuarkusKeycloakApplication.java:54)
        at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication_Observer_onStartupEvent_GNZ8m5QenZ9h9VNelo7awjUZFDE.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:108)
        at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:33)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:125)
        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)`

We use a different database schema for our Keycloak database.

Could it be possible to integrate Windows Integrated Security feature into the Keycloak codebase? Or maybe someone knows a workaround for this issue since we cannot configure another user (which is not how Integrated Security works) and we also cannot intervene with the startup process.

Thanks a lot for your suggestions and comments.

**Comment by DeepaThangaraj** [comment]
@Monolith-681 Have you solved the issue? I am in the situation where we need to use integrated windows authentication.

**Comment by Monolith-681** [comment]
@DeepaThangaraj unfortunately no. This topic is still dangling.
