### ISSUE TITLE
[Keycloak JavaScript CI] - Admin UI E2E -  Clients test

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#35654]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
  1) Clients test
       Client details - Client scopes subtab
         "after all" hook for "Should show initial items after filtering":
     Error: Could not find client scope

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Client details - Client sco...`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
      at fetchWithError (http://localhost:8080/__cypress/tests?p=cypress/e2e/clients_test.spec.ts:8865:11)
      at async Agent._requestWithParams (http://localhost:8080/__cypress/tests?p=cypress/e2e/clients_test.spec.ts:6134:17)
```

https://github.com/keycloak/keycloak/actions/runs/12165992827/job/33932359574#step:11:340
https://github.com/keycloak/keycloak/actions/runs/12161949108/job/33918077949#step:11:435

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by miquelsi** [comment]
Despite some fix done by @agagancarczyk, this test seems to fail still: https://github.com/keycloak/keycloak/actions/runs/12217264717/attempts/0
