### ISSUE TITLE
POST create client with id exceed 36 characters length response status 500 instead of 403

### ISSUE THREAD

**Issue by zapkub** [keycloak/keycloak#35723]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

POST create an invalid client id length cause keycloak return 500 response status code. This trigger a false alarm noise to monitoring system.

<img width="666" alt="image" src="https://github.com/user-attachments/assets/828b388e-a582-4595-b447-8bb401f51ae6">

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/881c7679-c5b0-47a3-97e4-08e60dadc089">

### Version

26.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

POST invalid client id length should response a proper status code (403 bad request)

### Actual behavior

POST invalid client id length response status code is 500 status code

### How to Reproduce?

setup keycloak realm and create a new client via admin API
```
set ID=theawesomeclientasdfsafsafasdfasdfsadf
set CLIENT_ID=my-test-cliewifjilsejf
curl -v -s -X POST ^
  -H "Authorization: Bearer %TOKEN%" ^
  -H "Content-Type: application/json" ^
  -d "{\"id\":\"%ID%\", \"clientId\":\"%CLIENT_ID%\",\"enabled\":true,\"protocol\":\"openid-connect\",\"publicClient\":false,\"clientAuthenticatorType\":\"client-secret\",\"redirectUris\":[\"http://localhost:3000/*\"]}" ^
  "%KEYCLOAK_URL%/admin/realms/%REALM%/clients"
  
## Response  
< HTTP/1.1 500 Internal Server Error
< content-length: 94
< Content-Type: application/json
< Referrer-Policy: no-referrer
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
<
{"error":"unknown_error","error_description":"For more on this error consult the server log."}  

```

### log from keycloak

```
2024-12-09 14:26:40,880 ERROR [org.hibernate.orm.jdbc.batch] (executor-thread-1) HHH100501: Exception executing batch [org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "ID CHARACTER VARYING(36)": "'theawesomeclientasdfsafsafasdfasdfsadf' (38)"; SQL statement:
insert into CLIENT (ALWAYS_DISPLAY_IN_CONSOLE,BASE_URL,BEARER_ONLY,CLIENT_AUTHENTICATOR_TYPE,CLIENT_ID,CONSENT_REQUIRED,DESCRIPTION,DIRECT_ACCESS_GRANTS_ENABLED,ENABLED,FRONTCHANNEL_LOGOUT,FULL_SCOPE_ALLOWED,IMPLICIT_FLOW_ENABLED,MANAGEMENT_URL,NAME,NODE_REREG_TIMEOUT,NOT_BEFORE,PROTOCOL,PUBLIC_CLIENT,REALM_ID,REGISTRATION_TOKEN,ROOT_URL,SECRET,SERVICE_ACCOUNTS_ENABLED,STANDARD_FLOW_ENABLED,SURROGATE_AUTH_REQUIRED,ID) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [22001-230]], SQL: insert into CLIENT (ALWAYS_DISPLAY_IN_CONSOLE,BASE_URL,BEARER_ONLY,CLIENT_AUTHENTICATOR_TYPE,CLIENT_ID,CONSENT_REQUIRED,DESCRIPTION,DIRECT_ACCESS_GRANTS_ENABLED,ENABLED,FRONTCHANNEL_LOGOUT,FULL_SCOPE_ALLOWED,IMPLICIT_FLOW_ENABLED,MANAGEMENT_URL,NAME,NODE_REREG_TIMEOUT,NOT_BEFORE,PROTOCOL,PUBLIC_CLIENT,REALM_ID,REGISTRATION_TOKEN,ROOT_URL,SECRET,SERVICE_ACCOUNTS_ENABLED,STANDARD_FLOW_ENABLED,SURROGATE_AUTH_REQUIRED,ID) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
2024-12-09 14:26:40,880 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-1) SQL Error: 22001, SQLState: 22001
2024-12-09 14:26:40,880 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-1) Value too long for column "ID CHARACTER VARYING(36)": "'theawesomeclientasdfsafsafasdfasdfsadf' (38)"; SQL statement:
insert into CLIENT (ALWAYS_DISPLAY_IN_CONSOLE,BASE_URL,BEARER_ONLY,CLIENT_AUTHENTICATOR_TYPE,CLIENT_ID,CONSENT_REQUIRED,DESCRIPTION,DIRECT_ACCESS_GRANTS_ENABLED,ENABLED,FRONTCHANNEL_LOGOUT,FULL_SCOPE_ALLOWED,IMPLICIT_FLOW_ENABLED,MANAGEMENT_URL,NAME,NODE_REREG_TIMEOUT,NOT_BEFORE,PROTOCOL,PUBLIC_CLIENT,REALM_ID,REGISTRATION_TOKEN,ROOT_URL,SECRET,SERVICE_ACCOUNTS_ENABLED,STANDARD_FLOW_ENABLED,SURROGATE_AUTH_REQUIRED,ID) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [22001-230]
2024-12-09 14:29:40,484 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.keycloak.models.ModelException: Database operation failed
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:109)
	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:68)
	at jdk.proxy2/jdk.proxy2.$Proxy63.flush(Unknown Source)
	at org.keycloak.models.jpa.JpaRealmProvider.lambda$addClientScopes$25(JpaRealmProvider.java:1133)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.keycloak.models.jpa.JpaRealmProvider.addClientScopes(JpaRealmProvider.java:1127)
	at org.keycloak.storage.ClientStorageManager.addClientScopes(ClientStorageManager.java:265)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.addClientScopes(RealmCacheSession.java:1487)
	at org.keycloak.models.jpa.ClientAdapter.addClientScopes(ClientAdapter.java:356)
	at org.keycloak.protocol.AbstractLoginProtocolFactory.lambda$addDefaultClientScopes$2(AbstractLoginProtocolFactory.java:88)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.keycloak.protocol.AbstractLoginProtocolFactory.addDefaultClientScopes(AbstractLoginProtocolFactory.java:92)
	at org.keycloak.protocol.AbstractLoginProtocolFactory.addDefaultClientScopes(AbstractLoginProtocolFactory.java:76)
	at org.keycloak.protocol.AbstractLoginProtocolFactory$1.onEvent(AbstractLoginProtocolFactory.java:51)
	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:87)
	at org.keycloak.models.jpa.ClientAdapter.setProtocol(ClientAdapter.java:266)
	at org.keycloak.models.utils.RepresentationToModel.lambda$updateProperty$4(RepresentationToModel.java:672)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.keycloak.models.utils.RepresentationToModel.updateClientProperties(RepresentationToModel.java:542)
	at org.keycloak.models.utils.RepresentationToModel.createClient(RepresentationToModel.java:338)
	at org.keycloak.models.utils.RepresentationToModel.createClient(RepresentationToModel.java:324)
	at org.keycloak.services.managers.ClientManager.createClient(ClientManager.java:83)
	at org.keycloak.services.resources.admin.ClientsResource.createClient(ClientsResource.java:190)
	at org.keycloak.services.resources.admin.ClientsResource$quarkusrestinvoker$createClient_1912e34f91860fbaabe8443c7133bbe9d618125d.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by rmartinc** [comment]
yes, this is because it exceeds the column size. This is a minor issue and help will be much appreciated to check the size of the ID. Note you have to include a test.
