### ISSUE TITLE
Optimized build with Provider Jar fails

### ISSUE THREAD

**Issue by Clashsoft** [keycloak/keycloak#35742]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I want to create an optimized build as suggested in https://www.keycloak.org/server/containers, and add a provider jar to it.

```dockerfile
ARG KEYCLOAK_VERSION=26.0.7
FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION AS builder

# Configure a database vendor
ENV KC_DB=postgres

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_HTTP_RELATIVE_PATH=/auth

WORKDIR /opt/keycloak
# https://github.com/p2-inc/keycloak-events
ADD https://repo1.maven.org/maven2/io/phasetwo/keycloak/keycloak-events/0.37/keycloak-events-0.37.jar /opt/keycloak/providers/keycloak-events-0.37.jar
RUN /opt/keycloak/bin/kc.sh build --verbose
```

This dockerfile fails with the error:

```
2.223 ERROR: Failed to run 'build' command.
2.223 Error details:
2.223 java.lang.NullPointerException
2.224   at java.base/java.util.Objects.requireNonNull(Objects.java:233)
2.224   at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:563)
2.224   at java.base/java.util.List.of(List.java:937)
2.224   at io.quarkus.paths.OpenContainerPathTree.getRoots(OpenContainerPathTree.java:96)
2.224   at io.quarkus.paths.SharedArchivePathTree$CallerOpenPathTree.getRoots(SharedArchivePathTree.java:142)
2.224   at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.toString(PathTreeClassPathElement.java:214)
2.224   at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3158)
2.225   at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3036)
2.225   at java.base/java.util.Formatter.format(Formatter.java:2791)
2.225   at java.base/java.util.Formatter.format(Formatter.java:2728)
2.225   at java.base/java.lang.String.format(String.java:4390)
2.225   at org.jboss.logmanager.ExtFormatter.formatMessagePrintf(ExtFormatter.java:144)
2.225   at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:91)
2.225   at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:832)
2.225   at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:227)
2.225   at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:90)
2.225   at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:58)
2.225   at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.close(QuarkusDelayedHandler.java:157)
2.226   at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:35)
2.226   at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:81)
2.226   at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
2.226   at picocli.CommandLine.access$1500(CommandLine.java:148)
2.226   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
2.226   at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
2.226   at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
2.226   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
2.226   at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
2.226   at picocli.CommandLine.execute(CommandLine.java:2174)
2.226   at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)
2.226   at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)
2.226   at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)
2.227   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2.227   at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2.227   at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
2.227   at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
```

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

No error and successful build.

### Actual behavior

Undescriptive error message that only shows when using --verbose.

### How to Reproduce?

See provided Dockerfile.

### Anything else?

https://www.keycloak.org/server/containers
https://github.com/p2-inc/keycloak-events

**Comment by shawkins** [comment]
Unfortunately the error that's displayed is simply masking the underlying issue, which is a file permission problem.

If you follwo the docs, you need to use something like:

ADD --chown=keycloak:keycloak --chmod=644 https://repo1.maven.org/maven2/io/phasetwo/keycloak/keycloak-events/0.37/keycloak-events-0.37.jar /opt/keycloak/providers/keycloak-events-0.37.jar

Not just a regular ADD.

**Comment by Clashsoft** [comment]
Thanks! Now at least this is documented here in case someone has the same problem.

**Comment by TheoCadoret** [comment]
*The narrator* : Someone had the same problem

Thanks

**Comment by eratolekov** [comment]
Hi 

Could you please explain how to fix this issue in OS Windows?
I'm debugging KC's extension locally. And have same issue.

Keycloak 26.0.6, 26.0.8

**Comment by shawkins** [comment]
@eratolekov this is a Docker related file permission problem https://github.com/keycloak/keycloak/issues/35742#issuecomment-2529445834

**Comment by eratolekov** [comment]
> @eratolekov this is a Docker related file permission problem [#35742 (comment)](https://github.com/keycloak/keycloak/issues/35742#issuecomment-2529445834)

Yes, it's clear to me.
But I have same issue at WIndows, standalone Keycloak.

```
C:\app\keycloak-26.0.6\bin>kc.bat build --verbose                                                                                                                                                                 Updating the configuration and installing your custom providers, if any. Please wait.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2025-01-14 10:03:38,034 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider
2025-01-14 10:03:56,305 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource io.smallrye.config.ConfigSourceContext$ConfigSourceContextConfigSource with ordinal 2147483647
2025-01-14 10:03:56,305 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource DefaultValuesConfigSource with ordinal -2147483648
2025-01-14 10:03:56,316 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource io.smallrye.config.ConfigSourceContext$ConfigSourceContextConfigSource with ordinal 2147483647
2025-01-14 10:03:56,316 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource DefaultValuesConfigSource with ordinal -2147483648
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PropertiesConfigSource[source=CliConfigSource] with ordinal 600
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource KcEnvVarConfigSource with ordinal 500
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource QuarkusProperties with ordinal 450
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource file:/C:/app/keycloak-26.0.6/bin/../conf/keycloak.conf with ordinal 450
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource SysPropConfigSource with ordinal 400
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource EnvConfigSource with ordinal 300
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PropertiesConfigSource[source=jar:file:///C:/app/keycloak-26.0.6/lib/app/keycloak.jar!/application.properties] with ordinal 250
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PropertiesConfigSource[source=jar:file:///C:/app/keycloak-26.0.6/lib/lib/main/org.keycloak.keycloak-quarkus-server-26.0.6.jar!/application.properties] with ordinal 250
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource PersistedConfigSource with ordinal 200
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource jar:file:///C:/app/keycloak-26.0.6/lib/lib/main/org.keycloak.keycloak-quarkus-server-26.0.6.jar!/META-INF/keycloak.conf with ordinal 150
2025-01-14 10:03:56,317 DEBUG [io.smallrye.config] (main) SRCFG01006: Loaded ConfigSource DefaultValuesConfigSource with ordinal -2147483648
2025-01-14 10:03:56,393 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-01-14 10:03:56,395 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-01-14 10:03:56,395 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-01-14 10:03:56,396 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.
2025-01-14 10:03:56,396 DEBUG [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Duplicated mappers for key 'kc.dir'. Used the first found.                                                                                                                                                                                                                                                                2025-01-14 10:03:56,446 TRACE [java.io.serialization] (main) Builtin factory: null -> new: null                                                                                                                                                                                                                                                                                                                                     2025-01-14 10:03:57,501 TRACE [java.io.serialization] (main) Builtin factory: null -> new: null                                                                                                                                                                                                                                                                                                                                     ERROR: Failed to run 'build' command.                                                                                                                                                                             
Error details:                                                                                                                                                                                                    
java.lang.NullPointerException                                                                                                                                                                                            
at java.base/java.util.Objects.requireNonNull(Objects.java:233)                                                                                                                                                   
at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:563)                                                                                                                          
at java.base/java.util.List.of(List.java:937)                                                                                                                                                                     
at io.quarkus.paths.OpenContainerPathTree.getRoots(OpenContainerPathTree.java:96)                                                                                                                                 
at io.quarkus.paths.SharedArchivePathTree$CallerOpenPathTree.getRoots(SharedArchivePathTree.java:142)                                                                                                             
at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.toString(PathTreeClassPathElement.java:214)                                                                                                         
at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3158)                                                                                                                                 
at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3036)                                                                                                                                       
at java.base/java.util.Formatter.format(Formatter.java:2791)                                                                                                                                                      
at java.base/java.util.Formatter.format(Formatter.java:2728)                                                                                                                                                      
at java.base/java.lang.String.format(String.java:4390)                                                                                                                                                            
at org.jboss.logmanager.ExtFormatter.formatMessagePrintf(ExtFormatter.java:144)                                                                                                                                   
at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:91)                                                                                                                                          
at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:832)                                                                                                                                   
at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:227)                                                                                                                    
at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:90)                                                                                                                          
at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:58)                                                                                                                                                 
at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.close(QuarkusDelayedHandler.java:157)                                                                                                                       
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:35)                                                                                                                                  
at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:81)                                                                                                                                              
at picocli.CommandLine.executeUserObject(CommandLine.java:2030)                                                                                                                                                   
at picocli.CommandLine.access$1500(CommandLine.java:148)                                                                                                                                                          
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)                                                                                                             
at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)                                                                                                                                                      
at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)                                                                                                                                                      
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)                                                                                                                                  
at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)                                                                                                                                                     
at picocli.CommandLine.execute(CommandLine.java:2174)                                                                                                                                                             
at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)                                                                                                                                                 
at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)                                                                                                                                         
at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)                                                                                                                                          
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)                                                                                                          
at java.base/java.lang.reflect.Method.invoke(Method.java:580)                                                                                                                                                     
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)                                                                                                                                 
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)                                                                                                                                                                                                                                                                                                                                            
```

OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)

**Comment by shawkins** [comment]
> But I have same issue at WIndows, standalone Keycloak.

If it's not due to a file permission problem, then open a new issue.

**Comment by domdomegg** [comment]
For others hitting this error on >=26.2.0 and using Docker, it might alternatively be: https://github.com/keycloak/keycloak/issues/38893
