### ISSUE TITLE
Unable to delete keycloak realm

### ISSUE THREAD

**Issue by alyssaruth** [keycloak/keycloak#35800]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

We're unable to delete a freshly created keycloak realm using the admin API. The issue is replicable in 23.0.7 and the latest keycloak, although the underlying error differs slightly.

I believe this relates to https://github.com/keycloak/keycloak/issues/19069

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

The realm should be deleted successfully

### Actual behavior

A 500 error is returned. On 23.0.7, the stack trace in keycloak is:

```
2024-12-10 15:15:14,827 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.keycloak.models.jpa.entities.RealmEntity.eventsListeners: could not initialize proxy - no Session
	at org.hibernate.collection.spi.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:635)
	at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218)
	at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615)
	at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136)
	at org.hibernate.collection.spi.PersistentSet.iterator(PersistentSet.java:169)
	at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1865)
	at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:414)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:508)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.keycloak.services.resources.admin.AdminEventBuilder.addListeners(AdminEventBuilder.java:135)
	at org.keycloak.services.resources.admin.AdminEventBuilder.<init>(AdminEventBuilder.java:63)
	at org.keycloak.services.resources.admin.AdminEventBuilder.<init>(AdminEventBuilder.java:56)
	at org.keycloak.services.resources.admin.RealmAdminResource.deleteRealm(RealmAdminResource.java:495)
	at org.keycloak.services.resources.admin.RealmAdminResource$quarkusrestinvoker$deleteRealm_56928e4b2fb2e8c48d4983df30b15118d69f3a51.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

In latest (26.0.7), the stack trace is:

```
2024-12-11 10:09:23,177 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.cache.infinispan.RealmCacheSession.getCache()" because "this.realmCache" is null
	at org.keycloak.models.cache.infinispan.idp.InfinispanIdentityProviderStorageProvider.<init>(InfinispanIdentityProviderStorageProvider.java:58)
	at org.keycloak.models.cache.infinispan.idp.InfinispanIdentityProviderStorageProviderFactory.create(InfinispanIdentityProviderStorageProviderFactory.java:31)
	at org.keycloak.models.cache.infinispan.idp.InfinispanIdentityProviderStorageProviderFactory.create(InfinispanIdentityProviderStorageProviderFactory.java:25)
	at org.keycloak.services.DefaultKeycloakSession.getOrCreateProvider(DefaultKeycloakSession.java:184)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:173)
	at org.keycloak.storage.datastore.DefaultDatastoreProvider.identityProviders(DefaultDatastoreProvider.java:218)
	at org.keycloak.services.DefaultKeycloakSession.identityProviders(DefaultKeycloakSession.java:304)
	at org.keycloak.models.jpa.JpaRealmProvider.removeRealm(JpaRealmProvider.java:207)
	at org.keycloak.services.managers.RealmManager.removeRealm(RealmManager.java:273)
	at org.keycloak.services.resources.admin.RealmAdminResource.deleteRealm(RealmAdminResource.java:490)
	at org.keycloak.services.resources.admin.RealmAdminResource$quarkusrestinvoker$deleteRealm_56928e4b2fb2e8c48d4983df30b15118d69f3a51.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### How to Reproduce?

Create a realm in keycloak, then attempt to destroy it via the admin API.

### Anything else?

We're creating the realm via terraform - see docs [here](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/realm). Our exact config is:

```
resource "keycloak_realm" "pkb" {
  realm                 = local.name
  enabled               = true
  display_name          = "PKB"
  display_name_html     = "<b>PKB</b>"
  login_theme           = "base"
  access_code_lifespan  = "1h"
  ssl_required          = "external"
  offline_session_idle_timeout = "120h" 
  security_defenses {
    brute_force_detection {
      permanent_lockout                 = false
      max_login_failures                = 10
      wait_increment_seconds            = 60
      quick_login_check_milli_seconds   = 1000 
      minimum_quick_login_wait_seconds  = 60 
      max_failure_wait_seconds          = 60*15 
      failure_reset_time_seconds        = 60*5 
    }
  }
}
```

We see the deletion error when trying to run `terraform destroy` - but under the hood all this is doing is calling the API to delete the realm.

**Comment by alyssaruth** [comment]
This can be replicated on the latest release, that's already in my issue.

**Comment by utamas** [comment]
Can be reproduced when keycloak is started with `--spi-realm-cache-default-enabled=false`. Deleting any created realm fails even on UI.
