### ISSUE TITLE
Regression Mysql 8 support as the upgrade script do not use temporary table 

### ISSUE THREAD

**Issue by etchepar** [keycloak/keycloak#35827]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

The fix of the issue https://github.com/keycloak/keycloak/issues/30631 in KC 26.0.7 broke the KC deployment on Mysql 8.0 with replication enabled.

Deploying KC 26.0.7 on a Mysql 8 replicated cluster fails with the error : 

```
     Reason: liquibase.exception.DatabaseException: The table does not comply with the requirements by an external plugin. [Failed SQL: (3098) DELETE FROM `adminop-db-rec`.USER_CONSENT WHERE ID IN (SELECT ID FROM TEMP_USER_CONSENT_IDS)]
```

As the table TEMP_USER_CONSENT_IDS is no more temporary, the above command failed.

We had to revert to KC 26.0.6

### Version

26.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

We can upgrade or install KC 26 with mysql 8

### Actual behavior

Upgrade to KC 26.0.7 is broken. 

### How to Reproduce?

With a KC 24 deployement using a Mysql 8 cluster with replicaton enabled
Upgrade to KC 26.0.7

On startup the installation fails and a TEMP_USER_CONSENT_IDS persists in the database

**Comment by jonkoops** [comment]
@mike-pt FYI

**Comment by mike-pt** [comment]
There are no other uses of temporary but also the error is:

> [Failed SQL: (3098) DELETE FROM adminop-db-rec.USER_CONSENT WHERE ID IN (SELECT ID FROM TEMP_USER_CONSENT_IDS)]

I don't see where KC is doing this migration script... the only reference to TEMP_USER_CONSENT_IDS is in the v25 upgrade scripts, these are not being dropped in v26 scripts so I have no idea where that query comes from... @jonkoops  any clue? 

Also, Error 3098 happens when a table (temporary or not) does not meet requirements like having a primary key or unique key and is involved in operations where such keys are mandatory (e.g., row-based replication). The fact that the table is temporary or not should not matter right?

It seems like something is imposing constraints like requiring a primary key, guessing this is indeed the replication, or a plugin.

What is the MySQL server/cluster in use here?

**Comment by etchepar** [comment]
I Will provide the cluster detailed information in a following post.

In our situation, we are migrating from a KC 22.X to KC 26+, so we use the 25 scripts

In our first test environnement, we deployed KC image based on 26.0.6 image and encountered no problem.
As the script used temporary table that do not need primary key.


in KC 26.0.7, the upgrade script change the 25 migration script removing the "temporary" 
https://github.com/keycloak/keycloak/commit/640f4190e090beade6f4c94d2db4576a259c3faf#diff-a493f4b1ef5c3b5d385b63730a00d056a4fb3cf510b7206f40ce471ce6c38402R38


So when we upgraded a new environment  from KC 22.X  to 22.0.7, the database migration stopped on the migration to 25 script.
This is typically where you stated the reference of the temporary table 

> There are no other uses of temporary but also the error is:
> 
> > [Failed SQL: (3098) DELETE FROM adminop-db-rec.USER_CONSENT WHERE ID IN (SELECT ID FROM TEMP_USER_CONSENT_IDS)]
> 
> I don't see where KC is doing this migration script... the only reference to TEMP_USER_CONSENT_IDS is in the v25 upgrade scripts, these are not being dropped in v26 scripts so I have no idea where that query comes from... @jonkoops any clue?
> 
> Also, Error 3098 happens when a table (temporary or not) does not meet requirements like having a primary key or unique key and is involved in operations where such keys are mandatory (e.g., row-based replication). The fact that the table is temporary or not should not matter right?
> 
> It seems like something is imposing constraints like requiring a primary key, guessing this is indeed the replication, or a plugin.
> 
> What is the MySQL server/cluster in use here?

**Comment by etchepar** [comment]
Here are the details of our Mysql cluster :

Server version: 8.0.35-commercial MySQL Enterprise Server - Commercial
##############################
Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SHOW PLUGINS\G
.....
*************************** 50. row ***************************
   Name: group_replication
 Status: ACTIVE
   Type: GROUP REPLICATION
Library: group_replication.so
License: PROPRIETARY
*************************** 51. row ***************************
...
#################################

**Comment by mike-pt** [comment]
> I will provide the cluster detailed information in a following post.
> 
> In our situation, we are migrating from a KC 22.X to KC 26+, so we use the 25 scripts
> 
> In our first test environnement, we deployed KC image based on 26.0.6 image and encountered no problem.
> As the script used temporary table that do not need primary key.
> 
> 
> in KC 26.0.7, the upgrade script change the 25 migration script removing the "temporary" 
> https://github.com/keycloak/keycloak/commit/640f4190e090beade6f4c94d2db4576a259c3faf#diff-a493f4b1ef5c3b5d385b63730a00d056a4fb3cf510b7206f40ce471ce6c38402R38
> ![image](https://github.com/user-attachments/assets/62a0bbcc-f4a7-4805-974b-f49837bda38d)
> 
> 
> So when we upgraded a new environment  from KC 22.X  to 22.0.7, the database migration stopped on the migration to 25 script.
> This is typically where you stated the reference of the temporary table 
> 
> > There are no other uses of temporary but also the error is:
> > 
> > > [Failed SQL: (3098) DELETE FROM adminop-db-rec.USER_CONSENT WHERE ID IN (SELECT ID FROM TEMP_USER_CONSENT_IDS)]
> > 
> > I don't see where KC is doing this migration script... the only reference to TEMP_USER_CONSENT_IDS is in the v25 upgrade scripts, these are not being dropped in v26 scripts so I have no idea where that query comes from... @jonkoops any clue?
> > 
> > Also, Error 3098 happens when a table (temporary or not) does not meet requirements like having a primary key or unique key and is involved in operations where such keys are mandatory (e.g., row-based replication). The fact that the table is temporary or not should not matter right?
> > 
> > It seems like something is imposing constraints like requiring a primary key, guessing this is indeed the replication, or a plugin.
> > 
> > What is the MySQL server/cluster in use here?
> 
> 

Create temporary fails in same cases (mostly Google Cloud SQL AFAIK)

This was removed to use simple create.

It's simple creating and droping the tables.

Whatever is failing it's very unlikely its because it's not using temporary clause, otherwise other scripts that create and drop tables fail.

The MySQL error code is suggestive that there is indeed something your system does not like, this tables don't have primary keys I.E. I found plenty cases where that's the actual problem.

It's possible, I suppose, that some policy in the cluster/plug-in only enforces the primary key on normal tables but not temporary.... But I would need more info on the system to look that up.

**Comment by mike-pt** [comment]
OK I see it's Oracle enterprise version.

It does seem that group replication enforces primary keys form what I could find in docs.

However temporary tables are not part of replication so that aligns with what I was thinking.

The quick work around is to use:
```
replicate-ignore-table = database_name.table_name
```


And ignore this tables in replication.

Ofc the code could simply add a primary key too. Or it could be smarter and try to detect the system I suppose, but Java is not my playground and this would be tricky for me.

I need to re-test but someone posted on my original GHI that temp tables are not a problem with replication in Gcloud SQL 8.4, maybe even recent versions of 8.0.

If this is the case perhaps it's simple to do it only if it's 5.7.

Either way that flag I posted would be a quick work around, can you try it out?

**Comment by etchepar** [comment]
Hello,

As stated, we use a MySql 8 with replication groups.
The migration script for KC 25 shipped in KC 26.07 fails.



> OK I see it's Oracle enterprise version.
> 
> It does seem that group replication enforces primary keys form what I could find in docs.
> 
> However temporary tables are not part of replication so that aligns with what I was thinking.
> 
Yes, thus the KC 25 migration script shipped in KC 26.0.6 using temporary tables works 
But the KC 25 migration script shipped in KC 26.0.7 with standard tables but no primary keys fails


> The quick work around is to use:
> 
> ```
> replicate-ignore-table = database_name.table_name
> ```
> 
> And ignore this tables in replication.
I will ask our DBA if they can test this configuration.
But we have started a two phase deployement KC 26.0.5 => KC 26.0.6

> 
> Ofc the code could simply add a primary key too. Or it could be smarter and try to detect the system I suppose, but Java is not my playground and this would be tricky for me.
If liquidbase is smart enough, it would be possible to detect the mysql version.

To my mind I was about to propose the first proposal : 
=> use a plain old table with a primary key

> 
> I need to re-test but someone posted on my original GHI that temp tables are not a problem with replication in Gcloud SQL 8.4, maybe even recent versions of 8.0.
> 
I confirm, temp tables are not a problem in our case

> If this is the case perhaps it's simple to do it only if it's 5.7.
> 
> Either way that flag I posted would be a quick work around, can you try it out?

**Comment by etchepar** [comment]
> > The quick work around is to use:
> > ```
> > replicate-ignore-table = database_name.table_name
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And ignore this tables in replication.
> 
> I will ask our DBA if they can test this configuration. But we have started a two phase deployement KC 26.0.5 => KC 26.0.6
> 

After an exchange with our DBA, this configuration is not an option as it does not work a MySql instance configured for Group Replication

![image](https://github.com/user-attachments/assets/b37f67c3-de69-41c8-a913-d14f7d5c79d2)

https://dev.mysql.com/doc/refman/8.4/en/change-replication-filter.html

**Comment by etchepar** [comment]
In our case, we have a workaround for this time but the problem will occurs for other projects that will start directly with a 8.4 replicated mySql instance.

With some time, I can propose a PR to test the database version in the java code using the getDatabaseProductVersion() method
see : https://contribute.liquibase.com/code/api/database-database/#iscorrectdatabaseimplementation

Or the other proposed approach : add a primary key to those "temporary" tables temporary as they are deleted in the end.

**Comment by mike-pt** [comment]
I'm currently on vacation but the simplest fix seems to be to create the
tables with primary keys, since they aren't really temp tables anymore.

If I have some time next week I'll file a PR

**Comment by mposolda** [comment]
Adding to core-iam queue due the fact that it seems to be caused by https://github.com/keycloak/keycloak/issues/30631 .

**Comment by mike-pt** [comment]
I proposed a PR where I add a primary key, I'm not sure if this is the best approach but sure is the more simple way to deal with it.

@etchepar I don't think getDBversion will work here, bc the original issue I was seeing in gcloud affects 8.x or at least it was, I can't seem to repo it in the latest 8.4 version, but it does still happen on 5.7 (google still offers support for this though they wont for long as they don't allow new installs anymore).

Its funny because this took a while and we are finally upgrading all to 8.4.. though it will take a bit to get to prod, for now just test envs, but soon I wont even need that other fix as from my tests it works fine.

Anyway this should work in any case because its just a normal table with a primary key.

**Comment by mike-pt** [comment]
@pedroigor would need others to test tbh, and I'm now getting different results from before, but when I last tested it was 5.7 and a earlier build of 8.x I think they have fixed it in recent versions, 8.4 works fine with the TEMP tables, so it seems at least in GCP the fix is only required in 5.7 WITH REPLICATION ENABLED. A recent 8.0 (i.e 8.0.31 ) seems to also work fine. I was testing by mimicking what the scripts were previously doing.

That said others had reported issues in my original ticket so it might affect others.

In any case per this ticket if we don't use TEMPORARY TABLES but also not set primary key 8.0.35-commercial MySQL Enterprise Server - Commercial doesn't like it either.

So it seems to me the best compromise is to rely on regular tables with primary key, but I reserve best judgment to you guys of course.

**Comment by mike-pt** [comment]
actually in 26.0.7 I'm seeing:
```
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Persistence unit 'keycloak-default' was configured to run with a database version of at least '8.0.0', but the actual version is '5.7.0'. Consider upgrading your database. Alternatively, rebuild your application with 'quarkus.datasource.db-version=5.7.0' (but this may disable some features and/or impact performance negatively).
	at io.quarkus.hibernate.orm.runtime.service.QuarkusRuntimeInitDialectFactory.checkActualDbVersion(QuarkusRuntimeInitDialectFactory.java:70)
	at io.quarkus.hibernate.orm.runtime.observers.QuarkusSessionFactoryObserverForDbVersionCheck.sessionFactoryCreated(QuarkusSessionFactoryObserverForDbVersionCheck.java:15)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:323)
	at io.quar
```
	
So I can't retest the 5.7 scenario on latest version. It also makes me think that since I'm no longer seeing the issue with TEMPORARY in 8.x in GCP then perhaps the best course is to reverse my first PR.

On a related note I think the release notes (https://www.keycloak.org/docs/latest/release_notes/index.html) should state mysql5.7 is no longer supported, I know there is the db versions docs but this is for tested versions not necessarily what is/is not supported, and until 25 mysql 5.7 was in fact working.
