### ISSUE TITLE
IDPs can not be found anymore by "Issuer" value when exchanging tokens

### ISSUE THREAD

**Issue by valentinvachev** [keycloak/keycloak#36053]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

We have several introduced Identity Providers (such as Azure, Google etc). By using "subject_issuer" in the request body params the Identity Provider was found by checking its values under "OpenID Connect settings ->  Issuer".  With Keycloak version 26 this is not possible because if the Identity Provider is not found by "Alias" it will not go and check if it can be found by "Issuer" values. This seems like a bug to me and it was introduced here: https://github.com/keycloak/keycloak/commit/aeb1951abad784bb51a0f2bc1f77fed7d33e14b4#diff-e50012fcfff1448c1d9614fd769d6332e1fe6c4949af2efb50b71429851293d3R522

In locateExchangeExternalTokenByAlias method if Identity Provider is not found by Alias, idpModel variable will be null and IdentityBrokerService.getIdentityProviderFactory throws Nullpointer. 

Respectively, the option to check also by Identity Provider Issuer values is never reached. 

### Version

26

### Regression

- [X] The issue is a regression

### Expected behavior

Identity Providers should be found not only by Alias by also by Issuer values. 

### Actual behavior

Identity Providers option to search by Issuer values is never reached. 

### How to Reproduce?

Token exchange for Identity Provider

**Comment by pedroigor** [comment]
@valentinvachev Can you please check if this change fixes your issue https://github.com/keycloak/keycloak/pull/36045?

I think they are related even though they relate to different areas.

**Comment by cernya** [comment]
@pedroigor I don't think this is related.

**Comment by cernya** [comment]
### How to reproduce:

1. Create new Identity-Provider:
	alias = test-idp
	issuer = test-issuer
	
2. Try to do token-exchange:
	**Request:**
```
	POST .../auth/realms/test_realm/protocol/openid-connect/token
	Content-Type: application/x-www-form-urlencoded

	client_id=...
	&client_secret=...
	&grant_type=urn:ietf:params:oauth:grant-type:token-exchange
	&subject_token_type=urn:ietf:params:oauth:token-type:access_token
	&subject_token=test_token
	&subject_issuer=test-issuer
```

	**Response:**
```
	HTTP/1.1 500 Internal Server Error
	Content-Type: application/json

	{
		"error": "unknown_error",
		"error_description": "For more on this error consult the server log."
	}
```
 
	**Log:**
```
	Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.IdentityProviderModel.getProviderId()" because "model" is null
		       at org.keycloak.services.resources.IdentityBrokerService.lambda$getIdentityProviderFactory$4(IdentityBrokerService.java:1334)
		       at java.base/…78)
		       ...
		       at org.keycloak.services.resources.IdentityBrokerService.getIdentityProviderFactory(IdentityBrokerService.java:1336)
		       at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.locateExchangeExternalTokenByAlias(DefaultTokenExchangeProvider.java:699)
		       at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchangeExternalToken(DefaultTokenExchangeProvider.java:521)
		       at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.tokenExchange(DefaultTokenExchangeProvider.java:164)
		       at org.keycloak.protocol.oidc.DefaultTokenExchangeProvider.exchange(DefaultTokenExchangeProvider.java:130)
```

**Comment by valentinvachev** [comment]
@pedroigor I confirm the case is how @cernya described it and the case which you are referring to does not seem to be solution of the issue

**Comment by pedroigor** [comment]
@valentinvachev Would you mind checking https://github.com/keycloak/keycloak/pull/36243? Added a test to cover exchanges using the issuer.
