### ISSUE TITLE
Keycloak adapter for WildFly/EAP doesn't report inaccessible key in keystore and throws NullPointerException instead

### ISSUE THREAD

**Issue by honza-kasik** [keycloak/keycloak#8837]
### Describe the bug

With following configuration:

```xml
<Keys>
     <Key signing="true" encryption="true">
          <KeyStore password="password" file="/etc/sso-saml-secret-volume/keystore.jks">
               <PrivateKey alias="xpaas.ca" password="wrongpassword"/>
               <Certificate alias="xpaas.ca"/>
          </KeyStore>
     </Key>
</Keys>
```

when `password` is wrong password or `alias` is not found in the keystore, adapter throws following exception:

```
    09:07:53,949 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /vanilla/profile.jsp: java.lang.RuntimeException: Could not create authentication request.
            at org.keycloak.keycloak-saml-adapter-core@9.0.15.redhat-00002//org.keycloak.adapters.saml.AbstractInitiateLogin.challenge(AbstractInitiateLogin.java:64)
            at org.keycloak.keycloak-saml-undertow-adapter@9.0.15.redhat-00002//org.keycloak.adapters.saml.undertow.AbstractSamlAuthMech.sendChallenge(AbstractSamlAuthMech.java:65)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.impl.SecurityContextImpl$ChallengeSender.transition(SecurityContextImpl.java:301)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.impl.SecurityContextImpl$ChallengeSender.transition(SecurityContextImpl.java:319)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.impl.SecurityContextImpl$ChallengeSender.access$300(SecurityContextImpl.java:284)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.impl.SecurityContextImpl.sendChallenges(SecurityContextImpl.java:130)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:102)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:107)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
            at org.wildfly.extension.undertow@7.4.2.GA-redhat-00002//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
            at org.wildfly.extension.undertow@7.4.2.GA-redhat-00002//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.handlers.MetricsHandler.handleRequest(MetricsHandler.java:64)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.core.MetricsChainHandler.handleRequest(MetricsChainHandler.java:59)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
            at org.wildfly.extension.undertow@7.4.2.GA-redhat-00002//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
            at org.wildfly.extension.undertow@7.4.2.GA-redhat-00002//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
            at org.wildfly.extension.undertow@7.4.2.GA-redhat-00002//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
            at org.wildfly.extension.undertow@7.4.2.GA-redhat-00002//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
            at org.wildfly.extension.undertow@7.4.2.GA-redhat-00002//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
            at io.undertow.servlet@2.2.12.Final-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
            at io.undertow.core@2.2.12.Final-redhat-00001//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
            at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
            at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
            at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
            at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
            at org.jboss.xnio@3.8.4.Final-redhat-00001//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
            at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: java.lang.NullPointerException: signingKey cannot be null
            at java.xml.crypto/javax.xml.crypto.dsig.dom.DOMSignContext.<init>(DOMSignContext.java:100)
            at org.keycloak.keycloak-saml-core@9.0.15.redhat-00002//org.keycloak.saml.processing.core.util.XMLSignatureUtil.sign(XMLSignatureUtil.java:412)
            at org.keycloak.keycloak-saml-core@9.0.15.redhat-00002//org.keycloak.saml.processing.api.saml.v2.sig.SAML2Signature.sign(SAML2Signature.java:142)
            at org.keycloak.keycloak-saml-core@9.0.15.redhat-00002//org.keycloak.saml.processing.api.saml.v2.sig.SAML2Signature.signSAMLDocument(SAML2Signature.java:159)
            at org.keycloak.keycloak-saml-core@9.0.15.redhat-00002//org.keycloak.saml.BaseSAML2BindingBuilder.signDocument(BaseSAML2BindingBuilder.java:277)
            at org.keycloak.keycloak-saml-core@9.0.15.redhat-00002//org.keycloak.saml.BaseSAML2BindingBuilder$BasePostBindingBuilder.<init>(BaseSAML2BindingBuilder.java:154)
            at org.keycloak.keycloak-saml-core@9.0.15.redhat-00002//org.keycloak.saml.BaseSAML2BindingBuilder.postBinding(BaseSAML2BindingBuilder.java:219)
            at org.keycloak.keycloak-saml-adapter-core@9.0.15.redhat-00002//org.keycloak.adapters.saml.SamlUtil.sendSaml(SamlUtil.java:45)
            at org.keycloak.keycloak-saml-adapter-core@9.0.15.redhat-00002//org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler$3.sendAuthnRequest(AbstractSamlAuthenticationHandler.java:622)
            at org.keycloak.keycloak-saml-adapter-core@9.0.15.redhat-00002//org.keycloak.adapters.saml.AbstractInitiateLogin.challenge(AbstractInitiateLogin.java:61)
            ... 49 more

```

### Version

Red Hat SSO 7.4.9

### Expected behavior

Underlying issue is not ignored and message that alias cannot be retrieved from the keystore is printed.

### Actual behavior

NPE is thrown. This NPE doesn't describe the root cause. Only outcome. The real root cause is inability to retrieve alias from the keystore and this fact stays hidden from the user.

### How to Reproduce?

Use Java kesytore in adapter configuration:

```xml
<Keys>
     <Key signing="true" encryption="true">
          <KeyStore password="password" file="/etc/sso-saml-secret-volume/keystore.jks">
               <PrivateKey alias="xpaas.ca" password="wrongpassword"/>
               <Certificate alias="xpaas.ca"/>
          </KeyStore>
     </Key>
</Keys>
```

set `password` to wrong valueor `alias` to one that cannot be found in the keystore and make a SAML request with adapter configured like this.

**Comment by douglaspalmer** [comment]
@honza-kasik I tried to write a test for this issue and get a deployment error stating "java.lang.RuntimeException: java.security.UnrecoverableKeyException: Cannot recover key". Do you not get this error at deployment? Do you have a simple example that can be used to reproduce this?

**Comment by abstractj** [comment]
Hi,

As this is an open-source community project, we cannot fill your request. I would suggest you to contact the Red Hat Single Sign-On (https://access.redhat.com/products/red-hat-single-sign-on), support from Red Hat.
