### ISSUE TITLE
ResteasyClient in Keycloak Admin Client uses default jvm ca certs in /etc/pki/java/cacerts and not user defined keycloak properties

### ISSUE THREAD

**Issue by Aleson95** [keycloak/keycloak#8853]
### Describe the bug

The ResteasyClient in Keycloak Admin Client dependencies does not use the user defined keycloak properties for truststore details:
keycloak.truststore=/path/toTrustStore
keycloak.truststore-password=secret

Instead it uses the default jvm ca certs in /etc/pki/java/cacerts so then it throw exception when performing any admin client api operation.

javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:321) 
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:494) 
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152) 
...

### Version

13.0.1

### Expected behavior

The ResteasyClient in Keycloak Admin Client dependency should use the user defined keycloak properties for truststore so it does not need to define ResteasyClient implementation to use specific truststore.

### Actual behavior

The ResteasyClient in Keycloak Admin Client dependencies uses the default jvm ca certs in /etc/pki/java/cacerts, even though the properties already been set.

### How to Reproduce?

1. Install Keycloak v13.0.1 on a server enable https with self sign cert
2. Create and configure new realm 
3. Perform any Keycloak Admin Client API operation on previous installed Keycloak.

**Comment by stianst** [comment]
The admin client library doesn't use keycloak.properties for anything, and never has. So this is not a bug. Changed to an enhancement request.

**Comment by shawkins** [comment]
Marking as not planned. Mixing the server and admin client configuration is not something we are looking to do.
