### ISSUE TITLE
User profile field with scope restrictions breaks configuration import on NullPointerException

### ISSUE THREAD

**Issue by regilero** [keycloak/keycloak#8872]
### Describe the bug

Using the declarative_user_profile test module I experimented NullPointerException on full realm configuration import if I use the "Required scopes" or "Enabled when scope" features.

In the user profile json definition that would be these two sections:

```json
    {
      "selector": {
        "scopes": [
          "microprofile-jwt" <--
        ]
      },
      "permissions": {
        "view": [],
        "edit": []
      },
      "name": "field",
      "displayName": "Field",
      "required": {
        "roles": [],
        "scopes": []
      }
    }
```

```json
    {
      "selector": {
        "scopes": []
      },
      "permissions": {
        "view": [],
        "edit": []
      },
      "name": "field",
      "displayName": "Field",
      "required": {
        "roles": [],
        "scopes": [
          "profile" <--
        ]
      }
    }
```

The realm configuration export is OK, but when trying to import it it will crash at  `java.lang.NullPointerException
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.userprofile.config.UPConfigUtils.validateScopes(UPConfigUtils.java:178)`

### Version

15.0.2

### Expected behavior

Regular full configuration import

### Actual behavior

Import crashing on NullPointerException

### How to Reproduce?

```
I use a very simple user profile to test the issue. I only add one field after the default ones (a field named _field_, with the 'Enabled when scope' option activated.
Here is the exported profile definition (in the main keycloak json export):

    (...),
    "org.keycloak.userprofile.UserProfileProvider" : [ {
      "id" : "133390a8-5744-454f-ab58-a09f3e28b04d",
      "providerId" : "declarative-user-profile",
      "subComponents" : { },
      "config" : {
        "config-piece-0" : [ "{\"attributes\":[{\"name\":\"username\",\"displayName\":\"${username}\",\"validations\":{\"length\":{\"min\":3,\"max\":255},\"username-prohibited-characters\":{}}},{\"name\":\"email\",\"displayName\":\"${email}\",\"validations\":{\"email\":{},\"length\":{\"max\":255}}},{\"name\":\"firstName\",\"displayName\":\"${firstName}\",\"required\":{\"roles\":[\"user\"]},\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}}},{\"name\":\"lastName\",\"displayName\":\"${lastName}\",\"required\":{\"roles\":[\"user\"]},\"permissions\":{\"view\":[\"admin\",\"user\"],\"edit\":[\"admin\",\"user\"]},\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}}},{\"selector\":{\"scopes\":[\"microprofile-jwt\"]},\"permissions\":{\"view\":[],\"edit\":[]},\"name\":\"field\",\"displayName\":\"Field\"}],\"groups\":[]}" ],
        "config-pieces-count" : [ "1" ]
      }
    } ],
    (...)

The problematic part is `\"selector\":{\"scopes\":[\"microprofile-jwt\"]}`, (mircoprofile_jwt could be any scope, that would still crash), If we replace it with an empty scope:
`\"selector\":{\"scopes\":[]}` the import goes without problems.

I run the import in a docker version of keycloak (image: jboss/keycloak:15.0.2) this way:

```bash
export JDBC_PARAMS=$(echo ${JDBC_PARAMS} | sed '/^$/! s/^/?/') \
 && /opt/jboss/keycloak/bin/standalone.sh \
   -Djboss.socket.binding.port-offset=150 \
   -Dkeycloak.migration.action=import \
   -Dkeycloak.migration.provider=dir \
   -Dkeycloak.migration.strategy=OVERWRITE_EXISTING \
   -Dkeycloak.profile.feature.upload_scripts=enabled \
   -Dkeycloak.migration.dir=/config/full \
   -Dkeycloak.profile.feature.declarative_user_profile=enabled
```

 And this is the java.lang.NullPointerException error on validateScopes obtained when a scope is added on a field:

```log

13:59:42,509 INFO  [org.keycloak.services] (ServerService Thread Pool -- 66) KC-SERVICES0030: Full model import requested. Strategy: OVERWRITE_EXISTING
13:59:42,698 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 66) Realm 'master' already exists. Removing it before import
13:59:48,417 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 66) Realm 'master' imported
13:59:48,668 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (ServerService Thread Pool -- 66) Imported users from /config/full/master-users-0.json
13:59:48,835 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 66) Realm 'cxx' already exists. Removing it before import
13:59:52,787 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 66) Realm 'cxx' imported
13:59:53,409 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (ServerService Thread Pool -- 66) Imported users from /config/full/cxx-users-0.json
13:59:53,637 INFO  [org.keycloak.exportimport.util.ImportUtils] (ServerService Thread Pool -- 66) Realm 'test' already exists. Removing it before import
13:59:55,253 FATAL [org.keycloak.services] (ServerService Thread Pool -- 66) Error during startup: java.lang.NullPointerException
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.userprofile.config.UPConfigUtils.validateScopes(UPConfigUtils.java:178)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.userprofile.config.UPConfigUtils.validateAttribute(UPConfigUtils.java:161)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.userprofile.config.UPConfigUtils.lambda$validateAttributes$2(UPConfigUtils.java:114)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.userprofile.config.UPConfigUtils.validateAttributes(UPConfigUtils.java:114)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.userprofile.config.UPConfigUtils.validate(UPConfigUtils.java:93)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.userprofile.DeclarativeUserProfileProvider.validateConfiguration(DeclarativeUserProfileProvider.java:182)
        at org.keycloak.keycloak-model-jpa@15.0.2//org.keycloak.models.jpa.RealmAdapter.importComponentModel(RealmAdapter.java:2020)
        at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.RepresentationToModel.importComponents(RepresentationToModel.java:620)
        at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:399)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:557)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.exportimport.util.ImportUtils.importRealm(ImportUtils.java:110)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.exportimport.dir.DirImportProvider$4.runExportImportTask(DirImportProvider.java:138)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.exportimport.util.ExportImportSessionTask.run(ExportImportSessionTask.java:35)
        at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:250)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.exportimport.dir.DirImportProvider.importRealm(DirImportProvider.java:134)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.exportimport.dir.DirImportProvider.importModel(DirImportProvider.java:76)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.exportimport.ExportImportManager.runImport(ExportImportManager.java:87)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.resources.KeycloakApplication.bootstrap(KeycloakApplication.java:207)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:136)
        at org.keycloak.keycloak-server-spi-private@15.0.2//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:250)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:128)
        at org.keycloak.keycloak-wildfly-extensions@15.0.2//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:36)
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2835)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:376)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:288)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:98)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)
        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
        at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)
        at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

13:59:55,255 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.keycloak.services.resources.KeycloakApplication
13:59:55,259 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002200: Adding class resource org.keycloak.services.resources.JsResource from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,260 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002205: Adding provider class org.keycloak.services.filters.KeycloakSecurityHeadersFilter from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,260 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002200: Adding class resource org.keycloak.services.resources.ThemeResource from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,260 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002205: Adding provider class org.keycloak.services.error.KeycloakErrorHandler from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,261 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RobotsResource from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,261 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.admin.AdminRoot from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,261 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.WelcomeResource from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,261 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002210: Adding provider singleton org.keycloak.services.util.ObjectMapperResolver from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,261 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 66) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.RealmsResource from Application class org.keycloak.services.resources.KeycloakApplication
13:59:55,260 INFO  [org.jboss.as.server] (Thread-1) WFLYSRV0220: Server shutdown has been requested via an OS signal
13:59:55,290 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-8) WFLYJCA0010: Unbound data source [java:jboss/datasources/KeycloakDS]
13:59:55,297 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0008: Undertow HTTPS listener https suspending
13:59:55,297 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-2) WFLYMAIL0002: Unbound mail session [java:jboss/mail/Default]
13:59:55,320 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0019: Stopped Driver service with driver-name = postgresql
13:59:55,324 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0007: Undertow HTTPS listener https stopped, was bound to 127.0.0.1:8593
13:59:55,341 INFO  [org.jboss.resteasy.plugins.validation.i18n] (ServerService Thread Pool -- 66) RESTEASY008550: Unable to find CDI supporting ValidatorFactory. Using default ValidatorFactory
13:59:55,404 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 66) WFLYUT0021: Registered web context: '/auth' for server 'default-server'
13:59:55,406 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 66) WFLYUT0022: Unregistered web context: '/auth' from server 'default-server'  
 13:59:55,412 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-6) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
13:59:55,415 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-4) WFLYJCA0019: Stopped Driver service with driver-name = h2
13:59:55,419 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0019: Host default-host stopping
13:59:55,441 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0008: Undertow HTTP listener default suspending
13:59:55,445 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0028: Stopped deployment keycloak-server.war (runtime-name: keycloak-server.war) in 179ms
13:59:55,447 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 127.0.0.1:8230
13:59:55,447 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 70) WFLYCLINF0003: Stopped loginFailures cache from keycloak container
13:59:55,452 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 69) WFLYCLINF0003: Stopped offlineClientSessions cache from keycloak container
13:59:55,452 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0004: Undertow 2.2.5.Final stopping
13:59:55,460 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 77) WFLYCLINF0003: Stopped keys cache from keycloak container
13:59:55,460 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 71) WFLYCLINF0003: Stopped authenticationSessions cache from keycloak container
13:59:55,461 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 73) WFLYCLINF0003: Stopped sessions cache from keycloak container
13:59:55,465 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 78) WFLYCLINF0003: Stopped users cache from keycloak container
13:59:55,472 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 75) WFLYCLINF0003: Stopped authorization cache from keycloak container
13:59:55,472 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 76) WFLYCLINF0003: Stopped offlineSessions cache from keycloak container
13:59:55,472 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 79) WFLYCLINF0003: Stopped clientSessions cache from keycloak container
13:59:55,472 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 72) WFLYCLINF0003: Stopped work cache from keycloak container
13:59:55,474 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 74) WFLYCLINF0003: Stopped actionTokens cache from keycloak container
13:59:55,482 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 80) WFLYCLINF0003: Stopped realms cache from keycloak container
13:59:55,483 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 80) Stopping cache manager null on null
13:59:55,550 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 66) WFLYCLINF0003: Stopped http-remoting-connector cache from ejb container
13:59:55,551 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 66) Stopping cache manager null on null
13:59:55,556 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "metrics")]): java.lang.NullPointerException
        at org.wildfly.extension.metrics@23.0.2.Final//org.wildfly.extension.metrics.MetricsSubsystemAdd$2.execute(MetricsSubsystemAdd.java:91)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1040)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:779)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:468)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1415)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:529)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:515)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:477)
        at org.jboss.as.server@15.0.1.Final//org.jboss.as.server.ServerService.boot(ServerService.java:459)
        at org.jboss.as.server@15.0.1.Final//org.jboss.as.server.ServerService.boot(ServerService.java:412)
        at org.jboss.as.controller@15.0.1.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:416)
        at java.base/java.lang.Thread.run(Thread.java:829)

13:59:55,562 ERROR [org.jboss.as.server] (ServerService Thread Pool -- 43) WFLYSRV0022: Deploy of deployment "keycloak-server.war" was rolled back with no failure message
13:59:55,581 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0050: Keycloak 15.0.2 (WildFly Core 15.0.1.Final) stopped in 314ms
```

**Comment by vmuzikar** [comment]
Thanks for the report! Can you please confirm if the issue still persists with the latest [`nightly` Keycloak version](https://quay.io/repository/keycloak/keycloak?tab=tags&tag=nightly) for you? If so, feel free to reopen. We believe it should be fixed already.
