### ISSUE TITLE
Disabling Create User If Unique for First Broker Login results in Invalid Username or Password

### ISSUE THREAD

**Issue by victorabclagerfors** [keycloak/keycloak#8900]
### Describe the bug

Hi,

When following the [instructions](https://www.keycloak.org/docs/latest/server_admin/#_disabling_automatic_user_creation) to disable automatic creation when signing in using an identity provider without an account, the result is being redirected to the keycloak page stating "Invalid username or password." I am currently working with a SAML idp, which works when user creation is enabled. 

### Version

15.0.0

### Expected behavior

I expect to be successfully authenticated and redirected to the url guarded by keycloak.

### Actual behavior

I am redirected to a keycloak page stating "Invalid username or password". The logs output Flow 'User creation or linking flow' failed. The stack trace reads: 

`Failed authentication: org.keycloak.authentication.AuthenticationFlowException
	at org.keycloak.keycloak-services@15.0.0//org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:993)
	at org.keycloak.keycloak-services@15.0.0//org.keycloak.services.resources.LoginActionsService$1.authenticateOnly(LoginActionsService.java:799)
	at org.keycloak.keycloak-services@15.0.0//org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:852)
	at org.keycloak.keycloak-services@15.0.0//org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:314)
	at org.keycloak.keycloak-services@15.0.0//org.keycloak.services.resources.LoginActionsService.brokerLoginFlow(LoginActionsService.java:829)
	at org.keycloak.keycloak-services@15.0.0//org.keycloak.services.resources.LoginActionsService.firstBrokerLoginGet(LoginActionsService.java:723)`

### How to Reproduce?

Set up an identity provider of type SAML. Set the first login flow to: first broker login. Follow the [instructions](https://www.keycloak.org/docs/latest/server_admin/#_disabling_automatic_user_creation) to disable automatic user creation. Try to sign in through the IdP guarding the website.

**Comment by rmartinc** [comment]
@victorabclagerfors When you disable the account creation completely the server only allows the login if the user in the realm is previously linked to the identity provider. Creating the user before and linking it to the provider using the `Identity provider links` tab in the user.

You can configure the first login flow to create or link the external provider account to someone in the realm (using the different options you have in the broker, you can only allow part of them, linking but not creation for example). If you doesn't allow to do anything the authentication fails with invalid password. What do you think it should happen?

**Comment by rmartinc** [comment]
Closing this. Feel free to re-open if needed.
