### ISSUE TITLE
Infinispan HotRod sockets are closed after a transaction is aborted by server

### ISSUE THREAD

**Issue by sre4ever** [keycloak/keycloak#8924]
### Describe the bug

Hello,

Currently (verified on 14.0.0, very probably still the case on current 16.0.0-SNAPSHOT) exceptions raised by Infinispan Server (such as `ISPN000136: Error executing command PrepareCommand on Cache 'sessions'` or  `ISPN000926: afterCompletion() failed for SynchronizationAdapter`) cause the HotRod socket to be closed by the client after the expiration of transport lock-timeout (default 1 min) even when the error was properly handled client-side and the connection is still healthy.

This seems to be mostly cosmetic as connections are properly reopened and transactions are retried.

This is caused by the issue [ISPN-12801](https://issues.redhat.com/browse/ISPN-12801) that was fixed in Infinispan 12.1.0. The fix would be to update the version of Infinispan client and dependencies, but some refactoring/upgrade of Keycloak code seems required due to deprecations and changes in Infinispan client API.

### Version

14.0.0

### Expected behavior

Infinispan exceptions do not always cause HotRod sockets to be closed later.

### Actual behavior

HotRod sockets are always closed after a server-side exception is reported to the client and the inactivity timeout elapsed.

The following exception is reported by Keycloak:
```
WARN
keycloak
org.infinispan.HOTROD
ISPN004098: Closing connection [id: 0x3c6691d7, L:/redacted:38524 ! R:redacted/redacted:11222] due to transport error
java.net.SocketTimeoutException: RemoveOperation{sessions, key=[B0x033E2430343034636331632D35636264..[39], flags=1, connection=redacted/redacted:11222} timed out after 60000 ms
at org.infinispan.client.hotrod@11.0.9.Final//org.infinispan.client.hotrod.impl.operations.HotRodOperation.run(HotRodOperation.java:176)
at io.netty@4.1.63.Final//io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at io.netty@4.1.63.Final//io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
at io.netty@4.1.63.Final//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty@4.1.63.Final//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty@4.1.63.Final//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
at io.netty@4.1.63.Final//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty@4.1.63.Final//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

### How to Reproduce?

Setup required: Keycloak cluster + Infinispan Server (remote cache) node or cluster, single site or cross-site.

Generate enough colliding traffic to cause transactions to be rolled back on the Infinispan cluster.

Check logs of both servers and notice that all errors reported by the Infinispan server are causing HotRod connections to be closed 1 min later by the Keycloak server.

**Comment by martin-kanis** [comment]
Hello, thanks for the report. We are now on Infinispan 13.0.10.Final and there's a PR for upgrade to 14.0.1.Final. According to your findings, the issue should be now resolved. Closing.
