### ISSUE TITLE
Can't set up Webauthn Security Key with Keycloak.X

### ISSUE THREAD

**Issue by chrisx8** [keycloak/keycloak#9092]
### Describe the bug

I'm not able to set up any Webauthn security key from the account console in Keycloak.X. When I try to set up a security key, an internal server error occurs.

In a fresh realm, I followed the [Webauthn setup steps in the Server Administration Guide](https://www.keycloak.org/docs/latest/server_admin/#_webauthn) to enable Webauthn support. I'm not able to set up security keys with Keycloak.X, but I can set up security keys after setting up following the same steps in WildFly-based Keycloak.

This bug has been around since at least version 14.0.0.

### Version

Keycloak.X 15.1.0

### Expected behavior

Can add security key from account console, after following [Webauthn setup steps in the Server Administration Guide](https://www.keycloak.org/docs/latest/server_admin/#_webauthn).

### Actual behavior

"An internal server error has occured"

```
ERROR [org.key.ser.err.KeycloakErrorHandler] (executor-thread-16) Uncaught server error: java.lang.NullPointerException: Cannot invoke "javax.ws.rs.core.MediaType.isCompatible(javax.ws.rs.core.MediaType)" because "mt" is null
        at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:53)
        at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
        at jdk.proxy2/jdk.proxy2.$Proxy47.getDecodedFormParameters(Unknown Source)
        at org.keycloak.authentication.requiredactions.WebAuthnRegister.requiredActionChallenge(WebAuthnRegister.java:135)
        at org.keycloak.services.managers.AuthenticationManager.executeAction(AuthenticationManager.java:1265)
        at org.keycloak.services.managers.AuthenticationManager.executionActions(AuthenticationManager.java:1224)
        at org.keycloak.services.managers.AuthenticationManager.actionRequired(AuthenticationManager.java:1112)
        at org.keycloak.services.managers.AuthenticationManager.nextActionAfterAuthentication(AuthenticationManager.java:959)
        at org.keycloak.services.resources.LoginActionsService.processRequireAction(LoginActionsService.java:995)
        at org.keycloak.services.resources.LoginActionsService.requiredActionGET(LoginActionsService.java:977)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:81)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:41)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1128)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:154)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1128)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:154)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:362)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:340)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1128)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:154)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:66)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

- Create a new realm
- Set up Webauthn support, following Webauthn setup steps [in the Server Administration Guide](https://www.keycloak.org/docs/latest/server_admin/#_webauthn)
- Go to Account Management console (`/realms/<realm>/account/`), "Signing In", "Set up Security Key"
- Internal server error (see traceback above)

### Anything else?

Following the exact same setup steps, Webauthn works as expected in WildFly-based Keycloak.

**Comment by pedroigor** [comment]
@chrisx8 It should work the same way.

We had similar issues in other places where Resteasy now is more strict about decoding form parameters and expects that the request is a `POST` and have the proper content-type set.

Are you able to link here the request headers sent by the account console when that error happens?

**Comment by chrisx8** [comment]
Here are the headers on the request to `https://keycloak-x.***.com/realms/master/login-actions/required-action?execution=webauthn-register&client_id=account-console&tab_id=O9_SSQf2COM`, which generated the 500 error.

<details>
  <summary>Request headers</summary>

   ```
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: AUTH_SESSION_ID=***; AUTH_SESSION_ID_LEGACY=***; KEYCLOAK_SESSION=master/***; KEYCLOAK_SESSION_LEGACY=master/***; KEYCLOAK_IDENTITY=***; KEYCLOAK_IDENTITY_LEGACY=***; KC_RESTART=***
pragma: no-cache
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
   ```
</details>


<details>
  <summary>Response headers</summary>
  
  ```
cache-control: no-store, must-revalidate, max-age=0
content-length: 2015
content-security-policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
content-type: text/html;charset=utf-8
date: Mon, 13 Dec 2021 15:51:35 GMT
referrer-policy: no-referrer
server: nginx
set-cookie: KEYCLOAK_LOCALE=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/; HttpOnly
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-robots-tag: none
x-xss-protection: 1; mode=block
  ```
</details>

For reference, here are the headers on the request to the same endpoint (`https://keycloak.***.com/auth/realms/master/login-actions/required-action?execution=webauthn-register&client_id=account-console&tab_id=X61T3NiLdEY`) on the WildFly-based version, which works correctly.

<details>
  <summary>Request headers</summary>

   ```
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: AUTH_SESSION_ID=***; AUTH_SESSION_ID_LEGACY=***; KEYCLOAK_SESSION=master/***; KEYCLOAK_SESSION_LEGACY=master/***; KEYCLOAK_IDENTITY=***; KEYCLOAK_IDENTITY_LEGACY=***; KC_RESTART=***
pragma: no-cache
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
   ```
</details>


<details>
  <summary>Response headers</summary>
  
  ```
cache-control: no-store, must-revalidate, max-age=0
content-encoding: gzip
content-language: en
content-security-policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
content-type: text/html;charset=utf-8
date: Mon, 13 Dec 2021 16:03:01 GMT
referrer-policy: no-referrer
server: nginx
set-cookie: KEYCLOAK_LOCALE=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/master/; Secure; HttpOnly
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-robots-tag: none
x-xss-protection: 1; mode=block
  ```
</details>

**Comment by pedroigor** [comment]
@chrisx8 Thanks, the error is related to how Resteasy 4.x behaves when trying to decode form parameters on a non-form-urlencoded request.

We fixed that in some other places, but it seems we are not covering this specific case.

**Comment by pedroigor** [comment]
@mposolda Do you have any hints on any test I can base on for WebAuthn? I remember we don't yet have anything, right?

**Comment by nmwael** [comment]
on 17,  this gives the same:
`curl --silent -X POST \
http://localhost:8080/realms/multi-customer/protocol/openid-connect/token \
-H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoVXBKcFdZaTBNWE5kUXJPeUtJWFZaV1lJd1NDX2JJbjhMcVUwUnZ5ZWlJIn0.eyJleHAiOjE2NDY5OTQ2OTcsImlhdCI6MTY0Njk5NDM5NywianRpIjoiNzZmZDg0Y2UtNmJmZC00NWNhLWE3NDMtOGJmOGVjZDliZWViIiwiaXNzIjoiaHR0cDovLzEwLjE2MC4xNjcuMzc6ODA4MC9yZWFsbXMvbXVsdGktY3VzdG9tZXIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiN2ZlOGI3YTktZTA0OC00N2JhLWI4MmUtOGUxMzEwY2VmNjliIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY3VzdG9tZXJzIiwic2Vzc2lvbl9zdGF0ZSI6IjUzNWZlNjJmLTAyMDYtNDhmMC04ZDU5LWRlNTE3OTJjNzUzNCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1tdWx0aS1jdXN0b21lciIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiI1MzVmZTYyZi0wMjA2LTQ4ZjAtOGQ1OS1kZTUxNzkyYzc1MzQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNZW1iZXIgU2VydmljZVRlYW0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZW1iZXJAc2VydmljZS10ZWFtIiwiZ2l2ZW5fbmFtZSI6Ik1lbWJlciIsImZhbWlseV9uYW1lIjoiU2VydmljZVRlYW0iLCJlbWFpbCI6Im1lbWJlckBzZXJ2aWNlLXRlYW0ifQ.rifiNKP-wl-d3SS9DCLk_jadEibvKEx1v4xraOKOaGo3UzvPgWtVz0hyuq2CyQT-WVqv3xNEuzmQbFLF2HvyLiN8JSMsapE6bKofGHQ6_R_8BtinmZLvozpV6AMTk9rrBI0l38vQwAcR3Ota6czNyIGf4B46zyo4DBW7PleAY_84stJJdnl_2BHCgNaiJvtPNpCTAzQR7SHucOVS8JUJjljbJsoXxO57mfkMF61wF24CqWZDO6MYppCzrBn4angM16UQ2v4MScvQT0p7sSFLpsHKFr4xqPQy9NDdif_qZQxCrb5bsduinjBKRbgx7l_d8gqRw-8yc_03Sj_YsgL8cg" \
--data "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
--data "audience=customers"`

Adding mediatype fixes this:
curl --silent -X POST \
http://localhost:8080/realms/multi-customer/protocol/openid-connect/token \
-H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoVXBKcFdZaTBNWE5kUXJPeUtJWFZaV1lJd1NDX2JJbjhMcVUwUnZ5ZWlJIn0.eyJleHAiOjE2NDY5OTQ2OTcsImlhdCI6MTY0Njk5NDM5NywianRpIjoiNzZmZDg0Y2UtNmJmZC00NWNhLWE3NDMtOGJmOGVjZDliZWViIiwiaXNzIjoiaHR0cDovLzEwLjE2MC4xNjcuMzc6ODA4MC9yZWFsbXMvbXVsdGktY3VzdG9tZXIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiN2ZlOGI3YTktZTA0OC00N2JhLWI4MmUtOGUxMzEwY2VmNjliIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY3VzdG9tZXJzIiwic2Vzc2lvbl9zdGF0ZSI6IjUzNWZlNjJmLTAyMDYtNDhmMC04ZDU5LWRlNTE3OTJjNzUzNCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1tdWx0aS1jdXN0b21lciIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiI1MzVmZTYyZi0wMjA2LTQ4ZjAtOGQ1OS1kZTUxNzkyYzc1MzQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNZW1iZXIgU2VydmljZVRlYW0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZW1iZXJAc2VydmljZS10ZWFtIiwiZ2l2ZW5fbmFtZSI6Ik1lbWJlciIsImZhbWlseV9uYW1lIjoiU2VydmljZVRlYW0iLCJlbWFpbCI6Im1lbWJlckBzZXJ2aWNlLXRlYW0ifQ.rifiNKP-wl-d3SS9DCLk_jadEibvKEx1v4xraOKOaGo3UzvPgWtVz0hyuq2CyQT-WVqv3xNEuzmQbFLF2HvyLiN8JSMsapE6bKofGHQ6_R_8BtinmZLvozpV6AMTk9rrBI0l38vQwAcR3Ota6czNyIGf4B46zyo4DBW7PleAY_84stJJdnl_2BHCgNaiJvtPNpCTAzQR7SHucOVS8JUJjljbJsoXxO57mfkMF61wF24CqWZDO6MYppCzrBn4angM16UQ2v4MScvQT0p7sSFLpsHKFr4xqPQy9NDdif_qZQxCrb5bsduinjBKRbgx7l_d8gqRw-8yc_03Sj_YsgL8cg" \
-H "Content-Type:application/x-www-form-urlencoded" \
--data "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
--data "audience=customers"
