### ISSUE TITLE
Start Keycloak.X with --features=experimental leads to exception

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#9094]
### Describe the bug

When running e.g. `kc.sh start-dev --features=experimental` I observed that the following exception occurs:

```
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureProviders threw an exception: java.lang.IllegalArgumentException: No enum constant org.keycloak.common.Profile.ProfileValue.EXPERIMENTAL
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.keycloak.common.Profile$ProfileValue.valueOf(Profile.java:109)
	at org.keycloak.common.Profile.<init>(Profile.java:133)
	at org.keycloak.quarkus.runtime.KeycloakRecorder.createProfile(KeycloakRecorder.java:86)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureProviders(KeycloakProcessor.java:240)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

It seems, there's no mapping found for "experimental" in ProductValue, which is true, bc. this only has 3 values, none of them experimental. Using e.g. `--features=preview` works as expected. 

### Version

15.1.0

### Expected behavior

Keycloak.X starts with experimental features enabled.

### Actual behavior

Exception is thrown. 

### How to Reproduce?

run kc.sh start-dev --features=experimental

### Anything else?

observed while trying to look into #9092

**Comment by DGuhr** [comment]
looking a bit further, it seems we actually should only use "preview" here, all others from "expectedValues" lead to the aforementioned exception. @pedroigor lets talk about this tomorrow. :)
