### ISSUE TITLE
VerificationException: SigAlg was null

### ISSUE THREAD

**Issue by seriouszyx** [keycloak/keycloak#9132]
### Describe the bug

This is a sample request which is sent to keycloak.

```xml
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" validUntil="2021-12-21T13:00:20.9528336Z" entityID="http://localhost:8000/api/acs">
    <SPSSODescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <KeyDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data xmlns="http://www.w3.org/2000/09/xmldsig#">
                    <X509Certificate xmlns="http://www.w3.org/2000/09/xmldsig#">MIIE+TCCAuGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMDYxHTAbBgNVBAoTFENhc2Rvb3IgT3JnYW5pemF0aW9uMRUwEwYDVQQDEwxDYXNkb29yIENlcnQwHhcNMjExMDE1MDgxMTUyWhcNNDExMDE1MDgxMTUyWjA2MR0wGwYDVQQKExRDYXNkb29yIE9yZ2FuaXphdGlvbjEVMBMGA1UEAxMMQ2FzZG9vciBDZXJ0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsInpb5E1/ym0f1RfSDSSE8IR7y+lw+RJjI74e5ejrq4b8zMYk7HeHCyZr/hmNEwEVXnhXu1P0mBeQ5ypp/QGo8vgEmjAETNmzkI1NjOQCjCYwUrasO/f/MnI1C0j13vx6mV1kHZjSrKsMhYY1vaxTEP3+VB8Hjg3MHFWrb07uvFMCJe5W8+0rKErZCKTR8+9VB3janeBz//zQePFVh79bFZate/hLirPK0Go9P1gOvwIoC1A3sarHTP4Qm/LQRt0rHqZFybdySpyWAQvhNaDFE7mTstRSBb/wUjNCUBDPTSLVjC04WllSf6Nkfx0Z7KvmbPstSj+btvcqsvRAGtvdsB9h62Kptjs1Yn7GAuoI3qt/4zoKbiURYxkQJXIvwCQsEftUuk5ew5zuPSlDRLoLByQTLbx0JqLAFNfW3g/pzSDjgd/60d6HTmvbZni4SmjdyFhXCDb1Kn7N+xTojnfaNkwep2REV+RMc0fx4GuhRsnLsmkmUDeyIZ9aBL9oj11YEQfM2JZEq+RVtUx+wB4y8K/tD1bcY+IfnG5rBpwIDpS262boq4SRSvb3Z7bB0w4ZxvOfJ/1VLoRftjPbLIf0bhfr/AeZMHpIKOXvfz4yE+hqzi68wdF0VR9xYc/RbSAf7323OsjYnjjEgInUtRohnRgCpjIk/Mt2Kt84Kb0wn8CAwEAAaMQMA4wDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEAn2lfDKkLX+F1vKRO/5gJ+Plr8P5NKuQkmwH97b8CS2gS1phDyNgIc4/LSdzuf4Awe6veC06lVdWSIis8UPUPdjmT2uMPSNjwLxG3QsrimMURNwFlLTfRem/heJe0Zgur9J1M8haawdSdJjH2RgmFoDeE2r8NVRfhbR8KnCO1ddTJKuS1N0/irHz21W4jt4rxzCvl2nR42Fybap3O/g2JXMhNNROwZmNjgpsF7XVENCSuFO1jTywLaqjuXCg54IL7XVLGomKNNNcc8h1FCeKj/nnbGMhodnFWKDTsJcbNmcOPNHo6ixzqMy/Hqc+mWYv7maAGJtevs3qgMZ8F9Qzr3HpUc6R3ZYYWDY/xxPisuKftOPZgtH979XC4mdf0WPnOBLqL2DJ1zaBmjiGJolvb7XNVKcUfDXYw85ZTZQ5b9clI4e+6bmyWqQItlwt+Ati/uFEVXzCj70B4lALX6xau1kLEpV9O1GERizYRz5P9NJNA7KoO5AVMp9w0DQTkt+LbXnZEHHnWKy8xHQKZF9sR7YBPGLs/Ac6tviv5Ua15OgJ/8dLRZ/veyFfGo2yZsI+hKVU5nCCJHBcAyFnm1hdvdwEdH33jDBjNB6ciotJZrf/3VYaIWSalADosHAgMWfXuWP+h8XKXmzlxuHbTMQYtZPDgspS5aK+S4Q9wb8RRAYo=</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <KeyDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" use="encryption">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data xmlns="http://www.w3.org/2000/09/xmldsig#">
                    <X509Certificate xmlns="http://www.w3.org/2000/09/xmldsig#">MIIE+TCCAuGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMDYxHTAbBgNVBAoTFENhc2Rvb3IgT3JnYW5pemF0aW9uMRUwEwYDVQQDEwxDYXNkb29yIENlcnQwHhcNMjExMDE1MDgxMTUyWhcNNDExMDE1MDgxMTUyWjA2MR0wGwYDVQQKExRDYXNkb29yIE9yZ2FuaXphdGlvbjEVMBMGA1UEAxMMQ2FzZG9vciBDZXJ0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsInpb5E1/ym0f1RfSDSSE8IR7y+lw+RJjI74e5ejrq4b8zMYk7HeHCyZr/hmNEwEVXnhXu1P0mBeQ5ypp/QGo8vgEmjAETNmzkI1NjOQCjCYwUrasO/f/MnI1C0j13vx6mV1kHZjSrKsMhYY1vaxTEP3+VB8Hjg3MHFWrb07uvFMCJe5W8+0rKErZCKTR8+9VB3janeBz//zQePFVh79bFZate/hLirPK0Go9P1gOvwIoC1A3sarHTP4Qm/LQRt0rHqZFybdySpyWAQvhNaDFE7mTstRSBb/wUjNCUBDPTSLVjC04WllSf6Nkfx0Z7KvmbPstSj+btvcqsvRAGtvdsB9h62Kptjs1Yn7GAuoI3qt/4zoKbiURYxkQJXIvwCQsEftUuk5ew5zuPSlDRLoLByQTLbx0JqLAFNfW3g/pzSDjgd/60d6HTmvbZni4SmjdyFhXCDb1Kn7N+xTojnfaNkwep2REV+RMc0fx4GuhRsnLsmkmUDeyIZ9aBL9oj11YEQfM2JZEq+RVtUx+wB4y8K/tD1bcY+IfnG5rBpwIDpS262boq4SRSvb3Z7bB0w4ZxvOfJ/1VLoRftjPbLIf0bhfr/AeZMHpIKOXvfz4yE+hqzi68wdF0VR9xYc/RbSAf7323OsjYnjjEgInUtRohnRgCpjIk/Mt2Kt84Kb0wn8CAwEAAaMQMA4wDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEAn2lfDKkLX+F1vKRO/5gJ+Plr8P5NKuQkmwH97b8CS2gS1phDyNgIc4/LSdzuf4Awe6veC06lVdWSIis8UPUPdjmT2uMPSNjwLxG3QsrimMURNwFlLTfRem/heJe0Zgur9J1M8haawdSdJjH2RgmFoDeE2r8NVRfhbR8KnCO1ddTJKuS1N0/irHz21W4jt4rxzCvl2nR42Fybap3O/g2JXMhNNROwZmNjgpsF7XVENCSuFO1jTywLaqjuXCg54IL7XVLGomKNNNcc8h1FCeKj/nnbGMhodnFWKDTsJcbNmcOPNHo6ixzqMy/Hqc+mWYv7maAGJtevs3qgMZ8F9Qzr3HpUc6R3ZYYWDY/xxPisuKftOPZgtH979XC4mdf0WPnOBLqL2DJ1zaBmjiGJolvb7XNVKcUfDXYw85ZTZQ5b9clI4e+6bmyWqQItlwt+Ati/uFEVXzCj70B4lALX6xau1kLEpV9O1GERizYRz5P9NJNA7KoO5AVMp9w0DQTkt+LbXnZEHHnWKy8xHQKZF9sR7YBPGLs/Ac6tviv5Ua15OgJ/8dLRZ/veyFfGo2yZsI+hKVU5nCCJHBcAyFnm1hdvdwEdH33jDBjNB6ciotJZrf/3VYaIWSalADosHAgMWfXuWP+h8XKXmzlxuHbTMQYtZPDgspS5aK+S4Q9wb8RRAYo=</X509Certificate>
                </X509Data>
            </KeyInfo>
            <EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes128-gcm"></EncryptionMethod>
            <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"></EncryptionMethod>
            <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"></EncryptionMethod>
        </KeyDescriptor>
        <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8000/api/acs" index="1"></AssertionConsumerService>
    </SPSSODescriptor>
</EntityDescriptor>
```

When I enable the `Client Signature Required` option, I get the following error and stacktrace in Keycloak.

```
20:59:54,487 WARN  [org.keycloak.events] (default task-152) type=LOGIN_ERROR, realmId=casdoor, clientId=null, userId=null, ipAddress=127.0.0.1, error=invalid_signature
21:00:21,277 ERROR [org.keycloak.protocol.saml.SamlService] (default task-152) request validation failed: org.keycloak.common.VerificationException: SigAlg was null
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:157)
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:147)
        at org.keycloak.protocol.saml.SamlService$RedirectBindingProtocol.verifySignature(SamlService.java:764)
        at org.keycloak.protocol.saml.SamlService$BindingProtocol.handleSamlRequest(SamlService.java:302)
        at org.keycloak.protocol.saml.SamlService$BindingProtocol.execute(SamlService.java:689)
        at org.keycloak.protocol.saml.SamlService.redirectBinding(SamlService.java:816)
        ...
```

### Version

15.0.2

**Comment by clafoutis42** [comment]
Hello @seriouszyx.

Did you find a solution or a workaround?

I am facing the same problem while configuring Keycloak in Slack as Custom SAML SSO.

**Comment by alikhil** [comment]
I have found the workarand [here](https://www.rancher.co.jp/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/)

**Comment by GavinCui9** [comment]
I have the same problem when enable "Client signature" after release 19. The workaround by disabling it is not a really solution. It looks a bug of KeyCloak.

When disabled the "Client signature", the captured saml response with certificate like:

        <dsig:X509Certificate>
MIICoTCCAYkCBgGGDkYhcDANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAlwb3J0YWwtMzMwHhcN&#13; MjMwMjAxMTgzNzAyWhcNMzMwMjAxMTgzODQyWjAUMRIwEAYDVQQDDAlwb3J0YWwtMzMwggEiMA0G&#13; CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDebgJ8Z5kIwGxC6FSwH3wozIPEQLprsPPcRHY4CrPl&#13;
          IUZ5ZVM7SsnfFagzkWV2L8hkGMNQWhplNlxyEgKc408NLZsdjdnYWEQFrb1TpJVygM78KA7V9uxE&#13; PWjmRQO1QQCR/Jf5lZZRO0D/9exkk3KmvGBnz4rbH1F+UVHP89Ukix2S54a4gMnSO3C4YT6eChWi&#13; d9n2ae/gP9Y+myD4xLsybPo/I9+eY0Pe043piPM1Sq5E4ZPerRjoEOppFfeJbB0s9eIGtZmDEmY/&#13;
          /aZ/pGNwSjJ62sNSya+XuRBDVh2Rj7fH9X+kcCgVoMpd2/dHx9kVlHfBzxilURZJGdATVM5FAgMB&#13; AAEwDQYJKoZIhvcNAQELBQADggEBABjmhFEbd8KlLWmbfDIl9boheGoJgP/BisS+vFqcxTkXas8a&#13; BEhkHx4GRluuFD6vsmR8WudrMy/C30rCZpNWs6QS9ESkzxpHtGCHDUf5vVThO2xCPtBFHqbBzkUi&#13;
          mAXz7YcWXCX8NEAGXhoFpi5wT4BMtebFoKJRlN9JlH/8BvI7io7mit+MlMijJgXBqxn7vbdVkMdn&#13; tCt6sTcwtyDw9pfFjy9JunwOeDaAnBaS9e2otbcSZw6GQI7h/Jlan9eh4dV6wmXWJ6sIsFVE4DY2&#13; J4Ld8xEAnWWeBOvkZLUnaT/JHqJxBazavcEKNueMjtQbOSLSW2b7ANYU9a/AQX8h2KY=
        
</dsig:X509Certificate>

Do not understand why a carriage return was attached to the end of each line.

**Comment by rmartinc** [comment]
Hi!

It seems that you are using Redirect Binding. In the redirect binding the other partner should send several query encoded parameters for the request to perform the signature validation. Besides the SAMLRequest it should also send the SigAlg and the Signature which it seems that is not sending (you can check that, in redirect binding they are jusr query parameters). You have to check if the other partner is correctly configured to do that (certificates should be interchanged and so on and so forth).

For more information check the [SAML bindings spec](https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) (chapter 3.4 HTTP Redirect Binding, there are examples at the end).

**Comment by rmartinc** [comment]
Closing this. Feel free to re-open if needed.
