### ISSUE TITLE
Cannot call toRepresentation on realm

### ISSUE THREAD

**Issue by hrstn** [keycloak/keycloak#9177]
### Describe the bug

calling "restclient.realm(realm).toRepresentation();" (using the java spring keycloak-admin-client 15.0.1)

causes 

`
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "oauth2DeviceCodeLifespan" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable (130 known properties: "userFederationMappers", "rememberMe", "duplicateEmailsAllowed", "adminEventsDetailsEnabled", "users", "clientOfflineSessionMaxLifespan", "webAuthnPolicyRequireResidentKey", "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister", "components", "otpPolicyType", "accessCodeLifespanUserAction", "id", "webAuthnPolicyAttestationConveyancePreference", "enabledEventTypes", "applications", "webAuthnPolicyPasswordlessSignatureAlgorithms", "eventsListeners", "ssoSessionMaxLifespanRememberMe", "defaultDefaultClientScopes", "webAuthnPolicyPasswordlessCreateTimeout", "clientOfflineSessionIdleTimeout", "notBefore", "publicKey", "smtpServer", "resetPasswordAllowed", "webAuthnPolicyAvoidSameAuthenticatorRegister", "accessTokenLifespanForImplicitFlow", "webAuthnPolicyPasswordlessUserVerificationRequirement", "clientScopes", "internationalizationEnabled", "attributes", "accessTokenLifespan", "passwordCredentialGrantAllowed", "federatedUsers", "applicationScopeMappings", "displayName" [truncated]])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 829] (through reference chain: org.keycloak.representations.idm.RealmRepresentation["oauth2DeviceCodeLifespan"])
		at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
		at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
		at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)
		at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
		at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
		at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2042)
		at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1201)
		at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:181)
		at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66)
		at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56)
		at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:211)
		... 88 more
`

### Version

15.0.1 15.1.0

**Comment by stianst** [comment]
Let me take a wild guess - you are not using the same version of rest admin client as the Keycloak server?

**Comment by hrstn** [comment]
Both is running 15.0.1 currently

**Comment by stianst** [comment]
Are you certain about that? Both the server side and the client is sharing the same Java class that handles the JSON, so can't see how this can be valid:

https://github.com/keycloak/keycloak/blob/122446c6cb284e897f816e886fd47443410173b0/core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java#L71

**Comment by hrstn** [comment]
Seems to be in the package in the same line
