### ISSUE TITLE
Failed to obtain authorization data

### ISSUE THREAD

**Issue by myifeng** [keycloak/keycloak#9269]
### Describe the bug

```
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.adapters.RequestAuthenticator        : Bearer AUTHENTICATED
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] .k.a.t.AbstractAuthenticatedActionsValve : AuthenticatedActionsValve.invoke /commercial-admin/order/list
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.a.AuthenticatedActionsHandler        : AuthenticatedActionsValve.invoke https://demo.com/commercial-admin/order/list?_t=0.5955129800688355
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.a.AuthenticatedActionsHandler        : Origin: https://tabop-tst.lenovo.com uri: https://demo.com/commercial-admin/order/list?_t=0.5955129800688355
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.a.AuthenticatedActionsHandler        : Allowed origins in token: [*]
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.a.AuthenticatedActionsHandler        : returning origin: https://tabop-tst.lenovo.com
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.a.authorization.PolicyEnforcer       : Policy enforcement is enabled. Enforcing policy decisions for path [https://demo.com/commercial-admin/order/list?_t=0.5955129800688355].
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.a.a.AbstractPolicyEnforcer           : Checking permissions for path [https://demo.com/commercial-admin/order/list?_t=0.5955129800688355] with config [PathConfig{name='/commercial-admin/order/list', type='null', path='/commercial-admin/order/list', scopes=[], id='885d7325-76b5-469f-bc58-5388e7faf199', enforcerMode='ENFORCING'}].
2021-12-21 05:19:42.873 DEBUG 1 --- [nio-9082-exec-4] o.k.a.a.KeycloakAdapterPolicyEnforcer    : Obtaining authorization for authenticated user.
2021-12-21 05:19:42.874 DEBUG 1 --- [nio-9082-exec-6] o.k.a.a.KeycloakAdapterPolicyEnforcer    : Authorization failed

java.lang.RuntimeException: Failed to obtain authorization data
        at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:45)
        at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:65)
        at org.keycloak.authorization.client.resource.AuthorizationResource.authorize(AuthorizationResource.java:98)
        at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.requestAuthorizationToken(KeycloakAdapterPolicyEnforcer.java:167)
        at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.isAuthorized(KeycloakAdapterPolicyEnforcer.java:66)
        at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:121)
        at org.keycloak.adapters.authorization.PolicyEnforcer.enforce(PolicyEnforcer.java:95)
        at org.keycloak.adapters.AuthenticatedActionsHandler.isAuthorized(AuthenticatedActionsHandler.java:158)
        at org.keycloak.adapters.AuthenticatedActionsHandler.handledRequest(AuthenticatedActionsHandler.java:60)
        at org.keycloak.adapters.tomcat.AbstractAuthenticatedActionsValve.invoke(AbstractAuthenticatedActionsValve.java:62)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
        at org.apache.catalina.core.StandardHostValve.invoke$original$KWnaGlVS(StandardHostValve.java:143)
        at org.apache.catalina.core.StandardHostValve.invoke$original$KWnaGlVS$accessor$bCqSa4YQ(StandardHostValve.java)
        at org.apache.catalina.core.StandardHostValve$auxiliary$UCo46sAk.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error executing http method [POST]. Response : null
        at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:106)
        at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
        at org.keycloak.authorization.client.resource.AuthorizationResource$1.call(AuthorizationResource.java:92)
        at org.keycloak.authorization.client.resource.AuthorizationResource$1.call(AuthorizationResource.java:74)
        at org.keycloak.authorization.client.resource.AuthorizationResource.authorize(AuthorizationResource.java:96)
        ... 27 common frames omitted
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:276)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:294)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:230)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:679)
        at org.apache.http.impl.client.DefaultRequestDirector.execute$original$ORx1f3LC(DefaultRequestDirector.java:481)
        at org.apache.http.impl.client.DefaultRequestDirector.execute$original$ORx1f3LC$accessor$qcbj92tQ(DefaultRequestDirector.java)
        at org.apache.http.impl.client.DefaultRequestDirector$auxiliary$ooxx2rNh.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute$original$SlxtXuTC(AbstractHttpClient.java:835)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute$original$SlxtXuTC$accessor$zJNzIAWB(AbstractHttpClient.java)
        at org.apache.http.impl.client.AbstractHttpClient$auxiliary$qh5pOPyl.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:84)
        ... 31 common frames omitted

2021-12-21 05:19:42.874 DEBUG 1 --- [nio-9082-exec-6] o.k.a.a.AbstractPolicyEnforcer           : Sending challenge to the client. Path [PathConfig{name='/commercial-admin/auth/resource', type='null', path='/commercial-admin/auth/resource', scopes=[], id='bf58f4c1-cd39-4c4c-a1dc-5284da4cfbd8', enforcerMode='ENFORCING'}]
2021-12-21 05:19:42.874 DEBUG 1 --- [nio-9082-exec-9] o.k.a.a.KeycloakAdapterPolicyEnforcer    : Authorization failed

java.lang.RuntimeException: Failed to obtain authorization data
        at org.keycloak.authorization.client.util.Throwables.handleWrapException(Throwables.java:45)
        at org.keycloak.authorization.client.util.Throwables.retryAndWrapExceptionIfNecessary(Throwables.java:65)
        at org.keycloak.authorization.client.resource.AuthorizationResource.authorize(AuthorizationResource.java:98)
        at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.requestAuthorizationToken(KeycloakAdapterPolicyEnforcer.java:167)
        at org.keycloak.adapters.authorization.KeycloakAdapterPolicyEnforcer.isAuthorized(KeycloakAdapterPolicyEnforcer.java:66)
        at org.keycloak.adapters.authorization.AbstractPolicyEnforcer.authorize(AbstractPolicyEnforcer.java:121)
        at org.keycloak.adapters.authorization.PolicyEnforcer.enforce(PolicyEnforcer.java:95)
        at org.keycloak.adapters.AuthenticatedActionsHandler.isAuthorized(AuthenticatedActionsHandler.java:158)
        at org.keycloak.adapters.AuthenticatedActionsHandler.handledRequest(AuthenticatedActionsHandler.java:60)
        at org.keycloak.adapters.tomcat.AbstractAuthenticatedActionsValve.invoke(AbstractAuthenticatedActionsValve.java:62)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
        at org.apache.catalina.core.StandardHostValve.invoke$original$KWnaGlVS(StandardHostValve.java:143)
        at org.apache.catalina.core.StandardHostValve.invoke$original$KWnaGlVS$accessor$bCqSa4YQ(StandardHostValve.java)
        at org.apache.catalina.core.StandardHostValve$auxiliary$UCo46sAk.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error executing http method [POST]. Response : null
        at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:106)
        at org.keycloak.authorization.client.util.HttpMethodResponse$2.execute(HttpMethodResponse.java:50)
        at org.keycloak.authorization.client.resource.AuthorizationResource$1.call(AuthorizationResource.java:92)
        at org.keycloak.authorization.client.resource.AuthorizationResource$1.call(AuthorizationResource.java:74)
        at org.keycloak.authorization.client.resource.AuthorizationResource.authorize(AuthorizationResource.java:96)
        ... 27 common frames omitted
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:276)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:294)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:230)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:679)
        at org.apache.http.impl.client.DefaultRequestDirector.execute$original$ORx1f3LC(DefaultRequestDirector.java:481)
        at org.apache.http.impl.client.DefaultRequestDirector.execute$original$ORx1f3LC$accessor$qcbj92tQ(DefaultRequestDirector.java)
        at org.apache.http.impl.client.DefaultRequestDirector$auxiliary$ooxx2rNh.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute$original$SlxtXuTC(AbstractHttpClient.java:835)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute$original$SlxtXuTC$accessor$zJNzIAWB(AbstractHttpClient.java)
        at org.apache.http.impl.client.AbstractHttpClient$auxiliary$qh5pOPyl.call(Unknown Source)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.keycloak.authorization.client.util.HttpMethod.execute(HttpMethod.java:84)
        ... 31 common frames omitted

```

### Version

15.0.2

### Expected behavior

success,get 200

### Actual behavior

fail. get 403

### How to Reproduce?

Occasionally this problem occurs.

### Anything else?

```xml
<dependency>
          <groupId>org.keycloak</groupId>
          <artifactId>keycloak-admin-client</artifactId>
          <version>14.0.0</version>
</dependency>
```

**Comment by pedroigor** [comment]
@myifeng Is the server restarting in between?

**Comment by myifeng** [comment]
@pedroigor server has been working.
When I log in with keycloak for the first time, this problem will most likely occur, get 403, but it works normally after refreshing.

**Comment by myifeng** [comment]
@pedroigor  I think it may be caused by the network or firewall. I am also using AWS.
["Connection reset" by keycloak's Java adapter](https://stackoverflow.com/questions/49994901/connection-reset-by-keycloaks-java-adapter)

**Comment by myifeng** [comment]
I use `tcpdump` get some tcp log, it might be helpful.

The problem occurred at 12:33:33, the client received the `RST`, but the server did not process any requests during this time.

So this is not a keycloak problem?

Should try again after failure?

client-tcp-log:
![77d13e494b120b144536b40f0222974](https://user-images.githubusercontent.com/26652657/147241983-cddfc9ed-d8fb-46f9-b0f0-c3010c73913c.jpg)


server-tcp-log:
![c1fa7417a35c150cf75807c43611cd5](https://user-images.githubusercontent.com/26652657/147242704-4a64549c-daf8-4928-a5e1-4f153ed169ba.jpg)

**Comment by pedroigor** [comment]
@myifeng I'm not sure, but it seems not related to Keycloak.

I'm not sure because we have a mechanism within the Keycloak Authz Java Client to retry requests when they fail. But the scenario we are covering is when the token expires and a retry is made to obtain new tokens to access the server endpoints.

**Comment by myifeng** [comment]
@pedroigor Today, AWS's technical support replied to us: They think it is because of the long connection disconnection. The timeout period of the client and ALB is 3600s, but the timeout period of the server and ALB is 60s, so the server is disconnected from the ALB. They suggested that we modify the timeout period or set the keep alive parameter.

**Comment by pedroigor** [comment]
@myifeng Interesting. Did you manage to configure that? FYI, the Authz Java Client API relies on Apache HTTP, so you should be able to configure it accordingly.

The policy enforcer should consider the configuration options available from the adapter configuration as per https://www.keycloak.org/docs/latest/securing_apps/#_java_adapter_config. You should be able to configure timeouts, max connection lifetime, etc.

Please, let me know if it helps and if we can close this issue.
