### ISSUE TITLE
Keycloak.X -Doc - ReadME)  Need to specify to use JDK 11

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#9326]
### Describe the bug

Keycloak.X is based upon Quarkus which requires JDK11.

If is is started using JDK8, following error is generated 
~~~
sh kc.sh
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/quarkus/bootstrap/runner/QuarkusEntryPoint has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

~~~

Java 55 correponds to JDK 11, Java 52 coordponds to JDK 8 [1].

Keycloak.x has to be started with JDK11 to work fine.

~~~
52 = Java 8
53 = Java 9
54 = Java 10
55 = Java 11
~~~

The Keycloak.X Readme shall indicate that JDK11 is required.

[1] https://www.baeldung.com/java-lang-unsupportedclassversion

### Version

16.1.0

### Expected behavior

Improve README

add to use JDK11

### Actual behavior

Not documented

**Comment by stianst** [comment]
Will be handled in #9216
