### ISSUE TITLE
Cannot start Spring boot tests with undertow individually

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#9466]
### Describe the bug

It's not possible to execute any spring boot test due to `Connection refused` error with Undertow adapter container. There's defined welcome page `/index.html`, where it's redirected after booting app server. The request to `index.html` is handled by `ServletPreAuthActionsHandler`, where is a call to auth server, however the auth server(KC server) is not started yet. 

It causes the error with `Connection refused`, because the URL is not accessible. It should be verified whether the auth server is available and if not, the request should be handled differently.
In pipeline, it still tries to connect to the auth server and waits until the auth server is started by another agent.

Redirected from [KEYCLOAK-17993](https://issues.redhat.com/browse/KEYCLOAK-17993)

```
2021-05-04 04:47:31.414  WARN 4465 --- [ XNIO-1 task-10] o.keycloak.adapters.KeycloakDeployment   : Failed to load URLs from http://localhost:8180/auth/realms/test/.well-known/openid-configuration
[INFO] 
[INFO] java.net.ConnectException: Connection refused (Connection refused)
[INFO] 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_291]
[INFO] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476) ~[na:1.8.0_291]
[INFO] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218) ~[na:1.8.0_291]
[INFO] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200) ~[na:1.8.0_291]
[INFO] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[na:1.8.0_291]
[INFO] 	at java.net.Socket.connect(Socket.java:606) ~[na:1.8.0_291]
[INFO] 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.12.jar:4.5.12]
[INFO] 	at org.k
[INFO] eycloak.adapters.KeycloakDeployment.getOidcConfiguration(KeycloakDeployment.java:219) [keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.KeycloakDeployment.resolveUrls(KeycloakDeployment.java:178) [keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.KeycloakDeployment.getAuthUrl(KeycloakDeployment.java:237) [keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.OAuthRequestAuthenticator.getRedirectUri(OAuthRequestAuthenticator.java:175) [keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.OAuthRequestAuthenticator.loginRedirect(OAuthRequestAuthenticator.java:213) [keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.OAuthRequestAuthenticator.authenticate(OAuthRequestAuthenticator.java:275) [keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:138) [keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.undertow.AbstractUndertowKeycloakAuthMech.keycloakAuthenticate(AbstractUndertowKeycloakAuthMech.java:110) [keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.undertow.ServletKeycloakAuthMech.authenticate(ServletKeycloakAuthMech.java:92) [keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityCont
[INFO] extImpl.java:125) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at org.keyclo
[INFO] ak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69) [keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69) [keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.ja
[INFO] va:830) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_291]
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_291]
[INFO] 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]
[INFO] 
[INFO] 2021-05-04 04:47:31.414 ERROR 4465 --- [ XNIO-1 task-10] io.undertow.request                      : UT005023: Exception handling request to /index.html
[INFO] 
[INFO] java.lang.NullPointerException: null
[INFO] 	at org.keycloak.adapters.OAuthRequestAuthenticator.getRedirectUri(OAuthRequestAuthenticator.java:175) ~[keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.OAuthRequestAuthenticator.loginRedirect(OAuthRequestAuthenticator.java:213) ~[keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.OAuthRequestAuthenticator.authenticate(OAuthRequestAuthenticator.java:275) ~[keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:138) ~[keycloak-adapter-core-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.undertow.AbstractUndertowKeycloakAuthMech.keycloakAuthenticate(AbstractUndertowKeycloakAuthMech.java:110) ~[keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.undertow.ServletKeycloakAuthMech.authenticate(ServletKeycloakAuthMech.java:92) ~[keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.Securi
[INFO] tyContextImpl.attemptAuthentication(SecurityContextImpl.java:125) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55) ~[undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59) ~[undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 
[INFO] ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69) ~[keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69) ~[keycloak-undertow-adapter-9.0.13.redhat-00006.jar:9.0.13.redhat-00006]
[INFO] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) [undertow-servlet-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at i
[INFO] o.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.28.Final.jar:2.0.28.Final]
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_291]
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_291]
[INFO] 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]
```

### Version

16.0.0

### Expected behavior

Properly execute all Spring Boot tests on Undertow. 

### Actual behavior

Not possible to start KC server and fetch all necessary information from there.

### How to Reproduce?

`mvn -f testsuite/integration-arquillian/tests/other/springboot-tests clean install -Dtest=SessionSpringBootTest -Dadapter.container=undertow`

**Comment by mabartos** [comment]
Spring Boot tests will be removed soon.
