### ISSUE TITLE
Test Failure: MigrationTest

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#9550]
### Describe the bug

Tests **migration2_xTest** and **migration9_xTest** are failing.

### Version

17.0.0

### Expected behavior

Tests should pass successfully.

### Actual behavior

Tests are failing in the following environments:
**OS:** RHEL (any Linux should work)
**Test group:** DB Migration and DB Migration - 2.5.5
**DB:** postgresql132 / postgresplus131 / mysql80 / mariadb103 / mssql2019 / mariadb_galera_103 / oracle19cRAC

**Stack trace:**
`java.lang.AssertionError: Error when refreshing offline token. Error: unknown_error, Error details: null, offline token from previous version: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCMHFMbWlvRkx3VzZMV0RIMllIRVR0TzF2alh5QVQtUXM5blpoYlBFU3pJIn0.eyJqdGkiOiIwZDA2M2Q2MS1mYTgxLTRmNzYtYTA0YS1iNzMxYjE5ZjEyODIiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNjQyMDIzNTg2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgxODAvYXV0aC9yZWFsbXMvTWlncmF0aW9uIiwiYXVkIjoibWlncmF0aW9uLXRlc3QtY2xpZW50Iiwic3ViIjoiNTU2ZWI0MzAtZDU3NC00OTU2LTkwOGEtODM1MjdhNzc5MzJhIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6Im1pZ3JhdGlvbi10ZXN0LWNsaWVudCIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjE0MTU5M2JkLWUwMTgtNDBiNy05YTVhLTczNzcxMTNmNDA5NyIsImNsaWVudF9zZXNzaW9uIjoiYzYxYTczNTgtYzMzOS00N2RjLThkMjMtOTk0NzAxMjY2YjgyIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fX0.gKB3ymmocBEfqMJdNRuB191_Etw3SW0-lDxDj9pzoT7hdiaNphGgH9ZzN93ZnSMS4vzS_EamKxAFJ8OIY-EFX9Ay67AqS48PKVjqvgQIrNqugQLaPGVT0ZypZ9T_uyZpvDPHGhEdK9zJ9lZXg-Q0DYZy6QyeWxWIeVdjVsvU1x_HxhtfJYDwLGAgglxIMP_0ekSArowE5HBdOGJ8aIflMcgoSZp7hcA6V57vwkTWqgnKixQxk0_W--AaGxfLvqvTKT-RkGmokMBFDwEYyjphmTG4hgAljLqUP8ngZ_VIDuY8Gf6vEzYSKhecOj_WNSIKG_C-o2iB6RGBvX2e_IWcvw
	at org.junit.Assert.fail(Assert.java:89)
	at org.keycloak.testsuite.migration.AbstractMigrationTest.testOfflineTokenLogin(AbstractMigrationTest.java:693)
	at org.keycloak.testsuite.migration.MigrationTest.migration2_xTest(MigrationTest.java:127)
`

### How to Reproduce?

Execute the tests in an environment like the one described above.

### Anything else?

https://keycloak-jenkins/job/universal-test-pipeline-server/1163/testReport/

**Comment by miquelsi** [comment]
@hmlnarik @martin-kanis can you please take a look at this? It might be related to the store.

**Comment by martin-kanis** [comment]
As I see it might by caused by https://github.com/keycloak/keycloak/pull/7897. In `TokenManager.getAcr` method there is following line:
`int loa = Integer.parseInt(clientSession.getNote(Constants.LEVEL_OF_AUTHENTICATION));`
If the session from previous version doesn't contain `Constants.LEVEL_OF_AUTHENTICATION` note it will try to parse `null` as a number. 
Resulting to the following error: 

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-2) Uncaught server error: java.lang.NumberFormatException: null
2022-01-13 01:06:44  	at java.lang.Integer.parseInt(Integer.java:542)
2022-01-13 01:06:44  	at java.lang.Integer.parseInt(Integer.java:615)
2022-01-13 01:06:44  	at org.keycloak.protocol.oidc.TokenManager.getAcr(TokenManager.java:857)
2022-01-13 01:06:44  	at org.keycloak.protocol.oidc.TokenManager.initToken(TokenManager.java:839)
2022-01-13 01:06:44  	at org.keycloak.protocol.oidc.TokenManager.createClientAccessToken(TokenManager.java:532)
2022-01-13 01:06:44  	at org.keycloak.protocol.oidc.TokenManager.validateToken(TokenManager.java:217)
2022-01-13 01:06:44  	at org.keycloak.protocol.oidc.TokenManager.refreshAccessToken(TokenManager.java:369)
2022-01-13 01:06:44  	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.refreshTokenGrant(TokenEndpoint.java:565)
2022-01-13 01:06:44  	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:201)
```

@mposolda WDYT?

**Comment by mposolda** [comment]
@martin-kanis Thanks for checking this. I will take a look...
