### ISSUE TITLE
Authentication Flow ID not imported

### ISSUE THREAD

**Issue by Robbilie** [keycloak/keycloak#9564]
### Describe the bug

When importing a realm with authentication flows that have an id set the flows don't have the same IDs after import. This is especially annoying when using the Keycloak Operator (or really any configuration as code setups that need the id rather than the alias). Setting authentication flow overrides on a client requires the id to be passed so being able to predefine it is crucial.

### Version

15.1.1

### Expected behavior

If an id is set in the realm.json that is imported the imported authentication flow has the defined I'd after import.

### Actual behavior

The set Id in the realm.json is ignored and a new one is generated.

### How to Reproduce?

1. Create Realm
2. Export Realm
3. Delete Realm
4. Import Realm
5. Compare authentication flow IDs from exported realm.json to IDs of the imported realm.

**Comment by Robbilie** [comment]
@stianst this isn't strictly an operator issue is it? That should affect everyone importing stuff with the assumption of IDs being applied like they are set in the imported file :)

**Comment by bpedersen2** [comment]
I can confirm that this affects  realm imports with a flow override set on a client, as the exported realm.json does containgthe id.


The realm.json has:
```  
  ... { # client config
      "authenticationFlowBindingOverrides": {
        "browser": "363edc1d-17cd-46ac-9e65-d5d68c131205"
      },
    "authenticationFlows": [ 
   ...   {
      "id": "363edc1d-17cd-46ac-9e65-d5d68c131205",
      "alias": "Copy of browser",
      "description": "browser based authentication",
      "providerId": "basic-flow",
 ...
```


```
2022-03-14 08:26:08,932 ERROR [org.keycloak.services] (executor-thread-40) KC-SERVICES0037: Error creating gerrit: java.lang.RuntimeException: Unable to resolve auth flow binding override for: browser
--
Mon, Mar 14 2022 9:26:10 am | at org.keycloak.models.utils.RepresentationToModel.createClient(RepresentationToModel.java:1446)
Mon, Mar 14 2022 9:26:10 am | at org.keycloak.models.utils.RepresentationToModel.createClient(RepresentationToModel.java:1360)
Mon, Mar 14 2022 9:26:10 am | at org.keycloak.partialimport.ClientsPartialImport.create(ClientsPartialImport.java:120)
Mon, Mar 14 2022 9:26:10 am | at org.keycloak.partialimport.ClientsPartialImport.create(ClientsPartialImport.java:43)
Mon, Mar 14 2022 9:26:10 am | at org.keycloak.partialimport.AbstractPartialImport.doImport(AbstractPartialImport.java:120)

```

**Comment by bpedersen2** [comment]
The additionial flow got created, but with a new id.

**Comment by mposolda** [comment]
@vmuzikar Do you please recall if this is already fixed? I have some feeling we discussed this (or very similar) issue already and not 100% sure if it happened to be fixed or not :-)

@Robbilie @bpedersen2 Anyone of you able to re-test this with latest Keycloak 21.0.1 and check if it is already fixed?

**Comment by vmuzikar** [comment]
@mposolda I believe it is not fixed. [Here](https://issues.redhat.com/browse/RHSSO-2253) a public RH-SSO tracker.

**Comment by mposolda** [comment]
@vmuzikar Thanks! I am scheduling to 22, however it is not a blocker, so we may eventually postpone...
