### ISSUE TITLE
add-user-keycloak.sh tries to talk with maven?

### ISSUE THREAD

**Issue by stromnet** [keycloak/keycloak#9589]
### Describe the bug

Env: rh-sso on OpenShift via rhsso-operator.7.5.1

Not sure if this is generic Keycloak or something rh-sso specific, but posting here to start with.

During initial startup of keyckloak-0 container, the add-user-keycloak.sh is executed but just stalled, resulting in hanging container.

Sending a -QUIT to the JVM revealed a stack-trace which shows a stuck HTTP client, which is trying to download something from Maven. The failure to download is because our outbound proxy have not been configured and thus outbound access is not possible. 
The question is why it's trying to downloading something from maven? Bad container image packaging from RHSSO or bad packaging in KeyCloak?

```
"main" #1 prio=5 os_prio=0 cpu=280.93ms elapsed=38.03s tid=0x00007f1b04018000 nid=0x1cc runnable  [0x00007f1b0c09a000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(java.base@11.0.13/Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(java.base@11.0.13/AbstractPlainSocketImpl.java:399)
	- locked <0x0000000082735760> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(java.base@11.0.13/AbstractPlainSocketImpl.java:242)
	at java.net.AbstractPlainSocketImpl.connect(java.base@11.0.13/AbstractPlainSocketImpl.java:224)
	at java.net.SocksSocketImpl.connect(java.base@11.0.13/SocksSocketImpl.java:392)
	at java.net.Socket.connect(java.base@11.0.13/Socket.java:609)
	at sun.security.ssl.SSLSocketImpl.connect(java.base@11.0.13/SSLSocketImpl.java:299)
	at sun.security.ssl.BaseSSLSocketImpl.connect(java.base@11.0.13/BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(java.base@11.0.13/NetworkClient.java:182)
	at sun.net.www.http.HttpClient.openServer(java.base@11.0.13/HttpClient.java:474)
	at sun.net.www.http.HttpClient.openServer(java.base@11.0.13/HttpClient.java:569)
	- locked <0x000000008272e7b8> (a sun.net.www.protocol.https.HttpsClient)
	at sun.net.www.protocol.https.HttpsClient.<init>(java.base@11.0.13/HttpsClient.java:266)
	at sun.net.www.protocol.https.HttpsClient.New(java.base@11.0.13/HttpsClient.java:373)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(java.base@11.0.13/AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(java.base@11.0.13/HttpURLConnection.java:1187)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(java.base@11.0.13/HttpURLConnection.java:1081)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(java.base@11.0.13/AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(java.base@11.0.13/HttpURLConnection.java:1592)
	- locked <0x000000008272bdb0> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@11.0.13/HttpURLConnection.java:1520)
	- locked <0x000000008272bdb0> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at java.net.HttpURLConnection.getResponseCode(java.base@11.0.13/HttpURLConnection.java:527)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(java.base@11.0.13/HttpsURLConnectionImpl.java:334)
	at org.jboss.modules.maven.MavenArtifactUtil.downloadFile(MavenArtifactUtil.java:164)
	at org.jboss.modules.maven.MavenArtifactUtil.resolveArtifact(MavenArtifactUtil.java:135)
	- locked <0x0000000080946ae0> (a java.lang.Object)
	at org.jboss.modules.maven.DefaultMavenResolver.lambda$resolveArtifact$0(DefaultMavenResolver.java:36)
	at org.jboss.modules.maven.DefaultMavenResolver$$Lambda$23/0x0000000840082040.run(Unknown Source)
	at java.security.AccessController.doPrivileged(java.base@11.0.13/Native Method)
	at org.jboss.modules.maven.MavenArtifactUtil.doIo(MavenArtifactUtil.java:237)
	at org.jboss.modules.maven.DefaultMavenResolver.resolveArtifact(DefaultMavenResolver.java:36)
	at org.jboss.modules.maven.MavenResolver.resolveJarArtifact(MavenResolver.java:40)
	at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:1048)
	at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:937)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:697)
	at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:469)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:335)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:293)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:254)
	at org.jboss.modules.LocalModuleFinder.parseModuleXmlFile(LocalModuleFinder.java:250)
	at org.jboss.modules.LocalModuleFinder.lambda$findModule$1(LocalModuleFinder.java:195)
	at org.jboss.modules.LocalModuleFinder$$Lambda$8/0x0000000840064c40.run(Unknown Source)
	at java.security.AccessController.doPrivileged(java.base@11.0.13/Native Method)
	at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:195)
	at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:700)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:693)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:503)
	at org.jboss.modules.DelegatingModuleLoader.preloadModule(DelegatingModuleLoader.java:57)
	at org.jboss.modules.Module.addPaths(Module.java:1274)
	at org.jboss.modules.Module.link(Module.java:1644)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1672)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:303)
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:92)
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:86)
	at __redirected.__DocumentBuilderFactory.changeDefaultFactory(__DocumentBuilderFactory.java:53)
	at __redirected.__JAXPRedirected.changeAll(__JAXPRedirected.java:53)
	at org.jboss.modules.Main.main(Main.java:362)
```

### Version

rhsso 7.5.1

### Expected behavior

User should be created with resources in the distribution (container image in this case, but I suspect that is outside of keycloak opensource project), not downloaded from maven.

**Comment by stromnet** [comment]
FYI: we managed to work around this by adding the following in the Keycloak object:
```
spec:
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: JAVA_OPTS
          value: >-
            -Dhttps.proxyHost=ourhost
            -Dhttps.proxyPort=8080
```

This is picked up by the add-user-keycloak.sh script, and it can then start up as expected.

**Comment by stromnet** [comment]
For some reason our rh-sso-operator was installing 7.5.0, when 7.5.1 was available. This had [some other proxy fixes](https://github.com/keycloak/keycloak/commit/7d0af8519b0c4c90badd420bba75005ae4cdfa8a), and it seems it also had fixed this problem (at least it does not fail anymore). Probably covered under KEYCLOAK-19080 "Simplify the RHSSO setup in an OpenShift Disconnected cluster".
