### ISSUE TITLE
Model tests consistently time out

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9648]
### Describe the bug

Model tests in the teststuite consistently fail because of the timeout

### Version

main

**Comment by ahus1** [comment]
In a preliminary analysis I ran with the help of @martin-kanis a unit test locally the CacheExpirationTest that took 5 minutes to complete. Looking a a thread dump I discovered that there is a deadlock where PersistenceManagerImpl acquires a writelock during close(), while the InfinispanClusterProviderFactory tries to clear the workCache via `workCache.entrySet().removeIf(new LockEntryPredicate(removedNodesAddresses));` and is waiting for a readlock.

Martin opened a discussion on Infinispan's Zulip chat: https://infinispan.zulipchat.com/#narrow/stream/118645-infinispan/topic/Cluster.20stuck.20after.20upgrade.20from.2011.2Ex.20to.2012.2E1

I'll have a look if some synchronization could help to avoid this deadlock.

[stack2.txt](https://github.com/keycloak/keycloak/files/7951081/stack2.txt)

**Comment by ahus1** [comment]
Created upstream issue https://issues.redhat.com/browse/ISPN-13664 after talking to @wburns

**Comment by ahus1** [comment]
New intermediate status: after some ugly workarounds for the time being, no timeouts in all the tests. 

Still, some tests are unstable and fail on GitHub actions. I suspect the reason for that being some nodes not being able to join properly in some circumstances.

After the following exception

```
17:12:48,372 WARN  [org.infinispan.CLUSTER] (jgroups-10,node-1) ISPN000071: Caught exception when handling command TopologyJoinCommand{cacheName='org.infinispan.CLIENT_SERVER_TX_TABLE', origin=node-4, joinInfo=CacheJoinInfo{consistentHashFactory=org.infinispan.distribution.ch.impl.SyncReplicatedConsistentHashFactory@238f0359, numSegments=256, numOwners=2, timeout=240000, cacheMode=REPL_SYNC, persistentUUID=04c47294-d241-4b72-99f3-2a9f8b399971, persistentStateChecksum=Optional.empty}, viewId=2}
java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.infinispan.topology.ClusterTopologyManagerImpl.handleJoin(ClusterTopologyManagerImpl.java:225)
	at org.infinispan.commands.topology.CacheJoinCommand.invokeAsync(CacheJoinCommand.java:42)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler$ReplicableCommandRunner.run(GlobalInboundInvocationHandler.java:252)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleReplicableCommand(GlobalInboundInvocationHandler.java:174)
	at org.infinispan.remoting.inboundhandler.GlobalInboundInvocationHandler.handleFromCluster(GlobalInboundInvocationHandler.java:113)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1391)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
	at org.jgroups.JChannel.up(JChannel.java:784)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
	at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
	at org.jgroups.protocols.Discovery.up(Discovery.java:300)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

there is the following message that node-4 leaves the cluster

```
17:12:48,398 INFO  [org.infinispan.CLUSTER] (jgroups-9,node-4) ISPN000094: Received new cluster view for channel ISPN: [node-1|3] (5) [node-1, node-2, node-4, node-5, node-3]
17:12:48,398 INFO  [org.infinispan.CLUSTER] (jgroups-9,node-4) ISPN100000: Node node-3 joined the cluster
17:12:48,418 INFO  [org.infinispan.CLUSTER] (pool-5-thread-3) ISPN000079: Channel ISPN local address is node-3, physical addresses are [127.0.0.1:58074]
17:12:48,418 INFO  [org.infinispan.CLUSTER] (pool-5-thread-2) ISPN000080: Disconnecting JGroups channel ISPN
17:12:48,420 INFO  [org.infinispan.CLUSTER] (jgroups-6,node-1) ISPN000094: Received new cluster view for channel ISPN: [node-1|4] (4) [node-1, node-2, node-5, node-3]
17:12:48,421 INFO  [org.infinispan.CLUSTER] (pool-5-thread-4) ISPN000080: Disconnecting JGroups channel ISPN
17:12:48,421 INFO  [org.infinispan.CLUSTER] (jgroups-6,node-1) ISPN100001: Node node-4 left the cluster
```

**Comment by ahus1** [comment]
The good news: the model tests are "in the green" again after two changes: 
1. in production code, adding some heavy synchronization around the remote cache (461a735aaa43fc3762c90b0e6b53bf5b6635afaf and f5632aa1247a37a632ae1ed472723616df28bea5)
2. in testing code, throttling the start of Infinispans (572bf53e2aa07ecaed3d45dca370e7bd12016dfa)

Now I wonder what of this could be taken to the main branch:
* should the synchronization in (1) be merged to main as an intermediate workaround, or would we need to wait for an Infinispan patch release? And if there is a patch release, would we need it for 12.1 (IMHO Quarkus is on Infinispan 13)?
* if we upgrade the Infinispan library to a new version, should we synchronize that with Wildfly?
* for the throttling of Infinispan in (2), I assume that it is OK to merge to main - please confirm. 
* I'm running some more tests to find out why throttling is necessary here. That analysis could be postponed to after the merge. 

Please advise how to proceed.

**Comment by martin-kanis** [comment]
@ahus1 Great news! 
I think we shouldn't wait for an Infinispan patch because it's not clear whether they will patch also 12.1.x stream which we use because of alignment with Wildfly. It will probably take some time anyway. I'm not sure whether we aim to align with Quarkus dependencies as it will be a default server in Keycloak 17. 

Regarding the synchronization on workRemoteCache in `HotRodListener`, I guess it should be OK in real production cluster. If I understand it correctly, the synchronization lock is only on `DefaultInfinispanConnectionProviderFactory` threads which means it will have effect only during the startup/shutdown? I am thinking about potential performance penalty here. 

The change in ModelTest is fine from my point of view if that helps with stability.

**Comment by ahus1** [comment]
Hi @martin-kanis - there is also the modification on InfinispanNotificationsManager.java that will wrap and synchronize IMHO all interactions with the remote cache. I'm not sure how many interaction will be there, and there will be a performance penalty as they will be done sequentially. This could be optimized to be a read-write-lock if this would be necessary.

Looking at the upstream bug in Infinispan, they plan for a 12.1.x release for this fix, so there is hope.

Let me know if this comment changes your view on things.

**Comment by ahus1** [comment]
The problem caches joining was reported here and is fixed for Infinispan 13: https://issues.redhat.com/browse/ISPN-13231 

Started a discussion upstream if this could be backported to 12.1.x: https://infinispan.zulipchat.com/#narrow/stream/118645-infinispan/topic/NPE.20in.2012.2E1.2E7.2EFinal.20when.20handling.20TopologyJoinCommand

For now, will assume that we'll use the workaround for the test to not start too many caches at a time and re-activate the workaround so that the caches don't start all at once.

**Comment by ahus1** [comment]
Some follow-up issues have been created: 
* Unstable model tests when starting multiple Infinispan instances #9867
* Improve readability of CacheExpirationTest #9869
* Remove workaround introduced to prevent deadlocks #9871

With these follow-up issues in place, I close this issue. 

// cc: @hmlnarik
