### ISSUE TITLE
PubKeySignRegisterTest failures in WebAuthn tests

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#9693]
### Describe the bug

The same for the passwordless test case in the test.

See: https://keycloak-jenkins.com/job/universal-test-pipeline-server/1177/testReport/org.keycloak.testsuite.webauthn.registration/PubKeySignRegisterTest/

```
org.openqa.selenium.UnhandledAlertException: 
unexpected alert open: {Alert text : Please input your registered authenticator's label}
  (Session info: chrome=90.0.4430.72): Please input your registered authenticator's label
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'paas.psi.redhat.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-240.22.1.el8_3.x86_64', java.version: '1.8.0_311'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [37397bc8984a6b2be0116cac184c9124, findElement {using=id, value=kc-try-again}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 90.0.4430.72, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.yHXDPT}, goog:chromeOptions: {debuggerAddress: localhost:40863}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:40863/devtoo..., se:cdpVersion: 90.0.4430.72, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 37397bc8984a6b2be0116cac184c9124
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:131)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:383)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:375)
	at org.jboss.arquillian.graphene.enricher.WebElementUtils.dropProxyAndFindElement(WebElementUtils.java:160)
	at org.jboss.arquillian.graphene.enricher.WebElementUtils.findElement(WebElementUtils.java:62)
	at org.jboss.arquillian.graphene.enricher.SearchContextInterceptor.intercept(SearchContextInterceptor.java:46)
	at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
	at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:47)
	at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:43)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.until(WebDriverWaitImpl.java:97)
	at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor.intercept(StaleElementInterceptor.java:43)
	at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.intercept(GrapheneContextualHandler.java:263)
	at org.openqa.selenium.chrome.ChromeDriver$$EnhancerByGraphene$$f0e7a83f.findElement(<generated>)
	at org.keycloak.testsuite.webauthn.pages.WebAuthnErrorPage.isCurrent(WebAuthnErrorPage.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.intercept(GrapheneContextualHandler.java:263)
	at org.keycloak.testsuite.webauthn.pages.WebAuthnErrorPage$$EnhancerByGraphene$$fb4df33f.isCurrent(<generated>)
	at org.keycloak.testsuite.webauthn.registration.PubKeySignRegisterTest.assertPublicKeyAlgorithms(PubKeySignRegisterTest.java:90)
	at org.keycloak.testsuite.webauthn.registration.PubKeySignRegisterTest.publicKeySignaturesRSA(PubKeySignRegisterTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Version

17.0.0

**Comment by mabartos** [comment]
This test doesn't fail anymore in the pipeline nor in GHAs. No ignored tests included.

See:
https://keycloak-jenkins.com/view/Keycloak/job/universal-test-pipeline-server/2616/testReport/
https://keycloak-jenkins.com/view/Keycloak/job/universal-test-pipeline-server/2614/testReport/

**Comment by Aboullos** [comment]
It is happening again
https://github.com/keycloak/keycloak/actions/runs/7193299036/job/19594569695

**Comment by ahus1** [comment]
@mabartos - thank you for the PR. I assume this would need to be backported as well. Probably 23, possibly also 22? Please check, add the labels to the issue and create the backports when you have the time. Thanks!

**Comment by mabartos** [comment]
@ahus1 Yep, will do
